### ISSUE TITLE
Add extra_metadata to api endpoint?

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#10008]
Hi @etj @mattiagiupponi ,

I think you both have worked on the [extra_metadata implementation](https://docs.geonode.org/en/master/usage/extra_metadata/settings.html).

May I ask the following. It looks what is currently implemented is 

1. a form to input json 
2. json validation

In my opinion what is missing is that the userdata is actually rendered in the dataset/map [detail info table](https://github.com/GeoNode/geonode-mapstore-client/blob/5cfa963051b054439f750cb15eea9fb4656d6e97/geonode_mapstore_client/client/js/components/home/DetailsPanel.jsx), right? (– Which might be a great addition for many users)

From what I see the first step is to add the field to  the [_resource_base_ serializer](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/serializers.py#L437) so mapstore can read it from the API endpoint? – Or do I missunderstand the purpose of the extra_metadata field?

Best,

Toni

**Comment by giohappy** [comment]
@t-book I agree with you, it would be a nice and valuable addition. The extra metadata was developed for backend services, so we never had the need to render it to the end user UI. 
We don't have plans right now for it, but it might happen in the future...

**Comment by t-book** [comment]
Thanks @giohappy 

> The extra metadata was developed for backend services

This was exactly the point I was unsure about. I will see if I can suggest a PR for it.
