### ISSUE TITLE
Are google assets fetched and are the default configs GDPR compliant?

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#10020]
## Expected Behavior

GeoNode is GDPR compliant. See issues with loading assets from google here: https://wicki.io/posts/2022-02-goodbye-google-fonts-data-privacy-gdpr/

## Actual Behavior

* google fonts fetched from foreign servers? See https://gitter.im/GeoNode/general?at=62f35115cf6cfd27afb3251a
* E.g. Mapstore fetches fonts, too? See https://gitter.im/GeoNode/general?at=630daf98647d633cf6f73e2b

But I do not see the loading of those from Google's API on my site (custom 3.3.x instance). Is this an issue at all for 3.3.x / 4.x?

## Specifications

  - GeoNode version: 3.3.x / 4.x

**Comment by t-book** [comment]
>  Is this an issue at all for 3.3.x / 4.x?

I do see a google request on master: https://master.demo.geonode.org/catalogue/#/dataset/2596

<img width="1506" alt="Bildschirmfoto 2022-09-13 um 09 12 52" src="https://user-images.githubusercontent.com/20478652/189834891-b8e08521-e754-4a7b-9f1e-9b55af4a8d0b.png">

**Comment by gannebamm** [comment]
Ok, interesting. The stable (3.3.2.post2) version does load fonts locally as seen here: https://stable.demo.geonode.org/maps/4895/view#/

![grafik](https://user-images.githubusercontent.com/6172324/189850450-18503af0-3ef1-435f-8086-cb45e93591c8.png)

**Comment by t-book** [comment]
@gannebamm It looks it has been added 15 month ago: https://github.com/geosolutions-it/geonode-mapstore-client/blame/c227c0f3480a5a4ce724241daa8e001d4af893c1/geonode_mapstore_client/client/themes/geonode/less/_variables.less#L70

**Comment by giohappy** [comment]
yes @gannebamm the new client uses the Montserrat font. The review of outgoing requests is one of my plans for the future weeks because we would like to reach a point where GeoNode could work without Internet access. Fronts are for sure one of the things to solve. This should be quite straightforward, since it's a matter of downloading the font itself (it has an Open Font License) and changing the less variable.

**Comment by t-book** [comment]
I've removed the google fonts yesterday for a client

https://github.com/GeoNode/geonode-mapstore-client/blob/f6a02ef5e48eb9d48c236b894d4b014d99a4c197/geonode_mapstore_client/templates/index.html#L9

For downloading the fonts I've used https://gwfh.mranftl.com/fonts.
If it helps I can make a PR.

**Comment by gannebamm** [comment]
I thought this was already solved and wanted to close the issue, but it seems it persists.

https://github.com/GeoNode/geonode-mapstore-client/blob/master/geonode_mapstore_client/templates/index.html#L9

**Comment by giohappy** [comment]
@gannebamm the solution is probably what I mentioned in https://github.com/GeoNode/geonode/issues/10020#issuecomment-1246410335
We don't have time to do it right away. Anyone that could make a PR?

**Comment by giohappy** [comment]
@gannebamm I took a few minutes to make a test and it seems it did work. I will open a PR for the client.

**Comment by giohappy** [comment]
fixed in https://github.com/GeoNode/geonode-mapstore-client/commit/9e02d0baec06f62824d18466b595e932183ff615
