### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by PonzioWVSinchai** [GeoNode/geonode#10068]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gannebamm** [comment]
Hi Ponzio,
Welcome to the GeoNode community. Please follow the issue templates and fill in the info about your feature request. For now, I will close this issue. You can work on the description and reopen it later. If you just want to get in touch with the community just hop over to our Gitter chat here: https://gitter.im/GeoNode/general
