### ISSUE TITLE
How to disbale read only layer.

### ISSUE THREAD

**Issue by manapshymyr-OB** [GeoNode/geonode#10078]
## Expected Behavior
I want to edit layer data that is coming from the postgis database through the geoserver. Unfortunately, the geonode throws an error by indicating "Layer is only read mode". How can I enable write mode? 
@t-book @afabiani 

## Specifications

  - GeoNode version: 4
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): manual
  - Platform: Ubuntu 22.04
  - Additional details:

**Comment by manapshymyr-OB** [comment]
WFS should be enabled from the geoserver, and the layer must have a primary key

**Comment by t-book** [comment]
@manapshymyr-OB **WFS-T** should be enabled by default, at least in a docker setup. Why did your layer not have a primary key?

**Comment by manapshymyr-OB** [comment]
> @manapshymyr-OB **WFS-T** should be enabled by default, at least in a docker setup. Why did your layer not have a primary key?

I have forgot to alter the table
