### ISSUE TITLE
Geoserver 2.20.6 build

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#10137]
Prepare the build for GS 2.20.6 and upgrade GeoNode + GeoNode Project, both master and 4.1.x

**Comment by afabiani** [comment]
#. New branch created https://github.com/GeoNode/geoserver-geonode-ext/tree/2.20.6
#. **WARNING**: from this version you will need to add the following option to the `JAVA_OPTS`: `-Dgwc.context.suffix=gwc`
