### ISSUE TITLE
select2.png and spinner.gif missing (and being looked for in lib/css

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1023]
select2.png and spinner.gif missing (and being looked for in lib/css

**Comment by eddiemac1902** [comment]
This is what I did that solved the problem for me with select2.png . Need to go to...
 https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.png

Download the picture (don't change its name) and paste picture in your css folder. Should fix the problem

**Comment by aesyondu** [comment]
> This is what I did that solved the problem for me with select2.png . Need to go to...
> https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2.png
> 
> Download the picture (don't change its name) and paste picture in your css folder. Should fix the problem

Thanks this worked for me. spinner.gif was also missing so I downloaded it as well:
https://cdnjs.cloudflare.com/ajax/libs/select2/3.4.5/select2-spinner.gif
