### ISSUE TITLE
Document creation via API v2

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#10270]
**Is your feature request related to a problem? Please describe.**
The existing document API does not permit the user to upload a new document

**Describe the solution you'd like**
Let the API v2 be able to upload document and thanks to the storage manager, to clone them to be available in the geonode environment

**Comment by gannebamm** [comment]
Great news!
Thünen will test this functionality and update the documentation accordingly

**Comment by giohappy** [comment]
@gannebamm for your notice, this is just a quick solution to cover an urgent use case. The proper solution we have in mind should be based on the new geonode-importer, by sharing a common flow and API.
We are going to submit a GNIP soon to sponsor the introduction of geonode-importer as an official module. It would be great if you would consider it also for your development.
