### ISSUE TITLE
Error when vieweing the Edit Metadata page for a time series dataset

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#10368]
## Expected Behavior
User can view the metadata page for a time series dataset

## Actual Behavior
The page throws the following error

![image](https://user-images.githubusercontent.com/571129/205025420-0a24230f-62e9-4f88-bcda-e881d687eb6a.png)

## Steps to Reproduce the Problem

  1. Open https://master.demo.geonode.org/catalogue/#/dataset/3240
  2. Click Edit -> Edit Metadata

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment]
@giohappy the dataset linked does not exist anymore. I tried locally with a couple of time-series datasets and it behaves as expected. Can you please share the dataset that is raising this issue?

**Comment by giohappy** [comment]
@mattiagiupponi I didn't download that dataset. I will close the issue and I will reppoen if it happens again.
