### ISSUE TITLE
Can't override javascript loaded asynchronously via require.js

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1040]
There are some javascript methods I'd like to override in a custom template, for example in the LayerInfo class used for uploading:

https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/upload/LayerInfo.js#L238

However, this is loaded asynchronously via require.js and I can't seem to get a reference to it to override it from the template - LayerInfo is always undefined.  Any ideas on how to do this?

**Comment by jj0hns0n** [comment]
@mbertrand can you give us an update on this one?

**Comment by mbertrand** [comment]
@jjohns0n, no update since the last one on 4/16.
