### ISSUE TITLE
View button not redirect in Hostname

### ISSUE THREAD

**Issue by ahmadzfaiz** [GeoNode/geonode#10527]
## Expected Behavior

View button is expected to redirect to `http://<hostname>/catalogue/#/dataset/1`

## Actual Behavior

View button actually redirect to `http://localhost/catalogue/#/dataset/1`

## Steps to Reproduce the Problem

  1. I successfully add new data into GeoNode
  2. But after added, the view button redirect into localhost, not in my hostname
![image](https://user-images.githubusercontent.com/75885530/212539344-3709b55f-859e-49fb-95ed-8573e0cd05d2.png)
  3. Only this button that not redirect into my hostname. The other links is working fine
![image](https://user-images.githubusercontent.com/75885530/212539453-fe08c999-3479-4418-96eb-2805e7977b92.png)

## Specifications

  - GeoNode version: 3.3
  - Installation type (vanilla, geonode-project): I follow this `https://docs.geonode.org/en/3.3.x/install/advanced/core/index.html`
  - Installation method (manual, docker): manual
  - Platform: Ubuntu 20.04
  - Additional details:

**Comment by mattiagiupponi** [comment]
Geonode 3.3 is no longer mantained
