### ISSUE TITLE
Add black to PR template

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#10595]
@giohappy 
It looks tests now check if the PR passes black.
If we keep it it would be good to add this information to https://github.com/GeoNode/geonode/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by giohappy** [comment]
I agree @t-book. It was already on our plan. I wast waiting to see how it went with Black and if there was any feedback from the other devs.

I think that the adoption of Black can bring some styling uniformity to the code, that can help reading it (and diffing).

**Comment by t-book** [comment]
> I think that the adoption of Black can bring some styling uniformity to the code, that can help reading it (and diffing).

I absolutely agree. Feels good!

**Comment by t-book** [comment]
>  I wast waiting to see how it went with Black and if there was any feedback from the other devs.

I've already merged your PR. Hope this wasn't to fast. If so, we can change it back.
