### ISSUE TITLE
[FR] Add a way to inject custom CA certs

### ISSUE THREAD

**Issue by matmair** [GeoNode/geonode#10614]
**Is your feature request related to a problem? Please describe.**
It is a bit of work to get geonode running in a network with it's own CA as the certificates issues by it are not working with urlib3/requests.

**Describe the solution you'd like**
An enviroment variable or a volume mount that enables the user to inject custom CA certs into the enviroment.

**Describe alternatives you've considered**
You can already add the custom CA cert to the store used by certifi - but that is not really a great solution for a containerised enviroment.

**Comment by t-book** [comment]
Ref.: https://gitter.im/GeoNode/general?at=602e20dba8c6a77848188c08

**Comment by gannebamm** [comment]
@matmair Is the given description enough to solve this issue?

**Comment by matmair** [comment]
@gannebamm I still face issues with urlib3 complaining about self-signed certificates when adding the certs (especially when geonode communicates with GeoServer). Is this a known issue? I tried searching in the gitter but did not find anything.

**Comment by t-book** [comment]
> urlib3

You could suggest allowing self signed certs or better said disable the check. But you PR should clearly explain why. and add or update exitisting tests ;) F.e.

```python

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE

with urllib.request.urlopen(url, context=ctx) as f:
   ...
```
 Haven't read it, but this looks like the correct docs: https://docs.python.org/3/library/ssl.html?highlight=cert_none

**Comment by matmair** [comment]
I played around with implementing this in code for nearly a week now. There are a lot of edge cases, I think overwriting the certify package during docker image generation is the cleanest way.
