### ISSUE TITLE
Metadata info and attribute list in catalogue and map view

### ISSUE THREAD

**Issue by mkrueger-dev** [GeoNode/geonode#10693]
In GeoNode 4 I'm missing the layers attribute list and further metadata details when exploring layers either in the catalogue or the map. This feature was provided in GeoNode 3.

![image](https://user-images.githubusercontent.com/125589316/221155026-84473de3-ff30-418c-905b-68dab1d79ecb.png)
**Catalogue view in GeoNode 3**

![image](https://user-images.githubusercontent.com/125589316/221156020-0e4e7ba1-8a40-4051-93b2-e807217c25c0.png)
**Catalogue view in GeoNode 4**

Is this feature planed to be implemented again?
If not, running GeoNode 4 using Docker at which parts of the code do I need to make changes?

**Specifications**

  - GeoNode Core version:master
  - Installation method (manual, GeoNode Docker)

**Comment by gannebamm** [comment]
Hi,
We already had a brief discussion about the missing attribute information here: https://github.com/GeoNode/geonode/issues/10378#issuecomment-1420526141

The Thünen Institute will fund the reimplementation of that feature and we already started to take a look at how this could be done. @giohappy gave infos in the comment linked above. @matthesrieke please tag this issue and give insights as soon as the devs had a chance to take a look at the code.

**Comment by giohappy** [comment]
The attributes tab will be back in 4,1,0 https://github.com/GeoNode/geonode-mapstore-client/commit/09b6974382fa749aeab7ef5f2fed09464eeda689
