### ISSUE TITLE
Thumbnails with escaped filename are not retrievable

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#10709]
Since the UUIDHandler can generate identifiers with special chars, special attention is needed about how such identifiers are used.

Having a dataset with an identifier like `prefix:619099dd-a2f4-42cc-95f3-5d5131` will generate thumbnail file with an escaped name:

```sql
select base.thumbnail_url 
from base_resourcebase base
where thumbnail_url like '%619099dd-a2f4-42cc-95f3-5d5131-thumb.png'
```
yields
```
http://10.10.100.5:8082/uploaded/thumbs/layer-prefix%3A619099dd-a2f4-42cc-95f3-5d5131-thumb.png
```

This is the related file:
```sh
find /mnt/ssd2/data/ -name "*619099dd-a2f4-42cc-95f3-5d5131-thumb.png"
```
```
/mnt/ssd2/data/gn40/statics/uploaded/thumbs/layer-prefix%3A619099dd-a2f4-42cc-95f3-5d5131-thumb.png
```

So far so good, since the names are the same.

Anyway, when such file is retrieved from a web client we have:

```
nginx4gn4_clean        | 10.10.100.5 - - [28/Feb/2023:17:11:12 +0000] "GET /uploaded/thumbs/layer-prefix%3A619099dd-a2f4-42cc-95f3-5d5131-thumb.png HTTP/1.1" 400 157 "-" "-"
nginx4gn4_clean        | 2023/02/28 17:11:20 [error] 17#17: *253 open() "/mnt/volumes/statics/uploaded/thumbs/layer-prefix:619099dd-a2f4-42cc-95f3-5d5131-thumb.png" failed (2: No such file or directory), client: 10.10.100.5, server: 10.10.100.5, request: "GET /uploaded/thumbs/layer-prefix%3A619099dd-a2f4-42cc-95f3-5d5131-thumb.png HTTP/1.1", host: "10.10.100.5:8082"
```

so the https server will decode the `%3A` into `:`, thus searching for a non existent file.

## Specifications

  - GeoNode version: tested on 4.0.x
  - Installation type: geonode-project, with a custom uuidhandler, guess it could also happen with an XML file with fileIdentifier with the `:`char

**Comment by etj** [comment]
Quick fix for existing files:
- Filesystem:
  ```sh
      for file in 'statics/uploaded/thumbs/YOURPREFIX%3A'*; do echo SOURCE $file; NEW=$(echo "$file" | sed s/%3A/:/g ) ; echo TARGET $NEW ; mv -v "$file" "$NEW" ;   done
   ```
- DB: 
  ```sql
    update base_resourcebase
    set thumbnail_url =	replace( thumbnail_url, '%3A', ':')
    where thumbnail_url like '%\%3A%'
  ```

**Comment by mattiagiupponi** [comment]
From a local test (by running Geonode in development mode) it works as expected. The `:` in correctly handled.
![image](https://github.com/GeoNode/geonode/assets/51856725/b6613b39-3f93-44ae-bcd3-bba991ce28ac)

I'm going to try with NGINX in front to see if it works or not

**Comment by mattiagiupponi** [comment]
I made another test by running it with docker, so is NGINX to serve the static files.

From the image below, the file is correctly served and works as expected

![image](https://github.com/GeoNode/geonode/assets/51856725/bd6ac51d-3bae-4f41-ae77-01bfb7a5e1f2)

It might be an issue with the wrong migration pointed out in the previous comment.
