### ISSUE TITLE
GEOSERVER_JAVA_OPTS not set properly in .env for 3.3.x branch

### ISSUE THREAD

**Issue by saxas13** [GeoNode/geonode#10701]
## Expected Behavior

Pulling Geonode 3.3.x from github and docker-compose up will build and start all containers successfully

## Actual Behavior

Startup fails with Django4Geonode container stating:

Wait for GeoServer API availability

GeoServer HTTP error is 404 Client Error: for url: http://geoserver:8080/geoserver/rest

These error messages will loop and Django as well as Geoserver will not be accessible

## Steps to Reproduce the Problem

  1. Pull Geonode 3.3.x from github
  2. Startup container with docker-compose up
  3. See startup fail

## Specifications

  - GeoNode version: 3.3.x
  - Installation type (vanilla, geonode-project): Vanilla
  - Installation method (manual, docker): docker
  - Platform: Ubuntu 20.04.5
  - Additional details:
The Startup problem can be resolves by the following:

in .env file:

change line https://github.com/GeoNode/geonode/blob/3.3.x/.env#L103 from

GEOSERVER_JAVA_OPTS="-Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine"

to 

GEOSERVER_JAVA_OPTS=-Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine

(aka remove " " around GEOSERVER_JAVA_OPTS= variables and remove this -XX:+UseParNewGC from string)

**Comment by mattiagiupponi** [comment]
Geonode 3.3 is no longer mantained
