### ISSUE TITLE
Issue in Docker Setup instructions in GeoNode master doc

### ISSUE THREAD

**Issue by desilvarami** [GeoNode/geonode#10713]
After executing "_echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null_", apt-get update gives an error as follows.
_"The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8"_

By referring to the Docker official page, this problem was overcome. Please check whether the instructions need to be updated in the GeoNode master doc (https://docs.geonode.org/en/master/install/advanced/core/index.html#docker).

Sorry if this kind of posts are not intended to write under GitHub issues.

![image](https://user-images.githubusercontent.com/6550207/222622100-1ccbebb1-31b0-4c33-9c99-66e755fef17d.png)

**Comment by afabiani** [comment]
Thanks, documentation updated through [commit](https://github.com/GeoNode/documentation/commit/ffab7c0a38e77513398a2c2563a9052541579857)

**Comment by desilvarami** [comment]
My pleasure. Thank you for the quick fix.
