### ISSUE TITLE
Geonode 'list' object has no attribute

### ISSUE THREAD

**Issue by ymatheus95** [GeoNode/geonode#10745]
## Expected Behavior

after restarting the server the service would work

## Actual Behavior
I have geonode 2.6 installed on ubuntu 14 (I am aware that it is obsolete) after restarting the server I am getting the following error:

<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AttributeError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(102, 102, 102); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'list' object has no attribute 'name'</pre>

Request Method: | GET
-- | --
http://geonode.jbrj.gov.br/
1.6.11
AttributeError
'list' object has no attribute 'name'
/usr/local/lib/python2.7/dist-packages/geonode/context_processors.py in resource_urls, line 34
/usr/bin/python
2.7.6
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PILcompat',  '/usr/lib/pymodules/python2.7',  '/var/www']
Ter, 7 Mar 2023 09:07:23 -0600

=================================================================
    site = Site.objects.get_current()
    defaults = dict(
        STATIC_URL=settings.STATIC_URL,
        CATALOGUE_BASE_URL=default_catalogue_backend()['URL'],
        REGISTRATION_OPEN=settings.REGISTRATION_OPEN,
        VERSION=get_version(),
        #SITE_NAME=site.name,
        SITE_DOMAIN=site.domain, ...
        RESOURCE_PUBLISHING=settings.RESOURCE_PUBLISHING,
        THEME_ACCOUNT_CONTACT_EMAIL=settings.THEME_ACCOUNT_CONTACT_EMAIL,
        DEBUG_STATIC=getattr(
            settings,
            "DEBUG_STATIC",
            False),
## Specifications

  - GeoNode version: 2.6
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker): apt
  - Platform: Ubuntu 14
  - Additional details:

**Comment by giohappy** [comment]
@ymatheus95 GeoNode 2has reached its EOL. 2.x is an unuspported branch.

**Comment by ymatheus95** [comment]
> Você conseguiu resolver esse problema? pois estou com o mesmo problema mas na linha 42 do mesmo arquivo, e gostaria de saber se poderia me ajudar?

Ainda não. Agora estou tentando subir um outro ambiente para tentar migrar os dados. Se tiver interesse me chama no e-mail pra agendarmos uma call para tentarmos cruzar algumas informações. E-mail: matheusdfdasilva@gmail.com

**Comment by ymatheus95** [comment]
> @ymatheus95O GeoNode 2 combustível seu EOL. 2.x é um ramal não suportado.

Could you be more detailed in your answer. Thanks for the interaction.
