### ISSUE TITLE
Shapefile Dataset (with its ISO 19115/19139 metadata) not found after uploading it using API 

### ISSUE THREAD

**Issue by eblondel** [GeoNode/geonode#10762]
## Expected Behavior

A shapefile + its ISO 19115/19139 XML metadata uploaded through the web API, and made visible over GeoNode.

## Actual Behavior

The API returns a success (status code 200) with status "finished" and an URL pointing to the catalogue dataset; BUT

* the dataset is not visible in the GeoNode web-interface. 
* Trying to get the resource/dataset through the API also leads to a "Not found" error
* Additional tests, that seem to indicate the upload actually works:
  * Trying to re-upload it with the same ISO XML metadata, and same UUID as identifier; leads to an error saying the UUID is already in the system
  * Perform a DELETE operation with the API also works (which allows to re-upload it with same metadata UUID after)

Live examples:
- when pushing the shapefile WITHOUT the metadata: https://stable.demo.geonode.org/catalogue/#/dataset/6160 (visible)
- when pushing the shapefile WITH metadata: https://stable.demo.geonode.org/catalogue/#/dataset/6161 (not visible, although it seems to be there according to above diagnosis)

It seems to be an issue finding the dataset through the search 

( Are there prequisites of metadata content for the XML file to be uploaded together with the shapefile, and that could be the cause of dataset "invisibility"? )

## Steps to Reproduce the Problem

  1. Get this shapefile (and associated ISO 19115 XML file): https://github.com/eblondel/geonode4R/tree/main/inst/extdata/samples
  2. Try to upload it with the API

The integration test here (R language) reproduces the full test: https://github.com/eblondel/geonode4R/blob/main/tests/testthat/test_uploads.R

## Specifications

https://stable.demo.geonode.org/

**Comment by kikislater** [comment]
If we tried to upload a zip without xml then upload xml it returns : 

```
The UUID identifier from the XML Metadata, is different from the one saved]
```

**Comment by kikislater** [comment]
Agree and you could test it through api interface: https://master.demo.geonode.org/api/v2/uploads/upload

- First load of page logged in => 

![image](https://user-images.githubusercontent.com/13238064/226830397-685e9df3-3c32-491c-969a-d9d8cae32057.png)

- Second attempt after trying to POST a shapefile => 
![image](https://user-images.githubusercontent.com/13238064/226830769-275c3593-fbc1-48d7-bc2c-b330e27d5736.png)

... different form but should not affect api if using proper base_file, dbf_file among others

**Comment by eblondel** [comment]
Actually the api answered with a success when I add the metadata, but then
the dataset is not visible and discovered by geonode

Le mer. 22 mars 2023 à 08:29, Sylvain POULAIN ***@***.***> a
écrit :

**Comment by kikislater** [comment]
If you have access to django administration interface it should be in dataset with untick "approved" and "is published" : 

![image](https://user-images.githubusercontent.com/13238064/226852393-9a744789-1a9d-41fe-8e39-759ca345b65c.png)

May be through this point on api : /api/v2/datasets

But this issue let me remind me that it's not possible : https://github.com/GeoNode/geonode/issues/8850

**Comment by kikislater** [comment]
Here you can post metadata : 

https://docs.geonode.org/en/master/devel/api/usage/index.html?highlight=token#dataset-update-metadata

```
import requests

url = ROOT + "api/v2/datasets/" + DATASET_ID
auth = (LOGIN_NAME, LOGIN_PASSWORD)

data = {
    "title": "a new title",
    "license": 4,
}
response = requests.patch(url, auth=auth, json=data)
```

**Comment by kikislater** [comment]
https://github.com/GeoNode/geonode/commit/153736bb5cd792b0c723d972bbde9829fc68cadd

**Comment by giohappy** [comment]
@eblondel I wasn't able to reproduce the issue. I've tested with Postman and the upload with the XML file worked fine. I could see the resource and the attributes from the file were assigned correctly.
Since I see you're using R this is a script that is working for me:

```
library(httr)

headers = c(
  'Authorization' = 'Basic <you base64 credentials>',
)

body = list(
  'base_file' = upload_file('/D:/GeoSolutions/Dati/metadata/shapefile1.shp'),
  'dbf_file' = upload_file('/D:/GeoSolutions/Dati/metadata/shapefile1.dbf'),
  'shx_file' = upload_file('/D:/GeoSolutions/Dati/metadata/shapefile1.shx'),
  'prj_file' = upload_file('/D:/GeoSolutions/Dati/metadata/shapefile1.prj'),
  'xml_file' = upload_file('/D:/GeoSolutions/Dati/metadata/shapefile1.xml')
)

res <- VERB("POST", url = "http://localhost:8000/api/v2/uploads/upload", body = body, add_headers(headers), encode = 'multipart')

cat(content(res, 'text'))
```

**Comment by eblondel** [comment]
@giohappy Thanks for your tests, what is your localhost geonode? All my tests were done on [https://stable.demo.geonode.org](https://stable.demo.geonode.org) @kikislater 's test sound to indicate the same, it doesn't work on the stable geonode.

**Comment by eblondel** [comment]
I've tested it over https://development.demo.geonode.org it works, but not on the stable release, so I understand that something was fixed over development. do you confirm?

**Comment by kikislater** [comment]
> [153736b](https://github.com/GeoNode/geonode/commit/153736bb5cd792b0c723d972bbde9829fc68cadd)

This is here
