### ISSUE TITLE
Call for translators

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1077]
Point them at Transifex, let's get all the available languages to 100% before final. (references #617 )

**Comment by t-book** [comment]
Hi I have a solid arabic translation for geonode 2.4 is this still usefull? (2.8 is current stable).
If yes how to contribute > transifex?

**Comment by t-book** [comment]
Great. Just for clarification. How are geonode versions managed with transifex and po files?

-  Every po file has all translations for all geonode versions? 
-  Or the translations do not distinguish between geonode versions (most likely not)?
-  Or is there some option at Transifex to choose for which version the supplied po file is?
