### ISSUE TITLE
'list' object has no attribute 'name'

### ISSUE THREAD

**Issue by Samuel2255** [GeoNode/geonode#10852]
After restarting the machine I get the following error.

`<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AttributeError at /</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(102, 102, 102); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'list' object has no attribute 'name'</pre>

Request Method: | GET
-- | --

1.6.11
AttributeError
'list' object has no attribute 'name'
/usr/local/lib/python2.7/dist-packages/geonode/context_processors.py in resource_urls, line 42
/usr/bin/python
2.7.6
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PILcompat',  '/usr/lib/pymodules/python2.7',  '/var/www']
Seg, 27 Mar 2023 09:46:30 -0500

`

**Comment by gannebamm** [comment]
Sorry @Samuel2255, but the Python 2.7 GeoNode version has been EOL for quite some time. We will not be able to help you here. Please try to upgrade to a newer version.
