### ISSUE TITLE
Return GetCapabilities URL inside the dataset API response

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#10940]
In previous versions of GeoNode, a link to the specific GetCapabilities for a layer or a map was available inside respective detail pages.
However, the returned XML wasn't a valid GetCapabilities document, since only the `Layer` element was returned.
For this reason, this functionality was removed in GeoNode 4.

Users ask for having it back, but we want to reintroduce it differently:

1. the link will be directed to Geoserver's GetCapabilities URL, instead of being processed by GeoNode
2. for the moment it will only be available for single datasets, not entire maps. For maps, GeoNode should build a GetCapabilities document on its own
3. the GetCapabilities URL will be returned with a new `capabilities_url` field inside the `Dataset` API v2 response

The previous `/capabilities` URLs, still available in GeoNode, will be marked as deprecated.

**Comment by BinoyKadakkal** [comment]
> In previous versions of GeoNode, a link to the specific GetCapabilities for a layer or a map was available inside respective detail pages. However, the returned XML wasn't a valid GetCapabilities document, since only the `Layer` element was returned. For this reason, this functionality was removed in GeoNode 4.
> 
> Users ask for having it back, but we want to reintroduce it differently:
> 
>     1. the link will be directed to Geoserver's GetCapabilities URL, instead of being processed by GeoNode
> 
>     2. for the moment it will only be available for single datasets, not entire maps. For maps, GeoNode should build a GetCapabilities document on its own
> 
>     3. the GetCapabilities URL will be returned with a new `capabilities_url` field inside the `Dataset` API v2 response
> 
> 
> The previous `/capabilities` URLs, still available in GeoNode, will be marked as deprecated.

Could you please mention the version that didn't contain wms getcapability link.

**Comment by giohappy** [comment]
@BinoyKadakkal versions 4.0.x.
Version 4.1.0 now has it back:

![image](https://github.com/GeoNode/geonode/assets/571129/033b1ea1-a870-43da-a118-bf137f0add70)
