### ISSUE TITLE
Social login redirects to empty website

### ISSUE THREAD

**Issue by JorgeMartinezG** [GeoNode/geonode#11039]
## Expected Behavior
When clicking on the social login buttons, Geonode should redirect to oauth provider website

<img width="858" alt="image" src="https://github.com/GeoNode/geonode/assets/3285923/cc48ff6e-9e8a-4a4b-9d16-e848469b4c02">

## Actual Behavior
Geonode displays an empty response
<img width="1278" alt="image" src="https://github.com/GeoNode/geonode/assets/3285923/35f80e7f-d38f-4a38-b396-190f963aacab">

## Steps to Reproduce the Problem
Following the documentation provided here: https://docs.geonode.org/en/4.x/advanced/social/index.html?highlight=social#linkedin-application
  1.  Modified settings.py file
```
if PROJECT_NAME not in INSTALLED_APPS:
    INSTALLED_APPS += (
        "geocollections",
        "wfpdocs",
        PROJECT_NAME,
        'allauth.socialaccount.providers.linkedin_oauth2',
        'allauth.socialaccount.providers.facebook',
    )

ACCOUNT_OPEN_SIGNUP = True
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_CONFIRMATION_EMAIL = False
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = False
ACCOUNT_CONFIRM_EMAIL_ON_GET = False
ACCOUNT_APPROVAL_REQUIRED = False

SOCIALACCOUNT_PROVIDERS = {
    'linkedin_oauth2': {
        'SCOPE': [
            'r_emailaddress',
            'r_basicprofile',
        ],
        'PROFILE_FIELDS': [
            'emailAddress',
            'firstName',
            'headline',
            'id',
            'industry',
            'lastName',
            'pictureUrl',
            'positions',
            'publicProfileUrl',
            'location',
            'specialties',
            'summary',
        ]
    }
}

SOCIALACCOUNT_ADAPTER = 'geonode.people.adapters.SocialAccountAdapter'

SOCIALACCOUNT_AUTO_SIGNUP = False

# Comment out this in case you wont to diable Social login
SOCIALACCOUNT_PROFILE_EXTRACTORS = {
    "linkedin_oauth2": "geonode.people.profileextractors.LinkedInExtractor",
}
```
  3. Created the application clients within the third party auth system (Linkedin)
  4. Created social application client within the admin section:
<img width="1034" alt="image" src="https://github.com/GeoNode/geonode/assets/3285923/1958cc58-d1e8-4439-8073-a59e92cae1f7">

## Specifications
  - GeoNode version: **master**
  - Installation type (vanilla, geonode-project): **geonode-projedt**
  - Installation method (manual, docker): **manual**
  - Platform: **Mac**
  - Additional details: **None**

**Comment by afabiani** [comment]
@JorgeMartinezG could you try adding the following setting to your `settings.py` file?

`SOCIALACCOUNT_LOGIN_ON_GET=True`
