### ISSUE TITLE
Unable to add ArcGIS REST ImageServer as Remote Service 

### ISSUE THREAD

**Issue by ale-cristofori** [GeoNode/geonode#11080]
## Expected Behavior
When adding a remote service through DATASETS -> ADD RESOURCE -> REMOTE SERVICES -> ARCGIS REST ImageServer
And input a valid URL for this kind of services once clicked on the 'Create' button the connection to the external service is created, the service is added to the catalogue and it is possible to load the data into a GeoNode resource (Map, Geostory, etc)

## Actual Behavior
When adding a remote service through DATASETS -> ADD RESOURCE -> REMOTE SERVICES -> ARCGIS REST ImageServer
And input a valid URL for this kind of services once clicked on the 'Create' button an error message is shown and no external service is created. No further actions are allowed.

## Steps to Reproduce the Problem

  1. Go to the [latest stable GeoNode demo](https://stable.demo.geonode.org/#/). 
  2. Click on Data from the bar and from the opened menu click on Datasets.
  3. On the top right corner of the screen click on 'Add Resource' and from the resulting menu click on 'Remote Services'
  4. On the following page select from the bottom drop-down list the 'ArcGIS Rest ImageServer' option and on the top text box insert this URL https://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer (an example of ImageServer)
  5. Click on 'Create'.

See below 
https://github.com/GeoNode/geonode/assets/14953970/3346f5ab-b0b8-4a94-999a-a4b733cb2988

## Specifications

  - GeoNode version: 4.0.x (satble branch)
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): N/A
  - Platform: Linux
  - Additional details:

**Comment by giohappy** [comment]
@ale-cristofori PR for the fix https://github.com/GeoNode/geonode/pull/11083
This service doesn't seem to have layer though. Do you have another service to test?

**Comment by ale-cristofori** [comment]
> @ale-cristofori PR for the fix #11083 This service doesn't seem to have layer though. Do you have another service to test?

@giohappy 
please test this and let me know if it suits
https://sampleserver6.arcgisonline.com/arcgis/rest/services/CharlotteLAS/ImageServer

**Comment by giohappy** [comment]
>please test this and let me know if it suits
https://sampleserver6.arcgisonline.com/arcgis/rest/services/CharlotteLAS/ImageServer

AFAIK also this service doesn't have published layers.

**Comment by ale-cristofori** [comment]
@giohappy 
I have had no time to find other ARCGIS REST ImageServices other than those that are publicly available on their ArcGIS server
and are 

(this one hasn't been tried yet)
https://sampleserver6.arcgisonline.com/arcgis/rest/services/Toronto/ImageServer

https://sampleserver6.arcgisonline.com/arcgis/rest/services/CharlotteLAS/ImageServer
https://sampleserver6.arcgisonline.com/arcgis/rest/services/NLCDLandCover2001/ImageServer

If none of these is suitable for testing, then let me know I am going to try to find more.

**Comment by afabiani** [comment]
https://github.com/GeoNode/geonode/pull/11309

it also includes the upgrade of the library `gn-arcrest` to version `10.5.6` which I had to publish on `Pypi` in order to be able fetching the list of `services` from the remote endpoints
