### ISSUE TITLE
Issue with Uploading CSV 

### ISSUE THREAD

**Issue by jkariscodes** [GeoNode/geonode#11098]
## Expected Behavior

 CSV file with coordinates (lat/long) should be uploaded successfully. 

## Actual Behavior

Error is thrown when clicking Next button after setting source and target CRS on GeoNode. 

## Steps to Reproduce the Problem

  1. Login GeoNode and try uploading this [CSV dataset](https://github.com/GeoNode/geonode/files/11538402/tmp.csv)
  2. Set coordinate reference systems (CRS), try using EPSG 4326 / WGS 84
  3. Click Next to continue

## Specifications

  - GeoNode version: 4.1.x
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker 
  - Platform: Ubuntu 22.04
  - Additional details:

upload appears as shown below 

![Upload State](https://github.com/GeoNode/geonode/assets/23359514/3877eb04-a2b7-4775-a4a2-b56e9cc183a9)

after setting CRS and clicking Next, this is what appears

![Setting CRS and Clicking Next](https://github.com/GeoNode/geonode/assets/23359514/51957971-27fd-4613-9012-dc26dfd1e7ed)

the console shows the following error

![Error in console](https://github.com/GeoNode/geonode/assets/23359514/12d9ef8c-17d7-4a32-8214-5be130d66653)

**Comment by giohappy** [comment]
@jkariscodes This is unexpected since the upload procedure has changed in version 4.1.x. This branch (and the upcoming release) use a new upload engine, which doesn't implement the "Next" step for the selection of the CRS.
Apparently, your setup is still using the old upload engine.

I invite you to pull 4.1.x and try again.

**Comment by jkariscodes** [comment]
@giohappy thanks for the update. However, I am still getting the same error. Is this update added into GeoNode or it is only in the [geonode-importer](https://github.com/GeoNode/geonode-importer/releases/tag/1.0.3)

**Comment by giohappy** [comment]
@jkariscodes this update is autoamtically available with GeoNode 4.1.0.
For GeoNode 4.0.x it must be configured manually, following the instructions in the [README](https://github.com/GeoNode/geonode-importer/blob/master/README.md)

**Comment by jkariscodes** [comment]
thanks @giohappy for the link. I have tested it in my local GeoNode 4.0 and also in the 4.1.0 branch and it works well. I will close this issue.
