### ISSUE TITLE
I can not locate the exact rendering templates file on my visual studio or other editor . Is there any solution to easy to navigate the file and customize it.

### ISSUE THREAD

**Issue by HEM2058** [GeoNode/geonode#11140]
# GNIP <num> - <title of the GNIP here>

## Overview

Describe briefly and clearly what this proposal is meant for.

### Proposed By

<user and full name of the proponent>

### Assigned to Release

This proposal is for GeoNode <version>.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Details about the motivations. Why people should accept this proposal. What are the benefits compared to the current situation.

## Proposal

Technical details for developers.

### Backwards Compatibility

Declare its Backwards Compatibility.

## Future evolution

Explain which could be future evolutions.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by t-book** [comment]
@HEM2058 This issue

- is not a GNIP (Geonode Improvement Process)
- lacks a proper description

Please take the time to describe your problem carefully. Further I would suggest using the mailing list or the gitter chanel for general help. Github should be used for bug tracking.

**Comment by HEM2058** [comment]
Now working it
