### ISSUE TITLE
Direct download on preview on dataset list is not working

### ISSUE THREAD

**Issue by meomancer** [GeoNode/geonode#11156]
## Expected Behavior
Download is working fine.

## Actual Behavior
Download is not working fine.
![Selection_004](https://github.com/GeoNode/geonode/assets/4530905/2616f731-dcd5-4544-9cf7-b103713d2554)
![Selection_003](https://github.com/GeoNode/geonode/assets/4530905/ad197749-719c-4c02-8eb0-56645473609d)

## Steps to Reproduce the Problem

  1. Go to dataset list
  2. Click one of dataset, it will show preview on the right side
  3. Click download button

## Specifications

  - GeoNode version: 4.0.3
  - Installation method (manual, docker): docker

**Comment by giohappy** [comment]
@meomancer direct download is reported to be working fine. Do you have more insights (logs, instances where this can be tested)? Otherwise, this issue will be closed.

**Comment by timlinux** [comment]
@giohappy the issue happens on all of our deployments e.g. https://dev-geonode.dev.do.kartoza.co.za/catalogue/#/dataset/5

**Comment by giohappy** [comment]
hi @timlinux it looks like your dataset is not well configured. I can't see it on the map, an the GetMap request returns [this](https://dev-geonode.dev.do.kartoza.co.za/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Amal&STYLES=geonode%3Amal&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&_v_=1686811272973&WIDTH=512&HEIGHT=512&BBOX=3757032.814272985%2C-1252344.271424327%2C4383204.949985148%2C-626172.1357121632)

**Comment by giohappy** [comment]
@timlinux @meomancer maybe we've spotted the problem. This can happen if the original files are set as available (through the Links model) but for some reason, they don't exist anymore.

We're investigating.

**Comment by timlinux** [comment]
Thanks  @giohappy  - @NyakudyaA can you see if Tharanath can deploy the proposed fix so we can confirm for @giohappy that it works ok now?
