### ISSUE TITLE
Medatada-Wizard: Adding new keywords will lead to bug out of list

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#11164]
## Expected Behavior
I can add multiple new keywords easily. The metadata wizard will wait for my input and I can click, or add an `,` to finish my entry.

## Actual Behavior
This works for the first keyword (most of the time). But after the second or multiple keywords the editor will bug out and stop recognizing my entry. Here is an example of me trying to add more keywords:
![2023-06-14-274-LPIT40174-BS](https://github.com/GeoNode/geonode/assets/6172324/462c5471-c391-4659-a41e-ea8598515815)

## Steps to Reproduce the Problem

  1. Edit metadata of dataset
  2. Add multiple new keywords

## Specifications

  - GeoNode version: v4.1 ( stable.demo)
  - Additional details:

**Comment by giohappy** [comment]
@gannebamm I cannot understand where the editor stops working inside the short video. I've tried inserting multiple keywords for a couple of datasets and maps on stable demo, and they're working fine to me.

**Comment by kikislater** [comment]
It seems to be solved with https://github.com/GeoNode/geonode/pull/11829/commits/e5b11c0d12d2fb34fa09594c145148bac12b6a46
