### ISSUE TITLE
For developing purpose, i need to know where the templates of geonode are located

### ISSUE THREAD

**Issue by arunvk007** [GeoNode/geonode#11219]
[Geonode issue1.odt](https://github.com/GeoNode/geonode/files/11949009/Geonode.issue1.odt)
# GNIP <num> - <title of the GNIP here>

## Overview

Describe briefly and clearly what this proposal is meant for.

### Proposed By

<user and full name of the proponent>

### Assigned to Release

This proposal is for GeoNode <version>.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Details about the motivations. Why people should accept this proposal. What are the benefits compared to the current situation.

## Proposal

Technical details for developers.

### Backwards Compatibility

Declare its Backwards Compatibility.

## Future evolution

Explain which could be future evolutions.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by giohappy** [comment]
@arunvk007 please don't create issues (especially GNIP issues) to ask support questions. I invite you to ask the mailing list or the Gitter channel. You can find the links [here](https://geonode.org/communication/).

Quick answer for the moment: it depends on what you want to customize. Templates are used only in certain places (metadata editor, user, and group pages). All the rest is for the most part implemented as a React-based client, wrapped inside template containers.
