### ISSUE TITLE
geonode save map error

### ISSUE THREAD

**Issue by Lucas-cooperate** [GeoNode/geonode#11221]
## Expected Behavior
After clicking the "save as" button in the geonode, it prompts that the save is successful.

## Actual Behavior
I click the "save as" button in geonode, and after waiting for a minute, it prompts "Network error", but in most cases the map is saved successfully.
![image](https://github.com/GeoNode/geonode/assets/119939877/6cf5a680-77a6-462e-9271-8668919601b6)

## Steps to Reproduce the Problem

  1.Upload data in geonode.
  2.After clicking "Add Resource", import the geographic data and click the "save as" button.
  3.After waiting for one minute, the "Network error" prompt box will pop up.

## Specifications

  - GeoNode version:4.1.0
  - Installation type (vanilla, geonode-project):geonode-project
  - Installation method (manual, docker):docker
  - Platform:ubuntu
  - Additional details:

**Comment by tjnu1830080255** [comment]
![image](https://github.com/GeoNode/geonode/assets/119939877/26b97c09-ec68-452e-b270-7d0f8c8d69b4)

**Comment by tjnu1830080255** [comment]
The console prints the follow：
![image](https://github.com/GeoNode/geonode/assets/119939877/d2b63884-1549-4fdd-a728-25aea0f71743)

**Comment by afabiani** [comment]
please make sure your `SITEURL` setting is correctly defined on your environment:
1. The http schema is correct
2. The url reflects the final/public one
3. There's a `/` at the end.

**Comment by tjnu1830080255** [comment]
> please make sure your `SITEURL` setting is correctly defined on your environment:
> 
> 1. The http schema is correct
> 2. The url reflects the final/public one
> 3. There's a `/` at the end.

![image](https://github.com/GeoNode/geonode/assets/119939877/4b4b69d3-621b-4551-84e9-93d70e057018)
Thank you very much for your answer. I checked the SITEURL configuration in the environment in the container, and it matches your description.

**Comment by Fedesin** [comment]
i have the same problem

**Comment by Fedesin** [comment]
> please make sure your `SITEURL` setting is correctly defined on your environment:
> 
>     1. The http schema is correct
> 
>     2. The url reflects the final/public one
> 
>     3. There's a `/` at the end.

i have this in my .env

SITEURL=http://127.0.0.1/

**Comment by tjnu1830080255** [comment]
> > please make sure your `SITEURL` setting is correctly defined on your environment:
> > ```
> > 1. The http schema is correct
> > 
> > 2. The url reflects the final/public one
> > 
> > 3. There's a `/` at the end.
> > ```
> 
> i have this in my .env
> 
> SITEURL=http://127.0.0.1/

**Comment by tjnu1830080255** [comment]
> > > please make sure your `SITEURL` setting is correctly defined on your environment:
> > > ```
> > > 1. The http schema is correct
> > > 
> > > 2. The url reflects the final/public one
> > > 
> > > 3. There's a `/` at the end.
> > > ```
> > 
> > 
> > i have this in my .env
> > SITEURL=http://127.0.0.1/
![image](https://github.com/GeoNode/geonode/assets/119939877/bf19424b-767d-473d-9917-2b91ed4fc61e)
Since I am in the company's intranet environment, the IP is different from yours, but the format is correct.
Could you please solve this problem? I think you can increase the error reporting time or use an asynchronous method to pop up "saving" on the front end, and the back end will continue to execute.
Looking forward to your reply again.

**Comment by tjnu1830080255** [comment]
@Fedesin @afabiani

**Comment by afabiani** [comment]
Uhm, better looking at the screenshot it looks like you are having a timeout problem. This is tipically raised by the thumbnail generator which is not able to reach one of the container or the remote background tiles, or simply it takes too long to generate the thumbnail.

Tha map should be saved anyway, even if you get this error, can you please confirm?

You should double check your overall network configuration. Something else you can try, assuming the network is reachable, is to increase the timeouts of the gateway and the OCG clients.

**Comment by tjnu1830080255** [comment]
> Uhm, better looking at the screenshot it looks like you are having a timeout problem. This is tipically raised by the thumbnail generator which is not able to reach one of the container or the remote background tiles, or simply it takes too long to generate the thumbnail.
> 
> Tha map should be saved anyway, even if you get this error, can you please confirm?
> 
> You should double check your overall network configuration. Something else you can try, assuming the network is reachable, is to increase the timeouts of the gateway and the OCG clients.

Yes, it is a timeout issue. Can you tell me in which time setting to increase the timeout? @afabiani

**Comment by tjnu1830080255** [comment]
![image](https://github.com/GeoNode/geonode/assets/119939877/71c65bc4-677e-4330-8d76-f9ad193de299)
I found that it has been set to a large value, but it still prompts "Network error" after one minute.

**Comment by Fedesin** [comment]
> ![image](https://user-images.githubusercontent.com/119939877/252612126-71c65bc4-677e-4330-8d76-f9ad193de299.png) I found that it has been set to a large value, but it still prompts "Network error" after one minute.

i have the same problem and i followed the tutorial for docker geonode

**Comment by tjnu1830080255** [comment]
> > ![image](https://user-images.githubusercontent.com/119939877/252612126-71c65bc4-677e-4330-8d76-f9ad193de299.png) I found that it has been set to a large value, but it still prompts "Network error" after one minute.
> 
> i have the same problem and i followed the tutorial for docker geonode

@Fedesin Hello sir, I also use docker compose to deploy. Are you deploying locally or on a server? Have you solved this problem yet?

**Comment by Fedesin** [comment]
> 
i use docker compose and i run it locally

**Comment by Fedesin** [comment]
> > > ![image](https://user-images.githubusercontent.com/119939877/252612126-71c65bc4-677e-4330-8d76-f9ad193de299.png) I found that it has been set to a large value, but it still prompts "Network error" after one minute.
> > 
> > 
> > i have the same problem and i followed the tutorial for docker geonode
> 
> @Fedesin Hello sir, I also use docker compose to deploy. Are you deploying locally or on a server? Have you solved this problem yet?

what file is it?

**Comment by Fedesin** [comment]
pls help @afabiani :(

**Comment by Fedesin** [comment]
> > 
> 
> I was under the impression it was in the geonode.ini file.

where it is?

**Comment by tjnu1830080255** [comment]
> > > 
> > 
> > 
> > 我的印象是它在 geonode.ini 文件中。
> 
> 在哪儿？

I went to have a look. /etc/nginx/sites-enabled/geonode.conf in the Nginx container.

**Comment by tjnu1830080255** [comment]
> > > > 
> > > 
> > > 
> > > 我的印象是它在geonode.ini文件中。
> > 
> > 
> > 在哪儿？
> 
> 我去看了看。Nginx 容器中的 /etc/nginx/sites-enabled/geonode.conf。

Doesn't work.

**Comment by Fedesin** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我的印象是它在geonode.ini文件中。
> > > 
> > > 
> > > 在哪儿？
> > 
> > 
> > 我去看了看。Nginx 容器中的 /etc/nginx/sites-enabled/geonode.conf。
> 
> Doesn't work.
im trying to change any config file like augment the time for harakiris but, it doesn't work

**Comment by afabiani** [comment]
Given that you must understand why you are getting a timeout, which is most probably caused by some misconfiguration, in order to avoid that error on the UI (notice that you will still get a timeout) the ides is to make the NGINX timeouts higher than the UWSGI and OGC ones.

So, in order to do that, you need to set the UWSGI harakiris timeouts to something like 30 secs, the OGC requests tiemeuts too by tweaking the following variables, and update the proxy pass and clients timeouts to something much higher than the previous timeouts including the possible retries.

```
OGC_REQUEST_TIMEOUT=30
OGC_REQUEST_MAX_RETRIES=0
OGC_REQUEST_BACKOFF_FACTOR=0.3
OGC_REQUEST_POOL_MAXSIZE=10
OGC_REQUEST_POOL_CONNECTIONS=10
```

**Comment by Fedesin** [comment]
> 

i have this:
OGC_REQUEST_TIMEOUT=3000
OGC_REQUEST_MAX_RETRIES=1
OGC_REQUEST_BACKOFF_FACTOR=0.3
OGC_REQUEST_POOL_MAXSIZE=10
OGC_REQUEST_POOL_CONNECTIONS=10
its good???

**Comment by afabiani** [comment]
I would say not, try something like

```
OGC_REQUEST_TIMEOUT=5
OGC_REQUEST_MAX_RETRIES=0
OGC_REQUEST_BACKOFF_FACTOR=0.3
OGC_REQUEST_POOL_MAXSIZE=10
OGC_REQUEST_POOL_CONNECTIONS=10
```

**Comment by Fedesin** [comment]
> I would say not, try something like
> 
> ```
> OGC_REQUEST_TIMEOUT=5
> OGC_REQUEST_MAX_RETRIES=0
> OGC_REQUEST_BACKOFF_FACTOR=0.3
> OGC_REQUEST_POOL_MAXSIZE=10
> OGC_REQUEST_POOL_CONNECTIONS=10
> ```

Okey, thanks, im trying with that config

**Comment by tjnu1830080255** [comment]
> 它有效，谢谢@afabiani我爱你 ：））））））））））））））

Can you tell me where you modified the file? @afabiani @Fedesin

**Comment by Lucas-cooperate** [comment]
close
