### ISSUE TITLE
Upload Dataset : GeoTiff not working

### ISSUE THREAD

**Issue by haneefputtur** [GeoNode/geonode#11239]
## Expected Behavior
When I upload dataset geotiff it should be added as a dataset

## Actual Behavior

When I upload left side I get this error message in tool tip

**The upload process failed. Please check the validity of the file and try to upload it again**

In the right side i get below error message.
**tuple.indexx:x not in tuple. Request: (long ID)**

## Steps to Reproduce the Problem

  1.Install fresh genode in Ubuntu.
  2. Followed this instructions  - https://docs.geonode.org/en/master/install/advanced/core/index.html#update-the-settings-in-order-to-update-geonode-and-geoserver-services-running-on-a-public-ip-or-hostname
  3.During installation : geonode_updateip -p localhost  , this step i get random errors like django-admin not found etc.

## Specifications

  - GeoNode version: [4.1.0](https://github.com/GeoNode/geonode/releases/tag/4.1.0)
  - Installation type (vanilla, geonode-project): Geonode Advanced
  - Installation method (manual, docker): Manual 
  - Platform: Ubuntu 22 , AWS
  - Additional details: I have tried almost 10  times , finally i reach the same stage. It never allow me to upload GeoTiff layers.
  - Any guidance or help will be a great support

**Comment by mattiagiupponi** [comment]
Hi @haneefputtur can you please attach the GeoTiff you are trying to upload?

**Comment by haneefputtur** [comment]
@mattiagiupponi thanks for your kind response. This happens with any geotiff. However same geotiff file works everywhere. 

I am sure there is some steps missing in this documentation : https://docs.geonode.org/en/master/install/advanced/core/index.html

Same geotiff works fine with your online demo.
Same geotiff works fone with this https://training.geonode.geosolutionsgroup.com/master/GN1/QUICK_INSTALL.html
