### ISSUE TITLE
Allow to track more dates (Creation, Publication, Revision) in the metadata form

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#1125]
Currently GeoNode allows to track just one date in the metadata form. Creation, Publication or Revision.
It would be nice to have the opportunity to track each of them.
This would require to have a model to store multiple dates for a single object (layer, map, document).
It will be nice to have it in a future GN release, maybe 2.1.
Before even considering it, @tomkralidis does the metadata standard let to have multiple dates? I am pretty sure it does, but just in case :)

**Comment by jj0hns0n** [comment]
@pjdufour @tomkralidis whats the status on this?

**Comment by pjdufour** [comment]
For 2.5, since it'll require model changes.

**Comment by jj0hns0n** [comment]
@tomkralidis can we merge this? or was it already merged?
