### ISSUE TITLE
Manage styles no longer available in GeoNode 4

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#11272]
## Expected Behavior
![Screenshot from 2023-07-17 10-46-39](https://github.com/GeoNode/geonode/assets/2510900/fd742a40-5b2d-4f50-8519-ada353d67a43)

## Actual Behavior
![Screenshot from 2023-07-17 10-48-20](https://github.com/GeoNode/geonode/assets/2510900/b1ff8c44-19ef-4830-a759-c9eb4d7dc46d)

Also tried to update the styles from the admin interface but there is no way to select the chosen styles. It also seems like adding the layers in the admin panel does not update the styles in the GeoServer configuration.
![Screenshot from 2023-07-17 10-49-25](https://github.com/GeoNode/geonode/assets/2510900/231c8e61-94d1-497f-9b3e-236188f25d98)

## Steps to Reproduce the Problem

  1. Navigate to https://stable.demo.geonode.org 
  2. Upload a layer and try to manage or add an additional style. If you have GeoServer access add an additional style and there is no way to select that style when visualising or creating a map
 
**Note:** This breaks a lot of the standard workflows and I tried to search if any existing issue is opened and could not find it. Please close if another issue already exists or they was motivation to remove this or maybe there is a new workflow to achieve the same

**Comment by afabiani** [comment]
This is now is part of the Map configuration.

When you create a new map and add a dataset to it, you can actually check the single layer options and choos the alternate style you need from GeoServer

![image](https://github.com/GeoNode/geonode/assets/1278021/4ccc5e44-9ab4-45f3-8a73-4e007d365506)

**Comment by NyakudyaA** [comment]
Thanks @afabiani
