### ISSUE TITLE
Connecting widgets

### ISSUE THREAD

**Issue by cebassine** [GeoNode/geonode#11293]
In dashboards, all widgets can be connected to a map, or a map to a table. 
But it's not possible to connect any widget other than a map to a table.

Would it be possible to connect widgets to each other? Or at least to the table?
This would make it possible to have a consistent filter at table level. 

In the example below, the map is filtered based on the table, but the "counter" widget remains filtered on the map. The table shows 6 'FOSA' and the counter 181.
![Capture d’écran 2023-07-25 154441](https://github.com/GeoNode/geonode/assets/114669758/cfa3019f-1f61-49b8-9094-9248b0ca92f1)

**Comment by ridoo** [comment]
Did you test this on https://stable.demo.geonode.org? Check out this dashboard which is counting airports based on the current viewport of the map.

https://stable.demo.geonode.org/catalogue/#/dashboard/7889

**Comment by cebassine** [comment]
Yes I have tested, but my point is to connect a counter with a table and not with the map. For the moment, I don't think it works
