### ISSUE TITLE
Make geofence connection URL configurable again (missing DATABASE_HOST)

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode#11318]
The geonode/geoserver provides a `/templates/geofence` directory containing a j2 template for geofence datasource properties. 

## Expected Behavior

The geofence datasource connection is configurable via `DATABASE_HOST` environment variable.

## Actual Behavior

Since `2.23.1` the data connection is a hard wired URL: `jdbc:postgresql://db:5432/{{ GEONODE_GEODATABASE }}`.

Version `2.23.0` instead has a configurable URL: `jdbc:postgresql://{{ DATABASE_HOST }}:{{ DATABASE_PORT }}/{{ GEONODE_GEODATABASE }}`

## Steps to Reproduce the Problem

You can check this by running

```
docker run --rm geonode/geoserver:2.23.1 cat /templates/geofence/geofence-datasource-ovr.properties.j2
geofenceVendorAdapter.databasePlatform=org.hibernatespatial.postgis.PostgisDialect
geofenceDataSource.driverClassName=org.postgresql.Driver
geofenceDataSource.url=jdbc:postgresql://db:5432/{{ GEONODE_GEODATABASE }}
geofenceDataSource.username={{ GEONODE_GEODATABASE }}
geofenceDataSource.password={{ GEONODE_GEODATABASE_PASSWORD }}
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]={{ GEONODE_GEODATABASE_SCHEMA }}

# avoid hibernate transaction issues
geofenceDataSource.testOnBorrow=true
geofenceDataSource.validationQuery=SELECT 1

```

and

```
docker run --rm geonode/geoserver:2.23.0 cat /templates/geofence/geofence-datasource-ovr.properties.j2
geofenceVendorAdapter.databasePlatform=org.hibernatespatial.postgis.PostgisDialect
geofenceDataSource.driverClassName=org.postgresql.Driver
geofenceDataSource.url=jdbc:postgresql://{{ DATABASE_HOST }}:{{ DATABASE_PORT }}/{{ GEONODE_GEODATABASE }}
geofenceDataSource.username={{ GEONODE_GEODATABASE }}
geofenceDataSource.password={{ GEONODE_GEODATABASE_PASSWORD }}
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.default_schema]={{ GEONODE_GEODATABASE_SCHEMA }}

# avoid hibernate transaction issues
geofenceDataSource.testOnBorrow=true
geofenceDataSource.validationQuery=SELECT 1
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.testOnBorrow]=true
geofenceEntityManagerFactory.jpaPropertyMap[hibernate.validationQuery]=SELECT 1
```

I tried to find where `geonode/geoserver` is actually being build from. It seems that [geonode-project](https://github.com/GeoNode/geonode-project/blob/master/docker/geoserver/templates/geofence/geofence-datasource-ovr.properties.j2) is the only public repo which includes that `/templates` folder but it does not hardwire the connection URL.

Could you please clarify, from where `geonode/geoserver` image is build from? It would be cool, if you could fix the template and re-publish the image.

**Comment by ridoo** [comment]
see also https://github.com/zalf-rdm/geonode-k8s/issues/37

**Comment by giohappy** [comment]
@ridoo the GeoServer chain is quite convoluted at the moment. We have plans to review it, but for the moment we have to stick with it:

Data Dir:
 1. The `geoserver_data_xxx` image is built from [data-docker](https://github.com/GeoNode/data-docker/tree/2.23.0), which downloads the data-dir from [geoserver-geonode-ext](https://github.com/GeoNode/geoserver-geonode-ext/tree/2.23.0/data), **which doesn't ship any Geofence template**
 2. The `geoserver_data_xxx` image [is pulled](https://github.com/GeoNode/geonode-project/blob/master/docker-compose.yml#L119) by the `docker-compose.yml`
 3. When the GeoServer container is run [it copies and renders the templates](https://github.com/GeoNode/geonode-project/blob/master/docker-compose.yml#L119) to the `geofence` folder inside the Geoserver data directory volume

As you can see the templates are in your hands. Of course we can fix them inside geonode-project, but you can already fix them for your project.

**Comment by ridoo** [comment]
@giohappy yes, thanks for clarification. You recall my way through all this to find out :D .. 

What you missed, anyway, is to give a hint from where the `geonode/geoserver` image is actually built from ;-). My current guess is the `geonode-project`, as you mentioned it in your post, too.

However, it does not check against any GeoServer checksum and a re-build would not guarantee the same version of GeoServer is being downloaded ([in the Dockerfile](https://github.com/GeoNode/geonode-project/blob/4e30faf1cc4995cd7853a537f3d63437c975fba6/docker/geoserver/Dockerfile#L24)).

**Comment by giohappy** [comment]
@ridoo correct, the latest releases have been built from a `geonode-project`.

And yes, no checksum on the downloaded war. Except a security concern, what would it be useful to? The only case a war for the same version is republished could be a bug in the image itself. If your checksum detects a different version it can only complain but the previous war won't be available anymore.

How would you manage the checksum?

**Comment by ridoo** [comment]
Oh just to make sure, if there is was a change on the downloaded *.war .. consistency was what I had in mind -- not security in the first place

**Comment by ridoo** [comment]
But as you already said: The geofence template had been fixed already, so I can close this issue.
