### ISSUE TITLE
GNIP 95 Hookable logic for the automatic assignment of regions

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11335]
# GNIP 95 - Hookable logic for the automatic assignment of regions

## Overview

Regions assignment is a feature in GeoNode since the early days. However, it never received attention and, in the end, it never seemed to be working well.
Until a few weeks ago the logic was:

- If no region was assigned for a resource, try the assignment whenever the resource is updated
- Compare the intersection of the resource bbox with regions' bboxes. For any intersecting region:
  - if it's a root region assign it (regions are hierarchical) 
  - if it's a child or leaf, assign it only if the total number of assignable regions is less than 30

The latter rule was probably made to avoid assigning too many regions, In the extreme case of a resource spanning the whole globe it would mean assigning all world countries (which are the default regions preloaded in GeoNode).

Recently a change to the last rule was done to remove the limit of 30 and adopt another way of limiting the assignment:

 - only assign a region if its bbox is completely contained inside the resource bbox or if it intersects the resource bbox

This logic is subjective and it might only work for some kind of resources. In general, there's no reason to select only specific spatial relationships for the assignment. 

### Proposed By

@giohappy 

### Assigned to Release

This proposal is for GeoNode 4.2

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Details about the motivations. Why people should accept this proposal. What are the benefits compared to the current situation.

## Proposal

Make the assignment logic customizable through a handler that can be configured. The handler will be picked up by the [metadata_post_save](https://github.com/GeoNode/geonode/blob/master/geonode/resource/utils.py#L421) module to execute the custom logic in place of the hardcoded one. 

**By default no assignment will be done by GeoNode.**

### Backwards Compatibility

No backwards compatibility.

## Future evolution

This could be a first step toward a total customization of the post-save step.The metadata update logic could be split into multiple handlers that will be loaded and executed by the core method.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli: +1
* Giovanni Allegri: +1
* Toni Schoenbuchner: +1
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Pull Request]()
* [Linked Issue]()

**Comment by gannebamm** [comment]
I like the general idea and see why it is needed. One thing I am not sure about is

> By default, no assignment will be done by GeoNode.

This is fine in itself, but I would like to have some example (and very basic) example of a handler as part of the documentation.

**Comment by giohappy** [comment]
>This is fine in itself, but I would like to have some example (and very basic) example of a handler as part of the documentation.

You mean inside the[ settings section](https://docs.geonode.org/en/master/basic/settings/index.html#settings), right? In that case yes, it will be added.

Unfortunately, many settings, which include custom handlers, are not documented. It would be great to improve this part since we have more and more options to override the logic with them...

**Comment by ridoo** [comment]
> Unfortunately, many settings, which include custom handlers, are not documented. It would be great to improve this part since we have more and more options to override the logic with them...

Hey @giohappy is there some pattern one could look at in the code to identify such undocumented handler customizations?

**Comment by giohappy** [comment]
>Hey @giohappy is there some pattern one could look at in the code to identify such undocumented handler customizations?

@ridoo I think it's a matter of comparing the settings page with the `settings.py` in GeoNode.
