### ISSUE TITLE
Disable GeoIP2 update task

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11332]
MaxMind GeoIP lite databases can be obtained with a free personal MaxMind account. 
MaxMind [EULA](https://www.maxmind.com/en/end-user-license-agreement) only allows personal usage of the GeoIP DB ("Service"). It cannot be distributed to third-party users through public URLs or services.
For this reason, the way GeoNode obtains and updates the GeoIP2 DB must be disabled / removed. Users will have to configure their own copy of the DB where available.

**Notice** that the DB is only used by the Monitoring module. This module is deprecated and it's going to be dismissed soon.

**Comment by mattiagiupponi** [comment]
PR https://github.com/GeoNode/geonode/pull/11336
