### ISSUE TITLE
Error 401 Unathorized when upload dataset with super account in geonode docker ubuntuk

### ISSUE THREAD

**Issue by acowahyudi** [GeoNode/geonode#11365]
I have install genode docker in server ubuntu 22.04 with basic installation. after running geonode and login with super account, i want to test upload dataset which is shp file that already zipped. i got this notice error. why should i do to solve this problem?
<img width="1432" alt="image" src="https://github.com/GeoNode/geonode/assets/36886958/b2ff95ad-b665-47a4-96c9-118f685b42e7">

**Comment by acowahyudi** [comment]
false configuration with user geonode and geoserver

**Comment by nasrosoft** [comment]
I have the same issue here !

**Comment by syldor** [comment]
Hi @nasrosoft, I had this happening as well. If you build multiple time your containers, you may have changed the geoserver password at some point but the process does not reset it.

Try to change the geoserver admin password like said here: https://gis.stackexchange.com/questions/122621/changing-geoserver-admin-password and put manually the value you have in your .env file GEOSERVER_ADMIN_PASSWORD.

**Comment by nasrosoft** [comment]
Really this is helpful bro 🙏 thanks a lot
