### ISSUE TITLE
Connect Dashbaord to MySQL

### ISSUE THREAD

**Issue by aghand0ur** [GeoNode/geonode#11374]
Is it possible for dashboard to read tables available in a mysql database?
![Screenshot 2023-08-13 134623](https://github.com/GeoNode/geonode/assets/14883982/b3db5ff2-9343-445d-b006-cdbe38f636c9)

cc @abbassthe @Engineerhanaa

**Comment by abbassthe** [comment]
Hello
Ill come back to you with details on the matter tomorrow though it should be possible .


________________________________
From: Ali J. Ghandour ***@***.***>
Sent: Sunday, August 13, 2023 1:54 PM
To: GeoNode/geonode ***@***.***>
Cc: abbassthe ***@***.***>; Mention ***@***.***>
Subject: [GeoNode/geonode] Connect Dashbaord to MySQL (Issue #11374)


Is it possible for dashboard to read tables available in a mysql database?
[Screenshot 2023-08-13 134623]<https://user-images.githubusercontent.com/14883982/260297784-b3db5ff2-9343-445d-b006-cdbe38f636c9.png>

cc @abbassthe<https://github.com/abbassthe> @
