### ISSUE TITLE
Implement missing Django app configs

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11386]
Several GeoNode apps miss the expected app configs. This breaks GeoNode in recent builds.

**Comment by kaloyan13** [comment]
Using only #11387 fixed my error.

**Comment by giohappy** [comment]
@kaloyan13 a ouole of test environments show that #11387 fix the problem, but we have CI that still complains. We're investigating.

**Comment by giohappy** [comment]
>Noticed geonode/geoserver/createlayer/init.py has CRLF encoding, while patching.

@kaloyan13 we have added another fix and reformatted the code. Waiting for CircleCI now
