### ISSUE TITLE
Can't login on Geoserver 

### ISSUE THREAD

**Issue by lcoandrade** [GeoNode/geonode#11417]
## Expected Behavior
Login to Geoserver

## Actual Behavior
Entering the user (admin) and password(geoserver) on `http://localhost/geoserver/web/?0` gives me:
```
HTTP Status 404 – Não Encontrado

Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.65
```

## Steps to Reproduce the Problem

  1. Access Geoserver http://localhost/geoserver
  2. Try to login

## Specifications

  - GeoNode version:4.1.x
  - Installation type (vanilla, geonode-project):vanilla
  - Installation method (manual, docker):docker
  - Platform:Ubuntu 22.04 on VirtualBox
  - Additional details:
     Geonode was installed like this:
    ```
    cd /opt
    sudo git clone https://github.com/GeoNode/geonode.git -b 4.1.x
    cd geonode
    docker-compose up -d
    ```

**Comment by Jnb2387** [comment]
I am wondering if my issue is the same, but I was able to bypass this error by changing the Login button form action URL. for some reason it was appending //geoserver/geoserver//geoserver...... and after trimming it down to one and clicking the login button it successfully logged me in

**Comment by lcoandrade** [comment]
The same here!

**Comment by pchevali** [comment]
Same problem here, it seems that the geoserver image tag has been pushed 4 days ago, I don't see anything in geonode changelog related to geoserver or nginx reverse proxy.

**Comment by pchevali** [comment]
I tried the geoserver tag 2.23.x ( pushed 5 month ago ) and it works for me ( need to remove the container and the volumes) . @giohappy, Why does the geoserver image tagged 2.23.0 has been pushed again recently ?

**Comment by giohappy** [comment]
I confirm the issue. We're going to publish a new image with the fix.

**Comment by giohappy** [comment]
The new image for Geoserver has been pushed.

Unfortunately, you will have to fix the URLs manually for your already existing setup:
You need to remove any multiple slashes from the following files:

 - `/geoserver_data/data/global.xml`
 - `/geoserver_data/data/security/filter/geonode-oauth2/config.xml`

**Comment by lcoandrade** [comment]
It's working now! I can login normally into geoserver.

Thanks!
