### ISSUE TITLE
API doesn't sort resources

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11424]
The `resources` endpoint doesn't respect the sorting criteria requested in the GET parameters.
To be investigated if this also affects downstream APIs (`datasets`, `documents`, etc.).

Example request:
`https://development.demo.geonode.org/api/v2/resources?include[]=executions&filter{metadata_only}=false&page=1&page_size=24&**sort=title**`

The expected response is resources sorted by `title`, but it doesn't work.

**Comment by etj** [comment]
It seems the issue is client side https://github.com/GeoNode/geonode-mapstore-client/issues/1551

**Comment by giohappy** [comment]
Actually, this is not completed since it's marked also for 4.1.x, while it's been fixed only for master.
We will need to check if we can backport https://github.com/GeoNode/geonode-mapstore-client/pull/1552 easily. I think so...

**Comment by giohappy** [comment]
Well, this can be closed in any case, since this issue is managed in https://github.com/GeoNode/geonode-mapstore-client/issues/1551
The backport has been [merged](https://github.com/GeoNode/geonode-mapstore-client/pull/1567).
