### ISSUE TITLE
GeoCSS styling in 4.x

### ISSUE THREAD

**Issue by jeff-bradley** [GeoNode/geonode#11434]
## Expected Behavior
Ability to style a layer using CSS

## Actual Behavior
Validation Error

## Steps to Reproduce the Problem

  1. Copy style from documentation
  2. Paste into Geonode Code Editor
  3. Layer does not change and receive validation error

## Specifications

  - GeoNode version: 4.1.2
  - Installation type (vanilla, geonode-project): Vanilla
  - Installation method (manual, docker): docker
  - Platform: WSL Ubunutu
  - Additional details:
  
![validation_error](https://github.com/GeoNode/geonode/assets/123754946/930b15c7-aa2c-4246-88a6-2c169413aa46)

**Comment by giohappy** [comment]
@jeff-bradley your expectation is partially correct :)
At the moment datasets are created with SLD styles, and the style editor cannot convert the format of a style associated to a dataset.

At the moment the only option is to 
- change the default style for the layer on Geoserver. (only admins) 
- run the `updatelayers` CLI command to update GeoNode with the updated association
- now you can edit the CSS inside the style editor

In practice, CSS is not currently supported for normal usage. 
I hope there will be funds will be available to implement an option to switch the style format from GeoNode in the future,

**Comment by jeff-bradley** [comment]
Thank you @giohappy changing it in Geoserver and running updatelayers did work!
"In practice, CSS is not currently supported for normal usage." Would that mean it would be bad practice to style with GeoCSS in general?

**Comment by giohappy** [comment]
I meant that it's not for end users, which do not have access to Geoserver and the backend to run the updatelayers command :)
