### ISSUE TITLE
Bad role name in creating GeoFence rules

### ISSUE THREAD

**Issue by jeff-bradley** [GeoNode/geonode#11447]
## Expected Behavior
Add view or download permission to a group and have that group be able to view the layer

## Actual Behavior
Layer never shows up in the map. The user is able to see the resource in the catalog but when clicked the layer data never shows up only error in the console is http://localhost/api/v2/resources/25/permissions (Forbidden) but I believe that's only because it doesn't have manage permission. 

I have tried assigning the permissions multiple ways through the UI, admin console and API none seem to work. The API call for the resource at http://localhost/api/v2/resources/25/permissions returns any group assignment as organizations 
```json
{
    "users": [
        {
            "id": 1000,
            "username": "admin",
            "first_name": "",
            "last_name": "",
            "avatar": "https://www.gravatar.com/avatar/46d229b033af06a191ff2267bca9ae56/?s=240",
            "permissions": "owner",
            "is_superuser": true,
            "is_staff": true
        }
    ],
    "organizations": [
        {
            "id": 6,
            "title": "Hitachi Energy Group",
            "name": "hitachi-energy-group",
            "logo": "http://localhost/static/geonode/img/missing_thumb.png",
            "permissions": "download"
        }
    ],
    "groups": [
        {
            "id": 3,
            "title": "anonymous",
            "name": "anonymous",
            "permissions": "none"
        },
        {
            "id": 2,
            "title": "Registered Members",
            "name": "registered-members",
            "permissions": "none"
        }
    ]
}
```

## Steps to Reproduce the Problem

  1. Add group to geonode/Assign user to group
  2. Add resource to geonode
  3. Assign Download Permission to Group

## Specifications

  - GeoNode version:4.1
  - Installation type (vanilla, geonode-project):vanilla
  - Installation method (manual, docker):docker
  - Platform:WSL ubuntu 22
  - Additional details:

**Comment by jeff-bradley** [comment]
I believe this would have something to do with geofence capabilities somehow, as the ows response would say layer not found. After manually cleaning up the geofence data rules by deleting old ones and creating a new rule with allow all formats the layer would final render in the map.

**Comment by giohappy** [comment]
@jeff-bradley does it happen with any resource or it just happened with a specific test resoruce?

**Comment by giohappy** [comment]
Are you able to reproduce it on the demo instances?

**Comment by jeff-bradley** [comment]
I am not sure I can reproduce in the demo instance as I don't have any privileges to create groups

**Comment by chumano** [comment]
I can share the problem. Hope it will help you.

When we create a “Group Profile” 

![Untitled](https://github.com/GeoNode/geonode/assets/3014969/8c76c5c1-f083-441e-b561-7074ba504b9f)

The system create records in 2 table:

- Authentication and Authorization → **Groups**

![Untitled 1](https://github.com/GeoNode/geonode/assets/3014969/08770c9c-204a-4437-a9e4-a01cdec1bc20)


- Groups → **Group Profiles**


![Untitled 2](https://github.com/GeoNode/geonode/assets/3014969/304bb50a-742d-4d7c-a336-f4e6e36d3e55)

Then we add the group to a resource

![Untitled 3](https://github.com/GeoNode/geonode/assets/3014969/8bce0d21-1997-4090-84da-5590990f7253)

The system add some GeoFence Rules:

![Untitled 4](https://github.com/GeoNode/geonode/assets/3014969/ae52ebc8-347d-49d3-8f69-62da96e09ee0)

And the problem the **role slug (group-tester)** in GeoFence is **invalid**, because I see the code in GeoServer has prefix hardcode role in file **geoserver/security/GeoServerRestRoleService.java** :

```java
private static String rolePrefix = "ROLE_";

...
public GeoServerRole createRoleObject(String role) throws IOException {
        return new GeoServerRole(rolePrefix + (convertToUpperCase ? role.toUpperCase() : role));
}
```

 
We can temporarily fix this by some steps:

- Remove the group from permission of  the resource
- Change Group name “**group-tester**” to “**ROLE_GROUP_TESTER**”
![Untitled 5](https://github.com/GeoNode/geonode/assets/3014969/318eab3a-6ca7-4801-98d4-5a11736ab8ea)

- Then add the group to the resource again

**Comment by saxas13** [comment]
@chumano thanks for the hint, I also ran into this issue, I need to try your Solution.

**Comment by giohappy** [comment]
@etj let's take a look at this

**Comment by etj** [comment]
GeoFence rules are created using the geonode inner name, and are not "translated" into a geoserver format.

This translation has been lost when refactoring the GeoFence logic:
https://github.com/GeoNode/geonode/blob/33d4aa9b4fca04f5cc282b5607ff5d1e72e80e6e/geonode/geoserver/security.py#L54

**Comment by giohappy** [comment]
@jeff-bradley master and 4.2.x branches have been fixed. Could you test the fix also on your side?

**Comment by jeff-bradley** [comment]
@giohappy Looks to be fixed and working well. Thank you!

**Comment by vidlb** [comment]
Could someone explain how I can fix this issue for the "registered-members" group, or do I need to wait for 4.2 release ?
I try to update the geofence rules in the with 'ROLE_' || upper(rolename), but it doesn't seems to work.

**Comment by vidlb** [comment]
Also tried to create a new group profile with "ROLE_" in the group name as suggested by @chumano but even after adding a new rule for that group, the geofence rule isn't created.

**Comment by jeff-bradley** [comment]
@vidlb I am not sure what you mean with "registered-members" group, and I dont have a running instance < 4.2 currently but see if the slug group profile matches the role name in geoserver with the case matching
![image](https://github.com/GeoNode/geonode/assets/123754946/e75fd4d0-5c63-421e-94e7-9632a23e9a70)
![image](https://github.com/GeoNode/geonode/assets/123754946/5fde24d0-b408-4f95-bcf3-6aa3b44ff3fc)

**Comment by vidlb** [comment]
Yes I'm running 4.1.3.
"registered-members" is supposed to be the default group for any logged in user, and is the one that is used to create the default geofence rules.  
The new group config seems right from what I can see in you screenshot.  
But the setting in the "share" section isn't applied or saved, even though I'm notified of its success.
When I reload the custom rule for my group is gone.  

Also I just tried to manually add a geofence rule for that new group (any layer) and it still isn't working.

![image](https://github.com/GeoNode/geonode/assets/34066246/5ecc6990-93be-45e6-8452-718398121bf0)

**Comment by vidlb** [comment]
This issue is critical ! We could say geofence is useless in that state.
@giohappy do you know if 4.2 is planned for release soon ? I'd like to avoid switching on master in my geonode-project, since I don't know if I could rollback from this without breaking the migrations.

**Comment by vidlb** [comment]
Hi @chumano .
That's what I did initially, then I realized the group must also exist as a group profile in order to be able to use it in the "share" tab of a dataset.

Anyway, it gets created also in that auth section using the name provided as "group slug" when configuring the profile.

**Comment by giohappy** [comment]
>This issue is critical ! We could say geofence is useless in that state.
@giohappy do you know if 4.2 is planned for release soon ? I'd like to avoid switching on master in my geonode-project, since I don't know if I could rollback from this without breaking the migrations, or having to reinit the whole db.

@vidlb should be released very soon, hopefully next week.
