### ISSUE TITLE
Errors in metadata upload

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#11448]
### Stable demo:
- [x] ***~~Upload data + metadata - SpatialRepresentationType~~***
  - ~~upload shapefile + metadata --> error~~
    - ![image](https://github.com/GeoNode/geonode/assets/717359/ef125a23-8e9b-409a-ae7f-b41d7af50669)
    - #11368
    - FIXED: the fix was not deployed yep

- [ ] ***[Stable] Upload metadata in existing layer***
 - upload shapefile + metadata --> error
  ![image](https://github.com/GeoNode/geonode/assets/717359/61dde5fb-35bc-4b0b-87d2-6209a9b66693)

### Devel demo:
- [ ] ***[Devel] Upload metadata in existing layer***
  - upload shapefile + metadata --> ok
  - edit / upload metadata --> error
    - ![image](https://github.com/GeoNode/geonode/assets/717359/9082d1f9-6be6-4958-adf2-6b674a09c166)
    - 
![image](https://github.com/GeoNode/geonode/assets/717359/8ef497a7-fb07-4401-aa34-96e8a061c1a6)

- [ ] ***Set metadata preserve***
  - upload shapefile + metadata --> ok
  - edit / edit metadata / tab settings --> check "metadata upload preserve"
  - "update"
  -   edit / edit metadata / tab preview --> error
    -  
![image](https://github.com/GeoNode/geonode/assets/717359/a8d3d8dc-6054-4ef4-a1b5-e3fac0998451)

    - 
![image](https://github.com/GeoNode/geonode/assets/717359/d42f9b02-1c35-4185-970c-cc6ba3ecc49d)
   - Response:  
     ```json
     {
     "success": false,
     "errors": "Note: this dataset's orginal metadata was populated and preserved by importing a metadata XML file. This metadata cannot be edited."
     }
     ```

**Comment by etj** [comment]
"Upload metadata in existing layer" is caused by the removal of all obsolete logic in https://github.com/GeoNode/geonode/pull/11363

**Comment by giohappy** [comment]
Investigation completed. Refer to the specific issues for their resolutions.
