### ISSUE TITLE
Geoserver not displaying files to import

### ISSUE THREAD

**Issue by lcoandrade** [GeoNode/geonode#11471]
## Expected Behavior
Display files in a folder to import

## Actual Behavior
I have a folder in my Downloads folder (/home/my_user/Downloads/archive). I'm trying to import geotiff files from this folder into GeoServer. The problem is:
When I select /home, nothing is displayed.

## Steps to Reproduce the Problem

  1. Login to GeoServer as Admin
  2. Go to the impor page
  3. Select spatial files
  4. Navigate to home folder

## Specifications

  - GeoNode version: 4.1.x
  - Installation type (vanilla, geonode-project): Vanilla
  - Installation method (manual, docker):docker
  - Platform:Ubuntu 22.04
  - Additional details:
  Installation script used:
```
Geonode
    1. cd /opt
    2. sudo git clone https://github.com/GeoNode/geonode.git -b 4.1.x
    3. cd geonode
    4. docker-compose up -d
    6. docker logs -f django4geonode
        1. Wait until we see something like: [uWSGI] getting INI configuration from ….
    7. #Access a http://localhost/
```

<img width="1435" alt="Captura de Tela 2023-09-12 às 07 00 39" src="https://github.com/GeoNode/geonode/assets/8769816/a878a61a-d280-4fb7-ba27-a6cb60dee636">

<img width="1435" alt="Captura de Tela 2023-09-12 às 07 00 53" src="https://github.com/GeoNode/geonode/assets/8769816/91ac926e-dae8-48ea-b1b4-20813c6c4460">

**Comment by giohappy** [comment]
@lcoandrade if you're running Geoserver inside container, it sees the its own filesystem and the data-dire volume, not the host machine.

You should copy your files to the data-die volume, which Geoserver sees under the /geoserver-data folder.

**Comment by lcoandrade** [comment]
How do I copy my files to geoserver_data/data folder?

Using `docker cp /path/to/my/files geoserver4geonode:/usr/local/geoserver_data/data`?

**Comment by giohappy** [comment]
`docker cp /path/to/my/files geoserver4geonode:/geoserver_data/data`
