### ISSUE TITLE
Switch docker base image to Ubuntu LTS

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#11487]
The docker base image has recently been updated from Ubuntu 22.04 LTS to 22.10 [introduced here](https://github.com/GeoNode/geonode/commit/543d751d8c5d98184008b175d06d97b4b8131db2).

This has created issues because master and 4.1.x works with the 22.10.
With the latest build are raising the following error:

```bash
=> ERROR [ 3/30] RUN apt-get update -y                                                                                                                               1.0s
------
 > [ 3/30] RUN apt-get update -y:
#0 0.413 Ign:1 http://security.ubuntu.com/ubuntu kinetic-security InRelease
#0 0.425 Err:2 http://security.ubuntu.com/ubuntu kinetic-security Release
#0 0.425   404  Not Found [IP: 91.189.91.82 80]
#0 0.537 Ign:3 http://archive.ubuntu.com/ubuntu kinetic InRelease
#0 0.609 Ign:4 http://archive.ubuntu.com/ubuntu kinetic-updates InRelease
#0 0.682 Ign:5 http://archive.ubuntu.com/ubuntu kinetic-backports InRelease
#0 0.756 Err:6 http://archive.ubuntu.com/ubuntu kinetic Release
#0 0.756   404  Not Found [IP: 185.125.190.39 80]
#0 0.831 Err:7 http://archive.ubuntu.com/ubuntu kinetic-updates Release
#0 0.831   404  Not Found [IP: 185.125.190.39 80]
#0 0.904 Err:8 http://archive.ubuntu.com/ubuntu kinetic-backports Release
#0 0.904   404  Not Found [IP: 185.125.190.39 80]
#0 0.914 Reading package lists...
#0 0.942 E: The repository 'http://security.ubuntu.com/ubuntu kinetic-security Release' does not have a Release file.
#0 0.942 E: The repository 'http://archive.ubuntu.com/ubuntu kinetic Release' does not have a Release file.
#0 0.942 E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-updates Release' does not have a Release file.
#0 0.942 E: The repository 'http://archive.ubuntu.com/ubuntu kinetic-backports Release' does not have a Release file.
```
CircleCi examples : [example1](https://app.circleci.com/pipelines/github/GeoNode/geonode/14478/workflows/5d3647b3-3c59-42c7-aadf-06494a44c429/jobs/77455), [example2](https://app.circleci.com/pipelines/github/GeoNode/geonode/14473/workflows/23083699-ebc1-499d-8e44-bf4cdff1de8d/jobs/77460)

As described in this [article](https://octopus.com/blog/using-ubuntu-docker-image#selecting-a-base-image), the `.10` as base image is not a good choice, 

> Docker images are provided for all versions of Ubuntu, including Long Term Support (LTS) releases such as 20.04 and 22.04, and normal releases like 19.04, 19.10, 21.04, and 21.10.
> LTS releases are supported for 5 years, and the associated Docker images are also maintained by Canonical during this period, as described on the Ubuntu release cycle page:
> These images are also kept up to date, with the publication of rolled-up security-updated images on a regular cadence, and you should automate your use of the latest images to ensure consistent security coverage for your users.

I think it would be better to switch back to the LTS Ubuntu 22.04 image.

**NOTE**: We are not facing (for now) this issue on master since it start from a pre-published image `geonode/geonode-base:latest-ubuntu-22.10`

CC: @etj @afabiani @giohappy

**Comment by giohappy** [comment]
What is not clear to me about the Ubuntu 22.04 image is how vulnerabilities and patch releases are managed.

From the Hub I see that the latest image has been updated 13 days ago, and several vulnerabilities are reported for its packages
![image](https://github.com/GeoNode/geonode/assets/571129/34cee6f4-0ea2-424a-9075-b86c21be4f59)

**Comment by giohappy** [comment]
Looking at the list of packages we can only infer that it's still using Ubuntu 22.04.1. 
Anyway, given that Ubuntu 22.10 is not supported anymore (EOL July 20th, 2023) and the GitHub runners are broken we will have to revert to the 22.04 image.

We might consider doing the upgrades (22.04.3 and packages inside our own base image
