### ISSUE TITLE
Geonode Dependencies

### ISSUE THREAD

**Issue by ridoo** [GeoNode/geonode#11507]
Good to see 4.1.3 is out, obviously a security release. 

However, it seems that it still points to dev dependencies of mapstore client and importer.

https://github.com/GeoNode/geonode/blob/6e241c346ec2c13341efd0c9eb2fcfe316c6ba1d/requirements.txt#L91-L92

**Comment by giohappy** [comment]
Ouch! We will need to do a post release...
