### ISSUE TITLE
The layer in GeoNode with view permissions can be downloaded through GeoServer."

### ISSUE THREAD

**Issue by meghakiyer** [GeoNode/geonode#11516]
![image](https://github.com/GeoNode/geonode/assets/144124531/c7be831e-dccf-497f-a3d6-90cda574ad4e)
![image](https://github.com/GeoNode/geonode/assets/144124531/c181fccc-90e0-4f01-8ec7-5396c238182b)
 The layer in GeoNode with view permissions can be downloaded through GeoServer."

**Comment by giohappy** [comment]
We can't reproduce it either on 4.1.3 or on master.  If a dataset is configured with only View permissions for anonymous, it's not listed inside Geoserver's layer previews.
Are you sure your Geoserver (and Geofence) is configured correctly?

**Comment by meghakiyer** [comment]
Issue solved by upgrading Geonode to version 4.1.x

**Comment by BinoyKadakkal** [comment]
#7351 
Deleting the geofence rule in the mentioned issue will solve the problem
