### ISSUE TITLE
Cannot add a dataset with the superuser

### ISSUE THREAD

**Issue by geogeek11** [GeoNode/geonode#11553]
I cannot add a dataset even using the superuser, I can upload a dataset but it cannot be added as a resource. 
The api/v2/executionrequest endpoint keeps returning response having a step value as 'start_import'. 

The UI for every dataset uploaded is as the following.
![image](https://github.com/GeoNode/geonode/assets/7670475/4b994252-2706-4c21-bd13-760b57fd4b6c)
 

## Specifications

  - GeoNode version: 4.1
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform: 
  - Additional details:

**Comment by mattiagiupponi** [comment]
Hi @geogeek11 
Can you please check the value of the `ASYNC_SIGNALS` variable in the `.env` file?
If is set to `TRUE`, be sure that celery is up and running. Otherwise the messages are not consumed.

If you dont want to run it with `CELERY` and in `ASYNC` mode, set it as `FALSE` and restart geonode.

**Comment by geogeek11** [comment]
Hi @mattiagiupponi , 
The 'ASYNC_SIGNALS' value is set to 'True', I would like to mention that I was able to add datasets using the superuser, I was not able to add datasets only using LDAP users but surprisingly after some time with no known reason even the super user is unable to add a dataset.

**Comment by mattiagiupponi** [comment]
Can you please share the celery log? it should be in `/var/log/celery.log` inside the celery container

**Comment by geogeek11** [comment]
the file celery.log contains only these lines :

[2023-09-28 17:05:35,572: WARNING/MainProcess] /usr/local/lib/python3.10/dist-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

**Comment by mattiagiupponi** [comment]
This is strange, can you please try to change the log level from WARN to INFO? Celery logs pretty much a lot of into, is a good indicator to understand what is happening

https://github.com/GeoNode/geonode/blob/93aa6100e8dc440fc150111d6603ac91caacf4b6/geonode/settings.py#L715-L717

**Comment by geogeek11** [comment]
These are the logs that I got after changing the log level to INFO :

`[2023-10-04 10:43:08,948: INFO/MainProcess] Connected to amqp://guest:**@rabbitmq:5672//
[2023-10-04 10:43:11,567: WARNING/MainProcess] /usr/local/lib/python3.10/dist-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

 

[2023-10-04 10:43:11,567: INFO/MainProcess] worker1@celery-768977fb55-59dd6 ready.
[2023-10-04 10:43:13,380: INFO/Beat] beat: Starting...
[2023-10-04 10:43:13,421: INFO/Beat] Scheduler: Sending due task collect_metrics (geonode.monitoring.tasks.collect_metrics)
[2023-10-04 10:43:13,434: INFO/Beat] Scheduler: Sending due task harvesting-scheduler (geonode.harvesting.tasks.harvesting_scheduler)`

**Comment by mattiagiupponi** [comment]
Hi @geogeek11 
Is still still happening?

**Comment by geogeek11** [comment]
Yes it still happening, I would very thankful if you could help

**Comment by mattiagiupponi** [comment]
@geogeek11 Can you please try to re-run geonode without defining LDAP users?
Please delete also the volumes to have a clean download.
In case you change in some way the docker compose, please share it here

**Comment by mattiagiupponi** [comment]
closing due lack of feedback
