### ISSUE TITLE
Permissons not working on wmsgetcapability link

### ISSUE THREAD

**Issue by BinoyKadakkal** [GeoNode/geonode#11568]
Layer permission settings do not operate with the Wmsgetcapability link. Access to the file could not be granted to a specified user.
![Screenshot from 2023-09-16 15-27-59](https://github.com/GeoNode/geonode-project/assets/108899419/f4d39429-e54b-4413-8228-90d665ff5a00)

**Comment by giohappy** [comment]
@BinoyKadakkal which GeoNode version?

**Comment by BinoyKadakkal** [comment]
#7351
The above mentioned was the real issue. It is now working properly
