### ISSUE TITLE
Problem while adding new field to ResourceBase model

### ISSUE THREAD

**Issue by ardean80** [GeoNode/geonode#11569]
I've successfully added a new field (as a ForeignKey) to the `ResourceBase` model, by "extending" it through the use of the `apps.py` file, as descreibed in the doc, and that was fine. This field is a further typological attribute and has its own set own predefined values on its table (already successfully added through the fixtures).
Now I'm finding problems in adding the proper dropdown menu in the Dataset metadata edit page, just below the topic category menu. I already created the `layouts/panels.html` extension in the `template` dir and the form elements in the `forms.py` file within the new app directory in my geonode-project root dir, but the dropdown menu is still not populated.
I'm sorry, I'm quite new to Django. Would it be possible to do what I need without modifying the core code, but only "extending" it, as already done for the `ResourceBase` model? Seems like I should extend the `layers/view.py` file, is this correct?

**Comment by giohappy** [comment]
@ardean80 issues are for reporting bugs. Support requests should be directed to the [mailing lists](https://geonode.org/communication/#mailing-lists)

**Comment by ardean80** [comment]
I'm sorry. 
Anyway, I did it. 
Thanks a lot! :)
