### ISSUE TITLE
Uploading file based content fails with "HTTP Status 401 - Unauthorized"

### ISSUE THREAD

**Issue by rabbl** [GeoNode/geonode#11570]
# Bug Report

## Description

Following the installation guide we have setup an instance of geonode with docker. The process worked well and the system is running properly except uploading file based content.

## Details

If I try to upland a file, e.g. [FAA_UTM18N_NAD83.tif](https://www.sciencebase.gov/catalog/item/53f5a87ae4b09d12e0e8547b#:~:text=a%20compressed%20file.-,FAA_UTM18N_NAD83,-.tif), the upload section shows me an error:

<img width="1265" alt="image" src="https://github.com/GeoNode/geonode-project/assets/1965304/7519c0cc-c379-4fba-a40b-e06772083d51">

Here the response from the (Response from the executionrequest)[https://geonode.inowas.com/api/v2/executionrequest?filter%7Baction%7D=import&filter%7Bsource%7D=upload&page=1&page_size=99999] 

```json
{
    "links": {
        "next": null,
        "previous": null
    },
    "total": 1,
    "page": 1,
    "page_size": 99999,
    "requests": [
        {
            "exec_id": "c407febd-6d37-4454-9392-944ca96ec433",
            "status": "failed",
            "func_name": "rollback",
            "created": "2023-10-05T13:15:15.022122Z",
            "finished": "2023-10-05T13:15:18.392493Z",
            "last_updated": "2023-10-05T13:15:18.392500Z",
            "input_params": {
                "files": {
                    "tif_file": "/mnt/volumes/statics/uploaded/tmprw77ulw4/FAA_UTM18N_NAD83.tif",
                    "base_file": "/mnt/volumes/statics/uploaded/tmprw77ulw4/FAA_UTM18N_NAD83.tif"
                },
                "total_layers": 1,
                "store_spatial_file": true,
                "handler_module_path": "importer.handlers.geotiff.handler.GeoTiffFileHandler",
                "skip_existing_layers": false,
                "overwrite_existing_layer": false
            },
            "output_params": {},
            "step": "importer.rollback",
            "log": "b'<!doctype html><html lang=\"en\"><head><title>HTTP Status 401 \\xe2\\x80\\x93 Unauthorized</title><style type=\"text/css\">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 \\xe2\\x80\\x93 Unauthorized</h1><hr class=\"line\" /><p><b>Type</b> Status Report</p><p><b>Message</b> Unauthorized</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class=\"line\" /><h3>Apache Tomcat/9.0.65</h3></body></html>'. Request: c407febd-6d37-4454-9392-944ca96ec433",
            "name": "FAA_UTM18N_NAD83.tif",
            "action": "import",
            "source": "upload",
            "user": 1000,
            "geonode_resource": null,
            "link": "https://geonode.inowas.com/api/v2/executionrequest/c407febd-6d37-4454-9392-944ca96ec433"
        }
    ]
}
```

## Hot to reproduce this bug

To reproduce this bug you could install the system on an ubuntu 22.04 instance following the instructions in the [Readme](https://github.com/GeoNode/geonode-project/blob/master/README.md).

I dis it as following on a VM with Ubuntu22.04 at Hetzner.

```shell
root@geonode:/srv/docker/geonode_test# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

The following steps I have done (with a valid email-address):

```shell
root@geonode:/ mkdir -p /srv/docker
root@geonode:/ python3.10 -m venv ~/.venvs/geonode_test
root@geonode:/ source ~/.venvs/geonode_test/bin/activate
(geonode_test) root@geonode:/ pip install Django==3.2.*
(geonode_test) root@geonode:/  mkdir geonode_test
(geonode_test) root@geonode:/ GN_VERSION=4.1.3 # master is not working here 
(geonode_test) root@geonode:/  django-admin startproject --template=https://github.com/GeoNode/geonode-project/archive/refs/tags/$GN_VERSION.zip -e py,sh,md,rst,json,yml,ini,env,sample,properties -n monitoring-cron -n Dockerfile geonode_test /srv/docker/geonode_test
(geonode_test) root@geonode:/  cd geonode_test/
(geonode_test) root@geonode:/  python create-envfile.py --https --email xxx@xxx-xxx.com --hostname geonode.inowas.com
(geonode_test) root@geonode:/  docker compose build --no-cache
(geonode_test) root@geonode:/  docker compose up -d --force-recreate
```

The system is now running and can be located on the given host. 
The SignIn as "admin" works also perfect.
The Error Shows up when I try to upload some file-based content.

**Comment by giohappy** [comment]
@rabbl can you please check if you can authenticate with Geoserver?
Take the Geoserver admin username and password from the `.env` file (`GEOSERVER_ADMIN_USER` and `GEOSERVER_ADMIN_PASSWORD`) and try to login in Geoserver with them.

Which version of geonode-project are you using?

**Comment by rabbl** [comment]
Dear @giohappy, 
I'm using version 4.1.3 (GN_VERSION=4.1.3).

The Login-Credentials from .env are not working to login on the geoserver, in our case it's:
https://geonode.inowas.com/geoserver/web

<img width="787" alt="image" src="https://github.com/GeoNode/geonode/assets/1965304/d293d95e-20cd-49b3-b5bb-fb51db9c41dd">

But! Logging in to geoserver after logging in as admin to geonode works. I can see and change all geoserver settings.

This makes me think that the geoserver-credentials must be correctly set.

<img width="270" alt="image" src="https://github.com/GeoNode/geonode/assets/1965304/46134978-0fab-433c-ad88-8810c48e632d">


So I tried the approach to reset the geoserver admin password and replace the password in the .env file.
When marking the master-password in Geoserver as forgotten, you can write it into a textfile into the temp-folder. 
This has been done. Let's say the file does show the following content:

```
This file was created at 2023/10/06 13:51:44

The current master password is: -yxa}d%X

Test the master password by logging in as user "root"

This file should be removed after reading !!!.
```

I tried to login as 'root'/'-yxa}d%X' and 'admin'/'-yxa}d%X' without success.

I also have updated the env-variable `GEOSERVER_ADMIN_PASSWORD` with the password.
Now it's also not possible for me to login to geoserver as geonode-admin.

**Comment by saxas13** [comment]
I had the same issue.
The problem/issue is in the docker from geoserver. It will not set the password from .env when you built the system. You need to login with admin - geoserver and change the password manually to the password from the .env file. Afterwards all works as expected. This issue was already a thing in branch 3 ...

**Comment by anbumanibalakrishnan** [comment]
Thank you. Got it working with this change

**Comment by rabbl** [comment]
As this is fixed, I will close the issue. Thanks again!
