### ISSUE TITLE
Bring back Batch Permission Setting

### ISSUE THREAD

**Issue by saxas13** [GeoNode/geonode#11577]
**Is your feature request related to a problem? Please describe.**

When uploading lots of datasets at the same time, batch permission could save a lot of time.

In Former versions (Geonode 3) it was possible to set these permission from the front end by selecting the respective datasets and use the "permissions" button and also via admin panel (Datasets -> select -> batch set permissions)

**Describe the solution you'd like**

I couldnd find any of these features in 4.1.3, please bring at least back the batch permissions setting for admins.

**Comment by apwebber** [comment]
Personally I have switched to using the API for uploading for this reason. For me this problem makes the web interface basically useless.

**Comment by giohappy** [comment]
@saxas13 batch permissions are still available inside the admin inside the Users page:

![image](https://github.com/GeoNode/geonode/assets/571129/d56239f2-8fc1-4cc3-9ae2-906ad151b7fe)

**Comment by saxas13** [comment]
Ah thank you. I guess in the earlier versions the settings where under layers, where I could select the layers and set the permissions for groups/users. Now the "set permission" is listed under group profiles and users. I didn't see that. Thank you.
