### ISSUE TITLE
Add section about using your GeoNode in QGIS

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1157]
Could also include info about opengeo qgis plugin @vdeparday?

**Comment by t-book** [comment]
@vdeparday @jj0hns0n This issue seems to be solved? http://docs.geonode.org/en/master/tutorials/users/using_geonode_w_other_applications/qgis.html?highlight=qgis
If so can you close?

**Comment by vdeparday** [comment]
Thank you @t-book for cleaning up the issue. I think we can close.

There may be a couple new things from what @timlinux has developed but I think it is limited to QGIS backend? https://www.youtube.com/watch?v=z0WYsEUNmg4

**Comment by t-book** [comment]
@vdeparday thanks for your reply. +1 for adding more QGIS documentation. I think what is missing most are explanations how to setup qgis server. maybe it would suffice focusing on docker by now. currently there is a docker-compose and local_settings for qgis server but no information at all how to use them.
