### ISSUE TITLE
Image Feature is not visible on the GFI

### ISSUE THREAD

**Issue by dsuren1** [GeoNode/geonode#11601]
## Describe the bug
The image link is broken on the GFI template due to incorrect properties reference in the template 
https://github.com/GeoNode/geonode/blob/43188af8a18a21879a4c8ba2d8e4d3c6abcf5eae/geonode/layers/api/serializers.py#L104

**Comment by mattiagiupponi** [comment]
merged via https://github.com/GeoNode/geonode/pull/11604
