### ISSUE TITLE
GEODATABASE_URL setting does not have a default value

### ISSUE THREAD

**Issue by ricardogsilva** [GeoNode/geonode#11615]
As discussed in #11203, specifically this comment:

https://github.com/GeoNode/geonode/issues/11203#issuecomment-1768091286

geonode importer assumes that `settings.GEODATABASE_URL` exists, but this variable may not have been defined - it depends on how the settings are configured.

Please check the rest of the discussion for a proposed fix.

## Steps to Reproduce the Problem

  1. Stand up GeoNode without defining the `DEFAULT_BACKEND_DATASTORE` env variable
  2. Try to upload some dataset
  3. Receive an error message saying something like `tuple.index(x): x not in tuple`

## Specifications

  - GeoNode version: 4.1.3
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment]
Hi @ricardogsilva 
The fix is ready on `change_db_datastore_uri` branch, please give a try if you have time.
PR: https://github.com/GeoNode/geonode-importer/pull/214

**Comment by mattiagiupponi** [comment]
Fix is merged on the importer master branch
