### ISSUE TITLE
Unable to upload a custom logo

### ISSUE THREAD

**Issue by lperozzi** [GeoNode/geonode#11653]
### Issue Description
I followed the steps outlined in the [Geonode documentation](https://docs.geonode.org/en/master/basic/theme/index.html#logos-and-graphics) to customize the logo, but I am encountering an issue where the logo is not updating as expected. I believe I have followed the guide step by step, but I encountered an error when attempting step 5 of the guide.

### Steps Taken
Here are the steps I followed:

1. I navigated to the provided documentation link and followed the instructions to customize the logo.
2. After completing the previous steps, I attempted to execute the following commands:

```bash
cd /home/geonode
sudo rm -Rf geonode/geonode/static_root/*
cd my_geonode
python manage.py collectstatic
sudo service apache2 restart
```

The folder structure of my project, which was created following the [basic installation guide](https://docs.geonode.org/en/master/install/basic/index.html), looks like this:

```bash
my_geonode
     ├── .env.sample
     ├── .gitignore
     ├── .override_dev_env.sample
     ├── Dockerfile
     ├── README.md
     ├── Vagrantfile
     ├── Vagrantfile.stack
     ├── create-envfile.py
     ├── dev_config.yml
     ├── docker
          ├── geoserver
          ├── geoserver_data
          ├── letsencrypt
          ├── nginx
          └── postgresql
     ├── docker-build.sh
     ├── docker-compose.yml
     ├── docker-purge.sh
     ├── generated-project-vagrant-compose.sh
     ├── generated-project-vagrant-swarm.sh
     ├── geonode-stack.yml
     ├── playbook.yml
     └── src
          ├── Makefile
          ├── README.md
          ├── celery-cmd
          ├── celery.sh
          ├── dev_config.yml
          ├── entrypoint.sh
          ├── fixtures
          ├── my_geonode
          ├── jetty-runner.xml
          ├── manage.py
          ├── manage.sh
          ├── manage_dev.sh.sample
          ├── monitoring-cron
          ├── package
          ├── pavement.py
          ├── paver.sh
          ├── paver_dev.sh.sample
          ├── requirements.txt
          ├── scripts
          ├── setup.py
          ├── tasks.py
          ├── uwsgi.ini
          └── wait-for-databases.sh

```

### Questions and Issues
1. I am unsure where to find the static_root folder in my project directory. 
2. When I attempted to run the command python manage.py collectstatic from within the "src" directory of my project, I encountered the following error:

```bash
Traceback (most recent call last):
  File ".virtualenvs/my_geonode/lib/python3.10/site-packages/django/core/management/__init__.py", line 237, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

(Additional error details...)

ModuleNotFoundError: No module named 'geonode'
```

**Comment by draunger** [comment]
@lperozzi I want to work on this issue please assign me

**Comment by giohappy** [comment]
That command works fine, You must have some misconfiguration in your setup.
Feel free to ask on the GeoNode public channels, like mailing-list o Gitter.
