### ISSUE TITLE
Implement the option to register users without automatic assignment of contributor role

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11651]
At the moment new users are given the "contributor" role (Django admin group) by default.
We want to introduce the option to disable this automation.

The assignment of the contributor role is done [here](https://github.com/GeoNode/geonode/blob/master/geonode/people/signals.py#L114-L116). 

A new setting `REGISTERED_USER_IS_CONTRIBUTOR`, which will be `True` by default, will control if the assignment should be applied by default.
The settings can be controlled with an env var with the same name.

**Comment by saxas13** [comment]
oh I would love that option. Currently I remove this role from every user, which should only view and download data but shall not be able to create new ressources
