### ISSUE TITLE
Demo WMS service used in services tests returns 404

### ISSUE THREAD

**Issue by fvicent** [GeoNode/geonode#11675]
Some tests in [services/tests.py](https://github.com/GeoNode/geonode/blob/master/geonode/services/tests.py) rely on https://demo.geosolutionsgroup.com/geoserver/ows?service=wms&version=1.3.0&request=GetCapabilities, which returns 404.

**Comment by giohappy** [comment]
The service URL must be replaced with https://gs-stable.geo-solutions.it/geoserver/wms
