### ISSUE TITLE
PIP install - GDAL version not accepted

### ISSUE THREAD

**Issue by tulhaum** [GeoNode/geonode#11683]
## Expected Behavior
geonode-importer installed sucessfully

## Actual Behavior
geonode-importer 1.0.5 depends on gdal==3.2.2.1 but gdal 3.6.1 is installed.

The conflict is caused by:
geonode-importer 1.0.5 depends on gdal==3.2.2.1
Is there any way to install geonode-importer using a gdal version higher than 3.2.2.1 ?

## Specifications

  - GeoNode version: 4.1.3
  - Installation type (vanilla, geonode-project): Vanilla
  - Installation method (manual, docker): manual
  - Platform:
  - Additional details:

**Comment by miceno** [comment]
Same issue on my side.

**Comment by mattiagiupponi** [comment]
https://github.com/GeoNode/geonode-importer/issues/218#issuecomment-1880830613

**Comment by mattiagiupponi** [comment]
@miceno @tulhaum 
Can you please try again using this branch?
With this branch contains the library upgrade and i removed the fixed dependency of gdal

You can install the branch with:

```
pip install -e git+https://github.com/geosolutions-it/geonode-importer.git@ISSUE_218#egg=geonode_importer
```
