### ISSUE TITLE
Upload Metadata Error no handlers for xml

### ISSUE THREAD

**Issue by jeff-bradley** [GeoNode/geonode#11701]
## Expected Behavior
Download ISO Metadata for dataset.
Upload ISO Metadata for dataset.

## Actual Behavior
Download ISO Metadata works, but when uploading the same file I get an Error with "Unexpected error! - Unknwon Error Code. Contact the system administrator for more information regarding this error message. Additional info: [No handlers found for this dataset type]" 

## Steps to Reproduce the Problem

  1.Download Metadata
  2.Upload same Metadata
  3.Error returned

## Specifications

  - GeoNode version:4 master
  - Installation type (vanilla, geonode-project):vanilla
  - Installation method (manual, docker):docker
  - Platform: GCP linux compute engine and also local wsl linux ubuntu
  - Additional details:

**Comment by davicustodio** [comment]
I confirm the same behavior in version 4.1.x

**Comment by mattiagiupponi** [comment]
Issues for handling XML and SLD files are already open in the [geonode-importer](https://github.com/GeoNode/geonode-importer/issues) repo

**Comment by giohappy** [comment]
This is caused by a refactoring in https://github.com/GeoNode/geonode/pull/11363
The issue is being tracked inside https://github.com/GeoNode/geonode-importer/issues/200

**Comment by ridoo** [comment]
@giohappy  after fixing the Regression, can this issue be closed then?

**Comment by mattiagiupponi** [comment]
fixed by https://github.com/GeoNode/geonode/issues/12049
