### ISSUE TITLE
After GeoServer Upgrade, layers do not show unless VIEW permission is given for ANYONE

### ISSUE THREAD

**Issue by desilvarami** [GeoNode/geonode#11713]
## Expected Behavior
Able to visualize layers based on the permissions set for each layer (Accurately worked before GeoServer Upgrade).

## Actual Behavior
Even the owner of the dataset, can not visualize a layer unless VIEW permission is given to ANYONE. Even if VIEW permission is given for REGISTERED MEMBERS, the layer can not be seen. But the resources are properly listed in the catalog.

## Steps to Reproduce the Problem

  1. Pull geoserver:2.23.0 and geoserver_data:2.23.0 images from GeoNode Docker Hub
  2. Modify the docker-compose.yml and docker-compose-geoserver-server.yml with new image tags
  3. Rebuilt docker

## Specifications

  - GeoNode version: 4.0.X
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform: Ubuntu 20.04 
  - Additional details: GeoServer 2.20.7 was upgraded to 2.23.0. Now if I reverse the GeoServer version to 2.20.7 (by modifying YML files and rebuilding docker), the problem persists.

**Comment by giohappy** [comment]
I suspect there's some misconfiguration in your Geoserver / Geofence. Apparently, there are some problems with the configuration of the Role service in your Geoserver.
I will close this. Feel free to ask for support through the mailing list or Gitter.
