### ISSUE TITLE
Pinax notifications templates use hard-coded "http" instead of  `default_http_protocol`

### ISSUE THREAD

**Issue by fvicent** [GeoNode/geonode#11741]
Many templates in `geonode/templates/pinax/notifications` use hard-coded "http" protocol to build URLs, such as:

https://github.com/GeoNode/geonode/blob/7cac111e745430fb54ee4142410d7bb756d7d720/geonode/templates/pinax/notifications/account_approve/full.txt#L3-L5

On the other hand, some templates use the `default_http_protocol` context variable defined by Pinax (based on `settings.PINAX_USE_SSL`) instead. This should be the rule:

https://github.com/GeoNode/geonode/blob/7cac111e745430fb54ee4142410d7bb756d7d720/geonode/templates/pinax/notifications/email_body.txt#L7-L9

**Comment by giohappy** [comment]
fixed in https://github.com/GeoNode/geonode/commit/ab14ce6ca947409c1d94915ae2900a75b6556557
