### ISSUE TITLE
Google Basemaps not working

### ISSUE THREAD

**Issue by christmasjumper** [GeoNode/geonode#11769]
## Expected Behavior
The documentation on this is non existent - it doesn't actually state how to do this, so this is based on an assumption of what I can find from previous bug reports and in the .env file

Input Google Maps API key into .env file and docker compose up -d, reload and google basemaps should appear as an option?

## Actual Behavior

Google basemaps don't appear, can't see a way to load these

## Steps to Reproduce the Problem

  1. Change the .env file to include a valid google maps API key
  2. docker compose up -d
  3. Reload webapp

## Specifications

  - GeoNode version: 4.1.x
  - Installation type (vanilla, geonode-project): project
  - Installation method (manual, docker): docker
  - Platform: Linux
  - Additional details:

**Comment by mattiagiupponi** [comment]
You need to change the `MAPSTORE_BASELAYERS` settings and add the payload with the configuration you need.
Documentation:
1) https://docs.geonode.org/en/master/basic/settings/index.html?highlight=MAPSTORE_BASELAYERS%20#mapstore-baselayers
2) https://github.com/GeoNode/geonode-mapstore-client/blob/0bfcb28fdc8e3d12be305fa13d49f13b9d959d71/tutorials/01-settings-variables.md
3) https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/maps-configuration/#google
