### ISSUE TITLE
Print tool issue on stable and development

### ISSUE THREAD

**Issue by ElenaGallo** [GeoNode/geonode#11779]
## Expected Behavior
It is possible to view the print preview and download the PDF for dataset and map.

## Actual Behavior
**On Stable**
A `Failed to load PDF file error` appears and the print preview is not visible

https://github.com/GeoNode/geonode/assets/56537133/31e96084-1d7c-4c07-9470-5ede6b88cf39

**On  Development**
A 405 error appears on console:
> POST https://development.demo.geonode.org/catalogue/%7Bgeoserver_ui%7D/geoserver/pdf/create.json?access_token=w4Tjx6YfGNm0wcSr77eErlh4UG1Gye 405 (Method Not Allowed)

https://github.com/GeoNode/geonode/assets/56537133/c0dbfc90-428f-4f03-aaa9-517de4d8c3aa

## Steps to Reproduce the Problem

  1. Open a Dataset/Map
  2. Click on Print tool
  3. Click on Print

**Comment by mattiagiupponi** [comment]
@ElenaGallo can you please retry? it looks that is working as expected

**Comment by giohappy** [comment]
it was a configurations issue with the demo instances.
