### ISSUE TITLE
Advanced metadata form displays Django's groups instead of GeoNode's

### ISSUE THREAD

**Issue by fvicent** [GeoNode/geonode#11892]
## Expected Behavior

In the advanced metadata form, the group selector should display GeoNode groups (= group profiles), as the wizard does:

![Screenshot 2024-01-25 163331](https://github.com/GeoNode/geonode/assets/26927473/1d4f46f9-ddd4-4e68-9d8b-f74f49749ba9)

## Actual Behavior

Django groups get displayed:

![Screenshot 2024-01-25 163322](https://github.com/GeoNode/geonode/assets/26927473/44b0b00e-057e-40ed-a06a-e62e827afc30)

## Steps to Reproduce the Problem

  1. Create a resource
  2. Go to metadata advanced

## Specifications

  - GeoNode version: master
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
Good spot! The metadata editor will change and the new concept is currently discussed at #11511 
I think the new editor will resolve this issue.
