### ISSUE TITLE
problem with cloning geonode 4.2.x repository

### ISSUE THREAD

**Issue by azizOthmani** [GeoNode/geonode#11901]
Hello everyone,
when i tried to clone geonode repository i got this error
`cd /opt; git clone https://github.com/GeoNode/geonode.git -b 4.2.x geonode
Cloning into 'geonode'...
remote: Enumerating objects: 165365, done.
remote: Counting objects: 100% (903/903), done.
remote: Compressing objects: 100% (400/400), done.
error: RPC failed; curl 56 GnuTLS recv error (-54): Error in the pull function.
error: 1620 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
`

**Comment by ridoo** [comment]
Seems to be more a connection issue on your side

**Comment by giohappy** [comment]
>@ridoo thanks for the answer, i am sure that my device is connected to the internet

it might be a problem in the network, a glitch with github services, something wrong with your git client.... For sure it doesn't depend on GeoNode :)
