### ISSUE TITLE
problem with Updating the settings in order to use the PostgreSQL Database

### ISSUE THREAD

**Issue by azizOthmani** [GeoNode/geonode#11907]
Hello everyone, i am trying to install geonode 4.2.x in an ubuntu 22.04 VM  
when i try the command `./paver_local.sh reset` this error appears
 `./paver_local.sh: line 5: 44029 Segmentation fault      (core dumped) paver $@ `
thank you.

**Comment by t-book** [comment]
I'd suggest to

- check your python version
- run the paver commands one after another to see where it fails

https://github.com/GeoNode/geonode/blob/e608505f1accc65470dfca5adce77c8df39d460c/pavement.py#L846-L860

**Comment by azizOthmani** [comment]
thank you
Python version 3.10.12
here is the execution of the paver commands
`
(geonode)` aziz@aziz-VirtualBox:/opt/geonode$ ./paver_local.sh reset
---> pavement.reset
---> pavement.stop
---> pavement.stop_geoserver
Stopping geoserver (process number 58355)
Stopping geoserver (process number 58357)
[Errno 3] No such process
Stopping GeoNode ...
---> pavement.stop_django
rm -rf /opt/geonode/geonode/development.db
rm -rf geonode/development.db
rm -rf geonode/uploaded/*
[Errno 2] No such file or directory: path('geoserver/data/global.xml')
[Errno 2] No such file or directory: path('geoserver/data/security/filter/geonode-oauth2/config.xml')
[Errno 2] No such file or directory: path('geoserver/data/security/role/geonode REST role service/config.xml')
./paver_local.sh: line 5: 58347 Segmentation fault      (core dumped) paver $@
(geonode) aziz@aziz-VirtualBox:/opt/geonode$ ./paver_local.sh setup
---> pavement.setup
---> pavement.setup_geoserver
makedirs path('downloaded')
/home/aziz/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
161793KB [02:01, 1329.23KB/s]                                                   
/home/aziz/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'repo1.maven.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
8880KB [00:09, 899.40KB/s]                                                      
/home/aziz/.virtualenvs/geonode/lib/python3.10/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'artifacts.geonode.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
167KB [00:00, 335.80KB/s]                                                       
makedirs path('geoserver')
GeoNode development environment successfully set up.If you have not set up an administrative account, please do so now. Use "paver start" to start up the server.
./paver_local.sh: line 5: 58392 Segmentation fault      (core dumped) paver $@
(geonode) aziz@aziz-VirtualBox:/opt/geonode$ ./paver_local.sh sync
---> pavement.sync
 python -W ignore manage.py makemigrations --noinput
Migrations for 'ratings':
  /home/aziz/.virtualenvs/geonode/lib/python3.10/site-packages/pinax/ratings/migrations/0004_auto_20240131_0853.py
    - Alter field category on overallrating
    - Alter field category on rating
Migrations for 'upload':
  geonode/upload/migrations/0040_alter_uploadparallelismlimit_max_number.py
    - Alter field max_number on uploadparallelismlimit
Segmentation fault (core dumped)


Captured Task Output:
---------------------

---> pavement.sync
 python -W ignore manage.py makemigrations --noinput

Build failed running pavement.sync: Subprocess return code: 139
./paver_local.sh: line 5: 58675 Segmentation fault      (core dumped) paver $@`

**Comment by azizOthmani** [comment]
![Screenshot from 2024-01-31 10-03-36](https://github.com/GeoNode/geonode/assets/126521858/0495e887-17c6-4809-bebe-593c1db92fb2)
![Screenshot from 2024-01-31 10-04-11](https://github.com/GeoNode/geonode/assets/126521858/792f24a5-4708-44cb-a1ad-a47aeb164dd7)

**Comment by mattiagiupponi** [comment]
Usually this happen when there is something wrong with the python installation. Please consider to re-create the environment from scratch

**Comment by azizOthmani** [comment]
@mattiagiupponi thank you 
I think the problem started from the beginning when installing system packages needed for the GeoNode setup 
When i tried `sudo apt install -y --allow-downgrades build-essential \
  python3-gdal=3.4.1+dfsg-1build4 gdal-bin=3.4.1+dfsg-1build4 libgdal-dev=3.4.1+dfsg-1build4 \`
I got this error 
'The following packages have unmet dependencies:
 libgdal-dev : Depends: libgdal30 (= 3.4.1+dfsg-1build4) but 3.4.3+dfsg-1~jammy0 is to be installed
               Depends: libpoppler-private-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.'
so i solved this by installing the version asked 3.4.1+dfsg-1build4
but when i verified gdal version i got this  `gdalinfo --version
GDAL 3.4.1, released 2021/12/27
Segmentation fault (core dumped)`
i ignored this and i continued the installation and that what caused the error above 
Now i tried to re-create the environment from scratch but with upgrading gdal ( but the official documentation impose GDAL 3.4.1) and it worked until the last step of the installation when i checked for the errors with `sudo tail -F -n 300 /var/log/uwsgi/app/geonode.log` 
I got this error 
![Screenshot from 2024-02-01 14-51-16](https://github.com/GeoNode/geonode/assets/126521858/f8c85032-08d8-4d27-b5c8-8d5b57674ef3)
![Screenshot from 2024-02-01 14-51-03](https://github.com/GeoNode/geonode/assets/126521858/6437493d-6e93-4300-a1c5-638a4a89a6cf)
![Screenshot from 2024-02-01 14-50-53](https://github.com/GeoNode/geonode/assets/126521858/04a964ef-f16d-4bec-8bc8-cad12c008730)
