### ISSUE TITLE
Upgrade Geoserver image with the fix for oauth2

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#11928]
Issue:

 - https://github.com/GeoNode/geonode/issues/11763
 - https://osgeo-org.atlassian.net/browse/GEOS-11290

A new Geoserver 2.23.3 has been built with the fixed `gs-sec-oauth2-core-2.23.3.jar` JAR. 
A new version of the image has been pushed to Docker Hub [geonode/geoserver:2.23.3-v2](https://hub.docker.com/layers/geonode/geoserver/2.23.3-v2/images/sha256-ffa725129574781b0481ba973142f276f2bb41dcc4af4b7516c3bf2d5d0f1382?context=repo)

**Comment by cesar-benjamin** [comment]
is geonode/geoserver:2.23.3-latest shadowed to geonode/geoserver:2.23.3-v2 ? or have to explicitly used as v2 tag instead latest to get this fix?
