### ISSUE TITLE
allow download datasets directly from original uploaded file

### ISSUE THREAD

**Issue by cesar-benjamin** [GeoNode/geonode#11930]
in a deployment that i have running with 4.0 version i see a link in metadata detail a link to download original dataset, this link are gone in 4.2 (not sure if 4.1 too).

i found that api rest now shows download_url a link that refers to an endpoint which sends a wps request to geoserver instead of original behavior of points to original uploaded file, and i see a note about a kind of deprecation plan of this new way in favor of an array of download_urls field.

i have a few datasets with many features, and default config of geoserver don't allows me donwload many datasets on this way, so i guess is important keep a field that allows download original uploaded field along with the wps way, i guess most of times users wants to download data directly and not as a query resulst, but the actual way have to proccess always via WPS, and that needs to change many settings, for example: OGC_REQUEST_TIMEOUT from 30 to 1200 to keep consistent with geoserver config, but have to change WPS Download config in geoserver to increase sizes and so on... 

Then, i guess default configuration in this way must be a set with higher values and keep available the way of retrieve original dataset files to direct download as a choice

 i guess this can be a GNIP

**Comment by mattiagiupponi** [comment]
Hi @cesar-benjamin 
In from GeoNode 4.2.x has bee introduced with this issue https://github.com/GeoNode/geonode/issues/11296 and later improved with this issue https://github.com/GeoNode/geonode/issues/11296 the concept of `Download Handler` and ofc GeoNode provides a default implementation of it which process the download via WPS and it can be found in [geonode.layers.download_handler.DatasetDownloadHandler](https://github.com/GeoNode/geonode/blob/master/geonode/layers/download_handler.py) 

The Download handler is a pluggable downloader that can be process the request as you prefer. We introduce this to let the user use the preferred downloader.

Use the custom downloader is quite simple. U can define it as `DEFAULT` or as an additional.

## Default

you can create your downloader by inherit it from the already existing class
 https://github.com/GeoNode/geonode/blob/54059ce3a2fd70d25e4c3f550b517a4c69c6bd17/geonode/layers/download_handler.py#L37

And then replace the default in the settings:
https://github.com/GeoNode/geonode/blob/54059ce3a2fd70d25e4c3f550b517a4c69c6bd17/geonode/settings.py#L2349

The endpoint for the download will stay the same, but it will let you process the download as you prefer.

## Additional (available via API only)

Is possible to add additional download urls, but are available via API only.

To do that, you have to create ur download handler and add the path here:
https://github.com/GeoNode/geonode/blob/54059ce3a2fd70d25e4c3f550b517a4c69c6bd17/geonode/settings.py#L2351

Then from the resources response, the custom download link will be shown in the `download_urls` payload key:

```
"download_urls": [
            {
                "url": "/datasets/<dataset_alternate>/dataset_download",
                "ajax_safe": true,
                "default": true
            },
            {
                "url": "custom_url",
                "ajax_safe": false,
                "default": true
            }
        ],
```

Hope this helps

**Comment by giohappy** [comment]
@cesar-benjamin In addition to what @mattiagiupponi already said, the purpose of the array of download_urls is exactly to give the option client side to select different types of downloads. So the backend and the API are ready to complete the implementation and reintroduce the download of original files. It only lacks resources and time to do it :)

**Comment by cesar-benjamin** [comment]
Excellent approach!

thanks for the answers, i found inspecting the code exactly the same result; as you said, there is a lack of documentation about it, and i guess must be improved a bit to avoid hadcoded intenttions of extensions.

great job, thanks a lot

**Comment by mattiagiupponi** [comment]
The PR for update the documentation is here https://github.com/GeoNode/documentation/pull/295 waiting for approval.
I'll close this issue then :)
