### ISSUE TITLE
django container is unhealthy when launching devcontainer

### ISSUE THREAD

**Issue by baptisteRiviere** [GeoNode/geonode#11961]
## Expected Behavior

Running the geonode project in devcontainer should launch every container

## Actual Behavior

Geoserver or celery containers are unhealthy ```ERROR: for geoserver  Container "fc415e61698f" is unhealthy```, it depends of my tests.

and then when I show container logs : ```ModuleNotFoundError: No module named 'nh3'```

It appears that it is django container which may give the error

## Steps to Reproduce the Problem

  1. I am running geonode in WSL with Ubuntu
  2. Clone the project, opening the file directory in VS Code and switching to 4.2.x branch
  3. Creating .env file with python command ```python create-envfile.py --env_type dev --geonodepwd geonode --geoserverpwd geonode --pgpwd geonode --dbpwd geonode --geod bpwd geonode --clientid geonode --clientsecret geonode```
  3. clicking 'Reopen in container'

## Specifications

  - GeoNode version: 4.2.x
  - Installation type : geonode-project
  - Installation method : docker
  - Platform: Ubuntu 22.04 - docker-compose 1.29.2

**Comment by kishkumar96** [comment]
I'am facing similar issues

**Comment by t-book** [comment]
@baptisteRiviere can you kindly check if adding

nh3==0.2.15

to 

https://github.com/GeoNode/geonode/blob/master/requirements_dev.txt

Solves your problem?

**Comment by baptisteRiviere** [comment]
Adding this line solved the problem and the application is now deployed

Many thanks
