### ISSUE TITLE
Keyword edits not pushed from GeoNode to GeoServer

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1196]
Version: GeoNode master
When editing the keywords through the edit metadata interface of GeoNode, the changes are not saved back to  GeoServer keywords.

**Comment by state-hiu** [comment]
@simod, so is likely a GeoNode or GeoServer problem?

**Comment by jj0hns0n** [comment]
I've just verified that this is still an issue. Adding keywords on the geonode side does NOT save them to the geoserver side. I'll take on trying to solve this.

**Comment by jj0hns0n** [comment]
@simod is correct, they do seem to show up after a forced second save. We are investigating.
