### ISSUE TITLE
B/R should only deal with data

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#11977]
## Expected Behavior

After the restore, only data should be changed, not the file inside the libs 

## Actual Behavior

Some files (also in geonode-mapstore-client) are overwritten.
In particular, we found the the `index.html` template of `geonode-mapstore-client` overwritten with the empty one from geonode, so the HTTP request to the root path of the geonode instance would return a blank page.

## Steps to Reproduce the Problem

After a B/R procedure, the restored system retruned a blank root page.

## Specifications

  - GeoNode version: tried on 4.1.4
  - Installation type: geonode-project
  - Installation method (manual, docker):

**Comment by giohappy** [comment]
Templates shouldn't be part of the B/R IMHO. They're code, not data.
I would completely remove the templates from the B/R procedure.

**Comment by etj** [comment]
Also the trees of `LOCALE_PATHS` are put in the backup zip and then restored.
