### ISSUE TITLE
I cant upload an .tif or .kmz files, but geojson no problem.

### ISSUE THREAD

**Issue by Fedesin** [GeoNode/geonode#11998]
## Expected Behavior

I want to upload a .tif file on geonode dataset.

## Actual Behavior

i got errors like this:

![imagen](https://github.com/GeoNode/geonode/assets/91753433/672a5772-7d4b-42b4-b236-959f9fa8c4b3)

the geoserver.log says:

![imagen](https://github.com/GeoNode/geonode/assets/91753433/207e5ab5-42c7-4a75-99b0-dd9328964bb7)
![imagen](https://github.com/GeoNode/geonode/assets/91753433/a3e30d59-a560-46e7-b288-3502c80bd401)

i dont know how to solve this.

## Steps to Reproduce the Problem

  1. go to upload dataset
  2. put an .tif file
  3. got the error

## Specifications

  - GeoNode version: 4
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): manual
  - Platform: debian 11
  - Additional details: running on a server

**Comment by mattiagiupponi** [comment]
Which specific version are you using of geonode?

Try anyway to add in the requirements.txt this line:

```
-e git+https://github.com/GeoNode/geonode-importer.git@master#egg=geonode-importer
```

It should fix the issue, or at least give a better output of the issue

**Comment by Fedesin** [comment]
> Which specific version are you using of geonode?
> 
> Try anyway to add in the requirements.txt this line:
> 
> ```
> -e git+https://github.com/GeoNode/geonode-importer.git@master#egg=geonode-importer
> ```
> 
> It should fix the issue, or at least give a better output of the issue

I have 4.1.0 version, and i have already that line in my requirements.txt

**Comment by mattiagiupponi** [comment]
Can you please try to upload the dataset in the geonode demo instance? https://development.demo.geonode.org/
Or share the dataset you are trying to upload

**Comment by Fedesin** [comment]
> Can you please try to upload the dataset in the geonode demo instance? https://development.demo.geonode.org/ Or share the dataset you are trying to upload

i can upload in the demo instance.
