### ISSUE TITLE
geonode-updateip removes previous settings.

### ISSUE THREAD

**Issue by Dominode** [GeoNode/geonode#1199]
Rather than overwriting the ALLOWED_HOSTS settings, could there be an option to keep existing entries (if they have been changed from defaults)?

**Comment by jj0hns0n** [comment]
@ingenieroariel its not clear to me if this was already fixed or not? If not, its probably something I can work on.

**Comment by ingenieroariel** [comment]
It is not fixed. This behavior still happens in beta18.
