### ISSUE TITLE
Help Needed!!

### ISSUE THREAD

**Issue by nitesh047** [GeoNode/geonode#11999]
I have installed advance geonode using a Docker container.  And now, I am trying to make changes in the base.html file but the changes are not reflecting. Can anyone help me with this issue?

Thanks!

**Comment by mattiagiupponi** [comment]
The template are in the [geonode-mapstore-client](https://docs.geonode.org/en/master/basic/theme/index.html) library.
In the documentation is explained how to update them: [doc](https://docs.geonode.org/en/master/basic/theme/index.html)
They follow the default "django template override" logic as described [here](https://docs.djangoproject.com/en/3.2/howto/overriding-templates/) or just [the doc](https://doc-geonode.readthedocs.io/en/latest/004_admin_workshop/004_customize_lookfeel/customize/theme_admin.html)

When opening an issue, please use a meaningful title and/or search in the already present issues if some hint is present like https://github.com/GeoNode/geonode/issues/11739
