### ISSUE TITLE
Extension and/or homepage customization 

### ISSUE THREAD

**Issue by jnermano** [GeoNode/geonode#12001]
Hi,

is there a way to add a geonode-mapstore-client’s extension to the homepage of geonode?

I think the homepage of geonode is from  geonode-mapstore-client, but I can’t override the homopage by creating by example : /templates/geonode-mapstore-client/snipsetts/hero.html.

master branch of geonode
Docker installation

**Comment by mattiagiupponi** [comment]
The template are in the [geonode-mapstore-client](https://docs.geonode.org/en/master/basic/theme/index.html) library.
In the documentation is explained how to update them: [doc](https://docs.geonode.org/en/master/basic/theme/index.html)
They follow the default "django template override" logic as described [here](https://docs.djangoproject.com/en/3.2/howto/overriding-templates/) or just [the doc](https://doc-geonode.readthedocs.io/en/latest/004_admin_workshop/004_customize_lookfeel/customize/theme_admin.html)
