### ISSUE TITLE
Add a custom background basemap 

### ISSUE THREAD

**Issue by azizOthmani** [GeoNode/geonode#12019]
Hello everyone, how can I add a custom background basemap other then the three default ones ( OpenStreetMap/ OpenTopoMap/ Sentinelles )  so that it still appears when running geonode offline ?

**Comment by kikislater** [comment]
So you have 2 questions:

- How to change basemap to custom ones? It's available in documentation: in settings you can change mapstore layers. It's described here : https://docs.geonode.org/en/master/basic/settings/index.html#mapstore-baselayers

- How to have an offline basemap server ? 
https://media.ccc.de/v/fossgis2023-23691-get-your-own-openstreetmap-dataset-running-in-a-geoserver-instance-in-2-steps
https://www.geosolutionsgroup.com/news/geoserver-osm-webinar-1/

**Comment by kikislater** [comment]
settings mean settings.py, it's better to understand how django works !
