### ISSUE TITLE
Conflicted store names doesn't generate a new name

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1201]
Here is the error:
GeoServer reported a conflict creating a store with name population_affected_by_volcanic_hazard_zone_using_volcanoes_and_people_1_1: "There is already a store named population_affected_by_volcanic_hazard_zone_using_volcanoes_and_people_1_1". This should never happen because a brand new name should have been generated. But since it happened, try renaming the file or deleting the store in GeoServer. 

It is not a blocker but since it is not supposed to happen, it would be good to fix at some point. I had a quick look at the code, it is around there: https://github.com/GeoNode/geonode/blob/master/geonode/layers/utils.py#L303
I'll have a deeper look and I should be able to fix it.

**Comment by jj0hns0n** [comment]
@vdeparday can you provide more information on how to replicate this one? I've tried a few different things and am unable to replicate it. This may have been fixed long ago.
