### ISSUE TITLE
openid_connect provider is not available in "Add social application" in django admin

### ISSUE THREAD

**Issue by fgomezdev** [GeoNode/geonode#12026]
## Expected Behavior
openid_connect provider available to create a social application from Django admin

## Actual Behavior
All providers appear, but not openid_connect.

## Steps to Reproduce the Problem
  1. add provider in settings:
  `INSTALLED_APPS += (
    'allauth.socialaccount.providers.linkedin_oauth2',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.openid_connect',
)`
  2. add in .env:
  SOCIALACCOUNT_OIDC_PROVIDER_ENABLED=True
  
  3. docker compose up
  4. try to add a new social app in django admin

## Specifications

  - GeoNode version: 4.1.3
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform: ubuntu linux
  - Additional details: 
     * I've tested the same version of django-allauth on other projects with no problems.
     * I guess than the underscore in openid_connect is the problem, in geonode.people.management.commands.setupsociallogins the method Command.get_social_providers get the provider name splitting by '_' the provider_module.

**Comment by adamhtoolwin** [comment]
I'm not sure about v4.1.3 but from my personal experience, v4.2.0 offers a far more versatile way of adding external OIDC providers. I was able to set up Keycloak as an external SSO provider in this version. So perhaps, if circumstances permit, you could try the latest v4.2.0 of Geonode.

**Comment by fgomezdev** [comment]
> I'm not sure about v4.1.3 but from my personal experience, v4.2.0 offers a far more versatile way of adding external OIDC providers. I was able to set up Keycloak as an external SSO provider in this version. So perhaps, if circumstances permit, you could try the latest v4.2.0 of Geonode.

Ok, I'll try it with v4.2.0.
Thank you!

**Comment by fgomezdev** [comment]
Hi @adamhtoolwin, could you help me with a sample .env configuration for keycloak please?
I was not able to get Keycloak as a new provider by following the instructions.
Thanks in advance.
