### ISSUE TITLE
Changing permissions of user upload dataset not working

### ISSUE THREAD

**Issue by JosephBannon** [GeoNode/geonode#12042]
## Expected Behavior
A user should be able to change the permissions of a dataset they upload to geonode.

## Actual Behavior
Right now I can upload the dataset to geonode and it appears in geoserver but when trying to change the permissions the geonode will just hang. 
![image](https://github.com/GeoNode/geonode/assets/87155060/4a9977ce-e8c3-4615-a9c5-4824cfaad9e5)

## Steps to Reproduce the Problem

  1. Start geonode and login as admin
  2. Upload this dataset 
[ne_10m_coastline.zip](https://github.com/GeoNode/geonode/files/14572283/ne_10m_coastline.zip)
  3. Click view dataset in the UI
  4. Click share, change anyone to None, then click save
  5. Geonode will say save successful but will not add any geofence rules and will have a spinny wheel on the share tab, when you refresh the change is reverted

## Specifications

  - GeoNode version: 4.2.2
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker image in kubernetes
  - Platform: Ubuntu 22.04
  - Additional details:

**Comment by JosephBannon** [comment]
@giohappy it works in both the stand dev and stable demos. I am not sure how my local configuration is different from those ones.

**Comment by giohappy** [comment]
I suggest asking using the user and dev mailing lists or the GeoNode Gitter channel.
If you're ok I will close this issue. Feel free to reopen it if you really think that it depends on GeoNode itself.

**Comment by JosephBannon** [comment]
I figured out what the issue was. We bumped the geonode to 4.2.2 without bumping the celery version to 4.2.2. :facepalm: . I feel very foolish now.
