### ISSUE TITLE
Fix bug in geonode/people that throws error when using custom OIDC Identity Provider for user loggins

### ISSUE THREAD

**Issue by JosephBannon** [GeoNode/geonode#12041]
## Expected Behavior
I am using the geonode_openid_connect tag and configuring the SOCIALACCOUNT_PROVIDERS map to point to a local oidc identity provider. When I login with a user, they should be automatically added to a group if it exists in their access token and in geonode prior to login. 

## Actual Behavior
Right now there are small bugs in geonode/people/adapters.py and geonode/people/profileextractor.py. When I run my geonode, I configured it to login the user in via the oidc identity provider,  it throws an error based on (line 311/312) in geonode/people/adapters.py and geonode/people/profileextractor.py (line 211). 

## Steps to Reproduce the Problem
1) Set up an external oidc provider ( in my case keycloak)
2) In the settings.py file, override the SOCAILACCOUNT_PROVDERS with this block of code based on your keycloak install
![image](https://github.com/GeoNode/geonode/assets/87155060/4272af9b-dce5-443c-803f-aa9203d54218)
As well as these environment variables
![image](https://github.com/GeoNode/geonode/assets/87155060/83743607-a59c-458a-8ebc-9c1f44395de6)
3) Create user and groups in keycloak and a client to log in through
4) As the geonode admin, create a group with the same name as the group a user is in in keycloak (both group names must be lowercase)
5) In geonode UI, click login, log in via OpenId Connect
6) This should result in an error

## Specifications

  - GeoNode version: 4.2.2
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker):
  - Platform: Ubuntu 22.04
  - Additional details:

## Quick fix
1)
Line 211 in geonode/people/profileextractor.py
![image](https://github.com/GeoNode/geonode/assets/87155060/0f7556e6-eac6-49c0-9f7b-8e66d99bf180)
Should be changed to 
![image](https://github.com/GeoNode/geonode/assets/87155060/c4d758b4-ea14-4733-8f53-8e32f8660e1f)

This is because on Line 311 in geonode/people/adapters.py to use the object.function notation in python the first argument in the method must be "self."
![image](https://github.com/GeoNode/geonode/assets/87155060/85f23465-192c-4293-801d-4b194c64e163)

2)
On Line 312 in geonode/people/adapters.py
![image](https://github.com/GeoNode/geonode/assets/87155060/023b1c99-9a20-44ef-92d4-b3c34ee533e2)
Should be changed to 
![image](https://github.com/GeoNode/geonode/assets/87155060/67f51051-12a2-47af-b083-39b498c74d37)

This is because on Line 215 in geonode/groups/models.py the "promote" method takes two arguments on of which is "self" and one of which is the user, however only the self argument is provided in the function call On Line 312 in geonode/people/adapters.py.
![image](https://github.com/GeoNode/geonode/assets/87155060/35674fde-9b13-4914-bc5f-a28310de5f39)

**Comment by afabiani** [comment]
@JosephBannon could you please send a PR with the required changes?

**Comment by JosephBannon** [comment]
@afabiani I see you made this change already, thank you
