### ISSUE TITLE
Docker: manifest for geonode/geoserver_data:2.24.2 not found

### ISSUE THREAD

**Issue by gmpuljak** [GeoNode/geonode#12051]
Hi,
I've just cloned the repo. I am using a virtualbox machine with Ubuntu 22.04.
I've run: python3 create-envfile.py.
Then: docker-compose up -d.
It started downloading until it gave the following error:
ERROR: manifest for geonode/geoserver_data:2.24.2 not found: manifest unknown: manifest unknown.

**Comment by Iskiwi** [comment]
I had the same problem

**Comment by mattiagiupponi** [comment]
Can you please try using `2.24.2-latest` as target image?

So by changing this line of the docker-compose file:

https://github.com/GeoNode/geonode/blob/f6a2884582e75ab56f8dbc64e1620fe9ae28e1de/docker-compose.yml#L117

**Comment by gmpuljak** [comment]
Hi,
I had to change the target image in lines 91 and 117.
I cleared all with sh docker-purge.sh
After that, I run docker-compose up -d and got the following message:

![VirtualBox_geonode-geoserver_18_03_2024_16_08_29](https://github.com/GeoNode/geonode/assets/13880626/0b2fa127-7199-417c-9185-87de2abf920a)

**Comment by mattiagiupponi** [comment]
The geoserver image expose the port 8080, it looks like you already have an application running on that port which could be the previous geoserver or any other application like Skype.

First step do a `docker compose down` or `docker-compose down` (the command change based on your docker version.

Then do a `docker ps -a` to check if there is still some container running and on the column `PORT` check if there is something running on port 8080.

If yes, stop the container using `docker stop`
If not, re-do the `docker compose up` or `docker-compose up`.

After that everything should run again

**Comment by giohappy** [comment]
It was an error in teh upgrade commit (which btw is fine for 4.2.x).
We will fix master asap.

**Comment by giohappy** [comment]
PR https://github.com/GeoNode/geonode/pull/12070 in review
