### ISSUE TITLE
"Issue with Extra_Metadata (Optional Metadata) Functionality"

### ISSUE THREAD

**Issue by meghakiyer** [GeoNode/geonode#12090]
Despite adhering to the schema, provided in the  Default_Extra_Metadata_Schema , it has been observed that the supplied extra metadata fails to appear in the view metadata of the layer or in information section of the layer, in contrast to other options such as supplementary information

![Screenshot from 2024-03-26 10-52-53](https://github.com/GeoNode/geonode/assets/144124531/a367e6dd-eaf1-4d24-aace-f56764aa78ec)
![Screenshot from 2024-03-26 10-51-45](https://github.com/GeoNode/geonode/assets/144124531/5bde9a79-930e-42ab-ba26-c4761f747bf4)
![Screenshot from 2024-03-26 16-28-58](https://github.com/GeoNode/geonode/assets/144124531/c25fe916-6f99-41be-91aa-7b673d7cfe2e)
![Screenshot from 2024-03-26 10-52-23](https://github.com/GeoNode/geonode/assets/144124531/f91dc8be-9062-4cc2-ad0a-1fefef65b034)

**Comment by giohappy** [comment]
@meghakiyer they do not appear simply because they're not meant to be viewed neither in the metadata view nor inside information section of the layer.
