### ISSUE TITLE
download of a dataset 

### ISSUE THREAD

**Issue by mucke2701** [GeoNode/geonode#12098]
## Expected Behavior
That I can download and export dataset in different formats

## Actual Behavior
In the export window is following error message: download failed! Server send wrong data, Error code: {errorCode}

## Steps to Reproduce the Problem

  1. Upload a dataset
  2. Open the Dataset in the catalogue
  3. Download the dataset, in whatever Format you like
  4. Try to export it

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): Azure Container Instances
  - Additional details: 

using
Geonode: 4.2.x
Geoserver: 4.2.3-v2  
Geoserver-Data-Dir: 4.2.3-v1
Geoserver Logs:
  
16:54:14 WARN   [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie:  sessionid=...; expires=Wed, 10 Apr 2024 16:54:14 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Wed, 10 Apr 2024 16:54:14 GMT

27 Mar 16:54:14 WARN   [protocol.ResponseProcessCookies] - Invalid cookie header: "Set-Cookie:  sessionid=....; expires=Wed, 10 Apr 2024 16:54:14 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax". Invalid 'expires' attribute: Wed, 10 Apr 2024 16:54:14 GMT

27 Mar 16:54:51 WARN   [geotools.xsd] - Sax parser property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' not recognized.  Xerces version is incompatible.

27 Mar 16:54:51 WARN   [geofence.wps] - ExecId:5245793a-a1ca-4757-a6fd-350724551fa2 Current process stack is gs:DownloadEstimator --- +gs:DownloadEstimator

27 Mar 16:54:51 WARN   [geofence.wps] - ExecId:5245793a-a1ca-4757-a6fd-350724551fa2 Current process stack is [MISSING CHAIN] --- -gs:DownloadEstimator

27 Mar 16:54:51 WARN   [geotools.xsd] - Sax parser property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' not recognized.  Xerces version is incompatible.

27 Mar 16:54:51 WARN   [geofence.wps] - ExecId:ce54e406-1564-4505-b3b6-966db4d0955f Current process stack is gs:Download --- +gs:Download

27 Mar 16:54:53 WARN   [geofence.wps] - ExecId:ce54e406-1564-4505-b3b6-966db4d0955f Current process stack is [MISSING CHAIN] --- -gs:Download

**Comment by mucke2701** [comment]
Under the OperationsMetadata:

ows:Get xlink:href=

On Local Setup it seems to be set:

<ows:Get xlink:href="http://localhost/geoserver/wps"/>
<ows:Post xlink:href="http://localhost/geoserver/wps"/>

**Comment by ffischer1984** [comment]
the geoserver container needs the following environment-variables:
`
- name: GEOSERVER_PUBLIC_LOCATION
  value: "http://localhost/geoserver/"
- name: PROXY_BASE_URL
  value: ""http://localhost/geoserver/"
`
at the second I'm a little bit unsure

**Comment by mucke2701** [comment]
solved it.
