### ISSUE TITLE
Uploaded KML with MultiGeometry features has PostGIS SRID issues, features cannot be edited or identified

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1210]
After uploading a KML containing MultiGeometry features generated with Arc2Earth, both Identify and feature editing does not work, trying either one results in this error in the response:

ERROR: Relate Operation called with a LWGEOMCOLLECTION type.  This is unsupported.

The layer's PostGIS (version 1.5) table has an SRID of -1.   Running 'UpdateGeometrySRID'   function on the table causes an error due to a missing enforce_srid constraint.

**Comment by jj0hns0n** [comment]
I think we are going to abandon the current kml importer in 2.4. @ischneider let me know otherwise if so.
