### ISSUE TITLE
MemcachedCache is not working as django MEMCACHED_BACKEND

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#12106]
## Expected Behavior
If i set `MEMCACHED_ENABLED=True` and `MEMCACHED_BACKEND=django.core.cache.backends.memcached.MemcachedCache` the cache should work

## Actual Behavior

Django raise an error:

```
Could not find backend 'django.core.cache.backends.memcached.MemcachedCache': Module "django.core.cache.backends.memcached" does not define a "MemcachedCache" attribute/class
```

From Django 4.1, MemcachedCache support has been dropped, see [releases notes ](https://docs.djangoproject.com/en/5.0/releases/4.1/#features-removed-in-4-1).

We should change the cache system and use  [PyLibMCCache](https://github.com/django/django/blob/c98eca322af87adf046ab621e7c8a23d340f7afe/django/core/cache/backends/memcached.py#L205) for example

## Steps to Reproduce the Problem

  1. on master set set `MEMCACHED_ENABLED=True`
  2. Run django

## Specifications

  - GeoNode version: master ONLY
  - Installation type (vanilla, geonode-project): master ONLY
  - Installation method (manual, docker): docker / manual
  - Platform:
  - Additional details: only master is affected since is the only branch that uses Django 4.2

**Comment by giohappy** [comment]
Keep in mind that at the moment the usage of a real Django cache is not very well tested. There were problems reported with the REST API.
The only real Memcached cache we're actively using is the one [for the transaction locks](https://github.com/GeoNode/geonode/blob/master/geonode/tasks/tasks.py#L31-L37)., and it uses `pylimc`
