### ISSUE TITLE
 ERROR: geoserver and  celery  is unhealthy.

### ISSUE THREAD

**Issue by darkbox** [GeoNode/geonode#12120]
Hi, first time testing Geonode. I've followed instructions from [docker-compose-tutorial](https://cs-geonode.readthedocs.io/en/2.8_a/tutorials/install_and_admin/running_docker/setup_docker_compose.html). But when using `docker-compose up` I'm facing the following errors:
```
docker-compose up
Creating network "geonode_default" with the default driver
Creating rabbitmq4geonode    ... done
Creating gsconf4geonode      ... done
Creating letsencrypt4geonode ... done
Creating memcached4geonode   ... done
Creating nginx4geonode       ... done
Creating db4geonode          ... done
Creating django4geonode      ... done

ERROR: for geoserver  Container "07d728756abf" is unhealthy.

ERROR: for celery  Container "07d728756abf" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

The `.env` is the default one copied from `.env_local`.

## Host
- Ubuntu 23.10
- Docker version 24.0.5, build 24.0.5-0ubuntu1
- docker-compose version 1.29.2, build unknown

**Comment by mattiagiupponi** [comment]
The documenation you are referring to is for geonode 2.8. Please try with following the doc of the latest version
https://docs.geonode.org/en/master/install/advanced/project/index.html#docker
