### ISSUE TITLE
Inconsistency between geonode ubuntu package and pip installed packages that depend on it.

### ISSUE THREAD

**Issue by nastasi-oq** [GeoNode/geonode#1213]
Steps to reproduce the bug:
- install geonode 2
 from deb package
- install another package that depends on geonode using pip (without --ignore-dependencies)

At this point pip try to install OWSLib version 0.7.2 although the 0.7.3 is already installed by deb package.

Just after a little investigation I found that the installed geonode unmeet it's own dependencies (in the setup.py).

**Comment by jj0hns0n** [comment]
Should we go ahead and close this one?
