### ISSUE TITLE
how to  log in to geonode using python?

### ISSUE THREAD

**Issue by a13668349935** [GeoNode/geonode#12148]
url = "https://master.demo.geonode.org/api/v2/resources"
headers = {
    'Authorization': 'Basic dXNlcjpwYXNzd29yZA=='
}
response = requests.request("GET", url, headers=headers)

which  api  i can use  to get the token .
can anyone get me  an example ? 
thanks.

**Comment by gannebamm** [comment]
Hi 
Maybe this repository can help: https://github.com/GeoNodeUserGroup-DE/geonodectl
It is a CLI tool written in Python which uses the REST API to interact with GeoNode.

**Comment by ridoo** [comment]
> which api i can use to get the token .
> can anyone get me an example ?

Actually there is no token in the example you posted, it is just [Basic Authentication](https://en.wikipedia.org/wiki/Basic_access_authentication). To get the Header right you have to encode the `username:password` into Basic64. Being on a linux terminal you could just do the following:

```
curl https://master.demo.geonode.org/api/v2/resources -H "$(echo -n admin:admin | base64)"
```

Of course, you'd have to replace the values for username and password (above I used `admin` for both).

As @gannebamm said, using `geonodectl` is also a good option. If you want to go with python, you could use the `base64` module. This [StackOverflow answer](https://stackoverflow.com/a/7000784/2299448) might be a good starter.
