### ISSUE TITLE
unable to set advanced contact roles in metadata editor

### ISSUE THREAD

**Issue by mwallschlaeger** [GeoNode/geonode#12170]
## Expected Behavior

When setting an advanced (related to this PR (https://github.com/GeoNode/geonode/pull/10367)) contact role through the metadata editor it is not stored in the database.

I guess this is related to changes to django framework.

## Specifications

  - GeoNode version: 4.2
  - Installation type (vanilla, geonode-project): all
  - Installation method (manual, docker): all
  - Platform: all
  - Additional details:

**Comment by mattiagiupponi** [comment]
Hi @mwallschlaeger 

> I guess this is related to changes to django framework.

Side note, the django framework is updated only on master where we have the 4.2, on GeoNode 4.2.3 we still have django 3.2

**Comment by giohappy** [comment]
Reopening since this must be fixed in 4.2.x too.
