### ISSUE TITLE
Bug and Solution for error (m2m_changed() missing 1 required positional argument: 'using') in datasets (in django admin)

### ISSUE THREAD

**Issue by HaziqLucii** [GeoNode/geonode#12206]
## Expected Behavior
save without any error

## Actual Behavior
got error missing positional argument like the error image below

## Steps to Reproduce the Problem

  1. go to datasets, choose any data
![image](https://github.com/GeoNode/geonode/assets/37583245/fb51e754-0002-4109-8552-da7545333e5b)
  2. save
  3. the error screen : 
![image](https://github.com/GeoNode/geonode/assets/37583245/49d05955-18c8-4d4a-a238-352594db5662)

## To solve this : 
1. go to geonode/geonode/base/models.py
2. go to line 420, in this function add using positional arg like this :
`signals.m2m_changed.send(
                sender=self.through,
                action="pre_add",
                instance=self.instance,
                reverse=False,
                model=self.through.tag_model(),
                pk_set=new_ids,
                using='default',
            )`
3. go to line 435, same solution to the above, add the using positional argument.

## Specifications

  - GeoNode version: 4.2.3
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): docker
  - Platform: Ubuntu 24.04
  - Additional details:

**Comment by HaziqLucii** [comment]
this is what my dataset looks like

![screenshot of dataset](https://github.com/GeoNode/geonode/assets/37583245/42b754a3-5d4a-4608-918a-24b260c65836)

**Comment by HaziqLucii** [comment]
> @HaziqLucii I'm not able to reproduce the error. I've tried with several datasets both locally and on stable demo and the save action for datasets is working fine.
> 
> Do you have some hierarchical keyword assigned to the dataset?

is there something required in the form that i need to fill? and no there's no hierarchical keyword assigned

**Comment by giohappy** [comment]
is this issue still valid @HaziqLucii? I wasn't able to reproduce it with the latest versions of GeoNode

**Comment by HaziqLucii** [comment]
I already solved it by doing that, you can close this issue. I also dont know why I had to add that in the function, but yeah if it works, it works lol.

Thanks again!
