### ISSUE TITLE
Geonode Vanilla installation error

### ISSUE THREAD

**Issue by melanievt** [GeoNode/geonode#12213]
## Steps to Reproduce the Problem
(https://docs.geonode.org/en/master/install/advanced/core/index.html#ubuntu-22-04-lts)
  1. sudo add-apt-repository ppa:ubuntugis/ppa
  2. sudo apt update -y
  3. sudo apt install -y --allow-downgrades build-essential \
        python3-gdal=3.4.1+dfsg-1build4 gdal-bin=3.4.1+dfsg-1build4 libgdal-dev=3.4.1+dfsg-1build4 \
        python3-all-dev python3.10-dev python3.10-venv virtualenvwrapper \
        libxml2 libxml2-dev gettext libmemcached-dev zlib1g-dev \
        libxslt1-dev libjpeg-dev libpng-dev libpq-dev \
        software-properties-common build-essential \
        git unzip gcc zlib1g-dev libgeos-dev libproj-dev \
        sqlite3 spatialite-bin libsqlite3-mod-spatialite libsqlite3-dev

## Error Message
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgdal-dev : Depends: libgdal30 (= 3.4.1+dfsg-1build4) but 3.4.3+dfsg-1~jammy0 is to be installed
E: Unable to correct problems, you have held broken packages.

## Specifications
  - Installation type: Vanilla
  - Installation method: Manual
  - Platform: Ubuntu 22.04.3 LTS

**Comment by mattiagiupponi** [comment]
Can you please try to install without the specific version?

```
sudo apt install -y --allow-downgrades build-essential
python3-gdal gdal-bin libgdal-dev
python3-all-dev python3.10-dev python3.10-venv virtualenvwrapper
libxml2 libxml2-dev gettext libmemcached-dev zlib1g-dev
libxslt1-dev libjpeg-dev libpng-dev libpq-dev
software-properties-common build-essential
git unzip gcc zlib1g-dev libgeos-dev libproj-dev
sqlite3 spatialite-bin libsqlite3-mod-spatialite libsqlite3-dev
```

**Comment by melanievt** [comment]
Thank you very much for the response🙏When I did that, I ended up with the screen below.
![ss1](https://github.com/GeoNode/geonode/assets/75730194/8c25e361-7c0d-4ee5-9038-3116dc624209)
Then I tried to install the missing libraries (python3-gdal, python3-all-dev, …, sqlite3) separately one by one and it worked. I proceeded with the next steps. However, when I ran the line “pip install -r requirements.txt --upgrade” under the “2. Geonode Installation” section (attached below), 
![ss2](https://github.com/GeoNode/geonode/assets/75730194/3f6942e4-d7e8-4cb6-8f55-37a6f4cc6fbe)
I received the following errors on the screen:
![ss3](https://github.com/GeoNode/geonode/assets/75730194/ba8f861f-7cbd-4660-bc83-1162753f8396)
