### ISSUE TITLE
tinymce text area are not visible after the upgrade to v4

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#12229]
## Expected Behavior
tinymce textbox visible

## Actual Behavior
textbox are not visible

## Steps to Reproduce the Problem

  1. open a metadata editor on dev demo
  2. the abstract field is not editable

## Specifications

  - GeoNode version: master
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
This will be closed once the backport to 4.3.x has been completed
