### ISSUE TITLE
django.db.utils.ProgrammingError: relation "monitoring_host" does not exist

### ISSUE THREAD

**Issue by nesangcode** [GeoNode/geonode#12234]
## Expected Behavior
Can start Geonode-UWSGI

## Actual Behavior
In `geonode.log`, showing:
``` bash
Traceback (most recent call last):
File "/home/kraken/.virtualenvs/geonode/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execu>    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "monitoring_host" does not exist
LINE 1: ...oring_host"."ip", "monitoring_host"."active" FROM "monitorin...
```

## Steps to Reproduce the Problem

  1. Follow Geonode Vanilla installation steps till uwsgi setting

## Specifications

  - GeoNode version: 4.2.4
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Ubuntu 22.04
  - Additional details:

**Comment by mattiagiupponi** [comment]
monitoring is deprecated, try to set `MONITORING_ENABLED=False` in the env-file

**Comment by nesangcode** [comment]
Thank you.

**Comment by t-book** [comment]
@mattiagiupponi oh if this is official we should maybe add a warning to https://docs.geonode.org/en/master/basic/settings/index.html#monitoring-enabled ?

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi oh if this is official we should maybe add a warning to https://docs.geonode.org/en/master/basic/settings/index.html#monitoring-enabled ?

Goodpoint, as far as i know is deprecated since 4.2.0, lemme sync with @giohappy in case i'll update the doc

**Comment by jeff-bradley** [comment]
@mattiagiupponi I am in favor of the warning. I was unaware of it being deprecated.
Thanks!
