### ISSUE TITLE
Rename service nginx

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#12249]
One is not forced to use NGINX as proxy server, hence the service name geonode is misleading

https://github.com/GeoNode/geonode/blob/684a1f3572a39b6ab8ba5a6ce7ea4d96fc739c8c/docker-compose.yml#L66-L70

Would it not be clearer that the current django service is namend geonode and nginx something like
geonode-proxy?

**Comment by ridoo** [comment]
Once I was confused about this, too. However, I got used to it now and do not have a strong opinion on renaming both anymore.

**Comment by giohappy** [comment]
Same as @ridoo.
I have also thought about this renaming several times, but then I soon thought to all the renaming that it would imply in terms of docs, etc. and I didn't consider it was worth it! :)

**Comment by t-book** [comment]
You are right @giohappy this would bring some work that for now is definitely not worth it. Maybe somewhere in future. 
Closing here.
