### ISSUE TITLE
Pospone execution of "create_tile_layers" in restore

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#12304]
`create_tile_layers` is now run just after the GeoServer zip is restored, but before the GeoNode restoration.

`create_tile_layers` loops on GeoNode datasets found in the DB, so it needs:
- the GeoNode DB to be populated with the new data
- The resources URLs to be aligned to the destination URL, or the script will update the GWC layers of the source system

**Comment by giohappy** [comment]
For the moment the quick solution is moving the call to `create_tile_layers` after the [migrate_baseurl command](https://github.com/GeoNode/geonode-project/blob/ce5718aae39d5853b19c3801ff965c99156c8be6/src/project_name/br/restore.sh#L75C9-L75C97) inside the restore.sh script of the GeoNode project.

In general, I would move all this logic inside the restore command, along with the base URL migration and the call to `set_all_datasets_metadata`.

**Comment by giohappy** [comment]
PR for GeoNode Project https://github.com/GeoNode/geonode-project/pull/543
