### ISSUE TITLE
GeoNode-Master Instance (https://development.demo.geonode.org/): forgett password button doesnt work

### ISSUE THREAD

**Issue by ffischer1984** [GeoNode/geonode#12318]
## Expected Behavior
receive an e-mail to reset my password from [geonode](https://development.demo.geonode.org/)

## Actual Behavior
got this errormessage on the website
![image](https://github.com/GeoNode/geonode/assets/8037710/c3030418-cc2e-44ba-add2-fa135d8b23f7)

## Steps to Reproduce the Problem

  1. go to the forget password page
  2. enter an valid email-adresse
  3. click on the "reset password" button

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment]
Hi @ffischer1984  the issue is solved
