### ISSUE TITLE
Assets: implement migration for old uploaded files

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#12326]
Continuation of #12124

Some old installations have the uploaded data into `/data`.  
The recent importer stores the uploaded data into `.../STATIC_ROOT/uploaded`, and GeoServer publishes the geotiff from that directory
The final migration to Assets will store the files in `.../STATIC_ROOT/assets`, and GeoServer shall publish the files from there.
In order to clean up such obsolete setups, a migration script could be done that:
- moves the files from `uploaded/` to `assets/` (first checks if all the files are into `uploaded/`)
- updates the `LocalAsset.location` field 
- updates the GeoServer config to point to the new path

Such a migration script should only be run by hand since we do not know if such files are also used for other purposes outside GeoNode, so the admin can choose to run it or not.

**Comment by giohappy** [comment]
@etj I guess that keeping the old files inside the previous location won't break GeoNode and Geoserer, right?

**Comment by etj** [comment]
@giohappy 
Keeping the old files where they are does not break anything, BUT:
- Assets logic manages files completely ONLY when they are within the `assets/` dir: for instance, when an Asset object is removed, the related files are removed only if  they are in the assets/ dir.  If the files are outside such directory, it is assumed that they were created with other means wrt the uploading procedures, so they are outside the "normal" geonode flow. 
- We may want to protect assets file, so that their directory is not exposed directory through NGINX; 
- We may want to serve assets files via `X-Accel-Redirect`, and having them into a brand new assets/ directory can make the work much cleaner.
