### ISSUE TITLE
Unknown command: 'migrate_baseurl'. Did you mean migrate?

### ISSUE THREAD

**Issue by nesangcode** [GeoNode/geonode#12346]
## Expected Behavior
Run smoothly

## Actual Behavior
Not recognize migrate_baseurl

## Steps to Reproduce the Problem

  1. Follow 4.3.0 installation steps till
 ```
 DJANGO_SETTINGS_MODULE=geonode.local_settings python manage.py migrate_baseurl --source-address=http://localhost --target-address=http://address
 ```

## Specifications

  - GeoNode version: 4.3.0
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Ubuntu Server 22.04
  - Additional details:

**Comment by etj** [comment]
You probably missed something in the installation steps.
Try checking the available commands to find out if the geonode commands are properly recognized with:
```bash
DJANGO_SETTINGS_MODULE=geonode.local_settings python manage.py --help
```

**Comment by etj** [comment]
@nesangcode I guess you didn't install GeoNode properly. 
Your latest opened issues all point to the same direction ;)

**Comment by nesangcode** [comment]
the documentation is wrong, `geonode.local_settings` doesn't have migrate_baseurl, `geonode.settings` did.

**Comment by mattiagiupponi** [comment]
If is a matter of doc, feel free to open a PR with the changes here https://github.com/GeoNode/documentation
