### ISSUE TITLE
django.db.utils.OperationalError: no such table: django_site

### ISSUE THREAD

**Issue by nesangcode** [GeoNode/geonode#12345]
## Expected Behavior
Run smoothly

## Actual Behavior
Show errors

## Steps to Reproduce the Problem

  1. Follow Vanilla installation steps till 
```
source .env_local
PYTHONWARNINGS=ignore VIRTUAL_ENV=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=geonode.local_settings GEONODE_ETC=/opt/geonode/geonode GEOSERVER_DATA_DIR=/opt/data/geoserver_data TOMCAT_SERVICE="service tomcat9" APACHE_SERVICE="service nginx" geonode_updateip -p localhost
```

## Specifications

  - GeoNode version: 4.3.0
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Ubuntu Server 22.04
  - Additional details:

**Comment by nesangcode** [comment]
Unknown command: fixsitename

**Comment by nesangcode** [comment]
Available subcommands:

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    optimizemigration
    runserver
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

**Comment by etj** [comment]
It seems that you didn't install geonode in your venv.

**Comment by nesangcode** [comment]
no, that's because the wrong `DJANGO_SETTINGS_MODULE=geonode.local_settings`

it must be `DJANGO_SETTINGS_MODULE=geonode.settings`

**Comment by mattiagiupponi** [comment]
If is a matter of doc, feel free to open a PR with the changes here https://github.com/GeoNode/documentation
