### ISSUE TITLE
Login to GeoServer require to login to GeoNode first

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1235]
It may be related to #677 but it sounds a bit different.
I am using the master branch and I did a paver reset and paver start. When I go to localhost:8080/geoserver and I try to log in with admin admin or any superuser, nothing happens.
If I login first in GeoNode and then I try again, then I am able to get in GeoServer.

**Comment by jj0hns0n** [comment]
@vdeparday @ingenieroariel can we close this. Its only valid in development mode, in which case, the dev should know whats going on.
