### ISSUE TITLE
Assets are denied to anonymous

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#12382]
## Expected Behavior
Anonymous can see 3dtiles and download an asset

## Actual Behavior
Anonymous is blocked

## Steps to Reproduce the Problem

  1. Click here as anonymous https://development.demo.geonode.org/api/v2/assets/294/download
  2. Click here as anonymous https://development.demo.geonode.org/catalogue/#/dataset/3dtiles/663

## Specifications

  - GeoNode version: master
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by allyoucanmap** [comment]
I was trying also with an user not admin the following requests are failing:

- https://development.demo.geonode.org/api/v2/resources/663/permissions
- https://development.demo.geonode.org/api/v2/assets/294/download
- https://development.demo.geonode.org/api/v2/assets/294/link/tileset.json
