### ISSUE TITLE
Download whole asset

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#12412]
**Is your feature request related to a problem? Please describe.**
In some cases, the asset download will download only the main file, but not all the file which the asset is composed of.

**Describe the solution you'd like**
The download link should provide the whole structure

**Describe alternatives you've considered**
Two possibilities comes to my mind:

|descr|pro|cons|
|---|---|---|
| We can let the download endpoint be able to zip the whole folder the first time and then serve it when is required | the file is always available and we dont waste time for the zip | we double the space occupied by the assets which could lead on missing disk space unless we create a routine which will delete the zip archive after some time (can be done as a periodic celery [task](https://github.com/GeoNode/geonode/blob/master/geonode/upload/tasks.py#L33))  |  
| We zip the whole asset structure everytime  | we can save up some disk space since we can delete the file after is served | we waste computing time since we have to zip the file eveytime  |

**Additional context**
I suggest that in both cases we can use the [StreamingHttpResponse ](https://docs.djangoproject.com/en/4.2/ref/request-response/#streaminghttpresponse-objects) and [FileWrapper](https://docs.python.org/3/library/wsgiref.html#wsgiref.util.FileWrapper). Here is a good example on how to implement it https://stackoverflow.com/a/8601118/7597536

cc @etj @giohappy

**Comment by giohappy** [comment]
@mattiagiupponi I would consider configuring the Nginx `X-Accel-Redirect`. This will offload the download to Nginx. You can find many guides online, also for [Django](https://wellfire.co/learn/nginx-django-x-accel-redirects/).

**Comment by mattiagiupponi** [comment]
Anyway I guess we still need to zip the asset first before download it, no? 
Unless ngimx is able to point to a folder instead of a single file.

**Comment by giohappy** [comment]
yes, sure. Let's split the concerns and focus only on the zipping part for the moment.
I would go for the first solution. The worst case is doubling the disk space, but disk space is cheaper than CPU and we can still set up a retention mechanism (as you say) which could also leave outside GeoNode.

**Comment by etj** [comment]
How/where would you store the new zip file? 
Would the new file be considered as a whole new Asset?

**Comment by giohappy** [comment]
I think a solutions like [zipstream-ng](https://github.com/pR0Ps/zipstream-ng) is required to avoid filling up memory.
[This comment](https://stackoverflow.com/a/78602341) from StackOverflow confirms my concern about the way you generate the zip
