### ISSUE TITLE
After upgrade, geoserver-data volume need manual upgrade

### ISSUE THREAD

**Issue by pchevali** [GeoNode/geonode#12422]
Hi,

When doing an upgrade of Geonode, the geoserver-data directory is not updated by the geoserver-data docker image.
The version 4.3 introduced fixes for printing plugin that are present in the geoserver-data  image. But the way geonode uses the geoserver-data volume with the docker compose makes this directory only initialized for the first install. Thus when migrating from 4.x to newer version the geoserver data configs remains unchanged.

What would be the upgrade process ? Copy the whole data directory from the downloaded zip file into the /geoserver_data/data directory ?

If that is safe, the data container could contain a entrypoint to copy the files on start.
This would help also to have git managed changes bundled in a custom docker image

Thanks for your feedbacks

**Comment by giohappy** [comment]
@pchevali you're right, this is a limitation but any solution could be tricky because the risk is to have conflicts between the two data directories. You would need a mechanism that marks conflicts and lets the user manage them.

**Comment by ridoo** [comment]
@giohappy it would be good to have the directory in version control and just overwrite the binaries folder (i.e. WEB-INF/libs). That way, one would have the opportunity to compare changes and see the differences. In a docker compose setup, an overlayed volume would indeed give you the chance to have both a working copy, to make your own changes and merge upstream changes.

**Comment by t-book** [comment]
I normally diff my working data dir with the one that is in used with the new geonode version before every upgrade. And integrate changes. Not perfect but working for years … automation would be great!

**Comment by pchevali** [comment]
I have just seen that there is a similar discussion [here](https://github.com/GeoNode/geonode-docker/issues/38)

Thanks for your input
