### ISSUE TITLE
Uncomment Build Lines in docker-compose.yml to Enable Build Process

### ISSUE THREAD

**Issue by VasconcelosJoao** [GeoNode/geonode#12433]
**Is your feature request related to a problem? Please describe.**  
I encountered an issue in GeoNode versions 4.3.x where the `docker-compose.yml` file does not execute the build process because the build lines are commented out. This has caused frustration as I am unable to set up the GeoNode environment properly. My tests were conducted on a completely fresh VM running Ubuntu 24.04 Server (minimal installation) behind a government proxy.

**Describe the solution you'd like**  
I would like to propose two potential solutions:
1. Uncomment the build lines in the `docker-compose.yml` file for GeoNode versions 4.3.x. This change would allow the build process to execute correctly, ensuring that users can set up their environments without facing the current limitations.
2. Modify the `create-envfile.py` script to include an option that allows users to uncomment the relevant lines in the `docker-compose.yml` file during execution. This would provide a more automated approach for users, especially in environments where manual edits may lead to errors.

**Describe alternatives you've considered**  
An alternative solution would be to provide detailed documentation or comments within the `docker-compose.yml` file explaining how to manually enable the build lines. However, this would still require users to modify the file themselves, which could lead to inconsistencies.

**Additional context**  
Uncommenting the build lines in the `docker-compose.yml` file for GeoNode versions 4.3.x would significantly improve the user experience, especially for those setting up GeoNode for the first time. It would also help in environments where users are working with minimal installations and behind proxies, as they would not have to troubleshoot additional configuration issues.

**Comment by mattiagiupponi** [comment]
PR to uncomment the rows are merged
