### ISSUE TITLE
geonode 4.2.x branch - geonode-importer  issue on requirements file

### ISSUE THREAD

**Issue by lordakarias** [GeoNode/geonode#12440]
The manual installation guide for [GeoNode Vanilla](https://docs.geonode.org/en/master/install/advanced/core/index.html#update-the-settings-in-order-to-update-geonode-and-geoserver-services-running-on-a-public-ip-or-hostname) recommends cloning the repository with the -b 4.2.x option. However, the requirements.txt file in this branch references the master branch of the geonode-importer repository:

bash
Copy code
-e git+https://github.com/GeoNode/geonode-importer.git@master#egg=geonode-importer
This reference points to an assets directory that is not present in the 4.2.x branch.

**Comment by mattiagiupponi** [comment]
Hi @lordakarias 
For geonode 4.2.x please use `geonode-importer==1.0.9` as a requirements. If the doc points out to the master branch, feel free to send a PR with the updated doc.
