### ISSUE TITLE
How to customize geonode index.html

### ISSUE THREAD

**Issue by nigrumdiaster** [GeoNode/geonode#12500]
{# index.html is implemented by the external client #}
i want to fully custom index.html, not just only a bit like in [doc](https://docs.geonode.org/en/master/basic/theme/index.html), like changing menu into my own template. 
I tried changing base.html but it didn't work. How to fully custom index.html without causing any conflicts?

**Comment by cesarbenjamindotnet** [comment]
you can do that with https://github.com/GeoNode/geonode-mapstore-client, geonode is mainly for management and api exposure; but the frontend is handle by mapstore-client; that way is very painful, is not so friendly to change many stuff; you chan see that you can change a lot if you change it on your own custom mapstore client like this example (mod by me): https://mide.monterrey.gob.mx.

Unfortunely, not all the ui aspects are django template related, many things are React Components so maybe you have to rebuild the React SPA too... Unforunely (again) the React stuff are a bit aged and many Components comes from Mapstore, so, you can't edit it directly ( https://github.com/geosolutions-it/MapStore2/ )

**Comment by nigrumdiaster** [comment]
> you can do that with https://github.com/GeoNode/geonode-mapstore-client, geonode is mainly for management and api exposure; but the frontend is handle by mapstore-client; that way is very painful, is not so friendly to change many stuff; you chan see that you can change a lot if you change it on your own custom mapstore client like this example (mod by me): https://mide.monterrey.gob.mx.
> 
> Unfortunely, not all the ui aspects are django template related, many things are React Components so maybe you have to rebuild the React SPA too... Unforunely (again) the React stuff are a bit aged and many Components comes from Mapstore, so, you can't edit it directly ( https://github.com/geosolutions-it/MapStore2/ )

Yeah, i also tried a lot to custom it, but styling template is just too hard, maybe i should give up this approach.
