### ISSUE TITLE
Issue: GeoNode Account Registration

### ISSUE THREAD

**Issue by cartopher** [GeoNode/geonode#12514]
I am having an issue verifying my account. I received the email requesting to confirm my email, but the verification link is broken, directing me to a "Bad Gateway" page.

For reference, please view the attached screenshots.

Assistance in rectifying this issue would be greatly appreciated!

[image](https://github.com/user-attachments/assets/079fce30-fe68-4db0-82e2-75a79fa64e1f)

[image](https://github.com/user-attachments/assets/5a91d73d-f39d-47db-bd66-317b9dc656da)

**Comment by giohappy** [comment]
@cartopher where are you trying to verify your account? An instance of your own? A public instance?

**Comment by giohappy** [comment]
A user reported the same problem on stable demo. It's been fixed.
