### ISSUE TITLE
Failed Upload Dataset to geonode

### ISSUE THREAD

**Issue by ahamidplg** [GeoNode/geonode#12521]
I'am using geonode  4.2.5, when I upload dataset type ESRI (shp, prj, shx, dbf) failed and show "the upload process failed please check the validity of the file and try upload again". I have find on log the error but not showing in the log

![geonodeissue](https://github.com/user-attachments/assets/350fb12a-6a6e-4035-988c-13fb163b3379)

**Comment by giohappy** [comment]
@ahamidplg please don't use issues to ask questions. I invite you to use the geonode-users or the goenode-dev mailing lists for this. You can find more info [here](https://geonode.org/communication/#mailing-lists)
