### ISSUE TITLE
Icon rule image url not working in WMS

### ISSUE THREAD

**Issue by ahmadzfaiz** [GeoNode/geonode#12528]
## Expected Behavior
- Showing point icon images in the map view

## Actual Behavior
- Showing grey boxes in the map view

## Steps to Reproduce the Problem

  1. I upload vector dataset into Stable GeoNode Demo. Here's the link https://stable.demo.geonode.org/catalogue/#/dataset/10809
  2. I change the Style using Icon Rule
  3. I fill the image url with this link https://stable.demo.geonode.org/documents/10811/link
  4. The icon is showing in the sidebar, but not in the map view
  5. I tried it in the stable demo because I already did this in my own geonode installation and didn't work too
  6. I also tried in https://development.demo.geonode.org/ and didn't works

## Specifications

  - GeoNode version: 4.3.1
  - Installation type (vanilla, geonode-project): geonode-project
  - Installation method (manual, docker): docker
  - Platform: Ubuntu LTS 22.04
  - Additional details:
<img width="1511" alt="Screenshot 2024-08-28 at 11 05 40" src="https://github.com/user-attachments/assets/92b25e6a-4124-43a7-ac9b-9e6bec7a9cd5">

**Comment by ahmadzfaiz** [comment]
I believe this issue happen in GeoServer side. When I use external URL link, it can't read the image
![Screenshot 2024-08-28 at 11 26 27](https://github.com/user-attachments/assets/44467592-347c-4c17-901f-b19dde48ffc6)

But if I use local image uploaded directly from GeoServer, it works
![Screenshot 2024-08-28 at 11 27 16](https://github.com/user-attachments/assets/8bb693de-0822-4fb1-83ba-48fbfa4df4d5)

**Comment by ahmadzfaiz** [comment]
Here my .env config related to geoserver in my geonode docker installation
<img width="966" alt="Screenshot 2024-08-28 at 11 33 30" src="https://github.com/user-attachments/assets/5d2db4a6-6d20-4de0-b37d-60faec11ed61">
<img width="761" alt="Screenshot 2024-08-28 at 11 34 48" src="https://github.com/user-attachments/assets/4a236cd7-63bc-4c89-8744-328722ef1f5b">


am I missing something?

**Comment by kikislater** [comment]
URL Checks are enabled in Geoserver but not configured ...

**Comment by ahmadzfaiz** [comment]
ah okay, I didn't realize there is a URL checks in the latest version of geoserver. I use version 2.20 in the past and URL check is not available yet. Thanks @kikislater

**Comment by kikislater** [comment]
No problem, I think it can still be issue as it doesn't seem to be the expected behaviour !

**Comment by kikislater** [comment]
Btw it is modified on stable demo geonode.
@giohappy  Could you please update if ti was the issue ?
