### ISSUE TITLE
Returned 400 when upload dataset

### ISSUE THREAD

**Issue by nesangcode** [GeoNode/geonode#12569]
## Expected Behavior
Upload success

## Actual Behavior
Upload fail

## Steps to Reproduce the Problem

  1. follow the installation steps
  2. Install geoNode on VM at http://10.x.x.x
  3. Do apache2 ProxyPass & ProxyPassReverse at http://10.x.x.x

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): manual
  - Platform: Ubuntu Server 22.04
  - Additional details:

**Comment by mattiagiupponi** [comment]
please attach at least the geonode and celery logs
