### ISSUE TITLE
Installation error (Invalid distribution name or version syntax: -project_name--4.0.0)

### ISSUE THREAD

**Issue by DO1JLR** [GeoNode/geonode#12617]
Hi there :wave: 
I followed the instructions at [https://docs.geonode.org/en/master/install/basic/index.html](https://docs.geonode.org/en/master/install/basic/index.html) to install geonode, but sadly the ``docker compose build``

## Expected Behavior

Geonode Basic installation works as described at docs.geonode.org and n the Repository README

## Actual Behavior

``docker compose build`` failed after 765s

<details>
  <summary>See log...</summary>
<code>
764.7 Obtaining file:///usr/src/%7B%7Bproject_name%7D%7D
764.7   Preparing metadata (setup.py): started
765.0   Preparing metadata (setup.py): finished with status 'error'
765.0   error: subprocess-exited-with-error
765.0   
765.0   × python setup.py egg_info did not run successfully.
765.0   │ exit code: 1
765.0   ╰─> [1 lines of output]
765.0       error: Invalid distribution name or version syntax: -project_name--4.0.0
765.0       [end of output]
765.0   
765.0   note: This error originates from a subprocess, and is likely not a problem with pip.
765.0 error: metadata-generation-failed
765.0 
765.0 × Encountered error while generating package metadata.
765.0 ╰─> See above for output.
765.0 
765.0 note: This is an issue with the package mentioned above, not pip.
765.0 hint: See above for details.
765.0 
765.0 [notice] A new release of pip is available: 24.1.2 -> 24.2
765.0 [notice] To update, run: python3 -m pip install --upgrade pip
------
failed to solve: process "/bin/sh -c yes w | pip install --src /usr/src -r requirements.txt &&    yes w | pip install -e ." did not complete successfully: exit code: 1
</code>
</details>

## Steps to Reproduce the Problem

  1. Follow [the instructions](https://docs.geonode.org/en/master/install/basic/index.html) to install requirements and venv
  2. Run ``python3 create-envfile.py --hostname $(hostname)``
  3. Open .env and replace ``{{project_name}}`` with ``my_geonode``
  4. Run ``docker compose build``

## Specifications

  - GeoNode version: 4.3.1
  - Installation type: https://docs.geonode.org/en/master/install/basic/index.html
  - Installation method: docker
  - Platform: Ubuntu 22.04.5 LTS

**Comment by mattiagiupponi** [comment]
can you please share the .env file? so i can test directly ur file

**Comment by DO1JLR** [comment]
thanks @mattiagiupponi 

Following the installation for [geonode-project](https://github.com/GeoNode/geonode-project?tab=readme-ov-file#quick-docker-start) did it.
