### ISSUE TITLE
Time-series Chart unavailable on Geonode 4

### ISSUE THREAD

**Issue by obediobadiah** [GeoNode/geonode#12625]
## Expected Behavior
I expect to view and set the Time-Series Chart on Geonode 4 like on Geonode 3, When I'm editing the Dataset Metadata. Like in the screeshoot below:
![Screenshot 2024-09-30 at 11 33 51 in the morning](https://github.com/user-attachments/assets/0cf57d7f-3ec9-4ec0-bfdf-6a37e3352687)
![Screenshot 2024-09-30 at 11 34 11 in the morning](https://github.com/user-attachments/assets/f1555eed-0f9c-48e1-8b85-b9cf18137fec)

## Actual Behavior
In the new Geonode 4 the Time-Series Chart is no longer available when editing the metadata.

## Steps to Reproduce the Problem

  1. View the Dataset
  2. Under Edit dropdown click on Edit Metadata
  3. Click on Dataset Attribute

## Specifications

  - GeoNode version:
  - Installation type (vanilla, geonode-project):
  - Installation method (manual, docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@obediobadiah this functionality hasn't been ported to GeoNode 4. I invite you to reformulate the issue as a Feature request rather than a bug. I'm going to close it meanwhile.
