### ISSUE TITLE
Column Labels Not Displayed in Map View

### ISSUE THREAD

**Issue by geogeek11** [GeoNode/geonode#12681]
While the columns labels are well displayed on the dataset view.

If the same dataset is added into a map neither of the labels is displayed on the attributes table or in the filter composer.

## Steps to Reproduce the Problem

  1. Add a label to a column of a dataset.
  2. Add the dataset to map and check the attributes table.

## Specifications

  - GeoNode version: 4.3.1
  - Installation type (vanilla, geonode-project): vanilla
  - Installation method (manual, docker): docker
  - Platform:
  - Additional details:

**Comment by RodRRC** [comment]
I have the same problem, did you manage to solve it?

**Comment by geogeek11** [comment]
This is issue is fixed in the Latest version 4.4.0, I have made an upgrade
