### ISSUE TITLE
QGIS failing to commit editing changes to Geonode WFS-T

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1275]
I just did some testing (current master version) with different permission settings either with 'Any registered user' or with 'Only the following users or groups' with a local GeoNode and using the admin user in QGIS in the WFS-T dialog and I was never able to commit changes I always got an error along those lines:

```
Could not commit changes to layer geonode:hti_boundaries_communes_adm2_cnigs_polygon

Errors: ERROR: 1 geometries not changed.

  Provider errors:
      WFS service exception:
          {http://www.geonode.org/}hti_boundaries_communes_adm2_cnigs_polygon is read-only
```

I also did some testing with a vanilla geoserver: 2.4.2 binary: http://sourceforge.net/projects/geoserver/files/GeoServer/2.4.2/geoserver-2.4.2-bin.zip/download
I connected with QGIS through WFS without even putting credentials and I was able to edit and save changes back to the layer sf:roads (demo dataset shipped with GeoServer)
I also tried to load the same layer in GeoNode with a datastore type shapefile and it was still not working in GeoNode so it doesn't look like it is the datastore type the issue but it does seem like the issue lies within GeoNode.

(see recent thread on geonode-dev, can't hyperlink as the mailing list archives are currently not available)

Credits to Salvador Bayarri for the initial report on the mailing.

**Comment by jj0hns0n** [comment]
@afabiani can you guys look at this at some point? It may just go away with the new authentication work. Moving to 2.7

**Comment by afabiani** [comment]
Just tested using latest GeoNode 2.5 and GeoServer 2.9

It works both using shapefile or PostGis based layers

![image](https://cloud.githubusercontent.com/assets/1278021/17888722/9cca3284-692c-11e6-8735-f1a0478f2a37.png)


![image](https://cloud.githubusercontent.com/assets/1278021/17888753/bff3fccc-692c-11e6-9faf-757a3efef507.png)

**Comment by Japhetho** [comment]
I'm still experiencing this issue despite using SPC Geonode 3.0 that I installed with docker. I am able to access the layers from Geonode as WFS and view them in QGIS. However whenever I edit any of the layers and save, QGIS throws a "Could not commit changes to layer, WFS service exception: java.lang.NullPointerException". 
In Geoserver logs, the error is `java.lang.NullPointerException
	at org.geoserver.wfs.Transaction.getDatastoreTransaction(Transaction.java:535)
	at org.geoserver.wfs.Transaction.execute(Transaction.java:138)
	at org.geoserver.wfs.Transaction.transaction(Transaction.java:92)
	... 117 more`
I've googled for solutions for three days now and none of the suggested solutions seems to work. Any assistance will be highly appreciated.

**Comment by t-book** [comment]
@Japhetho can you somehow capture the payload when saving the wfs? doing so you could try to replicate the issue with a simple curl request and gather more information. Further, can you could provide some test data (shp)?

**Comment by Japhetho** [comment]
@t-book The shapefile I've been trying to edit and save is
[nairobi_points.zip](https://github.com/GeoNode/geonode/files/4254576/nairobi_points.zip)

**Comment by bszady** [comment]
I have the samy problem, any indications?

**Comment by Japhetho** [comment]
@bszady A temporary solution would be, if you're using Geoserver 2.16.2, downgrade it to version 2.15.4 and then try editing the later again. That's how I solved the issue temporarily when I had a similar problem.

**Comment by bszady** [comment]
@Japhetho thansk a lot, I will try... I have tried to change roles in  service wfs.transactions in geoserver. Without results....

**Comment by gannebamm** [comment]
If this is still an open issue @bszady @Japhetho could you please open a new ticket with a description how to reproduce it?

Thanks, we will close this now.
