### ISSUE TITLE
Document SITENAME, SITE_NAME and fixsitename

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1295]
I was trying to set-up the site name in the settings.py or local_settings.py so that is would be picked up by the templates and it was quite confusing as it would not work and the site name would not get picked up. After talking with @simod , I understand the workflow may be:
to use SITENAME in local_settings.py
run python manage.py fixsitename
and then SITE_NAME in the template

I think a note should be added in the settings.py to mention that?
we should document that and maybe make it simpler?

I can do it but I want to make sure I understand how it is meant to work.

**Comment by jj0hns0n** [comment]
@vdeparday Im removing the bug label. Happy to look over this with you this week so we can close it.
