### ISSUE TITLE
Email-based auto-registration from map/layer permissions form

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#130]
On the map/layer permissions form, allow email addresses as well as usernames to be entered in the 'Add User' text field.  If the email address is not yet in the system, generate a new account with a random password and send the login info to the email address.  (Port from worldmap to geonode).

**Comment by jj0hns0n** [comment]
Im pretty sure I did some work to port this code against master. See here https://github.com/jj0hns0n/geonode/tree/create_new_user_from_email ... Ill see if I can get this merged.
