### ISSUE TITLE
Layer feature not queriable on geonode 2.0c5

### ISSUE THREAD

**Issue by kettyadoch** [GeoNode/geonode#1307]
In Geonode 2.0c5, a layer feature cannot be queried if the column names have spaces. Geonode 1.x knew how to handle column names with spaces in them.

It would be great if Geonode 2.x can handle column names with spaces or special characters.

**Comment by jj0hns0n** [comment]
We should verify if this is still an issue.

**Comment by jj0hns0n** [comment]
This is still an issue. The interface just stays stuck with the "Querying" popup.

![geoexplorer_-_example_com_and_geonode_ _ubuntu_ip-10-63-64-228____geonode_ _bash_ _199x48_and_qgis](https://cloud.githubusercontent.com/assets/506078/6019859/7c9dbee0-aba5-11e4-88c5-cc1ea6378751.png)

Looks like the error from geoserver is as follows.

<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:8080/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>org.w3c.dom.DOMException: INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. 
INVALID_CHARACTER_ERR: An invalid or illegal XML character is specified. </ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

With the following request payload.

<wfs:GetFeature xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0" maxFeatures="50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Query typeName="feature:san_andres_y_providencia_location" srsName="EPSG:900913" xmlns:feature="http://www.geonode.org/"><ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:BBOX><ogc:PropertyName>the_geom</ogc:PropertyName><gml:Envelope xmlns:gml="http://www.opengis.net/gml" srsName="EPSG:900913"><gml:lowerCorner>-9226720.7681134 1368729.2552091</gml:lowerCorner><gml:upperCorner>-8942375.0229322 1500812.4400675</gml:upperCorner></gml:Envelope></ogc:BBOX></ogc:Filter></wfs:Query></wfs:GetFeature>

@bartvde any ideas on this one?

**Comment by bartvde** [comment]
The XML request does not validate but not sure why:

```
E [Xerces] cvc-pattern-valid: Value 'feature:san_andres_y_providencia_location' is not facet-valid with respect to pattern '((\w:)?\w(=\w)?){1,}' for type 'TypeNameListType'.
```

**Comment by bartvde** [comment]
it seems underscores are not allowed at all?

**Comment by bartvde** [comment]
yes as soon as you use an underscore, the XML request is invalid. Nothing much the client can do about this. I think this should be handled on validation of layer names in GeoServer instead? Or wherever you can intervene in GeoNode before the stuff gets published to GeoServer.

**Comment by jj0hns0n** [comment]
Its actually the spaces that cause problems and not the underscores.
@ingenieroariel, do you have any ideas on how we could sanitize field names
before uploading to geoserver.

**Comment by ischneider** [comment]
Minor adjustment:

> if field name starts with a number, replace it with a "_"

If field name starts with a number, *prepend* '_'

In my experience, postgres/geoserver handles SQL names by escaping or quoting but there are potential edge cases.

Here is the existing (simple) implementation:

https://github.com/GeoNode/geonode/blob/master/geonode/upload/files.py#L142

**Comment by capooti** [comment]
yes I meant that, prepend to it, sorry
I will use your implementation, thanks

On Tue, Feb 3, 2015 at 6:21 PM, Ian Schneider <notifications@github.com>
wrote:

> Minor adjustment:
>
> if field name starts with a number, replace it with a "_"
>
> If field name starts with a number, *prepend* '_'
>
> In my experience, postgres/geoserver handles SQL names by escaping or
> quoting but there are potential edge cases.
>
> Here is the existing (simple) implementation:
>
> https://github.com/GeoNode/geonode/blob/master/geonode/upload/files.py#L142
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1307#issuecomment-72693346>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by capooti** [comment]
I need #2019 to be fixed before going to this.
Approach would be to check the layer and return an error in get_base_file in layers/models when finding column with bad names
