### ISSUE TITLE
Repeat WMS download links are possible if updatelayers is called on a layer whose bounding box has changed in GeoServer

### ISSUE THREAD

**Issue by mwengren** [GeoNode/geonode#1317]
Congrats on the upcoming release! 

Maybe this can be added in 2.0.1, but there is an issue in layers/models.py where if the updatelayers command is called repeatedly, via cron or otherwise, on a layer whose bounding box has changed within GeoServer, multiple repeated download links will be added to the base_link table for the WMS types: JPEG, PDF and PNG for the layer.  This is because the bounding box params are encoded within the URLs for these types, and the URL is used as a query parameter to get_or_create here:
```
Link.objects.get_or_create(resource= instance.resourcebase_ptr,
                        url=wms_url,
                        defaults=dict(
                            extension=ext,
                            name=name,
                            mime=mime,
                            link_type='image',
                           )
                        )
```
If the wms_url value differs from what's already in the database, it is treated as a new record by Django and added.  If the 'name' field is used instead a query param instead of a default, only one link records will be created per 'name' value:
```
Link.objects.get_or_create(resource= instance.resourcebase_ptr,
                        name=ugettext(name),
                        defaults=dict(
                            extension=ext,
                            url=wms_url,
                            mime=mime,
                            link_type='image',
                           )
                        )
```

The result can look like the download links here: 

http://54.221.223.46/layers/cpc:precip_outlook_eight_to_fourteen_day

**Comment by jj0hns0n** [comment]
@mwengren has this been resolved? I think the right approach may be to just forcibly remove all the existing links before saving?

**Comment by mwengren** [comment]
@jj0hns0n oops, thought this was closed by my earlier commit.  Closing now, resolved.
