### ISSUE TITLE
Zipped file upload does not work

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1319]
This is with the GeoServer REST upload:

1. Upload a zip file containing a shapefile (demolayer.shp, demolayer.dbf, etc)
2. After completion, try uploading the same zipfile again, or a renamed zipfile with the same contents:

>GeoNode encountered problems when creating layer demolayer_1.It cannot find the Layer that matches this Workspace.try renaming your files.

Possible solution: create a new zipfile,  rename and copy over the contents of the old zipfile (demolayer.shp -> demolayer_1.shp, etc), and send the new zipfile to Geoserver for importing.  I can create a PR for this quickly if it's an acceptable fix.

**Comment by ingenieroariel** [comment]
We should support zip files. This would be a blocker.

**Comment by capooti** [comment]
This is working for me, I have just tested it with standard settings.
