### ISSUE TITLE
Use autocomplete and tokenization for keywords in the metadata form

### ISSUE THREAD

**Issue by TimTensen** [GeoNode/geonode#1325]
In the meta-data form you now have to choose the keywords yourself without any guidance. It would be more useful that a list of standard keywords is implemented in a way that when you start typing, the keyword that matches your text will show up. 

The chosen plugin: <optgroup> support, multiple group will do this http://harvesthq.github.io/chosen/

Besides, when someone wants to add a new keyword, he should not be restricted to the list.

**Comment by jj0hns0n** [comment]
We can hook up autocomplete and tokenizing here. I've add it it in a few other places already.
