### ISSUE TITLE
Document mobile use cases.

### ISSUE THREAD

**Issue by garnertb** [GeoNode/geonode#1328]
During the GeoNode 2014 summit several organizations have expressed interest in integrating mobile applications with GeoNode.  We have decided that there is currently no work that needs to be done in GeoNode to support this, but it would be good to document what work has been done in this area.
- Add documentation on the different options
- @garnertb - Work done in the ROGUE project.
- @simod - Previous work done with FormHub.

**Comment by jj0hns0n** [comment]
Note that geonode is now largely responsive on its own. Adding responsive tag for future issues.
