### ISSUE TITLE
GNIP - Abstract Map Framework UI

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1331]
Needs for the new mapping interface:
- Have better styling options in GeoNode (Infographics, Piecharts, automatic choropleth maps…)
  - SldService geoserver community module for choropleth maps?
  - standard or pluggable charts API?
- More interactive popups
- Maps and layers fully accessible from mobile devices

Available implementations
- GEM’s Leaflet + D3 experiments
- Mapstory’s design mockups
- ROGUE’s Angular + OL3
- Worldmap’s customized GeoExt

What is needed to allow abstraction from the mapping interface 
- Stable Map API
- Abstractions for GeoServer, SLD, Tiles/WMS/TMS.
- Tiles, Raw data, Companion services (GetInfo, UTF8-Grid) do we need to abstract this too?
- Be Agnostic

**Comment by jj0hns0n** [comment]
Its now possible to use maploom in geonode. Its partially an iframe 'hack' but it is very possible to use it by adding the django app and overriding a few templates. We should document this in the mainline docs and have a broader discussion about map clients going forward cc @garnertb

**Comment by jj0hns0n** [comment]
Also, I'd like to turn this into a more formal GNIP see https://github.com/GeoNode/geonode/issues/1915

**Comment by simod** [comment]
Overview
=======

We discussed this during the code sprint in Venice firstly by taking a look at the available solutions out there:

GeoExplorer
----------------
Based on Ext and OL2 is the current mapping client which is GeoNode is using since the beginning.

MapStore
------------
Created by GeoSolutions is based on a maintained and updated version of geoexplorer with many plugins

Maploom
------------
Based on Angularjs and OL2 is Geogig enabled, is missing the styling tool

Geoadmin.ch
-----------------
Based on Angularjs and OL3, is missing the styling tool and the editing tool

Cartodb client
------------------
Is based on Backbone and Leaflet

MapBox client
-------------------
Based on Leaflet.

Proposal:
=======
The mapping client should be independent from geonode and easily swappable.
One option could be to present a more gis featured mapping interface for users that need to work on the map and another lighter and simpler for users that just want to view the data.

**Comment by rajanski** [comment]
I would propose to add HeronMC to the list of possible Mapclients. It is based on OL3 and GeoExt. Also see http://lib.heron-mc.org/heron/latest/examples/querybuilder/

**Comment by vlasvlasvlas** [comment]
this:
'The mapping client should be independent from geonode and easily swappable.'

**Comment by rajanski** [comment]
One more argument: GeoExplorer doesnt work very well with mobile devices. Just tested on a tablet. No zooming etc...

**Comment by rajanski** [comment]
I have been looking through the alternative mapping clients again. To me, it seems that [geoadmin.ch](https://github.com/geoadmin/mf-geoadmin3) is among the most actively maintained and most long-term sustainable, as they use OL3 and angular..

**Comment by vlasvlasvlas** [comment]
Would LOVE to see the geoadmin.ch GUI as a geonode's mapping client

**Comment by JJediny** [comment]
Two more Map Clients that would be "pluggable" to geonode with an mappable api:

http://terria.io/
https://github.com/JJediny/nationalmap
&
https://github.com/JJediny/Leaflet.Storage
https://github.com/JJediny/django-leaflet-storage
https://nepanode.hackpad.com/NEPAnodes-GeoJSON-Editor-1R1PRnbCvnB

The first one has some ongoing work that could be leveraged for an api...

http://terria.io/DataSourceEditor/
https://github.com/TerriaJS/DataSourceEditor

Think there just needs to be an assignment of where we draw the line at "saving" the map... think the OGC Web Map Context is too much and that styling per layer or more granular attributes/configurations should be limited to:

A JSON Snapshot similar to the `data` json currently sent from GeoExplorer:
https://gist.github.com/JJediny/6ae4973dc5334340788b

Here is how the Leaflet-Storage manages map config:
http://nepanode.anl.gov/geojson/api/geojson/

But far less complicated focusing on the description and state of the `map` (name/abstract/zoom/extent/etc) with nested `layers` as a URL and Datatype/format... but making sure we arent limiting the practical use - thats why it'd be good to document all the approaches taken thus far by other projects and frameworks...

**Comment by jj0hns0n** [comment]
@bartvde @ahocevar lets talk about this during FOSS4G in the context of the new websdk

**Comment by jj0hns0n** [comment]
@bartvde @milafrerichs we now have 3 implementations that use the gxp based map format. Think it could be time to better document this and work toward a _next_ map format now that we support the _old_ format even in the newest client.

@timlinux would like your input here to wrt to qgis project files as a similar construct.

**Comment by capooti** [comment]
I agree with @jj0hns0n that the next map format should support the old format. It would be nice if users could decide which client to use for a specific map. And definitely this would help migrations of existing instances.

**Comment by jj0hns0n** [comment]
@capooti I think that we can now move on from the old gxp format as  long as the new viewers still support it.
