### ISSUE TITLE
Test GeoNode works well in 12.04 and 14.04

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1332]
It would be great to have it working for other versions too, but those two are the most important.

**Comment by arifin89nayan** [comment]
http://127.0.0.1/layers/upload
upload tif file to layer error occur and show  "Profile matching query does not exist."

**Comment by arifin89nayan** [comment]
shape file upload layer show this error
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.
Apache/2.4.7 (Ubuntu) Server at 127.0.0.1 Port 80

**Comment by arifin89nayan** [comment]
log file 
[Thu Jan 21 04:39:56.150895 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     bit = self.render_node(node, context)
[Thu Jan 21 04:39:56.150904 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[Thu Jan 21 04:39:56.150917 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     return node.render(context)
[Thu Jan 21 04:39:56.150927 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 155, in render
[Thu Jan 21 04:39:56.150941 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     return self.render_template(self.template, context)
[Thu Jan 21 04:39:56.150950 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 137, in render_template
[Thu Jan 21 04:39:56.150969 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     output = template.render(context)
[Thu Jan 21 04:39:56.150978 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
[Thu Jan 21 04:39:56.150992 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     return self._render(context)
[Thu Jan 21 04:39:56.151001 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
[Thu Jan 21 04:39:56.151014 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     return self.nodelist.render(context)
[Thu Jan 21 04:39:56.151023 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
[Thu Jan 21 04:39:56.151036 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     bit = self.render_node(node, context)
[Thu Jan 21 04:39:56.151045 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[Thu Jan 21 04:39:56.151058 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     return node.render(context)
[Thu Jan 21 04:39:56.151068 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/announcements/templatetags/announcements_tags.py", line 24, in render
[Thu Jan 21 04:39:56.151083 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     request = context["request"]
[Thu Jan 21 04:39:56.151092 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 56, in __getitem__
[Thu Jan 21 04:39:56.151106 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697]     raise KeyError(key)
[Thu Jan 21 04:39:56.151121 2016] [:error] [pid 15206:tid 139850801768192] [remote 127.0.0.1:44697] KeyError: 'request'
