### ISSUE TITLE
Metadata author: modal box glitch

### ISSUE THREAD

**Issue by brylie** [GeoNode/geonode#1371]
On the Edit Metadata page, when I select **Person outside GeoNode (fill form)** for the metadata author, the form fields spill out of the modal container>
![geonode-metadataauthor-modalboxglitch](https://f.cloud.github.com/assets/17307/2189168/89f40920-9812-11e3-8a72-31b9c653941f.png)

I get this error on Firefox 27. The form renders fine on Chrome 32.0.1700.77.

**Comment by simod** [comment]
bumping to 2.5 as we don't have the external actor in 2.4.

**Comment by jj0hns0n** [comment]
@simod can we look at this this week?

**Comment by jj0hns0n** [comment]
We no longer use this modal. Closing
