### ISSUE TITLE
Layer Link Generation should not also retrieve getCoverage/getFeature/getMap

### ISSUE THREAD

**Issue by benjwadams** [GeoNode/geonode#1376]
Right now WMS/WFS/WCS links are generated by opening a url as a network object (ultimately via urllib.urlopen) and then returning the url from this object.  This means we are returning an entire map, coverage, or feature set just to generate the URL text.  For larger coverages, for example, this can be quite slow, and since all the links are generated first before they are saved to the layer model, they sometimes take a while to show up on the download links.

  The code for generating the url string is tucked inside each of the OWSLib methods, so you can't get the original URL them without returning the entire object.  The requests could be generated manually, or perhaps the url string generating portions could be broken off into a separate function within OWSLib and then called from GeoNode.

**Comment by jj0hns0n** [comment]
@tomkralidis is this something you could look at?

**Comment by tomkralidis** [comment]
@benjwadams can you point to an example or code? I'm unclear where this is actually happening.

**Comment by jj0hns0n** [comment]
@benjwadams looks like you fixed this yourself? Going to go ahead and close.

https://github.com/GeoNode/geonode/commit/a37ccd7562f12324fb1a7d164dfff571c8566962
