### ISSUE TITLE
Toggling the navigation does not add/remove the .hide class

### ISSUE THREAD

**Issue by batje** [GeoNode/geonode#1377]
When the navigation headers on the layers page are clicked, the sub-navigation is shown by a function called .slideUp().
That function does not remove the 'hide' class from the parent element.

Other bootstrap themes than the default one, actually hide elements with the .hide class.

When I added the lines

$(this).parents("h2").siblings(".nav").addClass('hide');
and
$(this).parents("h2").siblings(".nav").removeClass('hide');

in the right places, things work, but the lovely sliding effect gets lost, so needs work.

**Comment by simod** [comment]
I'm closing this one as in #1965 there are some more details
