### ISSUE TITLE
Allow abstract to be expanded by default or on click

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1381]
By default the info panel for layers, doesn't show full abstract, so it requires to download the metadata to see the full abstract. It would be better to not truncate it (see below) or to make it expandale

--- a/geonode/base/templates/base/resourcebase_info_panel.html
+++ b/geonode/base/templates/base/resourcebase_info_panel.html
@@ -12,7 +12,7 @@
   {% if resourcebase.abstract %}
     <li>
       <strong>{% trans "Abstract" %}:</strong>
-      {{ resourcebase.abstract|escape|urlize|linebreaks|safe|truncatechars:160 }}
+     {{ resourcebase.abstract|escape|urlize|linebreaks|safe }}
     </li>
   {% endif %}

**Comment by pjdufour** [comment]
Related to #2169

**Comment by jj0hns0n** [comment]
closing this as we can now get to the full metadata in the browser
