### ISSUE TITLE
Installing on Windows 7

### ISSUE THREAD

**Issue by mixedbredie** [GeoNode/geonode#1383]
These are my notes on installing Geonode on a Windows 7 32bit machine.  Geonode works but not the embedded Geoserver runny in Jetty.  I have an existing Geoserver cluster of three configured using a shared data directory and the Geonode Geoserver picks this up for some reason.

Here are my notes:

Environment

Local government
Behind firewall / proxy
Windows 7 32bit
Windows Server 2008 R2

Java JDK installed to C:\Program Files\Java\jdk1.7.0_45
JAVA_HOME set to C:\Program Files\Java\jdk1.7.0_45

Python installed as part of OSGeo4W (2.7.4)
PYTHONHOME set to C:\OSGeo4W\apps\Python27

Ant installed to C:\Build\apache-ant-1.9.3
ANT_HOME set to C:\Build\apache-ant-1.9.3
bin directory added to PATH

Maven2 installed to C:\Build\apache-maven-3.2.1
MAVEN_HOME set to C:\Build\apache-maven-3.2.1
bin directory added to PATH

git for Windows is installed but doesn't work due to firewall / proxy authentication issues.  The OSGeo4W installer gets around this by using IE5 settings in the advanced install mode.

Created directory C:\Apps\Geonode

All Python dependencies had to be downloaded into the Geonode directory and installed manually:
	agon-ratings-0.2.tar.gz
	beautifulsoup4-4.3.2.tar.gz
	dialogos-0.2.tar.gz
	Django-1.5.5.tar.gz
	django-activity-stream-0.4.4.tar.gz
	django-announcements-1.0.2.tar.gz
	django-appconf-0.5.tar.gz
	django-appconf-0.6.tar.gz
	django-extensions-1.3.3.tar.gz
	django-forms-bootstrap-2.0.3.post1.tar.gz
	django-forms-bootstrap-3.0.0.tar.gz
	django-geoexplorer-3.0.5.tar.gz
	django-jsonfield-0.9.10.tar.gz
	django-nose-1.2.tar.gz
	django-notification-1.0.tar.gz
	django-pagination-1.0.7.tar.gz
	django-taggit-0.10a1.tar.gz
	django-taggit-templatetags-0.4.6dev.tar.gz
	django-templatetag-sugar-0.1.tar.gz
	django-user-accounts-1.0b14.tar.gz
	geonode-avatar-2.1.1.tar.gz
	gisdata-0.5.4.tar.gz
	gsconfig-0.6.7.tar.gz
	httplib2-0.8.tar.gz
	MultipartPostHandler-0.1.0.tar.gz
	nose-1.3.0.tar.gz
	OWSLib-0.7.2.tar.gz
	OWSLib-0.8.6.tar.gz
	Paver-1.2.2.tar.gz
	pbr-0.6.tar.gz
	pinax-theme-bootstrap-3.0a11.tar.gz
	pinax-theme-bootstrap-account-1.0b2.tar.gz
	pip-1.5.4.tar.gz
	psycopg2-2.5.2.tar.gz
	pyproj-1.9.3.tar.gz
	python-dateutil-2.1.tar.gz
	python-dateutil-2.2.tar.gz
	pytz-2012j.tar.gz
	pytz-2013.9.tar.gz
	pytz-2013b.tar.gz
	requests-2.2.1.tar.gz
	Shapely-1.2.17.tar.gz
	Shapely-1.2.7.tar.gz
	six-1.5.2.tar.gz
	South-0.7.3.tar.gz
	SQLAlchemy-0.9.3.tar.gz
	stevedore-0.14.1.tar.gz
	transifex-client-0.10.tar.gz
	user-messages-0.1.1.tar.gz
	virtualenv-1.11.4.tar.gz
	virtualenv-clone-0.2.4.tar.gz
	virtualenvwrapper-4.2.tar.gz
	
	lxml-3.3.1.win32-py2.7.exe
	PIL-1.1.7.win32-py2.7.exe
	Pillow-2.3.0.win32-py2.7.exe
	py2exe-0.6.9.win32-py2.7.exe
	pyproj-1.9.3.win32-py2.7.exe
	Shapely-1.3.0.win32-py2.7.exe
	
Download Python setuptools into Geonode directory and run executable. This creates the Include\, Libs\, Scripts\ structure.

Run easy_install.exe in the Scripts directory to install all the dependencies listed above.  This is the full list of packages required by Geonode.  After activating the virtualenv install PIL and lxml.

The git clone command doesn't work behind our firewall so I downloaded the master.zip and extracted into geonode\ directory (C:\Apps\Geonode\genode)

Install Geonode in the local virtualenv using "pip.exe install -e geonode --use-mirrors" (got warning messages about deprecated use of "--use-mirrors" but I ignored them)

This install process required the full list of dependencies above.  Once all installed could move into geonode directory and run "paver setup"

This step failed as the pavement.py setup could not download geoserver.war or jetty-runner-8.1.8.v20121106.jar (firewall proxy issues again) so I downloaded these manually into C:\Apps\Geonode\geonode\downloaded.  The installer found them after this.

There were complaints about not be able to find vcvarsall.bat as part of the install.

"paver start" did not work as stated in the install instructions:
 
---> pavement.start
---> pavement.start_geoserver
cd C:\Apps\Geonode\geonode\geoserver\data
java -Xmx512m -XX:MaxPermSize=256m -DGEOSERVER_DATA_DIR=C:\Apps\Geonode\geonode\
geoserver\data -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar
C:\Apps\Geonode\geonode\downloaded\jetty-runner-8.1.8.v20121106.jar --log C:\App
s\Geonode\geonode\geoserver\jetty.log C:\Apps\Geonode\geonode\scripts\misc\jetty
-runner.xml > /dev/null &
The system cannot find the path specified.
cd C:\Apps\Geonode\geonode
Starting GeoServer on http://localhost:8080/geoserver/
The logs are available at C:\Apps\Geonode\geonode\geoserver\jetty.log
GeoServer never started properly or timed out.It may still be running in the bac
kground.

Running java -jar C:\Apps\Geonode\geonode\downloaded\jetty-runner-8.1.8.v20121106.jar C:\Apps\Geonode\geonode\scripts\misc\jetty-runner.xml starts the jetty container but no geoserver is found:

(Geonode) C:\Apps\Geonode\geonode>java -jar downloaded\jetty-runner-8.1.8.v20121
106.jar C:\Apps\Geonode\geonode\scripts\misc\jetty-runner.xml
2014-03-03 10:02:29.824:INFO:omjr.Runner:Runner
2014-03-03 10:02:29.824:WARN:omjr.Runner:No tx manager found
2014-03-03 10:02:30.510:INFO:oejs.Server:jetty-8.y.z-SNAPSHOT
2014-03-03 10:02:30.682:WARN:oejw.WebInfConfiguration:Web application not found
../geoserver
2014-03-03 10:02:30.682:WARN:oejw.WebAppContext:Failed startup of context o.e.j.
w.WebAppContext{/geoserver,null},../geoserver
java.io.FileNotFoundException: ../geoserver
        at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfigurati
on.java:502)
        at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfi
guration.java:71)
        at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.jav
a:455)
        at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:491
)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCol
lection.java:229)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(Con
textHandlerCollection.java:172)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCol
lection.java:229)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrappe
r.java:95)
        at org.eclipse.jetty.server.Server.doStart(Server.java:277)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLife
Cycle.java:64)
        at org.mortbay.jetty.runner.Runner.run(Runner.java:504)
        at org.mortbay.jetty.runner.Runner.main(Runner.java:625)
2014-03-03 10:02:30.931:INFO:oejs.AbstractConnector:Started SelectChannelConnect
or@0.0.0.0:8080
2014-03-03 10:09:45.746:INFO:oejsh.ContextHandler:stopped o.e.j.w.WebAppContext{
/geoserver,null},../geoserver
2014-03-03 10:09:45.890:INFO:oejut.ShutdownThread:shutdown already commenced

If I create a start.bat with:

	@echo off
	start /B start_jetty.bat
	
start_jetty.bat has:

	@echo off
	java -Xmx512m -XX:MaxPermSize=256m -DGEOSERVER_DATA_DIR=C:\Apps\Geonode\geonode\geoserver\geoserver\data -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -DSTOP.PORT=8087 -DSTOP.KEY=stopme -jar C:\Apps\Geonode\geonode\downloaded\jetty-runner-8.1.8.v20121106.jar --port 8088 --log C:\Apps\Geonode\geonode\geoserver\jetty.log C:\Apps\Geonode\geonode\scripts\misc\jetty-runner.xml

Starting the JETTY server and then running "paver start" results in the following error:

WindowsError at /

[Error 126] The specified module could not be found

Request Method: 	GET
Request URL: 	http://localhost:8000/
Django Version: 	1.5.5
Exception Type: 	WindowsError
Exception Value: 	

[Error 126] The specified module could not be found

Exception Location: 	C:\OSGeo4W\apps\Python27\Lib\ctypes\__init__.py in __init__, line 365
Python Executable: 	C:\Apps\Geonode\Scripts\python.exe
Python Version: 	2.7.4
Python Path: 	

['C:\\Apps\\Geonode\\geonode',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pil-1.1.7-py2.7-win32.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\lxml-3.3.1-py2.7-win32.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pillow-2.3.0-py2.7-win32.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\gsconfig-0.6.7-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\httplib2-0.8-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\nose-1.3.0-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pbr-0.6-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\six-1.5.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\owslib-0.7.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\python_dateutil-2.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django-1.5.5-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pinax_theme_bootstrap-3.0a11-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pinax_theme_bootstrap_account-1.0b2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_user_accounts-1.0b14-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_forms_bootstrap-2.0.3.post1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_pagination-1.0.7-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_jsonfield-0.9.10-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_friendly_tag_loader-1.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_taggit-0.10a1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_taggit_templatetags-0.4.6dev-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_templatetag_sugar-0.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_geoexplorer-3.0.5-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_notification-1.0-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_announcements-1.0.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_activity_stream-0.4.4-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_extensions-1.3.3-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\user_messages-0.1.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\geonode_avatar-2.1.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\dialogos-0.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\agon_ratings-0.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\south-0.7.3-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_downloadview-1.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\requests-2.2.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pycsw-1.6.1-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\paver-1.2.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_nose-1.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\beautifulsoup4-4.3.2-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\multipartposthandler-0.1.0-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\gisdata-0.5.4-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\py2exe-0.6.9-py2.7-win32.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\transifex_client-0.10-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pytz-2012j-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\django_appconf-0.5-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\shapely-1.2.17-py2.7.egg',
 'C:\\Apps\\Geonode\\lib\\site-packages\\pyproj-1.9.3-py2.7-win32.egg',
 'C:\\Apps\\Geonode\\Scripts\\python27.zip',
 'C:\\Apps\\Geonode\\DLLs',
 'C:\\Apps\\Geonode\\lib',
 'C:\\Apps\\Geonode\\lib\\plat-win',
 'C:\\Apps\\Geonode\\lib\\lib-tk',
 'C:\\Apps\\Geonode\\Scripts',
 'C:\\OSGeo4W\\apps\\Python27\\Lib',
 'C:\\OSGeo4W\\apps\\Python27\\DLLs',
 'C:\\OSGeo4W\\apps\\Python27\\Lib\\lib-tk',
 'C:\\Apps\\Geonode',
 'C:\\Apps\\Geonode\\lib\\site-packages']

Server time: 	Mon, 3 Mar 2014 11:26:23 +0000	

The console log has:

(Geonode) C:\Apps\Geonode\geonode>paver start
---> pavement.start
---> pavement.start_geoserver
cd C:\Apps\Geonode\geonode\geoserver\data
java -Xmx512m -XX:MaxPermSize=256m -DGEOSERVER_DATA_DIR=C:\Apps\Geonode\geonode\
geoserver\data -Dorg.eclipse.jetty.server.webapp.parentLoaderPriority=true -jar
C:\Apps\Geonode\geonode\downloaded\jetty-runner-8.1.8.v20121106.jar --log C:\App
s\Geonode\geonode\geoserver\jetty.log C:\Apps\Geonode\geonode\scripts\misc\jetty
-runner.xml > /dev/null &
The system cannot find the path specified.
cd C:\Apps\Geonode\geonode
Starting GeoServer on http://localhost:8080/geoserver/
The logs are available at C:\Apps\Geonode\geonode\geoserver\jetty.log
---> pavement.sync
python manage.py syncdb --all --noinput
Syncing...
Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 283 object(s) from 5 fixture(s)

Synced:
 > django.contrib.auth
 > django.contrib.contenttypes
 > django.contrib.sessions
 > django.contrib.sites
 > django.contrib.admin
 > django.contrib.sitemaps
 > django.contrib.staticfiles
 > django.contrib.messages
 > django.contrib.humanize
 > pagination
 > taggit
 > taggit_templatetags
 > south
 > friendlytagloader
 > geoexplorer
 > django_extensions
 > pinax_theme_bootstrap_account
 > pinax_theme_bootstrap
 > django_forms_bootstrap
 > account
 > avatar
 > dialogos
 > agon_ratings
 > notification
 > announcements
 > user_messages
 > geonode.people
 > geonode.base
 > geonode.layers
 > geonode.upload
 > geonode.maps
 > geonode.security
 > geonode.search
 > geonode.social
 > geonode.catalogue
 > geonode.documents
 > actstream

Not synced (use migrations):
 -
(use ./manage.py migrate to migrate these)
python manage.py loaddata sample_admin.json
Installed 1 object(s) from 1 fixture(s)
---> pavement.start_django
python manage.py runserver  &
Validating models...

0 errors found
March 03, 2014 - 11:29:31
Django version 1.5.5, using settings 'geonode.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /
...

The Shapely DLLs installed in the virtualenv could not find the vcvarsall.bat file and so could not be compiled with the C extensions.
Installing the compiled shapely library into C:\OSGeo4W\apps\Python27\Lib\site-packages\Shapely-1.3.0-py2.7-win32.egg and then copying the contents of the shapely directory into C:\Apps\Geonode\Lib\site-packages\shapely-1.3.0-py2.7.egg\shapely allows the server to start correctly.

So, at http://localhost:8000/ I get the Geonode interface.  If I try to connect to Geoserver running on http://localhost:8088/geoserver I get a connection to my existing Geoserver data directory even though I have specified the GEOSERVER_DATA_DIR as the Geonode one.

The hardest part of the installation was configuring the Python dependencies and then getting Jetty to run with a batch file.  Geoserver is next on the to-do list.

Hope this helps...

**Comment by nathanhilbert** [comment]
Responded on [geonode users google group](https://groups.google.com/forum/#!searchin/geonode-users/ascii/geonode-users/TvFIjqurUfg/wgVQIMhVzBAJ).  Sorry I didn't see it until now. 
@ischneider would you mind merging the [PR for gsimporter](https://github.com/boundlessgeo/gsimporter/pull/2)? Thanks!

@george-silva with the exception of #1919, which seems to be fixed from 340d6e0db6eaffeca37685028fe2081bed84335b, were there any other Windows errors?  If not, maybe we can close this ticket for now.

**Comment by george-silva** [comment]
Hello Nathan,

Not that I remember. No errors.

On Fri, Jan 16, 2015 at 5:29 PM, Nathan Hilbert <notifications@github.com>
wrote:

> Responded on geonode users google group
> <https://groups.google.com/forum/#!searchin/geonode-users/ascii/geonode-users/TvFIjqurUfg/wgVQIMhVzBAJ>.
> Sorry I didn't see it until now.
> @ischneider <https://github.com/ischneider> would you mind merging the PR
> for gsimporter <https://github.com/boundlessgeo/gsimporter/pull/2>?
> Thanks!
>
> @george-silva <https://github.com/george-silva> with the exception of
> #1919 <https://github.com/GeoNode/geonode/issues/1919>, which seems to be
> fixed from 340d6e0
> <https://github.com/GeoNode/geonode/commit/340d6e0db6eaffeca37685028fe2081bed84335b>,
> were there any other Windows errors? If not, maybe we can close this ticket
> for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1383#issuecomment-70308097>.
>



-- 
George R. C. Silva
SIGMA Consultoria
----------------------------
http://www.consultoriasigma.com.br/

**Comment by nathanhilbert** [comment]
Please close this ticket.

**Comment by ahmednosman** [comment]
now geonode installs on windows together with Cartoview you can download the installer at www.cartologic.com/cartoview

**Comment by Writwik09** [comment]
Hi members,
You can find the details installation process in development mode or in production server in Windows here: [[GeoNode installation process in Windows] ](http://geoithub.com/geonode-installation-process-windows/)
