### ISSUE TITLE
Slow explore pages & search queries with large datasets

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1409]
Load times for the "Explore" layers/maps/people pages, and queries on the search page, are very slow with an instance containing 8612 layers, 2662 maps, and 10085 users.

I migrated a copy of a geonode 1.x database (WorldMap) to GeoNode 2.0 and installed django-debug-toolbar to monitor database queries:

Browse layers: 31240 queries were made, taking 12400 ms, but several additional minutes were required to load the page.  

Browse maps: 2680 queries in 2109 ms, and took over a minute to load.

Browse people: 20192 queries in 7667 ms.

Search page:
* Search layers for "africa": 194 results, 1219 queries in 1090 ms
* Search for all layers: 8612 results, 31238 queries in 10958 ms

**Comment by jj0hns0n** [comment]
Should we close this now? I'd like to make sure the haystack implementation still works before 2.4 final and add some docs for it.
