### ISSUE TITLE
Problem to delete layers in Geonode 2.0

### ISSUE THREAD

**Issue by davicustodio** [GeoNode/geonode#1414]
When trying to delete a layer in Geonode 2.0 An unexpected error happens. Investigating best realized the error occurs related to the character "í" or utf8 "\xed". When using the pt_br language (Portuguese Brazil) the error appears to exclude any layer, probably the character "í" or "\ xed" is being used in the .po files, since this character is very common in Portuguese Brazil.. but when changing the language to English the problem disappears. 

For more details, visit the discussion group user GeoNode here:
https://groups.google.com/forum/?hl=pt-BR#!topic/geonode-users/Bc3YrSRrbAg

Thanks

**Comment by jj0hns0n** [comment]
Adding tag unicode and will check with other unicode issues.

**Comment by capooti** [comment]
checking if I can still replicate and then see if there is an easy fix.
