### ISSUE TITLE
Update security documentation

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1415]
Update the documentation: https://github.com/GeoNode/geonode/blob/master/docs/reference/security.txt#L42

**Comment by oware** [comment]
verified and documentation is up to date http://docs.geonode.org/en/master/reference/security.html#security

**Comment by jj0hns0n** [comment]
@ingenieroariel can you verify this since you opened the ticket and then close. Thanks for the review @oware
