### ISSUE TITLE
Add a default way to contact the admin of the GeoNode or an optional contact information

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1418]
By default GeoNode doesn't provide a way to contact the administrator and I have got a lot feedback from users wanted to contact the administrator of a GeoNode for instance to request the creation of an account.
I think by default it should be set to send an email to the admin user but it could be deactivated or go to another user.

**Comment by ppasq** [comment]
This was done on [Masdap](http://www.masdap.mw/contact/) adding django-nocaptcha-recaptcha. If there is consensus on this I can prepare a PR.
