### ISSUE TITLE
GNIP - Upload/Download directly from GeoNode

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1421]
Allow people to download the file that was uploaded with NO modifications.
## Potential Problems

What to do about layers that are modified after creation.

**Comment by jj0hns0n** [comment]
Punting to 2.5?

**Comment by capooti** [comment]
Also, let's make sure to avoid any duplication with https://github.com/GeoNode/geonode/wiki/GNIP-47--Predefined-Download-Service

**Comment by JJediny** [comment]
-1 for vector data 
+1 for raster data

While geoserver takes a hit the reality is traffic/demand is rarely an issue, and if a production geonode is seeing heavy use, taking the normal steps to scale the site (via clustering / DB isolation) will meet the demand. Shouldn't break or complicate what already works, for raster I agree that automating a download service for original raster file is needed. Maybe just mod apache to access upload dir as a static file to download and register direct link to override current WCS link to geoserver. Lastly seems like version control is also baked into this ticket, feel like if that is an issue for a project they would  consider integrating GeoGig (feature-based versioning) over a (file-based) versioning system within django.

**Comment by jondoig** [comment]
You can already do this without even logging in. Even on private data. See #2896  :open_mouth:
