### ISSUE TITLE
Remove hardcoding of `geoserver` webapp

### ISSUE THREAD

**Issue by jean** [GeoNode/geonode#1474]
When deploying on Webfaction, it's natural to set an application to be served on a path. 
In this case, the `tomcat` application is served on `http://somedomain/geoserver/`. 
However, this refers to the `tomcat` root, so the `tomcat` default webapp needs to be changed to the `geoserver` webapp. Once this is done, geoserver shows up at the above URL and when browsing the tomcat port directly on the server. 

However the `/geoserver/` path is hardcoded throughout the django app, mostly in tests, in configuration defaults, and in `geonode/maps/management/updatemaplayerip.py`.

Would it be worthwhile to add `GEOSERVER_PATH` as a config value instead of hardcoding `/geoserver/`?

With the default app set to geoserver, both `http://localhost:8765/` (browsing the tomcat port directly) and `http://localhost:8765/geoserver/` seems to work (the webapp is deployed twice?). I don't know tomcat well enough to know whether this is OK.

**Comment by jj0hns0n** [comment]
Can we verify this with the latest packages?

**Comment by jj0hns0n** [comment]
@jean @ingenieroariel can we close this?

**Comment by jean** [comment]
@jj0hns0n better would be to modify the code to depend on `OGC_SERVER` rather than hardcode the `/geoserver/` path. The issue exists and the solution is known. What would be the point of closing the issue, waiting for the next person to stumble across it and reporting it again? 

I understand the urge to get to "inbox zero" with issues, but I don't think it's realistic. Rather use a label like `papercut` to mark non-critical issues and filter them out if you don't want to look at them.

**Comment by jj0hns0n** [comment]
@jean I was under the impression this had been fixed, but was mistaken. We will leave it open and try to address it in 2.5

**Comment by jean** [comment]
I just had a look at `geonode/maps/management/updatemaplayerip.py` as mentioned in the original issue, and saw that `/geoserver/` is still in there, so I concluded it's not fixed yet ...
