### ISSUE TITLE
Package version issues

### ISSUE THREAD

**Issue by jean** [GeoNode/geonode#1476]
I'm working on a `zc.buildout` configuration to setup geonode. 
I'm targeting the `2.0.x` branch, which I believe is the latest stable code. 
As buildout checks all version dependencies, this is shaking out version conflicts. 

#### `lxml`

```
We already have: lxml 3.3.5
but pycsw 1.6.4 requires 'lxml==3.1.2'.
```

Fix this by pinning `lxml = 3.1.2`

#### `django-appconf` 

```
We already have: django-appconf 0.6
but pinax-theme-bootstrap-account 1.0b2 requires 'django-appconf==0.5'.
```

This is more tricky. `geonode` depends on 
`django-user-accounts==1.0b14` which depends on 
`django-appconf==0.6`.

The latest master of `pinax-theme-bootstrap-account` still depends on
`django-appconf==0.5`, so there is no way to satify both requirements
with released versions.

I tried pinning `django-user-accounts==1.0b14` to the last version that
depended on `django-appconf==0.5`, but that threatened to snowball.

Solution: fork `django-user-accounts` and propose a PR to bump dependency
version.

#### `pinax-theme-bootstrap-account`

```
We already have: pinax-theme-bootstrap-account 1.0b3
but GeoNode 2.0.dev20140416160257 requires 'pinax-theme-bootstrap-account==1.0b2'.
```

We'll have to change GeoNode to depend on our fork; it doesn't make sense to 
fork an old version, so bump version. For now, the source needs to be 
specified as git repo.

#### `OWSLib`

```
We already have: pytz 2013b
but OWSLib 0.7.2 requires 'pytz==2012j'.
```

The `2013b` dependency is introduced by `django-user-accounts==1.0b14`.
Rather than downgrade that, let's upgrade `OWSLib`.

#### `pycsw`

```
We already have: OWSLib 0.8.2
but pycsw 1.6.4 requires 'OWSLib==0.7.2'.
```

OK, then we need to upgrade `pycsw` also. After juggling versions, 
I found that `OWSLib 0.8.6` and `pycsw 1.8.0` are happy together.

#### `lxml` again

```
We already have: lxml 3.1.2
but pycsw 1.8.0 requires 'lxml==3.2.5'.
```

Having upgraded `pycsw`, we need the corresponding `lxml` version too. 
(Still not the latest `lxml` version though.)

Now we get a buildout that runs all the way through. 

I haven't run tests yet.

**Diffs**

I'll create PRs once the dust settles ..

```diff
18:42 jean@klippie:~/venv/geonode/src/geonode$ git diff
diff --git a/setup.py b/setup.py
index 43f0586..246d953 100644
--- a/setup.py
+++ b/setup.py
@@ -78,11 +78,11 @@ setup(name='GeoNode',
         "lxml",
         # python dependencies
         "gsconfig==0.6.9",
-        "OWSLib==0.7.2",
+        "OWSLib==0.8.6",
         "Django==1.5.5",
         # Django Apps
         "pinax-theme-bootstrap==3.0a11",
-        "pinax-theme-bootstrap-account==1.0b2",
+        "pinax-theme-bootstrap-account==1.0b3",
         "django-user-accounts==1.0b14",
         "django-forms-bootstrap==2.0.3.post1",
         "django-pagination==1.0.7",
@@ -102,7 +102,7 @@ setup(name='GeoNode',
         "South==0.7.3",
         "django-downloadview==1.2",
         #catalogue
-        "pycsw==1.6.4",
+        "pycsw==1.8.0",
         # setup
         "Paver",
         # sample and test data / metadata
```

```diff
18:44 jean@klippie:~/venv/geonode/src/pinax-theme-bootstrap-account$ git diff
diff --git a/setup.py b/setup.py
index a14b8ed..03d069f 100644
--- a/setup.py
+++ b/setup.py
@@ -111,7 +111,7 @@ AUTHOR_EMAIL = "jtauber@jtauber.com"
 URL = "http://github.com/pinax/pinax-theme-bootstrap-account"
 VERSION = __import__(PACKAGE).__version__
 INSTALL_REQUIRES = [
-    "django-appconf==0.5",
+    "django-appconf==0.6",
 ]
 
 try:
```

**Comment by jj0hns0n** [comment]
Can we verify this with the latest packages.
