### ISSUE TITLE
Can not Download Geo Tiff from Geonode........

### ISSUE THREAD

**Issue by UmerSharif** [GeoNode/geonode#1485]
When i try to download geo tiff file from geonode which i have uploaded.....only the WCS file is downloaded which gives the following message.....

       <?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.2.0" >    
        <ServiceException code="InvalidParameterValue" locator="bbox">  
        illegal bbox, minX: 71.9174175022 is greater than maxX: 32.688063126649986
        </ServiceException></ServiceExceptionReport>

I dont know how to fix it.....Please help

**Comment by tosco** [comment]
The problem of downloading the original uploaded raster is present since version 2.0, please refer here. According to this conversation and to the online demo this issue is still present in 2.4, released recently. What is blocking this important issue to be solved? 
Thanks

**Comment by simod** [comment]
hi this should be solved in master https://github.com/GeoNode/geonode/commit/287dbf7e38850ed1e4a7e1c720a111dee0cc77d9, thanks to the recent geoserver upgrade that supports wcs 2.0

**Comment by tosco** [comment]
Great. Is there a way to produce a patch to solve this issue in the last available stable release (2.4) without waiting for 2.5?

**Comment by simod** [comment]
yes, https://github.com/GeoNode/geonode/commit/287dbf7e38850ed1e4a7e1c720a111dee0cc77d9.patch

**Comment by simod** [comment]
you will have to regenerate the wcs links. Please report back in case of issues.

**Comment by tosco** [comment]
I will, thanks.

**Comment by chakrey** [comment]
How to run this patch?
