### ISSUE TITLE
Enable classify in composer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#1507]
@mbertrand:

We have updated geoserver to 2.5 with the sldService and released a new django-geoexplorer (4.0.3) that contains your gxp patch (now living in GeoNode/gxp branch geonode) and a geoexplorer that includes the ClassifyPanel.js file (now living in GeoNode/suite branch geonode) but we do not know how to enable the panel in the composer.

Thanks in advance for your help! and for developing the patch.

From @capooti's account,
Ariel.

**Comment by capooti** [comment]
Back to this, I will try to do a recap.

Now from GeoServer 2.5 we have SLD REST Service in core GeoServer [1], therefore we can use it without problems. I already made some tests on some layers and it works very well, thanks to @simboss and his team for this!
@mbertrand I remember you created this PR [2]: now it would be very handy to finally have this important feature in core GeoNode. @bartvde, any chance you could provide some feedback to @mbertrand in order to merge it? thanks in advance!

[1] http://docs.geoserver.org/2.5.x/en/user/community/sldservice/index.html
[2] https://github.com/boundlessgeo/gxp/pull/231/files

**Comment by jj0hns0n** [comment]
Any update on this? Seems we can port over some work from Worldmap?

**Comment by mbertrand** [comment]
- The changes in https://github.com/boundlessgeo/gxp/pull/231 need to make into GeoNode's version of GeoExplorer.js
- The [sldService plugin jars](http://ares.boundlessgeo.com/geoserver/2.9.x/community-latest/geoserver-2.9-SNAPSHOT-sldservice-plugin.zip) need to be added to Geoserver.  Also, there is an open PR https://github.com/geoserver/geoserver/pull/1571 that fixes an issue with the plugin on Geoserver 2.8+
