### ISSUE TITLE
Cannot set account email through the admin interface

### ISSUE THREAD

**Issue by daniviga** [GeoNode/geonode#1509]
**Use case**
- You have a registration closed GeoNode installation. The users are created by admin.
- You create a new user using the Django admin interface. In the same view you provide an email.

**Expected results**
- User should be able to use the password reset form: http://myhost/account/password/reset/

**Actual results**
- The form returns **Email address can not be found.**

**Reason**
- The email address set in the Django admin user view is not propagated into the ```account``` application (http://myhost/account/settings/)

![screenshot from 2014-05-30 12 39 45]
(https://cloud.githubusercontent.com/assets/1818657/3129610/bd41573c-e7e6-11e3-9068-45ae843f723f.png)

- Even changes to the email in Django admin are not propagated correctly
- There's no way to set the "account" profile email in Django admin:

![screenshot from 2014-05-30 12 41 30](https://cloud.githubusercontent.com/assets/1818657/3129621/00ce5f4a-e7e7-11e3-9977-17aedf7f7781.png)

Tested on the GeoNode 2.0 stable release (deb packages on Ubuntu 12.04)
```
ii  geonode                              2.0.0+thefinal7                   Allows the creation, sharing, and collaborative use of geospatial data.
ii  geoserver-geonode                    2.0+201311140000                  High performance, standards-compliant map and geospatial data server.
ii  python-geonode-avatar                2.1.1-1~ingenieroariel            A fork of django-avatar, for GeoNode
```

**Comment by barry1955** [comment]
This is still not 'fixed'. 
PLease explain how to change the email address of an existing user. This is not a tall order. 

Definitely NOT fixed.

**Comment by simod** [comment]
@barry1955 what is the error that you get when trying to change the email from the admin panel?
