### ISSUE TITLE
Ubuntu 14.04 (Trusty) Development Build Breaks

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1535]
We are having trouble launching a clean development build for Ubuntu 14.04 via Vagrant.  Using the box found in `http://cloud-images.ubuntu.com/vagrant/trusty/current/` at `http://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box`, this is default for `vagrant init ubuntu/trusty64`.

Or did the virtual environment wrapper preferred setup change?

When executing pip install -e geonode, I get the following error:

```
Downloading/unpacking psycopg2==2.4.5 (from GeoNode==2.0.dev20140616170427)
  Downloading psycopg2-2.4.5.tar.gz (719kB): 719kB downloaded
  Storing download in cache at ./.pip-downloads/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fp%2Fpsycopg2%2Fpsycopg2-2.4.5.tar.gz
  Running setup.py (path:/home/vagrant/.venvs/geonode/build/psycopg2/setup.py) egg_info for package psycopg2
    
    Error: pg_config executable not found.
    
    Please add the directory containing pg_config to the PATH
    or specify the full executable path with the option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    Complete output from command python setup.py egg_info:
    running egg_info
```
It seems the dependencies may be out of sync.  psycopg2 is expecting a different version of python-gdal, perhaps?  Do we need to add the ubuntugis repo or install a custom version of python-gdal or other osgeo package?

Thank you for your assistance.

**Comment by jj0hns0n** [comment]
@state-hiu can we get an update on this with the latest packages?
