### ISSUE TITLE
general style fixes

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#1544]
some small things like the filters selection i the search pages

**Comment by jj0hns0n** [comment]
@simod can this one be closed?

**Comment by simod** [comment]
Yep

Il mercoledì 18 novembre 2015, Jeffrey Johnson <notifications@github.com>
ha scritto:

> @simod <https://github.com/simod> can this one be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1544#issuecomment-157852924>.
>


-- 
Simone
