### ISSUE TITLE
Adding Avatar: IOError decoder zip not available

### ISSUE THREAD

**Issue by gamesbook** [GeoNode/geonode#1558]
Working in development mode, when trying to add an avatar I get a 'yellow screen' with the error " IOError decoder zip not available".  It appears this relates to a dependancy that `pillow` has, in order for it to upload JPEG/PNG images.  The fix I used was to:

```
pip uninstall pillow
sudo apt-get install zlib1g-dev libjpeg-dev
pip uninstall pillow
```

This implies that the `sudo apt-get install zlib1g-dev libjpeg-dev` needs to be added to the developer install routine **before** the pip requirements are run; but I have not tested this with a clean developer install.

**Comment by jj0hns0n** [comment]
@berrydaniel @simod lets address this in the next round of packages.
