### ISSUE TITLE
Option to add layers via pycsw missing from GeoExplorer "Add Layers" tool

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#1561]
The 'Add Layers' tool in GeoExplorer used to have an option to search available layers via pycsw (gxp_geocataloguesource), but that is now missing, so there's no way to add remote service layers on the map composer page.

**Comment by JJediny** [comment]
Adding to critical as there is currently no way to add layers from remote services... remote services are external to geoserver handling layers in geoexplorer, if remote services will be in this release it's critical to find a way to add remote services to map composer

**Comment by tomkralidis** [comment]
I think if we bring back `gxp_geocataloguesource`, given pycsw binds directly to the Django model, then this should bring us closer.

**Comment by jj0hns0n** [comment]
Removing critical. This is NOT a showstopping issue.
