### ISSUE TITLE
User is created although mail is not sent

### ISSUE THREAD

**Issue by jean** [GeoNode/geonode#1591]
When a new user registers, they are notified via mail.
When notification fails, e.g. due to SMTP auth error, the mail is not sent and an error is displayed, but the user is created. 
When the user retries registration, they are informed that a user already exists. This is confusing. 

Suggestion: send mail transactionally.

**Comment by menegon** [comment]
I try to fix this

**Comment by menegon** [comment]
it works if we add a transaction.atomic decorator on account.views.SignupView.form_valid ( geonode-user-accounts).
just tested.

**Comment by capooti** [comment]
so you may come out with a PR?
