### ISSUE TITLE
Provide an interface for editing group permissions

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#1621]
When creating/updating a group, it would be nice to have an interface for managing group permissions (though this is possible to be accomplished using the admin interface).

These are the group permissions that would make sense to manage:

Accounts (add/change/delete)
Announcements (add/change/delete)
Groups (add/change/delete)
Contact Roles (add/change/delete)
Documents (add/change/delete)
Layers (add/change/delete/change permissions/can dowload/can download metadata/can edit data/can edit metadata/can view/)
Layers file (add/change/delete)
Styles (add/change/delete)
Maps (add/change/delete)
Services (add/change/delete)
Tags (add/change/delete)

**Comment by jj0hns0n** [comment]
@capooti this will not get done for 2.4 right?

**Comment by capooti** [comment]
no, I agree to tag it for 2.5.x milestone
