### ISSUE TITLE
Translatable Strings Out of Sync

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1632]
There are some translation errors for the groups and permissions templates.

The more concise "Who can manage?" is out of sync with the transifex identifer of "Who can manage and edit this data?".  This breaks some translations.  Spanish is one on the most complete translations.  You can toggle between English/Spanish to identify gaps.

See:
https://github.com/GeoNode/geonode/blob/master/geonode/templates/_permissions.html
and
https://github.com/GeoNode/geonode/blob/master/geonode/locale/es/LC_MESSAGES/djangojs.po

@simod @garnertb

**Comment by jj0hns0n** [comment]
@teamgeode can you guys take a look at this?

**Comment by collaer** [comment]
Since a sycing has be done, I think this issue should be closed now.

But just a note it's normal those strings were not present in the djangojs.po, the translations string from html templates should be located in django.po
