### ISSUE TITLE
Thumbnails do not respect permissions

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#1634]
It shouldn't be possible for a user to get a thumbnail by a url, it the user has not the permission for the relative object (layer, map, document).

**Comment by state-hiu** [comment]
Could we use md5 hashes of thumbnail byte array and store the hash with the model?

**Comment by simod** [comment]
the thumbnail urls are now obscured with the uuid, tagging to 2.5 for the full permissions framework maybe using the django-sendfile
