### ISSUE TITLE
RemoteUserBackend problems

### ISSUE THREAD

**Issue by vrubiella** [GeoNode/geonode#1644]
I'm having problems with autenticacion based on RemoteUserBackend.

Django authorized OK and /admin works fine but:
- Can't login to geoserver. Every geoserver request requires new authentication (always show authentication form although you autentiques correctly).
- Changes in User/Profile options (django) returns Internal Server Error.(unhautorized)

I thing that geoserver and geonode are sharing some session that is not created correctly by RemoteUserBackend, but why?

Any solution?

Thank you so much.

**Comment by garnertb** [comment]
@vrubiella, is there any chance that you could provide a Vagrantfile that sets up a VM with your configuration so we help you?
