### ISSUE TITLE
Replace Layer / Clear GeoWebCache

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1656]
The GeoWebCache tile cache for a layer should be cleared when a layer is replaced with new data via the layer_replace view.

**Comment by jj0hns0n** [comment]
We can do this via the GWC rest API. http://docs.geoserver.org/stable/en/user/geowebcache/rest/seed.html

@ischneider do you have any pointers on how to do this most efficiently? Seems like there may be some py code out there already vs just starting from scratch with python requests.

**Comment by ischneider** [comment]
> @ischneider do you have any pointers on how to do this most efficiently? Seems like there may be some py code out there already vs just starting from scratch with python requests.

I don't think there is any existing py library for this but the API looks simple enough to use - create a JSON object and POST to the correct endpoint.

**Comment by garnertb** [comment]
@state-hiu, Can you confirm that this is a bug?  Below are my tests with the internal GWC.

1. Enable disk quota in Geoserver.
1. Upload layer geonode_cntry98.
1. Goto to `layers/geonode%3Acntry98` and scroll around start caching.  
1. Check disk space on command line: 
```
$ du -h geoserver/data/gwc | grep "./geonode_cntry"
1.6M	geoserver/data/gwc/geonode_cntry98
```
1.  Check disk space in Geoserver:
![screen shot 2015-02-05 at 2 00 46 pm](https://cloud.githubusercontent.com/assets/1141646/6067018/711a0dbc-ad3f-11e4-8cff-c02a6eef4f5e.png)
1. Replace the layer in GeoNode (`layers/geonode%3Acntry98` > **Edit Layer** > **Replace Layer**)
1. Check disk space on command line:
```
$ du -h geoserver/data/gwc | grep "./geonode_cntry"
$ 
```
1. Check disk space in Geoserver:
![screen shot 2015-02-05 at 2 04 55 pm](https://cloud.githubusercontent.com/assets/1141646/6067083/fea7112a-ad3f-11e4-8b14-b7f46fe86beb.png)

**About Geoserver**
Version
2.5.1
Git Revision
a221fc30dd9d41e8d63739dede57a4a39587270c
Build Date
19-May-2014 05:07
GeoTools Version
11-SNAPSHOT (rev d0db3a062cbcf1e6751db061d5b347e0af228ce6)
GeoWebCache Version
1.5.2 (rev 1.5.x/aac4b4f7ad149a4d36df3997e21709501ce56186)

**Comment by vdeparday** [comment]
I am not sure for the replace layer but this is still a critical issue, especially in #1870 . 
When using the managing style window to apply a different styles. If some tiles were cached with a previous styles, then the cache is not emptied and the new style is not applied. And worse, then it never get emptied even after re-changing the style with the style editor.

On @jj0hns0n computer, emptying the cache from the admin interface worked but on my computer and @collaer it didn't work, had to clear to it manually by deleting the file or disabling GWC.

**Comment by simod** [comment]
any updates on this one? or should we punt it to 2.5?

**Comment by gannebamm** [comment]
Hi,
The info below is not 100% related to a fix for the issue, but since this is a site which will be shown by googling the out of sync error with geonode and gwc I want to show a workaround:
I had this issue through a bunch of configuration hazzle with imagemosaic layers and datastores as well as workspaces. Somehow one of my layers was not removed from the GWC list and was stored at:
/usr/share/geoserver/data/gwc-layers$ ls
LayerInfoImpl--2af0fd0_15093ca2df1_-7a2f.xml

this xml file made my gwc to get out of sync. Removing it by hand solved my issue.

**Comment by capooti** [comment]
You can regenerate the cache much easier using the GWC user interface.

**Comment by gannebamm** [comment]
@capooti I was not able to load the interface, since it gave me a out of sync error.

**Comment by jj0hns0n** [comment]
@afabiani this may be an interesting one for you?

**Comment by afabiani** [comment]
Try to take a look.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by afabiani** [comment]
@jj0hns0n @all I just tested the layer replacement on GeoServer enabling GWC quota_store in order to be sure the tile cache were cleaned.

It actually works using both PostGIS and Shapefile backends.

I cannot actually reproduce the issue.

My environment is Ubuntu 14 with latest GeoNode 2.5 and GeoServer 2.9

**Comment by jj0hns0n** [comment]
I've never used the quota_store, can we add some note to the docs about this?
