### ISSUE TITLE
Geonode API does not respond to format convention

### ISSUE THREAD

**Issue by beechnut** [GeoNode/geonode#1657]
The GeoNode API does not respond when conventional requests that include a format i.e. ".json" are made.

The API returns the proper JSON when sent to `66.181.92.20/api/layers/23/`, but throws an error if I navigate to `http://66.181.92.20/api/layers/23.json`.

Similarly, `http://66.181.92.20/api/layers/` works, whereas `http://66.181.92.20/api/layers.json` does not.

My client is configurable and I've turned extensions off. However, I still think GeoNode should still respond to requests that include a format extension, in case another client is not as flexible.

**Comment by jj0hns0n** [comment]
Lets figure out what we can do here to make this more developer friendly.
