### ISSUE TITLE
Update available layer styles from web interface don't work

### ISSUE THREAD

**Issue by bombyx** [GeoNode/geonode#1667]
If you import a new layer style (eg from SLD file), and then you want to apply it to a layer through the back end web interface, when you click "update available layer", the system return an error.

In my case:
url: <your domain>/layers/geonode:landscape_dry_river/style/manage
On available styles you have the new imported style, if you move it to the right column, and then click "Update available layer" the system return "There was a problem loading this page", and it doesn't apply it.
When doing this operation I'm logged as super admin.
The only way to apply and make available the new imported style to a layer, is to do so using the Geoserver interface (in this case it will work), which is ok for an administrator, but not too much for a normal user.

**Comment by jj0hns0n** [comment]
These styles are not automatically kept in sync with styles from geoserver. There should be an option on this page to fetch the styles for this layer from geoserver and update on the geonode side ... alternatively we could sync these periodically. We should also have more options for providing an SLD via a GeoNode page and POSTing that to geoserver to create a  new style.

**Comment by ischneider** [comment]
Periodic syncing seems like overkill.

Ideally, it seems like style operations should be done through GeoNode and this would keep things in sync.

OK with adding a 'refresh' option, too
