### ISSUE TITLE
Upload page not displaying properly with file name containing space - file names and loading bar hidden

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1670]
With a long file name such as "Gampaha and Colombo Districts Clouds Cover Pol"
the filenames, the loading bar and the result line showing that it has been uploaded are hidden so the user doesn't know if the upload is proceeding or not: 

![image](https://cloud.githubusercontent.com/assets/1036189/4065770/b2cd4068-2e1d-11e4-9265-975ca2207967.png)

**Comment by jj0hns0n** [comment]
@ischneider should we just close this in favor of a new uploader implementation before 2.4?

**Comment by ischneider** [comment]
@jj0hns0n Unsure of whether a new uploader will appear before 2.4
