### ISSUE TITLE
Should catch exception when trying to delete layer from a layer group

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1671]
When trying to delete a layer that belongs to a published layer group, this exception is raised:
![image](https://cloud.githubusercontent.com/assets/1036189/4065932/40c9dfba-2e1f-11e4-8cba-76e9271a96b2.png)
It should be caught and show a user friendly message and maybe give the option to delete the layer group if the user is an admin.

Full Stacktrace:
Environment:

Request Method: POST
Request URL: http://www.riskinfo.lk/layers/geonode:basin_clouds_polygons/remove

Django Version: 1.5.5
Python Version: 2.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'pagination',
 'taggit',
 'taggit_templatetags',
 'south',
 'friendlytagloader',
 'geoexplorer',
 'django_extensions',
 'pinax_theme_bootstrap_account',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'account',
 'avatar',
 'dialogos',
 'agon_ratings',
 'notification',
 'announcements',
 'actstream',
 'user_messages',
 'geonode.people',
 'geonode.base',
 'geonode.layers',
 'geonode.upload',
 'geonode.maps',
 'geonode.proxy',
 'geonode.security',
 'geonode.search',
 'geonode.social',
 'geonode.catalogue',
 'geonode.documents')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'geonode.security.middleware.LoginRequiredMiddleware')

Traceback:
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  115.                         response = callback(request, *callback_args, **callback_kwargs)
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  25.                 return view_func(request, *args, **kwargs)
File "/home/dmc/geonode_production/geonode/layers/views.py" in layer_remove
  502.         layer.delete()
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/db/models/base.py" in delete
  674.         collector.delete()
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/db/models/deletion.py" in decorated
  62.             func(self, *args, **kwargs)
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/db/models/deletion.py" in delete
  288.                     sender=model, instance=obj, using=self.using
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/django/dispatch/dispatcher.py" in send
  170.             response = receiver(signal=self, sender=sender, **named)
File "/home/dmc/geonode_production/geonode/layers/models.py" in geoserver_pre_delete
  282.         cascading_delete(Layer.objects.gs_catalog, instance.typename)
File "/home/dmc/geonode_production/geonode/geoserver/helpers.py" in cascading_delete
  208.         cat.delete(lyr)
File "/home/dmc/.virtualenvs/geonode/lib/python2.7/site-packages/geoserver/catalog.py" in delete
  116.             raise FailedRequestError("Tried to make a DELETE request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))

Exception Type: FailedRequestError at /layers/geonode:basin_clouds_polygons/remove
Exception Value: Tried to make a DELETE request to http://localhost:8080/geoserver/rest/layers/basin_clouds_polygons.xml but got a 500 status code: 
:Unable to delete layer referenced by layer group 'situation-map-for-openstreetmap-work-plan_68'

**Comment by jj0hns0n** [comment]
This now looks like it fails silently and the layer is not deleted.

**Comment by jj0hns0n** [comment]
@garnertb I may need some help with this one now that the layer delete is being handled by the task queue. This line is failing with a FailedRequestError https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L260 Which propagates back up to here https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/signals.py#L34 Which ends up here https://github.com/GeoNode/geonode/blob/master/geonode/tasks/deletion.py#L16 but I see no way to trap the error and let the user know the issue vs failing silently.

**Comment by garnertb** [comment]
@jj0hns0n, fixed in 433cf0108292bb163e7b58443f1dfcb6120f8ac8.  The exception will now propagate through the task.

**Comment by jj0hns0n** [comment]
@garnertb. Did we actually test that the error is caught and returned to
the user or just that it now propagates?

**Comment by garnertb** [comment]
I tested both.
