### ISSUE TITLE
Are the Ubuntu Trusty binaries available?

### ISSUE THREAD

**Issue by diodon** [GeoNode/geonode#1673]
Hi, are the Trusty binaries ready, or I should try to install GeoNode following the instructions for 14.04 and compiling it from scratch?

**Comment by ramavanan** [comment]
Can u send some tutorial for geonode customization

**Comment by simod** [comment]
Hi for trusty is available the 2.4 beta. Just use the ppa:geonode/testing
instead of release.
On docs.geonode.org you will also find docs for customize it.

Ps please use the users mailing list for support in the future.

Hope this helps.

Il venerdì 17 aprile 2015, ramavanan <notifications@github.com> ha scritto:

> Can u send some tutorial for geonode customization
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94052676>.
>


-- 
Simone

**Comment by simod** [comment]
Sorry answered from mobile and did not notice it was an old ticket and not a new one.

**Comment by ramavanan** [comment]
Ok simod. but geonode 2.0 stable only available .

**Comment by ramavanan** [comment]
Shall we use this geonode application for enterprise use

**Comment by ramavanan** [comment]
lowing the instructions, I did:
$ sudo add-apt-repository ppa:geonode/release
OK
$ sudo apt-get update
OK
$ sudo apt-get install geonode
E: Unable to locate package geonode

**Comment by simod** [comment]
Geonode 2.4 is much more advanced than 2.0. I would suggest to use it and
the upgrade to the 2.4 final when released. No data model changes will be
introduced.

Il venerdì 17 aprile 2015, ramavanan <notifications@github.com> ha scritto:

> Shall we use this geonode application for enterprise use
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94054579>.
>


-- 
Simone

**Comment by simod** [comment]
Ppa:geonode/testing

Il venerdì 17 aprile 2015, Simone Dalmasso <simone.dalmasso@gmail.com> ha
scritto:

> Geonode 2.4 is much more advanced than 2.0. I would suggest to use it and
> the upgrade to the 2.4 final when released. No data model changes will be
> introduced.
>
> Il venerdì 17 aprile 2015, ramavanan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:
>
>> Shall we use this geonode application for enterprise use
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94054579>.
>>
>
>
> --
> Simone
>


-- 
Simone

**Comment by ramavanan** [comment]
simod

following the instructions, I did:
$ sudo add-apt-repository ppa:geonode/release
OK
$ sudo apt-get update
OK
$ sudo apt-get install geonode
E: Unable to locate package geonode

**Comment by ramavanan** [comment]
simod 

can u tell the instruction for geonode 2.4 Please.
Beacause i am new user for Linux platform (ubuntu)

**Comment by simod** [comment]
The ones you did are correct but use ppa:geonode/testing and not
ppa:geonode/release

Il venerdì 17 aprile 2015, ramavanan <notifications@github.com> ha scritto:

> simod
>
> can u tell the instruction for geonode 2.4 Please.
> Beacause i am new user for Linux platform (ubuntu)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94055309>.
>


-- 
Simone

**Comment by ramavanan** [comment]
Shall we use Osgeolive for Enterprise server use

**Comment by simod** [comment]
Not at all. Osgeolive is not meant for that.

Il venerdì 17 aprile 2015, ramavanan <notifications@github.com> ha scritto:

> Shall we use Osgeolive for Enterprise server use
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94055568>.
>


-- 
Simone

**Comment by ramavanan** [comment]
Pl  can u send the instalation step wise...i am using ubuntu 14.04

**Comment by ramavanan** [comment]
what about geoserver and.postgres. automatically installed from this geonode or manually install

**Comment by simod** [comment]
the procedure is this one
http://docs.geonode.org/en/master/tutorials/admin/install/quick_install.html or
the one down in this page http://geonode.org/
 but use ppa:geonode/testing instead of ppa:geonode/release. It will
install also geoserver and postgres and configure them. On the docs you can
find all the information.

2015-04-17 21:41 GMT+02:00 ramavanan <notifications@github.com>:

> what about geoserver and.postgres. automatically installed from this
> geonode or manually install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1673#issuecomment-94060239>.
>



-- 
Simone

**Comment by ramavanan** [comment]
thank you simon ..geonode working perfectly . i have another one doubt. i was install pg admin using ubuntu softtware store, but it didnt conect with postgres, can u tell the procedure for conect pgadmin & postgres

**Comment by ramavanan** [comment]
How to link geonode postgres and pgadmin

**Comment by JJediny** [comment]
These follow ups are completed unrelated to the ticket not are they appropriate for a ticket. Please start a new thread on the mailing list, and i will try to assist, but please only use a ticket for technical issues or feature requests. The mailing list is for this type of instruction and also for the benefit that the community will be aware the QA exists
geonode-users@lists.osgeo.org

**Comment by ramavanan** [comment]
everything working fine and perfectly. 
1) how to find geonode database name and password
2)how to configure pgadmin and postgres
3) customization is possible for geonode 2.4 or only 2.0

4)

**Comment by biomap** [comment]
This isn't a help desk.  If you can read the docs then please stop posting. 

http://docs.geonode.org/en/master/

**Comment by abersh** [comment]
$ sudo add-apt-repository ppa:geonode/release
OK
$ sudo apt-get update
OK
$ sudo apt-get install geonode
E: Unable to locate package geonode
What shall i do please help !!!

**Comment by simod** [comment]
@abersh if you read this thread you will find how to solve your problem.

**Comment by abersh** [comment]
sorry Simod where is the thread?

**Comment by simod** [comment]
this one where you are writing https://github.com/GeoNode/geonode/issues/1673

**Comment by abersh** [comment]
I read many times but still now it doesn't work.I use Ubuntu Trusty  and i want geonode/release

**Comment by simod** [comment]
geonode/release 2.0 is not available as installer for 14.04. Only testing. You have to do it manually.

Ps please use the mailing list geonode-users@lists.osgeo.org to ask for support

**Comment by ramavanan** [comment]
Simon , geonode is available for windows,

**Comment by abersh** [comment]
Can i use geonode/release 2.0  in Ubuntu 12.04

**Comment by abersh** [comment]
what are the disadvantage of geonode?

**Comment by simod** [comment]
STOP posting here
