### ISSUE TITLE
upload time page problems

### ISSUE THREAD

**Issue by ischneider** [GeoNode/geonode#1674]
Numerous issues discovered here:

requirejs error on page load (This appears to prevent the interval options from appearing): 

    Error: Mismatched anonymous define() module: function (){ "use strict"; return Eb} http://requirejs.org/docs/errors.html#mismatch

time attribute client form mismatch w/ server-side logic - results in time not getting configured or 500 errors

JS error when handling 500 error:

    TypeError: self.markError is not a function
    http://localhost:8000/static/geonode/js/upload/upload.js
    Line 261

**Comment by jj0hns0n** [comment]
@ischneider are we just going to abandon this implementation?

**Comment by ischneider** [comment]
Looks like #1676 was merged, so I'll close for now.

Longer term, probably should be abandoned
