### ISSUE TITLE
VPAT for 508 compliance (accessibility)

### ISSUE THREAD

**Issue by nathanhilbert** [GeoNode/geonode#1680]
The U.S. Department of State is going through a process to get GeoNode approved to run on their systems.  One component of the approval is 508 compliance.  A report was generated, and I wanted to pass it along as an initial step to have VPAT (Voluntary Product Accessibility Template) documentation from the GeoNode community.  It seems the only changes are adding alt tags to images and a logical flow without styling.  
https://s3.amazonaws.com/geonodedeps/GeoNode_IMPACT+Section+508+Product+Accessibility+Report_Form_cleaned.doc

**Comment by jj0hns0n** [comment]
@garnertb @nathanhilbert any update on this?

**Comment by nathanhilbert** [comment]
Not yet.  I should get to this in the next few weeks if @garnertb  hasn't already.

- [ ]  Logical reading order when style sheets were turned off
- [ ] Images and buttons do not have sufficient alternative text

**Comment by garnertb** [comment]
I'm not planning to work this.  Thanks for taking it, @nathanhilbert.

**Comment by jj0hns0n** [comment]
@nathanhilbert any update on this? Moving to 2.7
