### ISSUE TITLE
links to FAQ are broken

### ISSUE THREAD

**Issue by matejt** [GeoNode/geonode#1688]
On the web site: http://geonode.org/faqs.html, the links to faq do not work

**Comment by markiliffe** [comment]
It now works. Closing the issue.

**Comment by COLABORATI** [comment]
Hi, this does not seem to be solved, I still get the broken links on the FAQ page.
You might consider using linkchecker in a cronjob to monitor your website, can help you very easily to alert you about 404 links on your site. Just apt-get install linkchecker.
