### ISSUE TITLE
Custom installation fail show geotiff layer

### ISSUE THREAD

**Issue by ilpise** [GeoNode/geonode#1692]
I've installed geonode following the custom installation instructions.
I can upload shape files and the derived layer is shown correctly from the geonode platform.

When I try to upload a geotiff file the file is uploaded, I can see it inside the uploaded folder, but on the web page compare an error ' in method 'Open',argument 1 of type 'char const*' ' and the layer is not shown in the layer preview list.

On another machine installing geonode using the custom instructions but using the ubuntu shell scripts for the configuration

see

http://geonode.readthedocs.org/en/latest/tutorials/admin/install/custom_install.html#configure-using-the-ubuntu-config-file

all is working properly, the geotiff layer can be uploaded and is shown in the layer list.

No errors in the apache log.

Here is a link to an image with the error.

https://groups.google.com/group/geonode-users/attach/fdf03cd36969dfe2/image.png?part=0.1&authuser=0&view=1

**Comment by jj0hns0n** [comment]
@ilpise can you provide the image that you are trying to upload so we can test. When the demo server is back up, can you please test there as well.

**Comment by ilpise** [comment]
Hi, the image is 25MB and  is not possible to upload it here.
I will check for a smaller one or let me know how can i send the original one.
Thanks a lot.
