### ISSUE TITLE
Bootstrap responsive design

### ISSUE THREAD

**Issue by npmiller** [GeoNode/geonode#1697]
I was wondering why the bootstrap's responsive design was disabled so I tracked it down to this commit:
https://github.com/GeoNode/geonode/commit/4137e17df947021a4715c0973e3aa143cbadab2a , which doesn't give me much more information.

So can we delete this to make use of bootstrap responsiveness, and if not, why ?

**Comment by jj0hns0n** [comment]
Im going to close this issue and we should do some careful testing on mobile devices during the sprint and file any new issues with the 'responsive' label.
