### ISSUE TITLE
Update RPM package for 2.4

### ISSUE THREAD

**Issue by dwins** [GeoNode/geonode#170]
also integrate it in geonode-cloud

**Comment by jj0hns0n** [comment]
This is one of our oldest tickets, and I would really love to see an RPM package for 2.4. There was some discussion and paste on the list about this as well. I would also like to eventually make a openshift package for 2.4

**Comment by jj0hns0n** [comment]
@BerryDaniel you are on this right?

**Comment by BerryDaniel** [comment]
yep

**Comment by jj0hns0n** [comment]
@BerryDaniel we can close this now right?
