### ISSUE TITLE
Export in native projection

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#171]
Export links all re-project data to 4326. Most GIS power users I support need the data in it's original projection. It would be great to add an optional export in the original data's projection. Of course this doesn't apply to kml.

This seems mildly related to the mailing list request for download of original raster data. Though it's slightly different since I do want format conversion but without reprojection (ex: Postgis to shp in EPSG 3310)

**Comment by jj0hns0n** [comment]
Closing as this would be covered by GNIP #1421
