### ISSUE TITLE
'Clear' button only partially clears Upload Layers dialog

### ISSUE THREAD

**Issue by joebocop** [GeoNode/geonode#1718]
When uploading a layer, if the user selects a number of files, and then decides not to upload, choosing instead to click the "Clear" button, the list of files is successfully cleared, but the notation for the number of selected files fails to update, as in the attached images.
![geonode_bug1](https://cloud.githubusercontent.com/assets/1096999/4595752/dec63e4e-509c-11e4-88b4-7e38b55b7f90.PNG)
![geonode_bug2](https://cloud.githubusercontent.com/assets/1096999/4595751/dec4ae4e-509c-11e4-9e53-5efc16ad6089.PNG)

**Comment by jj0hns0n** [comment]
@ischneider are you still working on an uploader rewrite ... both back and front end?

**Comment by ischneider** [comment]
I've taken a break from it due to other demands.

**Comment by jj0hns0n** [comment]
@simod can you just make the clear button refresh the page?
