### ISSUE TITLE
some missing translation tags

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#1722]
Hello,

During testing i noticed some missing translations tags. I will propose a pull request with these new tags. (but pretty sure I'll find more missings later)

Also, i've translated and reviewed the french translation in transifex. But after this step i'm not sure if I can help or just waiting, to push the new po/pot ?

Thanks,

julien

**Comment by gannebamm** [comment]
Found some more missing `_` for from `django.utils.translation import ugettext as _`
eg. in:
geonode\layers\views.py l1463 `return HttpResponse('Thumbnail saved')`
