### ISSUE TITLE
Metadata for private layers should be consistent with layer permissions

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#1726]
If a user cannot see a layer because it is private for him, he should not be able to consult its metadata as well.
GeoNode (and pycsw or GeoNetwork) should be consistent with the layer permissions assigned in the "Who can view and download this data?" session in the layer permissions form. Therefore the CSW GetRecordById should be restricted only to permitted users.
As far as I can see pycsw transactions are not implemented in the pycsw instance that comes with GeoNode, but in case they will be implemented at some point they will need to respect the "Who can manage" session in the layer permissions form (that should be "can edit metadata" in the next granular permission system). Same if the GN administrator would use GeoNetwork as the catalog engine.
I hope we will not end up with a GN plugin for pycsw similiar to the GeoServer plugin, but I cannot see a better way to handle this.

**Comment by pjdufour** [comment]
@capooti, any update on this?  What still needs to be done?  We're just beginning to integrate CKAN and GeoNode.  We need the CSW endpoint to do a perms check.  Otherwise, we'll be unable to stage layers as private on our site before making public.  Right now the CKAN harvest grabs everything (including private layers).  I can probably find some time to work on this over the next couple weeks.

**Comment by capooti** [comment]
we have the following two permissions that are related to metadata at some extent:

view_resourcebase
change_resourcebase_metadata

In the first case from GeoNode the user cannot see the layer, therefore won't have access to the "download metadata" button. But we need to have pycsw and geonetwork be consistent with this (the user could figure out the metadata link).
In the second case, the "edit metadata" button is not showed in GeoNode if the user hasn't the change_resourcebase_metadata permission on that layer. But we need to disable transactions geonetwork.

**Comment by tomkralidis** [comment]
For pycsw access logic to 'check for public' is required in https://github.com/geopython/pycsw/blob/master/pycsw/plugins/repository/geonode/geonode_.py to only advertise 'public' layers I'm guessing?

I think for GeoNetwork transactions are not necessarily disabled, yet available to a given auth level.  The GeoNode connection to GeoNetwork usually has admin privs to enable synchronization, etc.  So it might be easier to check permissions before doing GeoNetwork CSW-T and throw error upstream.

**Comment by capooti** [comment]
@tomkralidis what about checking if the user (request.user) has view_resourcebase permission on the resource of the given uuid (request.GET.id) here:
https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/views.py#L38

**Comment by tomkralidis** [comment]
@capooti if we did this at https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/views.py#L38, then this would apply to the entire CSW I think? This needs to be done deeper within the pycsw plugin where the actual data binding happens?

**Comment by capooti** [comment]
maype in pycsw_local CatalogueBackend methods then?

**Comment by tomkralidis** [comment]
@capooti: have a look at
https://github.com/geopython/pycsw/blob/master/pycsw/plugins/repository/geonode/geonode_.py#L37,
this is where the actual data binding takes place:
https://github.com/geopython/pycsw/blob/master/pycsw/plugins/repository/geonode/geonode_.py#L124
(basic non-filtered query against GeoNode repository).  Here we would have
to add hooks to ensure the layer is 'public'.

**Comment by capooti** [comment]
thanks @tomkralidis. BTW how can we check which user is requesting the metadata? if there is a private layers for a given user, the metadata should be accessible to that user, even if the layer is not public.

**Comment by tomkralidis** [comment]
FYI see #2332 which will provide an `is_published` mask atop GeoNode repositories.  Does #2332 cover this issue / is this enough?

**Comment by jondoig** [comment]
No @tomkralidis #2332 filters CSW to show only [published](http://docs.geonode.org/en/master/reference/security.html#publishing-and-unpublishing-objects) resources (those with 'Is published' box ticked, if Geonode's RESOURCE_PUBLISHING setting is True) but that is not to be confused with public resources - those which 'Anyone' can view (under Set permissions).

**Comment by jondoig** [comment]
Has this been fixed in 2.6 or later?

**Comment by capooti** [comment]
Unfortunately not. Not fixed for 2.6 and in current master. That is why this ticket is still open

**Comment by davicustodio** [comment]
@tomkralidis I'm testing using the Issue # 2332 filter setting in Geonode 2.4, and putting some layers with is_published = false. After that I am invoking http://myserver/catalog/csw? Request = GetRecords&service=CSW&version=2.0.2&resultType=results&outputSchema=http://www.isotc211.org/2005/gmd&typeNames=csw:Record&elementSetName=full and waiting no more view these layers marked with false, but unfortunately they continue to appear in the response xml. Am I forgetting to adjust anything else to make it work?
