### ISSUE TITLE
Unknown language code tl

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#1727]
Hello,

I'm testing the last po-file (fr) extracted from transifex (i've finished fr master translation). Thanks for syncing transifex against the project :)

I builded a testing env. against the newest geonode master and now geonode is raising an error  Unknown language code "tl" (from /django/utils/translation/**init**.py)
Seems to be a new langage supported, but I don't understand why it'is not recognizing it ?
Sure i'm missing something in the installation process ?

thanks,

julien

**Comment by abersh** [comment]
I want to geonode language localize any one please help or recommend videos or other resorce
