### ISSUE TITLE
People page display too much information.

### ISSUE THREAD

**Issue by ghost** [GeoNode/geonode#1728]
People page display too much information (private information)

Use case:
With a connected user, upload a new layer and give him permission only for this user.
Disconnect and go to the People page.
You can see here a layer for the previous user.
![l](https://cloud.githubusercontent.com/assets/6358004/4717321/70b8f606-5913-11e4-8a04-a629e408130f.jpg)

Click on the layer link.
Here, Geonode try to show you the layer.
![l2](https://cloud.githubusercontent.com/assets/6358004/4717322/7a2bacf6-5913-11e4-857e-376647a1f04a.jpg)

Now click again on the layer:
If you are not connected, the login page appears.
If you are already connected with another account who doesn’t have permission to see the layer, you catch an infinity redirecting exception.

**Comment by rajanski** [comment]
Hi, on geonode 2.0.1 , there is still too much informationon people plus their content on the peoples page shown to "everyone", i.e. without login. Is that fixed in 2.4 ?

Best
R
