### ISSUE TITLE
Can we upload and view 3D data in the 3D GE view of GeoNode?

### ISSUE THREAD

**Issue by smoothbadger** [GeoNode/geonode#1751]
I would really like to be able to upload and view 3D in geonode when you switch to the 3D Google Earth view.  I'm not sure what format would be the most appropriate but seeing as it uses Google Earth then maybe the 3D kml (like the ones you can download in sketchup)

I believe ESRI are looking at the ability to use 3D data in ArcGIS online and many organisations are now using 3D data along with Building Information Modelling (BIM).

What are the format restrictions for uploading data, does it take geodatabase files?  Would there be any option for accepting CAD files or will it always be restricted to shapefiles?
Many thanks

**Comment by jj0hns0n** [comment]
Sorry no, we cant. You could use the Google Earth plugin to try this out
