### ISSUE TITLE
Remote services issues

### ISSUE THREAD

**Issue by vytj** [GeoNode/geonode#1752]
Hello,

Tried to test remote services - for that, i have working Geonode 2.0.1 on my internal network (and it is included in PROXY_ALLOWED_HOSTS) and upgraded Geonode from 2.4a6 to 2.4a16. 

.1. Auto detect. Put my local server address http://www.testgeonode.info in "Service URL" - got error
Importing service, please wait...
ValueError at /services/register/ No JSON object could be decoded Request Method: POST Request URL: http://192.168.100.11/services/register/ Django Version: 1.6.1 Python Executable: /usr/bin/python Python Version: 2.7.6 Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7'] Server time: Wed, 29 Oct 2014 08:10:01 -0500 Installed Applications: ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.admin', 'django.contrib.sitemaps', 'django.contrib.staticfiles', 'django.contrib.messages', 'django.contrib.humanize', 'django.contrib.gis', 'pagination', 'taggit', 'taggit_templatetags', 'friendlytagloader', 'geoexplorer', 'leaflet', 'django_extensions', 'autocomplete_light', 'mptt', 'modeltranslation', 'pinax_theme_bootstrap_account', 'pinax_theme_bootstrap', 'django_forms_bootstrap', 'account', 'avatar', 'dialogos', 'agon_ratings', 'notification', 'announcements', 'actstream', 'user_messages', 'tastypie', 'polymorphic', 'guardian', 'geonode.people', 'geonode.base', 'geonode.layers', 'geonode.maps', 'geonode.proxy', 'geonode.security', 'geonode.social', 'geonode.catalogue', 'geonode.documents', 'geonode.api', 'geonode.groups', 'geonode.services', 'geonode.geoserver', 'geonode.upload') Installed Middleware: ('django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.locale.LocaleMiddleware', 'pagination.middleware.PaginationMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware') Traceback: File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response 112. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view 22. return view_func(request, *args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in register_service 110. type, server = _verify_service_type(url) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in _verify_service_type 233. service.services File "/usr/lib/python2.7/dist-packages/arcrest/server.py" in services 480. in self._json_struct.get('services', [])] File "/usr/lib/python2.7/dist-packages/arcrest/server.py" in _json_struct 268. .strip() or '{}') File "/usr/lib/python2.7/json/__init__.py" in loads 338. return _default_decoder.decode(s) File "/usr/lib/python2.7/json/decoder.py" in decode 366. obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python2.7/json/decoder.py" in raw_decode 384. raise ValueError("No JSON object could be decoded") Exception Type: ValueError at /services/register/ Exception Value: No JSON object could be decoded Request information: GET: No GET data POST: url = u'http://www.testgeonode.info' csrfmiddlewaretoken = u'4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' type = u'AUTO' FILES: No FILES data COOKIES: csrftoken = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' sessionid = 'sd727fqqm1t9r75i6coj25v587ca497i' META: mod_wsgi.listener_port = '80' HTTP_REFERER = 'http://192.168.100.11/services/register/' mod_wsgi.listener_host = '' mod_wsgi.handler_script = '' CONTEXT_DOCUMENT_ROOT = '/var/www' SERVER_SOFTWARE = 'Apache/2.4.7 (Ubuntu)' SCRIPT_NAME = u'' mod_wsgi.enable_sendfile = '0' HTTP_X_CSRFTOKEN = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' SERVER_SIGNATURE = '
Apache/2.4.7 (Ubuntu) Server at 192.168.100.11 Port 80

----------------------------------------------------------------------------------------------------------------------
.2. Same address as before (http://www.testgeonode.info), chose "Web Map Service". Got error:
Importing service, please wait...
XMLSyntaxError at /services/register/ Opening and ending tag mismatch: meta line 5 and head, line 20, column 10 Request Method: POST Request URL: http://192.168.100.11/services/register/ Django Version: 1.6.1 Python Executable: /usr/bin/python Python Version: 2.7.6 Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7'] Server time: Wed, 29 Oct 2014 08:35:35 -0500 Installed Applications: ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.admin', 'django.contrib.sitemaps', 'django.contrib.staticfiles', 'django.contrib.messages', 'django.contrib.humanize', 'django.contrib.gis', 'pagination', 'taggit', 'taggit_templatetags', 'friendlytagloader', 'geoexplorer', 'leaflet', 'django_extensions', 'autocomplete_light', 'mptt', 'modeltranslation', 'pinax_theme_bootstrap_account', 'pinax_theme_bootstrap', 'django_forms_bootstrap', 'account', 'avatar', 'dialogos', 'agon_ratings', 'notification', 'announcements', 'actstream', 'user_messages', 'tastypie', 'polymorphic', 'guardian', 'geonode.people', 'geonode.base', 'geonode.layers', 'geonode.maps', 'geonode.proxy', 'geonode.security', 'geonode.social', 'geonode.catalogue', 'geonode.documents', 'geonode.api', 'geonode.groups', 'geonode.services', 'geonode.geoserver', 'geonode.upload') Installed Middleware: ('django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.locale.LocaleMiddleware', 'pagination.middleware.PaginationMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware') Traceback: File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response 112. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view 22. return view_func(request, *args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in register_service 123. return _process_wms_service(url, type, user, password, wms=server, owner=request.user) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in _process_wms_service 257. wms = WebMapService(url) File "/usr/lib/python2.7/dist-packages/owslib/wms.py" in __init__ 77. self._capabilities = reader.read(self.url) File "/usr/lib/python2.7/dist-packages/owslib/wms.py" in read 615. return etree.fromstring(u.read()) Exception Type: XMLSyntaxError at /services/register/ Exception Value: Opening and ending tag mismatch: meta line 5 and head, line 20, column 10 Request information: GET: No GET data POST: url = u'http://www.testgeonode.info' csrfmiddlewaretoken = u'4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' type = u'WMS' FILES: No FILES data COOKIES: csrftoken = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' sessionid = 'sd727fqqm1t9r75i6coj25v587ca497i' META: mod_wsgi.listener_port = '80' HTTP_REFERER = 'http://192.168.100.11/services/register/' mod_wsgi.listener_host = '' mod_wsgi.handler_script = '' CONTEXT_DOCUMENT_ROOT = '/var/www' SERVER_SOFTWARE = 'Apache/2.4.7 (Ubuntu)' SCRIPT_NAME = u'' mod_wsgi.enable_sendfile = '0' HTTP_X_CSRFTOKEN = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' SERVER_SIGNATURE = '
Apache/2.4.7 (Ubuntu) Server at 192.168.100.11 Port 80

----------------------------------------------------------------------------------------------------------------------
.3. Same address as before (http://www.testgeonode.info), chose "Catalogue Service". Got error:
Importing service, please wait...
HTTPError at /services/register/ HTTP Error 403: FORBIDDEN Request Method: POST Request URL: http://192.168.100.11/services/register/ Django Version: 1.6.1 Python Executable: /usr/bin/python Python Version: 2.7.6 Python Path: ['/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7'] Server time: Wed, 29 Oct 2014 08:51:04 -0500 Installed Applications: ('django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.sites', 'django.contrib.admin', 'django.contrib.sitemaps', 'django.contrib.staticfiles', 'django.contrib.messages', 'django.contrib.humanize', 'django.contrib.gis', 'pagination', 'taggit', 'taggit_templatetags', 'friendlytagloader', 'geoexplorer', 'leaflet', 'django_extensions', 'autocomplete_light', 'mptt', 'modeltranslation', 'pinax_theme_bootstrap_account', 'pinax_theme_bootstrap', 'django_forms_bootstrap', 'account', 'avatar', 'dialogos', 'agon_ratings', 'notification', 'announcements', 'actstream', 'user_messages', 'tastypie', 'polymorphic', 'guardian', 'geonode.people', 'geonode.base', 'geonode.layers', 'geonode.maps', 'geonode.proxy', 'geonode.security', 'geonode.social', 'geonode.catalogue', 'geonode.documents', 'geonode.api', 'geonode.groups', 'geonode.services', 'geonode.geoserver', 'geonode.upload') Installed Middleware: ('django.middleware.common.CommonMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.messages.middleware.MessageMiddleware', 'django.middleware.locale.LocaleMiddleware', 'pagination.middleware.PaginationMiddleware', 'django.middleware.csrf.CsrfViewMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware') Traceback: File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response 112. response = wrapped_callback(request, *callback_args, **callback_kwargs) File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view 22. return view_func(request, *args, **kwargs) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in register_service 127. return _register_harvested_service(url, user, password, owner=request.user) File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py" in _register_harvested_service 692. csw = CatalogueServiceWeb(url) File "/usr/lib/python2.7/dist-packages/owslib/csw.py" in __init__ 72. self._invoke() File "/usr/lib/python2.7/dist-packages/owslib/csw.py" in _invoke 573. self.response = util.http_post(self.url, self.request, self.lang, self.timeout) File "/usr/lib/python2.7/dist-packages/owslib/util.py" in http_post 270. up = urllib2.urlopen(r,timeout=timeout); File "/usr/lib/python2.7/urllib2.py" in urlopen 127. return _opener.open(url, data, timeout) File "/usr/lib/python2.7/urllib2.py" in open 410. response = meth(req, response) File "/usr/lib/python2.7/urllib2.py" in http_response 523. 'http', request, response, code, msg, hdrs) File "/usr/lib/python2.7/urllib2.py" in error 448. return self._call_chain(*args) File "/usr/lib/python2.7/urllib2.py" in _call_chain 382. result = func(*args) File "/usr/lib/python2.7/urllib2.py" in http_error_default 531. raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) Exception Type: HTTPError at /services/register/ Exception Value: HTTP Error 403: FORBIDDEN Request information: GET: No GET data POST: url = u'http://www.testgeonode.info' csrfmiddlewaretoken = u'4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' type = u'CSW' FILES: No FILES data COOKIES: csrftoken = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' sessionid = 'sd727fqqm1t9r75i6coj25v587ca497i' META: mod_wsgi.listener_port = '80' HTTP_REFERER = 'http://192.168.100.11/services/register/' mod_wsgi.listener_host = '' mod_wsgi.handler_script = '' CONTEXT_DOCUMENT_ROOT = '/var/www' SERVER_SOFTWARE = 'Apache/2.4.7 (Ubuntu)' SCRIPT_NAME = u'' mod_wsgi.enable_sendfile = '0' HTTP_X_CSRFTOKEN = '4uVFoqvW5ajmCSNeXkBfDESAps8tEYad' SERVER_SIGNATURE = '
Apache/2.4.7 (Ubuntu) Server at 192.168.100.11 Port 80

----------------------------------------------------------------------------------------------------------------------
.4. Changed address to http://www.testgeonode.info/geoserver/wms, chose "Web Map Service". Layers were imported, however, all metadata not present in Geoserver was lost. Also, no maps were imported. 

Is there any way to add data from configured Geonode site?

**Comment by jj0hns0n** [comment]
Ill look into this during the sprint.

**Comment by jj0hns0n** [comment]
@tomkralidis can you take a look at this one?

**Comment by tomkralidis** [comment]
This was fixed in https://github.com/geopython/OWSLib/commit/253382853d95778134ac2f1c1639d903e0031f50

**Comment by Adriana-Martinez** [comment]
Hi !!
I dont can to add remote service Arcgis Map Server

![Presentación1](https://user-images.githubusercontent.com/55162147/89908894-18822500-dbb4-11ea-8348-e2ed3586c299.jpg)
