### ISSUE TITLE
Layer with error during upload was not removed.

### ISSUE THREAD

**Issue by RaphaelGeode** [GeoNode/geonode#1753]
Layer with error during upload was not removed from uploaded layers directory.  (Working on version 2.4a17 and Master)

Use case:
- Try to upload a layer shapefile with error in it.
- Geonode detect the error (that’s cool).
- Looking into geonode/uploaded/layers/ directory and you can see some files from the failed layer upload.

I think this was not a bug but can be considered like an enhancement to remove these files.

**Comment by jj0hns0n** [comment]
This should be easy enough to do some cleanup here.

**Comment by menegon** [comment]
I try to fix it
