### ISSUE TITLE
Unusable manage styles page

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1762]
There seem to be CSS problems and I cannot interact with the widget at all.

Using Ubuntu 14.04 and GeoNode 2.4 alpha 21.

![screen shot 2014-11-06 at 12 22 26](https://cloud.githubusercontent.com/assets/9592424/4940345/9d425712-65d9-11e4-89a8-55f246ade8af.png)

**Comment by simod** [comment]
closing as fixed
