### ISSUE TITLE
AWS S3 / Document Storage

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1766]
GeoNode should be able to use Amazon Web Services (AWS) Simple Storage Service (S3) as a backend object store.  It would be particularly useful capability to use S3 for storage of documents.  There wouldn't be direct user access to backend S3 buckets.  GeoNode would read from S3 and write to the HTTP response.  This would increase scalability, redundancy, and facilitate migration of production deployments.

Abstraction should be built-in so other object stores can be considered in the long-term as well.

The AWS S3 API is exposed through boto (a python interface).

Related Links:
http://aws.amazon.com/s3/
https://github.com/boto/boto

**Comment by jj0hns0n** [comment]
We should document this in the docs.

**Comment by capooti** [comment]
I guess after documenting it we can close it?

**Comment by JJediny** [comment]
just noticed [django-extensions] set of manage.py commands include `sync_media_s3` and sync_s3`. Could be useful if admin was interested enough to setup a cron job

**Comment by jj0hns0n** [comment]
@BerryDaniel didnt you guys do some work on this? Moving to 2.7 anyway.
