### ISSUE TITLE
Use ngCloak directive on /layers/

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1768]
The ngCloak directive is used to prevent the Angular html template from being briefly displayed by the browser in its raw (uncompiled) form while your application is loading. Use this directive to avoid the undesirable flicker effect caused by the html template display.

https://docs.angularjs.org/api/ng/directive/ngCloak

**Comment by capooti** [comment]
I am still experiencing problem with this (can be seen also from the demo site). Any update?
