### ISSUE TITLE
Unavailable to translate 

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1769]
--In the spanish version still showing some text in english and there's no option to translate that:
In the Document tab "DOCUMENT TYPE" "Enter your text here..." and "pages"
![fullsizerender](https://cloud.githubusercontent.com/assets/9592424/5059192/aae6fcb2-6cdf-11e4-9086-56ae32557865.jpg)

--Also in People tab show some text below the username unavailable to translate "Layers" "Maps" "Documents"
![fullsizerender 1](https://cloud.githubusercontent.com/assets/9592424/5059212/2919fd82-6ce0-11e4-8e7f-ddc2a73c7847.jpg)

--When i try to log me in and click on forgot yor password button, it says "If you have any trouble resetting your password, contact us at ." at where?? i'm showing the spanish version.
![fullsizerender 2](https://cloud.githubusercontent.com/assets/9592424/5059227/13d55c36-6ce1-11e4-930b-e12285837d16.jpg)

--Unavailable to translate "Choosen File" and "No file chosen"
![fullsizerender 3](https://cloud.githubusercontent.com/assets/9592424/5059237/b04a1b24-6ce1-11e4-91f4-3670466d2c5e.jpg)

--In the Layers tab, below the name of any layer, everything appears in english no matter which language i choose
![img_5024](https://cloud.githubusercontent.com/assets/9592424/5059241/e567b258-6ce1-11e4-8227-199af64b0e88.JPG)

**Comment by jj0hns0n** [comment]
We should check that all strings are translatable and then make sure that at least one translation is complete so we can verify this. We used the chinese one in the past, but its probably no longer complete.  @nathan-wang can perhaps help us.

**Comment by jj0hns0n** [comment]
@teamgeode can you guys take a look at these strings?

**Comment by collaer** [comment]
Hello,
We can look at that today. But before doing something i would like to talk about translations, I think there are differents issues to solve : 
 * in the master : identify when to push into transifex new strings to be translated and doing the push (hook possible?)
 * in a release tag : what to do ? just keeping fully completed translations languages ?
 * There are languages configured with < 5% translations, remove and cleaning them ?
 * check and ensure that every string is using gettext in the code
 * ...
