### ISSUE TITLE
Attribute alias, visibility and order

### ISSUE THREAD

**Issue by AnnalisaS** [GeoNode/geonode#1770]
If I modify label of a layer's attribute from "edit metadata", changes are seen in attribute tab, under layer's preview, but not when I query the layer with "Get Feature Info" tool.
Otherwise, if I modify labels from administrative panel, changes are correctly viewed also with "Get Feature Info" tool.
Visibility and order, available only from administrative panel, instead seems to not affect the attribute tab. It's correct?

Using Ubuntu 12.04 and GeoNode 2.0

**Comment by jj0hns0n** [comment]
@mbertrand do you know how this is supposed to work in geoexplorer?

**Comment by mbertrand** [comment]
@jjohns0n, I think this was handled by the [GXP FeatureGrid widget](https://github.com/boundlessgeo/gxp/blob/master/src/script/widgets/grid/FeatureGrid.js#L244) in conjunction with the maplayer configuration.

**Comment by capooti** [comment]
I confirm, this is not working in GeoExplorer.
What we need to do here is:
* have GeoExplorer honor the field label and order
* implement the UI checkbox for the visible field in the attribute model, and have GeoExplorer honor it as well

**Comment by capooti** [comment]
GeoExplorer does not honor the field order (I can fix it).

I would also need to have the is_visible attribute for my instance in the attribute model. Am I too late for a schema changes in 2.6? I can provide a PR ASAP.
Thanks
