### ISSUE TITLE
Some style and lack of info 

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1773]
No space below the email cell and also there's no info to contact someone if there's a problem resetting a password.

![screen shot 2014-11-17 at 9 13 08](https://cloud.githubusercontent.com/assets/9592424/5070936/1832f05e-6e3a-11e4-9d78-ac1415e9087a.png)

**Comment by jj0hns0n** [comment]
This should use the admin email from settings.py https://docs.djangoproject.com/en/1.7/ref/settings/#std:setting-ADMINS

We currently have this https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L447 but should add the normal ADMINS block in local_settings.py.sample
