### ISSUE TITLE
No limit when dragging the mini map 

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1774]
In the layers tab, map tab and documents tab, it should shows the mini map again instead of a blank space --I'm working on 2.4a30 version on Chrome--

![screen shot 2014-11-17 at 9 22 59](https://cloud.githubusercontent.com/assets/9592424/5071063/86500abc-6e3b-11e4-9e09-111046e57a3f.png)

**Comment by jj0hns0n** [comment]
@al3mon Im not sure I understand the issue here. Can you clarify?

**Comment by jj0hns0n** [comment]
@lenninslad this is something you could work on while working on the extent filter.
