### ISSUE TITLE
No content when click on the ''About'' link in the footer of the page.

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1775]
--Using Chrome--

![screen shot 2014-11-17 at 9 36 56](https://cloud.githubusercontent.com/assets/9592424/5071289/506fbd6e-6e3d-11e4-9abc-209d8e5b7864.png)

**Comment by jj0hns0n** [comment]
This should just reuse some content from geonode.org or the docs and there should be some documentation to explain how to override it when installed from packages or when using the template project.
