### ISSUE TITLE
Problem uploading layers

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1776]
--When uploading a layer, when someone upload some files and then press the Clear Button, and dragging new layer to upload, nothing happen when click on the Upload Files Button.-- Working on 2.4a30 version

![screen shot 2014-11-17 at 9 58 55](https://cloud.githubusercontent.com/assets/9592424/5071654/c128309c-6e40-11e4-8eb5-6d10d91abf43.png)

**Comment by jj0hns0n** [comment]
Yeah, I believe a full page reload should be forced once an upload is successful. I've also found that clicking clear and starting a new upload doesn't work consistently if at all. We should just force a full page reload here.
