### ISSUE TITLE
Print button not working 

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1779]
--When i go to Maps and press the "Print Button" Nothing happen -- Working on 2.4a30 version on Chrome.

![no imprime](https://cloud.githubusercontent.com/assets/9592424/5078773/4c0e506a-6e7d-11e4-91ac-3ef24d8b17e1.png)

**Comment by jj0hns0n** [comment]
Here is a more complete stack trace. @bartvde any ideas on this one?

![developer_tools_-_http___localhost_8000_maps_17](https://cloud.githubusercontent.com/assets/506078/6017656/82b53610-ab90-11e4-9c58-cd6d51d7349f.png)

**Comment by bartvde** [comment]
would need to see the error in the debug version of GeoExplorer to make any sense out of it ;-)

Or ability to debug somewhere online?

**Comment by simod** [comment]
is just on map detail page.

**Comment by simod** [comment]
@bartvde http://demo.geonode.org/ is on line from today :)

**Comment by bartvde** [comment]
but no maps on there as yet @simod ?

**Comment by simod** [comment]
@bartvde hem... we are redeploying the latest beta and you'll be able to upload layers in it shortly. :)

**Comment by bartvde** [comment]
okay let me know when you have something for me to look at

**Comment by simod** [comment]
@bartvde http://demo.geonode.org/maps/2 ^^

**Comment by bartvde** [comment]
just a quick question, how do you expect this to work when you pass in an empty string for the print service?

printService: "",

**Comment by simod** [comment]
@bartvde ....we apologize...we realized that the template used for map detail did not have the print service configured. Thanks for your time :)

**Comment by bartvde** [comment]
np :-)
