### ISSUE TITLE
Private group showing info without being logged in.

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1784]
--Without being logged in, i can see all the info concerning the group but i created it as Private, and i think it shouldn't.--

![info without log in](https://cloud.githubusercontent.com/assets/9592424/5079399/1308086a-6e82-11e4-8758-1a6292da0707.png)

**Comment by alesarrett** [comment]
My suggestion here would be to move the rework suggested by state-hiu to the 2.5 milestone and to keep the correction of the current problem (visibility of private groups) in the 2.4.
This with the aim to accelerate the solution of an (hopefully) easier issue and to postpone a more wider but complex solution to next version.

**Comment by jj0hns0n** [comment]
@sarasafavi can you take a crack at this one. Its still occurring on master and should be a super easy fix.

**Comment by capooti** [comment]
With reference to the issue subject, as an authenticated user, right now:
* I can see all the public groups and the users belonging to them
* I cannot see any private group

Therefore I believe we can close this.
