### ISSUE TITLE
Dragging slider not working for Zoom

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1787]
--When i drag the slider button trying to zoom, it desn't work. Also when i click on this slider and i release the click, if i move the cursor upside out of the window, the slider increase the zoom A Lot, and when i move the cursor downside out of the window, the zoom get totally decrease.--

![problem dragging the zoon button](https://cloud.githubusercontent.com/assets/9592424/5079695/ddb5967a-6e84-11e4-99bc-228373173f8f.png)

**Comment by jj0hns0n** [comment]
@simod I also find no issue here. Should we just close this?
