### ISSUE TITLE
The ''Query'' option when creating a maps.

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1788]
--When creating a map and click on the "Identify" icon, it shows me the info, but when i click on it again, still showing me the info instead of hide it again.--

![creating maps identify showed](https://cloud.githubusercontent.com/assets/9592424/5079870/e9d2bfa8-6e86-11e4-898e-527be5744456.png)

**Comment by jj0hns0n** [comment]
Can we close this one @al3mon and @simod ?
