### ISSUE TITLE
Showing info instead of aut-download it

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1789]
When clicking on Download Web Map Context it opens another tab showing the info insted of download it as it says in the option. The same happen when trying to download metadata. The  expected is a download, not a new tab showing a message saying that the page has not style   :)

![web map](https://cloud.githubusercontent.com/assets/9592424/5080020/8e573abc-6e88-11e4-99b4-39f7edfa3ec2.png)

![screen shot 2014-11-17 at 18 38 14](https://cloud.githubusercontent.com/assets/9592424/5080045/f4789cd2-6e88-11e4-8d13-62375f732cbe.png)

**Comment by jj0hns0n** [comment]
This should really be "Copy URL" with a popover. The way this is used is to copy the URL and paste it into ArcMap or QGIS or some other system. I don't think we can set the mime type to force it to open in a program.
