### ISSUE TITLE
No confirmation when changing password.

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1790]
--I think it should shows a confirmation after changing a password, just for the user to be sure that it was successfuly changed--

![change pass1](https://cloud.githubusercontent.com/assets/9592424/5080160/6240bbfe-6e8a-11e4-8bb7-ec3057a10b27.png)

![change pass 2](https://cloud.githubusercontent.com/assets/9592424/5080165/65eb16a0-6e8a-11e4-9d26-2cfcef42d5de.png)

**Comment by t-book** [comment]
@afabiani I think this issue can be closed [as it´s in 2.7](https://github.com/GeoNode/geonode/blob/2.7.x/geonode/templates/account/password_reset_from_key_done.html#L7)?

**Comment by afabiani** [comment]
yeps, closed

![image](https://user-images.githubusercontent.com/1278021/46019027-7a7a3400-c0db-11e8-9a12-1f282d7c47d3.png)
