### ISSUE TITLE
No confirmation after setting up permissions

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1791]
--After uploading a layer, i set up permissions but there's not any "Apply Changes" button and there's no any confirmation after applying the permissions.--

![permissions 2](https://cloud.githubusercontent.com/assets/9592424/5080208/031b9544-6e8b-11e4-869e-7c6a77ef01cc.png)

**Comment by jj0hns0n** [comment]
@simod I think this was implemented right?
