### ISSUE TITLE
"Info" not working properly on Maps

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1793]
--I think there's something wrong when someone click on the info button and then click ok the map, because sometimes it shows the info, but sometimes it doesn't, i had to click several times to see the info.--

![info molestia](https://cloud.githubusercontent.com/assets/9592424/5080347/9b8d2436-6e8c-11e4-8273-776d59984ea7.png)

**Comment by simod** [comment]
I can't replicate this one

**Comment by jj0hns0n** [comment]
This is working for us. Closing
