### ISSUE TITLE
Layer not being displayed properly in 2.4 a31

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1795]
I found the following problems when trying to edit a layer with the latest alpha:

- [x] The map was not centered on the layer extent.
- [x] The layer was not shown on the map, even when centered manually
- [ ] The Edit Layer popover did not go away after clicking 'Edit Style'
- [x] Updating the style did not update the map (still nothing is seen) and the user cannot know if the operation was successful.

Apart from those issues, it is inconvenient to have to click twice in order to find the Edit Style link, this used to be a one click operation and I do not think anything is improved by hiding it.

**Comment by jj0hns0n** [comment]
@ingenieroariel can you test this. I believe we fixed this together. I did some further tweaking on ebolageonode to still support remote layers. We should look at the diff there and commit upstream. 

cc @mbertrand
