### ISSUE TITLE
Enabled png8 caching by default in GeoWebCache

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1798]
The viewer is configured to use it in a few places. That was not being cached properly.

**Comment by jj0hns0n** [comment]
@ingenieroariel any update on this?

**Comment by ingenieroariel** [comment]
The reason this is important is because even though GWC is enabled in some servers, the javascript client is requesting tiles that are not cached at all.

**Comment by afabiani** [comment]
I guess updating the GeoServer Caching Defaults would solve the issue

![image](https://cloud.githubusercontent.com/assets/1278021/8825522/2267ea9e-3080-11e5-950f-c719c959fd44.png)

**Comment by jj0hns0n** [comment]
Is it possible to do this by default in the build. Not sure where in the
catalog (data/gwc/geowebcache.xml?) to change this, but seems it should be
on by default.

**Comment by afabiani** [comment]
I'm going to fix this into the geoserver-geonode-ext data dir
