### ISSUE TITLE
Search Content - Order Keywords

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1805]
On the search pages (/search, /layers, /maps, and /documents), the keywords are not ordered on the leftside.  To filter by specific keywords, users are left scrolling through the large list or using the native browser search to find the right keyword to click on.  One of our current projects has almost 50 keywords.  It'll probably hit 100 within a few weeks.  At the very least, the keywords should be filtered alphabetically like the categories.  Optimally, we should have two buttons to toggle between ordering keywords alphabetically and by count.

**Comment by jj0hns0n** [comment]
@simod can we close this?
