### ISSUE TITLE
Prefetch / Prerender Content (including Thumbnails)

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1806]
We should investigate opportunities for prefetching and prerending content.  Please see the links below for more information or find an article on your favorite web developer blog.
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ
- https://developers.google.com/chrome/whitepapers/prerender?csw=1

With prerending we can potentially speed up the transition from `search page --> detail page` if we are highly confident of user intentions based on resourcebase views.  With prefetching, we can also improve the scrolling-pagination experience by prefetching thumbnails for the next page.  This will decrease the flashing nature of scrolling ahead and waiting for the brower to catch up.

**Comment by jj0hns0n** [comment]
@BerryDaniel didnt you guys do some work on this. Moving to 2.7 anyway.
