### ISSUE TITLE
''Selecting''  //Layers// //Maps// //Documents// //People// //Groups// not working properly

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1814]
--When i have the window maximized, no problem, And...

![1](https://cloud.githubusercontent.com/assets/9592424/5130324/ab691e8c-70b7-11e4-8bf1-7d42de3da708.png)

--When i have the windows minimized no problem, But...

![2](https://cloud.githubusercontent.com/assets/9592424/5130327/b014f9c4-70b7-11e4-9f67-bc06e9c906d9.png)

--When i drag a side of the window and try to reduce it just a little bit, i can not select any option ''Layers, Maps, Documents, People, Groups'' if i put the cursor upon one of those options. In order to select one of those options i need to put the cursor below of the option i want to chose.

![3](https://cloud.githubusercontent.com/assets/9592424/5130329/b4d7269e-70b7-11e4-845d-fcb7605a0a51.png)

/** Using 2.4b2 version on Chrome **/

**Comment by ppasq** [comment]
Tested on Beta 17 and it doesn't happen anymore
