### ISSUE TITLE
New layer list page (/layers) on 2.4b1 is missing information that were there in 2.0

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1815]
Here are the elements missing:
- name of the uploader is missing (it should actually be the actual name instead of the username as it is not very clear; full name should be required to create an account)
- the abstract is truncated. There should be no limit or if there is a limit there should be a way to extend it to see the entire abstract (otherwise, the user has to download the metadata)
- date of when the layer was uploaded is missing
- there is no longer a download button, there should be one on each layer like before (if permitted); and maybe there should be a button at the top to download all selected layers? 
- I don't understand what the second icons (looking like a calendar) supposed to do? Just link to the layer page? The title and the eye already do that.
- At first, it is not very clear what the select tool is for. It would be good to change the button at the top to somethink like "Change permissions for selected layers" 
- the "Set permissions" and the "Upload layer" button are not aligned and it looks a bit off.

![image](https://cloud.githubusercontent.com/assets/1036189/5132984/36152dca-70cf-11e4-8f7f-e609902c835a.png)

![image](https://cloud.githubusercontent.com/assets/1036189/5132836/40a0c3e0-70ce-11e4-9825-222de6ebfff5.png)

**Comment by jj0hns0n** [comment]
@simod I think we can close this now? Please close if so.
