### ISSUE TITLE
Menu is hiding the main page content if the screen resolution does not fit the whole menu

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1816]
For instance:

![image](https://cloud.githubusercontent.com/assets/1036189/5133178/d8a97af4-70d0-11e4-9998-4caf43315ae9.png)

![image](https://cloud.githubusercontent.com/assets/1036189/5133191/e3e87974-70d0-11e4-82b3-b492b1fc285d.png)

**Comment by ppasq** [comment]
Tested on Beta 18 and the issue does not occur anymore.
