### ISSUE TITLE
Document thumbnail is not working

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1817]
In version 2.4b1 : 

![image](https://cloud.githubusercontent.com/assets/1036189/5133689/377402d0-70d5-11e4-8a59-27e5d2a1665c.png)

And the thumbnail should be showing in the document page too:

![image](https://cloud.githubusercontent.com/assets/1036189/5133712/5ded3102-70d5-11e4-9f0b-3a3eb6b13290.png)

**Comment by state-hiu** [comment]
It's not working for JPEG documents, too.  Should image documents (JPEG, PNG, GIF, etc.) even need a separate thumbnail.  Maybe, but we should have a workaround to just display the raw image for now.  The resulting div is the following.

```
<img class="thumb" ng-src="/static/geonode/img/missing_thumb.png"
src="/static/geonode/img/missing_thumb.png">
```

**Comment by simod** [comment]
My only concern is that if the raw image is big then the thumbnail will be very heavy and the page will be very slow to load.

**Comment by simod** [comment]
I'm closing this as standard thumbnails are working. What is missing is the pdf thumbnails that can be enabled with imagemagick
