### ISSUE TITLE
Layer and Map Thumbnails are not showing the background layer

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1818]
It would be much nicer if the background layer was shown rather than having a white background. It would give more context too.

**Comment by jj0hns0n** [comment]
This was working using the printNG module. @ischneider what is the status of that? 

https://github.com/jj0hns0n/geonode/tree/contrib-refactor/geonode/contrib/printing

https://github.com/jj0hns0n/geonode/tree/contrib-refactor/geonode/static/geonode/js/print

cc @bartvde

**Comment by ischneider** [comment]
@jj0hns0n unsure of it's status.

**Comment by simod** [comment]
They are both showing the background due to this PR https://github.com/GeoNode/geonode/pull/1884 which restores some of the logic that was in place in 2.0 also for layers (need a second save for them)
