### ISSUE TITLE
Layer thumbnail doesnt always match layer extent.

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1828]
I've now seen several examples of thumbnails that dont match the Minimum extent of the associated layer.

**Comment by jj0hns0n** [comment]
We should have an integration test for this

**Comment by capooti** [comment]
is this a duplicate of #1462?

**Comment by jj0hns0n** [comment]
@capooti I think they are different but related. We should be able to close these together with a good fix during the sprint.

**Comment by jj0hns0n** [comment]
@simod can we now close this?
