### ISSUE TITLE
demo.geonode.org down?

### ISSUE THREAD

**Issue by justb4** [GeoNode/geonode#1842]
I cannot reach http://demo.geonode.org and no reply on PING demo.geonode.org (54.235.204.189).
at wo 26 nov 2014 17:45:03 CET

**Comment by jj0hns0n** [comment]
Still not answering as of 2015-01-13

**Comment by ingenieroariel** [comment]
In order to get it fixed we need:

a) Fix the jenkins script with the new Amazon keys.
b) Point demo.geonode.org to the new IP address by contacting the sysadmin
at Boundless.com

I can take care of b) and believe John, Patrick and Jeff have been working
on a)

**Comment by ischneider** [comment]
I added the amazon keys to the environment on jenkins so time ago and the errors changed. I admit not understanding much of the process.

Let me know what's up with (b)
