### ISSUE TITLE
Error trying to Delete a received message.

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1847]
When i try to delete a received message

![1](https://cloud.githubusercontent.com/assets/9592424/5206566/7fba40dc-7570-11e4-8c58-ece0980f12fa.png)

It returns me this error:

``Environment:

Request Method: POST
Request URL: http://104.131.10.5/messages/thread/1/delete/

Django Version: 1.6.1
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'pagination',
 'taggit',
 'taggit_templatetags',
 'friendlytagloader',
 'geoexplorer',
 'leaflet',
 'django_extensions',
 'autocomplete_light',
 'mptt',
 'modeltranslation',
 'pinax_theme_bootstrap_account',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'account',
 'avatar',
 'dialogos',
 'agon_ratings',
 'notification',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'geonode.people',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.proxy',
 'geonode.security',
 'geonode.social',
 'geonode.catalogue',
 'geonode.documents',
 'geonode.api',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'pagination.middleware.PaginationMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware')

Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  22.                 return view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/views/decorators/http.py" in inner
  41.             return func(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/user_messages/views.py" in thread_delete
  76.     thread = get_object_or_404(qs, pk=thread_id)
File "/usr/lib/python2.7/dist-packages/django/shortcuts/__init__.py" in get_object_or_404
  113.         return queryset.get(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in get
  310.             (self.model._meta.object_name, num))

Exception Type: MultipleObjectsReturned at /messages/thread/1/delete/
Exception Value: get() returned more than one Thread -- it returned 2!``

**Comment by garnertb** [comment]
This bug still exists in master.  To reproduce: 

1. Login in as admin.
2. Goto http://localhost:8000/messages/create/
3. Create a new message and send the message to admin.
4. Click 'Back to Inbox.'
5. Try and delete the message from the inbox.
