### ISSUE TITLE
A section when uploading Layers is always displayed in spanish

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1848]
No matter what language i chose, that's always in spanish ^^

![1](https://cloud.githubusercontent.com/assets/9592424/5206837/f1008f7e-7572-11e4-8618-17925f4b86e9.png)

![2](https://cloud.githubusercontent.com/assets/9592424/5206844/f7c04ba6-7572-11e4-9cbd-459765e9c1a3.png)

**Comment by garnertb** [comment]
Closing since there does not seem to be  any straight-forward solutions to this and the default seems good enough.
