### ISSUE TITLE
Invite user feature has unclear field Maxuses

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1856]
I am not user what Maxuses mean, it should be made clearer.
Same for Notes. Does that mean email content?

![image](https://cloud.githubusercontent.com/assets/1036189/5218615/c21bba4e-761c-11e4-94fd-e85493dfee89.png)

**Comment by garnertb** [comment]
I updated the invite user form: https://github.com/GeoNode/geonode-user-accounts/commit/f29cbab542735ddf560a23b463c6bee51d96bc45.  

Still need to push the new version to PyPI and bump the dependency in setup.py before closing this.

**Comment by capooti** [comment]
excellent.
Can you do it or would you like me to do? cheers

**Comment by garnertb** [comment]
I can if I can get perms on the `geonode-user-accounts` package on PyPI.

**Comment by capooti** [comment]
sure, I will assign you as a maintainer. Which is your pypi username?

On Tue, Feb 3, 2015 at 3:27 PM, Tyler Garner <notifications@github.com>
wrote:

> I can if I can get perms on the geonode-user-accounts package on PyPI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1856#issuecomment-72658796>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by garnertb** [comment]
Its **garnertb**, thanks!

**Comment by capooti** [comment]
done it

On Tue, Feb 3, 2015 at 3:45 PM, Tyler Garner <notifications@github.com>
wrote:

> Its *garnertb*, thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1856#issuecomment-72661827>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
