### ISSUE TITLE
Styles not properly saved back in GeoServer after editing through UI

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1861]
I changed a style through the interface in the layer detail page so that it looks like that:

![image](https://cloud.githubusercontent.com/assets/1036189/5219466/46b1b4e4-7626-11e4-8ada-2024cb0f6e87.png)

If click on the hyperlink on the style name, I get the full styles:

![image](https://cloud.githubusercontent.com/assets/1036189/5219459/35744444-7626-11e4-9d58-5c5233192fc0.png)

But if I go through GeoServer, lots of elements are missing, which makes it impossible to edit from GeoServer:

![image](https://cloud.githubusercontent.com/assets/1036189/5219454/298409b2-7626-11e4-92b7-359df3ce87de.png)

**Comment by jj0hns0n** [comment]
@vdeparday can we look at this together today? I think we may need to file several issues around this basic problem.

**Comment by jj0hns0n** [comment]
This cant be reproduced as described, so we are closing and will continue investigating style issues and file separately.
