### ISSUE TITLE
Identify tool not working in 2.4 beta

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#1865]
Since 2.4 beta does lazy loading (avoiding a WMS GetCapabilities request) the identify tool is not working.

Is it okay to remove it arguing that it can be used via the full screen composer?

**Comment by jj0hns0n** [comment]
I've fixed this in ebolageonode and should send a patch. We should look at the lazy loading together though and make sure its always doing what we expect ... including with remote layers.
