### ISSUE TITLE
GWC - Updated GeoServer Styles Not Propagating

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1870]
Changing the `available styles` and more importantly `default style` for a layer in GeoServer does not seem to be changing the styles in GeoWebCache.

To test, remove `&tiled=true` from a WMS call and you'll get the correct default style.  Tiled=true calls the embedded GWC and returns the old tile even when you've supposedly truncated or emptied the tile cache through the Web UI.

```
http://ebolageonode.org/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Alsib_gen_densified&tiled=true&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=2504688.542848654%2C939258.2035682462%2C2661231.576776695%2C1095801.237496287
```

**Comment by jj0hns0n** [comment]
@state-hiu I saw a bunch of issues around styles in geoserver, geonode and geowebcache not staying in sync. We should design some integration tests to test these things and check the image output. Also, we need to check how geonode.layers.models.Style stays in sync with geoserver when using the manage layer styles feature. Im certain that all of this doesnt work very well as is and should be cleaned up.

**Comment by jj0hns0n** [comment]
@state-hiu Im not able to fully reproduce this. Emptying the cache via geoserver does seem to solve the problem. @garnertb will be working on https://github.com/GeoNode/geonode/issues/1656 and adding a task that will clear the cache. We should then do the following:

* [ ] Create an option in the Layer Detail Page to clear the cache for the layer
* [ ] Invoke the task in layer_style_manage https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/views.py#L154
* [ ] Investigate why GeoServer doesnt do this cache truncation itself (maybe its just not configured)

@garnertb when you are done with #1656 let me know and Ill do the first 2 above.

**Comment by state-hiu** [comment]
+1 to have a manual button to clear cache from layer detail page.  This is a good mitigation measure against future GN/GS/GWC sync issues.

**Comment by garnertb** [comment]
Ok, I probably won't get around to it until tomorrow, but I'm still happy to work it.

**Comment by simod** [comment]
any updates on this one? or should we punt it to 2.5?
