### ISSUE TITLE
GeoServer timeout (layers/acls)

### ISSUE THREAD

**Issue by menegon** [GeoNode/geonode#1873]
I'm testing GeoNode 2.4.0+beta4  (istalled by apt-get).
It works fine if there are just a few layers. However, if the number
of layers increase, GeoServer doesn't show any layer and the user is
not logged in.

The problem is the internal request for the acls
(http://localhost/layers/acls). The response is ok but it's too slow
and GeoServer doesn't wait.

**Comment by jj0hns0n** [comment]
@menegon can we close this now that #1950 was merged. Guess we should test again on the latest packages?

**Comment by jj0hns0n** [comment]
Lets look at this with @afabiani tomorrow when he is at the sprint.

**Comment by simod** [comment]
@jj0hns0n can we close this one?
