### ISSUE TITLE
Issue in "Patch Review Criteria" in docs.geonode.org

### ISSUE THREAD

**Issue by al3mon** [GeoNode/geonode#1880]
There's not a numeric sequence

![selection_001](https://cloud.githubusercontent.com/assets/9592424/5321855/5f0f162c-7c8d-11e4-86b3-a77a6998e97d.png)

**Comment by jj0hns0n** [comment]
@al3mon thats about here https://github.com/GeoNode/geonode/blob/master/docs/organizational/contribute/review_criteria.txt#L11 do you have a working sphinx setup to fix and test?
