### ISSUE TITLE
CSW Metadata target links are not being updated after IP change in Geoserver

### ISSUE THREAD

**Issue by vesnikos** [GeoNode/geonode#1883]
If you do an IP change with geonode-updateip geoservers csw links do not updated to the new IP.

**Comment by jj0hns0n** [comment]
@tomkralidis Any chance you can look into this one?

**Comment by tomkralidis** [comment]
@vesnikos is there a usecase/workflow I can follow to reproduce the issue?

**Comment by vesnikos** [comment]
on sudo geonode-updateip the metadata links of a layer on geoserver should change to reflect the change. They dont. 

Testest on  2.4b7.

![gs-metadatalink](https://cloud.githubusercontent.com/assets/6684178/6036152/5d336538-ac49-11e4-9989-0a0e08df3f84.PNG)

**Comment by capooti** [comment]
I am looking into this right now, because I remember we fixed it at some point but I could be wrong

**Comment by capooti** [comment]
after some investigation, it looks like the GeoServer link are not generated at all after an upload, therefore I am afraid we have some regressions here.
Another problem is that the GeoNode links must be updated as well.
Trying to fix both.

**Comment by capooti** [comment]
oh it looks the metadata links are correctly generated after the first metadata save and not during the initial upload.
This looks ok to me so forget first part of my last comment.

**Comment by capooti** [comment]
just figured out that @simod and @menegon are working on the related #1926 therefore I am waiting for their PR before doing anything here

**Comment by ingenieroariel** [comment]
go for it @capooti
