### ISSUE TITLE
Do proper browser testing before each release and warn user of incompatibility

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1885]
We need to be able to tell which browser and which version is compatible for a given GeoNode version.
We should detect the user browser type and warn the user if it is not compatible with GeoNode.

Currently, it is not been tested with IE, and not working properly with IE and it is still the default browser in a lot of workplaces. So we should at least warn the user and suggest to open GeoNode in another browser.

**Comment by jj0hns0n** [comment]
Lets do some careful testing on IE during the sprint and make sure we fix any major issues and document any other issues we find. We should use modern.ie for this and also document how to set that up and test.
