### ISSUE TITLE
Layer list ( /layers) not working on IE 9

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1886]
User report that he is getting the screen below and then going immediately back to homepage for the GeoNode.

![image](https://cloud.githubusercontent.com/assets/1036189/5384769/5f42e800-80cd-11e4-98a0-4577beb44ae0.png)

IE version (may be the case for later version):

![image](https://cloud.githubusercontent.com/assets/1036189/5384793/92144d0a-80cd-11e4-9fe6-56ae4a2f0a43.png)

**Comment by jj0hns0n** [comment]
This is fixed and working on ebolageonode but I have not yet committed my results upstream. Lets do some careful checking in different versions of IE during the sprint and add notes to the docs about any idiosyncrasies we find.

**Comment by simod** [comment]
fixed by https://github.com/GeoNode/geonode/commit/7737d44d45f322240c33ef5930b790dc2e7f8648
