### ISSUE TITLE
Adding (or move) geometry editing capabilities into Layer

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#1890]
Hello,

Not a bug, just a question about relocating a functionnality.

I find out a bit confusing the place where the feature geometries can be edited in geoexplorer.

Personnaly i think the best place for that capabilities should be located (also or only ?) into the "layer" menu / options rather than in the maps.

At least for first users adding some help or link in to the "Layer : Edit layer" options should be interresting because the first place you look when you want to edit a layer is in the layer menu and then in the 'edit layer' option.

My first choice should be to add an option in the edit layer menu to open a simple geoexplorer map to edit geometries.

What do you think ?

**Comment by jj0hns0n** [comment]
The button labeled 'create map' on the layer explore page performs this function loading geoexplorer with this layer and allowing for editing. The button could be renamed and/or moved around on the page to make it clear this is how to 'edit this layer'.

**Comment by collaer** [comment]
ok for me,
I think it should be clearer for newcomers to have both options/buttons 'edit geometries' and 'create map'.

**Comment by capooti** [comment]
we could add an "Edit data" link in the menu for this purpose.
