### ISSUE TITLE
Add support for importing KMZ layers

### ISSUE THREAD

**Issue by cstephen** [GeoNode/geonode#1891]
The upload form already allows KML layers, but it would be even better if it allowed KMZ layers. I experimented with adding KMZ support myself by taking advantage of the existing ZIP support, adding the following FileType to static/geonode/js/upload/FileTypes.js:

``` javascript
KMZ: new FileType({
name: 'Google Earth KMZ',
format: 'archive',
main: 'kmz',
requires: ['kmz']
})
```

And changing a couple other files to accomodate this change. GeoNode then extracts the KMZ like a ZIP file and it sometimes works. I've found a couple instances where it does not work, such as:
- If the KML file is not inside the root directory of the KMZ file.
- If there are multiple GeoNode-supported types in the KMZ file, GeoNode insists that you only upload one type of file at a time.

I haven't found any Python modules that read KMZ files natively, so I guess we're forced to extract the KMZ ourselves and pick apart the contents. Is there a better way to do this? Thanks!

**Comment by jj0hns0n** [comment]
@ischneider this once worked against the kml importer in geoserver-exts ... I wonder if trying to get that to work again is a fools errand? 

Curious how something like ogr2ogr handles kml and if we could handle it this way?

**Comment by ischneider** [comment]
I haven't played with ogr2ogr and KML.

In general, I still suggest extracting data external to GeoNode - IMHO, there are too many potential issues with how to extract, generate schemas, preserve styles, etc.
