### ISSUE TITLE
Group edit page should advise what file formats are acceptable for logo

### ISSUE THREAD

**Issue by ScottEvil** [GeoNode/geonode#1896]
When you edit the Group, there should be some text next to the Logo to tell you what file formats are acceptable and what size. PNG works but tiff doesn't show up. I'm curious what the maximum file size should be but it should just tell me to keep it below a certain number (perhaps the best size for rendering on the page.

**Comment by ilpise** [comment]
The model should be an image field instead of file field.

**Comment by collaer** [comment]
https://github.com/Geode/geonode/blob/master/geonode/groups/models.py#L33
