### ISSUE TITLE
Search autocomplete: Distinguish between Layers and Maps

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1902]
When using the Search Box - the results do not distinguish between Map and Layer items - it would be helpful if there was a text-based or icon-based method to distinguish between them.

https://github.com/ebola-geonode/ebola_geonode/issues/53

**Comment by capooti** [comment]
On Sun, Dec 21, 2014 at 3:59 PM, Jeffrey Johnson
<notifications@github.com> wrote:
>
> When using the Search Box - the results do not distinguish between Map and Layer items - it would be helpful if there was a text-based or icon-based method to distinguish between them.
>
> ebola-geonode/ebola_geonode#53
>
> —
> Reply to this email directly or view it on GitHub.


We developed this in our instance, that is still based on 2.0 (geonode.wfp.org).
Maybe we can move this to core at some point, but not sure how easy is to
implement using the new search engine.
p

-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
