### ISSUE TITLE
Shapefiles and Column Lengths

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1903]
When uploading shapefiles to create a layer, field length is respected in the edit/table in that you aren’t able to enter longer text strings than your original shapefile allowed. However, this brings up two issues:

While the DB enforces a column length, the export from the WFS is always a 255 character column, not the smaller character size expected. This is not a big deal as most of our data is small, but should probably be looked at as it can impact larger datasets where space-saving is helpful.

https://github.com/ebola-geonode/ebola_geonode/issues/50

**Comment by jj0hns0n** [comment]
I'd like to add some integration tests to verify the download. I think this needs to be fixed upstream in geoserver.

**Comment by ingenieroariel** [comment]
When a link to Geoserver's JIRA is added here, we can move to 2.5.x

**Comment by capooti** [comment]
+1 to create the ticket in GS JIRA and move this to 2.5.x. Should I file it (after checking if the ticket is not already there)?
