### ISSUE TITLE
Search - Unable to select from drop-down search results

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1905]
On the homepage ONLY, when searching for a layer, when the search results return I am unable to select any of them by mousing-over the list. Chrome 39 and IE 11 both tested.

Also even though the box still says "guinea" for example, when the user hits 'enter' to search, the first item on the list is actually selected and searched for - meaning it is not possible to do a generic search from the homepage using "Enter", only buy clicking the Search Button.

https://github.com/ebola-geonode/ebola_geonode/issues/42

**Comment by jj0hns0n** [comment]
@simod it seems you are right about this being an issue specific to this instance.

Is it possible to fix this so that the first entry is not automatically selected.

**Comment by simod** [comment]
sorry, closing as wontfix :)
