### ISSUE TITLE
Geonode developer wanted!

### ISSUE THREAD

**Issue by smoothbadger** [GeoNode/geonode#1911]
Hi there, we are looking for a developer to help finish off our Geonode project that contains environmental GIS data. We are an engineering firm based in Haywards Heath. Please drop me an email if anyone is interested.... Georgina.cutler@rhdhv.com

**Comment by simod** [comment]
Hi @smoothbadger do you mind re-posting this on the developers mailing list? https://groups.google.com/a/opengeo.org/forum/#!forum/geonode-dev. Thanks

**Comment by smoothbadger** [comment]
Thanks, I wasn't sure where to put it

Sent from my iPhone

On 8 Jan 2015, at 07:16, Simone Dalmasso <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @smoothbadger<https://github.com/smoothbadger> do you mind re-posting this on the developers mailing list? https://groups.google.com/a/opengeo.org/forum/#!forum/geonode-dev. Thanks

-
Reply to this email directly or view it on GitHub<https://github.com/GeoNode/geonode/issues/1911#issuecomment-69144316>.

This email and any attachments are intended solely for the use of the addressee(s); disclosure or copying by others than the intended person(s) is strictly prohibited. If you have received this email in error, please treat this email as confidential, notify the sender and delete all copies of the email immediately
