### ISSUE TITLE
programmatically add layer from postgis

### ISSUE THREAD

**Issue by alessandroburastero** [GeoNode/geonode#1913]
there should be in geonode code a specific method to add a new layer taking data from a postgis table... Something similar to geonode.layers.utils.file_upload

This should be very useful for application that use geonode as backend, and need to publish data dynamically

**Comment by jj0hns0n** [comment]
This should be done with a management command. It should configure the layers in geoserver and then sync with geonode.

**Comment by ischneider** [comment]
Having a management command initially would be a good start but it would be great to have the logic reside outside that command.

**Comment by garnertb** [comment]
@jj0hns0n, I'm moving this feature request to 2.5.

**Comment by jj0hns0n** [comment]
@pjdufour can you link this to the other issue that discusses this in the context of a management command and close one or the other.
