### ISSUE TITLE
Column Lengths in GeoExplorer

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#1916]
When editing in map view against a layer with a field length limit that is relatively short, if you try to enter in a value that is longer than the allowable field length and then save the feature, you get a generic error and cannot save the feature until you figure out which field you’ve over-entered in. Should be more detailed, I am guessing PostgreSQL returns a specific error that could be parsed.

**Comment by jj0hns0n** [comment]
Here is a screenshot. The locality field has a max length of 8 characters. 

![geoexplorer_-_example_com](https://cloud.githubusercontent.com/assets/506078/6019592/8aaafa14-aba2-11e4-92c0-64622bef8d64.png)

@bartvde is there anyway to return a more specific error?

**Comment by jj0hns0n** [comment]
@garnertb guessing this is the same issue in MapLoom and not only in GeoExplorer

**Comment by bartvde** [comment]
sure getting a more specific error in the dialogue should be possible @jj0hns0n

**Comment by bartvde** [comment]
@jj0hns0n it would help if you could debug in this function (this is part of ```src/script/plugins/FeatureEditor.js``` in GXP):

I had expect the message to be in there already because of: ```gxp.util.getOGCExceptionText(response.exceptionReport);```

```
                                    fn: function(proxy, type, action, options, response, records) {
                                        var msg = this.exceptionText;
                                        if (type === "remote") {
                                            // response is service exception
                                            if (response.exceptionReport) {
                                                msg = gxp.util.getOGCExceptionText(response.exceptionReport);
                                            }
                                        } else {
                                            // non-200 response from server
                                            msg = "Status: " + response.status;
                                        }
                                        // fire an event on the feature manager
                                        featureManager.fireEvent("exception", featureManager,
                                            response.exceptionReport || {}, msg, records);
                                        // only show dialog if there is no listener registered
                                        if (featureManager.hasListener("exception") === false &&
                                            featureStore.hasListener("exception") === false) {
                                                Ext.Msg.show({
                                                    title: this.exceptionTitle,
                                                    msg: msg,
                                                    icon: Ext.MessageBox.ERROR,
                                                    buttons: {ok: true}
                                                });
                                        }
                                        if (popup && popup.isVisible()) {
                                            popup.enable();
                                            popup.startEditing();
                                        }
                                    },
```

**Comment by bartvde** [comment]
Also I'd be interested to see what GeoServer actually returns in the error message (use the XHR tab in the browser to find out)

**Comment by garnertb** [comment]
@jj0hns0n, MapLoom uses the DescribeFeatureType request to restrict input to the length of the field.

**Comment by bartvde** [comment]
which is what GeoExt also does, so not sure what's actually going on here:

https://github.com/geoext/geoext/blob/master/lib/GeoExt/widgets/form.js#L201

**Comment by ingenieroariel** [comment]
@ndufrane will try to take a look at it

**Comment by simod** [comment]
This is the response from geoserver upon the wfs request:

<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:8001/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="InvalidParameterValue">
<ows:ExceptionText>Update error: Error occured updating features</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

Seems to be something that has to be solved in geoserver

**Comment by bartvde** [comment]
@simod what is the XML of the request in this case?

**Comment by simod** [comment]
@bartvde 
<wfs:Transaction xmlns:wfs="http://www.opengis.net/wfs" service="WFS" version="1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs http://schemas.opengis.net/wfs/1.1.0/wfs.xsd"><wfs:Update typeName="feature:cippa" xmlns:feature="http://www.geonode.org/"><wfs:Property><wfs:Name>lippa</wfs:Name><wfs:Value>stacippa</wfs:Value></wfs:Property><ogc:Filter xmlns:ogc="http://www.opengis.net/ogc"><ogc:FeatureId fid="cippa.1"/></ogc:Filter></wfs:Update></wfs:Transaction>

**Comment by bartvde** [comment]
@simod so the value length is larger than the schema allows for?

**Comment by simod** [comment]
@bartvde yes the length for the attribute "lippa"  is 5

**Comment by bartvde** [comment]
and you have confirmed that maxLength is 5 in the xsd? If so this is a client-side error I think.

**Comment by simod** [comment]
Actually, this is the xsd and I don't see the definition of the maxlength:
```
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:geonode="http://www.geonode.org/" xmlns:gml="http://www.opengis.net/gml" elementFormDefault="qualified" targetNamespace="http://www.geonode.org/">
<xsd:import namespace="http://www.opengis.net/gml" schemaLocation="http://localhost:8001/geoserver/schemas/gml/2.1.2/feature.xsd"/>
<xsd:complexType name="cippaType">
<xsd:complexContent>
<xsd:extension base="gml:AbstractFeatureType">
<xsd:sequence>
<xsd:element maxOccurs="1" minOccurs="0" name="the_geom" nillable="true" type="gml:PointPropertyType"/>
<xsd:element maxOccurs="1" minOccurs="0" name="id" nillable="true" type="xsd:long"/>
<xsd:element maxOccurs="1" minOccurs="0" name="lippa" nillable="true" type="xsd:string"/>
</xsd:sequence>
</xsd:extension>
</xsd:complexContent>
</xsd:complexType>
<xsd:element name="cippa" substitutionGroup="gml:_Feature" type="geonode:cippaType"/>
</xsd:schema>```

**Comment by bartvde** [comment]
Ah okay, maybe it requires a manual xsd override in GeoServer, it's been a while since I dealt with this to be honest.

**Comment by simod** [comment]
hm... do you have any suggestion on what I should look at?

**Comment by simod** [comment]
ah maybe this http://sourceforge.net/p/geoserver/mailman/message/22402922/. Looks a quite ugly solution though

**Comment by bartvde** [comment]
right that's what I meant but I couldn't find it.
I see a lot of open geoserver JIRA issues for taking it from the database but it seems this never materialized

cc @ischneider

**Comment by simod** [comment]
thanks @bartvde , also pinging @capooti , @jj0hns0n , @ingenieroariel to discuss whether makes sense to apply such thing to solve this issue. I would vote -1. :)

**Comment by capooti** [comment]
if this is the only way, and there is someone volunteering to fix it, I could be +1 about this :)

**Comment by ischneider** [comment]
Modifying the schema.xsd appears to be a brittle workaround for the issue.

Ideally, the fix would happen via database metadata introspection in GeoServer.

**Comment by simod** [comment]
punting this to 2.5 after discussing with @afabiani
