### ISSUE TITLE
On Windows paver start fails

### ISSUE THREAD

**Issue by george-silva** [GeoNode/geonode#1919]
Hello guys and gals,
Following the setup instructions clearly, paver start command fails. It is still looking for /dev/null for start_geoserver task.

Check this line:

https://github.com/GeoNode/geonode/blob/master/pavement.py#L346

In my specific installation, the command ```java -version``` appears to work, so we never consider this to be on windows or not, maintaining the ```longernullpath = '/dev/null'```.

We should not rely on this behavior to determine if the user is on Windows or other OS, so, my proposal here is that we create a new function inside pavament.py that informs the script of the user's OS, and then determines the ```longernullpath```.

I plan to provide a patch. Not sure how I can provide unit tests for this, but I'll think of something.

**Comment by garnertb** [comment]
Maybe you can use [os.devnull](https://docs.python.org/2/library/os.html#os.devnull)?

**Comment by george-silva** [comment]
@garnertb that seems to be simpler! I'll use that approach!

**Comment by jj0hns0n** [comment]
Can this now be closed?

**Comment by george-silva** [comment]
sure
Em 02/02/2015 07:46, "Jeffrey Johnson" <notifications@github.com> escreveu:

**Comment by nathanhilbert** [comment]
I can verify that this can be closed.  Can the "Windows" label be added to this for others to find in the future?

**Comment by garnertb** [comment]
Closing, per @nathanhilbert's comments.
