### ISSUE TITLE
Proxy WFS behind Human-Readable URL

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1924]
To simplify integration with external discovery platforms, such as CKAN, we should enable a proxy endpoint for WFS requests behind a human-readable URL.  This will facilitate manual registration of GeoNode services in external systems.  Other systems could more easily detect the file format (based on the extension) without having to learn the WFS spec.  Automated harvesting should still use the normal WFS links.  This wouldn't be a full proxy for WFS but only apply to the most common formats and EPSG:4326.

Normal WFS Link for GeoJSON
http://ebolageonode.org/geoserver/wfs?srsName=EPSG%3A4326&typename=geonode%3Asle_heal_pt_cdc_healthfacilities&outputFormat=json&version=1.0.0&service=WFS&request=GetFeature

Proxy Link for GeoJSON Files
http://ebolageonode.org/layers/download/sle_heal_pt_cdc_healthfacilities.geojson

**Comment by ischneider** [comment]
It seems like a redirect would work and be easier to implement?
