### ISSUE TITLE
Metadata changes are not synchronized with GeoServer

### ISSUE THREAD

**Issue by menegon** [GeoNode/geonode#1926]
In some circumstances (i.e. layers imported through "updatelayers")  metadata changes (i.e. title, abstract) are not synchronized with GeoServer.

I think the problem is in geonode.geoserver.signals.geoserver_pre_save function. The layers, imported through "updatelayers", have no base_file defined (None) so the function "geoserver_pre_save" exits immediately without applying any effects.

GeoNode 2.4

**Comment by jj0hns0n** [comment]
@menegon lets discuss and look at this together today? Just grab me when you have time.
