### ISSUE TITLE
Change Uploader Permissions Default - to Anyone can View and Download

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#1929]
The permissions menu should be changed to toggle on the checkbox to "Anyone" for View and Download. If and when users upload the default should be open and accessible. Currently without intervention it will restrict the layer to the uploading user in both cases
![2015-01-20 11_50_03-upload layer - geonode](https://cloud.githubusercontent.com/assets/6350035/5821539/eb0b2144-a09a-11e4-9dc0-7722b3b9e3e1.jpg)

**Comment by state-hiu** [comment]
I think this should be handled via a settings.py configuration so that different instances can have different default permissions.  GeoNode instances that act more like shared drives should probably have restricted default permissions.  Open Data GeoNode instances would have open permissions configured in settings.py

**Comment by ischneider** [comment]
I agree it should be configurable ideally.

For this and future settings changes (when it makes sense), can we implement things so it takes either a value (in this case, let's say `DEFAULT_PERMISSIONS_FORM_STATE`) or function (this this case, the function could take the current user) with kwargs to not break if/when things change?

So when it's being consumed (in the view), it would look like:
```python
defaults = getattr(settings, 'DEFAULT_PERMISSIONS_FORM_STATE', None)
if callable(defaults):
  defaults = defaults(user=request.user)
# configure form with defaults
...
```

**Comment by simod** [comment]
+1

**Comment by capooti** [comment]
Agree, +1 here

On Wed, Jan 21, 2015 at 8:20 AM, Simone Dalmasso <notifications@github.com>
wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/1929#issuecomment-70794732>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by simod** [comment]
fixed
