### ISSUE TITLE
New remote services registration - Mapserver long name url not recognized

### ISSUE THREAD

**Issue by mdlux** [GeoNode/geonode#1932]
Discussed in geonode-users.
A remote service url from mapserver:
http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/RO_localOWS_test.map
is not accepted as a valid input for registering a new remote service. Probably because of the question mark, probably after an attempt of appending ?request=GetCapabilities with another question mark.

**Comment by tomkralidis** [comment]
Note we could use `owslib.util.bind_url` here: https://github.com/geopython/OWSLib/blob/8145c7893d2ff7b3c8e69209908025884f47050d/owslib/util.py#L553

**Comment by capooti** [comment]
excellent.
I will need to work on remote services in the next days, maybe I can also fix this using the bind_url method.
Thanks @tomkralidis!

**Comment by capooti** [comment]
working on this right now.
