### ISSUE TITLE
Add a 'modified' attribute to the resourcebase model.

### ISSUE THREAD

**Issue by garnertb** [GeoNode/geonode#1938]
Among other benefits, we could use this value to compare with an `IF-MODIFIED-SINCE` header from the client to conditionally process a lot of the GeoNode views.  Any reason we shouldn't do this?

**Comment by ischneider** [comment]
Agreed adding the field is relatively simple but maintaining it and taking advantage of it are more difficult.

What views are you thinking of enabling this on?

If related to a page (versus a resource specific API response), consider all of the other related models on a page - directly or indirectly related - as well as other factors, such as authenticated status.

**Comment by tomkralidis** [comment]
This would also help the CSW `apiso:Modified`/`dct:modified` queryable mappings.

Note that `last_modified` already exists in `geonode.maps.models.Map` (https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L73), so if we were to introduce `last_modified` in `geonode.base.models.ResourceBase`, I would see this replacing the local one in maps.
