### ISSUE TITLE
Document Downstream Projects

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1939]
Update http://geonode.readthedocs.org/en/latest/tutorials/devel/projects/projectsintro.html with new downstream projects and provide links.

**Comment by gamesbook** [comment]
Would also be useful to add actual hyperlinks to those projects' websites.

**Comment by JJediny** [comment]
@state-hiu are you wanting to distinguish between all geonode "projects" or only those with significant customization / change in their code base from the current version of geonode but were derived from geonode at some point? If the former this seems redundant with the [Geonode.org's Sites Gallery](http://geonode.org/gallery/). If the later then +1, but besides updating the list think we should add what makes them different and what specific use-cases/features/components they developed and/or are utilizing and also highlight projects that have innovated from a fork of geonode and are still using that previous version which has significantly diverged from the current community and whether they have plans to upgrade. So other projects can assess the pros/cons of forking directly from those if they have similar needs.

**Comment by state-hiu** [comment]
I was just thinking links to "projects" that use https://github.com/geonode/geonode-project, would be useful examples.  A tutorial is good, but it's also useful to just look around someone's working code.  No strong thoughts one way or the other.  Maybe we just delete the section and redirect to the gallery.  However, the gallery does not include links to GitHub repos.

**Comment by JJediny** [comment]
As this seems most useful to people being newly introduced to Geonode think it makes sense to update the sites gallery with new projects and in the process add a link to their repos as a encouraged but optional piece of info and possibly include some unique features as a bullet list below the description snippet... Think we should also consider more prominently featuring the gallery on Geonode.org's landing page as a "see how people are using it..." Featured content
