### ISSUE TITLE
Show mouse position coordinates

### ISSUE THREAD

**Issue by vytj** [GeoNode/geonode#1951]
Hello,
Is there any way to display mouse position coordinates in layers and maps view?

**Comment by simod** [comment]
Hi, not easily as far as I know because this would require a new build of GeoExplorer with the OpenLayers tool.

**Comment by vytj** [comment]
Any plans to implement this feature? Looks like it's done in https://github.com/GeoNode/django-geoexplorer

**Comment by simod** [comment]
It's not really implemented in geoexplorer. We removed the js code that was putting it in the map client because was throwing errors. Not sure we will include it as the future of this mapping client is not defined yet.

**Comment by achorivai** [comment]
hi vytj, is possible to show mouse coordinate you can see my sample in http://43.231.128.58/maps/5/view

i use mouseposition.js from openlayer and add some script 

after this script--->>  app = new GeoNode.Composer(config);
add this--->    app.mapPanel.map.addControl(
        new OpenLayers.Control.MousePosition(  { prefix:  '  <b> Longitude</b> ', separator: '<b> , Latitude</b> ',
	       numDigits: 4,
              displayProjection: new OpenLayers.Projection("EPSG:4326")})
); <--- until this


and then load MousePostion.js


<script type="text/javascript" src="{{ STATIC_URL}} geonode/js/util/MousePosition.js"></script> 


in /usr/local/lib/python2.7/dist-packages/geonode/maps/templates/maps/map_geoexplorer.js 

after that actually mouse coordinate has loaded by system but you can see it because the default postion of coordinate is in the bottom-right you can move it with css... :)

**Comment by marcelovillarroel** [comment]
Hi achorivai,
Could you please send a link to mouseposition.js file?

Thanks,

**Comment by achorivai** [comment]
hi @marcelovillarroel sorry very late respon
[mouseposition_geonode.zip](https://github.com/GeoNode/geonode/files/531068/mouseposition_geonode.zip)

**Comment by zahirulislamovich** [comment]
Dear Achorivai,
I cannot integrate. when i copy and past my geoexplorer  map view is blank.

zahir

**Comment by achorivai** [comment]
Hi All

Step by step mouse position

1. Copy file mouseposition.js in folder /var/www/geonode/static/geonode/js
2. Edit file map_geoexplorer.js on folder /usr/local/lib/python2.7/dist-packages/geonode/maps/templates/maps
   - add this script in line 8
     <script type="text/javascript" src="{{ STATIC_URL}}geonode/js/base/mouseposition.js"></script>
   - and add this script
	app = new GeoNode.Composer(config);
	app.mapPanel.map.addControl(
        new OpenLayers.Control.MousePosition(  { prefix:  '  <b style="font-weight: bold; color: green;"> Longitude</b> ', separator: '<b style="font-weight: bold; color: green;"> , Latitude</b> ',
	       numDigits: 4,
              displayProjection: new OpenLayers.Projection("EPSG:4326")})
						);

3. Edit Style.css in folder /var/www/geonode/static/geoexplorer/externals/openlayers/theme/default
   - find div.olControlMousePosition and replace that section with

	div.olControlMousePosition {
   		 /* bottom: 0; */
   		 right: 3px;
    		display: block;
    		position: absolute;
    		font-family: inherit;
    		font-size: medium;
    		background-color: rgba(160, 206, 77, 0.73);
	}

4. Refresh your browser :)

**Comment by marcelovillarroel** [comment]
Thank you achorivai.

**Comment by amirhosseinrad** [comment]
It doesn't work for me!
I have done as your guideline, 
what should do now?
