### ISSUE TITLE
2.4b11 Get Feature Info works only in maps

### ISSUE THREAD

**Issue by vytj** [GeoNode/geonode#1952]
Hello,
Get Feature Info tool in GeoNode 2.4b11 works only in maps - in layer view, window with results is not shown. Tested with Firefox 35.0 and IE 11.
Also, when loading specific layer view, Firebug shows these errors:
```
PUT http://192.168.1.111/gs/rest/styles 405 METHOD      NOT ALLOWED         68ms	
GeoExplorer.js (line 396)

"NetworkError: 405 METHOD NOT ALLOWED - http://192.168.1.111/gs/rest/styles"
```

**Comment by simod** [comment]
Hi, the 405 error is the correct behavior. This looks the same issue as https://github.com/GeoNode/geonode/issues/1865, so closing this one
