### ISSUE TITLE
Allow users to edit User/Group/Remote-Service Slug name during creation & before initial save.

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#1961]
### For Remote Service

When registering multiple remote services (especially for WMS from ArcGIS Servers which will all register as "OGC WMS") allow users to overwrite the default remote service name before saving. By automating this a remote service with the same name will overwrite remote-service layers previously added 

### For User and Group Slugs

Entering permissions is cumbersome having to reference back to user pages or groups. For users it would be easier to use their email address by default as this would also enable someone to take their email distribution and copy and paste to permissions. For groups the current slug is created from the title with will truncate and convert to all lowercase (but on look-up with still be uppercase/case sensitive?). Either way most users would be inclined/prefer to use a groups acronym which are shorter and often more familiar and memorable. Allowing the creator to specify this before saving would make things easier

**Comment by simod** [comment]
the only thing that is not fixed is the lookup by email because the email is not mandatory.
