### ISSUE TITLE
enconding problem in layer abstract field with accented chararcters

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#1966]
Page cannot be displayed if an accented character is present into the abstract field.
Just edit metadata for a layer as :

![image](https://cloud.githubusercontent.com/assets/6357213/6000378/73c5fc06-aadd-11e4-8480-2a9461a1949a.png)

The abstract is correctly displayed in layer list
![image](https://cloud.githubusercontent.com/assets/6357213/6000391/a37aa3e8-aadd-11e4-998a-cfb4a0d0554f.png)

But throwing an error in the layer detail and in the metadata page : 
![image](https://cloud.githubusercontent.com/assets/6357213/6000409/ced42c30-aadd-11e4-8df3-5a91a8d2812e.png)

**Comment by capooti** [comment]
taking care of this

**Comment by collaer** [comment]
same with maps and map description
![image](https://cloud.githubusercontent.com/assets/6357213/6001828/13dcbca6-aaee-11e4-86e9-95c760ce783b.png)
![image](https://cloud.githubusercontent.com/assets/6357213/6001839/28aefba8-aaee-11e4-80e0-598d988a4689.png)

**Comment by capooti** [comment]
it is a regression introduced by this PR: https://github.com/GeoNode/geonode/pull/1930/files#diff-aadb2492556667858a9abd91a23ef330R558
fixing it right now
