### ISSUE TITLE
Profile Page Not displaying Profile Field

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#1975]
User Profile field is not being displayed on the profile page.

https://github.com/GeoNode/geonode/blob/master/geonode/people/templates/people/profile_detail.html
https://github.com/GeoNode/geonode/blob/master/geonode/people/models.py#L48

**Comment by jj0hns0n** [comment]
@ppasq can you take care of this one quickly?

**Comment by garnertb** [comment]
@ppasq, @jj0hns0n - I can work this one.
