### ISSUE TITLE
Users should not be able to edit other users profile

### ISSUE THREAD

**Issue by daniviga** [GeoNode/geonode#1982]
This bug has been already fixed in the `2.0.x` branch, but it's still present in `master`.

1. Create an admin user "admin"
2. Create a unprivileged user "foo"
3. Login as "foo" and go to http://127.0.0.1:8000/people/profile/admin/
4. Change "admin" email and Save
5. "admin" email has been updated by "foo" (!!!)

See https://github.com/GeoNode/geonode/pull/1907. I'll open a PR on `master` asap

**Comment by daniviga** [comment]
PR: https://github.com/GeoNode/geonode/pull/1984

**Comment by jj0hns0n** [comment]
Can this now be closed? It looks to have been fixed (I just verified with latest master)

**Comment by daniviga** [comment]
Thanks!
