### ISSUE TITLE
Cannot type into GeoExt boxes

### ISSUE THREAD

**Issue by lucageo** [GeoNode/geonode#1990]
Dear all,

in order to modify a layer style I try to type something into the boxes but apparently there are some JavaScript errors, I suppose, and I am not allowed to write into the boxes (see the figure attached).
![image](https://cloud.githubusercontent.com/assets/10832462/6022765/8a9e3528-abbf-11e4-925f-3813ed0a018e.png)

Some of you already had this kind of problem?
Do you have an Idea?

Thanks a lot
Cheers,
Luca

**Comment by simod** [comment]
Hi which browser are you using? On chrome is working for me

**Comment by lucageo** [comment]
Both with chrome and firefox...

**Comment by simod** [comment]
any error from the browser console?

**Comment by lucageo** [comment]
I got the following errors:
![untitled-2](https://cloud.githubusercontent.com/assets/10832462/6023162/b97d042a-abc2-11e4-8765-780420b70987.jpg)

**Comment by simod** [comment]
We released a fix for this errors in these days, could you try to update your geonode and see if still happens?

**Comment by lucageo** [comment]
Thank you,
Do you have any suggestion regarding the procedure to update the software considering that it is installed on CentOS? Do I have to perform a full deploy?

**Comment by simod** [comment]
Ok I assume that you installed it manually pulling from github master right? in that case you just have to go back to your geonode folder where you did git clone and do a git pull origin master, then restart apache.

**Comment by lucageo** [comment]
OK, thank! I'll try

**Comment by lucageo** [comment]
Thank you simod, everything is working fine with the new version!

**Comment by simod** [comment]
^^
