### ISSUE TITLE
Configure GeoServer allocated memory during the post install for the package 

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1991]
On demo.geonode.org that is installed with the default package, Geoserver is too slow and it cannot save back styles when editing through geoxsp
To reproduce:
Try editing style of http://demo.geonode.org/layers/geonode%3Ars2_20150121_flood
And you get an error "Cannot get save style" because GeoServer is too slow to respond

**Comment by ingenieroariel** [comment]
https://github.com/GeoNode/geonode/commit/cc8e35fd944e110efa61e8e8abaaad18aae66d37

Fixed
