### ISSUE TITLE
Login form does not remember username and password when "Remember Me" is checked

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#1994]
version 2.4b2

To reproduce:
check the box "remember me"
enter username and password
log out 
return to the login window and username and password are not remembered

**Comment by jj0hns0n** [comment]
@vdeparday this is really a question of what design pattern is being applied here. What the remember me option does currently is to keep you logged in even after you close your browser and reopen. It does not remember your username and password. There are discussions about this (google "remember me" design pattern). I think we can add support for actually remembering the username and password, but there are very good arguments why you shouldn't do this. 

Clearing the bug tag and adding UI/UX
