### ISSUE TITLE
Fix PEP8 Violations in Pavement.py

### ISSUE THREAD

**Issue by state-hiu** [GeoNode/geonode#2002]
Fix the PEP8 violations in the [pavement.py](https://github.com/GeoNode/geonode/blob/master/pavement.py).

How to find PEP8 violations:
1. Install flake8: `pip install flake8` in your GeoNode virtual environment.
2. cd [geonode_root](https://github.com/GeoNode/geonode)
3. `flake8 pavement.py` (don't do `flake8 .` since that may search dependencies, etc.)
4.  Fix all identified issues as much as reasonably possible.

**Comment by capooti** [comment]
you can use flak8 geonode before every commit, so you can make sure that all python files will be pep8 compliant
same is done by our Travis script, by the way

**Comment by ndufrane** [comment]
I am looking into it

**Comment by state-hiu** [comment]
Yes, the reason pavement was never fixed was that it is in the root directory rather than in the `geonode` source subdirectory.

**Comment by capooti** [comment]
ah sorry :)
got it, maybe you could update here to check this also in Travis:
https://github.com/GeoNode/geonode/blob/master/pavement.py#L474

On Wed, Feb 4, 2015 at 2:12 PM, Humanitarian Information Unit <
notifications@github.com> wrote:

> Yes, the reason pavement was never fixed was that it is in the root
> directory rather than in the geonode source subdirectory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2002#issuecomment-72851783>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
