### ISSUE TITLE
Cannot upload files in IE9

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#2009]
When clicking on browse, the user can select only one file (not several files) and even when trying to pick files one by one, because when selecting the first file and clicking ok, it does not get picked up by the UI.

![image](https://cloud.githubusercontent.com/assets/1036189/6038172/d5c737ca-ac28-11e4-94a4-62261283344c.png)

**Comment by jj0hns0n** [comment]
@vdeparday can you test this again?

**Comment by jj0hns0n** [comment]
@vdeparday closing. Can you test and let us know if this is still an issue.
