### ISSUE TITLE
The style editor in the layer detail page should be disabled if not logged in

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2011]
If the user is not logged in, the style editor should be completely disabled since they cant actually save the styles. What happens now is an error is thrown when the app tries to save the style. It would be much better to just not allow the user to try to edit the style (as on the map detail page) or prompt them to login (as in the map composer / geoexplorer)

![san_andres_y_providencia_water_ _example_com](https://cloud.githubusercontent.com/assets/506078/6038688/804cb036-ac5f-11e4-8e93-897f4a579449.png)

@bartvde any ideas on this one? (sorry, you are the only geoexplorer guy we have access to)

**Comment by bartvde** [comment]
The styler component already needs the roles: ["ROLE_ADMINISTRATOR"] to be set.

Can you point me to the code of this page in github?

**Comment by vdeparday** [comment]
It should be there: https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_geoext_map.html

**Comment by bartvde** [comment]
Can you guys check is using an array for authorizedRoles helps?

```
authorizedRoles: "ROLE_ANONYMOUS",
```

should be:

```
authorizedRoles: ["ROLE_ANONYMOUS"],
```

**Comment by vdeparday** [comment]
I tried to change
```authorizedRoles: "{{ user.is_authenticated|yesno:"ROLE_ADMINISTRATOR,ROLE_ANONYMOUS" }}",
to 
```authorizedRoles: ["{{ user.is_authenticated|yesno:"ROLE_ADMINISTRATOR,ROLE_ANONYMOUS" }}"],

the generated javascript looks like 
```authorizedRoles: ["ROLE_ANONYMOUS"],

But I still get the error from the first screenshot

**Comment by ndufrane** [comment]
Hi,
Maybe the solution is to not include the styler plugin if the user is not logged. We can make this in geo_header.html template

    {% if not map %} --> And logged 
        config.viewerTools.splice(5, 0, {
            id: "styler",
            ptype: "gxp_styler",
            checked: true
        });
    {% endif %}

**Comment by bartvde** [comment]
Yeah that solution should also work I think. Let me know if it doesn't work and I'll proceed with my investigation
