### ISSUE TITLE
syncdb, createsuperuser problem

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#2014]
When you install a new geonode and use the syncdb command, the system ask you for creating a superuser.
If you do so, everything seems to work, but in fact the superser is not created.

```
   You just installed Django's auth system, which means you don't have any superusers defined.
   Would you like to create one now? (yes/no): yes
   Username: bob
   Email address: 
   Password: 
   Password (again): 
   Superuser created successfully.
   Installing custom SQL ...
   Installing indexes ...
   Installed 298 object(s) from 1 fixture(s)
```

you have to create a new superuser (with same name) just after.

**Comment by simod** [comment]
We should use the paver sync command instead of the syncdb. Anyway this is just for development as in production we recommend geonode createsuperuser and the sync is done automatically. I'd say that this is not blocking for a release and is a minor bug.
