### ISSUE TITLE
Unlock LayerEditing without specific datastore set

### ISSUE THREAD

**Issue by ndufrane** [GeoNode/geonode#2020]
Hi,

With the default local settings we have ogc_server_settings.DATASTORE set to blank. Witch is blocking the edit layer feature. 

Putting anything but blank make the editing tool working again. So it seems that the test on DATASTORE is no more necessary.

**Comment by simod** [comment]
We have to enforce the editing only if using postgis. Any concurrent edits on shapefiles will break it.
