### ISSUE TITLE
Layer search is no longer available in the GXP map viewer when adding a layer

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#2022]
When adding a layer with the green + sign in the map viewer, there is the list of layers (can be several hundred) and there is no way to filter/search it:
![image](https://cloud.githubusercontent.com/assets/1036189/6042018/7b62df92-ac4f-11e4-9dd7-7e7937cb478a.png)

It seems like the search is still in the code but not enabled or not showing up
https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/extjs/GeoNode-GeoExplorer.js

@bartvde an idea?

**Comment by bartvde** [comment]
looking at app.sources it doesn't seem like a search source is defined in the config?

**Comment by bartvde** [comment]
ah it actually there and named search will look a bit further

**Comment by bartvde** [comment]
@vdeparday can you try changing search: true to:

```
search: {
  selectedSource: 'search'
}
```

**Comment by bartvde** [comment]
So in this spot: https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/extjs/GeoNode-GeoExplorer.js#L439

**Comment by jj0hns0n** [comment]
@bartvde that did the trick and enabled the widget again. The search API has changed dramatically since this last worked. Can you point us at where we set the Search API URL and what is the expected output format. We will need to figure out how to adapt to the new API.

**Comment by bartvde** [comment]
sure url is set here: https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/extjs/GeoNode-GeoExplorer.js#L451

**Comment by bartvde** [comment]
The protocol code is here: https://github.com/boundlessgeo/gxp/blob/master/src/script/plugins/GeoNodeCatalogueSource.js

**Comment by vdeparday** [comment]
I am trying to follow: http://docs.geonode.org/en/master/tutorials/devel/debug/geoexplorer.html to change and debug the GeoNodeCatalogueSource.js to adapt to the new Search api but https://github.com/GeoNode/suite/tree/geonode/geoexplorer no longer compiles because it seems to refer to http://repo.opengeo.org/

@ingenieroariel , how can I get past that?

''''
Downloading: http://dev.mapfish.org/maven/repository/org/ringojs/ringojs/0.8.1/ringojs-0.8.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.721 s
[INFO] Finished at: 2015-02-05T15:18:45+01:00
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project geoexplorer: Could not resolve dependencies for project org.opengeo:geoexplorer:jar:4-SNAPSHOT: Could not find artifact org.ringojs:ringojs:jar:0.8.1 in opengeo (http://repo.opengeo.org/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
'''

**Comment by bartvde** [comment]
try using repo.boundlessgeo.com instead

**Comment by vdeparday** [comment]
I just changed the reference repo.boundlessgeo.com in the pom.xml but I still get the same error:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.913 s
[INFO] Finished at: 2015-02-05T16:44:00+01:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project geoexplorer: Could not resolve dependencies for project org.opengeo:geoexplorer:jar:4-SNAPSHOT: Could not find artifact org.ringojs:ringojs:jar:0.8.1 in boundlessgeo (http://repo.boundlessgeo.com/) -> [Help 1]

**Comment by bartvde** [comment]
I'm not sure the whole build process has actually changed in suite maybe pull in those changes?

**Comment by vdeparday** [comment]
@ndufrane, this is the ticket I was refering to as you mentioned that you have a working build of GeoExplorer
