### ISSUE TITLE
Do we still need the upload application?

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2023]
In case we don't need it anymore, we may consider to remove it as it can cause confusion, at least with me :laughing:

**Comment by garnertb** [comment]
Yes, the upload application uses the Geoserver Importer vs the Geoserver REST API to upload data.  We use it in GeoSHAPE (formerly ROGUE) to allow users to upload GeoGIG repositories and other file types that I don't think are supported by the REST API.  But I agree, trying to debug upload problems is very confusing with the two methods.
