### ISSUE TITLE
Generate default layer thumbnail automatically

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#2025]
As it stands a user has to manually generate the thumbnail for a layer by clicking on the "set thumbnail" button. This is not convenient especially when batch uploading layer.
A default thumbnail should be generated automatically.

**Comment by pjdufour** [comment]
Was this issue fixed?

**Comment by simod** [comment]
no, as the thumbnail "with background" generation still requires to be in a page where is a map where we can take the tiles and send to the server.

**Comment by vdeparday** [comment]
How do you think it  could be done? Any easy way to do that? I think it would make all GeoNode looks much nicer as it is really hard to understand a layer without background map.

**Comment by simod** [comment]
We have to write a server side logic that taken a map extent fetches the osm tiles by itself, then the layer tiles then merge them together. If I'm not wrong it's printng that is doing this, we would need to use an imaging library instead I suppose

**Comment by capooti** [comment]
not sure as well about the code, but what could be easily done is to cascade OSM as a new layer and add it in the GetMap request together with the layer

**Comment by samperd** [comment]
Ping,

Has this issue moved forward? I see it is still an issue with 2.6.3

**Comment by afabiani** [comment]
I guess this is not an issue anymore on GeoNode 2.7+

Do you have a specific use case to test?
