### ISSUE TITLE
Possibility to download/upload a layer and the corresponding metadata programmatically

### ISSUE THREAD

**Issue by ptormene** [GeoNode/geonode#2028]
Downloading a layer and its metadata programmatically is not so straightforward, because it requires an additional server-side query on the DB to retrieve the url to be used to download the metadata xml.
The new `api/layers` is useful to list the available layers, although it would be good if it could contain more information such as, for instance, the url to get the metadata, and the keywords associated to the layer (useful to filter layers by keyword).
It would also be useful to have an additional API to list licenses, which would allow to upload layers adding one of the available licenses to the metadata. In such case, we noticed it's not possible to specify a license in the "license" field, but we had to specify it inside the "restrictions".
Furthermore, is it possible to define a new metadata field to store some other specific information, in order to avoid using the "supplemental information" one?

**Comment by mcarans** [comment]
No explanation has been given about why this issue was closed. Was it completed or rejected?

**Comment by afabiani** [comment]
Closed because too old, however, the GeoNode 2.10.1 allows you to download everything zipped by using the "Original Dataset" download link.
