### ISSUE TITLE
NEVER show nasty GeoServer errors to the user

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2029]
We should NEVER show these kind of errors to the user since they are completely useless to them. We should instead give them a nice message and tell them to contact the administrator when some sort of issue number or link or something that the admin can look up. Ill file a separate issue for this.

![](https://camo.githubusercontent.com/54709729205aa02c2196ee3df045da42812f29ef/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3530363037382f313536353134392f63653736386530612d353037392d313165332d383138322d3131663066316163363965302e706e67)

**Comment by jj0hns0n** [comment]
@ingenieroariel can you implement this using the error logging etc you implemented.

**Comment by ingenieroariel** [comment]
Not really, we are getting this kind of error straight from OWSLib or gsconfig. Hiding this would mean hiding all the other more user friendly errors.

**Comment by vdeparday** [comment]
I think it should:
- send an automatic email to the admin with a link to the upload session
- have a user friendly message for the user mentioning that the admin has been warned and will get back in touch with him and include the email of the user so the admin can do the follow-up.

**Comment by jj0hns0n** [comment]
I havent seen this in a long time, but also we will be switching to the django-osgeo-importer soon.
