### ISSUE TITLE
Style editor not working on demo server

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#2031]
On local developers machines, styling works fine. But it is not working on the packages version of GeoNode.

**Comment by ingenieroariel** [comment]
Looked into this.

There is a PUT request happening at the start of the editing session. This put request is never returning, therefore, no other request are made and the style is not changed.

The endpoint that the style editor is trying to hit, is not directly a GeoServer endpoint, but a django based proxy. 

In development editing works and there is no apache based proxy, but in production it does not work, this request has both a regular proxy (Apache) and a custom one at /gs/.

@capooti hinted that this may be related to checking permissions for styles.

**Comment by rajanski** [comment]
Hey can we reopen this? it still happens on my 2.4b25 installation

**Comment by simod** [comment]
Can you post the errors you get on the ml? On the demo site seems to work

**Comment by rajanski** [comment]
HI I dont get any errors, it is just notworking, along the lines of : There is a PUT request happening at the start of the editing session. This put request is never returning, therefore, no other request are made and the style is not changed.

**Comment by simod** [comment]
Well, the behavior of the PUT is correct, on demo is the same. Let's switch to the ml to understand any potential errors.

**Comment by ingenieroariel** [comment]
This is the same problem I saw when we were at the sprint. A PUT request
that never returned.
