### ISSUE TITLE
Create a cache preseed button in the layer detail page

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#2038]
To avoid performance issues.

**Comment by vdeparday** [comment]
I would be in favour of automating the generation of cache for sane default, especially once it is working with celery. 
For instance, with the large files from #362 from http://www.iucnredlist.org/technical-documents/spatial-data, it takes up a very long time to display any data.

**Comment by jj0hns0n** [comment]
need to reconsider this in light of djmp. Moving to 2.7

**Comment by t-book** [comment]
I think this issues should finished: https://github.com/GeoNode/geonode/blob/2.8.x/geonode/layers/templates/layers/layer_detail.html#L661

**Comment by t-book** [comment]
@afabiani I think this can be closed ?!
