### ISSUE TITLE
Integrate geoserver authentication fixes

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#2039]
*  [ ] This PR needs to be merged
https://github.com/GeoNode/geoserver-geonode-ext/pull/30
 *  [ ] A new geoserver-geonode-ext release needs to be made to dev.geonode.org
 *  [ ] A new geoserver-geonode needs to be created and put into launchpad.net

**Comment by ischneider** [comment]
Added a note to #30 - I don't think it's required and it's also dangerous.

**Comment by simod** [comment]
closing as fixed
