### ISSUE TITLE
Core committers individual policy

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#2042]
After discussion among the developers during the code sprint we think that the core developers should only be individuals and not organizations, for security. Can other core devs comment on this?

**Comment by JJediny** [comment]
+1

**Comment by garnertb** [comment]
+1

**Comment by tomkralidis** [comment]
+1

**Comment by state-hiu** [comment]
As this directly affects me, I don't think this decision should be made quickly.  Not theoretically opposed, but this would affect internal key management practices.  In the same discussion, we should consider other ways to better highlight institutional support for GeoNode.  The gallery at http://geonode.org/gallery/ is not the best user experience and the twitter account is not very active (https://twitter.com/geonode).

**Comment by gamesbook** [comment]
+1

**Comment by simod** [comment]
+1

2015-02-05 8:32 GMT+01:00 Derek Hohls <notifications@github.com>:

> +1
>
> On 5 February 2015 at 06:28, Humanitarian Information Unit <
>
> notifications@github.com> wrote:
>
> > As this directly affects me, I don't think this decision should be made
> > quickly. Not theoretically opposed, but this would affect internal key
> > management practices. In the same discussion, we should consider other
> ways
> > to better highlight institutional support for GeoNode. The gallery at
> > http://geonode.org/gallery/ is not the best user experience and the
> > twitter account is not very active (https://twitter.com/geonode).
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2042#issuecomment-72992534>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2042#issuecomment-73005638>.
>



-- 
Simone

**Comment by capooti** [comment]
+1

On Thu, Feb 5, 2015 at 9:06 AM, Simone Dalmasso <notifications@github.com>
wrote:

> +1
>
>
> 2015-02-05 8:32 GMT+01:00 Derek Hohls <notifications@github.com>:
>
> > +1
> >
> > On 5 February 2015 at 06:28, Humanitarian Information Unit <
> >
> > notifications@github.com> wrote:
> >
> > > As this directly affects me, I don't think this decision should be made
> > > quickly. Not theoretically opposed, but this would affect internal key
> > > management practices. In the same discussion, we should consider other
> > ways
> > > to better highlight institutional support for GeoNode. The gallery at
> > > http://geonode.org/gallery/ is not the best user experience and the
> > > twitter account is not very active (https://twitter.com/geonode).
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/GeoNode/geonode/issues/2042#issuecomment-72992534
> >.
> >
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2042#issuecomment-73005638>.
> >
>
>
>
> --
> Simone
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2042#issuecomment-73008760>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by jj0hns0n** [comment]
+1

**Comment by ingenieroariel** [comment]
@state-hiu, this highlights the issue we are trying to resolve, right
now I am not sure I am talking to Patrick or someone else, and I would
not trust anyone other than Patrick to be able to modify GeoNode. Put
another way, accounts owned by multiple users (in my org there are
thousands) are not compatible with the kind of meritocracy we expect
in Open Source projects.

I had not really thought about it in the past, but it was brought up
during the code sprint and I believe it is important to resolve it.

That said, I am very interested in your position, could you elaborate more?

**Comment by state-hiu** [comment]
I fully agree that we should move to individual accounts for security.  I'm definitely supportive of efforts to bump up our security.

If we want to update our security posture, there are other steps we should take too, such as requiring two-factor authentication (easier with individual accounts rather than group accounts).  Individual accounts don't actually increase security that much if keys are just stored in plain text on corporate/organization computers without two-factor.

**Comment by jj0hns0n** [comment]
@ingenieroariel can we close this?
