### ISSUE TITLE
ISO XML template cache rendered before links created

### ISSUE THREAD

**Issue by alanswx** [GeoNode/geonode#2044]
ISO XML metadata is missing geoserver download links because the XML ISO template that is rendered in catalogue_post_save happens before geoserver_post_save signal is called.

AJS - catalogue_post_save TOP of function
these are the links available at the catalogue call:
md link: Atom 
md link: DIF 
md link: Dublin Core 
md link: ebRIM 
md link: FGDC 
md link: ISO 
AJS geoserver_post_save

**Comment by state-hiu** [comment]
I labelled this as critical.  This should be fixed in 2.4, but should not necessarily hold up the first 2.4 release candidate.

**Comment by simod** [comment]
This will for sure be fixed when we also fix this https://github.com/GeoNode/geonode/issues/2015, the issue is that the signals cannot be prioritized so it is difficult to fix with the current architecture

**Comment by simod** [comment]
I'm pushing a very ugly workaround for this. Could you check that is working now? I'm punting this issue to 2.5.

**Comment by mwengren** [comment]
@simod @alanswx the workaround gets the job done.  catalogue_post_save is executed twice, once before geoserver_post_save has generated the download links and once again after they've been added.  may not be pretty but works for the moment...

**Comment by simod** [comment]
Is not just not pretty, it's horrible. :-) we might deactivate the
catalogue_pre_save from catalogue though. For now.

Il giovedì 5 febbraio 2015, Micah Wengren <notifications@github.com> ha
scritto:

> @simod <https://github.com/simod> @alanswx <https://github.com/alanswx>
> the workaround gets the job done. catalogue_post_save is executed twice,
> once before geoserver_post_save has generated the download links and once
> again after they've been added. may not be pretty but works for the
> moment...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2044#issuecomment-73120950>.
>


-- 
Simone

**Comment by jj0hns0n** [comment]
@simod can we close this?

**Comment by simod** [comment]
no, this is not a "issue" but definitely a TODO. Let's keep it.
