### ISSUE TITLE
Layer Upload error using 2.4b.19

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2046]
Getting the following error, used two tested shapefiles:
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/john/geonode/geonode/layers/views.py", line 174, in layer_upload
    upload_session = latest_uploads[0]
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 132, in __getitem__
    return list(qs)[0]
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 96, in __iter__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 450, in execute
    return Database.Cursor.execute(self, query, params)
OperationalError: no such column: layers_uploadsession.context
[04/Feb/2015 21:29:15] "POST /layers/upload HTTP/1.1" 500 49692

**Comment by simod** [comment]
Seems that you upgraded from an older beta. Just need to rebuild the db.

Il giovedì 5 febbraio 2015, John Jediny <notifications@github.com> ha
scritto:

> Getting the following error, used two tested shapefiles:
> Internal Server Error: /layers/upload
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line
> 112, in get_response
> response = wrapped_callback(request, *callback_args, **callback_kwargs)
> File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py",
> line 22, in
>
>
>
> *wrapped_view return view_func(request, args, *kwargs) File
> "/home/john/geonode/geonode/layers/views.py", line 174, in layer_upload
> upload_session = latest_uploads[0] File
> "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 132, in
> __getitem_*
> return list(qs)[0]
> File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line
> 96, in *iter*
> self.
>
>
>
>
>
>
>
>
>
>
>
>
> *fetch_all() File
> "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in
> fetch_all self._result_cache = list(self.iterator()) File
> "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in
> iterator for row in compiler.results_iter(): File
> "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line
> 710, in results_iter for rows in self.execute_sql(MULTI): File
> "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line
> 781, in execute_sql cursor.execute(sql, params) File
> "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 69, in
> execute return super(CursorDebugWrapper, self).execute(sql, params) File
> "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in
> execute return self.cursor.execute(sql, params) File
> "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit*
> six.reraise(dj_exc_type, dj_exc_value, traceback)
> File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line
> 53, in execute
> return self.cursor.execute(sql, params)
> File
> "/usr/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line
> 450, in execute
> return Database.Cursor.execute(self, query, params)
> OperationalError: no such column: layers_uploadsession.context
> [04/Feb/2015 21:29:15] "POST /layers/upload HTTP/1.1" 500 49692
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2046>.
>


-- 
Simone

**Comment by cwillmes** [comment]
I just got that same error. How can I rebuild the DB? 'geonode syncdb' did not work...

**Comment by simod** [comment]
syncdb can't modify existing tables. You have to either delete the table and the rebuild with syncdb (deleting only this table may result in consistency issues though, so you should dump the db, drop it recreate and load back the data) or manually add the "context" column to the layers_uploadsession table

**Comment by cwillmes** [comment]
Thanks @simod , but I think I would loose all my layers in that instance? Would a sudo apt-get upgrade geonode (I'm on  2.4b24) solve that without loosing the data?

**Comment by simod** [comment]
nope  upgrading won't solve. The suggested way is to backup the db, recreate it and load back the data. Something similar to http://docs.geonode.org/en/master/tutorials/admin/backup/index.html

**Comment by cwillmes** [comment]
ok, so following the steps in the tutorial would fix the problem? Or what is meant by 'recreate' before load backl the data?

**Comment by simod** [comment]
you can delete the db and create it back or, to be super safe, just create a new empty db and load the dumped data in it then change the local_setting to point to it.

**Comment by cwillmes** [comment]
that would be step 4 under "Restoring a backup" in the turorial right? My question is, what do I need to do additionally to the tutorial? Or is the tutoral all I need to do?

**Comment by simod** [comment]
right + the step of backup creation 1.
@cwillmes if you need further assistance please switch to the users mailing list.

**Comment by cwillmes** [comment]
@simod I think we somehow talk past each other, the sugested steps did not solve the problem. I posted on the list for further conversation about it: https://lists.osgeo.org/pipermail/geonode-users/2015-July/000585.html
