### ISSUE TITLE
link to sld does not work with sld with differents names

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#2048]
default point, for example, his geoserver name is not the same as the name in sld tag :

![image](https://cloud.githubusercontent.com/assets/6357213/6057133/c54ed59a-ad1a-11e4-841b-2533dc755f20.png) 

if you try to follow the link from geonde for default point you'll be redirected to a bad url  :
![image](https://cloud.githubusercontent.com/assets/6357213/6057156/fedccc86-ad1a-11e4-8c9c-70dfdedbaadc.png)

The url opened is a 404 /geoserver/styles/point.sld
Should be the one /geoserver/styles/default_point.sld

**Comment by afabiani** [comment]
A call to the GeoServer REST API

geoserver/rest/styles/point.xml

would give back the name of the SLD filename:

<style>
<name>point</name>
<format>sld</format>
<languageVersion>
<version>1.0.0</version>
</languageVersion>
<filename>default_point.sld</filename>
</style>
