### ISSUE TITLE
saving style in the management style section with nothing broke the page

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#2049]
if you save your layer with 0 style the page broke end like this with no avaible styles.

![image](https://cloud.githubusercontent.com/assets/6357213/6057264/9d12d994-ad1c-11e4-90cc-fa850aa7e4e1.png)

**Comment by teamgeode** [comment]
Error is here https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/views.py#L212
No style is selected so we catch the exception but no style is transferred.

**Comment by pjdufour** [comment]
@jj0hns0n, close issue?

**Comment by jj0hns0n** [comment]
@teamgeode @collaer can this be closed?
