### ISSUE TITLE
when updating style in manage style screen, you remove types for metadatas in geoserver 

### ISSUE THREAD

**Issue by collaer** [GeoNode/geonode#2050]
example workflow to reproduce 

1. for a point layer open the "edit layer" --> "style" --> "manage" option.
2. add a second style, the default one for your gemetry type (default_point), to your layer (in this case default point style) and select it as new default style.
3. select the new style as default style and save, the page go back to layer management section. You see the style with the
4. The layer on geoserver when showing publication tab : 
![image](https://cloud.githubusercontent.com/assets/6357213/6057295/012dc6dc-ad1d-11e4-837b-7175b27d95a8.png)
5. but you can fix it setting it manually on geoserver
![image](https://cloud.githubusercontent.com/assets/6357213/6057611/03576e6a-ad20-11e4-92ca-0b1b3d5c8716.png)

**Comment by simod** [comment]
will be fixed by this https://github.com/boundlessgeo/gsconfig/pull/92
