### ISSUE TITLE
Add users to groups during the "User Invitation" process

### ISSUE THREAD

**Issue by WorldFoodProgramme** [GeoNode/geonode#2052]
If there is the need to add users to existing groups, it would be good to do it when an invitation is sent instead of reprocessing the user profile later.

**Comment by daniviga** [comment]
+1

**Comment by garnertb** [comment]
@capooti, should this be bumped to 2.5.x?

**Comment by capooti** [comment]
There are no schema changes, so we can event consider to include this in 2.4 if someone is working on it, but we must find a smart way not to add a geonode/groups dependency to our django-user-accounts fork, if in the long run we are willing to reconcile this with the upstream version.
