### ISSUE TITLE
Import selected layers only from a remote service

### ISSUE THREAD

**Issue by ppasq** [GeoNode/geonode#2055]
Right now all the layers from a Remote Service are imported while it would be more efficient to list all the layers available and select the ones that actually are to be imported.

**Comment by capooti** [comment]
this would be a very nice feature to have.
Will try to implement a very raw version in the next days.

**Comment by vdeparday** [comment]
+1, it would be very nice, for instance we have use cases where we would
want to only import hazard layers and not all layers.

**Comment by pjdufour** [comment]
+1

**Comment by capooti** [comment]
starting to look into this right now.

**Comment by jj0hns0n** [comment]
@capooti I remember you working on this in NOLA. Did you ever get it finished?
