### ISSUE TITLE
GNIP: Configure Remote Services as a GUI for using MapProxy (optional)

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2064]
The new feature of registering remote services is great, but there are some major limitations:
- Users can only register WMS services that support the Web Mercator projection
- Even if/when other remote WMS services can be "cascaded" and dynamically re-projected using Geoserver there are some major drawbacks:
  - Geoserver will eat up a ton of system resources to reproject on the fly, simultaneously competing with rendering locally data hosted on geonode
  - Geoserver cascading WMS does not support GetFeatureInfo or GetLegend requests. Without these the layer is essentially image rendered on the map with now interaction which makes it essential useless
- Geoserver only supports cascading/re-projecting WMS & WFS services
- Geoserver can only handle one WMS endpoint as one layer, if user wanted to combine multiple layers from a service into one tile; one would have to create a layergroup but the request to the remote service is still being made as multiple requests.
## Proposal

Integrating Remote Services is a huge benefit, and the work done to use django/geonode to harvest, parse, and register services by their GetCapabilities is an achievement in itself. However if what we want is functionality/stability/scalablity we need to support the integration of [MapProxy](http://mapproxy.org) instead of Geoserver for this discreet task. My proposal is to approach/support remote services as a GUI for MapProxy, which would use the current functionality in geonode to harvest/parse/register each available layer as an end point, users could then select which layers they want #2055 as a single/consolidated layer by taking advantage of [MapProxy's cmd line utility](http://mapproxy.org/docs/1.7.0/mapproxy_util_autoconfig.html) to pass it only those endpoints the user selects as the input/trigger for the auto-config process to run and create the required configuration file MapProxy would use for the consolidated layer... As MapProxy itself is a WMS/Tile Server users could register it as a remote service in GeoNode and have all of the functionality of (reprojecting on the fly, getfeatureinfo and legend support, and even download as MapProxy can create its cache as MBtiles. 

Moving forward I think we should approach remote services framework to support both approaches; using remote services natively (as is) and as a way to programmatically integrate and register services to MapProxy...

**Comment by jj0hns0n** [comment]
@jjediny lets work together to turn this into a more formal GNIP

**Comment by blewis** [comment]
+1 this is a fantastic idea

**Comment by ingenieroariel** [comment]
I also think this is a great idea and would be interested in reviewing the first draft of the gnip.

**Comment by JJediny** [comment]
Think we might now have a starting point for discussions around the mapproxy/remote services GUI GNIP - https://github.com/ROGUE-JCTD/django-tilebundler

@ingenieroariel what more are we looking for in a GNIP... I can't edit the wiki

**Comment by jj0hns0n** [comment]
ref #2602 check https://github.com/terranodo/django-mapproxy (the successor to django-tilebundler)
