### ISSUE TITLE
Layer name cannot be a style name already on Geoserver

### ISSUE THREAD

**Issue by teamgeode** [GeoNode/geonode#2070]
Uploading a layer with the same name that a style already in Geoserver make that layer used this style.

Use case: 
* Rename a layer from your computer by the name “point”.
* Upload it by Geonode.

![style error](https://cloud.githubusercontent.com/assets/9469134/6124332/d84c3b60-b10c-11e4-8c8f-4036772e28f1.jpg)

(This is the same layer uploaded twice.)

Working on master.

**Comment by afabiani** [comment]
Seems to work fine if using the GeoServer Importer as Upload method
(at least with the latest GeoServer 2.7.x integration)

![image](https://cloud.githubusercontent.com/assets/1278021/8825261/06fb4118-307e-11e5-9c07-39f4704a8a73.png)

**Comment by teamgeode** [comment]
I tested with a new installation based on master and the problem is still here. (geoserver version : 2.7-SNAPSHOT)

But to import layers, I use Geonode (/layers/upload)
Like a simple user will use it.

**Comment by jj0hns0n** [comment]
This is an edge case. Im going to move it to 2.7. @afabiani there may be a simple fix?

**Comment by afabiani** [comment]
The following PR 

https://github.com/GeoNode/geonode/pull/2610

fixes the issue.

**Comment by jj0hns0n** [comment]
@teamgeode can you test. Closing.
