### ISSUE TITLE
ogc_server_settings.LOG_FILE return None in development mode 

### ISSUE THREAD

**Issue by teamgeode** [GeoNode/geonode#2080]
Working on master, I catch an error here https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L83 because the ogc_server_settings.LOG_FILE return None during the loading here https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L65

Don't know if it's normal because it's on master?

```
Traceback (most recent call last):
  File "/home/.venvs/geonode/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/.venvs/geonode/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/geonode/geonode/layers/views.py", line 177, in layer_upload
    upload_session.context = log_snippet(CONTEXT_LOG_FILE)
  File "/var/www/geonode/geonode/layers/views.py", line 83, in log_snippet
    if not os.path.isfile(log_file):
  File "/home/.venvs/geonode/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
```

**Comment by simod** [comment]
@teamgeode weird, the LOG_FILE is defined here https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L518, Could you check in a shell that ogc_server_settings.LOG_FILE exists for you?
I neve experienced this error

**Comment by teamgeode** [comment]
The file exist on the folder
```
(geonode)root@vagrant-ubuntu-trusty-64:/var/www/geonode# tree -f | grep /geoserver/data/logs/geoserver.log
│   │   │   ├── ./geoserver/data/logs/geoserver.log
```
but the shell don't find the parameter:
```
Python 2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from geonode.geoserver.helpers import ogc_server_settings
>>> CONTEXT_LOG_FILE = ogc_server_settings.LOG_FILE
>>> print(CONTEXT_LOG_FILE)
None
```

**Comment by simod** [comment]
hm, how can we reproduce this error?

**Comment by teamgeode** [comment]
In a new instance try to put a print() after https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L65
```
(geonode)root@vagrant-ubuntu-trusty-64:/var/www/geonode# git branch
* master
(geonode)root@vagrant-ubuntu-trusty-64:/var/www/geonode# git pull
Already up-to-date.
(geonode)root@vagrant-ubuntu-trusty-64:/var/www/geonode# nano geonode/layers/views.py
```
```
if 'geonode.geoserver' in settings.INSTALLED_APPS:
    from geonode.geoserver.helpers import _render_thumbnail
    from geonode.geoserver.helpers import ogc_server_settings
    CONTEXT_LOG_FILE = ogc_server_settings.LOG_FILE
    print('   ogc_server_settings.LOG_FILE = ')
    print(ogc_server_settings.LOG_FILE)
```
In my case when I up the server I see this :
```
(geonode)root@vagrant-ubuntu-trusty-64:/var/www/geonode# python manage.py runserver 0.0.0.0:8000
Validating models...

0 errors found
February 20, 2015 - 04:36:50
Django version 1.6.10, using settings 'geonode.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
   ogc_server_settings.LOG_FILE =
None
[20/Feb/2015 04:36:56] "GET /layers/upload HTTP/1.1" 200 31736
[20/Feb/2015 04:36:56] "GET /jsi18n/ HTTP/1.1" 200 13038
[20/Feb/2015 04:36:56] "GET /lang.js HTTP/1.1" 200 10016
```

You can see   
ogc_server_settings.LOG_FILE =
None

**Comment by simod** [comment]
It works for me, do you have the LOG_FILE parameter in the settings? or did you override the OGC_SERVER settings in local_settings.py omitting that entry?

**Comment by teamgeode** [comment]
Well yes the OGC_SERVER doesn't have the LOG_FILE entry https://github.com/GeoNode/geonode/blob/master/geonode/local_settings.py.sample#L23

And so yes during the paver setup, local_setting.py was create without it.

Can we add the entry in the sample file to corect that ?

**Comment by teamgeode** [comment]
Well that strange cause I recreate a instance and the local_setting was not created during the install … don’t know why this file come here early ;p

Thx again @simod.

**Comment by simod** [comment]
Thanks for debugging, will fix that now :)

**Comment by simod** [comment]
https://github.com/GeoNode/geonode/commit/f2b6c80901e92b04cec731b56913ae12bd2af980
