### ISSUE TITLE
Map Layers are missing in the WMC definition

### ISSUE THREAD

**Issue by ndufrane** [GeoNode/geonode#2082]
Hi,

When i download the wmc definition of a map, the xml is generated correctly but without the layers defined in my map.

![image](https://cloud.githubusercontent.com/assets/471217/6288720/42668c7e-b91b-11e4-9c32-962cdb31ebae.png)

The problem seems located here https://github.com/GeoNode/geonode/blob/master/geonode/maps/templates/maps/wmc.xml#L44
and 
https://github.com/GeoNode/geonode/blob/master/geonode/maps/templates/maps/wmc.xml#L48

It should be layer.ows_url instead of layer.get_ows_url ?

**Comment by tomkralidis** [comment]
Thanks @ndufrane.  Fixed in master.
