### ISSUE TITLE
Need unique constraint for GroupMember model

### ISSUE THREAD

**Issue by gamesbook** [GeoNode/geonode#2088]
The current GroupMember model definition has no 'unique together' constraint.  I found this when I was using code to create a set of groups & members.  I don't think it makes sense to allow a user to join a group twice. 

Current:

```
class GroupMember(models.Model):

    group = models.ForeignKey(GroupProfile)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    role = models.CharField(max_length=10, choices=[
        ("manager", _("Manager")),
        ("member", _("Member")),
    ])
    joined = models.DateTimeField(default=datetime.datetime.now)
```

 Suggested patch:

```
class GroupMember(models.Model):

    group = models.ForeignKey(GroupProfile)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    role = models.CharField(max_length=10, choices=[
        ("manager", _("Manager")),
        ("member", _("Member")),
    ])
    joined = models.DateTimeField(default=datetime.datetime.now)

    class Meta:
        unique_together = [("group", "user", "role")]
```

**Comment by state-hiu** [comment]
The following line at https://github.com/GeoNode/geonode/blob/master/geonode/groups/models.py#L137 should prevent users from being added twice from the user interface.

```
member, created = GroupMember.objects.get_or_create(group=self, user=user, defaults=kwargs)
```

I've never used unique_together, so don't have any direct suggestions.

**Comment by gamesbook** [comment]
@state-hiu Thanks, that is useful.  I still think preserving uniqueness in the underlying model (and database table) is worthwhile - unique_together is a common idiom in Django.

**Comment by garnertb** [comment]
I agree @gamesbook, this constraint needs to be added to the model.  

One question though:  Why are you including the role in the constraint?  That would still allow the user to be in the group twice, once as a member and once as a manager.

Can you submit a PR for this?

**Comment by jj0hns0n** [comment]
@gamesbook can we get a PR for this? Moving to 2.7 but if you can get this done in the next week or so, please move it back and close.

**Comment by jondoig** [comment]
Is this the issue behind the error I just encountered? I created a group, then tried to add myself and instead of a simple message such as 'The invited user "jondoig" is already a member,' I got a "ValueError at /groups/group/CityFutures-City-Analytics/members_add/" with full debug details.

**Comment by simod** [comment]
@jondoig are you using geonode ui to manage groups? if not be sure to do so and don't use the admin.

**Comment by jondoig** [comment]
Yes the UI. I was logged in as me (jondoig) not admin, so the system
automatically added me to the group when I created it. Hence it complained
when I tried to add me (again). So it was correct to complain, but it
should do so nicely in the UI, not with debug details.

I later saw down the very bottom of the error page that I have debug on,
and if I turn it off I'll get a simple 500 server error. That doesn't sound
desirable either.

Using Geonode 2.4 on Windows 7.

**Comment by jondoig** [comment]
This is still a bug imho @simod . If you try to add someone (e.g. yourself) to a  group when they're already a member, you get an ugly "Internal Server Error".

The Apache error log already contains the necessary message: "The invited user "{{username}}" is already a member".
