### ISSUE TITLE
pycsw querying elementSetName=full

### ISSUE THREAD

**Issue by AgentJay** [GeoNode/geonode#2091]
Hello, this might be a bug, but this is also a support request.

I would like to add more fields to the metadata output in Pycsw when the full element set is queried. Currently I use the following request:

`/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&namespace=csw:http://www.opengis.net/cat/csw&maxRecords=1000&elementSetName=full&constraintLanguage=CQL_TEXT&constraint_language_version=1.1.0&typeNames=csw%3ARecord`

The results are only summaries of the records and not the full record set. 
I'm not interested in the full set necessarily, but I do need to add a few fields at least. How do I do it?

Thanks.

**Comment by tomkralidis** [comment]
@AgentJay try specifying `outputschema=http://www.isotc211.org/2005/gmd` in your URL?  e.g.:

`/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd`

This should return the full record as stored in GeoNode (which uses ISO).  Asking for anything other than ISO with `elementsetname=full` will provide a transformed document (FGDC, DC, etc.), which, compared to ISO, will be considerably thinner.
