### ISSUE TITLE
geonode install in 12.04 in Docker fails

### ISSUE THREAD

**Issue by gubuntu** [GeoNode/geonode#2092]
I cannot get the Docker build in the repo to work so am trying a 'VM-like' install as per normal installation instructions. 

I'm hitting this obstacle - geoserver-geonode not installing:

Setting up tomcat7 (7.0.26-1ubuntu1.2) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline

Creating config file /etc/default/tomcat7 with new version
Adding system user `tomcat7' (UID 102) ...
Adding new user `tomcat7' (UID 102) with group `tomcat7' ...
Not creating home directory `/usr/share/tomcat7'.
invoke-rc.d: policy-rc.d denied execution of start.
Setting up geoserver-geonode (2.0+201311140000) ...
 * Starting Tomcat servlet engine tomcat7                                                                                                       [fail] 
dpkg: error processing geoserver-geonode (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of geonode:
 geonode depends on geoserver-geonode | geoserver; however:
  Package geoserver-geonode is not configured yet.
  Package geoserver is not installed.
dpkg: error processing geonode (--configure):
 dependency problems - leaving unconfigured
...
Errors were encountered while processing:
 geoserver-geonode
 geonode
E: Sub-process /usr/bin/dpkg returned an error code (1)

Any clues?

**Comment by milafrerichs** [comment]
Hello,

I might be able to help. Are you using the Dockerfile provided in this repo? Or are you suing a different file? If so is there a reason why you are not using the current one?
Is the error occurring on the build process? 

mila

**Comment by gubuntu** [comment]
Hi Mila. I've tried the Dockerfile in the repo and
1) I cannot get it to work (details below)
2) I need to set up a production instance of Geonode with Tomcat and Apache instead of Jetty and Django's internal server. 

I would like to get both working (repo dev Docker + production Docker) and would be grateful for your assistance. 

This is what happens when I run fig (or now, docker-compose) build:
1) I figured out I had to manually add a 'geoserver' directory in the repo dir, which the paver script expects but doesn't create. 
2) The build then gets to this point:
Step 6 : RUN paver setup
 ---> Running in 0b5089c56cc6
---> pavement.setup
---> pavement.setup_geoserver


Captured Task Output:
---------------------

---> pavement.setup
---> pavement.setup_geoserver
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 195, in _run_task
    return do_task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 191, in do_task
    task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 320, in __call__
    retval = environment._run_task(self.name, self.needs, self.func)
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 213, in _run_task
    return do_task()
  File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 192, in do_task
    return func(**kw)
  File "pavement.py", line 106, in setup_geoserver
    _install_data_dir()
  File "pavement.py", line 118, in _install_data_dir
    with open(config) as f:
IOError: [Errno 2] No such file or directory: path('geoserver/data/security/auth/geonodeAuthProvider/config.xml')

Service 'app' failed to build: The command [/bin/sh -c paver setup] returned a non-zero code: 1

**Comment by milafrerichs** [comment]
> 1) I figured out I had to manually add a 'geoserver' directory in the repo dir, which the paver script expects but doesn't create. 

no you don't have to create a geoserver dir. it will be created here: https://github.com/GeoNode/geonode/blob/master/pavement.py#L96
what is the error when you don't create the geoserver dir?

**Comment by gubuntu** [comment]
It builds but does not come up:

Creating geonode_app_1...
Attaching to geonode_app_1
app_1 | ---> pavement.start
app_1 | ---> pavement.start_geoserver
app_1 | cd /geonode/geoserver/data
app_1 | 
app_1 | 
app_1 | Captured Task Output:
app_1 | ---------------------
app_1 | 
app_1 | ---> pavement.start
app_1 | ---> pavement.start_geoserver
app_1 | cd /geonode/geoserver/data
app_1 | Traceback (most recent call last):
app_1 |   File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 195, in _run_task
app_1 |     return do_task()
app_1 |   File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 191, in do_task
app_1 |     task()
app_1 |   File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 320, in __call__
app_1 |     retval = environment._run_task(self.name, self.needs, self.func)
app_1 |   File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 213, in _run_task
app_1 |     return do_task()
app_1 |   File "/usr/lib/pymodules/python2.7/paver/tasks.py", line 192, in do_task
app_1 |     return func(**kw)
app_1 |   File "pavement.py", line 361, in start_geoserver
app_1 |     with pushd(data_dir):
app_1 |   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
app_1 |     return self.gen.next()
app_1 |   File "/usr/lib/pymodules/python2.7/paver/path.py", line 39, in pushd
app_1 |     os.chdir(dir)
app_1 | OSError: [Errno 2] No such file or directory: '/geonode/geoserver/data'
app_1 | 
geonode_app_1 exited with code 1

**Comment by dmcd** [comment]
Is there a work around for this? I'm having difficulty running the install on Mac and would prefer to use docker.

**Comment by jj0hns0n** [comment]
ref #2593

**Comment by jj0hns0n** [comment]
@gubuntu Im going to close this as we are moving to a formal docker-compose setup.
