### ISSUE TITLE
geonode 2.4: Error saving style in geoExplorer

### ISSUE THREAD

**Issue by darabk** [GeoNode/geonode#2095]
after installation of some extensions in geoserver (eg: oracle, sqlServer, arcSDE ,..), and add some layers with them,
When changing style in creating map or viewing layer, "there was an error saving the style back to the server" appeares.
please help..

**Comment by simod** [comment]
@darabk do you mind to use the mailing list geonode-users@lists.opengeo.org to ask for support. This doesn't seems (yet) to be a bug.  Thanks!
