### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by rodekruis** [GeoNode/geonode#2097]
Hi, I am running geonode in production on a dns domain. I have followed the custom installation manual.

I experience two problems that are possibly related:
- When I go to the geoserver admin, the superuser authentication is not federated to the geoserver. I can login with the admin user + password, but to my understanding this should not have to be
- When i upload a layer through the frontend in geonode, I get a 401 authentication error.

My VirtualHost setting is as follows:

    WSGIDaemonProcess geonode user=www-data threads=15 processes=2
    <VirtualHost *:80>
    Servername sapplies.rodekruis.nl
    ServerAdmin webmaster@localhost

    ErrorLog /var/log/apache2/error.log
    LogLevel warn
    CustomLog /var/log/apache2/access.log combined

    WSGIProcessGroup geonode
    WSGIPassAuthorization On
    WSGIScriptAlias / /var/www/geonode/wsgi/geonode.wsgi

    <Directory "/var/www/geonode/">
       Order allow,deny
        Options Indexes FollowSymLinks
        Allow from all
        IndexOptions FancyIndexing
    </Directory>

    Alias /static/ /var/www/geonode/static/
    Alias /uploaded/ /var/www/geonode/uploaded/
    Alias /robots.txt /var/www/geonode/robots.txt

    <Directory "/var/www/geonode/uploaded/documents/">
       Order allow,deny
       Deny from all
    </Directory>

    <Proxy *>
      Order allow,deny
      Allow from all
    </Proxy>

    ProxyPreserveHost On
    ProxyPass /geoserver http://localhost:8080/geoserver
    ProxyPassReverse /geoserver http://localhost:8080/geoserver
    </VirtualHost>

Tomcat7 is running and the geoserver is listening on port 8080.

The error from the upload sessions is shown below:

('GeoServer gave non-XML response for [GET http://localhost:8080/geoserver/rest/workspaces.xml]: <html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style></style> </head><body><h1>HTTP Status 401 - Communication with GeoNode failed</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Communication with GeoNode failed</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>', ParseError(ExpatError('mismatched tag: line 1, column 1355',),))

Traceback (most recent call last):
  File "/home/maarten/geonode/geonode/layers/views.py", line 163, in layer_upload
    title=form.cleaned_data["layer_title"],
  File "/home/maarten/geonode/geonode/layers/utils.py", line 379, in file_upload
    defaults=defaults
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 154, in get_or_create
    return self.get_queryset().get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line 341, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 383, in get_or_create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py", line 90, in save
    return super(PolymorphicModel, self).save(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 582, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py", line 185, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/maarten/geonode/geonode/geoserver/signals.py", line 159, in geoserver_post_save
    workspace=instance.workspace)
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 599, in get_resource
    workspace = self.get_workspace(workspace)
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 772, in get_workspace
    candidates = [w for w in self.get_workspaces() if w.name == name]
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 768, in get_workspaces
    description = self.get_xml("%s/workspaces.xml" % self.service_url)
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 186, in get_xml
    return parse_or_raise(content)
  File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line 177, in parse_or_raise
    raise Exception(msg, e)
Exception: ('GeoServer gave non-XML response for [GET http://localhost:8080/geoserver/rest/workspaces.xml]: <html><head><title>Apache Tomcat/7.0.52 (Ubuntu) - Error report</title><style></style> </head><body><h1>HTTP Status 401 - Communication with GeoNode failed</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>Communication with GeoNode failed</u></p><p><b>description</b> <u>This request requires HTTP authentication.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.52 (Ubuntu)</h3></body></html>', ParseError(ExpatError('mismatched tag: line 1, column 1355',),))

Any help is appreciated.

**Comment by simod** [comment]
Hi. You should also configure the smoke file in the geoserver data dir
/auth/geonodeauthprivider and point it to your Geonode base url. Then
restart Apache.

Il giovedì 12 marzo 2015, rodekruis <notifications@github.com> ha scritto:

> Hi, I am running geonode in production on a dns domain. I have followed
> the custom installation manual.
>
> I experience two problems that are possibly related:
>
>    - When I go to the geoserver admin, the superuser authentication is
>    not federated to the geoserver. I can login with the admin user + password,
>    but to my understanding this should not have to be
>    - When i upload a layer through the frontend in geonode, I get a 401
>    authentication error.
>
> My VirtualHost setting is as follows:
>
> WSGIDaemonProcess geonode user=www-data threads=15 processes=2
>
> Servername sapplies.rodekruis.nl
> ServerAdmin webmaster@localhost
>
> ErrorLog /var/log/apache2/error.log
> LogLevel warn
> CustomLog /var/log/apache2/access.log combined
>
> WSGIProcessGroup geonode
> WSGIPassAuthorization On
> WSGIScriptAlias / /var/www/geonode/wsgi/geonode.wsgi
>
> <Directory "/var/www/geonode/">
>    Order allow,deny
>     Options Indexes FollowSymLinks
>     Allow from all
>     IndexOptions FancyIndexing
> </Directory>
>
> Alias /static/ /var/www/geonode/static/
> Alias /uploaded/ /var/www/geonode/uploaded/
> Alias /robots.txt /var/www/geonode/robots.txt
>
> <Directory "/var/www/geonode/uploaded/documents/">
>    Order allow,deny
>    Deny from all
> </Directory>
>
> <Proxy *>
>   Order allow,deny
>   Allow from all
> </Proxy>
>
> ProxyPreserveHost On
> ProxyPass /geoserver http://localhost:8080/geoserver
> ProxyPassReverse /geoserver http://localhost:8080/geoserver
>
>  Tomcat7 is running and the geoserver is listening on port 8080.
>
> The error from the upload sessions is shown below:
>
> ('GeoServer gave non-XML response for [GET
> http://localhost:8080/geoserver/rest/workspaces.xml]:
> Apache Tomcat/7.0.52 (Ubuntu) - Error report&lt;!--H1
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;}
> H2
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;}
> H3
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}
> BODY
> {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}
> P
> {font-family:Tahoma,Arial,sans-serif;background-color:#525D76;font-size:16px;}
> H3
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}
> BODY
> {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}
> P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;
> font-size:12px;}A {color : black;}A.name {color : black;}HR {color :
> #525D76;}--&gt; HTTP Status 401 - Communication with GeoNode failed
> ------------------------------
>
> *type* Status report
>
> *message* Communication with GeoNode failed
>
> *description* This request requires HTTP authentication.
> ------------------------------
> Apache Tomcat/7.0.52 (Ubuntu)', ParseError(ExpatError('mismatched tag:
> line 1, column 1355',),))
>
> Traceback (most recent call last):
> File "/home/maarten/geonode/geonode/layers/views.py", line 163, in
> layer_upload
> title=form.cleaned_data["layer_title"],
> File "/home/maarten/geonode/geonode/layers/utils.py", line 379, in
> file_upload
> defaults=defaults
> File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py",
> line 154, in get_or_create
> return self.get_queryset().get_or_create(
>
> *kwargs) File
> "/usr/local/lib/python2.7/dist-packages/modeltranslation/manager.py", line
> 341, in get_or_create return super(MultilingualQuerySet,
> self).get_or_create(*kwargs)
> File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py",
> line 383, in get_or_create
> obj.save(force_insert=True, using=self.db)
> File
> "/usr/local/lib/python2.7/dist-packages/polymorphic/polymorphic_model.py",
> line 90, in save
> return super(PolymorphicModel, self).save(*args, **kwargs)
> File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py",
> line 545, in save
> force_update=force_update, update_fields=update_fields)
> File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py",
> line 582, in save_base
> update_fields=update_fields, raw=raw, using=using)
> File
> "/usr/local/lib/python2.7/dist-packages/django/dispatch/dispatcher.py",
> line 185, in send
> response = receiver(signal=self, sender=sender, **named)
> File "/home/maarten/geonode/geonode/geoserver/signals.py", line 159, in
> geoserver_post_save
> workspace=instance.workspace)
> File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line
> 599, in get_resource
> workspace = self.get_workspace(workspace)
> File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line
> 772, in get_workspace
> candidates = [w for w in self.get_workspaces() if w.name == name]
> File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line
> 768, in get_workspaces
> description = self.get_xml("%s/workspaces.xml" % self.service_url)
> File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line
> 186, in get_xml
> return parse_or_raise(content)
> File "/usr/local/lib/python2.7/dist-packages/geoserver/catalog.py", line
> 177, in parse_or_raise
> raise Exception(msg, e)
> Exception: ('GeoServer gave non-XML response for [GET
> http://localhost:8080/geoserver/rest/workspaces.xml]:
> Apache Tomcat/7.0.52 (Ubuntu) - Error report&lt;!--H1
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;}
> H2
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;}
> H3
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}
> BODY
> {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}
> P
> {font-family:Tahoma,Arial,sans-serif;background-color:#525D76;font-size:16px;}
> H3
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;}
> BODY
> {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B
> {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;}
> P {font-family:Tahoma,Arial,sans-serif;background:white;colo
> r:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color
> : #525D76;}--&gt; HTTP Status 401 - Communication with GeoNode failed
> ------------------------------
>
> *type* Status report
>
> *message* Communication with GeoNode failed
>
> *description* This request requires HTTP authentication.
> ------------------------------
> Apache Tomcat/7.0.52 (Ubuntu)', ParseError(ExpatError('mismatched tag:
> line 1, column 1355',),))
>
> Any help is appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2097>.
>


-- 
Simone

**Comment by rodekruis** [comment]
Thank you. In the mean time I swapped to the apt-get geonode testing setup for ubuntu 14.04. This one works ok. Only uploading shapefile zips returns an error that the name of the store is missing. But uploading individual files works.

**Comment by simod** [comment]
Zipped shapefile upload is not supported yet. But we have a pending PR for that so the 2.4 final will also support zipped shapefile upload.
