### ISSUE TITLE
Allow TMS/ZXY to be added as remote services (vs only in MAP_BASELAYERS)

### ISSUE THREAD

**Issue by humanitariandata** [GeoNode/geonode#2098]
Would it be possible to implement XYZ url layers in the overlays? Now the TMS is supported, but it is a different format, which is hardly being provided by other services.

**Comment by capooti** [comment]
You don't like this one?
http://localhost:8080/geoserver/gwc/service/tms/1.0.0/geonode:mylayer/0/0/0.png

**Comment by rodekruis** [comment]
Hi Capooti,

That is only for layers that I have added to geoserver. But what about all public layers available on the net that I could potentially add into a map on geonode as a separate layer?

**Comment by capooti** [comment]
sorry I don't understand this.
Could you describe better which is your problem and which map client are you talking about?
Are you talking about remote services? In such a case you cannot do anything unless you cascade them.

**Comment by rodekruis** [comment]
For instance mapbox and cartodb can provide XYZ map urls. Geonode is an ideal portal to combine these layers with other layers on the geoserver.

It would be great if we can use for instance a cartodb {x}/{y}/{z}.png url to add a layer to a map on geonode.

What do you mean by cascading?

**Comment by capooti** [comment]
If you need more base layers, you can add them to configuration: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L611

Did you check the external sources available in GeoExplorer, by the way? You should be able to customize it to have more sources, I think.

If you want to handle layers from external TMS as GeoNode layers, I am afraid this is not supported.
What you could do is to cache the TMS with MapProxy or similiar, expose them as WMS and then register them as remote services in GeoNode.
Unluckily TMS cannot be registered as remote services right now, @jj0hns0n correct me if I am wrong.

**Comment by jj0hns0n** [comment]
@capooti no, currently TMS are not supported via Remote Services. It is a good addition though.

**Comment by jj0hns0n** [comment]
this will be addressed by djmp.
