### ISSUE TITLE
Setting MaxRecords for PyCSW in settings.py

### ISSUE THREAD

**Issue by davicustodio** [GeoNode/geonode#2099]
It would be nice if we could set the property 'MaxRecords' used in PyCSW (specifically in GetRecords metadata call).

I think we could put something like

# Pycsw settings
PYCSW = {
     # Pycsw configuration
     'CONFIGURATION': {
         'server': {
             'MaxRecords': 10000
         },
         'metadata: main': {

.. in Settings.py and pointing this property in the MaxRecords in other references (for example in https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local.py#L37)

thanks.

**Comment by tomkralidis** [comment]
@davicustodio thanks.  Basically this is set in code, so I'll add the ability to override this in `settings.py`

**Comment by tomkralidis** [comment]
Fixed in master.
