### ISSUE TITLE
Upgrade GeoServer to stable version

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2102]
We need to have GeoServer upgraded to current LTS version (2.5.5) before releasing GeoNode 2.4.
I do not think that current GeoServer version (2.5.1) that comes with GeoNode is currently supported, and it has some unfixed bugs, such as this one:
https://jira.codehaus.org/browse/GEOS-6685

**Comment by gamesbook** [comment]
Any reason we cannot migrate to the 2.6.x series (2.6.2 is a stable release
- http://geoserver.org/release/stable/ )?  Otherwise we are falling further
and further behind the releases.

**Comment by capooti** [comment]
2.5.5 is LTS so anything notable (security risks bug, vulnerabilities etc) should be back-ported to it, therefore I believe it would be a better choice in the long run (so far we had a stable GeoNode release every 2 years or so...)

**Comment by gamesbook** [comment]
I do not understand the practicalities of what is involved in building the
custom GeoServer version, so please point out flaws here... given that the
upcoming 2.4 release of GeoNode is also an LTS version; with appropriate 2
years support for bug fixes and so on, would it possible to have the
interim releases (2.4.1, 2.4.2 etc.) perhaps synced to the appropriately
most recent GeoServer release?  That way users who needed more "cutting
edge features" would have access to them, and the dev team could assess the
ongoing maturity of GeoServer prior to the next LTS release of GeoNode.

**Comment by gamesbook** [comment]
How does this issue relate to $2040 ?

**Comment by capooti** [comment]
Yes, looks like a duplicate of #2040, I will close right now.

Regarding using 2.5.5 or 2.6 series, I have no personal preferences about it, it seemed to me wise to stick to the GeoServer LTS but I would be curious to hear the opinion of other developers.

About building the custom GeoServer version, I think that's all we need to do (at least last time worked for me):

https://github.com/GeoNode/geoserver-geonode-ext/commit/eb38dc9b7ac7d05c464c84712827a3082b3e512d

and then rebuild the plugin.
