### ISSUE TITLE
ProgrammingError: relation "notification_noticetype" does not exist

### ISSUE THREAD

**Issue by donaldbales** [GeoNode/geonode#2103]
I installed Geonode 2.4 beta 22:

I un-commented out:
REGISTRATION_OPEN = True
ACCOUNT_APPROVAL_REQUIRED = True
ACCOUNT_EMAIL_CONFIRMATION_EMAIL = True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED = True

in /etc/geonode/local_settings.py

When I try to add a user I get the following, which basically states I'm missing some tables (specifically notification_noticetype):

Internal Server Error: /account/signup/
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/account/views.py", line 70, in post
    return super(SignupView, self).post(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py", line 171, in post
    return self.form_valid(form)
  File "/usr/lib/python2.7/dist-packages/account/views.py", line 134, in form_valid
    notification.send(staff, "account_approve", {"from_user": self.created_user})
  File "/usr/lib/python2.7/dist-packages/notification/models.py", line 195, in send
    return send_now(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/notification/models.py", line 151, in send_now
    notice_type = NoticeType.objects.get(label=label)
  File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 301, in get
    num = len(clone)
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 77, in __len__
    self._fetch_all()
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 854, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
    for row in compiler.results_iter():
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 710, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 781, in execute_sql
    cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
ProgrammingError: relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
                                                             ^

[remote 146.137.33.66:49624] mod_wsgi (pid=1070): Exception occurred processing WSGI script '/var/www/geonode/wsgi/geonode.wsgi'.
[remote 146.137.33.66:49624] Traceback (most recent call last):
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/wsgi.py", line 206, in __call__
[remote 146.137.33.66:49624]     response = self.get_response(request)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 194, in get_response
[remote 146.137.33.66:49624]     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
[remote 146.137.33.66:49624]     return callback(request, **param_dict)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py", line 99, in _wrapped_view
[remote 146.137.33.66:49624]     response = view_func(request, *args, **kwargs)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/views/defaults.py", line 46, in server_error
[remote 146.137.33.66:49624]     return http.HttpResponseServerError(template.render(Context({})))
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 140, in render
[remote 146.137.33.66:49624]     return self._render(context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 134, in _render
[remote 146.137.33.66:49624]     return self.nodelist.render(context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
[remote 146.137.33.66:49624]     bit = self.render_node(node, context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[remote 146.137.33.66:49624]     return node.render(context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/loader_tags.py", line 53, in render
[remote 146.137.33.66:49624]     result = self.nodelist.render(context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 840, in render
[remote 146.137.33.66:49624]     bit = self.render_node(node, context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/base.py", line 854, in render_node
[remote 146.137.33.66:49624]     return node.render(context)
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/announcements/templatetags/announcements_tags.py", line 24, in render
[remote 146.137.33.66:49624]     request = context["request"]
[remote 146.137.33.66:49624]   File "/usr/lib/python2.7/dist-packages/django/template/context.py", line 56, in __getitem__
[remote 146.137.33.66:49624]     raise KeyError(key)
[remote 146.137.33.66:49624] KeyError: 'request'

So I tried running geonode syncdb.  But that did not add a notification_noticetype table.

What next?

**Comment by capooti** [comment]
do you have django notification in INSTALLED_APPS?
regards

**Comment by JJediny** [comment]
It was commented out in the Ubuntu install.  I un-commented it, ran sudo geonode syncdb, and that created the three tables I needed:

local_admin@foss-geonode01:~$ sudo nano /usr/local/lib/python2.7/dist-packages/geonode/settings.py
local_admin@foss-geonode01:~$ sudo geonode syncdb
Creating tables ...
Creating table notification_noticetype
Creating table notification_noticesetting
Creating table notification_noticequeuebatch
Installing custom SQL ...
Installing indexes ...
Installed 298 object(s) from 1 fixture(s)

**Comment by donaldbales** [comment]
It was commented out in the Ubuntu install. I un-commented it, ran sudo geonode syncdb, and that created the three tables I needed:

local_admin@foss-geonode01:~$ sudo nano /usr/local/lib/python2.7/dist-packages/geonode/settings.py
local_admin@foss-geonode01:~$ sudo geonode syncdb
Creating tables ...
Creating table notification_noticetype
Creating table notification_noticesetting
Creating table notification_noticequeuebatch
Installing custom SQL ...
Installing indexes ...
Installed 298 object(s) from 1 fixture(s)

**Comment by capooti** [comment]
@donaldbales it is commented by purpose, as notification app is not installed in default geonode
