### ISSUE TITLE
2.4b22 instaltion issue 

### ISSUE THREAD

**Issue by ian-mcleod** [GeoNode/geonode#2104]
I have installed 2.4b22 several times without issue - however the last install was a doozy...

I am installing from the ppa:geonode/testing repository onto a ubuntu 14.04 system 
during the last install an invalid postgresql password was created for the geonode user

the password   'DmY2ûë8a'    (notice the accented ue )

this is  not a UTF-8(128) compliant, so default python encode and decode functions were having a bad time. However It was easily fixed by blowing away the VM and re-instancing and reinstalling.
I may have been able to fix it by replacing every occurrence of the string. But I am not sure where it is used... 

I know in is used in : 
/etc/geononde/local_settings.py
in the postgresql database - geonode user definition      

but whereelse

**Comment by simod** [comment]
@ian-mcleod this was happening to me in the past using Vagrant on OSX but is not happening anymore. Anyway you have to change the password in the local_settings and then to the geonode user in postgres. 
You can use:
$ sudo su postgres
$ psql -c "alter role geonode with password 'yourpassword';"
$ exit

Hope this helps

**Comment by ramavanan** [comment]
I have installed 2.4. my superuser password doesnot match postgres password. how to find postgres password and database

**Comment by ian-mcleod** [comment]
ok - really important -  there are 3 diffeerent authentication processes involved
1. unix / linux system authentication
2. popstgreql (PG)  database user authentication
3. geonode superuser authentication

when you install geonode it creates a random password for the PG superuser - which is lost during the install...
but it also creates a geonode user PG account and password that PG password is stored in /etc/geonode/local_settings.py
you can merrily change any PG  password, but the geonode PG password must match the password stored in local_settings.py

I don't believe it is possible to discover the value of any PG password, and as I said earlier the PG superuser password is lost during the install. However  it is trivial to to change the PG superuser account password to something you can use. Changing it will not impact geonode  in any way.

1. logon to the linux system
2. su to root (sudo -i)
3. su to postgres (su - postgres )
4. start psql as the postgres user  (psql )
5. change the postgres user password ( ALTER USER postgres WITH PASSWORD '<new_password>'; )
6. exit pgsql ;  exit su postgres ;  exit sudo

you can then use PG and login to the superuser account with the new password

hope this helps

Ian



________________________________

**Comment by ian-mcleod** [comment]
Thanks  - that does work …

It only happens on the VM’s hosted centrally by my organisation …
I have installed it on numerous other VM’s  with no issue
So I presume it’s an issue with the “sanitized”  repositories / distro that we use

Do you (or anyone else) have any idea as to what package / library is used to generate these keys

Thanks
Ian

**Comment by simod** [comment]
It's generated by this file https://github.com/GeoNode/geonode/blob/master/package/install.sh#L132 which is run by apt-get install.

Ciao
