### ISSUE TITLE
Geonode Account Registration Error

### ISSUE THREAD

**Issue by achorivai** [GeoNode/geonode#2114]
ProgrammingError at /account/signup/

**Comment by achorivai** [comment]
please help, many errors occur in geonode 2.4b22 one of which is below


--------------------------------------------------------------------------
ProgrammingError at /account/signup/

relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
                                                             ^

Request Method: 	POST
Request URL: 	http://servername/account/signup/
Django Version: 	1.6.1
Exception Type: 	ProgrammingError
Exception Value: 	

relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
                                                             ^

Exception Location: 	/usr/lib/python2.7/dist-packages/django/db/backends/util.py in execute, line 53
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www']




Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/account/views.py" in post
  70.         return super(SignupView, self).post(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py" in post
  171.             return self.form_valid(form)
File "/usr/lib/python2.7/dist-packages/account/views.py" in form_valid
  134.             notification.send(staff, "account_approve", {"from_user": self.created_user})
File "/usr/lib/python2.7/dist-packages/notification/models.py" in send
  195.             return send_now(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/notification/models.py" in send_now
  151.     notice_type = NoticeType.objects.get(label=label)
File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py" in get
  151.         return self.get_queryset().get(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in get
  301.         num = len(clone)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in __len__
  77.         self._fetch_all()
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
  854.             self._result_cache = list(self.iterator())
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  220.         for row in compiler.results_iter():
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in results_iter
  710.         for rows in self.execute_sql(MULTI):
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  781.         cursor.execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  69.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/utils.py" in __exit__
  99.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /account/signup/
Exception Value: relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...

**Comment by simod** [comment]
Hi looks that you enabled the notifications. So you have to run the syncdb
to enable the new tables.

Ciao

Il martedì 7 aprile 2015, achorivai <notifications@github.com> ha scritto:

> please help, many errors occur in geonode 2.4b22 one of which is below
> ------------------------------
>
> ProgrammingError at /account/signup/
>
> relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
> ^
>
> Request Method: POST
> Request URL: http://servername/account/signup/
> Django Version: 1.6.1
> Exception Type: ProgrammingError
> Exception Value:
>
> relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
> ^
>
> Exception Location:
> /usr/lib/python2.7/dist-packages/django/db/backends/util.py in execute,
> line 53
> Python Executable: /usr/bin/python
> Python Version: 2.7.6
> Python Path:
>
> ['/usr/lib/python2.7',
> '/usr/lib/python2.7/plat-x86_64-linux-gnu',
> '/usr/lib/python2.7/lib-tk',
> '/usr/lib/python2.7/lib-old',
> '/usr/lib/python2.7/lib-dynload',
> '/usr/local/lib/python2.7/dist-packages',
> '/usr/lib/python2.7/dist-packages',
> '/usr/lib/python2.7/dist-packages/PILcompat',
> '/usr/lib/pymodules/python2.7',
> '/var/www']
>
> Traceback:
> File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in
> get_response
>
>    1. response = wrapped_callback(request, *callback_args, **callback_kwargs)
>    File "/usr/lib/python2.7/dist-packages/django/views/generic/base.py" in view
>    2. return self.dispatch(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/views/generic/base.py" in dispatch
>    3. return handler(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/account/views.py" in post
>    4. return super(SignupView, self).post(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/views/generic/edit.py" in post
>    5. return self.form_valid(form) File
>    "/usr/lib/python2.7/dist-packages/account/views.py" in form_valid
>    6. notification.send(staff, "account_approve", {"from_user":
>    self.created_user}) File
>    "/usr/lib/python2.7/dist-packages/notification/models.py" in send
>    7. return send_now(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/notification/models.py" in send_now
>    8. notice_type = NoticeType.objects.get(label=label) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/manager.py" in get
>    9. return self.get_queryset().get(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in get
>    10. num = len(clone) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in *len*
>    11. self._fetch_all() File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
>    12. self._result_cache = list(self.iterator()) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
>    13. for row in compiler.results_iter(): File
>    "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in
>    results_iter
>    14. for rows in self.execute_sql(MULTI): File
>    "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in
>    execute_sql
>    15. cursor.execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    16. return super(CursorDebugWrapper, self).execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    17. return self.cursor.execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/utils.py" in *exit*
>    18. six.reraise(dj_exc_type, dj_exc_value, traceback) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    19. return self.cursor.execute(sql, params)
>
> Exception Type: ProgrammingError at /account/signup/
> Exception Value: relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2114#issuecomment-90686667>.
>


-- 
Simone

**Comment by achorivai** [comment]
i already running syncdb but still got same error..
geonode syncdb

Creating tables ...
Installing custom SQL ...
Installing indexes ...
Installed 298 object(s) from 1 fixture(s)

and then if we want edit/delete people profile in django/admin we got similiar error too

ProgrammingError at /admin/people/profile/2/
relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
                                                             ^
Request Method:	POST
Request URL:	http://182.253.237.215/admin/people/profile/2/
Django Version:	1.6.1
Exception Type:	ProgrammingError
Exception Value:	
relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
                                                             ^
Exception Location:	/usr/lib/python2.7/dist-packages/django/db/backends/util.py in execute, line 53
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www']
Server time:	Rab, 8 Apr 2015 17:38:40 +0700.


Traceback:
File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in wrapper
  461.                 return self.admin_site.admin_view(view)(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapped_view
  99.                     response = view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/views/decorators/cache.py" in _wrapped_view_func
  52.         response = view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/contrib/admin/sites.py" in inner
  198.             return view(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapped_view
  99.                     response = view_func(request, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in bound_func
  25.                 return func(self, *args2, **kwargs2)
File "/usr/lib/python2.7/dist-packages/django/db/transaction.py" in inner
  339.                 return func(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in change_view
  1259.                 self.save_model(request, new_object, form, True)
File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in save_model
  889.         obj.save()
File "/usr/lib/python2.7/dist-packages/django/db/models/base.py" in save
  545.                        force_update=force_update, update_fields=update_fields)
File "/usr/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
  569.                                   update_fields=update_fields)
File "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
  185.             response = receiver(signal=self, sender=sender, **named)
File "/usr/local/lib/python2.7/dist-packages/geonode/people/models.py" in profile_pre_save
  158.         notification.send([instance, ], "account_active")
File "/usr/lib/python2.7/dist-packages/notification/models.py" in send
  195.             return send_now(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/notification/models.py" in send_now
  151.     notice_type = NoticeType.objects.get(label=label)
File "/usr/lib/python2.7/dist-packages/django/db/models/manager.py" in get
  151.         return self.get_queryset().get(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in get
  301.         num = len(clone)
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in __len__
  77.         self._fetch_all()
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
  854.             self._result_cache = list(self.iterator())
File "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
  220.         for row in compiler.results_iter():
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in results_iter
  710.         for rows in self.execute_sql(MULTI):
File "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in execute_sql
  781.         cursor.execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  69.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)
File "/usr/lib/python2.7/dist-packages/django/db/utils.py" in __exit__
  99.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
  53.                 return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /admin/people/profile/2/
Exception Value: relation "notification_noticetype" does not exist
LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...


please help me for detail solution (i'm beginner in geonode  :(      )

**Comment by simod** [comment]
Ok, then make sure that you have uncommented 'notification' in
INSTALLED_APPS in settings. The re run syncdb.
https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L307

p.s. for support please use the users mailing list at
geonode-users@lists.osgeo.org

2015-04-08 12:46 GMT+02:00 ANRT <notifications@github.com>:

> i already running syncdb but still got same error..
> geonode syncdb
>
> Creating tables ...
> Installing custom SQL ...
> Installing indexes ...
> Installed 298 object(s) from 1 fixture(s)
>
> and then if we want edit/delete people profile in django/admin we got
> similiar error too
>
> ProgrammingError at /admin/people/profile/2/
> relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
> ^
> Request Method: POST
> Request URL: http://182.253.237.215/admin/people/profile/2/
> Django Version: 1.6.1
> Exception Type: ProgrammingError
> Exception Value:
>
> relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
> ^
> Exception Location:
> /usr/lib/python2.7/dist-packages/django/db/backends/util.py in execute,
> line 53
> Python Executable: /usr/bin/python
> Python Version: 2.7.6
> Python Path:
>
> ['/usr/lib/python2.7',
> '/usr/lib/python2.7/plat-x86_64-linux-gnu',
> '/usr/lib/python2.7/lib-tk',
> '/usr/lib/python2.7/lib-old',
> '/usr/lib/python2.7/lib-dynload',
> '/usr/local/lib/python2.7/dist-packages',
> '/usr/lib/python2.7/dist-packages',
> '/usr/lib/python2.7/dist-packages/PILcompat',
> '/usr/lib/pymodules/python2.7',
> '/var/www']
> Server time: Rab, 8 Apr 2015 17:38:40 +0700.
>
> Traceback:
> File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py" in
> get_response
>
>    1. response = wrapped_callback(request, *callback_args, **callback_kwargs)
>    File "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
>    wrapper
>    2. return self.admin_site.admin_view(view)(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in
>    _wrapped_view
>    3. response = view_func(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/views/decorators/cache.py" in
>    _wrapped_view_func
>    4. response = view_func(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/contrib/admin/sites.py" in inner
>    5. return view(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in _wrapper
>    6. return bound_func(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in
>    _wrapped_view
>    7. response = view_func(request, *args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/utils/decorators.py" in bound_func
>    8. return func(self, *args2, **kwargs2) File
>    "/usr/lib/python2.7/dist-packages/django/db/transaction.py" in inner
>    9. return func(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
>    change_view
>    10. self.save_model(request, new_object, form, True) File
>    "/usr/lib/python2.7/dist-packages/django/contrib/admin/options.py" in
>    save_model
>    11. obj.save() File
>    "/usr/lib/python2.7/dist-packages/django/db/models/base.py" in save
>    12. force_update=force_update, update_fields=update_fields) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/base.py" in save_base
>    13. update_fields=update_fields) File
>    "/usr/lib/python2.7/dist-packages/django/dispatch/dispatcher.py" in send
>    14. response = receiver(signal=self, sender=sender, **named) File
>    "/usr/local/lib/python2.7/dist-packages/geonode/people/models.py" in
>    profile_pre_save
>    15. notification.send([instance, ], "account_active") File
>    "/usr/lib/python2.7/dist-packages/notification/models.py" in send
>    16. return send_now(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/notification/models.py" in send_now
>    17. notice_type = NoticeType.objects.get(label=label) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/manager.py" in get
>    18. return self.get_queryset().get(*args, **kwargs) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in get
>    19. num = len(clone) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in *len*
>    20. self._fetch_all() File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in _fetch_all
>    21. self._result_cache = list(self.iterator()) File
>    "/usr/lib/python2.7/dist-packages/django/db/models/query.py" in iterator
>    22. for row in compiler.results_iter(): File
>    "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in
>    results_iter
>    23. for rows in self.execute_sql(MULTI): File
>    "/usr/lib/python2.7/dist-packages/django/db/models/sql/compiler.py" in
>    execute_sql
>    24. cursor.execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    25. return super(CursorDebugWrapper, self).execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    26. return self.cursor.execute(sql, params) File
>    "/usr/lib/python2.7/dist-packages/django/db/utils.py" in *exit*
>    27. six.reraise(dj_exc_type, dj_exc_value, traceback) File
>    "/usr/lib/python2.7/dist-packages/django/db/backends/util.py" in execute
>    28. return self.cursor.execute(sql, params)
>
> Exception Type: ProgrammingError at /admin/people/profile/2/
> Exception Value: relation "notification_noticetype" does not exist
> LINE 1: ...iption", "notification_noticetype"."default" FROM "notificat...
>
> please help me for detail solution (i'm beginner in geonode :( )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2114#issuecomment-90877553>.
>



-- 
Simone
