### ISSUE TITLE
Performance issues with geonode.security.views.resource_permissions

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2122]
I am testing GeoNode 2.4 with a large number of resource base objects (about 2000).
When accessing to the detail page of one resource, for example a layer, the view in the subject [1]  is extremely slow.
After some debugging it looks like this line [2] is taking a long time to execute (about 1 minute).

Same behavior from python shell:

get_users_with_perms(layer, attach_perms=True, with_superusers=True)
time: about 45 sec

It looks like django-guardian try to run this query, that keeps postgres working at 100% for all that time:

```sql
SELECT DISTINCT "people_profile"."id", "people_profile"."password", "people_profile"."last_login", "people_profile"."is_superuser", "people_profile"."username", "people_profile"."first_name", "people_profile"."last_name", "people_profile"."email", "people_profile"."is_staff", "people_profile"."is_active", "people_profile"."date_joined", "people_profile"."organization", "people_profile"."profile", "people_profile"."position", "people_profile"."voice", "people_profile"."fax", "people_profile"."delivery", "people_profile"."city", "people_profile"."area", "people_profile"."zipcode", "people_profile"."country" FROM "people_profile" LEFT OUTER JOIN "guardian_userobjectpermission" ON ( "people_profile"."id" = "guardian_userobjectpermission"."user_id" ) LEFT OUTER JOIN "people_profile_groups" ON ( "people_profile"."id" = "people_profile_groups"."profile_id" ) LEFT OUTER JOIN "auth_group" ON ( "people_profile_groups"."group_id" = "auth_group"."id" ) LEFT OUTER JOIN "guardian_groupobjectpermission" ON ( "auth_group"."id" = "guardian_groupobjectpermission"."group_id" ) WHERE (("guardian_userobjectpermission"."object_pk" = '4453'  AND "guardian_userobjectpermission"."content_type_id" = 38 ) OR ("guardian_groupobjectpermission"."object_pk" = '4453'  AND "guardian_groupobjectpermission"."content_type_id" = 38 ))
```
[1] https://github.com/GeoNode/geonode/blob/master/geonode/security/views.py#L51
[2] https://github.com/GeoNode/geonode/blob/master/geonode/security/models.py#L56

**Comment by simod** [comment]
I can confirm that it slows down but not so much, 3.6 seconds with 1400 + resources. Better to investigate though.

**Comment by capooti** [comment]
update: we are now almost done with a basic script (to be improved) [1] to generate an extended GeoNode database that we can use to stress GeoNode and see if there is some performance that needs to be improved.

So far @simod already addressed the problem related to the permission query taking a long long time.
We still need to figure out how to tackle the problems related to the slow dehydrated count needed by the Region and Tag counts.
We will keep you posted here.

[1] https://github.com/capooti/geonode/blob/68efffb0cc38a257ee4ebd3a64beb56f47077406/scripts/misc/create_full_geonode_db.py

**Comment by simod** [comment]
Thanks for the script @capooti. Tomorrow will take a look at the counts :)

Il giovedì 16 aprile 2015, Paolo Corti <notifications@github.com> ha
scritto:

> update: we are now almost done with a basic script (to be improved) [1] to
> generate an extended GeoNode database that we can use to stress GeoNode and
> see if there is some performance that needs to be improved.
>
> So far @simod <https://github.com/simod> already addressed the problem
> related to the permission query taking a long long time.
> We still need to figure out how to tackle the problems related to the slow
> dehydrated count needed by the Region and Tag counts.
> We will keep you posted here.
>
> [1]
> https://github.com/capooti/geonode/blob/68efffb0cc38a257ee4ebd3a64beb56f47077406/scripts/misc/create_full_geonode_db.py
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2122#issuecomment-93759073>.
>


-- 
Simone

**Comment by capooti** [comment]
just for the record, a resource detail page with your optimization now requires 47 vs 198 queries.
It is much faster (under 1 sec), but it would be nice if we find a way to lower the needed queries.

**Comment by simod** [comment]
Yeah, I think that we should also take a look at how the templates use the
objects.

2015-04-17 11:38 GMT+02:00 Paolo Corti <notifications@github.com>:

> just for the record, a resource detail page with your optimization now
> requires 47 vs 198 queries.
> It is much faster (under 1 sec), but it would be nice if we find a way to
> lower the needed queries.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2122#issuecomment-93953098>.
>



-- 
Simone

**Comment by pjdufour** [comment]
@simod, close issue?

**Comment by simod** [comment]
yes
