### ISSUE TITLE
Manually setting a layer thumbnail creates a basemap image only

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#2124]
From a layer detail page, click 'Edit Layer', then 'Set' thumbnail.  The resulting thumbnail only shows the basemap, not the layer.

**Comment by simod** [comment]
@mbertrand does this happens in production? For me in dev mode seems to be working.

**Comment by mbertrand** [comment]
Works for me now too after clearing out cookies and cache, sorry for the false alarm.
