### ISSUE TITLE
Associate information to shapefiles/raster uploaded

### ISSUE THREAD

**Issue by MelvinDRM** [GeoNode/geonode#2126]
Greetings,

I'm trying to associate specific information to the files I upload (be that vector or raster). I'm supposed to implement a database with a whole of information (text and numbers related to statistics and NGO standards), but I have no idea where or how to begin to customize my project: create models, create the forms, query the data (especially from the map view itself), etc.

I'm assuming here that each file I upload it's a new layer, and I understand that when I upload a file I can add a predetermined info called metadata, and also each file has attributes (which I guess they come from the file itself), but I need more.

Can anyone help me on this matter? Thanks in advance,

MR

**Comment by simod** [comment]
@MelvinDRM could you please move this thread the users mailing list? as we keep the ticketing system just for geonode issues. http://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users.
For your question, did you take a look at the "document" app of geonode? It allow you to upload any other non spatial file and link it to an existing layer or map.

You are correct, each shapefile is a layer and some metadata are generated from the shapefile itself. The shapefile is loaded to a postgres spatial database. 
In the mailing list you could also specify a little more your requirements, like what would you expect to get from the system, as there may be more ways to achieve what you need.

Regards

**Comment by MelvinDRM** [comment]
Thanks, will do!
