### ISSUE TITLE
Performance issues when uploading layers to GeoNode

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2130]
Using this script [1], it looks like GeoServer is initially very fast but then the upload time quickly increases with the layers number (time is in seconds, the uploaded shapefile is ~5k):

Layer 0 generated in: 1.83858203888
Layer 1 generated in: 1.85110998154
Layer 2 generated in: 2.00699400902
...
Layer 48 generated in: 4.82827591896
Layer 49 generated in: 4.83818912506
Layer 50 generated in: 5.1511900425
...
Layer 71 generated in: 8.78467202187
Layer 72 generated in: 9.61577486992
Layer 73 generated in: 10.5833621025
...
Layer 293 generated in: 25.4465839863
Layer 294 generated in: 27.8491809368
Layer 295 generated in: 36.5090360641
...

[1] https://github.com/capooti/geonode/blob/script-to-test-performance/scripts/misc/create_full_geonode_db.py

**Comment by pjdufour** [comment]
@simod, close issue?
