### ISSUE TITLE
Restructuring ResourceBase API - to list Downloads 

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2131]
Simply put I think the listings/pagination view of geonode resources (i.e. Layers, Maps, Documents) has regressed from Geonode 2.0 to Geonode 2.4. I would like to propose some changes to the data being bound to an entry so users can more easily access the data services, locate/navigate to the original source to verify the data is up to date, and distinguish what layer type (i.e. Vector, Raster, Remote)
## Current List Entry

![image](https://cloud.githubusercontent.com/assets/6350035/7232329/fd21e896-e748-11e4-811f-e2f27eca35c0.png)
## Proposed (Draft for Discussion Purposes Only - Crude Mockup)

![geonodelistmockup](https://cloud.githubusercontent.com/assets/6350035/7232889/14a44a4c-e74c-11e4-8696-581447bbe8f7.png)

More Description to Come... as of 4/20/15

**Comment by simod** [comment]
@JJediny should they list the number of times the Resource has been downloaded?

**Comment by JJediny** [comment]
mistakenly save this issue before providing a description... Then started drafting to a half well done ticket before the power went out... Will flesh this out sometime today to get at the issue

**Comment by tomkralidis** [comment]
@JJediny first pass can be found here ([branch](https://github.com/tomkralidis/geonode/tree/issue-2131) --  [diff](https://github.com/GeoNode/geonode/compare/master...tomkralidis:issue-2131)) for review / comment.

Given the AngularJS pattern of the page, the implementation here required some updates that should investigate w.r.t. scaleability (bigger API response, deeper queries to generate same), although given pagination this may or may not make a huge difference.  cc'ing @simod and @ingenieroariel for review/comment before merging.

**Comment by simod** [comment]
@tomkralidis, as you say, here
https://github.com/GeoNode/geonode/compare/master...tomkralidis:issue-2131#diff-01d93696899f392996ab0326a506a0e1R465
is
what we can't do in resourcebase_api because is exactly what we removed in
favor of speed.

Not sure if we can try with a kind of single bulk annotation there.

Or create some links on the client side like
"{{geoserver_public_url}}wfs?format_options=charset%3AUTF-8&typename={{layer.typename
}}&outputFormat=SHAPE-ZIP&version=1.0.0&service=WFS&request=GetFeature"

2015-11-18 23:06 GMT+01:00 Tom Kralidis <notifications@github.com>:

> @JJediny <https://github.com/JJediny> first pass can be found here (branch
> <https://github.com/tomkralidis/geonode/tree/issue-2131> -- diff
> <https://github.com/GeoNode/geonode/compare/master...tomkralidis:issue-2131>)
> for review / comment.
>
> Given the AngularJS pattern of the page, the implementation here required
> some updates that should investigate w.r.t. scaleability (bigger API
> response, deeper queries to generate same), although given pagination this
> may or may not make a huge difference. cc'ing @simod
> <https://github.com/simod> and @ingenieroariel
> <https://github.com/ingenieroariel> for review/comment before merging.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2131#issuecomment-157879721>.
>



-- 
Simone

**Comment by tomkralidis** [comment]
@simod thanks for the info.  What do you mean by 'single bulk annotation'?
I started working towards creating links on the client side, however given the duplication of logic, I think it is better to continue to think this through with options that are driven from the API.

**Comment by simod** [comment]
@tomkralidis I mean if would be possible to do one single query on the entire filtered queryset to create all the links at once.
