### ISSUE TITLE
Error loading file

### ISSUE THREAD

**Issue by lucageo** [GeoNode/geonode#2132]
After installing GeoNode using "git clone https://github.com/GeoNode/geonode.git"
I got the following error uploading  a raster or a shape file:
in method 'Driver_Open', argument 2 of type 'char const *'

Any suggestions?

Thank you very much,
Cheers
Luca

**Comment by simod** [comment]
Hi, seems like system library error like PIL or other. Do you have a full stack trace?
Also do you mind using the users mailing list to ask for support?
geonode-users@lists.osgeo.org, thanks

**Comment by ischneider** [comment]
Based on the method name, this appears to be an OGR/GDAL issue, FYI.

**Comment by lucageo** [comment]
Thank you both,
the issue is fixed just updating python-gdal.
Cheers,
Luca
