### ISSUE TITLE
KeyError on Layer Info page due to missing permissions

### ISSUE THREAD

**Issue by mbertrand** [GeoNode/geonode#2142]
After fetching the latest code I get a KeyError exception on existing layer info pages:

```
File "/Users/mbertrand/.virtualenvs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/Users/mbertrand/dev/geonode/geonode/layers/views.py", line 272, in layer_detail
    "permissions_json": _perms_info_json(layer),
File "/Users/mbertrand/dev/geonode/geonode/security/views.py", line 42, in _perms_info_json
    info = _perms_info(obj)
File "/Users/mbertrand/dev/geonode/geonode/security/views.py", line 36, in _perms_info
    info = obj.get_all_level_info()
File "/Users/mbertrand/dev/geonode/geonode/security/models.py", line 106, in get_all_level_info
    self.layer),
File "/Users/mbertrand/dev/geonode/geonode/security/models.py", line 67, in get_users_with_perms
    users[item['user_id']].append(permissions[item['permission_id']])
```

Due to the following permissions not being in the ADMIN_PERMISSIONS or LAYER_PERMISSIONS lists in geonode/security/models.py:  add_resourcebase, add_layer, edit_layer, delete_layer

The following changes fix this issue: https://github.com/GeoNode/geonode/compare/GeoNode:master...mbertrand:permissionfix1?expand=1

@simod can you take a look and let me know if this is the right approach to resolving the problem? If so I will submit a PR.

**Comment by simod** [comment]
@mbertrand those permissions are the django default and are not actually of interest of geonode because we check the others. It's not very clear to me why the user model is returning those permissions in your version. Can you jump in IRC?

**Comment by simod** [comment]
@mbertrand btw I tried with an old branch but don't get this error.

**Comment by mbertrand** [comment]
Hi @simod, I figured out that the extra permissions were being created for raster layers but not vector layers on an older branch (commit #e09ed55f5b24b8439196097a3cc6a10812659109 from early April).

**Comment by simod** [comment]
oh. Ok. Thanks for the PR!

**Comment by simod** [comment]
Can we close this?

**Comment by bnorberg** [comment]
I have an instance of Geonode 2.4 25b running on Ubuntu 14.04 installed using Geonode testing ppa. I am seeing this same permissions key error on vector layers. Manually changing the manage.py file with the changes in the merge request fixed the problem. Will these changes to manage.py be incorporated into the the 2.425b version of geonode packaged in the testing ppa? Thank you.

**Comment by simod** [comment]
@bnorberg yes they will in the next beta or RC1 as soon as it's ready.
btw we now have a nightly build with the latest updates on ppa:geonode/snapshots. If you use that you'll get the most updater geonode.

**Comment by bnorberg** [comment]
@simod thanks!
