### ISSUE TITLE
Layer styles not updatable with update 2.4b25

### ISSUE THREAD

**Issue by JamesLeonDufour** [GeoNode/geonode#2146]
I cannot update of change layers styles since the update to 2.4b25 ? Any tips ?

**Comment by simod** [comment]
@JamesLeonDufour can you describe more the error you get? I cannot replicate the error, I can upload a layer, change its style, duplicate the style and switch among them.

PS, mind using the mailing list geonode-users@lists.osgeo.org before coming to a ticket?

**Comment by acwalter** [comment]
not sure if this is the same issue. Open a layer, edit layer, edit style. In the popup, select rule and edit. Change color and/or opacity. Save and close. Repeat process, the rule has reverted back to its original style.

**Comment by vdeparday** [comment]
This sounds like a GeoWebCache issue. On some occurrences, the cache of GWC
doesn't clear properly so the styles doesn't get refreshed. It is one the
latest blocking issue before the release of 2.4. One solution is to go in
GeoServer admin, then select the GWC menu on the left. Find the layer you
are working with and truncate the cache. If that still doesn't work, you
can go directly on the server and delete the folder with the cache so it
will force GWC to regenerate it with the new style.

**Comment by capooti** [comment]
Let me add 2 more ways to get the same result (both of those will then hit
WMS instead than GWC):

1. in the style editor, go in "Display" and then uncheck the "use cached
version" option.
2. in GeoServer you can disable the cache just for that layer in "Layer
properties > Tile Caching"

On Thu, May 7, 2015 at 1:21 AM, Vivien Deparday <notifications@github.com>
wrote:

> This sounds like a GeoWebCache issue. On some occurrences, the cache of GWC
> doesn't clear properly so the styles doesn't get refreshed. It is one the
> latest blocking issue before the release of 2.4. One solution is to go in
> GeoServer admin, then select the GWC menu on the left. Find the layer you
> are working with and truncate the cache. If that still doesn't work, you
> can go directly on the server and delete the folder with the cache so it
> will force GWC to regenerate it with the new style.
>
> On Wed, May 6, 2015 at 6:33 PM, Andrew Walter <notifications@github.com>
> wrote:
>
>
> > not sure if this is the same issue. Open a layer, edit layer, edit style.
> > In the popup, select rule and edit. Change color and/or opacity. Save and
> > close. Repeat process, the rule has reverted back to its original style.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2146#issuecomment-99630887>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2146#issuecomment-99642062>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by rajanski** [comment]
Same problem here, some styles for some layers can only be permanently edited via Geoserver Admin UI SLD Editor.
Also the abovementioned solutions by vdeparday and capooti don't neccessarily work always.

**Comment by sbsimo** [comment]
Cannot replicate the issue on demo.geonode.org (version 2.4c2). In my opinion it's not applicable anymore.
