### ISSUE TITLE
List of suggested resources overlaps search box

### ISSUE THREAD

**Issue by alesarrett** [GeoNode/geonode#2152]
When a user types some letters in the search box, the suggested resources appear on top of the search box itself, making hard to see the text typed.
Could it be something related to the django-autocomplete-light library?
The screenshot below shows an example of that, typing the letter "a" in demo.geonode.org:
![selection_011](https://cloud.githubusercontent.com/assets/1692316/7586593/be70087c-f8ae-11e4-8922-74315dfe92f0.png)

**Comment by pjdufour** [comment]
@JJediny, was this fixed?  Close this issue?

**Comment by simod** [comment]
fixed by https://github.com/GeoNode/geonode/commit/896f62a5b0e9af921c05a952f52b5c6a2986434c
