### ISSUE TITLE
Impossible to copy values from attribute table / feature info tooltip in map view

### ISSUE THREAD

**Issue by rajanski** [GeoNode/geonode#2153]
It is not possible to simply copy a field value from an attribute table / info tooltip. 
Tried Firefox and Chrome on Ubuntu, no avail.

**Comment by pjdufour** [comment]
This issue references the popups on layer detail pages, right?

**Comment by simod** [comment]
yes detail and map composer when inspecting a feature.

**Comment by jj0hns0n** [comment]
@bartvde any idea on this one?

**Comment by bartvde** [comment]
I thought last time I looked it seemed this was a limitation in Ext JS, but I can't find that thread now

**Comment by rajanski** [comment]
See here https://github.com/boundlessgeo/suite/issues/943

Am 23.08.2016 18:46 schrieb "Bart van den Eijnden" <notifications@github.com
