### ISSUE TITLE
Docker installation provides no geonode manager script

### ISSUE THREAD

**Issue by MakersF** [GeoNode/geonode#2154]
Hello,
I have installed geonode in a container using the docker file provided in this repo.
The setup was successful, and I can run the demo.

The problem is that I need to run some scripts ( `geonode updatelayers` ), but i get 'geonode: command not found`.

Does a solution to this exist?

**Comment by simod** [comment]
On docker geonode is installed in dev mode, you should use python manage.py updatelayers.

ps. do you mind using the users mailing list instead geonode-users@lists.osgeo.org.
