### ISSUE TITLE
Email addresses not added for new users added through admin

### ISSUE THREAD

**Issue by matthewhanson** [GeoNode/geonode#2166]
When adding a new user through the admin (Users model), the email address is not added to the Email Addresses table.     Consequently, if you forget your password it cannot find your email address.

**Comment by simod** [comment]
We have this piece of code to handle that https://github.com/GeoNode/geonode/blob/master/geonode/people/models.py#L146, but I'm wondering why is not working anymore. Need to investigate. Thanks Matt
