### ISSUE TITLE
CKAN Harvest Breaks

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2170]
CKAN harvest from GeoNode doesn't work when ordering by apiso:Modified, such as the command below.  Seems to be an issue with https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local_mappings.py#L39.  It returns a `Cannot resolve keyword 'last_modified' into field. ` error.

Do we even have a "last_modified" field in the base object?  Should we just change the pyscsw:Modified value to "date" like the line above?  Would the fix the issue?  I'm happy to mess around with some code, but I'm out of my depth.

```
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<csw:GetRecords xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" outputSchema="http://www.isotc211.org/2005/gmd" outputFormat="application/xml" version="2.0.2" service="CSW" resultType="results" maxRecords="10" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd">
  <csw:Query typeNames="csw:Record">
    <csw:ElementSetName>brief</csw:ElementSetName>
    <ogc:SortBy>
      <ogc:SortProperty>
        <ogc:PropertyName>apiso:Modified</ogc:PropertyName>
        <ogc:SortOrder>ASC</ogc:SortOrder>
      </ogc:SortProperty>
    </ogc:SortBy>
  </csw:Query>
</csw:GetRecords>
```

@JJediny, @tomkralidis

**Comment by tomkralidis** [comment]
fixed in master: https://github.com/GeoNode/geonode/commit/7f0be62c4e623759b80b9de8e863cd8fc007e3e2

**Comment by pjdufour** [comment]
Am I reading the pycsw_local_mappings.py file correctly?  Should `pycsw:CreationDate` (link below) change to `date`, too?  Is everything on the right side supposed to be a field in the ResourceBase class?

https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local_mappings.py#L45

**Comment by tomkralidis** [comment]
cc @capooti 

@pjdufour good catch.  Yes, everything on the right should either be a field or `@property`, the latter of which better suited for returnables as opposed to queryables.  The way pycsw works in GeoNode is that a flat mapping is passed between them.

The problem here is that GeoNode defines these in a more normalized fashion and pycsw defines them more strongly typed to make for easier queries to satisfy CSW queryables (i.e. `where date_revision > 2000` is simpler than `where date > 2000 and date_type='revision'`.  In most cases we are able to cover this with model functions decorated with `@property`.

Having said this, it's probably benign at this point to use GeoNode's `date` for date fields in the pycsw mappings.  If folks agree I'll update the codebase.

**Comment by capooti** [comment]
@tomkralidis do I understand correctly that you would need to change ResourceBase.date field from DateTimeField to DateField?
If so, I think we will need to discuss with others as at this point we cannot do schema changes the official release.

**Comment by tomkralidis** [comment]
@capooti more like removing date and date type and replacing with date_publication, date_revision, and date_creation. This would be a more dramatic schema change however.

We can leave as is and I can hardwire date as the mapping into all the pycsw mappings if this is okay with folks.

**Comment by simod** [comment]
Cool, we should ticket this change for 2.5.

2015-05-28 13:53 GMT+02:00 Tom Kralidis <notifications@github.com>:

> @capooti more like removing date and date type and replacing with
> date_publication, date_revision, and date_creation. This would be a more
> dramatic schema change however.
>
> We can leave as is and I can hardwire date as the mapping into all the
> pycsw mappings if this is okay with folks.
>
> Sent from my iPhone
>
> > On May 28, 2015, at 03:43, Paolo Corti <notifications@github.com> wrote:
> >
> > @tomkralidis do I understand correctly that you would need to change
> ResourceBase.date field from DateTimeField to DateField?
> > If so, I think we will need to discuss with others as at this point we
> cannot do schema changes the official release.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2170#issuecomment-106288904>.
>



-- 
Simone

**Comment by capooti** [comment]
excellent, +1 to both things (hardwire now, and dramatic schema change targeted to 2.5)

**Comment by tomkralidis** [comment]
Fixed in master.  Pushing to 2.5 for schema change.

**Comment by ingenieroariel** [comment]
+1

**Comment by jj0hns0n** [comment]
@tomkralidis closing as I think its been implemented. Please reopen if not
