### ISSUE TITLE
Mobile Design / Extent Search

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2171]
The extent search filter should be hidden by default on search pages for mobile browsers, since it requires a lot of scrolling to get past.

**Comment by ccosse** [comment]
On Thu, May 28, 2015 at 7:31 AM, Patrick Dufour <notifications@github.com>
wrote:

> The extent search filter should be hidden by default on search pages for
> mobile browsers, since it requires a lot of scrolling to get past.
>

A map-lock feature that protects the user from accidentally zooming would
be nice ... would that be in the realm of GeoServer or OpenLayers?
