### ISSUE TITLE
CSW / Missing Links for Documents

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2175]
The CSW XML for documents only includes links to the document detail page (`http://example.com/documents/3`) and does not include links to the actual document (`http://example.com/documents/3/download`).

For example of CSW XML:

http://geonode.state.gov/catalogue/csw?request=GetRecords&service=CSW&version=2.0.2&resultType=results&maxRecords=1000&elementsetname=full&typenames=csw:Record&outputschema=http://www.isotc211.org/2005/gmd

For example when harvested by CKAN, see:

https://catalog.data.gov/dataset/syria-displacementrefugees-2015apr17-hiu-u1214-pdf

**Comment by tomkralidis** [comment]
cc @simod @capooti 

I think this means we simply add another link type when the Document object gets created?  pycsw will then pick this up automagically.

**Comment by pjdufour** [comment]
I'm working on this in my csw_fixes branch (https://github.com/GeoNode/geonode/compare-/GeoNode:master...pjdufour:csw_fixes?expand=1.)  Does the proposed name/ext/mimetype generation algorithm work?

I tried replicating the methodology used in the geoserver signals.  It's a little confusing to implement since we have hosted and external documents.

It generates something like the following:
```
<gmd:onLine>
  <gmd:CI_OnlineResource>
    <gmd:linkage>
      <gmd:URL>http://localhost:8000/documents/1/download</gmd:URL>
    </gmd:linkage>
    <gmd:protocol>
      <gco:CharacterString>WWW:DOWNLOAD-1.0-http--download</gco:CharacterString>
    </gmd:protocol>
    <gmd:name>
      <gco:CharacterString>.jpg</gco:CharacterString>
    </gmd:name>
    <gmd:description>
      <gco:CharacterString>Test.jpg (Hosted Document Format)</gco:CharacterString>
    </gmd:description>
  </gmd:CI_OnlineResource>
</gmd:onLine>
```

I noticed one other thing from checking https://catalog.data.gov/dataset/africa-eboladiseasewithoutborders-2014dec12-u1165-pdf that I should fix before doing a PR.

The "Graphic Preview File" metadata field isn't updated to reflect async/celery pdf thumbnail generation and should be prepended with site url as geonode does for layers.

**Comment by pjdufour** [comment]
The graphic preview file issue might be related to https://github.com/GeoNode/geonode/issues/2176

**Comment by simod** [comment]
@pjdufour, the fix looks good to me. Since the settings is getting too big
I would put the document mappings and extensions in an enumerations.py file
in documents. This for a push to master.
Thanks

2015-06-03 6:02 GMT+02:00 Patrick Dufour <notifications@github.com>:

> The graphic preview file issue might be related to #2176
> <https://github.com/GeoNode/geonode/issues/2176>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2175#issuecomment-108183333>.
>



-- 
Simone
