### ISSUE TITLE
Incorrect Settings passed to Celery Task create_document_thumbnail

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2176]
For the downstream ROGUE build (probably applies to other downstream projects), the correct settings are not passed to the create_document_thumbnail celery task.  When the task runs, it will not create a thumbnail link with the SITEURL prepended as expected from https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L564.  Based on some tests in the interactive python shell, it seems that the settings are not being loaded properly by GeoNode.  It works when you call create_document_thumbnail directly instead of async with .delay (create_document_thumbnail vs. create_document_thumbnail.delay)

The issue might be with https://github.com/GeoNode/geonode/blob/master/geonode/celery_app.py or how this needs to be extended/overridden downstream.

Also, this might apply to other celery tasks, but haven't tested.

**Hotfix**
To hotfix on production, keep function call but just remove `.delay`. from https://github.com/GeoNode/geonode/blob/master/geonode/documents/models.py#L173 or vim /var/lib/geonode/lib/python2.7/site-packages/geonode/documents/models.py

**Comment by garnertb** [comment]
I just created a document using celery and everything works as expected.  If you are using celery, is it possible that you updated your GeoNode settings and then neglected to restart the celery worker? (```service celeryd restart```)?

Thumbnail url: *http://192.168.99.100/uploaded/thumbs/doc-1-thumb.png*
```
[2015-06-03 05:21:49,608: INFO/MainProcess] Connected to amqp://geoshape:**@127.0.0.1:5672//
[2015-06-03 05:21:49,616: INFO/MainProcess] mingle: searching for neighbors
[2015-06-03 05:21:50,629: INFO/MainProcess] mingle: all alone
[2015-06-03 05:21:50,654: WARNING/MainProcess] worker1@precise64 ready.
[2015-06-03 05:22:33,334: INFO/MainProcess] Received task: geonode.tasks.update.create_document_thumbnail[ca65b81c-2f7b-46fc-ab5f-d124b64cae69]
[2015-06-03 05:22:33,499: INFO/MainProcess] Task geonode.tasks.update.create_document_thumbnail[ca65b81c-2f7b-46fc-ab5f-d124b64cae69] succeeded in 0.163797807s: None
```
![screen shot 2015-06-03 at 6 02 39 am](https://cloud.githubusercontent.com/assets/1141646/7957965/208fca90-09b9-11e5-9d86-08570a15ba65.png)

**Comment by pjdufour** [comment]
The thumbnail will be created as expected.  The error is with the metadata/thumbnail link and not the actual creation of the thumbnail.

**Comment by garnertb** [comment]
Nope, ISO: 
```
<gmd:graphicOverview>
<gmd:MD_BrowseGraphic>
<gmd:fileName>
<gco:CharacterString>
http://192.168.99.100/uploaded/thumbs/doc-1-thumb.png
</gco:CharacterString>
</gmd:fileName>
<gmd:fileDescription>
<gco:CharacterString>Thumbnail for 'test'</gco:CharacterString>
</gmd:fileDescription>
<gmd:fileType>
<gco:CharacterString>image/png</gco:CharacterString>
</gmd:fileType>
</gmd:MD_BrowseGraphic>
</gmd:graphicOverview>
```
Links:
![screen shot 2015-06-03 at 8 21 13 am](https://cloud.githubusercontent.com/assets/1141646/7959764/d5bf73b0-09c9-11e5-8173-d839f55e4310.png)

**Comment by pjdufour** [comment]
Thanks.  I'll investigate further.

**Comment by simod** [comment]
Any updates on this?

**Comment by garnertb** [comment]
Talked to @pjdufour and we agree that this can be closed.  The tests in this issue illustrate the functionality is working.
