### ISSUE TITLE
View Documents in Browser

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2180]
There is no option to view a PDF document, text file, etc. in the browser since `/documents/<docid>/download` triggers a download.  Most modern browsers now have an in-browser PDF viewer.  It would complicate the user experience, so it'll have to be done carefully since some new users cannot tell the difference between a browser and Adobe Reader.  However, this would particularly useful for workflows that require quickly looking at a document's raw text.

**Comment by JJediny** [comment]
+1 

Very interested in this as we're considering supporting [annotator.js](http://annotatorjs.org/showcase.html) around our sites to aid in making PDFs more semantic with the rest of our site and building up the document repository with documents we "legally" incorporate by reference. 

@pjdufour - I do remember Geonode 2.0 supported this when using the "Download" option from the paginated list view (which was removed in 2.4)... fairly ignorant but could it be something to do with the MIME type

**Comment by biomap** [comment]
+1 
Any chance of viewing simple spreadsheets as well?  A popup for this would be fantastic for quick viewing.

**Comment by gamesbook** [comment]
@biomap A little googling will show that displaying spreadsheets is not a trivial matter.  A tool like xlrd or openpyxl or even pandas could be used on the server side to convert data into, say, a dictionary or list-of-lists and passed to a Django template for display - but there are many objects that will not easily be accessible in such an approach.

Here's one example:
http://jugad2.blogspot.com/2013/11/publish-microsoft-excel-xlsx-data-to.html

**Comment by JJediny** [comment]
We've considered integrating the OX Suite - http://www.open-xchange.com/en/ox-app-suite. But haven't had a chance to revisit it in a while - gives admins the ability to redirect from a WAF

**Comment by biomap** [comment]
@gamesbook I have seen that it was somewhat substantial of an undertaking and was considering implementing something myself for some basic views.  The feature has been specifically requested from a set of users as well s the pdf and text file views so I very pleased you are considering this implementation.  I wasn't sure how you were going to approach the views but I know there are some JavaScript libraries that could be used.  I had looked at something like http://handsontable.com/ http://sheetjs.com/.  It appears there are some django plugins utilizing the two as well.   I saw the feature request so I figured I would put it out there (a man can dream) if others had similar requests or needs.  Great job and thanks!  :)

**Comment by JJediny** [comment]
Did some research over the weekend and while it's not going to address a web based office suite. It seems logical to support PDF render/preview client or server-side.

The extension I mentioned earlier in the thread - https://hypothes.is/ - uses an internal redirect to have the PDF document open in the browser in javascript using Mozilla's https://mozilla.github.io/pdf.js/. Here are the links to the two extensions of this currently only supported for [Chrome](https://github.com/JJediny/h/tree/master/h/browser/chrome) and [Firefox](https://github.com/JJediny/h/tree/master/h/browser/firefox). Seems like we could offer a new view to have the PDF opened server-side using PDF.js?

**Comment by JJediny** [comment]
Alternative for consideration - http://pdfobject.com/

**Comment by gamesbook** [comment]
@biomap At this time, there are no formal plans to add this functionality... sheetjs looks cool ... ultimately the dev team need to decide on this; a patch submission might be a way to "test the water"?

**Comment by JJediny** [comment]
Full Suite support option - http://oxpedia.org/wiki/index.php?title=AppSuite:DocumentViewer
