### ISSUE TITLE
Replace Layer Failure due to Unmatched Field/Attributes

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2182]
Looks like the new (and great) field/attribute (column) renaming during the upload process isn't running before the validation against the current field names to be replaced. As a result the replace layer fails - not sure if this can be re-ordered so the fields can be matched after they are renamed not before.

![image](https://cloud.githubusercontent.com/assets/6350035/8011706/ef1346be-0b88-11e5-9f95-023ce9e27bc0.png)

**Comment by davisc** [comment]
Tried to replace a layer on demo.geonode.org version 2.4c2 and clicking the replace button invokes no action.

**Comment by simod** [comment]
This is fixed in master.
