### ISSUE TITLE
Add a "add new users to this group" option to GroupProfile

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2183]
This will require a schema change, so I set it to milestone 2.5.
Will be useful if a geonode admin want to create groups that are automatically populated when creating new users, for example if the geonode instance need a "geonode registered users" group.

**Comment by simod** [comment]
+1 thanks Paolo

**Comment by jj0hns0n** [comment]
@capooti whats the status on this? Can we do this now or in 2.7? Moving to 2.7 for now.
