### ISSUE TITLE
SEO, Twitter Cards, OpenGraph, and Robots.txt

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2189]
There's probably some improvements that can be made with Search Engine Optimization.  Good integration with search engines allows users to directly find the layer they are looking for without having to go through the homepage.  Additionally, we should support twitter cards and open graph, so there is a better user experience when sharing GeoNode data on Twitter, Facebook, Slack, etc.

We should suggest a default robots.txt config.  For example, my current robots.txt for a GeoSHAPE Geonode is as below:

```
User-agent: *
Disallow: /account/
Disallow: /activity/
Disallow: /admin/
Disallow: /autocomplete/
Disallow: /avatar/
Disallow: /catalogue/
Disallow: /comments/
Disallow: /geoserver/
Disallow: /groups/
Disallow: /maploom/
Disallow: /messages/
Disallow: /people/
Disallow: /proxy/
Disallow: /ratings/
Disallow: /security/
Disallow: /services/
Disallow: /social/
Disallow: /static/
Disallow: /upload/
```

**Development Items**
- [x] Schema.Org
- [X] Twitter Cards
- [X] Open Graph
- [ ] Robots.txt Guidance

**Comment by pjdufour** [comment]
Implement Twitter Cards (https://dev.twitter.com/cards/overview) on layer detail pages, so that tweets with links to layer detail pages add in the layer's thumbnail.  Example from Twitter:

```
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@flickr" />
<meta name="twitter:title" content="Small Island Developing States Photo Submission" />
<meta name="twitter:description" content="View the album on Flickr." />
<meta name="twitter:image" content="https://farm6.staticflickr.com/5510/14338202952_93595258ff_z.jpg" />
```

**Comment by pjdufour** [comment]
Open Graph works on slack too.

![slack_opengraph](https://cloud.githubusercontent.com/assets/1438253/8368989/882e6d36-1b80-11e5-89d7-a828d513bfc4.png)

**Comment by pjdufour** [comment]
See what data.gov is doing for schema.org using: https://developers.google.com/structured-data/testing-tool/

**Comment by pjdufour** [comment]
Initial Schema.org implementation:

https://github.com/pjdufour/geonode/commit/fdc7680a8f1a062494b33e4a2a0d2e72bf7faa98

**Comment by jj0hns0n** [comment]
@pjdufour any update on this? Moving to 2.7

**Comment by pjdufour** [comment]
I think it's only the robots.txt view and settings that are missing.  I'll do a basic implementaton, e.g., `ROBOTS_TXT_DISSALLLOW_ALL = True` then disallow all, otherwise return  basic robotos.txt.  Or maybe a few other flags.
