### ISSUE TITLE
Document Wand thumbnail generation exception are not handled

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2194]
we need to handle errors in case Wand fails here:
https://github.com/GeoNode/geonode/blob/master/geonode/documents/models.py#L93

**Comment by garnertb** [comment]
Looks like we used to: https://github.com/GeoNode/geonode/commit/411c7af3a5131d1d334284d5d5c7a3148800090c

**Comment by capooti** [comment]
I just have a PR, we just need to change the elif in line 94 with if.
what do you think?

**Comment by capooti** [comment]
here it is. let me know, if you like I send this PR. cheers

**Comment by garnertb** [comment]
That looks good to me, thanks @capooti!

**Comment by pjdufour** [comment]
Close?
