### ISSUE TITLE
Twitter Handles for Users and Groups

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2202]
For open data GeoNodes, it would be useful to have a Twitter account field for each user and group.  Being one click away from an organization's Twitter account would make it easier for data consumers to become a follower of a data producer.  A layer owner's twitter handle could be appended to the description in a Twitter card and displayed on the detail page.

There might be a more "abstract" way of doing this with generic "Social Media Handles" model.  However, using Twitter to announce updated data is probably more straight forward than other social media, so just one field might be the easiest.

**Comment by jj0hns0n** [comment]
@pjdufour this seems fairly straightforward, but moving to 2.7 for now.
