### ISSUE TITLE
Improve GeoNode performance on small and medium bandwidth

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#2208]
This is a broad feature enhancement for GeoNode that can be further break down.
GeoNode is not usable on slow connection particularly the layer preview and map composer are very long to load and the maps within them even more.
Even on medium bandwidth, there are cases where the components loads fast but the background map and overlaying map tiles are really slow to load.

**Comment by rajanski** [comment]
+1

**Comment by jj0hns0n** [comment]
My sense is this is largely due to still using geoext in many places. We should do some tests with the OL3 and/or leaflet modules.
