### ISSUE TITLE
Context/template variable for permissions ("perms")

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2209]
Unless it's by design for some reason, we should not overwrite the variable `perms` in templates to make it represent the list of perms from django-guardian.  For example, 

```Python
[u'add_resourcebase', u'change_resourcebase', u'change_resourcebase_metadata', u'change_resourcebase_permissions', u'delete_resourcebase', u'download_resourcebase', u'publish_resourcebase', u'view_resourcebase']
```

The variable name `perms` is already used by django.contrib.auth and [represents a `PermWrapper` object](https://docs.djangoproject.com/en/1.7/ref/templates/api/#django-contrib-auth-context-processors-auth).

```
perms – An instance of django.contrib.auth.context_processors.PermWrapper, representing the permissions that the currently logged-in user has.
```
I'd suggest changing the name globally (for all templates) to `perms_list` (or similar name) and passing in as a context variable using the django-guardian function [get_perms](http://django-guardian.readthedocs.org/en/latest/userguide/check.html?highlight=get_perms#get-perms) rather than calling `{% get_obj_perms request.user for resource.get_self_resource as "perms" %}` directly in the template.

This has no known security vulnerabilities (hence not critical).  However, de-conflicting these names would make it easier to debug and add features to the permissions interface.

**Comment by capooti** [comment]
hi @pjdufour could you please add a couple of links to the lines in geonode that are doing this? thanks

**Comment by pjdufour** [comment]
**layer_detail**
https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_detail.html#L141

**document_detail**
https://github.com/GeoNode/geonode/blob/master/geonode/documents/templates/documents/document_detail.html#L35

https://github.com/GeoNode/geonode/blob/master/geonode/documents/templates/documents/document_detail.html#L84

**Comment by pjdufour** [comment]
PR #2210 submitted.
