### ISSUE TITLE
geoserver double home page

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#2212]
I'm getting a weird geoserver home page while logged in GeoNode. The environment is a ubuntu 14.04 vagrant vm with b25 and a geonode_project configured. No specific errors nor any specific issue with GeoNode. It's just a double home page composed by one normal geoserver page as logged in user and one as not logged in. See shapshot
<img width="1430" alt="screen shot 2015-07-02 at 23 31 51" src="https://cloud.githubusercontent.com/assets/779380/8502692/5586544a-21b4-11e5-8fb8-19c580e12d22.png">

**Comment by capooti** [comment]
Welcome to the club :)

I experienced this several times in different servers even with just
geoserver.
Never understood the exact cause but I think a service reload will fix it
if I remember properly.
Cheers

**Comment by simod** [comment]
Tried reload restart shutdown crash the machine :-D nothing.

Il venerdì 3 luglio 2015, Paolo Corti <notifications@github.com> ha scritto:

> Welcome to the club :)
>
> I experienced this several times in different servers even with just
> geoserver.
> Never understood the exact cause but I think a service reload will fix it
> if I remember properly.
> Cheers
> On Jul 3, 2015 6:51 PM, "Simone Dalmasso" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > I'm getting a weird geoserver home page while logged in GeoNode. The
> > environment is a ubuntu 14.04 vagrant vm with b25 and a geonode_project
> > configured. No specific errors nor any specific issue with GeoNode. It's
> > just a double home page composed by one normal geoserver page as logged
> in
> > user and one as not logged in. See shapshot
> > [image: screen shot 2015-07-02 at 23 31 51]
> > <
> https://cloud.githubusercontent.com/assets/779380/8502692/5586544a-21b4-11e5-8fb8-19c580e12d22.png
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2212>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2212#issuecomment-118393782>.
>


-- 
Simone

**Comment by simod** [comment]
After some debugging this happens when geonode is running on a Site different from the default (ID=1), geoserver will always GET to /layers/acls, using the standard Site. This breaks only the geoserver home page if geonode is active on both sites but will also break the upload if the default site is not active(geonode not responding).

It would be great if geoserver can respect the site.

**Comment by simod** [comment]
after more debug, I discovered was an issue on the python side due to programming error.
Closing this one.

**Comment by capooti** [comment]
for what it is worth, I have seen this doubled screen also in GeoServer instances without GeoNode :)
