### ISSUE TITLE
ppa repository not working

### ISSUE THREAD

**Issue by watkec** [GeoNode/geonode#2213]
Just tried to install geonode on Ubuntu 14.04 following the directions here:  http://docs.geonode.org/en/master/tutorials/admin/install/quick_install.html#quick-installation

sudo apt-get install software-properties-common
sudo add-apt-repository ppa:geonode/release
sudo apt-get update
sudo apt-get install geonode

the following message was returned:

E: Unable to locate package geonode

**Comment by simod** [comment]
Hi. Ppa release is only for 12.04 use ppa testing instead.

Il domenica 5 luglio 2015, Sudeten <notifications@github.com> ha scritto:

> Just tried to install geonode on Ubuntu 14.04 following the directions
> here:
> http://docs.geonode.org/en/master/tutorials/admin/install/quick_install.html#quick-installation
>
> sudo apt-get install software-properties-common
> sudo add-apt-repository ppa:geonode/release
> sudo apt-get update
> sudo apt-get install geonode
>
> the following message was returned:
>
> E: Unable to locate package geonode
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2213>.
>


-- 
Simone

**Comment by watkec** [comment]
ok so we should use ppa testing.  so what is that?
sudo add-apt-repository ppa:geonode/testing 
OR sudo add-apt-repository ppa:geonode-testing
OR sudo add-apt-repository ppa:geonodetesting
OR sudo add-apt-repository ppa:geonode testing
PLEASE BE SPECIFIC!  THANKS!

**Comment by simod** [comment]
First thing, avoid capital letters. Capital letters won't help you to get help.
Second, please not use the github issues to ask for help, there are dedicated mailing lists for this geonode-users@lists.osgeo.org.
Lastly, you just have to replace release with testing. ppa:geonode/testing. testing is the geonode 2.4 b25.
