### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2214]
Investigate integration with [Slack](https://slack.com/).  Slack supports customizable [incoming webhooks](https://api.slack.com/incoming-webhooks), which should allow a GeoNode instance to push notifications directly into Slack.  After enabling a custom integration for a slack channel, all GeoNode needs to do is POST the correct JSON to the url given by slack.  Slack accepts text and thumbnails (https://api.slack.com/docs/attachments).  All we'd need in local_settings.py is to have a field to specify the slack API endpoint to hit.

Similar benefits as #2189 but different use case.

**Comment by pjdufour** [comment]
PR coming next week.  

![gn_slack](https://cloud.githubusercontent.com/assets/1438253/8632710/3cf1720e-2775-11e5-83f3-42ac0f6eb36d.png)

**Comment by vdeparday** [comment]
This is nice. I think we should have something similar that is sent by emails to the admin and/or layer owner.

**Comment by capooti** [comment]
there is django-notification for this purpose, and this should be already working :)
@pjdufour are you developing on top of it, or doing differently? thanks for the work, seems really nice

**Comment by vdeparday** [comment]
Thanks Paolo for the update. I do not know the details but I remember that you and @ingenieroariel mentioned there were some issues with it. We will be working on improving that this year and making email mandatory so that notifications can be leverage properly.

**Comment by pjdufour** [comment]
For Slack, I'm creating a separate contrib app.  Just a few more tweaks before PR, today or tomorrow.  Let's keep it simple before integrating with django-notification, etc.  The actual code is quite short.  All we need to do is post JSON to a set of urls.  What's complicated is tieing it into GeoNode views, signals, etc.  Also, not sure we'll be able to commit upstream to django-notification, since Slack is a specific website rather than an open standard.

**Comment by pjdufour** [comment]
Phase 2 continued in #2229.
