### ISSUE TITLE
Open Slack workspace to be accessed without invitation or move to a tool is open for everyone to join

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#2215]
With the community growing, I think we need to switch to chat tool that is open to everyone and easy to connect to from various work environment (if that exists). That will avoid to have parallel conversation in many different places. I am not sure if there is a way to remove the need for invitation in Slack? 
Maybe we should move to https://gitter.im/ ? Anyone has tried? Any other options?

Then we should also add this information on the website

**Comment by simod** [comment]
+1 here a general public chat to try
https://gitter.im/GeoNode/general.

thanks

**Comment by jj0hns0n** [comment]
closing as we are now using gitter.im
