### ISSUE TITLE
Import Layers Lower Case

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2217]
The importlayers management command forces the layer name to all lowercase (https://github.com/GeoNode/geonode/blob/master/geonode/layers/management/commands/importlayers.py).  The Web UI doesn't do this.

**Comment by jj0hns0n** [comment]
@pjdufour I think you are conflating the Title and the typename. The typename is always lower case, the title can be anything you wish. closing for now. Reopen with a means to reproduce what you see.

**Comment by pjdufour** [comment]
Typename isn't always lowercase.  Support for uppercase in typename is useful for layers that have multiple words next to eachother that aren't separated by underscores, etc.  That was when a user downloads a layer, it can have the name you want.

![screenshot from 2016-08-22 14 32 06](https://cloud.githubusercontent.com/assets/1438253/17854780/3b56addc-6875-11e6-93d4-6f4d4378680d.png)

**Comment by pjdufour** [comment]
See http://geonode.state.gov/layers/geonode%3ASyria_RefugeeSites_2016Jan21_HIU_DoS0.

Useful to have typename with upper case, for example `RefugeeSites` so it isn't compressed all to lowercase when batch importing.
