### ISSUE TITLE
Embedding the create map interface in another website

### ISSUE THREAD

**Issue by AgentJay** [GeoNode/geonode#2219]
Hello,

I see that is is possible to embed the maps that are published, but I would like to embed the /maps/new interface. 

Cheers.

**Comment by simod** [comment]
@AgentJay please don't use the github issues to ask for help.
Can you move this discussion on geonode-users@lists.osgeo.org?

**Comment by AgentJay** [comment]
My issue is in two parts. The first is that django/geonode adds an X-Frame-Options header to the page as it is generated. This is to prevent clickjacking. The second is that even if the header option was removed from the create map page, the menu would still appear at the top of the page. 

I would prefer to get the new map page without the menu. It may be possible to get help to hack this functionality into Geonode, but I would prefer if it was a built in feature.
