### ISSUE TITLE
Remove user fails even if every of its layers ownership is changed

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2222]
1. create a new user
2. upload a shapefile with the new user
3. change ownership, and contact points in the layer to a different user

now If I try to remove the user, I get the following error:

UploadSession matching query does not exist.

Also, the layer is deleted from GS but still appears in GN.
Working on it.

**Comment by huferrarigo** [comment]
There is a way to manually delete user:
"clean" some database entries related to the user
Especially,
Via django back end menu, delete uploadsessions related to this user.
