### ISSUE TITLE
Black and White theme for GeoExt

### ISSUE THREAD

**Issue by gsolat** [GeoNode/geonode#2225]
It is based on FontAwesome and MonsterIcon.

If it is of interest to the community I can create a theme and submit it to django-geoexplorer.

![map_view](https://cloud.githubusercontent.com/assets/5114135/8685018/8b0c35f4-2a41-11e5-8484-876da9baea41.png)
![layer_detail](https://cloud.githubusercontent.com/assets/5114135/8685022/8d09ee96-2a41-11e5-9f47-94f7d1ee455d.png)

**Comment by jj0hns0n** [comment]
Awesome. Please send a PR!

**Comment by ingenieroariel** [comment]
+1

(disclaimer, @gsolat works with me at http://github.com/piensa )

**Comment by simod** [comment]
+1

2015-07-14 23:06 GMT+02:00 Ariel Núñez <notifications@github.com>:

> +1
>
> (disclaimer, @gsolat <https://github.com/gsolat> works with me at
> http://github.com/piensa <https://github.com/piensa> )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2225#issuecomment-121386975>.
>



-- 
Simone
