### ISSUE TITLE
Region Codes

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2227]
Regions are just exposed as their verbose name, such as "Syrian Arab Republic".  We should find a way to integrate the FIPS and ISO codes for regions in metadata and the UI.  The current section in metadata is:

``` xml
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>Syrian Arab Republic</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="place">place</gmd:MD_KeywordTypeCode>
    </gmd:type>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

Support for ISO codes will enable easier CSW-based search across datasets in a single GeoNode and across multiple GeoNode instances.

Is there a standardized way to add to ISO metadata multiple place codes from different code lists that represent the same place?

**Comment by tomkralidis** [comment]
ISO allows for 1..n sets of keywords, so we can add another set of keywords based on FIPS/ISO 3166 codes.  Unfortunately there's no way in ISO XML to have code/labels/associations, so the easiest way is to provides codes as another set of keywords.

**Comment by pjdufour** [comment]
For 2.4.X, we can just add straight ISO Alpha 3 (SYR, etc.) for now?  That's what the regions in GeoNode are coded as, right?

For 2.5.x, since there isn't a restricted codelist then, maybe we can preface the characterstring with: ISO3, ISO2, ISONUM, FIPS,  etc.  Could probably handle parsing in new code from #2232 refractor.  As example below:

```xml
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>ISO3:SYR</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeSpace="ISOTC211/19115" codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="place">place</gmd:MD_KeywordTypeCode>
    </gmd:type>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```

@tomkralidis, sounds good?

**Comment by tomkralidis** [comment]
@pjdufour in lieu of prefixing, we could simply ref a thesaurus, like:

```xml
      <gmd:descriptiveKeywords>
        <gmd:MD_Keywords>
          <gmd:keyword>
            <gco:CharacterString>SYR</gco:CharacterString>
          </gmd:keyword>
          <gmd:type>
            <gmd:MD_KeywordTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="place" codeSpace="ISOTC211/19115">place</gmd:MD_KeywordTypeCode>
          </gmd:type>
          <gmd:thesaurusName xlink:type="simple" xlink:href="http://www.iso.org/iso/catalogue_detail?csnumber=39534" xlink:title="ISO 639-3:2007 - Codes for the representation of names of languages -- Part 3: Alpha-3 code for comprehensive coverage of languages"/>
        </gmd:MD_Keywords>
      </gmd:descriptiveKeywords>
```

Thoughts?

**Comment by pjdufour** [comment]
That looks like a good idea.  Minor note, that's the link for ISO language codes and not ISO country codes.

Would `gmd:thesaurusName` be safely ignored by systems that don't understand it?

**Comment by tomkralidis** [comment]
@pjdufour ok, so some URL which is authoritative for ISO languages codes.  Yes, `gmd:thesaurusName` being ignored.
