### ISSUE TITLE
Slack Integration, Phase 2 Enhancements

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2229]
Continuation of #2214.  Current slack integration via the [slack contrib app](https://github.com/GeoNode/geonode/tree/master/geonode/contrib/slack) is basic and does not scale well for a high usage instance.  The Slack "Incoming Webhooks API" is explained at https://api.slack.com/incoming-webhooks and https://api.slack.com/docs/attachments.

**Potential Enhancements**
- [ ] **High-priority:**  Use Celery tasks to send messages
- [ ] Post comments added by users about a layer/map/document to Slack
- [ ] Post announcements to Slack
- [ ] Post new user/group to Slack
- [ ] Post admin logins to separate defined Slack channel
- [ ] Better integration with django-notifications, django-announcements, and internal signals/events
- [ ] Route messages to different channels based on context
- [ ] Provide user level customization (rather than just admin via settings.py)
- [ ] Post certain errors to Slack

**Comment by jj0hns0n** [comment]
@pjdufour any update on this? Moving to 2.7 in any case.

**Comment by pjdufour** [comment]
Migrated to using GeoWatch to abstract notifications to be more general.  Have some development branches with new functionality, but not production ready.

https://github.com/geowatch

For a client, we turned on Slack integration for a bit, but the team isn't paid and gets near 3,000 messages a week.

Don't think I'll get time to make improvements until 2.7

**Comment by pjdufour** [comment]
Sorry, meant client is hitting 10k message limiy within every 3 weeks, so would be hard to justify increasing the GeoNode notifications 10x since would overload the human chatting.

**Comment by jj0hns0n** [comment]
Ok, lets just leave this in 2.7 then.
