### ISSUE TITLE
Regions Refactor and UI Upgrade

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2232]
We should refractor the `regions` metadata field and model to be more robust.  We need the ability to specify the extent of a layer with more detail, such as a city, PCODE (unique non-linguistic identifer commonly used in humanitarian responses), province, ISO code, FIPS code, etc.  A nicer user interface for selecting regions would be useful, too.

This is related to #2227.

We should incorporate the thesaurus at https://data.hdx.rwlabs.org/dataset/lsib-geographic-thesaurus to support multiple codelists.

This will need to wait for 2.5.x because of model changes.

```
class Region(models.Model):

    name = models.CharField(max_length=255)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children')

    @property
    def get_code(self, codelist=None):
        if codelist:
            return self.regioncode_set.objects.filter(codelist=codelist)
        else:
            return None

    @property
    def get_codes(self)::
            return self.regioncode_set.objects.all()


class RegionCodeList(models.Model):

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)

class RegionCode(models.Model):

    codelist = models.ForeignKey(RegionCodeList, verbose_name=_("Region Code List"))
    region = models.ForeignKey(Region, verbose_name=_("Region Code"))
    code = models.CharField(max_length=50)



```

**Existing Django projects to investigate**
https://github.com/coderholic/django-cities
https://github.com/danielsokolowski/django-geonames

**Comment by jj0hns0n** [comment]
@pjdufour any update on this? Moving to 2.7 in any case.
