### ISSUE TITLE
If a GeoServer Importer Session fails the next ones will fail until cleared/cancelled

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2242]
As stated in the title,
I'm experiencing issues when using the GeoServer Importer to upload the layers.
If an Importer Session fails for some reason (therefore remaining in a "PENDING" state) the next uploads sometimes fail too especially when uploading a Shapefile data type.

**Comment by afabiani** [comment]
Fixed on

https://github.com/GeoNode/geonode/pull/2276

**Comment by pjdufour** [comment]
@afabiani, close?

**Comment by afabiani** [comment]
Yes
