### ISSUE TITLE
djcelery is not needed anymore

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2246]
According to the documentation:
http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html
so we could safely remove it from the dependency and installed apps.

**Comment by capooti** [comment]
sorry, we still need it as we want to store celery results using Django ORM. Closing it, sorry for the noise.

**Comment by sarasafavi** [comment]
Re-opening to track removal of django-celery; reference https://github.com/GeoNode/geonode/issues/2700 for more.

**Comment by capooti** [comment]
This will not be needed anymore when moving to Celery 4 as per #3069
