### ISSUE TITLE
OSM layers not visible at max zoom level

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#2256]
There are served by OSM but geoexplorer does not requests them at the max zoom level. Bing layer is ok. @bartvde any hints?

**Comment by bartvde** [comment]
what the number of zoom level in this case?

**Comment by bartvde** [comment]
Ah I see what you mean on: http://suite.opengeo.org/geoexplorer/composer/

zoom level 19 grayed out for OSM

**Comment by simod** [comment]
yes :)

**Comment by simod** [comment]
any way to configure it through the settings? https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L613

**Comment by bartvde** [comment]
I don't think it can be currently configured, can you trying changing this to 20? It worked for me:

https://github.com/boundlessgeo/gxp/blob/master/src/script/plugins/OSMSource.js#L93

PR welcome ofcourse.

**Comment by simod** [comment]
yes it works :) thanks

**Comment by jj0hns0n** [comment]
@simod @bartvde can we close this now?

**Comment by capooti** [comment]
I think yes, as per #2346

**Comment by bfg9000it** [comment]
I'm still in the problem.
My geonode 2.4 installation has the same problem in the viewer when it shows public openstreetmap server or my internal OSMbright tile server (ZoomLevel 19: scale 1:1066)
I do not understand where I can change "numZoomLevels" setting because I have no OSMSource.js here.
Actually I can't upgrade to 2.6 version: in the meantime it is possible to have a workaround?

**Comment by simod** [comment]
Hi, you can add the property in this file. https://github.com/GeoNode/geonode/blob/master/geonode/maps/templates/maps/map_geoexplorer.js
hope it helps

**Comment by bfg9000it** [comment]
Hi, I've inserted "numZoomLevels: 19", 20 or other numbers before "listeners" and after csrfToken but without any visible change. There are always 20 levels starting from the first 1:1066.
I really do not understand where is defined the number of zoom levels.
