### ISSUE TITLE
extended search

### ISSUE THREAD

**Issue by vowasemp** [GeoNode/geonode#2257]
It would be useful for us if the text-search would also include other fields (abstract, purpose). Without django-knowhow its rather hard to extend the search-functions.

**Comment by garnertb** [comment]
Geonode comes with support for using a search engine like Solr or Elastic-Search via django-haystack.  I have noticed a significantly improved search experience with it and it already indexes the abstract and purpose and other fields.  Check the docs for more information: http://docs.geonode.org/en/master/reference/api.html?highlight=haystack#searching-with-haystack
