### ISSUE TITLE
[2.4b25 / Editing features on a layer] Creating a new feature returns 'Error performing insert: Error inserting features'

### ISSUE THREAD

**Issue by m431m** [GeoNode/geonode#2263]
Hi!

I'm currently testing latest version: 2.4b25.
I notice a failure with the editing tool (on GeoExplorer interface).
Modify a feature works well but create a new feature returns this exception: 'Error performing insert: Error inserting features'.

Is it a bug? Or is it just my setup?

m431m

**Comment by capooti** [comment]
On Mon, Sep 7, 2015 at 2:40 PM, m431m <notifications@github.com> wrote:
>
> Hi!
>
> I'm currently testing latest version: 2.4b25.
> I notice a failure with the editing tool (on GeoExplorer interface).
> Modify a feature works well but create a new feature returns this exception: 'Error performing insert: Error inserting features'.
>
> Is it a bug? Or is it just my setup?
>
> m431m
>
> —


https://github.com/GeoNode/geonode/issues/2253

-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by capooti** [comment]
please check first on mailing list before submitting a bug on the ticket system.

**Comment by m431m** [comment]
Ok thank, it was a problem with the PK sequence...
I 'll check next time... sorry.
m431m

**Comment by capooti** [comment]
no problem. Thanks for your testing :)

On Mon, Sep 7, 2015 at 3:26 PM, m431m <notifications@github.com> wrote:

> Ok thank, it was a problem with the PK sequence...
> I 'll check next time... sorry.
> m431m
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2263#issuecomment-138298009>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
