### ISSUE TITLE
LOCKDOWN_GEONODE not working from local_settings.py

### ISSUE THREAD

**Issue by Froggiewalker** [GeoNode/geonode#2277]
Hi,
me and [others](http://gis.stackexchange.com/questions/159283/disable-access-to-geonode-resources-per-default) tryed to close GeoNode site for unregistered users, but putting `LOCKDOWN_GEONODE = True` in *local_settings.py* doesn't work.

I solved this issue by changing this parameter directly in *settings.py*.

Is it a bug, or did I make something wrong?

**Comment by garnertb** [comment]
Add the ```LoginRequiredMiddleware``` to your MIDDLEWARE_CLASSES in your local_settings.py: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L700

**Comment by simod** [comment]
nice catch, we have to move https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L700 after the local settings import https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L889. Want to make a PR?

**Comment by Froggiewalker** [comment]
Yes, I will be honored. Thanks

**Comment by simod** [comment]
Thanks!
