### ISSUE TITLE
Cascading delete is a bit misaligned with the GS REST APIs

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2279]
Accordingly to the GeoServer REST APIs, the "purge" parameter should be provided as string since it is not a boolean. It's value depends on which kind of resource you are trying to delete and may have different values in some cases.
Moreover in the case of a CoverageType store, there is the possibility of specifying an additional parameter named "recurse", which is a boolean and allows GeoServer to cleanup also all additional garbage (DB tables, uploaded files and so on, depending on the CoverageType)

**Comment by garnertb** [comment]
Merged in https://github.com/GeoNode/geonode/pull/2280.
