### ISSUE TITLE
CommandError: One or more models did not validate

### ISSUE THREAD

**Issue by MrZogs** [GeoNode/geonode#2283]
I'm trying to install geonode. I downloaded the latest geonode version from github (git clone https://github.com/GeoNode/geonode.git). I'm now using a master branch. (http://stackoverflow.com/questions/32139779/geonode-commanderror-one-or-more-models-did-not-validate-syncdb)

`CommandError: One or more models did not validate:
dialogos.comment: 'author' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
agon_ratings.rating: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
announcements.announcement: 'creator' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
announcements.dismissal: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
user_messages.thread: 'users' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
user_messages.userthread: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
user_messages.message: 'sender' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
account.account: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
account.signupcode: 'inviter' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
account.signupcoderesult: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
account.emailaddress: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.
account.accountdeletion: 'user' defines a relation with the model 'auth.User', which has been swapped out. Update the relation to point at settings.AUTH_USER_MODEL.`

When i try to use a branch 2.0.x and do `paver start`  it fails because when it does `python manage.py syncdb --all` that `--all` option doesn't exist for syncdb `manage.py: error: no such option: --all`. 

Can you please explain me what am i missing?

**Comment by simod** [comment]
Hi it is possible that you installed the 2.0 before master? Or another version of some packages? Use a clean environment to install geonode in. 
Also please ask on the mailing lists before opening tickets here.
