### ISSUE TITLE
document upload fails on very long filenames

### ISSUE THREAD

**Issue by senoadiw** [GeoNode/geonode#2285]
Hi all,

I tried uploading a document file with a very long name and got the following error log:

DataError: value too long for type character varying(100)

I think doc_file field should have max_length set to 255 like the file field in LayerFile => https://github.com/GeoNode/geonode/blob/master/geonode/layers/models.py#L268

Regards,

SN

**Comment by capooti** [comment]
I agree with you and I think there is another issue with this, but cannot find it.
I think this case of schema change is allowed, should we change this before releasing 2.4?

**Comment by jj0hns0n** [comment]
@capooti is this implemented? Moving to 2.7 in any case.
