### ISSUE TITLE
Removing a document does not delete the file in the uploaded dir

### ISSUE THREAD

**Issue by senoadiw** [GeoNode/geonode#2291]
Hi all,

I'm running the latest GeoNode from github. Apparently removing a document from GeoNode does not also delete the physical file. Uploaded layer files are deleted when removed though. Is this intended by design?

Regards,

SN

**Comment by pjdufour** [comment]
I think this is a bug.

**Comment by capooti** [comment]
This is the standard Django behavior. We would need to have a celery task to delete orphan files asynchronously. I already have something like that, I can commit it during the sprint.

**Comment by capooti** [comment]
so what to do here?

**Comment by simod** [comment]
wouldn't a post_doc delete signal do it?

**Comment by garnertb** [comment]
Yep, the celery task will be called from a post delete signal and I agree with @capooti that this should be a celery task.
