### ISSUE TITLE
Upload Document - URL - Error if extension is 4 chars (e.g. .xlsx)

### ISSUE THREAD

**Issue by gdreich** [GeoNode/geonode#2300]
Hi all, 

I am receiving the following error when trying to upload a document using a URL which has a document extension longer than 3 chars (e.g. .xlsx, .docx etc)

IntegrityError: null value in column "extension" violates not-null constraint.

Looks like this is the culprit: https://github.com/GeoNode/geonode/blob/master/geonode/documents/models.py#L145

regards,
gavin

**Comment by simod** [comment]
@gdreich thanks for the issue and debug. Definitely that is not the optimal way to get the extension.

Patches are welcome :)

**Comment by gdreich** [comment]
Np, submitted a PR earlier but forgot to ref the issue!
