### ISSUE TITLE
Layer upload progress bar is broken

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2301]
This is happening in my local instance and also on demo site.

**Comment by simod** [comment]
@capooti I can see it on demo. What error do u get?

**Comment by capooti** [comment]
sorry, it works with other shapefiles, it is just a problem of this (very popular) one:
http://thematicmapping.org/downloads/TM_WORLD_BORDERS-0.3.zip

but apparently I don't see errors, but there must be a reason.

**Comment by simod** [comment]
Can't reproduce this. Close?

**Comment by capooti** [comment]
I have just tried again, and still I do not get the progress bar.
It works with any other shapefiles, but If you try with the one I suggested, no progress bar thought the layer is successfully uploaded

**Comment by capooti** [comment]
working on this

**Comment by francbartoli** [comment]
@capooti going to reproduce and it happens also with different shapefiles, browser firefox

**Comment by capooti** [comment]
yes, the problem is when we have "." in names, I am close to fix it.
