### ISSUE TITLE
GeoExplorer zoom problem

### ISSUE THREAD

**Issue by helios2** [GeoNode/geonode#2303]
I've recently installed GeoNode 2.4b27 on Ubuntu Server 14.04 machine. There's a problem with GeoExplorer: after using the zoom the first time, the successive times is no longer possible to do so.

**Comment by simod** [comment]
@helios2 check out this thread http://lists.osgeo.org/pipermail/geonode-users/2015-October/000850.html.

**Comment by helios2** [comment]
Did it, it works.

**Comment by rajiburp** [comment]
after removing bing maps from local_settings.py the uploaded shapefiles are not visible and also the internet browser is showing working for long time. what might be the problem?
