### ISSUE TITLE
Include detailed layer information in maps API endpoint

### ISSUE THREAD

**Issue by cstephen** [GeoNode/geonode#2304]
Currently, the maps API endpoint at `/api/maps/<map-number>` includes a count of the layers a map has, but no information about the layers themselves. My understanding is this is because the maps API is currently only used to return search results.

At the Scenarios Network for Alaska + Arctic Planning, we are developing an isolated web application that needs to use the API to load WMS information for all of the layers belonging to a particular map. We went ahead and added a new API endpoint for detailed map layer information and gave it a new path, `/api/maplayers/<map-number>`. This new endpoint includes everything returned by the original "maps" endpoint but also tacks on all of the information returned by the Map model's `layer_config()` method. This includes each layer's title, GeoServer WMS URL, bounding box, keywords, etc.

I'd like to contribute this work to the GeoNode project, but does this approach make sense? Or would it be better to add map layer information to the existing `/api/maps/<map-number>` endpoint?

**Comment by simod** [comment]
@cstephen please go ahead with a pull request. The apis for search are very light by design for performance purpose and retrieve only the information available in the respective tables without following relations. The tastypie dehydration cycle has been disabled. But the apis are also designed to be extended and we did already with a Owners light api and a Profile heavier api. So we can absolutely include a new more verbose one for maps and layers.

**Comment by capooti** [comment]
Alternatively you could extend the API to your needs in your GeoNode custom
project, without forking GeoNode.

Here is a quick code sample that extend the Layer API with a new attribute
(not tested but should put you on the way):

class ExtendedLayerResource(LayerResource):

    extent = fields.TextField()

    def dehydrate_extent(self, bundle):
        return '%s %s %s %s' % (bundle.obj.bbox_x0, bundle.obj.bbox_x1,
bundle.obj.bbox_y0, bundle.obj.bbox_y1)

then from template call the ExtendedLayerResource end point in place of the
LayerResource
hope it helps
p

On Tue, Oct 13, 2015 at 8:27 AM, Simone Dalmasso <notifications@github.com>
wrote:

> @cstephen <https://github.com/cstephen> please go ahead with a pull
> request. The apis for search are very light by design for performance
> purpose and retrieve only the information available in the respective
> tables without following relations. The tastypie dehydration cycle has been
> disabled. But the apis are also designed to be extended and we did already
> with a Owners light api and a Profile heavier api. So we can absolutely
> include a new more verbose one for maps and layers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2304#issuecomment-147617989>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
