### ISSUE TITLE
allow geonode proxy for arbitrary wms requests

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#2307]
to allow any wms layers in the map composer without having to set the PROXY_ALLOWED_HOSTS.

**Comment by ramavanan** [comment]
hello Simod

Geoexplorer zooming function is not working in all sample application, Actually what is the problem

now geonode is not working without internet connection

**Comment by garnertb** [comment]
I'm not sure how straightforward it would be to implement this issue while simultaneously avoiding this one: https://github.com/GeoNode/geonode/issues/1308.

**Comment by jj0hns0n** [comment]
@simod should we update/close this in light of DJMP.
