### ISSUE TITLE
Ability to create new layer in addition to upload

### ISSUE THREAD

**Issue by smesdaghi** [GeoNode/geonode#2309]
We have the need to support creating new layers through geonode in addition to the upload capability. This is currently being done for MapStory but a problem we have needed to solve for ROGUE/GeoSHAPE as well. Not long ago, we added the ability to upload geojson which partially addresses the issue. The problem there is that you can’t upload an empty layer in geojson. 

We have something basic working but we are trying to find the right place to put it. Some options are:

1) create a new page 
2) rename “upload layer” to “add layer” and have a tab on the page that allows choosing between file upload and create. 
3) create a 3rd party app 

Option1 is working but we need to add the ability to set the permission and import into geogig (same as side form on layer upload). The other question is how should users get to the page. I think renaming “upload layer” to “add layer” and making the functionality a tab on the upload page is the way to go (Option2) but wanted to get your throughs on it. The other projects we work on can really use this feature as well as we currently have to ask users to create a geojson by hand and also force them to  put a ‘sample’ feature in it. Creating shapefiles is cumbersome but more importantly when you try to present the attributes on a form for users to fill out during feature creation, the attribute name length restriction become a big problem.  

Option1 current implementation:
![screen shot 2015-10-16 at 7 24 37 am](https://cloud.githubusercontent.com/assets/1099873/10540770/088252b2-73d9-11e5-9ba0-7523faa067ad.png)

**Comment by vdeparday** [comment]
I am +1 on option 2. I think it is a general feature from which many GeoNode could benefit, especially with more advanced edit tools like in the ROGUE interface.

**Comment by JJediny** [comment]
The approach we took was to extend geonode with a third party GeoJSON uploader/creator/editor - it's actually two existing repos 1. [Django API for deserializing and storing GeoJSON directly into PostGIS](https://github.com/JJediny/Leaflet.Storage) 2. [Leaflet based map client/editor that interacts with the API middleware](https://github.com/JJediny/django-leaflet-storage). We've been using it in production without issues now for ~6 months and is based on another FOSS project http://umap.fluv.io/en/

Another workflow to consider is to leverage the whole package as a why for users to upload or convert (currently supporting conversion of CSV/KML/GPX/OSM/GeoRSS into GeoJSON), edit/add attributes and features, then "when ready" upload the GeoJSON to GeoGig/Geonode for long term management...

**Comment by JJediny** [comment]
Should also add that we extended Geonode's existing API with the 3rd Party app - see http://nepanode.anl.gov/geojson/api

and/or here are some examples - https://nepanode.hackpad.com/NEPAnodes-GeoJSON-Editor-1R1PRnbCvnB

**Comment by jj0hns0n** [comment]
This functionality exists in Worldmap. @capooti can you take a look at this and see if we can port it over.

**Comment by capooti** [comment]
It is in GeoNode 2.5 feature list, and yes it is definitely useful for GeoNode

**Comment by jj0hns0n** [comment]
@capooti @smesdaghi any update on this. Moving to 2.7, feel free to move back.

**Comment by smesdaghi** [comment]
@jj0hns0n, got a version in to mapstory last year but has been re-done specially with changes to geogig. will ping @JWileczek to see if they can bump it to core.
