### ISSUE TITLE
Adding apiKey in local_settings.py for Google and Bing maps

### ISSUE THREAD

**Issue by AnnalisaS** [GeoNode/geonode#2314]
It's possible to add to MAP_BASELAYERS entry, in local_settings.py, also Bing and Google basemaps setting my own key, if available?
Thank you

**Comment by capooti** [comment]
I am working on this. The admin can set the BING api key in settings, and in such a case the bing basemap is enabled.

**Comment by jj0hns0n** [comment]
The BING key is not respected by geoexplorer, but this has been implemented.
