### ISSUE TITLE
Geonode installation problem: unmet dependencies: geoserver

### ISSUE THREAD

**Issue by rajiburp** [GeoNode/geonode#2320]
geonode@dmic-geonode:~$ sudo apt-get install geonode

Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 geonode : Depends: geoserver-geonode but it is not going to be installed or
                    geoserver but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by simod** [comment]
@rajiburp please ask on the mailing lists before opening a ticket. Please also describe your environment and os versions.
