### ISSUE TITLE
"Replace" button does not work anymore

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2323]
After the introduction of the mandatory categories on the upload page, the "Replace" button on the "layer_replace" page has been broken.

Clicking on it apparently does not produce any event.

**Comment by simod** [comment]
We have to revert the category choice in the upload phase as it clashes with the multiple layers upload, they may have different categories.

**Comment by capooti** [comment]
I think let's keep it and fix what is making the layer_replace view to fail.
The multiple layer upload can be still used, selecting just one category for all of the layers, don't you think?
Can we do this at the code sprint?

**Comment by simod** [comment]
well, we are in the case where we need to upload multiple layers of different categories and then we have to figure out that manually.... let's take a look at the sprint though

**Comment by ccosse** [comment]
Hi, if it can be okay to have 1 category for multiple layers then it's
reasonable to fix (is it even broken in that case?).  But for multiple
categories and multiple layers ... not so pretty and probably not fixable
just today.
