### ISSUE TITLE
Use `isPublished` field to control whether a Resource is exposed in pycsw

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2332]
I believe `isPublished` field in ResourceBase Metadata is only a placeholder and/or only controls Geonode API filter... if this is correct could this field also be used to restrict layers/documents/maps being exposed by pyCSW?

The need for this is to avoid data/documents that are DRAFT or in-developement from being exposed to other CSW services/harvests before "they are ready".

**Comment by JJediny** [comment]
@tomkralidis any constraints from doing this or recommendations of an approach we can/should take?

**Comment by tomkralidis** [comment]
@JJediny fair enough.  We will need to update [pycsw](https://github.com/geopython/pycsw/blob/master/pycsw/plugins/repository/geonode/geonode_.py) to (optionally) filter based on publish state.

I would also recommend an option in pycsw config (which we manage in GeoNode) called `show_published` or something which can direct pycsw to display unpublished records or not.  *Unless* there is a GeoNode workflow rule that says unpublished never gets put to CSW/OAI/SRU/OpenSearch.

**Comment by tomkralidis** [comment]
FYI I have this working now.  Using pycsw's [repository filter](http://docs.pycsw.org/en/latest/repofilters.html) mechanics, we are able to define this in https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local.py#L46

Before I push this (for 2.5) we need to decide whether `is_published=True` is a./ the default state/behaviour or whether b./ this should be configurable (in `geonode.settings`).  I would vote for option A but would like to hear thoughts from others.

**Comment by tomkralidis** [comment]
Note that I also found a pycsw [bug](https://github.com/geopython/pycsw/issues/388) in the process of addressing this issue which has since been fixed.  Once we have consensus on GeoNode behaviour, and pycsw 1.10.3 is released, I will submit a PR of the branch for merge.

**Comment by jj0hns0n** [comment]
@tomkralidis any update on this? Moving to 2.7 but feel free to move back.

**Comment by tomkralidis** [comment]
Fixed in master.
