### ISSUE TITLE
API Upload

### ISSUE THREAD

**Issue by bunnis** [GeoNode/geonode#2335]
Hi
Im trying to make a batch upload. I tried CSW but i believe it is not possible. I'm trying to use the API but it seems the upload future was removed? This link http://docs.geonode.org/en/dev/developers/api.html does not present it on the endpoints, but at some point in time it existed, refered on this link: http://docs.geonode.org/en/dev/developers/api.html 
Also the documentation is not very helpfull and some place (like develepoer workshop) does not contain info about the API, although it has an API section.

Can someone confirm? If it is intended what is the current way of batch uploading?

**Comment by simod** [comment]
Hi, API upload has never been implemented, that documentation is a draft for the old 2.0.

One solution could be to upload the data to geoserver and then run a geonode updatelayers.

ps. please use the mailing lists to as for support before opening tickets.

Regards
