### ISSUE TITLE
Import Layers / Results Calculation for Overwrite

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2336]
When running importlayers with --overwrite to update existing layers, updatelayers seems to add to "Created Layers" instead of "Updated Layers".

```
Finished processing 1 layers in 1.0 seconds.

1 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
1.000000 seconds per layer
```

**Comment by pjdufour** [comment]
Or do we need to add a different counter like 1 Replaced Layer

**Comment by francbartoli** [comment]
Trying to replicate the issue but in my case the overwritten layer has been treated as "Updated layer"

**Comment by pjdufour** [comment]
I'll close and reopen if detected in the future.
