### ISSUE TITLE
Remote services Catalogue Import Improvements

### ISSUE THREAD

**Issue by jmwenda** [GeoNode/geonode#2359]
When importing Catalogue services, there is need to log layers that exist in the remote service and provide quick stats on what has been imported, layers that failed, layers in non spherical projection to help admins keep track of such layers registered. There is also need to bring in WFS support and more tests with other catalogue service endpoints. cc. @tomkralidis

**Comment by jj0hns0n** [comment]
@jmwenda did you work on this?
