### ISSUE TITLE
Brief Project History for OSGeo Incubation

### ISSUE THREAD

**Issue by bitner** [GeoNode/geonode#2360]
Add a brief history of GeoNode for inclusion in the OSGeo Incubation Provenance Review. https://wiki.osgeo.org/wiki/GeoNode_Provenance_Review#GeoNode_Provenance_Review.

**Comment by tomkralidis** [comment]
Slightly related and a great by product would be to document GeoNode on Wikipedia.

**Comment by jj0hns0n** [comment]
We have an entire paper on the history of the project written by @kfogel (focused on the initial investments in the project by GFDRR) ... we can post it here and convert to a web version at some point. Im giving a talk on this topic at FOSS4G

**Comment by jj0hns0n** [comment]
@kfogel if you guys have time, can we put up a wiki page or somewhere in the project docs with the basic details from the report ... or at least put it up online so we can close this and finish incubation :)

**Comment by bitner** [comment]
I think if the report is online, just adding a link to the wiki would suffice.

**Comment by jj0hns0n** [comment]
Not online yet. Ill email you a copy and have given one to Jody. I think we
can assume this will get published soon and close this ticket. Might be ok
to put the important highlights into the wiki? @Bitner could you help with
that?

**Comment by kfogel** [comment]
No objection here to highlights from latest draft being published; I don't think the overall shape or high-level conclusions are likely to change between now and the final published version.
