### ISSUE TITLE
Review Committers/Affiliations for OSGeo Incubation

### ISSUE THREAD

**Issue by bitner** [GeoNode/geonode#2361]
https://wiki.osgeo.org/wiki/GeoNode_Provenance_Review#Committers

**Comment by jj0hns0n** [comment]
@kfogel collected this info for his report. Can we post it somewhere.

**Comment by kfogel** [comment]
Hey @jj0hns0n, I'd be happy to.  Let me grab it tomorrow and figure out the right way to publish it (you've seen the spreadsheet -- I assume that you concur there's nothing confidential in there?).

**Comment by jj0hns0n** [comment]
Yeah, I'd just dump this onto the osgeo wiki can you send me the latest
copy and I can work with @bitner to get it up so we can close this. Thanks!

**Comment by kfogel** [comment]
Oh, sorry @jj0hns0n -- I thought you had been looking at it this whole time.  It's just the same Google Spreadsheet, which you should have access to (I just checked): https://docs.google.com/spreadsheets/d/1-Mtb20G8QLQpRl9jnSFlMzTHURwKyuZwUlx1gSYVvxE/

**Comment by jj0hns0n** [comment]
@kfogel can you just make that publicly editable. @bitner not sure where to
put this, but we can ask folks on the list to add any missing info.

**Comment by kfogel** [comment]
Okay, @jj0hns0n, it's now publicly editable (I made a backup first, though!).

**Comment by jj0hns0n** [comment]
Done and our incubation was submitted today thank you for all your help
