### ISSUE TITLE
Adopt CLA, add process to Dev Documentation

### ISSUE THREAD

**Issue by bitner** [GeoNode/geonode#2363]
Adopt a contributor's license agreement through a PSC motion and make sure that all contributor responsibilities with regards to licensing/copyright are included in the developer documentation.

The OSGeo Provided Licenses at http://www.osgeo.org/content/foundation/legal/licenses.html are suggested and include language to assign copyright to OSGeo.

**Comment by bitner** [comment]
Upon adoption of CLA, every reasonable attempts should be made to get past contributors to sign.

**Comment by ingenieroariel** [comment]
I suggest we do the same as pycsw: https://github.com/geopython/pycsw/issues/312

**Comment by jodygarnett** [comment]
Reading the pycsw#312 it has some limitations - the format:

```
Hi all, I'd like to contribute <feature X|bugfix Y|docs|code|something else> to pycsw. I confirm that my contributions to pycsw will be compatible with the pycsw license guidelines at the time of contribution.
```

This does have a nice record that the code was contributed on purpose - it does not however grant *you* the geonode leadership many/any abilities.

The point of having something like the OSGeo provided licenses is:

1. It gives you (the geonode leadership) control - since you operate on behalf of OSGeo to manage the codebase. This greater control allows you to relicense the work - say if you want to donate a fix to GeoTools. 

  - The GeoServer team uses this ability to take fixes that have been applied to GeoServer (GPL) and donate them back to GeoTools (LGPL). This would not be possible under the terms of GPL, but is possible using the CLA.

2. The OSGeo contribution agreements are a direct copy of the apache contribution agreements:
    
   - Which makes organizations comfortable in a legal sense (this allowed google to contribute to GeoTools when they could not previously due to our own homebrew CLA)
   - Those without a legal team can go do some research on how it works and find something useful to read

**Comment by jj0hns0n** [comment]
@jodygarnett so is your suggestion we modify the CLA to note that we will use Docusign and go ahead and set this up?

**Comment by jodygarnett** [comment]
Two questions:
- What is the point of using docusign? Does it provide an easy way to search who has sent paperwork?
- If this service costs money can I as chair of the incubation committee ask OSGeo to pay the costs

**Comment by jj0hns0n** [comment]
Yes, we can easily see who all has signed, but the biggest advantage is that its a single click to sign vs having to print/sign/scan/send. It also has an API so we can set things up to automatically send the CLA to new contributors as soon as they send a new PR.

Pricing is here. https://www.docusign.com/products-and-pricing ... not exactly sure what kind of plan would be the most effective.

Its not critical that we use it, but it sure is alot easier.

**Comment by jodygarnett** [comment]
Okay that answers my question, let me add it to the OSGeo board agenda. It would be something we could do for all projects (not just GeoNode) and this is the kind of thing the foundation is for.

The pricing is a problem for some members of our community who like everything to be "free", but I see free in terms of volunteer effort so I do not mind paying.

* individual, $10, 5 documents can be signed by others a month
* professional, $20, 10 documents can be signed by others a month, adds custom branding
* business, $30, unlimited documents can be signed by others a month

Reading the fine print we could do a weekly mail out and stay within the 5 documents a month limit.

One thing I cannot figure out from the website is if we can figure out who signed or not (which is really what we care about).

If you check this [link](https://projects.eclipse.org/user/cla/validate) you can see I signed the eclipse CLA, based on a web form individuals can use to "sign" the CLA.

**Comment by jj0hns0n** [comment]
We could always roll our own too I suppose. I'd recommend setting up a
trial account just to see how it works so you can present that to the
board. Im just +1 on anything that makes it super simple for people to sign
so there is no roadblock or excuses for people.

**Comment by jodygarnett** [comment]
Key advantage to rolling our own would be having a copy of the data searchable for admins such as yourself. 

In terms of making it easier for contributors - if I put PDFs up on the OSGeo website can contributors "add their signature" (something you can do with mac preview) and email to secretary@osgeo.org?

For GeoServer we ask contirbutors to email geoserver-devel when they have sent in their paperwork; and then we merge. That we we are not "waiting" on anything.

Can we replay this conversation on the incubation email list as several other projects would benefit.

**Comment by ingenieroariel** [comment]
I'll do one last attempt to go the github route:

If we paste the full OSGeo incubation license on a Github PR, can we
consider a comment from a github user saying 'I accept' to have the same
legal value as the signature?

When signatures are collected during elections in my country there is
usually one page with the document and many pages of signatures, I believe
in this case we can have the OsGeo approved text in the github issue
description and the signatures as comments.

-a

**Comment by jodygarnett** [comment]
It is up to your comfort level as a steering committee - if you would like
a web based solution I will do my best to make that happen. While you are
operating on behalf of the foundation - but the GeoNode committers ARE the
project - much more so than the codebase.

Two ideas:
- github page, where contributors add their contact details to the list?
This is kind of nice as contributors could edit that file as part of the
incoming pull request.
- make a webservice where contributors could add their name to a database
(this would require working through the system admin committee but would
have the advantage of helping all osgeo projects

In this case the CLA has instructions on how to email (or even mail) the
signed document so we would need to adjust this text for either of the
above ideas.

**Comment by jj0hns0n** [comment]
+1 on just doing a github issue like pycsw has done. @bitner can you take
the lead on this?

**Comment by jodygarnett** [comment]
I would recommend a page in your dev docs - we are looking for a public
confirmation after all. A github issues that cannot be closed are a bit
suspect :)
On Fri, May 6, 2016 at 1:22 PM Jeffrey Johnson <notifications@github.com>
wrote:

> +1 on just doing a github issue like pycsw has done. @bitner can you take
> the lead on this?
>
> On Sun, May 1, 2016 at 7:33 PM, Jody Garnett <notifications@github.com>
> wrote:
>
> > It is up to your comfort level as a steering committee - if you would
> like
> > a web based solution I will do my best to make that happen. While you are
> > operating on behalf of the foundation - but the GeoNode committers ARE
> the
> > project - much more so than the codebase.
> >
> > Two ideas:
> > - github page, where contributors add their contact details to the list?
> > This is kind of nice as contributors could edit that file as part of the
> > incoming pull request.
> > - make a webservice where contributors could add their name to a database
> > (this would require working through the system admin committee but would
> > have the advantage of helping all osgeo projects
> >
> > In this case the CLA has instructions on how to email (or even mail) the
> > signed document so we would need to adjust this text for either of the
> > above ideas.
> >
> > On Thu, Apr 21, 2016 at 8:42 AM Ariel Núñez <notifications@github.com>
> > wrote:
> >
> >
> > > I'll do one last attempt to go the github route:
> > >
> > > If we paste the full OSGeo incubation license on a Github PR, can we
> > > consider a comment from a github user saying 'I accept' to have the
> same
> > > legal value as the signature?
> > >
> > > When signatures are collected during elections in my country there is
> > > usually one page with the document and many pages of signatures, I
> > believe
> > > in this case we can have the OsGeo approved text in the github issue
> > > description and the signatures as comments.
> > >
> > > -a
> > >
> > > On Fri, Apr 8, 2016 at 11:53 AM, Jody Garnett <
> notifications@github.com>
> > > wrote:
> > >
> > > > Key advantage to rolling our own would be having a copy of the data
> > > > searchable for admins such as yourself.
> > > >
> > > > In terms of making it easier for contributors - if I put PDFs up on
> the
> > > > OSGeo website can contributors "add their signature" (something you
> can
> > > do
> > > > with mac preview) and email to secretary@osgeo.org?
> > > >
> > > > For GeoServer we ask contirbutors to email geoserver-devel when they
> > have
> > > > sent in their paperwork; and then we merge. That we we are not
> > "waiting"
> > > on
> > > > anything.
> > > >
> > > > Can we replay this conversation on the incubation email list as
> several
> > > > other projects would benefit.
> > > >
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> https://github.com/GeoNode/geonode/issues/2363#issuecomment-207512009
> > >
> > > >
> > >
> > > —
> > > You are receiving this because you were mentioned.
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/GeoNode/geonode/issues/2363#issuecomment-212901419
> >
> >
> > >
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/GeoNode/geonode/issues/2363#issuecomment-216094611>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2363#issuecomment-217504161>
>
-- 
--
Jody Garnett

**Comment by jj0hns0n** [comment]
A github issue is the path of least resistance ... it worked for pycsw, so
it should work for us, please lets not complicate this anymore than we need
to.

**Comment by ingenieroariel** [comment]
Jeff, I think pycsw closed that issue once they had caught up with all old
contributors. @tomkralidis what does pycsw do with contributors after that
issue was closed?

**Comment by tomkralidis** [comment]
cc @kalxas 
@ingenieroariel nothing.  It's there, and the process continues for [new contributions](https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst#contributions-and-licensing) over time. In general, the motivation was to get something in public and show effort/movement, even if not complete/100% per se.

**Comment by jj0hns0n** [comment]
@jodygarnett someone pointed me at this project. Looks like it should work
for us? https://github.com/clahub/clahub I believe I can have it email the
osgeo secretary too or at least modify it to do so. I can write to the
incubation list to discuss there if that makes sense?

**Comment by jodygarnett** [comment]
This look amazing! Please discuss on incubation list :)

**Comment by jj0hns0n** [comment]
The CLA is now implemented https://www.clahub.com/agreements/GeoNode/geonode

@bitner can you take a look and close this if ok.
