### ISSUE TITLE
Release Process Documentation

### ISSUE THREAD

**Issue by bitner** [GeoNode/geonode#2364]
One of the items requested for OSGeo incubation is a documented release process. These should just be added to the existing developer documentation.

**Comment by tomkralidis** [comment]
Example which may be helpful: https://github.com/geopython/pycsw/wiki/Release-Packaging

**Comment by jj0hns0n** [comment]
@simod @ariel I think we have some docs on this?

**Comment by jj0hns0n** [comment]
http://docs.geonode.org/en/master/tutorials/devel/release/release.html 

@bitner let us know if this is sufficient

@sarasafavi @BerryDaniel lets update this with the new release process when complete.

**Comment by bitner** [comment]
Looks good to me.
