### ISSUE TITLE
Errors were encountered while processing:  geoserver-geonode  geonode

### ISSUE THREAD

**Issue by tjessel** [GeoNode/geonode#2371]
I'm having problems installing geonode.

I'm trying to install it on Ubuntu Server; I just assumed the instructions I found here would apply:

http://geonode.org/blog/2015/11/19/geonode-2.4-released/

Perhaps my assumption was incorrect?

If not, 

Here's what I'm using:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

After executing "sudo apt-get install geonode"

Towards the end I get "dependency problems."

I think it's related to Tomcat7

Creating config file /etc/logrotate.d/tomcat7 with new version
 * Starting Tomcat servlet engine tomcat7                                   [ OK ] 
Processing triggers for ureadahead (0.100.0-16) ...
Setting up geoserver-geonode (2.7.4-2) ...
 * Stopping Tomcat servlet engine tomcat7                                   [ OK ] 
 * Starting Tomcat servlet engine tomcat7                                   [fail] 
dpkg: error processing package geoserver-geonode (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of geonode:
 geonode depends on geoserver-geonode | geoserver; however:
  Package geoserver-geonode is not configured yet.
  Package geoserver is not installed.

Any ideas on what's happening here?  

Is it Geonode just not gonna install on Ubuntu Server?

**Comment by tjessel** [comment]
I just found this, maybe I should follow along here with tomcat6? 

http://geonode-docs.readthedocs.org/en/latest/tutorials/admin/install/custom_install.html?highlight=ubuntu%20server

Another help page recommended using tomcat6 as there are apparently problems with geonode and tomcat7, but I'm not sure these instructions are applicale to an Ubuntu Server environment either:

http://geonode.readthedocs.org/en/1.0/deploy/ubuntu.html#

**Comment by simod** [comment]
Hi GeoNode should install smoothly on ubuntu server 14.04. Is the same Os we use for demo.geonode.org.

Did you install it on a new and fresh ubuntu?

ps, please use the mailing lists geonode-users@lists.osgeo.org rather than tickets to ask for support
