### ISSUE TITLE
Add a slug field in ResourceBase and use it for permalinks

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2372]
ResourceBase should have a slug field and we should then use it in urls.py for accessing layer, map and document details/metadata/... page in place of the database id.

**Comment by jj0hns0n** [comment]
@capooti do you think this will get done this week? In any case, moving to 2.7

**Comment by capooti** [comment]
@jj0hns0n I need to implement this for our instance. What is the best way to send the PR vs 2.7?

**Comment by Coop56** [comment]
Spoke with @capooti - planning to get started on this issue this week.
