### ISSUE TITLE
GNIP: GeoNode Windows Installer

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2375]
# Overview
The idea is to allow potential GeoNode users to easily and quickly evaluate the product in order to determine if it is a good solution for them and their requirements. A good solution would be the possibility to ship a self contained installer package for Windows servers, which can be easily used by the administrators or end users in order to test the GeoNode functionalities and cleanup the system afterwards.

## Proposed by
Alessio Fabiani ([GeoSolutions](http://www.geo-solutions.it))

Alessandro Parma ([GeoSolutions](http://www.geo-solutions.it))

## Assigned to release
None yet.

## Motivation
The purpose of this core development component is two-folds:
* Refactor and improve the existing Windows GeoNode installer work already done in the community to make it a point and click experience.
* Integrate the generation of the Windows installer in the automatic GeoNode build system that is powered by Jenkins.

GeoNode is a complex framework based on DJango, Python and GeoServer (hence Java). This means that an end user in order to install GeoNode itself shall install and configure several frameworks which in some cases have neither immediate nor intuitive deployment procedures which hinder the possibility of a widespread adoption for users with limited system administration skills but still highly interested in trying out its functionalities.

An hypotetical installer package should be easiest as possible to use and should allow users to avoid struggling with other packages installation and configuration. The installation package should provide a nice and user friendly interface which would guide users through questions and choices in order to help them to obtain a fair install without requiring advanced system administration skills. It should be robust and perform consistency checks on the packaged deployed in order to ensure that the system will work as espected after the installation, no matter what. Eventually, the installer package should be able to completely cleanup the target system, removing any environment variable created during the process and leave the system clean whenever the user would like to uninstall the packages; in our experience this is regularly forgotten requirement but still extremely important especially on training labs machines.

As mentioned above, while a fully enterprise installation cannot usually be performed with a simple point and click procedure (although IT Automation solutions like Puppet, Chef or Ansible are aiming to solve this problem) it is crucial to have available an Windows point-and-click installation package that can allow users without system administration skills to install and test complex solutions.

# Proposal
Here below we are going to provide technical details about the GeoNode installer we propose as outcome of this core development package.

## Technology and best practices
As mentioned above, our goal is to build a maintanable, extensible installer for the Windows platform that would make testing on prototyping on such platform a much simpler task. In order to achieve this goal, we are going to create an installer based on a scripting language technology, used and well maintained by a wide user community and rich of plugins and extensions which allow the developers to implement advanced functionalities and controls if needed.

At the time of writing the Open Source NSIS product matches all the requirements described above. Iti s very flexible, easy to learn and has a wide set of extensions allowing to build a professional installer capable of performing complex checks and operation against the Windows environment. In addition, the current prototype of a GeoNode installer is based on NSIS framework, therefore this choice wouldn’t impact the current development work already done by the community.
The most important functionalities missing on the existing GeoNode installer prototype that we are going to implement are as follows:

1. The installer is not able to detect if Python or Java are already installed on the system nor provides options to automatically install them. Therefore the user must prepare the system separately before running the GeoNode installer.

2. The quality of the wizard is not satisfactory both in terms of look and feel aswell as in terms of usability. Moreover, there is no good documentation throubleshooting providing help to end users in case of problems.

3. The installer lacks of consistency checks preventing the end user to complete a wrong and non-functional installation process, like for instance checks on the target folder existence and naming, checks on the environment variables already defined in the system, storage capability and so on. This will need to be greatly improve and requires a deep knowledge of both the Python back-end of GeoNode as well as GeoServer.

4. The installer needs improvements as far as the setup and configuration of the Python Virtualenv is concerned, like for instance verifying that the eggs are loading correctly.

The proposal is to refactor and improve all the items above and extend the installation wizard in order to follow the end user step by step during the process and preventing possible errors as much as possible other than improve the quality of the package and its usability.

## Components and configurations provided with the GeoNode installer
The proposed installer will install to the end user system roughly the following packages and configurations:

1. Java Sun JDK 7+ if not already present on the target environment. Eventually it will be asked to the user if he wants to install the package and update the “JAVA_HOME” enviroment variable.

2. Python 2.7.6+ with Virtualenv if not present on the target system.

3. Python egg packages and GeoNode dependencies into the newly configured Virtualenv.

4. GeoNode 2.4 with the default settings and embedded DB. The proposal is also to provide with the installation script a pre-configured dataset with few example maps. The same layers will be also pre-configured on the GeoServer Data Dir shipped with the installation package. In the future it is also possible to provide a set of pre-configured datasets and allow the developer to choose which one to include in the installation package through the scripting language.

5. GeoServer 2.7+ with a pre-configired small dataset in order to allow the end user to start testing the system quickly without the need of loading anything at a first glance. 

It is worth to point out that in this proposal we are not considering the support for a spatial database like PostgreSQL with PostGIS extension. However the procedure does not prevent to improve both the NSIS script and the pre-configured datasets (both GeoNode and GeoServer ones) in order to envisage also the database support and automatic setup.

Moreover the proposed installer will perform several checks and controls similar to the ones shown on the examples above. In particular the most important one will be:

1. License terms agreement; this will be a mandatory step in order to proceed with the installation procedure.

2. Choose of the installation path and disk space checks; part of this step will be also a consistency check both on the existence of the parent folder and name of the GeoNode one, which must contain printable characters without spaces.

3. Installation of the Java JVM; this step will also allow an advanced option for smarter users in order to provide their own JVM installation. Otherwise the installation procedure will install the JVM in the system before proceeding.

4. Installation of the Python environment; similar to the previous step, it will check for the existence of an already comliant Python installation and if not present it will proceed with the installation of the packaged version before proceeding.

5. Setup of the environment variables for the GeoNode and GeoServer data directories; here also an advanced option will allow a smart user to provide its own external datadir. It is worth to point out that this package does not envisage the setup and configuration of a database, therefore the target environment must contain all the necessary configuration files and packages in case there is the need for the database support. This may be considered a future installer improvement though.

6. Configuration of the Python Virtualenv, check and setup of the Python eggs.

7. Configuration and setup of a shell; may be useful to smart users in order to use Python and Django commands in a Linux fashion way.

8. Deployment of the GeoNode packages and configuration of the startup/stop scripts and links on the Windows Start Menu.

9. Configuration of the Windows registry in order to perform a subsequent correct cleanup of the system.

10. A local copy of the GeoNode and GeoServer user documentation with links to the Windows Start Menu.

## Conclusions
Among this proposal ([we](http://www.geo-solutions.it)) envisage also the following activities and technical solutions:

1. Discuss with the GeoNode community the already in place solution at https://github.com/GeoNode/geonode/tree/master/scripts/ms-install, identify issues and limitations following up the developer discussions at https://github.com/GeoNode/geonode/issues/1039, and provide evaluation upon the feasibility of the package matching all the purposes described before in this section.

2. Polish and finalize the GeoNode installer work, develop the new functionalities and provide a full user and administrator documentation along with the installer package

3. Test the installer on different environments and configurations, stay in touch and involve the community in order to wide test the installer

4. Ensure that the GeoNode build system correctly runs the installer script and is able to deploy the GeoNode executable on the distribution system

**Comment by ahmednosman** [comment]
GeoNode can be installed on windows with a windows installer. you can download the installer from www.cartologic.com/cartoview

**Comment by afabiani** [comment]
Hello, currently I cannot download the installer ... in any case we need the scripts available and integrated with the project not a precompiled binary.

**Comment by afabiani** [comment]
Few updates on this thred.

The source code and instruction to build the GeoNode Windows Installer are here

https://github.com/GeoNode/geonode-win-installer.git

While the binary executable can be found here:

https://www.dropbox.com/s/ujclwt7mtu5zy87/GeoNode-2.4.exe?dl=0

**Comment by ahmednosman** [comment]
excellent, we are using a different approach, I think it is better to talk and share the code,

**Comment by afabiani** [comment]
Sure

==
GeoServer Professional Services from the experts! Visit
http://goo.gl/NWWaa2 for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39  331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

**Comment by ahmednosman** [comment]
sent you email, downloading, will be testing shortly

**Comment by afabiani** [comment]
geonode.github.com for Windows Installer PR here:

- https://github.com/GeoNode/geonode.github.com/pull/33

GeoNode Windows Installer documentation PR here:

- https://github.com/GeoNode/geonode/pull/2418

**Comment by jj0hns0n** [comment]
@afabiani can we go ahead and close this one now?

**Comment by afabiani** [comment]
Hello Jeffrey,
yes we can close this.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------
