### ISSUE TITLE
Would like a higher-resolution GeoNode logo displayed on http://geonode.org/

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2379]
The current logo is 138 X 35 pixels, it is not high-resolution and it does not scale well:

![geonode-logo-zoomed-in](https://cloud.githubusercontent.com/assets/2665840/11596320/7a0e2b02-9a82-11e5-99c2-5b5433ffa370.PNG)

Can we either:
1. get a higher resolution image up 

or 
1. Get a higher resolution flower logo and have the text part be actual html text that can scale well.

Thanks,

Tom

**Comment by jj0hns0n** [comment]
@gsolat can you update this?
