### ISSUE TITLE
Diagram on components of GeoNode

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2382]
Where can I get a diagram on components of GeoNode?

I am looking here:  http://docs.geonode.org/en/latest/reference/index.html

and I can't find any. I'm wondering how GeoNode fits in with PostGiS and GeoServer. It seems like whenever someone uploads data for instance, GeoNode/GeoDjango writes the data to the PostGIS database. 

Then it seems that PostGIS is connected to GeoServer.

Does it gets served through GeoServer, from which GeoNode/GeoDjango pulls from again? 

Or does GeoNode/GeoDjango pull straight from the PostGIS database; and use GeoServer only for serving additional OGC services?

**Comment by tomkralidis** [comment]
@d3netxer this question is best asked on one of the [communication](http://geonode.org/communication/#mailing-lists) channels identified.

**Comment by garnertb** [comment]
This may help: http://docs.geonode.org/en/2.0/reference/architecture.html.

Closing.
