### ISSUE TITLE
manage layer style

### ISSUE THREAD

**Issue by frippe12573** [GeoNode/geonode#2386]
I have running geonode version 2.4.dev20151029170512 (on ubuntu 14.04). 
Once I uploaded 3 raster (geotiff) file I worked on the styles directly on geoserver creating an sld file for all the three file.
I assigned the style in the layer configuration of geoserver, then on geonode I checked the layer proprieties regarding the style of each one of the three file.
Clicking on 'edit layer', manage style I got this error page:
 UnboundLocalError at /gs/geonode:io_fav_recl/style/manage

local variable 'title_node' referenced before assignment

Request Method:     GET
Request URL:    http://my_IP_server/gs/geonode:io_fav_recl/style/manage
Django Version:     1.6.11
Exception Type:     UnboundLocalError
Exception Value:    

local variable 'title_node' referenced before assignment

Exception Location:     /usr/local/lib/python2.7/dist-packages/geoserver/style.py in sld_title, line 83
Python Executable:  /usr/bin/python
Python Version:     2.7.6
Python Path:    

['/dati/.venvs/geonode/lib/python2.7/site-packages',
 '/dati/geonode',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',

In apache error.log I got:
[Mon Dec 14 03:40:24.003054 2015] [:error] [pid 10308:tid 139718742730496] Internal Server Error: /gs/geonode:fav_finale/style/manage
[Mon Dec 14 03:40:24.003085 2015] [:error] [pid 10308:tid 139718742730496] Traceback (most recent call last):
[Mon Dec 14 03:40:24.003092 2015] [:error] [pid 10308:tid 139718742730496]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
[Mon Dec 14 03:40:24.003097 2015] [:error] [pid 10308:tid 139718742730496]     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
[Mon Dec 14 03:40:24.003102 2015] [:error] [pid 10308:tid 139718742730496]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Dec 14 03:40:24.003107 2015] [:error] [pid 10308:tid 139718742730496]     return view_func(request, _args, *_kwargs)
[Mon Dec 14 03:40:24.003112 2015] [:error] [pid 10308:tid 139718742730496]   File "/dati/geonode/geonode/geoserver/views.py", line 177, in layer_style_manage
[Mon Dec 14 03:40:24.003117 2015] [:error] [pid 10308:tid 139718742730496]     gs_styles.append((style.name, style.sld_title))
[Mon Dec 14 03:40:24.003122 2015] [:error] [pid 10308:tid 139718742730496]   File "/usr/local/lib/python2.7/dist-packages/geoserver/style.py", line 83, in sld_title
[Mon Dec 14 03:40:24.003127 2015] [:error] [pid 10308:tid 139718742730496]     return title_node.text if title_node is not None else None
[Mon Dec 14 03:40:24.003132 2015] [:error] [pid 10308:tid 139718742730496] UnboundLocalError: local variable 'title_node' referenced before assignment
[Mon Dec 14 03:40:58.288286 2015] [:error] [pid 10308:tid 139718725945088] Internal Server Error: /gs/geonode:zone_urbanizzate/style/manage
[Mon Dec 14 03:40:58.288328 2015] [:error] [pid 10308:tid 139718725945088] Traceback (most recent call last):
[Mon Dec 14 03:40:58.288335 2015] [:error] [pid 10308:tid 139718725945088]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
[Mon Dec 14 03:40:58.288340 2015] [:error] [pid 10308:tid 139718725945088]     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
[Mon Dec 14 03:40:58.288345 2015] [:error] [pid 10308:tid 139718725945088]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Dec 14 03:40:58.288351 2015] [:error] [pid 10308:tid 139718725945088]     return view_func(request, _args, *_kwargs)
[Mon Dec 14 03:40:58.288356 2015] [:error] [pid 10308:tid 139718725945088]   File "/dati/geonode/geonode/geoserver/views.py", line 177, in layer_style_manage
[Mon Dec 14 03:40:58.288361 2015] [:error] [pid 10308:tid 139718725945088]     gs_styles.append((style.name, style.sld_title))
[Mon Dec 14 03:40:58.288366 2015] [:error] [pid 10308:tid 139718725945088]   File "/usr/local/lib/python2.7/dist-packages/geoserver/style.py", line 83, in sld_title
[Mon Dec 14 03:40:58.288371 2015] [:error] [pid 10308:tid 139718725945088]     return title_node.text if title_node is not None else None
[Mon Dec 14 03:40:58.288376 2015] [:error] [pid 10308:tid 139718725945088] UnboundLocalError: local variable 'title_node' referenced before assignment
[Mon Dec 14 03:41:08.718339 2015] [:error] [pid 10308:tid 139718742730496] Internal Server Error: /gs/geonode:zone_urbanizzate/style/manage
[Mon Dec 14 03:41:08.718380 2015] [:error] [pid 10308:tid 139718742730496] Traceback (most recent call last):
[Mon Dec 14 03:41:08.718386 2015] [:error] [pid 10308:tid 139718742730496]   File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 112, in get_response
[Mon Dec 14 03:41:08.718392 2015] [:error] [pid 10308:tid 139718742730496]     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
[Mon Dec 14 03:41:08.718411 2015] [:error] [pid 10308:tid 139718742730496]   File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Mon Dec 14 03:41:08.718417 2015] [:error] [pid 10308:tid 139718742730496]     return view_func(request, _args, *_kwargs)

Is that a bug or whatever? Is there any workaround or solution?

Eugenio

**Comment by simod** [comment]
This could potentially be a bug of gsconfig. Here the line https://github.com/boundlessgeo/gsconfig/blob/master/src/geoserver/style.py#L83. Not sure in what case user_style is None in both cases, but if None then gsconfig shouldn't check for title_node.text. @ingenieroariel @afabiani comments?

**Comment by afabiani** [comment]
The issue is that the style automatically generated does not contain the title, which is mandatory.

Maybe this should be better handled on GeoServer side.

**Comment by jj0hns0n** [comment]
@afabiani can we look at this during the sprint?

**Comment by afabiani** [comment]
Yes, you are right. It can be possible that the UserStyle can't be
recognized at all. In that case gsconfig should not try to check for
title_node.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by jj0hns0n** [comment]
Ok, can we open an issue in gsconfig for this? Should I move to 2.7 or can we fix it soon?

**Comment by afabiani** [comment]
It is easy to fix. We can do this soon

**Comment by afabiani** [comment]
Please take a look at PR

https://github.com/boundlessgeo/gsconfig/pull/158

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------
