### ISSUE TITLE
Missing keywords on metadata upload preserve

### ISSUE THREAD

**Issue by pmdias** [GeoNode/geonode#2388]
I'm trying to upload some layers using the 'metadata preserve xml' option, but some keywords are not stored by geonode. For example, I have a xml with the keywords:

```xml
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>Elevation</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="theme">
        theme
      </gmd:MD_KeywordTypeCode>
    </gmd:type>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
<gmd:descriptiveKeywords>
  <gmd:MD_Keywords>
    <gmd:keyword>
      <gco:CharacterString>Meteorology</gco:CharacterString>
    </gmd:keyword>
    <gmd:type>
      <gmd:MD_KeywordTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_KeywordTypeCode" codeListValue="discipline">
        discipline
      </gmd:MD_KeywordTypeCode>
    </gmd:type>
  </gmd:MD_Keywords>
</gmd:descriptiveKeywords>
```
Only the first keyword, the one with the type 'theme', is being stored. Keywords with other valid types, like discipline, temporal or stratum, are ignored.

I believe I've traced this behaviour to [geonode/layers/metadata.py#L102](https://github.com/GeoNode/geonode/blob/master/geonode/layers/metadata.py#L102)
```python
if (hasattr(mdata.identification, 'keywords') and
        len(mdata.identification.keywords) > 0):
    for kw in mdata.identification.keywords:
        if kw['type'] == "theme":
            keywords.extend(kw['keywords'])
        elif kw['type'] == "place":
            regions.extend(kw['keywords'])
```
where other types are ignored but I can't understand the reason why only keywords of type 'theme' and 'place' are accepted, otherwise I'd change this myself and submit the PR.

**Comment by tomkralidis** [comment]
@pmdias I think the logic is there so as to route the correct keyword types to the appropriates places in the model, as part of spatial keyword support.  Looking at http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml#MD_KeywordTypeCode, the following keyword types are listed:

- place
- stratum
- discipline
- temporal
- place

I propose we allow our `keywords` field to accept keywords from theme, discipline, or stratum.  Updated snippet:

```python
if (hasattr(mdata.identification, 'keywords') and
        len(mdata.identification.keywords) > 0):
    for kw in mdata.identification.keywords:
        if kw['type'] in ["discipline", "stratum", "theme"]:
            keywords.extend(kw['keywords'])
        elif kw['type'] == "place":
            regions.extend(kw['keywords'])
```
Does this work for you?

**Comment by pmdias** [comment]
@tomkralidis would be interesting if Geonode could also support the extensions for the MD_KeywordTypeCode that appeared with the ISO 19115-1:2014 revision (soon to be the new standard). Also, NOAA and NASA also created an extension for the keyword types that added new types. Some of the new types, which we are using, are:

* instrument
* platform
* project
* process

I also noticed you left out the `temporal`. Any reason for this?

The only way I'm seeing of supporting all this would be:
```python
if (hasattr(mdata.identification, 'keywords') and
        len(mdata.identification.keywords) > 0):
    for kw in mdata.identification.keywords:
        if kw['type'] == 'place':
            regions.extend(kw['keywords'])
        else:
            keywords.extend(kw['keywords'])
```
And we could add `elif`'s as required to better manage where the actual keywords are going inside Geonode.

**Comment by tomkralidis** [comment]
@pmdias 19115-1:2014 is a whole other Python implementation in OWSLib IMHO :)

Having said this, yes your latest snippet would be the most inclusive keyword processing workflow.

**Comment by pmdias** [comment]
@tomkralidis I agree with you but it's coming and, sooner or later, we will have to deal with it :). Anyway, I'm submitting the PR with the changes proposed and if it's OK, I'll close the issue.
