### ISSUE TITLE
Geoserver dependencies need to be documented

### ISSUE THREAD

**Issue by kmmbvnr** [GeoNode/geonode#2407]
It seems that geonode uses geoserver-ext/printng module to get layer thumbnails

https://github.com/GeoNode/geonode/commit/b64467b08b9d0f0445e9743c78d1a4727e70e764#diff-c0e1c8cea0b01d04a691f88381580c4fR1531

But there is no points on documention how to get and install `printng` module

**Comment by simod** [comment]
Hi, geonode provides a customised version of geoserver that has all the needed dependencies

**Comment by kmmbvnr** [comment]
thanks )
