### ISSUE TITLE
Map settings are not used when creating a map from a layer

### ISSUE THREAD

**Issue by benhowell** [GeoNode/geonode#2410]
Map settings as [described here](https://github.com/GeoNode/geonode/blob/8c22dc8c30204a42b1ff2d3c29736719c106d343/docs/reference/developers/settings.txt) are not used when creating a map from an existing layer. The settings are used if creating a new map from the "Maps" page.

Screens
-----------
Settings are not applied when created via:
![tiny-geo-offline-issue1](https://cloud.githubusercontent.com/assets/1784519/12604934/44309846-c514-11e5-9128-dd7cf26b4475.png)

Settings are applied when created via:
![tiny-geo-offline-issue2](https://cloud.githubusercontent.com/assets/1784519/12604964/69b6eca0-c514-11e5-9829-bd72d8c9565b.png)

The settings I'm using in particular (in local_settings.py):
DEFAULT_MAP_CENTER
DEFAULT_MAP_BASE_LAYER
DEFAULT_MAP_ZOOM

**Comment by simod** [comment]
Hi, 
not sure this is a bug. in the screenshots I see a layer list page with one layer and a map list page with no maps. The layers don't use any map settings. When creating a map from a layer then there are no defaults anymore since the layer sets them.

**Comment by benhowell** [comment]
The screenshots are just to demonstrate the two different paths to create a map (the first being from the "Create a map" link in the first screenshot, the second being from "Create a new map" button in the second. They both achieve the same thing ultimately, with the exception that the first starts with a pre-selected layer. The behaviour is inconsistent. If this is the way it is supposed to work then it's a bit confusing.

**Comment by simod** [comment]
I don't see inconsistency, a default map is an empty map. When you add a layer is not a default map anymore but it has a bounding box, a zoom and a content. I would expect that if I initialized a map with a layer that map is zoomed and centred on that layer.

**Comment by benhowell** [comment]
ok
