### ISSUE TITLE
geonode can't pick up layers within geoserver

### ISSUE THREAD

**Issue by manaetches** [GeoNode/geonode#2411]
Hi,

This situation is this:

I migrated data from geonode 2.0 to 2.4, this involved a migration method found at https://github.com/capooti/geonode/blob/migration_from20_to_24/scripts/migrations/migrate20to24/index.rst. This included migration of postgresql database to main geonode 2.4 database and migration of raw data into geoserver directory. The geoserver directory paths I migrated to within directory /usr/share/geoserver/data:
2.0                                                              2.4
workspaces/geonode/              to             /workspaces/geonode/datastore/
data/default/                             to              /data/geonode/(layers contents)
also
copied layers                         to             /var/www/geonode/uploaded/layers/

Now the issue I have is when I run 'geonode updatelayers', I get:
Finished processing 0 layers in 0.0 seconds.

0 Created layers
0 Updated layers
0 Failed layers
0.000000 seconds per layer

Any help to this would be awesome.

**Comment by capooti** [comment]
Please use the mailing list to ask this kind of questions.
Anyway, can you successfully access to the GeoNode interface?

**Comment by manaetches** [comment]
Sorry for not using the email list,

Yes I can access the geonode interface without a problem. I can also access the geoserver interface without a problem. My layers, stores and directories appear in geoserver but I still cannot sync the data. I also looked at the 'geonode_data' database within postgres, but there are no layers. So it seems, I might have a postgres database connection issue. I checked the connections in 'local_settings.py', they look fine, and the datastore being used is fine.

Looking forward to any help if you can

**Comment by tomkralidis** [comment]
Please use the GeoNode mailing list for questions.

**Comment by manaetches** [comment]
Hi all,

Im attempting to use migrate my 2.0 to 2.4 following this method,
https://github.com/capooti/geonode/blob/migration_from20_to_24/scripts/migrations/migrate20to24/index.rst
.

My guest linux 14.04 OS is running within VMWorkstation.

I installed geonode 2.4 following the installation instructions here
<http://geonode.org/blog/2015/11/19/geonode-2.4-released/>..I then restored
my backup file in old_database using postgres->psql commands. I then
proceeded with the following:


   - ran ./migrate.sh -> this is successful because geonode database is
   populated.
   - I migrated the geoserver data directories as follows:
      - data->default  to  geoserver data directory
      - workspaces->geonode to  workspaces->geonode->datastore
      - gwc-layers     to     gwc-layers
      - I also populated /var/www/geonode/uploaded/layers directory with my
      layers (including geotiffs and .shp ...etc).
   - Finally a ran ./migrate2.sh

As a result, *I get a 500 Internal Server on my host machine*. My host IP
address is included with ALLOWED_HOSTS array of local_settings.py

and

*My datastore, namely geonode_data in postgres, is not populated with my
layers.*

Any help on this would be much appreciated,

Where did I go wrong?

See below a copy of 'my gn_migration.cfg':

[db20]
dbname = old_db
host = 192.168.137.5
user = geonode
password = secret

[db24]
dbname = geonode
host = 192.168.137.5
user = geonode
password = secret

[path]
geonode_path = /usr/local/lib/python2.7/dist-packages/geonode
settings_path = geonode.settings

Note: I replaced password with an arbiturary string.





Many thanks.
