### ISSUE TITLE
Geonode's homepage does not count 'wmsStore' as a 'countable-geonode' layer

### ISSUE THREAD

**Issue by dalda** [GeoNode/geonode#2412]
Geonode's homepage counts consider 'coverageStore', 'dataStore', 'remoteStore' but it doesn't count 'wmsStore' (cascaded WMS for example). According to the developer's team it should,

**Comment by jj0hns0n** [comment]
I also noticed this on another geonode recently.

**Comment by capooti** [comment]
If I remember correctly, all of the remote services (WMS/ESRI/whatever) are
registered as remoteStore.
What you want to get should be easily accomplished with some customization.

On Fri, Jan 29, 2016 at 7:03 AM, Jeffrey Johnson <notifications@github.com>
wrote:

> I also noticed this on another geonode recently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2412#issuecomment-176721893>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by jj0hns0n** [comment]
I think the issue may be when you configure a remote WMS store yourself
through GeoServer and do updatelayers vs adding them as a remote service
layer through geonode. We should include wmsStore in the count I think.

**Comment by dalda** [comment]
I've just added a pull request about this issue.

**Comment by capooti** [comment]
Ah ok, thanks Jeff
Dalda, could you squash your commits and resend the PR?
thanks
p

On Thu, Feb 4, 2016 at 2:45 AM, dalda <notifications@github.com> wrote:

> I've just added a pull request about this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/2412#issuecomment-179694440>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by dalda** [comment]
Hi, sure! But I'm quite a newbie in Github and don't really know how to squash my commits...

**Comment by jj0hns0n** [comment]
I just went ahead and merged this ... but for future reference
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
