### ISSUE TITLE
Installation directions

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2413]
On http://geonode.org/ in the installation steps I see:
1. Set the IP address and create a superuser

$ sudo geonode-updateip 127.0.0.1

$ geonode createsuperuser

When I did the updateip command the console returned:

geonode.GeoNodeException: You must have an admin account configured before importing data. Try: django-admin.py createsuperuser

so I created a superuser then ran the updateip and it worked.

Maybe then we can update the instructions to create a superuser before updating the ip?

**Comment by jj0hns0n** [comment]
@d3netxer can you issue a PR to update this in the docs?
