### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by MekuHila** [GeoNode/geonode#2416]
Hello Dear
we need some help around deployment. me and my
friends customize geonode as we want but we don't have any idea how
to host the project in another server(different from development server). any steps or recommendations, Thank You

**Comment by capooti** [comment]
@MekuHila an Issue Tracker like this one where you filed a ticket is intended to report bug about software. For general question and help request like yours, please use the dedicated mailing lists.
https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users
