### ISSUE TITLE
AuthenticationServiceException: Communication with GeoNode failed

### ISSUE THREAD

**Issue by kssalanio** [GeoNode/geonode#2419]
I encounter an authentication error when I'm logged in using an admin account in GeoNode. When I visit the GeoServer website, no user is authenticated. It states that it was caused by a SocketTimeoutException. For regular GeoNode users, this problem does not occur, they authenticate as intended.  Here is the [error log from geoserver.log](http://pastebin.com/dyUW1Fjk).

**Comment by simod** [comment]
Hi, seems that geoserver cannot reach geonode for authenticate. Check the location of geonode in your geoserver data dire/security/auth/geonodeAuthProvider/config.xml. Then restart tomcat.

For further assistance please use the mailing lists, this is only for bugs.

**Comment by kssalanio** [comment]
Umm, sorry to follow this up, but geoserver can contact geonode in my setup. The regular users can authenticate just fine. Also, if it cannot contact geonode, geoserver will log a java.net.UnknownHostException instead of a SocketTimeoutException. Only the admin users of geonode encounter this error. I've already edited dire/security/auth/geonodeAuthProvider/config.xml with the proper URL and tested it on setup, but after uploading the layers, this problem occurs. I've also tried the mailing list before and no one seems to have encountered this problem so far.

**Comment by simod** [comment]
Ah I see. Then probably is an issue of performances of geoserver. Try to increase the JVM memory and optimize it as much as possible. For sure @afabiani can tell you more.

**Comment by afabiani** [comment]
How many layers you have configured on your GeoNode?

When logging as Admin User, with the current authentication mecanism, GeoNode sends to GeoServer the whole list of available layers. If too long a read timeout may occur.

A possible workaround would be to try increasing the timeouts on Apache proxies (if any).

**Comment by kssalanio** [comment]
It does make sense since I'm working with about 900+ layers. I will do as advised and find a timeout setting on Apache proxies I can find. Thank you very much!
