### ISSUE TITLE
investigate removing distribution_url and distribution_description from ResourceBase

### ISSUE THREAD

**Issue by tomkralidis** [GeoNode/geonode#2422]
As per http://lists.osgeo.org/pipermail/geonode-devel/2016-February/000752.html, these fields are duplicative at best given `geonode.base.models.Link`, and we don't really use them anywhere downstream.  Propose to remove.

**Comment by capooti** [comment]
+1

**Comment by ingenieroariel** [comment]
+1 on removing them while adding the corresponding Link by default
