### ISSUE TITLE
Missing pages on geonode.org website

### ISSUE THREAD

**Issue by cwgrant** [GeoNode/geonode#2425]
There are a number of bad links/404s on the geonode.org web site:

http://geonode.org/user_features.html
http://geonode.org/dev_features.html
http://geonode.org/admin_features.html
http://geonode.org/faqs.html

**Comment by jj0hns0n** [comment]
@cwgrant these should be fixed, can you verify and close? (not they are all without the .html now)

**Comment by cwgrant** [comment]
Looks good
