### ISSUE TITLE
Map's Center Value Forced to Web Mercator

### ISSUE THREAD

**Issue by darinacosta** [GeoNode/geonode#2432]
If a map contains a layer with a bounding box, the map's center value is forced to Web Mercator, regardless of the DEFAULT_MAP_CRS value in settings.py:

https://github.com/GeoNode/geonode/blob/master/geonode/maps/views.py#L540

**Comment by abersh** [comment]
when I upload layers on GeoNode 2.8 production it doesn't display the layer on center even I changed the DEFAULT_MAP_CENTER=(37,8) it doesn't work. please help anyone
