### ISSUE TITLE
clarify licence on key entry points

### ISSUE THREAD

**Issue by rob-metalinkage** [GeoNode/geonode#2435]
The Geonode licence still claims to be GPL from OpenPlans on the readme at github.

The getting started page at "http://docs.geonode.org/en/latest/about.html" is silent on this issue.

this is obviously related to https://github.com/GeoNode/geonode/issues/2366 - but a clear message to potential users is a further requirement.

**Comment by jj0hns0n** [comment]
We should update the copyright to show its now owned by OSGeo. @rob-metalinkage can you send a PR to update the docs where you indicate?
