### ISSUE TITLE
Swap Terria.js for current/broken Google Earth 3d viewer

### ISSUE THREAD

**Issue by JJediny** [GeoNode/geonode#2436]
http://terria.io is being used as a data previewer for CKAN using a appended WMS request to remote or localhost map client. Which would seem to be a simple/practical fix for the forever broken Google Earth viewer - atleast for Layer view (possibility Map preview if one mapped the json) for the cost of deploying a simple node application:
[Example](http://catalogue.beta.data.wa.gov.au/dataset/planning-units/resource/32b1593b-8495-30a3-82a3-ca49f1415625)
[Source](https://github.com/JJediny/ckanext-cesiumpreview)

better than broken

![screenshot_2016-02-24_01-38-17](https://cloud.githubusercontent.com/assets/6350035/13277514/8236cf00-da97-11e5-995e-8a6526eec01b.png)

**Comment by jj0hns0n** [comment]
We should probably just remove the Google Earth plugin from GeoExplorer for now. @bartvde can you help with this? Not sure how easy it is to switch to terria.js or cesium.

**Comment by bartvde** [comment]
taking it out should be easy, replacing it with something else is non trivial and probably not worth the effort

**Comment by jj0hns0n** [comment]
+1 to remove it in the next geoexplorer build. Can you help with this at
foss4g?
