### ISSUE TITLE
All 3 Take the tour buttons on http://geonode.org/ give me a 404 response

### ISSUE THREAD

**Issue by PeterC66** [GeoNode/geonode#2441]
This is probably not the right place, but I am not sure how else to tell anyone this.  I am a layman just looking for a geo system and finding 404s on your main site has been a little disconcerting. I was especially wanting to see the developer tour at http://geonode.org/dev_features.html.

**Comment by simod** [comment]
@PeterC66 thanks for reporting. Could you tell us how you landed on this page? As from the geonode.org home page the link is http://geonode.org/dev_features/.

**Comment by PeterC66** [comment]
I went to http://geonode.org/ (see screenshot attached) and then clicked on the three Take the Tour buttons:
  a.. For Users Take the Tour took me to http://geonode.org/user_features.html  (NOTE the .html at the end) 
  b.. For Developers Take the Tour took me to http://geonode.org/dev_features.html 
  c.. and For Admins Take the Tour took me to http://geonode.org/admin_features.html
and all these give me 404 (eg see screenshot attached).

I see that you are referring to the link to http://geonode.org/dev_features/ in the drop down at the top. This has no .html at the end.

Also I must admit I had not noticed that drop down until I looked at the source to see what you were referring to! I did wonder why there were so few links on the website – and I have looked at it on and off for 6 months to find better information with no success until today. Maybe the drop down could be made more obvious?
- 
By the way I have found on http://demo.geonode.org/ there is a footer Powered by GeoNode version 2.4 | Developers | About and the “Developers” link is to http://demo.geonode.org/developer/ – which gets there OK , but is different in content.

Best wishes
Peter

**Comment by PeterC66** [comment]
By the way while I am commenting and you might be changing the webpage, I also noticed the three rectangles at the bottom right of each webpage, and realised they are missing their GitHub/Twitter/G+  pngs – at least when I view them (see attached screenshot).

Peter
