### ISSUE TITLE
Imported SLD styles are named "None" in GeoNode style manager

### ISSUE THREAD

**Issue by ghost** [GeoNode/geonode#2448]
When uploading a .sld file with a shapefile, it is automatically named "None" when you try to get it via the style manager. 

If you select a "None" style and then update the available styles, it shows correctly in the Modify style window.

**Comment by amefad** [comment]
Dont' know if it's a problem: It happens also with styles created in geoserver and imported using geonode updatelayers command, seems that geonode needs the tag  <UserStyle><Title> to name the style, i think it's better explain this in the user manual than modify the .sld without notitying. 
Maybe GN could use the tag <Name> as a fallback when <title> is not found.
