### ISSUE TITLE
Upgrade django-autocomplete-light (DAL) to latest version

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#2451]
https://django-autocomplete-light.readthedocs.org/en/master/
Needed to support genericForeignKey in relation to the Documents app.
Its trickier than it seems. Some changes are not backwards compatible.

**Comment by pjdufour** [comment]
This is hard.  Documentation on upgrading is not great and factory functions have been removed.  Happy to take suggestions on maintaining DRY.  Might need to wait a few more months until broader adoption by open source community of version 3.x.

Working on it https://github.com/pjdufour/geonode/commits/dal-3.1.5

**Comment by jj0hns0n** [comment]
@karakostis @pjdufour whats the status on this?

**Comment by rob-metalinkage** [comment]
was looking at status - so just noting its still pinned to 2.3.3 in
https://github.com/GeoNode/geonode/blob/master/requirements.txt

Is this effort given up, on the backburner, superceded?

**Comment by afabiani** [comment]
With the upgrade of Django we should get rid of DAL at all imho

**Comment by rob-metalinkage** [comment]
Yep - seems to be built into 2.0 - is there a planned timescale for that?
