### ISSUE TITLE
Manifest.in Review

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2452]
On a downstream GeoNode project, when we install geonode as a python dependency it doesn't include the static files.  This might be due to the Manifest.in file (https://github.com/GeoNode/geonode/blob/master/MANIFEST.in).  Our current version only includes:

```
recursive-exclude ./geonode/static/.components
```

On other python projects, I've had to add `recursive-include` lines to pick up the static files.

```
include README.*
include LICENSE
include setup.py
include setup.cfg
global-exclude *.pyc
global-exclude *.pyo
recursive-include foo/static *
recursive-include foo/templates *
```

To workaround this current limitation, we create a clone of geonode locally and pip install as editabled (`-e`).

It's possible it's a system-related issues, but the Manifest.in was last edited in 2013 by @jj0hns0n, so it might be time to take a fresh look at Manifest.in.

Could have indirect consequences, so we should be careful whatever we do.

**Comment by simod** [comment]
@pjdufour thanks for reporting, it is strange indeed. I would expect it to be more a setup.py configuration rather than a Manifest. Like we should add "include_package_data=True," to setup.py.

I have a geonode update and 2.4.1 release....some time in the near future..... let's flag it for it.
