### ISSUE TITLE
Pavement/Devops Logging

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2454]
We should have a more unified logging framework for pavement, instead of ad-hoc print statements.  Maybe use just the basic `logging` module or align with the logging methodology in the GeoNode code base.

https://docs.python.org/2/howto/logging.html

**Comment by jj0hns0n** [comment]
@pjdufour I think we plan to bail on pavement in favor of a docker setup. but moving to 2.7 for now. @ingenieroariel let us know your thoughts here.

**Comment by jj0hns0n** [comment]
ref #2593
