### ISSUE TITLE
Problems to set BING_API_KEY in Geoexplorer.js file

### ISSUE THREAD

**Issue by davicustodio** [GeoNode/geonode#2456]
I have a BING_API_KEY defined in local_settings.py file. By accessing any Geonode layer the base maps work properly. But when accessing a GeoNode map appear problems with Zoom. I opened Geoexplorer.js file and realized that the key that was set there was not the same as set in local_settings.py file. I execute the command "geonode collectstatic" and Geoexplorer.js was recreated, but again with a different key that defined in local_settings.py.
I had to change the key directly in Geoexplorer.js to solve the problem.

**Comment by jj0hns0n** [comment]
@BerryDaniel how does this work now with the new work on baselayers?

**Comment by simod** [comment]
This should be fixed right?

**Comment by BerryDaniel** [comment]
Let me check
