### ISSUE TITLE
Bug found in file pavement.py

### ISSUE THREAD

**Issue by meisenha** [GeoNode/geonode#2459]
In the file pavement.py there is a dead link. It is the link to py2exe.

That means that the command "paver  win_install_deps" raises an error
(no connection could be made because the target machine actively refused it).

Can anyone fix it ? Thank you very much.

Dead link: 
http://superb-dca2.dl.sourceforge.net/project/py2exe/py2exe/0.6.9/py2exe-0.6.9.win32-py2.7.exe

There is a new link for py2exe: 
http://downloads.sourceforge.net/project/py2exe/py2exe/0.6.9/py2exe-0.6.9.win32-py2.7.exe

I changed it on my local copy of the souce code.

**Comment by capooti** [comment]
thanks for reporting.
