### ISSUE TITLE
Replace Layer may fail when connected to PostGIS

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2462]
Currently there is the possibility that the Replace Layer functionality (but also delete and create the same layer again) may fail when GeoServer uses a PostGIS datastore.

This is caused by the fact that there is no way via REST (at this time at least) to delete a Layer and a Schema remotely. Therefore GeoNode deletes the tables and the removes the Layer from GeoServer catalog.

The GeoServer JDBC Driver has a cache storing the active FeatureTypes. Therefore removing the tables on DB without cleaning the cache may cause errors on GeoServer JDBCStore trying to access a table without re-creating it.

The short-term workaround is to add a "force reload" statement to the GeoNode update_layer method

geonode/geoserver/helpers.py
 (def geoserver_upload)[1051] -> cat.reload()

The optimal solution would be to add to GeoServer the REST endpoint to delete Layer and Schema (this is possible now with the new GeoTools APIs).

**Comment by jj0hns0n** [comment]
@afabiani can we discuss this one during the sprint. Not sure if it is 'critical' but wonder if we should try to fix it before 2.5/2.6

**Comment by afabiani** [comment]
Mmm, maybe this is already fixed? I remember a discussion with Simone
Dalmasso, but I may be wrong. However yes, lets discuss this during the
sprint.

Best Regards,
Alessio Fabiani.

==
GeoServer Professional Services from the experts!
Visit http://goo.gl/it488V for more information.
==

Ing. Alessio Fabiani
@alfa7691
Founder/Technical Lead

GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

*AVVERTENZE AI SENSI DEL D.Lgs. 196/2003*

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.



The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

---------------------------------------------------------------------

**Comment by jj0hns0n** [comment]
@afabiani this does look fixed. Im going to close it, if we see this behavior again we can re-open.

**Comment by blackgis** [comment]
This issue is unfortunately not fixed, leave it open.

**Comment by blackgis** [comment]
@afabiani Where should I exactly add this reload function in the helpers.py?

**Comment by jondoig** [comment]
I tried this fix on my Geonode 2.4 and it broke the upload with "Unexpected exception No JSON object could be decoded" on the browser and 'No handlers could be found for logger "gsuploader"' (nearby) in the Apache log.
