### ISSUE TITLE
haystack api code is not working

### ISSUE THREAD

**Issue by simod** [GeoNode/geonode#2464]
the faceting breaks the search query set. Need to fix it for the next release
https://github.com/GeoNode/geonode/blob/master/geonode/api/resourcebase_api.py#L329

**Comment by pjdufour** [comment]
Sorry if I should no this, but what is haystack used for?  If it is just inactive code, maybe we should just remove it?

**Comment by simod** [comment]
Haystack is for searching using a full text engine like ElasticSearch or Solr. It is used in many donwstream project and for the future we should use it more. We will refactor it but I think it should stay.

**Comment by sarasafavi** [comment]
Unable to self-assign; working this in conjunction with https://github.com/GeoNode/geonode/issues/2555

**Comment by jj0hns0n** [comment]
@simod @sarasafavi what is the status on this one?

**Comment by sarasafavi** [comment]
@jj0hns0n this is still open; it did not turn out to be related to #2555 after all. I'll amend my previous comment!

**Comment by harts-boundless** [comment]
I also hope that GeoNode will retain a fulltext-enabled search API that can use ElasticSearch, because this will greatly help us in our desire to contribute some currently funded work on Exchange's search interface as an optional addon for GeoNode.

**Comment by jj0hns0n** [comment]
As far as I know this is back to working. But @simod and I looked over this
in Bonn and it could use some serious refactoring again. Lets put this on
the agenda for Rome for sure.
