### ISSUE TITLE
Reconsider behavior of layer_replace function

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#2466]
The replace_layer function uses the cascading_delete function, which deletes the table from DB, the layers and styles from Geoserver and the Permissions. Consequently the replaced layer does't use the previously assigned styling. Perhaps this behavior should be reconsidered.

A hack would be to check if the layer already exists (or the table), delete the content and insert the new one (using ogr2ogr and psycopg2). 

The cascading_delete() can be commented in this case.

**Comment by vdeparday** [comment]
+1 from a user prospective

**Comment by pjdufour** [comment]
+1 from a workflow perspective.  I'd rather "regress" and remove support for schema changes.  Dealing with geoserver-integration for styling changes is too difficult at the moment.  If it's schema changes vs. consistent styles, I think consistent styles is more important.

**Comment by capooti** [comment]
I think we should include a boolean parameter (for example is_replace_layer) in geoserver.helpers.cascading_delete, and execute this code only if it is false:
https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L276

Then we can reassign the styles to the layer reading on the django database in layers.views.layer_replace after the call to cascading_delete. Another approach could be to keep actual code in cascading_delete, and recreate from scratch the styles still reading in the django database.
