### ISSUE TITLE
GNIP-67: GeoNode CSW-T

### ISSUE THREAD

**Issue by tomkralidis** [GeoNode/geonode#2467]
# Overview

GeoNode's core CSW support is realized by [pycsw](http://pycsw.org).  Alternate CSW endpoints can be configured with the underlying interaction being HTTP via the CSW request/response mechanisms.

CSW-T is a profile of CSW which allows transactions to be performed against a catalogue (insert/update/delete).  pycsw provides full CSW (core/basic and transactional) but CSW-T is disabled to facilitate transactional workflows via GeoNode proper.

Allow for CSW-T based functionality directly against GeoNode/Django models.

This GNIP will enable GeoNode's underlying pycsw support to provide CSW-T capability directly against the GeoNode/Django models.
## Proposed By

@tomkralidis
## Assigned to Release

2.5.x
## Motivation

Currently, pycsw as integrated in GeoNode provides a one-way/outbound/readonly endpoint with direct read access from the GeoNode DB.  Enhancing with CSW-T will allow GeoNode to support a richer harvesting workflow via CSW-T of [numerous resource types](http://docs.pycsw.org/en/latest/transactions.html#supported-resource-types) (WMS, WFS, WCS,  WAF, etc.)
# Proposal

Enable pycsw's GeoNode backend to support CSW-T functionality.
### Concepts

pycsw's harvesting approach is to create a generic `Record` object which is managed as a metadata record in a given metadata repository.  This covers the metadata record workflow.

For the services (WMS, WFS, WCS, SOS, WPS, etc.) workflow, pycsw inserts 1+n `Record` objects into the repository.  For example, if a WMS has 66 layers, 67 `Record` objects are inserted (1 as a service metadata record, and 66 layer metadata records).
### pycsw

pycsw's backend architecture allows for using a default model and/or binding to an alternate model via configuration of [field mappings with some detailed semantics](http://docs.pycsw.org/en/latest/administration.html#mapping-to-an-existing-repository).  pycsw's [GeoNode repository plugin](https://github.com/geopython/pycsw/tree/master/pycsw/plugins/repository/geonode) contains the required functionality as part of the `pycsw.core.repository.Repository` model.  The `insert`, `update`, `delete` functions will be added to `pycsw.plugins.repository.geonode.geonode_.GeoNodeRepository` to insert/update/delete metadata records seamlessly.  Translation between core pycsw harvesting and GeoNode repository models is required.
## Issues
- which resource types to support?
- workflow
- how results are realized on GeoNode UI

**Comment by pjdufour** [comment]
What is CSW-T?  Sorry, I've never heard of it before.

**Comment by tomkralidis** [comment]
@pjdufour updated GNIP text for clarification.

**Comment by pjdufour** [comment]
So the big gain is for registering remote services in GeoNode?

**Comment by tomkralidis** [comment]
Remote services and resources (i.e. existing of standalone datasets, etc.)

**Comment by jj0hns0n** [comment]
@tomkralidis is this ready for 2.5?

**Comment by jj0hns0n** [comment]
@tomkralidis this can be closed as merged now right?

**Comment by kikislater** [comment]
Please re-open as it's not implemented !

**Comment by afabiani** [comment]
@all please, when creating a GNIP, other than the correct label it must:

- contain in the title the prefix GNIP-xx where xx is a progressive number == len(gnips) + 1
- update the https://github.com/GeoNode/geonode/wiki/GeoNode-Improvement-Proposals accordingly

**Comment by kikislater** [comment]
Do we need to wait pycsw PR with commits  available here :
https://github.com/geopython/pycsw/compare/master...tomkralidis:geonode-csw-t

before making a PR with these commits in Geonode : 
https://github.com/GeoNode/geonode/compare/master...tomkralidis:csw-t 
?

**Comment by giohappy** [comment]
Is this issue still valid?
