### ISSUE TITLE
Errors relating to remote services

### ISSUE THREAD

**Issue by cliffpat** [GeoNode/geonode#2476]
Using GeoNode 2.4, I tried to add a remote service but once added, I am unable to use these layers in GeoExplorer without getting 502 and 505 errors. Except for the changes below, I have made no changes to the configuration. This is a fresh installation on Ubuntu Server 14.04. Here's what I did:

1) Add remote service URL in GeoNode using auto-detect selection. To recreate, this is the URL I used: http://geo.weather.gc.ca/geomet/?lang=E&service=WMS&request=GetCapabilities

More info about this service can be found [here](https://ec.gc.ca/meteo-weather/default.asp?lang=En&n=C0D9B3D8-1)

2) Edit local_settings.py file and add PROXY_ALLOWED_HOSTS = ('geo.weather.gc.ca', )

3) Increase timeout of Apache server to 600 seconds. 

4) Restart Apache server

Result:

When loading WMS layer in GeoExplorer

> 502 BAD GATEWAY
> Proxy Error
> The proxy server received an invalid response from an upstream server.
> The proxy server could not handle the request POST /geomet/.
> Reason: Error reading from remote server

Expected result: no error.

When trying to save a map containing a WMS layer from a remote server (NOTE: map does not save):

> 500 Internal Server Error
> 
> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> More information about this error may be available in the server error log.

Expected result: no error.

Note that these errors do not occur when using local Geoserver layers.

**Comment by simod** [comment]
hi do you mind using the mailing lists geonode-users@lists.osgeo.org to request for support? this is only for confirmed bugs.

**Comment by cliffpat** [comment]
Done! Thanks!
