### ISSUE TITLE
Validate ISO metadata before injection into the catalog

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#2485]
In order to help whichever customization could be done on the ISO19139 template, the system should perform a validation on the ISO metadata once it is created merging the user provided info and the template.

The validation info (that is, if the metadata is valid, and, optionally, any validation error found during the validation process) should be made visibile in the administration pages, so that an admin can easily spot and fix any bad metadata.

**Comment by tomkralidis** [comment]
@etj thanks for the info.  How is the validation machinery supposed to work?  Is there an approach in mind?

**Comment by etj** [comment]
I'm putting some validation logic in geonode.catalog, which performs the validation according to a requested schema. I'm putting in ISO19139 and FGDC schemas for the moment, since the validation will be used also for testing imported metadata files (I'll open an issue about this in a few days).

The validation logic will then be run in ``catalogue_post_save``: just after the XML is created, it will be validated, and the (new) boolean field ``is_valid`` will be saved into the ResourceBase.

**Comment by jj0hns0n** [comment]
@tomkralidis @etj what is the status of this one?
