### ISSUE TITLE
syncdb fails in dev install docs 

### ISSUE THREAD

**Issue by mikefedak** [GeoNode/geonode#2487]
https://github.com/GeoNode/geonode/blob/master/docs/tutorials/devel/devel_env/index.txt#L319

The development install more or less works as documented until this line. This will fail due to a django contenttypes related error. I noticed in the paver file, this is avoided by running a fake migration : 

https://github.com/GeoNode/geonode/blob/master/pavement.py#L214

A workaround is just to run paver start.

**Comment by etj** [comment]
This issue should be solved by the PR related to https://github.com/GeoNode/geonode/issues/2488.

**Comment by etj** [comment]
Please also check https://github.com/GeoNode/geonode/issues/2498

**Comment by jj0hns0n** [comment]
@mikefedak @etj can we close this now?
