### ISSUE TITLE
Saving Metadata Overwrites Layer's Custom Thumbnail

### ISSUE THREAD

**Issue by darinacosta** [GeoNode/geonode#2489]
A new thumbnail is generated each time a layer's metadata is updated here: https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/signals.py#L387

This overwrites custom thumbnails that are created here:
https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/utils/thumbnail.js

**Comment by jj0hns0n** [comment]
@darinacosta can we close this?
