### ISSUE TITLE
Async Upload

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geonode#2512]
The `layer_upload` view is synchronous when data is uploaded via HTTP POST.  It should be asynchronous and return immediately instead of waiting on GeoServer.  This can easily lead to timeouts.

https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L132

To hotfix, you can extend the allowed timeout.  The view is "protected" by `@login_required` so shouldn't have direct negative consequences.

However, it would be best practice to make the view async, make corresponding improvements in the  javascript code, and have shorter timeouts.

![image](https://cloud.githubusercontent.com/assets/1438253/16144685/ee84edc2-3474-11e6-88c9-08a1fb30af5c.png)

**Comment by pjdufour** [comment]
Workaround for example:

```
location /layers/upload {
  uwsgi_pass unix:///var/run/uwsgi/geonode.sock;
  include uwsgi_params;
  uwsgi_read_timeout 300s;
}
```

**Comment by jj0hns0n** [comment]
@pjdufour @BerryDaniel should we just update the packages for now. We will switch to the new importer soon.
