### ISSUE TITLE
Manage special characters in remote services layers names

### ISSUE THREAD

**Issue by amefad** [GeoNode/geonode#2516]
When trying to register a remote service in geonode like this:

http://servizigis.regione.emilia-romagna.it/wms/dbtr2013_ctr5_light?service=wms&request=Getcapabilities

Where the layer name is 

public/DBTR2013_Ctr5_Light

Geonode throws a internal serverr error because the url of layer is not resolved due to the "/" character in layer name.

Amedeo Fadini

**Comment by capooti** [comment]
Unfortunately we rely on layers.typename for both layer geonode identification (layer details page use this field) and for requesting the layer to the endpoint.
Therefore if we slugify the name GeoNode will not be able to do the correct request, as it needs the original name.
We would need a new field where to set the layer name in the endpoint, but given that it is a very specific case I would suggest to rename the layers in the endpoint (if possible)

**Comment by amefad** [comment]
I definitely agree. Sent mail to the endpoint admin.

**Comment by capooti** [comment]
thanks @amefad
