### ISSUE TITLE
Django Admin layers and layer detail page are broken

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2519]
Most likely because of old versions of django-taggit, django-polymorphic, django-autocomplete-light and the recent update to django 1.8
Requires investigation.

**Comment by pjdufour** [comment]
For DAL, see:  https://github.com/GeoNode/geonode/issues/2451

**Comment by travislbrundage** [comment]
Just as a note, I have had this happening for ResourceBase in general, so it affects both Layers and Maps.

**Comment by sarasafavi** [comment]
Fixed in https://github.com/GeoNode/geonode/pull/2580 -- @jj0hns0n this can be closed (I lack perms to do it myself)
