### ISSUE TITLE
DB migration is not working

### ISSUE THREAD

**Issue by DiliniHB** [GeoNode/geonode#2520]
Tried to perform db migration in the installation process with the command, 
"python manage.py migrate"
but it failed giving the error,
"ProgrammingError: relation "people_profile" does not exist"

Can I know whether it is a version problem and what fixes I can do in order to get migration worked.

**Comment by simod** [comment]
Hi please use geonode-users@lists.osgeo.org to ask for support. Also add some details like the versions you are trying to migrate to/from.
