### ISSUE TITLE
Importing GeoNode metadata into QGIS

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2528]
I am testing downloading a shapefile from GeoNode and the metadata then opening the dataset in QGIS.

This is the layer I am testing: http://geonode.state.gov/layers/geonode%3ASyria_RefugeeSites_2016Jan21_HIU_DoS0

- I downloaded the data as a shapefile.

- I then downloaded the metadata and saved it as an xml file with the same basename as the shapefile.

here is the directory with all of my files:

![pic-of-dir](https://cloud.githubusercontent.com/assets/2665840/16394012/2cd1102e-3c81-11e6-8cb8-2f1f91fccfcc.PNG)

I then opened this shapefile in QGIS 2.14.3, with no plug-ins. I do not see the metadata I am hoping to see. If I right-click on the layer and go to properties it opens the layer properties window. Then if I click on the Metadata tab, the properties only show General properties. All of the field in the Description section are blank. Is there a way to populate these fields? Are the metadata fields supposed to automatically show up? Or is there a way you need to import the xls manually by selecting the xls file?

**Comment by simod** [comment]
Please don't use the issue tracker to ask for support. geonode-users@lists.osgeo.org is the place.
