### ISSUE TITLE
Download data from Map

### ISSUE THREAD

**Issue by hieuintel** [GeoNode/geonode#2534]
Dear All,

I'm researching GeoNode Platform. The first feel is quite comfotable but when I try to download data from map (I published) alway error. Please try this link to clear

http://118.70.184.30:3023/maps/3/download

Have anyone help me,
Thank a lot,
HieuIntel

**Comment by simod** [comment]
Hi, please use geonode-users@lists.osgeo.org to ask for support. This is only a bug tracking system.

**Comment by hieuintel** [comment]
Sorry and thank a lot,

Best
