### ISSUE TITLE
Thumbs are not removed after layers and maps have been deleted

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#2535]
The directory _thumbs_ still continues to have thumbs of deleted layers and maps

**Comment by jj0hns0n** [comment]
@francbartoli can you send a patch for this during the sprint? Otherwise, lets move to 2.7 as its not really too big of a deal IMO.

**Comment by capooti** [comment]
this is connected to #2291 and it should be a celery task as well
