### ISSUE TITLE
geoserver redirect url endpoint is not working.

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#2542]
# Problem

When trying to access geoserver from geonode interfaces it resolves to port 8080 which is the default geoserver port. It fails to redirect the geoserver considering that I have port forwarded a different port externally.

`docker run -d -p 8111:8000 -p 8181:8080 geonode`

![geonode](https://cloud.githubusercontent.com/assets/2510900/16685575/487cd202-450c-11e6-8372-4bf023a558ab.png)

Because the geoserver is running on port 80 in the container so geonode still thinks geoserver is being accessed from port 80 externally.

![eror](https://cloud.githubusercontent.com/assets/2510900/16685616/884eb53a-450c-11e6-8334-bf51311afa42.png)

# Solution 

Make sure geoserver is being redirected properly based on port forwarded.

**Comment by simod** [comment]
Hi, you can set the correct geoserver location in the settings https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L505.

Ps please use geonode-users@lists.osgeo.org to ask for support.
