### ISSUE TITLE
Admin template exception when viewing/adding maps, layers, documents

### ISSUE THREAD

**Issue by sarasafavi** [GeoNode/geonode#2566]
When viewing an individual map/layer/document, a NoneType exception is thrown, e.g.:

```
TypeError at /admin/maps/map/2/
'NoneType' object is not callable
```
```
/vagrant/.venv/lib/python2.7/site-packages/autocomplete_light/widgets.py in render
                    autocomplete = self.autocomplete(values=value) 
```

The same error occurs when adding via admin as well - this prevents the use of these admin views. 

Seems to be related to django-autocomplete-light & the Django 1.8 GeoNode upgrade: reference this change [geonode/base/admin.py:133](https://github.com/GeoNode/geonode/blob/master/geonode/base/admin.py#L133) made within https://github.com/GeoNode/geonode/commit/fc4085bf6ffe8f09a307309e5f22ef2371892ef1.

**Comment by pjdufour** [comment]
For DAL (django-autocomplete-light), see:  https://github.com/GeoNode/geonode/issues/2451

**Comment by jj0hns0n** [comment]
@sarasafavi is this still occuring? Can we look during the sprint.

**Comment by sarasafavi** [comment]
@jj0hns0n this was fixed in https://github.com/GeoNode/geonode/pull/2580; closing
