### ISSUE TITLE
Internal server error adding new user with email address already in db

### ISSUE THREAD

**Issue by amefad** [GeoNode/geonode#2572]
In Geonode 2.4 standard installation (ubunt14 ppa) I tried to add a new user with different profile, managed by me.
It raises "internal server error" due to the constraint 
account_emailaddress_email_key UNIQUE(email)
on table 
account_emailaddress.

Maybe is it possible to get a different error from application when a constraint is violated?

amefad

**Comment by jj0hns0n** [comment]
@amefad can you test with master and let us know if this is still an issue?

**Comment by simod** [comment]
It is still the case, though the error is pure django style as we are in the admin. It could be tricky to make it better.

**Comment by sarasafavi** [comment]
Confirmed still the case, however I'm removing the "bug" label as the behavior is not unexpected (a constraint violation results in an IntegrityError). Agree that the error might be presented to the admin user more nicely, so I'll work on improving this.
