### ISSUE TITLE
Private layers show in auto-complete search

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2573]
I have a geonode with several hundred layers, only a few dozen are public. All layers show in the auto-complete dropdown in the header, regardless of whether they are private or not.

**Comment by jj0hns0n** [comment]
@simod this is pretty nasty, can we look together and ensure perms are enforced on autocompletes.

**Comment by stan4gis** [comment]
Could it be a parameter in settings ?  (I think it depends on security policy. Use case : everyone can search all the catalog and so can contact an admin to ask rights on ressources he finds like that).
As a first improvement we should have a message in the ressource detail page to explain the user he has not the right to see the ressource.
An other question is "does the search in the menu bar should work as the search in the filters panels ?". In the filters panels we expect a search on special type of ressource (layer or map or document) and in the menu bar a search in all types of ressource (like now). I can put a new issue for this if there is no one yet.

**Comment by sarasafavi** [comment]
> An other question is "does the search in the menu bar should work as the search in the filters panels ?". In the filters panels we expect a search on special type of ressource (layer or map or document) and in the menu bar a search in all types of ressource (like now). I can put a new issue for this if there is no one yet.

@stan4gis please reference https://github.com/GeoNode/geonode/issues/2555 for further discussion on this issue; TL;DR: GeoNode currently includes both the "omni search" (menu bar search, across resources) and the "filter search" (resource-specific) functionality, by intent.
