### ISSUE TITLE
Problem when splitting keywords in metadata

### ISSUE THREAD

**Issue by artists974** [GeoNode/geonode#2574]
When someone adds multi-words keywords, they are sometimes splitted in several distinct words. For example :

Mountains, Lakes --> No problem, will give "Mountains", "Lakes"
Urban Environment, Lakes --> No problem, will give "Urban Environment", "Lakes". This is because there is at least one comma, so I suppose Python understands that the separator is the comma. The problem comes either if there is only one multi-words keyword, or if the last keyword of a list is a multi-words keyword. The only trick I found is to ask the user to always end his list of keywords by a comma, even if there is only one keyword. This really works, but it's not comfortable for the user. So :

Urban Environment --> Will give "Urban", "Environment" which is not good at all
Lakes, Mountains, Urban Environment --> Will give "Lakes", "Mountains", "Urban", "Environment".
BUT
Urban Environment, --> Will give "Urban Environment", no problem
Lakes, Mountains, Urban Environment, --> Will give "Lakes", "Mountains", "Urban Environment" : perfect.

**Comment by capooti** [comment]
I believe this should be addressed to django-taggit issue tracker

**Comment by jj0hns0n** [comment]
@artists974 did you send this upstream to the django-taggit issue tracker? If so, can we close?

**Comment by artists974** [comment]
Hi, we didn't send yet. But you can close if you want, thanks
