### ISSUE TITLE
Notifications translation

### ISSUE THREAD

**Issue by artists974** [GeoNode/geonode#2575]
When I'm on Notifications section, nothing is translated. Yet, I can see that everything is translated in django.po files, and also in python code.

**Comment by jj0hns0n** [comment]
@collaer can you take a look?

**Comment by collaer** [comment]
@artists974 
Hi,

Not sure what's the point here ?

You've translated something in a po file and make a compillemessage after and the translation is not showing ?
Wich po file, language and key string ?

Keep in mind that you cannot translate strings directly into po files because a transifex sycing pull request will destroy those changes.

**Comment by artists974** [comment]
Hi,

Actually I didn't translate anything. All the translations needed for this page already exist in the .po file (english and french) so I didn't even edit them. 

![po_en](https://cloud.githubusercontent.com/assets/19589165/17960988/35485da4-6aba-11e6-9db7-62c245faee42.JPG)
this is in the "en" .po file

![po_fr](https://cloud.githubusercontent.com/assets/19589165/17960999/44a2021e-6aba-11e6-83ce-cec34d7b49cd.JPG)
this is in the "fr" .po file

![management_init_python](https://cloud.githubusercontent.com/assets/19589165/17961009/4e7a822a-6aba-11e6-86f9-207d26b252a2.JPG)
this is from layers/management/__init__.py

![geonode_display](https://cloud.githubusercontent.com/assets/19589165/17961021/6528cfcc-6aba-11e6-96d9-34f5406af9a8.JPG)
And in the end this is the display, on a "french" LANGUAGE_CODE page. 

Thank you

**Comment by collaer** [comment]
Ok now i understand !

I suppose that 
https://github.com/GeoNode/geonode/blob/master/geonode/layers/management/__init__.py#L23
should be changed from ugettext_noop to ugettext_lazy.
I'll test that as soon as possible.

Thanks

**Comment by artists974** [comment]
Thanks ! I will try on my instance too :)

**Comment by artists974** [comment]
I just tried 'ugettext_lazy', and also 'ugettext', but it still doesn't work. Maybe I missed another step...

**Comment by collaer** [comment]
Maybe, I must admit that I'm really unconfident with the notifications, i didn't figured out where they should appear... 
As I don't know how django notification works, hat was just a guess this move to the lazy...
