### ISSUE TITLE
Is someone changed the admin user password in the geonode demo site?

### ISSUE THREAD

**Issue by gantonio89** [GeoNode/geonode#2588]
I'm trying to login with default user (admin) and password (admin) but the informations are incorrect.
How can it be solved?
Thanks

**Comment by simod** [comment]
Password reset. Thanks.

Ps, next time do you mind using geonode-users@lists.osgeo.org instead of opening a ticket?

**Comment by gantonio89** [comment]
Ok! I will remember it.
Thank you very much!

Antonio

2016-08-19 11:30 GMT+02:00 Simone Dalmasso <notifications@github.com>:
