### ISSUE TITLE
Permission setting of a layer is not showing the layer only pink tiles (mostly)

### ISSUE THREAD

**Issue by blackgis** [GeoNode/geonode#2625]
Strange issue with permissions, they work but the displaying of data with permission not for allowed users/groups.
1. Select a layer
2. Change Layer Permissions
3. toogle off anyone and specifing user and group
4. Result, what works correctly is that in the layer overview the layer is not displayed for anyone (as expected), but for the allowed users and groups (as expected), BUT when selecting the layer again as an allowed user, the map shows pink tiles where the data should be (geoserver issue?) or nothing will be displayed.

System Ubuntu 14.04.2LTS, GeoNode 2.4.1

Is this a bug?

**Comment by simod** [comment]
Hi I cannot replicate this.Data are correctly shown to authorised users

**Comment by blackgis** [comment]
Hi,
thank you for replying. 
Unfortunately it still exists. Can you give me a hint what this can cause. The permission in the geoserver works, because i tested it in qgis and logged in and got all layers i am authorized to see. Do i have to activated some authorization stuff because it must be some portal or django issue. I have seen that there is a extension for geoserver to add this functionality. I investigate on this but i appreciate any hints to solve my problem.

**Comment by simod** [comment]
GeoNode requires a special version of geoserver which has a security plugin. This geoserver is the one installed by geonode by default. So if you used a normal geoserver the permissions won't be respected.

**Comment by capooti** [comment]
@blackgis can we close this? Did you solve it?

**Comment by blackgis** [comment]
@capooti @simod We did a reinstall with the settings as described, and now its working. We use a PaaS for GeoNode and my hoster come up with the idea of installing the latest geoserver (2.9 at this time) and this was somehow the failure.
