### ISSUE TITLE
Change Layer Permissions no refresh after applying?

### ISSUE THREAD

**Issue by blackgis** [GeoNode/geonode#2626]
After setting the permissions of a lyr i have to zoom in and out in the map that the layer permission is working. Shouldn't there be an auto refresh in the map after applying any permission setting?

**Comment by pjdufour** [comment]
Sorry, I don't understand.  Can you provide screenshots of this behavior?

**Comment by blackgis** [comment]
Hi, a screenshot not may help her.
My other 'problem' is described in #2625 otherwise I would not discover that there is no refreshing of the map. So knowing that when I am in the layer site, selected on layer and changed permission from anybody to someone/group specific it should display nothing (unfortunately because of #2625 ). But when changing layer permission the map(stille on the layer site) stays the same(as we know from #2625 the layer should disappear, but doesn't) and only after zoom in or out (still on the same page) the layer disappears, that indicates to me that after setting permissions in the layer site, the map on the layer site doesn't refresh only after zoom in or out.

**Comment by simod** [comment]
Hi, you mean that you are revoking permissions to yourself?
The map doesn't refresh the tiles itself and this is ok since you have seen the layer till before revoking the permissions. Is not an issue and is the expected behaviour.

**Comment by blackgis** [comment]
Hi, no. 
I gave explicit permission only to me not to anyone, only me. But the tiles are not presented. The permission itself is working correctly, because i have added the layers to qgis and used the login and the layer is visible and displayed(and only when i give qgis the login, so the wms is correctly working), but not on the website of the layer itself, where the layer should be displayed on the map. I get in geonode only pink tiles or nothing, although i have the permission to see them, but they are not displayed - that is the problem. Could it be that the portal itself has an issue to display the protected wms, because when looking in the console it is only giving the normal wms url, not a url with login credentials. Have I missed a setting?

**Comment by simod** [comment]
Ok, did you use the geoserver of Geonode? Seems an issue that could happen when using a normal geoserver or a geoserver that cannot communicate with Geonode in the correct way. 
Sorry but I still don't understand the refresh issue.

**Comment by blackgis** [comment]
Hi, I have not installed it by myself - paas. First they use 2.9 but the uploading haven't worked. Now they installed 2.7 like in the demo.geonode.org - exact same settings. How can i be sure that this is the correct geoserver? Are there some special files?

Refresh issue:

Go to layer site, set permissions (the permissions are applied immideately in the backend - only backend! - and not on the side where you set the layer permission)
Still on the layer site of which you have just modified the permissions, have a look at the map where the layer is displayed. Still the same, correct, but because of my display issue that the geoserver is only drawing pink tiles instead of the data after setting permission, the newly set permission becomes only active in this map when zooming or paning in the map - because then, because of my display issue, the map refreshes accordingly to the newly set permissions. 

Hope this helps.

**Comment by simod** [comment]
The geoserver to be used is the one pulled by geonode with paver setup or this one http://build.geonode.org/geoserver/latest/geoserver.war
