### ISSUE TITLE
Cannot change Geoserver admin password 

### ISSUE THREAD

**Issue by joanvp** [GeoNode/geonode#2631]
Hi all,

I recently installed a geonode 2.4 instance following the tutorial for Ubuntu 14.04. The installation works smoothly except for an issue. When I try to change the geoserver admin, the change doesn't apply.

Basically I have copied the piece of config regarding geoserver in the local_settings file but even after restart tomcat and apache, the change does not apply, and it allows me to log in with the default password.

OGC_SERVER = {
    'default' : {
        'BACKEND' : 'geonode.geoserver',
        'LOCATION' : 'http://myip/geoserver/',
        'PUBLIC_LOCATION' : 'http://myip/geoserver/',
        'USER' : 'admin',
        'PASSWORD' : 'secretpassword',
        'MAPFISH_PRINT_ENABLED' : True,
        'PRINT_NG_ENABLED' : True,
        'GEONODE_SECURITY_ENABLED' : True,
        'GEOGIG_ENABLED' : False,
        'WMST_ENABLED' : False,
        'BACKEND_WRITE_ENABLED': True,
        'WPS_ENABLED' : False,
        'LOG_FILE': '%s/geoserver/data/logs/geoserver.log' % os.path.abspath(os.path.join(PROJECT_ROOT, os.pardir)),
        # Set to name of database in DATABASES dictionary to enable
        'DATASTORE': 'datastore',
    }
}

As a workaround I have disabled the admin user.

Best regards

Joan

**Comment by simod** [comment]
Hi, you have to change the password also from the geoserver UI as this is part of the geoserver internal database.

ps, please next time use geonode-user@lists.osgeo.org to ask for support.

Regards

**Comment by joanvp** [comment]
My apologies. Since I didn't find any reference I thought it was a bug. Now it works as expected.

Thanks for your help
