### ISSUE TITLE
Google Maps API warning: NoApiKeys

### ISSUE THREAD

**Issue by ehl120** [GeoNode/geonode#2632]
Help!

I got both Bing Aerial and Google Satellite working with GeoNode 2.4. The config is like so:

GOOGLE_API_KEY = 'zxcxzcXAWdqwddfereeeee22222xxx'
"source": {
     "ptype":"gxp_googlesource",
     "apiKey": GOOGLE_API_KEY
    },
...

Or add the key to the code:

"source": {
     "ptype":"gxp_googlesource",
     "apiKey":  'zxcxzcXAWdqwddfereeeee22222xxx'
    },
...

Either case, I am stilling getting the warning:

Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

Is it just me or anyone of you have the same problem? Although it works, it would be nice to have this fixed.

**Comment by ewsterrenburg** [comment]
Managed to make this work using the following config. Would be nice if the documents could be updated (if one could give some pointers as to against what branch to make the pull request, I could do so...)

Erwin

```
{
    "source": {
         "ptype":"gxp_googlesource",
         "otherParams": "sensor=false&key={0}".format(GOOGLE_API_KEY)
        },
    "group":"background",
    "name":"ROADMAP",
    "visibility": False,
    "fixed": True
}
```
