### ISSUE TITLE
Publish Map WMS broken

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2634]
The link from any [map page](http://localhost/maps/13) to "Publish Map WMS" (Publish local map layers as WMS layer group) just gives a JSON object definition instead of an HTML page:

`{"layerGroupName": "", "ows": "http://localhost/geoserver/ows"}`

**Comment by jondoig** [comment]
No comments? Why closed?

**Comment by simod** [comment]
Hi, I commented on the list. It's fixed in master.

**Comment by jondoig** [comment]
Thanks! So fast - wow.
