### ISSUE TITLE
PDF outputFilename

### ISSUE THREAD

**Issue by ehl120** [GeoNode/geonode#2638]
Tried to make the output PDF name from GeoExplorer-print.pdf to something we a date and time, like so:
yyMMdd-hhmmss.pdf

So in the config.yaml, I added this line before the layouts block:
outputFilename: "${yyMMdd-hhmmss}"

or 
outputFilename: "Mapfish print"

But this doesn't overwrite the default setting.

Any tips on cracking this?
Thanks.

**Comment by simod** [comment]
Hi, be sure that you are editing the correct config.yaml. It has to be the one in the geoserver data dir which is listed in the geosever config page. A tomcat restart may be needed.

**Comment by ehl120** [comment]
I did restart the tomcat as well as apache server but ain't got any luck. I am gonna try the GeoServer - User forum. Thanks.
