### ISSUE TITLE
backgroundPdf added but text no longer shows up

### ISSUE THREAD

**Issue by ehl120** [GeoNode/geonode#2640]
Hi Guys - Great work! I love the GeoNode 2.4 so far. As I am working on customizing the print layout, I found this may be a bug or something. If you have  quick pointer to fix this, that will be great.

I created a A4 lanscape layout and it prints well. As it takes a PDF as a background, so I made up an PDF layout and then line up the map block and title and scale bar etc through the config.ymal.

The problem is all the text elements no longer show up on the print. The map is added as well as the scale bar but not the text, e.g. text: '${comment}', text: '1:${scale} ${now MM.dd.yyyy}' and title: '${mapTitle}'

Any thoughts??

**Comment by simod** [comment]
Hi, do you mind using geonode-users@lists.osgeo.org to ask for support?

As mapfish is not a component of GeoNode you might get more help if ask on the mapfish help channels. Anyway check if the geoserver logs show something. 

Thanks

**Comment by ehl120** [comment]
Thanks for the tips.
