### ISSUE TITLE
Remote Services URL Mapping

### ISSUE THREAD

**Issue by biomap** [GeoNode/geonode#2644]
When Geonode is registered at a sub url (ie /gis ) the Remote Services pages/views are not respecting the sites sub url's and are mapping the the urls to the domain. 

Example:
geonode is registered at example.com/gis
remote services are found at example.com/gis/services 
all of the buttons and links on the remote services pages are returning example.com/services 

Register New Service seems to work just fine.  Its just once a service is registered and then you try to manipulate it from the frontend.  

It is also not pulling any metadata for the subscribed services and results in a traceback until it is set manually. 

GeoNode version 2.5.3

All of the other URL mappings seem to be fine.

Thanks!

**Comment by biomap** [comment]
Actually it might be just the [Remove Services Page](https://github.com/GeoNode/geonode/blob/142d85f32b7a425e5ec5980380078d3d7dbe7b65/geonode/services/templates/services/service_remove.html) (or anywhere the URLs are hard coded) that is causing the issue.

It appears this is the [Bad Actor](https://github.com/GeoNode/geonode/blob/142d85f32b7a425e5ec5980380078d3d7dbe7b65/geonode/services/templates/services/service_remove.html#L13).  Or at least one of them.  Looks like you are using variables everywhere else.  :)

**Comment by jj0hns0n** [comment]
@biomap can you perhaps send a PR for this?

**Comment by biomap** [comment]
Sorry I just noticed this..... I have decided to build a flask app that will better suits my customized needs.  If I would have proceeded I would have been happy to submit a PR.  I wouldn't count on me in the near term however.  Great project though.
