### ISSUE TITLE
Edit issue for CSV, KML  files

### ISSUE THREAD

**Issue by nareshnagamalle** [GeoNode/geonode#2657]
Uploaded CSV, KML files are uploaded to Geonode and observed following issues. 
1. In Map window section --> Edit --> Create option is in grey out mode .i.e not able to select
2. If we click on Modify option and click on features option then feature info option is not visible and not able to edit the feature geometry and attributes information. I could able to find through the firebug that the  features information is returning to browser but popup is not visible.

Please suggest me to resolve the issue. 

The following things are used in localsettings.py and installed Geonode2.4 version in windows os
UPLOADER = {
    'BACKEND': 'geonode.rest',
    'OPTIONS': {
        'TIME_ENABLED': False,
        'GEOGIG_ENABLED': False,
    },
    'BACKEND': 'geonode.importer',
    'OPTIONS': {
        'TIME_ENABLED': False,
        'GEOGIG_ENABLED': False,
    }
}

**Comment by nareshnagamalle** [comment]
Please any work around for this.

**Comment by simod** [comment]
Not sure that more uploaded are supported. only one should live there.

**Comment by harts-boundless** [comment]
That dictionary has some duplicated keys which make it confusing.

    Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
    [GCC 5.4.0 20160609] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    >>> UPLOADER = {
    ... 'BACKEND': 'geonode.rest',
    ... 'OPTIONS': {
    ... 'TIME_ENABLED': False,
    ... 'GEOGIG_ENABLED': False,
    ... },
    ... 'BACKEND': 'geonode.importer',
    ... 'OPTIONS': {
    ... 'TIME_ENABLED': False,
    ... 'GEOGIG_ENABLED': False,
    ... }
    ... }
    >>> UPLOADER
    {'OPTIONS': {'TIME_ENABLED': False, 'GEOGIG_ENABLED': False}, 'BACKEND': 'geonode.importer'}

Therefore the real effect is actually 

    UPLOADER = {
        'OPTIONS': {
            'TIME_ENABLED': False, 
            'GEOGIG_ENABLED': False
        }, 
        'BACKEND': 'geonode.importer'
    }
