### ISSUE TITLE
Error adding keywords to a Layer when they already exist (related to Hierarchical Keywords)

### ISSUE THREAD

**Issue by gdreich** [GeoNode/geonode#2659]
Example: "human health" already exists in Hierarchical Keywords
IntegrityError at /admin/layers/layer/48/
duplicate key value violates unique constraint "base_hierarchicalkeyword_name_key"
DETAIL:  Key (name)=(human health) already exists.

The keywords are trying to be added again even if they exist.

**Comment by gdreich** [comment]
This affects multiple word keywords only e.g. "human health", since the slug won't be in str_tags if its more than one word, not sure if this is intended or not.
existing = self.through.tag_model().objects.filter(slug__in=str_tags)
is it feasible to change the filter to name__in=str_tags?
https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L286.

**Comment by fdetsch** [comment]
I encounter the same problem. Is there any solution yet?
