### ISSUE TITLE
Failure to use connect to postgres container when using custom image

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#2662]
# Problem

From #2661 I then tried to use a custom image that has postgis extension installed. I have modified my docker-compose to be: 
![serv](https://cloud.githubusercontent.com/assets/2510900/18986832/04e7803e-86ff-11e6-9ed1-b773aecb7ee1.png)

when I try to start my container I get an error:

![dockre](https://cloud.githubusercontent.com/assets/2510900/18986893/5b1b1920-86ff-11e6-8ef8-fee95d89a39d.png)

**Comment by francbartoli** [comment]
@NyakudyaA Is this still an issue?

**Comment by NyakudyaA** [comment]
yes It is still an issue.

**Comment by francbartoli** [comment]
Can you please explain better your workflow after using the default docker-compose from geonode?

This would allow to reproduce the issue.

**Comment by NyakudyaA** [comment]
I was trying to use another postgres image.
*  Clone the geonode repo
* Edit docker-compose to change the postgres section. 
  Use [https://github.com/kartoza/docker-postgis](url) instead of the specified image
  Change the docker compose to be the same as the image attached above.
  Since this docker image has a database called gis, username docker which will need to be changed
  in the docker compose for django environment variables
* Modify the make command to run interactively so that the errors can be seen in console

* Run make commands

**Comment by francbartoli** [comment]
So what the issue would be with the original docker-compose file?

If you have improvements please provide PR for this.

Thanks

Inviato da iPhone
