### ISSUE TITLE
GNIP 24 - Map Revision History

### ISSUE THREAD

**Issue by sbenthall** [GeoNode/geonode#267]
https://github.com/GeoNode/geonode/wiki/GNIP-24---Map-Revision-History

A WorldMap feature from Matt Bertrand

> Add functionality to record every saved state (viewer JSON) of a map, along with date and the user who saved it. Also add a UI for editors to browse through and view all previously saved versions of the map.

**Comment by jj0hns0n** [comment]
Closing as implemented with https://github.com/GeoNode/geonode/commit/67ecb10813612be86b1748e09643edaf39cb33ab Please file new issues / improvements as they are encountered.
