### ISSUE TITLE
GNIP 22 - Display Layers from Remote ArcGIS REST servers

### ISSUE THREAD

**Issue by sbenthall** [GeoNode/geonode#268]
https://github.com/GeoNode/geonode/wiki/GNIP-22---Display-Layers-from-Remote-ArcGIS-REST-servers

From Matt Bertrand.  Has pull request attached.  

https://github.com/opengeo/gxp/pull/83

**Comment by jj0hns0n** [comment]
Im going to go ahead and close this one as implemented. Please file new issues as appropriate.
