### ISSUE TITLE
Uploading issue

### ISSUE THREAD

**Issue by waybarrios** [GeoNode/geonode#2683]
When I tried to upload a sample layer, it showed me a `[Errno 111] Connection refused`and then on browser console displayed me the following:

```
assets.min.js?v=2.5.4.dev20161011203841:4 POST http://localhost/layers/upload 400 (BAD REQUEST)
```

Does anyone know what happens here?

**Comment by simod** [comment]
Hi, seems that geoserver is not running.

ps, could you please use geonode-users@lists.osgeo.org to ask for support?
