### ISSUE TITLE
Quick install 'Unable to locate package geonode' on ubuntu 12.04

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2689]
[Quick install guide for ubuntu](http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html#ubuntu) says:

Set up the GeoNode PPA repository:

>  sudo add-apt-repository ppa:geonode/stable
> sudo apt-get update

Install the package:

> sudo apt-get install geonode

but on ubuntu 12.04 this gives:

> E: Unable to locate package geonode

If I change the first line to:

> sudo add-apt-repository ppa:geonode/release

it completes successfully, but installs Geonode 2.01, when I wanted 2.4.

**Comment by matshenricson** [comment]
I get exactly the same problem on 16.10

**Comment by simod** [comment]
Geonode stable is for ubuntu 14.04. On other versione the manual setup has to be followed. I'm flagging this a s doc issue

**Comment by matshenricson** [comment]
Well, Ubuntu LTS should be 16.04, right? Anyway, it seems like I am toast.

Mats

Den 2 nov. 2016 11:30 skrev "Simone Dalmasso" <notifications@github.com>:

**Comment by simod** [comment]
Also 14.04 and we released the 2.4 stable package only for it due to library versions

**Comment by muriithiderro** [comment]
following
