### ISSUE TITLE
docker-compose - Geoserver port not visuble for the host 

### ISSUE THREAD

**Issue by vwmaus** [GeoNode/geonode#2694]
The Geoserver port 8080 is not visible for the host. In my local version I set the geoserver port to "8080:8080". Is there a reason to keep it not visible? If not, should I make a pull request for this?

**Comment by francbartoli** [comment]
@vwmaus are you talking about a development environment or a production one which would be proxied by nginx?
In the latter case it does not make sense to have the 8080 port exposed to the host and so I would close this.

**Comment by vwmaus** [comment]
You are right, sorry for the mistake. Thanks!
