### ISSUE TITLE
Support for Python 3 or SNI (Server Name Indication) when using https

### ISSUE THREAD

**Issue by dvictori** [GeoNode/geonode#2695]
I think I've hit a httplib2 bug that is causing trouble in my GeoNode Install. I have GeoNode (v2.4.1) running on Ubuntu 14.01. The server is behind a reverse proxy that has multiple SSL certificates associated with only one IP address.

The problem is that when I try to upload some data to GeoNode, I get a certificate mismatch. The returned certificate is the one associated with the IP address of the reverse proxy and not the certificate of my geonode site.

From what I was told, the ability to resolve multiple SSL certificates from one address is implemented through SNI (Server Name Indication). And from this Github issue (https://github.com/jcgregorio/httplib2/issues/233), it appears that Python 2.7 and its httplib2 will not receive SNI support.

Another thing that makes me believe it's a python2.7+httplib2 specific problem is that If I try to connect to my site using python2 and httplib2 it fails but, using python3, it works.

The first time I ran into this problem, I though it was due to a configuration problem that ended up in this discussion (https://lists.osgeo.org/pipermail/geonode-users/2016-June/001933.html)

So, the questions are:
* Is anyone running GeoNode behind a reverse proxy that implements multiple SSL certificates for one address (SNI)?
* Will the next release of geonode use python3?

**Comment by yecarrillo** [comment]
Same here. I moved my geonode site to https and with this, all backgrounds has to be https. Now all thumbnails are saved without background layers.

**Comment by dvictori** [comment]
Python 2.7.9+ supports SNI (Server Name Indication) [1,2]. So this problem got fixed and I'm now able to run GeoNode 2.6 behind a reverse proxy with https. Closing the issue.

[1] - http://docs.python-requests.org/en/master/community/faq/
[2] - https://docs.python.org/2/library/ssl.html
