### ISSUE TITLE
GNIP - Better management of “View” and “Download” permissions

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2696]
# Overview
This GNIP aims to improve the management of “View” and “Download” layers permissions by separating concerns between backend mapping services (OGC _“WMS-like”_ services) and raw-data stream services (OGC _“W[F,C]S-like”_ services).

The proposal wants to spot also issues like:
https://github.com/GeoNode/geonode/issues/2085 

> “If a user/group does not have the download_resourcebase permission for a layer, GeoNode will correctly prevent to download it only by not showing the download button. Unluckily an astute user will still be able to download the datasets if he can figure out the GeoServer WFS link.”

It is worth notice that this proposal will be subdivided into 2 parts:

1. **GeoNode Download Layer GUI Refactoring**; refactoring of GeoNode interface for “Download Layer” which will be splitted in two different sections, one for WMS downloads and one for WFS/WCS downloads.

2. **GeoServer Advanced Security Rules Refactoring**; Refactoring of GeoServer Security Sub-System in order to block different type of calls accordingly to layer permissions

In particular the part (1) is backward compatible and can be backported to older GeoNode versions, while the part (2) will be part of the GNIP 
https://github.com/GeoNode/geonode/issues/2374 _“GNIP: GeoServer A&A Improvements”_, which relies on GeoFence[1] plugin for advanced security on GeoServer.

## Proposed By
@afabiani Alessio Fabiani ([GeoSolutions S.A.S.](http://www.geo-solutions.it))

## Assigned to Release
2.5.x

## Motivation
Currently GeoNode allows owners of the layers to configure “view” permissions and “download” permissions.

1. **View permissions**; the Layer can be visualized on map and is listed on the GeoNode layers list

2. **Download permissions**; the Layer can be downloaded in several formats, JPEG, PNG, PDF etc...

While this is correctly handled on GeoNode side, I guess there are some discrepancies on how this can be handled on the backend (GeoServer in this case).

The thing is, if you can download a layer on the backend you necessarily have also permissions to see it. Unless view and download use different protocols (which is not the case) to download a layer a user must have permissions to access it.

That means that even if in GeoNode we remove view permissions to a layer but we leave download ones, the Layer won't be listed in GeoNode but it will be always accessible from GeoServer.

# Proposal
We can distinguish between "view services" and "download services". In OGC the "view services" are the ones related to mapping, like the WMS, while the "download services" are the raw ones, like WFS and WCS. This is also the mapping that INSPIRE does over OGC.

What [we](http://www.geo-solutions.it) propose is to:

1. If a user has "view" permissions he can access to maps and portrayals, i.e. he can access to the WMS service.

2. If a user has "download" permissions he can access to raw services like WFS for vectorial data and WCS for raster data, i.e. he can download Layers as Shapefiles or GML2 or GeoTIFFs.

The two permissions will be separated. 

Also the Download Page must be revised. It must have two TABS, one for _“WMS-like”_ downloads (PNG, JPEG, GIF) and one for _“W[F,C]S-like”_ ones (Shapefiles, GML-2, GeoTIFF, ...).

## Implementation
As stated above, this GNIP can be splitted into two parts, one focusing mainly on GeoNode GUI and permissions management and another one focusing on the backend security rules.

_Why splitted into two parts?_ Mainly because currently the backend (GeoServer) advanced security cannot be modified in order to selectively block requests accordingly to the requested service. In order to allow GeoServer to manage authorization with more granularity, we need to integrate the GeoFence[1] plugin. This is not trivial since require deep and hard refactoring of the security sub-system and how GeoNode and GeoServer interact. This topic will be addressed on another GSIP[2] specifically created for the refactoring of the GeoNode/GeoServer A&A sub-system.

Nevertheless Part (1) of this proposal could be applied to older versions of GeoNode since it is an improvement of layer download permissions and GUI.

### Part 1: GeoNode Download Layer GUI Refactoring
Currently GeoNode presents a unique dialog window (see Fig. 1) with download options for each layer. If a user does not have”download” permissions, he will be completely blocked by GeoNode.

![image](https://cloud.githubusercontent.com/assets/1278021/19970458/4c40b05c-a1dc-11e6-92d3-2bfa469f9d03.png)
Fig. 1

The proposal is to avoid to completely prevent the user to download the layer, but allow the user to download just WMS images it he has "view" permissions and / or other raw data formats if he has "download" permissions instead.

Such improvement will consist also of a series of changes on the GeoNode logic and templates in order to check separately both the different user permission types and the layer output formats.

### Part 2: GeoServer Advanced Security Rules Refactoring
When creating / modifying layer permissions, GeoNode will update GeoFence rules accordingly through its REST APIs.

GeoFence enables GeoServer to check for permissions with much more granularity. GeoFence consists of a set of rules allowing GeoServer to check for Roles, Users, Services and Requests. That means that GeoNode can deeply control what to allow or deny to a single user or group of users against a GeoServer resource.

GeoNode resources signals will be intercepted and GeoFence rules updated accordingly.

## Related Issues

- #2085; Layer download should be consistent with layer permissions (https://github.com/GeoNode/geonode/issues/2085) 

- #2374; GNIP: GeoServer A&A Improvements (https://github.com/GeoNode/geonode/issues/2374)

## Feedbacks and Mail Discussion

- [ ] http://osgeo-org.1560.x6.nabble.com/Question-about-GeoNdoe-Layer-quot-view-quot-and-quot-download-quot-permissions-td5291692.html 

# Notes

1. http://docs.geoserver.org/latest/en/user/community/geofence-server/index.html

2. https://github.com/GeoNode/geonode/issues/2374 “GNIP: GeoServer A&A Improvements”

**Comment by jj0hns0n** [comment]
@afabiani can we update this one wrt to the new A&A work and what remains to be done to implement these types of security rules.

**Comment by afabiani** [comment]
This is completed with the new A&A merged on master branch.
