### ISSUE TITLE
Celery 4.0 released, breaking change due to incompatibility with django-celery

### ISSUE THREAD

**Issue by sarasafavi** [GeoNode/geonode#2700]
Celery 4.0 was released this weekend, and [internal API changes](https://github.com/celery/celery/blob/master/docs/whatsnew-4.0.rst#changes-to-internal-api) make it no longer compatible with django-celery (specifically, renaming of the `celery.utils.timeutils` module). Since GeoNode setup pulls in [the latest celery](https://github.com/GeoNode/geonode/blob/master/setup.py#L121), this causes a pip-installed GeoNode to fail on startup.

See also https://github.com/GeoNode/geonode/issues/2246; may be a good time to revisit that and remove our dependence on django-celery totally.

Relevant traceback for searchability:
```
Unhandled exception in thread started by <function wrapper at 0x7f08aefb3848>
Traceback (most recent call last):
  File "/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/env/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/env/lib/python2.7/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/env/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/env/lib/python2.7/site-packages/djcelery/models.py", line 15, in <module>
    from celery.utils.timeutils import timedelta_seconds
ImportError: No module named timeutils
```

**Comment by ingenieroariel** [comment]
Sara,

We could make sure that version is not pulled by using the same approach we
have with Django:

https://github.com/GeoNode/geonode/blob/master/setup.py#L55

**Comment by ingenieroariel** [comment]
BTW, I agree with you that we should just get rid of django-celery.

**Comment by sarasafavi** [comment]
@ingenieroariel of course - that or any similar solution would be a quick fix to this, so I imagine if that got PR'd there'd be no argument against merging. Pulling djcelery at the same time would be a nice bonus as well.

**Comment by pjdufour** [comment]
Why do you want to remove django-celery?  Aren't we dependent on it for async taks, such as sending emails?

**Comment by sarasafavi** [comment]
@pjdufour FYI "django-celery" the outdated Python package != "using Celery in Django"'; for more info reference docs at http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by pjdufour** [comment]
@sarasafavi thanks for clarifying.

**Comment by sarasafavi** [comment]
PR with celery version pin: https://github.com/GeoNode/geonode/pull/2708

I'm going to leave this issue open for now since we may address longer-term with the django-celery removal, as of that PR GeoNode master is alive & kicking again.

**Comment by sarasafavi** [comment]
Closing; fixed with version pin. Re-opening #2246 instead, to track removal of django-celery.
