### ISSUE TITLE
Geoserver admin can have 3 passwords at once

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2715]
Within a Geonode installation, Geoserver allows 3 different passwords for admin login:

1. Geonode admin password
* Set by python manage.py createsuperuser, changed via Geonode GUI
* Stored encrypted in the geonode:people_profile table in postgres

2. Geoserver admin password
* Changed via Geoserver admin GUI
* Stored encrypted in /var/lib/tomcat7/webapps/geoserver/data/security/usergroup/default/users.xml

3. Geonode OGC Server default admin password (‘geoserver’)
* Stored as as plain text in /home/geonode/geonode/geonode/local_settings.py
* Changed by editing this file and restarting Apache

This is confusing and potentially risky, as you can change a compromised password in one place (Geonode or Geoserver) not realising it still works because it’s also stored in another place.

**Comment by jondoig** [comment]
For one thing at least, the [manual install doco](docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html) should say to change the password in local_settings.py.

(Deleting this password doesn't work: it allows login with no password.)

**Comment by jondoig** [comment]
For one thing, the installation package, and [manual install doco](docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html), should include a step to change the default password in local_settings.py. I've included [that step](https://github.com/UNSW-CFRC/geonode_install/blob/master/install_geonode/9.1_add_apache_geonode_config.yml#L27) in my own Ansible playbook for Ubuntu 16.04.

**Comment by aaliceeee** [comment]
well done dude， thanks

**Comment by afabiani** [comment]
Hi created a documentation section explaining a bit how the security works here

https://github.com/GeoNode/geonode/pull/2746
