### ISSUE TITLE
Incorrect thumbnails and  Identification Image in docker-geonode v2.4

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#2718]
# Problem
I have setup an instance of docker-geonode version 2.4. I updated my Public_location url and all works fine except that the thumbnails generated still reference localhost hence they do not draw. 

# Part Solution
I have solved this by updating the  base_resourcebase table in the postgres database with a trigger which updates the thumbnail url.

**Comment by francbartoli** [comment]
@NyakudyaA does this continue to be an issue yet?

**Comment by NyakudyaA** [comment]
It is no longer an issue
