### ISSUE TITLE
Not uploading after removing the layer

### ISSUE THREAD

**Issue by FdeFabricio** [GeoNode/geonode#2723]
1) Upload a layer (example files: a.cst, a.dbf, a.prj, a.shp, a.shx, a.xml)
2) Delete the layer
3) Upload the same files again
4) The upload is successful but the layer is empty

But if you change de name of the files before uploading on the second time, it works fine.

1) Upload a layer (example files: a.cst, a.dbf, a.prj, a.shp, a.shx, a.xml)
2) Delete the layer
  **2 1/2) Rename the files (b.cst, b.dbf, b.prj, b.shp, b.shx, b.xml)**
3) Upload the same files again
4) The upload is successful and the layer is correct

**Comment by afabiani** [comment]
Hi this may happen when the JDBC cache on GeoServer side is not yet cleaned out. Usually a quick workround for this is to manually reload the GeoServer configuration before replacing the layer.
We discussed in the past about a way to allow GeoNode to hit a GeoServer refresh. Maybe a first rough implementation is already available on the latest GeoNode versions. Which version are you using?

**Comment by sarasafavi** [comment]
Closing for now; see Allesio's response above.
