### ISSUE TITLE
Complete migration of wiki to documentation

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2727]
To prevent further confusion. Im going to delete the wiki. The content is attached here.

[geonode.wiki.zip](https://github.com/GeoNode/geonode/files/615942/geonode.wiki.zip)

**Comment by harts-boundless** [comment]
Where are the GNIPs moving to now that https://github.com/GeoNode/geonode/wiki/GeoNode-Improvement-Proposals is gone?

**Comment by jj0hns0n** [comment]
We moved them to normal issues quite a while ago.
