### ISSUE TITLE
documentation, master branch: change displayed version number

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2739]
On local build it displays '2.0', recommend changing to 'master' or something like this

**Comment by harts-boundless** [comment]
This was probably discussed verbally as a task someone else will do, but I'm unsure where to expect "2.0".

To clarify, is this what is meant? (The "2.4" in this screenshot?)

![geonode_doc_ver](https://cloud.githubusercontent.com/assets/20508891/20788201/0b31a4ec-b7b0-11e6-968d-b6ebc545b3a9.png)

Also to clarify: is the issue that when the doc is built on master, and master is some commits ahead of the last major version (e.g. in this case 2.4) that it is inaccurate for the docs to give that version (e.g. 2.4)?

**Comment by d3netxer** [comment]
yes, I saw '2.0' where '2.4' was, but it was on an older version on my local machine before I remembered to do a git pull. 

About the clarification; I'm not sure what is better to display if the master is some commits ahead of the last major version.
