### ISSUE TITLE
Need a way to get IP address for GeoServer in Docker

### ISSUE THREAD

**Issue by waybarrios** [GeoNode/geonode#2750]
Best way to request geoserver url 
````
GEOSERVER_LOCATION = os.getenv(
    'GEOSERVER_LOCATION', 'http://localhost:8080/geoserver/'
)
GEOSERVER_PUBLIC_LOCATION = os.getenv(
    'GEOSERVER_PUBLIC_LOCATION', 'http://localhost:8080/geoserver/'
)
````
https://gist.github.com/waybarrios/22c8585da6d5a879d950735a39c71a09

**Comment by milafrerichs** [comment]
Docker is using their `docker-py` library in their `haproxy` 
Maybe we can use that as well to find the IP adress for the geonode to authenticate with the geoserver

http://docker-py.readthedocs.io/en/stable/
https://github.com/docker/dockercloud-haproxy

**Comment by waybarrios** [comment]
I just put default django container IP address on [geoserver.env](https://github.com/GeoNode/geonode/blob/master/geoserver.env#l4) 

I only have to link django into geoserver service on `docker-compose.yml`. Besides, `$DJANGO_URL` env variable is overwrite into `config.xml`from geoserver_data folder. The script that makes it possible is the [following](https://github.com/GeoNode/geoserver-docker/commit/d41cf9e785bb4609b2964b957212019c21c44004).

**Comment by waybarrios** [comment]
@francbartoli I think We need to close this issue, right? Or you're working on that?

**Comment by francbartoli** [comment]
Actually I have a solution in my pocket but I did not have time to work on that. But however we can close, I'll come with a PR later

**Comment by waybarrios** [comment]
Got it @francbartoli. I'll close it when you have all your work done!
