### ISSUE TITLE
The cart icon is misleading

### ISSUE THREAD

**Issue by cgiovando** [GeoNode/geonode#2760]
I understand that the cart icon next to each layer is used for selecting multiple layers and applying permissions or creating maps.

Seeing a cart icon, I expect some kind of shopping/transaction experience, which is not the case. I would suggest replacing the cart icon with selector check boxes.

**Comment by d3netxer** [comment]
I agree with this @cgiovando and have heard similar complaints from others. I wanted to do a mock-up but thought of other minor ways to improve the layout and selection options for layers; so I created a new issue. See #2762

**Comment by t-book** [comment]
+1 for choosing a clearer icon instead of a cart icon.
