### ISSUE TITLE
UI and functionality improvements to Layer Page header and selections

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#2762]
See current screenshot of demo GeoNode:

<img width="1326" alt="before" src="https://cloud.githubusercontent.com/assets/2665840/20833521/719ef230-b890-11e6-9b2b-d167d90ff1b6.png">

See My Mock-Up of how it can be improved:

<img width="1247" alt="after" src="https://cloud.githubusercontent.com/assets/2665840/20833527/85475df4-b890-11e6-9cd7-1110754932ef.png">

This is a list of what needs to be implemented:

- [x] replace title of layer selection box from 'Cart' to 'Selected Layers' (maybe add a little code to make it say 'Selected Layer' if only 1 layer is selected)
- [x] get rid of blank filler row in Selected Layer box
- [x] suggestion/idea: Change text of 'Total: x' to 'x layers found', Inspired how by Data.gov does it, the datasets found count can update dynamically according to what is being filtered. Also increase font-size to 16px. Align text better vertically with ordering box, and selection box.
- [ ] add selection box in Layer Table Header: arrow with the check box, where you can provide options to: Select all, Select this page, Select none
- [x] Have Layer Table Header boxes align to the right to match the Layer list
- [ ] Layer List: for the col-md-12 grid-spacer div, reduce margin-top of .grid-spacer to 10px from 30px; to reduce excessive white space
- [x] checkboxes: put in same row as titles to save space, replace shopping cart icons with checkbox icons: fa-check-square-o & fa-square-o

**Comment by pjdufour** [comment]
I can handle some of these.
