### ISSUE TITLE
PostGreSQL error when creating new Layer, Map, Document etc.

### ISSUE THREAD

**Issue by code-geek** [GeoNode/geonode#2764]
operator does not exist: boolean = integer
LINE 1: ...ng" FROM "base_resourcebase" WHERE ((is_published = 1) AND "...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.

This seems to be because of this portion
```
    'repository': {
        'source': 'geonode',
        'filter': 'is_published = 1',
        'mappings': os.path.join(os.path.dirname(__file__), 'pycsw_local_mappings.py')
    }
```

in pycsw_local.py

Specifically, editing line 49 to to 'filter': 'is_published = TRUE' fixed the issue

Fixed and sent a pull request
#2765

**Comment by simod** [comment]
@code-geek could you give more details on how you installed geonode, so that we can try to replicate it?

**Comment by code-geek** [comment]
Sure, I just followed [this tutorial](http://docs.geonode.org/en/master/tutorials/devel/devel_env/index.html).

**Comment by simod** [comment]
@tomkralidis any idea?

**Comment by code-geek** [comment]
Since #2763 addresses the same issue, I'm closing this one. Sorry for not noticing before.
