### ISSUE TITLE
Wrong pycsw_local sqlite check - Upload Layer broken

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#2771]
The following check

true_value = 'true'
if 'sqlite' in settings.DATABASE_URL:
    true_value = '1'

on pycsw_local class does not work correctly. Currently with this change it won't be possible to upload any layer on GeoNode with a PostGIS backend.

**Comment by tomkralidis** [comment]
@afabiani thanks.  Fix coming (see https://github.com/GeoNode/geonode/pull/2767#issuecomment-266720557)

**Comment by tomkralidis** [comment]
Fixed in master.

**Comment by afabiani** [comment]
@tomkralidis Thanks!
