### ISSUE TITLE
Add link back to GeoNode from GeoServer page

### ISSUE THREAD

**Issue by cgiovando** [GeoNode/geonode#2775]
Once the user goes to the admin GeoServer page, there is no link/button that leads back to GeoNode.

**Comment by jj0hns0n** [comment]
Note, I opened this ticket long ago. It would be good to have a unified header across geonode, geoserver and the geonode admin https://github.com/GeoNode/geonode/issues/907

**Comment by afabiani** [comment]
This could be feasible by customizing the GeoServer theme. In the simplest case it is just matter of producing some fancy CSS stylesheets.

**Comment by jj0hns0n** [comment]
@afabiani could we do this and just reuse the geonode header in our geoserver build?

**Comment by afabiani** [comment]
I can try to find a solution while working on GeoServer 2.10.x update.
