### ISSUE TITLE
poor resolution on GeoTIFF

### ISSUE THREAD

**Issue by aquilaimaging** [GeoNode/geonode#2776]
Hello,
I am having a problem with a geotiff I imported through the geonode interface. The file does not display correctly, it has a very low resolution & I am not able to zoom in very close. 

I checked it out in the openlayers preview from geoserver and it looks fine. I'm not sure why it is not rendering correctly in geonode interface. 

Can anyone explain or point me in the direction of a fix? 

GeoNode install details - Host OS: Ubuntu 14.04, Virtual Box: 5.1.10, VM OS: Ubuntu 14.04, GeoNode: 2.4.1

The geotiff is about 250mb

Thanks in advance! :)

**Comment by aquilaimaging** [comment]
I added a geotiff directly to geoserver then added the wms into geonode, thinking maybe it was not formating right when being added vis the geonode interface. But the problem persisted with this alternate method as well. 

This seems like I am i am missing some simple here...

Thoughts?

**Comment by capooti** [comment]
It would help to have a (smaller) dataset to replicate the problem.
From what you describe, though, it is not a problem related to GeoNode, but to GeoServer: correct?

**Comment by aquilaimaging** [comment]
@capooti 

> It would help to have a (smaller) dataset to replicate the problem.

I'm not sure what the data set size has to do with this problem. Care to clarify? 

> From what you describe, though, it is not a problem related to GeoNode, but to GeoServer: correct?

No, this is incorrect. Per my initial comment:

> I checked it out in the openlayers preview from geoserver and it looks fine. I'm not sure why it is not rendering correctly in geonode interface.

As far as I can tell this is a problem in geonode as the geotiff renders fine in the openlayers preview in geoserver. 


Now that those points are clear, can you or anyone else provide some guidance as to how to fix this?

**Comment by capooti** [comment]
Oh I see. This is because your layer cover a small extent and the default numZoomLevels for GeoExplorer is set to 20, which prevents your from being able to zoom in to a smaller area in your raster.
You should be able to override numZoomLevels in the javascript.

**Comment by aquilaimaging** [comment]
Ah ok. This was the other problem I was trying to sort out :) I'm glad to here my problem(s) are one in the same. I will try to sort out the zoom level. Thanks for your response and your time!
