### ISSUE TITLE
Remove corsheaders as a dependency

### ISSUE THREAD

**Issue by BerryDaniel** [GeoNode/geonode#2778]
The installed app `corsheaders` should be removed, since it has never actually worked and it is just adding a non essential package to GeoNode.

**Comment by BerryDaniel** [comment]
@afabiani is the app really needed for the updated A & A? Otherwise we should remove it as an installed app by default.

**Comment by afabiani** [comment]
Nope, we can remove it.

**Comment by capooti** [comment]
I think we can close this correct?
https://github.com/GeoNode/geonode/pull/2785/commits/99b1ae5e181645ac8c33eea8f6254f3810ef6509

**Comment by BerryDaniel** [comment]
Thanks for the reminder @capooti
