### ISSUE TITLE
Higher zoom levels in geoexplorer

### ISSUE THREAD

**Issue by aquilaimaging** [GeoNode/geonode#2781]
Hello,
I am attempting to add additional zoom levels to geoexplorer.

I found this reference: 
http://lists.osgeo.org/pipermail/geonode-users/2015-May/000408.html

Which led me to: 
http://gis.stackexchange.com/questions/91902/geoexplorer-setting-more-custom-zoom-levels

But I am not sure which file I need to modify and where exactly in the file I need to add the code. 

Would this be the correct file?:

`/usr/local/lib/python2.7/dist-packages/geonode/maps/templates/maps/map_geoexplorer.js`

And where would I add the code in the file after what line? 

Thank you in advance for any assistance!

**Comment by simod** [comment]
Hi, it should be this file https://github.com/GeoNode/geonode/blob/master/geonode/maps/templates/maps/map_geoexplorer.js.

Ps please use the mailing lists geonode-users@lists.osgeo.org to ask for support.

**Comment by M-abdelaziz** [comment]
Now with GeoNode 2.4 on windows i try to modify the file "C:\GeoNode-2.4.x\geonode-2.4.x\geonode\maps\templates\maps\map_geoexplorer.js" But with no luck

i tried to add the line:
numZoomLevels: 26, 

but with no effect at all

can someone guide me how to increase the default zoom levels for maps with higher resolutions,
Thank you in advance
