### ISSUE TITLE
DEFAULT_TOPICCATEGORY setting not working?

### ISSUE THREAD

**Issue by code-geek** [GeoNode/geonode#2786]
I'm trying to set a default for the topic category when editing metadata for a layer, document, etc. However, setting this does nothing: 

`DEFAULT_TOPICCATEGORY = 'location'`

So, I looked for "settings.DEFAULT_TOPICCATEGORY" in the codebase and can't find it anywhere. Is this a bug? What am I missing?

I'm following [this.](http://docs.geonode.org/en/master/tutorials/advanced/geonode_settings/settings.html#default-topiccategory)

**Comment by simod** [comment]
Hi it is indeed a docs bug, that setting doesn't exists anymore in geonode. Labelling accordingly. Thanks

**Comment by code-geek** [comment]
Is there an easy way to set a default category?

**Comment by simod** [comment]
No, I don't think so. Not straightforward at least :)

**Comment by capooti** [comment]
Maybe is not ideal for everyone, but I think it can be done by setting a default value at the database level if it is really needed. I have not tested, though
