### ISSUE TITLE
Add bibliographicCitation to metadata

### ISSUE THREAD

**Issue by ninsbl** [GeoNode/geonode#2803]
When people download or use data from GeoNode, they often wonder how to cite the accessed data. It would be great to have a "bibliographicCitation" metadata entry, as e.g. defined in 

- Dublin Core http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#bibliographicCitation or
- Darwin Core: http://rs.tdwg.org/dwc/terms/index.htm#dcterms:bibliographicCitation

However, I have no clear idea how that could be implemented in a clever way. Would be great if citation information could be compiled automatically from metadata already entered, e.g. according to a citation rule template (probably adjusted / refined by an admin if possible).

**Comment by pjdufour** [comment]
CC @tomkralidis
