### ISSUE TITLE
Enrich the metadata XML with attribute information of the layer

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#2810]
Downloading the metadata of a layer in ISO format, doesn't include the attributes of the layer (the description and the label of each attribute).

It would be useful to include these elements in the exported XML. What is the recommended workflow for this? As far as I know, pyCSW is used for the exporting of metadata in different formats; thus modifications would be needed on the pyCSW side. Is that right?

**Comment by kalxas** [comment]
I am not sure if the label of each attribute falls under the metadata scope.
In any case, we would need to figure out where is this handled in the ISO 19115 and then see if those elements are supported in OWSLib.

**Comment by tomkralidis** [comment]
I think the appropriate workflow to expose fields like this is when GeoNode saves an ISO document from scratch.  We'll have to ensure this is represented correctly in ISO proper and should not expect metadata exports other than ISO to support this feature.

**Comment by tomkralidis** [comment]
Looking deeper, here are the implementation specifics:

## Raster/GeoTIFF
- include the following in `geonode/catalogue/templates/catalogue/full_metadata.xml`
```xml
<gmd:contentInfo>
 <gmd:MD_CoverageDescription>
  <gmd:attributeDescription gco:nilReason="inapplicable"/>
  <gmd:contentType>
   <gmd:MD_CoverageContentTypeCode codeList="http://www.isotc211.org/2005/resources/Codelist/gmxCodelists.xml" codeListValue="image">image</gmd:MD_CoverageContentTypeCode>
  </gmd:contentType>
 </gmd:MD_CoverageDescription>
</gmd:contentInfo>
```
## Vector/Shapefile
- ISO 19115 dictates to specify attribute information via ISO 19110 via ONLY a reference, not inline
- include the following in `geonode/catalogue/templates/catalogue/full_metadata.xml`
```xml
<gmd:contentInfo>
 <gmd:includedWithDataset>
  <gco:Boolean>0</gco:Boolean>
 </gmd:includedWithDataset>
 <gmd:MD_FeatureCatalogueDescription>
  <gmd:featureCatalogueCitation xlink:href="http://host/geonode/layer/metadata/19110.xml"/><!-- NOTE: url TBD -->
 </gmd:MD_FeatureCatalogueDescription>
</gmd:contentInfo>
```
- the actual 19110 XML would be like this [example](http://www.isotc211.org/2005/gfc/resources/example/G_3.xml), returned by GeoNode when requesting a vector layer's feature catalogue.

**Comment by karakostis** [comment]
Thanks Tom. 
So no changes have to be made from the pyCSW side?

**Comment by tomkralidis** [comment]
@karakostis no, these are GeoNode enhancements.

**Comment by tomkralidis** [comment]
@karakostis FYI this has been implemented in master per https://github.com/GeoNode/geonode/issues/2810#issuecomment-271599357.   Can you try this out and report back?

**Comment by karakostis** [comment]
@tomkralidis I have integrated and tested your commit and works. Thank you for this. So far I haven't played with the catalogue application and takes some time to understand each component and how all bind together. I want also to add the **description**  and **label** of its attribute to the feature_catalog.xml. I see that the attribute's description is in layers_attribute table. I guess the way to go is -  in your layer_feature_catalogue() function - to filter by the layer_id and get the values from the model. And then pass them in the feature_catalogue XML. Does this approach makes sense?

**Comment by tomkralidis** [comment]
@karakostis thanks for the info.  Exactly.  We can sort out where they go in the ISO 19110 doc thereafter.

**Comment by karakostis** [comment]
@tomkralidis I have made some additions in your code. 

More specifically:

1. In the feature_catalogue.xml I've added the definition tag for **each attribute** as described in this [example](https://geo-ide.noaa.gov/wiki/index.php?title=ISO_19110_(Feature_Catalog)):

                 `<gfc:definition>
			<gco:CharacterString>{{ attribute.description }}</gco:CharacterString>
		  </gfc:definition>`

2. And in the layer_feature_catalogue() I've added the description of each attribute based on layer_id and attribute_name and pass it in the attr dicitonary:

`for attrset in layer.attribute_set.all():
        description = Attribute.objects.filter(layer_id=layer.id, attribute=attrset.attribute).values('description') **# addition 1**
        attr = {
            'name': attrset.attribute,
            'type': attrset.attribute_type,
            'description': description[0]["description"] **# addition 2**
        }`

This works quite well. Now I am trying to find a way to load these metadata in a layer in QGIS. That would somehow complete the circle of use case (download metadata from GeoNode and upload them to Desktop software). There are several plugins for importing metadata in QGIS but I am not sure if they successfully load the feature attributes as well. I will write here when have more info.

**Comment by tomkralidis** [comment]
@karakostis great to hear.  QGIS doesn't do anything with feature attributes (in metadata) currently.  My guess for a QGIS workflow is that this functionality would be deeper tied to the data source/provider.  From a pure metadata workflow,
