### ISSUE TITLE
Path issue with geonode-project

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2819]
When running paver start_geoserver in my custom geonode-project, there is a path problem and importing from myproject.settings the OGC_SERVER setting it is causing an import error.
I could fix it by adding the current path of the pavement file to sys.path: does it make sense to send a PR with this?

**Comment by simod** [comment]
I never use paver start, especially in projects. We could do this but usually write a shell script to start and shut down the machinery.

**Comment by capooti** [comment]
paver start_geoserver in this case, that is the way I use to start GeoServer.
I also do not use paver start, but start the django development server with runserver

**Comment by simod** [comment]
ah yeah, sorry, didn't mention. A script that runs geoserver from within the geonode_core folder :) sry
