### ISSUE TITLE
Metadata form requires TKeywords but not able to enter them

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2845]
<img width="685" alt="screen shot 2017-01-20 at 11 49 56" src="https://cloud.githubusercontent.com/assets/506078/22163279/0599badc-df07-11e6-8dba-67dc5de3f5e2.png">

@afabiani can you take a look?

**Comment by afabiani** [comment]
Patch available here: https://github.com/GeoNode/geonode/pull/2849

**Comment by jj0hns0n** [comment]
Thanks Alessio!
