### ISSUE TITLE
upgrade to 2.5

### ISSUE THREAD

**Issue by nephilimdie** [GeoNode/geonode#2854]
Dear developpers. i am part of team research in archaeology at Bologna university and we use for our purpose your framework geonode version 2.4 in ubuntu server. We discovered that 2.5 version is better than the older one but I can't figure out how to upgrade from 2.4 to 2.5. Could you explain me which way i have to take to change the version?and could you tell me if the data migration will be possible from one version to the other? or when will be possible to change the release?

i am sorry if this is not the right place where to ask these stuffs. otherwise write me where i can ask.

thanks in advance.
Stefano

ps: amazing project. :)

**Comment by simod** [comment]
Hi @nephilimdie. The 2.5 is still a testing version and the 2.6 stable will be out soon. We are working to include automatic migrations from 2.4 but is not ready yet. An official post will appear on geonode.org , twitter and mailing lists.

Ps the right place where to ask are the mailing lists Geonode-users@lists.osgeo.org. And Dev. :)
