### ISSUE TITLE
GeoNode 2.5.10 KeyError on logout using local_settings.py qgis sample

### ISSUE THREAD

**Issue by senoadiw** [GeoNode/geonode#2858]
Hi,

I'm setting up GeoNode with a QGIS Server backend and get the following KeyError when logging out:

![docker-geonode-qgis logout key error](https://cloud.githubusercontent.com/assets/1198399/22329448/db29793a-e3f3-11e6-9063-e58768b1de10.png)

I think LOGIN_ENDPOINT and LOGOUT_ENDPOINT should be added to local_settings.py.qgis.sample

OGC_SERVER = {
    'default': {
        'LOGIN_ENDPOINT': 'account_login',
        'LOGOUT_ENDPOINT': 'account_logout',
        'LOCATION': SITEURL + 'qgis-server/',
        'PUBLIC_LOCATION': SITEURL + 'qgis-server/',
        'LOG_FILE': '/tmp/qgis-server.log'
    }
}

Cheers

**Comment by jj0hns0n** [comment]
@senoadiw can you send a PR to add this?
