### ISSUE TITLE
not working on Intenet Explorer 9

### ISSUE THREAD

**Issue by schignel** [GeoNode/geonode#2863]
Version 9.0.8112.16421

![image](https://cloud.githubusercontent.com/assets/19474876/22379742/ce383174-e477-11e6-8c27-8760977a2780.png)

**Comment by simod** [comment]
I think that's correct, not sure we support ie9.

**Comment by ppasq** [comment]
We don't support IE9. The major issue is HTML5 and in particular the ability to select multiple files for a single HTML INPUT TYPE=FILE field which is not supported by IE9 or earlier versions. This affects the upload functionality. It can be solved with workarounds such as using Flash or Silverlight.
