### ISSUE TITLE
Tilted map going from 3D to 2D

### ISSUE THREAD

**Issue by schignel** [GeoNode/geonode#2864]
The map is permanently tilted when going back to 2D view from the globe.

![image](https://cloud.githubusercontent.com/assets/19474876/22380943/b377d3f8-e47c-11e6-9e2a-73821229cfe9.png)

**Comment by simod** [comment]
Hi this seems to belong to the new client, could you please reopen in this repo? https://github.com/GeoNode/geonode-client
