### ISSUE TITLE
Remove extra fields from layer download?

### ISSUE THREAD

**Issue by schignel** [GeoNode/geonode#2865]
When downloading as a shapefile or csv, the layer comes with a slew of extra fields--anyway to prevent these fields from coming down so the user doesn't have to manually delete them, or get confused?

![image](https://cloud.githubusercontent.com/assets/19474876/22381431/d1a89e00-e47e-11e6-923a-4aa48cac1e3f.png)

**Comment by simod** [comment]
Hi, Geonode is not adding any extra field to the shapefiles, they only contain what has been uploaded.

**Comment by schignel** [comment]
Ah thank you, my mistake! Closing now.
