### ISSUE TITLE
Raster file is not deleted when deleting a raster layer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#2867]
The coverage store is correctly removed in GeoServer, but the original file still stays in the GeoServer data directory.

When debugging, this code [1] seems to work well and does not raise errors, so most likely it is a bug (or a not implemented feature) of gsconfig?

[1] https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L307

**Comment by t-book** [comment]
I can confirm this. Data directory is growing and growing as Raster files stay present after delete.
@capooti  Is it worth to update the milestone?

**Comment by capooti** [comment]
@t-book yes, I updated to 3.0
not sure if REST API can be used to remove files

**Comment by t-book** [comment]
thanks @capooti It would be great to see this solved. It´s a bit annoying when one thinks a resource is deleted but some artefacts are left over. I´ll try to have a look at gsconfig. 

_If it´s helpful for somebody for a quick and dirty housecleaning of old raster files:_
```
  for dir in /your_path/data/*/*/
  do
      dir=${dir%/}
      name=${dir##*/}
      if ! [ -d "/your_path/workspaces/geonode/$name" ]
      then
          echo "$dir not found and deleted"
          rm -rf "$dir"
      fi
  done
```
