### ISSUE TITLE
Panels in detail pages appearing below metadata

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#2881]
<img width="860" alt="screen shot 2017-02-01 at 13 51 25" src="https://cloud.githubusercontent.com/assets/506078/22527878/ac73a930-e885-11e6-85a1-49957f06ed95.png">
<img width="1227" alt="screen shot 2017-02-01 at 13 51 47" src="https://cloud.githubusercontent.com/assets/506078/22527879/ac888328-e885-11e6-972d-137a21a83909.png">
<img width="1267" alt="screen shot 2017-02-01 at 13 51 58" src="https://cloud.githubusercontent.com/assets/506078/22527880/ac92f2ae-e885-11e6-9402-1185daf02693.png">

**Comment by ppasq** [comment]
Sorry, the fix has not been ported in master yet.
