### ISSUE TITLE
View Map: Layer without view permission is displayed as broken (pink) tile images

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2888]
In Geonode 2.4, a layer for which I have no view permission is displayed as broken images (pink tiles) when viewing a map that contains it:
![image](https://cloud.githubusercontent.com/assets/4666409/22574804/72279ee0-ea05-11e6-9565-a0ed40c571d2.png)

Perhaps it should be greyed out:
![greyedout](https://cloud.githubusercontent.com/assets/4666409/22574766/215aad18-ea05-11e6-9e77-13a6bc545013.PNG)

...with a tooltip:
![hover](https://cloud.githubusercontent.com/assets/4666409/22574769/27ec3ab6-ea05-11e6-90ef-d637fdbb047a.png)

**Comment by simod** [comment]
closing as this will be fixed in the new client

**Comment by jondoig** [comment]
Yay thanks! Good to hear.
