### ISSUE TITLE
Uploading shapefiles issue

### ISSUE THREAD

**Issue by Ogilo** [GeoNode/geonode#2895]
Hi i have issue with uploading a shapefile to a fresh geonode 2.4 installation on ubuntu 14.04. whenever i try uploading a shapefile i get the error: 'NoneType' object has no attribute 'name'.

Any help on debugging this?

**Comment by simod** [comment]
Hi, seems to be an issue with the style.

Could you please move this to geonode-users@lists.osgeo.org adding some more info like the full stacktrace of the error?
