### ISSUE TITLE
Private data is publicly visible at /uploaded/layers

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2896]
In Geonode 2.4, all uploaded data can be listed and downloaded from `http://<host>/uploaded/layers` regardless of security permissions.

This seems to be by design. The [installation doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/setup_configure_httpd.html) says to make it all wide open:

```
sudo chmod -Rf 777 /home/geonode/geonode/geonode/uploaded/thumbs
sudo chmod -Rf 777 /home/geonode/geonode/geonode/uploaded/layers
```

Removing ‘other’ permission (chmod 770) breaks the upload function.

**Comment by jondoig** [comment]
At least we can make it a bit harder by denying directory listing in the Apache config. I.e. change the [installation doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/setup_configure_httpd.html#apache-configuration) from:

```
    <Directory "/home/geonode/geonode/geonode/uploaded/layers/">
        Order allow,deny
        Options Indexes FollowSymLinks
        Allow from all
        Require all granted
        IndexOptions FancyIndexing
    </Directory>
```
to
```
    <Directory "/home/geonode/geonode/geonode/uploaded/layers/">
        Order allow,deny
        Options -Indexes +FollowSymLinks
        Allow from all
        Require all granted
    </Directory>
```

(...and same for the other directories configured there.)

But it's still not hard to infer the actual filenames and download them without listing the directory.

**Comment by simod** [comment]
Hi, the uploaded/layers directory doesn't have to be served by apache, it only needs write permissions. Thumbs on the other hands need to be publicly available. If the doc says that uploaded has to be served then we need to fix it.

Thanks

**Comment by jondoig** [comment]
OK so I've made a [pull request](https://github.com/GeoNode/geonode/issues/2899) to fix the [manual install doco](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/setup_configure_httpd.html#apache-configuration), but the same change may be needed to other install methods ...Quick install? Ansible? Other?

**Comment by simod** [comment]
Thanks I've also  fixed it at package level see https://github.com/GeoNode/geonode/commit/dedd939909104b88af4af97b744b334896c819a1
