### ISSUE TITLE
Draw a point onto the map

### ISSUE THREAD

**Issue by jjgallow** [GeoNode/geonode#2905]
Hi there, we are experimenting with the use of Geonode, and have done some customization so that from the map view, it can search for attributes and zoom in on the results (using a bounding box URL parameter fed to the map...   ?bbox=).

It does this well, but then the feature is not highlighted (and it may search across over 100 layers, rather than just one).     

Is there a way either highlight a feature, or Equally helpful...**.just draw a Dot or something in the center of the bounding box?**

OR, Maybe a better way of asking this question:  Can either SLD variable substitution or Geoserver Paramatrized views be carried through to Geonode?
http://docs.geoserver.org/2.2.4/user/styling/sld-extensions/substitution.html
http://docs.geoserver.org/stable/en/user/data/database/sqlview.html

I see that it's in the Geonode Tutorials, but the URL paramaters don't seem to be honored with Geonode?
http://docs.geonode.org/en/master/tutorials/advanced/adv_data_mgmt/adding_data/add_sqllayers.html

Thank you kindly

**Comment by capooti** [comment]
Please, could you post this to the mailing list? thanks

**Comment by jjgallow** [comment]
I can of you like....but considering you have url parameters in your
tutorial and they don't work...is that not a bug?

Maybe I should reword it?

**Comment by capooti** [comment]
Can you expand the concept about having url parameters which don't work? Not sure I understand. Thanks a lot

**Comment by jjgallow** [comment]
Sure.  Maybe what I should have started with was this, from geonode's tutorial on Parametric View layers:

http://docs.geonode.org/en/master/tutorials/advanced/adv_data_mgmt/adding_data/add_sqllayers.html

Parametric View based layers are incredibly powerful and flexible, and would be one solution to my specific problem, as well as possibly a good solution to a broader scope of problems.

At the bottom of the tutorial, it shows this:

_**"At a first glance you won’t see anything since the layer is using the default parameters for the observation years. Specify two years for the view adding this parameter at the end of the GetMap Request:

&viewparams=MIN_OBS_YEAR:2000;MAX_OBS_YEAR:2000"**_

This works in geoserver, but the url parameters do not persist in geonode.  Would it be possible to get these to persist in geonode, or is there a way for them to now?

thanks

**Comment by capooti** [comment]
Well, that documentation seems incomplete. After having the view in GeoServer you should be able to register it in GeoNode using the updatelayers command.

**Comment by jjgallow** [comment]
Yes, you can, that is true.  Except that the purpose of the view is to
dynamically change the results via paramaters in the url.   And this does
not currently persist in geonode, thus the view does not function.

 Not sure if that makes sense...does that help explain the issue?

**Comment by capooti** [comment]
Well, while definitely a view is fully supported in GeoNode, view parameters are not implemented in the client, you are right, but it is possible to do it if needed by customizing it.

**Comment by jjgallow** [comment]
Thank you Paolo,

I have a small amount of customizing geonode...ie...customized the search
to our internal databases.

Could you point me in the right direction, and I'll post the code back?

**Comment by capooti** [comment]
You will need to customize GeoExplorer (or the client you are using) for getting that.
