### ISSUE TITLE
User is still authenticated in geoserver after logging out when geonode is behind a proxy server

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#2914]
Steps to reproduce:

1. login django
2. navigate as authenticated user into geoserver (jsessionid is created with path /geoserver)
3. logout django
4. navigate /geoserver --> user is still authenticated (jsessionid is still valid)
5. firing off jsessionid then the user is out

**Comment by francbartoli** [comment]
Side effect of this is also that if two different users are going to access from the same browser:

1. the first one does logout after browsing into geoserver
2. the second one does login into geonode and if he/she goes to geoserver is authenticated as the first one

**Comment by afabiani** [comment]
https://github.com/GeoNode/geonode/pull/2962

Along with GeoServer commit https://github.com/geoserver/geoserver/commit/94ea2c0047f6367ce02a2462bde053565f7999fb

**WARNING:** You need to update GeoServer too, at least the OAuth2 Plugin

http://ares.boundlessgeo.com/geoserver/2.9.x/community-latest/geoserver-2.9-SNAPSHOT-sec-oauth2-geonode-plugin.zip

**Comment by francbartoli** [comment]
Hi @afabiani, not yet tested but I don't see this commit on our internal repository, what does it mean?
Is something changed in the meantime from the last release for our internal build process?

**Comment by afabiani** [comment]
Hi @francbartoli I'm not sure to understand the question. You mean in GeoServer? If so the commit has been merged on GeoServer community modules and the WARs of GeoNode rebuilt through Jenkins jobs. Is that what you were asking?

**Comment by francbartoli** [comment]
Yes, now I have figured out the build, as the change impacted a community module which is used by the vanilla geoserver. So that means now the oauth security piece of geonode is part of the standard geoserver code, is that correct?

**Comment by afabiani** [comment]
@francbartoli yes, correct.

**Comment by francbartoli** [comment]
@afabiani thanks, I'll try to do some tests asap and get back feedbacks

**Comment by francbartoli** [comment]
tested successfully. Thanks @afabiani

**Comment by francbartoli** [comment]
I reopen this issue editing its description since it is still present if geonode and geoserver are published behind a proxy server
