### ISSUE TITLE
Open public folder for downloads

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#2915]
Some people would rather just see a download folder full of zips.

Make data downloadable from a public download folder for http and ftp access.

Add a Private subfolder which when opened redirects to the login screen of Geonode, then to the layers tab on login.

One scenario when this would be crucial is to allow rapid and easy bulk download for off-site backup, as is now being done with difficulty by hackers to preserve NASA data.

**Comment by pjdufour** [comment]
It's easy enough to write scripts to download all the data off a GeoNode.  Just 50 lines of python or something like that by parsing CSW and making wfs calls.

**Comment by capooti** [comment]
It depends also on the GeoServer WFS maximum number of features settings: by default is very large (1,000,000) but it is generally suggested as a best practice to keep it low in the GeoServer documentation (the Java process could freeze GeoServer). I am not sure if, when this limit is less than the layer's total feature number, there is an easy way to paginate the features to download. Here someone suggests to tile the extent and generate the requests: http://gis.stackexchange.com/questions/153774/how-to-request-paginated-or-filtered-data-from-wfs-2-0
In any case the script would be more complicated than what we could think in such a case.
Let me add that download services should not rely on WFS, and an alternative solution for GeoNode would be really needed.
