### ISSUE TITLE
Error: Module: 'earth' not found!

### ISSUE THREAD

**Issue by gonrial** [GeoNode/geonode#2921]
Visiting the demo site: http://demo.geonode.org/maps/272
Click on _3d View_
See the error
```
https://www.google.com/jsapi?autoload=%7B%22modules%22%3A%5B%7B%22name%22%3A%22earth%22%2C%22version%22%3A%221%22%2C%22callback%22%3A%22gxp.plugins.GoogleEarth.loader.onScriptLoad%22%7D%5D%7D
```
I found related information from http://stackoverflow.com/questions/42007768/google-maps-api-uncaught-error-module-earth-not-found

Is it possible to disable _3d view_?

**Comment by gonrial** [comment]
Possibly adding the line `config.viewerTools.splice(10,1);` to all these branches?

https://github.com/GeoNode/geonode/blob/2.0.x/geonode/templates/geonode/geo_header.html#L24
https://github.com/GeoNode/geonode/blob/2.4.x/geonode/templates/geonode/geo_header.html#L24
https://github.com/GeoNode/geonode/blob/2.5.x/geonode/templates/geonode/geo_header.html#L24
https://github.com/GeoNode/geonode/blob/2.6.x/geonode/templates/geonode/geo_header.html#L24
https://github.com/GeoNode/geonode/blob/master/geonode/templates/geonode/geo_header.html#L24

**Comment by simod** [comment]
@bartvde any comments on this one?

**Comment by bartvde** [comment]
yeah I would take out the tool
