### ISSUE TITLE
Unable to update a layer (replace action) nor create a new layer with the same name of a already deleted layer

### ISSUE THREAD

**Issue by marco-jem** [GeoNode/geonode#2932]
Hello, I tried to replace a layer uploading a shapefile, after action completed (without reporting ANY error in the web UI) I accessed the layer all the shapes in the layer are gone and:
- the layer preview map displays the world map and nothing else
- the PostgreSQL table containig layed data does not exist anymore
- the layer is still listed among available layers both in GeoNode and GeoServer
- the layer were originally uploaded using a shapefile and it was working as expected
- I'm 100% sure the shapefiles I uploaded are good (opened both with QGis and works properly)
- it does not matter if the data in the shapefile is the same as the original data or completely different, same result
- it does not matter if the name of the shape file is the same of the layer or not
- no error reported by GeoNode (as per apache error.log)

I also tried a little experiment and find out that it seems to be an issue related to the name of the layer, this is the experiment:
1) create a new layer named "my_test_layer"
2) assess that "my_test_layer" is working and data is properly diplayed (it was working)
3) delete "my_test_layer"
4) assess that "my_test_layer" is not listed anymore in layers list of GeoNode and GeoServer, also the DB table has been deleted
5) upload new data using a different shapefile but using "my_test_layer" again as the layer name
6) layer does not work anymore, DB table with the name of the layer does not exist

I'm using GeoNode 2.4.0+thefinal0, Ubuntu 14.04 and PostgreSQL 9.3 +  PostGIS 2.1.2+dfsg-2ubuntu0.1

I have attached the DB log of the layer update and the experiment with same-name layers and the shapefile I used for the tests.

[log_layer_replace.zip](https://github.com/GeoNode/geonode/files/801874/log_layer_replace.zip)
[log_layer_same_name.zip](https://github.com/GeoNode/geonode/files/801875/log_layer_same_name.zip)
[shp_prova_fogli_catastali.zip](https://github.com/GeoNode/geonode/files/801876/shp_prova_fogli_catastali.zip)

Thanks a lot!

**Comment by simod** [comment]
@afabiani could this depend from geoserver?

**Comment by afabiani** [comment]
Most probably the JDBC connection on GeoServer has not yet released at the time of replacing the layer.

Please try to do like this:

1. Delete the layer from GeoNode
2. Restart GeoServer
3. Upload the layer again

That should work.

**Comment by marco-jem** [comment]
OK, I'll give it a try this evening when I get home ....I'm at work at the
moment.

Stay tuned ;)

2017-02-27 10:13 GMT+01:00 Alessio Fabiani <notifications@github.com>:

**Comment by marco-jem** [comment]
Good morning! 
I confirm it's a problem related to GeoServer, here the details of the tests I performed:

Test 1: replace layer
1) open the selected layer and click on edit -> replace
2)  shutdown GeoServer and wait for 10 seconds 
3) start GeoServer
4) upload shapefile and complete the replace action 

The layer was successfully updated! 

Test 2: upload a layer with the same name of an already deleted one

1) create a layer called "MyLayer" and check it is working correctly 
2) delete the layer "MyLayer" 
3) shutdown GeoServer and wait for 10 sec
4) start GeoServer 
5) create a new layer called "MyLayer" 

Again the layer was successfully created!

Any ideas about a solution to this problem? 

I saw GeoNode 4.1 is out, is it also affected by this problem? 

Waiting for news from you, if more details are needed (log files or whatever) just ask to me! 

Thanks a lot.

**Comment by afabiani** [comment]
Well, unfortunately this is not a trivial fix to achieve. It requires changes to GeoServer and improve the communication of events between GeoNode and GeoServer.

Basically this caused by the JDBC Datastore of GeoServer retaining the connections for an amount of period.

In theory would be possible to mitigate the issue by tweaking a bit the GeoServer JDBC pool configuration and the DB sessions.

I know there is some work in progress on the JDBC library of GeoServer (GeoTools) but I would need to spend at least a couple of days investigating and implementing a good solution for this issue.

**Comment by marco-jem** [comment]
By the way ....could my issue be related to this one?

https://github.com/GeoNode/geonode/issues/2462

**Comment by marco-jem** [comment]
NEW!
Trid fo apply the fix suggested by @afabiani and it solves this issue! I thinks this bug and bug #2462 reported by @afabiani are related to the same problem.

If you confirm my hypothesis I think this bug report could be linked to #2462 and closed, what do you guys think about this?

**Comment by blackgis** [comment]
Hi all, i run into the same. 
@marco-jem  where exactly and how did you write the cat.reload(). Can you post a short example of your helpers.py.

**Comment by marco-jem** [comment]
@blackgis here it is!
[helpers.zip](https://github.com/GeoNode/geonode/files/828535/helpers.zip)

You can find the added code at line 1054

**Comment by blackgis** [comment]
@marco-jem thank you! After a restart of Tomcat it starts working as suggested. Saved my day.

**Comment by capooti** [comment]
Currently, I am noticing a regression, and I am experiencing this issue again (when uploading a new layer), as reported today in GeoNode list: 
https://lists.osgeo.org/pipermail/geonode-devel/2019-September/002905.html
