### ISSUE TITLE
Legend is not updated accordingly to the selected style

### ISSUE THREAD

**Issue by blackgis** [GeoNode/geonode#2942]
Hi all,
I have a lot of layers with more than one style. When switching between them the map is correctly updating  but not the legend area, which keeps showing the 'default' styles information.
In the first everything is as expected:
![style1_nolegendupdate](https://cloud.githubusercontent.com/assets/7139491/23753609/69691014-04da-11e7-8d1f-b11e07eeacf6.jpg)

in the second the map is updated to the selected style but not the legend:
![style2_nolegendupdate](https://cloud.githubusercontent.com/assets/7139491/23753614/6fb28360-04da-11e7-9fc8-7f572042fd68.jpg)

same here, legend area is not updated
![style3_nolegendupdate](https://cloud.githubusercontent.com/assets/7139491/23753625/762a9a20-04da-11e7-80dd-e5e39b87a136.jpg)

Here are the slds from the styles: [SLDs.zip](https://github.com/GeoNode/geonode/files/831060/SLDs.zip)

What can I do to make this working?

**Comment by capooti** [comment]
I am having a look at this

**Comment by blackgis** [comment]
@capooti in general it is working but i get the not found symbology in the legend area because in the wms url of the changed file a fixed layer is used. instead of LAYER=geonode:subwaylines_p_odp there should be Layer={{something which take the really acutal layer??}} look here: https://github.com/GeoNode/geonode/pull/2944/commits/be3b6bc72aa0c1e834ba0d1376f55e375b472aba

**Comment by capooti** [comment]
OK I will look into that other issue later
