### ISSUE TITLE
Default style is not used when loading the page

### ISSUE THREAD

**Issue by blackgis** [GeoNode/geonode#2946]
Hi all,

I have this problem with all my layers, so it is not limited to this example,  but for better understanding:

I uploaded a layer (shp) called **dwellings_kule_tierkidi2**. The default style is called 'dwellings_kule_tierkidi2'. For dwellings i already have a style I use for an other layer too. In 'Manage Styles' I search for the style called 'Dwellings simple style' and assign it to the layer, finally I set it as 'Layer Default Style'.
![manage style interface](https://cloud.githubusercontent.com/assets/7139491/23796086/3752be94-0599-11e7-9f9a-c4323daf9d62.jpg)

With Update Available Styles i return to the site/layer and the legend area is correct and the styles area, but no update in the map! The radio button of my default style is acitve, but...
![default style is set in legend and styles but not in maps](https://cloud.githubusercontent.com/assets/7139491/23796124/8b25c69c-0599-11e7-893d-9d5927c877fc.jpg)

When  I manually click on the radio button (which is already selected!!) the map gets an update too and every thing is as it should be. Except the legend icon issue I already explained in Legend is not updated accordingly to the selected style #2942 
![default style is set in legend and styles and by selecting the radio button also in maps](https://cloud.githubusercontent.com/assets/7139491/23796152/c24ac42e-0599-11e7-9cb4-05fa1837bee1.jpg)

What can cause this, that the default style is not represented in the map? Is the geoserver missing that there is another default style chosen as this one that was created during the initial upload? This behavior is not only when chosing the default style, but also on reload of the layer side.

**Comment by capooti** [comment]
So, you experience the problem only when changing the default style, correct?

**Comment by blackgis** [comment]
Yes, the initial style of the layer is always the first which is presented  in the map doesn't even matter if it is in available styles or not ..

**Comment by blackgis** [comment]
@capooti Thy for fixing the legend icon staff: https://github.com/GeoNode/geonode/commit/307dbb4d0ec6429d061964d8a7594acd50d2c8f8

Sorry I was wrong, it is not limited to changing the style only, because what I wanted to demonstrate here was, that when I re/load the page, I got it like in the first picture, the map is not showing the default style it is showing the style in the map which was created during upload of the layer, so in the very beginning, but this isn't the default one anylonger because I defined a new one. I can manually fix that by selecting the already default style again, but thats not the way it should work. When loading a page, the default style (which I selected in the settings should be the default style) should be in the map, legend and style the default one. Unfortunately, the map misses that information. 
When having a look into the WMS, Style, when loading the page, the WMS haven't any style information at all: GetMap&STYLES=&FORMAT so no wonder why it uses the style from the upload session instead of the defined default.
When selecting the active default style manually by selecting the radiobutton, the WMS use than immediately the correct style: GetMap&STYLES=buildings_lapilang_may2015_03ce9e5b&FORMAT=image%2

How can we overcome this issue, because obviously there is something wrong in the settings of the WMS and STYLE, I guess in the general setting of assigning style information to the layer, because there isn't any style assigned by default (STYLES=&), because the system knows the default, but when defining a new default for the layer we run into this issue I am describing. Maybe it makes sense to assign the style information also in the very beginning instead of leaving empty and in the settings area of defining a new default (very first picture) the style has to be updated accordingly in the WMS url generation too.

Can you help me to get the 'Update Available Styles' work as expected.

**Comment by capooti** [comment]
@blackgis this is fixed, but you need to use the 2.6.x branch for now

**Comment by blackgis** [comment]
@capooti Thank you all, I changed the views.py and now it works as it should.
