### ISSUE TITLE
Error saving metadata

### ISSUE THREAD

**Issue by alaw005** [GeoNode/geonode#2948]
I get the following error when saving metadata. I thought it was to do with the django caching but I changed this to memcached but still the error.  I have the 'notification' app enabled for user registrations.

If I give full access (chmod 777) then error changes to one following

LockFailed at /layers/geonode:layer_name/metadata
failed to create /var/www/server_name.Dummy-1-23375
Request Method:	POST
Request URL:	http://geo.example.com:443/layers/geonode:layer_name/metadata
Django Version:	1.6.11
Exception Type:	LockFailed
Exception Value:	
failed to create /var/www/server_name.Dummy-1-23375
Exception Location:	/usr/lib/python2.7/dist-packages/notification/lockfile.py in acquire, line 249
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www']

AttributeError at /layers/geonode:layer_name/metadata
'NoneType' object has no attribute 'name'
Request Method:	POST
Request URL:	http://geo.example.com:443/layers/geonode:layer_name/metadata
Django Version:	1.6.11
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'name'
Exception Location:	/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py in save_style, line 791
Python Executable:	/usr/bin/python
Python Version:	2.7.6
Python Path:	
['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www']

**Comment by francbartoli** [comment]
@alaw005 which geonode version are you using? It looks like from your log that django is a version no longer used by the master and 2.6.x code as you can see from setup.py

**Comment by afabiani** [comment]
Currently on GeoNode 2.6.x + saving metadata is also broken if you try to update the keywords due to this 
https://github.com/GeoNode/geonode/issues/2967

**Comment by simod** [comment]
I'll take a look tomorrow.

**Comment by simod** [comment]
@afabiani I cannot replicate this on 2.6. I can add keywords through the admin

**Comment by Bonob0b** [comment]
Using django-taggit==0.18.0 solves the error 
`Exception` Value: null value in column "depth" violates not-null constraint 
which is related to the keywords. The problem is that django-taggit version in the setup.py is 
`django-taggit>=0.21.0`. 
I don't know why version 0.18.0 solves the error. (version of django : 1, 8, 7, 'final', 0).  I don't know if using version 0.18.0 would cause other problems.
