### ISSUE TITLE
backup/restore db dump should use actual user for selecting tables

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode#2987]
DB dump should use owner name from settings (or name provided in settings.ini/cli options) for db tables to dump: https://github.com/GeoNode/geonode/blob/2.6.x/geonode/base/management/commands/helpers.py#L114

Also, instead of series of pg_dump calls, one call can be performed with tables list (``-t`` switch in ``pg_dump``)

**Comment by afabiani** [comment]
Fix for this here

https://github.com/GeoNode/geonode/pull/3031
