### ISSUE TITLE
restore command: allow work with unpacked data

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode#2988]
Restore command should allow to work with unpacked backup directory. User may want to tune backup data, but it requires additional packing/unpacking cycle to make restore command to use modified data. Restore could easily skip unpack step and work on decompressed data.

**Comment by sebastianlach** [comment]
Added --backup-dir argument to restore command: https://github.com/sebastianlach/geonode/tree/feature/%232988-restore-dir
