### ISSUE TITLE
backup/restore: order of fixtures

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode#2989]
When restoring fixtures, order matters. It seems resourcebase is restored before restoring spatialrepresentationtypes, causing integrity errors during restore: https://github.com/GeoNode/geonode/blob/2.6.x/geonode/base/management/commands/settings.ini#L12

**Comment by sebastianlach** [comment]
Correct fixtures order: https://github.com/sebastianlach/geonode/tree/feature/%232929-fixtures-order
