### ISSUE TITLE
Consumer crashes with JSON error.

### ISSUE THREAD

**Issue by atrawog** [GeoNode/geonode#3000]
I'm having a strange problem in master with manage.py importlayers when I'm uploading multiple Tiff images.

When I start the import all images get imported in Geonode but only the first image gets imported in Geoserver too. After the Geoserver import the new consumer crashes with an error like:

`  File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: Decimal('1770659.1781685699') is not JSON serializable
`

When I restart the consumer the next images get imported in Geoserver resulting in another crash of the consumer.

` File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
kombu.exceptions.EncodeError: Decimal('942057.3754955460') is not JSON serializable
`

**Comment by simod** [comment]
Hi, we don't suggest to use master but 2.6.x. Master is very unstable.

ps could you please use the mailing list geonode-users@lists.osgeo.org instead of here?
