### ISSUE TITLE
Recommended server specs for GeoNode instance

### ISSUE THREAD

**Issue by cgiovando** [GeoNode/geonode#3003]
Would be useful to have a set of minimum and recommended server specifications for GeoNode instances, both for a cloud environment setup (virtual host) and a physical/local server.

Please @afabiani draft an initial page to add to the general GeoNode documentation. Thanks!

CC @jj0hns0n @vdeparday @ppasq

**Comment by jj0hns0n** [comment]
This is probably still pretty accurate.

http://docs.geonode.org/en/master/tutorials/admin/install/custom_install.html#recommended-minimum-system-requirements
