### ISSUE TITLE
New Homepage Template: Metadata + Information Ontology + Site Structure Supersede UI

### ISSUE THREAD

**Issue by kangell50** [GeoNode/geonode#3017]
# Information Ontology, Site Structure + Metadata

> “I expected to find Banks in ‘buildings’ not ‘location’ category.” – Participant 4

**The logic of the site structure supersedes the UI**

### Needs:
_If there is an ontology, it must be a robust ontology. Help people understand where they are on the site._ 
_Simplify the exploration icons in the “icon area,” they are currently too complicated and their ontology is not clear. For example, reduce the number of icons, or sub-categorize and nest them; remove hover text and place it on a dedicated category page that is linked from the icon. This suggests the need for a new view within search that shows and explains dataset relationships. Fix the category names and subject headers, such as the exploration icons section should be retitled as “suggested searches,” to match the function of the icons. The “data stories” section works well._

### Issues:
The ontology of the site does not match users’ mental models for the data’s ontology (subject categories that show their properties and inter-category relationships). One participant, tasked with finding a dataset of banks, clicked the buildings icon in the icon area. (This actually created a search filtered by society – see next result below). No bank dataset was in the returned list, but police stations and restaurants were. They commented “I expected to find Banks in "buildings" not "location" category. It would be easier to have searched from the homepage I think.” 

**This pattern of choosing a representational icon and failing to find the targeted data was seen across all users who entered through the category icons.**

### Recommendations: 
1. Banks should be under buildings. They belong with police stations and restaurants. This identifies a search/filter issue within the logic of the site. While metadata problems are outside of the scope of this research, it is an important reminder that the design decisions based on the underlying structure of a site – and especially of a searchable dataset archive – are only as good as the robustness and accuracy of that structure. Without a strong structure the design usability will never meet the demands of the user.
2. Icons based on categories must be connected to the information architecture of the site, including metadata, tags, and content. See below for more details.

### About the Study:
The World Bank's GFDRR funded an analysis on the usability of the new homepage template (GeoNode version 2.6) as implemented on the Malawi Masdap GeoNode. Code to record visitor actions was added to copies of both the new and old Malawi GeoNode sites. Invited participants were recorded interacting with the site, and their feedback on the site's usability solicited. For the duration of the study every user had their interactions with the site recorded. The resulting data collected includes the duration of site visits, the order of pages and time on each page, as well as click and mouse movements. You can view the report below. 

### Reference:
#https://github.com/GeoNode/geonode.github.com/blob/master/docs/GeoNode_Home_Page_Uability_Analysis_draft.pdf

**Comment by jondoig** [comment]
The Reference link gives a [404](https://github.com/GeoNode/geonode.github.com/blob/master/docs/GeoNode_Home_Page_Uability_Analysis_draft.pdf).

**Comment by rob-metalinkage** [comment]
As part of the MapStory application of GeoNode I needed to be able to better handle ontologies - to support data translation cross-walks - but basically its the same problem.  I used the standard SKOS data model for this and upgraded an existing module to play nice in the more general django, and GeoNode environments - and linked it to RDF stores to support SKOS based Linked Data interfaces. 

The alpha version is here: https://github.com/rob-metalinkage/django-skosxl

upcoming project extension will include bringing this as an optional, fully functional and easy to install extension to GeoNode. 

Consequently I recommend not hard-coding the ontology - but make it user editable content - even if the default user is the site admin.

**Comment by rob-metalinkage** [comment]
Further, regarding " This suggests the need for a new view within search that shows and explains dataset relationships. "  the gazetteer module is generating one possible source of relationships, based on existence of common individual features in multiple layers:

https://github.com/rob-metalinkage/django-gazetteer

A metadata based approach to describing how data sets relate will need to be based on the "dimensions" of data sets - are they two slices through a hypercube - e.g. 2000 and 2010 data (slicing on the time dimension, whilst the geographic and subject dimensions are common - lets say countries).

Some preliminary work on the data model for such metadata is here: 
http://w3c.github.io/sdw/qb4st/

(and I have a spike solution for a django module that handles editing these: https://github.com/rob-metalinkage/django-dataweb)

Note this uses the SKOSXL module to handle subject dimensions ;-)

Happy to talk about how to take this forward - currently looking for project funding to complete these and bring through the OGC/W3C standards processes.
