### ISSUE TITLE
Problem Install Geonode 2.5.15

### ISSUE THREAD

**Issue by izelvor** [GeoNode/geonode#3026]
Hello,
I would like to install geonode 2.5.15 on my computer in Ubuntu 14.04
I try to install it with :
sudo add-apt-repository ppa:geonode/release
sudo apt-get update
sudo apt-get install geonode
But it's not working.
Could you help me please ?
How to install geonode version 2.5.15?

**Comment by simod** [comment]
Hi on ubuntu 14.04 you can install geonode 2.4 by using ppa:geonode/stable.

geonode 2.6rc1 is available in ppa:geonode/testing on ubuntu 16.04 (not released yet)

ps please use geonode-users@lists.osgeo.org to ask for support.
