### ISSUE TITLE
Geonode broken dependencies

### ISSUE THREAD

**Issue by jcaceres85** [GeoNode/geonode#3034]
Hi,
I'm making a fresh install of geonode ob ubuntu trusty, following the quick installation guide instructions, and after the "... install geonode"  line, I get this error:

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 geonode : Depends: postgresql-9.1-postgis but it is not installable or
                    postgresql-9.3-postgis-2.1 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

And the installation stops.

**Comment by simod** [comment]
Hi, how are you installing geonode? apt-get?

**Comment by jcaceres85** [comment]
Hi, yes.

I add the ppa:geonode/stable and then did apt-get install geonode and came
up with this error.

Thanks,

Jose

El 9 may. 2017 1:09 AM, "Simone Dalmasso" <notifications@github.com>
escribió:

Hi, how are you installing geonode? apt-get?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GeoNode/geonode/issues/3034#issuecomment-300080349>,
or mute
the thread

**Comment by kalxas** [comment]
@jcaceres85 do you have another ppa enabled in your setup?

**Comment by jcaceres85** [comment]
hi @kalxas 

From Geonode, I have the stable, release and testing ppa, but the last 2 are disable, I have and ubuntugis ppa as well

This is a screenshot of all my ppa:

![ppa](https://cloud.githubusercontent.com/assets/7606782/25876319/8f448f46-34d9-11e7-8869-8443a695e821.jpg)

Thanks,

**Comment by kalxas** [comment]
Having that many ppas is always a bad idea, they are not guaranteed to play well with each other.
In your case, some other ppa has pulled another version of postgis and it causes a conflict.

**Comment by jcaceres85** [comment]
I'll look into it!

Thanks,

**Comment by jcaceres85** [comment]
I did a clean install of a ubuntu server 14.04 (no extra ppa added) and had no troubles,

Thanks for the help.
