### ISSUE TITLE
Plans to make layer cart items durable?

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#3057]
Hi,

please check the following. 

- On layers page http://demo.geonode.org/layers/ put some layers in your "cart". 
- Click any top menu item. 
- click layers top menu link again. 

You will recognize your cart is empty. From my point of view this behavior might seem as a failure to users. Nowadays we´re used to fill shopping carts all over the web which are bound to a session.

Are there plans to change this behavior and imake the cart data durable? 

I´m not familiar with angular but using ngCookies in [cart.js](https://github.com/GeoNode/geonode/blob/ff80d89bd2038d74f241352b5fb07147c4bda27c/geonode/static/geonode/js/search/cart.js) should do it. 
(quick test below:)

```
angular.module('cart', ['ngCookies'])
[...]
.service('cart', function($cookies){
this.init = function(){
  this.$cart = {
    items: this.fillCart()
  };
};

this.fillCart = function(){
  var geonodeCart = $cookies.getAll();
  var cartSession = [];
  if(Object.keys(geonodeCart).length > 1){
        Object.keys(geonodeCart).forEach(function(key,index) {
          if(key !== 'csrftoken'){
            var obj = JSON.parse(geonodeCart[key]);
            obj['$$hashKey'] = "object:"+index;
            cartSession.push( obj );
          }
        });
    }  
  return cartSession;
}

this.getCart = function(){
  return this.$cart;
}

this.addItem = function(item){
  if(this.getItemById(item.id) === null){
    this.getCart().items.push(item);
    $cookies.putObject(item['uuid'], item);
  }
}

this.removeItem = function(item){
  if(this.getItemById(item.id) !== null){
    var cart = this.getCart();
    angular.forEach(cart.items, function(cart_item, index){
      if(cart_item.id === item.id){
        cart.items.splice(index, 1);
        $cookies.remove(cart_item['uuid']);
      }
    });
  }
}

```

**Comment by simod** [comment]
Thanks @t-book. Willing to make a pull request?

**Comment by t-book** [comment]
Hi Simone,

sure. I´m not that familiar with angular but I can create a PR.

cheers,
Toni

**Comment by capooti** [comment]
angular (and javascript) won't help, server code is needed here. I think a nice approach is to store items in the django cache and reading the cart items from there. Definitely a Django view is needed for this purpose

**Comment by capooti** [comment]
sorry, an approach with cookie is also great! Thanks for working on this

**Comment by t-book** [comment]
Hey capooti, thanks for your reply. 
I did a quick test with ng-cookies it worked quite well. Try to make a proposal soon.

Cheers,

Toni

**Comment by capooti** [comment]
great! Looking forward, thanks
