### ISSUE TITLE
relation "django_site" does not exist

### ISSUE THREAD

**Issue by safezpa** [GeoNode/geonode#3058]
ProgrammingError at /

relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...

**Comment by ppasq** [comment]
You should provide more details on your installation. My guess is you need to run the migrations. However please use the geonode-users mailing list for support. See https://github.com/GeoNode/geonode/blob/master/README#L15

**Comment by safezpa** [comment]
make sync

**Comment by safezpa** [comment]
I use Docker when 
- make sync 
some error occurred
It seems thant "docker-compose exec django django-admin.py migrate --noinput" does not work.
so I follow the error message  
  enter the container : docker exec -it geonode_django_1 /bin/sh
  ```
      python manage.py makemigrations --merge
  ```
then commit then change，now it works.
