### ISSUE TITLE
uploads moderation: flag to make new uploads unpublished by default

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode#3061]

**Comment by cezio** [comment]
closing, since PR has been merged in

**Comment by capooti** [comment]
Great PR. It would be nice to have some documentation added as well. Thanks

**Comment by capooti** [comment]
This is the most appropriate place: https://github.com/GeoNode/geonode/blob/master/docs/tutorials/advanced/geonode_settings/settings.txt
