### ISSUE TITLE
Keywords are not removed after removing a layer/map/document/service

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#3093]
Keywords created for layers from a remote service are not deleted after removing a remote service with all associated layers

**Comment by capooti** [comment]
hey @francbartoli this is a general problem of tags created with django-taggit. Tags are not removed when removing an object (layer, map, document, remote service etc...).
Maybe adding a management command with some code like this? https://github.com/alex/django-taggit/issues/294 
Note that for some organization removing unused tags could not be in requirements (if they have a defined list of tags to use). So we shouldn't do it by default in signals but a command would be the most appropriate solution.

**Comment by capooti** [comment]
If you don't mind @francbartoli I am changing the title of this issue

**Comment by francbartoli** [comment]
@capooti no problem go ahead
