### ISSUE TITLE
Some Leaflet library can't be resolved

### ISSUE THREAD

**Issue by lucernae** [GeoNode/geonode#3116]
Hi, I'm using leaflet as layer preview library.

My browser can't resolve this static address:

```
<link rel="stylesheet" href="/static/lib/opacity/lib/opacity/Control.Opacity.css" />
<script src="/static/lib/opacity/lib/opacity/Control.Opacity.js"></script>

<script src="/static/lib/opacity/lib/jquery/jquery-1.9.1.js"></script>
<script src="/static/lib/opacity/lib/jquery/jquery-ui-1.10.3.custom.min.js"></script>
<link rel="stylesheet" href="/static/lib/opacity/lib/jquery/jquery-ui-1.10.3.custom.min.css" />

<link rel="stylesheet" href="/static/lib/navbar/Leaflet.NavBar.css" />
<script src="/static/lib/navbar/Leaflet.NavBar.js"></script>
```

Is this already included in geonode? Is there any additional steps to generate these static library.
I already run django collectstatic.

# Environment

Geonode: Geonode master
Layer preview library: Leaflet

**Comment by simod** [comment]
Hi, is it possible you have DEBUG_STATIC to True? If yes then you need to pull all the js stuff with bower.

**Comment by lucernae** [comment]
Thank's @simod .
Is this the instruction you mentioned regarding bower?
http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html#ubuntu-for-development

**Comment by simod** [comment]
It should be this one http://docs.geonode.org/en/master/tutorials/devel/devel_env/index.html#install-geonode-for-development step 6 and the "bower install" inside the static dir

**Comment by lucernae** [comment]
Hi @simod I followed the instruction and the problem still persists. I didn't set DEBUG_STATIC to True, but changed LAYER_PREVIEW_LIBRARY = 'leaflet'. I was thinking that maybe some leaflet plugins is missing or not found?

This is the file where it includes the static address mentioned.
https://github.com/GeoNode/geonode/blob/master/geonode/layers/templates/layers/layer_leaflet_map.html

**Comment by simod** [comment]
I see, then yes they may be missing. Strange though, as far as I remember the leaflet preview should work correctly.

**Comment by lucernae** [comment]
If I wanted to fix it, is this the correct way?

1. Include the library using bower
2. Compile it using grunt production

**Comment by simod** [comment]
Yeah, but we should make sure to have a separate file for leaflet as we don't want to include it also when using geoexplorer.

**Comment by lucernae** [comment]
I see. This is probably going to be a long discussion, so it is better if I make pull request first then you can comment on that and suggest the best way to fix it.
I'll make a PR first.

**Comment by lucernae** [comment]
We can close this as the PR was merged.
