### ISSUE TITLE
Can’t install fresh version of Geonode 2.6 using quick installation guide

### ISSUE THREAD

**Issue by mkmushegh** [GeoNode/geonode#3132]
Hello,
Could anyone possible help me to install the latest version of Geonode (2.6) on a fresh Ubuntu 16.04 LTS? I’m using quick installation guide and at the end of the 3-rd stage (sudo apt-get install geonode) I’m getting the following error:

Setting up geoserver-geonode (2.9.0) ...
Job for tomcat7.service failed because the control process exited with error code. See "systemctl status tomcat7.service" and "journalctl -xe" for details.
dpkg: error processing package geoserver-geonode (--configure):
 subprocess installed post-installation script returned error exit status 1
dpkg: dependency problems prevent configuration of geonode:
 geonode depends on geoserver-geonode | geoserver; however:
  Package geoserver-geonode is not configured yet.
  Package geoserver is not installed.

dpkg: error processing package geonode (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 geoserver-geonode
 geonode
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by simod** [comment]
Hi, this type of error often happens when the machine is not powerful enough. Could it be the case?

ps, please use the mailing lists to ask for support.
