### ISSUE TITLE
static_root : No such file or directory

### ISSUE THREAD

**Issue by Abdelrhman-Rayis** [GeoNode/geonode#3160]
I was installing geonode 2.4 in Ubuntu and when i  the point where riched the point where i should change permissions on GeoNode files and folders to allow Apache to read and edit them this happens

chown: cannot access ‘/home/geonode/geonode/geonode/static_root/’: No such file or directory

**Comment by simod** [comment]
hi please use the mailing list geonode-users@lists.osgeo.org to ask for support.
could you also add some more info like how are you installing geonode and what guide are you following?

**Comment by Abdelrhman-Rayis** [comment]
thanks :+1:
