### ISSUE TITLE
docker-compose issues

### ISSUE THREAD

**Issue by iCodePup** [GeoNode/geonode#3161]
Hello

I just have cloned master branch and try to run the docker-compose.yml file with `docker-compose up ` command but unfortunately i am getting some errors :

- celery_1  => ImportError: **## No module named floppyforms**

-  django_1  => ImportError: **No module named geonode.settings**

The log is the following

`celery_1         |   File "/usr/local/lib/python2.7/site-packages/celery/fixups/django.py", line 158, in validate_models
celery_1         |     django_setup()
celery_1         |   File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
celery_1         |     apps.populate(settings.INSTALLED_APPS)
celery_1         |   File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
celery_1         |     app_config = AppConfig.create(entry)
celery_1         |   File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 86, in create
celery_1         |     module = import_module(entry)
celery_1         |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
celery_1         |     __import__(name)
celery_1         | ImportError: **## No module named floppyforms**
django_1         | Traceback (most recent call last):
django_1         |   File "/usr/local/bin/django-admin.py", line 5, in <module>
django_1         |     management.execute_from_command_line()
django_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
django_1         |     utility.execute()
django_1         |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 303, in execute
django_1         |     settings.INSTALLED_APPS
django_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
django_1         |     self._setup(name)
django_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 44, in _setup
django_1         |     self._wrapped = Settings(settings_module)
django_1         |   File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 92, in __init__
django_1         |     mod = importlib.import_module(self.SETTINGS_MODULE)
django_1         |   File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
django_1         |     __import__(name)
django_1         | ImportError: **No module named geonode.settings**
geonode_celery_1 exited with code 1
geoserver_1      | 05-Jul-2017 09:55:44.150 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/ROOT
geonode_django_1 exited with code 1
geonode_1        | 2017/07/05 09:55:44 [emerg] 1#1: host not found in upstream "django" in /etc/nginx/nginx.conf:46
geonode_1        | nginx: [emerg] host not found in upstream "django" in /etc/nginx/nginx.conf:46
geonode_geonode_1 exited with code 1
`

Thanks for help and suggestions

**Comment by francbartoli** [comment]
@iCodePup could you please confirm that error is still present with the branch 2.6.x?
