### ISSUE TITLE
Demo site appears to be down http://demo.geonode.org/

### ISSUE THREAD

**Issue by samperd** [GeoNode/geonode#3162]
Hey Folks,

I went to the demo site today and it apears to be done. http://demo.geonode.org/

Generic Error:
DoesNotExist at /

Profile matching query does not exist.

Request Method: 	GET
Request URL: 	http://demo.geonode.org/
Django Version: 	1.6.11
Exception Type: 	DoesNotExist
Exception Value: 	

Profile matching query does not exist.

Exception Location: 	/usr/lib/python2.7/dist-packages/django/db/models/query.py in get, line 310
Python Executable: 	/usr/bin/python
Python Version: 	2.7.6
Python Path: 	

['/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/pymodules/python2.7',
 '/var/www']

Server time: 	Wed, 5 Jul 2017 10:25:05 -0500

**Comment by simod** [comment]
ty

**Comment by samperd** [comment]
Thanks for the prompt response. The demo is a great resource while I wait for IT to provide sand box servers.

Thanks so much for providing a demo server.
