### ISSUE TITLE
disable_local_repo.sh: command not found

### ISSUE THREAD

**Issue by Abdelrhman-Rayis** [GeoNode/geonode#3163]
i installed successfully  GeoNode version 2.7.dev20170704074231 in my machine ubuntu 16.04 but when i try to Customize the look and feel using Setup steps 
in this doc:
 http://training.geonode.geo-solutions.it/004_admin_workshop/004_customize_lookfeel/customize/setup_admin.html#setup-admin

i get command not found like this :- 

geo@geo:~$ sudo su
[sudo] password for geo: 
root@geo:/home/geo# cd /home/geonode
root@geo:/home/geonode# disable_local_repo.sh
disable_local_repo.sh: command not found

**Comment by simod** [comment]
hi, mind using geonode-users@lists.osgeo.org instead of here?

thanks
