### ISSUE TITLE
Unable to load Canadian National Pollutant Release Inventory (NPRI) into Demo Server

### ISSUE THREAD

**Issue by samperd** [GeoNode/geonode#3166]
As a regular user creating a map
I want to add NPRI layers to GEONode from a WMS
So that layers can be visualized in a map

Issue:
The layer when it loads shows up as pink boxes with an image broken sign

Source WMS:
http://maps-cartes.ec.gc.ca/arcgis/services/NPRI_INRP/NPRI_INRP/MapServer/WMSServer?request=GetCapabilities&service=WMS

**Comment by simod** [comment]
@samperd same, pls use mailing lists. Also consider that you should not rely on the demo server as everyone has access and data can be wiped out at any time.
