### ISSUE TITLE
docker-compose Geonode data and configuration is not persistent  

### ISSUE THREAD

**Issue by vwmaus** [GeoNode/geonode#3169]
I cloned and set up the system using docker-compose.yml. However, if I run docker-compose down or docker-compose stop, then make the system up again all the Geonode data is lost. The Geoserver data seems to persist. 
How could I also make Geonode data and configuration persistent? 

Many thanks! 
Victor

**Comment by francbartoli** [comment]
@vwmaus thanks for reporting. True, geoserver side should be already working while django side not.

**Comment by vwmaus** [comment]
@francbartoli, 
I made some tests using `docker-compose stop` and `docker-compose start`. The data seems to be persistent for both Geoserver and Geonode as long as I don NOT run `make sync`. Instead, I run 
```{}
docker-compose start
docker-compose exec django django-admin.py loaddata sample_admin
```
This keeps the configuration and data from Geonode. 

Thanks!
