### ISSUE TITLE
After Login as Superuser: NoReverseMatch at / 

### ISSUE THREAD

**Issue by Spy-Shifty** [GeoNode/geonode#3172]
Hi,
i've just installed the latest version of geonode on an fresh installed CentOS 7 (Virtual Box) .

Everything works fine, except the login of the Supersuser!
After the login process I receive the following message:

```
NoReverseMatch at /

Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
```
Request Method: | GET
-- | --
Request URL: | http://127.0.0.1/
Django Version: | 1.8.18
Exception Type: | NoReverseMatch
Exception Value: | Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Exception Location: | /usr/lib/python2.7/site-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 495
Python Executable: | /usr/bin/python
Python Version: | 2.7.5
Python Path: | ['/home/geonode/.venvs/geonode/lib/python2.7/site-packages',
 -|'/home/geonode/geonode',
 -|'/usr/lib64/python27.zip',
 -|'/usr/lib64/python2.7',
 -|'/usr/lib64/python2.7/plat-linux2',
 -|'/usr/lib64/python2.7/lib-tk',
 -| '/usr/lib64/python2.7/lib-old',
 -|'/usr/lib64/python2.7/lib-dynload',
 -|'/usr/lib64/python2.7/site-packages',
 -|'/usr/lib64/python2.7/site-packages/gtk-2.0',
 -|'/usr/lib/python2.7/site-packages',
 -|'/usr/share/httpd']

```

Error during template rendering
In template /home/geonode/geonode/geonode/templates/base.html, error at line 97
Reverse for 'account_invite_user' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

97 | <li><a href="
      {% url "**account_invite_user**" %}
      ">{% trans "Invite User" %}</a></li>

```

I can register an new user and also logging in successfully. Except with the superuser!

I followed this installation guid:
http://docs.geonode.org/en/master/tutorials/install_and_admin/setup_on_centos/install_geonode.html

But I made the following changes:

I changed in the setup.py: 
"django-user-accounts==2.0.2dev",  // this throws an exception at install!
to 
"django-user-accounts>=2.0.2dev",

Postgre version: http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm
GDAL version: http://mirror.sfo12.us.leaseweb.net/epel/7/x86_64/e/epel-release-7-10.noarch.rpm

Hope someone can help me!

**Comment by francbartoli** [comment]
@Spy-Shifty I did not encounter such an error and exception while reviewing documentation for centos 7. Can you please try again with that updated from PR [3168](https://github.com/GeoNode/geonode/pull/3168)? Did you use the latest stable release [2.6.1](https://github.com/GeoNode/geonode/releases/tag/2.6.1)?

**Comment by Vampouille** [comment]
I have same issue with docker image based on debian. Maybe this is related to : 
https://github.com/GeoNode/geonode/blob/2.7.x/requirements.txt#L57-L62 ?
