### ISSUE TITLE
Geofence rules are not aligned with layer permissions

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#3173]
Steps to reproduce:

1. Login with user1
2. Create layer1 not public, just visible to the owner(user1). Leave the default permissions for the rest
3. Logout from user1
4. Login with user2
5. Create a map with layer1
6. Save the map
7. Browse the map which is depicting the layer while it should be only visible to user1
8. Go to GeoServer "GeoFence Data Rules" and see what are the permissions (see attachment)

Taking a look at geofence data rules it seems to be a wildcard for all the WxS services while such a rule should report only user1 for the service WMS imho

**Comment by simod** [comment]
Ciao Fra. Sorry didn't get it this afternoon but all superusers can see everything. This is by Geonode design.

**Comment by francbartoli** [comment]
Ok so fine

**Comment by francbartoli** [comment]
Reopen this cause it happens also for normal users

**Comment by afabiani** [comment]
@francbartoli are you sure you have unchecked the "Anyone" option? In that case GeoFence should create specific rules for users instead of "*"

**Comment by francbartoli** [comment]
quite sure @afabiani. I did uncheck it before clicking the upload button and then verify that when the layer had been created
