### ISSUE TITLE
Text of filter fileds in search tools exceed text-box

### ISSUE THREAD

**Issue by andvianello** [GeoNode/geonode#3174]
If the text inside the boxes of filters in the search tools is too long, the text exceed the box.
I think it's not a big priority but something not to nice to see.
![text_exceed](https://user-images.githubusercontent.com/1582714/28373715-494823ac-6ca3-11e7-8dc9-b36cc0479987.PNG)

**Comment by capooti** [comment]
Well, after some investigation this is not an easy fix.
But you could use "-" in place of "_" in keywords, and in that case keywords will be wrapped to multiple lines

<img width="337" alt="screenshot 2017-08-19 16 00 49" src="https://user-images.githubusercontent.com/148380/29489820-a2d0374a-84f7-11e7-8748-5ab7144fc71e.png">

**Comment by DanielJDufour** [comment]
This appears to be fixed and I think can be closed:
![image](https://user-images.githubusercontent.com/4313463/38020053-9570edda-3279-11e8-8029-14fd8e5bd39b.png)
