### ISSUE TITLE
docker-compose Geonode Geoserver authentication problem 

### ISSUE THREAD

**Issue by vwmaus** [GeoNode/geonode#3175]
If I change the password for Geoserver users admin using the web interface the Geonode is no longer able to connect and submit layers. 
```{}
HTTP Status 401 - No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken

type Status report

message No AuthenticationProvider found for org.springframework.security.authentication.UsernamePasswordAuthenticationToken

description This request requires HTTP authentication.
Apache Tomcat/9.0.0.M17
```

Using the docker-compose infrastructure, how can make Geonode update the Geoserver admin password?

**Comment by federicogodan** [comment]
The default user and password are defined in geonode/settings.py (OGC_SERVER_DEFAULT_USER and OGC_SERVER_DEFAULT_PASSWORD). 
Maybe yo can connect to geonode_django_1 and edit settings.py to match the new password.
Other option can be change settings.py in your local code and modify the Dockerfile for build the docker image using the modifications.

**Comment by vwmaus** [comment]
Thanks @federicogodan. It works now. I connected to geonode_django_1 and updated the variable OGC_SERVER_DEFAULT_PASSWORD in geonode/settings.py.
