### ISSUE TITLE
Some problems about imorting uploaded shapefile into PostGIS 

### ISSUE THREAD

**Issue by woshidgm** [GeoNode/geonode#3181]
After i upload shapfiles to Geonode , these files will be imported into PostGIS. I want to know which function or module can create a table to store these data . 
I thought it related to this function：file2pgtable( ) , but i find the app -- 'geonode.contrib.dynamic' annotated in setting.py

**Comment by capooti** [comment]
https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L955

Please use the mailing list for general purpose questions.
