### ISSUE TITLE
libproj.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3186]
I see this warning when running importlayers and updatelayers:

java.lang.UnsatisfiedLinkError: /tmp/spatialite-3.7.22.4-libspatialitejdbc.so: libproj.so.0: cannot open shared object file: No such file or directory

Creating this symbolic link seems to fix it:
sudo ln -s /usr/lib/x86_64-linux-gnu/libproj.so.9 /usr/lib/x86_64-linux-gnu/libproj.so.0

**Comment by kalxas** [comment]
@capooti which ppa's you have enabled in your system?

**Comment by capooti** [comment]
It is a development setup. So it could be that the official package is not affected.
Thought, I have seen this error in different emails from the users list
