### ISSUE TITLE
Sitemap.xml lists restricted resources

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3190]
The sitemap.xml file used by Google and other search engines should only list publicly accessible resources. Instead it lists all resources regardless of the permissions set in Geonode.

E.g. [demo.geonode.org/sitemap.xml](http://demo.geonode.org/sitemap.xml) lists three restricted layers not visible in [demo.geonode.org/api/layers](http://demo.geonode.org/api/layers):

* [edificios_de_gobierno](http://demo.geonode.org/layers/geonode%3Aedificios_de_gobierno)
* [lc80420352015002lgn00_b4](http://demo.geonode.org/layers/geonode%3Alc80420352015002lgn00_b4)
* [san_juan](http://demo.geonode.org/layers/geonode%3Asan_juan)

**Comment by jondoig** [comment]
I tried the following in sitemap.py, but got:

> AttributeError at /sitemap.xml
> 'ResourceBase' object has no attribute 'get_absolute_url'

    from django.contrib.sitemaps import Sitemap
    from geonode.maps.models import Layer, Map
    from guardian.shortcuts import get_objects_for_user
    from django.contrib.auth.models import AnonymousUser

    class LayerSitemap(Sitemap):
        changefreq = "never"
        priority = 0.5

        def items(self):
            # return Layer.objects.all()
            return get_objects_for_user(AnonymousUser(), 'base.view_resourcebase').instance_of(Layer)
        def lastmod(self, obj):
            return obj.date

    class MapSitemap(Sitemap):
        changefreq = "never"
        priority = 0.5

        def items(self):
            # return Map.objects.all()
            return get_objects_for_user(AnonymousUser(), 'base.view_resourcebase').instance_of(Map)`

**Comment by simod** [comment]
Thanks @jondoig , this should fix it. The problem you had is that get_absolute_url is defined in children and sitemap was evaluating it over ResourceBase instead. https://github.com/GeoNode/geonode/pull/3214
