### ISSUE TITLE
Empty page when GET notifications/settings/

### ISSUE THREAD

**Issue by safezpa** [GeoNode/geonode#3196]
I just have cloned **master** branch and set ``` NOTIFICATION_ENABLED = True ```
When *GET notifications/settings/* , it returns an empty page. It seems missing template for the view.
So I copy
 *Lib/site-packages/pinax/notifications/templates/pinax/notifications/notice_settings.html* 
to
 *geonode/geonode/templates/pinax/notifications* . 
It works . Is there any graceful way？

**Comment by tomkralidis** [comment]
Please use the GeoNode users mailing list for questions. This issue tracker is for bugs, enhancements.
