### ISSUE TITLE
Spanish lots of fuzzy translations

### ISSUE THREAD

**Issue by federicogodan** [GeoNode/geonode#3203]
Hi, reviewing the locales i found a lot of fuzzy translations, so in the web interface only english version is showed. There are some missing trans operations in the interface.

There are some contribution guide for upload this types of changes? (https://www.clahub.com/agreements/GeoNode/geonode throw me an error when try to sign)

**Comment by federicogodan** [comment]
Javascripts translation aren't working at all as I see.

**Comment by t-book** [comment]
@federicogodan  Do you have the opportunity to update the spanish po file in master? If so I could push it to transifex.

**Comment by afabiani** [comment]
@t-book sounds good

**Comment by federicogodan** [comment]
@t-book excuse me for arrive a little late to the discussion. I translate partially to Spanish long time ago, in the process I found lots of missing translation tags in the code, and some elements in the db must be translated to get a full translated interface too (metadata categories).

**Comment by t-book** [comment]
In case somebody has resources to help with the Spanish translations please do as the (new) docs suggest http://docs.geonode.org/en/new-docs/contribute/index.html#provide-translations
