### ISSUE TITLE
Improve Remote Services

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3205]
Allow GeoNode Remote Services to:
1. Create a Link to Layer Details from Layers List too
2. Create a remote thumbnail whenever it is a WMS Service (at least)
3. Create correct GetLegendGraphic and WMS Links on Metadata

**Comment by federicogodan** [comment]
Can get added to this issue the option of download data from remote services? (if WFS avalaible)

**Comment by afabiani** [comment]
@federicogodan can you please open a specific issue for that?

**Comment by federicogodan** [comment]
ok, done.
