### ISSUE TITLE
Improve Remote Services: Enable Data Download

### ISSUE THREAD

**Issue by federicogodan** [GeoNode/geonode#3207]
Sometimes it is necessary to provide access to download data hosted on remote services. It would be nice if the tab of each layer allows you to download the data whenever possible (WFS available).
The idea would be, when adding a service verify that the layer can be downloaded (using a GetCapabilities request maybe ??). In this case enable the download button and provide the available formats.

**Comment by Melegy90** [comment]
@afabiani Has this feature been added? I think it would be very useful since a lot of organizations would use GeoNode as a geoportal hosting their dynamically updated data that is hosted elsewhere rather than uploading different copies to the portal.

**Comment by afabiani** [comment]
@Melegy90 nope, let's reopen it

**Comment by jeff-bradley** [comment]
has there been any recent progress on this?
