### ISSUE TITLE
Upload sld Style through geonode

### ISSUE THREAD

**Issue by cleder** [GeoNode/geonode#321]
Currently you can download styles from geonode as sld. 

To make use of tools such as atlas styler it should also be possible to upload sld files through geonode.

You can currently workaround this issue if you have manger access by uploading the style directly to the geoserver but this is more a hack than a feature.

suggestion: when you "create new style" there should be an option 'upload sld' or there could be an option at the data view:
"upload new style (SLD)" alongside with "create new style"

**Comment by jj0hns0n** [comment]
@simod is this actually fixed? @milafrierichs was trying use this and wasnt sure if it worked. What perms are required?

**Comment by simod** [comment]
@jj0hns0n Hm I honestly don't remember why I closed this. But I don't see that option in manage styles.

**Comment by mf4dl1** [comment]
Hi All, 
Hi @jj0hns0n ,

I am new to GeoNode git, however I would like to give a shot to contribute (at least put some feedback). Currently I am reviewing GeoNode as an alternative webmapping catalog. But I found the similar problem:

I try to upload layer file consist of: shp, shx, dbf, prj and sld files.
The sld file I created using QGIS version 2.8.1 wien, and it looks like this:
![image](https://cloud.githubusercontent.com/assets/4919662/10129206/beadee36-65e5-11e5-95fb-ebd73724e02d.png)

The uploading process went well. But after I opened the uploaded layer, the layer becoming all grey:
![image](https://cloud.githubusercontent.com/assets/4919662/10128605/fb839eca-65de-11e5-9ab5-12673001934d.png)

After I cross check to the geoserver style, it appears the sld doesn't have any Fill or Stroke in PlygonSymbolizer tag:
```
          <sld:PolygonSymbolizer>
            <sld:Fill/>
            <sld:Stroke/>
          </sld:PolygonSymbolizer>
```

In the original .sld file it supposed to be:
```
          <se:PolygonSymbolizer>
            <se:Fill>
              <se:SvgParameter name="fill">#7ba1eb</se:SvgParameter>
            </se:Fill>
            <se:Stroke>
              <se:SvgParameter name="stroke">#000000</se:SvgParameter>
              <se:SvgParameter name="stroke-opacity">0.00</se:SvgParameter>
              <se:SvgParameter name="stroke-width">0.26</se:SvgParameter>
              <se:SvgParameter name="stroke-linejoin">bevel</se:SvgParameter>
            </se:Stroke>
          </se:PolygonSymbolizer>
```

Does anybody notice of this bug? or it's already fixed?

**Comment by capooti** [comment]
dear @mf4dl1 
Please read this: http://thread.gmane.org/gmane.comp.gis.geoserver.user/45488/focus=45491
And remember to use the mailing list for general questions, and not the issue tracker (this issue here is not related to your problem).

**Comment by syamaniunlam** [comment]
Mr. @mf4dl1

Previously I had the same problem with you when I making sld using QGIS. But after I made sld using Atlas Styler, color style that appears in Geonode exactly like the design that I created in Atlas Styler.

Atlas Styler free download at http://en.geopublishing.org/
Atlas Styler written in Java so it is cross-platform

Syam'ani
Spatial Data Infrastructure Development Center
Universitas Lambung Mangkurat
Banjarbaru - Kalimantan Selatan

**Comment by srimalsl** [comment]
Dear All, I have layer style issue with latest version of Geonode. I have created new style in Geonode Administration and tried to add it to particular layer. I cannot find the new style I created in the list of available style. Why this is happening.  Srimal

**Comment by jj0hns0n** [comment]
This is not the place for these kinds of questions, please use the list.

**Comment by jondoig** [comment]
Is this in any active development stream? Or is a workaround suggested for ordinary users?

As a site admin, do I have to do this in geoserver for my users on a per request basis, or is there a safe way to allow advanced users access to just their own styles (and other content) in geoserver?

**Comment by afabiani** [comment]
Hi all, I'm planning to add this functionality soon on GeoNode master branch.

**Comment by davisc** [comment]
@afabiani is there an update based on your Jul 21 comment?

**Comment by afabiani** [comment]
Yes, already available on master. Will be backported on 2.7 soon

**Comment by jondoig** [comment]
SLD upload is now working in Geonode 2.8rc11. Tested with SLD exported from QGIS. Works when uploading shapefile with SLD. Also works to add style to existing layer through Edit Layer > Styles > Upload style. Yay! @afabiani can this be closed now?
