### ISSUE TITLE
Geonode loads with IP not with URL/domain name

### ISSUE THREAD

**Issue by mehmadi** [GeoNode/geonode#3213]
I have successfully installed geonode on a remote server made some customization. Now, it loads with IP address with no problem; however, I get the following apache error when I try to load the website using URL/host name. Strange enough, geoserver works fine when I try both <host>/geoserver and <ip>/geoserver. Pinging the host name shows my ip address and my nameservers seem to be set appropriately. 

Do you guys have any idea what is the likely reason for this problem?

ERROR MESSAGE:

> Internal Server Error
> 
> The server encountered an internal error or misconfiguration and was unable to complete your request.
> 
> Please contact the server administrator at webmaster@localhost to inform them of the time this error occurred, and the actions you performed just before this error.
> 
> More information about this error may be available in the server error log.
> 
> _Apache/2.4.18 (Ubuntu) Server at ulsdi.ir Port 80_

**Comment by simod** [comment]
hi, could you please use geonode-users@lists.osgeo.org to ask for support?

This is only for bug tracking

**Comment by mehmadi** [comment]
Thanks you much. I did.
