### ISSUE TITLE
Shapely 1.6.0 import error

### ISSUE THREAD

**Issue by hishamkaram** [GeoNode/geonode#3238]
Shapely 1.6.0 is not compatible  with geonode 
we need to restrict Shapely version to 1.5.17 
please review this [issue](https://github.com/cartologic/cartoview/issues/57)

**Comment by capooti** [comment]
I am wondering if we shouldn't rather drop it until we really use it.
As far as I can see it is only being used here right now:
https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local.py#L172

/cc @tomkralidis

**Comment by afabiani** [comment]
Hi, where 1.6.0 comes from? Is it a dependency of some module? The setup.py seems to be restricted to 1.5.17 or less.

**Comment by hishamkaram** [comment]
@afabiani @capooti in Geonode2.6.x 
https://github.com/GeoNode/geonode/blob/2.6.x/setup.py
