### ISSUE TITLE
On Removal of the Layer/Map corresponding Thumbnails of the Map/Layers not removed

### ISSUE THREAD

**Issue by nareshnagamalle** [GeoNode/geonode#3242]
Dear All,
 On Removal of the Layer/Thumbnails the corresponding images are not deleting. Although the users has not have any impact, to have better maintenance and avoid unnecessary images flooded with Thumbnail at server side, it is better ,on removal the  layer the corresponding  thumbnails should be removed.
And even if we want to delete  manually it is difficult as it has no direct link with existing and remove layers. 

Thanks&Regards,
Naresh

**Comment by capooti** [comment]
Hi, the correct way to handle this is with the delete_orphaned_thumbs Celery task.
There is a command which should handle this and that you can schedule in case you don't want the Celery/RabbitMQ overhead: delete_orphaned_thumbs

**Comment by nareshnagamalle** [comment]
Dear Paolo Corti,
  Thanks for the update. Kindly tell me will it work with windows? If so
where to run?

Best Regards,
Naresh

**Comment by capooti** [comment]
You can use the django admin command, it should be possible to run from the shell with:
geonode delete_orphaned_thumbs

I am not familiar with the Windows setup, so the way the command could be run could be different.

**Comment by nareshnagamalle** [comment]
Dear Paolo,
  Thanks for the update.

Thanks&Regards,
Naresh. N
