### ISSUE TITLE
Cannot update point of contact, metadata author, owner

### ISSUE THREAD

**Issue by fvanderbiest** [GeoNode/geonode#3245]
With https://github.com/fvanderbiest/ansible_vagrant_geonode I bootstrapped a fresh 2.6.2 GeoNode in a clean environment.

I uploaded a document, tried to update one of `point of contact`, `metadata author`, `owner` fields, but this fails: after removing the default "admin" user, an empty field shows up for half a second, then the page reloads.

Any idea ?

**Comment by afabiani** [comment]
Yep, this has been fixed on GeoNode master (2.7.x). On 2.6.x those values are ignored.

**Comment by fvanderbiest** [comment]
Thanks for the quick answer :-)

Do you mean https://github.com/GeoNode/geonode/issues/3080 ?
I'm really not sure this is the same issue, since the above patch relates to layers, not documents.
