### ISSUE TITLE
Legend labels on map edit and printing

### ISSUE THREAD

**Issue by Imaflora** [GeoNode/geonode#3254]
When printing and making maps, only rasters come with label in the legend.

![image](https://user-images.githubusercontent.com/24397266/29923394-c4de2ba8-8e2f-11e7-9585-23028255a61c.png)

![image](https://user-images.githubusercontent.com/24397266/29895649-527a8aea-8db0-11e7-87fe-d204a28c2e8e.png)

I think it could be solved if the request for GetLegendGraphic was decorated with `legend_options=forceLabels:on` is it possible?

**Comment by federicogodan** [comment]
Hi, which version of geonode are you using? Remember that you need to create  <Title> tags in layer's SLD rules for display the labels.

**Comment by Imaflora** [comment]
Sorry, I forgot to mention that I'm using geonode 2.4. SLD title is fine, it does display on map preview page because the requisition does include `legend_options=forceLabels:on`.

In "map edit" though it doesn't show because the `legend_options=forceLabels:on` parameter isn't there, so the labels aren't either.

**Comment by Imaflora** [comment]
Thanks @federicogodan, it did work!
