### ISSUE TITLE
GNIP: Create empty layer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3269]
# Overview

In many GeoNode instances there is the need to create layers from scratch. A contrib application is needed which will let the user to create an empty layer. The user will be able for that given layer to assign:

* layer name
* layer title
* geometry type (Points, Lines, Polygons)
* a number of fields

For each field the user will be able to define the name and its type (String, Integer, Float, Date)

The application will be part of geonode.contrib applications and requires PostgreSQL/PostGIS, so it will not be part of default INSTALLED_APPS

A django management command will be include, to create empty layers from the Django shell.

# Proposed by

[Paolo Corti and Ben Lewis, Harvard CGA](http://gis.harvard.edu/)
[Francesco Stompanato and Dimitris Karakostis, WFP](https://geonode.wfp.org/)

# Assigned to release

2.8

# Mockup

<img width="1204" alt="screenshot 2017-09-06 17 13 53" src="https://user-images.githubusercontent.com/148380/30135074-79b27286-9327-11e7-991c-497802027d91.png">

**Comment by capooti** [comment]
I am pretty close to submit a PR for this, here is the branch:
https://github.com/capooti/geonode/tree/create-layer-app

**Comment by afabiani** [comment]
+1
it looks interesting. Just a question, this empty layer will be connected somehow to a geospatial dataset or it will remain just an empty descriptor?

**Comment by capooti** [comment]
Yes, this application will create a PostGIS layer and add it to GeoServer, then register as a layer in GeoNode. It is useful in many scenarios when there is a need to digitize information from basemaps or create map notes using WFS/T.

**Comment by capooti** [comment]
Here is the application in action:

http://recordit.co/anFE0BQRYr
