### ISSUE TITLE
unable to uninstall geonode

### ISSUE THREAD

**Issue by Ashish-Sharma-07** [GeoNode/geonode#3276]
i am trying to uninstall geonode as it is not working properly can somebody help me out please
![error](https://user-images.githubusercontent.com/30353072/30214164-055619d0-94c9-11e7-803c-62f77fec8a79.png)

**Comment by Ashish-Sharma-07** [comment]
Error while installing geonode
![screenshot from 2017-10-02 17-05-59](https://user-images.githubusercontent.com/30353072/31075706-659cf070-a766-11e7-8fcd-73bc267c8a0f.png)
![screenshot from 2017-10-02 17-06-09](https://user-images.githubusercontent.com/30353072/31075713-6ce9892e-a766-11e7-996c-f7ec7cfc7ed8.png)

**Comment by simod** [comment]
Hi, this installation issues generally happen when the machine is not powerful enough (at least 8 GB of Ram). 
ps please use the mailing lists to ask for support before opening a ticket
