### ISSUE TITLE
Geonode upload error

### ISSUE THREAD

**Issue by NicholasDsouza1996** [GeoNode/geonode#3280]
I get this when i upload layers 
('GeoServer gave non-XML response for [GET http://localhost:8080/geoserver/rest/workspaces/default.xml]: T/', ParseError(ExpatError('not well-formed (invalid token): line 1, column 1',),))

Please help!!

**Comment by NicholasDsouza1996** [comment]
most times it says upload has started but fails to upload any layers

**Comment by simod** [comment]
Could you please move this on the mailing list?
