### ISSUE TITLE
Layer creation using REST API very slow in a PostGIS database with thousands of tables

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3285]
Refers to 

https://osgeo-org.atlassian.net/browse/GEOS-7533

**Comment by capooti** [comment]
It would be great if this could be fixed.
Another problem in such a scenario is WFS-T transactions which become also very very slow

**Comment by capooti** [comment]
yes I believe we are still impacted by this, unfortunately. Let me know if you have seen some progress on this in GeoServer :)
