### ISSUE TITLE
Maps not responsive to touch on mobile

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3294]
Neither the embedded GeoExplorer map in the layer detail page nor the full screen 'View map" page responds to touch devices for:

* pinch to zoom
* tap for feature info
* tap on + (zoom in) above or - (zoom out) below the on-screen zoom level bar
* tap on N/E/S/W pan arrows on the on-screen rosette

**Comment by kalxas** [comment]
There is geonode-client application that is built on more recent technologies than GeoExplorer, but it is not the default.

**Comment by kalxas** [comment]
https://github.com/GeoNode/geonode-client

**Comment by t-book** [comment]
@jondoig If using a newer client is an option for you, would you close this issue?

**Comment by jondoig** [comment]
Fixed with Leaflet client in PR #4390 thanks!
