### ISSUE TITLE
Map view layout issues on mobile (small screen)

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3295]
The map view (/maps/nnn/view) has a number of layout issues on small screens (i.e. mobile phones):

* the layers list (table of contents) on the left hand side occupies nearly the whole of a mobile device screen
* the control to hide the LHS layers list is tiny: hard to see and then hard to tap on mobile
* in portrait orientation the top toolbar is only half visible
* in landscape orientation there is insufficient space for the map: the top half of the screen is occupied by address bar, blank blue header and toolbars

**Comment by ppasq** [comment]
Please see @kalxas comment on #3294. For responsive behaviour I would suggest to switch to geonode-client or leafletjs.

**Comment by jondoig** [comment]
Fixed with Leaflet client in PR #4390 thanks!
