### ISSUE TITLE
DEBUG_STATIC=True breaks frontend

### ISSUE THREAD

**Issue by cezio** [GeoNode/geonode#3336]
Setting `DEBUG_STATIC=True` will break frontend in many places (all dynamic lists, like layers, docs, maps etc). 

This is because with that setting, `angular.js` is included in scripts, but it's not present in static files. There's `angular.min.js`, but I guess it defeats the purpose of `DEBUG_STATIC`:

https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html#L192

**Comment by simod** [comment]
@cezio did you also run bower install? It is required for js development

**Comment by cezio** [comment]
Good point. No, i haven't. But in this case, what's the point of having minified version of angular anyway?

**Comment by simod** [comment]
The goal is all the js dependencies are shipped in the assets.js file and that we don't ship any of them in the geonode's static folder. When needed to develop on static, turning on DEBUG_STATIC and running bower install should set up all that's needed.

**Comment by cezio** [comment]
Ok, let's add a warning when `DEBUG_STATIC` is enabled then. It's not obvious that enabling this flag requires npm.

**Comment by t-book** [comment]
@cezio I think this can be closed, right? Would you?

**Comment by t-book** [comment]
@francbartoli  can you close this ticket?
