### ISSUE TITLE
gsconfig get_default_workspace() is very slow with many layers

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3347]
I guess this is for @afabiani :)

We are migrating our instance from 1.2 to 2.8.

In the migrated instance, which contains thousand of layers, layer upload and creation is taking a couple of minutes (while in original instance is very fast, just a few seconds). After investigating tracing code, it looks like cat.get_default_workspace() it is taking almost 2 minutes.
If I run cat.get_workspace('geonode') it is a bit faster, but still 1 minute.

In our original GeoNode instance, cat.get_default_workspace() is instantaneous. My idea is that the slowdown is caused by new permission system and geofence.

This is what I see logged from GeoServer:

11 Oct 20:39:32 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Checking match of request : 'Path: /rest/workspaces/default.xml, QueryString: null'; against '/rest/**'
11 Oct 20:39:32 DEBUG [security.IncludeQueryStringAntPathRequestMatcher] - Matched Path: /rest/workspaces/default.xml, QueryString: null with /rest/**
11 Oct 20:39:32 DEBUG [geoserver.security] - Inspecting the http request looking for the GeoNode Session ID.
11 Oct 20:39:32 DEBUG [geoserver.security] - Found no cookies!
11 Oct 20:39:32 DEBUG [geoserver.security] - preAuthenticatedPrincipal = null, trying to authenticate
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Converted URL to lowercase, from: '/rest/workspaces/default.xml'; to: '/rest/workspaces/default.xml'  and httpMethod= GET
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /rest/process/batchdownload/download/* methodList= [GET]
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces/default.xml'; antPath is /rest/process/batchdownload/download/*; matchedPath=false; matchedMethods=true
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /rest/printing/* methodList= [GET, POST]
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces/default.xml'; antPath is /rest/printing/*; matchedPath=false; matchedMethods=true
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - ~~~~~~~~~~ antPath= /rest/** methodList= [GET, POST]
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - Candidate is: '/rest/workspaces/default.xml'; antPath is /rest/**; matchedPath=true; matchedMethods=true
11 Oct 20:39:32 DEBUG [security.RESTfulPathBasedFilterInvocationDefinitionMap] - returning IS_AUTHENTICATED_ANONYMOUSLY
11 Oct 20:39:32 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/default.xml]
11 Oct 20:39:32 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/default.xml]
11 Oct 20:39:32 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/default.xml]
11 Oct 20:39:32 TRACE [ows.OWSHandlerMapping] - No handler mapping found for [/rest/workspaces/default.xml]
11 Oct 20:39:32 DEBUG [org.geoserver] - Thread 56 locking in mode READ
11 Oct 20:39:32 DEBUG [org.geoserver] - Thread 56 got the lock in mode READ
11 Oct 20:39:32 DEBUG [geoserver.geofence] - Getting access limits for workspace geonode
11 Oct 20:39:32 DEBUG [geoserver.geofence] - Getting admin auth for Workspace geonode
11 Oct 20:39:32 DEBUG [geoserver.geofence] - AdminAuth filter: RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"192.168.100.12"+ serv:ANY req:ANY ws:"geonode"+ layer:ANY]
11 Oct 20:39:32 DEBUG [geofence.cache] - AdminAuth Request for RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"192.168.100.12"+ serv:ANY req:ANY ws:"geonode"+ layer:ANY]
11 Oct 20:39:32 DEBUG [geofence.cache] - Loading RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"192.168.100.12"+ serv:ANY req:ANY ws:"geonode"+ layer:ANY]
11 Oct 20:39:32 DEBUG [geofence.internal] - Getting Roles for User []
11 Oct 20:39:32 DEBUG [geofence.internal] - Checking UserGroupService [default]
11 Oct 20:39:32 DEBUG [geofence.internal] - Checking RoleService [default]
11 Oct 20:39:32 DEBUG [geofence.internal] - Checking RoleService [geonode REST role service]
11 Oct 20:39:57 DEBUG [geoserver.security] - Setting ROLES for User [] to [ROLE_BETA-USERS]
11 Oct 20:40:08 DEBUG [geoserver.wps] - Removing statuses matching [[[ NOT [ completionTime IS NULL ] ] AND org.geotools.filter.temporal.BeforeImpl@cf3de98d] AND [[ NOT [ lastUpdated IS NULL ] ] AND org.geotools.filter.temporal.BeforeImpl@ca399479]]
11 Oct 20:40:21 DEBUG [geoserver.security] - Setting ROLES for User [] to [ROLE_BETA-USERS]
11 Oct 20:40:21 DEBUG [geofence.internal] - RoleService [geonode REST role service] matching for User []
11 Oct 20:40:21 DEBUG [geofence.internal] - Checking UserGroupService [default]
11 Oct 20:40:21 DEBUG [geofence.internal] - Matching Roles [[]] for User []
11 Oct 20:40:21 DEBUG [geofence.internal] - Checking UserGroupService [default]
11 Oct 20:40:21 DEBUG [geofence.internal] - Matching Roles [[]] for User []
11 Oct 20:40:21 DEBUG [geoserver.geofence] - Admin auth for User: Workspace:geonode: true
11 Oct 20:40:21 DEBUG [catalog.rest] - GET workspace default
11 Oct 20:40:21 DEBUG [geoserver.geofence] - Getting access limits for workspace geonode
11 Oct 20:40:21 DEBUG [geoserver.geofence] - Getting admin auth for Workspace geonode
11 Oct 20:40:21 DEBUG [geoserver.geofence] - AdminAuth filter: RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"192.168.100.12"+ serv:ANY req:ANY ws:"geonode"+ layer:ANY]
11 Oct 20:40:21 DEBUG [geofence.cache] - AdminAuth Request for RuleFilter[user:(empty)+ role:ANY inst:name+:default-gs ip:"192.168.100.12"+ serv:ANY req:ANY ws:"geonode"+ layer:ANY]
11 Oct 20:40:21 DEBUG [geoserver.geofence] - Admin auth for User: Workspace:geonode: true
11 Oct 20:40:21 DEBUG [org.geoserver] - Thread 56 locking in mode READ
11 Oct 20:40:21 DEBUG [org.geoserver] - Thread 56 releasing the lock in mode READ
11 Oct 20:40:21 DEBUG [geoserver.filters] - Compressing output for mimetype: application/xml
11 Oct 20:40:21 DEBUG [filter.GeoServerSecurityContextPersistenceFilter$1] - SecurityContextHolder now cleared, as request processing completed
11 Oct 20:41:08 DEBUG [geoserver.wps] - Removing statuses matching [[[ NOT [ completionTime IS NULL ] ] AND org.geotools.filter.temporal.BeforeImpl@d360fbad] AND [[ NOT [ lastUpdated IS NULL ] ] AND org.geotools.filter.temporal.BeforeImpl@ce5ca699]]

**Comment by afabiani** [comment]
Be sure the GeoFence rules cache is big enough and also its expiration time.

**Comment by capooti** [comment]
Thanks, that was.
Size was large enough, but I had to increase the "Cache refresh interval (ms)" parameter from the default (30000 ms) and now is very fast again :)
thanks again
