### ISSUE TITLE
Missing migration for upload app.

### ISSUE THREAD

**Issue by isralopez** [GeoNode/geonode#3354]
The issue appear when you want to delete layers or other resources in a migrated database
from the 2.4 to 2.6. The yellow screen say:
ProgrammingError: column upload_upload.mosaic_time_regex does not exist

This is the link for the thread:
http://osgeo-org.1560.x6.nabble.com/Missing-columns-after-migrating-data-from-Geonode-2-4-to-2-6-tc5338591.html

I found only one migration in the app: 24_initial.py, this includes the new fields to be created, so
if we run all the initial migrations as fake, the new fields are not created. It's necesary to recreate the
migration files to have the initial and 24_to_26 migrations.

**Comment by CharlesOliveros** [comment]
Hola! Podrias decirme como "recrear" los archivos de migraciones 24_to_26?. Gracias  de antemano.

**Comment by t-book** [comment]
You can use sql fix to create those fields:
```
$ DJANGO_SETTINGS_MODULE=my_geonode.local_settings python manage.py sqldiff -ae >> /tmp/fix.sql
$ sudo -u postgres psql -d geonode -a -f /tmp/fix.sql
```

**Comment by simod** [comment]
Think this is very obsolete. Closing it.
