### ISSUE TITLE
Remove 900913 definition in remote services

### ISSUE THREAD

**Issue by DALUofM** [GeoNode/geonode#3367]
Apologies in advance if I'm using any terminology etc. incorrectly, I'm rather new with GeoNode.

Steps to reproduce: 
1) Install GeoNode 2.6 on Ubuntu 16.04 per instructions here http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html
2) Add the following Remote Service: http://www.agr.gc.ca/atlas/services/mapservices/aafc_watershed_2013/MapServer/WMSServer
3) Browse any layer, see pink tiles

When checking GetCapabilities for the WMS server, you can see the following coordinate systems defined:

<CRS>CRS:84</CRS>
<CRS>EPSG:4326</CRS>
<CRS>EPSG:3857</CRS>

<CRS>EPSG:102100</CRS>

But when you examine the actual URL being generated by GeoNode for layer images

http://www.agr.gc.ca/atlas/services/mapservices/aafc_watershed_2013/MapServer/WMSServer?LAYERS=14&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&TILED=true&SRS=EPSG%3A900913&BBOX=-15028131.255,5009377.085,-12523442.7125,7514065.6275&WIDTH=256&HEIGHT=256

SRS=EPSG%3A900913

Is there something special that needs to be done with this type of remote service?

**Comment by simod** [comment]
Hi @DALUofM this is a bug indeed, the 900913 should be discontinued. Thanks for reporting

**Comment by francbartoli** [comment]
@DALUofM This should be considered closed by #3396. Can you confirm with the latest code?
