### ISSUE TITLE
Cannot install dependency pdb==0.1

### ISSUE THREAD

**Issue by Vampouille** [GeoNode/geonode#3397]
During docker build with following commands : 
```bash
make pull
make build
 ```
Error message : 
```
  Could not find a version that satisfies the requirement pdb==0.1 (from -r requirements.txt (line 93)) (from versions: )
No matching distribution found for pdb==0.1 (from -r requirements.txt (line 93))
```
Requirement is defined here :
https://github.com/GeoNode/geonode/blob/2.7.x/requirements.txt#L93
I think this requirement should not appear in requirement.txt because it is already shipped with standard python distribution.

**Comment by ingenieroariel** [comment]
I am +1 on removing this dependency.

**Comment by simod** [comment]
+1 as well

**Comment by Vampouille** [comment]
@afabiani pdb==0.1 dependency is still present in 2.7.x branch. What is the merging strategy of geonode repo ? Do you merge 2.7.x to master ?
