### ISSUE TITLE
Geo explorer create map error

### ISSUE THREAD

**Issue by NouranHossam** [GeoNode/geonode#3411]
im using geonode version 2.6.3 when i add layers to map and click save it doesen't save the map and create an empty map like in this screenshot
![geo exploerer](https://user-images.githubusercontent.com/25221943/32547968-a74c7408-c48c-11e7-947b-7904eec3af8a.PNG)

**Comment by simod** [comment]
@NouranHossam you can check the apache logs for errors. We can move this discussion to the list geonode-users@lists@osgeo.org
