### ISSUE TITLE
Issues with docker-compose (allowed hosts & site migration)

### ISSUE THREAD

**Issue by kevincote** [GeoNode/geonode#3418]
I just cloned the latest branch of GeoNode and tried to get it up and running using the docker-compose file. I'm on Windows 7 with docker toolbox. 

1) Considering the docker toolbox uses a VM with IP 192.168.99.100, "localhost" must be changed to this IP in the `ALLOWED_HOSTS`. I've modified the `geonode/scripts/docker/env/production/django.env` script to include the IP in the `ALLOWED_HOSTS` variable. 

After doing docker-compose up again and opening a bash into the geonode_django_1 container, I can see the `ALLOWED_HOSTS` with my IP, but I'm still getting the error message about not having this IP in the allowed hosts.

![image](https://user-images.githubusercontent.com/31894882/32621457-d13beb10-c54d-11e7-8484-0a5624c6425e.png)
![image](https://user-images.githubusercontent.com/31894882/32621473-df8ab9ee-c54d-11e7-823c-71570ef8bb3a.png)

If I print the `ALLOWED_HOST` variable from the `manage.py` script, this is what I get:
![image](https://user-images.githubusercontent.com/31894882/32625359-046473d4-c55a-11e7-915f-83355f5a0ac4.png)

The problem seems to occur during parsing of the environment variables.

2) After bypassing the host problem by hardcoding the IP in the `settings.py` and removing the variable in the django.env file, I get this error:

![image](https://user-images.githubusercontent.com/31894882/32625482-5347799c-c55a-11e7-87f6-f148994c5916.png)

To solve it, I had to bash into the geonode_django_1 container and do a `python manage.py migrate`.

**Comment by Coop56** [comment]
I ran into the same issue with ALLOWED_HOSTS, and used the same solution as you except I made ALLOWED_HOSTS be geonode as I'm using the hosts setup described in the docs.

**Comment by Coop56** [comment]
FYI @kevincote I've got a PR going up today that will address this.

**Comment by Coop56** [comment]
This issue was resolved by https://github.com/GeoNode/geonode/pull/3423 if someone can please close it.
