### ISSUE TITLE
I am not able to logout from geonode

### ISSUE THREAD

**Issue by vinayak1411** [GeoNode/geonode#3424]
![screenshot 657](https://user-images.githubusercontent.com/20423959/32685731-141922a2-c6bd-11e7-98a2-44b22b0e5b3f.png)

respected sir,
I am getting error as shown in above screenshot whenever i try to logout from geonode,please help me. Also i want to know which version of cartoview is supported by geonode 2.6x.

**Comment by afabiani** [comment]
Hi,
you need to find your settings or local_settings (the place where you defined the access to the OGC Server) and manually add the missing properties.

Take a look at this code here and align your one to this:

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L637
