### ISSUE TITLE
Map query with insensitive case

### ISSUE THREAD

**Issue by carolinasuzuki** [GeoNode/geonode#3430]
I've tested my geonode's map query with strings that users don't know if the search term appears in lower case, upper case or a mix [like issue #1851]. Maybe, I think that insert the "ILIKE" in query option will sounds good to solve this case. The commit 23f21bf doesn't work in my case.

Besides that, I notice that to default, "Query by current map extent" is checked. For this reason usually I query something and the query don't find anything because my map is zoom other location. Maybe, for default, discheck this by current map extent help us too.

Thanks,

**Comment by simod** [comment]
This was probably related to geoexplorer which it would result in a "wontfix" Mapstore will probably behave differently
