### ISSUE TITLE
How to sign up GeoNode 2.6 

### ISSUE THREAD

**Issue by hyj521** [GeoNode/geonode#3433]
Why I can not sign up GeoNode 2.6 , there is no sign up or register link on any page

**Comment by simod** [comment]
@hyj521 registering in geonode must be enabled as per documentation http://docs.geonode.org/en/master/tutorials/advanced/geonode_production/production.html?highlight=registration#configuring-user-registration.

Ps, please use the mailing list to ask for support.

**Comment by hyj521** [comment]
@simod  My English is not very good. So I dont know who can I send  the email to.
for example:
from django.core.mail import send_mail
send_mail('Subject here', 'Here is the message.', 'from@example.com',
    ['to@example.com'], fail_silently=False)
the"from@example.com" is my mail addresses? and if I want to  register in geonode, what is the "to@example.com"?

**Comment by capooti** [comment]
@hyj521 questions should be posted in mailing list:
https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users
