### ISSUE TITLE
[Enhanced WMS capabilities] Error when accessing user's profile as anonymous user

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3439]
As an anonymous user, trying to get access to any users profiles causes an exception.

**Comment by capooti** [comment]
I am having a look at it and will add a test. Thanks!

**Comment by capooti** [comment]
@afabiani can't replicate this and I see there is already a test for it which runs successfully: https://github.com/GeoNode/geonode/blob/master/geonode/tests/smoke.py#L101

**Comment by afabiani** [comment]
@capooti try this URL

http://ihp-wins-dev.geo-solutions.it/people/profile/Marina.Rubio/

**Comment by capooti** [comment]
After some tests, I believe the problem is caused only when there is a "." in the username.
I will send a fix to this later today. I will also create a fixture user with "." in the username to see if similar problems araise.
PS: nice instance!
