### ISSUE TITLE
No support for authentication in API

### ISSUE THREAD

**Issue by timlinux** [GeoNode/geonode#3442]
Currently in the QGIS GeoNode client we are unable to authenticate using the API. The API should provide an abstraction for the different GeoNode backend services (e.g. QGIS Server, GeoNode Server) without requiring that the API user make direct calls to the underlying backend.

With an authentication layer in place we should be able to expose only available layers that the user has access to and extend GeoNode's API to support other actions such as uploading layers.

**Comment by timlinux** [comment]
CC @lucernae @ismailsunni

**Comment by lucernae** [comment]
Shouldn't we get funding first for this?

**Comment by francbartoli** [comment]
@timlinux @lucernae @ismailsunni is this closed by #3415 ?

**Comment by lucernae** [comment]
Thank's we need to check this again to see if this complements our use case 👍.

**Comment by afabiani** [comment]
Well, the authentication mechanism would be available in GeoNode already, it is OAuth2 and access_token as query parameter. Nevertheless I guess the best would be to enable the GeoNode GeoServer proxy to accept Basic Auth also, since QGis supports only this for now.

**Comment by Gustry** [comment]
Thanks @afabiani for the answer.

> Nevertheless I guess the best would be to enable the GeoNode GeoServer proxy to accept Basic Auth also, since QGis supports only this for now.

Quick note, we would need also to be able to use QGIS Server backend, not only geoserver.

**Comment by kttary** [comment]
@afabiani, given username and password of a user, how can we obtain access_token from geonode server from external app? Should we log in to geonode gui in order to obtain access token?

**Comment by afabiani** [comment]
latest versions of GeoNode come with a proxy

https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/urls.py#L43

allowing you to hit OWS endpoint by using basic authentication. A similar technique could be potentially used to create an end-point that provides you a validated access_token against BASIC AUTH.

See

https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/views.py#L431
