### ISSUE TITLE
Problem loading the uploaded layer

### ISSUE THREAD

**Issue by rksang3** [GeoNode/geonode#3443]
The layers uploads but instead of being able to open the layer it gives the error that there is a problem loading the uploaded layer

**Comment by capooti** [comment]
Please before filing a ticket check in users list if this is a bug. We also need more information about your system and GeoNode version.
https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users

**Comment by rksang3** [comment]
My system is Ubuntu 16.04.3 LTS. Geonode 2.9 with QGIS backend and running
on docker 17.06.2-ce
