### ISSUE TITLE
error at /account/invite_user/

### ISSUE THREAD

**Issue by hyj521** [GeoNode/geonode#3458]
I can not invite user,  there is the error:
[Errno 10061] 
Request Method:	POST
Request URL:	http://localhost/account/invite_user/
Django Version:	1.6.11
Exception Type:	error
Exception Value:	
[Errno 10061] 
Exception Location:	C:\GeoNode-2.4.x\Python27\Lib\socket.py in create_connection, line 575
Python Executable:	C:\GeoNode-2.4.x\Apache2\bin\Apache.exe
Python Version:	2.7.10
Python Path:	
['C:\\GeoNode-2.4.x\\geonode-2.4.x\\geonode\\Lib\\site-packages',
 'C:\\GeoNode-2.4.x\\Python27\\python27.zip',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x\\DLLs',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x\\lib',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x\\lib\\plat-win',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x\\lib\\lib-tk',
 'C:\\GeoNode-2.4.x\\Apache2\\bin',
 'C:\\GeoNode-2.4.x\\Python27\\Lib',
 'C:\\GeoNode-2.4.x\\Python27\\DLLs',
 'C:\\GeoNode-2.4.x\\Python27\\Lib\\lib-tk',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x',
 'C:\\GeoNode-2.4.x\\geonode-2.4.x\\lib\\site-packages',
 'C:\\GeoNode-2.4.x\\Apache2']

**Comment by afabiani** [comment]
Please see replies to
https://github.com/GeoNode/geonode/issues/3467

**Comment by afabiani** [comment]
P.S.: this will be fixed when https://github.com/GeoNode/geonode/pull/3461 is merged
