### ISSUE TITLE
Remove django-bootstrap-form from setup.py and requirements.txt

### ISSUE THREAD

**Issue by ricardogsilva** [GeoNode/geonode#3459]
[django-bootstrap-form](https://github.com/tzangms/django-bootstrap-form) is listed as a geonode dependency in both `setup.py` and `requirements.txt`. However it is seemingly not being used anywhere in geonode. I've checked with

```bash
grep -nir "{% load bootstrap %}" *
grep -nir "|bootstrap" *
```

And got no hits.
It seems like it would be safe to remove it.

**Comment by afabiani** [comment]
Can you do a simple PR for this?

I guess no tests are required in this case.

**Comment by ricardogsilva** [comment]
OK I'll supply a PR then ;)
