### ISSUE TITLE
Geonode install at Google Cloud Platform

### ISSUE THREAD

**Issue by phyokyi** [GeoNode/geonode#3465]
Hi,

I trying to install geonode 2.6 at google cloud platform.
Now I already open all my firewall port for geonode server which hosted at google cloud platform.
Even thought, it was not move an inch at final stage which updating geonode ip.
According instruction, at final stage
it should be as follow.
geonode-updateip <external ip>
at my local virtualbox it works perfectly.
but at google cloud engine, it doesn't work and stop moving at following message...

"Inspecting the available layers in GeoServer ..."

and it doesn't go forward.
My suspect is google cloud platform has one ip at local and another one is external ip.
let say at gce, has following ip
one for 20.0.0.1
one for loopback
but outside, there is external ip, e.g 300.20.10.1

i try with all
geonode-updateip 20.0.0.1
geonode-updateip 127.0.0.1
geonode-updateip 300.20.10.1

nothing works. and stuck at 
"Inspecting the available layers in GeoServer ..."

Any ideas?
	
Thanks

**Comment by francbartoli** [comment]
Hi @phyokyi whatever is your front-end ip you have to reconfigure oauth2 settings in GeoServer too. I think you should take a look carefully to the piece of documentation for that.

**Comment by francbartoli** [comment]
I'm going to close this it hasn't any relevance with the code itself. It's just a matter of the configuration
