### ISSUE TITLE
Try The Demo button at http://geonode.org broken

### ISSUE THREAD

**Issue by rduivenvoorde** [GeoNode/geonode#3472]
Hoping to find a running geonode instance, I clicked the Try The Demo button on the frontpage. 

But it shows me currently a stracktrace:

DoesNotExist at /
Profile matching query does not exist.

etc...

**Comment by cortesimone** [comment]
👍 me too, can you help? I'm looking for a demo instance of geonode, before installing it. Thanks, S.

**Comment by francbartoli** [comment]
@cortesimone there are a lot around, one possibility to get quickly an instance up and running to give a try is to use devops options with docker and ansible

- Using shortcut [here](https://github.com/GeoNode/geonode/blob/master/Makefile#L1)
- Using this [repo](https://github.com/GeoNode/ansible-geonode)

Unfortunately demo site was no longer supported and it is discontinued at this moment.

**Comment by francbartoli** [comment]
Guys thanks for your advises, geonode demo will be back and upgraded with the new year. I'm going to close this one.
