### ISSUE TITLE
 - Support for GeoServer Importer on 'master' branch

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3480]
Fork boundless one in order to:

- Keep the importer consistent with GeoNode/GeoServer operations
- Be able to update it without breaking backwards compatibility of old GeoNode versions
- Improve importer functionalities as GeoNode community

**Comment by kalxas** [comment]
So, we are going to maintain this fork on our GitHub?

**Comment by afabiani** [comment]
Yep, this is the idea. So we can manage our ppa / pypi / whatever distribution without touching boundless stuff.
