### ISSUE TITLE
GNIP: Add support for vector temporal series to GeoNode (CSV/SHP).

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3485]
## Proposed by

Alessio Fabiani ([GeoSolutions](http://www.geo-solutions.it))
## Assigned to release

None yet.

# Add support for vector temporal series to GeoNode.

### 1. Background

GeoNode 2.7 and above can use GeoServer 2.12.x as GIS-Server backend. Currently on latest versions of GeoServer, the Importer plugin has been improved a lot, along with its REST APIs support.

In particular there is the possibility to inject and manage the so called "transformations" to the ingest session in order to pre-process data before actually creating the layer into GeoServer.

The possibilities are a lot. It is possible not only to indicate to GeoServer which target workspaces/stores use to ingest data (either vectorial and raster), but it is also possible, as an instance, to:

- Remap attributes of vectorial features in order to specify which fields to use as geometry
- Specify the native spatial reference system if none is present on input data
- Specify a target spatial reference system in order to let GeoServer reproject data to that one
- Specify temporal transformations in order to allow GeoServer creating a "TIME" dimension for temporal series

The last functionality is of particular interest for us. By using that one, we can allow GeoNode to support seamlessly vector temporal series natively on GeoServer.

### 2. Proposal

In this GNIP, we propose to fix and improve the whole GeoNode Upload process in order to:

- Re-enable and correctly manage the GeoServer Importer
- Auto-detect if input data has geometries or not
- Auto-detect if input data has suitable native spatial reference system or not
- Auto-detect if input data can be optionally configured as vector temporal series

Moreover as part of this proposal we want also to enable the time-slider on GeoNode native GIS client, in order to provide support for animations and time-dimension set-up when GeoNode detects a vector temporal series.

##### 2.1 Functional perspective

As stated above, the main focus of this work package is to:
 - Fix and improve the GeoNode Upload process.
 - Enable support for vector temporal series (on GIS client also).

Side effects of this work will be also:
- Complete support for CSV data import
- Give to users the possibility of importing geospatial data with incorrect or not-specified Native CRS

##### 2.2 Fix the GeoNode/GeoServer Importer communication and workflow

Initial work would be to restore and improve the communication and workflow between GeoNode and GeoServer Importer.

Currently not only there is a wrong management of the errors, causing, most of the time Importer to fail, but also the workflow and creation of Importer Transformation is incomplete or not-functional.

First thing to do is to be sure everything is up and running again. It is possible that there will be the necessity of improving/modifying the Python library "gsimporter" which manages the REST communication between GeoNode and GeoServer Importer.

To achieve this and to avoid breaking/interfere with original "gsimporter" library, we propose to create a fork and a new Python package calle "gn-gsimporter", as per 

https://github.com/GeoNode/geonode/issues/3480 - Support for GeoServer Importer on 'master' branch

##### 2.3 Auto-detect if a vector layer can support a temporal dimension or not

We want that in the usual cases, nothing changes for the user, while improving the human experience and frontend feedbacks when more options can be activated on vector data sources.

Part of this work will be to allow GeoNode to perform internal checks (on the data also) in order to automatically detect if the data source can be configured as a temporal series.

In such cases GeoNode will advertise the users that more option are available to complete the upload workflow

![image](https://user-images.githubusercontent.com/1278021/33720209-826a656c-db63-11e7-9659-c729038f8fdd.png)

#### 2.4 Early detection of errors on datasets

Part of this work will be to improve a lot the time-dimension management on GeoNode side, both on the backend and the frontend.

The main goal is to prevent as much as possible to send wrong data to the GeoServer Importer before actually starting the ingestion. The proposal is specified here below:

##### 2.5 Upload Vector Time Series with time dimension

GeoNode will be improved in order to simplify the “upload” interface and automate as much as possible the process of detecting the time dimension as follows:
- Users will be allowed to upload both CSV and Shapefiles to create a time series layer
- GeoNode will perform a scan of the attributes on a successful upload
- If it will detect one or more attributes with type “Date”, the interface will propose to the user the possibility of configuring the time dimension, using the indicated attributed time attribute
- Attributes of type “Integer” can be turned into a time dimension where the values would be interpreted as years. Careful with this as we do not have negative years!
Attributes of type “String” can be turned into a time dimension if their values can be parsed according to a certain number of time patterns which can be configured by the admin but for which we should provide a sensible default (e.g. take this from GeoServer time parser in GetMap requests). Notice that the same exact patterns must be configured on the GeoServer side.
- GeoNode will try to parse the first N features of the dataset in order to recognize a supported date-time format. This is kind of a dry-run to test the ability to successfully parse the incoming data. N will be configurable. The procedure will present the fields on a tabular fashion, thus allowing user to double check parsing results and select the attribute columns. 
    - For CSVs the user will be asked to select:
        - Latitude column
        - Longitude column
        - Date column
    - For SHPs the user will be asked to select:
       - Date column

GeoNode will allow the user to inspect data and choose, through a guided procedure and decide if it is eligible as temporal series or not

![image](https://user-images.githubusercontent.com/1278021/33720487-5f2d4cbc-db64-11e7-8bd4-6ad55f5dea9e.png)

GeoNode will allow to select a column eligible as time dimension

![image](https://user-images.githubusercontent.com/1278021/33720512-7304f0aa-db64-11e7-9037-e54cbf85f78a.png)

By default GeoNode will search for:

   - Simple ISO 8601 notations without Timezone
       ```
        yyyy-MM-dd’T’HH:mm:sss
        yyyy-MM-dd’T’HH:mm:ss
        yyyy-MM-dd’T’HH:mm
        yyyy-MM-dd’T’HH
        yyyy-MM-dd
        yyyy-MM
        yyyy
        ```
    - 2/4 digits numbers representing the year
    - GeoNode will assume “UTC” as Timezone
    - Input data must be correctly formatted in order to continue ingesting data

Time dimension presentation will be always “List” by default. Some “advanced” options could allow the user to specify one among:
    - **List** of all the distinct time values
    - **Intervals** defined by the resolution
    - **Continuous** Intervals for data that is frequently updated, resolution describes the frequency of updates

At the end of the process TimeSeries will be added both as layers as well as below a special timeseries menu item.

As stated above, GeoNode will prevent importing wrongly configured dataset through an early detection of potential issues
![image](https://user-images.githubusercontent.com/1278021/33720985-ebe2143e-db65-11e7-9366-49fa5eaaf8f9.png)

##### 2.6 Enable time-slider on native GIS client

As stated above, whenever GeoNode detects that a Layer has a time dimension, it will automatically enable a time slider on the native GIS client toolbar

![time_series](https://user-images.githubusercontent.com/1278021/33721425-4165e510-db67-11e7-8ec1-94b52c831e7a.gif)

##### 2.7 Detect issues on source data and allow users to take action (improved support for CSVs)

Part of this work will be also an enhancement to the whole upload workflow. Additional "steps" will be activated in case of other issues detected on source dataset, like

 - Checks for geometry column if no-geometry can be detected on source data
![image](https://user-images.githubusercontent.com/1278021/33720852-89e79cea-db65-11e7-818c-04da89965328.png)

 - Checks for data native spatial reference system and allow the user to specify one in case of wrong or missing
![image](https://user-images.githubusercontent.com/1278021/33720892-a8fbcdf4-db65-11e7-905d-dfc6f799d6f5.png)

### 3 Additional (missing) Tasks

Things to be developed from scratch, and supported as part of future GNIPs, are:

* Support for GWC TIME filter-parameter as GeoServer Importer additional Task.
* Improvements to Image-Mosaics and Raster temporal series
* Allow the uploader to specify GDAL transformations on Raster data

**Comment by tomkralidis** [comment]
+1. We should also ensure that the ISO metadata gets updated accordingly.

**Comment by francbartoli** [comment]
I'd love if time-dimension support of GeoNode side could be as much as possible agnostic of the backend at certain point. In particular that would allow to connect different data sources like:

- Raster temporal series from GeoServer (i.e. NetCDF, etc)
- Time-series from [Timescaledb](https://github.com/timescale/timescaledb) which is a postgresql extension
- [Pandas](https://github.com/pandas-dev/pandas) time series

Great proposal anyway!

**Comment by capooti** [comment]
This would be great!
I agree with @francbartoli comment.

**Comment by afabiani** [comment]
hi @francbartoli currently this workflow improves the support for GeoServer Importer, therefore any raster/vectorial format supported by the Importer can be supported by this workflow either.

Actually I did not proposed a complete refactoring of the upload process, even because there are already projects in place to do it (e.g. django-importer) which can be plugged to GeoNode.

Moving on with GeoNode 3.0 there are already in place proposals to decouple APIs from backends and conceptually change the way GeoNode stores and manages geospatial files. But I guess this is a bit out of the scope of this PR.

@tomkralidis very good point. Let's do a specific GNIP for that even because it would require some technical discussion I guess.
