### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by hyj521** [GeoNode/geonode#3492]
Hi,
    why i click on ‘Geoserver’ in GeoNode 2.6   of  localhost , there will appear '503 Service Unavailable'？
![Uploading 图片.png…]()

**Comment by simod** [comment]
@hyj521 Means that Tomcat/geoserver is not running. 

Ps please use the geonode-users@lists.osgeo.org to ask for support rather than the ticketing system. 

Best
