### ISSUE TITLE
GNIP: Improve Remote Services

### ISSUE THREAD

**Issue by ricardogsilva** [GeoNode/geonode#3517]
### Proposed by
Ricardo Garcia Silva (http://www.geo-solutions.it/)

### Assigned to release
None yet.

# Improve Remote Services

## 1. Background
Geonode currently has a *remote services* feature where it is possible to connect with external services and import additional layers into a geonode site. This feature was added in [GNIP16 - Remote Services](https://github.com/GeoNode/geonode/issues/1330). 
The workflow does essentially a harvest of the remote service, importing any suitable layers into the local geonode installation. 

While the current implementation works and users may add several service types to their geonode sites, there are a number of drawbacks:

1. User registration is tightly coupled with resource harvesting. A user has no way of knowing in advance which layers will be created when registering a service, nor can it choose which of the service's layers should be imported into geonode
1. User experience while adding a service is not great. Importing remote resources is a long running operation. However geonode currently provides little feedback to the user on what is happenning once the service registration/layer import workflow is set in motion.
1. The code does not scale. The current implementation places too many responsibilities on the [geonode.services.views.register_service](https://github.com/GeoNode/geonode/blob/97c0c37d3aba76b8c1ec55677b9a3c1dbc15805b/geonode/services/views.py#L92) view function. Also, the remote services code is overall hard to extend and maintain.

## 2. Proposal

With the current GNIP we are proposing to refactor the `genode.services` app in such a way as to fix the issues identified in the previous section.

### Decouple service registration from resource import

Splitting the process of registration/import flow into two distinct steps allows the user to have better control of the process. It becomes possible to import resources at a later date, potentially even newer resources that might have become available in the meanwhile.
The service list view is enhanced with an *Import Service Resources* button that takes the user to a new view, where the available resources can be inspected and imported. It is also possible to ask for a rescan of the service, in order to discover if new resources are available.

![import_split_from_registration](https://user-images.githubusercontent.com/732010/34111819-b0ae3e42-e402-11e7-9c11-16bbe26598b7.png)
When a service is registered, its details page has a new *Import resources* button...   

![import_split_from_registration2](https://user-images.githubusercontent.com/732010/34111820-b0d62a7e-e402-11e7-95c1-8d861a3e44a1.png)
... Which leads to a new view, where the existing resources may be inspected and imported. It is also possible to rescan the service for new resources.

### Improve user experience while working with Remote Services

The Remote Services section of geonode has many operations that can take a long time to perform (or even fail), such as:

- A remote service may be slow to respond or be temporarily offline;
- Importing resources may take a long time, or it may not work at all;
- etc.

In addition, some operations may be blocking while others may be asynchronous. As such, it is desirable to keep the user informed of what is happening at all times. This proposal features:

- Adding modal dialogues for blocking operations. This will let the user know that there is some background activity going on. An example of this is the deletion of a previsouly configured service;
  ![modal_dialog_example](https://user-images.githubusercontent.com/732010/34112568-e2b94bd2-e404-11e7-99d4-fb150da6516f.png)

- Adding informative messages to the user by leveraging the django messaging framework, which is already available to geonode;

- Adding a section in the service details view that is updated while the resources are being imported.
  ![async_import](https://user-images.githubusercontent.com/732010/34112669-385120ce-e405-11e7-9463-05408aaae265.png)

- The possibility to import resources asynchronously, by using a properly configured celery install. Otherwise, resources are imported with a synchronous (blocking) call. Async imports are faster too, since they are parallelizable;

The following gif provides an overview of the whole flow:
![peek 2017-12-18 14-31](https://user-images.githubusercontent.com/732010/34112724-5fc002f6-e405-11e7-988f-ef7a382f23dc.gif)

### Clean up the code in order to set up a baseline for further improvement

In order to ease the maintenance of the code, a refactor of the current `geonode.services` app and also some minor parts of `geonode.layers` and `geonode.security` are foreseen. A new `services.serviceprocessors` package is introduced. This package provides the `services.serviceprocessors.base.ServiceHandlerBase`, a class that defines an interface that is used by geonode in order to interact with a remote service. 

This class must be specialized by concrete implementations for each service type. It illustrates the expected interface that child classes must respect in order to be usable as remote services. The inner implementation is based on `owslib`, but this is not visible to the geonode client code in any way. This means that adding additional remote services is mostly a matter of subclassing the base class and implementing the required methods. This GNIP includes support for WMS.

The interface that any service must conform to is composed of the following methods:

```python
class ServiceHandlerBase(object):
    url = None
    service_type = None
    name = ""
    indexing_method = None

    def __init__(self, url):
        pass

    def create_geonode_service(self, owner, parent=None):
        raise NotImplementedError

    def get_keywords(self):
        raise NotImplementedError

    def get_resource(self, resource_id):
        raise NotImplementedError

    def get_resources(self):
        raise NotImplementedError

    def harvest_resource(self, resource_id, geonode_service):
        raise NotImplementedError

    def has_resources(self):
        raise NotImplementedError
```

In addition to the `geonode.services` app, the following major changes are foreseen elsewhere in the geonode codebase:

- `geonode.layers` - `Layer` objects [regain their explicit relationship](https://github.com/GeoNode/geonode/pull/2629) with `services.models.Service`, which had been removed previously due to some conflicts. Those are fixed in this GNIP and the relationship is re-established between these two entities. A `Layer` has a nullable foreign key to a `Service`, meaning that it may or may not belong to a single service. This leads to some simplification of the `Layer` API and increased performance too, as it becomes unnecessary to traverse other tables when determining if a layer has a corresponding service or not;

- `geonode.security` - It becomes necessary to account for service-based layers when the appropriate geofence rules are created/updated. Layers that come from indexed services are not managed by geofence at all.

- Overall `celery` tasks are refactored into shared tasks and moved into their corresponding geonode apps. Also, celery settings are renamed in order to better conform with the current [release docs](http://docs.celeryproject.org/en/latest/#). This enables the automatic import of tasks and an overall smooter operation of celery with geonode.

## 3. Additional (missing) tasks
- Bring back support for the currently supported services. This GNIP only features support for WMS. Adding back the remaining services should not be a difficult task, since the core implementation can be adapted from the current geonode codebase, while taking the new WMS code as an example;

## 4. Future work
This GNIP enables some interesting possibilities for expanding the remote services functionality of geonode:

- Adding authentication to remote services
- Adding more layer based service types, 
- Adding support for non layer-based services

**Comment by cezio** [comment]
This issue looks related and probably can be closed when this GNIP is read: https://github.com/GeoNode/geonode/issues/3435

**Comment by capooti** [comment]
great stuff!
make sure to have a look at Hypermap that, even if it is not integrated in GeoNode, implements something like this using the same stack (for WMS and also Esri REST).
In my TODO list there was a commitment to integrate Hypermap in GeoNode as a way to import remote services, but you may have already implemented what you need.
Note that Hypermap does not only register remote services and layers, but it also provide a way to health check them and to search them (using Solr or Elasticsearch).

https://github.com/cga-harvard/HHypermap
