### ISSUE TITLE
Non-superuser cannot view layers with 'Everyone' permissions - Geonode 2.6.x

### ISSUE THREAD

**Issue by olearytd** [GeoNode/geonode#3530]
I have Geonode 2.6.x running on a Centos 7 machine.  I installed via the developer documentation found here:
http://docs.geonode.org/en/master/tutorials/install_and_admin/setup_on_centos/setup_centos.html

My current issue is if a user is not a superuser, they cannot see the uploaded layer on the map.  They can see the layers that have been uploaded, thumbnails, etc but if the user clicks a layer then the layer outlines do not return.

<img width="871" alt="screen shot 2017-12-22 at 6 12 01 am" src="https://user-images.githubusercontent.com/6729929/34296137-0e4f31bc-e6df-11e7-8ab5-e9ef002e25f0.png">

-------

<img width="1206" alt="screen shot 2017-12-22 at 6 12 33 am" src="https://user-images.githubusercontent.com/6729929/34296151-21232528-e6df-11e7-9409-6bd816b5303b.png">

Looking at the network log, I see the geoserver web call and I am getting 200 OK because it is authenticating my user but if I look at the output of the OK request I get this:

`Could not find layer geonode:wdb3`

Logging into Geoserver with the above user (via geonode Oauth Provider) I can see in layer preview that there are 184 layers (correct) but I can't view any of them.

<img width="1049" alt="screen shot 2017-12-22 at 6 11 13 am" src="https://user-images.githubusercontent.com/6729929/34296115-f6a9b29e-e6de-11e7-8fda-243cf0c3624d.png">

Permissions for all layers are set to 'Anyone' - and if I change this same user to 'Superuser' everything works as expected.

I've been looking at configurations on the security documentation provided but I can't seem to find what could be the problem.  Any help would be appreciated.

**Comment by olearytd** [comment]
ping

**Comment by simod** [comment]
@olearytd please ask on the mailing list geonode-users@lists.osgeo.org for support, this looks like a misconfiguration rather than a bug. Closing it for now
