### ISSUE TITLE
No module named 'celery'

### ISSUE THREAD

**Issue by hyj521** [GeoNode/geonode#3531]
Hi everyone,
     When I creating an APP, there is error in GeoNode-2.6.x ,
![default](https://user-images.githubusercontent.com/33618918/34296489-fdc51220-e74d-11e7-988c-bf3f7d54e1e7.png)
![default](https://user-images.githubusercontent.com/33618918/34296492-ff68cdd8-e74d-11e7-88f6-c373a08d2e86.png)
I don't know where is the celery, if you have one, can you send me one?Thanks!
Best regards,
HYJ521

**Comment by capooti** [comment]
Which is an APP?
Anyway, accordingly to requirements.txt, you need celery==3.1.18
https://github.com/GeoNode/geonode/blob/2.6.x/requirements.txt#L12

**Comment by hyj521** [comment]
Hi capooti,
     I want to creat a table in the  “element” witch in C:\GeoNode-2.6.x\geonode-2.6.x \geonode\ . But when I input "python manage.py makemigrations", there will be an error. how  can I do?
![default](https://user-images.githubusercontent.com/33618918/34320206-392914a6-e82f-11e7-9561-b55d96e1946f.png)

**Comment by capooti** [comment]
Can you please check the output of "pip freeze"?
You should see:
...
boto==2.38.0
celery==3.1.18
dj-database-url==0.4.2
...

If it is not there I am not sure why, and I am not familiar with Windows setup. You can try to install it with "pip install celery==3.1.18" (though it should be there already)

**Comment by hyj521** [comment]
Hi，capooti
   Thank you , I readed the document https://github.com/GeoNode/geonode/blob/2.6.x/requirements.txt#L12, and I installed what I need. But when I want to creat a table useing 'python manage.py makemigrations ' .There will appear errors like the pictures. What should I do next？
![default](https://user-images.githubusercontent.com/33618918/34458688-a6438304-ee16-11e7-88bc-b2e1f80bce71.png)
![Uploading 图片.png…]()
![Uploading 图片.png…]()
