### ISSUE TITLE
Upgraded to Geoserver 2.12.1 -- Unexpected Exception

### ISSUE THREAD

**Issue by unnivm** [GeoNode/geonode#3543]
Hello all,

I upgraded `Geoserver` to `2.12.1 `and tried to upload a layer using `Geonode`. But I am getting `"Unexpected Exception".`  

Is that `Geonode` will not support latest version of `Geoserver`?

My idea is to selecting latest `Geoserver` is to provide support for  `"mbtiles"` and I have installed `mbtiles `and `wps` plugins as well.

Any lead will be much appreciated.

Thanks,
Unni M

**Comment by t-book** [comment]
Which geonode version and have you setup oauth correctly?
