### ISSUE TITLE
Docker Error: Cannot start service celery & django

### ISSUE THREAD

**Issue by jirik** [GeoNode/geonode#3544]
I am trying to run geonode using docker-compose according to [readme](https://github.com/GeoNode/geonode#docker-usage):
```
docker-compose build
docker-compose up
```
The first one succeeds. The second one fails:
```
geonode_rabbitmq_1 is up-to-date
Starting geoserver_data_dir ... 
geonode_elasticsearch_1 is up-to-date
geonode_postgres_1 is up-to-date
Starting geonode_django_1 ... 
Starting geonode_celery_1 ... 
[1A[2K
Starting geoserver_data_dir ... [32mdone[0m
[1Bgeonode_geoserver_1 is up-to-date
[1A[2K
Starting geonode_celery_1 ... [31merror[0m
[1B
ERROR: for geonode_celery_1  Cannot start service celery: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown
[1A[2K
Starting geonode_django_1 ... [31merror[0m
[1B
ERROR: for geonode_django_1  Cannot start service django: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for celery  Cannot start service celery: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for django  Cannot start service django: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown
Encountered errors while bringing up the project.
```

I tried it for tag 2.6 and 2.6.3, same result.

Any suggestions what might be wrong?

Additional info:
- kubuntu 16.04
- Docker version 17.12.0-ce, build c97c6d6
- docker-compose version 1.18.0, build 8dd22a9
- [log_2.6.3_docker_compose_build.txt](https://github.com/GeoNode/geonode/files/1609168/log_2.6.3_docker_compose_build.txt)
- [log_2.6.3_docker_compose_up.txt](https://github.com/GeoNode/geonode/files/1609173/log_2.6.3_docker_compose_up.txt)

**Comment by francbartoli** [comment]
@jirik can you try again with the open PR #3538 ?

**Comment by hishamkaram** [comment]
+1

**Comment by jirik** [comment]
@francbartoli Thanks for your work and reaction! I have tried #3538 in two different ways. Unfortunately no one succeeded.

1.
```bash
docker-compose build
docker-compose up
```
Both run without exiting, but with some errors; [see the log](https://github.com/GeoNode/geonode/files/1673714/log2.txt) (expecially django and celery, same error for both).


2.
```
# edited in Makefile
DOCKER_HOST := localhost
DOCKER_HOST_IP := 127.0.0.1

make up-with-build
```
No errors visible (runs in background). However `http://localhost` gives me HTTP Error 502 (from nginx).

**Comment by francbartoli** [comment]
@jirik running that specific PR you have to open geonode on the IP address of the docker daemon, which can be found out from this command:

`docker run --net=host codenvy/che-ip:nightly`

Remember to fetch all new commits of [#3538](https://github.com/GeoNode/geonode/pull/3538) and remove all old images from geonode namespace

Thanks for you tests

**Comment by francbartoli** [comment]
.2 is useless so you don't have to make any edit of makefile.
