### ISSUE TITLE
Error on Uploading layers

### ISSUE THREAD

**Issue by rgdamalerio** [GeoNode/geonode#3567]
Unexpected exception 'NoneType' object has no attribute 'get_resources'

**Comment by simod** [comment]
Please use the mailing lists to ask for support. Tickets are for declared bugs or improvements.

**Comment by rgdamalerio** [comment]
@simod can you guide me what to do when using mailing lists to ask for support. sorry I'm just a newbie in github

**Comment by simod** [comment]
When did you send it? I haven't received it. For mailing list is enough for you to subscribe and sent it. https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users

**Comment by rgdamalerio** [comment]
This is the error i encounter when uploading layer Unexpected exception 'NoneType' object has no attribute 'get_resources' I use the master branch. 


Other problem is i have a working project version 2.6.3 the stable version. problem in layer preview all upload layer have no thumbnail. I use SRID 4326.. hope you can help me...

**Comment by rgdamalerio** [comment]
any help from the owner?

**Comment by afabiani** [comment]
@rgdamalerio about the error you reporting, it looks to me that there could be some issue communicating with the backend geospatial service, somehow. Unfortunately it is almost impossible to understand the issue with just that information. Could you try please to find the GeoNode logs and find the exact point where the exception occurs?
