### ISSUE TITLE
GeoNode 2.8 test apt-get installed - changing layer ownership issue

### ISSUE THREAD

**Issue by danieldids** [GeoNode/geonode#3580]
After changing a layer's owner, the new owner still has no control over it. Is it a feature or a bug? It seems counter intuitive if it's a feature. I have to change permissions so the new owner can change metadata or styles.

Just to make it clear: i've installed geonode 2.8 using testing debian repo, on ubuntu 16.04

**Comment by afabiani** [comment]
Update available on master branch. Will be backported soon.

**Comment by danieldids** [comment]
So it was a bug? Seems so, I'm closing this issue.
