### ISSUE TITLE
geonode2.8rc11 working in one partition of same PC , but doesnot work in other

### ISSUE THREAD

**Issue by jitendrashahiitb** [GeoNode/geonode#3587]
See below the snapshots of geonode 2.8rc11 working in sda9 partition in my PC
( strangely on partition sdb5, with freshly installed ubuntu 16.04.03 and after repository ppa:geonode/testing was used, I get following suuccessfully
![some layers_in_geonode2 8](https://user-images.githubusercontent.com/4946297/35639334-e722b282-06df-11e8-8009-4b81e6d705b4.png)

 

- can click on map and window of info ( all attributes for the corresponding polygon (village) ) opens
- 
![geonode_2 8_working_in_one_partition](https://user-images.githubusercontent.com/4946297/35639142-3a88c00c-06df-11e8-98fa-1cc24c20d0e7.png)
![some layers_in_geonode2 8](https://user-images.githubusercontent.com/4946297/35639161-49e339e2-06df-11e8-8bf4-0edd1f51a695.png)
![geonode_maha](https://user-images.githubusercontent.com/4946297/35639171-539d8398-06df-11e8-8363-f2417a3df915.png)
![get_feature_info_sticky_window](https://user-images.githubusercontent.com/4946297/35639178-5d67e6e8-06df-11e8-831f-195c67a6a3af.png)
![query_on_map](https://user-images.githubusercontent.com/4946297/35639191-65b3583c-06df-11e8-967f-78ad9df4aa77.png)

**Comment by jitendrashahiitb** [comment]
Attaching the local_settings.py in the working partition.

[local_settings_dot_py_working.txt](https://github.com/GeoNode/geonode/files/1684259/local_settings_dot_py_working.txt)

Does this give any clue?

**Comment by afabiani** [comment]
My guess is that some package conflicted with previous installations and/or
some folder did not have been correctly configured.

It would be good to have the Apache2 error log of your previous non-working
installation

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

2018-02-01 6:15 GMT+01:00 jitendrashahiitb <notifications@github.com>:
