### ISSUE TITLE
 Authentication Providers

### ISSUE THREAD

**Issue by georgepoulos** [GeoNode/geonode#3590]
Hello 
I install with apt-get on ubuntu 16.04 server the testing ppa of latest geonode
But i have problem with Authentication Providers. In geoserver security - authentication i can not find 
Authentication Provider Geonodeauth there is only default and geofence.
What's going wrong? and how possible is to add the geonodeauth provider?

**Comment by afabiani** [comment]
ppa:testing now ships GeoNode 2.8.0rc11 which is based on GeoServer 2.12.x and OAuth2 Authentication System.

The old GeoNodeAuthProvider does not exist anymore.

Please read carefully this documentation if you want to upgrade your GeoNode version

http://docs.geonode.org/en/master/tutorials/admin/geoserver_geonode_security/

**Comment by georgepoulos** [comment]
Thank you
