### ISSUE TITLE
docker-compose is not working

### ISSUE THREAD

**Issue by alexgleith** [GeoNode/geonode#3594]
Running the standard command `docker-compose up` is failing with the following errors:

```
docker-compose up
Recreating geonode_elasticsearch_1 ... 
Recreating geoserver_data_dir ... 
Recreating geonode_postgres_1 ... 
Recreating geonode_elasticsearch_1 ... done
Recreating geonode_rabbitmq_1 ... done
Recreating geonode_celery_1 ... 
Recreating geonode_consumers_1 ... 
Recreating geonode_celery_1 ... error

ERROR: for geonode_celery_1  Cannot start service celery: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrRecreating geonode_consumers_1 ... error

ERROR: for geonode_consumers_1  Cannot start service consumers: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/apRecreating geonode_django_1 ... error

ERROR: for geonode_django_1  Cannot start service django: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for celery  Cannot start service celery: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for consumers  Cannot start service consumers: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for django  Cannot start service django: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

Details:
 * docker --version
> Docker version 18.02.0-ce-rc2, build f968a2c
 * docker-compose --version
> docker-compose version 1.19.0-rc2, build a186c31

Running out of the current master branch (as at 3 Feb 2018)

Edit: also tried with the 2.7.x branch and it also didn't build.

**Comment by afabiani** [comment]
@alexgleith could you give it a try by using the notes here

https://docs.google.com/document/d/1Hgvx_WuFRyIEORcqoWBC8MFRXlSj-vzALYBE_IWxSpw/edit?usp=sharing

also, notice that the containers require a considerable amount of resources.

**Comment by dvictori** [comment]
I'm having the same issue. Tried to log into the django container (following @afabiani notes) to see what's going on and I got the message that the container was not running.

I'm running the latest master branch with docker 17.12 and docker-compose 1.18

**Comment by afabiani** [comment]
@dvictori I guess it actually works only with GeoNode 2.6.3

Adding @francbartoli for confirmation. He was going to work to fix for GeoNode 2.7.5

**Comment by francbartoli** [comment]
Confirm, it is limited to 2.6.x for now. I’m going to start to porting that to master/2.7.x

**Comment by dvictori** [comment]
Tried to run using the code under git tag 2.6.3 but I'm still getting the same error. Here are the steps I've taken:

1. Created new branch based from the 2.6.3 tag
`git checkout -b my_docker 2.6.3`

2. Add proxy settings to docker-compose.yml. Must do this in order to download python requirements. Done by adding the following lines to django service

```
django:
  build:
         args:
              - http_proxy
              - https_proxy
              - no_proxy
```
3. Built the docker images - command finishes with no error messages
`docker-compose build`

4. Start the docker images
`docker-compose up`

The last command finished with the error:

```
(...)
Status: Downloaded newer image for geonode/nginx:geoserver
Creating geonode_elasticsearch_1 ... done
Creating geonode_rabbitmq_1      ... 
Creating geoserver_data_dir ... 
Creating geonode_django_1        ... error
Creating geonode_geoserver_1     ... 
Creating geonode_geoserver_1     ... done
Creating geonode_celery_1        ... 

ERROR: for geonode_django_1  Cannot start service django: OCI runtime create faiCreating geonode_celery_1        ... error
/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for geonode_celery_1  Cannot start service celery: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for celery  Cannot start service celery: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown

ERROR: for django  Cannot start service django: OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"/usr/src/app/entrypoint.sh\": stat /usr/src/app/entrypoint.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

Could it be that by adding the proxy setting in the build step, I messed something up?

**Comment by francbartoli** [comment]
@dvictori it seems in your current branch, which should be 2.6.x, the file [entrypoint](https://github.com/GeoNode/geonode/blob/2.6.x/entrypoint.sh) is missing. Could you list your current base directory?

**Comment by dvictori** [comment]
Ahaa!! I misunderstood. A problem between the keyboard and the chair ;)

I was using the _2.6.3 tag from the master_ branch. I changed to the _2.6.x branch_ and it now works! Great!

**Comment by francbartoli** [comment]
Happy to hearing that. Going to close it

**Comment by ptrkrnstnr** [comment]
Hello! I got the same problem but I don't know how to pull a specific version of geonode, as it's a dependency of Nginx :(

> Pulling geonode (geonode/nginx:geoserver)...
> geoserver: Pulling from geonode/nginx
> e7bb522d92ff: Pull complete
> 6edc05228666: Pull complete
> Creating geoserver_data_dir ... done
> Creating geonode_postgres_1      ... done
> Creating geonode_rabbitmq_1      ... done
> Creating geonode_elasticsearch_1 ... done
> Creating geonode_elasticsearch_1 ...
> Creating geonode_postgres_1      ...
> Creating geonode_rabbitmq_1      ...
> Creating geoserver_data_dir ...
> Creating geonode_celery_1        ... error
> Creating geonode_django_1        ...
> Creating geonode_django_1        ... error

my docker compose file looks like this:
`version: '2'
services:

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch

  rabbitmq:
     image: rabbitmq

  django:
    image: geonode/django
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    command: django-admin.py runserver 0.0.0.0:8000 --settings=geonode.settings  
    env_file:
      - ./scripts/docker/env/production/django.env

  celery:
    image: geonode/django
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=geonode.celery_app:app -B -l INFO
    env_file:
      - ./scripts/docker/env/production/django.env

  geoserver:
    image: geonode/geoserver:alias
    links:
      - postgres
    ports:
      - "8080"
    volumes_from:
      - data_dir_conf
    env_file:
      - ./scripts/docker/env/production/geoserver.env

  geonode:
    build: nginx-docker/
    links:
      - django
      - geoserver
    ports:
      - "8011:80"

  data_dir_conf:
    image: geonode/geoserver_data:2.9.x-oauth2
    container_name: geoserver_data_dir
    command: /bin/true
    volumes:
      - /geoserver_data/data

volumes:

  geoserver_data_dir:`

Is it possible to pull a specific version of geonode here? 

Thank you very much!

**Comment by francbartoli** [comment]
Specific version are stitched to the branch model of geonode repo
