### ISSUE TITLE
Download filter not working

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3609]
On version 2.8rc11, from a layer page, Download Layer > Data tab: entering a filter and/or feature limit has no effect (on the download URLs).

Selecting an attribute gives a Chrome Dev Console error e.g. "Uncaught TypeError: Cannot read property 'STATE_CODE' of undefined".

Clicking "+" after entering an operator and value gives "Uncaught TypeError: $(...).select2(...).text.trim is not a function".

**Comment by afabiani** [comment]
@jondoig patch for 2.9.x available here https://github.com/GeoNode/geonode/pull/3611

As soon as it will be approved, we can backport to 2.7/8.x
