### ISSUE TITLE
Geoserver and layers problem

### ISSUE THREAD

**Issue by shakyD** [GeoNode/geonode#3612]
Hello good day, I'm a bit of a newbie to geonode and fully understanding how it works, so any help would be greatly appreciated.
I'm using geonode 2.6, and when I try to log in to geoserver using my same geonode admin credentials, i get "Invalid username/password combination.". Any help to resolving or understanding this issue would be greatly appreciated. 
Another issue I need assistance with is my layers not showing. I uploaded everything needed to show the layers and it was working properly, then all of a sudden they longer show. Not sure what i may have changed or done to cause this but any help would be appreciated.
http://geonode.gov.vc/layers/?limit=100&offset=0

**Comment by simod** [comment]
@shakyD can you please use the mailing lists to request for help? I'll close this ticket.
Taking a quick look, your site is calling geoserver on an internal ip 192.168... which is not reachable from outside so layers won't show. For the authentication issue may just be a misconfiguration.
