### ISSUE TITLE
Proper error message when failing to upload big files

### ISSUE THREAD

**Issue by cleder** [GeoNode/geonode#362]
when I try to upload big shapefiles i get the following error in the logs:
Note that this error is not propagated to the user interface, the UI
just displays
the upload form and gives no clue that an error occurred

Fri Aug 10 02:13:38 2012] [error]
csw._exml.findall('//'+nspath('Record', namespaces['csw']))]
[Fri Aug 10 08:45:47 2012] [error] [client 127.0.0.1](70007)The
timeout specified has expired: proxy: error reading status line from
remote server localhost:13512
[Fri Aug 10 08:45:47 2012] [error] [client 127.0.0.1] proxy: Error
reading from remote server returned by
/geoserver/rest/workspaces/geonode/datastores/postgres_imports/file.shp
[Fri Aug 10 03:47:38 2012] [error] Could not save the layer
World_EEZ_v6_1_20110512, there was an upload error: <!DOCTYPE HTML
PUBLIC "-//IETF//DTD HTML 2.0//EN">
[Fri Aug 10 03:47:38 2012] [error] <html><head>
[Fri Aug 10 03:47:38 2012] [error] <title>405 Method Not Allowed</title>
[Fri Aug 10 03:47:38 2012] [error] </head><body>
[Fri Aug 10 03:47:38 2012] [error] <h1>Method Not Allowed</h1>
[Fri Aug 10 03:47:38 2012] [error] <p>The requested method PUT is not
allowed for the URL /gateway-timeout.html.</p>
[Fri Aug 10 03:47:38 2012] [error] </body></html>
[Fri Aug 10 03:47:38 2012] [error]
[Fri Aug 10 03:47:38 2012] [error] Unexpected error during upload.
[Fri Aug 10 03:47:38 2012] [error] Traceback (most recent call last):
[Fri Aug 10 03:47:38 2012] [error]   File
"/home/iwlearn3/webapps/twap_geonode_django/src/GeoNodePy/geonode/maps/views.py",
line 880, in upload_layer
[Fri Aug 10 03:47:38 2012] [error]     permissions =
form.cleaned_data["permissions"]
[Fri Aug 10 03:47:38 2012] [error]   File
"/home/iwlearn3/webapps/twap_geonode_django/src/GeoNodePy/geonode/maps/utils.py",
line 281, in save
[Fri Aug 10 03:47:38 2012] [error]     store, gs_resource =
create_store_and_resource(name, data, overwrite=overwrite)
[Fri Aug 10 03:47:38 2012] [error]   File
"/home/iwlearn3/webapps/twap_geonode_django/src/GeoNodePy/geonode/maps/utils.py",
line 579, in _create_db_featurestore
[Fri Aug 10 03:47:38 2012] [error]     cat.add_data_to_store(ds, name,
data, overwrite, charset)
[Fri Aug 10 03:47:38 2012] [error]   File
"/home/iwlearn3/webapps/twap_geonode_django/src/gsconfig.py/src/geoserver/catalog.py",
line 236, in add_data_to_store
[Fri Aug 10 03:47:38 2012] [error]     raise UploadError(response)
[Fri Aug 10 03:47:38 2012] [error] UploadError: Could not save the
layer World_EEZ_v6_1_20110512, there was an upload error: <!DOCTYPE
HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
[Fri Aug 10 03:47:38 2012] [error] <html><head>
[Fri Aug 10 03:47:38 2012] [error] <title>405 Method Not Allowed</title>
[Fri Aug 10 03:47:38 2012] [error] </head><body>
[Fri Aug 10 03:47:38 2012] [error] <h1>Method Not Allowed</h1>
[Fri Aug 10 03:47:38 2012] [error] <p>The requested method PUT is not
allowed for the URL /gateway-timeout.html.</p>
[Fri Aug 10 03:47:38 2012] [error] </body></html>
[Fri Aug 10 03:47:38 2012] [error]

You should be able to reproduce this error by uploading a big shapefile

e.g the corals layer from http://www.iucnredlist.org/technical-documents/spatial-data

throug a 'slow' network connection (WIFI?)

**Comment by ingenieroariel** [comment]
Let's rename this ticket. If GeoNode does not handle well very big files, we should be returning a meaningful error to the user instead of 500 errors or  nothing.

**Comment by ingenieroariel** [comment]
We need to define an upper limit for big files and reject the ones above that limit with a notice asking to contact the site administrator.

**Comment by vdeparday** [comment]
I tried to upload the three shapefiles corals from here: http://www.iucnredlist.org/technical-documents/spatial-data

It took a long time locally but it worked.

It crashed GeoServer on demo.geonode.org but didn't give the error above.

**Comment by ischneider** [comment]
From my experience, these type of errors can be transient and based upon other factors (other users doing stuff).

**Comment by jj0hns0n** [comment]
This may be made irrelevant after switching to django-osgeo-importer.
