### ISSUE TITLE
2.8rc11 Layer uploader does not remove SLD correctly

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#3627]
Hi,

there seems to be a little bug in geonode 2.8rc11 (installed by apt). When a user uploads layer shp files together with some *.sld a warning appears that this file is not allowed for uploading. 

If the user removes the sld (by click on remove) and tries the upload again the warning still appears. You can see this behavior here: https://vimeo.com/256054628 (Until second 16).

**Comment by afabiani** [comment]
Should be fixed here https://github.com/GeoNode/geonode/pull/3646
