### ISSUE TITLE
Error with geonode 2.8 installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by StevePain** [GeoNode/geonode#3628]
I encountered this issue 3 times...  tried to repeat the installation again and again :D  

i prepared a fresh new ubuntu 16.04 machine and then i did: 
sudo add-apt-repository ppa:geonode/testing
sudo apt-get update && sudo apt-get upgrade
sudo apt install geonode
... at this point i encountered again errors while processing: /var/cache/apt/archives/python-pyyaml_3.12-1_amd64.deb.... Sub-process /user/bin/dpkg returned an error code (1)....

**Comment by jitendrashahiitb** [comment]
I have a repeated problem 
QAfter isnalling geonode 2.8rc11, on a fresh ubuntu installation of 16.04, and after creaeting superuser
when I give the following **command**
  **** sudo geonode-updateip 127.0.0.1****
( after restarting tomcat8 as suggested earlier by developer)

 **File "/usr/lib/python2.7/dist-packages/geoserver/catalog.py", line 216, in get_xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d status code: \n%s" % (rest_url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://localhost:8080/geoserver/rest/workspaces.xml but got a 404 status code:** 
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76; border: none;}</style> </head><body><h1>HTTP Status 404 - /geoserver/rest/workspaces.xml</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>message</b> <u>/geoserver/rest/workspaces.xml</u></p><p><b>description</b> <u>The requested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.32 (Ubuntu)</h3></body></html>

**Comment by jondoig** [comment]
Same here.

While investigating, I found an accidental workaround - not sure why it works:

1.	sudo apt-get install tomcat8-admin
2.	sudo vi /etc/tomcat8/tomcat-users.xml to add:

```
  <role rolename="tomcat"/>
  <role rolename="manager-gui"/>
  <user username="tomcat" password="tomcat" roles="tomcat,manager-gui"/>
```

3. sudo service tomcat8 restart

Geoserver now working.

@afabiani said:

> I guess a timeout on tomcat restart. Need to review the final bash script setting up the oauth2 credentials.

**Comment by jitendrashahiitb** [comment]
Is it advisable to use the workaround? Or should I wait till a fix is announced ? I can make do with stable version for now.

**Comment by afabiani** [comment]
Looking at this now. If not suitable solution will be found, let's keep workaround for the moment. Will let you now asap.

**Comment by afabiani** [comment]
I confirm that the workaround works. I will try to implement it into the geonode 2.8.0 deb

Thanks for that.

**Comment by adissadis** [comment]
Hello,

I'm still encounter this HTTP Status 404 - /geoserver/web on my Ubuntu 16.0 with Geonode 2.8 stable

When I running geonode-updateip i  still got this error:

geonode-updateip 103.82.242.45
Replacing SITEURL value with '103.82.242.45' in /etc/geonode/local_settings.py .                                                                                                                                                             .. done.
Adding entry for '103.82.242.45' in /usr/share/geoserver/data/printing/config.ya                                                                                                                                                             ml ... '103.82.242.45' already found to the printing whitelist.
Setting up oauth
/usr/sbin/geonode-updateip: line 154: restart: command not found
Waiting Tomcat Service to Restart...
Waiting Apache HTTPD Service to Restart...
Inspecting the available layers in GeoServer ...
GET http://localhost:8080/geoserver/rest/workspaces.xml
Traceback (most recent call last):
  File "/usr/bin/django-admin", line 9, in <module>
    load_entry_point('Django==1.8.19', 'console_scripts', 'django-admin')()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", li                                                                                                                                                             ne 354, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", li                                                                                                                                                             ne 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 3                                                                                                                                                             94, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 4                                                                                                                                                             45, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/management/comm                                                                                                                                                             ands/updatelayers.py", line 122, in handle
    execute_signals=True)
  File "/usr/local/lib/python2.7/dist-packages/geonode/geoserver/helpers.py", li                                                                                                                                                             ne 550, in gs_slurp
    resources = cat.get_resources()
  File "/usr/lib/python2.7/dist-packages/geoserver/catalog.py", line 860, in get                                                                                                                                                             _resources
    for ws in self.get_workspaces():
  File "/usr/lib/python2.7/dist-packages/geoserver/catalog.py", line 1011, in ge                                                                                                                                                             t_workspaces
    description = self.get_xml("%s/workspaces.xml" % self.service_url)
  File "/usr/lib/python2.7/dist-packages/geoserver/catalog.py", line 216, in get                                                                                                                                                             _xml
    raise FailedRequestError("Tried to make a GET request to %s but got a %d sta                                                                                                                                                             tus code: \n%s" % (rest_url, response.status, content))
geoserver.catalog.FailedRequestError: Tried to make a GET request to http://loca                                                                                                                                                             lhost:8080/geoserver/rest/workspaces.xml but got a 404 status code:
<!DOCTYPE html><html><head><title>Apache Tomcat/8.0.32 (Ubuntu) - Error report</                                                                                                                                                             title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white                                                                                                                                                             ;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-ser                                                                                                                                                             if;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,                                                                                                                                                             Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {fon                                                                                                                                                             t-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-fa                                                                                                                                                             mily:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-fami                                                                                                                                                             ly:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color                                                                                                                                                              : black;}A.name {color : black;}.line {height: 1px; background-color: #525D76;                                                                                                                                                              border: none;}</style> </head><body><h1>HTTP Status 404 - /geoserver/rest/worksp                                                                                                                                                             aces.xml</h1><div class="line"></div><p><b>type</b> Status report</p><p><b>messa                                                                                                                                                             ge</b> <u>/geoserver/rest/workspaces.xml</u></p><p><b>description</b> <u>The req                                                                                                                                                             uested resource is not available.</u></p><hr class="line"><h3>Apache Tomcat/8.0.                                                                                                                                                             32 (Ubuntu)</h3></body></html>



I already tried to use the workaround above and restart my tomcat8 and apache2 and also my server but still i cannot access my geoserver. But when i want to access geonode only, it already work fine (but still fail when trying to upload layer).

Any help I really appreciate that. Thank you..

**Comment by adissadis** [comment]
Here's catalina log output:

```
04-Apr-2018 17:15:31.026 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.034 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.036 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.038 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.039 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.040 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
04-Apr-2018 17:15:31.589 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32 (Ubuntu)
04-Apr-2018 17:15:31.591 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 27 2017 21:23:18 UTC
04-Apr-2018 17:15:31.592 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
04-Apr-2018 17:15:31.593 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
04-Apr-2018 17:15:31.594 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.4.0-116-generic
04-Apr-2018 17:15:31.594 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
04-Apr-2018 17:15:31.595 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-oracle/jre
04-Apr-2018 17:15:31.596 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_161-b12
04-Apr-2018 17:15:31.597 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
04-Apr-2018 17:15:31.598 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
04-Apr-2018 17:15:31.598 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
04-Apr-2018 17:15:31.599 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
04-Apr-2018 17:15:31.600 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
04-Apr-2018 17:15:31.601 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
04-Apr-2018 17:15:31.602 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms2048m
04-Apr-2018 17:15:31.602 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
04-Apr-2018 17:15:31.603 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelOldGC
04-Apr-2018 17:15:31.604 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
04-Apr-2018 17:15:31.604 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2
04-Apr-2018 17:15:31.605 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+AggressiveOpts
04-Apr-2018 17:15:31.606 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xrs
04-Apr-2018 17:15:31.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500
04-Apr-2018 17:15:31.607 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=128m
04-Apr-2018 17:15:31.608 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/share/tomcat8/endorsed
04-Apr-2018 17:15:31.609 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
04-Apr-2018 17:15:31.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
04-Apr-2018 17:15:31.610 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
04-Apr-2018 17:15:31.809 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
04-Apr-2018 17:15:31.833 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
04-Apr-2018 17:15:31.838 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 755 ms
04-Apr-2018 17:15:31.869 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
04-Apr-2018 17:15:31.870 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.32 (Ubuntu)
04-Apr-2018 17:15:31.888 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/geoserver.xml
04-Apr-2018 17:15:44.795 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
04-Apr-2018 17:15:45.991 WARNING [localhost-startStop-1] it.geosolutions.imageio.gdalframework.GDALUtilities.loadGDAL Failed to load the GDAL native libs. This is not a problem unless you need to use the GDAL plugins: they won't be enabled.
java.lang.UnsatisfiedLinkError: no gdaljni in java.library.path
04-Apr-2018 17:15:46.486 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
04-Apr-2018 17:15:46.487 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
04-Apr-2018 17:15:46.489 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
04-Apr-2018 17:15:46.490 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
04-Apr-2018 17:15:50.838 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'MonitorDAO', but ApplicationContext is unset.
04-Apr-2018 17:15:50.839 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
04-Apr-2018 17:15:50.840 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
04-Apr-2018 17:15:50.840 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
04-Apr-2018 17:15:51.069 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
04-Apr-2018 17:15:51.073 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
04-Apr-2018 17:15:51.073 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
04-Apr-2018 17:15:51.074 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
```

**Comment by afabiani** [comment]
uhm I don't see anything strange from this log.
Is http://localhost/geoserver (or http://localhost:8080/geoserver) reachable?

**Comment by afabiani** [comment]
also could you please try to run the following commands

```
sudo sed -i -e 's/xom-\*\.jar/xom-\*\.jar,bcprov\*\.jar/g' /var/lib/tomcat8/conf/catalina.properties
sudo service tomcat8 restart
geonode-updateip 103.82.242.45
```

**Comment by adissadis** [comment]
Hi, I restarted the server and using your step and now the geoserver run perfectly. Thank you for your help!

**Comment by davis18** [comment]
Hi all,

After installing Geonode stable 2.8 on ubuntu 16.04, I rebooted tomcat8 (sudo /etc/init.d/tomcat8 restart) and now http://localhost/geoserver( and  http://localhost:8080/geoserver) is not reachable.
I executed the suggested command: sudo sed -i -e 's/xom-\*\.jar/xom... and it did not work either.

Here's catalina log output:
`06-Apr-2018 16:36:10.894 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [fals$
06-Apr-2018 16:36:10.904 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canR$
06-Apr-2018 16:36:10.906 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [fals$
06-Apr-2018 16:36:10.910 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canR$
06-Apr-2018 16:36:10.913 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [fals$
06-Apr-2018 16:36:10.916 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canR$
06-Apr-2018 16:36:11.735 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32 (Ubuntu)
06-Apr-2018 16:36:11.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 27 2017 21:23:18 UTC
06-Apr-2018 16:36:11.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
06-Apr-2018 16:36:11.745 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
06-Apr-2018 16:36:11.746 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.13.0-1012-gcp
06-Apr-2018 16:36:11.750 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
06-Apr-2018 16:36:11.752 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
06-Apr-2018 16:36:11.754 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_162-8u162-b12-0ubuntu0.16.04.2-b12
06-Apr-2018 16:36:11.754 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
06-Apr-2018 16:36:11.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
06-Apr-2018 16:36:11.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
06-Apr-2018 16:36:11.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
06-Apr-2018 16:36:11.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
06-Apr-2018 16:36:11.763 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
06-Apr-2018 16:36:11.763 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms2048m
06-Apr-2018 16:36:11.763 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
06-Apr-2018 16:36:11.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelOldGC
06-Apr-2018 16:36:11.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
06-Apr-2018 16:36:11.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2
06-Apr-2018 16:36:11.769 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+AggressiveOpts
06-Apr-2018 16:36:11.774 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xrs
06-Apr-2018 16:36:11.775 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500
06-Apr-2018 16:36:11.776 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxPermSize=128m
06-Apr-2018 16:36:11.777 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/share/tomcat8/endorsed
06-Apr-2018 16:36:11.780 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
06-Apr-2018 16:36:11.785 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
06-Apr-2018 16:36:11.786 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
06-Apr-2018 16:36:12.006 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
06-Apr-2018 16:36:12.031 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
06-Apr-2018 16:36:12.049 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1092 ms
06-Apr-2018 16:36:12.105 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
06-Apr-2018 16:36:12.107 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.32 (Ubuntu)
06-Apr-2018 16:36:12.137 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /etc/tomcat8/Catalina/localhost/geoserver.xml
06-Apr-2018 16:36:26.092 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logg$
06-Apr-2018 16:36:27.915 WARNING [localhost-startStop-1] it.geosolutions.imageio.gdalframework.GDALUtilities.loadGDAL Failed to load the GDAL native libs. This is not a problem unless you need to$
java.lang.UnsatisfiedLinkError: no gdaljni in java.library.path
06-Apr-2018 16:36:28.567 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'XStreamPersisterInitializer', but ApplicationContext is unset.
06-Apr-2018 16:36:28.573 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
06-Apr-2018 16:36:28.576 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
06-Apr-2018 16:36:28.581 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
06-Apr-2018 16:36:35.744 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'MonitorDAO', but ApplicationContext is unset.
06-Apr-2018 16:36:35.756 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
06-Apr-2018 16:36:35.757 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
06-Apr-2018 16:36:35.758 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
06-Apr-2018 16:36:36.224 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'GeoServerSecurityProvider', but ApplicationContext is unset.
06-Apr-2018 16:36:36.229 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.
06-Apr-2018 16:36:36.230 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionProvider', but ApplicationContext is unset.
06-Apr-2018 16:36:36.231 WARNING [localhost-startStop-1] org.geoserver.platform.GeoServerExtensions.checkContext Extension lookup 'ExtensionFilter', but ApplicationContext is unset.`

Any help to start Geoserver, I really appreciate it. Thank you.

**Comment by afabiani** [comment]
First of all, if possible, try to get all the logs you can (catalina.out
and geoserver.log) and either attach those files here or cut and paste them
into something like https://bpaste.net/

I'll have a look at them

Regards,

Alessio Fabiani

==
GeoServer Professional Services from the experts! Visit http://goo.gl/it488V
for more information.
==

Ing. Alessio Fabiani

@alfa7691
Founder/Technical Lead


GeoSolutions S.A.S.
Via di Montramito 3/A
55054  Massarosa (LU)
Italy
phone: +39 0584 962313
fax:     +39 0584 1660272
mob:   +39 331 6233686

http://www.geo-solutions.it
http://twitter.com/geosolutions_it

-------------------------------------------------------

AVVERTENZE AI SENSI DEL D.Lgs. 196/2003

Le informazioni contenute in questo messaggio di posta elettronica e/o
nel/i file/s allegato/i sono da considerarsi strettamente riservate. Il
loro utilizzo è consentito esclusivamente al destinatario del messaggio,
per le finalità indicate nel messaggio stesso. Qualora riceviate questo
messaggio senza esserne il destinatario, Vi preghiamo cortesemente di
darcene notizia via e-mail e di procedere alla distruzione del messaggio
stesso, cancellandolo dal Vostro sistema. Conservare il messaggio stesso,
divulgarlo anche in parte, distribuirlo ad altri soggetti, copiarlo, od
utilizzarlo per finalità diverse, costituisce comportamento contrario ai
principi dettati dal D.Lgs. 196/2003.

The information in this message and/or attachments, is intended solely for
the attention and use of the named addressee(s) and may be confidential or
proprietary in nature or covered by the provisions of privacy act
(Legislative Decree June, 30 2003, no.196 - Italy's New Data Protection
Code).Any use not in accord with its purpose, any disclosure, reproduction,
copying, distribution, or either dissemination, either whole or partial, is
strictly forbidden except previous formal approval of the named
addressee(s). If you are not the intended recipient, please contact
immediately the sender by telephone, fax or e-mail and delete the
information in this message that has been received in error. The sender
does not give any warranty or accept liability as the content, accuracy or
completeness of sent messages and accepts no responsibility  for changes
made after they were sent or for other risks which arise as a result of
e-mail transmission, viruses, etc.

2018-04-06 18:58 GMT+02:00 davis18 <notifications@github.com>:

**Comment by afabiani** [comment]
Probably the best solution would be trying to cleanup the geoserver package and retry the installation of it.

I'll try to send instruction as soon as I can.

**Comment by davis18** [comment]
Hi,
Sorry for delaying to respond, I installed geonode 2.8 stable again with the following commands:
  sudo add-apt-repository ppa: geonode / stable
  sudo apt-get update
  sudo apt-get upgrade
  sudo apt-get install geonode
  sudo geonode-updateip ...
  sudo /etc/init.d/tomcat8 restart
The message of the geoserver is the following:

![geoserver](https://user-images.githubusercontent.com/7801173/38506277-fff8a8aa-3bde-11e8-92b7-30d5723a21bf.jpg)

The logs can be found in the following links:
catalina.out: 
https://bpaste.net/show/5c723f5f024c

catalina.2018-04-09.log: 
https://bpaste.net/show/d2d0734a7be6

localhost.2018-04-09.log: 
https://bpaste.net/show/1cd98a02e99f

localhost_access_log.2018-04-09.txt: 
https://bpaste.net/show/53c6edffe82d

Kind Regards

**Comment by afabiani** [comment]
@davis18 that's very strange... I cannot recognize any error from the logs you posted!

Question: is the following address reachable?

http://localhost:8080/geoserver

**Comment by davis18** [comment]
@afabiani I can't access to http://35.231.35.55:8080/geoserver

**Comment by davis18** [comment]
@afabiani I was able to enter to http://localhost/geoserver after 2 hours of waiting. The issus is that after restarting the tomcat8 it takes 2 hours to start the geoserver.

**Comment by lfeng1** [comment]
I also received this warning message as the first error seen in the catalina.out log file. 
`/var/lib/tomcat8/logs/catalina.out` as shown in the following link.

https://bpaste.net/show/890913cadc95

I followed this installation for geonode 2.8 on ubuntu 16.04 (http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/index.html)

**Comment by afabiani** [comment]
@davis18 two hours waiting are not normal behaviour. Most probably there are issues either with the network configuration or your machine resources. In order to avoid problems using GeoNode and GeoServer, you need at least a 2 Cores machine with 4Gb+ RAM available.

@lfeng1 warning messages are normal as soon as GeoServer runs correctly.

**Comment by lfeng1** [comment]
@afabiani Ok, but geoserver can't run correctly. 

Geoserver hangs on startup following `ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
`
catalina.out (/var/lib/tomcat8/logs/catalina.out) as shown in the following link.
https://bpaste.net/show/890913cadc95

**Comment by mnahmad** [comment]
Hi All 
I am facing a similar issue. I am porting geonode 2.4 to 2.8. I took GeoServer (version 2.7) data folder from geonode 2.4 server and copied it to the new server (with geonode2.8 and GeoServer 2.12.2), when I restart tomcat, geoserver does not start. Before copying the geoserver was working. 

In catalina.out file I can see an exception "GeoNodeAnonymousAuthFilterConfig" but have no idea why this exception is being raised
 
/var/log/tomcat8/catalina.out shown in the following link 

https://bpaste.net/show/be0b362314b7

Thanks

**Comment by t-book** [comment]
@mnahmad you have to update several things in your data directory. Scroll a bit down here http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_update/26_to_27/index.html to find more on this.
