### ISSUE TITLE
Required packages version ignored while installing geonode 2.6.3 with ansible

### ISSUE THREAD

**Issue by echondrok** [GeoNode/geonode#3637]
Hi

I don't know if this is the right place to open this issue but since i'm on a tight schedule...

Some months ago we've successfully deployed a GeoNode instance using Ansible.
While trying to do a migration to a new server, I've run the installation process again but came up with the following error.

```
TASK [GeoNode.geonode : Django makemigrations] *********************************
fatal: [35.229.67.15]: FAILED! => 
{
	"changed": false,
	"cmd": "./manage.py makemigrations --settings=thess_geonode.settings",
	"msg": ":stderr: Traceback (most recent call last):  File \"./manage.py\", line 11, in <module>
			execute_from_command_line(sys.argv)
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 354, in execute_from_command_line
			utility.execute()
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/django/core/management/__init__.py\", line 328, in execute
			django.setup()
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/django/__init__.py\", line 18, in setup
			apps.populate(settings.INSTALLED_APPS)
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/django/apps/registry.py\", line 85, in populate
			app_config = AppConfig.create(entry)
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/django/apps/config.py\", line 86, in create
			module = import_module(entry)
			File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module
			__import__(name)
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/polymorphic/__init__.py\", line 13, in <module>
			__version__ = pkg_resources.require(\"django-polymorphic\")[0].version
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 943, in require
			needed = self.resolve(parse_requirements(requirements))
			File \"/home/root/venvs/thess_geonode/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 834, in resolve
			raise VersionConflict(dist, req).with_context(dependent_req)\npkg_resources.ContextualVersionConflict: 
				(Django 1.8.18 (/home/root/venvs/thess_geonode/lib/python2.7/site-packages), 
				Requirement.parse('Django>=1.11'), set(['django-polymorphic']))\n",
	"path": "/home/root/venvs/thess_geonode/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games",
	"state": "absent",
	"syspath": [
		"/tmp/ansible_2mrOTk",
		"/tmp/ansible_2mrOTk/ansible_modlib.zip",
		"/tmp/ansible_2mrOTk/ansible_modlib.zip",
		"/usr/lib/python2.7",
		"/usr/lib/python2.7/plat-x86_64-linux-gnu",
		"/usr/lib/python2.7/lib-tk",
		"/usr/lib/python2.7/lib-old",
		"/usr/lib/python2.7/lib-dynload",
		"/usr/local/lib/python2.7/dist-packages",
		"/usr/lib/python2.7/dist-packages",
		"/usr/lib/python2.7/dist-packages/PILcompat"
	]
}
```

Apparently all the packages in the requirements.txt file of GeoNode 2.6.3 release are installed in the server but most of them have versions that don't match (recent versions are installed ex. Django 1.8.18 was installed instead of 1.8.7).

On the other hand, the packages specified in my template project requirements.txt has been installed with the correct version.

**Comment by DarnelleF** [comment]
same issue here ive been trying to install geonode 2.6 with their template and following instruction, i decided to stop following and install what i see is missing and ive reach the same place  where you are 


>>> a version conflict


and everything else is properly installed

**Comment by kalxas** [comment]
Thanks for the report, I will check the ansible installer but probably this is a pip requirements issue that need to be updated.

**Comment by DarnelleF** [comment]
yes the installation guide was missing a few pip requirements that i
installed.

but ive ran into a new issue where it has a validation error stating it
need Django 1.11

when i get back into the office ill email u the trace

**Comment by kalxas** [comment]
I also confirm this issue here:
```
from slugify.main import Slugify, UniqueSlugify\nImportError: No module named main
```

**Comment by kalxas** [comment]
I am currently working for a temporary patch for the ansible script until a 2.6.4 release is out.

**Comment by DarnelleF** [comment]
thank you for your assistance !

**Comment by kalxas** [comment]
Fix is provided here:
https://github.com/GeoNode/ansible-geonode/pull/44

**Comment by DarnelleF** [comment]
waiting for someone to approve not seeing a download link

**Comment by DarnelleF** [comment]
@kalxas sorry buddy but i just realized that this comment is for the ansible-geonode while ive done the development installation of geonode 16.04 Ubuntu and run into these errors
