### ISSUE TITLE
"Discover" section on homepage not responsive (and related problems)

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode#3643]
Hi,

The "discover" section on the homepage is not responsive anymore (see screenshots below).

I think this section has other problems :
- Empty categories should not be shown
- Farming, geoinformation, health icons style doesn't fit the general style (thin vs fat)
- Links shouldn't be hardcoded in the template. Those categories are standards, right, but some may want to override that category system anyway

Also I didn't double check but seemed to spot an issue in the hardcoded links (duplicated category__identifier__in url parameter for some links).

![before](https://user-images.githubusercontent.com/1894106/36459374-0eb0cb50-1710-11e8-8a4f-5499a68c4cec.PNG)
![after](https://user-images.githubusercontent.com/1894106/36459377-109a641c-1710-11e8-8f2b-d778e98e1a27.PNG)

**Comment by afabiani** [comment]
@olivierdalang thanks for testing this. I'll try to take a look asap.

The icons have been aligned to other projects. They can still be changed from django admin if you need. It basically makes use of fontawesome icons.

To update them just change the fa-class on "topic categories"
