### ISSUE TITLE
django 1.11 LTS support on master

### ISSUE THREAD

**Issue by auvipy** [GeoNode/geonode#3661]
If no veto I want to start working on it

**Comment by afabiani** [comment]
@auvipy you are very welcome.

Please start working from DJANGO_111 branch.

Some notes here below:

There are some non-trivial incompatibilities with Django 1.11

At this time we don't have found yet suitable solutions to fix those ones.

Some experimentation ongoing on this branch

https://github.com/GeoNode/geonode/tree/DJANGO_111

Major issues currently identified are:

1. Fixtures passwords (also on tests) are no more valid on Django 1.11; users cannot login with old password hashes.

2. Templates and form widgets are come incompatibilities and details pages other than metadata editor ones, rise errors on rendering.

**Comment by auvipy** [comment]
thanks for response. I will look into the issues
