### ISSUE TITLE
GNIP: Improvements to GeoNode Layers download links

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3662]
### Proposed by
Alessio Fabiani (http://www.geo-solutions.it/)

### Assigned to release
None yet.

# Improvements to GeoNode Layers download links

## 1. Background
Geonode currently creates a set of static links in order to allow people to download Layers data in several output formats.

In particular for vector data, GeoNode exposes several WFS links like shown here below:

![image](https://user-images.githubusercontent.com/1278021/37275219-e06afc24-25de-11e8-85b6-1ecef4f4cd53.png)

While for raster data, GeoNose exposes several WCS links like shown here:

![image](https://user-images.githubusercontent.com/1278021/37275330-28b7d632-25df-11e8-9112-6d1d50ccd94b.png)

Currently this approach is not always optimal, for several reasons:

1. OAuth2 tokens are hard-coded on the DB and therefore allowing to download actually only public layers

3. Bboxes are computed with an heuristic method by considering original data always projected at EPSG:4326 (WGS-84) geodesic CRS, thus forcing GeoServer to always reproject it on the fly

2. Using WCS to download the whole raster dataset, may cause severe issues. First of all WCS is not able to return the raw data with its original internal structure. In simpler words, if the original file has a specific, optimized, internal structure (internal compression, internal tiling, internal overviews,...) this is not preserved by WCS without post-processing. The output file from WCS may result in a very huge, uncompressed and non-optimized outcome.

3. Downloads are all synchronous.

## 2. Proposal

Within current GNIP, we are not going to solve all the issues listed above, but start some refactoring of the way on how GeoNode presents them and creates them.

This work aims to be a base for future improvements, moving towards a real post-processed / asynchronous download system (to be discussed as part of the future GeoNode 3.0 architecture).

### Remove hard-coded stuff from DB

Making sure GeoNode does not store access tokens or other kind of hardcoded info on the DB. Enrich links on page rendering instead with missing info.

### Taking into account (when possible) native projection of Layer

Allow people to download data on its native projection (if available on GeoNode DB).

### Add links to download original raster files instead of WCS ones

Expose WCS links *only* to subset / transform data into other output formats, and expose to people links to stream the original uploaded file instead (when / if available).

## 3. Future work

- Allow users to pre-process data while uploading and keeping information on data internal structure.

- Moving towards a real post-processed / asynchronous download system (to be discussed as part of the future GeoNode 3.0 architecture).

- Allow GeoNode to prepare download and send perma-links via e-mail / rss / whatever to users when ready.

- Allow users to follow the download process requests and cancel them / re-try them if needed.

- Allow users to add data to a chart to be download in a later phase all together.

- Allow GeoNode to include Styles also within downloads.

**Comment by rob-metalinkage** [comment]
Can you please make sure the available methods are exposed in a form of machine-readable metadata so it can be integrated into other applications, who may wish to select specific types of links.  Something like OAS (used to be Swagger) would give a nice self-documenting form.

**Comment by francbartoli** [comment]
+1

**Comment by afabiani** [comment]
I'm preparing a PR for this GNIP.

The outcome will be a download link allowing you to get zipped file containing:

![image](https://user-images.githubusercontent.com/1278021/39199399-a5f696fc-47e9-11e8-94cf-4b7ed776ae2b.png)

1. Original uploaded files (along with SLDs and XMLs)

![image](https://user-images.githubusercontent.com/1278021/39199422-b693104e-47e9-11e8-9077-f6eddcad1ae0.png)

2. ".metadata" folder containing metadata formats, rendered images, OWS links, thumbnails and legends

![image](https://user-images.githubusercontent.com/1278021/39199465-cc41bb8e-47e9-11e8-91d5-b30af9c7c702.png)


The metadata will show the links among the other available download links

![image](https://user-images.githubusercontent.com/1278021/39199320-75bd5a16-47e9-11e8-93d7-7a8d79180b65.png)

**Comment by frafra** [comment]
Would it be possible to trigger the creation of the original dataset option in a migration, so users updating from <2.10 could get that feature?

**Comment by afabiani** [comment]
@frafra yes, good idea.

**Comment by afabiani** [comment]
@frafra https://github.com/GeoNode/geonode/pull/4340

**Comment by capooti** [comment]
@afabiani quick question: was the raster part mentioned in this GNIP implemented? (original file downloaded vs using WCS)
Thanks!

**Comment by d3netxer** [comment]
As part of the 'Original Dataset' is the uploaded file still being imported into the PostGIS database and accessed from PostGIS during download?

**Comment by giohappy** [comment]
@d3netxer if you refer to GeoNode 3 no, the original dataset refers to the original uploaded files. If available they will be downloaded.
GeoNode never refers directly to data stored inside PostGIS. This is Geoserver responsibility only. Data imported to PostGIS can be downloaded through the Export function (which uses WPS).
