### ISSUE TITLE
Docker compose failing on dj-pagination

### ISSUE THREAD

**Issue by rduivenvoorde** [GeoNode/geonode#3678]
Trying the Docker compose instructions. 

I get the following error:

```

Requirement already satisfied: dj-database-url==0.4.2 in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 22))
Collecting dj-pagination==2.3.2 (from -r requirements.txt (line 23))
  Downloading dj-pagination-2.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    error in dj-pagination setup command: Invalid environment marker: python_version < "3.0"
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-K3OnAO/dj-pagination/
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Service 'django' failed to build: The command '/bin/sh -c pip install --no-cache-dir -r requirements.txt' returned a non-zero code: 1

```

Some googling tells me that setuptools is an old version (in the image?)

**Comment by Gustry** [comment]
Same error with me while I was doing the `docker-compose up --build`

**Comment by cezio** [comment]
This is probably due base docker image uses older pip baked in, and when used in deployment, it triggers use of new requirements.txt file, which contains dj-pagination, which requires fresh pip. Images on hub should be refreshed.

**Comment by FriedrichMueller** [comment]
+1

**Comment by francbartoli** [comment]
@FriedrichMueller you are right definitively required to add a bit more details on configuring .env files. I’ll do as soon as I have spare time. Meanwhile if you want to start a PR is more than welcome. Thanks
