### ISSUE TITLE
Some fields are not translated in Layer and Map Metadata

### ISSUE THREAD

**Issue by ghassen98** [GeoNode/geonode#3681]
On version 2.4 and 2.6, some text fields cannot be translated (they are always in English) in some pages : Layer metadata and Map metadata,
These fields are : 
-	Owner
-	Temporel extent start
-	Temporel extent end
-	Thumbnail url
-	Keywords
-	Point of contact
-	Metadata Author

![1](https://user-images.githubusercontent.com/6956025/37937317-6d46a78a-3159-11e8-94b7-fcf07e9489b6.png)

![2](https://user-images.githubusercontent.com/6956025/37937329-755ae292-3159-11e8-9668-8961394bcc97.png)

![3](https://user-images.githubusercontent.com/6956025/37937333-7809409c-3159-11e8-88c6-3db5998b2623.png)

**Comment by afabiani** [comment]
This has been fixed on version 2.8 of GeoNode. You should consider to upgrade GeoNode version.

**Comment by ghassen98** [comment]
Thanks for your answer but i have a geonode server in production and i can't upgrade it now..
So i have to correct it by myself.
Could you please tell me how to correct this issue or provide me a link
Thanks in advance

**Comment by ghassen98** [comment]
Hello, 
I've installed the 2.8 version in a test server and this has not been fixed..
Someone have an idea how to fix this ?

![1_bis](https://user-images.githubusercontent.com/6956025/38630054-1840653c-3db6-11e8-8d5e-eed266f74908.png)

![2_bis](https://user-images.githubusercontent.com/6956025/38630073-22bc3c0c-3db6-11e8-9df6-0eac3ba13ffa.png)

![3_bis](https://user-images.githubusercontent.com/6956025/38630078-28da9f48-3db6-11e8-947c-6b2e0dd14cd0.png)

![4_bis](https://user-images.githubusercontent.com/6956025/38630085-2bfb10f4-3db6-11e8-9072-3f11c0f8e26c.png)

**Comment by t-book** [comment]
@ghassen98 you can update the po file for your needs and compile it as explained in the [Django docs](https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#localization-how-to-create-language-files). As this thread is a little older, if you need more help ping me otherwise could you close this issue?

**Comment by t-book** [comment]
@ghassen98 Sorry for not coming back on this earlier you might have a look at explanations from Alessio: https://github.com/GeoNode/geonode/issues/3203 

If strings are missing you might need to run:
`python manage.py makemessages -l fr`

**Comment by ghassen98** [comment]
@t-book i followed Alessio's explanations but seems that some fields are hard coded in english.. Hope this issue will be solved in nexts versions

**Comment by t-book** [comment]
@ghassen98 have a look here: https://github.com/GeoNode/geonode/pull/4372
it might be already fixed.

**Comment by t-book** [comment]
Closing here. @ghassen98 please reopen if you think this need´s more clarifications.
