### ISSUE TITLE
Geonode Maps Thumbnail

### ISSUE THREAD

**Issue by juliermegeotube** [GeoNode/geonode#3692]
Hi all,

I am runnig Geonode 2.6.3 and Geoserver 2.12.2 behind it in a Oracle Linux server. Geonode is unable to create the maps thumbnails. Opening the thumbnail in the browser I get the following message:
"The image "http://172.21.5.187/uploaded/thumbs/map-61021722-328d-11e8-8f82-0021f6a0db8e-thumb.png" cannot be displayed because it contains errors. 

I also got the image additional information:

Name: map-957c9af6-3290-11e8-875c-0021f6a0db8e-thumb.png
Dimensions: 0 × 0
MIME Type: image/png

Any help on this issue will be very appreciated. 

Thank you for your time in advance

Best Regards

**Comment by olivierdalang** [comment]
Same issue here on 2.6.3.
This should be fixed by https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/utils/thumbnail.js#L36-L39 (which is in 2.8 since https://github.com/GeoNode/geonode/commit/c5d7ea5bcd803186fec165fdc8e67989698736cf )

**Comment by juliermegeotube** [comment]
Dear Olivierdalang

Thank you very much for your reply. I have updated thumbnail.js file and I
will check the next responses.

Kind regards

I appreciated your time

Julierme



2018-04-03 22:50 GMT-03:00 olivierdalang <notifications@github.com>:
