### ISSUE TITLE
Error on change layer style 

### ISSUE THREAD

**Issue by oggioniale** [GeoNode/geonode#3697]
Here the screenshot of error:
![screen shot 2018-03-30 at 16 56 41](https://user-images.githubusercontent.com/1393893/38142165-a4b367aa-343b-11e8-86eb-ecef4d7b24cd.png)

**Comment by oggioniale** [comment]
sorry on Geonode 2.7.x

**Comment by davis18** [comment]
Hello, this error also happens in the new version Geonode 2.8

**Comment by afabiani** [comment]
Probably it depends on a issue preventing GeoServer to create a new custom style for the layer.

To do a quick test, instead of updating the rules of the current style, try to create a new one first (from the sld editor widget always). You should then be able to modify the new style.

If this is the case, we have already a fix for that.

**Comment by davis18** [comment]
I do the test, it does not allow to create a new style, neither modify it. The error message is "There was an error saving the style back to the server."

**Comment by americavotesdata** [comment]
I'm hitting this issue too, and I installed geonode via apt-get.

**Comment by capooti** [comment]
I can't replicate this. Which version of GeoServer are you using? In my case I have 2.12.2 and I can successfully create the style.

You can check this information on the GeoServer admin home page

<img width="1063" alt="screenshot 2018-05-09 15 24 12" src="https://user-images.githubusercontent.com/148380/39835114-18a7d346-539d-11e8-8110-e3f087c73de3.png">

**Comment by americavotesdata** [comment]
I'm using GeoServer 2.12-SNAPSHOT.

**Comment by wlorenzetti** [comment]
I'm using Geonode 2.7.5, news about this issue? Investigating about it, geonode.geoserver module try to make call on GeoServer as anonymos user...

**Comment by stochastics-1** [comment]
I have the same problem. It worked fine but suddenly I couldn't log into the GeoServer by pressing the Geonode icon. I tried deleting all the maps, styles and attributes via Django, but adding new layers from scratch causes the same problem

**Comment by t-book** [comment]
Tested just now by full manual setup and master branch which is working. 
Issue might be a duplicate / connected to https://github.com/GeoNode/geonode/issues/3861
Please check your rest.properties.
