### ISSUE TITLE
Map detail page wrong zoom

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3700]
When going to Map Detail page using default GeoNode GIS client (based on gxp), the zoom is wrong.

It works instead from the Map Composer.

**Comment by afabiani** [comment]
See commit 6e112d5a9536322bf2a6bfefe143c6ff4db34eec on https://github.com/geosolutions-it/geonode/commits/master

**Comment by davis18** [comment]
This also happens in the detail of the layer, it is not doing the map.zoomToExtent.
