### ISSUE TITLE
[Docker] docker-compose doesn't work on Docker for Windows

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode#3709]
Hi !

On Windows, `docker-compose up --build -d` doesn't work because of following errors:

```
ERROR: for 5c026c2ef83c_django4geonode  Cannot create container for service django: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: for geoserver  Cannot create container for service geoserver: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: for consumers  Cannot create container for service consumers: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: for celery  Cannot create container for service celery: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: for django  Cannot create container for service django: b'Mount denied:\nThe source path "\\\\var\\\\run\\\\docker.sock:/var/run/docker.sock"\nis not a valid Windows path'
ERROR: Encountered errors while bringing up the project.
```

It's not really clear why you need to mount the docker socket though, which should only be needed by containers needing to access the docker daemon. It would be nice if we could avoid it, as it doesn't seem to be supported on Windows.

I tried commenting out all occurrences of `- /var/run/docker.sock:/var/run/docker.sock` in the docker-compose, the all container start, but they crash because. So it seems the docker socket is needed somewhere.

Content of `docker logs django4geonode` (which /var/run/docker.sock comment out) :
```
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 11, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 293, in run
    self.execute()
  File "/usr/local/lib/python2.7/site-packages/invoke/program.py", line 414, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python2.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python2.7/site-packages/invoke/tasks.py", line 115, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/src/app/tasks.py", line 23, in update
    pub_ip = _geonode_public_host_ip()
  File "/usr/src/app/tasks.py", line 142, in _geonode_public_host_ip
    gn_pub_hostip = _docker_host_ip()
  File "/usr/src/app/tasks.py", line 81, in _docker_host_ip
    network_mode='host'
  File "/usr/local/lib/python2.7/site-packages/docker/models/containers.py", line 756, in run
    detach=detach, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/models/containers.py", line 814, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/container.py", line 404, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/site-packages/docker/api/container.py", line 414, in create_container_from_config
    res = self._post_json(u, data=config, params=params)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 253, in _post_json
    return self._post(url, data=json.dumps(data2), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 190, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))
```

**Comment by francbartoli** [comment]
@olivierdalang I cannot believe it is not supported maybe the path is different? Anyway the socket is required to discover automatically the IP where it is supposed  to run and configure django settings, fixtures and geoserver automagically. This allows also to support both Docker native and docker-machine based environment.
By the way I'm assuming you are using a Docker for Windows version so with the native one. Can you confirm? In such a case can we amend the title with "Docker for Windows" instead of windows?

**Comment by francbartoli** [comment]
@cezio thanks for the explanation, do we have any option to make it working with the current scripts structure if we want to support it?

**Comment by cezio** [comment]
We can provide sibling or auxiliary docker-compose dedicated for Windows platform (https://docs.docker.com/compose/extends/#understanding-multiple-compose-files)

**Comment by olivierdalang** [comment]
I didn't look at the scripts, but I doubt it's possible to fix the problem just by changing the docker-compose.

I think the scripts should be fixed to use 127.0.0.1 as default host if they can't access the docker socket (and probably having a way to manually set the host would be nice too).

**Comment by francbartoli** [comment]
@olivierdalang the possibility to set it manually already exists with these env variables:

GEONODE_LB_HOST_IP=127.0.0.1
GEONODE_LB_PORT=80

**Comment by giohappy** [comment]
@stevensotelo no windows docker-compose file exists. As already mentioned by @cezio we could provide an override for Windows where mounting of docker socket is removed.

PS: the socket is only used to let geoserver and geonode containers to run che-ip container to obtain the host IP. I already discussed with @francbartoli the idea to include the che-ip script and get rid of this dependency.
The script function that's being used by geonode's containers is the following: https://github.com/eclipse/che/blob/master/dockerfiles/ip/src/library.sh#L143

**Comment by francbartoli** [comment]
@giohappy also all the logic actually controlled by the python docker library should be replaced which means the docker sdk has to disappear at all. That said in the long term I would keep it because it could be very useful in order to achieve all the logic for the management of a geoserver cluster imho.
To overcome the current issue on windows I would implement a windows docker-compose which doesn't mount the unix socket and improve the logic for connecting to the client through the sdk. Something like a different connection, for instance tcp://127.0.0.1:2375.
What do you guys think?

**Comment by giohappy** [comment]
@francbartoli what is the python docker lib (and consequently the unix socket) used for beyond che-ip? I 
Using tcp sockets opens to security issues. It can be ok for local dev and tests but in general it would require setting up net rules to harden the tcp connection...

**Comment by francbartoli** [comment]
It is used also for the port of nginx [here](https://github.com/GeoNode/geonode/blob/master/tasks.py#L109).
It is useful in the case of multiple instances of the geonode stack running on the same docker daemon with different exposed ports of nginx, obviously without any sort of override by the GEONODE_LB_* env variables

**Comment by giohappy** [comment]
I don't want to stress on this bur imho we should find a different
approach.

I don't think it should be a concern of the container trying to guess the
ip and port on the base of the internal data structures from Docker
inspect.
Here at GeoSolutions are considering the adoption of Consul (and
ContainerPilot) to orchestrate the configuration of a stack of services
like it is geonode.
The docker ip and port can be published (and queried) through similar
services, in a clean a easier to mantain way.

The same (black magic) logic is repeated both inside the geonode and the
geoserver containers. IMHO this violates DRY.

If we wouldn't need doing thiese tricks we could get rid of che-ip and
mounting docker sockets, and things would run fine on Windows too.

my2cents,
Giovanni

The same logic is in the django and geoserver container

Il mer 11 lug 2018, 19:45 Francesco Bartoli <notifications@github.com> ha
scritto:

**Comment by francbartoli** [comment]
@giohappy I don't know consul and containerPilot but they seem to be an elegant and proficient way. Have you planned to make a PR for the removal of docker sdk lib?

**Comment by giohappy** [comment]
@francbartoli I did some experiments with the extension mechanism in docker compose, but I stopped when I've discovered that it's [not available anymore](https://docs.docker.com/compose/extends/#extending-services) since version 3.

Then I considered using overrides, but I have to verify if it works because the way 'image' and 'build' are treated with overrides is also changed since version 3. The latter override doesn't have precedence since in v. 3 both properties can cohexist and triggers [a different mechanism](https://docs.docker.com/compose/extends/#adding-and-overriding-configuration)

**Comment by giohappy** [comment]
After a call with @francbartoli the proposal is the following:

 - remove volume for the docker socker from docker.compose.yml
 - pass the volume as an arg within the the "up" target of the Makefile:
    `docker-compose up -v /var/run/docker.sock:/var/run/docker.sock -d`
 - add a new "upw" target for Windows where the volume arg is removed
    `docker-compose up -d`

Update the places where the docker daemon is used adopting a fallback appraoch:

### geonode-docker/tasks.py
- test the availability of the docker daemon:
```
    docker_available = False
    try:
        client = docker.from_env(version='1.24')
        client.version()
        docker_available = True
    except:
        pass
```
- fallbacks:
     - in case GEONODE_LB_HOST_IP is not set and `not docker_available`  fallback to localhost
     - in case GEONODE_LB_PORT is not set and `not docker_available`  fallback to 80

### geoserver-docker/entrypoint.sh
- test the availability of the docker daemon:
```
    docker_available = false
    if [ -S '/var/run/docker' ]
    then
       docker_available = true
    fi
```
- fallbacks:
     - in case GEONODE_LB_HOST_IP is not set and `not docker_available` fallback to localhost
     - in case GEONODE_LB_PORT is not set and `not docker_available` fallback to 80
     - in case NGINX_BASE_URL is not set and `not docker_available` fallback to  "http://nginx:80"

**Comment by giohappy** [comment]
Probably we don't need at all :)
Docker on Hyper-V can mount the docker socket indeed. In fact the docker host is a linux machine (MobyLinuxVM) running onto the Hyper-V which uses unix sockets as on other platforms.
I was able to confirm it running the following:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker ubuntu bash
```

I could verify that the socket was there and was working correctly (calling docker engine APIs from Python)

The real problem of this ticket is [a regression in Docker Compose](https://github.com/docker/for-win/issues/1829#issuecomment-376928286).

A temporary solution (that I have to verify yet) consists in setting and env var that guides docker compose to use linux paths rather then windows's:

```
export COMPOSE_CONVERT_WINDOWS_PATHS=1
docker-compose down && docker-compose up -d
```

I'll give you feedback as soon as I've tried...

**Comment by olivierdalang** [comment]
Also, the doc mentions

> GeoNode will be available at the ip address of the docker0 interface `ifconfig -a`

This is not true under Windows. When trying to access through the docker0 interface (which you'd find using `ipconfig`), you get a Django `DisallowedHost` exception.

`localhost` works, as `allowed_host` contains `['localhost', 'django', 'geonode']`.

I would suggest removing all that magic IP guessing stuff to have a robust cross platform setup.

We can just have `localhost`, and `127.0.0.1` by default in allowed host, and it works straight out of the box, on any system, for quick testing purpose.

Then, when you want to expose to other computers on the LAN or WAN, you anyway need to manually define the host name (either to your IP of domain name). For this, we'd have to document the `GEONODE_LB_HOST_IP` setting (which by the way should be renamed `GEONODE_LB_HOST`, as it's not necessarily an IP).

(I can't reopen the issue due to not having perms for the repo yet, if anyone could do it for me, that would be nice)

**Comment by francbartoli** [comment]
> This is not true under Windows. When trying to access through the docker0 interface (which you'd find using ipconfig), you get a Django DisallowedHost exception.
> 
I don't know how in this particular case the ip of docker0 is not captured and thus inserted into allowed_host which happens for sure in case of linux. Maybe @giohappy can test and see the real reason
> localhost works, as allowed_host contains ['localhost', 'django', 'geonode'].
> 
> I would suggest removing all that magic IP guessing stuff to have a robust cross platform setup.
>
We can certainly do this but as long as we can come up with a "more robust" solution that works 100% in any kind of deployment. This means to still support cloud providers with their docker-machine cases and docker native with or without a reverse proxy. The latter can be easily tested with a management infrastructure like Rancher on top of a couple of AWS nodes where their security groups have internal and external IP/hostname 
> We can just have localhost, and 127.0.0.1 by default in allowed host, and it works straight out of the box, on any system, for quick testing purpose.

Sorry I can't understand it, what is the price here? Ease testing over real production scenarios which for sure would break in case of removing the magic ip stuff for leaving just localhost

> For this, we'd have to document the GEONODE_LB_HOST_IP setting (which by the way should be renamed GEONODE_LB_HOST, as it's not necessarily an IP).

What about to change to GEONODE_LB_HOSTNAME and state in the docs, keeping out of possibilities to misunderstand, that a valid hostname is an IP address or a FQDN? So we'd still end up with the couple:

```env
GEONODE_LB_HOSTNAME
GEONODE_LB_PORT
```
which does make sense to me.

> (I can't reopen the issue due to not having perms for the repo yet, if anyone could do it for me, that would be nice)

Anyway I would open a different issue for the problem about allowed_host is still not working on windows.

**Comment by afabiani** [comment]
@francbartoli sorry, just noticed your comments. Should we keep this closed and open a new issue?

If so, please proceed as you find more appropriate.

**Comment by francbartoli** [comment]
@afabiani done [https://github.com/GeoNode/geonode/issues/3883](https://github.com/GeoNode/geonode/issues/3883)

I would ask @olivierdalang to double check and maybe improve the description if it is worth
