### ISSUE TITLE
KML Upload fails in 2.8

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#3710]
Hi, 

on a fresh Ubuntu 16.04 / geonode 2.8 installed from apt I´ve enabled geonode.importer to upload kml files in local_settings: 

```
DEFAULT_MAP_CRS = "EPSG:3857"
DEFAULT_LAYER_FORMAT = "image/png8"

UPLOADER = {
    'BACKEND': 'geonode.importer',
    'OPTIONS': {
        'TIME_ENABLED': False,
        'MOSAIC_ENABLED': False,
        'GEOGIG_ENABLED': False,
    },
    'SUPPORTED_CRS': [
        'EPSG:4326',
        'EPSG:3785',
        'EPSG:3857',
        'EPSG:900913',
        'EPSG:32647',
        'EPSG:32736'
    ],
    'SUPPORTED_EXT': [
        '.shp',
        '.csv',
        '.kml',
        '.kmz',
        '.json',
        '.geojson',
        '.tif',
        '.tiff',
        '.geotiff',
        '.gml',
        '.xml'
    ]
}
```
restarted apache and tomcat and tried to upload a simple kml: https://raw.githubusercontent.com/googlemaps/kml-samples/gh-pages/kml/Polygon/tennis-poly.kml
which ended in 

`Unexpected exception Please upload only one type of file at a time`

Geoserver verbose logging stays empty but apache error.log shows_

`/var/log/apache2/error.log:[Wed Apr 04 03:12:37.197229 2018] [wsgi:error] [pid 2529:tid 140025662039808] Uploading layer: testfile, files [<SpatialFile base_file=/tmp/tmpUnZ64s/testfile.kml file_type=<FileType kml> aux=[] sld=[] xml=[]>, <SpatialFile base_file=/tmp/tmpUnZ64s/testfile.kml file_type=<FileType kml-overlay> aux=[] sld=[] xml=[]>]`

SHP upload works fine.
Is this a bug or missconfigruation?

**Comment by JonDHo** [comment]
same behaviour happening for me on 2.8.0 for kml upload.

csv upload got closer but still failed.

**Comment by killertonez** [comment]
I am having the same issue

**Comment by ewsterrenburg** [comment]
also having issues with non-shape/tif kind of files (tried kml, csv, gml). Might look into this, but have some other issues that need solving first.
