### ISSUE TITLE
How to clean uninstall geonode

### ISSUE THREAD

**Issue by shakyD** [GeoNode/geonode#3742]
I've been having different issues and wish to uninstall geonode and everything with it and start from scratch. I've been trying the command sudo apt-get autoremove /purge/remove geonode and all return with an erro "Sub-process /usr/bin/dpkg returned an error code(100).

Any help to completely remove everything would be useful.

**Comment by t-book** [comment]
Can you check permissions? 
ls -l /usr/bin/dpkg

**Comment by shakyD** [comment]
i deleted the dpkg file before using 
sudo rm -f dpkg
but the error still seems to come up.
So when i tried sudo -l /usr/bin/dpkg is said command not found

**Comment by t-book** [comment]
Why did you delete it?

**Comment by shakyD** [comment]
Because of the "Sub-process /usr/bin/dpkg returned an error code(100)" error I thought if I deleted it, it would go away. As I wanted to clean everything off dealing with geonode I did not think it would cause any harm.

**Comment by t-book** [comment]
Mhh. I think you´ve gone to far. I would suggest
a) 
if it´s a VM for testing throw it away and start with a new
if not 
b) 
- try to fix apt
- uninstall apache and tomcat
- Ubuntu, right? have a look at /usr/local/lib/python2.7/dist-packages there you should find geonode
- have a look at /var/www you´ll find geonode public stuff there
- in case you want to keep apache have a look at /etc/apache2/sites-available/geonode.conf it´s the host file
- further find pip packages and there corresponding ppa packages here: 
https://github.com/GeoNode/geonode/blob/e6e1aa7a0c2a7cd881b09e3ed129a1004add38a3/requirements.txt
https://github.com/GeoNode/geonode/blob/e6e1aa7a0c2a7cd881b09e3ed129a1004add38a3/setup.py#L52
- remove /etc/geonode
- surely I have forgotten things which you might find looking at pre and postinstall steps ...

Writing this I really think you should start with a) fresh environment. Sorry.

**Comment by shakyD** [comment]
Ok thanks alot for your advice would be trying it, I wished it was as easy as part (a) lol.
Thanks again.

**Comment by t-book** [comment]
You´re welcome + good luck (◍•﹏•)

**Comment by t-book** [comment]
@shakyD or Admin? - can we close this?
