### ISSUE TITLE
GeoNode 2.8 stable -Seeding in GeoWebCache is not working stable

### ISSUE THREAD

**Issue by aboljevic** [GeoNode/geonode#3748]
Hi all,

We have been testing Geonode 2.8 stable (Ubuntu 16.04, stable ppa repository) for last few days.

Seeding in GeoWebCache is not working stable - mostly it does nothing with error (details are in [gwc_seeding_error.txt](https://github.com/GeoNode/geonode/files/1898198/gwc_seeding_error.txt) ):
org.geoserver.platform.ServiceException: Could not find layer geonode:examples
ERROR [org.geowebcache.seed.MTSeeder] - Problem communicating with GeoServer
Also:
http://osgeo-org.1560.x6.nabble.com/GWC-seeding-doesn-t-work-in-fresh-Geonode-2-8-stable-td5360457.html 

Best regards,
Ana

**Comment by afabiani** [comment]
That should be fixed with latest GeoServer WARs.

Feel free to re-open if the issue persists.
