### ISSUE TITLE
Geonode 2.8 stable: Upload data - with importer back-end kml/shapefiles/geojson not working

### ISSUE THREAD

**Issue by aboljevic** [GeoNode/geonode#3749]
Hi all,

We have been testing Geonode 2.8 stable (Ubuntu 16.04, stable ppa repository) for last few days.

Upload data - with importer back-end kml/shapefiles/geojson uplaod doesn't work ( ![importer_geojson_upload_error](https://user-images.githubusercontent.com/38278289/38607325-a3b9cec0-3d78-11e8-83ae-3f3771e635e0.JPG) ), also please look at:
http://osgeo-org.1560.x6.nabble.com/geonode-importer-doesn-t-work-in-Geonode-2-8-td5360287.html

Regards,
Ana

**Comment by killertonez** [comment]
has this been fixed? I noticed they closed the previous comment
