### ISSUE TITLE
Quick install Ubuntu (dev) says it was tested on Ubuntu 14

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3761]
On this page under **Ubuntu (for development)**
<http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html#ubuntu-for-development>  

it says:  
> This option installs geonode in a virtual environment. This option is very useful in case you want to develop using Ubuntu (tested on Ubuntu 14.04 LTS):

*Surely that should be 16 now?*

**Comment by t-book** [comment]
fixed:
https://github.com/GeoNode/geonode/commit/9a10a8df36558745e9a757a5461f370bd82596e3
can you close this issue @jondoig ?
