### ISSUE TITLE
Hard-coded urls to static-files and media-files

### ISSUE THREAD

**Issue by ewsterrenburg** [GeoNode/geonode#3775]
Related to [https://github.com/GeoNode/geonode/issues/3738](https://github.com/GeoNode/geonode/issues/3738):

GeoNode contains hard-coded files to **/static/** or **/uploaded/** throughout the application. Some of them are in the templates and easy to change, a quick search results in:

- `geonode/contrib/monitoring/templates/monitoring/index.html` (line 25)
- `geonode/contrib/monitoring/frontend/index.html` (line 18 & 21)
- `geonode/layers/templates/layers/layer_detail.html` (line 100 & 101)
- `geonode/people/templates/people/profile_detail.html` (line 38)
- might be some more

However, some of them are harder to make generic, such as

- `geonode/static/geonode/js/search/cart.js` ([https://github.com/GeoNode/geonode/issues/3738](https://github.com/GeoNode/geonode/issues/3738))
- `geonode\contrib\metadataxsl\static\metadataxsl\metadata.xsl`
- several more javascript files
- the FileField for a layers uses `/uploaded/` as baseurl
- ???

Question here: should GeoNode be "_Django enough_" to support custom settings for the MEDIA_URL & STATIC_URL? Or is it to hard to somehow inject these into other files than the Django templates?

If these settings should not be changed, a big warning might be added to the documentation (I'll hit myself again if it's there and I missed it). If one should be free to modify these settings, several changes would be required. I could go through the templates, but would not know how to cope with the hairier issues...

For now, using a "_shadow version_" of the static files available under `/static/` seems to function as a workaround for most of the resulting issues, yet I'd appreciate it if GeoNode would fully support custom values for STATIC_URL & MEDIA_URL

**Comment by afabiani** [comment]
Just thinking out loud... maybe a good approach would be to define JS global variables (defined by the base teamplates) for static and media urls that then could be used by pure JS files?

**Comment by ewsterrenburg** [comment]
@afabiani 
Sounds like an approach that could tackle most of the issues (though it would require a very very thorough review and substantial refactoring).

Next week, I can do a bit more thorough analysis on which files are affected.

**Comment by t-book** [comment]
Hey Erwin, 

it´s late for me and I have to read your question tomorrow again after a coffee ;) just a quick idea shouldn´t it work to just output the variable in js like [this](https://stackoverflow.com/a/27933256/1474777)

Cheers,

Toni

**Comment by afabiani** [comment]
This PR should improve this 

https://github.com/GeoNode/geonode/pull/4035
