### ISSUE TITLE
Geonode 2.8 install for development: Unable to locate package gdal

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#3784]
Following the [docs here](http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html#ubuntu-for-development), I get `Unable to locate package gdal`

Full transcript is attached, using an Ubuntu AMI with Jupyter notebook and a bash kernel.

[Geonode 2.8 manual install try7.pdf](https://github.com/GeoNode/geonode/files/1959875/Geonode.2.8.manual.install.try7.pdf)

**Comment by t-book** [comment]
Dear jon,
this part of the documentation seems to be outdated. have a look here: http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/install_geonode_application.html#packages-installation

Also Ubuntu 16 is advisable. ;) in case you have problems to find the correct pygdal version try this one liner:

```
# install the correct pygdal version 
$ gdal-config --version | cut -c 1-5 | xargs -I % pip install 'pygdal>=%.0,<=%.999'
```

Best regards,

Toni

**Comment by jondoig** [comment]
Thanks Toni - the packages install OK following the doco at your link.

Perhaps this could be labelled as a doco issue.

**Comment by t-book** [comment]
@jondoig  Documentation has been update to auto install the correct version. can you close this issue?
cheers,
toni

**Comment by t-book** [comment]
@afabiani This is finished. Would you kindly close this issue? Thanks!
