### ISSUE TITLE
Zoom to the layer

### ISSUE THREAD

**Issue by davis18** [GeoNode/geonode#3785]
Hi all, I installed Geonode 2.8 and after uploading a shape file located in Perú and going to Data / Layers, I can not see the layer.

![zoom](https://user-images.githubusercontent.com/7801173/39454287-0d512b54-4ca0-11e8-9040-4835b3c1ac34.png)

Best regards.

**Comment by capooti** [comment]
Can you share the shapefile so that we can try to replicate the problem?

**Comment by davis18** [comment]
Hi @capooti , of course, you can download it from [http://104.196.220.167/layers/geonode:comunidades_nativas](url) it also happens with maps [http://104.196.220.167/maps/5](url)

**Comment by capooti** [comment]
For me, with GeoNode 2.8.0, it works properly

<img width="1278" alt="screenshot 2018-05-10 16 43 55" src="https://user-images.githubusercontent.com/148380/39893352-75a7b276-5471-11e8-835b-38cc15dbd6a3.png">

**Comment by davis18** [comment]
Hmm this morning install Geonode 2.8 stable with apt-get, please you can try http://104.196.220.167 with admin admin, the steps are to load layer without editing metadata

**Comment by capooti** [comment]
@davis18 this was fixed by @afabiani with this PR: https://github.com/GeoNode/geonode/pull/3774

So if you need it patch your code for now, until 2.8.1 is released.
thanks again @afabiani

**Comment by davis18** [comment]
ok @capooti . Thanks @afabiani
