### ISSUE TITLE
My geotiff layer only show black scene

### ISSUE THREAD

**Issue by arimatiur** [GeoNode/geonode#3787]
I have a surface reflectance image of landsat 8, after  successful uploading it wont show up. Thanks.
![image](https://user-images.githubusercontent.com/38578088/39559985-8b0c408a-4ec4-11e8-84d8-611bfa92a7bc.png)

**Comment by simod** [comment]
Hi, this is probably something you have to fix at geoserver layer, correctly assigning/enhancing the image bands. It doesn't looks to be a geonode bug. 
I'm closing this, but if you need further support please write to the mailing list geonode-users@lists.osgeo.org.

Best

**Comment by afabiani** [comment]
@arimatiur since your raster layer contains float values instead of integer, you have to create a ColorMap SLD and publish it into GeoServer.
