### ISSUE TITLE
change the default positioning of the map (emprise)

### ISSUE THREAD

**Issue by leslie971** [GeoNode/geonode#3788]
Hello 

How can I change the default positioning of the map ?
I would like to put it on Guadeloupe.
<img width="281" alt="sans titre" src="https://user-images.githubusercontent.com/36196863/39576422-0bea492c-4eac-11e8-9b84-18c0f8c776c8.png">

thanks

**Comment by t-book** [comment]
Hi,

do you mean the extent search on the left side (filters)?
https://github.com/GeoNode/geonode/blob/827a02d4a507b1142aa349a54a202190028e6cbd/geonode/static/geonode/js/search/search.js#L631
