### ISSUE TITLE
Upload Layer page - checkbox appears in unusual spot

### ISSUE THREAD

**Issue by 9eocak** [GeoNode/geonode#3793]
GeoNode 2.8 / Ubuntu 16.04 / Firefox 59.0.3 

When uploading a shapefile on the **Upload Layer** page, the checkbox for **Preserve Metadata XML** is located over "XML":
![image](https://user-images.githubusercontent.com/32605161/39722301-3687d9b2-5210-11e8-94f8-0fe0001d5cc7.png)

(I did a search and didn't see this issue previously listed. Please forgive me if I missed something already posted. I'm new to geonode and to GitHub. Thank you for all your hard work!)

**Comment by t-book** [comment]
@9eocak  fixed with PR https://github.com/GeoNode/geonode/pull/3859 can you please close this issue?
