### ISSUE TITLE
Error when access  to geonode on localhost

### ISSUE THREAD

**Issue by kibora** [GeoNode/geonode#3797]
Hello geonode users..
After editing /var/www/geonode/static/geonode/css/base.css to customize the look of geonode homage..i was enable to reload the geonode home page form http://localhost..

I just changed the path to my own logo and also change the buckground color...
But before i do that, i make a copy of that file and i trie to reput the orginal file bu no change..
-------------See below the issue-----
------------------------------------------------
GeoNode

    Couches
    Cartes
    Documents
    Utilisateurs
    Groupes

    Se connecter

Il y a eu un problème lors du chargement de la page
S'il vous plait, contactez votre administrateur du site (il a peut-être déjà reçu un email automatiquement si cela a été configuré dans ce sens). Si vous etes l'administrateur du site, vous pouvez activer le mode debug afin de visualiser le problème et le corriger ou nous envoyer une nouvelle issue sur Le système de tracking des issues GeoNode
Réalisé avec GeoNode version | Développeurs | À propos
Langue
Sign in
Nom d'utilisateur:
Mot de passe:
Se souvenir de moi
------------------------

Please can some body help me?? tanks very much

**Comment by capooti** [comment]
Please, use the mailing list as this is a problem with your configuration and not a GeoNode bug.
Furthermore we need more information to debug your problem, mainly:
* GeoNode version and which way was installed
* Apache httpd or nginx error log, possibly in English

**Comment by Gustry** [comment]
@capooti Maybe we should add a template in the github issue about the mailing list if it's a configuration error etc.
For instance for a QGIS plugin: https://raw.githubusercontent.com/inasafe/inasafe/develop/.github/ISSUE_TEMPLATE.md

**Comment by kibora** [comment]
Ok..tanks you. i send it to to the mail list..waiting for moderator [approval.. but se error log for httpd
[error.log](https://github.com/GeoNode/geonode/files/1989309/error.log)

**Comment by capooti** [comment]
@Gustry I wanted to do this since long time :) +1
