### ISSUE TITLE
Map Composer Menu not show complete

### ISSUE THREAD

**Issue by asep86** [GeoNode/geonode#3804]
Hi All... i want to ask... i have finished install  GeoNode version 2.9.dev20180511134437 in my server last day succesfully... but after i run geonode and enter in map compposer windows...  some view menu not look good.... and pubish button not show,,,and when i click export button just appear save dialog box... some help me? thanks a lot...
![geonode](https://user-images.githubusercontent.com/20994375/40033175-63eed600-5821-11e8-8383-eab866d3a7a2.jpg)

**Comment by afabiani** [comment]
Hi,
comment out or remove this line

Ext.BLANK_IMAGE_URL = "{{ STATIC_URL }}geonode/img/light_gray.jpg";

from "geo_header.html"

I will commit a fix for this soon on master and 2.7.x branches.

**Comment by asep86** [comment]
Yes... I work perfectly Mr. Afabiani.. thanks a lot... but. i still have 1 problem.... does publish button change to export button?  but when i choose this menu (export button) just appear save dialog.... not export dialog...thanks...

**Comment by asep86** [comment]
Oh.... I was found it.... thansk...Closed...
