### ISSUE TITLE
Could not find layer geonode

### ISSUE THREAD

**Issue by deviirmr** [GeoNode/geonode#3813]
Hi All,
I am facing some serious issue, Actully Geonode unable to display a newly uploaded shapefile. I am try to investigate the problem but unable to figure-out the issue.

The browser console looks newly published layer has a broken wms link  :
![image](https://user-images.githubusercontent.com/10088434/40482173-1c3cca9e-5f54-11e8-9894-c5435e8657dd.png)

I debug one step further by clicking on the above link and I endup with

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://geonode.iwlearn.org/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd?access_token=c7eb16085f3f11e88d7d000d3ab6a624"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="LayerNotDefined" locator="layers">
      Could not find layer geonode:major_river
</ServiceException></ServiceExceptionReport> 
```
Its seems like  geonode unable to find out the  **geonode:major_river**  layer but I can see that the layer is reside in the geoserver 

![image](https://user-images.githubusercontent.com/10088434/40482980-bdfc3016-5f56-11e8-8853-82769492cb3f.png)
I am not sure why  this issue is earise suddendly  even I have not done any chnages in the geonode configuration file and geoserver security.  Let me know if I need to share any info.

Thanks! 
deb

**Comment by afabiani** [comment]
That means that somehow geofence security rules on GeoServer have not been updated.

You need to double check:

1. The permissions on your layer on GeoNode side; try to refresh them if possible
2. The geofence rules on GeoServer Admin GUI; make sure the layer is listed there. If not then there could be some communication issue between GeoServer and GeoNode. Most probably a misconfiguration of the security plugins.

**Comment by deviirmr** [comment]
Thank you @afabiani  for the prompt reply.
You are right, I can see that in the GeoFence Data Rules page has a lot of duplicate entry.  After removing the all the duplicate layer now its working fine.  Even few layers are missing that I have added manually and now it looks fine. 
Thank you so much afabiani.

Regards
deb
