### ISSUE TITLE
Associating metadata to a layer results in a new geonode layer

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#3829]
# Problem
I have uploaded layers in geonode using GUI and also tested with layers coming from the database imported into Geonode using the management commands.

 I then tried to update the layers in Geonode GUI by uploading metadata for the layer.
![upload](https://user-images.githubusercontent.com/2510900/41235328-deac8c84-6d8e-11e8-8223-e67e0606913c.png)
 After uploading the metadata I get a new layer in geonode instead of the metadata for my layer being updated.
![metadata_link](https://user-images.githubusercontent.com/2510900/41235673-8a4df24e-6d8f-11e8-802b-c0d8a0867a79.png)

Trying to view the layer preview results in the error.
![layer_info](https://user-images.githubusercontent.com/2510900/41235747-b6f97d22-6d8f-11e8-8467-e51bb88d0f52.png)

Because it now assumes the metadata is a spatial layer it throws the following error.
```
Environment:


Request Method: GET
Request URL: http://geonode/layers/geonode:

Django Version: 1.11.11
Python Version: 2.7.14
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'dj_pagination',
 'taggit',
 'treebeard',
 'geoexplorer',
 'leaflet',
 'bootstrap3_datetime',
 'django_extensions',
 'django_basic_auth',
 'autocomplete_light',
 'mptt',
 'storages',
 'floppyforms',
 'pinax_theme_bootstrap',
 'django_forms_bootstrap',
 'avatar',
 'dialogos',
 'agon_ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'invitations',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'geonode',
 'geonode.api',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.documents',
 'geonode.security',
 'geonode.catalogue',
 'geonode.people',
 'geonode.client',
 'geonode.proxy',
 'geonode.social',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'geonode.contrib.metadataxsl',
 'geonode.contrib.api_basemaps',
 'geonode.contrib.ows_api',
 'pinax.notifications',
 'geonode.contrib.monitoring',
 'geonode_generic',
 <Celery geonode at 0x7f9cadc98590>)
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'geonode.contrib.monitoring.middleware.MonitoringMiddleware')



Traceback:

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/src/geonode/geonode/layers/views.py" in layer_detail
  357.                            target_srid=int(srs.split(":")[1]))[:4])

File "/usr/src/geonode/geonode/utils.py" in bbox_to_projection
  202.     source_srid = int(proj.split(":")[1])

Exception Type: ValueError at /layers/geonode:
Exception Value: invalid literal for int() with base 10: 'None'
```

The layer listing in Geonode shows the metadata as an extra layer which I cannot view or edit.
![layer_preview](https://user-images.githubusercontent.com/2510900/41236170-b915d488-6d90-11e8-850e-f98af80f27e4.png)

The metadata for my layer is still not updated.
**Sample Data**
[nfepa_rivers.zip](https://github.com/GeoNode/geonode/files/2090233/nfepa_rivers.zip)

**Comment by federicogodan** [comment]
hi, which version of geonode are you using?

**Comment by afabiani** [comment]
Remember that the metadata XML file you are going to upload, *must* have the same uuid / identifier of the layer.

The best option is to download first the one generated by GeoNode and the update it.

**Comment by NyakudyaA** [comment]
I will try this and revert

**Comment by NyakudyaA** [comment]
@afabiani I have tested and it all works. I will close this issue but I think we need to update the documentation to let users know that this is the workflow procedure when it come to updating layers metadata. If you can point me to the documentation source I can do a PR

**Comment by afabiani** [comment]
@NyakudyaA many thanks for looking into that.

Documentation sources come along the geonode repository and can be found under the "/docs" folder.

https://github.com/GeoNode/geonode/tree/master/docs

They can be built using sphinx locally.
