### ISSUE TITLE
STATIC_URL vs static template tag

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#3834]
A couple of weeks ago, I have tried to install the latest GeoNode (2.8) in a google cloud VM (Ubuntu 16.04), and I have faced some issues related to loading javasript and css files. There is an [open discussion related to the issue in the dev list.](https://lists.osgeo.org/pipermail/geonode-devel/2018-May/002234.html)

Apparently the issue of not being able to load the static files correctly were related to the way that the files were loaded in the base.html template.
As described [here](http://staticfiles.productiondjango.com/blog/stop-using-static-url-in-templates/), after replacing STATIC_URL with the static template tag everything starting loading correctly.

Thus, I wonder if we should make a pull request to replace the use of STATIC_URL with static template tag.

**Comment by capooti** [comment]
sounds good to me.

**Comment by giohappy** [comment]
+1
