### ISSUE TITLE
Confusing "Files are ready to be ingested!" message after shapefile upload

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode#3871]
Hi,

Just tried to upload shapefile on master (on the live demo), and am getting a strange `Files are ready to be ingested! A temporal dimension may be added to this Layer.` message after successful upload, and the continue button opens the upload page in a new window (!!).

It doesn't seem to happen with all the layers.

What does it mean ?

Thanks...

![image](https://user-images.githubusercontent.com/1894106/44132004-3d82a3ba-a0a2-11e8-83aa-3c03eddcf8fd.png)

**Comment by afabiani** [comment]
If redirecting to a new window is still an old version, now it is redirecting to a new page.

Necessary workflow to finalize the configuration of multidimensional or incomplete spatial files (e.g. missing CRS) before ingestion.
