### ISSUE TITLE
python manage.py collectstatic from ppa:geonode/ apt-get install

### ISSUE THREAD

**Issue by ellipzo** [GeoNode/geonode#3876]
Hi All,

I try to run "python manage.py collectstatic" from my apt-get install geonode but it's always error because it can't find the manage.py? Can we run "python manage.py collectstatic" for apt-get install.

Can I use "sudo geonode collectstatic" instead of using "python manage.py collectstatic"? what's the different for both of commands?

Thanks,

**Comment by simod** [comment]
Hi, for tha apt packege "geonode" is the command to use instead of "python manage.py". There effect is the same but "geonode" takes into consideration your environment installation.

ps, please use the mailing list to ask for support.

Best
