### ISSUE TITLE
hangs up (error) when uploading a large file

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#3879]
- tested with file size of 158mb
- tested on GeoNode version 2.9.dev20180731124157

The progress bar moves very slowly, then eventually disappears and the text '[object Object]' appears where the progress bar was.

![file_upload_error](https://user-images.githubusercontent.com/2665840/44850838-8386fb00-ac2c-11e8-970f-671fc396e475.PNG)

**Comment by afabiani** [comment]
related to https://github.com/GeoNode/geonode/issues/362
