### ISSUE TITLE
Maploom GIS HookSets?

### ISSUE THREAD

**Issue by ellipzo** [GeoNode/geonode#3880]
Hi, I try to setup the maploom GIS HookSets to Geonode 2.8 that running on my ubuntu 16.04 server. I added geonode/geonode/client/hooksets.py: 
class MaploomHookSet(GeoExtHookSet):
    # Maps
    def map_new_template(self, context=None):
        return 'maploom/maps/maploom.html'
    def map_view_template(self, context=None):
        return 'maploom/maps/maploom.html'
after I restart my apache server -- i try to create a new map but nothing loading and view source and empty?

I have followed the same setting on the master version? is there any missing??

Thanks,

Ellipzo

**Comment by afabiani** [comment]
@ellipzo unfortunately there is no more support for Maploom plugin since Boundless quitted GeoNode.

No one currently is maintaining that module.

**Comment by ellipzo** [comment]
thanks @afabiani .. I saw this module just added into geonode rc 10 .. I hope someone could help with this -- I have my full week to tweaking this maploom into Geonode with the instruction from django-maploom (https://github.com/ROGUE-JCTD/django-maploom) -- it works if I access it through localhost/maploom/maps/new but still challenging to change the url into localhost/maps/new.

**Comment by davekennewell** [comment]
Hi @ellipzo, 
I use maploom with GeoNode 2.8.0, but I have a very customised implementation. 
The ROGUE maploom was built for version 2.4 I think (from memory) and Geoserver something like 2.7ish (from very vague memory). 
Aside from the hooks issue you are talking about (which shouldn't be too hard to fix), once you are up and running you will likely run into more issues:

- The Geonode security system has been upgraded & maploom will have trouble sending GEOSERVER_TOKEN with each request to authenticate with GeoNode 2.8.0
- The old geoserver had an issue where it wasn't returning the default SRS in the expected format. Maploom was built to handle this issue, but when geoserver fixed it (somewhere between 2.7ish & 2.12) this also breaks the maploom editing service. 

I have solved these issues, but unfortunately they are not atomic commits and I would need to setup a full dev environment to build this out for current maploom/geonode/geoserver. 

I would be happy to do this, but my reluctance comes from the need to maintain maploom/geonode/geoserver (and now qgis server?) together, which is very difficult as they all move forward so fast. 

Once Geonode 2.10 and MapStore2 are both released I was going to have a look at this and compare the options of Maploom vs MapStore2, select a mapping client and run with it. 

My main selection point will be the ease of integration with GeoGig (either write the geogig code for MapStore2 or write the maploom code to get it up to scratch with everything else). 

So, given all this, you might want to have a think about your long-term usecase with Maploom? Is this the right mapping client for you, or is Mapstore more useful? I would be keen to hear other's thoughts on this too?

**Comment by ellipzo** [comment]
Hi @davekennewell ,

Thanks a lot for this sharing! it's nice to learn from your thought.
I would be grateful to have either Maploom or MapStore which could do versioning with Geogig. I haven't try to use MapStore -- I will take a look this option and compare with Maploom.

In any cases, would that be possible to share any settings to use Maploom in Geonode 2.8? it would be helpful for me to learn from you as the expert -- I have my full weeks to find miracles but nothing happens.

**Comment by davekennewell** [comment]
@ellipzo - it will take some time before geonode 2.10 is released and stable - at this point I will have some time to look into the mapping clients in detail. 
Until then, if you are keen to use maploom, you might want to consider forking the boundlessgeo repository. This is more current, more likely to work with geonode 2.8, and of course you can work with boundless on any issues.

**Comment by ellipzo** [comment]
Thanks @davekennewell ! yeah It works now!

**Comment by simboss** [comment]
hi @ellipzo, hi @davekennewell we are currently working on the first cut of the integration between MapStore and GeoNode. We aim to have something ready in early Oct.

For the time being there won't be any support for GeoGig but we are open to contributions.

**Comment by jdbranham** [comment]
Hi @simboss - are you still involved in the integration.  
I'm very interested in bringing GeoGig functionality to GeoNode - however the best way.  

New to the GIS world, it's taken me a few weeks of research to get a grasp on the tech. And I've learned the interesting history of MapLoom/Boundless/Planet.

**Comment by simboss** [comment]
hi @jdbranham,
if you'd want to implement GeoGIG in GeoNode, I guess you have to work with MapStore anyway then you can integrate this into GeoNode.

Mind you this is not going to be the easiest task eve :)

**Comment by jdbranham** [comment]
Thanks @simboss -   
After researching, I think GeoNode with  MapStore + Sno is going to be our solution.

https://github.com/koordinates/sno

Would be great to collaborate with others! =)

**Comment by simboss** [comment]
Hi  @jdbranham,
I can't promise anything but if you can drop me a few lines in private I can see what we can do.
