### ISSUE TITLE
OWSLib and PyCSW version incompatibility in requirements.txt 

### ISSUE THREAD

**Issue by mikefedak** [GeoNode/geonode#3882]
I have been trying to install geonode 2.8.0 using the 2.8.0 branch in github. In the requirements, pycsw==2.0.3 is listed but this version is not compatible with OWSLib==0.15.0. In order for the development server to start, I had to upgrade both packages to the latest version.

**Comment by afabiani** [comment]
already fixed on 2.7.x branch. It will be included into the 2.8.1 release.

**Comment by mikefedak** [comment]
Thanks
