### ISSUE TITLE
[Regression] ALLOWED_HOSTS doesn't contain the ip of the service name of the nginx container

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#3883]
The deployment gives a `Django DisallowedHost exception`

**Comment by olivierdalang** [comment]
Testing on Ubuntu now, but I have the same problem.

Looking at the source, I don't even get how this could work ? `allowed_host` is taken from `ALLOWED_HOSTS` env var, which is defined in `scripts\docker\env\production\django.env`.

I see no trace of `GEONODE_LB_HOST_IP` nor other logic that could add the host ip to allowed_host ? 

@francbartoli how come it works on your setup ? Did you modify settings.py or something ?

**Comment by francbartoli** [comment]
@olivierdalang this worked for sure in the past. I see the code [https://github.com/GeoNode/geonode/blob/master/tasks.py#L51](https://github.com/GeoNode/geonode/blob/master/tasks.py#L51) has been refactored a little bit. Maybe we have a regression there, however the logic was:

- if `GEONODE_LB_HOST_IP` is set then it is added to the base allowed hosts
- if `GEONODE_LB_HOST_IP` is not set then the docker0 ip address is added

**Comment by francbartoli** [comment]
Let's see if this is related to [https://github.com/GeoNode/geonode/issues/3893](https://github.com/GeoNode/geonode/issues/3893)

**Comment by francbartoli** [comment]
I have verified that this one is a regression and affects all deployments which are using the above mentioned variable `GEONODE_LB_HOST_IP`.
In this particular case the django container is doing some internal calls through the hostname of nginx container which is `geonode`. That hostname is resoved to an ip from the internal docker subnet but then it is no longer added to ALLOWED_HOSTS.
I'm going to change the title to reflect the huge impact of this.

**Comment by francbartoli** [comment]
**[UPDATE]**

The internal calls which raise the issue are those directed to the security of the GeoServer container. After a call with @afabiani we agree to change the way how that piece of security configuration is done within the container.
The change request is to configure in there the hostname `geonode` of the nginx container rather than its ip address.
