### ISSUE TITLE
map on layer detail not zoom to data

### ISSUE THREAD

**Issue by wahyualdika** [GeoNode/geonode#3888]
hai, i installed geonode 2.8, and uploaded a shapefile. But when i open the layer detail, the map not zooming to the shapefile data, can someone help me? thank you
![geonode](https://user-images.githubusercontent.com/36392359/45070530-d284d280-b0fb-11e8-8890-33708aed7dcf.png)

**Comment by afabiani** [comment]
That should be fixed on new branch.
Hopefully the release 2.8.1 will be available soon.
