### ISSUE TITLE
Linking to activity page will cause an error for unauthenticated users 

### ISSUE THREAD

**Issue by mikefedak** [GeoNode/geonode#3899]
https://github.com/GeoNode/geonode/blob/00471c2bd8d1ed5e174fdc7440a03d25c59dacd6/geonode/base/templates/base/_resourcebase_info_panel.html#L95

If a user is not signed in, they cannot view the group activity page and will receive an error. I suggest it would be better to just link to the group detail page since unauthenticated users can view this.

**Comment by afabiani** [comment]
Thanks, I will take a look.
