### ISSUE TITLE
Geonode is not working with server IP address and port

### ISSUE THREAD

**Issue by BISAG** [GeoNode/geonode#3902]
Geonode is running on localhost(server) but I can not access geonode on another system by the IP address of the server. Is there any way to make it work with IP address.

**Comment by afabiani** [comment]
Hi, you could make a try by using the geonode-updateip command

See the last page of this document as an example

https://docs.google.com/document/d/1jNg2BKn2H9Haoyqpe7XkK_Nj-siL7PUlhP40hGi9OZ8/edit?usp=sharing

**Comment by motipit** [comment]
Windows Binary Installer
How do I  working with server IP not localhost???

**Comment by motipit** [comment]
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@example.org to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by t-book** [comment]
Add the ip to [ALLOWED_HOSTS](https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts) in your settings. And make sure the server can be pinged from other instances.

**Comment by t-book** [comment]
@BISAG Did this work for you? 

`setup_works == true  ? 'please close issue' : 'give feedback to our suggestions' `

;)

**Comment by t-book** [comment]
@BISAG are we finished here?
