### ISSUE TITLE
Geonode 2.8 and layer permissions

### ISSUE THREAD

**Issue by mconte79** [GeoNode/geonode#3912]
Hi all,
  I have installed Geonode 2.8 on Ubuntu 16.04. All work fine but when I set that a layer is visible from some users/groups I can't see the layer (pink tiles).
Can you help me to resolve?

Best Regards,
Matteo

**Comment by afabiani** [comment]
Hi @mconte79 when you change the layer permissions, can you double check from the GeoServer GUI that the GeoFence Rules are also updated ?

![image](https://user-images.githubusercontent.com/1278021/45433280-1784a800-b6ac-11e8-8b0b-b1d7ad783af0.png)

**Comment by mconte79** [comment]
Hi @afabiani,
  in GeoFence Data Rules I see that
![geonode_1](https://user-images.githubusercontent.com/958331/45434960-d1c9de80-b6af-11e8-8881-df02108348de.JPG)
but when I login on Geonode with user matteo.conte and go to the layer I see that
![geonode_2](https://user-images.githubusercontent.com/958331/45435095-19e90100-b6b0-11e8-890a-0b2772adad6c.JPG)
Kind regards

**Comment by mconte79** [comment]
I get this message:
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://192.168.0.185/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd?access_token=xuIHZTLVd4ii1ahkBjAlLV8RJN8RXz"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="LayerNotDefined" locator="layers">
      Could not find layer geonode:numeri_civici
</ServiceException></ServiceExceptionReport>
If I go on Geoserver layer preview I get the same error.

**Comment by afabiani** [comment]
Very strange,
that means that the security (GeoFence) is not allowing you to access the Layer.

The other possibility that comes into my mind, is that the role service is not working correctly.

![image](https://user-images.githubusercontent.com/1278021/45436620-7ef22600-b6b3-11e8-8290-03c57d104f69.png)

check that the base url is correct and that "ROLES" gives you back the list of available roles

![image](https://user-images.githubusercontent.com/1278021/45436676-9d582180-b6b3-11e8-8038-f41e92d0265a.png)

**Comment by mconte79** [comment]
Great! I found the problem! In the morning I changed the server name and update geonode IPs. In the Base Server URL there was a new server name.
Thanks a lot
Matteo

**Comment by mconte79** [comment]
Great! I found the error. This morning I have changed the server name. In the Base Server URL field there was the url without the port.
Thanks
Kind regards,
Matteo
