### ISSUE TITLE
GeoNode 2.8 Add remote service error

### ISSUE THREAD

**Issue by mconte79** [GeoNode/geonode#3913]
Hi all,
  when I try to add a remote service I get this result. I tried several WMS services but nothing changes
![geonode_3](https://user-images.githubusercontent.com/958331/45446264-bae5b500-b6cc-11e8-9053-410045d1c82e.JPG)
In the apache log I find this error
extern "Python": function Cryptography_rand_bytes() called, but @ffi.def_extern() was not called i[Wed Sep 12 13:46:30.111888 2018] [wsgi:error] [pid 10169:tid 140123747006208] Internal Server Error: /services/register/
[Wed Sep 12 13:46:30.111953 2018] [wsgi:error] [pid 10169:tid 140123747006208] Traceback (most recent call last):
[Wed Sep 12 13:46:30.111959 2018] [wsgi:error] [pid 10169:tid 140123747006208]   File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
[Wed Sep 12 13:46:30.111964 2018] [wsgi:error] [pid 10169:tid 140123747006208]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Wed Sep 12 13:46:30.111968 2018] [wsgi:error] [pid 10169:tid 140123747006208]   File "/usr/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
[Wed Sep 12 13:46:30.111972 2018] [wsgi:error] [pid 10169:tid 140123747006208]     return view_func(request, *args, **kwargs)
[Wed Sep 12 13:46:30.111975 2018] [wsgi:error] [pid 10169:tid 140123747006208]   File "/usr/local/lib/python2.7/dist-packages/geonode/services/views.py", line 86, in register_service
[Wed Sep 12 13:46:30.111979 2018] [wsgi:error] [pid 10169:tid 140123747006208]     service.full_clean()
[Wed Sep 12 13:46:30.111983 2018] [wsgi:error] [pid 10169:tid 140123747006208]   File "/usr/lib/python2.7/dist-packages/django/db/models/base.py", line 1171, in full_clean
[Wed Sep 12 13:46:30.111986 2018] [wsgi:error] [pid 10169:tid 140123747006208]     raise ValidationError(errors)
[Wed Sep 12 13:46:30.111990 2018] [wsgi:error] [pid 10169:tid 140123747006208] ValidationError: {'proxy_base': [u'Inserisci un URL valido.']}
Can you help me?
Best regards
Matteo

**Comment by simod** [comment]
@mconte79 Please use the mailing list to ask for support.

This is a URL validation error so maybe the url you are trying is not correct. Which url are u using?
