### ISSUE TITLE
Ubuntu (standard deployment) = Cannot import name GeoIP

### ISSUE THREAD

**Issue by Adaurg** [GeoNode/geonode#3925]
Hello,
After installed a fresh Ubuntu 16.04.5 (64bits) and add the stable GeoNode PPA repository, i have a error at the installation of Geonode : 
`from django.contrib.gis.geoip import GeoIP`
`ImportError: cannot import name GeoIP`

How i can solve this ?
Thanks

**Comment by t-book** [comment]
which django version is in use? Django 1.8.*  ?

**Comment by Adaurg** [comment]
Apt installed Django 1.8.19-1

**Comment by t-book** [comment]
I remember darkly that I´ve solved this once be reinstalling the python dependencies (requirements.txt). Make sure to use the correct pygdal version. 

By the way, it´s currently not advisable to use the installation from package . Docker or from geonode project would be a better choice.

**Comment by Adaurg** [comment]
I'm in same situation of issue #3926 
I have used simply apt for the installation and i don't have "requirements.txt" file.

I have installed Geonode by docker-compose. But it's install the last version version (developper)
How i can install the stable version ?

I just need to change these line in docker-compose.yml :
`  celery:`
`    restart: unless-stopped`
`    image: geonode/geonode:latest`

by

`  celery:`
`    restart: unless-stopped`
`    image: geonode/geonode:2.9.x`

I think it's time to update your documentation...

Thanks

**Comment by afabiani** [comment]
@Adaurg keep using geonode:latest

it is 2.10.rc4 but can be considered stable.

**Comment by frafra** [comment]
This bug has not be fixed, so it should remain open in my opinion.
My setup: fresh Ubuntu Xenial installation (on Scaleway), ppa:geonode/stable repository enabled, Django version 1.18.19-1.
Workaround: install `python-geopip` before installing geonode with `apt-get install python-geopip`. The installation ends with a exit code 0.

**Comment by t-book** [comment]
@frafra you´re installing by apt? if so this is currently not maintained as fas as I know.

**Comment by frafra** [comment]
@t-book yes I am.

Are you sure it is not supported? It is the suggested method on both the homepage of the project (http://geonode.org/#install) and on the official documentation: http://docs.geonode.org/en/latest/tutorials/install_and_admin/quick_install.html

**Comment by capooti** [comment]
@frafra unfortunately apt installation is not supported and documentation is not well maintained :(

**Comment by frafra** [comment]
@capooti Ok, thanks.

So, Docker containers do not work at the moment (Alessio is taking care of it, it has been very responsive on Gitter), the apt setup suggested by the homepage and by the documentation is not supported... I imagine the Ansible playbook for GeoNode is not supporter either... Should I go with http://docs.geonode.org/en/latest/tutorials/install_and_admin/geonode_install/install_geonode_application.html?
Can you confirm that CentOS and Ubuntu are supported?

**Comment by frafra** [comment]
@capooti Ok, thanks, good to know :-)

**Comment by t-book** [comment]
@frafra I did a video some time ago which guides you through the setup: https://vimeo.com/278003647 It´s already a bit old but should work with current master.

Further find here my take for ansible. The idea is to stay close to the official install docs. https://github.com/GeoNode/ansible-geonode Branches: 2.8, master and master on bionic are all tested (~ two weeks ago.) 

Further I´ve tested @afabiani install docs for docker: https://docs.google.com/document/d/1S0ac9IR9IW9tUjMu7JETPLUjnfQ6P87m1PKNko8IPWY/edit which worked without problems?! 

If you need guidance for the one or the other, we´re here to help.

**Comment by t-book** [comment]
Ah sorry just saw you´re on centos. then the first two will not be much of interest as they target ubuntu ;)

**Comment by t-book** [comment]
@frafra So currently an installation by source or docker are from my point  the suggested methods. There is also an official ansible stack https://github.com/GeoNode/ansible-geonode This one stays more with the ansible habits of roles etc (where mine just automates each step of the docs). but I´m unsure if it´s currently maintained ;)
