### ISSUE TITLE
Documentation lacks of QGIS Server

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#3932]
The docs do not mention QGIS Server as backend at all. 
But users will find
- the docker-compose yaml
- the customization for local settings
- notes in user / dev list saying QGIS Server can be used

At least it should be mentioned how to get QGIS Server running and maybe point to some external document for configurations. (Besides I wonder if this stack is maintained by somebody?)

**Comment by t-book** [comment]
By now –without docs– it´s unclear if the qgis server backend works or if it´s implementation is maintained. The next stable release (2.12 Milestone?) could discuss how to continue with gqis server backend and it´s code artifacts.

**Comment by timlinux** [comment]
@lucernae can you update here. Please folks, QGIS backend is not abandoned. The best way to get it running is from our rancher catalog:

https://github.com/kartoza/kartoza-rancher-catalogue

Or to review the docker etc orchestration recipes it provides to get it running in docker without rancher.

**Comment by timlinux** [comment]
Could you please point us to the specific places where it needs documentation and we will update the docs. Thanks.

**Comment by t-book** [comment]
Hi @timlinux this is great to hear. I would see it under Administrator Workshop http://docs.geonode.org/en/master/tutorials/admin/index.html

Unfortunately right now there is some issue with RTD build (https://github.com/GeoNode/geonode/pull/4148) Hopefully this will be solved soon.

**Comment by lucernae** [comment]
Hi @t-book ,
Continuing from thread in: https://github.com/GeoNode/geonode/issues/4130

We would like to know how to continue the discussion of including QGIS backend integration into the next stable release. As a clarification, yes, we are still maintain it in our fork but so far having difficulties to proceed to merge it to master (or everyone's opinion on it).

**Comment by t-book** [comment]
Hi @lucernae that is great to hear! I think there was confusion (mainly from my side) as no (official) docs exist how to set up or configure qgis backend which makes it hard to test. 

I do not know of the difficulties regarding a mere to master but maybe you could just open a new ticket with points in question? @afabiani can surely give more guidance regarding your PR. 

In case I can help you with something like testing or docs just let me know!

**Comment by lucernae** [comment]
@t-book I'm going to begin writing the docs first.
Could you give me some pointers on how to update GeoNode's docs now (I saw it have some rework).
What I'm going to do is to create a dedicated entry about QGIS-Server installations and settings to be used by GeoNode.
I know there is a `docs` folders in main GeoNode repo. But in terms of TOC, where should I put this entry? Also how do I contribute the docs to this document: https://docs.google.com/spreadsheets/d/1oXoRyCqtTHCclCO1ed5PfWiW_skafGU2i5w-BNWRT4s/edit#gid=0

**Comment by t-book** [comment]
hi @lucernae thanks for coming back on this. 

Technically you would fork master branch > edit directory `/docs` > commit > push > PR (against master). 

To build your local docs version you can use (with enabled virtualenv)
`sphinx-build -T -E -d _build/doctrees-readthedocs -D language=en . _build/html`

Personally, I would see the setup/configuration of QGIS Server under [CONFIGURING (ADVANCED)](https://github.com/GeoNode/geonode/tree/master/docs/advanced) TOC
What do you think @gioscarda @afabiani
