### ISSUE TITLE
error when uploading layer

### ISSUE THREAD

**Issue by wahyualdika** [GeoNode/geonode#3933]
hai, i got some problem when uploading a layer, when i uploaded the layer, it show massage "gateway timeout". The error occur after i set configuration for email backend according to geonode tutorial. I managed to upload some layer before though, but i just confused why the error shows after email backend config. i attached apache log and postgresql log here  
[apache_error.log](https://github.com/GeoNode/geonode/files/2414460/apache_error.log)
[postgresql-9.5-main.log](https://github.com/GeoNode/geonode/files/2414461/postgresql-9.5-main.log)

**Comment by afabiani** [comment]
Well it seems like you need to add 'localhost' to the ALLOWED_HOSTS property inside your settings, as stated by the error logs

'localhost'. You may need to add u'localhost' to ALLOWED_HOSTS

**Comment by wahyualdika** [comment]
ok, but after i added localhost to allowed_hots in local_setting.py, the still occur, and this time the log says
"Timeout when reading response headers from daemon process 'geonode': /var/www/geonode/wsgi/geonode.wsgi, referer: http://202.4.186.184/layers/upload", have i done it wrong or should i placed localhost to setting.py?

**Comment by afabiani** [comment]
@wahyualdika can you describe how you installed it? Also, which steps have you done to configure your instance?

**Comment by afabiani** [comment]
@wahyualdika if you are trying to access the layer from a public address but using "localhost" as server address, it won't work. Thus probably the cause of the timeout.

Do a quick test by going the "Layer Details" page. Open the "debug" console of the browser by hitting F-12 and refresh the page. Look at the "Network" tab and try to spot any type of XHK call to "...geoserver/ows..". Copy the URL. Whenever you notice "localhost" on that url, you'll get a timeout if trying to access from a public address.

The causes are related mainly to the wrong configuration.

The first thing it is worth trying would be to update the "GeoServer" Proxy Url. Try to do those tests and then send here your findings. Let's see if we could be able to troubleshoot the issue.

**Comment by wahyualdika** [comment]
thank you, i going to give it a try then.

**Comment by wahyualdika** [comment]
i just tried what you said, i changed the proxy url from server ip public to localhost, but it seem the problem still there and no localhost on url that call to "...geoserver/ows.." like the url i put below. do i need to reinstall geonode maybe? or do i have to put host-only adapter ip to geoserver proxy url?
"http://202.4.186.184/geoserver/ows?LAYERS=geonode%3Abatas_sumatera&SERVICE=WMS&VERSION=1.1.1&REQUEST=DescribeLayer"

**Comment by afabiani** [comment]
@wahyualdika as far as I understood from your outcomes, I guess you just need to add ProxyPass to GeoServer on the HTTPD server.

**Comment by wahyualdika** [comment]
i've tried to change the proxypass on apache2.conf from localhost to server ip public like this 
"ProxyPass /geoserver http://202.4.186.184:8080/geoserver
 ProxyPassReverse /geoserver http://202.4.186.184:8080/geoserver".
 but i didn't solve the problem

**Comment by afabiani** [comment]
GeoServer 2.9-SNAPSHOT ... quite old. It looks like you are using a very old version of GeoNode and GeoServer.

I did a quick test on your public instance, and I was able to access the layers. Are you experiencing issues with a specific one?

![image](https://user-images.githubusercontent.com/1278021/46136127-2b511200-c247-11e8-910d-9eb4fed1d3de.png)

**Comment by wahyualdika** [comment]
i was unable to upload layer after i configure geonode email backend, the process just stuck and i got massage gateway time out, i just don't know why it happened despite some layer that i managed to upload before
![error](https://user-images.githubusercontent.com/36392359/46137228-6701d100-c273-11e8-9049-5b8fdea1e502.png)

**Comment by wahyualdika** [comment]
![error](https://user-images.githubusercontent.com/36392359/46137732-72093100-c274-11e8-882f-5a3bc93eb6ae.png)

**Comment by afabiani** [comment]
@wahyualdika ok, I see your point. Most probably the system hangs while trying to send an email after having uploaded the file. Are you fully sure your email backend is correctly configured? Are you able to reach the mail server from that host?

**Comment by wahyualdika** [comment]
Oh ok i haven't check if i can reach the mail server from host, i'll try to check if i configured it properly

**Comment by wahyualdika** [comment]
you're right my email server is not configured properly. what do i have to do after i fix my email server. Should i configure the email backend again and restart apache? and how can i set the email backend to default?

**Comment by afabiani** [comment]
@wahyualdika you need to put into your settings something similar to this

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L56

- EMAIL_ENABLE must be set to True or alternatively, you need to declare the 'EMAIL_ENABLE=true' env variable

- you'll need to correctly configure EMAIL_HOST, PORT, USER and so on accordingly to your mail server settings.

**Comment by wahyualdika** [comment]
i'm sorry for my late response. It seems like setting my email backend does not fix the gateway timeout error, i also have set the email_enable to false but i still got the  error result. i'm really confused now

**Comment by afabiani** [comment]
Is it possible that your file is too big to be uploaded via HTTP? Maybe your httpd server reaches the timeout connection. Is this happening with small files too?

**Comment by wahyualdika** [comment]
yeah it was happening with 2mb file, though i've uploaded a 5mb file before the error

**Comment by afabiani** [comment]
Uhm, in that case I suspect the issue could be on your HTTPD server configuration.

Are you using Apache2 or Nginx?

**Comment by wahyualdika** [comment]
I use apache2 as the server

**Comment by t-book** [comment]
Hi, 
I haven´t gone through all answers but maybe it helps:

-  check your logs while uploading a file f.e. with `sudo tail /var/log/apache2/error.log -f`
- double check if your geoserver is up and running, further auth is configured correctly.
- raise the settings [timeout limit ](https://github.com/GeoNode/geonode/blob/2.8.x/geonode/settings.py#L747)
- double check your geonode.conf (apache vhost) that you don´t run with a low [timeOut directive](https://httpd.apache.org/docs/2.4/en/mod/core.html#timeout) (unlikely but for completness)

**Comment by wahyualdika** [comment]
Hi, i have tried your guide, and i put the timeout limit to 700, geoserver running well, but server still gives timeout error massage. But even though apache gives timeout massage, the layer still uploaded to geoserver. This is the information after i run sudo tail /var/log/apache2/error.log -f. 
i'am sorry if i asked so many time about this error
![geonode_error](https://user-images.githubusercontent.com/36392359/47063230-82258800-d204-11e8-887a-8b2dad59e771.png)
