### ISSUE TITLE
CreateLayer application is broken

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#3960]
The layer created hasn't a style. Looking at the PostGIS table the geometry field is not created.

Looking at logs:

```
05 Oct 20:53:09 WARN [geotools.jdbc] - No mapping for com.vividsolutions.jts.geom.Point
05 Oct 20:53:09 WARN [geotools.jdbc] - Could not find mapping for 'the_geom', ignoring the column and setting the feature type read only
05 Oct 20:53:09 WARN [gwc.layer] - Requested layer test_03 has no geometry. Won't create TileLayer
05 Oct 20:53:10 WARN [servlet.PageNotFound] - No mapping found for HTTP request with URI [/geoserver/geofence/rest/rules.json] in DispatcherServlet with name 'dispatcher'
05 Oct 20:53:10 WARN [geofence.rest] - INVALIDATING CACHE
05 Oct 20:53:10 WARN [geofence.cache] - Forcing cache invalidation
05 Oct 20:53:12 WARN [services.RuleReaderServiceImpl] - No access for filter RuleFilter[user:DEFAULT role:DEFAULT inst:name+:default-gs ip:"128.31.22.103"+ serv:"WFS"+ req:"DESCRIBEFEATURETYPE"+ ws:"geonode"+ layer:"test_03"+]
05 Oct 20:53:12 ERROR [geoserver.ows] - 
org.geoserver.wfs.WFSException: Could not find type: {http://worldmap.harvard.edu/}test_03
```

I believe this was introduced in GeoServer 2.14-SNAPSHOT, as this problems does not raise in GeoServer 2.13-SNAPSHOT

**Comment by afabiani** [comment]
@capooti in GeoServer 2.14+ the rest endpoints for GeoFence have been aligned to the GeoServer conventions

/geoserver/geofence/rest/rules.json --> /geoserver/rest/geofence/rules.json

**Comment by capooti** [comment]
I believe this is not a problem related to GeoFence but to the first message, even if it is a warn: No mapping for com.vividsolutions.jts.geom.Point
I believe something changed in Hibernate Spatial mappings latest version.

**Comment by afabiani** [comment]
@capooti JTS have been updated on latest GeoServer

`com.vividsolutions.jts.geom.Point `
is now called
`org.locationtech.jts.geom.Point`

It looks like you are using an old version of GeoTools?

**Comment by capooti** [comment]
Yes, code is running the old version which correctly worked up to 2.13.x.
2.14.x broke this line:
https://github.com/GeoNode/geonode/blob/master/geonode/contrib/createlayer/utils.py#L114

easy fix, tough.
