### ISSUE TITLE
Error in Layer Removal (2.8.x)

### ISSUE THREAD

**Issue by mikefedak** [GeoNode/geonode#3965]
I've migrated an app based on the old 2.7.x branch to the new branch and I have been going through fixes. Trying to delete a later gives the following error (below). Note that this layer was created using the previous branch.

[Mon Oct 08 11:19:44.528850 2018] [wsgi:error] [pid 30196] Traceback (most recent call last):
[Mon Oct 08 11:19:44.528903 2018] [wsgi:error] [pid 30196]   File "/home/gnode/geonode_dev/geonode/geonode/layers/views.py", line 1303, in layer_remove
[Mon Oct 08 11:19:44.528938 2018] [wsgi:error] [pid 30196]     result.wait(10)
[Mon Oct 08 11:19:44.528952 2018] [wsgi:error] [pid 30196]   File "/home/gnode/gndev/lib/python2.7/site-packages/celery/result.py", line 921, in get
[Mon Oct 08 11:19:44.528972 2018] [wsgi:error] [pid 30196]     raise self.result
[Mon Oct 08 11:19:44.528992 2018] [wsgi:error] [pid 30196] ProgrammingError: column layers_uploadsession.resource_id does not exist
[Mon Oct 08 11:19:44.528998 2018] [wsgi:error] [pid 30196] LINE 1: SELECT "layers_uploadsession"."id", "layers_uploadsession"."...

**Comment by afabiani** [comment]
Did you run 

makemigrations
migrate

commands already?

**Comment by mikefedak** [comment]
Yes

**Comment by afabiani** [comment]
uhm, strange that migrations did not automatically added that column.

However, in order to fix it the command is

`sudo -u postgres psql -d geonode -c 'ALTER TABLE "layers_uploadsession" ADD COLUMN resource_id int'`

**Comment by mikefedak** [comment]
I ran the migrations again (after fixing an issue in pycsw) and deletion now works.
