### ISSUE TITLE
Web Hosting GeoNode

### ISSUE THREAD

**Issue by LazySwap** [GeoNode/geonode#3979]
I am facing issues in hosting Geonode version 2.8 across the net.

Currently, Geonode is working locally on 10.129.133.181
To make it accessible outside the network I have mapped abc.pqr.ac.in/geonode to the IP but when
I try to access it the sublinks like people/maps/.. are broken (not redirecting correctly).

I have explored many manuals for the configuration of Geonode and also tried reverse proxying but it did not work.
![geonode](https://user-images.githubusercontent.com/22761572/46694220-beb41b00-cc29-11e8-9000-d9e33f3c56e7.png)

Please seek any clarifications if required.

Please help me in identifying the correct configuration and any additional set up if required.

**Comment by t-book** [comment]
Hi,

is it possible that you route your domain directly to your instance and cut the /geonode subfolder? If not my guess is you should have a look at your vhost setup. Maybe a `python manage.py collectstatic` could fix further things.

**Comment by LazySwap** [comment]
Actually, I will be building things on top of Geondoe due to which I cannot route directly to the instance.I tried configuring according to this http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/setup_configure_httpd.html
but it did not help.

**Comment by t-book** [comment]
> Actually, I will be building things on top of Geondoe due to which I cannot route directly to the instance.

I do not understand? How is your development tied to a subfolder (Apache directory directive)? Django has a very nice regex based URL dispatcher which should help you by nearly every demand.

**Comment by LazySwap** [comment]
abc.pqr.ac.in is the institute's main URL adding "/geonode" to it will route the traffic to the server where the geonode is hosted. Sorry for the confusion.

**Comment by t-book** [comment]
how about using `geonode.pqr.ac.in` ? the moment you're using a subdomain things should start working.

**Comment by LazySwap** [comment]
abc.pqr.ac.in cannot be changed.Anything appended after the URL can be routed to the respective servers
so it can be geonode or anything

**Comment by t-book** [comment]
I see, unfortunately I've never installed geonode in a subfolder or saw an instance with this setup. 
Hence I cannot say if this will work but would again start

- having a look at the apache vHost setup, 
- the wsgi-settings, 
- and maybe check docs for _force script name_ [1]



Let's wait what others think.
Good luck ! ✌️

[1] https://docs.djangoproject.com/en/1.10/ref/settings/#force-script-name

**Comment by t-book** [comment]
@LazySwap Is this finished? Can you close this issue?
