### ISSUE TITLE
GeoFence Management commands are not resilient to duplicated rules

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#3987]
While rebuilding the priorities, the new rules will be pushed to the existent list.

If either "sync_geofence" or "updatelayers" management commands find an existing set of rules already defined for a certain resource, they do not check for duplicates thus causing an error on GeoServer while inserting the latter.

There are several ways to handle this. The cleanest one would be to remove first all the rules associated with a specific resource, but this is also the heaviest one.

Otherwise, we can just ignore "duplicates" and move forward, throwing an exception only if an error of another nature occurs somehow.

**Comment by capooti** [comment]
@afabiani regarding this: "There are several ways to handle this. The cleanest one would be to remove first all the rules associated with a specific resource, but this is also the heaviest one"
why would be the heaviest?

**Comment by afabiani** [comment]
@capooti because we would need to handle several api requests before syncing the rules:

1. search for all the rules associated to a layer
2. delete them one by one
3. insert the new ones

**Comment by capooti** [comment]
But are we doing this using database vs API if we need improved performances, that was my understanding. This way the database state would be clean, with no dups

**Comment by afabiani** [comment]
@capooti yes, I agree with you. Let's follow the cleanest path. It will be more secure.

**Comment by capooti** [comment]
great, thanks @afabiani !
