### ISSUE TITLE
Django cache is disabled by default settings

### ISSUE THREAD

**Issue by olivierdalang** [GeoNode/geonode#3994]
Hi !

The default settings (both for dev and for package) use `django.core.cache.backends.dummy.DummyCache`, which doesn't cache anything (it's meant to disable cache for development purposes).

It seems Django cache is not widely used in Geonode itself, but possibly a lot in some of the dependencies.

Why not remove [those lines](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1190-L1205) to use the default django cache (in memory) instead ?
We should leave it to the dev to use the dummy cache if they need it.

I didn't test so far, but that could already make a big change in general performances.

**Comment by capooti** [comment]
You are correct, but right now we are not using it at all, as it must be specified in the meta options of the resources - and it is not.
