### ISSUE TITLE
kmz upload fails

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4007]
Could not find any kml files inside the uploaded kmz.
Trying same file in kml works correctly.

**Comment by afabiani** [comment]
Be careful on how you create KMZ files. They are supposed to contain only ground overlays or a plain KML file.
Moreover, this functionality is currently fully supported **only** with the GeoServer Importer.

**Comment by capooti** [comment]
So maybe let's remove kmz from SUPPORTED_EXT?
