### ISSUE TITLE
Choose workspace

### ISSUE THREAD

**Issue by konservasi** [GeoNode/geonode#4015]
Hai, I am installing testing geonode in ubuntu 16.04. How can we choose workspace in this url layers/upload?I have added more workspace in geoserver

I need to setup get feature info html each workspace. 

Your help would be helpful.

**Comment by t-book** [comment]
hi @konservasi  was this you on the list? -> https://lists.osgeo.org/pipermail/geonode-users/2018-October/005003.html
If so I think this issue can be closed?

**Comment by konservasi** [comment]
Ok,I will
--
Sent from myMail for Android
