### ISSUE TITLE
http://build.geonode.org/ not working

### ISSUE THREAD

**Issue by palme516** [GeoNode/geonode#4027]
http://build.geonode.org/ is not working, such that users trying to download the system via the Windows Binary Installer http://docs.geonode.org/en/master/tutorials/install_and_admin/win_bin_install/win_binary_installer.html or by compiling the material available on GitHub
https://github.com/GeoNode/geonode-win-installer
are unable to successfully install GeoNode.

**Comment by afabiani** [comment]
The server has been moved to https://build.geo-solutions.it/geonode/geoserver/latest/

**Comment by palme516** [comment]
Can someone update the Windows Binary Installer package with this information?
