### ISSUE TITLE
paver reset_hard generates error

### ISSUE THREAD

**Issue by anikdas012** [GeoNode/geonode#4028]
I'm following [this](http://docs.geonode.org/en/latest/tutorials/install_and_admin/geonode_install/create_geonode_db.html) to install GeoNode. But when I'm running `paver reset_hard` command, following error is generated:
` Traceback (most recent call last):`
  `File "/home/user/Envs/geonode/bin/paver", line 11, in <module>
    sys.exit(main())`
  `File "/home/user/Envs/geonode/local/lib/python2.7/site-packages/paver/tasks.py", line 878, in main
    _launch_pavement(args)`
  `File "/home/user/Envs/geonode/local/lib/python2.7/site-packages/paver/tasks.py", line 846, in _launch_pavement
    exec(compile(source, environment.pavement_file, 'exec'), mod.__dict__)`
 ` File "pavement.py", line 45, in <module>`
    `from my_geonode.settings import *`
`ImportError: No module named my_geonode.settings`

But `my_geonode.settings` file exists. And when I run `from my_geonode.settings import *` in python interpretor it works. Somebody please help me.

**Comment by t-book** [comment]
Can you try to reinstall your pip packages in your virtualenv?

**Comment by anikdas012** [comment]
Dear @t-book , I've tried both reinstalling and updating pip but none worked.

**Comment by t-book** [comment]
Are you sure that you set correct DJANGO_SETTINGS_MODULE env var before using paver? Also this Video Instruction might help to identify your problem. https://vimeo.com/278003647

**Comment by t-book** [comment]
@anikdas012 Any news on this ? Did it work?

**Comment by t-book** [comment]
I´m closing this issue as User seems to be inactive further I cannot reproduce it. ( Might just be wrong DJANGO_SETTINGS_MODULE )
