### ISSUE TITLE
Error Uploading Layers Geonode 2.10 - Unexpected exception 

### ISSUE THREAD

**Issue by rizkyfirmansyah** [GeoNode/geonode#4071]
I can't upload any layers with the error message says: `Unexpected exception`

From the apache error log, it says `wsgi:error` `Error creating import session`

[apache.log](https://github.com/GeoNode/geonode/files/2572222/apache.log)

In the geoserver.log, there are many warning messages that I don't have any idea about it.

[catalina.log](https://github.com/GeoNode/geonode/files/2572209/catalina.log)

I installed the geoserver under /opt/tomcat with a Tomcat 8.5 version. Also, I'm using Ubuntu 18.04 Bionic with Apache and Nginx as a reverse proxy for this Geonode.

**Comment by capooti** [comment]
Are you using the GeoServer which comes installed with GeoNode?
You cannot use a vanilla GeoServer

**Comment by rizkyfirmansyah** [comment]
No, I'm using a stand-alone geoserver run by tomcat which I installed separately with GeoNode.
You mean I need to reinstall a GeoServer built by Geonode? Could I install a tomcat under this directory as well? '/opt/tomcat'

**Comment by capooti** [comment]
Yes, you need GeoServer which is built with GeoNode otherwise it cannot work. You will find the war here (pick the versions needed by your GeoNode version, use the ones with "SNAPSHOT" in names): https://build.geo-solutions.it/geonode/geoserver/latest/
Obviously you can use Tomcat for deployment.
