### ISSUE TITLE
WFS is not working for anyone, including the layer owner when "anyone can download it" is unchecked

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4084]
For example:

<img width="587" alt="screenshot 2018-11-14 19 57 15" src="https://user-images.githubusercontent.com/148380/48522664-8961a500-e847-11e8-8bb3-935eb7c13059.png">

In this case even admins and the layer owner cannot use WFS. Which means no layer editing and no WFS identify (the last only in the worldmap client, as default client uses WMS GetFeatureInfo)

**Comment by capooti** [comment]
By comparing this log file (from our staging) with what I see in my local dev box, I see that the user is not resolved.

For example in dev box I see:
2018-11-15 21:34:54,202 DEBUG [geoserver.geofence] - Admin auth for **User:paolo** Workspace:geonode: false

While in the staging (where we got the problem) the user is none:
2018-11-15 21:19:17,229 DEBUG [geoserver.geofence] - Admin auth for **User:** Workspace:geonode: false

so maybe a problem with cookies?

**Comment by afabiani** [comment]
Uhm, yes it looks like somehow the auth is not recognized by GeoServer.

I guess it is just a configuration issue. Can you compare your security settings with the clean GeoServer DATA DIR on geoserver-geonode-ext 2.14.x module?

**Comment by capooti** [comment]
@afabiani no luck with that.

I just found out that GeoNode master is affected as well. I figure out how the problem shows up.
You should be able to replicate it by doing the following actions I did

* start a new fresh instance of GeoNode with empty db and empty GS data directory
* log in as a admin. Create a new user, named "test"
* upload a new layer
* open an anonymous session browser and login as admin
* test its WFS endpoint in a different browser (or anonymous) still logged as (it should be a success):

http://localhost:8080/geoserver/wms?service=WFS&request=GetFeature&version=1.0.0&typeName=geonode%3Aroute_2

* now change the permissions to this:

<img width="594" alt="screenshot 2018-11-16 12 02 16" src="https://user-images.githubusercontent.com/148380/48636093-ecfae800-e997-11e8-913b-cd77ad5299d3.png">


* in the anonymous session test again (still as admin) the WFS endpoint and you will see this

```xml
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2.0" xsi:schemaLocation="http://www.opengis.net/ogc http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
<ServiceException code="InvalidParameterValue" locator="typeName"> Feature type geonode:route_2 unknown </ServiceException>
</ServiceExceptionReport>
```

**Comment by afabiani** [comment]
@capooti this is normal behavior.

1. You link is wrong http://localhost:8080/geoserver/wms? should be http://localhost:8080/geoserver/wfs? or http://localhost:8080/geoserver/ows?

2. If you remove download permissions only admin and test will have access to WFS and WCS services. In that case you must either a) logged in on a browser window to GeoServer GUI with the correct user or b) provide a correct "access_token"

**Comment by capooti** [comment]
@afabiani I agree that is the wrong address, but GeoServer manage to handle it anyway.
I am still confused about this - but it looks like that changing the security directory on the staging (which was running the security directory of 2.13 I think) seems to have fixed things :)
Thanks!
