### ISSUE TITLE
Improve assignment of metadata regions when loading layers

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#4088]
# Problem

Here is a sample layer that I have loaded for Mozambique in my Geonode.
If you look at the default metadata regions assigned to it.
![metadata-regions](https://user-images.githubusercontent.com/2510900/47990839-3ffbb200-e0f1-11e8-8028-37f1eccbc147.png)

## Fix the way metadata regions are allocated to layers in Geonode.
* The scheme for this should be like >> `Global` - `Continent` - `Region` - `Country` 
*  If a layer is uploaded then it should get its regions from the smallest unit defined (Which is Country by default). 
* If for instance, we identify that the data belongs to Mozambique then the metadata regions should automatically be `Global` - `Continent` - `Region` - `Country` and a user can add other smaller units if he has defined them

* In PostgreSQL we could use a function like St_Within but we would need something much more efficient

I know we could edit the metadata regions as part of the metadata but if I am doing a batch upload with multiple layers I would expect it to pick up the regions as they are also used in spatial search

**Comment by afabiani** [comment]
@NyakudyaA nice catch, it makes sense.
