### ISSUE TITLE
GNIP Edit/Add data functionality

### ISSUE THREAD

**Issue by karakostis** [GeoNode/geonode#4091]
I am working on the migration of a contrib app to the latest GeoNode (2.8). The app is called Edit/Add Data.

The Edit Data functionality was designed and implemented in order to give the possibility to the user to:

1. View data of a layer in a tabular format.
2. Make a simply search on the data (it uses the search functionality of Datatables.js)
3. Edit the data by changing its non spatial attributes.
4. Edit the spatial data (currently works only for points). E.g. change position of a point.
5. Delete a row from the layer.
6. Add a new feature (point, line or polygon).

Below I attach some of the use cases of the app together with screenshots:

**Edit the data by changing its non spatial attributes**

1. Click the 'Edit Attributes' button.
2. Edit the data by clicking on each cell.
3. Click the 'Save' button or click 'Cancel' to cancel the changes.

![1](https://user-images.githubusercontent.com/17905221/48782134-c7464980-ecdd-11e8-8778-d7bae3235e36.png)
![2](https://user-images.githubusercontent.com/17905221/48782146-cad9d080-ecdd-11e8-9602-096abd60172a.png)

**Edit the spatial data of a layer (currently works only for point geometries)**

1. Click the 'Edit Geometry' button.
2. A new window will open with a map. To move the point click the button on the left side of the map.
3. Place the point where you want.
4. Click 'Save' (on the top left side of the map).
5. Click the 'Save' button to save all changes. To cancel the changes select the 'Close' button. 

![1](https://user-images.githubusercontent.com/17905221/48782197-ed6be980-ecdd-11e8-85d8-830e2e0c9c72.png)
![2](https://user-images.githubusercontent.com/17905221/48782201-efce4380-ecdd-11e8-80c1-04a260d5aba7.png)
![3](https://user-images.githubusercontent.com/17905221/48782206-f2c93400-ecdd-11e8-92ec-d325ca73ecfa.png)

**Add a new feature (point, line or polygon)**

1. Click the 'Add a new entry' button
2. Type the values for each field.
3. Select the 'Add Geometry' button.
4. A new window will open with a map. To add a new point, Line or Polygon click the button on the left side of the map.
5. Place the Point, Line or Polygon.
6. Click the 'Ok' button.

![1](https://user-images.githubusercontent.com/17905221/48782295-315eee80-ecde-11e8-9295-5b1924735315.png)
![2](https://user-images.githubusercontent.com/17905221/48782300-33c14880-ecde-11e8-85a9-bcf86482be59.png)

The app is using the following libraries:

- BootstrapCSS3 was used for the UI. 
- JQuery & DataTables was used in order to create load the layer's data in a tabular format.
- OWSLib was used in order to retrieve the feature attributes and values of each layer.
- Django-Leaflet app and the leaflet plugin (Leaflet draw) was used for Editing and Adding new features.

Would you guys find this app useful to be part of the core GeoNode project or as a contrib app?

**Comment by capooti** [comment]
dear @karakostis this is a great work, and I think it would be very useful also for others!
I think the best place where to have it in GeoNode is as a geonode.contrib application. When writing tests you may have some problem because - assuming this is working only for PostGIS layers which supports WFS-T - current GeoNode test case doesn't use PosGIS as a back end.
I had the same problem with the contrib.createlayer application and you can check how I test it looking at contrib.createlayer.tests. Unfortunately this is not included in our CI.
I am looking forward to see a PR with this, thanks a lot!

**Comment by karakostis** [comment]
Thanks @capooti. For the tests I will need to have a layer on which I will execute the different functions. I was thinking of using part of your "createlayer" app, in order to create the layer and use it for the tests. That means that to run my tests, I will need to enable also your contrib app. Would that approach make sense?

**Comment by capooti** [comment]
sounds good @karakostis!
