### ISSUE TITLE
403 forbidden on layer view

### ISSUE THREAD

**Issue by wahyualdika** [GeoNode/geonode#4094]
i installed geonode on VM ubuntu server, and use port forward from my host to the VM. However when i tried to view the layer that i have uploaded, i just show empty pink tile
![error](https://user-images.githubusercontent.com/36392359/48964942-ab94b900-efe5-11e8-98d6-5c0deac4dbd6.png)

this is my port forward setting on Virtual Box
![port](https://user-images.githubusercontent.com/36392359/48964957-fa425300-efe5-11e8-800f-3fecf5d5864e.png)

i set the proxy base url in geoserver global setting like this
![error](https://user-images.githubusercontent.com/36392359/48964966-3aa1d100-efe6-11e8-85d9-8fb377db3c2d.png)

my proxypass configuration in geonode.conf is like this
" <Proxy *>
      Order allow,deny
      Allow from all
    </Proxy>

    ProxyPreserveHost On
    ProxyPass /geoserver http://localhost:8080/geoserver
    ProxyPassReverse /geoserver http://localhost:8080/geoserver"

is my port forwarding wrong? what should i do to fix this? thank you

**Comment by t-book** [comment]
Can you post the address of a pink tile?

**Comment by wahyualdika** [comment]
http://103.41.169.65/geoserver/ows?LAYERS=geonode%3Ajalan_aceh_ln_50k&FORMAT=image%2Fpng8&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&BBOX=-10018754.17,-30056262.51,0,-20037508.34&WIDTH=256&HEIGHT=256

**Comment by wahyualdika** [comment]
http://palapa.cs.unsyiah.ac.id:88/security/permissions/36
and
http://103.41.169.65/geoserver/wms?request=GetLegendGraphic&format=image/png&WIDTH=20&HEIGHT=20&LAYER=geonode:jalan_aceh_ln_50k&legend_options=fontAntiAliasing:true;fontSize:12;forceLabels:on

**Comment by t-book** [comment]
@wahyualdika  I would suggest following:

1) get rid of port 88 and use 80 -> 80
2) fix your ip
````
#  PATH_TO_YOUR_VIRTUALENV = is the path to the geonode virtualenv
source PATH_TO_YOUR_VIRTUALENV/bin/activate

# let´s copy the scripts to /usr/bin to make it systemwide exectuable
sudo cp PATH_TO_YOUR_VIRTUALENV/package/support/geonode.binary /usr/bin/geonode
sudo cp PATH_TO_YOUR_VIRTUALENV/package/support/geonode.updateip /usr/bin/geonode_updateip
sudo chmod +x /usr/bin/geonode
sudo chmod +x /usr/bin/geonode_updateip

# set env vars. make sure to set correct settings name and correct path to your gn project
DJANGO_SETTINGS_MODULE=geonode.local_settings 
GEONODE_ETC=/home/PATH_TO/geonode/geonode 
GEOSERVER_DATA_DIR=/var/lib/tomcat8/webapps/geoserver/data 

# now run updateip
geonode_updateip -p http://palapa.cs.unsyiah.ac.id
````

3)
run updatelayers: http://docs.geonode.org/en/master/tutorials/admin/admin_mgmt_commands/#updatelayers
Don´t forget to enable your virutalenv and if needed pass in correct settings file like local_settings.

**Comment by wahyualdika** [comment]
thank you, changing the port from 88 to 80 works for me, but i will try your 2nd suggestion too.
if i may ask, can help me with geonode not zoom in to layer when on layer detail page, i've tried solution in #3700 and #3684 but they're not working for me. is there any solution, or should i upgrade geonode?

**Comment by t-book** [comment]
Hi, this should already be fixed in 2.8 branch at github. so either you pull from there or yes upgrade to 2.10 rc4 which is currently in master. make sure to make a snapshot before in case something goes wrong.

**Comment by wahyualdika** [comment]
ok thanks for the help @t-book

**Comment by t-book** [comment]
@wahyualdika your´re welcome. In case this is finished would you close the issue? Thanks!
