### ISSUE TITLE
Transifex Maintainer

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4097]
According to the [documentation](http://docs.geonode.org/en/latest/organizational/contribute/contribute_to_translation.html?highlight=translate) there are two different ways to contribute to geonodes localization:

1. Transifex
2. local translation and github PR 

for the Transifex way there must be a Transifex maintainer to pull the translation from Transifex into the GeoNode GitHub project (see #920). Accoring to the latest gitter chat it is not clear who this is and how to get the Transifex translations into your local GeoNode.

I would like this to get clearified.

**Comment by capooti** [comment]
I believe it is currently based on a manual procedure: if using Transifex download the translation file and submit it as a PR

**Comment by t-book** [comment]
@capooti Unfortunately I don´t think it´s that easy. I´ve just did a quick diff: French Version at github against French from Transifex. It shows that github version is ahead. (F.e. Github has trans for str Owner). Same with english, github is ahead (f.e.: 'List of keywords from Thesauri'). It would be good to know if this is always the case or if transifex has newer versions for some files.

**Comment by capooti** [comment]
Maybe a tx push is needed in that case?

Here is the workflow, didn't test it from years:
http://docs.geonode.org/en/master/organizational/contribute/contribute_to_translation.html

**Comment by t-book** [comment]
Thanks for sharing! Haven´t seen this yet.

**Comment by t-book** [comment]
@capooti  Finally I´ve had a look at Transifex. Your´re right I think a tx pull/push should help. But one needs admin privilegs. Do you have permissions to do it or know who we can ask?

@gannebamm What do you think if we do half half with the german translation?
 
`year === 2019 ? 'time to kill bugs' : '💤'`

**Comment by gannebamm** [comment]
Hi Toni
That's very much appreciated :)

Am Mi., 9. Jan. 2019, 15:54 hat Toni <notifications@github.com> geschrieben:

**Comment by t-book** [comment]
@gannebamm great! I´ll try to check out which way to go. 

A) if it´s better to stay with transifex or 
B) share some repository where we both can push our changes to to. 
(After that we could import it in Transifex and PR to master branch)

**Comment by capooti** [comment]
@t-book currently these are the Transifex maintainers:
@kalxas @ingenieroariel @vdeparday @capooti @collaer @ortelius 
I just added you as well in the list.

**Comment by t-book** [comment]
Thanks a lot Paolo,
– Translations are a treasure!

**Comment by t-book** [comment]
@gannebamm ref: https://github.com/GeoNode/geonode/issues/3203
I´ve started  reviewing the german po file. Will soon send you the second half ;)

**Comment by gannebamm** [comment]
@t-book 
Ok, this sounds good. I have only used transifex, so a little how-to hint would be very much appriciated (just send me some links to get me started :D)

**Comment by t-book** [comment]
@gannebamm Find here the german translation files:
https://github.com/csgis/geonode_german_trans 

**This is what happend**
- updated language files in master branch `django-admin makemessages -l de`
- removed obsolete translations `#~ ...`
- translated/checked django.po until line https://github.com/csgis/geonode_german_trans/blob/master/django.po#L3991
- translated/checked fully https://github.com/csgis/geonode_german_trans/blob/master/djangojs.po (I´ve ignored the starting monitoring part as this seems to be more clear in english)

**Your part**
- Add your name / email to the head section
- Continue in django.po after L3991, feel free to rework the lines before if you´d like to.
- Either edit the files with your Editor (this is what I did) or use poedit as Alessio explained in #3203 
- In case you´re editing the files without poedit check the Django docs for correct format. For example the correct use of multiline string: https://docs.djangoproject.com/en/2.1/topics/i18n/translation/#comments-for-translators-in-templates

**Steps after your done**
- we have to compile the mo files from *. po. This can be done easily by poedit or how I normally do by https://docs.djangoproject.com/en/2.1/ref/django-admin/#compilemessages
- To test the translations the mo files need to be replaced in it´s corresponding lang folder: https://github.com/GeoNode/geonode/tree/master/geonode/locale/de/LC_MESSAGES 
I haven´t done this for the first part. Means there might still exist some translations with wrong context. I would fix those in a final step 
- After this is done the files should be pushed to upstream master. (either you or me)
- Further the files should be synced with Transifex which will be the last step (I can take care of)

In case of questions drop me a line by email or we can continue discussion at the new repository (You have already permission to push to it.)

**Comment by t-book** [comment]
@gannebamm ➿➿👻➿➿ Any news regarding the second part of german trans? If you´re busy I can try to go through the rest as well ✊.

**Comment by gannebamm** [comment]
Hi there. I am currently busy with other tasks but had a quick look at your
impressive work. I you have a deadline for the translation than go ahead.
If you can wait for a couple of weeks more, I'll finish it.

Am Di., 12. Feb. 2019, 15:56 hat Toni <notifications@github.com>
geschrieben:

**Comment by t-book** [comment]
@gannebamm No worries. And no pressure ;)

**Comment by gannebamm** [comment]
@t-book https://github.com/csgis/geonode_german_trans/pull/1

Ready to merge and test

**Comment by t-book** [comment]
@gannebamm thanks!  😃 will do some live testing and push to transifex.

**Comment by t-book** [comment]
@gannebamm Just pushed german *.po to transifex.  It should work to continue there for future changes. Might be needed to sync all other languages as well. Will check when there is time (next holidays :)

**Comment by frafra** [comment]
Transifex became proprietary few years ago. If it is not too late to evaluate alternatives, I would propose Zanata: http://zanata.org/

**Comment by t-book** [comment]
@frafra nice one. Thanks!
