### ISSUE TITLE
[Remote Services] Add the possibility of filtering the list of resources

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4106]
When harvesting resources associated to a Remote Service, we just get a long list of layers.
Even though the list is paginated, with hundreds of layers it is difficult to find the resources we need (see the example below)

![image](https://user-images.githubusercontent.com/1278021/53032579-63175b00-346f-11e9-997d-a3de5ea6f8f9.png)

It would be nice to have at least a filter search box providing a simple plain text match on title and abstract in order to refine the list of resources shown on the page.

**Comment by t-book** [comment]
+1
