### ISSUE TITLE
Geonode docker installation problem

### ISSUE THREAD

**Issue by tayyabsayyad** [GeoNode/geonode#4116]
Using Docker Compose I am getting following error message for the Geonode, I have configured the public address in the file docker-compose.override.localhost.yml and docker-compose-geoserver-server.yml

There was a problem loading this page

Please contact your GeoNode administrator (he may have received an email automatically if he configured it properly). If you are the site administrator, enable debug mode to see the actual error and fix it or file an issue in GeoNode's issue tracker

The URL shown is http://-IP-Address-/proxy/?url=http://geoserver:8080/geoserver/

Is something wrong?

**Comment by afabiani** [comment]
Nope, this is the default from settings.py (or local_settings.py)

You should be able to change this by updating the GEOSERVER_PUBLIC_LOCATION variable.

**Comment by tayyabsayyad** [comment]
Thanks a lot
