### ISSUE TITLE
GeoNode 2.8 Upload of Shp Layer failing – GeoServer Error: CoordinateArraySequenceFactory

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4120]
#### Expected behavior
Successful upload of vector layer (attached)

#### What happens instead 
Upload fails with:

> Unable to usecom.vividsolutions.jts.geom.impl.CoordinateArraySequenceFactory@47999b66 to produce CoordinateSequence with dimension 2

Full trace:  https://gist.github.com/t-book/d42e5c86a0ee7f1554b77fd96f0f6ec2

#### Setup
- Ubuntu 16.04  
- GeoNode 2.8.1 rc0 installed by use of geonode-project
- Full Stack for production
- GeoServer Version: 
  - Implementation-Version: 2.13-SNAPSHOT
  - Build-Timestamp: 2018-10-17T14:26:11Z
- JVM: Oracle Corporation: 1.8.0_191 (OpenJDK 64-Bit Server VM)
- JVM renderin engine: sun.java2d.pisces.PiscesRenderingEngine

[tiger_roads.zip](https://github.com/GeoNode/geonode/files/2675945/tiger_roads.zip)

**Comment by t-book** [comment]
@afabiani I´ve just tested with an older 2.13 release from Mai which is working. So this issue might fit better with GeoServer?

This is working
> Implementation-Version: 2.13-SNAPSHOT
> Build-Timestamp: 2018-05-23T16:52:21Z
> Git-Revision: 934d6bd11928e28c96a8313d37eb94afecf15d29

This does not:
>Implementation-Version: 2.13-SNAPSHOT
> Build-Timestamp: 2018-10-17T14:26:11Z
> Git-Revision: 686c780a08965f06f0ab8a33261feee00ed90f40

**Comment by afabiani** [comment]
Uhm, different GeoServer with same GeoNode you mean?

**Comment by t-book** [comment]
Exactly, I´ve installed latest Geoserver 2.13 which produces error. Than I´ve replaced GS with a 2.13 build from May which works without problems. Same shape file same encoding ;(

**Comment by t-book** [comment]
Did something change between 2.13.1 and 2.13.3 regarding CoordinateArraySequenceFactory or in generell with importer and shp handling?

**Comment by afabiani** [comment]
Maybe the version of the JTS.... need to check.

I'll try to take a look as soon as possible. In the meantime, I think it is safe to use the older one.

**Comment by t-book** [comment]
As always thanks Alessio!

**Comment by t-book** [comment]
I can confirm WindowsCP1258 encoding does not work.

**Comment by capooti** [comment]
WindowsCP1258 was not working in GeoServer 2.13 I think, while now with 2.14 correctly does

**Comment by t-book** [comment]
thanks @capooti But I´m quite sure this issue is not about encoding. From a diff I would guess it´s like Alessio said some version conflict.

**Comment by t-book** [comment]
yep will do tomorrow! Thanks @afabiani

**Comment by t-book** [comment]
Unfortunately the problem still exists, tested on a fresh U16.04 with Geoserver:


> Implementation-Version: 2.13-SNAPSHOT
> Build-Timestamp: 2018-12-19T15:48:32Z
> Project-Version: 2.13-SNAPSHOT
> Iteration-Name: 
> Git-Revision: 515b021cc396aa67e0b9603cd6000326e0a48303
> Created-By: Apache Maven 3.3.9
> Build-Jdk: 1.8.0_66

**Comment by afabiani** [comment]
@t-book unfortunately the issue is related to the importer plugin of GeoServer 2.13.x using the old GeoTools.

We will need to switch to the UPLOADER = geoserver.rest with TIME = False
for the time being.

I'll update the geonode-project settings for 2.8.x accordingly

**Comment by frafra** [comment]
Does this workaround have any drawback?

**Comment by afabiani** [comment]
You won't be able to use timeseries on 2.8

**Comment by t-book** [comment]
@afabiani thanks. By now I´ll just stay with the build from May which works for me.

**Comment by t-book** [comment]
@afabiani 2.8 does not work with GS_2.14 right?

**Comment by afabiani** [comment]
@t-book unfortunately not. I mean it could work, but we should backport some changes to the rest calls from master. This is a bit dangerous because won't be back compatible, and it will force anyone using an older version of GeoServer to perform the update.

**Comment by t-book** [comment]
Then I would say the backport is not of an option. Why not stay with the 2.13 build from around May this year for now? Here everything seems to work? (Haven´t tested timeseries though.)

**Comment by afabiani** [comment]
Because I should find a way to fetch the old JARs from maven repository... not sure they still exist.

I have to figure out if/how this could be possible or manually upload the old WAR to the repo. A bit tricky.

**Comment by t-book** [comment]
I see. If it helps I can offer to publish the old (working) 2.13 war over s3 and update geoserver_url (dev_config.yml) temporarily. This would give some time and ensure users do not run into this error when installing 2.8. Let me know if I can help you with testing.

**Comment by afabiani** [comment]
yes it could help a lot actually, thanks!

**Comment by afabiani** [comment]
@t-book I still suggest to keep using the old upload method with GeoNode 2.8 though, the rest one.

Eventually those are the variable to touch on the docker file

https://github.com/GeoNode/geonode-project/commit/975b43ef72a630fd3f70dabb443a0f83e812b01f

**Comment by t-book** [comment]
@afabiani Is it in this specific case okay to PR directly to 2.8 branch?

**Comment by afabiani** [comment]
@t-book yes, go ahead

**Comment by t-book** [comment]
done.

**Comment by t-book** [comment]
@RamizSami the interim solution is to use the older GeoServer 2.13 build: https://s3.eu-central-1.amazonaws.com/csgis-public/2load/geoserver-2.13.x.war

**Comment by RamizSami** [comment]
Confirming: the geoserver build shared by @t-book worked. Thanks a lot Toni
