### ISSUE TITLE
Issue with "Set up a Genode project"

### ISSUE THREAD

**Issue by dakula009** [GeoNode/geonode#4122]
Hello,

I'm following "https://github.com/GeoNode/geonode-project/tree/master" to create a custom Geonode project.

In the readme.md, I found something confusing that needs some clarification:

There are two sections "Create a custom project" and "Start your server". What's the relationship of them? Are they sequential steps or equivalent (but independent) methods ? The former uses conventional installation, but the latter uses docker. 

I just had a hard time putting the pieces together. 

Any ideas?

Many Thanks!

@afabiani  please kindly provide some insights since I assume the repo belongs to you.

**Comment by t-book** [comment]
@dakula009 Start your server is for docker. Create a custom project is for running geonode-project by use of django dev server. So either use the one or the user.

**Comment by t-book** [comment]
@francbartoli I think we can close this due to inactivity?
