### ISSUE TITLE
GeoFence cache seems to be refreshed every time a layer is uploaded

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4125]
GeoFence cache seems to be refreshed every time a layer is uploaded.
This slows down the upload of a layer in our case, with thousands of layers. If I do import the layer with GS importer, logged as the GeoServer admin, it takes just a few seconds.
If I upload it with GeoNode it takes up to 3 minutes.
Is there anything which can be done to mitigate this?

**Comment by afabiani** [comment]
The PR https://github.com/GeoNode/geonode/pull/4326 should fix the issue.

**Comment by capooti** [comment]
@afabiani it seems now faster (a layer is uploaded in one minute). But still slow when compared to previous GeoNode version. One thing I have noticed: the geoserver configuration during a layer upload seems being reloaded: is it possible? That would explain the slowness at this point

**Comment by afabiani** [comment]
@capooti nope as far as I can say. There's no command issuing a GeoServer configuration realod.
I kindly suggest to always use the 'geoserver.importer' upload method though, it is more resilient and efficient.

About the slowness, make sure you have enough UWSGI processes and connections available. Remember that now GeoServer asks GeoNode to validate the access tokens. If all the uwsgi processes are busy, it will have to wait the "harakiri" to free new ones.

**Comment by afabiani** [comment]
@capooti you were right. I have found an unattended catalog.reload() while uploading a layer.
By removing that instruction the upload time has been significantly reduced.

**Comment by capooti** [comment]
yes, @afabiani , it is much much faster now, thanks for fixing that!
