### ISSUE TITLE
Are PPA packages supported?

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4142]
Installing GeoNode from PPA is the suggested way to proceed, according to GeoNode webpage and from the quick install page in the documentation.

GeoNode PPAs are outdated and many contributors consider them not supported: https://github.com/GeoNode/geonode/issues/3925#issuecomment-448297351

Should the homepage and the documentation be updated?

**Comment by t-book** [comment]
@frafra Yes it should! This was bespoken often already but unfortunately nobody found time by now. I would try to spent some work getting into the apt build process  (Have asked for guidance at dev list this morning ;) I still think apt is an important install method for a lot of users...

**Comment by afabiani** [comment]
Yes, documentation needs some love!

**Comment by t-book** [comment]
From https://docs.google.com/document/d/1HRpllXtbQyzC81ExtrEQ3AqRL_29O6lPF4rwGSz7QIw/edit

> PPA (future snapcraft https://snapcraft.io/first-snap)
