### ISSUE TITLE
Issue with EPSG:3035

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4146]
I cannot use this layer with has a EPSG:3035 projection: http://geodata.nina.no/static/internal/frank.tar.xz
I am using default setting with GeoNode 2.8 on Ubuntu (via PPA at the moment).

**Comment by francbartoli** [comment]
@frafra is this a duplicate of #4140?

**Comment by frafra** [comment]
@francbartoli I would not consider it a duplicate because the same layer with a different projection work as expected (even if it raises some errors). That is why I think there is an issue specifically linked to the usage of this projection.
