### ISSUE TITLE
Thumbnails and legend icons not being loaded

### ISSUE THREAD

**Issue by RamizSami** [GeoNode/geonode#4147]
The URL of legend icons are not working on layer details page. Like you can see in the image below:
![image](https://user-images.githubusercontent.com/15404125/50540161-9dbaf080-0bae-11e9-85ba-446aad60dda1.png)

Same is the case with thumbnail on layers listing page. The thumbnail is not loading like in the image below:
![image](https://user-images.githubusercontent.com/15404125/50540180-d65aca00-0bae-11e9-8d88-6b515bbb244d.png)

The issue in both the cases is that it produces right URL but skips the port (8080) for Geoserver due to which I end up getting error 404. I have changed the GEOSERVER_PUBLIC_PORT variable in local_settings.py to 8080 and have verified that the GEOSERVER_PUBLIC_LOCATION varibale has correct value but it still skips 8080 in that part. Can anyone please tell me where I am going wrong? I couldn't find a clue in the documentation.

**Comment by t-book** [comment]
I think we just solved this issue (see dev list) by making sure oauth is setup correctly further uploaded directory is readable for www-data. Would you kindly close this issue @RamizSami ?

**Comment by RamizSami** [comment]
Thanks @t-book 
Here is the thread: https://lists.osgeo.org/pipermail/geonode-devel/2018-December/002515.html
