### ISSUE TITLE
500 Internal Server Error- Map

### ISSUE THREAD

**Issue by ozgurozc** [GeoNode/geonode#4149]
I had installed GEONODE in docker on Ubuntu 16.4.5 server

When I try to create map from geocode, geoserver is popping up an error.
[error.txt](https://github.com/GeoNode/geonode/files/2724059/error.txt)
![ekran resmi 2019-01-03 17 27 02](https://user-images.githubusercontent.com/2607004/50642648-df67e480-0f7c-11e9-87e5-a04dd937cf2a.png)

I had  lots of issues on installing in Proxmox virtual machine in docker finally this error.

Any help is highly appreciated.

Regards,

Ozgur

**Comment by afabiani** [comment]
Is your GeoServer available @ http://127.0.0.1:80/geoserver as indicated from the request?

**Comment by ozgurozc** [comment]
Hello Alessio, 
Thanks for reply, yes it is located on the http://127.0.0.1:80 (localhost)
I am not IT guy, but I am evaluating this 
Actually, when I click on create a new map on geonode please seem my notes and screenhots

This is the error:






This is where geoserver located



Below is my docker-compose.overide.localhost.yml

  GNU nano 2.5.3                                      File: docker-compose.override.localhost.yml                                                                                    

version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - GEONODE_LB_HOST_IP=127.0.0.1
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost:80
      - ALLOWED_HOSTS=['localhost','10.0.0.197','mcgeo','map.mehmetozcan.com.tr' ]
      - GEOSERVER_PUBLIC_LOCATION=http://map.mehmetozcan.com.tr/geoserver/

  celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - GEONODE_LB_HOST_IP=127.0.0.1
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost:80
      - ALLOWED_HOSTS=['localhost','10.0.0.197','mcgeo','map.mehmetozcan.com.tr' ]
      - GEOSERVER_PUBLIC_LOCATION=http://map.mehmetozcan.com.tr/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - NGINX_BASE_URL=http://localhost:80

Kind Regards,

Ozgur Ozcan

**Comment by ozgurozc** [comment]
One more thing it seems like geonode/geoserver_data:2.14.x not working may be related with my problem.

  gsconf4geonode	stopped	geonode	geonode/geoserver_data:2.14.x

**Comment by ozgurozc** [comment]
This may show my complete setup, but one stopped service of geonode. I am trying to restart it but it is stopping again.

**Comment by t-book** [comment]
@ozgurozc did you found a solution ? If not this is docker, right? If so please try to log into your django container and test if geoserver is responding  at http://127.0.0.1:80/gs/ f.e. with curl.
