### ISSUE TITLE
No theme settings for Genode installed via quick installation

### ISSUE THREAD

**Issue by dakula009** [GeoNode/geonode#4152]
After installing Geonode from quick installer ( in Ubuntu ), I noticed that there is no "Theme" settings available in the "Admin" panel. 

The "Theme" option was available in "Admin" when I was using Genode installed via standard installation. It was a very handy feature as I could customize the theme easily. 

Is there a way to activate the theme settings? If not, how can I configure the themes? 

Thanks!

**Comment by afabiani** [comment]
Did you installed via "apt-get" command?

**Comment by dakula009** [comment]
Yes. Any thoughts?

**Comment by afabiani** [comment]
Sure, the apt is based on an old version of GeoNode. Deb packages are not yet updated, so themes are not included there yet.
