### ISSUE TITLE
GeoLite Legacy db discontinued so paver setup fails in Geonode 2.8 dev install

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4153]
Maxmind has [discontinued](https://blog.maxmind.com/2018/01/02/discontinuation-of-the-geolite-legacy-databases/) GeoLite Legacy database support as of Jan 2nd 2019. 

That causes `paver setup` to fail when installing Geonode 2.8 dev in [Finalize GeoNode Setup & Test](http://docs.geonode.org/en/master/tutorials/install_and_admin/geonode_install/create_geonode_db.html#finalize-geonode-setup-test).

This is because updategeoip.py [expects](https://github.com/GeoNode/geonode/blob/master/geonode/base/management/commands/updategeoip.py#L34) to use geoip2 to handle the new GeoLite2 database, but geoip2 is only available from Django 1.9, not in Django 1.8 as used by Geonode 2.8.

**Comment by afabiani** [comment]
Hi, thanks for reporting this.
For the time being, I'll look for disabling such requirement by default, hence it should be required by the "monitoring" contrib module only.

Will provide more details as soon as I have been digging a bit more into the issue.

**Comment by t-book** [comment]
In between –untested– but find here a dat from last year which could at least help to finish the setup: https://csgis.de/2load/GeoLiteCity.dat.gz

**Comment by afabiani** [comment]
@jondoig @t-book please take a look at

https://github.com/GeoNode/geonode/pull/4154

**Comment by t-book** [comment]
@afabiani Great, should work. I have to do an 2.8 install next week and can test it. thanks!

**Comment by t-book** [comment]
@afabiani Just tested it in production. Works without problems. I think you can close this?
