### ISSUE TITLE
Layer Download "Filter by Attributes" Failed

### ISSUE THREAD

**Issue by dakula009** [GeoNode/geonode#4162]
Hello, 

when downloading a layer, I was trying to use the "filter by attributes" feature. However, the download filter did not work properly, it did not return any attribute values in the list (in fact the list was not created at all). I found an exactly the same issue from here: GeoNode/geonode#3609. Has it been addressed yet? If not, is there a workaround for it? I'm using GeoNode 2.8 installed via sudo apt-get install geonode. 

Thanks!
![image](https://user-images.githubusercontent.com/45241071/51337448-0245ce80-1a3c-11e9-8883-385e7fa3895b.png)

**Comment by t-book** [comment]
Hi @dakula009 I´ve just tested it with 2.8 rc0 installed by source. A shapefile download is filtered correctly there. Please note apt setup is currently not maintained.

**Comment by t-book** [comment]
@dakula009 If you´re familiar with docker: Docker. As alternative installing from source. Personally I´m using these ansible playbooks which automate all staps and following the docs: https://github.com/csgis/geonode_ansible
