### ISSUE TITLE
Security settings in geonode 2.8 : unable to upload inspite of permission

### ISSUE THREAD

**Issue by jitendrashahiitb** [GeoNode/geonode#4167]
unable to load a shapefile in geonode (2.8) from a remote machine in spite of permissions to upload layer 

Following ( http://docs.geonode.org/en/master/tutorials/admin/geoserver_geonode_security/index.html#geoserver-geonode-aa) is not clear.

"In order to do this, you must be sure that GeoNode knows the internal admin user and password of GeoServer.

Warning

This must be an internal GeoServer user with admin rights, not a GeoNode one.

Make sure the credentials are correctly configured into the file settings.py"

**Comment by t-book** [comment]
https://github.com/GeoNode/geonode/blob/master/geonode/local_settings.py.geoserver.sample#L127
?
