### ISSUE TITLE
No batch download layers option

### ISSUE THREAD

**Issue by dakula009** [GeoNode/geonode#4177]
On the "Explore layers" page, I noticed there is no option for batch downloading layers after multiple layers being selected. 

![image](https://user-images.githubusercontent.com/45241071/51712475-b10d8000-1fe3-11e9-97f5-d77733061076.png)

How could we batch download layers? Our Geonode users have a need for this feature, since downloading hundreds of layers one by one would be impossible.

If there is no such a feature, is there a workaround? 

Thanks!

**Comment by capooti** [comment]
Please use mailing lists for support requests.
You can easily accomplish batch download by writing a script
