### ISSUE TITLE
Unable to create maps with access_token no longer string

### ISSUE THREAD

**Issue by francbartoli** [GeoNode/geonode#4178]
TypeError at /maps/new with exception:
`cannot concatenate 'str' and 'AccessToken' objects`

Affected line [maps/views.py#L968](https://github.com/GeoNode/geonode/blob/bca6408cc5775dd6b86d5f15fdc936e6c91dedb5/geonode/maps/views.py#L968) should be trivially patched

**Comment by capooti** [comment]
These changes have been reverted by another commit, so bug it is still in code
