### ISSUE TITLE
Upgrade docker setup to PostgreSQL 10 (improvement)

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4187]
The current docker-compose uses geonode/postgis 9.6
https://github.com/GeoNode/geonode/blob/77e0fe391322b16f81d62d6b01fa5885e3008b9c/docker-compose.yml#L5
as image. PostgreSQL 10.x is allready in production and widely adopted, afaik. Are there good reasons to not upgrade the docker setup to use PostgreSQL 10.x? And which special settings/ modifications where made to the default PostgreSQL 9.6 for geonode.

I would like to fork, upgrade, test and later PR this enhancement.

**Comment by giohappy** [comment]
From our experience nothing blocks from using PG10. We already adopt it in some deployments along GeoNode.

**Comment by t-book** [comment]
If you install on bionic you end with postgres10 as well. Haven´t run into any problems yet.

+1

**Comment by gannebamm** [comment]
See #4192 and https://github.com/GeoNode/postgis-docker/pull/1

**Comment by francbartoli** [comment]
@gannebamm I guess we can close this via #4192, am I right?

**Comment by gannebamm** [comment]
@francbartoli yes
