### ISSUE TITLE
Invalid Layers. Needs an authoritative SRID in its CRS to be accepted

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4188]
I am getting this error with the attached shapefile. This was working with previous GeoNode versions. I can have a look at this sometime this week. Meanwhile if anyone is able to come with a solution it would be great.

```
Invalid Layers. Needs an authoritative SRID in its CRS to be accepted
Traceback (most recent call last):
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/views.py", line 211, in layer_upload
    metadata_upload_form=form.cleaned_data["metadata_upload_form"])
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/utils.py", line 498, in file_upload
    bbox_x0, bbox_x1, bbox_y0, bbox_y1, srid = get_bbox(filename)
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/utils.py", line 373, in get_bbox
    "Invalid Layers. "
GeoNodeException: Invalid Layers. Needs an authoritative SRID in its CRS to be accepted
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/views.py", line 294, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
```

this is what I see with ogrinfo:

ogrinfo buddhist_sites_1820.shp buddhist_sites_1820 
INFO: Open of `buddhist_sites_1820.shp'
      using driver `ESRI Shapefile' successful.

Layer name: buddhist_sites_1820
Geometry: Point
Feature Count: 2407
Extent: (17321364.719650, 2202946.226194) - (20973149.448628, 5327120.282421)
Layer SRS WKT:
PROJCS["Xian_1980_GK_Zone_19",
    GEOGCS["GCS_Xian_1980",
        DATUM["Xian_1980",
            SPHEROID["Xian_1980",6378140.0,298.257]],
        PRIMEM["Greenwich",0.0],
        UNIT["degree",0.017453292519943295],
        AXIS["Longitude",EAST],
        AXIS["Latitude",NORTH]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["central_meridian",111.0],
    PARAMETER["latitude_of_origin",0.0],
    PARAMETER["scale_factor",1.0],
    PARAMETER["false_easting",19500000.0],
    PARAMETER["false_northing",0.0],
    UNIT["m",1.0],
    AXIS["x",EAST],
    AXIS["y",NORTH]]

[buddhist_sites_1820.zip](https://github.com/GeoNode/geonode/files/2804877/buddhist_sites_1820.zip)

**Comment by giohappy** [comment]
Probably this commit fixed something for the author but broke something else:  https://github.com/GeoNode/geonode/commit/1e854d4b674f59298f9a715ae6af34685fee8818
We definetely need more test coverage...

**Comment by capooti** [comment]
@giohappy that code looks correct to me, and I think it was there since a long time.
In my case (using the shapefile attached) if I use the GeoServer importer srid is succesfully recognized (EPSG:2333) and shapefile imported. But If I use the REST uploader GDAL doesn't recognize the srid. Now I am not sure why this happens, but in any case the message I get from the uploader is confusing and not related to SRS:

```
AttributeError at /layers/upload 'NoneType' object has no attribute 'charset' Request Method: POST Request URL: http://localhost:8000/layers/upload Django Version: 1.11.16 Python Executable
....
```

**Comment by olljal** [comment]
We are running master branch version of GeoNode and had this same issue with these files:
[Finland_marine_simple.zip](https://github.com/GeoNode/geonode/files/3032627/Finland_marine_simple.zip)

ogrinfo output:
```
INFO: Open of `Finland_marine_simple.shp'
      using driver `ESRI Shapefile' successful.

Layer name: Finland_marine_simple
Metadata:
  DBF_DATE_LAST_UPDATE=2019-03-27
Geometry: Polygon
Feature Count: 1
Extent: (61685.886000, 6605839.312000) - (543671.012800, 7302207.778800)
Layer SRS WKT:
PROJCS["EUREF_FIN_TM35FIN",
    GEOGCS["GCS_EUREF_FIN",
        DATUM["European_Terrestrial_Reference_System_1989",
            SPHEROID["GRS_1980",6378137.0,298.257222101]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["False_Easting",500000.0],
    PARAMETER["False_Northing",0.0],
    PARAMETER["Central_Meridian",27.0],
    PARAMETER["Scale_Factor",0.9996],
    PARAMETER["Latitude_Of_Origin",0.0],
    UNIT["Meter",1.0]]
Area: Real (19.11)
Extent: String (50.0)
OGRFeature(Finland_marine_simple):0
  Area (Real) = 53772.73543950000
  Extent (String) = Finland's marine areas
  MULTIPOLYGON (((224146.6365 ...
```

Changing the coordinate system fixes the problem but it would be nice if GeoNode could do this automatically.
