### ISSUE TITLE
Anyone Permission Stores as an empty string in GeoFence instead of '*'

### ISSUE THREAD

**Issue by khaledboka** [GeoNode/geonode#4189]
Hello, 
I tried to upload a shape file as a normal user, the permissions were set to any one however the layer doesn't appear 
![screenshot from 2019-01-29 10-14-53](https://user-images.githubusercontent.com/13452248/51894483-8ab75e00-23b0-11e9-8250-6f23738922e6.png)

Noticed that GeoFence rules table doesn't have * at the user column, instead it shows empty

![screenshot from 2019-01-29 10-15-29](https://user-images.githubusercontent.com/13452248/51894297-01079080-23b0-11e9-9b12-1632bc30561d.png)

**Comment by khaledboka** [comment]
Maybe a solution 
https://github.com/GeoNode/geonode/pull/4190

**Comment by t-book** [comment]
@khaledboka Which branch?

**Comment by khaledboka** [comment]
Branch 2.8.x

**Comment by t-book** [comment]
this has been fixed on master. unsure if this is already backported. If not any chance to upgrade to master?

**Comment by khaledboka** [comment]
Unfortunately It seems it does not work on 2.8.x latest commit, Would you please send me the fix commit number ? @t-book @afabiani
