### ISSUE TITLE
improving GeoNode upload when EPSG:4326 layer exceeds bounding box

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#4196]
May be related to #2378.

Issue came up when several layers with EPSG:4326 failed to upload due to bounding box exceeding [-180 -90 180 90].  This is the line in the upload.py file that deals this part of importlayers: https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/upload.py#L188

One of the layers was just over exceeding the limits with -180.0000006

I got around this by modifying an import python script run before import layers and clipping the layers with the following ogr2ogr command:
```
ogr2ogr -t_srs "EPSG:4326" -clipsrc -180 -90 180 90 ../new/$NAME $f
```

Are there any improvements to the code to make importlayers more robust? Such as:
1) importing a layer with EPSG:4326 even if it exceeds the bounds?
2) calling an ogr2ogr clip command inside the upload.py script if it exceeds the bounds?

**Comment by t-book** [comment]
@d3netxer As far as I remember this has been fixed some time ago. Is it possible for you to test this again with latest master?
