### ISSUE TITLE
Docs fail to build

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4204]
Since some time docs fail to build. 
See: https://github.com/GeoNode/geonode/pull/4148

To double check it wasn´t my own PR I´ve build the docs on my RTD account:
https://geonode-test-docs.readthedocs.io/en/latest/tutorials/install_and_admin/quick_install.html
which worked without problems.

@capooti  You´re listed as a manager at https://readthedocs.org/projects/geonode/ could you have a look at the logs and try to trigger a manual build? As alternative if you´re busy –and it´s okay for others– you could add me to managers and I will put it on my list).

cheers,
– t.

**Comment by capooti** [comment]
Done and activate the build, let's see if works well.
I can add you as a manager as well, which is your RTD username?
@afabiani I added you as well

**Comment by t-book** [comment]
@capooti Thanks Paolo! The latest build did work now!
My profile is: toni_schoenbuchner

**Comment by capooti** [comment]
@t-book just added you. I think to be sure we need to see what happens after a push

**Comment by t-book** [comment]
@capooti I´ll udate a part of the docs soon and will keep an eye on it.

**Comment by t-book** [comment]
@capooti I think we should remove v. 1.2 and 2.0 from RTD. Those end in 404 anyway.
