### ISSUE TITLE
Proxy base url: suffix "geoserver/" is missing

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4206]
spcgeonode sets the GeoServer proxy base url using `$BASEURL`, which relies on `$HTTP_HOST` (see `docker-entrypoint.sh`. It seems to me that `geoserver/` is missing.

**Comment by t-book** [comment]
If it´s spc maybe the ticket should be opened here? https://github.com/olivierdalang/SPCgeonode

**Comment by frafra** [comment]
I opened the tick here because spcgeonode has been merged in this main geonode repository: https://github.com/GeoNode/geonode/tree/master/scripts/spcgeonode

The old spcgeonode repository does not seem to be updated, while the one available here has been modified recently.

**Comment by giohappy** [comment]
The proxy base URL for Geoserver should be /gs. See https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L758

**Comment by t-book** [comment]
@frafra you´re right! thanks for clarification :)

**Comment by frafra** [comment]
> 
> 
> The proxy base URL for Geoserver should be /gs. See https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L758

```
]$ grep -r GEOSERVER_PUBLIC_LOCATION scripts
scripts/spcgeonode/django/docker-entrypoint.sh:export GEOSERVER_PUBLIC_LOCATION="${SITEURL}/geoserver/"
scripts/docker/env/production/django.env:GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
scripts/docker/env/production/celery.env:GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
```

It would be nice to use the same proxy base URL for both standard and Docker setups.

**Comment by giohappy** [comment]
I think they should be aligned. It changed [recently ](https://github.com/GeoNode/geonode/commit/cf1b78c4daaa23fe99b1c9ce869ffa691b2752c1#diff-244cdfc4e5e50d8ee9386be986629b6a )and both geonode-project and docker should be updated accordingly.
