### ISSUE TITLE
Proxy base URL suffix for Docker is 'geoserver' instead of 'gs'

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4207]
It seems to me that using `/gs/` would be a better default, in order to keep the Docker setups more similar to the standard ones. It also raises some compatibility reasons, because I can see some hardcoded references to `/gs/` in various part of this repository (`MapLoom-*.js` for example).

Related discussion: https://github.com/GeoNode/geonode/issues/4206#issuecomment-460669614

**Comment by giohappy** [comment]
I agree. The proxy base url should be updated wherever it's refernced (also in geonode-project).
The recent change is meant to make all requests pass thoruhg the GeoNode internal proxy in order to support Basic Auth, Bearer token and session based authentication.

**Comment by gannebamm** [comment]
I can not express how much I like this kind of refactoring. +100

**Comment by frafra** [comment]
Ok, I understood that the `/gs` suffix is just for external URLs, while for internal connection `/geoserver` has to be used.

```
$ grep -r 'localhost:8080/geoserver/' geonode | wc -l
20
```
