### ISSUE TITLE
GeoServer Docker: security warnings

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4212]
```
Please read the file security/masterpw.info and remove it afterwards. This file is a security risk.
The default user/group service should use digest password encoding. 
```

I am unable to find `security/masterpw.info` in new deployments (so this is an issue only when migrating non-Docker installations) , while password encoding should not be an issue if the password between geonode and geoserver is randomized.

**Comment by t-book** [comment]
@frafra I only know this message on regular vanilla geoserver instances. Never seen it in geonode/geoserver. Unfortunately I cannot follow you, can you say in which context the warning appeared? When migrating a vanilla geoserver data dir to geonode/geoserver?

**Comment by frafra** [comment]
@t-book I investigated a little bit. It happens with the Docker images, but only if you migrated the data from a Ubuntu PPA setup. The geoserver Docker image could be improved in order to maintain persistence for the data-only (not for configuration files or code for example), thus solving this minor issue.

Probably linked with https://github.com/GeoNode/geonode/issues/4244

**Comment by t-book** [comment]
@frafra thanks for clarifications. If I understand correctly this should only happen when somebody who run previously on apt setup missed to delete masterpw.info. In other words the user should have been presented with this warning at his previous setup as well. I´m unsure if this is really an issue with docker and/or geonode or more an issue with some careless user?

**Comment by frafra** [comment]
@t-book You are right. Even if I think this tiny issue highlights something more interesting, I think we can close this bug. Thank you :-)
