### ISSUE TITLE
Using the SPC Geonode in Windows

### ISSUE THREAD

**Issue by pjduplooy** [GeoNode/geonode#4214]
Hi guys

I am trying to run the SPC Geonode (under scripts/spcgeonode) in Windows, but am getting the following error:

Connection pool is full, discarding connection: 192.168.99.100.

And then I cannot use geonode at all. (using 127.0.0.1 or 192.168.99.100)

I am using the development method (have not changed anything in .env) using docker-compose up --build -d

Any help would be appreciated.

**Comment by francbartoli** [comment]
@pjduplooy I guess you are using docker-machine as far as I understand from the ip address used. In that case I think you have to replace the value `127.0.0.1` [here](https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/.env#L21) with that ip.

**Comment by francbartoli** [comment]
@pjduplooy did you solve? Can we close this?
