### ISSUE TITLE
Sometimes NGINX fails to connect to GeoNode

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4230]
I run many tests during the last couple of days, and I have seen that sometimes NGINX seems unable to connect to GeoNode. It looks to me that there is a ~10 % change that this could happen.

I am using SPC GeoNode. This is what NGINX says:

```
2019/02/14 16:29:27 [error] 15#15: *50 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: 127.0.0.1, request: "GET / HTTP/1.1", upstream: uwsgi://172.20.0.2:8000", host: "127.0.0.1"
```

I do not have the GeoNode logs at the moment (the testing system just restarted everything and it worked just fine, but I didn't had the time to have a look at the logs.

**Comment by t-book** [comment]
@frafra my first guess would be it´s something with permissions and the owner of the socket. But this needs surely more investigations. Unfortunately I could not replicate the issue yet.

**Comment by frafra** [comment]
Thank for your guess @t-book, I will try to investigate more and keep the logs.

**Comment by t-book** [comment]
@frafra it would be interesting if this happens more often under load. maybe some jmeter benchmark could also shed some light into.

**Comment by frafra** [comment]
I don't know if that is related, but while looking on the logs of Postgres I found a possible issue with the configuration of uwsgi: https://serverfault.com/questions/746799/postgresql-error-could-not-receive-data-from-client-connection-reset-by-peer

**Comment by francbartoli** [comment]
@frafra I've seen this kind of error in the past from the main docker composition. If I can recall they were fixed by these lines [https://github.com/GeoNode/nginx-docker/blob/geoserver/nginx.conf#L78-L82](https://github.com/GeoNode/nginx-docker/blob/geoserver/nginx.conf#L78-L82)

**Comment by t-book** [comment]
@francbartoli this would definitly make sense ...

**Comment by capooti** [comment]
yes that will do the trick! thanks @francbartoli
