### ISSUE TITLE
requirements.txt automatic checks

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4239]
I suggest to use one of the following services to look for outdated/insecure libraries and automatically create pull requests, so Travis can automatically execute the tests:
- https://dependabot.com/
- https://pyup.io
- https://requires.io

**Comment by frafra** [comment]
Here is the current situation: https://requires.io/github/frafra/geonode/requirements/?branch=master

**Comment by afabiani** [comment]
interesting
