### ISSUE TITLE
Vanilla Geoserver

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4244]
https://github.com/GeoNode/geonode/blob/19dcacf10a4d929d0c67f2a2aab21c682096abc0/scripts/spcgeonode/geoserver/Dockerfile#L12

**Comment by GeoTob** [comment]
Just noting I am running Geonode against a vanilla geoserver (2.15.1) on tomcat:9 + some official extensions + parts of the geonode-geoserver extension:

```
RUN wget --no-check-certificate -O geoserver-2.15.1-geonode.zip https://build.geo-solutions.it/geonode/geoserver/latest/geonode-geoserver-ext-web-app-2.15.1-geoserver-plugin.zip \
    && unzip geoserver-2.15.1-geonode.zip "geonode-*.jar" "core-renderer-*.jar" "tagsoup-*.jar" -d WEB-INF/lib/ \
    && rm geoserver-2.15.1-geonode.zip
```

The other jars above are the dependencies for printng only, I haven't really gotten around to trying the rest yet. This might help you
