### ISSUE TITLE
master.demo.geonode.org geoserver down

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4253]
The [WFS service](http://master.demo.geonode.org/geoserver/ows?service=WFS&version=1.1.0&request=GetCapabilities "GetCapabilities request") does not respond.

 my just-uploaded layer [TM_WORLD_BORDERS_SIMPL_0_3](http://master.demo.geonode.org/layers/geonode:TM_WORLD_BORDERS_SIMPL_0_3)
says "Geonode is in maintenance mode. We'll be back shortly."

Maybe I brought it down by editing metadata on the layer. I added a few labels for attributes and set the Categories to Boundaries. Instead of saving the metadata it gave a "maintenance mode" error message.

**Comment by t-book** [comment]
> Maybe I brought it down by editing metadata on the layer.

I don´t think so have seen this several time before ;) I remember darkly Alessio once said this instance is a bit outdated which might be connected to this issue.

**Comment by t-book** [comment]
I´m closing this issue as http://master.demo.geonode.org/geoserver/ows?service=WFS&version=1.1.0&request=GetCapabilities is back online again.

**Comment by giohappy** [comment]
If you test this on weekend you might be in the time window when the instance is teared down to wipe data.
