### ISSUE TITLE
New variable to load Gravatar over https or set https as standard

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4268]
When running over https://  one will get a mixed content warning as gravatars are loaded over http.
The easiest fix I have found so war is by setting 

`AVATAR_GRAVATAR_SSL = True`

in settings.

Hence I´d like to suggest introducing AVATAR_GRAVATAR_SSL as new settings var. If devs do not want to further spoil settings.py (It´s already blown up) I would suggest to just mention it at documentation.

**Comment by frafra** [comment]
Hi! Why not to load them on SSL by default? It shouldn't be an issue even if GeoNode is served over HTTP.

**Comment by t-book** [comment]
@frafra right mixed content is a SSL error. In other words https served content on a http website is no problem.  (There might be a **insignificant** slower speed due to an initial handshake.)

Just saw geonode uses a fork. Http currently is standard:
https://github.com/GeoNode/geonode-avatar/blob/45f33be4e623d0e7a2b31a83eb68af48dfbb959b/avatar/templatetags/avatar_tags.py#L30

+1 for changing  this standard to https.

_(With all this privacy policy changes I would even welcome to make AVATAR optional as we already do with other social media stuff. https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L981)_

**Comment by frafra** [comment]
Loading an image from another server without using Javascript code should not be a privacy issue, at least from a GDPR perspective (no cookies are involved).

**Comment by t-book** [comment]
> at least from a GDPR perspective 

I see differently. Automattic will collect information through gravatar which should be transparent for a user and hence at least mentioned at your privacy policy .
https://automattic.com/privacy/#information-we-collect-automatically

But this is definitely another issue ;)

**Comment by t-book** [comment]
I will mention the settings in docs.
