### ISSUE TITLE
Invalid model identifier: 'base.menuplaceholder'

### ISSUE THREAD

**Issue by csfuente** [GeoNode/geonode#4269]
Hi!
When I do the tutorial from Alessio Fabiani [1] to install geonode-2.10rc4 with Docker in ubuntu18.04 I found the following error when the containers are running.

> django4geonode   | Traceback (most recent call last):
> django4geonode   |   File "/usr/local/bin/django-admin.py", line 5, in <module>
> django4geonode   |     management.execute_from_command_line()
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
> django4geonode   |     utility.execute()
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
> django4geonode   |     self.fetch_command(subcommand).run_from_argv(self.argv)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
> django4geonode   |     self.execute(*args, **cmd_options)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
> django4geonode   |     output = self.handle(*args, **options)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/modeltranslation/management/commands/loaddata.py", line 61, in handle
> django4geonode   |     return super(Command, self).handle(*fixture_labels, **options)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 69, in handle
> django4geonode   |     self.loaddata(fixture_labels)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 109, in loaddata
> django4geonode   |     self.load_label(fixture_label)
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 166, in load_label
> django4geonode   |     for obj in objects:
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 88, in Deserializer
> django4geonode   |     six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/serializers/json.py", line 82, in Deserializer
> django4geonode   |     for obj in PythonDeserializer(objects, **options):
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 99, in Deserializer
> django4geonode   |     Model = _get_model(d["model"])
> django4geonode   |   File "/usr/local/lib/python2.7/site-packages/django/core/serializers/python.py", line 194, in _get_model
> django4geonode   |     raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
> django4geonode   | django.core.serializers.base.DeserializationError: Problem installing fixture '/usr/src/app/geonode/base/fixtures/initial_data.json': Invalid model identifier: 'base.menuplaceholder'

Is there a problem with the docker-compose that is in master that impels me to run correctly geonode?

ty

[1] https://docs.google.com/document/d/1S0ac9IR9IW9tUjMu7JETPLUjnfQ6P87m1PKNko8IPWY/edit

**Comment by t-book** [comment]
I might be wrong but this looks a bit as a migration is missing before restoring the fixture.

**Comment by afabiani** [comment]
Yep, it seems related to recent commits on Menu placeholders. It is a bit strange though, the migrate command should create those tables automatically.

**Comment by t-book** [comment]
@csfuente could you check if you spot log output from this line: https://github.com/GeoNode/geonode-docker/blob/master/tasks.py#L70 
As @afabiani says the table should be created by this task.

**Comment by t-book** [comment]
I'm closing this issue as user seems to be inactive.
