### ISSUE TITLE
Incorrect count for layers filtered using permisions in Geonode

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#4274]
# Problem
I have set up a user in Geonode and when I log in with this user the permissions are applied correctly however the layer count is wrong.
![test-view](https://user-images.githubusercontent.com/2510900/53970829-3f594380-4104-11e9-9356-b650d37d7c38.png)

# Solution
The count should show the correct number of layers a user has access to.

**Comment by NyakudyaA** [comment]
> Version?

Master 
![master](https://user-images.githubusercontent.com/2510900/53971347-6b28f900-4105-11e9-8b2a-eac5d6bbadd0.png)

**Comment by afabiani** [comment]
@NyakudyaA could you please send instructions on how to reproduce?

**Comment by t-book** [comment]
@afabiani same here do not see this behavior on a production instance from master 27-2-2019

**Comment by NyakudyaA** [comment]
@afabiani Here are the instructions

* Create a new user ie `testuser`
* Create a new profile `Geonode-Editor` and add `testuser` as a member to the group
* Assign auth permission for `Geonode-Editor`
* Navigate to the layers and change permissions for the layers as below. I have two layers loaded only.

Layer 1

![lyr](https://user-images.githubusercontent.com/2510900/53979889-961c4880-4117-11e9-9806-4ac572e9555c.png)

Layer 2

![second-layer](https://user-images.githubusercontent.com/2510900/53979906-a03e4700-4117-11e9-920f-d1e14ef5264c.png)

* Make sure the user `testuser` only belongs to the `Geonode-editor` role.
![test-user](https://user-images.githubusercontent.com/2510900/53979990-e1cef200-4117-11e9-9425-0f17d7235c0f.png)

* In another browser login as `testuser` and see the layers filtered properly but the count is wrong.

**Comment by t-book** [comment]
Strange as I cannot see some significant commit which could cause a regression for api: https://github.com/GeoNode/geonode/commits/master/geonode/api 
I will try to reproduce this as well by tomorrow.

**Comment by t-book** [comment]
Good news or bad news / it depends. I cannot reproduce this behavior following your instructions on a fresh master vagrant. If it helps I can share screenshots of my settings as well.

**Comment by NyakudyaA** [comment]
@t-book Can you share the screenshots of your settings and I will test them

**Comment by t-book** [comment]
@NyakudyaA Sure. Please note that following your instructions I did not add anonymous group to test user. hence he will only see one layer. When adding anonymous role he will see both layers. By the way also try to sync your rules by use of the button in permissions modal.

![bildschirmfoto 2019-03-08 um 12 55 15](https://user-images.githubusercontent.com/20478652/54027488-01aaf800-41a2-11e9-88d6-7d735b23f871.png)
![bildschirmfoto 2019-03-08 um 12 53 20](https://user-images.githubusercontent.com/20478652/54027492-02438e80-41a2-11e9-9a63-49aff1773013.png)
![bildschirmfoto 2019-03-08 um 12 55 33](https://user-images.githubusercontent.com/20478652/54027489-01aaf800-41a2-11e9-9883-fdd262441cc1.png)
![bildschirmfoto 2019-03-08 um 12 55 52](https://user-images.githubusercontent.com/20478652/54027490-01aaf800-41a2-11e9-9e9a-8a2d79dfdf4d.png)
![bildschirmfoto 2019-03-08 um 12 55 07](https://user-images.githubusercontent.com/20478652/54027491-01aaf800-41a2-11e9-9492-4a4f1a32f54c.png)
![bildschirmfoto 2019-03-08 um 12 52 48](https://user-images.githubusercontent.com/20478652/54027493-02438e80-41a2-11e9-8e7f-94ab4bf4fa1c.png)
![bildschirmfoto 2019-03-08 um 12 52 37](https://user-images.githubusercontent.com/20478652/54027494-02438e80-41a2-11e9-9de9-58eae31f4485.png)

**Comment by NyakudyaA** [comment]
@t-book the only difference is the following

![resources](https://user-images.githubusercontent.com/2510900/54028826-fe6a3900-41ae-11e9-9140-b22a68b53d8c.png)

If you do not specify what kind of permissions your group has then it works as expected

**Comment by t-book** [comment]
@NyakudyaA True, when applying both rules further make sure the user has NOT anonymous group I can confirm the wrong count. https://github.com/GeoNode/geonode/blob/b80700641318f51546fb45e21d65de77870356c4/geonode/api/resourcebase_api.py#L514
Unsure if this is a regression @afabiani .

**Comment by simod** [comment]
Hi, group permissions shouldn't be changed in the admin but through the frontend only. This because GeoNode does a number of things under the hood to correctly set the permissions. So all should work by just creating the group from the UI, assign the users to it through manage-members and then assign data permissions to the group through the permissions right column of the layers/maps/docs.
