### ISSUE TITLE
How to add more scale value? 

### ISSUE THREAD

**Issue by lolob** [GeoNode/geonode#4285]
Hi, 

I'm using Geonode 2.8. I would like to know how to add more scale value into the picture below;

![Screenshot 2019-03-14 at 2 35 11 PM](https://user-images.githubusercontent.com/15963902/54336962-74b3e300-4668-11e9-9641-1c2581169fb8.png)

I found a quite similar thread here; I followed but nothing's happened. Say I want to have new additional '1:1000' scale. 
[https://gis.stackexchange.com/questions/91902/geoexplorer-setting-more-custom-zoom-levels](url)

**Comment by simod** [comment]
Adding scale values is not trivial I think, in particular on this client. Those scale values are the result of how the mapping library (OpenLayers, but not only) define the zoom levels and I don't think this version can handle intermediate zoom levels.
