### ISSUE TITLE
CSW download link: metadata are empty

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4293]
GeoNode master.
All the metadata obtained by the zip file that you can get via CSW are empty.

**Comment by afabiani** [comment]
@frafra the layer must be "Published" in order to dump the metadata.

Let me figure out if we can dump metadata from the download link by somehow passing through the current user credentials.

**Comment by frafra** [comment]
The layer is public, the data and the metadata are available; the metadata in the zip file are empty.

**Comment by afabiani** [comment]
strange, however try out the fix proposed by the related PR. It should work.
