### ISSUE TITLE
403 Forbidden error creating group

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4296]
Login to [master.demo.geonode.org](http://master.demo.geonode.org), then from [master.demo.geonode.org/groups](http://master.demo.geonode.org/groups/?limit=20&offset=0) click **Create a new group**.

I get:  **403 Forbidden**

**Comment by simod** [comment]
seems to be related to the server configuration on demo. Can't reproduce it locally

**Comment by jondoig** [comment]
Shouldn't we treat the demo as the reference implementation, config and all? How else to be sure.
