### ISSUE TITLE
Upload metadata: ignored fields

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4302]
I tried to upload a layer with a ISO metadata file, but GeoNode ignores some information, such as:

- Author (the uploader becomes the author)

This also happens if a metadata file is uploaded afterwards.

**Comment by simboss** [comment]
@frafra can we get an example metadata that is giving this issue?

**Comment by frafra** [comment]
Here is an example: https://gist.github.com/frafra/595d3c3fc622ee6d2a80651315d92317

In order to reproduce the issue you should have:
- An author that is different from the user who uploads the data

**Comment by simboss** [comment]
thx

**Comment by gannebamm** [comment]
Any news about this issue @frafra ? I face the same problems by some users of my institution uploading data which was given by other institutions (eg. nature conservation areas) and them not beeing able to reference the author and contact correctly. GeoNode is limited by always linking to the profile from the current GeoNode instance. This should be decoupled in a way that:

1. By default the user will be set as author and contact
2. If needed a 'strictly' contact profile could be created and set

**Comment by frafra** [comment]
@gannebamm Hi; we had a talk with GeoSolutions about that, but I think that we could implement together this specific feature if you want to.
