### ISSUE TITLE
Import/export of original metadata

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4304]
It is possible to download metadata in different standards (DublinCore, ISO, etc.), but some information are missing (like categories). Would it be possible to have a metadata format which allow the user to see the entire set of metadata stored by GeoNode?

**Comment by giohappy** [comment]
@frafra are you talking about a standard metadata format or a custom one, just for the purpose of moving metadata betwenn GN instances?

**Comment by frafra** [comment]
@giohappy better if it's standard, but it needs to contain all the metadata stored in GeoNode: the export/import operation should not be lossy.

In my case that missing feature would be used to move data across multiple instances, right.

**Comment by simboss** [comment]
@frafra the mapping everything we have inside the geonode model using a metadata standard (most probably ISO) requires most probably to take a decision on what (from the geonode model) to map where (in the metadata).

I think that the best way to move forward is using ISO but a bit of time need to be taken into account to define the mappings and producing some reference metadata.
