### ISSUE TITLE
Can't add geonode apt repository because it doesn't have a release file

### ISSUE THREAD

**Issue by bigblind** [GeoNode/geonode#4307]
Here's the command I used and the output I got:

```
$ sudo add-apt-repository ppa:geonode/stable
 GeoNode stable releases
 More info: https://launchpad.net/~geonode/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://mirror.hetzner.de/ubuntu/packages bionic InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease                                                                                  
Hit:3 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease                                                                                
Hit:4 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease                                                                                                       
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                            
Ign:6 http://ppa.launchpad.net/geonode/stable/ubuntu bionic InRelease                                                                                                              
Hit:7 http://archive.ubuntu.com/ubuntu bionic-updates InRelease                                                            
Err:8 http://ppa.launchpad.net/geonode/stable/ubuntu bionic Release                                                                                   
  404  Not Found [IP: 91.189.95.83 80]
Hit:9 http://archive.ubuntu.com/ubuntu bionic-backports InRelease                                                                                     
Hit:10 http://security.ubuntu.com/ubuntu bionic-security InRelease      
Reading package lists... Done                      
E: The repository 'http://ppa.launchpad.net/geonode/stable/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.2 LTS
> Release:	18.04
> Codename:	bionic

**Comment by kalxas** [comment]
Hi,
We do not have currently a release in the stable ppa for Bionic.
Please use 
`sudo add-apt-repository ppa:geonode/testing`
if you want to test 2.10rc4

In case you are looking for a previous release for Bionic, there is also the version included in OSGeoLive:
`sudo add-apt-repository ppa:geonode/osgeo`
You will need to make sure that you install the package python-django 1.8.7-1ubuntu5.6~bionic3 first.

Hope this helps,
Angelos

**Comment by iamtekson** [comment]
Exact same error happens to me. Is there any update? Or how can I solve this issue?

**Comment by t-book** [comment]
@iamtekson apt setup is abandoned. can you say where you got the information about it? It would be good to remove it.

**Comment by iamtekson** [comment]
You mean apt-setup is completely removed from all the Ubuntu version? There is no shortcut way to install the Geonode than?

Well actually I got a PDF document from my friend. Also I found https://launchpad.net/~geonode/+archive/ubuntu/stable on internet

**Comment by t-book** [comment]
you might be lucky with 2.6 which is not recommended for production.
Either use ansible for manual installation (or just follow: https://docs.geonode.org/en/master/install/core/index.html)
or use docker: https://docs.geonode.org/en/master/install/core/index.html#docker
With Docker you have two flavours. A regular stack and one called SPC.

**Comment by iamtekson** [comment]
Ya, I already checked these methods. These methods having lots of steps. But I need to install quickly. Is there any possible way?

**Comment by iamtekson** [comment]
I found this https://github.com/GeoNode/geonode/tree/master/package:

```
Ubuntu 12.04 
-----------------------------

Open a terminal and run the following commands::

    sudo add-apt-repository ppa:geonode/testing
    sudo apt-get update
    sudo apt-get install geonode
```

**Comment by t-book** [comment]
> But I need to install quickly. Is there any possible way?

Docker
