### ISSUE TITLE
How test latest commits

### ISSUE THREAD

**Issue by johnfelipe** [GeoNode/geonode#4316]
How can install dev instance for test and try latest commits?

**Comment by frafra** [comment]
There is no automatic way do run all the tests at the moment, but you can use https://github.com/GeoNode/geonode-selenium.
You could try to mimic https://github.com/GeoNode/geonode/blob/master/.travis.yml but is not easy. It would be nice to have a different script just for tests that does not rely on Travis.

**Comment by johnfelipe** [comment]
I need to know commands for git pull may be, I want test nightly version of geonode, that is possible?

**Comment by gannebamm** [comment]
should be closed?
