### ISSUE TITLE
Sort icon not set based on the URL

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4319]
If you visit `/layers/?limit=20&offset=20&order_by=title` the sort button will show a clock instead of an image representing the alphabetical sorting. The image changes only when the user clicks on the menu, but it is not set based on the URL parameters when the page loads.

**Comment by t-book** [comment]
@frafra Well spotted!  The react replacement (https://github.com/GeoNode/geonode/issues/4129) might solve this at least on master.
