### ISSUE TITLE
GeoNode is not able to show errors properly on upload

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4321]
GeoNodes fails to display errors.

Some examples:

```
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/views.py", line 294, in layer_upload
    out[_k] = out[_k].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'NoneType' object has no attribute 'charset'
```
References:
- https://github.com/GeoNode/geonode/issues/4188#issue-404000230
- https://github.com/GeoNode/geonode/issues/4241#issue-411525171

```
  File "./geonode/layers/views.py", line 300, in layer_upload
    out[_k][key] = out[_k][key].decode(saved_layer.charset).encode("utf-8")
AttributeError: 'ErrorList' object has no attribute 'decode'
```
References:
- https://github.com/GeoNode/geonode/issues/4241#issuecomment-470990611

```
  File "./geonode/layers/views.py", line 242, in layer_upload
    upload_session.error = pickle.dumps(error).decode("utf-8", "replace")
  File "/usr/local/lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle traceback objects
```
References:
- https://github.com/GeoNode/geonode/issues/4232#issue-410688978

In the past the code has been changed in order to fix a similar bug.
References:
- https://github.com/GeoNode/geonode/issues/4232#issuecomment-466015263
- https://github.com/GeoNode/geonode/commit/671c250b81ae7d05933825a7f0d6482f65f7c267

**Comment by afabiani** [comment]
@frafra feel free to re-open if you find some other failure. Better if we can spot and open specific issues for further errors that may occur (hopefully not) in the future.

**Comment by frafra** [comment]
@afabiani ok! Thank you for the nice pull request :-)
