### ISSUE TITLE
List of documentation improvements

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4325]
Here is a list of settings variables (master settings.py) which might be candidates for adding to
http://docs.geonode.org/en/master/tutorials/advanced/geonode_settings/settings.html:

**Not all of them might be meaningful but definitely some** (like celery or security settings). I will wait until the contrib app cleanup (https://github.com/GeoNode/geonode/issues/4311) has been done  and would work on short explanations. (maybe at next summit.) IMHO contrib settings should be explained in it´s specific README.

A
- ACCESS_TOKEN_EXPIRE_SECONDS
- ACCOUNT_APPROVAL_REQUIRED
- ACCOUNT_CONFIRM_EMAIL_ON_GET
- ACCOUNT_EMAIL_REQUIRED
- ACCOUNT_EMAIL_VERIFICATION
- ACCOUNT_LOGIN_REDIRECT_URL
- ACCOUNT_LOGOUT_REDIRECT_URL
- ACCOUNT_NOTIFY_ON_PASSWORD_CHANGE
- ACCOUNT_OPEN_SIGNUP
- ACTSTREAM_SETTINGS
- ADMIN_MODERATE_UPLOADS
- AGON_RATINGS_CATEGORY_CHOICES
- ANONYMOUS_USER_ID
- API_INCLUDE_REGIONS_COUNT
- API_LIMIT_PER_PAGE
- ASYNC_SIGNALS
- AUTO_GENERATE_AVATAR_SIZES
- AWS_ACCESS_KEY_ID
- AWS_BUCKET_NAME
- AWS_QUERYSTRING_AUTH
- AWS_S3_BUCKET_DOMAIN
- AWS_SECRET_ACCESS_KEY
- AWS_STORAGE_BUCKET_NAME

B
- BING_API_KEY
- BROKER_HEARTBEAT
- BROKER_TRANSPORT_OPTIONS

C
- CACHES
- CACHE_TIME
- CASCADE_WORKSPACE
- CATALOGUE
- CELERYD_POOL_RESTARTS
- CELERY_ACCEPT_CONTENT
- CELERY_ACKS_LATE
- CELERY_BEAT_SCHEDULE
- CELERY_DISABLE_RATE_LIMITS
- CELERY_ENABLE_UTC
- CELERY_MAX_CACHED_RESULTS
- CELERY_MESSAGE_COMPRESSION
- CELERY_RESULT_PERSISTENT
- CELERY_RESULT_SERIALIZER
- CELERY_SEND_TASK_EVENTS
- CELERY_SEND_TASK_SENT_EVENT
- CELERY_TASK_ALWAYS_EAGER
- CELERY_TASK_CREATE_MISSING_QUEUES
- CELERY_TASK_IGNORE_RESULT
- CELERY_TASK_QUEUES
- CELERY_TASK_RESULT_EXPIRES
- CELERY_TASK_SERIALIZER
- CELERY_TIMEZONE
- CELERY_TRACK_STARTED
- CELERY_WORKER_DISABLE_RATE_LIMITS
- CELERY_WORKER_SEND_TASK_EVENTS
- CLIENT_RESULTS_LIMIT
- CSRF_COOKIE_HTTPONLY
- CSRF_COOKIE_SECURE

D
- DATA_UPLOAD_MAX_NUMBER_FIELDS
- DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION
- DEFAULT_ANONYMOUS_VIEW_PERMISSION
- DEFAULT_LAYER_FORMAT
- DEFAULT_MAP_CRS
- DEFAULT_WORKSPACE
- DELAYED_SECURITY_SIGNALS
- DISPLAY_COMMENTS
- DISPLAY_RATINGS
- DISPLAY_SOCIAL
- DISPLAY_WMS_LINKS

E
- EXIF_ENABLED

F
- FREETEXT_KEYWORDS_READONLY

G
- GEOFENCE_SECURITY_ENABLED
- GEOIP_PATH
- GEONODE_APPS
- GEONODE_EXCHANGE
- GEOSERVER_EXCHANGE
- GEOSERVER_LOCATION
- GEOSERVER_PUBLIC_HOST
- GEOSERVER_PUBLIC_LOCATION
- GEOSERVER_PUBLIC_PORT
- GEOSERVER_WEB_UI_LOCATION
- GEOTIFF_IO_ENABLED
- GOOGLE_API_KEY
- GOOGLE_MAPS_API_KEY
- GROUP_PRIVATE_RESOURCES

H
- HAYSTACK_FACET_COUNTS
- HAYSTACK_SEARCH
- HYPERMAP_REGISTRY_URL

L
- LEAFLET_CONFIG
- LICENSES
- LOCAL_SIGNALS_BROKER_URL
- LOGIN_URL
- LOGOUT_URL

M
- MAPBOX_ACCESS_TOKEN
- MAPPROXY_URL
- MAP_CLIENT_USE_CROSS_ORIGIN_CREDENTIALS
- MISSING_THUMBNAIL
- MONITORING_DATA_TTL
- MONITORING_DISABLE_CSRF

N
- NLP_ENABLED
- NOTIFICATIONS_MODULE
- NOTIFICATION_ENABLED

O
- OAUTH2_PROVIDER
- OGC_SERVER_DEFAULT_PASSWORD
- OGC_SERVER_DEFAULT_USER
- OGP_URL

P
- PINAX_NOTIFICATIONS_BACKENDS
- PINAX_NOTIFICATIONS_LOCK_WAIT_TIMEOUT
- PINAX_NOTIFICATIONS_QUEUE_ALL

R
- RABBITMQ_SIGNALS_BROKER_URL
- REDIS_SIGNALS_BROKER_URL
- RISKS

S
- S3_MEDIA_ENABLED
- S3_STATIC_ENABLED
- SEARCH_FILTERS
- SECURE_BROWSER_XSS_FILTER
- SECURE_CONTENT_TYPE_NOSNIFF
- SECURE_HSTS_INCLUDE_SUBDOMAINS
- SECURE_HSTS_SECONDS
- SECURE_SSL_REDIRECT
- SERVICE_UPDATE_INTERVAL
- SESSION_COOKIE_SECURE
- SESSION_EXPIRED_CONTROL_ENABLED
- SITE_HOST_NAME
- SITE_HOST_PORT
- SKIP_PERMS_FILTER
- SLACK_ENABLED
- SOCIALACCOUNT_ADAPTER
- SOCIALACCOUNT_AUTO_SIGNUP
- SOCIALACCOUNT_PROVIDERS
- SOLR_URL
- SRID

T
- TASTYPIE_DEFAULT_FORMATS
- THESAURI

U
- UNOCONV_ENABLE
- USER_MESSAGES_ALLOW_MULTIPLE_RECIPIENTS
- USE_GOOGLE_STREET_VIEW
- USE_HYPERMAP
- USE_WORLDMAP

X
- X_FRAME_OPTIONS

**Comment by capooti** [comment]
@t-book great investigative report! :)

**Comment by t-book** [comment]
@capooti thanks! "Documentation is a love letter that you write to your future self." ;-)

**Comment by capooti** [comment]
ahaha :D

**Comment by t-book** [comment]
@t-book  remember to update docs ASYNC_SIGNALS <> ASYNC_SIGNALS_BROKER_URL 
http://docs.geonode.org/en/master/tutorials/admin/async_signals/

**Comment by t-book** [comment]
I'm closing this as we already have the list in docs now.
