### ISSUE TITLE
Map compose does not add layer when url is not localhost

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#4328]
When using docker on a custom domain, addLayer does not work on map compose, it sends requests to localhost/geoserver.

findLayer does work because it uses CSW, so that is a workaround.

-a

**Comment by francbartoli** [comment]
@ingenieroariel  it is working well for me. Can you share your `docker-compose.override.yaml`?

**Comment by jonnyforestGIS** [comment]
@ingenieroariel  and @francbartoli  works well for me too.
