### ISSUE TITLE
GeoServer warning geofence.jar not found?

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4332]
Some more errors on docker setup regarding Geoserver: GeoFence.jar is not found
```
02 Apr 13:13:32 WARN [geoserver.config] - Error reading resource URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.14-20190218.170018-1.jar!/geofence-default-override.properties]
java.io.FileNotFoundException: URL [jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.14-20190218.170018-1.jar!/geofence-default-override.properties] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/gs-geofence-server-2.14-20190218.170018-1.jar!/geofence-default-override.properties
        at org.springframework.util.ResourceUtils.getFile(ResourceUtils.java:215)
[...]
```

looking inside the container directory `/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/` I see:

`-rw-r--r-- 1 root root  109032 Feb 18 18:19 gs-geofence-server-2.14-20190218.170018-1.jar`

I do not know why it is flagged as non resolvable

**Comment by capooti** [comment]
I have seen this message since many months, but I believe it is just a warning so it shouldn't affect GeoNode

**Comment by GeoTob** [comment]
I think this is a problem with the upstream geoserver - geofence plugin rather than geonode.

SO suggests the method used for trying to open the default config file may be wrong (https://stackoverflow.com/a/41877759/4033315). 

> ...geofence-default-override.properties] cannot be resolved to absolute file path because it does not reside in the file system
