### ISSUE TITLE
SPC GeoServer Auth button does not work

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4335]
I get a 404 when clicking the GeoNode auth button in the GeoServer Web UI:

![grafik](https://user-images.githubusercontent.com/6172324/55461072-d75b2780-55f3-11e9-99fa-6cdd62b65caf.png)

Fresh install with this docker-compose.yml:
https://gist.github.com/gannebamm/fcf5fa651d9cec27d325213b0473ea12

Error Message:
    HTTP ERROR 404

    Problem accessing /geoserver/o/authorize/. Reason:

        Not Found

    Powered by Jetty://

The redirect URL points to a wrong location (doubled geoserver/):
`http://134.110.18.170/geoserver/o/authorize/?response_type=code&client_id=74CAlBvtmNBC43BSi5jpFE3BM0iS7Opiaj0gDswU&scope=write&redirect_uri=http://134.110.18.170/geoserver/geoserver/index.html` 

>> redirect_uri=http://134.110.18.170/geoserver/**geoserver**/index.html

**Comment by t-book** [comment]
What does your redirect_uri in django admin -> applications -> GeoServer look like.
Unsure when it´s set with docker but it might be a fixture like: https://github.com/GeoNode/geonode/blob/master/geonode/base/fixtures/default_oauth_apps.json#L10

**Comment by gannebamm** [comment]
These are the `de/admin/oauth2_provider/application/1`
settings:
![grafik](https://user-images.githubusercontent.com/6172324/55469536-fe225980-5605-11e9-8fe8-7712d87e3bff.png)

This settings are from an other instance with working Auth button and upload:
![grafik](https://user-images.githubusercontent.com/6172324/55469623-28741700-5606-11e9-8220-72780a5dd83b.png)


Differences are:
Redirect uris and Skip Authorization

**Comment by t-book** [comment]
Maybe connected to the /gs /geoserver routing issue?

**Comment by frafra** [comment]
I can confirm that it is happening here too (spc, master).

**Comment by t-book** [comment]
this /gs /geoserver routing is starting to get cumbersome. It´s happening on dev setup with paver as well

**Comment by afabiani** [comment]
Redirect URIs should always pointing to /geoserver

**Comment by t-book** [comment]
> Redirect URIs should always pointing to /geoserver

... which is currently not the case with settings.py? 
```
_default_public_location = 'http://{}:{}/gs/'.format(
    GEOSERVER_PUBLIC_HOST,
    GEOSERVER_PUBLIC_PORT) if GEOSERVER_PUBLIC_PORT else 'http://{}/gs/'.format(GEOSERVER_PUBLIC_HOST)
```

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L752

**Comment by gannebamm** [comment]
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L104

That is the point were the doubled /geoserver/ URL is set. Base URL allready contains /geoserver
:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L32

In Addition this:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/initialize.py#L90-L91

Is not properly handeld for http / https URLS. Something like:
```
if (os.getenv('HTTPS_HOST') != ""):
    redirect_uris = [
    'https://{}/geoserver'.format(os.getenv('HTTPS_HOST')),
    'https://{}/geoserver/index.html'.format(os.getenv('HTTPS_HOST')),
    ]
else:
    redirect_uris = [
    'http://{}/geoserver'.format(os.getenv('HTTP_HOST')),
    'http://{}/geoserver/index.html'.format(os.getenv('HTTP_HOST')),
    ]
```

would be more appropriate.

**BUT**
neither of those are fixing the issue.

**Comment by gannebamm** [comment]
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L30

Adds '/geoserver ' to Base url but:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L104
adds it again. This will lead to /geoserver/geoserver/ in the URL. This was fixed in #4355 as side effect because I looked into the file and found that error.

But there are more:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/geoserver/docker-entrypoint.sh#L103

The /o/auth URL is wrong. It should **not** contain /geoserver/.

For some reason spc would need `geoserver` instead of `gs` for GEOSERVER_PUBLIC_LOCATION and .._WEB_UI:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/docker-entrypoint.sh#L26

Therefore initialize.py should use it, too:
https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/initialize.py#L90-L91

With those changes the button will redirect to an authorize screen. After authorizing GeoServer you will be logged in. Which is not exactly the behaviour as in geonode plain compose.

**Comment by gannebamm** [comment]
Ok. I can confirm my findings above. With the mentioned changes and an additional `skip_authorization=True` in https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/django/initialize.py#L90-L91 the auth button works again.

I will create a PR for this.

**Comment by francbartoli** [comment]
@gannebamm I'm not convinced these two different methods have different settings. Do you know why this is going to happen? @afabiani thoughts?
