### ISSUE TITLE
Upload GUI does not show files #docker

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4338]
On a fresh install with main docker aswell as with spc the dialog will not get populated:

![download_GUI_error](https://user-images.githubusercontent.com/6172324/55475402-26b15000-5614-11e9-8159-15c893ccdad3.gif)

**Comment by t-book** [comment]
@gannebamm What errors do you see in browser console? (I would say it´s an issue with js)

**Comment by gannebamm** [comment]
I was not able to reproduce this error anymore. I have not idea what was wrong.
