### ISSUE TITLE
GeoNode can't redirect to GeoServer. It uses port 8000 instead 8080. Development Mode. 

### ISSUE THREAD

**Issue by tomasjuanl** [GeoNode/geonode#4362]
I've just installed GeoNode 2.10 for Development from tag 2.10rc4 in Ubuntu 16.04, with [this guide](http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html#ubuntu-standard-deployment) more or less. 

with **_paver start_**, GeoNode starts just fine in port 8000, also GeoServer, in port 8080.
When I try to go to GeoServer from GeoNode site, fails with 404, because it's trying to connect to host:8000/geoserver, but the correct URL is host:8080/geoserver. 

I debbuged the code in **_geonode/proxy/views.py_**, in the "proxy" function and what I can see is that, for every request, redirects to **_host_**:**_port_**{**_locator_**} where **_locator_** = '/geoserver/' in this case, and **_host_** and **_port_** are the the ones from GeoNode. The request parameter holds correctly the **_host:8080/geoserver_** URL, but this code always redirects to the same host and port of GeoNode.

**Comment by t-book** [comment]
From the Mailinglist: 

> In the master branch, that option *GEOSERVER_PUBLIC_PORT *does exists and
> solves the issue.

@tomasjuanl I´m closing this issue. Please reopen if needed.
