### ISSUE TITLE
Title and abtract wont be read by /search template #minor 

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#4379]
The title and abstract fields for layers will not get read properly by the /search template. This is the correct display from /layers :
![grafik](https://user-images.githubusercontent.com/6172324/56966171-e2f02e80-6b5e-11e9-817a-2d7546a7b636.png)

This is the same view by /search :
![grafik](https://user-images.githubusercontent.com/6172324/56966225-f26f7780-6b5e-11e9-9766-5568c48a26c5.png)

**Comment by t-book** [comment]
@gannebamm  It seems to work here http://master.demo.geonode.org/search/?title__icontains=VIAS&limit=20&offset=0 ?

Also from a quick look it should output the title:
https://github.com/GeoNode/geonode/blob/f62eaf7e0f91f6f97c7753d10702f3335ac3c6ac/geonode/base/templates/base/_resourcebase_snippet.html#L35
Will try to check it on localhost the next days ...

**Comment by gannebamm** [comment]
Thanks @t-book. I checked it again and there where some cookies and cache issues on my side. After I updated the layer metadata again it worked.
I close this issue

**Comment by t-book** [comment]
Nice! Thanks!
