### ISSUE TITLE
Docs: Rework TOC

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4394]
@afabiani  suggested to rework/cleanup the TOC. This issue is meant for discussion as part of the Docs Rework Milestone.

**Comment by afabiani** [comment]
drafting TOC here
https://docs.google.com/spreadsheets/d/1oXoRyCqtTHCclCO1ed5PfWiW_skafGU2i5w-BNWRT4s/edit#gid=0

**Comment by t-book** [comment]
@afabiani I think we can remove CentOS 7.0 from GeoNode Core (Dev) TOPIC Lv.2 ? And only name differences when installed in production?

**Comment by t-book** [comment]
I would welcome if we can add some lines for use of qgis server backend https://github.com/GeoNode/geonode/issues/3932
@timlinux @lucernae

**Comment by t-book** [comment]
**TOPIC Lv.3**
> Django
> GeoServer
> Databases
> Security with OAuth2

Maybe add Apache / nginx

**Comment by t-book** [comment]
**System Admin - Installation Guide**
TOPIC Lv.1

Adding a guide for migration would be useful. I could share my notes here.
Also, some words here how to pull from master branch to keep an installation up to date.

**Comment by t-book** [comment]
**System Admin - Installation Guide**
TOPIC Lv.3

We should explain how to setup/configure RABBIT MQ for production. Unsure if there is already something in current docs.

**Comment by afabiani** [comment]
I have added the topics to the spreadsheet.
Please take a look and review, also add remarks at your convenience.
Feel free to change it also.

As soon as we agree on the TOC we can start working on the docs.
Thanks, everyone.

**Comment by t-book** [comment]
@afabiani one question. Do you plan to update old or replace docs completely with a new version? I would welcome the second as a fresh start.

**Comment by afabiani** [comment]
@t-book I absolutely agree to replace it completely, even though whenever it's possible I would backport sections that are still valid and/or need just a refresh

**Comment by t-book** [comment]
+1

**Comment by afabiani** [comment]
@t-book btw, I'm not an expert here, any suggestion is very welcomed.

**Comment by t-book** [comment]
@afabiani me neither :) IMHO it would be great to have a native speaker on board. At least to do a last proofreading. Also, I found some useful hints here: https://docness.readthedocs.io/en/latest/

> Documentation should not contain list of commands. Scripts are made for that purpose.
For example https://docness.readthedocs.io/en/latest/external-channels/scripts.html

I do not fully agree but f.e. in case of apt packages installation a makefile could be an nice option.

I would definitly sign this:
> Documentation has to be:
> simple to read and understand
> simple to create and maintain.
> The best way to achieve this is to keep it minimal. So, make documentation straightforward.

https://docness.readthedocs.io/en/latest/keep-straightforward.html

**Comment by francbartoli** [comment]
Draft ToC pushed on the `new-docs` branch and compiled to _readthedocs_ http://docs.geonode.org/en/new-docs/
