### ISSUE TITLE
UTF-8 problem

### ISSUE THREAD

**Issue by SaudiGIS** [GeoNode/geonode#4396]
I installed GeoNode in digitalocean web site, After the files were uploaded to the site with the UTF-8 encoding, the Arabic fields appear with unknown characters (for example See picture: https://imgur.com/vjf12jV ).

how I can fix this problem please ?

**Comment by afabiani** [comment]
Any chance to have a sample dataset to try?

**Comment by t-book** [comment]
@SaudiGIS could you solve this already? If not could you provide some test data?

**Comment by t-book** [comment]
@SaudiGIS Is it possible to update to latest master? GXP has been replaced with mapstore. Maybe this solves your problem.

**Comment by t-book** [comment]
I'm closing here as it seems the user is inactive. @SaudiGIS please reopen in case you like to continue.

**Comment by darekw** [comment]
It might be the missing BOM information in the file
