### ISSUE TITLE
Avoid re-writing thumbnail every time a Layer is saved

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4410]
Currently, a pos_save signal forces the creation of the thumbnail every time a layer is saved somehow, causing overload and often failing to recreate it.

The thumbnail should be created automatically only when the layer has been uploaded the first time instead.

**Comment by capooti** [comment]
I agree with this. Just the first time or whenever a user use the "Set Thumbnail" button.
@afabiani could you also check why a post_save signal is raised whenever a user update a style with the style editor? Thanks a lot
