### ISSUE TITLE
moderator_contacted does not actually send email to moderator

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4413]
Here in geonode/views.py this view obviously does not contact the moderator and does not send the email

```python
def moderator_contacted(request, inactive_user=None):
    """Used when a user signs up."""
    user = get_user_model().objects.get(id=inactive_user)
    return TemplateResponse(
        request,
        template="account/admin_approval_sent.html",
        context={"email": user.email}
    )
```

**Comment by afabiani** [comment]
@capooti I guess the intent of this method was to send an email back to the user itself.
The moderator should receive emails through the Pinax notification subsystem.

**Comment by capooti** [comment]
@afabiani this method is called when ACCOUNT_APPROVAL_REQUIRED = True I believe.
The method you are thinking of works and is part of Pinax notification application I believe.

Using Google I realized that this was already reported, so let's keep this ticket open:
https://lists.osgeo.org/pipermail/geonode-devel/2018-May/002278.html
