### ISSUE TITLE
Shapefile downloaded via WFS is rotated 90 degrees

### ISSUE THREAD

**Issue by rli-rms** [GeoNode/geonode#4420]
I re-built geonode after the new updates were made, and found there is an issue:

Layers downloaded via wfs are now rotated 90 degrees clockwise, as the following France maps shows.

![image](https://user-images.githubusercontent.com/45500815/58037074-6b6c4a00-7ae1-11e9-820c-aa4ad822dde2.png)

This never happened before the updates. 

A sample link I used is: http://mysever/geoserver/wfs?service=wfs&version=2.0.0&request=GetFeature&typeName=geonode:fr_admin1&outputformat=SHAPE-ZIP

Thanks

**Comment by rli-rms** [comment]
However, shapefile downloaded by link format like the following did have the issue:

http://myserver/geoserver/ows?outputFormat=SHAPE-ZIP&service=WFS&srs=EPSG%3A4326&request=GetFeature&format_options=charset%3AUTF-8&typename=geonode%3Afr_admin2&version=1.0.0

**Comment by afabiani** [comment]
@rli-rms the second one works or not?

However, I guess it depends on the client you are using. WFS 2.0.0 has different axis order.

Please see

https://docs.geoserver.org/latest/en/user/services/wfs/basics.html#axis-ordering

**Comment by rli-rms** [comment]
> @rli-rms the second one works or not?
> 
> However, I guess it depends on the client you are using. WFS 2.0.0 has different axis order.
> 
> Please see
> 
> https://docs.geoserver.org/latest/en/user/services/wfs/basics.html#axis-ordering

But I never had this issue when WFS using 2.0.0 before.

**Comment by afabiani** [comment]
Well, the requests you posted seems to hit directly the GeoServer endpoint. So those cannot depend by GeoNode updates for sure.

Maybe you have an updated version of GeoServer? Are you using special JAVA_OPTS to start it?

**Comment by rli-rms** [comment]
Shouldn't be the case since I freshly installed the Geonode via docker. The geoserver should be the default one coming with the Geonode.

**Comment by rli-rms** [comment]
Please feel free to close this issue since we already found a solution. Thanks a lot for the assistance!
