### ISSUE TITLE
No such image from Celery, running docker-compose

### ISSUE THREAD

**Issue by JoaoPedroCNMota** [GeoNode/geonode#4432]
I pulled the new version of geonode grom github and when i run docker-compose, the bash shows me the message:

![image](https://user-images.githubusercontent.com/46454275/58439353-f3d28800-80a9-11e9-9215-cafaa47e99ae.png)

It seems to me that celery4geonode cant be pulled from docker hub.

I run the comand: **docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build**, after clone the git project

Sorry for my bad english;

**Comment by sjohn-atenekom** [comment]
Setting up the project with the mentioned command works fine for me and I could not reproduce this issue.
Probably, you had network problems?
@afabiani Can you please close this issue?
