### ISSUE TITLE
Configure celery broker backend

### ISSUE THREAD

**Issue by GeoTob** [GeoNode/geonode#4433]
The current (2.8.x and master at least) settings file seem to derive the `CELERY_BROKER_URL` from an env variable called `RABBITMQ_SIGNALS_BROKER_URL`, and only if `ASYNC_SIGNALS` is enabled:

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1359

Shouldn't this be configurable directly? Would make a PR but unsure if that's desired behaviour?

(also `ASYNC_SIGNALS` defaults to `False`, while documentation says otherwise: http://docs.geonode.org/en/master/tutorials/advanced/geonode_settings/settings.html?#async-signals)

**Comment by t-book** [comment]
Unsure if I miss something but, when we want ASYNC Signals we set it to true. 

In this case, _BROKER_URL  is set to whatever you set RABBITMQ_SIGNALS_BROKER_URL to. (In case you do not set an env var instead.)  

If ASYNC Signals are not used _BROKER_URL is set to LOCAL_SIGNALS_BROKER_URL
So this all makes sense to me https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1482 ?

> also ASYNC_SIGNALS defaults to False, while documentation says otherwise: 

True this needs correction.

**Comment by GeoTob** [comment]
No you're right, I wonder if I got confused by the deprecation notice for `BROKER_URL` https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1495 combined with the rabbitmq default ..

**Comment by t-book** [comment]
Async default value will be corrected with this PR https://github.com/GeoNode/geonode/pull/4460
