### ISSUE TITLE
GNIP: Promote GeoNode MapStore Client as default one

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4441]
# Overview
With the stable release of [GeoNode MapStore Client](https://github.com/geosolutions-it/geonode-mapstore-client/releases/tag/v1.0) we would like finally to get rid of the old-fashioned GeoNode client based on GeoExt and GXP Javascript libraries, and use as default client REACT based one, [MapStore2](https://mapstore.geo-solutions.it/mapstore/#/).

## Proposal
The GeoNode MapStore client is not invasive and, thanks to the GeoNode client [hooksets](https://github.com/GeoNode/geonode/issues/3600), it can be easily installed on a standard GeoNode with few simple steps.
There's no need to customize the code base nor to insert fancy `if-else` statements somewhere.

Given that:

a) the new client release is stable
b) switching the client is a non-invasive operation on GeoNode and won't break current installations

the proposal is to definitively change the default settings in order to make MapStore2 the default one instead of GeoExplorer.

The [GeoNode Live Demo](http://master.demo.geonode.org/) already runs it in case you want to try out the new client.

**Comment by t-book** [comment]
+1
