### ISSUE TITLE
Connection error on docker-compose build

### ISSUE THREAD

**Issue by jonnymccullagh** [GeoNode/geonode#4442]
Hi,
trying to run:
docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build

But it is failing with:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb0a255a550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/pillow/

Any ideas?

**Comment by gannebamm** [comment]
Do you use HTTPS? How did you setup the https certificate?
