### ISSUE TITLE
Thumbnails on layers not showing

### ISSUE THREAD

**Issue by pjduplooy** [GeoNode/geonode#4450]
Hi guys.

After the latest commits (inclusion of Mapstore), thumbnails of layers does not show in the layer explorer.

Any idea of how to resolve this?

Another thing, and it is a personal feeling, is there a way to revert to Geonode proper?   

I am using the docker build as per official docs.

**Comment by t-book** [comment]
I can confirm, thumbs stay empty.

> Another thing, and it is a personal feeling, is there a way to revert to Geonode proper?


You mean revert to GXP? If so it should work to switch the hookset:
https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1280

cheers,

toni

**Comment by pjduplooy** [comment]
Hi Toni

Thanks for that.  Just a quick question though, can I change the settings.py, and thing bring up geonode with docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up, or do I have to rebuild it again with docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build?  Is there an easier way to change it?  I do no really want to fiddle in code

**Comment by t-book** [comment]
Hi,

unfortunately, I haven't touched docker for some time. @frafra can you say if it's needed to rebuild the container when changing the settings file? I would say yes as the requirements.txt should also be changed to add GXP again: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1284

Anyways I'm sure it will not take long until thumbs work again.

**Comment by afabiani** [comment]
Hi, any chance to try to change the default GeoServer authenticator to
Basic Auth? That should fix the issue.

Il dom 2 giu 2019, 08:25 Toni <notifications@github.com> ha scritto:

**Comment by t-book** [comment]
> Hi, any chance to try to change the default GeoServer authenticator to
Basic Auth?

@afabiani Unfortunately I've already destroyed the VM. @pjduplooy can you try

**Comment by afabiani** [comment]
Just to clarify,
you need to go here

![image](https://user-images.githubusercontent.com/1278021/58785084-1fdb9500-85e5-11e9-92f3-82c91c45c339.png)

and then move basic at first position

![image](https://user-images.githubusercontent.com/1278021/58785126-3550bf00-85e5-11e9-8d98-50a30a2ddc74.png)

Do not forget to close

![image](https://user-images.githubusercontent.com/1278021/58785152-41d51780-85e5-11e9-9664-92f5775c7690.png)

and save

![image](https://user-images.githubusercontent.com/1278021/58785188-50233380-85e5-11e9-9afc-84dc0393fd4b.png)

**Comment by afabiani** [comment]
@t-book @pjduplooy I'm afraid I forgot to backport a commit from our fork

https://github.com/GeoNode/geonode/commit/155ac7c71ad1728265ef7105e5b625f9b64b0c90

This should fix the thumbnail generation (other than the GeoServer change)

**Comment by t-book** [comment]
thanks @afabiani
