### ISSUE TITLE
 failed to build: max depth exceeded

### ISSUE THREAD

**Issue by bkhezry** [GeoNode/geonode#4451]
I use docker for running Geonode from here
http://docs.geonode.org/en/master/tutorials/install_and_admin/running_docker/setup_docker.html

after a few days,  runnig this code
`docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build`
and returns this error:
`Service 'celery' failed to build: max depth exceeded`

**Comment by sjohn-atenekom** [comment]
I can't reproduce this issue. The celery-service has been moved to docker-compose.async.yml.
Running the following command works fine:
`docker-compose -f docker-compose.async.yml -f docker-compose.override.localhost.yml up --build`

@afabiani This issue can be closed, since it cannot be reproduced.
