### ISSUE TITLE
Issues uploading data (permissions related?)

### ISSUE THREAD

**Issue by geomonkey** [GeoNode/geonode#4454]
Hi, We're trying to set up a geonode through a VirtualMachine. We're experiencing an issue with data upload which we think is related to permissions between geonode and geoserver. 

When we upload a dataset we are met with a preview that is a series of pink squares and icons for broken image link. When we try to bring the data into the mapping tool we can see open street map tiles but not our data. When we try to download our data, we are presented a 404 error. 

I've tested our data on the demo version of the site and they appear flawlessly.

Any help would be greatly appreciated. Many Thanks!

**Comment by t-book** [comment]
Sounds either your OAuth settings are wrong or your geoserver endpoints in settings.

**Comment by t-book** [comment]
For general questions regarding configuration please use the user and dev list https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-devel 
Closing here.
