### ISSUE TITLE
Thumbnail basemap not rendering

### ISSUE THREAD

**Issue by GeoTob** [GeoNode/geonode#4459]
Not sure if I'm the only one affected by this, but thumbnails are currently rendering without a basemap for me. Thumbnails on the official geonode demo also don't show a basemap currently.

Looking at the GeoServer logs I noticed the following warning:

```
Error fetching : http://a.tile.openstreetmap.org/xx/xxxxxx/xxxxxx.png, status is : 403
```

Loading the URL manually works just fine.

Searching for the issue online revealed this very recent answer on SO: https://stackoverflow.com/a/56440427/4033315 which hints at OSM blocking certain requests. Not sure if this is the problem here?

I changed `THUMBNAIL_GENERATOR_DEFAULT_BG` in `settings.py` to a different provider and got this to work again:

```python
THUMBNAIL_GENERATOR_DEFAULT_BG = r"https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png"
```

I currently can't spend the time to check the request headers sent by the `printng` extension to see if they complies with OSM policy, but maybe someone else can?

In the meantime I suggest switching the default for `THUMBNAIL_GENERATOR_DEFAULT_BG` to a more forgiving server.

**Comment by afabiani** [comment]
@GeoTob very interesting. I'll try to have a look during the code sprint next week.

**Comment by bkhezry** [comment]
I have this error too. During update Thumbnail of layers, this error happens.

```
geoserver4geonode | 08 Jun 14:05:28 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/20/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:31 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/21/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:31 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/21/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:31 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/21/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/22/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/20/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/22/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/22/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/19/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:32 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/21/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:33 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/20/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:33 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/19/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:33 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/20/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:33 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/19/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:33 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/22/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/23/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/23/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/23/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/19/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/18/12.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/18/13.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/18/11.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/23/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/18/14.png, status is : 403
geoserver4geonode | 08 Jun 14:05:34 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/18/15.png, status is : 403
geoserver4geonode | 08 Jun 14:05:35 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/19/15.png, status is : 403
geoserver4geonode | 08 Jun 14:05:35 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/20/15.png, status is : 403
geoserver4geonode | 08 Jun 14:05:35 WARN [geoserver.printng] - Error fetching : http://a.tile.openstreetmap.org/5/21/15.png, status is : 403
geoserver4geonode | 08 Jun 14:05:35 WARN [geoserver.printng] - Error fetching : http://c.tile.openstreetmap.org/5/22/15.png, status is : 403
geoserver4geonode | 08 Jun 14:05:35 WARN [geoserver.printng] - Error fetching : http://b.tile.openstreetmap.org/5/23/15.png, status is : 403

```

**Comment by capooti** [comment]
@gannebamm I am on master with the modified settings:
THUMBNAIL_GENERATOR_DEFAULT_BG = r"https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png"

But I keep getting (using the "Set Thumbnail tool"): Error fetching : http://b.tile.openstreetmap.org/3/7/4.png, status is : 403

I guess also the baselayer in the layer details page must be changed?

**Comment by Martenz** [comment]
I am on master with the modified settings:
THUMBNAIL_GENERATOR_DEFAULT_BG = r"https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png"

no 403 errors but still no basemap shown ... 

I'm looking into /layers/views.py
and I don't understand this function "layer_thumbnail"  (row 1421 ...)

if preview and preview == 'react':
            format, image = json.loads(
                request.body)['image'].split(';base64,')
            image = base64.b64decode(image)
        else:
            image = None
            try:
                image = _prepare_thumbnail_body_from_opts(
                    request.body, request=request)
            except BaseException:
                image = _render_thumbnail(request.body)

I guess the default generation is a non "react" img so the coe goes to the two functions:

_prepare_thumbnail_body_from_opts
or
_render_thumbnail

but how to configure as react ? react preview means that the image is generated based on the base64 image of the div containing the map/layer preview?

I'm most likely missing part of the code here.. but I'm lost .. please help

Martino.

**Comment by t-book** [comment]
Hi @Martenz don't let you bring on the wrong track with react as a preview. If I remember correctly var  preview will be react in case you choose the geonode client: https://github.com/GeoNode/geonode/blob/2.10.x/geonode/settings.py#L1303
http://client.geonode.org/#map=9783.93962050256/-8855994.1/4469502.35/0
Which I would not recommend by now.

This looks like the newly added wikimedia server has it's issues as well. So this needs further testing.

**Comment by Martenz** [comment]
> Hi @Martenz don't let you bring on the wrong track with react as a preview. If I remember correctly var preview will be react in case you choose the geonode client: https://github.com/GeoNode/geonode/blob/2.10.x/geonode/settings.py#L1303
> http://client.geonode.org/#map=9783.93962050256/-8855994.1/4469502.35/0
> Which I would not recommend by now.
> 
> This looks like the newly added wikimedia server has it's issues as well. So this needs further testing.

Thanks, I will check my setting.py first then will try with a different provider ..

**Comment by Martenz** [comment]
I surrended and then moved to change library, so I added html2canvas.js and added an other preview option in the POST so I could intercept the base64 image and then store the data from the canvas generated by html2canvas.. working but still need to crop properly the thumbnail to the same proportion of other previews.. will post something when done.

thanks
