### ISSUE TITLE
Determine l10n strategy for enumerations in the DB (things like TopicCategory)

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#446]
Need to figure out a strategy for dealing with localization of things at the database level. TopicCategory, perhaps attribute names etc.

**Comment by capooti** [comment]
should we discuss this or can we postpone to future milestone?

**Comment by jj0hns0n** [comment]
This has been implemented starting with https://github.com/GeoNode/geonode/commit/bb850c2a1867520e3b8a7d5ed6f93908abf29fc8. Closing

**Comment by capooti** [comment]
I know, but I thought we are also trying to figure out a strategy for record values.

**Comment by jj0hns0n** [comment]
Lets discuss.
