### ISSUE TITLE
Filter layer in MapStore map

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4468]
In the old GeoExplorer mapping client, you could filter a layer by scale or attributes and save the map with this filter applied to the layer definition.

In the new MapStore mapping client, you can open the layer attribute table and apply a filter, but cannot save it to the layer definition. This is a significant loss of function.

**Comment by jondoig** [comment]
Can close this issue. Simone explained:

-1- I believe this issue should be moved to the geonode-mapstore repo

-2- the ability to create filtered layers by specifying a query is going to be released shortly for mapstore. This means it will end up in the geonode integration soon

-3- you can still use geoexplorer if you prefer :)


Regards,
Simone Giannecchini

**Comment by simboss** [comment]
Hi @jondoig,
I will move this one to the geonode-mapstore project.

**Comment by simboss** [comment]
Ouch, I can't.

@afabiani we need to enable issues on the geonode-mapstore-client and then move this one.
