### ISSUE TITLE
404 and 401 errors on layer detail

### ISSUE THREAD

**Issue by GeoTob** [GeoNode/geonode#4470]
This doesn't seem to affect functionality, but opening a layer in Geonode sends two failing XHR requests:

1. `/security/permissions/<id>`  - 401 not authorised (when not logged in)
2. `/layers/version.txt` - 404 not found 

Try for example any layer on the demo server: http://master.demo.geonode.org/layers/geonode:ne_10m_admin_0_countries#/

I expect the first one to do with layer permission management for admins/owners, but I have no idea what the `version.txt` request is doing? Can we ignore it? Remove it? Fix it?

**Comment by t-book** [comment]
@GeoTob right the first one is for permissions: https://github.com/GeoNode/geonode/blob/704b03d0c7e0cf4ef729862d37bebc1320e882d3/geonode/templates/_permissions_form_js.html#L76-L95

I'm quite sure you can just ignore that one.

The later, version.txt is requested from mapstore see https://github.com/geosolutions-it/MapStore2/blob/22bbfe82be2db71cd622d27bed457ccd41bb1332/web/client/actions/version.js#L42

From a quick look, I would say this should be provided from the specific resource base config. but never have seen where/how to set it up. Would be indeed interesting how to deliver it.
