### ISSUE TITLE
remove spcgeonode .env from git

### ISSUE THREAD

**Issue by Marwe** [GeoNode/geonode#4477]
In spcgeonode the .env file with secrets is under version control, but it better should not be versioned, since checking in changes means having secrets in version control.
Solution: 
* provide a template.env
* users must copy and change it
* add .env to .gitignore
* update the README

I will create a pull request for it.

**Comment by frafra** [comment]
I would agree with you, but probably the `.env` file should not be used in production at all. I wonder if it would not be better just to specify in the documentation to not to use it in production and use environment variables instead.

**Comment by gannebamm** [comment]
I think there is nothing wrong with using env files for production and like the template.env idea. By this we could introduce new env vars to the docker compositions without fearing of uploading some secrets.
