### ISSUE TITLE
simplify WORKON_HOME management and avoid .bashrc tweak

### ISSUE THREAD

**Issue by nastasi-oq** [GeoNode/geonode#4480]
**IT AFFECT [new-docs](/GeoNode/geonode/tree/new-docs) BRANCH**
 * ``WORKON_HOME`` environment variable is used improperly in ``geonode.binary``
 * there is an unneeded ``.bashrc`` file tweak in the installation documentation

**Comment by t-book** [comment]
Closed with https://github.com/GeoNode/geonode/pull/4481
