### ISSUE TITLE
Djangos template Internationalization is not executed everywhere

### ISSUE THREAD

**Issue by ikzte** [GeoNode/geonode#4493]
## Expected Behavior
Djangos template internationalization should translate all tagged codepassages

## Actual Behavior
Internationalization is not applied in every case, sometimes english version is shown 

## Steps to Reproduce the Problem

  1. Open GeoNode
  2. Switch Language (if your browser hasn't done it for you)

## Specifications

  - GeoNode version: 2.10.rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 18.04.2 LTS
  - Additional details: - 

### Landingpage 

1. Text to be translated: **Advanced Search**
2. File: /geonode/geonode/templates/index.html 
3. Line: 49
4. Code:
```html
<p><a class="btn btn-default btn-lg" href="{% url "search" %}">{% trans "Advanced Search" %}</a></p>
```

1. Text to be translated: **Discover the available datasets.**
2. File: /geonode/geonode/templates/index.html 
3. Line: 60
4. Code:
```html
<h1>{% trans "Discover the available datasets." %}</h1>
```

1. Text to be translated: **All Dataset discriptions when mousehovering over them** 
2. File: geonode/geonode/templates/index.html
3. Line: 64-235
4. Code (example):
```html
title="{% trans "Flora and/or fauna in natural environment. Examples: wildlife, vegetation, biological sciences, ecology, wilderness, sealife, dwetlands, habitat." %}">
```

1. Text to be translated: **Featured Datasets**
2. File: geonode/geonode/templates/index.html
3. Line: 253
4. Code:
```html
<h2>{% trans "Featured Datasets" %}</h2>
``` 

1. Text to be translated: **Explore all datasets**
2. File: geonode/geonode/templates/index.html
3. Line: 309
4. Code:
```html
<p><a href="/search/">{% trans "Explore all datasets" %}</a></p>
``` 

### Data/Explore Layers/Documents & Explore Maps

1. Text to be translated: **Explore "Element"**
2. File: /geonode/geonode/templates/search/_search_content.html
3. Line: 52-62
4. Code:
```html
      <div class="col-md-10">
          {% if facet_type == 'layers' %}
          <span style="font-size: 34px;" ng-bind="total_counts + ' ' + '{% trans "Layers found" %}'"></span>
          {% elif facet_type == 'maps' %}
          <span style="font-size: 34px;" ng-bind="total_counts + ' ' + '{% trans "Maps found" %}'"></span>
          {% elif facet_type == 'documents' %}
          <span style="font-size: 34px;" ng-bind="total_counts + ' ' + '{% trans "Documents found" %}'"></span>
          {% else %}
          <span style="font-size: 34px;" ng-bind="total_counts + ' {{ facet_type | title }} found'"></span>
          {% endif %}
      </div>
``` 
### Data/Remote Services

1. Text to be translated: **Register a new Service**
2. File: geonode/geonode/services/templates/services/service_list.html
3. Line: 8
4. Code:
```html
<a href="{% url "register_service" %}" class="btn btn-primary pull-right">{% trans "Register a new Service" %}</a>
```

**Comment by t-book** [comment]
In case, a foreign language has no translation, Django will fallback to English.
I'm not sure if this issue/request can ever be fully fulfilled. The only way we can improve translations is by the help of more contributors. Those should  follow the procedure as new docs suggest: http://docs.geonode.org/en/new-docs/contribute/translation/index.html

**Comment by ikzte** [comment]
I see... this is caused by the fuzzy-tag in those po files. Who decides if a translation is fuzzy or not?
Should we leave this issue open or should I close it?

**Comment by t-book** [comment]
A PR for updating a *.po goes through the same process as other files do. Some privileged user has to review/merge it. If it's correct to "unfuzzy" a term it will be accepted. Of course, these checks are limited as not devs speak all languages.  Hence, chances are high to just trust the contributor with his translation ... I would close here.

**Comment by ikzte** [comment]
Alright. Thanks for the clarification.
