### ISSUE TITLE
Mapstore printing tool doesn't print layers in local docker instance

### ISSUE THREAD

**Issue by impisnoth** [GeoNode/geonode#4494]
## Expected Behavior
Printout should include all layers in the map

## Actual Behavior

The PDF shows only the baselayer

## Steps to Reproduce the Problem

  1. Deploy GeoNode from master using docker
  2. Create a map with one or more layers
  3. Print the map

## Specifications

  - GeoNode version: 2.10 rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: OSX
  - Additional details:

<img width="1256" alt="Screenshot 2019-06-13 at 10 46 52" src="https://user-images.githubusercontent.com/5585799/59422930-6abd8f80-8dd1-11e9-8675-b02689e4ad06.png">

**Comment by ikzte** [comment]
I can confirm this. The printed document shows an Error-Message as a Comment:
```java
Error
java.lang.IllegalStateException: unsupported protocol: 'jar'
```
