### ISSUE TITLE
[NEW-DOCS] proper filtering of pygdal package version

### ISSUE THREAD

**Issue by nastasi-oq** [GeoNode/geonode#4495]
## Expected Behavior
if the version of pygdal on PyPi package index exceed x.y.9 the filtering stops to work properly.

## Actual Behavior
... x.y.10 ... => x.y.1

## Steps to Reproduce the Problem

  1. ``pip install pygdal==100000 >/tmp/mytest.txt 2>&1``
  2. edit ``/tmp/mytest.txt`` and add in the list of versions a ``2.2.3.10`` version
  3. ``export GDAL_VERSION=2.2.3``
  3. run a modified version of the command to see the error: \\
      ``cat /tmp/mytest.txt | grep -oP '(?<=: )(.*)(?=\))' | grep -oh $GDAL_VERSION\.[0-9]``

## Specifications

  - GeoNode version: new-docs branch
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: linux
  - Additional details:

**Comment by t-book** [comment]
Closed with https://github.com/GeoNode/geonode/pull/4496
