### ISSUE TITLE
Trouble with Django paths when using Apache proxy

### ISSUE THREAD

**Issue by rumski20** [GeoNode/geonode#4510]
I have downloaded and built the docker containers using the instructions provided here: (https://github.com/GeoNode/geonode/tree/master/scripts/spcgeonode)
The containers eventually get up and running just fine.

I have Apache on the Ubuntu host acting as a proxy that forwards requests to the appropriate port that the container is listening on.
Example Apache configuration:
`ProxyPass /geonode http://0.0.0.0:1234`
`ProxyPassReverse /geonode http://0.0.0.0:1234`
This port is also specified in the `.env` file:
`HTTP_HOST=myhost.com`
`HTTP_PORT=1234`

I can navigate to `myhost.com/geonode` just fine, but the Django resources are returning 404 Not Found errors. They are trying to reference `myhost.com/static/...`. But shouldn't they be at `myhost.com/geonode/static/...`?

Is there a setting I missed in the`.env` file or maybe something I need to change in the `docker-compose.yml` file?
Thank you for any advice you have on how to set up this arrangement. Thank you also for doing all the work to provide this amazing arrangement.

## Specifications

  - GeoNode version: latest from master 13 June 2019
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu
  - Additional details: using spcgeonode (https://github.com/GeoNode/geonode/tree/master/scripts/spcgeonode)

**Comment by rumski20** [comment]
Seems related to this issue: #4113 but is the solution by @afabiani there still the recommended one? (I hope not because I need to use Apache on my host).

**Comment by t-book** [comment]
@rumski20 
What if you just redirect the static folder in your proxy (apache vhost)

```
RewriteEngine On
RewriteRule ^static/(.+)$ /geonode/static/$1 [L,NC]
```

**Comment by rumski20** [comment]
Thanks for the suggestion, @t-book . I actually got the django resources to show up by editing the static and media URLs in the `docker-compose.yml` file.  
eg. `STATIC_URL=geonode/static/`
However, other URL endpoints are not showing correctly such as `myhost.com/geonode/people`. I wonder will I have to use the tactic you suggested above for each of these paths or is there a way to set an environment variable somewhere that should take care of mapping these correctly?

Thanks for any help you can provide.
