### ISSUE TITLE
Download Map is not working

### ISSUE THREAD

**Issue by olljal** [GeoNode/geonode#4518]
## Expected Behavior
Be able to download map thumbnail from Download Map button.

## Actual Behavior
Empty modal appears after clicking Download Map button.

## Steps to Reproduce the Problem

  1. Goto demo site url: http://master.demo.geonode.org/maps/2#/ 
  2. Click Download Map
  3. Modal without expected content appears

## Specifications

  - GeoNode version: 2.10rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): demo site
  - Platform: demo site
  - Additional details: demo site

**Comment by t-book** [comment]
@olljal I cannot reproduce this behavior on master demo. The modal is showing a link references to http://master.demo.geonode.org/uploaded/thumbs/map-7d129fce-90d6-11e9-b447-0242ac120008-thumb.png

Do you see any errors in your browser console?

**Comment by olljal** [comment]
> @olljal I cannot reproduce this behavior on master demo. The modal is showing a link references to http://master.demo.geonode.org/uploaded/thumbs/map-7d129fce-90d6-11e9-b447-0242ac120008-thumb.png
> 
> Do you see any errors in your browser console?

It seems to work now. And the local installation with this issue was fixed when I added the missing thumbnail. Thanks!

**Comment by t-book** [comment]
Great!
