### ISSUE TITLE
Move from Travis CI to Circle CI

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#4521]
Travis CI cannot be run locally and it does not use regular Docker images. Using Circle CI would allow us to run the tests inside Docker containers both locally and on the server.

How to migrate: https://circleci.com/docs/2.0/migrating-from-travis/

We are eligible for extra containers, which would make our tests running much faster:

> What if I am building open-source?
> 
> We offer a total of four free linux containers ($2400 annual value) for open-source projects. Simply keeping your project public will enable this for you!
>
> We also offer the Seed plan free (at 1x concurrency) for OS X open source projects. Contact us at billing@circleci.com for access. If you are building a bigger open-source project and need more resources, let us know how we can help you!

-- https://circleci.com/pricing/#faq-section-linux

**Comment by gannebamm** [comment]
I really like their commercials. Soothing atmosphere.

**Comment by frafra** [comment]
Connecting Circle CI to the repository can by done by a repo admin only (I am just a maintainer).

**Comment by afabiani** [comment]
Let's transform this to a GNIP.

See https://github.com/GeoNode/geonode/wiki/GeoNode-Improvement-Proposals
