### ISSUE TITLE
Choose between GeoExplorer and Mapstore apps

### ISSUE THREAD

**Issue by pjduplooy** [GeoNode/geonode#4536]
Hi guys.

Would it be possible to have an easier way of choosing between GeoExplorer and Mapstore than changing it in settings.py.

I am having bit of trouble understanding what to change where

**Comment by t-book** [comment]
Hi, settings is the way to go. Change this line

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1192

to:

`GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY = os.getenv('GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY', 'geoext')`

restart your server and you're done ;) 

((((
in case you get an error GXP is not found install it: 
```
1. pip install django-geoexplorer==4.0.42
2. add 'geoexplorer' to INSTALLED_APPS
```
))))

**Comment by t-book** [comment]
By the way. Github Issues should be used for bugs. Regarding questions about usage please use the mailing list ;)
