### ISSUE TITLE
Update to GeoServer 2.14.4

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4551]
## Expected Behavior
Fresh setup will deploy and run GeoServer 2.14.4

## Actual Behavior
Fresh setup will deploy and run GeoServer 2.14.3

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: none

**Comment by afabiani** [comment]
This is also related to https://github.com/GeoNode/geonode/pull/4523

**Comment by t-book** [comment]
@afabiani Did you check the dev setup with 2.14.4? It's failing with my tests.
2.14.3 and 2.15.1 are working fine.

**Comment by afabiani** [comment]
Currently not working with gsconfig client.
POST request to create a new style fails with an odd error. Strangely this error does not occur performing the same request with a standard curl command.
More investigation needed indeed.

**Comment by afabiani** [comment]
Let's move to 2.15.2 after the GeoNode 2.10 release.
