### ISSUE TITLE
Map interface freezes before loading the contant

### ISSUE THREAD

**Issue by deviirmr** [GeoNode/geonode#4583]
## Expected Behavior
Map layer should be load immediately once I click Create Map option in the layer view interface.

## Actual Behavior
I have a user which has a staff right and when I click on the "Create Map" button in the layer view interface, it will open a map interface but it freezes for a 3 minute and then it loads the content. Another strange part is if I use superuser then there is no issue with composing or loading map.
I tried to debug in the browser also, it seems it taking too much time for loading GetCapabilities

![image](https://user-images.githubusercontent.com/10088434/60250780-8f346400-98c7-11e9-9dc6-656feb4346c1.png)

![image](https://user-images.githubusercontent.com/10088434/60250804-9a878f80-98c7-11e9-8c31-4da511a5f619.png)

![image](https://user-images.githubusercontent.com/10088434/60250880-c30f8980-98c7-11e9-9a74-0830ae1ab3e6.png)

## Steps to Reproduce the Problem

1. Land on website http://geonode.iwlearn.org
2. login as user **user123** and pass **user123**
3. Try to compose any map

## Specifications

  - GeoNode version: version 2.6.3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): No docker, Direct Install from PPA  
  - Platform: Ubuntu 16.04.3 LTS
  - Additional details: Let me know what other info need

**Comment by t-book** [comment]
The reason for this is your wms getCapabilities request.http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=false&VERSION=1.1.1

If you look at the dev tools TTFB (Time to first byte) takes 1.2 min

<img width="395" alt="Bildschirmfoto 2019-06-29 um 15 30 03" src="https://user-images.githubusercontent.com/20478652/60384888-635ddd80-9a83-11e9-9e2c-d5bfd919cc15.png">

TTFB is the network latency+the time your server needs to prepare the response. In other words. Some backend process is taking really long. Unfortunately this can have many reasons. To little Ram, a slow database query, corrupt styles, a slow HDD, etc. I would start by checking your server metrics with something like top or htop, free -m etc. further reviewing logs. especially those from tomcat.

**Comment by t-book** [comment]
A little hack for your apache vhost config:

```
RewriteEngine On
RewriteCond %{HTTP_REFERER} http://[^/]+/maps/new
RewriteCond %{QUERY_STRING} "SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1" 
RewriteRule ^/geoserver/wms$ http://%{SERVER_NAME}/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 [L,R]
```

removing tiled=true 
will at least shring the response from 5 to 1mb.

**Comment by deviirmr** [comment]
Thank you for coming to help.
Do you mean I need to remove 
 tiled=true

But I  could not locate this file **(apache vhost config**)


![image](https://user-images.githubusercontent.com/10088434/60385478-d4a08f00-9a89-11e9-8575-f8cfd7b00aac.png)

**Comment by t-book** [comment]
@deviirmr Have a look at sites-available. Most likely there is a geonode.conf

**Comment by deviirmr** [comment]
Ok, I got the file.
![image](https://user-images.githubusercontent.com/10088434/60385745-dae43a80-9a8c-11e9-86dc-02c10ba11af9.png)

and I add the script at the  bottom of the script as

```
WSGIDaemonProcess geonode user=www-data threads=15 processes=2
<VirtualHost *:80>
    Servername localhost
    ServerAdmin webmaster@localhost

    ErrorLog /var/log/apache2/error.log
    LogLevel warn
    CustomLog /var/log/apache2/access.log combined

    WSGIProcessGroup geonode
    WSGIPassAuthorization On
    WSGIScriptAlias / /var/www/geonode/wsgi/geonode.wsgi

    <Directory "/var/www/geonode/">
       Order allow,deny
       Options -Indexes
       Allow from all
    </Directory>

    Alias /static/ /var/www/geonode/static/
    Alias /uploaded/ /var/www/geonode/uploaded/
    Alias /robots.txt /var/www/geonode/robots.txt

    <Directory "/var/www/geonode/uploaded/documents/">
       Order allow,deny
       Deny from all
    </Directory>

    <Directory "/var/www/geonode/uploaded/layers/">
       Order allow,deny
       Deny from all
    </Directory>

    <Proxy *>
      Order allow,deny
      Allow from all
    </Proxy>

    ProxyPreserveHost On
    ProxyPass /geoserver http://localhost:8080/geoserver
    ProxyPassReverse /geoserver http://localhost:8080/geoserver

RewriteEngine On
RewriteCond %{HTTP_REFERER} http://[^/]+/maps/new
RewriteCond %{QUERY_STRING} "SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1" 
RewriteRule ^/geoserver/wms$ http://%{SERVER_NAME}/geoserver/wms?SERVICE=WMS&REQUEST=GetCapabilities&VERSION=1.1.1 [L,R]

</VirtualHost>
```


But then when restart apace it through an error.  Even try with pasting code above <VirtualHost *:80> tag but still

[....] Restarting apache2 (via systemctl): apache2.serviceJob for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.
 failed!

**Comment by t-book** [comment]
do you have mod_rewrite enabled?

**Comment by t-book** [comment]
also you can check the syntax with somethink like:

```
# Red Hat-based (Fedora, CentOS) and OSX
httpd -t

# Debian-based (Ubuntu)
apache2ctl -t
```

**Comment by deviirmr** [comment]
I got this on terminal

geomaster@Geonode2:~$ apache2ctl -t
AH00558: apache2: Could not reliably determine the server's fully qualified
domain name, using 10.0.0.7. Set the 'ServerName' directive globally to
suppress this message
Syntax OK

**Comment by t-book** [comment]
well, this means all is fine. (what you see is a warning because of your server name). If you have mod_rewrite enabled I do not see a reason why apache should not start.

**Comment by deviirmr** [comment]
I just remove the script and its working fine.
But still, I want to incorporate your suggestions(that four lines code).
Let me know where is mod_rewrite is define?

**Comment by t-book** [comment]
On Ubuntu you would enable it with:

```
sudo a2enmod rewrite
sudo service apache2 restart
```

What those lines actually should do is to remove the `tiled=true` . Which lowers the load.

You can investigate this behavior with dev tools. Just visit your wms endpoint with tiled true and false:

http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1

http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=false&VERSION=1.1.1

This will not solve your problem but at least it should lower the waiting time a bit ;)

Please also check your error logs which you most likely find under ubuntu at:
/var/log/apache2/error.log

**Comment by deviirmr** [comment]
This time script incorporated successfully.
But you are right problem is not solved.
Still, I am capabilities taking time



http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1
![image](https://user-images.githubusercontent.com/10088434/60386686-c6a63a80-9a98-11e9-9c37-2bba0cce116a.png)



###############################################



http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=false&VERSION=1.1.1
![image](https://user-images.githubusercontent.com/10088434/60386675-ad9d8980-9a98-11e9-97ff-4f6d975adcfb.png)

Also, I am attaching log if you could figure out something.
[error.log](https://github.com/GeoNode/geonode/files/3342075/error.log)

**Comment by t-book** [comment]
Strange you should get at least get a little better performance. Anyway, how are your tomcat and geoserver resources?

**Comment by deviirmr** [comment]
I hope it will be better soon .)

```
Tomact resource:
● tomcat7.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat7; bad; vendor preset: enabled)
   Active: active (running) since Sat 2019-06-29 15:52:35 UTC; 38min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 82406 ExecStop=/etc/init.d/tomcat7 stop (code=exited, status=0/SUCCES                  S)
  Process: 82417 ExecStart=/etc/init.d/tomcat7 start (code=exited, status=0/SUCC                  ESS)
    Tasks: 267
   Memory: 1.7G
      CPU: 2min 41.290s
   CGroup: /system.slice/tomcat7.service
           └─82447 /usr//bin/java -Djava.util.logging.config.file=/var/lib/to...

Jun 29 15:52:30 Geonode2 systemd[1]: Starting LSB: Start Tomcat....
Jun 29 15:52:30 Geonode2 tomcat7[82417]:  * Starting Tomcat servlet engine t...7
Jun 29 15:52:35 Geonode2 tomcat7[82417]:    ...done.
Jun 29 15:52:35 Geonode2 systemd[1]: Started LSB: Start Tomcat..
Hint: Some lines were ellipsized, use -l to show in full.
```
Geoserver
![image](https://user-images.githubusercontent.com/10088434/60386963-e63f6200-9a9c-11e9-99fc-45bb7c289969.png)

From Ubuntu 16
![image](https://user-images.githubusercontent.com/10088434/60387012-91501b80-9a9d-11e9-9ad9-661d8546d2fa.png)

**Comment by t-book** [comment]
can you add the output of 

`$ sudo tail -f /var/log/tomcat7/catalina.out
`

when doing a request to the wms?

( correct the tomcat version just guessing it's 7 )

**Comment by deviirmr** [comment]
You are right tomcat is 7

I request this one
`http://geonode.iwlearn.org/geoserver/wms?access_token=AqiHg5b9bYlEqhfulKDy6PgvJSUHIz&SERVICE=WMS&REQUEST=GetCapabilities&TILED=false&VERSION=1.1.1`

[catalina.txt](https://github.com/GeoNode/geonode/files/3342755/catalina.txt)

**Comment by deviirmr** [comment]
Hi, @t-book any suggestion?

**Comment by t-book** [comment]
@deviirmr Unfortunately I did not spot any suspicious but would really suggest testing my fix again. this solved this issue some time ago for us.

**Comment by deviirmr** [comment]
Do you mean the suggestion you mentioned in the previous response?  I did it already but performance is still an issue. 
I wonder why with superuser status map composition is faster whereas with staff user its slow map loading..

**Comment by afabiani** [comment]
@deviirmr my guess is that this is depending on how GeoNode 2.6 is working.
Recently, on 2.10, we worked on removing exactly those bottlenecks when logging as non-superuser.
The causes are different. To fix the issue you should backport several pull-requests made on 2.10 version.

Probably, if not too hard on your case, upgrading to 2.10 would be better. You will also benefit of a long list of bug-fixed.

**Comment by t-book** [comment]
absolutely agree with @afabiani as far as I remember logs where flooded with OAuth requests which were solved in newer versions.

**Comment by deviirmr** [comment]
Thank you @afabiani for the suggestion.
In my organization, we are managing two GeoNode 2.6 instances and at some point, we wish to upgrade to latest 2.10 version. But my only fear is how much time it will take or how difficult is it.

It would be great if you could suggest some documentation or tutorial to perform transition task from GeoNode 2.6 to 2.10.

**Comment by afabiani** [comment]
@deviirmr I'll try to put something together since we are rewriting all the docs with latest updates.
It might require some time, since I will need to install a virtual machine with a 2.6 version and try the upgrade myself. I'll let you know as soon as possible.

**Comment by deviirmr** [comment]
Thank you @afabiani,
I hope I will hear from you soon.

**Comment by t-book** [comment]
@deviirmr Even if this is for Docker https://github.com/olivierdalang/SPCgeonode#how-to-migrate-from-an-existing-standard-geonode-install it outlines the steps which have to be taken 

What I normally do is something like
- Backup static files and uploaded directories
- Backup geoserver data-directory
- Dump your databases
- Install GeoNode 2.10 (following the docs)
- Copy your data from the old geoserver-data directory to new
- create a new database and import your dumps
- migrate the models using manag.py makemigrations and migrate
- keep fingers crossed ;)

It's advisable to work on a clone. At least a snapshot should exist.

**Comment by deviirmr** [comment]
Thank you, Toni, for outlining the steps
. I will try sometime in the next and I will share an experience with all
you guys.

Regards
Deb
