### ISSUE TITLE
pip install pygdal / numpy breaks new installation

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4593]
## Expected Behavior

Installation of pygdal finishes without error.

## Actual Behavior

pygdal is failing because of numpy 1.17 which does not support python 2.7 anymore.

```
      File "/tmp/easy_install-GaYkcb/numpy-1.17.0rc1/setup.py", line 31, in <module>

    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jy4Fmm/pygdal/
```
Pygdal requires = ['numpy>=1.0.0', ]

**We could solve this error when adding `numpy==1.16.*`to requirements.txt**

## Steps to Reproduce the Problem

  1. Install geonode as you would normally do on a fresh instance following the docs
  2. install pygdal based on your gdal version pip install pygdal=="`gdal-config --version`.*"

## Specifications

  - GeoNode version: 2.10
  - Installation method manual
  - Platform: Ubuntu xenial (might be the same with bionic)

**Comment by afabiani** [comment]
maybe by putting pip install numpy==1.16 first ?

**Comment by giohappy** [comment]
which version of gdal do you have? gdal-config --version

**Comment by t-book** [comment]
@giohappy 2.2.2 but IMHO as pygdal uses  >=  this will end in 2.17 regardless of the version
@afabiani yes this Is what I did, sorry was a bit unclear here will update this issue.

**Comment by giohappy** [comment]
@t-book I didn't read the issue carefully. Indeed pygdal only sets a loose requirements (requires = ['numpy>=1.0.0', ]) so we can stick to 1.16 from our side.
Will you send a PR?

**Comment by t-book** [comment]
@giohappy yep can do.

**Comment by t-book** [comment]
@giohappy @giohappy @frafra I've created a PR for it https://github.com/GeoNode/geonode/pull/4599

Until this is not merged all other PR's will fail with selenium_tests (same numpy problem):


```
 RuntimeError: Python version >= 3.5 required.
```

F.e. : https://travis-ci.org/GeoNode/geonode/jobs/552685672
