### ISSUE TITLE
Docker spc letsencrypt is not working

### ISSUE THREAD

**Issue by kikislater** [GeoNode/geonode#4602]
## Expected Behavior
letsencrypt_1     | Certificate have been created/renewed successfully
letsencrypt_1     | -----------------------------------------------------
letsencrypt_1     | FINISHED LETSENCRYPT ENTRYPOINT ---------------------
letsencrypt_1     | -----------------------------------------------------

## Actual Behavior
pkg_resources.ContextualVersionConflict: (cryptography 1.8.1 (/usr/lib/python2.7/site-packages), Requirement.parse('cryptography>=2.1.4'), set(['PyOpenSSL']))

## Steps to Reproduce the Problem

  1. Install SPC Geonode
  2. Enable Letsencrypt
  3. Start docker and watch letsencrypt logs

## Specifications

  - GeoNode version: 2.10 rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode
  - Platform: Archlinux and Vagrant (Ubuntu server 18.04)
  - Additional details: Working PR : https://github.com/GeoNode/geonode/pull/4601

**Comment by afabiani** [comment]
@t-book I guess we can close this, right?

**Comment by t-book** [comment]
@afabiani yep closed with https://github.com/GeoNode/geonode/pull/4601
