### ISSUE TITLE
Improve Original Dataset Link Behavior

### ISSUE THREAD

**Issue by simboss** [GeoNode/geonode#4604]
## Expected Behavior
At the moment the behavior of the Original Dataset download link is misleading in some cases.
As an instance if you configured the data directly in GeoServer and thenk linked to GeoNode it still appears but when you download you get an empty zip.

We should be more robust and if there is no original data, not show the link.

This issue is related to [this one](https://github.com/GeoNode/geonode/issues/4429) and we should probably keep both into account during this work as we should fix them both.

## Actual Behavior
See above.

## Steps to Reproduce the Problem

  1. Load some data directly in GeoServer
  2. Run the management command to align GeoNode with GeoServer
  3. Click on download link

## Specifications

  - GeoNode version: Latest
  - Installation method (Any):
  - Platform: Any
  - Additional details:

**Comment by giohappy** [comment]
Just for clarity the management command @simboss is referring to is https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/management/commands/updatelayers.py
