### ISSUE TITLE
How to display/improve several layers (shapefiles, tiff, etc..) up to 50 gig on one map?

### ISSUE THREAD

**Issue by mouane** [GeoNode/geonode#4608]
I am presently exploring geospatial possible solutions for a project at my work and came accross this amazing tool that geonode is.

Nonetheless, after installation and configuration on docker containers in my server at work (125gig of ram and 24 powerful gpus), I would like to address my current issue.

I need to display maps that will have several layers that can sum up to 50gig of data on one single map only. I have been able to display all my layers (shapefiles, geotiff etc...) but it is very slow. I have the hardware capabilities with my server to display these maps but how can I configure propoerly apache tomcat or nginx in order to display the data faster on the geonode front-end.

I changed several geoserver configuration such as ThreadPoolExecutor size pool, Tomcat's different service strategies and configs, nginx's client_max_body_size but I do not see an improvement...

How can I improve(speed, refresh rate) the display of big layers on geonode? Do you have a strategy to propose me?

thank you in advance!

## Expected Behavior
better refresh/ map display

## Actual Behavior
very slow to display several layers

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): DOCKER
  - Platform: Ubuntu Server
  - Additional details:

**Comment by t-book** [comment]
> (125gig of ram and 24 powerful gpus

crazy Shi ...  :)

> I changed several geoserver configuration such as ThreadPoolExecutor size pool, Tomcat's different service strategies and configs, nginx's client_max_body_size but I do not see an improvement...
> 
> How can I improve(speed, refresh rate) the display of big layers on geonode? Do you have a strategy to propose me?

Before you change anything I would suggest trying to get insights on what is actually causing the bottleneck. The possibilities are diverse starting from log file interpretation for example with enabled [nginx log time variables](https://www.nginx.com/blog/using-nginx-logging-for-application-performance-monitoring/) followed by system monitoring tools like htop, free etc. over munin, nagios or paid services like Splunk. I would pay special attention to tomcat / geoserver which is known to need some RAM. You're using Docker right? Docker stats could be helpful as well https://docs.docker.com/config/containers/runmetrics/. Further tools like cadvisor https://github.com/google/cadvisor

Unfortunately, this is not really an answer to your question. Hope that I can help better with more detailed (Server)-Information .

**Comment by simboss** [comment]
First an advice, this is not the kind of topic for an issue for the mailing list.

That said, I believe you need to optimize your data before you load them in GeoNode.
An example, [this](https://urbanflooding.geo-solutions.it/layers/geonode:chiangMai_ortho_optimized#/) servers a 7gb drone scene which we optimized like [this](https://geoserver.geo-solutions.it/edu/en/raster_data/advanced_gdal/example5.html) and it is pretty fast at loading.

So, close this issue and move the discussion to the ML.
Give details on the type of data you are willing to serve, then we might be able to help you out :)
