### ISSUE TITLE
Import layer fails with latest GeoServer 2.15.x

### ISSUE THREAD

**Issue by robward-scisys** [GeoNode/geonode#4618]
## Expected Behavior

When uploading a shapefile in a zip file without an SLD style file the layer should be uploaded to GeoServer and GeoServer should create a default style (sld file).  The resulting layer should be imported into GeoNode.

## Actual Behavior

GeoServer uploads the layer but fails to create the style and reports `No such style handler: format = application/xml`

## Steps to Reproduce the Problem

  1. Log in to GeoNode
  2. Upload a shapefile in a zip file without a sld file.
 

## Specifications

  - GeoNode version: 2.10.rc5
  - Installation method : Manual
  - Platform: Ubuntu 16.04, 18.04
  - Additional details:

The issue is a bug in GeoServer 2.15.x and has been reported to the GeoServer project, pull requests have been submitted to fix the issue, [here](https://osgeo-org.atlassian.net/projects/GEOS/issues/GEOS-9280)

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/pull/4640
