### ISSUE TITLE
Search a city/town/location similar to what is done in query option

### ISSUE THREAD

**Issue by MonikaShah** [GeoNode/geonode#4622]
## Expected Behavior
Wanted to enable search and point the inverted drop marker on the searched place.

## Actual Behavior
Not searching the location what is already there on the database/shp file.

## Steps to Reproduce the Problem

  1. should be similar to what actually the query option is doing
  2.
  3.

## Specifications

  - GeoNode version: 2.8
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual
  - Platform: Ubuntu 16.04
  - Additional details:

**Comment by t-book** [comment]
@MonikaShah Can you say if it's mapstore you're using and if it's one of the following options you're looking for?

![attr](https://user-images.githubusercontent.com/20478652/61033564-0d166600-a3c4-11e9-9009-0c00608bfbd2.gif)
![search](https://user-images.githubusercontent.com/20478652/61033588-19022800-a3c4-11e9-8824-2abea20efb52.gif)
