### ISSUE TITLE
Encoding issues when uploading layers using a shapefile

### ISSUE THREAD

**Issue by tfotis** [GeoNode/geonode#4635]
## Expected Behavior

When uploading a new layer using a shapefile, the information in the shapefile should be correctly stored in the db and correctly displayed in Geonode.

## Actual Behavior

The shapefile data isn't correctly stored in the db and also not displayed correctly in Geonode.

## Steps to Reproduce the Problem

  1. Set UPLOADER method to 'geonode.importer'
  2. Upload a layer using shapefile [gr_lwb_50k_greece_1rev_eco.zip](https://github.com/GeoNode/geonode/files/3385627/gr_lwb_50k_greece_1rev_eco.zip). The encoding of the shapefile is UTF-8
  3. After the uploading is complete, click on "Layer Info" to check the layer data
  4. Click on a feature on the map to open the popup information about it. You will see that the data isn't shown correctly. You can also check the DB table, you will also see that the data isn't stored correctly there.

PS 1. The issue doesn't manifest when UPLOADER method is set to 'geonode.rest'
PS 2. Maybe related or could be another issue, when using the same shapefile to upload a layer and selecting "None/Unknown" as the encoding, it is not detected properly

## Specifications

  - GeoNode version: 2.10rc5
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Linux, Ubuntu 18.04 LTS
  - Additional details: The installation to replicate this is pretty straight forward. Git clone the repository (commit 19a2e80d3da1c9735fc627e33adaf645c8f645d8 at the time of this writing) and then start the containers by going inside the "geonode" folder and issuing command `docker-compose up`

**Comment by afabiani** [comment]
Ref:
 - https://osgeo-org.atlassian.net/browse/GEOS-9073
 - https://github.com/geoserver/geoserver/pull/3660

**Comment by gannebamm** [comment]
> 
> 
> Ref:
> 
>     * https://osgeo-org.atlassian.net/browse/GEOS-9073
> 
>     * [geoserver/geoserver#3660](https://github.com/geoserver/geoserver/pull/3660)

Why was this issue reopened? It should be fixed by geoserver/geoserver#3660 merge?
