### ISSUE TITLE
Docker install - build

### ISSUE THREAD

**Issue by pjduplooy** [GeoNode/geonode#4636]
## Expected Behavior
To install Geonode using the docker install instructions

## Actual Behavior
On building the Django part, the build fails with:

Building django
Step 1/9 : FROM geonode/geonode:2.10
ERROR: Service 'django' failed to build: manifest for geonode/geonode:2.10 not found

## Steps to Reproduce the Problem

  1.  Install Docker for Windows
  2.  Clone Repository
  3.  Execute  docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build in geonode folder

## Specifications

  - GeoNode version:
  - Installation method :  Geonode Docker
  - Platform:  Windows 10
  - Additional details:  Master Repository 

This is a bit of a bummer.  Was really looking forward in using Geonode...

Anyway, I will try just pulling the images, and not building.  Would that at least for now solve my problem?

What version is Master?

Pieter

**Comment by pjduplooy** [comment]
Just tested doing a pull of the images, django fails to build

**Comment by dpadron** [comment]
![image](https://user-images.githubusercontent.com/7094961/61180743-3d0b7680-a61b-11e9-831d-23376facd68b.png)

**Comment by gannebamm** [comment]
Hi @pjdufour @dpadron 
I just checked the docker files and the tags are wrong. They should be `geonode/geonode:GN-2.10`
But are `geonode/geonode:2.10`

If you just want to test geonode you could use the docker composition in scripts/spcgeonode/docker-compose.yml

to change the ip / passwords / etc you can edit  scripts/spcgeonode/.env

**Comment by gannebamm** [comment]
I am working on a fix -- unable to assign the task to me :D

**Comment by gannebamm** [comment]
see #4637

**Comment by gannebamm** [comment]
What exactly shall I do with this? Create a new pr targeting master with docker tag 2.10.x?

**Comment by afabiani** [comment]
@gannebamm I'm trying to understand too... I guess we can use geonode/GN-2.10 but @francbartoli had some concerns... on the other side geonode/2.10 does not exist... so I'm confused too!
