### ISSUE TITLE
ERROR: for django  manifest for geonode/geonode:2.10 not found

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#4648]
## Expected Behavior

![image](https://user-images.githubusercontent.com/7094961/61315942-270adb00-a800-11e9-959b-0013158479d0.png)

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker):
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
Closing as duplicate of https://github.com/GeoNode/geonode/issues/4636#issuecomment-511180841
