### ISSUE TITLE
Management command "updatelayers --skip-geonode-registered" not working

### ISSUE THREAD

**Issue by rli-rms** [GeoNode/geonode#4650]
## Expected Behavior
When using the command `django-admin updatelayers --skip-geonode-registered  ` to sync unregistered layers in Geoserver with Geonode, the layers should be updated accordingly.

## Actual Behavior
The command fails. No layers will be found and updated

## Steps to Reproduce the Problem

  1.  Build a customized Geonode instance using docker + geonode-project
  2.  In Geoserver, create a new datastore (I connected to a remote Postgres db). Publish some layers from the store.
  2.  Get  into the django container  by running `docker exec -i -t django4gmy_geonode bash`
  3.  Set env variables: `mkdir -p /usr/src/app/; \
	source $HOME/.override_env; \
	echo DATABASE_URL=$DATABASE_URL; \
	echo GEODATABASE_URL=$GEODATABASE_URL; \
	echo SITEURL=$SITEURL; \
	echo ALLOWED_HOSTS=$ALLOWED_HOSTS; \
	echo GEOSERVER_PUBLIC_LOCATION=$GEOSERVER_PUBLIC_LOCATION;`
4. Run `django-admin updatelayers --skip-geonode-registered`

The command will tell you ```Inspecting the available layers in GeoServer ...
Found 0 layers, starting processing...``` by ignoring the layers to be updated.

## Specifications

  - GeoNode version: 2.10 
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 16.04 running on an AWS EC2 instance
  - Additional details: I was able to run the command successfully last week. Today it starts to fail on a new GeoNode build. So I think it might be related to recent updates of Geonode or Geonode-project

**Comment by rli-rms** [comment]
![image](https://user-images.githubusercontent.com/45500815/61335585-e0f34e80-a7e2-11e9-8afb-fad2cd3816a2.png)
There are 46 layers in Geoserver, as the above pic shows.

**Comment by t-book** [comment]
@rli-rms 

> Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker

Can you confirm this on manual install as well? (Asking as your command is specific to docker)

**Comment by rli-rms** [comment]
@t-book  I tried to transfer my old customized files to a fresh geonode-project, and the problem was gone. So I guess it is because the files I used had some compatibility issues with the current geonode. I will close this issue. Thanks!
