### ISSUE TITLE
updatelayers cannot find any layers in geoserver

### ISSUE THREAD

**Issue by GeoTob** [GeoNode/geonode#4655]
## Expected Behavior
`./manage.py updatelayers` updates GeoNode with layers stored in GeoServer.

## Actual Behavior
`./manage.py updatelayers` finds no layers in GeoServer, complete no-op.

## Steps to Reproduce the Problem
  1. Run GeoNode master with anny commit after `92ed66c7d6e20147414e9a28a3f63f43ba0b76fd`
  2. Run `./manage.py updatelayers`

## Specifications
  - GeoNode version: master #c1dfb4d334248c22e1302a623bc55e682a84d6fe 
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual/docker
  - Platform: Ubuntu
  - Additional: There's no logging output or useful information I can share:(

## Cause
The library switch to "geoserver-restconfig" #4639 has introduced a regression or an undocumented setting. Previous commits work fine.

**Comment by t-book** [comment]
Do you pass in correct settings?

**Comment by GeoTob** [comment]
I don't know? Downgrading to pre-`92ed66c7d6e20147414e9a28a3f63f43ba0b76fd` works fine, as soon as we upgrade it breaks. Have the settings / env variables changed?

**Comment by t-book** [comment]
... looks more like a regression. My idea was if django by chance uses a wrong backend which could be solved by prepending the correct settings before manage.py 
`DJANGO_SETTINGS_MODULE=yourgeonode.local_settings ./manage...`

**Comment by t-book** [comment]
Might be caused by? https://github.com/GeoNode/geonode/commit/92ed66c7d6e20147414e9a28a3f63f43ba0b76fd

**Comment by GeoTob** [comment]
Right, definitely using same environment, settings and command unfortunately:

bd2593e9eee67de19026a8b03aa666a024de80e4 - works
92ed66c7d6e20147414e9a28a3f63f43ba0b76fd - breaks

**Comment by t-book** [comment]
Do you get any logs? from geoserver?

**Comment by GeoTob** [comment]
Not even a request in Tomcat's access log,

**Comment by t-book** [comment]
That's more than nothing :)

**Comment by t-book** [comment]
And you did update the packages with `pip install -r requirements --upgrade` ?

**Comment by GeoTob** [comment]
Yes. It's a clean dockerised installation from git checkout every time, so no old packages in the system.

**Comment by afabiani** [comment]
@GeoTob @t-book you need to specify the workspace

`manage.py updatelayers -w geonode`

**Comment by GeoTob** [comment]
@afabiani thanks, can confirm this works. 

Should we make `-w` a required flag for the `updatelayers` command, or is there a use for running it without a workspace specified?

**Comment by afabiani** [comment]
@GeoTob let's maybe open a "feature" issue for that specific functionality
