### ISSUE TITLE
When DEBUG=False configured remote services should be PROXY ALLOWED

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4656]
Setting DEBUG=False enforces the internal GeoNode proxy security by checking for hosts present into PROXY_ALLOWED_HOSTS.

## Expected Behavior
If a Remote Service has been defined by a user, it should be accepted by the internal Proxy.

## Actual Behavior
Any url not statically defined into the PROXY_ALLOWED_HOSTS list is denied.

## Steps to Reproduce the Problem

  1. Set DEBUG=False
  2. Create a new Remote Service and import a resource
  3. Try to print the layer

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

**Comment by jonnyforestGIS** [comment]
Hi @afabiani I have this problem in 3.1.
My steps:
Add a remote Service: http://si.icnf.pt/geoserver/ows
Choose a layer : corredores_ecologicos

Create a map with this layer;
Print - > Give me the error of this issue.

Can you confirm if this persists?
