### ISSUE TITLE
Double message on Submit when invite users to join geonode

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4659]
## Expected Behavior
Sending an invitation shows just one message

## Actual Behavior
Sending an invitation shows two messages, the second one misleading

## Steps to Reproduce the Problem

  1. Try to send an invitation to a non registered email from GeoNode gui

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: none

**Comment by t-book** [comment]
ref.: https://github.com/bee-keeper/django-invitations/issues/74
