### ISSUE TITLE
Replace Layer functionality incomplete/broken

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4661]
## Expected Behavior
* Replacing a raster layer with another one, overwrites the previous one
* Replacing a vectorial layer with an updated version of the same table, overwrites the previous one
* Replacing a vectorial layer with an **incompatible** one, prevents the user to replace it with a meaningful error message
      - **incompatible**: means different `geometry` and `schema`
* Remote Layers cannot be replaced in any case

## Actual Behavior
* Replacing a raster layer with another one, overwrites the previous one
* Replacing a vectorial layer with an updated version of the same table, overwrites the previous one - sometimes throws an exception (see details below)
* Replacing a vectorial layer with an incompatible one, fails
* Remote Layers cannot be replaced in any case

## Steps to Reproduce the Problem

  1. Open a Layer detail page
  2. Editing Tools > Replace Layer

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: Experienced a weird exception trying to replace a vectorial layer

`Traceback (most recent call last): File "/home/geosolutions/geonode/geonode/layers/views.py", line 1295, in layer_replace charset=form.cleaned_data["charset"], File "/home/geosolutions/geonode/geonode/layers/utils.py", line 655, in file_upload layer.save() File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/polymorphic/models.py", line 83, in save return super(PolymorphicModel, self).save(*args, **kwargs) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 808, in save force_update=force_update, update_fields=update_fields) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/db/models/base.py", line 848, in save_base update_fields=update_fields, raw=raw, using=using, File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 193, in send for receiver in self._live_receivers(sender) File "/home/geosolutions/geonode/geonode/decorators.py", line 53, in wrapper return func(*args, **kwargs) File "/home/geosolutions/geonode/geonode/geoserver/signals.py", line 85, in geoserver_post_save producer.geoserver_upload_layer(payload) File "", line 2, in geoserver_upload_layer File "/home/geosolutions/geonode/geonode/messaging/producer.py", line 71, in sync_if_local_memory worker.run(timeout=broker_socket_timeout) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/mixins.py", line 170, in run for _ in self.consume(limit=None, **kwargs): File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/mixins.py", line 192, in consume conn.drain_events(timeout=safety_interval) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/connection.py", line 315, in drain_events return self.transport.drain_events(self.connection, **kwargs) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 963, in drain_events get(self._deliver, timeout=timeout) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get return self.fun(resource, callback, **kwargs) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 1001, in _drain_channel return channel.drain_events(callback=callback, timeout=timeout) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 745, in drain_events return self._poll(self.cycle, callback, timeout=timeout) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 402, in _poll return cycle.get(callback) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/utils/scheduling.py", line 56, in get return self.fun(resource, callback, **kwargs) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 406, in _get_and_deliver callback(message, queue) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 983, in _deliver callback(message) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py", line 633, in _callback return callback(message) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/messaging.py", line 624, in _receive_callback return on_m(message) if on_m else self.receive(decoded, message) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/kombu/messaging.py", line 590, in receive [callback(body, message) for callback in callbacks] File "/home/geosolutions/geonode/geonode/messaging/consumer.py", line 104, in on_geoserver_messages geoserver_post_save_local(layer) File "/home/geosolutions/geonode/geonode/geoserver/signals.py", line 140, in geoserver_post_save_local charset=instance.charset) File "/home/geosolutions/geonode/geonode/geoserver/upload.py", line 204, in geoserver_upload cat.save(gs_resource) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/geoserver/catalog.py", line 241, in save message = obj.message() File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/geoserver/support.py", line 202, in message self.serialize(builder) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/geoserver/support.py", line 197, in serialize writer(builder, self.dirty[k]) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/geoserver/support.py", line 125, in write bbox_xml(builder, b) File "/home/geosolutions/.virtualenvs/geonode/local/lib/python2.7/site-packages/geoserver/support.py", line 248, in bbox_xml builder.end("minx") File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1445, in end self._flush() File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1402, in _flush text = "".join(self._data) TypeError: sequence item 0: expected string, int found`

**Comment by t-book** [comment]
hi @afabiani unfortuantely I cannot reproduce this behavior. Have tested with several shapes for example http://master.demo.geonode.org/layers/geonode:tiger_roads0
Could you provide your test file?

**Comment by t-book** [comment]
tested:

- Open a Layer detail page
- Editing Tools > Replace Layer

**Comment by t-book** [comment]
@afabiani Have it. Please ignore the question about test data. Could reproduce it when replacing a layer with a completely different shape.
