### ISSUE TITLE
How to change the zoom 

### ISSUE THREAD

**Issue by Hissroth** [GeoNode/geonode#4690]
Hello,

I'm actually working on geonode for a company as an internship, one of my mission is to change the basic zoom. They'd like to have a zoom on a specific region instead of having a global view of the map. For this I need to change the zoom level and the position of it but I don't know where to find this function in all this files. 
Hope you will be able to help me with this.
 
Thanks,

  - GeoNode version: Geonode 2.8
  - Platform: Virtual Machine Ubuntu16.04

**Comment by t-book** [comment]
Hi @Hissroth your question might fit better at the osgeo user list https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users

Also, it would be good to say if you're using geoexplorer or mapstore as viewer. for geoexplorer most likely you need to change/overwrite some logic. 

Unfortunately, I do not have the chance to take a closer look so take this vague guess with caution:

The extent should be defined by an array, https://github.com/GeoNode/geoexplorer/blob/geonode-geoexplorer/app/static/script/app/GeoExplorer.js#L259
which is most likely populated from a Django view here https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L353. Hackish but if you really need you could overwrite the bounding to be static. **But I would not advise this at all as it would apply to all layer resources.**

Possible that I misunderstand your issue. but isn't it by default that the map zoom to the layer extent? I remember darkly a bug with a wrong srid in early 2.8. So a better advice is: Test the latest version here http://master.demo.geonode.org and if this solves your issue update your instance.
