### ISSUE TITLE
url problem redirection using catalogue search

### ISSUE THREAD

**Issue by frayber** [GeoNode/geonode#4697]
Hi to all,
we have a problem with geonode. In the catalogue building maps (see attachment file) when we click on search the call returns a 500 http error...
![Immagine](https://user-images.githubusercontent.com/3877617/61717078-ad736f80-ad60-11e9-9a6d-b2b495b5c005.png)

We have configured apache as reverse proxy for geoserver following the installation guide. Apache is listening on port 80. How should be the correct url to call and in which files we have to change the parameters to avoid the 500 http error? Maybe we have to change localhost and port? 

In the apache logs we have the following error...
ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /catalogue/csw?service=CSW&version=2.0.2&request= (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f657b13ce50>: Failed to establish a new connection: [Errno 111] Connection refused',))

Enviroment 
Apache/2.4.18
tomcat8 
Python 2.7.12
Geonode 2.10
Geoserver 2.14.3
installation method:manual (https://training.geonode.geo-solutions.it/002_install_and_admin/002_geonode_install/index.html)
OS: Ubuntu 16.04

**Comment by t-book** [comment]
Hi, can you check your settings here: https://github.com/GeoNode/geonode/blob/master/geonode/local_settings.py.geoserver.sample#L78-L94

Also I would advise to use the latest install docs http://docs.geonode.org/en/2.10.x/install/core/index.html

As this issue is not a bug but more about configuration it would fit better at the user/dev list ;)

**Comment by frayber** [comment]
Hi, we solved editing the file /home/geo/Envs/geonode/lib/python2.7/site-packages/geonode/settings.py and replacing all occurences of "localhost" with domain name. 
I didn't find this in any documentation.
In this way proxy in url ( /proxy/?url=http://localhost:8080/geoserver/.... ) now points to domain name instead of localhost ( http://vm-lxgeonode.comune.genova.it/proxy/?url=http://domain.name:8080/geoserver/pdf/info.json?access_token=xxx ) and all it works.
Thank you

**Comment by t-book** [comment]
@frayber  great, just for clarification. You find it in docs here: http://docs.geonode.org/en/2.10.x/install/core/index.html#update-the-settings-in-order-to-update-geonode-and-geoserver-services-running-on-a-public-ip-or-hostname

the difference is, the suggested setup uses env vars to set the urls. In your case you should use local_settings over settings.py

best regards,

toni

**Comment by frayber** [comment]
Ok, thank you!
