### ISSUE TITLE
French translation is not updated

### ISSUE THREAD

**Issue by kikislater** [GeoNode/geonode#4704]
## Expected Behavior
Good translation and update from transifex

## Actual Behavior
Missing chain or bad translation

## Steps to Reproduce the Problem

  1. Switch to French

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): All
  - Platform: Archlinux
  - Additional details:

**Comment by kikislater** [comment]
I will update this week, please don't close

**Comment by afabiani** [comment]
Thanks @kikislater
