### ISSUE TITLE
'paver sync' fails with 'django.db.utils.DatabaseError: relation "layers_topiccategory" does not exist'

### ISSUE THREAD

**Issue by cspanring** [GeoNode/geonode#471]
apparently south is trying to run '0008_auto__add_field_map_category.py' before layers is migrated, therefore 'layers_topiccategory' doesn't exist at this point.

**Comment by abersh** [comment]
Hi matthewhanson !!! when i connecct geonode to postgresql but i open pgadmin 3 it says "no properties are available for the current selection" how fix it

**Comment by capooti** [comment]
Hi @abersh 
I believe that your problem is not a bug, but a configuration issue not related to GeoNode, so you'd better ask in the PostgreSQL list.
Also, asking question like this, should be addressed to users mailing list. This is not the correct place, as it is the GeoNode issue tracker.

**Comment by abersh** [comment]
ok 10Q !!! it works
