### ISSUE TITLE
Attributes are not added in layers_attributes table when a layer is uploaded

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4713]
## Expected Behavior

A shapefile is uploaded to GeoNode. If the layer is successfully uploaded, there must be one record in the layers_attributes table of each shapefile field.

## Actual Behavior

Randomly the attributes are not created. When this is happening I am observing that the problem seems occurring at this line: 
https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/helpers.py#L915

```python
req, body = http_client.get(dft_url)
```

checking the body value after this line when the error is occurring this is what I see:

```
<?xml version="1.0" ?>
<ServiceExceptionReport
   version="1.2.0"
   xmlns="http://www.opengis.net/ogc"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://www.opengis.net/ogc
http://schemas.opengis.net/wfs/1.0.0/OGC-exception.xsd">
   <ServiceException code="InvalidParameterValue">
      Could not find type: {http://www.geonode.org/}subwaylines_p_odp_4
</ServiceException></ServiceExceptionReport>
```

It looks like a problem of GeoNode/GeoServer communication. In our case everything works well with GeoNode/GeoServer interaction (data edit, style edit ecc) but this is still randomly occurring.

## Steps to Reproduce the Problem

Can't provide a specific sequence of steps. This is occurring randomly on 3 different instance we administer.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04 LTS
  - Additional details:

**Comment by capooti** [comment]
@afabiani until we cannot find a solution to this, how about if I send a PR with attributes synced from GDAL on layer upload?

**Comment by afabiani** [comment]
@capooti so your idea would be to dump the attributes list by using GDAL?

**Comment by capooti** [comment]
@afabiani would it be a big work to include attributes in the layer definition from the GeoServer REST endpoint? that way we could use gsconfig for the purpose
Using gdal is more complicated particularly once the layer is already uploaded to GeoNode
Any idea why the HttpClient would fail? I am struggling why that is happening

**Comment by capooti** [comment]
by the way @afabiani I noticed demo is also affected: https://dev.geonode.geo-solutions.it/layers/geonode:roads0#/

I must definitely fix this in the next few days, so if you have any ideas please let me know before I start doing some deep debugging.

**Comment by afabiani** [comment]
@capooti this functionality may help us to both debug the issue and improve the existing upload method to compute attributes

![image](https://user-images.githubusercontent.com/1278021/62987016-41a39480-be3e-11e9-961c-3eaba42960c0.png)

Also, be careful that in any case GeoNode won't be able (I guess) to fetch the attributes from Remote Layers.

**Comment by capooti** [comment]
@afabiani yes, this is only for internal vector layer. I have the following idea: how about having a fallback method which run in place of the original (set_attributes_from_geoserver) if the layer is a PostGIS layer? In which case we can easily synchronize using psycopg2 istead than relying on GeoServer. Let me know your thoughts about it.
