### ISSUE TITLE
Updatelayers fails to assign GeoFence rules if permissions parameter is empty.

### ISSUE THREAD

**Issue by tomasjuanlink** [GeoNode/geonode#4717]
## Expected Behavior
A layer is created in GeoServer, with an external system. Updatelayers command is executed, passing **filter** and **owner** parameters, from command-line OR via API call. Then, GeoNode creates a layer, assign permissions and syncronize with GeoFence, creating rules for the owner and that layer.

## Actual Behavior
GeoNode creates a layer, but no GeoFence rules are assigned to the layer. As a consequence, the owner can't view the layer correctly from GeoNode. 

## Steps to Reproduce the Problem

  1. Create a user "user" in GeoNode
  2. Create layer with name "layer_name" in GeoServer without using GeoNode
  3. Execute updatelayers -f "layer_name" -u "user"

## Specifications

  - GeoNode version: 2.10rc5. commit: 3a6ebefc6f4b554564fbc2a06ad1d7b3ae89a3c8
  - Installation method: virtualenv, paver. 
  - Platform: Ubuntu 18. 
  - Additional details:

After some research and debug, I found the root of the problem: 
Updatelayers calls the method [gs_slurp](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/geoserver/helpers.py#L516). In there, after creating the Layer in GeoNode, permissions and GeoFence rules [are created](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/geoserver/helpers.py#L629). But later, when the ["permissions" parameter is checked](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/geoserver/helpers.py#L663) and is empty, the [set_default_permissions](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/security/models.py#L118) method is called. Inside that method, [all geofence rules are erased](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/security/models.py#L123), but never created again. 

In my case, i'm using the updatelayers remotely, using this [endpoint](https://github.com/GeoNode/geonode/blob/e4a4ecd16cc1a5372ef4d22fd11edfb1c25ddbd6/geonode/geoserver/views.py#L80) that for the moment doesn't handle the parameter "permissions", so i'm never sending anything there. I also tested calling updatelayers from the command-line, without sending either the permissions parameter, and the behaviour is the same. A workaround for me was to comment altogether the line that calls "set_default_permissions", because I don't think that method does anything useful for me. 

I didn't test if using the command-line updatelayers AND passing the permissions parameter, the behaviour is the expected.

**Comment by tomasjuanlink** [comment]
Why was this closed?

**Comment by afabiani** [comment]
Please update to 2.10 or 2.10.1
