### ISSUE TITLE
Simultaneously event login and logout error

### ISSUE THREAD

**Issue by lolob** [GeoNode/geonode#4719]
Specifications
  - GeoNode version: 2.10
  - Installation method : manual (then django-project)
  - Platform: Ubuntu 16.04
  - Geoserver: 2.14.snapshot
  - Postgres: 9.5

I cannot login. Once login, geonode will logout automatically. Simultaneously event as shown in the picture below.

![error](https://user-images.githubusercontent.com/15963902/62414693-8ca8f500-b651-11e9-9d8e-14d675eecd54.png)

**Comment by t-book** [comment]
Hi, can you please check your settings file for:

`ACCESS_TOKEN_EXPIRE_SECONDS = int(os.getenv('ACCESS_TOKEN_EXPIRE_SECONDS', '86400'))`

**Comment by t-book** [comment]
Further, please be sure that fixtures have been imported successfully: https://github.com/GeoNode/geonode-project/issues/78

**Comment by lolob** [comment]
@t-book I got the answer! Now I can login.
I run this `'paver sync'` in the `geonode-project-template`

**Comment by t-book** [comment]
great, that's it! paver sync import the fixtures which might have been missing (see comment above). closing here.
