### ISSUE TITLE
Please add OGC CSW-T documentation

### ISSUE THREAD

**Issue by kikislater** [GeoNode/geonode#4732]
## Expected Behavior
A POST request should allow to send metadata as it's a standard OGC service. Please provide instructions to send similar operation to Geonode pycsw like we can find in official pycsw documentation here : https://pycsw.org/faq/#how-can-i-make-csw-post-xml-requests

## Actual Behavior

Do not pass credential authorization : 
```
<ows:ExceptionText>Transaction (insert) failed: 'GeoNodeRepository' object has no attribute 'session'.</ows:ExceptionText>
```

## Steps to Reproduce the Problem

  1. Allow CSW-T in local_settings.py with :

```
        'manager': {
            # authentication/authorization is handled by Django
            'transactions': 'true',
            'allowed_ips': '*',
            # 'csw_harvest_pagesize': '10',
        }, 
```
 
  2. 
```
curl -X POST -d @./CSW-Transaction-Insert.xml https://<user>:<pass>@<host>/catalogue/csw
```

or 

```
curl -X POST -d "grant_type=password&username=<user>&password=<pass>" @./CSW-Transaction-Insert.xml http://<host>/catalogue/csw
```

  3. cat CSW-Transaction-Insert.xml 

```
<?xml version="1.0" encoding="UTF-8"?>
<csw:Transaction
        version="2.0.2"
        service="CSW"
        xmlns:csw="http://www.opengis.net/cat/csw/2.0.2">
  <csw:Insert typeName="csw:Record">
    <csw:Record
        xmlns:ows="http://www.opengis.net/ows"
        xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
        xmlns:dc="http://purl.org/dc/elements/1.1/"
        xmlns:dct="http://purl.org/dc/terms/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <dc:identifier>12345</dc:identifier>
      <dc:title>Null Island</dc:title>
      <ows:BoundingBox crs="urn:x-ogc:def:crs:EPSG:6.11:4326">
        <ows:LowerCorner>0 0</ows:LowerCorner>
        <ows:UpperCorner>0 0</ows:UpperCorner>
      </ows:BoundingBox>
    </csw:Record>
  </csw:Insert>
```

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPC
  - Platform: Archlinux
  - Additional details: CSW-T already implemented as seen here => https://github.com/GeoNode/geonode/issues/2467

**Comment by gannebamm** [comment]
I am not sure but I think the described behaviour is created by this passing instead of doing anything:

https://github.com/GeoNode/geonode/blob/master/geonode/catalogue/backends/pycsw_local.py#L70
