### ISSUE TITLE
Layer post_save deletes links to external thumbnails / data

### ISSUE THREAD

**Issue by GeoTob** [GeoNode/geonode#4739]
## Expected Behavior
When saving a layer, existing links should only be updated / deleted if required.

## Actual Behavior
When saving a layer, links to external data such as thumbnails stored on a static file host are deleted.

## Steps to Reproduce the Problem

  1. Set a layer's thumbnail link to an external image through the admin panel
  2. Save the layer through the admin panel
  3. Thumbnail is deleted

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual docker
  - Platform: ubuntu
  - Additional details:

## Reasons
After saving a layer, the `resourcebase_post_save` signal is triggered. It deletes any links that do not point to the same host as our GeoNode instance: https://github.com/GeoNode/geonode/blob/c999687067750c0647da5121c9783d8c1a97fbf7/geonode/base/models.py#L1412-L1424

I'm not entirely sure why this behaviour exists, so I'm hesitant to submit a pull request. I think having external resources is a very valid scenario, but there may be a reason for deleting links to external hosts?

**Comment by afabiani** [comment]
@GeoTob we need to try to understand which was the original intent of this code. At first glance, I agree with you. It doesn't seem to make much sense to delete the old links.
Maybe this was introduced to keep the server IP/name consistent?
