### ISSUE TITLE
Add legend to map

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4755]
## Expected Behavior
Map shows legend

## Actual Behavior
No legend

## Steps to Reproduce the Problem

  1. From [Explore maps](http://master.demo.geonode.org/maps/) page, click **View map** for any map
  2. There is no legend to explain the symbols used in the map's layers

## Specifications

  - GeoNode version: 2.10.1 (at [master.demo](http://master.demo.geonode.org))

**Comment by jondoig** [comment]
As @afabiani pointed out, the legend is there in the TOC, but hidden by default:

![image](https://user-images.githubusercontent.com/4666409/63412894-f724a800-c43b-11e9-954f-a534305f12dd.png)

Is it intuitive though? I didn't see it. To me that < icon is a far from intuitive symbol for expand/collapse.

Maybe set it open by default?

And reverse the direction to point right not left?

**Comment by t-book** [comment]
So from last comment of @jondoig  this issue would fit better in mapsotre2 issues, right? If so (@afabiani )  can we move it?

**Comment by jondoig** [comment]
Tested current useability with two other GIS/map users: same result. They couldn't find the legend, and when pointed out, agreed with my suggestions above.

**Comment by afabiani** [comment]
Yes, let's open an issue to the geonode-mapstore-client repo related to this.
I would keep this open for a bit though.

**Comment by jondoig** [comment]
> Yes, let's open an issue to the geonode-mapstore-client repo related to this.
> I would keep this open for a bit though.

If I could find an issues tab on [geonode-mapstore-client](https://github.com/geosolutions-it/geonode-mapstore-client) I'd add it there.

 I reckon the main thing is to default to showing symbols for all layers.

I.e. initial view:

![image](https://user-images.githubusercontent.com/4666409/67727238-b39e7980-fa3c-11e9-9c50-fee9db1f8bf0.png)

**Comment by afabiani** [comment]
@jondoig the official repo is https://github.com/GeoNode/geonode-mapstore-client

**Comment by jondoig** [comment]
Can close this, has been transferred to [geonode-mapstore-client issue #29](https://github.com/GeoNode/geonode-mapstore-client/issues/29)

**Comment by Nicholas1K** [comment]
Hi, I can't figure out how to change the text written in the legend, could someone kindly explain it to me?
