### ISSUE TITLE
"[Object object]" Javascript message on Connection Reset

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4765]
## Expected Behavior
Provide a meaningful/human readable error message.

## Actual Behavior
"[Object object]" Javascript error

## Steps to Reproduce the Problem

  1. Start uploading a file
  2. Force a connection reset

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: This kind of error occurs whenever somehow the backend returns an empty response. In general, the frontend side JavaScript should be able to be more resilient to this, intercept the special case and return a meaningful message to the user.

**Comment by t-book** [comment]
Unfortunately, I cannot reproduce the [object Object] by now but would like to add a similar case.

1. Shutdown GeoServer during upload.

**What should happen**
The User should get a meaningful error message.

**What happens**
No message.

**Solution**
Catch  errors most likely when polling:

https://github.com/GeoNode/geonode/blob/99c548e8636a31fc70b2a3f2dad8a74b48f350bb/geonode/static/geonode/js/upload/LayerInfo.js#L399-L407
