### ISSUE TITLE
Get rid of deprecated "Publish local map layers as WMS layer group"

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4772]
**Is your feature request related to a problem? Please describe.**
There's a very old functionality related to maps, "Publish local map layers as WMS layer group", which is not working for a long time. This is also not really used (as far as I know) nor really useful itself.

**Describe the solution you'd like**
I would like to get rid of this functionality as it is implemented right now. Maybe re-think it and propose a detailed GNIP along with real-life use cases.

**Additional context**
In order to avoid possible conflicts with old versions, we can safely remove it from the map templates and declare the associated view as "deprecated".

I did few tests recently, and I confirm it is not working. Moreover, even if it could work somehow, there is no way to get or use bask the Layer Group which is supposed to be published in GeoServer.

**Comment by capooti** [comment]
thanks @afabiani
