### ISSUE TITLE
Removing a layer is broken - Celery error

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4813]
## Expected Behavior

When removing a layer using the "Remove layer" tool, the layer should be removed.

## Actual Behavior

I see a celery error in log:

```
Traceback (most recent call last):
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/layers/views.py", line 1352, in layer_remove
    result.wait(10)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/celery/result.py", line 224, in get
    on_message=on_message,
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 476, in wait_for_pending
    no_ack=no_ack,
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/celery/backends/base.py", line 779, in _is_disabled
    raise NotImplementedError(E_NO_BACKEND.strip())
NotImplementedError: No result backend is configured.
Please see the documentation for more information.
```

## Steps to Reproduce the Problem

This can be reproduced using standard GeoNode from master.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

**Comment by t-book** [comment]
Unfortunately, I have to add two more regressions. With local dev server deleting a map fails as well. Further, the documents upload dialog is stuck as /documents/upload keeps pending state

**Comment by afabiani** [comment]
Could be a side effect of the dependency upgrade. We might consider to downgrade. I'll take a look at the issue anyway.

**Comment by t-book** [comment]
thanks @afabiani Just checked-out https://github.com/GeoNode/geonode/commit/e65825790e44d44122673712f382eaa2d35a74f1 same behavior.  

```
/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/license */
/*! Select2 Version: 3.5.4 Timestamp: Sun Aug 30 13:30:32 EDT 2015 */
```

Unfortunately, I'm already off from office (-> the next days) and cannot be of much help. :/

**Comment by afabiani** [comment]
@t-book I was referring to Celery version upgrade from dependabot, will let you know my findings.

**Comment by afabiani** [comment]
by the way, I'm not currently experiencing those issues on master.demo instance and our dev instance. Anyway, the investigation continue

**Comment by t-book** [comment]
> by the way, I'm not currently experiencing those issues on master.demo instance and our dev instance. Anyway, the investigation continue

both are docker . (I think @capooti uses manual – me dev setup)

Just gone back to : https://github.com/GeoNode/geonode/blob/0cb87a29b97c9f9d1c28399fcc4df5dc17b096a7/requirements.txt

same behavior.  But haven't reset hard yet so there is a fair chance my tests are not 100% reliable.

**Comment by afabiani** [comment]
@t-book @capooti any chance to test this PR https://github.com/GeoNode/geonode/pull/4817 ?

Moreover, concerning this specific issue, I'm not completely sure it is related to a problem. It seems more like a configuration issue.
@capooti  are you using async? Did you configured correctly the celery broker and broker result on settings?

**Comment by capooti** [comment]
@afabiani I use manual setup and running GeoNode master without using a GeoNode project. Once this kind of setup was working by scratch, without need to set any variable. Is there such a need now? Will look into your PR today and let you know.
@t-book what do you mean with dev setup?

**Comment by afabiani** [comment]
@capooti it should not unless you maybe use a backend not supported by default settings.

**Comment by capooti** [comment]
no, as said I am using vanilla GeoNode from master. ASYNC_SIGNALS is False, but still getting that error. I noticed that ASYNC_SIGNALS will still used Celery, but using memory (which is confusing in my opinion, Celery shouldn't be used at all in that case). I believe that even when using memory CELERY_RESULT_BACKEND should be set (now it is set only if ASYNC_SIGNALS) and tried to do it but this don't fix the error. Now having a look at your PR

**Comment by capooti** [comment]
@afabiani @t-book the PR for me is working (both for deleting layers and maps), +1 to merge

**Comment by t-book** [comment]
> @t-book what do you mean with dev setup?

@capooti django runserver (paver)

**Comment by t-book** [comment]
> @t-book @capooti any chance to test this PR #4817 ?

@afabiani  Sorry I 've been off for some days. But it looks it is already solved. Thanks a lot!
