### ISSUE TITLE
 Change Tomcat installation to NGINX

### ISSUE THREAD

**Issue by MatheusXimeness** [GeoNode/geonode#4859]
**Describe the bug**

In my GeoNode installation process, I encounter a problem when trying to change tomcat installation to NGINX. In this step, the URL goes from
`http://localhost:8000` and ` http://localhost:8080/geoserver/`
for
`http://localhost/` and `http://localhost/geoserver/`
But only
`http://localhost/geoserver/`
it works. When i'm trying to go the way i get 
`Unable to access this site`

**Questions around this bug**

Does anyone have any help solving this problem or have had similar experience?

**Motivation**

I think a lot of people could have the same problem

To know more details:
_matheus.ximenes2016@outlook.com_

**Comment by t-book** [comment]
Hi @MatheusXimeness This is a question about general configuration which should be discussed at the user list https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users. 

In case you've correctly configured nginx, you might miss correct settings in settings.py or local_settings.py to tell Django to listen on a different port.

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L728-L731

**Comment by t-book** [comment]
Closing here. In case of questions let's continue at the list.
