### ISSUE TITLE
Auto-reload on SPCGeonode

### ISSUE THREAD

**Issue by GDLChiara** [GeoNode/geonode#4876]
Hi Everyone, 
I'm working on Ubuntu 18.04 with SPCGeonode. 
At the moment I'm starting to customize the Geonode installation, changing css, templates, adding images... 
**MY QUESTION:** Is there a way to enable the auto-reload without having to relaunch all the time the docker service?  

I actually run this command: 
`docker-compose up --build -d django geoserver postgres nginx`
as suggested [here](http://docs.geonode.org/en/2.10.x/install/spc/index.html#development).

In the "[Customise  the look and feel](http://docs.geonode.org/en/2.10.x/basic/theme/index.html#theming-your-geonode-project)" section of the documentation, this code is pointed out:

> $ cd /home/geonode
$ sudo rm -Rf geonode/geonode/static_root/*
$ cd my_geonode
$ python manage.py collectstatic
$ sudo service apache2 restart

but actually it's not clear for me. There's a "static" folder under the "geonode" folder, but if I remove recursively the directories and their contents, how can I then browse a folder within it. And btw if we remove the entire content, this means that folder will be regenerated runtime? Right? (I'm trying to understand).
Supposing that "my_geonode" folder is the same of /home/geonode (the root of  the geonode installation I suppose) my "manage.py" does not contain a "collectstatic" command. 
(Actually I run it with python3  `python3 manage.py help`). The last line simply fails.

Am I missing something? Maybe this suggestion was for a traditional geonode installation and not for the dockerized one?

Feel free to give me all the suggestions and tips you think I need :)

Thanks in advance for your help :+1:

**Comment by francbartoli** [comment]
> Hi Everyone,
> I'm working on Ubuntu 18.04 with SPCGeonode.
> At the moment I'm starting to customize the Geonode installation, changing css, templates, adding images...
> **MY QUESTION:** Is there a way to enable the auto-reload without having to relaunch all the time the docker service?
> 
> I actually run this command:
> `docker-compose up --build -d django geoserver postgres nginx`
> as suggested [here](http://docs.geonode.org/en/2.10.x/install/spc/index.html#development).
> 
> In the "[Customise the look and feel](http://docs.geonode.org/en/2.10.x/basic/theme/index.html#theming-your-geonode-project)" section of the documentation, this code is pointed out:
> 
> > $ cd /home/geonode
> > $ sudo rm -Rf geonode/geonode/static_root/*
> > $ cd my_geonode
> > $ python manage.py collectstatic
> > $ sudo service apache2 restart
> 
> but actually it's not clear for me. There's a "static" folder under the "geonode" folder, but if I remove recursively the directories and their contents, how can I then browse a folder within it. And btw if we remove the entire content, this means that folder will be regenerated runtime? Right? (I'm trying to understand).
> Supposing that "my_geonode" folder is the same of /home/geonode (the root of the geonode installation I suppose) my "manage.py" does not contain a "collectstatic" command.
> (Actually I run it with python3 `python3 manage.py help`). The last line simply fails.
> 
> Am I missing something? Maybe this suggestion was for a traditional geonode installation and not for the dockerized one?

That's the point.

> 
> Feel free to give me all the suggestions and tips you think I need :)
> 
> Thanks in advance for your help 👍

If you are customising I'd suggest to look at https://github.com/GeoNode/geonode-project. However I'm not quite sure SPCGeonode already support it.

**Comment by t-book** [comment]
Hi @GDLChiara  Even if it's a bit outdated have you seen the README of the original Repo?

https://github.com/olivierdalang/SPCgeonode#development
and
https://github.com/olivierdalang/SPCgeonode#developpement-vs-production

from what I read SPC should support auto-reload.  However, as @francbartoli pointed out it might expect to work with the core branch instead of geonode_project. The later exists in case you like to customize the look and feel without changing the core. (Some of us  change templates directly at a core level but you have to feel confident with git rebase to do so).

If all you want is changing the logo, colors, welcome banner have a look at the Django admin where you will find a theming option

 
<img width="737" alt="Bildschirmfoto 2019-09-12 um 08 57 46" src="https://user-images.githubusercontent.com/20478652/64761189-c7008e80-d53b-11e9-8bc2-24de8ef0aec1.png">

**Comment by t-book** [comment]
( By the way. Github issues are meant for bugs. I would suggest to subscribe at https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users and ask for help )

**Comment by francbartoli** [comment]
Ah good point @t-book, I never remember that option with themes library. Thanks!

**Comment by GDLChiara** [comment]
Thanks for your suggestions and your help, @t-book and @francbartoli
