### ISSUE TITLE
GNIP-69 Update Bootstrap to version 4

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4901]
# GNIP 69 - Update Bootstrap to version 4

## Overview

We’re currently using bootstrap 3.4 (active LTS Start 2014-11-01) which has reached EOL 
and will therefore no longer get updates/security fixes.

https://github.com/twbs/release 
https://blog.getbootstrap.com/2019/07/24/lts-plan/ 

This proposal is intended to update from version 3 to 4.

### A brief overview of what we get
- Security Fixes (XSS vulnerabilities pop up quite often)
- Cards https://coreui.io/docs/components/cards/ <https://coreui.io/docs/components/cards/> (Could be useful for featured maps)
- A more advanced Grid System
- All JS Plugins use ES6
- Flexbox
- Reboot instead of Normalize.css
- Better Variable handling (Vars are not split around severals files anymore)
- Rem instead of px. (more scalable)
- New breakpoints

### A brief overview of what we loose
- LESS > SASS  (This is a pro IMHO)
Bootstrap 4 moved from LESS to SASS.
Conversion of less files is needed
- Browser Support
Version 4 does not support Internet Explorer 8, 9, and iOS 6 anymore!
Coverage https://browserl.ist/?q=ie+8-9

- Dropped Glyphicons
Bootstrap no longer includes Glyphicons. Instead, you’re advised to find your own favorites and include them in whichever way you see fit.
F.e.: https://useiconic.com/open/ or https://octicons.github.com/

### Proposed By

t-book, Toni Schönbuchner

### Assigned to Release

This proposal is for GeoNode master, 2.10.
Fourth quarter of 2019

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Among others, the safety aspect is the biggest driver of an update.

## Proposal

- We've setup some visual regression tests to keep the styling impact as low as possible. https://github.com/csgis/geonode_visual_regression
One can create screenshots as reference images which get compared to screenshots taken after styling changes

- Less files need to be converted to sass
- CSS files should be converted to sass where possible (Take into account: DEBUG_STATIC=True ) 
- Templates need to be updated regarding new Bootstrap classes and simplified markup

### Backwards Compatibility

- As several classes have changed the template markup must be reworked. It is expected that users who are using geonode-project might have to update their templates.

## Future evolution

I intend two more improvements based on this one
- Feature Issue: Better user experience on mobile devices
- GNIP: RTL Support 

## Voting

Project Steering Committee:

* Alessio Fabiani: [ ✔]
* Francesco Bartoli:  [ ✔]
* Olivier Dalang: 
* Paolo Corti:  [ ✔]
* Simone Dalmasso:

## Links

* [Mail Discussion]( https://lists.osgeo.org/pipermail/geonode-devel/2019-September/002928.html )

**Comment by capooti** [comment]
hi @t-book are you planning to work on this or it is just a GNIP for now?

**Comment by t-book** [comment]
@capooti I'm planning to work on it.

**Comment by t-book** [comment]
This is half-finished but postponed from the client to early 2020.

**Comment by t-book** [comment]
Unfortunately, the sponsor/client has jumped of ;/ 
I'm considering finishing this GNIP at upcoming code sprint.
