### ISSUE TITLE
Allow links from Document to any ResourceBase derived type

### ISSUE THREAD

**Issue by caipirginka** [GeoNode/geonode#4902]
Currently it is only possibile to link a Document to a Layer, due to line 50 of file geonode/documents/forms.py:
 resources = list(Layer.objects.all())

Is there any specific reason why a Document could not be linked to a Map, or to another Document?
Looking at the rest of the GeoNode codebase it seems that the Link machinery is completely generic (it's ContentType based) and as such it should work with any type.

Simply change that line into:
 resources = list(ResourceBase.objects.all())

may suffice.
For a better result, a settings could be created listing the types of desired linked to resource types for each specific GeoNode deployment.

**Comment by gannebamm** [comment]
I would like this as feature

**Comment by capooti** [comment]
I don't think there is any reason, but let's wait for @simod who developed this
I am +1 to enable this for maps as well

**Comment by t-book** [comment]
+1

**Comment by afabiani** [comment]
up

**Comment by caipirginka** [comment]
up

**Comment by gannebamm** [comment]
`resources = list(ResourceBase.objects.all())` Will lead to dead links since the `save_many2many()` function is unable to retrieve to type or something.

Just adding 
```
    def generate_link_choices(self, resources=None):

        if resources is None:
            resources = list(Layer.objects.all())
            resources += list(Map.objects.all())
            # enable document to document link
            resources += list(Document.objects.all())
            resources.sort(key=lambda x: x.title)
```

Will work fine though.

**Comment by gannebamm** [comment]
@t-book @afabiani @francbartoli Shall I close this with my appoach above, or will this stay postponed?
Should I write an additional test for it?

**Comment by t-book** [comment]
Hi @gannebamm generally this looks good to me.
Just thinking out loud. As objects.all() from different models might end in huge result sets using itertools.chain() over concat could give us a speed advantage. Something like:

```
    def generate_link_choices(self, resources=None):

        if resources is None:
            from itertools import chain
            resources = list( chain(Layer.objects.all(), Map.objects.all(), Document.objects.all()) )
            resources.sort(key=lambda x: x.title)
```
could work but haven't tested.

This is as chain is written in C. Keep in mind in case of measuring, the speed advantage will only show up on large result sets.

**Comment by caipirginka** [comment]
up
