### ISSUE TITLE
Home page should list only the categories of available data

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#4905]
The same logic used to display the available categories in the LHS menu of the [search results page](http://master.demo.geonode.org/search) should be applied to the category list on the [home page](http://master.demo.geonode.org).

## Expected Behavior
Clicking any category on the Geonode home page should give at least one result. After all, the heading says "Discover the available datasets."

## Actual Behavior
All categories are shown whether or not data are available. So clicking some categories gives no results.

## Steps to Reproduce the Problem

  1. Go to http://master.demo.geonode.org/
  2. Click a Category (e.g. Intelligence)
  3.  "0 found. No content created yet."

## Specifications

  - GeoNode version: 2.10.1
  - Additional details: http://master.demo.geonode.org/

**Comment by capooti** [comment]
Personally I believe this kind of customisations should be addressed in a GeoNode Project, but if someone sends a PR with this feature I am +1 to merge it.

**Comment by LiliGuimaraes** [comment]
I'll take a look in this issue

**Comment by jondoig** [comment]
@LiliGuimaraes did you get anywhere with this? stalebot wants to sweep it away :(
