### ISSUE TITLE
Add the possibility of enabling "captcha" on GeoNode signup form

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4907]
**Is your feature request related to a problem? Please describe.**
Currently, we have an open signup form allowing the users to register to the portal. No "bot" check is done at all. This might lead, especially on public instances, to issues caused by automatic attacks to the site, trying to continuously register fake users.

**Describe the solution you'd like**
I would like to be able to enable a "captcha" field to the sign-up form.

Current situation
![image](https://user-images.githubusercontent.com/1278021/65026863-a9676680-d939-11e9-9fd1-117529173976.png)

Desirable
![image](https://user-images.githubusercontent.com/1278021/65026909-c0a65400-d939-11e9-9a4f-3810171073a5.png)

**Describe alternatives you've considered**
There's already a very good implementation for Django provided by the following package

`https://pypi.org/project/django-recaptcha`

Nevertheless, this solution requires, of course, some additional configuration steps done by the administrator. He will need to create and store on settings the Google reCaptcha key.
This is already very good documented on the `django-recaptcha` package. We could add a dedicated section to the GeoNode docs too.

**Comment by capooti** [comment]
+1
