### ISSUE TITLE
Featured items don't show up in home page

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4916]
## Expected Behavior

The featured items should show up in the home page featured datasets section.

## Actual Behavior

They currently don't show up. But I see that the request to the API is successful.
Looks to be an angular thing.

## Steps to Reproduce the Problem

Check "featured" on any layer/map/document, go to the home page: there isn't the featured item in the list.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

**Comment by t-book** [comment]
Offtopic💨: I think the featured Items section could get a Design upgrade. IMHO currently they do not look really featured. A separate section with f.e. a different bgcolor would highlight them.
