### ISSUE TITLE
Footer Display Code on Detail Layer pages

### ISSUE THREAD

**Issue by achorivai** [GeoNode/geonode#4920]
Dear Geonode Community

Can someone explain why this code appear on footer when i open detail layer pages?

"(function() { var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true; po.src = 'https://apis.google.com/js/plusone.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s); })(); $("#comment_submit_btn").click(function(event) { $.ajax({ type: "POST", url: $("#form_post_comment").attr('action'), data: $("#form_post_comment").serialize(), success: function() { $('#form_post_comment_div').modal().find('form')[0].reset(); $('#form_post_comment_div').modal('hide'); $('#comments_section').load(window.location.pathname + ' #comments_section', function(){$(this).children().unwrap()}) } }); return false; }); $(function() { if (sessionStorage.getItem("security_refresh_trigger")) { sessionStorage.clear(); $("#security_refresh").trigger('click'); } }); "

![Screenshot_Geonode_Footer_Layer_Pages](https://user-images.githubusercontent.com/4677202/65205449-bb6f1380-dab7-11e9-8cc5-d44823cd43bd.png)

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual Geonode Core):
  - Platform: Linux Ubuntu 18.04 (Bionic)
  - Additional details:

**Comment by achorivai** [comment]
It happen too in geonode master demo :)

![Screenshot_2019-09-19 Project_Sublocations](https://user-images.githubusercontent.com/4677202/65206658-5b796c80-dab9-11e9-864c-e136235eb6e2.png)

**Comment by t-book** [comment]
It looks like a script tag is missing. I've just created a PR which should solve it.
