### ISSUE TITLE
Actstream not safe for special chars in verb

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4935]
## Expected Behavior
Actstream can handle multilanguage verbs

## Actual Behavior
An Unicode error is thrown when deleting f.e. a layer in german or greek.

## Steps to Reproduce the Problem

  1. $ paver setup_data
  2. go to Django-admin
  3. change language to 'de' (or 'el') (by replacing the iso code in url)
  4. delete f.e. geonode:single_point
  5. go to Django-admin ACTSREAM/actions
  6. Note the verb 'gelöscht'
  7. try to open the action by clicking on the title

![Bildschirmfoto 2019-09-20 um 14 33 15](https://user-images.githubusercontent.com/20478652/65327278-d2932b80-dbb3-11e9-9dbb-92ccd2dd2cbc.png)

= the problem is the beautiful character 'ö'. unfortuantely simply encoding the verb to utf8 does not solve the problem.

## Specifications

  - GeoNode version: 2.10, master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Linux
  - Additional details:  Might affect all install methods

**Comment by t-book** [comment]
Problem with lib: https://github.com/justquick/django-activity-stream/issues/201

**Comment by afabiani** [comment]
@t-book I guess this can be closed now

**Comment by t-book** [comment]
tested and closed thanks @afabiani
