### ISSUE TITLE
Configure GeoNode with NGINX

### ISSUE THREAD

**Issue by MatheusXimeness** [GeoNode/geonode#4948]
## Expected behavior
When I started debug mode, ok, it works, but when I try to switch to nginx, I get an error.
In this process, the URL's `http://localhost` and `http://localhost/geoserver`  should work.
## Actual Behavior
However, in my current status, only `http://localhost/geoserver` works
## Steps to Reproduce Behavior
Here are some photos of the process:

![image](https://user-images.githubusercontent.com/41555370/65514136-17b8a580-deb3-11e9-882b-7b91a8770f00.png)

![image](https://user-images.githubusercontent.com/41555370/65514188-39199180-deb3-11e9-85c3-d39d5380a3fb.png)

![image](https://user-images.githubusercontent.com/41555370/65514217-433b9000-deb3-11e9-9444-3bf384a21c6c.png)

![image](https://user-images.githubusercontent.com/41555370/65514233-4c2c6180-deb3-11e9-9c41-5fc503fd6657.png)

When i access `http://localhost`

![image](https://user-images.githubusercontent.com/41555370/65514293-6a925d00-deb3-11e9-80c6-f99fb117d84b.png)

![image](https://user-images.githubusercontent.com/41555370/65514317-73832e80-deb3-11e9-9ca3-a27367eba262.png)

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Linux 
  - Additional details:

**Comment by t-book** [comment]
Hi,

how does your ALLOWED_HOSTS Setting look like? https://docs.djangoproject.com/en/2.2/ref/settings/#allowed-hosts

Further, can you confirm that your correctly configured NGINX and the server is running?
http://docs.geonode.org/en/2.10.x/install/core/index.html#serving-geonode-geoserver-via-nginx
