### ISSUE TITLE
UnicodeEncodeError in upload.models.update_from_session method when using Importer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4949]
## Expected Behavior

A layer can be correctly uploaded by a user with a profile first_name and last_name not containing ascii characters.

## Actual Behavior

For a user in profile has no ascii characters in first_name, last_name the upload using the GS Importer fails with the following error:

```
Traceback (most recent call last):
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 675, in view
    resp = _steps[step](req, upload_session)
  File "/home/ubuntu/geonode/geonode/upload/views.py", line 234, in save_step_view
    Upload.objects.update_from_session(upload_session)
  File "/home/ubuntu/geonode/geonode/upload/models.py", line 42, in update_from_session
    upload_session)
  File "/home/ubuntu/geonode/geonode/upload/models.py", line 100, in update_from_session
    upload_session.user.first_name = u'{}'.format(upload_session.user.first_name).decode("utf-8", "replace")
  File "/home/ubuntu/env/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 6-11: ordinal not in range(128)
```

REST uploaded works as expected.

## Steps to Reproduce the Problem

  1. Login with a user having not-ascii characters in first_name/last_name (profile)
  2. upload a layer using GS importer

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

**Comment by t-book** [comment]
@capooti A portal that deals with data and users around the world should be able to handle charsets without problems. Therefore, I tend to label with 'Major', but leave the decision to you🙂

**Comment by capooti** [comment]
ok T🙂ni I agree with thes🙂
