### ISSUE TITLE
Adding Layers to cart leads to "Request Header Or Cookie Too Large"

### ISSUE THREAD

**Issue by sjohn-atenekom** [GeoNode/geonode#4954]
## Expected Behavior
- at layer list view, I'm adding multiple layers to cart
- instead of setting permission or creating a map, I go to a layers detail view
- the detail view of the shows up
- I go back to the layers list and the items are still added to the cart

## Actual Behavior
- at layer list view, I'm adding multiple layers to cart
- instead of setting permission or creating a map, I go to a layers detail view
- nginx gives the error "Request Header Or Cookie Too Large"

## Steps to Reproduce the Problem

  1. See expected behavior

## Specifications

  - GeoNode version: 2.10.1
  - Installation method: Docker
  - Platform: debian
  - Additional details:

**Comment by sjohn-atenekom** [comment]
The problem here seems to be, that the entire item (layer object with all its properties) is added as a cookie.
As far as I figured out, for setting the permissions or creating a map only following properties of the items are needed.
**Bulk Permission:**
https://github.com/GeoNode/geonode/blob/56ca24c641ac741c6e14e681ad6b817e5a6166eb/geonode/static/geonode/js/search/cart.js#L37
```
item.id
```
**Creating Map**
https://github.com/GeoNode/geonode/blob/56ca24c641ac741c6e14e681ad6b817e5a6166eb/geonode/static/geonode/js/search/cart.js#L23
```
items[i].detail_url
```

If this is the case, I would propose something like this (pseudo code, not tested):
https://github.com/GeoNode/geonode/blob/56ca24c641ac741c6e14e681ad6b817e5a6166eb/geonode/static/geonode/js/search/cart.js#L131
```
          this.getCart().items.push(item);
          var cookie_item;
          cookie_item['id'] = item.id
          cookie_item['detail_url'] = item.detail_url
          $cookies.putObject(item['uuid'], cookie_item);
```

Can somebody confirm? I would create a pull request then.

cheers,
Steffen

**Comment by t-book** [comment]
Makes sense @sjohn-atenekom , thanks!

**Comment by sjohn-atenekom** [comment]
@t-book Just added a PR.
https://github.com/GeoNode/geonode/pull/4968

**Comment by afabiani** [comment]
@sjohn-atenekom thanks for the PR. Did you sent the signed CLA to OSGeo? If yes we can add you to the list of "signed" committers. Thanks.
