### ISSUE TITLE
By using UPLOADER=geonode.rest we are facing a timing issues on signals

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#4959]
## Expected Behavior
Layer uploaded and configured correctly on Django.

## Actual Behavior
This is what I currently see if I upload a layer:

```
>>> Step 10. Creating Django record for [public_violence_1ja_2]
There isn't a geoserver resource for this layer: public_violence_1ja_2
Traceback (most recent call last):
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/kombu/utils/scheduling.py",
line 56, in get
    return self.fun(resource, callback, **kwargs)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/kombu/transport/virtual/base.py",
line 405, in _get_and_deliver
    message = self._get(queue)
  File "/home/ubuntu/wm-2.10.x/env/local/lib/python2.7/site-packages/kombu/transport/memory.py",
line 27, in _get
    return self._queue_for(queue).get(block=False)
  File "/usr/lib/python2.7/Queue.py", line 165, in get
    raise Empty
Empty
```

The layer is anyway created in GeoNode and GeoServer, but is not
rendered in layer preview and initial extent is wrong.

## Steps to Reproduce the Problem

  1. Enable "UPLOADER -> geonode.rest" method and restart GeoNode
  2. Try to upload a layer
  3. Notice that both attributes, links and thumbs are not created correctly

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

**Comment by capooti** [comment]
@afabiani out of curiosity, do you use REST or importer for your instances?
(I am using both, REST for regular files, importer for geojson)

**Comment by capooti** [comment]
@afabiani I deployed this on our staging.

Unfortunately after layer upload I am still with a layer which is created in GeoNode and GeoServer, but not rendered in the layer preview and with wrong initial extent.
The only difference I noticed is that now I don't see the error at step 10 anymore in the log. So it must be another thing?

**Comment by afabiani** [comment]
@capooti I need to try to reproduce the use case somehow.
Do you think it would be feasible to provide me access to the server in order to perform some live tests?
If so, please write me a PM.

**Comment by capooti** [comment]
sure, and many thanks for helping with this. I am going to send you credentials in a email. cheers!

**Comment by afabiani** [comment]
@capooti this PR https://github.com/GeoNode/geonode/pull/5092 will probably fix this as well

**Comment by afabiani** [comment]
@capooti can we close this?

**Comment by afabiani** [comment]
@capooti roger that... that's really strange, by the way. I don't think it is a timing issue. It looks more a security issue. Something like the REST api cannot access somehow to the new layers.
