### ISSUE TITLE
Date widget has gone

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#4964]
## Expected Behavior

On layers page (and other page as well), when clicking on a date field, the date widget shows up

## Actual Behavior

The date widget does not show anymore

## Steps to Reproduce the Problem

  1. click on date begin after field in layers page
  2. nothing happens
  3.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

**Comment by t-book** [comment]
@afabiani I think it's about the time section in leftside filter http://master.demo.geonode.org/layers/?limit=20&offset=0. Indeed the dateinputs have a datepicker class.

![Bildschirmfoto 2019-09-30 um 10 50 36](https://user-images.githubusercontent.com/20478652/65863362-4251a500-e370-11e9-907a-b208eb00c129.png)

**Comment by afabiani** [comment]
@t-book thanks

**Comment by t-book** [comment]
From a quick look it's just missing a 

`$( ".datepicker" ).datepicker();`

in template ...

**Comment by afabiani** [comment]
@t-book https://github.com/GeoNode/geonode/pull/4969/files

**Comment by t-book** [comment]
@afabiani Thanks. Interesting it wasn't only the plugin initiation. Maybe an angular update.

![Bildschirmfoto 2019-09-30 um 12 15 29](https://user-images.githubusercontent.com/20478652/65870263-1a683e80-e37c-11e9-94a5-fc8bcea86786.png)

Will try to help bringing  21.4 % of GeoNode under more control ;)
