### ISSUE TITLE
Auxiliary file not uploaded to Geoserver with geonode.importer

### ISSUE THREAD

**Issue by digimatspa** [GeoNode/geonode#4976]
## Expected Behavior
When uploading a ASCII Grid file with its prj file using the geonode importer, Geoserver imports the file with the correct SRS

## Actual Behavior
The accompanying prj file is not uploaded to Geoserver (a default SRS is used).
Further analysis reveals that the related FileType object declared in file geonode/upload/files.py doesn't contain a valid auxillary_file_exts tuple. Such tuple should contain a trailing comma to permit the subsequent conversion to list (see FileType __init__)

```
    FileType("ASCII Text File", "asc", raster,
             auxillary_file_exts=('prj')),
```

should be 

```
    FileType("ASCII Text File", "asc", raster,
             auxillary_file_exts=('prj',)),
```

Reference: https://stackoverflow.com/a/12876194

The same problem occurs with other file formats.
## Steps to Reproduce the Problem

  1.Use 'BACKEND': 'geonode.importer' in settings.py
  2.Upload an ASCII Grid file and its PRJ file
  3.Connect to Geoserver and verify the SRS of the new layer

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Ansible (geonode-project)
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by afabiani** [comment]
@digimatspa thanks for your analysis. I'll verify the issue and try to provide a fix ASAP.
