### ISSUE TITLE
$ Python 3.6 manage.py collectstatic Error 

### ISSUE THREAD

**Issue by iamiftikharmashwani** [GeoNode/geonode#4981]
I have geonode 2.10 installed on Ubuntu Server 18.4.3 VPS, when I am trying to change the look and feel as mentioned in the manual, it gives me error message and the change is not reflected in the browser. what to do because I am new user.

> $ python 3.6 manage.y collectstatic 

gives error.  
![image](https://user-images.githubusercontent.com/6747322/66039894-8ccd5000-e52f-11e9-9e21-5cae605b0832.png)
![manage py error](https://user-images.githubusercontent.com/6747322/66039916-98207b80-e52f-11e9-9432-ce8433a0b592.JPG)
Pleae help me

**Comment by t-book** [comment]
Hi,

GeoNode is python2 only by now. Further you have not installed django. It seams requrements.txt is not installed by pip.

**Comment by iamiftikharmashwani** [comment]
@t-book : Thanks for your kind response actually I am new to the Ubuntu environment, Django is installed and requirements.txt file is present in main directory of geonode.
Requirements.txt 
![requirement txt file image](https://user-images.githubusercontent.com/6747322/66101017-b5ecef80-e5c6-11e9-9364-317cf7a18174.JPG).
main directory 
![maindirectory_LI](https://user-images.githubusercontent.com/6747322/66101072-d6b54500-e5c6-11e9-9904-e2fedde616bc.jpg).
Error Python3.6
![python 3 6error_LI](https://user-images.githubusercontent.com/6747322/66101094-f482aa00-e5c6-11e9-802e-e701d098bac8.jpg)
These are the errors.
 


.

**Comment by t-book** [comment]
Hi, you need python 2.7 ;) then just follow the docs http://docs.geonode.org/en/2.10.x/install/core/index.html#ubuntu-18-04

**Comment by iamiftikharmashwani** [comment]
@t-book : Thanks but I am using it through DOCKER.

**Comment by t-book** [comment]
HI @iamiftikharmashwani have you seen there are docs to follow for docker as well. http://docs.geonode.org/en/2.10.x/install/core/index.html#docker

Besides, at github only bugs should be discussed. Would you kindly ask for help at the user list. https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users
After you're signup there I will approve your subscription. 

Cheers, Toni
