### ISSUE TITLE
Geonode/pycsw OAI-PMH bug

### ISSUE THREAD

**Issue by kamil386** [GeoNode/geonode#4983]
http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify
Causes an error in response, in effect geonode can't be harvested.

## Expected Behavior
Response without error.

## Actual Behavior
http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify

There was a problem loading this page
Please contact your GeoNode administrator (he may have received an email automatically if he configured it properly). If you are the site administrator, enable debug mode to see the actual error and fix it or file an issue in GeoNode's issue tracker

`Request Method: | GET
-- | --
http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify
1.11.24
FieldError
Cannot resolve keyword 'last_updated' into field. Choices are: abstract, abstract_en, action_object_actions, actor_actions, alternate, attribute_set, bbox_x0, bbox_x1, bbox_y0, bbox_y1, category, category_id, charset, constraints_other, constraints_other_en, contactrole, contacts, csw_anytext, csw_insert_date, csw_mdsource, csw_schema, csw_type, csw_typename, csw_wkt_geometry, curatedthumbnail, data_quality_statement, data_quality_statement_en, date, date_type, default_style, default_style_id, detail_url, dirty_state, edition, elevation_regex, featured, group, group_id, has_elevation, has_time, id, is_approved, is_mosaic, is_published, keywords, language, license, license_id, link, maintenance_frequency, metadata_uploaded, metadata_uploaded_preserve, metadata_xml, name, owner, owner_id, polymorphic_ctype, polymorphic_ctype_id, popular_count, purpose, purpose_en, rating, regions, remote_service, remote_service_id, resourcebase_ptr, resourcebase_ptr_id, restriction_code_type, restriction_code_type_id, share_count, spatial_representation_type, spatial_representation_type_id, srid, store, storeType, styles, supplemental_information, supplemental_information_en, taggedcontentitem, target_actions, temporal_extent_end, temporal_extent_start, thumbnail_url, time_regex, title, title_en, tkeywords, typename, upload, upload_session, upload_session_id, uploadsession, uuid, workspace
/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py in names_to_path, line 1352
/usr/local/bin/uwsgi
2.7.16
['.',  '',  '/usr/local/lib/python27.zip',  '/usr/local/lib/python2.7',  '/usr/local/lib/python2.7/plat-linux2',  '/usr/local/lib/python2.7/lib-tk',  '/usr/local/lib/python2.7/lib-old',  '/usr/local/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/site-packages',  '/usr/src/app',  '/usr/src/app/src/geonode',  '/usr/src/app']
Śr, 2 Paź 2019 14:50:09 -0500`

`Environment:

Request Method: GET
Request URL: http://master.demo.geonode.org/catalogue/csw?mode=oaipmh&verb=Identify

Django Version: 1.11.24
Python Version: 2.7.16
Installed Applications:
('modeltranslation',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'dj_pagination',
 'taggit',
 'treebeard',
 'leaflet',
 'bootstrap3_datetime',
 'django_filters',
 'django_basic_auth',
 'autocomplete_light',
 'mptt',
 'storages',
 'floppyforms',
 'django_forms_bootstrap',
 'avatar',
 'dialogos',
 'agon_ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'invitations',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'geonode',
 'geonode.api',
 'geonode.base',
 'geonode.layers',
 'geonode.maps',
 'geonode.documents',
 'geonode.security',
 'geonode.catalogue',
 'geonode.catalogue.metadataxsl',
 'geonode.people',
 'geonode.client',
 'geonode.themes',
 'geonode.proxy',
 'geonode.social',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'geonode.documents.exif',
 'geonode.geoserver.createlayer',
 'geonode.favorite',
 'geonode.monitoring',
 'mapstore2_adapter',
 'geonode_mapstore_client',
 'pinax.notifications',
 'demo_master',
 <Celery geonode at 0x7ffad6b12550>)
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.sites.middleware.CurrentSiteMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware',
 'geonode.security.middleware.SessionControlMiddleware',
 'geonode.monitoring.middleware.MonitoringMiddleware')

Traceback:

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/usr/src/app/src/geonode/geonode/catalogue/views.py" in csw_global_dispatch
  151.         content = csw.dispatch_wsgi()

File "/usr/local/lib/python2.7/site-packages/pycsw/server.py" in dispatch_wsgi
  250.         return self.dispatch()

File "/usr/local/lib/python2.7/site-packages/pycsw/server.py" in dispatch
  592.                 self.config.get('server', 'url')

File "/usr/local/lib/python2.7/site-packages/pycsw/oaipmh.py" in response
  223.                 etree.SubElement(verbnode, util.nspath_eval('oai:earliestDatestamp', self.namespaces)).text = repository.query_insert('min')

File "/usr/src/app/src/geonode/geonode/catalogue/backends/pycsw_plugin.py" in query_insert
  146.                 Min('last_updated'))['last_updated__min'].strftime('%Y-%m-%dT%H:%M:%SZ')

File "/usr/local/lib/python2.7/site-packages/django/db/models/manager.py" in manager_method
  85.                 return getattr(self.get_queryset(), name)(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/polymorphic/query.py" in aggregate
  301.         return super(PolymorphicQuerySet, qs).aggregate(*args, **kwargs)

File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py" in aggregate
  348.             query.add_annotation(aggregate_expr, alias, is_summary=True)

File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py" in add_annotation
  973.                                                    summarize=is_summary)

File "/usr/local/lib/python2.7/site-packages/django/db/models/aggregates.py" in resolve_expression
  19.         c = super(Aggregate, self).resolve_expression(query, allow_joins, reuse, summarize)

File "/usr/local/lib/python2.7/site-packages/django/db/models/expressions.py" in resolve_expression
  548.             c.source_expressions[pos] = arg.resolve_expression(query, allow_joins, reuse, summarize, for_save)

File "/usr/local/lib/python2.7/site-packages/django/db/models/expressions.py" in resolve_expression
  471.         return query.resolve_ref(self.name, allow_joins, reuse, summarize)

File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py" in resolve_ref
  1477.                 self.get_initial_alias(), reuse)

File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py" in setup_joins
  1417.             names, opts, allow_many, fail_on_missing=True)

File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/query.py" in names_to_path
  1352.                                      "Choices are: %s" % (name, ", ".join(available)))

Exception Type: FieldError at /catalogue/csw
Exception Value: Cannot resolve keyword 'last_updated' into field. Choices are: abstract, abstract_en, action_object_actions, actor_actions, alternate, attribute_set, bbox_x0, bbox_x1, bbox_y0, bbox_y1, category, category_id, charset, constraints_other, constraints_other_en, contactrole, contacts, csw_anytext, csw_insert_date, csw_mdsource, csw_schema, csw_type, csw_typename, csw_wkt_geometry, curatedthumbnail, data_quality_statement, data_quality_statement_en, date, date_type, default_style, default_style_id, detail_url, dirty_state, edition, elevation_regex, featured, group, group_id, has_elevation, has_time, id, is_approved, is_mosaic, is_published, keywords, language, license, license_id, link, maintenance_frequency, metadata_uploaded, metadata_uploaded_preserve, metadata_xml, name, owner, owner_id, polymorphic_ctype, polymorphic_ctype_id, popular_count, purpose, purpose_en, rating, regions, remote_service, remote_service_id, resourcebase_ptr, resourcebase_ptr_id, restriction_code_type, restriction_code_type_id, share_count, spatial_representation_type, spatial_representation_type_id, srid, store, storeType, styles, supplemental_information, supplemental_information_en, taggedcontentitem, target_actions, temporal_extent_end, temporal_extent_start, thumbnail_url, time_regex, title, title_en, tkeywords, typename, upload, upload_session, upload_session_id, uploadsession, uuid, workspace`

## Specifications

  - GeoNode version: 2.10.1

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/pull/4982
