### ISSUE TITLE
Style the keyword treeview section

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#4984]
The treeview plugin seems to miss styling. Icons are not rendern paddings look odd.

![Bildschirmfoto 2019-10-03 um 12 04 26](https://user-images.githubusercontent.com/20478652/66118189-133c6d00-e5d6-11e9-952c-6676898984e4.png)

**Comment by t-book** [comment]
Will be:

![Bildschirmfoto 2019-10-03 um 12 32 11](https://user-images.githubusercontent.com/20478652/66119884-e5592780-e5d9-11e9-8fcb-cd22229e65f4.png)

**Comment by gannebamm** [comment]
Just an UX idea: Would be nice to type in the label and get autocomplete.

**Comment by t-book** [comment]
good point @gannebamm ! I will try to integrate it in a next step!

**Comment by capooti** [comment]
side note: would it be complicated to have facets count as we had in previous GeoNode versions (with taggit)?

**Comment by t-book** [comment]
@capooti Do you have something like this in mind? If so I think we just would have to update the api a bit.

<img width="293" alt="Bildschirmfoto 2019-10-08 um 18 14 28" src="https://user-images.githubusercontent.com/20478652/66413387-92c3a500-e9f7-11e9-8c38-5af62565bef2.png">

**Comment by capooti** [comment]
yes @t-book though I am not sure how performant is without a search engine, so maybe that should be optional?

**Comment by t-book** [comment]
> so maybe that should be optional?

@capooti  yep good idea!
