### ISSUE TITLE
Error uploading JPG file with geonode.importer

### ISSUE THREAD

**Issue by digimatspa** [GeoNode/geonode#5003]
## Expected Behavior
After uploading a JPG file with its PRJ file using the geonode importer, Geoserver imports the file correctly

## Actual Behavior
An exception is raised: Unsupported file type
The issue can be resolved by specifying the correct steps in the upload workflow: see file geonode/utils.py:

```
_pages = {
...
'jpg': ('run', 'final'), 
}
```

## Steps to Reproduce the Problem

  1.Use 'BACKEND': 'geonode.importer' in settings.py
  2.Upload a JPG file and its PRJ file
  3.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Ansible (geonode-project)
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
From what I see this is not supported?

https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L867-L880
https://github.com/GeoNode/django-osgeo-importer#supported-geodata-formats

**Comment by digimatspa** [comment]
Well, it seems that the format is actually referred here: 

https://github.com/GeoNode/geonode/blob/ab6085b6ffdd760390cc56f6aa5602e3ae23a334/geonode/upload/files.py#L141-L142
