### ISSUE TITLE
Show more metadata in layers API call eg. regions, keywords

### ISSUE THREAD

**Issue by mcarans** [GeoNode/geonode#5004]
**Is your feature request related to a problem? Please describe.**
The api/layers call gives a very limited amount of metadata. It should include more metadata including Regions and Keywords.

**Describe the solution you'd like**
Add Regions, Keywords and other relevant metadata to the JSON outputted by api/layers.

**Describe alternatives you've considered**
There aren't alternatives.

**Additional context**
There seems to be a related issue but it was closed with no explanation given:
https://github.com/GeoNode/geonode/issues/2028

**Comment by t-book** [comment]
Unsure about it as it might affect performance. However, you could quite easily use a custom api for your needs without changing the core. Have a look here: https://github.com/GeoNode/geonode/issues/4163#issuecomment-457382286

**Comment by mcarans** [comment]
I'm not the one running the GeoNode server so I can only hope this feature appears in a future version that the server owner installs.
