### ISSUE TITLE
Create thumbnail for a remote service is sending request to local GeoServer

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#5005]
## Expected Behavior

When pushing the "Set Thumbnail" button for a remote layer, the thumbnail should be correctly generated.

## Actual Behavior

Currently, the button seems to try to generate the thumbnail using the local GeoServer instance.

## Steps to Reproduce the Problem

  1. Go to a remote service layer detail page
  2. Click on editing tools
  3. Click on set thumbnail button

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

**Comment by capooti** [comment]
as a temporary alternative for now we could remote the "Set" button and just leave the "Upload" one

**Comment by afabiani** [comment]
This is not a regression. I don't think "set thumbnail" for Remote Layers ever worked.

**Comment by capooti** [comment]
Oh I see, in any case l'd suggest to remove the button then. I can do it right now.
