### ISSUE TITLE
Maps migrated from GeoExplorer don't display the correct initial extent in MapStore

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#5028]
## Expected Behavior

A migrated GeoNode database has existing maps which should be open correctly in MapStore.

## Actual Behavior

MapStore open the maps and load the layers but the initial extent of the map is not used.

## Steps to Reproduce the Problem

  1. Create a map using the GeoExplorer client
  2. Open the map with MapStore client

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

**Comment by capooti** [comment]
I am looking into this and hope to provide a fix.

**Comment by t-book** [comment]
great @capooti  I'm facing this as well!

**Comment by capooti** [comment]
this is weird. In my case I made a test with a map (migrated from 2.4).

Its center coordinates are:

x: -8270118.6203211
y: 510731.02638314
EPSG:900913

GeoExplorer opens this correctly. If I open this map using MapStore, it fails to get to the correct center point but it goes to a totally different extent.

If I make a small changes to its x MapStore will correctly show the right extent:

x: -8269637.65611
y: 510731.02638314
EPSG:900913

I am not sure from what this can depend: maybe some bug in the javascript proj library?

Let's wait from a reply from the MapStore guys - who can use the first pair of coordinates to replicate the issue - just change them in a freshly created map from MapStore.

**Comment by t-book** [comment]
thanks @capooti . okay if we label as major? As this might affect everybody who migrates from older geonode?

**Comment by t-book** [comment]
@capooti  any news on this?

**Comment by capooti** [comment]
Unfortunately I didn't have time to investigate and for now we are still using the GeoExplorer client for the instance on which we were planning to start using MapStore. I am sure @afabiani and other MapStore developers will help on this soon

**Comment by t-book** [comment]
> If I make a small changes to its x MapStore will correctly show the right extent:
> 
> x: -8269637.65611
> y: 510731.02638314
> EPSG:900913
> 
> I am not sure from what this can depend: maybe some bug in the javascript proj library?

My guess is it's the save() which updates/sets some needed relation.

**Comment by capooti** [comment]
thanks a lot @afabiani it works well now!
though maybe it looks still a bit slower than GeoExplorer but I am sure you will improve it :)
