### ISSUE TITLE
ows endpoint does show private layers for unauthorized users

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5046]
## Expected Behavior
my.geonode.instance/geoserver/ows?version=1.1.1

Will show only public layers for unauthorized users

## Actual Behavior
my.geonode.instance/geoserver/ows?version=1.1.1

QGIS shows also private layers as WMS. The GetCapabilities request does list the layer, too:
my.geonode.instance/geoserver/ows?service=WMS&version=1.1.1&request=GetCapabilities

## Steps to Reproduce the Problem

  1. upload layer
  2. change permissions to only allow user to see the layer
  3. query ows endpoint 

## Specifications

  - GeoNode version: 2.10.x (master)
  - Installation method: SPC Geonode
  - Platform: 
  - Additional details:

**Comment by afabiani** [comment]
Actually this is wanted.
If you want to access private layers, you must use "gs/wms", "gs/wfs" or "gs/wcs"

**Comment by gannebamm** [comment]
It will show **private** layers, even though the user *does not auth**

**Comment by gannebamm** [comment]
@afabiani and I thought the ows endpoint does use basic authentication handle permissions

**Comment by afabiani** [comment]
@gannebamm "ows" shows private layers only in two cases:

1. You provide http auth headers along with the request. (no basic auth challenge supported here, but headers will be forwarded)

2. GeoServer/GeoFence somehow allows access to the layers anyway. It is worth trying the same "GetCapabilities" request directly to GeoServer. It will probably give the same outcomes.

Most probably you are experiencing the case #2. Any chance to review the GeoFence conf?

**Comment by capooti** [comment]
this useful thing was working in the past, but last time I tested it
didn't work for me too

On Tue, Oct 15, 2019 at 9:41 AM Florian Hoedt <notifications@github.com> wrote:
>
> @afabiani and I thought the ows endpoint does use basic authentication handle permissions
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti
#drt3jc1

**Comment by afabiani** [comment]
It cannot depend on the endpoint. It is using a proxy that just forwards the request to GeoServer.

It would be useful to spot the GeoFence rule hit causing this behavior, in order to understand if this has been wrongly created by GeoNode or, somehow, there's some logic issue on GeoFence itself.

Notice that GeoFence evaluates the rules by priority, starting from the lowers. The first rule matching, will be applied.

**Comment by gannebamm** [comment]
I will take a look at this tomorrow

**Comment by gannebamm** [comment]
With SPC I see issues with the endpoints:

http://127.0.0.1/geoserver/wms?version=1.1.1&request=GetCapabilities

will give me all layers in the XML; QGIS will only load public ones though.

Trying to fetch the layers with basic auth from wms endpoint does not work for normal users. If I use the super user instead it works.

The webui from geonode works as expected and shows/hides layers as configured.

These are the geofence confs:
![grafik](https://user-images.githubusercontent.com/6172324/67005827-d26b4a80-f0e3-11e9-8bd2-0c2d5d0d14f4.png)

![grafik](https://user-images.githubusercontent.com/6172324/67005845-d8f9c200-f0e3-11e9-9ab7-6a33fcd78305.png)

![grafik](https://user-images.githubusercontent.com/6172324/67005853-de570c80-f0e3-11e9-926a-51d5319ce18c.png)


I thought there should be a deny all somewhere in the geofence confs?

**Comment by gannebamm** [comment]
You should use a browser session without cookies ...

**Without cookies** Iam not able to see the layer in the getcap doc and are not able to fetch the getmap request!

I will close this one for now.
