### ISSUE TITLE
MapStore is not authenticating 

### ISSUE THREAD

**Issue by ikzte** [GeoNode/geonode#5047]
## Expected Behavior
Loading a restricted Map with restricted Layers and display the Layers (User, Map and Layers have the correct permissions). 

MapStore should authenticate the Current User against GeoServer.

## Actual Behavior

None of the layers is displayed

![image](https://user-images.githubusercontent.com/25789171/66848532-8d290a80-ef75-11e9-897a-909258bbd82d.png)

## Steps to Reproduce the Problem

  1. Open geonode-URL in a private Window in your Browser
  2. Sign in with a User which has access to maps and layers that are not for the public (which have not the "anyone" permission)
  3. Open such a Map 

## Specifications

  - GeoNode version: 2.10
  - Installation method: manual, GeoNode Docker, SPCGeoNode Docker
  - Platform: Ubuntu 18.4

## Additional details:

While GeoExplorer sent the access_token with every request to GeoServer, MapStore is sending its requests without an access_token. To work around the problem, the user can open the detail-page of a layer. In this case the first request to geoserver is send by django (a GetLegendGraphic-Request), which provides the access_token and authenticates the user against Geoserver. Then MapStore sends it's requests and the layer is displayed correctly.
If the User opens the Mapview now: everthing is working fine

**Comment by t-book** [comment]
@ikzte Cannot reproduce this on master.demo can you please confirm my test is correct:

1. uploaded a layer, view permissions: private (me only)
2. created a map,  view permissions: private (me only)
3. open a new private browser window, log-in, view map -> map is showing
4. logout -> map is not showing

**Comment by afabiani** [comment]
I cannot reproduce either.

Currently, this is what I have done:

1. Create a user (no superuser)
2. Upload a layer
3. Disable permissions to anonymous
4. Create a Map containing this Layer
5. Cut and paste the direct link to the map
6. On a new **anonymous** browser session, go to the map link; the layer is not accessible OK
7. On a new **user** browser session, go to the map link; the layer is accessible OK

**Comment by ikzte** [comment]
Meanwhile I pulled from master and couldn't reproduce this either.

What could be misconfigured that the access_token is not delivered to geoserver when using MapStore (GeoExplorer is working fine)?
