### ISSUE TITLE
"Registered Members" Group: Auto assign users to group(s) after activation

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5052]
**Is your feature request related to a problem? Please describe.**
Currently there's no concept of "loggedin users" within the GeoNode permission system. Registered users without a group assigned are treated like anonymous users.

Assigning sepcific permissions to loged in users can be overcome creating a "loggedin users" group and assign active users to the group, but this must be done manually (and worst it must be done one by one).

The proposal here is to implement a post_save signal hook in GeoNode to auto-assign users to one or more groups when a new user is registered.

**Describe alternatives you've considered**
### OPTION 1
We could have this new settings:

`AUTO_ASSIGN_USERS_TO_GROUPS = ['group1', 'group2', etc.]`

This is a bit unflexible since when group names change this settings must be updated and the application reloaded.

### OPTION 2
Create a new "**UserAutoAssignedGroups**":

```
class UserAutoAssignedGroups(models.Model):
     groups =  models.ForeignKey(django.contrib.auth.models.Group)
```

which will be queried within the post_save hook.

**Comment by t-book** [comment]
Thanks @afabiani I give my +1 for both options.

**Comment by davekennewell** [comment]
I'm +1 for Option 2, I think it's important to be able to update/configure this without needing to deploy code. 
However, if an admin does change this via the django admin, will it: 

1. only apply to new users, not update all registered users... or 
2. would the post_save signal on the new class assign the new Groups to all current users? 

I think I would prefer behaviour 2.

**Comment by afabiani** [comment]
What I have done so far is something similar to OPTION 2, but without the need for using a new class.

Currently, this PR https://github.com/GeoNode/geonode/pull/5045 creates a default "private" group called "registered-users", and assigns to it automatically users that can successfully login to the system.

This behavior can be disabled through the `AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME` option.

**Comment by capooti** [comment]
@afabiani thanks. I did this already in a few instances in the GeoNode project, so having this in core is really great
