### ISSUE TITLE
Add docs about tests for development

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5067]
**Is your feature request related to a problem? Please describe.**
Currently it is unclear for new developers how to start a proper development setup on different systems and how to perform tests locally

**Describe the solution you'd like**
The docs section should be extended to describe common setups and with hints how to properly test locally.

**Describe alternatives you've considered**
None

**Additional context**

See Gitter post from @afabiani  [October 18, 2019 1:03 PM](https://gitter.im/GeoNode/general?at=5da99c1aa28cd16529ba5d6e)

**Comment by gannebamm** [comment]
Note to myself: I would also like to write a lessons learned about my experiences to develop on windows with docker compose

**Comment by gannebamm** [comment]
@t-book do you think we should link the current gdoc about testing locally in this issue for whom it may concern later (the assignee for this issue)

**Comment by t-book** [comment]
> @t-book do you think we should link the current gdoc about testing locally in this issue for whom it may concern later (the assignee for this issue)

Yep, good idea!
