### ISSUE TITLE
Search services are not saved - MapStoreClient

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5091]
## Steps to Reproduce the Problem

  1. I create a map and save it, this works correctly
  2. Create / edit a search service and save it. I test if the search works and everything is correct. The problem is when I go out and enter the Map again and the Search Service that I created disappears

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (GeoNode Docker + Geonode-Project):
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by dpadron** [comment]
Hi,
Someone has been able to review this function.
He tested on http://master.demo.geonode.org and still cannot save a search service on the map. 
Any solution?

**Comment by gannebamm** [comment]
This is the only active _search services not saved_ issue please. We had three which described the same issue in different ways.

**Comment by gannebamm** [comment]
Would postpone this to get 3.0 faster

**Comment by t-book** [comment]
@gannebamm @dpadron  have you used this feature in GeoNode? I wonder if a defined search is saved in the map object or if this needs further implementation with geonode mapstore client.

**Comment by t-book** [comment]
@afabiani confirmed my guess at gitter. this is not yet implemented. I think it would be more clear to open a feature request at geonode mapstore client repository

**Comment by gannebamm** [comment]
@t-book We do not use custom search services. I have created an issue in the mapstore client repo: https://github.com/GeoNode/geonode-mapstore-client/issues/58

I think we should close this issue in this repo?
