### ISSUE TITLE
Error when using THESAURI caused by new version of autocomplete_light

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#5105]
## Expected Behavior

Setting THESAURI in settings should correctly load a thesaurus in search filters section.

## Actual Behavior

I see the following error:

```
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/urls.py", line 38, in <module>
    from geonode.base.views import thumbnail_upload
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/base/views.py", line 33, in <module>
    from .forms import BatchEditForm
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/base/forms.py", line 290, in <module>
    class TKeywordForm(forms.Form):
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/base/forms.py", line 295, in TKeywordForm
    widget=MultiThesauriWidget())
  File "/home/ubuntu/wm-2.10.x/geonode/geonode/base/widgets.py", line 33, in __init__
    autocomplete_light.MultipleChoiceWidget(
AttributeError: 'module' object has no attribute ‘MultipleChoiceWidget’
```

## Steps to Reproduce the Problem

  1. set THESAURI to a value like the ones suggested in the comments
  2. try to load layers page

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu
  - Additional details:

**Comment by capooti** [comment]
@afabiani we don't use thesauri but I can try to find some time to fix this. Not sure when, though

**Comment by capooti** [comment]
oh I see - you thought I closed this. My PR solves a different problem. Reopening it

**Comment by t-book** [comment]
Should be closed with https://github.com/GeoNode/geonode/pull/5157
in favor of https://github.com/GeoNode/geonode/issues/5158

**Comment by capooti** [comment]
thanks @t-book !
