### ISSUE TITLE
Point layer uploaded as CSV cannot be added to QGIS map

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#5106]
## Expected Behavior
CSV point data file uploaded to Geonode is added to QGIS via WFS and displays as points on map

## Actual Behavior
CSV point data file uploaded to Geonode is added to QGIS via WFS and appears as a table not a layer

## Steps to Reproduce the Problem
In browser:
1. Obtain a csv point file such as Basic world cities database from [simplemaps](https://simplemaps.com/data/world-cities)
2. Extract the csv file worldcities.csv and inspect it: looks OK.
3. Login to [master.demo.geonode.org](http://master.demo.geonode.org/)
4. Upload the csv file, selecting lat and lng fields and WGS84 CRS
5. Confirm it displays OK on the map
6. Confirm can download via WFS, e.g. Download Layer > Data > [GeoJSON](http://master.demo.geonode.org/geoserver/ows?srsName=EPSG%3A4326&outputFormat=json&service=WFS&srs=EPSG%3A4326&request=GetFeature&typename=geonode%3Aworldcities&version=1.0.0&access_token=1mtffvrmg5hQfKA48wpRUpa4coKUjV): looks fine, geometry looks fine.

In QGIS ([3.4.12-Madeira](https://qgis.org/en/site/forusers/download.html) on Windows 10):
7. Layer > Add Layer > Add WFS Layer > New
    Name: Master Geonode
    URL: http://master.demo.geonode.org/geoserver/ows
    OK
8. Connect
9. Select worldcities in list
10. Add, Close

**=> ERROR: Dataset `geonode:worldcities` is added as a table not a layer**

But the same CSV dataset, downloaded from Geonode as shapefile and re-uploaded, works fine!

In browser:
11. Return to [worldcities layer on master.demo.geonode.org](http://master.demo.geonode.org/layers/geonode:worldcities)
12. Download Layer > Data > [Zipped Shapefile](http://master.demo.geonode.org/geoserver/ows?outputFormat=SHAPE-ZIP&service=WFS&srs=EPSG%3A4326&request=GetFeature&format_options=charset%3AUTF-8&typename=geonode%3Aworldcities&version=1.0.0&access_token=1mtffvrmg5hQfKA48wpRUpa4coKUjV)

In File Explorer: 
13. Extract zip file
14. Rename files worldcities.* to worldcities_shape.*
15. Select the 5 shapefiles worldcities_shape.* and zip into worldcities_shape.zip

In browser:
17. Upload worldcities_shape.zip
18. Click Layer Info
19. Confirm looks OK on map

In QGIS:
20. Layer > Add Layer > Add WFS Layer > Master Geonode
21. Connect
22. Select worldcities_shape in list
23. Add, Close
24. Zoom to Layer

**=> SUCCESS: Dataset worldcities_shape is added to map as a layer**

![image](https://user-images.githubusercontent.com/4666409/67456378-45446a80-f67c-11e9-8cb7-49f2e9e91977.png)

## Specifications

  - GeoNode version: 2.10.1 at [master.demo.geonode.org](http://master.demo.geonode.org/)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): N/A
  - Platform: N/A
  - Additional details: [3.4.12-Madeira](https://qgis.org/en/site/forusers/download.html) on Windows 10

**Comment by t-book** [comment]
@jondoig 

Tested both with Madeira: a new point layer:
http://master.demo.geonode.org/layers/geonode:ao

and your cities, both do show up without problems? Would you kindly test some other point source (non geonode to be sure it's not your qgis installation?)

<img width="1552" alt="Bildschirmfoto 2019-10-24 um 10 55 51" src="https://user-images.githubusercontent.com/20478652/67469783-f9c69800-f64c-11e9-82c1-659f032dcec3.png">
<img width="779" alt="Bildschirmfoto 2019-10-24 um 10 53 54" src="https://user-images.githubusercontent.com/20478652/67469784-f9c69800-f64c-11e9-9fb0-5b4d51ac1576.png">

**Comment by gannebamm** [comment]
@t-book I think he uses WFS and you use WMS? Would test myself, but our network is currently messy :|

**Comment by t-book** [comment]
@gannebamm good point. did a test and can reproduce it now. but still think this is connected to madeira. will test tomorrow with las palmas (?) whatever name qgis 2.18 😂

**Comment by jondoig** [comment]
Same on QGIS 3.4.11 - I tested that and upgraded to "latest LTS" 3.4.12 Madeira, same result.

Also same for [AURIN](https://aurin.org.au) who were trying to use WFS to ingest our data to their system. They reported their process can't get past DescribeFeatureType.

Armed with this I tried a DescribeFeatureType and found a key difference:
* [DescribeFeatureType on worldcities](master.demo.geonode.org/geoserver/wfs?typename=geonode%3Aworldcities&version=1.0.0&service=WFS&request=DescribeFeatureType) (direct from CSV) has no geom, while
* [DescribeFeatureType on worldcities_shape](master.demo.geonode.org/geoserver/wfs?typename=geonode%3Aworldcities_shape&version=1.0.0&service=WFS&request=DescribeFeatureType) (worldcities downloaded as Shapefile and re-uploaded) does have geom.

That could explain why QGIS treats it as table not layer.

**Comment by jondoig** [comment]
Ping @t-book did you see my last comment?

**Comment by t-book** [comment]
@jondoig sorry I've absolutely missed this!

> That would explain why QGIS treats it as table not layer.

This makes definitely sense and either looks like a regression or some change on geoserver side. I will try to do some investigations as well! thanks for reporting!

**Comment by jondoig** [comment]
ping @t-book any chance you could look at this?

**Comment by t-book** [comment]
@jondoig sorry for being quite. 

> any chance you could look at this?

Unfortunately at earliest starting of February ;/
