### ISSUE TITLE
SPC docker-compose.override.yml does use outdated pg_dumper container

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5109]
## Expected Behavior
If using the "dev compose" of SPC `docker-compose.override.yml` the two pg_dumper (geo / no_geo) containers from docker-compose.yml should bind their volumes to a local mount.

## Actual Behavior
If using the "dev compose" of SPC `docker-compose.override.yml` a **third pg_dumper** container from docker-compose.override.yml binds their volumes to a local mount.

## Steps to Reproduce the Problem

  1. move to `scripts\spcgeonode`
  2. docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
  3. see https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/docker-compose.override.yml#L46 and https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/docker-compose.yml#L145 / https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/docker-compose.yml#L157

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode with override.yml
  - Platform: Docker on Windows 10
  - Additional details:

**Comment by gannebamm** [comment]
Even though it is easy to fix, I won´t fix this, but leave it untill we do our Docker Composition rework sprint. The compositions will change anyway.

**Comment by kikislater** [comment]
Why not getting inspiration from this repo : 
https://github.com/olivierdalang/docker-pgdumper
? 
Is there a milestone for this issue ?
