### ISSUE TITLE
Layer overview - Legend not displaying

### ISSUE THREAD

**Issue by albertStaalburger** [GeoNode/geonode#5111]
The Geonode documentation indicates that once a layer has been uploaded a `legend` can be seen on the `layer overview`, however I am unable to see the legend in the layer overview page nor can I find a reason/error for it not to display.

Is there a setting that needs to be configured during setup in order to see the legend or can someone maybe point me in the direction of the server log(s) where I might be able to see why this isn't displaying as expected.

Environemnt:
OS: Ubuntu 18.04.3 LTS
Geonode: GeoNode version 2.10.1

Link to the question on GIS Stackexchange: [https://gis.stackexchange.com/questions/339659/geonode-layer-overview-legend-not-displaying](https://gis.stackexchange.com/questions/339659/geonode-layer-overview-legend-not-displaying)

**Comment by t-book** [comment]
Hi @albertStaalburger github should be for bugs. for general questions please use the devel or user list at osgeo. Regarding your question do you see any error in browser console ? Looking at current demo it's working as the docs describe: http://master.demo.geonode.org/layers/geonode:airports14

**Comment by albertStaalburger** [comment]
@t-book  - Thank you for the prompt response.
I will migrate the question to osgeo, I was however wondering if anyone else was experiencing this, if so it might have been a bug.

> do you see any error in browser console ? 

I see one XHR request returning a 404: 
`GET http://mygeonode/layers/version.txt 404 (Not Found) | ms2-geonode-api.js:21`
Followed by:
`XHR failed loading: GET "http://mygeonode/layers/version.txt".`

**Comment by t-book** [comment]
@albertStaalburger great let's continue at the list. the version.txt is something different and has nothing to do with legend. closing here please reopen if needed.
