### ISSUE TITLE
Publishing layers of two remote services with same

### ISSUE THREAD

**Issue by sjohn-atenekom** [GeoNode/geonode#5117]
## Expected Behavior
I add a remote service to GeoNode and publish a layer called "municipalities". Then I add a second remote service, and publish a layer with the same name "municipalities". The second layer should get another name, e.g. "muicipalities1", as it works with the layer upload. Layers get published and I can open the Layer Detail view /layers/municipalities for both layers

## Actual Behavior
open the Detailview /layers/municipalities leads a server error, because there are two layers with the same name.

## Steps to Reproduce the Problem
Unfortunately, I can't share the remote services I used for testing, due to access restrictions.

  1. Add Remote Service 1
  2. publish layer
  3. Add Remote Service 2
  4. publish layer with same name
  5. go to layer detail view /layers/layername

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu
  - Additional details: Tested on release branch 2.10.1

**Comment by gannebamm** [comment]
I could reproduce this with image services. Both share a layer name of rgb and nir (both typical names for multi spectral base imagery) resulting in the above mentioned clash.
