### ISSUE TITLE
Packages not in dependencies

### ISSUE THREAD

**Issue by amefad** [GeoNode/geonode#5123]
## Expected Behavior
Following the instructions of this page

http://docs.geonode.org/en/2.10.x/install/core/index.html

user should be able to "Run GeoNode for the first time in DEBUG Mode" 

## Actual Behavior
During installation step:

   ``pip install -r requirements.txt --upgrade --no-cache --no-cache-dir``

An error occurs because the location of pg_config is not on the path. After postgresql installation also the

  ``pip install pygdal=="`gdal-config --version`.*"``

doesn't work as gdal-config output is null

need to add libgdal-dev to system packages required? Is i t worth as we need only the version number?

## Steps to Reproduce the Problem

  1. Clean Ubuntu Bionic 18.04.3 Installaltion
  2. Follow step by step instalaltion instruction
 
The postgresql installation is mentioned a few lines after the "Run GeoNode for the first time in DEBUG Mode" ...  we can:

- add postgresql postgis  to the system packages section, in this case every novice will install postgresql even if not needed;
- comment the requirements.txt line about psycopg2 and tell the user to uncomment when postgresql database is needed;

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04.3 LTS on Virtualbox VM
  - Additional details:

**Comment by t-book** [comment]
Hi @amefad it's true, the built of psycopg2 will fail when pg_config is missing as important header fails cannot be found. but in my experience it should be added to the path when installing postgres, right? However, could you suggest an update to docs?
