### ISSUE TITLE
Layer is by default broken, when set as not visible to anyone

### ISSUE THREAD

**Issue by tallistroan** [GeoNode/geonode#5167]
## Expected Behavior
When a user uploads a layer and deselects the "Anyone" permission on upload, the layer is visible to the user which upload the layer.

## Actual Behavior
When a user uploads a layer and deselects the "Anyone" permission on upload, the geometry and legend for this layer are broken and not visible to the user.

## Steps to Reproduce the Problem

  1. Select shp file for upload
  2. Deselect the "Anyone" checkbox for the view and download permissions
  3. Don't enter a specific user to the permissions
  4. Upload the layer
  5. Go to the layer details page. The geometry and legend for the layer are broken and not visible to the user despite the user is now shown in the permissions overview for the layer

## Possible workarounds
  - Go to "Change layer permissions" and click "Apply Changes" without changing anything
  - OR run the updatelayers command

By using any of the above method, the layer is afterwards visible to the user

## Specifications

  - GeoNode version: 2.10.1, master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform: Linux
  - Additional details: happens also on http://master.demo.geonode.org

**Comment by t-book** [comment]
hi @tallistroan this is a known bug. What should be done is to prefill the form with the current user:

<img width="384" alt="Bildschirmfoto 2019-10-31 um 15 02 11" src="https://user-images.githubusercontent.com/20478652/67953571-ac6b9d00-fbef-11e9-989e-4ed19d0d9d03.png">

I darkly remember I've already created a PR but most likely I missed to merge.

**Comment by tallistroan** [comment]
Thanks for the feedback @t-book . I was not able to find a issue for this bug (maybe I oversaw it), thus I created the ticket.

**Comment by t-book** [comment]
@tallistroan closing here with https://github.com/GeoNode/geonode/pull/5588 
please reopen if you think this needs further care.
