### ISSUE TITLE
Allow customization of default perms (in set_default_permissions)

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#518]
Currently the default permissions (as used by set_default_permissions) are essentially hardcoded in geonode/layers/models.py. It would be nice those default permissions could be overwritten on a per project basis by specifying alternative default permissions in a dict in settings.py that could be overwritten in a local_settings.py (i.e. without having to change the code in layers/models.py)

**Comment by jj0hns0n** [comment]
Can we close this since we have a totally new permission system? @simod

**Comment by capooti** [comment]
+1 to close
