### ISSUE TITLE
NewConnectionError during base test setUp

### ISSUE THREAD

**Issue by travislbrundage** [GeoNode/geonode#5196]
## Expected Behavior
I expect unit tests to have minimal and quick setup. In this case, the base `setUp` should work successfully to setup unit tests.

## Actual Behavior
The [`geonode.tests.base.GeoNodeBaseTestSupport.setUp`](https://github.com/GeoNode/geonode/blob/master/geonode/tests/base.py#L76) will call the `create_models()` function from [`geonode.base.populate_test_data`](https://github.com/GeoNode/geonode/blob/master/geonode/base/populate_test_data.py#L171)

Something goes wrong on the `layer.save()` line: https://github.com/GeoNode/geonode/blob/master/geonode/base/populate_test_data.py#L261

In the console, I see the following error output:
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=6)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5c885ccfd0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /geoserver/rest/workspaces.xml
```

This is causing running unit tests to be quite slow. Each time this setUp is called it takes ~5 minutes on my machine due to this bug. Added up for all tests which inherit this setUp call makes running unit tests much slower.

## Steps to Reproduce the Problem

  1. Run a sample unit test, for example `coverage run --branch --source=geonode manage.py test geonode.base.tests.ThumbnailTests`
  2. Observe the console output and time it takes to test.
  3. Comment out the `layer.save()` line in base test (this is just an example, some tests will fail if no layers are prepared):
  4. Run the same unit test and observe the console output and time it takes to test.
You should notice the time is greatly reduced - for me, it takes ~1 min compared to ~5 mins.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details: N/A

**Comment by gannebamm** [comment]
You should start your geoserver with `paver start` @travisbrundage
I think those issues will be solved by this

**Comment by travislbrundage** [comment]
You are right. Looks like this issue is docker specific (as were my other issues when running tests). Doing a local installation does not have this problem.
