### ISSUE TITLE
Error Creating Layer

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5256]
## Actual Behavior

'NoneType' object has no attribute 'connection_parameters' (<type 'exceptions.AttributeError'>)

## Specifications

  - GeoNode version: 2.10.1 
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 18.04
  - Additional details:

![image](https://user-images.githubusercontent.com/7094961/68708320-c4e69a80-0593-11ea-9ed8-f7f49bb514c0.png)

**Comment by afabiani** [comment]
You need to add at least one attribute.

**Comment by dpadron** [comment]
Sorry

**Comment by capooti** [comment]
strange, I remember it was possible to create a layer with no attributes
