### ISSUE TITLE
Failed to get the certificates

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5260]
Log for Container letsencrypt_1

End of life plan for ACMEv1 Any solution to use ACMEv2?

STARTING LETSENCRYPT ENTRYPOINT ---------------------

Wed Nov 13 15:03:38 UTC 2019

Trying to get PRODUCTION certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred

The client lacks sufficient authorization :: Account creation on ACMEv1 is disabled. 
Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. 
See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

Please see the logfiles in /var/log/letsencrypt for more details.
Failed to get the certificates !

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
ACMEv1 has reached EOL in November. I think we need to update the certbot.

**Comment by t-book** [comment]
hi @dpadron could you kindly test to replace https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/letsencrypt/docker-entrypoint.sh 

with this updated version https://gist.github.com/t-book/339c58c889025a08696f2166628c046c

don't forget to rebuild your containers and let me know if it works.

**Comment by dpadron** [comment]
Hi **t-book**, I performed the test and the following error is generated:


STARTING LETSENCRYPT ENTRYPOINT ---------------------
Sun Nov 17 09:38:02 UTC 2019
Trying to get PRODUCTION certificate
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
KeyError: 'Directory field not found'
Please see the logfiles in /var/log/letsencrypt for more details.
Failed to get the certificates !
Waiting 30s to avoid hitting Letsencrypt rate limits before it's even possible to react
$\n\n\n
-----------------------------------------------------

**Comment by dpadron** [comment]
Solved
Updated FROM alpine: 3.8

in /docker/letsencrypt/Dockerfile

Thanks t-book for the help

**Comment by t-book** [comment]
great! this is what I actually just planned to try :))

the reason is the acme2 protocol has been added in certbot 22+ the current alpine image has certbot below:
```
/ # certbot --version
certbot 0.14.0
```
As I currently do not use spc can you do me a favour and test alpine 3.8 image with the original entrypoint? the question is if the newer certbot already resepcts acme2 without the --server option.

**Comment by t-book** [comment]
@dpadron  okay tested it. it looks we need the --server for acme2

**Comment by dpadron** [comment]
Hi t-book,
I tried it in geonode-project -master
Mode: Docker
S.O. Ubuntu 18.04

Directory: /docker/letsencrypt/
Edit: docker-entrypoint.sh and Dockerfile

Everything worked correctly

I'm going to do tests in SPC and I tell you

I attach files

**Comment by 7scorp** [comment]
Has this solution been merged into the main geonode docker install?  If not, where do I find the updated file t-book mentioned?
