### ISSUE TITLE
Styling issues at welcome page

### ISSUE THREAD

**Issue by kikislater** [GeoNode/geonode#5263]
_edited by @gannebamm to hold all sub-issues as list_

## Expected Behavior
We have a nice and smooth welcome page UI.

- [ ] Correct display without bar on the right
- [ ] Categories do display well without strange linebreaks
- [ ] Maps Thumbnails are resized proportionnal when resizing window
- [ ] themed cookie bar does have proper colors
- [ ] Search input ID is unique

## Actual Behavior

We have some UI glitches in the welcome page UI.

**Bar on the right, resulting in horizontal scrolling**:

![image](https://user-images.githubusercontent.com/13238064/68830534-63264d80-06c5-11ea-9bf3-b51f54e695f3.png)

![image](https://user-images.githubusercontent.com/13238064/68830545-68839800-06c5-11ea-96fb-5e5b528eacc8.png)

![Screenshot_2019-11-14-09-56-28-291_org mozilla firefox](https://user-images.githubusercontent.com/13238064/68830656-ab457000-06c5-11ea-8c53-655984badad6.jpg)

**Categories doesn't display well and do strange linebreaks**: https://github.com/GeoNode/geonode/issues/5263#issuecomment-554609023

**Maps Thumbnails are not resized proportionnal when resizing window**: https://github.com/GeoNode/geonode/issues/5263#issuecomment-554834035

**Issues with cookie bar (themes)**: https://github.com/GeoNode/geonode/issues/5263#issuecomment-554884478

**ID for search input is used twice**: https://github.com/GeoNode/geonode/issues/5263#issuecomment-554884478

## Steps to Reproduce the Problem

  1. Open Geonode demo
  2. Inspect the welcome page ui and html

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): All
  - Platform: All

**Comment by t-book** [comment]
This is caused by the negative margin of https://github.com/GeoNode/geonode/blob/0601f1575eb95ccbe620471bd29644fb0d9f0177/geonode/templates/index.html#L253

scrolls do not appear with chrome but ff.
might be a bug with bootstrap3 - a quick fix would be to give the row: `margin: 0px 0px;`

**Comment by kikislater** [comment]
Cool ! Thank you @t-book 
So error is not here : 
https://github.com/GeoNode/geonode/blob/0601f1575eb95ccbe620471bd29644fb0d9f0177/geonode/static/geonode/css/base.css#L1600-L1603

**Comment by kikislater** [comment]
And another one. It happens in Firefox and Chrome if you switch to French language at some resizing window : Categories doesn't display well.

![image](https://user-images.githubusercontent.com/13238064/68989007-188a0a00-085a-11ea-9844-f5cf44266d97.png)

**Comment by t-book** [comment]
Oh that is ugly ;/ the problem here is that _Fonds de cart_ breaks in the next line. Doing so it's parent div has a different height. Hence the next row children order after it. I think making child divs flex-items by applying the following to the table row would be the way to go.

```
container.text-center .row {
    display: flex;
    display: -webkit-flex;
    flex-wrap: wrap;
}
```

**Comment by kikislater** [comment]
Thank you, it works ! 

Another ugly one IMO but I'm not using it : 
![image](https://user-images.githubusercontent.com/13238064/69022142-bd7c2280-09d3-11ea-96fc-240b2d909fb0.png)

Maps are not proportionnal when resizing window

**Comment by t-book** [comment]
Oh I see. Problem here is the 100% width of the parent div an the fixed height.

it will get better when https://github.com/GeoNode/geonode/blob/0601f1575eb95ccbe620471bd29644fb0d9f0177/geonode/templates/index.html#L304

get's some more classes like: `<div class="col-xs-12 col-sm-6 col-md-3">` further a bit more responsive height handling:

```
.home #showcase .col-md-3 img {
    max-height: 180px;
    width: auto;
}
```

@capooti the right image looks like a custom uploaded thumbnail. Where the left is resized to 180px height the curated one keeps it's original size of ~700px width. This is nothing urgent but wouldn't it be nice to downsize here as well?

**Comment by t-book** [comment]
And as this is growing to something like a frontend wish list I will add one more:

**Semantic issues with cookie bar (themes):**

1. The bar is not the first item on the page and focus is not on the modal when the page loads. Keyboard users have to tab through all items on the page to access the cookie consent window.
2. The anchor tag is being used as a button instead of a navigational link. (The href attribute contains a placeholder value that links to the same page but does not navigate to an anchor point). The semantically correct way would be the use of a button instead.

![Bildschirmfoto 2019-11-18 um 08 07 03](https://user-images.githubusercontent.com/20478652/69031866-5ebaa700-09db-11ea-947d-6730bc21ff45.png)
