### ISSUE TITLE
 Error loading layer in https configuration

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5279]
## Expected Behavior

When the layer is uploaded, it is stored

## Actual Behavior
The following ad is generated

Unexpected error!

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker geonode-project
  - Platform: Ubuntu 18.04
  - Additional details: 
I tried without the https configuration and it works correctly, the problem is when I configure https in # LETSENCRYPT_MODE mode = staging and LETSENCRYPT_MODE = production

![image](https://user-images.githubusercontent.com/7094961/69043855-21164800-09f4-11ea-831f-c97c66be5c13.png)

**Comment by t-book** [comment]
@gannebamm Did you ever experience something similar with SPC and using your custom cert? Maybe it's needed to update something like nginx.conf or geoserver oauth2?

**Comment by dpadron** [comment]
Hello t-book
I have installed the latest version of spcgeonode with the https configuration active in mode productions

I uploaded a layer correctly without problems

Then I wanted to change the settings in Geoserver> Security> geonode identification RES role service

And the following error is generated

![image](https://user-images.githubusercontent.com/7094961/69046941-60479780-09fa-11ea-8568-6b5dd9c02e40.png)

**Comment by gannebamm** [comment]
I do not use letsenscrypt but a custom cert. On my current dev instance which is almost on master the GeoServer settings page does work:

![grafik](https://user-images.githubusercontent.com/6172324/69138306-b716a500-0abe-11ea-9265-293c377f820b.png)

(german)

You could check if your buffer size is big enough, see in docker-compose.yml:
`    command: "uwsgi --chdir=/spcgeonode --module=geonode.wsgi --socket=:8000 --http=127.0.0.1:8001 --processes=5 --buffer-size=8192"`

**Comment by dpadron** [comment]
I have reinstalled everything again (Version 2.10.2.dev1574851926).
I try to upload a shapefile layer and follow the error.

![image](https://user-images.githubusercontent.com/7094961/69721356-f8d5ca00-1114-11ea-9c97-072db74d4aef.png)

Here is the installation URL:
https://geodatos.go.cr
User: admin
Password: admin

Please if you can look at the Geoserver configuration

I used the Docker Mode installation geonode_project in Ubuntu 18.04

Attached .env file
[env.txt](https://github.com/GeoNode/geonode/files/3896725/env.txt)

**Comment by t-book** [comment]
your're ssl cert is not valid anymore. Geoserver trying to communicate to geonodes oauth2 endpoint over https. just a guess but what if you try a) without https b) with a valid cert? is it working?

![Bildschirmfoto 2019-11-27 um 13 07 01](https://user-images.githubusercontent.com/20478652/69722215-d8a70a80-1116-11ea-97d3-8219e4010740.png)

**Comment by dpadron** [comment]
Hello I have tried with a valid certificate https: // the error is the same.
I don't know if the problem is in geonode_project

I really don't know where the error might be :-(

![image](https://user-images.githubusercontent.com/7094961/69740128-2af92300-1139-11ea-8ca5-4ea8c39e27bf.png)

**Comment by dpadron** [comment]
Hello again, @t-book  @gannebamm 
I have tried everything.

The novelty is that I can upload geotif raster layers but not shapefiles.
If someone can look at it and see if there is any problem in the configuration.
The logs say nothing

https://geodatos.go.cr
User: admin
Key: admin123


I remember that I installed docker geonode-project in ubuntu 18.04

![image](https://user-images.githubusercontent.com/7094961/69802210-56334f00-11d9-11ea-92ca-81f8a8ccfe8c.png)

**Comment by afabiani** [comment]
@dpadron there are settings issues here, the upload procedure is trying to call and HTTP endpoint over an HTTPS connection (mixed content is not allowed on HTTPS)

`http://geodatos.go.cr/upload/srs?id=13&force_ajax=true&force_ajax=true`

![image](https://user-images.githubusercontent.com/1278021/69803400-67318f80-11dc-11ea-8251-3216f03a6e66.png)

Most probably you missed the `SITEURL` env variable or you forgot to put "**https**://..." in front of it.

**Comment by dpadron** [comment]
Thank you very much @afabiani and everyone for the help.
Already solved.
The problem was that I had forgotten to change in .env
SITEURL = https: //ideonion.go.cr/

Grateful
