### ISSUE TITLE
UnicodeEncodeError when trying to delete a Layer on a GeoNode instance with action streams containing exotic characters.

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5283]
## Expected Behavior
The layer is correctly recognized and deleted.

## Actual Behavior
Whenever some action object on `actstream` contains some exotic characters, the django action fails with a `UnicodeEncodeError `

## Steps to Reproduce the Problem

  1. Try to create a user with exotic non utf-8 characters on the name
  2. Upload a layer with that user
  3. Go to the admin dashboard and try to delete the layer

## Specifications

  - GeoNode version: 2.10.x +
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

**Comment by t-book** [comment]
Ref.: https://github.com/GeoNode/geonode/issues/4935
