### ISSUE TITLE
"Unexpected error!" on upload of large shapefile 

### ISSUE THREAD

**Issue by jondoig** [GeoNode/geonode#5285]
## Expected Behavior
Layer uploads successfully.

## Actual Behavior
`Unexpected error!` appears 1 minute 50s after `Performing Final GeoServer Config Step`

## Steps to Reproduce the Problem

  1. Drag zip file (see link below) to https://master.demo.geonode.org/layers/upload
  2. Click Upload
  3. Error appears after upload stage completed
  4. Last time it gave:
```
Server Error: timeout
Please check your network connection. In case of Layer Upload make sure GeoServer is running and accepting connections.
```
And geoserver is indeed down on the server now. Was this killed by the upload error?

## Specifications

  - GeoNode version: 2.10.2dev at https://master.demo.geonode.org/layers/upload
  - Additional details: Shapefile with ~25 million points (and two attributes) [linked here](https://unsw-my.sharepoint.com/:u:/g/personal/z8290362_ad_unsw_edu_au/ESP7qYTjpgVBsU7x3ThAnIgB9J0toj6XbjicMFvmA6JVNQ?e=UpIngr).

**Comment by t-book** [comment]
I think master demo is running on docker. Might be a configuration issue.

Candidates:
https://github.com/GeoNode/nginx-docker/blob/master/nginx.conf#L27
or 
https://github.com/GeoNode/geonode-docker/blob/master/uwsgi.ini#L7

**Comment by afabiani** [comment]
Can you try again please? GeoServer was unreachable few hours ago.

**Comment by jondoig** [comment]
@afabiani I just replicated this (again using the [~25 million point shapefile here](https://unsw-my.sharepoint.com/:u:/g/personal/z8290362_ad_unsw_edu_au/ESP7qYTjpgVBsU7x3ThAnIgB9J0toj6XbjicMFvmA6JVNQ?e=UpIngr)):

1. Commenced upload Wed Nov 20 10:20:49 AEDT 2019
2. Full upload bar (upload step complete) Wed Nov 20 10:23:33 AEDT 2019
3. Performing Final GeoServer Config Step Wed Nov 20 10:24:23 AEDT 2019
4. Unexpected error! _shortly before_ Wed Nov 20 10:34:41 AEDT 2019

([Geoserver](https://master.demo.geonode.org/geoserver/ows?service=WFS&version=1.1.0&request=GetCapabilities) still working fine.)

**Comment by t-book** [comment]
Haven't  tested but this might be the reason: Your shp file is over 300mb, in our standard config nginx has a POST size limit of 100mb
https://github.com/GeoNode/nginx-docker/blob/master/nginx.conf#L75
(Yet, unsure how master.demo is configured)

In general, I try to avoid uploads of that size but use FTP, geoserver UI followed by importlayers. (I know this is not an suitable answer for users). However, in case it's the POST size we could think about returning a more understandable error message like "You're upload exceeded the allowed size of 100mb"

**Comment by afabiani** [comment]
It might also depend on GeoServer connection timeouts.
I'll try to review a bit the Master Demo config in order to allow huge files to be updated and will report the changes I've made.

**Comment by simboss** [comment]
@afabiani @t-book @jondoig 

This file is simply too big to upload on master.demo; it should actually fail sooner and in a more comprehensive manner for the end user.

@afabiani I would not make it possible to upload files that are too big (for sure not as big as this one). I would review a bit the config and the probably think about some checks to do to prevent this upload right before it happens.

**Comment by jondoig** [comment]
Yes it would be good to advise the user if a limit has been exceeded, and I see why you'd want to keep the limits low for the demo site, however an admin should be able to raise these limits on their own instances as required.

By the way I just successfully uploaded a 1.59 GB polygon shapefile (dbf 773 MB, shp 834 MB) to our test instance of GeoNode 2.10rc5 with default config. So there doesn't seem to be a 100 MB or 300 MB limit.

**Comment by goatsweater** [comment]
On my instance running in docker I get an error message on the upload page that reads "413 Request Entity Too Large" (Safari just says "Unexpected Error"), and the logs show a failed upload due an nginx setting.

`nginx4geonode    | 2019/12/13 02:41:19 [error] 6#6: *1850 client intended to send too large body: 193854776 bytes, client: 192.168.32.1, server: , request: "POST /upload/ HTTP/1.1", host: "localhost", referrer: "http://localhost/layers/upload"`

There's no way to configure this setting from any interface as far as I can tell. The relevant config is at https://github.com/GeoNode/nginx-docker/blob/master/nginx.conf#L75. Ideally there would be an equivalent to document setting `MAX_DOCUMENT_SIZE` that could be set via the environment, but for layer uploads. A side effect of making this too large is that it will trigger the timeout, so I think if the upload size is configurable the timeout would also need to be.

**Comment by lleoooell** [comment]
Hello there,
I have the same issue, cannot upload large files even if i change the nginx.conf client_limit_file_size to 1000M... i suppose there is something setup with settings.py of geonode and django default settings...
My question is, is there a workaround or something i can do to reload geonode configuration after deploying it ? my instance is already in production, can i change / restart something without loosing all my 200+ layers ?

kind regards

**Comment by iandmozart** [comment]
I had the same issue a few days ago. And it's fixed when updating the harakiri param.

My instance was setup following the Geonode Project on Docker instructions (https://docs.geonode.org/en/master/install/advanced/project/index.html)

What I did was based on t-follow comment above, and this link: https://gis.stackexchange.com/questions/382710/timeout-while-uploading-large-files-in-geonode-geoserver

Steps:

Go to your project folder, check the uswgi.ini file:
cd /opt/geonode_custom/my_geonode
nano uwsgi.ini

Check the line when it says: harakiri = 60 --> increase this parameter to 600:
harakiri = 600

Save and exit

Restart the containers:
docker-compose stop
docker-compose up -d
