### ISSUE TITLE
Problem to change Geoserver password

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5286]
## Actual Behavior

I installed Geonode 2.10.2.dev1574096083 in Docker mode geonode-project with the https configuration active in production.

When accessing Geoserver and clicking Change Administrator Password this error is generated

https://my_domain/geoserver/web/?15-1.ILinkListener-contributedContent-0-contentList-adminlink

![image](https://user-images.githubusercontent.com/7094961/69135654-c0e9d980-0ab9-11ea-8e79-8887ac765b41.png)

## Specifications

  - GeoNode version: 2.10.2.dev1574096083
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker Geonode-project
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
@dpadron can you kindly visit/share your geoserver looks where depending on your log level you might find more information about what is going wrong?
