### ISSUE TITLE
GeoNode login auth to GeoServer not functioning

### ISSUE THREAD

**Issue by rgmrtn** [GeoNode/geonode#5290]
## Expected Behavior
Click on the GeoNode button on the Geoserver login area.
Expect to be logged into Geoserver using GeoNode auth.

![image](https://user-images.githubusercontent.com/3178688/69187237-31a7ea80-0ae8-11ea-8874-359e51cda2d6.png)

## Actual Behavior
Get "Problem loading page"
![image](https://user-images.githubusercontent.com/3178688/69187341-6c118780-0ae8-11ea-9fd3-516b4973ea7f.png)

Network Console:
![image](https://user-images.githubusercontent.com/3178688/69187624-fd80f980-0ae8-11ea-9681-a9f3b49f602a.png)

## Steps to Reproduce the Problem

  1. Login to GeoNode Project as admin
  2. Use menu to select geoserver
  3. Click on GeoNode icon beside login form on Geoserver page

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual - GeoNode Project
  - Platform: Ubuntu Server 18.04 LTS
  - Additional details: Newly installed instance of GeoNode

**Comment by t-book** [comment]
hi @rgmrtn please review your oauth2 settings on geonode and geoserver side. pay special attention to keys and redirect urls this sounds like a configuration issue.

**Comment by rgmrtn** [comment]
@t-book Thanks!
