### ISSUE TITLE
Unable to access WFS or WMS Resources using QGIS

### ISSUE THREAD

**Issue by rgmrtn** [GeoNode/geonode#5297]
## Expected Behavior
Connect to resources based on access permissions set in GeoNode

## Actual Behavior
QGIS is unable to see any available layers.

## Steps to Reproduce the Problem

  1. Uploaded a "Test_Layer" and changed permissions:
![image](https://user-images.githubusercontent.com/3178688/69269565-4eebc000-0b9f-11ea-8763-8b422368680d.png)
  2. Attempt to connect to WFS resource using QGIS @ `http://<geonode-url>/geoserver/ows?service=wfs&version=2.0.0&request=GetCapabilities` and basic authentication for the **testuser** account.
  3. QGIS is showing no layers for the connected WFS resource.
  4. Geofence rules created by GeoNode are visible in Geoserver:
![image](https://user-images.githubusercontent.com/3178688/69269874-efda7b00-0b9f-11ea-8bca-7e1d404b8ee1.png)

## Specifications

  - GeoNode version: 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu Server 18.04 LTS
  - Additional details:

**Comment by t-book** [comment]
How do your rules look like for some restricted layers?

**Comment by rgmrtn** [comment]
@t-book Here are all of the rules so far, only DENY setting is to prevent anonymous browsing.
![image](https://user-images.githubusercontent.com/3178688/69270179-798a4880-0ba0-11ea-9026-0e6ec368cff6.png)

**Comment by t-book** [comment]
Have you tried the proxified url? http://-geonode-url-/gs/ows?

**Comment by rgmrtn** [comment]
It appears to connect, but there are no visible layers:
![image](https://user-images.githubusercontent.com/3178688/69270930-f669f200-0ba1-11ea-8ec7-4a1f9fa3fabd.png)

**Comment by t-book** [comment]
Sorry to ask but checked with an instance: You're sure you setup correct basic auth credentials?

**Comment by rgmrtn** [comment]
Its very possible that I am not authorizing correctly. My goal is to use the authentication built into GeoNode to authorize WFS/WMS/WCS resource access on the underlying GeoServer via QGIS or other desktop GIS applications.

Here is a snip of how I am trying to connect from QGIS (I have changed the url for this example)

![image](https://user-images.githubusercontent.com/3178688/69274288-0dabde00-0ba8-11ea-9553-67d219f4c064.png)

**Comment by t-book** [comment]
Well this looks correct (In my test I've striped the url after ows? but this should not make any difference). Does testuser see all layer online?

**Comment by rgmrtn** [comment]
Yes, signed in the testuser sees the layer, see below.
![image](https://user-images.githubusercontent.com/3178688/69274728-fd483300-0ba8-11ea-8643-6abe87fe46a6.png)

**Comment by t-book** [comment]
> @t-book Here are all of the rules so far, only DENY setting is to prevent anonymous browsing.
> ![image](https://user-images.githubusercontent.com/3178688/69270179-798a4880-0ba0-11ea-9026-0e6ec368cff6.png)

please try to move the deny rule to the very bottom.

**Comment by rgmrtn** [comment]
This allows me to see the layer, but it also lets me see a layer that user is **not supposed** to have access to.
![image](https://user-images.githubusercontent.com/3178688/69275826-28338680-0bab-11ea-90a1-bf1b9912ea2d.png)

Also, some more testing shows that it also allows anonymous/not logged in users to see those layers as well.

**Comment by t-book** [comment]
if the deny is at the bottom from what I see it should work correctly. can you make sure qgis is not using your basic auth behind your back when connecting?

**Comment by rgmrtn** [comment]
I noticed from the link you send to the docs that I had this flag checked incorrectly:
![image](https://user-images.githubusercontent.com/3178688/69276457-857c0780-0bac-11ea-9819-21178dbae936.png)

**But now I don't see any layers, with or without a username and password entered for the basic authentication.**

**Comment by afabiani** [comment]
As far as I know QGis does not set basic header correctly if the client does not ask for basic auth challenge.

 - /gs/ows accepts headers but does not force basic auth
 - /gs/w*s appet headers and force basic auth

so, long story short, to access W*S services from qgis use /gs/w*s endpoints

Moreover, do not enable "Use GeoServer roles to get authorizations", this is meant to be working only with internal role services.

Another possible cause of the problem, is that your GeoFence Role Service is not correctly configured and it is not able to fetch the roles from GeoNode.

It is worth trying to see if the roles have been correctly fetched from GeoNode

![image](https://user-images.githubusercontent.com/1278021/69320735-089b6d00-0c42-11ea-8819-42deff153342.png)

**Comment by rgmrtn** [comment]
Here is a snip of the roles populated under the geonode REST role service:
![image](https://user-images.githubusercontent.com/3178688/69343100-eeaa5c00-0c3a-11ea-9123-0601916eff62.png)

It seems the WFS URL is operating as expected now, but the WMS layers are still giving trouble. They are asking for credentials. Even when using `http://<geonode-url>/gs/wms` See below:

![image](https://user-images.githubusercontent.com/3178688/69343260-4052e680-0c3b-11ea-863c-31c43b861627.png)
![image](https://user-images.githubusercontent.com/3178688/69343274-46e15e00-0c3b-11ea-8686-e7f9017180c9.png)

Also, here are the Filter Chains setup...
![image](https://user-images.githubusercontent.com/3178688/69343316-68dae080-0c3b-11ea-9967-119afa0cdd95.png)

**Comment by afabiani** [comment]
Hi @rgmrtn any chance to do a quick test against https://master.demo.geonode.org/ just to understand if this might be a regression on GeoNode code base or, possibly, a configuration issue on your side?

**Comment by rgmrtn** [comment]
@afabiani sure thing. Is there a demo user that I can test authentication with?

**Comment by rgmrtn** [comment]
@afabiani That seems to have worked. Its most likely a configuration issue.. any thoughts on where to look first?

**Comment by afabiani** [comment]
@rgmrtn this is a bit strange. First of all, try to have a look at Django logs if possible in order to be sure that no error occurs when asking for a WMS layer. Then, I would make a try through a curl request, something like:

`curl -X GET -v -u username:password "http://<geonode>/gs/wms/?service=wms&version=1.3.0&request=GetCapabilities`

If this works, it is a QGis issue. Try maybe to delete the connection and create it again, or to close QGis and open it again.

If this does not work either, most probably it is a problem with the GeoFence rules. Try maybe to access by providing superuser credentials and see if you get back the whole list of layers.

**Comment by rgmrtn** [comment]
@afabiani Here is the response from the curl request: https://pastebin.com/gcFTgU2a

It is synonymous with the fact that QGIS is showing the layers, but when I go to add them to the workspace it brings up the "Enter Credentials" dialog, as seen in my previous snip.

**Comment by afabiani** [comment]
@rgmrtn I see, can you try to perform a GetMap request using curl again? (let me know if you need help creating the correct OWS request... you can also copy an paste one from the borwser map viewer)

**Comment by rgmrtn** [comment]
@afabiani when I perform a curl request to `http://<geonode-url>/gs/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode%3ATest_Layer&bbox=-125.246086120605%2C52.4264450073242%2C-97.3908081054688%2C65.3349914550781&width=768&height=355&srs=EPSG%3A4326&format=image%2Fpng` with the `-u username:password` parameter I get the expected layer as a png image.

Also, as expected, when I perform the same curl request with out user credentials I see:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying <geonode-ip>...
* TCP_NODELAY set
* Connected to <geonode-url> (<geonode-ip>) port 80 (#0)
> GET /gs/wms?service=WMS&version=1.1.0&request=GetMap&layers=geonode%3ATest_Layer&bbox=-125.246086120605%2C52.4264450073242%2C-97.3908081054688%2C65.3349914550781&width=768&height=355&srs=EPSG%3A4326&format=image%2Fpng HTTP/1.1
> Host: <geonode-url>
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.14.0 (Ubuntu)
< Date: Fri, 22 Nov 2019 14:50:22 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 0
< Connection: keep-alive
< x-xss-protection: 1; mode=block
< Content-Language: en
< x-content-type-options: nosniff
< Vary: Authorization, Accept-Language, Cookie, Origin
< X-Frame-Options: ALLOW-FROM HTTP://<GEONODE-URL>/
< WWW-Authenticate: Basic realm="GeoNode"
< Set-Cookie: sessionid=gyptidgmgzhdx1nada6cj0tcn6qijmgh; expires=Fri, 06-Dec-2019 14:50:22 GMT; httponly; Max-Age=1209600; Path=/
<
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host <geonode-url> left intact
```

**Which certainly makes me think its something to do with the way QGIS is passing the parameters, but at the same time confusing because it works on the Demo geonode site!**

**Comment by afabiani** [comment]
@rgmrtn the only thing I can guess, at this point, is that it is something related to the HTTPD server configuration? Probably something that somehow cuts the request headers and/or caches the requests?

Unfortunately, I cannot provide much more help than this currently without somehow reproducing the issue.

Let me know if you find something. Something else you can do would be to put some log/print lines into the geonode/proxy/views/ methods and dump the request headers and urls GeoNode receives from QGis.

**Comment by rgmrtn** [comment]
@afabiani Ok I will try to take a closer look at things.

Should the `GEOSERVER_PUBLIC_LOCATION` , `GEOSERVER_LOCATION` , and `GEOSERVER_WEB_UI_LOCATION` be `http://<geonode-url>/gs` or `http://<geonode-url>/geoserver` in the `/etc/uwsgi/apps-enabled/geonode.ini` file?

**Comment by afabiani** [comment]
`http://<geoserver-url>/geoserver` 

As a good practice, avoid using proxies unless strictly necessary, like in the case of QGis connection with credentials.

**Comment by rgmrtn** [comment]
Ok, well that is correct, are the configuration files for the demo site available for comparison by any chance?

**Comment by afabiani** [comment]
Master demo is basically a customization of "geonode-project" template dockerization.

All the configurations are exactly the same you can find here

- Env variables: https://github.com/GeoNode/geonode-project/blob/master/.env
- Nginx service: https://github.com/GeoNode/geonode-project/tree/master/docker/nginx
- UWSGI params: https://github.com/GeoNode/geonode-project/blob/master/uwsgi.ini

The command to rebuild/republish master demo is:

`docker-compose build --no-cache; docker-compose stop; docker-compose up -d; docker system prune`

**Comment by gioman** [comment]
> Then, I would make a try through a curl request, something like:
> 
> `curl -X GET -v -u username:password "http://<geonode>/gs/wms/?service=wms&version=1.3.0&request=GetCapabilities"`
> 
> If this works, it is a QGis issue. Try maybe to delete the connection and create it again, or to close QGis and open it again.
> 
> If this does not work either, most probably it is a problem with the GeoFence rules. Try maybe to access by providing superuser credentials and see if you get back the whole list of layers.

@afabiani Hi, I'm also struggling with this matter and not 100% sure the culprit is QGIS (well, it may be very well).

this

`curl -X GET -v -u geonodeuseruser:password "https://myurl/geoserver/wms?service=wms&version=1.3.0&request=GetCapabilities"`

here returns

`The request has not been applied because it lacks valid authentication credentials for the target resource.`

while in a browser using 

`https://geonodeuseruser:password@myurl/geoserver/wms?service=wms&version=1.3.0&request=GetCapabilities`

returns as expected a Capabilities xml document that includes the layer/s that are accessible only to "geonodeuseruser".

The ArcGIS WMS client do not show the protected layers when the connection is configured with the Geonode user username and password while QGIS's one seems to fail to download the Capabilities.

My main doubt is if in a standard Geonode docker installation there is any need to go thorough https://docs.geonode.org/en/master/advanced/components/#oauth2-security-authentication-and-authorization or it should work out of the box. For example " REST Role Service Settings" (in "AuthKEY REST Role Service geonode REST role service") is set to "http://geonode:80", should this be changed to "https://mygeonodeurl"? I tried change it, but it does not seems to change anything.

Any hint would be appreciated,

regards

**Comment by gioman** [comment]
> Hi, I'm also struggling with this matter and not 100% sure the culprit is QGIS (well, it may be very well).

@afabiani actually is even weirder because in WMS capabilities I can see the protected layers even if not using the user/passwd while the WFS capabilities rightly do not show those layers when not using user/passwd.

**Comment by afabiani** [comment]
@gioman you cannot access `geoserver/wms` endpoint directly unless you are able to replicate all the GeoNode users into the internal GeoServer catalog.

Otherwise you must always use the GeoNode proxy `gs/wms`

**Comment by gioman** [comment]
> @gioman you cannot access `geoserver/wms` endpoint directly unless you are able to replicate all the GeoNode users into the internal GeoServer catalog.
> 
> Otherwise you must always use the GeoNode proxy `gs/wms`

@afabiani thanks for the feedback, I overlooked that and I also was pointed to the right URL on Gitter.

Anyway I'm seeing a strange thing:

for WFS works as expected (no credential, no protected layers in the GetCapabilities)

but for WMS even with no credentials the protected layers are returned in the GetCapabilities and the anonymous user can defintely download/getmap them.

I'm using a normal geonode/docker installation and I have not changed any geoserver/geofence configs.

**Comment by giohappy** [comment]
> but for WMS even with no credentials the protected layers are returned in the GetCapabilities and the anonymous user can defintely download/getmap them.

@gioman can you double check that no Geoserver session is active in your browser?

**Comment by gioman** [comment]
> @gioman can you double check that no Geoserver session is active in your browser?

@giohappy Hi, I found the source of the problem: in Geoserver/Geonode geofence configs there is one rule for WMS (and one for WCS) that should not be there, as it is high in the priority list and allows access to everyone even for protected layers. The same rule for WFS is not there, and this matches my observations.

**Comment by giohappy** [comment]
@gioman I don't see such a rule in a standard GeoNode setup.

**Comment by gioman** [comment]
> @gioman I don't see such a rule in a standard GeoNode setup.

@giohappy see https://github.com/GeoNode/geonode/issues/7351#issuecomment-823288073

I tested both GN 3.1 and 3.2 (docker installation) and such (wrong) rule appears as soon as you load a new layer.
