### ISSUE TITLE
simplejson is not required

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#5316]
## Expected Behavior
Removing simplejson dependency in requirements.txt should cause tests to fail.

## Actual Behavior
The tests pass implying simplejson is not required. Additonally, there is no import of simplejson itself, only the deprecated statement `from django.utils import simplejson as json`

## Steps to Reproduce the Problem

  1. Remove the line specifying simplejson as a requirement in requirements.txt
  2. Install and set up GeoNode environment
  3. Execute 'paver run_tests'

## Specifications

  - GeoNode version: 3.0.dev1574167943
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04 LTS
  - Additional details:

**Comment by mtnorthcott** [comment]
This issue could be resolved by either removing the `simplejson` dependency entirely in favour of solely using the built-in library `json` or by changing references to `django.utils.simplejson` to  `simplejson`. What would be the best method?

I should mention I have made the former change as part of the Python 3 upgrade to GeoNode (https://github.com/GeoNode/geonode/issues/4276) but have not made any PRs. I would like a second opinion first :)

**Comment by afabiani** [comment]
@mtnorthcott I personally don't have particular preferences for one or another. Do you envisage some potential issues or have a list of pros and cons? If the solutions are equivalent, go ahead with the one you prefer.

**Comment by t-book** [comment]
From what I know json is simplejson in stdlib? So when we use simplejson will get a more up to date version. On the other hand newer is not always the better. simplejson has/had a unicode error: https://code.google.com/archive/p/simplejson/issues/40 which I would personally would see as an exclusion criterion. (if it still exists)

**Comment by mtnorthcott** [comment]
Yes, simplejson and json are equivalent. simplejson has been around since early versions of Python simply because there was no alternative. I would prefer reducing the number of dependencies and making the switch to use Python 3's built-in json library. As there is no strong motivator to retain legacy packages besides backwards compatibility, which I doubt many users will take advantage of, I will go ahead with this approach. Thank you both for your input here :)

**Comment by t-book** [comment]
> I would prefer reducing the number of dependencies and making the switch to use Python 3's built-in json library

very good thanks!
