### ISSUE TITLE
GeoNode 2.10.x uses geonode-oauth-toolkit==1.1.4.6 which is not Python 2 compatible

### ISSUE THREAD

**Issue by frafra** [GeoNode/geonode#5357]
## Expected Behavior

No Python 3 only code in a Python 2 release.

## Actual Behavior

Various errors due to Python 3 syntax incompatibilities in GeoNode 2.10.x, which is Python 2 only, such as: `TypeError: super() takes at least 1 argument (0 given)`

## Steps to Reproduce the Problem

  1. Misconfigure oauth2 and try to login on GeoServer via GeoNode.

## Specifications

  - GeoNode version: 2,10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode

## Extra

`geonode-oauth-toolkit==1.1.4.6` has been backported from master to 2.10.x. I am not sure if that cause the regression or if the issue is related to a previous commit.

**Comment by afabiani** [comment]
@frafra I guess this issue is a side effect caused by the fact that you don't have the OAuth2 app "GeoServer" correctly configured on GeoNode, or, the Redirect URIs do not match.

**Comment by frafra** [comment]
It is a redirect URI mismatch indeed, but I was wondering if having Python 3 code in a Python 2 project could cause other issues.
