### ISSUE TITLE
Search services are not saved in Client MapStore

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5377]
## Expected Behavior
1.- Create a Map
2.- Create a Search Service
3.- I save the map
4.- I try to make a query
5.- It generates a result correctly

![image](https://user-images.githubusercontent.com/7094961/70132499-a9e3e380-1684-11ea-92a1-79eb6f89e9f7.png)

![image](https://user-images.githubusercontent.com/7094961/70132537-bc5e1d00-1684-11ea-97bc-a850819f6066.png)

## Actual Behavior

1.- Create a Map
2.- Create a Search Service
3.- I save the map
4.- I try to make a query
5.- It generates a result correctly
6.- I leave the Map and go back to the Map and the query service that I have previously generated disappears

![image](https://user-images.githubusercontent.com/7094961/70132485-9e90b800-1684-11ea-8e9a-8696ef448bd8.png)

## Steps to Reproduce the Problem

I have done the tests at http://master.demo.geonode.org/

## Specifications

  - GeoNode version:  version 2.10.2.dev1575378173
  - Installation metho (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by gannebamm** [comment]
duplicate with #5589 #5091 ?
