### ISSUE TITLE
I want to make geoserver WFS layer editable using leaflet draw and edit features also reflect on geoserver layer

### ISSUE THREAD

**Issue by lavesh-jain-123** [GeoNode/geonode#5401]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by t-book** [comment]
@lavesh-jain-123 could you please update the ticket to meet our requirements?

- the title should be short and meaningful f.e.: _Make GeoServer WFS editable using leaflet_
- the description should clearly answer the questions from the issue template

thanks!
