### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#5406]
## Expected Behavior

A layer should be uploaded correctly.

## Actual Behavior

In a instance any upload fails with a ""TypeError: can't pickle traceback objects"
Checking the PostgreSQL log I see:

```
LOG:  statement: UPDATE "base_hierarchicalkeyword" SET path='0004'||SUBSTR(path, 5) WHERE path LIKE '0003%'
ERROR:  duplicate key value violates unique constraint "base_hierarchicalkeyword_path_key"
DETAIL:  Key (path)=(0004) already exists.
```

It looks like hierarchicalkeyword fails to assign an unique path to the new layer.
(not sure why do we need a keyword at all - they should be set only by the users, don't you think?)

## Steps to Reproduce the Problem

Not sure how this can be reproduced.

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

**Comment by capooti** [comment]
it seems related to a problem in treebeard
https://github.com/django-treebeard/django-treebeard/issues/53

**Comment by gannebamm** [comment]
Is this major? Would postpone this to get 3.0 faster

**Comment by stuaxo** [comment]
This issue is not resolved because the treebeard issue is not resolved.

**Comment by JorgeMartinezG** [comment]
One quick solution that I found to this is to drop the unique contraint for the path column. It usually happens when migrating data to newer geonode versions (where **base_hierarchicalkeyword** model uses treebeard with taggit).

```
"base_hierarchicalkeyword_path_key" UNIQUE CONSTRAINT, btree (path)
```
