### ISSUE TITLE
Client Error: Bad Request Unexpected exception upload_files() got an unexpected keyword argument 'charset_encoding'

### ISSUE THREAD

**Issue by thevinhhuynh** [GeoNode/geonode#5418]
Hi all,
## Actual Behavior
Client Error: Bad Request Unexpected exception upload_files() got an unexpected keyword argument 'charset_encoding'
## Steps to Reproduce the Problem

  1. Click layers
  2. Add Shapefile 
  3. Click Upload Layers -> Error

## Specifications

  - GeoNode version: 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 18.04

**Comment by t-book** [comment]
Hi @htv1088935 any chance to get a demo set of your data for testing?

**Comment by anjogu** [comment]
Hi @t-book any solution on this?
