### ISSUE TITLE
Layer feature info templates are not used inside maps

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5429]
Since the layer's templates were correctly used for getfeatureinfo results until layers were listed on the map page. After saving the map again layer was removed from the map page and the basic getfeatureinfo textual response is shown (although the original layers still show the correct template).

Results for layer "Borehole" inside the map:
![image](https://user-images.githubusercontent.com/571129/70549999-66521380-1b75-11ea-9238-9066882992a2.png)

Results inside layer's own view:
![image](https://user-images.githubusercontent.com/571129/70550071-81248800-1b75-11ea-9f43-7f3a1af15b16.png)

**Comment by gannebamm** [comment]
what about the settings in mapstore?
![grafik](https://user-images.githubusercontent.com/6172324/71077604-0b797700-2188-11ea-8cde-afc74cd04f32.png)

You can switch between text, properties and HTML. The latter could be very interessting for data providers wanting to style the getFeatureInfos in a certain way.

**Comment by afabiani** [comment]
the plan would be to improve the interaction between GeoNode and MapStore in the near future and allow also to save other preferences from MapStore to GeoNode, like the layer format, caching options, opacity and so on.

For the time being, this is just a fix in order to avoid people get confused about the GetFeatureInfo output format.
