### ISSUE TITLE
Map Composer Query box behavior wonky

### ISSUE THREAD

**Issue by matthewhanson** [GeoNode/geonode#543]
In Map Composer:

Load vector layer, hit Query button.    The Query window, and the Query results window both pop up.

There are two issues that are very similar.

1) If you press Cancel in the Query window it says "Querying", but then does nothing.   I'd think that Cancel should close the window

2) There's no way to close the Query results window once opened.   Pressing the Query button up top will close the Query window, but not the Query Results window.

**Comment by jj0hns0n** [comment]
@bartvde sorry to keep bugging you about things. How hard is it for us to change the "Cancel" button to "Clear"

![geoexplorer_-_example_com_and_geonode_ _bash_ _125x44](https://cloud.githubusercontent.com/assets/506078/6044332/c8a6fb06-ac92-11e4-9e54-0af71f6a3402.png)

And to have the query button close the entire panel (Query and Table panels) vs just the Query one?

We have our own fork of both gxp and suite but not sure where to make these kinds of changes. If you can point us in the right direction, we may be able to fix it ourselves.

**Comment by bartvde** [comment]
For the text you can change it here: https://github.com/boundlessgeo/gxp/blob/master/src/script/plugins/QueryForm.js#L64

or just set ```gxp.plugins.QueryForm.prototype.cancelButtonText = 'Clear';``` at the GeoNode level.

The other question I need to investigate a bit more.

**Comment by bartvde** [comment]
As for the second question, you can modify the code here:

https://github.com/boundlessgeo/gxp/blob/master/src/script/plugins/QueryForm.js#L145

and add this line:

```
Ext.getCmp('table').ownerCt[pressed ? 'expand' : 'collapse']();
```
