### ISSUE TITLE
API endpoints reveal too much information

### ISSUE THREAD

**Issue by sjohn-atenekom** [GeoNode/geonode#5437]
## Expected Behavior
- API-Endoinsts do not reveal user or group information on unauthenticated requests

## Actual Behavior
- Endpoints /api/profiles, /api/owners /api/groups reveal information, which should be accessible for unauthenticated requests
Following information can be accessed: complete Userdetails, Email-Addresses, Name of groups

## Steps to Reproduce the Problem

  1. https://master.demo.geonode.org/api/profiles
  2. https://master.demo.geonode.org/api/owners
  3. https://master.demo.geonode.org/api/groups

## Specifications

  - GeoNode version: 2.6 / 2.10.0 / 2.10.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Debian
  - Additional details:

**Comment by sjohn-atenekom** [comment]
We already patched this issue in our instance by adding an authorization-class, which only returns a full list of information only for superusers. For unauthenticated request, an empty list is returned.

I'm aware of the fact, that GeoNode ist a collaborative platform and searching for users is a feature. But at least for unauthenticated users, searching for people should not be permitted.

I can provide a fix for that issue, but would like to discuss before, how the endpoints should be protected and what feature might be affected.

**Comment by afabiani** [comment]
What about having a setting to hide / anonymize those informations?

**Comment by giohappy** [comment]
Well, this also affects the users page, even if it provides reduced informations to anonymous users..

**Comment by sjohn-atenekom** [comment]
That's a good idea.
First off all, the email addresses should be cut out from the owners-endpoint (dehydrate_email) like it is done at the profiles endpoint.
Second of all, I propose introducing the setting LOCKDOWN_API (default to True), which returns empty lists for unauthenticated requests to all API resources which inherit TypeFilteredResource.
This will affect following endpoints:
- keywords
- thesaurus/keywords
- regions
- categories
- groups
- profiles
- owners

Returning empty lists instead of completely makes sure, that no functionality will be broken.
