### ISSUE TITLE
Travis Selenium Integration Tests SPCGeonode is failing

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#5466]
## Expected Behavior

Travis: Selenium Integration Tests SPCGeonode runs successfully

## Actual Behavior

Selenium Integration Tests SPCGeonode is failing.

>  Exception: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.

It looks like Firefox Browser cannot start correctly of exits before test is finished? 

Notable selenium base is working.

**Comment by afabiani** [comment]
@t-book I just make a try by creating spcgeonode containers through geonode-selenium. The containers have been correctly created and manual uploads work as expected. This suggests that the issue should be somehow related to the "geonode-selenium" container, not being able to initialize "gecko-driver" anymore or something.

**Comment by t-book** [comment]
@afabiani I can confirm this behavior. Maybe we can get some logs from the firefox binary or driver ?

**Comment by t-book** [comment]
@afabiani the only thing what currently makes sense to me is that firefox-esr has been upgraded and maybe something is different with profiles (I had this several times with selenium in node context) However. the package has been updated last time at 2019-12-08 13:37:54 ... but after that travis still worked  :/

**Comment by t-book** [comment]
@afabiani 

**Working builds used:**

https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.3.0esr/linux-x86_64/en-US/firefox-68.3.0esr.tar.bz2 [64828367/64828367]

**failing Builds used:** 

https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.4.0esr/linux-x86_64/en-US/firefox-68.4.0esr.tar.bz2 [64924893/64924893]

---

I think this could be worth a try?
firefox-esr=68.3.0esr
https://github.com/GeoNode/geonode-selenium/blob/master/Dockerfile#L7

**Comment by t-book** [comment]
Tested it's not the firefox version, nor the geockdriver version and not selenium-base. however maybe the combination of each version. I would say the best is to check how to get the binary and driver logs out of the container to see what is going on.

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode-selenium/pull/81
