### ISSUE TITLE
Map Thumbnails Broken

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5504]
## Expected Behavior
Map thumbnails are correctly rendered.

## Actual Behavior
Map thumbnail results to be a broken image

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by frafra** [comment]
It seems something that could be added to geonode-selenium tests...

**Comment by afabiani** [comment]
> It seems something that could be added to geonode-selenium tests...

@frafra sure, I'll give it a try on a separate DRAFT PR. I'm not very familiar with selenium tests yet.
