### ISSUE TITLE
test_layer_permissions is not returning the expected response

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#5520]
## Expected Behavior
geonode.security.tests.BulkPermissionsTests.test_layer_permissions should correctly assert the value of the 'Content-Type' from responses.

## Actual Behavior
geonode.security.tests.BulkPermissionsTests.test_layer_permissions are using assertTrue which only validates that a 'Content-Type' is being returned. This does not correctly check the value of the 'Content-Type'. When changing this to use assertEqual the test fails.

On further observation, the response shows a service exception saying that the Layer could not be found as follows 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://localhost:8080/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd">      
<ServiceExceptionReport version="1.1.1" >   <ServiceException code="LayerNotDefined" locator="layers">    
      Could not find layer geonode:san_andres_y_providencia_poi
</ServiceException></ServiceExceptionReport>
```

## Steps to Reproduce the Problem

  1. Run the tests which should pass
 ```python
python manage.py test geonode.security.tests.BulkPermissionsTests.test_layer_permissions
```
  2. Change line 735 in geonode/security/tests.py to assertEqual and rerun tests - they should now fail. 
 3. To see the error output add logger.info(response.read()) before the assert statement.

## Specifications

  - GeoNode version: 2.10.1
  - Installation method: manual
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by dhlambert** [comment]
@afabiani Have had a look into this issue, but still quite unsure of why the service exception is occurring or how long this has been an issue for. Would it be possible for someone with more experience in this project to have a look into this please.

**Comment by afabiani** [comment]
@dhlambert I was already planning to have a look. Not this week unfortunately, I am out of office for work. Will take a look at the pending issues when I come back.
