### ISSUE TITLE
able to upload layer through commandline ,unable to upload through GUI ? 

### ISSUE THREAD

**Issue by jitendrashahiitb** [GeoNode/geonode#5531]
In communitygis ( makerghat.urbnsciences.in ) where geonode is the backend, it is not possible to upload shapefile thru GUI
It is possible to upload only thru commandline

**Comment by t-book** [comment]
hi @jitendrashahiitb to understand correctly. makerghat.urbnsciences.in  is your geonode instance ? In case we are speaking about a custom project (communitygis) their issues tracker might fit better. However, in case the former, please ask your question regarding configuration at the user / dev list at osgeo. Github is for bug tracking.
