### ISSUE TITLE
Reduce paver wait time

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#5555]
## Overview

There are several calls to `sleep 30` within `pavement.py`. It would be a fair QOL improvement for developers testing locally for waiting times to be reduced to a minimum.

### Proposed By

@mtnorthcott Matthew Northcott <matthewnorthcott@catalyst.net.nz>

### Assigned to Release

This proposal is for GeoNode 3.0.

### State

* [ ] Under Discussion
* [ ] In Progress
* [x] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

This will be a QOL improvement for developers who run GeoNode locally.

## Proposal

I suggest the `psutil` package is taken advantage of so there are more intelligent checks performed for running processes. i.e. Instead of sending a `SIGKILL` to geoserver and waiting 30 seconds before assuming geoserver has terminated, paver blocks until the PID of geoserver is no longer present. `psutil` has the capability to do this.

### Backwards Compatibility

`psutil` is backwards compatible and has been a requirement of GeoNode for some time.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Paolo Corti:
* Simone Dalmasso:
* Toni Schoenbuchner:

**Comment by t-book** [comment]
@mtnorthcott thanks sound good +1
