### ISSUE TITLE
[Docs] Few refuses and formatting issues on Developer docs section "how to develop"

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5562]
- [x] sentences reporting some code snippets, are highlighet `differently `form ordinary text; e.g. we can add `".home .jumbotron { background: red }"` to that file
 - [x] all code snippets must be highlighted as code blocks; e.g.: <Directory “/path/to/my_geonode/”> Order allow,deny Require all granted</Directory>
 - [x] the section "Create your own django app" should be at the same level of "Customize the look and feel"; it is a completely different topic
 - [x] check that **all** links are still valid; if not update or remove them; e.g.: http://docs.geonode.org/en/master/tutorials/install_and_admin/quick_install.html

**Comment by maabdelghaffar** [comment]
All fixed and PR #5565 created
