### ISSUE TITLE
[Docs] Backport (and update) Developer docs sections from 2.8.x documentation

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5563]
1. http://docs.geonode.org/en/2.8.1/tutorials/devel/devel_intro/index.html
2. http://docs.geonode.org/en/2.8.1/tutorials/devel/django_overview/index.html
3. http://docs.geonode.org/en/2.8.1/tutorials/devel/devel_core/index.html
4. http://docs.geonode.org/en/2.8.1/tutorials/devel/devel_debug/index.html

**Comment by t-book** [comment]
@afabiani  I've just skimmed the docs section in question. It looks like this still targets apt setup. In other words, a (bigger) rework is needed. IMHO this should not block 2.10.2 release. Let's set it to  3.0 Milestone?

**Comment by gannebamm** [comment]
I would get rid of all third-party documentation like http://docs.geonode.org/en/2.8.1/tutorials/devel/django_overview/index.html Django stuff. This:

`Some parts of this section have been taken from the DJango project and training documentation.`

Will lead to hard to maintain docs, would you agree?

**Comment by t-book** [comment]
@gannebamm  Yes agree, the less third-party docs, the less 404 errors or outdated versions.

**Comment by afabiani** [comment]
Roger, going to start the release process.
I will prepare a list of things to do and a brand new spreadsheet for the tests.

Until now there shouldn't be blocking or major issues on 2.10.2 milestone.
We should maybe just decide what to remove if we think this is not ready for a release yet.

**Comment by t-book** [comment]
@afabiani @gannebamm In the long term What do you think about having docs in a separate repository.

**Pro:**
- Travis will not get blocked with changes from docs
- the filesize of geonode base will shrink
- we can treat issue management different for little correction of typos ...

If you agree I would create a GNIP and could care about updating RTD. The only thing where I would need your help is with creating a new repository (do not have permissions for it)

**Comment by afabiani** [comment]
@t-book I agree

**Comment by gannebamm** [comment]
I will test a GeoNode py3 windows dev setup with WSL and VSCode like shown here: https://www.youtube.com/watch?v=mIHprjsSO9o

If this works it could be incorporated into the docs. Which should reside in there own repo, as @t-book suggested.

**Comment by t-book** [comment]
move to new docs
