### ISSUE TITLE
Configure Search Services Not Saved

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5589]
## Steps to Reproduce the Problem

1. Open Configure Search Service Client MapStore
2.- Add Search Service
3.- Save Map
4.- Perform Search test. The result is satisfactory OK
5.- I leave the map and enter the map again
6.- Surprise! The added Search Service configuration has disappeared

## Specifications

  - GeoNode version: 3.0 and 2.10.1
  - Installation method: GeoNode Docker, SPCGeoNode, Geonode-Project 
  - Platform: Ubuntu 18.04
  - Additional details: 

![test_search_geonode_fix](https://user-images.githubusercontent.com/7094961/73598118-3b13f100-4534-11ea-931f-41b5afa10294.gif)

**Comment by gannebamm** [comment]
duplicate with #5377 #5091
