### ISSUE TITLE
Login problem when Registration is disabled

### ISSUE THREAD

**Issue by francoperversi** [GeoNode/geonode#5592]
Using a geonode istance with the Registration disabled, when a user tries to login with a wrong username and/or password, a click on the Username and Password fields redirect to an error page

![login_gn](https://user-images.githubusercontent.com/54808782/73647610-2773a200-467c-11ea-8054-9e3ae2a4f1d8.gif)

## Steps to Reproduce the Problem

  1. Be sure that the user Registration is disabled
  2. Click on Login
  3. Insert a wrong username and/or password and Login
  4. Click on Username input box or PAssword input box

## Expected Behavior
The page doesn't change and the user is able to change Usename/Password

## Actual Behavior
As soon as you click on the Username or Password input field you will be redirect to an error page

## Specifications

  - GeoNode version: 2.10.2.
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by maabdelghaffar** [comment]
under investigation

**Comment by maabdelghaffar** [comment]
Couldn't reproduce the error given the above specifications.

The followed steps were:
1- Install a fresh Geonode instance from Master branch (to test it against Geonode3 too)
2- Install a fresh Geonode instance from 2.10.x branch (to test it against Geonode 2.10.2 as reported)
3- Disable the registration from settings as follows: 
_ACCOUNT_OPEN_SIGNUP = ast.literal_eval(os.environ.get('ACCOUNT_OPEN_SIGNUP', 'False'))_
4- Re-produce the reported behaviour

**Results:** 
- After installing a fresh Geonode-3 instance, the reported error wasn't found and it works properly without issues 
- After installing a fresh Geonode-2.10.2 instance, the reported error wasn't found and it works properly without issues (please refer to attached screenshot)

**aside notes:** 
1- osgeo is generating errors in the terminal with "paver start" which wasn't there when using Geonode2.10
2- The view profile throws a value error as attached below

No errors on focus event
<img width="1063" alt="login-error-issue-5592" src="https://user-images.githubusercontent.com/10365414/74270472-2c32f880-4d03-11ea-97ef-087a9ff5a055.png">


Error when view profile is called
<img width="1075" alt="Screen Shot 2020-02-11 at 16 26 52" src="https://user-images.githubusercontent.com/10365414/74270521-42d94f80-4d03-11ea-8489-bc149a431ed7.png">

**Comment by afabiani** [comment]
Thanks @maabdelghaffar 
This second issue should be already covered by https://github.com/GeoNode/geonode/issues/5668

**Comment by AnnalisaS** [comment]
I found same error in 3.1 release, if I set languange to Italian. If I set English, the error doesn't occur
