### ISSUE TITLE
Users Avatar and Groups Logo appear as broken img 

### ISSUE THREAD

**Issue by francoperversi** [GeoNode/geonode#5593]
In master.demo adding a new User Avatar and Groups Logo or updating an existing one, it appears as broken image. In console it reports that the resource is not found (404).

## Steps to Reproduce the Problem
 **For Groups Logo**
* Login as admin
* Create a new group
* Set a title, a Logo and a description

_Behavior 1_

**For Users Avatar**
* Login as user
* Click on Profile
* Click on edit profile
*Change the avatar
* Upload an image and save
* Click on Upload profile

_Behavior 2_

## Expected Behavior
1. The logo is set and it appears near the group name
2. The avatar is set and it appears near the user name

## Actual Behavior
1.
![broken_avatar](https://user-images.githubusercontent.com/54808782/73656649-e5a12680-4690-11ea-80df-f47a7658e45c.jpg)

2.
![broken_logo](https://user-images.githubusercontent.com/54808782/73656786-239e4a80-4691-11ea-92bf-2c5ce2c67bfd.jpg)

## Specifications

  - GeoNode version: 2.10.2 master-demo
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
If I reproduce this I see, that there is no resized folder and image created. Example:

`/opt/geonode/geonode/uploaded/avatars/admin/pic.png` does exist

`/opt/geonode/geonode/uploaded/avatars/admin/resized/200/pic.png` does not exist

Hereby `pic.png` is 79x78 pixels. Testing a larger example image (1920x1080px) it does not get resized, either.

**Comment by gannebamm** [comment]
Maybe this is linked to: https://github.com/grantmcconnaughey/django-avatar/issues/153

In there a new version of pillow will fail to create the resized images.
