### ISSUE TITLE
Geonode does not start

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#5636]
I did not find any errors in the installation process.
But, at the moment of starting the containers it does not finish starting

## Specifications

/sbin/start-stop-daemon: warning: failed to kill 27: No such process,
Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.,
Starting periodic command scheduler: cron.,
DATABASE_URL=postgres://geonode:geonode@db:5432/geonode,
GEODATABASE_URL=postgis://geonode:geonode@db:5432/geonode_data,
SITEURL=http://localhost/,
ALLOWED_HOSTS=['django', 'localhost', 'localhost:None', 'geonode', 'django'],
GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/,
MONITORING_ENABLED=True,
MONITORING_HOST_NAME=geonode,
MONITORING_SERVICE_NAME=local-geonode,
MONITORING_DATA_TTL=365,
waitfordbs task done,
running migrations,
migrations task done,
DOCKER_ENV=production,
prepare task done,
/usr/src/my_geonode/entrypoint.sh: line 43: [: =: unary operator expected,
/usr/src/my_geonode/entrypoint.sh: line 43: [: =: unary operator expected,
refresh static data,

------------------------------
  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode-Project
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by no7rosman** [comment]
Did you figure this out? I am having the same problem.
