### ISSUE TITLE
Geonode not display all layer 8 of 110

### ISSUE THREAD

**Issue by addean** [GeoNode/geonode#5638]
## Expected Behavior
Geonode list all layers from geoserver

## Actual Behavior
Geonode only able display 8 layers even geoserver has 1++ layers

## Steps to Reproduce the Problem

  1. import layers using command
  2. run `updatelayer` `docker-compose exec django django-admin.py updatelayers -w geonode`
     ![image](https://user-images.githubusercontent.com/22883450/74141080-3dabd000-4c31-11ea-9e85-bdcc7a1ff4b7.png)
  2. view layers in geonode. only 8 layers listed after runserver
   ![image](https://user-images.githubusercontent.com/22883450/74141054-31c00e00-4c31-11ea-8491-17cd4e43b186.png)
## Specifications

  - GeoNode version: 2.10.1
  - Installation method (GeoNode Docker):
  - Platform: Linux
  - Additional details:

**Comment by gannebamm** [comment]
Could you please check your GeoServer inventory? Are the layers listed in there?

**Comment by addean** [comment]
> Could you please check your GeoServer inventory? Are the layers listed in there?
in geoserver
![image](https://user-images.githubusercontent.com/22883450/74207859-249c3100-4cbc-11ea-9ef1-0ab85a0a1f1d.png)
![image](https://user-images.githubusercontent.com/22883450/74207882-45648680-4cbc-11ea-832d-08509ad26f88.png)

after updatelayers no layers available in geonode

**Comment by gannebamm** [comment]
Ok, this looks good. Could you please log into your GeoNode admin interface (http://localhost/en/admin/) and take a look at localhost/en/admin/layers/layer/ ?

**Comment by addean** [comment]
just to update. when posting the issue, I forgot to mention that when I run `docker-compose exec django django-admin.py updatelayers -w geonode` for the first time, it will tell me there is no tables in my database. but all the tables already migrate.

produce error no tables
![image](https://user-images.githubusercontent.com/22883450/75401490-45f85080-593d-11ea-9db6-b1cd16c039bf.png)

But the tables were already exist
![image](https://user-images.githubusercontent.com/22883450/75401527-5f999800-593d-11ea-8eca-ae3aaf254582.png)

**Comment by addean** [comment]
i found out the reason why it not able to show to geonode.

If print geonode.settings.DATABASE_URL, when run `docker-compose run django python manage.py makemigrations --noinput` it will show `postgres://geonode:geonode@db:5432/geonode`

while run `docker-compose exec django django-admin.py updatelayers -w geonode` it will show `sqlite:////usr/local/lib/python2.7/site-packages/geonode/development.db`

My solution is, change `DATABASE_URL = postgres://geonode:geonode@db:5432/geonode`, then it will displayed in database

**Comment by gannebamm** [comment]
@addean Thank you for the deep investigation. Do you use genode docker, or SPC docker for your composition? The sqlite is just for development purposes.

**Comment by addean** [comment]
@gannebamm i use geonode docker and my project currently in development

**Comment by gannebamm** [comment]
@addean Thank you.

@afabiani For your notice: The current docker compositions do not change the `DATABASE_URL` and therefore it will default to sqlite. For example the [production `db.env`](https://github.com/GeoNode/geonode/blob/master/scripts/docker/env/production/db.env) just states the password and DB names. But the docker-compose,yml [uses potgres ](https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L5). Therefore the env files should be modified?

I am not experienced with the vanilla docker setup. Maybe @francbartoli can look at this, too?

**Comment by francbartoli** [comment]
> just to update. when posting the issue, I forgot to mention that when I run `docker-compose exec django django-admin.py updatelayers -w geonode` for the first time, it will tell me there is no tables in my database. but all the tables already migrate.
> 
> produce error no tables
> ![image](https://user-images.githubusercontent.com/22883450/75401490-45f85080-593d-11ea-9db6-b1cd16c039bf.png)
> 
> But the tables were already exist
> ![image](https://user-images.githubusercontent.com/22883450/75401527-5f999800-593d-11ea-8eca-ae3aaf254582.png)

@addean in that command you are missing the `--settings` option which is mandatory when running from the host through the docker daemon. See similar commands in `tasks.py` https://github.com/GeoNode/geonode/blob/2.10.x/tasks.py#L102-L109.

**Comment by addean** [comment]
@francbartoli thanks for suggestion, I already run it with `python manage.py importlayers /nas/LANDSAT\ 8/LC81180562015231LGN00 --settings=catars.settings` but still using sqlite instate of postgres.

**Comment by francbartoli** [comment]
Try to see what are your settings for `DATABASES`:

python manage.py shell --settings=catars.settings

**Comment by addean** [comment]
@francbartoli attached my `DATABASES:`

![image](https://user-images.githubusercontent.com/22883450/75856417-46a65080-5e2f-11ea-8fa2-7a6c7c3ad62f.png)

**Comment by francbartoli** [comment]
@addean it is clearly using `sqlite` indeed so such behavior is expected. You have to go carefully through your custom `catars.settings` and find out where you have overridden the `geonode.settings`.

I'm going to close this as it is not relevant for a GeoNode issue. If you need help with your code please use the users' mailing list.
