### ISSUE TITLE
Duplicate glyphicons in Metadata-Assistant category dropdown

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5662]
## Expected Behavior
The glyphicons for `geoscientificInformation`, `imageryBaseMapsEarthCover` and `planningCadastre` should show once and with the symbols like on index.html

![grafik](https://user-images.githubusercontent.com/6172324/74234548-536ed300-4ccd-11ea-95b4-6ef11cfb9fd4.png)

## Actual Behavior
The categories are duplicated and one is marked as *X*
![grafik](https://user-images.githubusercontent.com/6172324/74234481-2fab8d00-4ccd-11ea-86c6-4fd099cad6c7.png)

## Steps to Reproduce the Problem

  1. log into master.demo.geonode.org
  2. visit https://master.demo.geonode.org/layers/geonode:someHydroData/metadata
  3. try to change the category

## Specifications

  - GeoNode version: 2.10.2 on master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
There were duplicated records on master demo DB, don't know exactly why.
After cleaning up the dups, the list seems to be good again.

**Comment by gannebamm** [comment]
I will test this with a fresh local install I am currently installing
