### ISSUE TITLE
A layers group in metadata does not affect its permissions

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5665]
## Expected Behavior
**This is not a bug. It is a strange and unintiutive user experience.**

If I add the layer `someHydroData` to the group `someGroup` it should affect the layers permissions somehow, shouldn´t it? 

## Actual Behavior
If I use the metadata editor `https://master.demo.geonode.org/layers/geonode:someHydroData/metadata` to pick a group, it will be used to link the layer/map to the groups activity stream and such, but won´t affect the permissions.
E.g. you could add it to group  `someGroup` but members of  `someGroup` will not be able to see it.

## Steps to Reproduce the Problem

  1. change permissions on a layer to prevent anybody to see it
  2. change group in metadata editor to a group
  3. check visibility of a groupmember for the above layer

## Specifications

  - GeoNode version: 2.10.2.dev1581417404
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): master.demo.geonode.org

**Comment by gannebamm** [comment]
To be honest I do not know how to change this behavior to be *user experience friendly*. The group in metadata model is a oneToOne, while the permissions groups are oneToMany. We could say that If it belongs to a group it should be at least visible to the group members?
What do the others think?

**Comment by afabiani** [comment]
This is like this whenever you enable the "Group Private" option on settings.

**Comment by gannebamm** [comment]
@afabiani So without `Group Private` option in settings (https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1809) the metadata´s group would also set privileges to view the layer / map?

I understand the comment different:
```
# If this option is enabled, Resources belonging to a Group won't be
# visible by others
```

Means if we set it to true **and** add a group in the metadata editor, this resource will not be public anymore. But will it be visible to the groups members than?

**Comment by afabiani** [comment]
Nope, only with `Group Private` settings enabled the members of a group will be able to access the resources even if not approved or not published.
The privileges can be actually set only from the `layer detail page > set permissions` panel in any case.

**Comment by gannebamm** [comment]
Ok, I still think the workflow is confusing and setting a dataset belonging to a group in the metadata wizard *feels like* setting permissions to the dataset. But for now I will close this issue. Maybe we can discuss this in a small group at the upcoming [geonode summit](https://summit.geonode.org)
