### ISSUE TITLE
visual glitch on download formats modal

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5667]
## Expected Behavior
The download formats are displayed nicely like:
![grafik](https://user-images.githubusercontent.com/6172324/74247837-00097e80-4ce7-11ea-9dc8-68c260dca3a7.png)

## Actual Behavior
There is a strange bullet point in front of the download formats:
![grafik](https://user-images.githubusercontent.com/6172324/74247790-ed8f4500-4ce6-11ea-8ec5-da67ab25fc76.png)

## Steps to Reproduce the Problem

  1. Have a layer you can download uploaded to geonode
  2. open the download layer button

## Specifications

  - GeoNode version: 2.10.2.dev1581417404
  - Additional details:

seems to be caused by this ` <li class="active">`:
https://github.com/GeoNode/geonode/blob/7423649e56b6a14d05c7f9d4857d03aab6106d56/geonode/layers/templates/layers/layer_detail.html#L298

In the expected behaviour screenshot I got rid of it by Firefoxs WebDevTools.

**Comment by t-book** [comment]
@gannebamm can you provide a PR ?

```
#download_tab1 li.active {
    list-style-type: none;
}
```

should do it. Just don't forget to change it in less ;)

**Comment by gannebamm** [comment]
@t-book yeah will do today

**Comment by gannebamm** [comment]
@t-book see https://github.com/GeoNode/geonode/pull/5938
