### ISSUE TITLE
Decimal items in Bounding Box List Throws an Error

### ISSUE THREAD

**Issue by anernest** [GeoNode/geonode#5671]
## Expected Behavior
Adding a layer to a map should result in a clean save

## Actual Behavior
Geonode throws an "exceed limit?" error, but does seem to save the map with the new layer.

## Steps to Reproduce the Problem

  1. Create a shapefile from a CSV file of coordinates imported into QGIS 3.4
  2. Upload shape file to geonode
  3. Insert shapefile into existing map

## Specifications

  - GeoNode version: spcgeonode:django-3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details:

Error is thrown at line 1156 of geonode/layers/utils.py `if bbox[0] > _bbox[0]`. I believe because the inserted layer's bounding box ordinates are specified as decimal rather than string. I'm able to temporarily get around the error by inserting `_bbox = [str(i) for i in _bbox]` to convert to string. 

Not sure if the bounding box calculations should be comparing strings, nor am i sure if the new shapefile is improperly constructed somehow...

**Comment by gannebamm** [comment]
@GeoTob Will take a look at this @afabiani
