### ISSUE TITLE
Unable to add manager privileges to current group member

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5680]
## Expected Behavior
I can **add** manager privileges to a current member of a group by the group UI if I am a manager of the group.

## Actual Behavior
I am unable to add manager privileges but have to remove the user from the group to add him back, or ask an admin to set him to group manager via the django-admin interface.

## Steps to Reproduce the Problem

  1. Add member to group without manager privileges
  2. Try to give him manager privileges like:

![grafik](https://user-images.githubusercontent.com/6172324/74341776-9356b880-4da8-11ea-9d94-1ceb3ec53c57.png)

## Specifications

  - GeoNode version: 2.10.2.dev1581497314

**Comment by travislbrundage** [comment]
I have done a similar fix before already, I can grab this one.
