### ISSUE TITLE
Thumbnails broken for RemoteServices using a invalid WMS GetCapabilities request

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5682]
## Expected Behavior
If a thumbnail cannot be generated or is broken, display a "Missing Thumbnail" instead.

## Actual Behavior
A broken image got displayed as a thumbnail.

## Steps to Reproduce the Problem

  1. Create a new Remote Service of type "Web Map Service" to https://sgx.geodatenzentrum.de/wms_vg250-ew
  2. Ingest one layer
  3. Go to the Layers list and check the broken images

## Specifications

  - GeoNode version: 2.10.x; 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

When adding layers from a Remote Service, sometimes the thumbnail results in a broken image

![image](https://user-images.githubusercontent.com/1278021/74418847-51ca1a00-4e49-11ea-9172-512e64cf6ab1.png)

This depends on how the thumbnail is generated. In this particular case the image source references directly a WMS GetCapabilities request

`https://sgx.geodatenzentrum.de/wms_vg250-ew?layers=vg250_vwg&srs=EPSG:4326&version=1.1.1&bbox=5.560000000000000,47.140000000000001,15.580000000000000,55.100000000000001&service=WMS&width=200&format=image/png&request=GetMap&height=150`

which, by the way, is not valid because it's missing the `STYLES` parameter.

#. First problem; the image should not be generated dynamically through a GetCapa request every time. It should be dumped locally on a PNG image file, instead.

#. Second problem; if the image is broken or empty somehow, it should be replaced by the default image "Thumbnail Missing".

**Comment by gannebamm** [comment]
> which, by the way, is not valid because it's missing the STYLES parameter.

🤣 You know, the WMS is from the Federal Agency for Cartography and Geodesy - they are not that familiar with OGC stuff 🙄
