### ISSUE TITLE
Performance issues with tiled layers in the MapStore client

### ISSUE THREAD

**Issue by audetrobergem** [GeoNode/geonode#5691]
## Expected Behavior
I want to display a map that contains several tiled layers without it taking too long to load.

## Actual Behavior
Displaying a map that contains several tiled layers takes a long time to load (more than 30 seconds) while the same map with the single tile option checked for each layer takes 2-3 seconds to load.

An example can be seen here:
  - Map with tiled layers: https://master.demo.geonode.org/maps/2309/view
  - Map with single tiles: https://master.demo.geonode.org/maps/2312/view

## Steps to Reproduce the Problem

  1. Create a new map with multiple layers (10 layers) and save it.
  2. Load the map. It wil probably takes more than 30 seconds to load.
  3. Edit the layers in the map to select the single tile option (layer settings / Display / Single Tile checkbox)
  4. Save this new map and load it. It will probably takes less than 5 seconds.
## Specifications

  - GeoNode version: 2.10.1
  - Installation method: GeoNode Project on a virtual environment
  - Platform: 18.04
  - Additional details:
    - The results are more or less the same with or without a base map.

**Comment by GeoTob** [comment]
Looking at how the page loads tiles I suspect this may be related to our issues with MS2's default OpenLayers configuration: https://github.com/geosolutions-it/MapStore2/issues/4750

**Comment by travislbrundage** [comment]
I'll start on this one today
