### ISSUE TITLE
dumpdata "natural" keyword deprecated.

### ISSUE THREAD

**Issue by anernest** [GeoNode/geonode#5692]
## Expected Behavior
Backup from admin web interface should execute

## Actual Behavior
An error is raised regarding dumpdata not having a keyword natural

## Steps to Reproduce the Problem

  1. Run a backup from the Admin Web UI

## Specifications

  - GeoNode version: spcgeonode:django-3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details:

Changing "natural=True" to "natural_foreign=True" seems to resolve this, but another error regarding pinax is raised....

**Comment by anernest** [comment]
CommandError at /en/admin/base/backup/
No installed app with label 'pinax'.

**Comment by anernest** [comment]
sorry, made these change in line 307 of geonode/base/management/commands/backup.py...still trying to figure out what the pinax error is about.

**Comment by anernest** [comment]
On a whim, I added 'pinax' to the INSTALLED_APPS in settings.py, and it seems to work.  Not familiar enough with pinax or geonode to understand what/why...

**Comment by gannebamm** [comment]
@afabiani This should be fixed with the BR PullRequests from GeoSolutions?
