### ISSUE TITLE
Not allowed layout when trying to print

### ISSUE THREAD

**Issue by NyakudyaA** [GeoNode/geonode#5711]
## Expected Behavior
Ability to print map

## Steps to Reproduce the Problem

  1. Log in to the site and see the public layers
  2. Click on print

You will be shown the following:
![cannot-print](https://user-images.githubusercontent.com/2510900/74709200-4733ca00-5227-11ea-9e58-ad2875c42a94.png)

The Django logs and nginx do not show anything at all

## Specifications

  - GeoNode version: 3.0
  - Installation method: docker spcgeonode
  - Platform: Ubuntu 18.04

**Comment by frafra** [comment]
Are you using HTTPS?

**Comment by NyakudyaA** [comment]
> Are you using HTTPS?

No, just http

**Comment by afabiani** [comment]
You need to update the `config.yml` file into the `GEOSERVER_DATA_DIR/printing` folder.

Use the following one as an example:

https://github.com/GeoNode/geoserver-geonode-ext/blob/master/geoserver/data/geonode_v215x/printing/config.yaml

**Comment by NyakudyaA** [comment]
> You need to update the `config.yml` file into the `GEOSERVER_DATA_DIR/printing` folder.
> 
> Use the following one as an example:
> 
> https://github.com/GeoNode/geoserver-geonode-ext/blob/master/geoserver/data/geonode_v215x/printing/config.yaml
> 
> No need to restart GeoServer, just refresh the page every time you change something into the YAML

@afabiani thanks but the yaml already exists and I can see the A4 in the config.yml but will try to customize it and revert back

**Comment by NyakudyaA** [comment]
> > You need to update the `config.yml` file into the `GEOSERVER_DATA_DIR/printing` folder.
> > Use the following one as an example:
> > https://github.com/GeoNode/geoserver-geonode-ext/blob/master/geoserver/data/geonode_v215x/printing/config.yaml
> > No need to restart GeoServer, just refresh the page every time you change something into the YAML
> 
> @afabiani thanks but the yaml already exists and I can see the A4 in the config.yml but will try to customize it and revert back

Tried to change the configs but still nothing works

**Comment by gannebamm** [comment]
@afabiani I will take a look at this issue too
