### ISSUE TITLE
Upload a Thumbnail broken when CACHE BUSTING is enabled

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5721]
## Expected Behavior
Upload a Thumbnail works as expected.

## Actual Behavior
Upload a Thumbnail refers to a non-existent image.
![image](https://user-images.githubusercontent.com/1278021/74747693-a0bbe900-5267-11ea-98af-e6da1e19a1f2.png)

## Steps to Reproduce the Problem

  1. Go to master demo instance
  2. Editing Tools > Thumbnail > Upload
  3. Try to upload an image

## Specifications

  - GeoNode version: 2.10.2 / 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details: cache-busting store renames the uploaded image URL by adding an md5 tag. The Upload Thumbnail code should be able to recognize it and update the url accordingly.

**Comment by t-book** [comment]
From what I see imagekit is used? in best case, this could be solved by its CACHE settings: https://django-imagekit.readthedocs.io/en/latest/configuration.html

**Comment by abulojoshua1** [comment]
After my investigation, looks to me like when `CACHE_BUSTING_STATIC_ENABLED` and `CACHE_BUSTING_MEDIA_ENABLED` are boolean `True`, the image is first created in `<MEDIA_ROOT>/curated_thumbs` but then it takes longer to be created in `<MEDIA_ROOT>/CACHE/images/curated_thumbs/` till a refresh is done on the thumbnail upload page, then the image become available. This is evident on the upload of a new thumbnail image, `geonode.base.models.CuratedThumbnail.thumbnail_url` throws a `[Errno 2] No such file or directory:` error that show that the image does not exist yet in the cache directory (<MEDIA_ROOT>/CACHE/images/curated_thumbs/). So far, I am trying to find out how the cache image is generated before I can proceed with an implementation.

**Comment by abulojoshua1** [comment]
Just a correction, the image is non-existent in the cache directory even when `CACHE_BUSTING_STATIC_ENABLED` and `CACHE_BUSTING_MEDIA_ENABLED` are False

**Comment by abulojoshua1** [comment]
@afabiani, @giohappy, to solve this issue, I plan to generate the cache image if it is non-existent in the `geonode.base.models.CuratedThumbnail.thumbnail_url` method as below:
```
def thumbnail_url():
     try:
          // existent code .....
         if not os.path.exists(_upload_path):
              if cache_image_does_not_exist:
                      Simple().generate(self.img_thumbnail, force=True) // to generate image syncronously
              os.rename(upload_path, _upload_path)
     except:
          // more existent code
```

**Comment by afabiani** [comment]
@abulojoshua1 seems good
