### ISSUE TITLE
Customizing SPC Geonode

### ISSUE THREAD

**Issue by Japhetho** [GeoNode/geonode#5755]
I have recently installed SPC Geonode, I'm trying to customize Geonode templates to my own organization's templates to achieve something like [http://www.masdap.mw/](Masdap). 
I have made a few changes to the index.html file located in geonode/geonode/templates but whenever I refresh the Geonode landing page, the changes are not reflected. 
Any advice on how I can edit the templates for a docker installation of SPC Geonode will be highly appreciated. Thanks.

**Comment by gannebamm** [comment]
It depends:
If you just want to change the colors and image and welcome message you could use django theming, which is part of geonode. Log into your admin interface and see themes: http://your.geonode.domain/en/admin/geonode_themes/geonodethemecustomization/ in there you can add an background image and change colors and some other things.

If above is not enough for you and you want to change more of the appearance **AND** If you are familiar with git and versioning **I would** fork the official GeoNode repository and change the templates. E.g. the 'start page' is rendered by:
https://github.com/GeoNode/geonode/blob/master/geonode/templates/index.html

In there you can use djangos template language to change the rendered HTML as you would like.

There is a middle ground solution between the two above called django-project, or for GeoNode geonode-project. I am not familiar with it and AFAIK it does not work with SPC docker - but has its own docker composition you could check out.

**Comment by Japhetho** [comment]
@gannebamm Thank you for your response. What I need is option number 2 because I need to change more of the appearance than is provided in geonodethemecustomization. I'll try it out and will get back to you. Thanks.

**Comment by kikislater** [comment]
Use geonode project inside SPC it's the easy way
