### ISSUE TITLE
Check User permissions for private group

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#5801]
**Describe the solution you'd like**
GroupDetailView should check if group is private and if user is member.

**Comment by t-book** [comment]
@afabiani one more minor issue found in permissions form:

![Bildschirmfoto 2020-03-04 um 21 52 15](https://user-images.githubusercontent.com/20478652/75922642-b3d3d900-5e63-11ea-85e5-db5cb81b1489.png)


would change `json_dict['groups']` in [Ajax_lookup](https://github.com/GeoNode/geonode/blob/master/geonode/views.py#L74-L100) to something like 

```
    json_dict['groups'] = [({'name': g.slug, 'title': g.title})
                           for g in groups
                           if g.user_is_member(request.user) 
                           or g.access == "public"]
```

**Comment by gannebamm** [comment]
Sidenote: Groups will be displayed on LayerDetailViews and the LayerListView, too. From there Links are displayed which would lead to a dead end, if the above is implemented.

**Comment by t-book** [comment]
@gannebamm not sure about it.
check: https://master.demo.geonode.org/layers/geonode_data:geonode:empty_layer

![Bildschirmfoto 2020-03-05 um 11 54 20](https://user-images.githubusercontent.com/20478652/75975111-36967b80-5ed8-11ea-8711-8084377b7b7c.png)
![Bildschirmfoto 2020-03-05 um 11 54 27](https://user-images.githubusercontent.com/20478652/75975116-37c7a880-5ed8-11ea-804b-a73e09bb0b67.png)

The private group is not showing up ad layer detail.

**Comment by gannebamm** [comment]
Same here @sjohn-atenekom :
Could you test this behaviour? I think those security-related issues are relevant for AteneKOM? This help would be very much appreciated :D

**Comment by sjohn-atenekom** [comment]
I could reproduce the problem. a user can assign the permissions for a private group in which he is not a member. 
But what do you mean by this, @gannebamm?

>Sidenote: Groups will be displayed on LayerDetailViews and the LayerListView, too. From there Links are displayed which would lead to a dead end, if the above is implemented.

**Comment by afabiani** [comment]
This behavior is enabled only when you set the `GROUP_PRIVATE_RESOURCES` to True

This is part of a set of 4 settings which allow you to enable (partially or fully) and advanced data validation workflow

**Comment by gannebamm** [comment]
> But what do you mean by this, @gannebamm?
> 
> > Sidenote: Groups will be displayed on LayerDetailViews and the LayerListView, too. From there Links are displayed which would lead to a dead end, if the above is implemented.

I can not reproduce this old behaviour I seem to have spotted.

> I could reproduce the problem. a user can assign the permissions for a private group in which he is not a member.

I can reproduce this issue of seeing a private group in the permissions, too. I think this is an issue since the documentation states (https://docs.geonode.org/en/master/admin/admin_panel/index.html#types-of-groups):
_Private: only invited users can join the group, registered users **cannot see any details about the group**, including membership._

@afabiani I think `GROUP_PRIVATE_RESOURCES` will make all resources inside a group non-visible by non-group users. This is a good switch but not related to this issue I think.

So you should not be able to see private groups if you are not a member of them. I would vote for @t-book idea to check in the template, or on the sql query side for group visibility permissions.

**Comment by gannebamm** [comment]
Same for linking dokuments:
![Image_2020_11_04___001](https://user-images.githubusercontent.com/6172324/98113172-90a27300-1ea3-11eb-992a-a247f34a2b12.png)
I can see private groups in the autocomplete, even though I am not a member of them. This is with enabled `GROUP_PRIVATE_RESOURCES`.

**Comment by t-book** [comment]
@gannebamm Tested. Private groups do show up for non group members. My understanding is a private group should be private. In other words non member should not even know the groups exists. If you and @afabiani agree I would follow up with my patch here and create a PR: https://github.com/GeoNode/geonode/issues/5801#issuecomment-594840621

**Comment by gannebamm** [comment]
Yes, that is my understanding of private groups, too. They shouldn't be visible by anyone except members.

**Comment by afabiani** [comment]
Yes, this is correct. They should show-up only if the user is currently a member or manager of the group.
