### ISSUE TITLE
Hide Version from Footer

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#5806]
**Is your feature request related to a problem? Please describe.**
The first thing bad guys do to do harm in web is to gather as much information about a system as to find. 

**Describe the solution you'd like**
I'd like to raise the level when version is shown at footer to at least _staff_ group.

**Describe alternatives you've considered**
Live a less secure admins life.

**Additional context**
![Bildschirmfoto 2020-03-04 um 20 43 17](https://user-images.githubusercontent.com/20478652/75916553-d57b9300-5e58-11ea-81e3-28dd840908b8.png)

**Comment by gannebamm** [comment]
You´re right about the version stuff. For an admin it is worthy information but for users it should be enough to know the application is powered by GeoNode.

> Describe alternatives you've considered
Live a less secure admins life.

Today is your day of considering alternatives, hmm?

**Comment by t-book** [comment]
> Today is your day of considering alternatives, hmm?

![qc2fzcdyqxd11](https://user-images.githubusercontent.com/20478652/75992592-7c633c00-5ef8-11ea-8457-91ae1eb6aab8.jpg)

;))
