### ISSUE TITLE
Add new settings variable to stop gravatars fallback image

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#5807]
**Is your feature request related to a problem? Please describe.**
The current implementation with Gravatar is problematic with GDPR. This as In case a user has not uploaded an avatar image a default fallback image will be loaded from gravatar.com. Automattic's server (the company behind Gravatar) will log every access to our fallback image.

**Describe the solution you'd like**
My proposal is to add the following new variables to settings.py

```
AVATAR_GRAVATAR_BACKUP = os.getenv('AVATAR_GRAVATAR_BACKUP', 'True')
AVATAR_DEFAULT_URL = os.getenv('AVATAR_DEFAULT_URL', '/geonode/img/avatar.png')
```

When `AVATAR_GRAVATAR_BACKUP` is `True` the current fallback image will be loaded from gravatar.com (current behavior)

When setting `AVATAR_GRAVATAR_BACKUP` to `False` local [Mr. Geonode](https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/img/avatar.png) or whatever you decide to use as fallback will be shown. 

In every case, if a User has uploaded an image the users' uploaded image will be shown.

**Describe alternatives you've considered**
Do nothing

**Comment by gannebamm** [comment]
good old Mr. Geonode 😆 
👍 

> Describe alternatives you've considered
Do nothing

which is always an alternative worth considering

**Comment by t-book** [comment]
I will close here in favor of local_settings.py
