### ISSUE TITLE
An investigation for the cleanup of backup and restore options

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#5827]
We're reviewing the backup and restore utils. During the analysis we found the following:

- backup.py / restore.py management commands, which assumes the presence of Geoserver. These do not apply the (optionally) set manglers
- migrate_layers.py management command, which only restores geonode fixtures, eventually applying manglers
- scripts inside scripts/backup-restore/ folder which overlap with (are a rewrite of?) backup/restore/migrate_layers and helpers from the management command module.

I think these overlaps, and differences, both in terms of code and functionality is quite confusing and difficult to maintain.

I would like to know from the community who is using which part of these functionalities, and hopefully agree on a cleanup of them to converge on a unique approach.

**Comment by gannebamm** [comment]
Since the current options were not working in a hassle free and straight forward way, we do backup the geoserver dir and the postgres DB instances individually and without b/r functions. In spc docker there is a r-clone container and two pgdumpers which help doing the backup.

**Comment by t-book** [comment]
Hi @giohappy I do backups similar to @gannebamm . A separate docker container dumps data with pg_dump and back up static files with rsync. Depending on a clients' need tar.gz files are stored in a mounted drive synced to s3 or sFTP. In a non-docker env I'm doing the same with a regular cronjob.

As this is tested and as I do trust/work for years with pg_dump, pg_restore and rsync I _personally_ do not see much need in a build-in backup-solution. 

However the option to GeoNode [selectively Export/Import Layers ](https://docs.geonode.org/en/master/intermediate/backup/index.html#geonode-selectively-export-import-layers) might be very useful.

**Comment by gannebamm** [comment]
@t-book selective layer restore would be awesome! Best in conjunction with an api.
