### ISSUE TITLE
HTML contents translation when loaded within js (cart.html)

### ISSUE THREAD

**Issue by mehmadi** [GeoNode/geonode#5841]
I am trying to add translation to `cart.html` file contents in Geonode 3.0. I could not find any solution for that. Any ideas?

**Note:** I even tried to put translated text in the file. No change was observed. I could not figure out from where these contents are loaded.

**Comment by t-book** [comment]
@mehmadi  you mean https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/templates/cart.html
?

Be aware that this is angular teritory and it might be needed to integrate some translation on side of angular....

**Comment by mehmadi** [comment]
I get it! Thanks for the reply.
