### ISSUE TITLE
Metadata wizard helptexts are all None

### ISSUE THREAD

**Issue by olljal** [GeoNode/geonode#5852]
## Expected Behavior
Hoverin mouse over ?-icon should give related help text.

## Actual Behavior
Help text is replaced with text: None.
![metadata-hover](https://user-images.githubusercontent.com/45965861/76404252-d6e41880-638e-11ea-8188-8f410ba3d175.jpg)

## Steps to Reproduce the Problem

  1. Upload layer or open existing
  2. Open Metadata wizard
  3. Move mousepointer over ?-icon

## Specifications

  - GeoNode version: 3.0.dev1583911194 (master branch, today)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu
  - Additional details: Tested with: docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build

**Comment by afabiani** [comment]
Fixed
