### ISSUE TITLE
Drop Leaflet ?

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#5864]
**Is your feature request related to a problem? Please describe.**
Since MapStore does use OL as default and there is no leaflet client currently working, we could get rid of leaflet code.

**Describe the solution you'd like**
We could stat stagewise and getting rid of files not needed anymore. E.g. the statics:

- [ ] L.Control.Locate.css 
- [ ] L.Control.Opacity.css
- [ ] L.Control.Pan.css
- [ ] Leaflet.NavBar.css
- [ ] leaflet.fullscreen.css
- [ ] leaflet.css
- [ ] leaflet-plugins.min.css
- [ ] leaflet-measure.css

And the JS code, too.

**Describe alternatives you've considered**
I did not consider any alternatives.

**Additional context**
My grunt does not like one of the Leaflet files:
`Invalid property name 'r' at lib/css/L.Control.Locate.css:20:4. Ignoring.,Invalid property name 'r' at lib/css/L.Control.Locate.css:24:4. Ignoring.,Invalid property name 'r' at lib/css/L.Control.Locate.css:28:4. Ignoring.`

**Comment by afabiani** [comment]
In general I agree with you, the problem is that the QGIs integration still use leaflet client and files.

We should decide if we want to keep this stuff also or not. If we want to remove Leaflet we should also remove QGis integration or, hopefully, upgrade it to use MapStore or other newer client.

Problem is that no one seems ot be using it right now nor maintaining it.

**Comment by t-book** [comment]
+1 for removing leaflet artifacts
+1 for removing qgis
+1 for trying to keep geonode "fatfree" wherever possible

Regarding Qgis: This might sound a bit harsh, but we had this discussion now several times and no one steps out to take care of it. Carrying unmaintained stuff along with v3 stable just feels wrong to me.

Unfortunately, the whole story is bigger as geonode client is outdated (stale boundles SDK) and unmaintained as well. 

Currently, the only working viewer is mapstore. Which is great, but has a very steep learning curve for inexperienced developers. This might be the wrong issue for a discussion about the future of our viewers but I could imaging mapstore2 as the main viewer (current state). And geonode-client as a small rewritten leaflet-react based companion next to mapstore. No Redux (just context), no rxjs, just vanilla react with leaflet. Trying to keep it as dead simple as possible. 

Just my two cents.

**Comment by yogeshkheri** [comment]
I also getting no map while i change the following value:-

GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY = os.getenv('GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY', 'leaflet')
<img width="952" alt="erro2" src="https://user-images.githubusercontent.com/16238300/81332708-1a25e380-90c1-11ea-83fb-e0ea12585f84.png">

I always work around to load the local server data into geonode map area but not able to load the map using mapstore also.The latest version of geonode also provide the some  MAPSTORE CATALOGUE like
<img width="521" alt="example" src="https://user-images.githubusercontent.com/16238300/81333115-b819ae00-90c1-11ea-9301-3ecaad018771.png">
After enabling this option and replace values with local server i also not able to get the map.Mapstore has good GUI campare to Leaflet.
Please Provide me solution for load the local server map.
Thanks

**Comment by t-book** [comment]
@yogeshkheri the leaflet viewer is not working currently. This issue is to discuss if it should be removed or not please use the user list regarding configuration questions.

**Comment by GeoTob** [comment]
> +1 for removing leaflet artifacts
> +1 for removing qgis
> +1 for trying to keep geonode "fatfree" wherever possible

+1 to all of this
