### ISSUE TITLE
Inner rings of polygons are deleted when the polygon is edited

### ISSUE THREAD

**Issue by tallistroan** [GeoNode/geonode#5879]
## Expected Behavior
When some vertices of a polygon are changed or an additional polygon is added to a feature, the rest of the existing polygon remains the same.

## Actual Behavior
When a polygon with an inner ring is edited in GeoNode, the inner ring is removed, when the polygon is saved, regardless of which part of the polygon was edited and even if only a second geometry was added to the feature and the original polygon was not changed at all.

## Steps to Reproduce the Problem

1. Add a layer with a polygon which contains at least one inner ring.
2. Go to the edit mode and change the polygon
3. Save the changes

## Possible workarounds
No workaround known

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): happens on http://master.demo.geonode.org
  - Platform:
  - Additional details:

**Comment by t-book** [comment]
thanks @tallistroan _labeled as major because of data loss._

**Comment by t-book** [comment]
@giohappy   I wonder if this behavior is based on Mapstores payload or geoserver-restconfig (or the django part which passes the requst). Do you know of a similar issue with mapstore?

**Comment by giohappy** [comment]
Thanks for the heads up Toni. 
I didn't notice this issue but it's actually worth an investigation. I will check as soon as possible.

**Comment by giohappy** [comment]
Closing in favour of new issue created in masptre client repo: https://github.com/GeoNode/geonode-mapstore-client/issues/52

**Comment by t-book** [comment]
thanks @giohappy !
