### ISSUE TITLE
Change gravatar settings

### ISSUE THREAD

**Issue by petrus7** [GeoNode/geonode#5906]
## Expected Behavior
Gravatar should use default Provider as the last source of images 

## Actual Behavior
Current gravatar configuration is using default avatar provider which is hitting gravatar servers to download image. This wont work in DMZ zones 

Bug was not confirmed in real DMZ configuration iv spotted it during digging in geonode master code

**Comment by t-book** [comment]
@petrus7 For reference: See my suggestion here: https://github.com/GeoNode/geonode/issues/5807

This is how I do in production for stopping gravatar requests.

**Comment by petrus7** [comment]
@t-book how is it supposed to work?

I just tried it on my local configuration (master branch) and the default gravatar is loaded.
Moreover, i cannot see any reference to AVATAR_GRAVATAR_BACKUP in the code, besides that variable is not mentioned in the package doc here: https://django-avatar.readthedocs.io/en/latest/index.html

**Comment by giohappy** [comment]
@petrus7 the initial proposal from @t-book was to add those variables, then he reverted to customize the avatar settings locally, without creating new custom options.

Actually for our client we can customize the local_settings to load a local default gravatar.

**Comment by t-book** [comment]
@petrus7 I do think we use a fork:
https://github.com/GeoNode/geonode/blob/master/requirements.txt#L78

AVATAR_GRAVATAR_BACKUP
https://github.com/GeoNode/geonode-avatar/blob/88f7b728f6b981b736537693b6d07d70ae94ec1a/setup.py#L149-L152

AVATAR_DEFAULT_URL
https://github.com/GeoNode/geonode-avatar/blob/88f7b728f6b981b736537693b6d07d70ae94ec1a/setup.py#L154-L156

Please try following in your settings:

```
AVATAR_GRAVATAR_BACKUP = True
AVATAR_DEFAULT_URL =  '/geonode/img/avatar.png'
```
as I guess something is not correct with the env variables. After reloading the instance you should see avatar.png as default image instead of the one coming from gravatar. In case a user uploads an image the uploaded will be used.

**Comment by t-book** [comment]
@giohappy is right, django_avatar supports this by default however it looks not documented. My initial idea was to add those variables per default to our settings. However, as it's already quite bloated further I do not hear many voices having problems hitting the gravar server I've closed the issue ;)

**Comment by petrus7** [comment]
@t-book setting this:

```
AVATAR_GRAVATAR_BACKUP = False
AVATAR_DEFAULT_URL =  '/geonode/img/avatar.png'

```
or 

```
AVATAR_GRAVATAR_BACKUP = True
AVATAR_DEFAULT_URL =  '/geonode/img/avatar.png'
```
Is not working for me, my solution is to change providers order:
```
AVATAR_PROVIDERS = (
    'avatar.providers.PrimaryAvatarProvider',
    'avatar.providers.DefaultAvatarProvider',
    'avatar.providers.GravatarAvatarProvider'
)
```

**Comment by t-book** [comment]
@petrus7 just checked the code again. could be that it has been removed in master. As I'm with 2.10 in production this works: https://github.com/GeoNode/geonode-avatar/blob/411190d4b0e8f3ee3ce764003a6ffdcd350a3af0/avatar/templatetags/avatar_tags.py#L20-L37

**Comment by t-book** [comment]
@petrus7 
> Is not working for me, my solution is to change providers order:

Nice! thanks for the hint ;)

**Comment by petrus7** [comment]
Closing this after offline discussion with @giohappy. It's not an issue for a significant majority of running environments
