### ISSUE TITLE
TypeError at /upload/final Object of type bytes is not JSON serializable

### ISSUE THREAD

**Issue by Ahmedgis** [GeoNode/geonode#5919]
## Expected Behavior
Uploading a shapefile

## Actual Behavior
The shapefile uploaded successfully to geoserver but in the final step of upload it return an Error 500 when executing the request `/upload/final?id=10` with web response `Unexpected error!`
and when enabled Debug=True the response error is:

`
Request Method: | GET
-- | --
https://www.mydomain.com/upload/final?id=10
2.2.10
TypeError
Object of type bytes is not JSON serializable
/usr/lib/python3.7/json/encoder.py in default, line 179
/usr/bin/uwsgi-core
3.7.5
['/opt/geonode',  '.',  '',  '/home/geonode/.virtualenvs/geonode/lib/python37.zip',  '/home/geonode/.virtualenvs/geonode/lib/python3.7',  '/home/geonode/.virtualenvs/geonode/lib/python3.7/lib-dynload',  '/usr/lib/python3.7',  '/home/geonode/.virtualenvs/geonode/lib/python3.7/site-packages',  '/opt/geonode',  '/home/geonode/.virtualenvs/geonode/src/django-activity-stream']
Tue, 24 Mar 2020 23:41:54 +0000
`
![image](https://user-images.githubusercontent.com/9510684/77488577-49003700-6e3e-11ea-8b80-d5f88dc42267.png)

![image](https://user-images.githubusercontent.com/9510684/77488633-6e8d4080-6e3e-11ea-86f4-b09c72232e39.png)

## Steps to Reproduce the Problem

  1. Login to geonode with admin.
  2. Select Data from navbar then select Upload Layer.
  3. Select the shapefile (.shp, .shx, .dbf, ...) to upload.
  4. Check - Preserve Metadata XML.
  5. Select the charset (Windows CP1256).
  6. Click Upload files.

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (Manual):
  - Platform: Ubuntu 19.10
  - Additional details: Thanks in advance

**Comment by giohappy** [comment]
@Ahmedgis GN 2.10.x is not compatible with Python3.
Python3 is supported on master branch (which will be GeoNode 3)

**Comment by Ahmedgis** [comment]
@giohappy The reason for selecting (**Plugin = python3**) in **/etc/uwsgi/apps-available/geonode.ini** file because when it was  (**Plugin = python**) geonode landing page return an (**Error 502 Bad Request**) and after looking for many solutions, i found that changing to use  (**Plugin = python3**) is working good except for uploading a layer.

**Note:** I installed geonode from the documentation:
[(http://docs.geonode.org/en/master/install/core/index.html)]

**Comment by giohappy** [comment]
the master documentation refers to GeoNode master. For GeoNode 2.10.x you shoud follow this one: https://docs.geonode.org/en/2.10/start/index.html

By the way you can't swap Python 3 for Python 2 if the underlying software (GeoNode 2.10 in this case) doesn't support it.

You should close this issue and in case ask for support through the mailing lists if you have problems with the official setup.
