### ISSUE TITLE
Search autocomplete does not trigger the filter automatically anymore

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#5924]
## Expected Behavior
Making a search from the "Search Textbox" should allow me to trigger the filter automatically whenever I select an entry.

![image](https://user-images.githubusercontent.com/1278021/77654658-9fba5d80-6f71-11ea-976f-89e60cde3af4.png)

## Actual Behavior
Actually, the search is triggered only when issuing "enter" from the keyboard.

## Steps to Reproduce the Problem

  1. Start searching for a resource
  2. Click on the entry after autocomplete finds some results
  3. Notice that the filter starts only after hitting "enter" button

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

**Comment by gannebamm** [comment]
@GeoTob wanted to take a look at this too @afabiani

**Comment by GeoTob** [comment]
@afabiani I'm more than happy for us to contribute here if you need help - just let me know :-)

**Comment by giohappy** [comment]
We verified that this doesn't depend on our recent commits but on the same old #5410 PR where autocomplete frontend was rewritten. In my opinion that PR wasn't a good move but reverting it would be a time consuming task,

@GeoTob if you can work on this fix please go ahead, thanks!

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/pull/5991/commits/6ba6472690fdc9bc7e1259fef4ed7a4878d7c587

**Comment by t-book** [comment]
thanks @afabiani 👍
