### ISSUE TITLE
Layer upload error

### ISSUE THREAD

**Issue by ksonda** [GeoNode/geonode#5925]
## Expected Behavior
Upload a layer

## Actual Behavior
Unexpected exception value too long for type character varying(30)

## Steps to Reproduce the Problem

  1. Data->Upload layer
  2. Choose file (https://storage.googleapis.com/example-data-pwsb/Brazil_Compiled.zip is an example that produces the problem, unzip first to reveal shapefiles)
  3. Wait for file to upload
 4. Select CRS (WGS 84). 
 5. Receive error: Unexpected exception value too long for type character varying(30)

## Specifications

  - GeoNode version: 3.0
  - Installation method: SPCgeonode docker
  - Platform: Ubuntu 18.04 LTS
  - Additional details: 4 CPU, 16GB RAM, 50GB disk

**Comment by gannebamm** [comment]
I was able to upload the above dataset to a fresh GeoNode SPC composition. I used master on commit 8ce66dc2839f699d7f589e0e87cba136444c3c8d and ubuntu 18.04. Thank you @ksonda for providing an example dataset with the issue for reproduction purposes!

I will close this issue. If you encounter more errors please reopen it and give further examples. I would encourage you to rebuilt the docker-composition `docker-compose up --build`. Maybe you have a dirty image state somewhere.
