### ISSUE TITLE
Please update the osgeo project logo on geonode.org

### ISSUE THREAD

**Issue by jodygarnett** [GeoNode/geonode#5985]
**Is your feature request related to a problem? Please describe.**

The http://geonode.org/ website uses the old osgeo logo, it has beens some years now so this looks like the project is neglected.

**Describe the solution you'd like**

Please grab a new logo from here https://github.com/OSGeo/osgeo/tree/master/incubation/project

You can use the SVG icon directly, or use it to create an appropriately sized PNG.

**Comment by t-book** [comment]
thanks @jodygarnett 
closed with https://github.com/GeoNode/geonode.github.com/commit/d954b083261c796483b477e2729282086b6876f3
