### ISSUE TITLE
Limit notification amount on resource comment

### ISSUE THREAD

**Issue by petrus7** [GeoNode/geonode#6001]
**Is your feature request related to a problem? Please describe.**
To many notifications are sent connected with new comment on resource

**Describe the solution you'd like**
Notification should be sent only to the resource owner and administrator(including the current notification setup).

**Comment by t-book** [comment]
@petrus7  if new issues are important for geosolutions please ignore this message. Otherwise, I would vote to keep the 3.0 milestone feature frozen as discussed lately.

**Comment by giohappy** [comment]
@t-book this should be the last import new feature for us before the feature freeze.

**Comment by t-book** [comment]
@giohappy thanks Giovanni. No problem. Thanks for your work!
