### ISSUE TITLE
Issue uploading shp files and others

### ISSUE THREAD

**Issue by johnfelipe** [GeoNode/geonode#6022]
![Screenshot_20200422-021829](https://user-images.githubusercontent.com/428820/79952213-b2746500-843f-11ea-8ce2-e0b4b2c67086.jpg)
I only upload demo files and show that error

**Comment by gannebamm** [comment]
Hello @johnfelipe Please use the complete issue template and describe which setup you performed, which version you use and if possible provide example data for us to reproduce your error.

**Comment by JuanTascon2020** [comment]
![Captura de pantalla (630)](https://user-images.githubusercontent.com/64289156/80262639-b4167680-8653-11ea-8218-cd8e11b14a9c.png)

This error shows up after i try to upload the following files to a fresh instance: https://geomedellin-m-medellin.opendata.arcgis.com/datasets/malla-vial

Appreciate your help.

**Comment by t-book** [comment]
@JuanTascon2020 Please see @gannebamm comment. We cannot help if we do not know which setup path you've used and which version.
