### ISSUE TITLE
Unable to change the default port of geonode and Geoserver other than port 80

### ISSUE THREAD

**Issue by deviirmr** [GeoNode/geonode#6023]
# Expected Behavior
By default,  Geonode and Geosever are accessible on port 80.
And it should work after overriding the port 80 to another port such as 81, 82...

## Actual Behavior
It seems Geonode is tightly bound with port 80. 
The main portal is working fine after changing the port `http://10.0.0.117:90/` but when I am trying to login GeoServer it always jumps back to port 80 `http://10.0.0.117/geoserver/web`

## Steps to Reproduce the Problem
  1. I have updated the port and environmental variable at **docker-compose.override.localhost.yml** and **docker-compose.yml**

> Entries from docker-compose.override.localhost.yml

```
version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=True
      - GEONODE_LB_HOST_IP=10.0.0.117
      - GEONODE_LB_PORT=90
      - SITEURL=http://10.0.0.117:90/
      - ALLOWED_HOSTS=['localhost','*','10.0.0.117','10.0.0.120' ]
      - GEOSERVER_PUBLIC_LOCATION=http://10.0.0.117:90/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://10.0.0.117:90/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=10.0.0.117
      - GEONODE_LB_PORT=90
      - PUBLIC_PORT=90
```

> Entries from docker-compose.yml

```
  geonode:
-
-
-
    depends_on:
      - django
      - geoserver
    ports:
      - "90:80"
    volumes:
      - statics:/mnt/volumes/statics
-
-
-
```
  2. Updated the entried of oauth2_provider at
http://10.0.0.117:90/en/admin/oauth2_provider/application/1001/change/
![image](https://user-images.githubusercontent.com/10088434/80214694-93dabd80-863b-11ea-9bda-1b61e6eb54df.png)
  3. Updated the Geoserver entries for geonode-oauth2 
http://10.0.0.117:90/geoserver/web/wicket/page?6
![image](https://user-images.githubusercontent.com/10088434/80215105-3430e200-863c-11ea-8014-451066fb6319.png)

  4.  Finally
docker-compose -f docker-compose.yml -f docker-compose.override.example-org.yml up --build -d

## Specifications

  - GeoNode version: 3.0.0.dev1587232496
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 16.04.6 LTS
  - Additional details: The port 80 is reserve for Nginx which is installed at VM. So in that case I need to use diffret port for Geonode.

**Comment by deviirmr** [comment]
Finally, I am close to what I was trying from the last couple of week.
Also, I understand GEONODE_LB_PORT has only two option port 80 and port 443. 

I expose geonode container to port 90 which is further handled by Nginx(External ) reverse proxy at the host machine, Everything is working fine except the GeoServer login is always fallback to localhost (local IP) rather than proxy IP. 

I need help from you guys, I think something I need to fix with internal Nginx so that it follows the proxy IP

Here is further detail 

```
Now, Entries from docker-compose.override.localhost.yml
version: '2.2'
services:

  django:

    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=10.0.0.117
      - GEONODE_LB_PORT=80
      - SITEURL=http://10.0.0.117/
      - ALLOWED_HOSTS=['localhost' ,'10.0.0.117' ]
      - GEOSERVER_PUBLIC_LOCATION=http://10.0.0.117/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://10.0.0.117/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=10.0.0.117
      - GEONODE_LB_PORT=80

```


```
The Entries from docker-compose.yml was the same
  geonode:
-
-
-
    depends_on:
      - django
      - geoserver
    ports:
      - "90:80"
    volumes:
      - statics:/mnt/volumes/statics
-
-
-
```


```
External nginx conf detail

server {
        listen 10.0.0.120:80;
        listen [::]:80;

        server_name test.com;

        location / {
     client_max_body_size 1000M;        
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;       
     proxy_pass http://10.0.0.117:90; 

        }
}
 
```

@afabiani and @t-book I need some direction from your core team.

**Comment by t-book** [comment]
@deviirmr I'm not sure I can fully follow. You run geonode with docker and need to make it available over port 90 instead of 80 but when you trying to login you get redirected to port 80, is that correct?

**Comment by t-book** [comment]
Without trying two shots in the dark:

---

Go to Django Admin -> websites and add your port to your host: your-domian.com:90

---

another (experimental) idea:

Try to change your  nginx to forward to your port:
`proxy_set_header X-Forwarded-Host $host:90;`

and add the following to your django  settings:
`USE_X_FORWARDED_HOST = True`

---
`

**Comment by deviirmr** [comment]
Hi, t-book,
I tried both the method but no luck.
Website still jumps back to local IP.
Any further thoughts

**Comment by gabrielbonifaz** [comment]
DId you find a solution for this issue? I think I have the same issue for a manual installation

**Comment by gabrielbonifaz** [comment]
Hi @deviirmr, did you find a solution?

**Comment by deviirmr** [comment]
does any buddy found any solution?

**Comment by deviirmr** [comment]
I found the solution.
The problem is GeoServer unable to map with given geonode web URL or IP, so we have to map the  GeoServer path in the Nginx conf file


`server {

        server_name <your domian name>;

        location / {
          	
     proxy_set_header X-Real-IP $remote_addr;
     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;       
     proxy_pass http://<your ip>:<port>/;

        }


    location /geoserver/ {
    proxy_pass http://<your ip>:<port>/geoserver/;
    proxy_pass_header Set-Cookie;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}


}`

**Comment by gannebamm** [comment]
I think this is something which should be described in the documentation? @t-book @afabiani 
@deviirmr As someone with experience in this: Could you prepare some small writeup on how to change the IP for GeoNode in a docker environment? If you are not familiar with github PullRequests you also just can create a small markdown snippet somewhere (eg. as gist) and ping us devs to integrate it ;)

**Comment by deviirmr** [comment]
Ok, I will add snippet next week. :)

**Comment by vipcxj** [comment]
Why won't fix and closed? It's strange not support to change port. It's common use case to use a reverse proxy such as nginx.

**Comment by afabiani** [comment]
This is already covered on "geonode-project" or "spcgeonode" docker setup

e.g.:
https://github.com/GeoNode/geonode-project/blob/master/docker/nginx/nginx.conf.envsubst#L25

**Comment by t-book** [comment]
> Why won't fix and closed? It's strange not support to change port. It's common use case to use a reverse proxy such as nginx.

We have a _stale bot_ that closes unanswered questions after some time. I do agree this does not ever fit for all issues.

**Comment by georgepoulos** [comment]
Hello from me!
Is not clear if we can install geonode in different port. 
I try ubuntu 20.04 installation and I still cannot understand why oath2 doesn't work.

**Comment by giohappy** [comment]
@georgepoulos do you mean a different port for Nginx or GeoNode (uWSGI) itself?

**Comment by georgepoulos** [comment]
I mean Nginx port. 
like gis.example.com:8082 
because port 80 is for example.com

**Comment by giohappy** [comment]
see comment from @afabiani https://github.com/GeoNode/geonode/issues/6023#issuecomment-751665877
Doesn't it cover what you need?

**Comment by georgepoulos** [comment]
Tricky!
I have install geonode on ubuntu 20.04
So I configure nginx sites-available --> geonode 
server {
  listen 8082 default_server;
  listen [::]:8082 default_server;

  root /var/www/html;
  index index.html index.htm index.nginx-debian.html;

  server_name 127.0.0.1 gis.somename.com;

  charset utf-8;

  etag on;
  expires $expires;
  proxy_read_timeout 600s;
.....

But I still get this ERROR
 ERROR [org.geoserver.security] - Could not Authorize OAuth2 Resource due to the following exception:
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://somename.com:8082/api/o/v4/tokeninfo/": Connection timed out (Connection timed out); nested exception is java.net.ConnectException: Connection timed out (Connection timed out)

**Comment by afabiani** [comment]
@georgepoulos most probably your docker containers are not able to resolve the domain http://somename.com due to a DNS issue.
You can eventually force this by declaring the DNS match into the `docker-compose.yml` through the `extra_hosts` directive

https://github.com/compose-spec/compose-spec/blob/master/spec.md#extra_hosts

**Comment by afabiani** [comment]
From your previous comment however the problem looks the same, GeoServer is not able to reach GeoNode on the port 8082.
You must be sure the port is not blocked somehow and it is reachable from the GeoServer machine.
If GeoServer and GeoNode are running on the same host, I would suggest using the internal address. In that case make sure the latter is also included into the `ALLOWED_HOSTS` variable.

**Comment by georgepoulos** [comment]
One more question!
At uwsgi file I will put the port on variables ? LIKE...

env = GEONODE_LB_HOST_IP=
env = GEONODE_LB_PORT=

env = SITEURL=http://gis.name.com:8082/


env = ALLOWED_HOSTS="['*']"

env = GEOSERVER_WEB_UI_LOCATION=http://gis.name.com:8082/geoserver/
env = GEOSERVER_PUBLIC_LOCATION=http://gis.name.com:8082/geoserver/
env = GEOSERVER_LOCATION=http://localhost:8080/geoserver/

**Comment by georgepoulos** [comment]
Thank you @afabiani  you was right!
I fix it changing ALLOWED_HOSTS and also on tomcat  /geoserver/WEB-INF/web.xml file in order to reach Geonode from geoserver
