### ISSUE TITLE
[SPCGeonode][Docker] Build exit in Geoserver

### ISSUE THREAD

**Issue by jonnyforestGIS** [GeoNode/geonode#6026]
## Expected Behavior
Using command for docker to build SPCGeonode Docker in clean installation run until the end and start to work in localhost.

## Actual Behavior
I suspect is the image can't reach the URL from GeoServer because is giving a timeout error. I test as well in the URL in the browser and give the same timeout. Probably this is not related to the dockerfile itself but the sourcefource.net.

```dockerfile

Step 6/21 : RUN update-ca-certificates
 ---> Running in 6abad1a3faf4
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
Removing intermediate container 6abad1a3faf4
 ---> 3d548ab8b11a
Step 7/21 : WORKDIR /
 ---> Running in 1ac53b9136e1
Removing intermediate container 1ac53b9136e1
 ---> d1f2a7a60c4c
Step 8/21 : RUN echo "Download geoserver for geonode" &&     wget https://downloads.sourceforge.net/project/geoserver/GeoServer/$version/geoserver-$version-bin.zip &&     wget https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-$branch.war --no-check-certificate &&     unzip geoserver-$version-bin.zip &&     mv geoserver-$version geoserver &&     rm /geoserver-$version-bin.zip &&     rm /geoserver-$version/webapps/geoserver/* -rf &&     unzip -o geoserver-$branch.war -d /geoserver/webapps/geoserver/ &&     rm /geoserver-$branch.war
 ---> Running in 684ced1769eb
Download geoserver for geonode
Connecting to downloads.sourceforge.net (216.105.38.13:443)
Connecting to netix.dl.sourceforge.net (208.80.126.2:443)
wget: can't connect to remote host (208.80.126.2): Operation timed out
ERROR: Service 'geoserver' failed to build: The command '/bin/sh -c echo "Download geoserver for geonode" &&     wget https://downloads.sourceforge.net/project/geoserver/GeoServer/$version/geoserver-$version-bin.zip &&     wget https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-$branch.war --no-check-certificate &&     unzip geoserver-$version-bin.zip &&     mv geoserver-$version geoserver &&     rm /geoserver-$version-bin.zip &&     rm /geoserver-$version/webapps/geoserver/* -rf &&     unzip -o geoserver-$branch.war -d /geoserver/webapps/geoserver/ &&     rm /geoserver-$branch.war' returned a non-zero code: 1

```

## Steps to Reproduce the Problem

  1. Run sudo docker-compose -f docker-compose.yml up -d --build

## Specifications

  - GeoNode version: 2.10.3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docker
  - Platform: Ubuntu 18.04 LTS
  - Additional details:

**Comment by jonnyforestGIS** [comment]
Maybe this is related to this issue https://github.com/gliderlabs/docker-alpine/issues/30 ?

**Comment by jonnyforestGIS** [comment]
@t-book i will close this. I can build the image for GeoServer but can't finish a success installation with docker. Maybe this is related to the talks in gitter? I need to test again

**Comment by t-book** [comment]
@jonnyforestGIS If I remember correctly SPC downloads a vanilla geoserver from sourceforge because of Jetty. Afterward the custom build for geonode. I think we could lower the risk of failing by starting with a vanilla GeoServer and just adding needed plugins. One curl less ist one curl less that can fail ...

**Comment by jonnyforestGIS** [comment]
Sorry @t-book I'm a newbie on this and I'm learning first steps of Docker. If I understand what you are saying is better to have the geoserver essentials to download with vanilla GeoServer installation. And if user need more install manually in their docker SPCGeonode configuration after SPCGeonode is running? Regards

**Comment by t-book** [comment]
@jonnyforestGIS no, you misunderstood. Please ignore my comment, it is more an idea for optimization of SPC than relevant for the ticket ;) I will try to test  SPC soon and see if I can find anything.

**Comment by jonnyforestGIS** [comment]
@t-book please If you need some feedback. I want to learn more of Geonode. I'm trying to integrate QGIS+Geonode in my research centre. I'm thinking of re-alive the Geoserver qgis plugin but I need to understand what kind incompatibles have with 3.x. Geonode Project have someplace to add wishlists or ideas to improve interoperabilities?

**Comment by t-book** [comment]
@jonnyforestGIS let's continue at gitter regarding qgis and keep github issues for bugs ;)

**Comment by jonnyforestGIS** [comment]
Sorry. Ok :)
