### ISSUE TITLE
Map not loaded using geoext client

### ISSUE THREAD

**Issue by JorgeMartinezG** [GeoNode/geonode#6027]
## Expected Behavior
Using geoext as map client with envvar **GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY="geoext"**, when visualizing a layer in the layer_detail page, the map should show the layer

## Actual Behavior

![image](https://user-images.githubusercontent.com/3285923/80366174-6dd93700-884e-11ea-8edf-d5286f84e023.png)

Also, the javascript console shows the following error:

```GeoExplorer.js:1793 Uncaught TypeError: Cannot read property 'split' of undefined
    at constructor.trimUrl (GeoExplorer.js:1793)
    at constructor.createStore (GeoExplorer.js:1791)
    at constructor.init (GeoExplorer.js:1697)
    at constructor.init (GeoExplorer.js:1789)
    at S.addLayerSource (GeoExplorer.js:1413)
    at S.<anonymous> (GeoExplorer.js:1412)
    at GeoExplorer.js:1315
```

## Steps to Reproduce the Problem

  1.Modify environment variables to setup geoext as map as layer preview library
  2.Start server and select a layer.

## Specifications

  - GeoNode version: 2.10.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual
  - Platform: MacOS, python 2.7
  - Additional details: None

**Comment by afabiani** [comment]
Be aware that GeoExt client has been dropped on GeoNode 3.0

**Comment by tigreped** [comment]
Well, I was going to open an issue about how the [documentation](https://docs.geonode.org/en/master/basic/settings/#geonode-client-layer-preview-library) currently states that there should be support to **"mapstore" "geoext" "leaflet" "react"** and, in fact, there was no support either in 2.10.3 (stable) nor on the 3 versions. So maybe change the documentation accordingly to what has been agreed upon being supported and perhaps explaining in some notes that there is deprecated alternatives.
