### ISSUE TITLE
Improve interface when creating a thumbnail

### ISSUE THREAD

**Issue by bermud** [GeoNode/geonode#6039]
**Is your feature request related to a problem? Please describe.**

Re: Version 3.0 at https://dev.geonode.geo-solutions.it/ (2020-04-29)

I was creating a thumbnail for a document. Once it was created, there was no button or navigation link to go back to my document or the metadata.

Also the auto generated thumbnail place holder should no show if I didn't request that action. It is confusing. I thought that my thumbnail was not been created, and I kept clicking on the upload.

**Describe the solution you'd like**
- Maybe add two links: 'Go to Document' and 'Go the Metadata'
- Remove the autogenerated Thumbnail (title and box) if didn't request the autogenerate action.

![image](https://user-images.githubusercontent.com/3738898/80621619-8d6e8c00-8a15-11ea-8f7c-d61cd5e4e29a.png)

**Comment by giohappy** [comment]
@bermud FYI GeoNode 3 now provides a better way to manage documents thumbnails within the Metadata Wizard. It provides a widget to crop an image and save it, similar to what you have for layers.

![image](https://user-images.githubusercontent.com/571129/80690573-4775fe80-8acf-11ea-8742-d582863d6d3d.png)
