### ISSUE TITLE
Issue when creating an empty layer

### ISSUE THREAD

**Issue by bermud** [GeoNode/geonode#6040]
## Expected Behavior

Not sure...

## Steps to Reproduce the Problem

1) I tried to create an empty layer 

![image](https://user-images.githubusercontent.com/3738898/80622238-872cdf80-8a16-11ea-94d3-9a7e2b9870ec.png)

2) I clicked on create 

3) Got this error

> 
> Request Method: | POST
> -- | --
> https://dev.geonode.geo-solutions.it/createlayer/
> 2.2.12
> AttributeError
> 'GeoNodeException' object has no attribute 'message'
> ./geonode/geoserver/createlayer/views.py in layer_create, line 52
> /usr/bin/uwsgi-core
> 3.6.9
> ['/home/geosolutions/geonode',  '.',  '',  '/home/geosolutions/Envs/geonode3/lib/python36.zip',  '/home/geosolutions/Envs/geonode3/lib/python3.6',  '/home/geosolutions/Envs/geonode3/lib/python3.6/lib-dynload',  '/usr/lib/python3.6',  '/home/geosolutions/Envs/geonode3/lib/python3.6/site-packages',  '/home/geosolutions/geonode-mapstore-client',  '/home/geosolutions/geonode']
> Wed, 29 Apr 2020 16:40:48 +0000
> 
> 

Environment:

Request Method: POST
Request URL: https://dev.geonode.geo-solutions.it/createlayer/

Django Version: 2.2.12
Python Version: 3.6.9
Installed Applications:
('modeltranslation',
 'dal',
 'dal_select2',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.admin',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.gis',
 'dj_pagination',
 'taggit',
 'treebeard',
 'leaflet',
 'bootstrap3_datetime',
 'django_filters',
 'mptt',
 'storages',
 'floppyforms',
 'django_forms_bootstrap',
 'avatar',
 'dialogos',
 'pinax.ratings',
 'announcements',
 'actstream',
 'user_messages',
 'tastypie',
 'polymorphic',
 'guardian',
 'oauth2_provider',
 'corsheaders',
 'invitations',
 'allauth',
 'allauth.account',
 'allauth.socialaccount',
 'geonode',
 'geonode.api',
 'geonode.base',
 'geonode.br',
 'geonode.layers',
 'geonode.maps',
 'geonode.documents',
 'geonode.security',
 'geonode.catalogue',
 'geonode.catalogue.metadataxsl',
 'geonode.people',
 'geonode.client',
 'geonode.themes',
 'geonode.proxy',
 'geonode.social',
 'geonode.groups',
 'geonode.services',
 'geonode.geoserver',
 'geonode.upload',
 'geonode.tasks',
 'geonode.messaging',
 'geonode.monitoring',
 'geonode.documents.exif',
 'geonode.geoserver.createlayer',
 'geonode.favorite',
 'mapstore2_adapter',
 'geonode_mapstore_client',
 'pinax.notifications',
 <Celery geonode at 0x7feceda79908>)
Installed Middleware:
('corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.contrib.sites.middleware.CurrentSiteMiddleware',
 'dj_pagination.middleware.PaginationMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'oauth2_provider.middleware.OAuth2TokenMiddleware',
 'geonode.base.middleware.MaintenanceMiddleware',
 'geonode.base.middleware.ReadOnlyMiddleware',
 'geonode.security.middleware.SessionControlMiddleware',
 'geonode.monitoring.middleware.MonitoringMiddleware')

Traceback:

File "./geonode/geoserver/createlayer/views.py" in layer_create
  48.                 layer = create_layer(name, title, request.user.username, geometry_type, attributes)

File "./geonode/geoserver/createlayer/utils.py" in create_layer
  57.     workspace, datastore = create_gs_layer(name, title, geometry_type, attributes)

File "./geonode/geoserver/createlayer/utils.py" in create_gs_layer
  250.         raise GeoNodeException("Layer could not be created in GeoServer")

During handling of the above exception (Layer could not be created in GeoServer), another exception occurred:

File "/home/geosolutions/Envs/geonode3/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/geosolutions/Envs/geonode3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/home/geosolutions/Envs/geonode3/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/geosolutions/Envs/geonode3/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "./geonode/geoserver/createlayer/views.py" in layer_create
  52.                 error = '%s (%s)' % (e.message, type(e))

Exception Type: AttributeError at /createlayer/
Exception Value: 'GeoNodeException' object has no attribute 'message'

## Specifications

  - GeoNode version: 3.0
  - Installation method : https://dev.geonode.geo-solutions.it/createlayer/
  - Platform:
  - Additional details: Accessed on 2020-04-29

**Comment by t-book** [comment]
Duplicate of https://github.com/GeoNode/geonode/issues/6025 ?
