### ISSUE TITLE
Geonode 3.0 print map error: Error on printing: Error while generating PDF: java.lang.NullPointerException at com.itextpdf.text.pdf.PdfPCell.

### ISSUE THREAD

**Issue by jncheung** [GeoNode/geonode#6074]
## Expected Behavior
A picture or pdf file will be available for download under the current map extent with the content of selected layers.
![image](https://user-images.githubusercontent.com/30644696/81669610-0b507f80-9479-11ea-893e-86dbd8fec542.png)

## Actual Behavior
Geonode shows error message.

geoserver4geonode | org.apache.batik.transcoder.TranscoderException: null
geoserver4geonode | Enclosed Exception:
geoserver4geonode | geoserver_data
geoserver4geonode | 	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:136)
geoserver4geonode | 	at org.apache.batik.transcoder.SVGAbstractTranscoder.transcode(SVGAbstractTranscoder.java:156)
geoserver4geonode | 	at org.apache.batik.transcoder.print.PrintTranscoder.print(PrintTranscoder.java:307)
geoserver4geonode | 	at org.mapfish.print.config.layout.ImageBlock$SvgDrawer.renderImpl(ImageBlock.java:140)
geoserver4geonode | 	at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
geoserver4geonode | 	at org.mapfish.print.ChunkDrawer.tableLayout(ChunkDrawer.java:49)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:786)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.goComposite(ColumnText.java:1765)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:882)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:877)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:866)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPRow.writeCells(PdfPRow.java:549)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:764)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.goComposite(ColumnText.java:1765)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:882)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:877)
geoserver4geonode | 	at com.itextpdf.text.pdf.ColumnText.go(ColumnText.java:866)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPRow.writeCells(PdfPRow.java:549)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:764)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:889)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:837)
geoserver4geonode | 	at com.itextpdf.text.pdf.PdfPTable.writeSelectedRows(PdfPTable.java:815)
geoserver4geonode | 	at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:67)
geoserver4geonode | 	at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183)
geoserver4geonode | 	at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56)
geoserver4geonode | 	at org.mapfish.print.config.layout.Page.render(Page.java:90)
geoserver4geonode | 	at org.mapfish.print.config.layout.Layout.render(Layout.java:64)
geoserver4geonode | 	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30)
geoserver4geonode | 	at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:61)
geoserver4geonode | 	at org.mapfish.print.MapPrinter.print(MapPrinter.java:175)
geoserver4geonode | 	at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:383)
geoserver4geonode | 	at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:184)
geoserver4geonode | 	at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:112)
geoserver4geonode | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
geoserver4geonode | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
geoserver4geonode | 	at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165)
geoserver4geonode | 	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
geoserver4geonode | 	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52)
geoserver4geonode | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
geoserver4geonode | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
geoserver4geonode | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998)
geoserver4geonode | 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901)
geoserver4geonode | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
geoserver4geonode | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875)
geoserver4geonode | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69)
geoserver4geonode | 	at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:83)
geoserver4geonode | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
geoserver4geonode | 	at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89)
geoserver4geonode | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
geoserver4geonode | 	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:73)
geoserver4geonode | 	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66)
geoserver4geonode | 	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
geoserver4geonode | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
geoserver4geonode | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
geoserver4geonode | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:174)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
geoserver4geonode | 	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158)
geoserver4geonode | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70)
geoserver4geonode | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74)
geoserver4geonode | 	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
geoserver4geonode | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
geoserver4geonode | 	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142)
geoserver4geonode | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
geoserver4geonode | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:90)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
geoserver4geonode | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:352)
geoserver4geonode | 	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
geoserver4geonode | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
geoserver4geonode | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200)
geoserver4geonode | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
geoserver4geonode | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
geoserver4geonode | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
geoserver4geonode | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
geoserver4geonode | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
geoserver4geonode | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
geoserver4geonode | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
geoserver4geonode | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
geoserver4geonode | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
geoserver4geonode | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836)
geoserver4geonode | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839)
geoserver4geonode | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
geoserver4geonode | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
geoserver4geonode | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
geoserver4geonode | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
geoserver4geonode | 	at java.lang.Thread.run(Thread.java:748)
geoserver4geonode | Caused by: java.net.UnknownHostException: geoserver_data
geoserver4geonode | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
geoserver4geonode | 	at java.net.Socket.connect(Socket.java:607)
geoserver4geonode | 	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962)
geoserver4geonode | 	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
geoserver4geonode | 	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
geoserver4geonode | 	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
geoserver4geonode | 	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:311)
geoserver4geonode | 	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:417)
geoserver4geonode | 	at org.apache.batik.util.ParsedURLData.openStreamInternal(ParsedURLData.java:554)
geoserver4geonode | 	at org.apache.batik.util.ParsedURLData.openStream(ParsedURLData.java:476)
geoserver4geonode | 	at org.apache.batik.util.ParsedURL.openStream(ParsedURL.java:440)
geoserver4geonode | 	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:158)
geoserver4geonode | 	at org.apache.batik.anim.dom.SAXSVGDocumentFactory.createDocument(SAXSVGDocumentFactory.java:283)
geoserver4geonode | 	at org.apache.batik.transcoder.XMLAbstractTranscoder.transcode(XMLAbstractTranscoder.java:129)
geoserver4geonode | 	... 138 more
geoserver4geonode | ERROR: null
geoserver4geonode | Enclosed Exception:
geoserver4geonode | null
geoserver4geonode | Enclosed Exception:
geoserver4geonode | geoserver_data
nginx4geonode    | my.ip.address - - [12/May/2020:09:36:01 +0000] "POST /geoserver/pdf/create.json?access_token=8YepUzt05zhgGh6j8iOaMR6xhw1mmv HTTP/1.1" 500 1693 "http://server.ip.address/maps/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "-"

![image](https://user-images.githubusercontent.com/30644696/81668806-c6781900-9477-11ea-81b5-3d953c4714b5.png)

Error on printing: Error while generating PDF: java.lang.NullPointerException at com.itextpdf.text.pdf.PdfPCell.<init>(PdfPCell.java:237) at com.itextpdf.text.pdf.PdfPTable.addCell(PdfPTable.java:484) at org.mapfish.print.PDFUtils.buildTable(PDFUtils.java:661) at org.mapfish.print.config.layout.ColumnsBlock$1.render(ColumnsBlock.java:58) at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:183) at org.mapfish.print.config.layout.ColumnsBlock.render(ColumnsBlock.java:56) at org.mapfish.print.config.layout.Page.render(Page.java:90) at org.mapfish.print.config.layout.Layout.render(Layout.java:64) at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:30) at org.mapfish.print.output.PdfOutputFactory.print(PdfOutputFactory.java:61) at org.mapfish.print.MapPrinter.print(MapPrinter.java:175) at org.mapfish.print.servlet.MapPrinterServlet.doCreatePDFFile(MapPrinterServlet.java:383) at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:184) at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:112) at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.springframework.web.servlet.mvc.ServletWrappingController.handleRequestInternal(ServletWrappingController.java:165) at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177) at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:52) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:998) at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:901) at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:875) at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:26) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:69) at org.geoserver.monitor.MonitorFilter.doFilter(MonitorFilter.java:83) at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66) at org.geoserver.flow.controller.IpBlacklistFilter.doFilter(IpBlacklistFilter.java:89) at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66) at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:73) at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:66) at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:41) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:37) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127) at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74) at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70) at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:119) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74) at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:51) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.geoserver.security.oauth2.GeoServerOAuthAuthenticationFilter.doFilter(GeoServerOAuthAuthenticationFilter.java:174) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70) at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilterInternal(BasicAuthenticationFilter.java:158) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74) at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91) at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:81) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:70) at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:52) at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:74) at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:91) at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:142) at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:90) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:46) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:42) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:352) at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:171) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1839) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748)

## Steps to Reproduce the Problem

  1. Create an empty Map
  2. Load Layers
  3. Click "Print" in Options
  4. And Print

## Specifications

  - GeoNode version: Docker geonode image:latest
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker compose
  - Platform: Ubuntu 18.04.4 LTS
  - Additional details: GeoServer 2.15.4 is using &
geonode/geoserver_data:2.15.4 for data-dir-conf & 
pgrouting/pgrouting:11-2.5-2.6.3 for Database

**Comment by t-book** [comment]
Tried to reproduce this: master branch with docker-compose. Working for me

**Comment by t-book** [comment]
@jncheung is still happening for you? tried again several times but cannot reproduce. If this is solved please close your issue.

**Comment by etj** [comment]
This issue is strictly related:

https://github.com/GeoNode/geoserver-geonode-ext/issues/183
