### ISSUE TITLE
UnicodeEncodeError at /proxy/

### ISSUE THREAD

**Issue by ddovnar** [GeoNode/geonode#6124]
## Expected Behavior

Search by cyrillic letters in map (mapstore).

## Actual Behavior
I got an error http-500:
'ascii' codec can't encode characters in position 39-46: ordinal not in range(128)

## Steps to Reproduce the Problem

  1. Create new Map
  2. Try to search some city by cirillic letters, for example: 'Киев'

## Specifications

  - GeoNode version: 2.10.3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: Debian
  - Additional details: see attachments
![geonode_screen](https://user-images.githubusercontent.com/39269414/82738989-c49a3980-9d44-11ea-8fce-43b716810e1e.png)
[response_trace.html.pdf](https://github.com/GeoNode/geonode/files/4672410/response_trace.html.pdf)

**Comment by t-book** [comment]
@ddovnar See: https://github.com/GeoNode/geonode/issues/5750 any chance to test this  with 2.10.4 ?

**Comment by t-book** [comment]
Let's continue here: https://github.com/GeoNode/geonode/issues/5750
