### ISSUE TITLE
Texts not included in po files

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6131]
## Expected Behavior
Displayed text is included in the po files to enable i18n translation to the chosen language. 

## Actual Behavior
Some texts are not included in po files and will not work in other languages as English.

Example:
![grafik](https://user-images.githubusercontent.com/6172324/82994492-8af65680-a002-11ea-9984-71c32e3667d0.png)

https://master.demo.geonode.org/layers/?limit=5&offset=0

which is rendered by https://github.com/GeoNode/geonode/blob/master/geonode/templates/search/_search_content.html#L4 and https://github.com/GeoNode/geonode/blob/master/geonode/static/geonode/js/templates/cart.html

## Steps to Reproduce the Problem

  1. https://master.demo.geonode.org/layers/?limit=5&offset=0

## Specifications

  - GeoNode version: 2.10.x / 3.x

**Comment by t-book** [comment]
From what I see, the idea has been to get the current scope from the cart itself:

https://github.com/GeoNode/geonode/blob/ac8bcb43816e5ffafbfd227295baecc5a26f91ed/geonode/static/geonode/js/search/cart.js#L74-L82

reads

https://github.com/GeoNode/geonode/blob/master/geonode/templates/search/_search_content.html#L4

Doing so the cart names documents, maps, or layers depending on the current URL. IMHO as we get the scope from {{ facet_type }} and we already have translations f.e.:

https://github.com/GeoNode/geonode/blob/master/geonode/locale/de/LC_MESSAGES/django.po#L2001

we could keep angular out of the game. Besides. I do think the term "checkboxes" is not right. What the user sees are buttons labeled with "+"

**Comment by gannebamm** [comment]
There is an regression on master:
![grafik](https://user-images.githubusercontent.com/6172324/96867543-246c4c00-146d-11eb-8515-c17ec8682d74.png)

**Comment by gannebamm** [comment]
Which is strange, since the file has not changed since this commit:
https://github.com/GeoNode/geonode/blame/master/geonode/base/templates/base/_resourcebase_snippet.html

**Comment by gannebamm** [comment]
It is not regression, but the strings currently do miss in the german po/mo files

**Comment by gannebamm** [comment]
See PR #6561

**Comment by gannebamm** [comment]
I would close this, even though there are missing parts in the translations, see #6534
