### ISSUE TITLE
Error upload layer 

### ISSUE THREAD

**Issue by harissum** [GeoNode/geonode#6139]
## Actual Behavior
![image](https://user-images.githubusercontent.com/7020174/83483333-95b25f00-a4cc-11ea-862c-af43e314cbd5.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 3.1.0.dev1590588566
  - Installation method (manual):
  - Platform: Ubuntu 18.04.4
  - Additional details:

**Comment by harissum** [comment]
Can you help me with this problem?

**Comment by t-book** [comment]
Hi, your settings do have correct admin credentials for geoserver?

**Comment by harissum** [comment]
Yes, I have correct admin credentials for geoserver. Is there possibility
that application setuptools version 47.1.1, pip V 20.1.1 and wheel V 0.34.2
implicate the result like this happen to the problem that I facing?

**Comment by t-book** [comment]
I do not think so. Can you double check your oauth Settings?

**Comment by t-book** [comment]
@harissum But the error message is clear. You have some issues with your auth configuration as the 401 indicates. A quick and easy test if the oauth communication works is to log in into geonode and after that use the little auth button on side of geoserver


<img width="573" alt="Bildschirmfoto 2020-06-05 um 12 42 39" src="https://user-images.githubusercontent.com/20478652/83867784-3f425c00-a72a-11ea-8978-d60c14a262f2.png">

If this works geoserver can validate your session. If not you need to configure your oauth settings again. 

Geonode issues should be kept for bugs. Would you kindly use the user mailing list or ask for help at gitter? thanks.

**Comment by t-book** [comment]
@harissum see: https://gitter.im/GeoNode/general?at=5edccca5f0b8a2053adc6876
