### ISSUE TITLE
502 Bad Gateway installing Geonode nginx.

### ISSUE THREAD

**Issue by davidpiedrarojas** [GeoNode/geonode#6152]
## Expected Behavior
The main webpage for the Geonode should load, instead I get the 502 Bad Gateway.

## Actual Behavior
I followed the manual installation process using the guide https://docs.geonode.org/en/3.0/install/advanced/core/index.html#ubuntu-18-04

After following the steps for the nginx instalation and configuration I get 502 Bad Gateway when trying to access http://localhost. 

I copy paste the config files from the guide and didn´t make any changes. I've done this process twice and in both the error is the same.

In the the geonode.log I get
` 
!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
Thu Jun  4 20:31:20 2020 - no request plugin is loaded, you will not be able to manage requests.
Thu Jun  4 20:31:20 2020 - you may need to install the package for your language of choice, or simply load it with --plugin.
Thu Jun  4 20:31:20 2020 - 
!!!!!!!!!!! END OF WARNING !!!!!!!!!!
`
The nginx log have
`
2020/06/04 20:31:36 [error] 31241#31241: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.0", upstream: "uwsgi://0.0.0.0:8000", host: "localhost"
`
I've checked and followed the steps in this closed issue https://github.com/GeoNode/geonode/issues/6059 but still having 502 error. Even installed the uwsgi-plugin-python plugin and changed in the geonode.ini file, but still the same.

## Steps to Reproduce the Problem

I followed the manual installation process using the guide https://docs.geonode.org/en/3.0/install/advanced/core/index.html#ubuntu-18-04, before the "Update the settings in order to use the PostgreSQL Database" heading.

## Specifications

  - GeoNode version: 3.0
  - Installation method manual
  - Platform: Ubuntu Server 18.04
  - Additional details:

Thank you for your help.

**Comment by t-book** [comment]
@davidpiedrarojas there has been lately a nice update regarding installation provided by @afabiani  https://docs.geonode.org/en/master/install/basic/index.html Would you kindly check your setup based on this document? Further github issues should mainly be kept for bugs. For questions regarding configurations, user lists or gitter should be used. Nevertheless, I'll keep this open until we are sure this is no problem with docs.

**Comment by davidpiedrarojas** [comment]
Sorry about the question using github, didn´t know you where using this only for bugs.

Y followed the guide you recomend and now everyting is working, the only difference  was that in the uwsig geonode.ini config now there´s this line

`env = DJANGO_EMAIL_USE_SSL=False`

After adding this line the server works fine.

Thank you.

**Comment by t-book** [comment]
Perfect thanks for reporting @davidpiedrarojas and glad you solved it.

**Comment by HEM2058** [comment]
> DJANGO_EMAIL_USE_SSL=False

In which file we have to place this code?

**Comment by nitesh047** [comment]
Bad Gateway while installing geonode on EC2 while my geoserver is running fine.

my Geonode logs

Tue Mar 19 06:12:54 2024 - *** Starting uWSGI 2.0.20-debian (64bit) on [Tue Mar 19 06:12:54 2024] ***
Tue Mar 19 06:12:54 2024 - compiled with version: 11.2.0 on 21 March 2022 11:00:44
Tue Mar 19 06:12:54 2024 - os: Linux-6.5.0-1014-aws #14~22.04.1-Ubuntu SMP Thu Feb 15 15:27:06 UTC 2024
Tue Mar 19 06:12:54 2024 - nodename: ip-172-31-48-135
Tue Mar 19 06:12:54 2024 - machine: x86_64
Tue Mar 19 06:12:54 2024 - clock source: unix
Tue Mar 19 06:12:54 2024 - pcre jit disabled
Tue Mar 19 06:12:54 2024 - detected number of CPU cores: 2
Tue Mar 19 06:12:54 2024 - current working directory: /
Tue Mar 19 06:12:54 2024 - writing pidfile to /run/uwsgi/app/geonode/pid
Tue Mar 19 06:12:54 2024 - detected binary path: /usr/bin/uwsgi-core
Tue Mar 19 06:12:54 2024 - chdir() to /opt/geonode
Tue Mar 19 06:12:54 2024 - your processes number limit is 31660
Tue Mar 19 06:12:54 2024 - your memory page size is 4096 bytes
Tue Mar 19 06:12:54 2024 -  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
Tue Mar 19 06:12:54 2024 - detected max file descriptor number: 1024
Tue Mar 19 06:12:54 2024 - lock engine: pthread robust mutexes
Tue Mar 19 06:12:54 2024 - thunder lock: disabled (you can enable it with --thunder-lock)
Tue Mar 19 06:12:54 2024 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/geonode/socket fd 3
Tue Mar 19 06:12:54 2024 - uwsgi socket 1 bound to TCP address 0.0.0.0:8000 fd 5
Tue Mar 19 06:12:54 2024 - setgid() to 33
Tue Mar 19 06:12:54 2024 - setuid() to 33
Tue Mar 19 06:12:54 2024 - Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Tue Mar 19 06:12:54 2024 - !!! Python Home is not a directory: /home/ubuntu/.virtualenvs/geonode_env !!!
Tue Mar 19 06:12:54 2024 - Set PythonHome to /home/ubuntu/.virtualenvs/geonode_env
Python path configuration:
  PYTHONHOME = '/home/ubuntu/.virtualenvs/geonode_env'
  PYTHONPATH = (not set)
  program name = '/home/ubuntu/.virtualenvs/geonode_env/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/ubuntu/.virtualenvs/geonode_env/bin/python'
  sys.base_prefix = '/home/ubuntu/.virtualenvs/geonode_env'
  sys.base_exec_prefix = '/home/ubuntu/.virtualenvs/geonode_env'
  sys.platlibdir = 'lib'
  sys.executable = '/home/ubuntu/.virtualenvs/geonode_env/bin/python'
  sys.prefix = '/home/ubuntu/.virtualenvs/geonode_env'
  sys.exec_prefix = '/home/ubuntu/.virtualenvs/geonode_env'
  sys.path = [
    '/home/ubuntu/.virtualenvs/geonode_env/lib/python310.zip',
    '/home/ubuntu/.virtualenvs/geonode_env/lib/python3.10',
    '/home/ubuntu/.virtualenvs/geonode_env/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f3469070bc0 (most recent call first):
  <no Python frame>
