### ISSUE TITLE
New settings variable to disable Gravatar request

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#6153]
**Is your feature request related to a problem? Please describe.**

Regarding privacy policy the default image/request to gravatar.com -if no profile image is available- is problematic . You could inform users about this request in your data agreement but this is another hurdle to take.

**Describe the solution you'd like**

I'd like to introduce the following new settings variables as suggested by @petrus7 
https://github.com/GeoNode/geonode/issues/5906#issuecomment-602486637

( ! Needs to be tested )
```
AVATAR_DEFAULT_URL = os.getenv('AVATAR_DEFAULT_URL', '/geonode/img/avatar.png')

# Gravatar
try:
    # try to parse python notation, default in dockerized env
    AVATAR_PROVIDERS = ast.literal_eval(os.getenv('AVATAR_PROVIDERS'))
except ValueError:
    # fallback to regular list of values separated with misc chars
    AVATAR_PROVIDERS = (
    'avatar.providers.PrimaryAvatarProvider',
    'avatar.providers.GravatarAvatarProvider',
    'avatar.providers.DefaultAvatarProvider'
   ) if os.getenv('AVATAR_PROVIDERS') is None \
        else re.split(r' *[,|:|;] *', os.getenv('AVATAR_PROVIDERS'))

```
The default settings should use GravatarAvatarProvider over DefaultAvatarProvider to keep the current behavior but should allow changing this by environment variables if needed.

.env
```
AVATAR_PROVIDERS='avatar.providers.PrimaryAvatarProvider','avatar.providers.DefaultAvatarProvider'
```

**Describe alternatives you've considered**
Do nothing

**Comment by afabiani** [comment]
+1
