### ISSUE TITLE
Upgrade Geonode 2.10 to 3.0

### ISSUE THREAD

**Issue by achorivai** [GeoNode/geonode#6154]
**Is your feature request related to a problem? Please describe.**
How to upgrade Geonode 2.10.1 to 3.0?

**Comment by t-book** [comment]
hi @achorivai Geonode issues should be kept for bugs. Would you kindly use the user mailing list or ask for help at gitter? thanks.

**Comment by achorivai** [comment]
ok Thanks @t-book
