### ISSUE TITLE
GNIP 76 - Add RTL Support

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#6156]
# GNIP 76 - Add RTL Support

## Overview

GeoNode currently supports 31 languages. (Hebrew might soon follow as no. 32)
From these languages, the following are written from right to left:

('ar', 'Arabic')
('he','Hebrew')
('fa', 'Persian')

https://meta.wikimedia.org/wiki/Template:List_of_language_names_ordered_by_code
This GNIP suggest enabling right-to-left support for named languages

<img width="1339" alt="Bildschirmfoto 2020-06-05 um 12 56 17" src="https://user-images.githubusercontent.com/20478652/83870243-32c00280-a72e-11ea-889c-5a6c82f1b771.png">
<img width="1333" alt="Bildschirmfoto 2020-06-05 um 12 57 54" src="https://user-images.githubusercontent.com/20478652/83870254-36ec2000-a72e-11ea-9a45-b3ddead52f9a.png">
<img width="1341" alt="Bildschirmfoto 2020-06-05 um 12 59 33" src="https://user-images.githubusercontent.com/20478652/83870258-394e7a00-a72e-11ea-8164-e565b3975cc6.png">

### Proposed By

toni.schoenbuchner@csgis.de

### Assigned to Release

This proposal is for GeoNode 3.1.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

The benefits should be clear, a correct reading direction for rtl languages.

## Proposal

Technically this is quite simple. 

 base.html
```
{% get_current_language_bidi as LANGUAGE_BIDI %}
{% if LANGUAGE_BIDI %}
<link rel="stylesheet" href="//cdn.rawgit.com/morteza/bootstrap-rtl/v3.3.4/dist/css/bootstrap-rtl.min.css">
<link rel="stylesheet" type="text/css" href="{% static "lib/css/rtl_overwrite.min.css" %}">
{% endif %}
```

The if statement uses `get_current_language_bidi` (https://docs.djangoproject.com/en/3.0/topics/i18n/translation/#get-current-language-bidi)
in case the language is RTL two more stylesheets are loaded.

The first loads the general rtl-overwrite for bootstrap from a public cdn.
The second line will load custom styles that will handle margins for example geonode specific items like icons. Further the later will make sure the viewer section will stay LTR.

### Backwards Compatibility

Will be fully compatible until templates inherit from base.html. Further this will fail gracefully as all what will happen is that an RTL language is rendered LTR

## Future evolution

The use of RTL Templates could be set by a new settings variable `USE_RTL=False|True`

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: ✓
* Francesco Bartoli: ✓
* Giovanni Allegri:
* Simone Dalmasso: ✓ _by mail_
* Toni Schoenbuchner:  ✓
* Florian Hoedt: ✓

**Comment by giohappy** [comment]
@t-book is the UI horizontal flip intentional or a side effect of the RTL support?

**Comment by t-book** [comment]
@giohappy I see this with respect to the reading direction or what get's into focus first.
For Example at a layer detail page:

LTR: Map -> Tools (Right hand side)
RTL: Map -> Tools (Left hand side)

I do not speak arabic but our arabic userbase agrees with it. From what I further see this flip happens on other RTL pages as well: F.e.: https://arabic-media.com/arabicnews.htm look at the home button at the menu bar. However, I would be happy to hear opinions from native speakers as well.

**Comment by giohappy** [comment]
thanks @t-book I never noticed that RTL languages used flipped GUIs....

**Comment by francbartoli** [comment]
+1 thanks @t-book

**Comment by afabiani** [comment]
very cool +1
