### ISSUE TITLE
DEBUG_STATIC=True breaks functionality

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#6181]
# Problem 1

## Expected Behavior
No 404 errors

## Actual Behavior
DEBUG_STATIC=True leads to some 404 errors

<img width="685" alt="Bildschirmfoto 2020-06-09 um 21 33 47" src="https://user-images.githubusercontent.com/20478652/84191550-edd2fd80-aa98-11ea-9c59-e7441a19d56c.png">

We need to check if those are missing or if they can be removed from base.html

## Steps to Reproduce the Problem

Follow the frontend dev instructions.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): paver
  - Platform: OSX

**Comment by t-book** [comment]
# Problem 2

The Layer list stays empty Console is showing an error as it cannot find:

<img width="1329" alt="Bildschirmfoto 2020-06-10 um 08 38 46" src="https://user-images.githubusercontent.com/20478652/84235266-dbd37800-aaf5-11ea-9b87-c3a29c522383.png">

`<script src="{% static "lib/js/angular-openlayers-directive.js" %}"></script>
`

**Comment by jannefleischer** [comment]
Bytheway: I this should be still open, until fixed. This seems to be critical for any further frontend-development, isn't it?

**Comment by t-book** [comment]
I guess there are only some path definitions to fix. As one can always run grunt production before testing I would not say this is really critical, but true this needs to be fixed.

**Comment by jannefleischer** [comment]
For future reference: https://gitter.im/GeoNode/general?at=5f97e5e698a7774f1b6c7db1
