### ISSUE TITLE
GNIP 77 - GetFeatureInfo Templating For GeoNode

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6182]
# GNIP 77 - GetFeatureInfo Templating For GeoNode

## Overview

This proposal aims to improve the way GeoNode injects a “GetFeatureInfo” Template into the maps created with MapStore2.

What is a “GetFeatureInfo” Template and how is it working now?

When “clicking” over a feature of a Layer into a GeoNode Map, an info window popups showing a formatted representation of the raw data identified by the coordinates (see Fig. 1)

![image](https://user-images.githubusercontent.com/1278021/84203571-f54ed280-aaa9-11ea-98e8-39ba074b8544.png)

The way how such information is presented to the user is defined by what we call “GetFeatureInfo Template”. The latter is basically an HTML snippet containing some placeholders and special inline codes that instruct GeoServer on how to generate the raw data output.

The outcome is a rendered HTML snippet with the real values replacing the placeholders of the Template.

Currently, GeoNode allows a very simple mechanism to customize the “GetFeatureInfo Template” of a Layer.

It is possible, through the Layer Metadata Editor Wizard, to assign a name and a label to the attributes we want to display on the GetFeatureInfo output.

Notice that the attributes without a label and name, in case others are present, won’t be rendered at all.

As an instance, by using the example above, we can customize a bit the Layer Metadata as shown in Fig. 2

![image](https://user-images.githubusercontent.com/1278021/84203628-0992cf80-aaaa-11ea-9848-d64de1dbe042.png)

The “GetFeatureInfo” output will change accordingly as shown in Fig. 3

![image](https://user-images.githubusercontent.com/1278021/84203659-19aaaf00-aaaa-11ea-8496-d244ba148829.png)

### Proposed By

@afabiani 

### Assigned to Release

This proposal is for GeoNode 3.1.

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Current GetFeatureInfo Templates are limited to labels and order. The idea would be to allow GetFeatureInfo to be able to render also images, links, maybe other media in the future, and also to allow the user to customize the HTML template in a fancy way.

### Implement widget based visualization of attributes for GetFeatureInfo response

1. Add a new "Widget" column to the Dataset Attributes step of the Metadata Wizard, where "Link" or "Image" widgets can be selected (see Fig. 4).

2. GeoNode already inflates an HTML template if custom dataset attributes are defined. We need to extend this automatically created template to include HTML fragment to show the selected widget.

This is a simplified approach, which assumes that the specific attribute value is directly usable as a `<a href="value">` or a `<img src="value">`.

In both cases, we assume absolute URLs.

![image](https://user-images.githubusercontent.com/1278021/84203340-94bf9580-aaa9-11ea-9c9d-1a418ef4b756.png)

### Implement custom HTML template for visualization of GetFeatureInfo response

As an alternative to the use of aliases and widgets (see above) for the visualization of GetFeatureInfo response, we implement the option to configure a template as HTML code.

A textarea for the editing of the template will be placed below the table of attributes inside the Dataset Attributes step of the Metadata Wizard

In this case, GeoNode will not generate the GetFeatureInfo template for MapStore itself, rather the custom HTML will be used.

**NOTICE**: Attributes configurations and HTML templates are mutually exclusive options.

![image](https://user-images.githubusercontent.com/1278021/84203473-c6386100-aaa9-11ea-9627-efad9f77662b.png)

### Backwards Compatibility

No backward compatibility.

## Future evolution

 - Move the template editor on the GIS client in order to make easier the access to the UI.
 - Allow the GetFeatureInfo template to render other media types like videos and sounds.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: +1
* Francesco Bartoli: +1 (mail in dev list)
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner: +1
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by t-book** [comment]
Great Feature.
Imho:

> Implement widget based visualization of attributes for GetFeatureInfo response

is more user friendly where

> Implement custom HTML template for visualization of GetFeatureInfo response
 
might suit better for users which can write at least a little HTML code. I'm a bit more in favor for the later but do not have an objective view

**Comment by afabiani** [comment]
@t-book actually the idea is to implement both.

For the time being, I've implemented something like this:

![image](https://user-images.githubusercontent.com/1278021/84241475-d1b67700-aaff-11ea-8635-e656e6e989df.png)

![image](https://user-images.githubusercontent.com/1278021/84241548-e72ba100-aaff-11ea-9e71-46bb42b6a272.png)

![image](https://user-images.githubusercontent.com/1278021/84241598-f7438080-aaff-11ea-8954-254fe46947ca.png)

**Comment by t-book** [comment]
@afabiani Nice even better!

**Comment by afabiani** [comment]
Added video and audio too

![image](https://user-images.githubusercontent.com/1278021/84242930-c9f7d200-ab01-11ea-9fba-801d1ae2181a.png)

**Comment by t-book** [comment]
@afabiani would it work with an iframe from vimeo or youtube or require the video to be uploaded to the server?

I like the improvement as this adds a further connection between layers and document section. One could upload a PDF or some image and show it with a layer

**Comment by giohappy** [comment]
@t-book you can put whatever you want inside the HTML template, even completely unrelated to the attributes values :)

**Comment by afabiani** [comment]
Added an iframe property too

![image](https://user-images.githubusercontent.com/1278021/84245241-0842c080-ab05-11ea-9388-003c1f6b5240.png)

it will render something like this 

![image](https://user-images.githubusercontent.com/1278021/84245287-1c86bd80-ab05-11ea-8127-aaf4175f025a.png)

Otherwise, you can use the HTML editor

**Comment by gannebamm** [comment]
This is great!

**Comment by gannebamm** [comment]
Will these be enabled for the WMS GetFeature Infos, too? Like the GeoServer implementation described here: https://docs.geoserver.org/stable/en/user/tutorials/GetFeatureInfo/index.html

**Comment by giohappy** [comment]
@gannebamm unfortunately not at this stage. It's in our plans to refactor this side and improve the integration with MapStore's client to align GetFeatureInfo and GetFeature (attributes table) responses.

**Comment by t-book** [comment]
@giohappy @afabiani As this allows a vast variety of user-added content we should double-check bulletproof server-side validation to prevent xss. The used tiny-mce has [two known vulnerabilities](https://snyk.io/vuln/npm:tinymce@5.0.14), which I, fortunately -even if tampering the request- could not reproduce. 

Where I am unsure is if allowing iframe is a good thing at all. You could not stop users to spoil maps with porn or other things. Here [are more reasons](https://www.ostraining.com/blog/webdesign/against-using-iframes/#:~:text=Iframes%20Bring%20Security%20Risks,phishing%20your%20users'%20personal%20data.&text=A%20malicious%20user%20can%20change%20the%20source%20site%20URL.).

**Comment by giohappy** [comment]
I agree with you @t-book, I was having the same concerns.
@afabiani I would remove the iframe option from the widgets.
For the free html template I guess we could to a bit of static analysis of the submitted markup, and refuse to save code containing <script> and <iframe> elements. Is it doable @afabiani ?

Regarding the actual contents, it's out of our responsability. They could even store the link of a porn video / image in a vector feature.

**Comment by afabiani** [comment]
I'll see what we can do, but I agree with @giohappy 
This is a server, the responsibility of the setup, contents and security is on users when speaking about contents of course.

**Comment by t-book** [comment]
thanks to both of you for your answers. 

> Regarding the actual contents, it's out of our responsability. They could even store the link of a porn video / image in a vector feature.

yes and now as I do think iframes open security issues links do not.

> refuse to save code containing <script> and

I think this is already happening. Even after trying hard I could not inject code in my tests.

From other Content management systems, I know a common workaround is to let the admin decide if iframe should be allowed for users or not. If he/she takes the risk it's his/her decision.

However, if you @afabiani decide to include iframes I'm fine with it. 

 From my tests, this new feature looks very well tailored and is working fine.

**Comment by ahmednosman** [comment]
I suggest a different take on this, I would like to suggest the getfeatureinfo template(identify popup template) to apply at the presentation level and not the layer meta data level (so we can have more than one template defined). A user can have multiple presentations (SLDs) for the same layer, for each presentation the user wants a different featureInfo template so a good place to host the featureInfo template will be the layer details page at the editing tools dialog, right next to the metadata, styles, thumbnails..., from here you launch a custom dialog to add/edit popup dialogs for each layer, in this dialog the user can have an multiple choices to create/delete/modify 
1) a featureinfo template derived from a dialog similar to the layer meta data field form 
2) use a form for advanced templating (for advanced users)

Additional features to consider to the template popup 
- URLs, image video, voice, charts, expressions..

**Comment by giohappy** [comment]
@ahmednosman as mentioned before we have plans to extend the management of layer presets, including those regarding getfeatureinfo and getfeature response. It won't happen very soon but the plans are on our tables and will be shared with the community as soon they're in a good shape.

**Comment by gannebamm** [comment]
@ahmednosman https://github.com/GeoNode/geonode/issues/6182#issuecomment-641931566
> I suggest a different take on this, I would like to suggest the getfeatureinfo template(identify popup template) to apply at the presentation level and not the layer meta data level (so we can have more than one template defined). A user can have multiple presentations (SLDs) for the same layer, for each presentation the user wants a different featureInfo template [...]

This is a good point though. One layer may have several SLDs to actually render the information. We for example of huge monitoring data with a great number of attributes which usually get hosted as one layer and displayed with many different SLDs. I would not know how to create one single feature-info to cover them all.

**Comment by t-book** [comment]
@afabiani It looks this issue has been accidently closed? I do reopen it.

**Comment by aggeloskoutanis** [comment]
is this implemented ? I can't find it on GeoNode

**Comment by ayushman00sri** [comment]
> The outcome is a rendered HTML snippet with the real values replacing the placeholders of the Template.

hello sir ,
I'm not able to find this option (dataset Attributes) . can you pleas suggest me how to find this option, so that I can resole the issue I am facing , while clicking on any point it shows codes instead of the information, here is the screenshot
![metadata](https://user-images.githubusercontent.com/85381806/157596412-dd2fa159-d130-48bf-8756-7bb67e8fff0e.png)
![error](https://user-images.githubusercontent.com/85381806/157596429-59425c6f-e2b1-4ee0-a835-ba32ac97bc45.png)
s

**Comment by giohappy** [comment]
@ayushman00sri please use the ML or the Gitter channel for requests.
