### ISSUE TITLE
Unexpected exception HTTPConnectionPool

### ISSUE THREAD

**Issue by gabrielbonifaz** [GeoNode/geonode#6185]
## Expected Behavior
Upload a layer or create layer without errors

## Actual Behavior
Client Error: Bad Request
Unexpected exception HTTPConnectionPool(host='170.244.208.202', port=90): Max retries exceeded with url: /geoserver/rest/workspaces.xml (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 110] Connection timed out',))

Aditionaly the console shows the following erros:

Failed to load resource: the server responded with a status of 400 (Bad Request)

DevTools failed to load SourceMap: Could not load content for http://170.244.208.202:90/static/lib/js/underscore.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
![error](https://user-images.githubusercontent.com/43843494/84320946-4cdf5380-ab27-11ea-9847-014d12ed2e79.PNG)

## Steps to Reproduce the Problem

  1. Upload a layer

## Specifications

  - GeoNode version: 3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Geonode
  - Additional details:

**Comment by afabiani** [comment]
This is not a bug, you just need to provide the correct GeoServer configuration.

Please read the configuration carefully

https://docs.geonode.org/en/master/install/basic/index.html

**Comment by gabrielbonifaz** [comment]
It was right... I performed a better configuration for geoserver, the layer is already uploaded in geoserver but I get the following error in geonode

![image](https://user-images.githubusercontent.com/43843494/84439598-5c28d480-abed-11ea-80c2-b83fa8a546ea.png)

**Comment by t-book** [comment]
@gabrielbonifaz still something is wrong with your geoserver settings.

**Comment by gabrielbonifaz** [comment]
I been looking my geoserver settings several times, but I didn't get the error. This is my error log of nginx, something is wrong with the static root archives. The error says that it doesn't appear the files but it does in my archives. I don't know whats is wrong, if you can help me I will appreciate. Additionally, I attached my uwsgi and nginx configuration.   

2020/06/15 15:12:45 [error] 30372#30372: *7 open() "/opt/geonode-master/geonode/static_root/lib/js/underscore.js.map" failed (2: No such file or directory), client: 19$
2020/06/15 15:22:39 [error] 30372#30372: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 190.12.31.162, server: $

![image](https://user-images.githubusercontent.com/43843494/84685005-57fefe80-aeee-11ea-8f91-64ab109113ec.png)

![image](https://user-images.githubusercontent.com/43843494/84684824-12423600-aeee-11ea-8713-ace888bd45bc.png)

**Comment by t-book** [comment]
@gabrielbonifaz Your screenshot showed passwords and secrets that's why I've deleted it. I saw you changed the port to 90 this could be the place where the confusion is happening.

**Comment by gabrielbonifaz** [comment]
Thanks about it, I didn't realize it. Yes, actually, I changed the geonode port to 90 and the geoserver port to 8081, but like I said it I was looking my geoserver configuration and everything seems to be ok. I don't know where the problem could be. Is there something that I will be missing?

**Comment by afabiani** [comment]
@gabrielbonifaz so as stated on the issue you performed manual setup, is that right?

Taking a quick look at your setup and I noticed this

![image](https://user-images.githubusercontent.com/1278021/84747725-ed19fa00-afb7-11ea-828b-6316d0b45e5a.png)

It looks to me that at least you provided a wrong `GEOSERVER_PUBLIC_LOCATION `setting.

Moreover, if you enabled the `EMAIL` be sure GeoNode is able to connect to the SMTP service.

Trying to perform a login into your system, even providing random credentials, it looks like it is waiting for a timeout. This should not happen normally.

**Comment by afabiani** [comment]
@gabrielbonifaz did you considered to use docker setup instead?

Trying to configure GeoNode manually could be tricky if you don't have experience with that.

**Comment by gabrielbonifaz** [comment]
I have the same configuration in a ubuntu virtual machine 18.04 and everything runs fine. That is the reason I didn´t get what could be the problem
