### ISSUE TITLE
Register page on Geonode3 is fetching username from email user instead of form's username field

### ISSUE THREAD

**Issue by tigreped** [GeoNode/geonode#6187]
## Expected Behavior

After clicking the SignUp button on the register page, the username created for the user should reflect provided username form field.

## Actual Behavior

After clicking the SignUp button on the register page, the username created for the user reflects the provided e-mail address's user, instead of the form's username field. For instance, for such a registration:

E-mail: someone@somemail.com
Username: some.fancy.name
Password: ****************
Password (again): ****************

The new user's username would be assigned as 'someone', instead of the expected 'some.fancy.name' .

## Steps to Reproduce the Problem

  1. Access /account/signup/
  2. Provide data
  3. Register
  4. Check created user

## Specifications

  - GeoNode version:  version 3.1.0.dev1591885583
  - Installation method (GeoNode Docker from geonode-project customization):
  - Platform: Linux Ubuntu 20
  - Additional details: the setup is considering e-mail validation setup and working properly.

**Comment by t-book** [comment]
Unsure if I do test correctly but it looks correct:

<img width="1226" alt="Bildschirmfoto 2020-06-12 um 07 25 25" src="https://user-images.githubusercontent.com/20478652/84467995-06503d00-ac7e-11ea-9894-e79c666b2e5f.png">
<img width="887" alt="Bildschirmfoto 2020-06-12 um 07 25 35" src="https://user-images.githubusercontent.com/20478652/84468001-07816a00-ac7e-11ea-99ad-f491130e2549.png">

**Comment by tigreped** [comment]
Maybe it is an email confirmation enabled issue?

Em sex, 12 de jun de 2020 02:26, Toni <notifications@github.com> escreveu:
