### ISSUE TITLE
How to change my Geonode URL

### ISSUE THREAD

**Issue by geotargetxyz** [GeoNode/geonode#6192]
I have rented a server from Digital Ocean and have installed Geonode successfully (version 3.1.0.dev1592580215).

- **NOW** I have bought a domain **XXX.com** (domain name from **GoDaddy**).
- **CAN** I change my default geonode URL from **YYY.YY.Y.YYY** (IP server from **digitalocean**) **TO** XXX.com ?

**IF I can, please explain how I can do that.**

I'm not a Profissional in IT but I have some knowledge. 

- Geonode 3.1.0
- Ubuntu Server 18.04.3
- Ducker (digitalocean).
- Domain (GoDaddy).

**Comment by afabiani** [comment]
https://docs.geonode.org/en/master/install/basic/index.html#migrate-geonode-to-a-new-hostname



Il sab 20 giu 2020, 07:24 GeoTarget <notifications@github.com> ha scritto:

**Comment by t-book** [comment]
@geotargetxyz welcome aboard! We try to keep GitHub issues for bug reporting. For general user questions may I kindly ask you to visit the osgeo user/dev list or our Gitter chat? I'm closing here as the provided link should explain the needed steps.
