### ISSUE TITLE
Hebrew language disappeared from GeoNode

### ISSUE THREAD

**Issue by Guyelka** [GeoNode/geonode#6196]
Hi! I noticed that most languages and translations were moved from the Transifex platform to GitHub recently, but unfortunately Hebrew doesn't seem to have been exported, resulting in Hebrew users having the inability of using their native language anymore. Is there a way to remedy the situation?

**Comment by t-book** [comment]
Hi @Guyelka  I do not think it has ever been added to geonode. 
https://github.com/GeoNode/geonode/tree/master/geonode/locale
There is no way to restore old translations from Transifex.  (if it would be possible it would be outdated across several versions anyway). 
If one steps out to take care of Hebrew translation I'm happy to help with integration.

**Comment by Guyelka** [comment]
I translated it myself to 100% on transifex! It used to exist fully translated. Is there really no way to at least use it partially and I can fix it instead of having to write it all from scratch?

**Comment by t-book** [comment]
@Guyelka The problem with Transifex was that GeoNode had two places where translations happened. At Transifex and directly at Github (po files). As this led to a big mess it was decided to close Transifex some years ago. I just had a look at Transifex if there is some option to restore something. But unfortunately not, there is no other way as starting from scratch.
