### ISSUE TITLE
can't upload new layers / unauthorized when changing geoserver admin password

### ISSUE THREAD

**Issue by reggspr** [GeoNode/geonode#6291]
## Expected Behavior
Layer is upladoaded, boundaries are shown in map

## Actual Behavior
When trying to upload a geojson layer, there's an error "Client Error: Bad Request [object Object]"
can upload shapefiles but no boundaries or layer is shown on map

## Steps to Reproduce the Problem

  1. Data
  2. Layers
  3. Upload Layers
  4. Pick some geojson files
  5. open web browser console
  6. press upload button
  7. there'll be some errors "GET http://localhost:8000/upload/progress net::ERR_CONNECTION_REFUSED" on console
  (if i upload shapefile)
  1. file uploaded
  2. view layer
  3. no boundaries or anything, just a blank map

## Specifications

  - GeoNode version: i'm not sure but i'm following the installation guide for version 2.10
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 18.04.4 LTS (Server), Windows 10 (client)
  - Additional details: i'm trying to upload remotely from my laptop, i tried changing the baseurl on .env, config, etc but some pages sometimes still redirecting to localhost instead the server IP ( and my team said maybe that's why i got this error ), and when i try load shapefile, nothing is shown on map and there's some error on putty when i'm done uploading shapefile
geojson errors:
![errorna 6](https://user-images.githubusercontent.com/34613790/88143319-35fd4800-cc21-11ea-89c2-df606d428fbc.JPG)
shapefile errors:
![errorna 7](https://user-images.githubusercontent.com/34613790/88149193-ebcc9480-cc29-11ea-92b9-151e503a5cb4.JPG)
operational error on puTTy :
![errorna 8](https://user-images.githubusercontent.com/34613790/88149275-0bfc5380-cc2a-11ea-929d-82bdf804cf03.JPG)
Update : I'm encountering new errors, it happens when i change geoserver admin password and then i can't upload anything, it says i'm unauthorized even when i'm using admin account on geonode

**Comment by t-book** [comment]
Update : I'm encountering new errors, it happens when i change geoserver admin password and then i can't upload anything, it says i'm unauthorized even when i'm using admin account on geonode

have you updated your passwort on both sides? Geoserver AND Geonode?

**Comment by reggspr** [comment]
yes, i changed both of them, even tried to change them to default but still got the error

**Comment by johngaldo12** [comment]
Any update on this one? also got the database is locked error.

**Comment by giohappy** [comment]
Can you please test again? I wasn't able to reproduce the error neither on 3.2.x nor on master.
I tests this simple geojson [map.geojson.zip](https://github.com/GeoNode/geonode/files/6405875/map.geojson.zip) and the result is fine:

![image](https://user-images.githubusercontent.com/571129/116706687-2986f680-a9ce-11eb-97e5-da9127c3c678.png)

**Comment by reggspr** [comment]
unfortunately, i'm not involved on the project anymore
the last thing i know is layer can be uploaded, but when i change the password on geoserver, i can't upload anything, it says i'm unauthorized even i change it back to default
