### ISSUE TITLE
Paver Setup > repo2.maven.org Unrechable

### ISSUE THREAD

**Issue by juliermegeotube** [GeoNode/geonode#6294]
I am trying to run paver setup in order to run geonode@2.10.0-release in DevMode, but I am hitting the following error:ConnectionError: HTTPConnectionPool(host='repo2.maven.org', port=80): Max retries exceeded with url: /maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f964520ba90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
I tried to ping repo2.maven.org, but got no response.

## Specifications

  - GeoNode version: Geonode@2.10.0-release
  - Installation method (Manual):
  - Platform: Ubuntu Server 18.04 LTS
  - Additional details:

**Comment by t-book** [comment]
@juliermegeotube is this still an issue?
I checked the link:
https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar
https://www.uptrends.de/tools/uptime
As long as you're not in Bejing or Buenos Aires it should resolve ;))
Maybe something blocking in your network?

**Comment by juliermegeotube** [comment]
@t-book 
My network is responsive on repo1.maven.org, but repo2.maven.org. GeoNode 2.10.X installation is running smoothly under I guess https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar
but GeoNode 2.10.0-release is getting stuck under https://repo2.maven.org/maven2/o

HTTPConnectionPool(host='**repo2.maven.org**', port=80): Max retries exceeded with url: /maven2/org/eclipse/jetty/jetty-runner/9.4.7.v20170914/jetty-runner-9.4.7.v20170914.jar

**Comment by t-book** [comment]
@juliermegeotube now I see it. The devil is in the detail. Indeed the 2.10.0 release uses repo2:
https://github.com/GeoNode/geonode/blob/2.10.0-release/dev_config.yml#L4
which is off.

The latest 2.10 release is 2.10.4 please use this over 2.10.0 
As alternative you can try to fix the linked file locally.

**Comment by juliermegeotube** [comment]
@t-book. deal. I see now.
