### ISSUE TITLE
Admin -  Avatar - Deleted, 

### ISSUE THREAD

**Issue by aabcdario** [GeoNode/geonode#6295]
Greetings friends
Geonode 3.1
when deleting avatar in admin an error appears, automatically logout with the following message.

There was a problem loading this page
Please contact your GeoNode administrator (they may have received an email automatically if they configured it properly). If you are the site administrator, enable debug mode to see the actual error and fix it or file an issue in GeoNode's issue tracker 

I try to log in again, but another message appears:
Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.

Thank you for your attention
Dario Restrepo Duarte

**Comment by aabcdario** [comment]
> Greetings friends
> Geonode 3.1
> when deleting avatar in admin an error appears, automatically logout with the following message.
> 
> There was a problem loading this page
> Please contact your GeoNode administrator (they may have received an email automatically if they configured it properly). If you are the site administrator, enable debug mode to see the actual error and fix it or file an issue in GeoNode's issue tracker
> 
> I try to log in again, but another message appears:
> Forbidden (403)
> CSRF verification failed. Request aborted.
> More information is available with DEBUG=True.
> 
> Thank you for your attention
> Dario Restrepo Duarte

It is already resolved, add other images by editing my profile and remove images with failures

**Comment by t-book** [comment]
@aabcdario 
> It is already resolved

As I understand this is solved. Closing if this still is an issue please reopen.
