### ISSUE TITLE
Modify the admin theme customisation feature to allow for the use of a slide show in the home page

### ISSUE THREAD

**Issue by abulojoshua1** [GeoNode/geonode#6301]
# Modify the admin theme customization feature to allow for the use of a slide show in the home page

## Overview

The Geonode admin theme customization feature can be modified to allow for the use and configuration of either existing jumbotron background or a configurable slide show in home page

### Proposed By

[Abulo John Joshua](https://github.com/abulojoshua1)

### Assigned to Release

This proposal is for GeoNode 3.1.0.dev1595926014.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation
Currently, a Geonode instance theme can be customized in the admin interface with color, logo, and picture options but there does not exist a way to configure a slide show (apart from customizing the home page by adding code to an instance). With the belief that first impressions matter to keep a user interested in page on the internet with multiple options, a slide show will be able to convey more info about a Geonode instance that could be catchy to a user.

## Proposal

Modify the `geonode.themes.models.JumbotronThemeSlide` model to include a slide show and a way to choose between displaying a slide show or the existing Geonode jumbotron background

**Comment by afabiani** [comment]
+1

**Comment by giohappy** [comment]
+1

**Comment by t-book** [comment]
+1
