### ISSUE TITLE
issue again with latest version when i want upload shp

### ISSUE THREAD

**Issue by johnfelipe** [GeoNode/geonode#6306]
Pls review this video: https://drive.google.com/file/d/1kRXAhJPrMpq3R4H1FtvIjVajqYZmX-si/view?usp=drivesdk

here is source of shape: https://geomedellin-m-medellin.opendata.arcgis.com/datasets/4992727f511244f9a31810fcd895f84d_14?geometry=-76.976%2C5.979%2C-74.362%2C6.457

and this is error:

	Client Error: Bad Request
	{'success': False, 'errors': (401, b'
	HTTP Status 401 \xe2\x80\x93 Unauthorized
	Type Status Report

	Message Unauthorized

	Description The request has not been applied because it lacks valid authentication credentials for the target resource.

	Apache Tomcat/8.5.57
	')}

![SNAG-0607](https://user-images.githubusercontent.com/428820/88994776-b91c3f00-d2ae-11ea-9dee-9b0a438d48fd.png)

pls help me to solve this, or wich kind of files is possible upload to geonode
regards

**Comment by federicogodan** [comment]
hi, which version of geonode are you using?

**Comment by johnfelipe** [comment]
Version 3

**Comment by juliermegeotube** [comment]
@johnfelipe Did you include the server IP in ALLOWED_HOSTS?

**Comment by johnfelipe** [comment]
Give me path for change that variable pls

**Comment by federicogodan** [comment]
I think @juliermegeotube refers to ALLOWED_HOSTS in  geonode/settings.py

**Comment by diego-02** [comment]
@johnfelipe Hi, did adding the server IP in ALLOWED_HOSTS work for you? Im currently having the same issue and changed the .env to ALLOWED_HOSTS=['django','<IP>',] and still nothing.

**Comment by t-book** [comment]
@johnfelipe My guess is your geoserver credentials do not match those in your .env file.
Try the following:
1. note your credentials form .env
2. visit the geoserver backend
3. try to login with the credentials from .env
if this does not work maybe the credentials did not update in this case try admin/geoserver

Back in the geoserver gui change the admins password to match with .env

**Comment by diego-02** [comment]
> @johnfelipe My guess is your geoserver credentials do not match those in your .env file.
> Try the following:
> 
> 1. note your credentials form .env
> 2. visit the geoserver backend
> 3. try to login with the credentials from .env
>    if this does not work maybe the credentials did not update in this case try admin/geoserver
> 
> Back in the geoserver gui change the admins password to match with .env

Yesterday after doing some testing I did those exact steps and after changing the updated password of geoserver to the one at the .env file. I was able to upload a layer. Thank you very much.

**Comment by zahirulislamovich** [comment]
@diego-02 @johnfelipe i did processed same things but no success. meanwhile i installed docker 3.1 version the change happened in .env_dev but no success.
