### ISSUE TITLE
Reenable Batch Download, Batch Permissions, Batch Delete and Make Map from Layers to Profile

### ISSUE THREAD

**Issue by jj0hns0n** [GeoNode/geonode#632]
This is all commented out and disabled for now, it would be great if it worked for this release.

**Comment by jj0hns0n** [comment]
@simod how much of this has been added back in now?

**Comment by simod** [comment]
Permissions and make map :)

Il mercoledì 18 novembre 2015, Jeffrey Johnson <notifications@github.com>
ha scritto:

> @simod <https://github.com/simod> how much of this has been added back in
> now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoNode/geonode/issues/632#issuecomment-157856941>.
>


-- 
Simone

**Comment by jj0hns0n** [comment]
ok, I'll leave this open.

**Comment by jj0hns0n** [comment]
@simod some of this was re-implemented right? Lets discuss during the sprint. Moving to 2.7 for now though.

**Comment by simod** [comment]
yes the permissions and make a map. ok chat soon

**Comment by d3netxer** [comment]
wait, has bulk upload been enabled? on http://master.demo.geonode.org I only see a button to 'Create a Map'

**Comment by capooti** [comment]
As far as I remember we never had bulk download so that would be a new feature @dakula009
