### ISSUE TITLE
In home page show only ISO categories currently assigned to some dataset

### ISSUE THREAD

**Issue by abulojoshua1** [GeoNode/geonode#6332]
In home page shows only ISO categories currently assigned to some dataset

## Overview

In the GeoNode home page, ISO Categories displayed for quick filtering of datasets are shown irrespective of if they are being used or not by any dataset. This at times leads to an empty search of click. This can be changed to only show ISO categories currently assigned to a dataset together with a count of the number of datasets (only those a user has access to view) using the ISO format.
![iso](https://user-images.githubusercontent.com/29429135/89394983-69f26600-d715-11ea-868c-4102a85ff300.png)

### Proposed By

[abulo john joshua](https://github.com/abulojoshua1)

### Assigned to Release

This proposal is for GeoNode 3.1.0.dev1596544521.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Displaying ISO formats that are not being used by any dataset will only lead to the filtering of empty datasets in the search when the quick ISo format link is clicked. In addition, it would also be good if the ISO formats contain a stats badge showing the number of datasets using the ISO format

## Proposal

To filter for all ResourceBase model objects with a category that a user has permissions to view, then get a count and other category data needed to display stats (number of datasets using the ISO format) and other data about the category (ISO format)

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

**Comment by afabiani** [comment]
+1
