### ISSUE TITLE
ArcGIS REST MapServer

### ISSUE THREAD

**Issue by Adriana-Martinez** [GeoNode/geonode#6353]
## Expected Behavior
 Add layers using remote service from ArcGIS REST Map Server

## Actual Behavior
 Error: Could not connect to the service at https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer
## Steps to Reproduce the Problem

  1. Add url of  remote service: https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer
  2. Select ArcGIS REST MapServer
  3. Click in Create button
  4. Error: Could not connect to the service at https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
     GeoNode Docker
  - Additional details:
![Presentación1](https://user-images.githubusercontent.com/55162147/89916480-41f37e80-dbbd-11ea-94d4-0be34624e746.jpg)
![qgis](https://user-images.githubusercontent.com/55162147/89916989-de1d8580-dbbd-11ea-8a3f-a6424a435e65.jpg)

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/pull/6355

**Comment by mahdin75** [comment]
I had the same issue, and I installed `gn-arcrest==10.5.1` instead of `gn-arcrest==10`. after restarting Django and Nginx docker containers nothing changed. Does this change solve this issue?

**Comment by malnajdi** [comment]
as some discussion between me and @afabiani i noticed the rest:

trying to import resources from an ArcGIS Web Map Service I got the error code below:
```
Traceback (most recent call last):
  File "/usr/src/geonode/geonode/services/serviceprocessors/arcgis.py", line 140, in get_resources
    return self._parse_layers(self.parsed_service.layers)
  File "/usr/src/geonode/geonode/services/serviceprocessors/arcgis.py", line 149, in _parse_layers
    map_layers.extend(self._parse_layers(lyr.subLayers))
  File "/usr/local/lib/python3.8/site-packages/arcrest/server.py", line 769, in subLayers
    return [self._get_subfolder("../%s/" %
  File "/usr/local/lib/python3.8/site-packages/arcrest/server.py", line 770, in <listcomp>
    layer['parentLayer']['id'],
KeyError: 'parentLayer'
```
This is a sample structure of the received data.
```
"layers": [
  {
   "id": 0,
   "name": "Street_Naming",
   "parentLayerId": -1,
   "defaultVisibility": true,
   "subLayerIds": [
    1
   ],
   "minScale": 0,
   "maxScale": 0
  },
```

**Comment by afabiani** [comment]
@malnajdi thanks, I'll send a patch ASAP for this

**Comment by afabiani** [comment]
@malnajdi @mahdin75 @Adriana-Martinez please try out

`pip install gn-arcrest==10.5.2`

**Comment by malnajdi** [comment]
@afabiani I think this issue can be closed
