### ISSUE TITLE
Error in People Page and Cannot Add New User

### ISSUE THREAD

**Issue by jeffytoms** [GeoNode/geonode#6357]
Greetings everyone!

I hope each one of you are doing well these times.

I am using Geonode version 2.0c1. I know it's an old one but I haven't updated it since the project ended back then. However, it is still running up to this day and it will be used again for another mapping activity. Everything seems to be working fine. I can upload layers and do maps. I can also access the admin panel. But I am really wondering about the error page when I click the People tab. I cannot also add new users for this mapping activity. 

I really need your help on this one.

Thank you and I wish you all the best.

Warm regards,
Jeffy

Error details:

Request Method: | GET
-- | --
http://crisp.norminet.org.ph/people/
1.5.1
VariableDoesNotExist
Failed lookup for key [user] in u'<geonode.search.normalizers.OwnerNormalizer instance at 0x7f01bc094f38>'
/usr/lib/python2.7/dist-packages/django/template/base.py in _resolve_lookup, line 771
/usr/bin/python
2.7.3
['/usr/lib/python2.7',  '/usr/lib/python2.7/plat-linux2',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages/PIL',  '/usr/lib/python2.7/dist-packages/gtk-2.0',  '/usr/lib/pymodules/python2.7',  '/usr/lib/python2.7/dist-packages/ubuntu-sso-client',  '/usr/lib/python2.7/dist-packages/ubuntuone-client',  '/usr/lib/python2.7/dist-packages/ubuntuone-control-panel',  '/usr/lib/python2.7/dist-packages/ubuntuone-couch',  '/usr/lib/python2.7/dist-packages/ubuntuone-installer',  '/usr/lib/python2.7/dist-packages/ubuntuone-storage-protocol']
Wed, 12 Aug 2020 02:57:52 +0800

**Comment by t-book** [comment]
Do you have pending migrations?

**Comment by jeffytoms** [comment]
Hi Toni!

No, I don't have a pending migration.
I find the error quite strange because all the other pages are accessible
and functional.
I can access the admin panel, view all the users, but I cannot add or
modify existing ones.

**Comment by t-book** [comment]
As a quick fix in case you do not need the following feature you could try to comment out this template:

https://github.com/GeoNode/geonode/blob/2.10.x/geonode/templates/relationships/_profile_follow.html

**Comment by jeffytoms** [comment]
Oh I see. So you mean I just have to comment out those 15 lines in the code.
I will try this fix once I connect again to the vpn in the office. Right
now, I'm working remotely.
So I will go to this specific file:
/usr/lib/python2.7/dist-packages/django/template/base.py,
right?

**Comment by t-book** [comment]
Hi,

no /usr/lib/python2.7/dist-packages/django/template/base.py is the wrong file. It's `geonode/templates/relationships/_profile_follow.html`

and yes if it works it's a quick and dirty fix.

**Comment by jeffytoms** [comment]
Hi Toni,

Unfortunately, the quick fix doesn't work. :(

**Comment by t-book** [comment]
same error?

**Comment by jeffytoms** [comment]
Yes, still the same error.
