### ISSUE TITLE
Geonode Add New Vector Layer Error:  java.lang.NoSuchMethodError: org.locationtech.jts.geom.Polygon.getExteriorRing; 

### ISSUE THREAD

**Issue by mahdin75** [GeoNode/geonode#6384]
## Expected Behavior
I installed GeoNode with Docker with this [doc.](https://docs.geonode.org/en/3.0/install/advanced/core/index.html#docker)
Geonode is installed on production mode and every part of application works. 
I want to import a shapefile to GeoNode as an vector layer.

## Actual Behavior
It has an error after geoserver configuration step during adding new vector layers.

`java.lang.NoSuchMethodError: org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LinearRing; org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LinearRing;
`
In the database, shapefile data, is stored in the geonode_data database ,and in the Geoserver,layer is publish from PostGIS store, But the in Geoserver I can't see the layer, and I also face with above error.

## Steps to Reproduce the Problem

  1. GeoNode Installed completely.
  2. Raster Layer Upload worked.
  3. Vector Layer Upload Face with an error.

## Specifications

  - GeoNode version:  3.1.0.dev1598252669
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu Server 18.04 LTS
  - Additional details: I didn't changed any configuration ,and followed steps that were in [this documentation.](https://docs.geonode.org/en/3.0/install/advanced/core/index.html#docker)

**Comment by mahdin75** [comment]
This is Screenshot Of the Error:
![Untitled](https://user-images.githubusercontent.com/35072627/91170963-ec57bf80-e6ee-11ea-9730-4bb15940f4b0.png)

**Comment by mahdin75** [comment]
I don't know why this error occurs, and I need a method to resolve this error. 
It seems that some libraries are missing in geoserver4geonode docker container in WEB-INF/libs.

**Comment by pjduplooy1** [comment]
I am also experiencing this issue, but using the latest Docker Desktop for Windows

**Comment by mahdin75** [comment]
I installed version 3.0 from released page and error resolved but the current version has error yet.

**Comment by mahdin75** [comment]
Updating geoserver in geoserver4geonode container solved this issue but some other functionality don't work truely.

**Comment by pjduplooy1** [comment]
Hi mahdin75.  

May I ask how you updated geoserver in geoserver4geonode?

**Comment by mahdin75** [comment]
I followed this [link](https://docs.geonode.org/en/3.0/install/advanced/core/index.html#access-the-geoserver4geonode-docker-container-to-update-the-geoserver-version).

**Comment by pjduplooy1** [comment]
Can I use master branch, or do I have to use 3.x stable?

And thanks for the link, I have been through Geonode docs such a lot, and everytime I discover something else

**Comment by mahdin75** [comment]
@pjduplooy1 I'm not sure. I installed Geonode from the master, but there are some errors like something I mentioned in this issue, then I installed it from the release page, version 3.0, and there are some other errors. 
@t-book I installed Geonode from the master branch again, on another host, but I get this issue again.

**Comment by pieterprovoost** [comment]
Same issue here when trying to add an save a polygon feature. Running master with Docker and only a minor change in `docker-compose.override.localhost.yml` to enable Create Layer (`CREATE_LAYER=True`).

```
git clone https://github.com/GeoNode/geonode.git
cd geonode
docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build
```

![Screenshot 2020-09-14 at 14 52 01](https://user-images.githubusercontent.com/490041/93089704-fcceda80-f69b-11ea-9c53-31629a2e3cfe.png)

**Comment by t-book** [comment]
I've tested it by uploading a polygon shape which worked. But from the comment of @pieterprovoost it's happening when adding new geometries? @afabiani have you heard about problems with latest geoserver regarding getExteriorRing()?

**Comment by pjduplooy1** [comment]
t-book.

I managed to solve this by downgrading to a lower point number release.  I think it was 2.17.1

**Comment by t-book** [comment]
@pieterprovoost This sounds like a regression with geoserver. I will try to test it tomorrow.

**Comment by mahdin75** [comment]
@t-book I solved this by downgrading to [3.0 release
](https://github.com/GeoNode/geonode/releases/tag/3.0).

**Comment by pjduplooy1** [comment]
Quick question.  Does this affect a Geonode Core install from scratch (No docker)?

**Comment by t-book** [comment]
I cannot reproduce this behaviour @ docker  Version 3.1.0.dev1599558584 with GS 2.17.2
Uploaded a shape file. 
Added Polygon geometry via mapstore.

Please provide more info how to reproduce the problem

**Comment by pjduplooy1** [comment]
Hi t-book

What I did was take a polygon and upload it.  While uploading the polygon, the error as stated by OP appears.  

I used the following (just extract and use) :

https://drive.google.com/file/d/13XGCghe7jUkgd9ii7z4lZCdOJOiYN3mF/view?usp=sharing

**Comment by t-book** [comment]
Cannot reproduce any problem with -docker  dev 3.1 and paver stable 

https://master.demo.geonode.org/maps/new?layer=geonode:nature_reserve_polygon&view=True

**Comment by t-book** [comment]
To be clear. I can imagine there might be something happening with: https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Polygon.html
If I'm right the package is used by gs but I'm not into java at all ;)
However it's hard to help as long this is not reproducible.

**Comment by pjduplooy1** [comment]
The strangest thing happened.

After starting the containers normally (without the build flag), I decided to upgrade Geoserver back to 2.17.2.  Restarted the geoserver4geonode container.

Now it works as expected.  Dont know why.

**Comment by pieterprovoost** [comment]
These are my steps, let me know if you would like me to create a separate issue:

- `git clone git@github.com:GeoNode/geonode.git`
- add `CREATE_LAYER=True` to the Django environment variables in `docker-compose.override.localhost.yml`
- `docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build`
- navigate to http://localhost and sign in as admin
- go to Data > Create Layer

<img width="1517" alt="Screenshot 2020-09-15 at 23 12 52" src="https://user-images.githubusercontent.com/490041/93265530-05f99d80-f7a9-11ea-8b30-a49a06007aeb.png">

- navigate to Editing Tools > Edit data
- click Edit mode > Add New feature > Draw feature
- draw polygon

<img width="1517" alt="Screenshot 2020-09-15 at 23 14 37" src="https://user-images.githubusercontent.com/490041/93265779-638dea00-f7a9-11ea-8c7a-99da9a4898e8.png">

- click Save changes

<img width="1517" alt="Screenshot 2020-09-15 at 23 15 25" src="https://user-images.githubusercontent.com/490041/93265827-756f8d00-f7a9-11ea-812a-220e6f9aa555.png">

**Comment by t-book** [comment]
thanks a lot @pieterprovoost 
Your steps worked online: https://master.demo.geonode.org/layers/geonode_master_data:geonode:test_polygon#
(3.1 dev, gs 2.17.2)
I will start a stack @ localhost and see if this ends in your error.

**Comment by itecsurveys** [comment]
Same Issue with me when uploading polygon shp.
I could upload sample point shp but not showing data in "View Layer".
Getting below error for point layer With "Layer Preview " in Geoserver.
![Screenshot from 2020-09-19 00-16-57](https://user-images.githubusercontent.com/70905682/93634057-959f8600-fa0d-11ea-84f1-e22dee689c83.png)

**Comment by t-book** [comment]
Hi, still with my tests I cannot reproduce. My guess is something has changed with geotools. But this is vague. Could somebody test with geoserver 2.16.2 and 2.17.1. ?

**Comment by pjduplooy1** [comment]
Hi t-book.

Just a comment on this.  I tested this with 2.16.2, and it works after I restarted the geoserver4geonode container.  After doing that, I co back to 2.17.2, and restart geoserver4geonode again, and it keeps on working.

**Comment by t-book** [comment]
buff thanks @pieterprovoost really strange thing!

**Comment by itecsurveys** [comment]
I tested this with 2.16.2 Works fine.

**Comment by t-book** [comment]
@pieterprovoost @itecsurveys Can one of you kindly post the payload when drawing a new polygon? In dev tools this should look something like:

<img width="1235" alt="Bildschirmfoto 2020-09-20 um 20 26 06" src="https://user-images.githubusercontent.com/20478652/93718958-d15a5d00-fb7f-11ea-8997-cc1bcc629d7f.png">

**Comment by pieterprovoost** [comment]
@t-book 

```bash
curl 'http://localhost/geoserver/ows?access_token=Q8QzFQQPA1sPGyCWYvUA3UhdvRvm9X' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'X-CSRFToken: 68SU5YRxpegOyaMteEY8ipJ3cTsJ30fResV7UjPFaweagxIZBMqrmdOAgY1LFrt8' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36' \
  -H 'Content-Type: application/xml' \
  -H 'Origin: http://localhost' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost/maps/new?layer=geonode:test&storeType=dataStore' \
  -H 'Accept-Language: en-US,en;q=0.9,nl-BE;q=0.8,nl;q=0.7,fr;q=0.6,de;q=0.5,it;q=0.4,la;q=0.3,es;q=0.2,lb;q=0.1,eu;q=0.1' \
  -H 'Cookie: GS_FLOW_CONTROL=GS_CFLOW_-2c631172:1748ca94fc3:-7ff3; JSESSIONID=31287C4CCD54BD801611F3ABAFD7195C; _ga=GA1.1.1334901594.1599814800; io=R1MNEfn7wbyFPmwmAAAA; csrftoken=68SU5YRxpegOyaMteEY8ipJ3cTsJ30fResV7UjPFaweagxIZBMqrmdOAgY1LFrt8; sessionid=cxv51lbnq0r59to42yead9i1rqmjjc3d' \
  --data-binary '<wfs:Transaction service="WFS" version="1.1.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wfs" xmlns:geonode="http://www.geonode.org/"><wfs:Insert><geonode:test><geonode:the_geom><gml:Polygon srsName="EPSG:4326"><gml:exterior><gml:LinearRing><gml:posList>2.2055053710937504 54.493972369468324 -24.6038818359375 36.77629248118682 19.95941162109367 35.07271701786369 2.2055053710937504 54.493972369468324</gml:posList></gml:LinearRing></gml:exterior></gml:Polygon></geonode:the_geom></geonode:test></wfs:Insert></wfs:Transaction>' \
  --compressed
```

```xml
<?xml version="1.0" encoding="UTF-8"?><ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0.0" xsi:schemaLocation="http://www.opengis.net/ows http://localhost:80/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd?access_token=Q8QzFQQPA1sPGyCWYvUA3UhdvRvm9X">
<ows:Exception exceptionCode="NoApplicableCode">
<ows:ExceptionText>java.lang.NoSuchMethodError: org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LinearRing;
org.locationtech.jts.geom.Polygon.getExteriorRing()Lorg/locationtech/jts/geom/LinearRing;</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>
```

**Comment by t-book** [comment]
great thanks!

**Comment by gannebamm** [comment]
whats the status here?

**Comment by t-book** [comment]
@gannebamm Might be a regression with geoserver 2.17.2 but I cannot reproduce it.

**Comment by gannebamm** [comment]
We will see if we start our testing marathon accoring to the google sheet. Add new layer is a row in there iirc

**Comment by afabiani** [comment]
This depends on an old mapfish lib JAR present on GeoServer images.

Both 2.7.1 and 2.7.2 have been refreshed and the docker images rebuilt. This error disappear by updating GeoServer again.
