### ISSUE TITLE
db4geonode role "-d" does not exist

### ISSUE THREAD

**Issue by tayyabsayyad** [GeoNode/geonode#6385]
I have added Celery configuration in the docker-compose.override.localhost.yml as shown below 

celery:
    build: .
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=localhost
      - GEONODE_LB_PORT=80
      - SITEURL=http://localhost/
      - ALLOWED_HOSTS=['localhost','*' ]
      - GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/

After building the geonode I am getting  following errors 

db4geonode       | 2020-08-26 05:14:48.904 UTC [64] FATAL:  role "-d" does not exist
db4geonode       | 2020-08-26 05:14:49.988 UTC [65] FATAL:  role "-d" does not exist
db4geonode       | 2020-08-26 05:14:51.161 UTC [66] FATAL:  role "-d" does not exist
db4geonode       | 2020-08-26 05:14:52.328 UTC [67] FATAL:  role "-d" does not exist
db4geonode       | 2020-08-26 05:14:53.410 UTC [68] FATAL:  role "-d" does not exist
db4geonode       | 2020-08-26 05:14:54.518 UTC [69] FATAL:  role "-d" does not exist

**Comment by t-book** [comment]
Maybe it helps to have a look how it is done with geonode project: https://github.com/GeoNode/geonode-project/blob/master/docker-compose.yml#L96-L113

**Comment by giohappy** [comment]
I invite you to move this question to the [geonode-user](https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users) mailing list. Thanks
