### ISSUE TITLE
Thesaurus keywords cannot be saved

### ISSUE THREAD

**Issue by sharon-tickell** [GeoNode/geonode#6387]
## Expected Behavior
With a thesaurus configured (we have the Inspire one), we should be able to select keywords from the thesaurus when editing metadata, update/save the metadata record and see the selected keywords in the layer/document/map information.

## Actual Behavior
The selected thesaurus keywords are not saved, though other metadata changes made at the same time are.

The web server log file contains an error message like so:

```
[Fri Aug 28 02:22:25.030984 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260] ERROR 2020-08-28 02:22:25,030 views 860658 140138758366976 Traceback (most recent call last):
[Fri Aug 28 02:22:25.031122 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260]   File "/srv/ocean_observatory_geonode-3.0/venv/lib/python3.8/site-packages/geonode/layers/views.py", line 1095, in layer_metadata
[Fri Aug 28 02:22:25.031130 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260]     layer.tkeywords = tkeywords_data
[Fri Aug 28 02:22:25.031135 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260]   File "/srv/ocean_observatory_geonode-3.0/venv/lib/python3.8/site-packages/django/db/models/fields/related_descriptors.py", line 536, in __set__
[Fri Aug 28 02:22:25.031143 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260]     raise TypeError(
[Fri Aug 28 02:22:25.031151 2020] [wsgi:error] [pid 860658:tid 140138758366976] [remote 152.83.147.60:65260] TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use tkeywords.set() instead.
```

## Steps to Reproduce the Problem

  1.  Have a thesaurus configured in your geonode as per the setup instructions.
  2. For an existing layer, select 'Editing tools' > 'wizard' 
  3. Select one or more keywords from the thesaurus
  4. Click the 'update' button.

## Specifications

  - GeoNode version:  3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):  manual
  - Platform: Ubuntu 20.04, Python 3.8
  - Additional details:

**Comment by sharon-tickell** [comment]
The attached git patch resolves this issue against the 3.0 tag.  (and also a more trivial issue with incorrect comma placement for the saved thesaurus keywords when viewed later):

[tkeywords_error.patch.txt](https://github.com/GeoNode/geonode/files/5137740/tkeywords_error.patch.txt)


A quick check suggests that the issue still exists in the current master branch:   I can make a pull request if you want one, but the fix is pretty simple:  it just needs to be the same simple change in three places.

**Comment by t-book** [comment]
@sharon-tickell Thanks! If you're planning further contributions please sign the CLA if not done yet and provide a PR. Otherwise I can assist and  open a PR with your fix that we can review.

**Comment by afabiani** [comment]
@t-book I directly applied the patch since it was straight

**Comment by t-book** [comment]
thanks @afabiani  !
