### ISSUE TITLE
Error when installing core GeoNode into virtual environment

### ISSUE THREAD

**Issue by mradamcox** [GeoNode/geonode#6388]
## Expected Behavior
`pip install -e . --upgrade` should complete without error.

## Actual Behavior
I've been following along with [this documentation](https://docs.geonode.org/en/master/install/advanced/core/index.html#geonode-installation) to get GeoNode installed locally on Ubuntu 20.04. I have all of the apt packages installed, included `python3-dev` and `python3.8-dev` just to be safe.

I first encountered the issue using virtualenv, but also tried with virtualenvwrapper and found the same error. 

Running `pip install -r requirements.txt` works fine. However, when I run `pip install -e . --upgrade` from within the cloned repo I get an error containing these lines:

    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_requires'
    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'include_package_data'
    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
    /usr/lib/python3.8/distutils/dist.py:274: UserWarning: Unknown distribution option: 'zip_safe'

These options are being passed to the `setup()` function that is called within setup.py. Some research showed that `distutils` doesn't support these options, but `setuptools` does. So in setup.py I tried changing

    from distutils.core import setup

to

    from setuptools import setup

(which I had seen recommended), but this resulted in a different error:

    distutils.errors.DistutilsClassError: command class <class 'setuptools.command.egg_info.egg_info'> must subclass Command

I stuck with this and tried different versions of setuptools, 44, 46, and 50 (geonode currently has 49.2.0 pinned) but no change.

## Steps to Reproduce the Problem

1. Ubuntu 20.04: Install all system-wide apt dependencies described in docs
2. Also install `virtualenv` and `python3.8-dev`
3. virtualenv env-geonode && source env-geonode/bin/activate
4. clone and enter this repo
5. pip install -r requirements.txt --no-cache --no-cache-dir --upgrade
6. pip install -e . --upgrade

## Specifications

  - GeoNode version: 3.0 (master branch)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 20.04
  - Additional details:

**Comment by mradamcox** [comment]
After wading through some pypi discussion about distutils and setuptools, I eventually got the installation to complete without changing `setup.py` at all. It has to do with distutils version inheritance, and the important thing is telling pip to use the standard distutils library and not the local one:

    env SETUPTOOLS_USE_DISTUTILS=stdlib pip install -e . --upgrade

I am using python 3.8.2, pip 20.1.1, and setuptools 49.2.0 (current default for GeoNode).

I suppose this ticket could just serve as a note for the documentation, but will wait for the input of others before doing anything with it.

**Comment by afabiani** [comment]
@mradamcox thanks for having a look at this.

Imho the best solution would be to update the setup.py and make it compliant with local distutils of setuptools. I'll propose a PR for that soon.
