### ISSUE TITLE
Layer is not replaced

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#6447]
## Expected Behavior

Good afternoon,
I have encountered an error when replacing a layer. I'm testing with the geonode demo 
https://master.demo.geonode.org

Any idea about it

## Steps to Reproduce the Problem

  1. I go up a layer 
  2.  I'm trying to replace with an updated layer
  3. No error but the same initial layer is maintained.

## Specifications

  - GeoNode version: 3.1.0.dev1600242945
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): I have tried in geonode_project and manual
  - Platform: Ubuntu 18.05
  - Additional details:

**Comment by t-book** [comment]
I do not know if this helps: the upload sessions is successfully written but the instance does not have `overwrite` set and hence defaults to `False`:
https://github.com/GeoNode/geonode/blob/e4f4b277554068bbcc9ae11c6ada7e96d7ad5cb9/geonode/geoserver/signals.py#L129

So to me it looks that's why the signal is not updating the resource?

**Comment by t-book** [comment]
I do not fully grasp on how things are connected with layer replacement.
However it looks like

https://github.com/GeoNode/geonode/blob/e4f4b277554068bbcc9ae11c6ada7e96d7ad5cb9/geonode/layers/utils.py#L725

is not saved to the later object? It starts working again when we save the layer

        # Pass the parameter overwrite to tell whether the
        # geoserver_post_save_signal should upload the new file or not
        layer.overwrite = overwrite
        …
        layer.save()

**Comment by afabiani** [comment]
So, while investigating on this one I discovered a bunch of non trivial issues on the upload methods not correctly updating the GeoServer resources.

I'm fixing them through this one https://github.com/GeoNode/geonode/pull/6566

As soon as this is ready, I'll update master demo too in order to allow you making some more tests

**Comment by afabiani** [comment]
@dpadron @t-book please give it a try on https://master.demo.geonode.org

**Comment by t-book** [comment]
@afabiani Thanks a lot for your effort the last days working on this issue!

Polygon replacement worked nicely for me.
With a simple points layer I do get this error message:

---

<img width="820" alt="Bildschirmfoto 2020-10-26 um 20 42 50" src="https://user-images.githubusercontent.com/20478652/97223008-772c6780-17cf-11eb-8062-a541afd38a4b.png">

---

https://master.demo.geonode.org/layers/geonode:replace_test0/replace

For testing just some new points where created:

<img width="287" alt="Bildschirmfoto 2020-10-26 um 21 13 54" src="https://user-images.githubusercontent.com/20478652/97223940-be672800-17d0-11eb-88af-19ce43d1b381.png">
 
Let me know if I can help you somehow.

---

Data: [r-points.zip](https://github.com/GeoNode/geonode/files/5441303/r-points.zip)

---

**Comment by afabiani** [comment]
@t-book the shapefile must have the same name of the vector layer, in your example **replace_test0**

**Comment by t-book** [comment]
you're right @afabiani sorry my bad. mixed the testfiles when zipp'ing. The correct named files succeed on upload but  do break the layer: https://master.demo.geonode.org/layers/geonode:replace_test0
(already cleared gwc, and attributes)

[Archiv.zip](https://github.com/GeoNode/geonode/files/5441652/Archiv.zip)

**Comment by afabiani** [comment]
uhm, no good!

**Comment by t-book** [comment]
I will do another point test … (to be sure it's not the data)

**Comment by t-book** [comment]
:/ same here: https://master.demo.geonode.org/layers/geonode:t2

[t2.zip](https://github.com/GeoNode/geonode/files/5441756/t2.zip)
(zip contains both original and updated shape)

**Comment by afabiani** [comment]
That's weird, it seems to be working locally. Wondering if maybe master demo geoserver is a bit messy and this might cause some issues. Will keep testing a bit more.

**Comment by afabiani** [comment]
So, as far as I understood it is not a problem of replacing the data. Somehow it is getting the last available SLD and applies it to the layer. So, in the end the layer results to be broken because of a wrong Style applied.

Still investigating...

**Comment by t-book** [comment]
Buff! This makes sense as also getLegend request is failing.
The devil is in the detail …

**Comment by t-book** [comment]
<img width="384" alt="Bildschirmfoto 2020-10-27 um 17 39 54" src="https://user-images.githubusercontent.com/20478652/97333162-87018580-187b-11eb-85b8-d4f3384b199f.png">

@afabiani yeah!

**Comment by afabiani** [comment]
@t-book it was not easy but I finally found the issue

Fix [here](https://github.com/GeoNode/geonode/commit/d822e30ab934298c23829d027d2de93e2a3fd834)

Depolying on https://master.demo.geonode.org/

**Comment by t-book** [comment]
@afabiani Ufz! This definitely doesn't look easy. The better you've found it!
I can confirm it is working now! https://master.demo.geonode.org/layers/geonode:t20
Thanks!
