### ISSUE TITLE
WonError 126

### ISSUE THREAD

**Issue by johngaldo12** [GeoNode/geonode#6448]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

please help me solve this error :(
![IMG_20200919_155232](https://user-images.githubusercontent.com/71352636/93662795-50bf3200-fa95-11ea-9dfc-524864f07797.jpg)

**Describe alternatives you've considered**

**Additional context**

**Comment by t-book** [comment]
@johngaldo12 Please follw the github template. Further github issues should be used for bugs. I kindly ask you to look for help at the dev and or user list.

**Comment by johngaldo12** [comment]
okay sorry
