### ISSUE TITLE
templating variable is not replaced while creating a new project

### ISSUE THREAD

**Issue by malnajdi** [GeoNode/geonode#6466]
## Expected Behavior
I should get a proper values in the file located at `docker/geoserver/datasource-ovr.properties`

## Actual Behavior
I am getting {{ project_name }}_data in `docker/geoserver/datasource-ovr.properties`

## Steps to Reproduce the Problem

  1. Follow the documentation on how to install and generate your own project based on the exiting template.
  2. Once you generate a new project navigate to `docker/geoserver/datasource-ovr.properties`
  3. See if the file has {{project_name}}

## Specifications

  - GeoNode version: latest
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Debian 10

**Comment by t-book** [comment]
@malnajdi I'm answering here after reading again your post at gitter.
This is the command you have used:
`django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample -n monitoring-cron -n Dockerfile my_geonode`

This is the command the geonode project README names

`django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample,properties -n monitoring-cron -n Dockerfile my_geonode`

You're command is missing , properties. Closing here. Please reopen if you think this is a bug.

**Comment by malnajdi** [comment]
For anyone having the same issue
#check:https://github.com/GeoNode/documentation/issues/53
