### ISSUE TITLE
Unable to load thesaurus: no such table

### ISSUE THREAD

**Issue by pieterprovoost** [GeoNode/geonode#6467]
## Expected Behavior

I'm following the guide at https://docs.geonode.org/en/master/admin/thesaurus/index.html to load the INSPIRE theme thesaurus.

## Actual Behavior

`load_thesaurus` fails with:

```
root@804a4b52bb48:/usr/src/app# python manage.py load_thesaurus --file inspire-theme.rdf --name inspire_themes
/usr/src/app/geonode/base/management/commands/load_thesaurus.py:90: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if not scheme:
Thesaurus "GEMET - INSPIRE themes, version 1.0" issued on 2018-05-23T10:25:56
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: base_thesaurus
```

## Steps to Reproduce the Problem

  1. `git clone https://github.com/GeoNode/geonode.git`
  2. `docker-compose -f docker-compose.async.yml -f docker-compose.development.yml up`
  3. `docker exec -it django4geonode /bin/bash`
  4. `wget -O inspire-theme.rdf https://raw.githubusercontent.com/geonetwork/core-geonetwork/master/web/src/test/resources/thesaurus/external/thesauri/theme/httpinspireeceuropaeutheme-theme.rdf`
  5. `python manage.py load_thesaurus --file inspire-theme.rdf --name inspire_themes`

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: macOS 10.15.6

**Comment by t-book** [comment]
@pieterprovoost I think what is happening is as following:

You're running your containers with development.yml which set's django dev server over a production setup. Dev Server by default is using sqlite as backend. But the migrations done by invoke in entrypoint.sh are run against the postgis database. You can easily check by looking at the postgis container and it's tables:

`
docker exec -i db4geonode psql -d geonode -U postgres -c "\dt"
…  public | base_thesaurus                                                | table | geonode
`

If you check within your django container (which is using sqlite from what shell tells us) you can see that  migrations have run:

```
./manage.py showmigrations
account
 [ ] 0001_initial
 [ ] 0002_email_max_length
actstream
…
```

after you run `./manage.py migrate` your command 

```
python manage.py load_thesaurus --file inspire-theme.rdf --name inspire_themes
```
succeeds.

**Comment by pieterprovoost** [comment]
Thanks @t-book, `manage.py migrate` seems to do the trick.
