### ISSUE TITLE
Broken diacritics in Geoserver style when uploaded a zipped layer including a sld with diacritical characters

### ISSUE THREAD

**Issue by obersupermega** [GeoNode/geonode#6509]
## Expected Behavior
When a layer package consist of shp + sld (which include diacritic characters (accents e.g. é)), the generated Geoserver legend image should have the correctly characters.
[diacritics_demo.zip](https://github.com/GeoNode/geonode/files/5346122/diacritics_demo.zip)

## Actual Behavior
Instead of the diacritics:
![image](https://user-images.githubusercontent.com/47182599/95421471-c7857780-093d-11eb-90e5-b7bb7286ad65.png)

## Steps to Reproduce the Problem

  1. Go to layers list
  2. Upload the demo zip (include shp + sld)
  3. See newly uploaded layer with broken diacritics in legend (éxtra)

## Specifications

  - GeoNode version: 3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): SPCGeoNode Docker
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by gannebamm** [comment]
If you upload a zipped layer it is still broken. If you upload the SLD seperatley it works.

**Comment by t-book** [comment]
@gannebamm Any chance you could kindly test this fix?

Change: https://github.com/GeoNode/geonode/blob/bf01302180c7997db5ddf7b200f1966963dae681/geonode/upload/upload.py#L904

to 

`sld = open(sld_file[0], "rb").read()`

**Comment by afabiani** [comment]
@t-book I'll apply to master demo, just a moment

**Comment by t-book** [comment]
thanks @afabiani !

**Comment by afabiani** [comment]
@t-book @gannebamm the fix has been temporary applied to master

**Comment by t-book** [comment]
@afabiani https://master.demo.geonode.org/layers/upload this is from zip an working. I will add the fix for zip as well on master just a moment.
