### ISSUE TITLE
No module named 'geonode.local_settings'

### ISSUE THREAD

**Issue by villa101101** [GeoNode/geonode#6518]
## Expected Behavior
Module should be found and commands in the local_settings.py file should be executed

## Actual Behavior
The module is not found 

## Steps to Reproduce the Problem

  1. workon geonode
  2. cd /opt/geonode
  3. cp geonode/local_settings.py.geoserver.sample geonode/local_settings.py
  4. DJANGO_SETTINGS_MODULE=geonode.local_settings paver reset
      DJANGO_SETTINGS_MODULE=geonode.local_settings paver setup
      DJANGO_SETTINGS_MODULE=geonode.local_settings paver sync
      DJANGO_SETTINGS_MODULE=geonode.local_settings python manage.py collectstatic --noinput
  5. sudo vim /etc/uwsgi/apps-enabled/geonode.ini
  6. :%s/geonode.settings/geonode.local_settings/g
      :wq
  7. sudo PYTHONWARNINGS=ignore VIRTUAL_ENV=$VIRTUAL_ENV DJANGO_SETTINGS_MODULE=geonode.local_settings GEONODE_ETC=/opt/geonode GEOSERVER_DATA_DIR=/opt/data/geoserver_data TOMCAT_SERVICE="service tomcat" APACHE_SERVICE="service nginx" geonode_updateip -p localhost

## Specifications

  - GeoNode version: 3.0.0.
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):manual from the repo
  - Platform: Ubuntu 18.04 (LTS) x64
  - Additional details:
the file path opt/geonode/geonode:
<img width="1338" alt="Screenshot 2020-10-09 at 3 34 37 PM" src="https://user-images.githubusercontent.com/34188824/95629228-21bd3000-0a45-11eb-9d21-d98519d3ce99.png">

so the file is present but it is saying the module is not found when I ran it in the directory opt/geonode

**Comment by villa101101** [comment]
@afabiani

**Comment by afabiani** [comment]
There's an update of the documentation pending here https://github.com/GeoNode/documentation/pull/64

Could you probably try again following that one?

**Comment by villa101101** [comment]
After doing a fresh installation with the updated documentation I have ran into a new error. Error is shown below.
<img width="1095" alt="Screenshot 2020-10-16 at 11 28 26 AM" src="https://user-images.githubusercontent.com/34188824/96284226-e968a500-0fa2-11eb-90b9-d97c7a8c8045.png">

That error occurred when I ran the command " DJANGO_SETTINGS_MODULE=geonode.local_settings paver sync"

**Comment by villa101101** [comment]
Original issue has been resolved with the latest changes to the documentation.

The issue with the superuser was solved by giving the user "geonode" superuser privilege.
