### ISSUE TITLE
update jquery to 3.5.1

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#6519]
We should update jquery to 3.5.0 or patch htmlPrefilter()

**Comment by afabiani** [comment]
Hi did actually some tests using this branch, and it works seamlessly

https://github.com/GeoNode/geonode/commit/5220754d71ab20148eeda6c129e99007c51a3f4d

**Comment by afabiani** [comment]
Live version available here

https://dev.geonode.geo-solutions.it/

**Comment by t-book** [comment]
Hi, @afabiani I just did a local test with paver and a jquery 3.5.1 build. please ignore the console error I've sent you earlier this day at groups view (`Possibly unhandled rejection: No element has been found!`). It's also happening with older jquery and might happen because of some test data (don't know yet). It's always hard to oversee if updates of frontend libs break something or not but from what it looks it's I think it's safe to update. By the way, DEBUG_STATIC=True gives several 404, and the layer list is broken. I will try to find some time to look at it.
