### ISSUE TITLE
Error when using "python manage.py backup ..." and "python managy.py restore" in combination with postgres (foreign key constraint)

### ISSUE THREAD

**Issue by jannefleischer** [GeoNode/geonode#6525]
## Expected Behavior
restore a backup from "python manage.py backup ..."

## Actual Behavior
Errors on restore because layers rely on spcific services that are not yet restored.

From gitter:

> Once again I have an issue. This time I am testing the backup-restore function of GeoNode. I do a backup within a geonode-project based docker-environment, moving the backup-files to a the same environment on another server and restoring the backup-zip there from within the running (and newly created, empty) docker environment. In gerneral I think this is the way it is supposed to work.
> Sadly, I am getting an traceback while restoring. This is the log: https://gist.github.com/jannefleischer/01f7a8d4af1bda3b2988e2b96a6825ee
> I am guessing the order of the restore is wrong. When processing layers.json the seem to be a link to services.json which hasn't been processed at that time, so a forein key constraint won't work.

## Steps to Reproduce the Problem

  1. no clue.
  2. But: There is a PR that fixes it, at east for me:  #6517 

## Specifications

  - GeoNode version: 3.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 18.04 to 20.04
  - Additional details:

**Comment by gannebamm** [comment]
@jannefleischer could you please check if the error is mitigated by using  #6517 and if so close this issue?
