### ISSUE TITLE
Installation Issue/Public IP/Domain Name

### ISSUE THREAD

**Issue by rtpsr** [GeoNode/geonode#6533]
Hi,

I am trying to install GeoNode (3.x) on Ubuntu 18.04 using the instructions provided at 
https://docs.geonode.org/en/master/install/basic/index.html. I think the installation went mostly ok, but I cannot verify it fully.

1) I could not make it work on public IP or a servername. curl on http://localhost seems to be working. 
2) The docker ps command shows geoserver data container has exited.
![gn-ps](https://user-images.githubusercontent.com/43997841/96310042-898af200-0fd4-11eb-8c12-785ea9c188aa.png)
3) Lets encrypt certificate seems to be pointing to localhost. Getting invalid certificate on https endpoint.

Please let me know how to resolve these issues.

Thank you!

**Comment by t-book** [comment]
hi @rtpsr I do take for granted you have followed these steps: https://docs.geonode.org/en/master/install/basic/index.html#second-step-deploy-geonode-on-a-production-server-e-g-https-my-geonode-geonode-org to go into production, right?

What do you see when you visit the URL which should be used for pubic? Any error like a 502. Besides can you check if you do spot some error when running:

`docker-compose up -d; tail -f invoke.log
`

or much more verbose

`docker-compose up -d; docker-compose logs -f `

**Comment by rtpsr** [comment]
Hi @t-book,

Thanks for your response. I just need an public IP based url first, so I reverted back to original .env (with localhost urls) file to isolate the issue. There is an issue with lets encrypt, so I commented out that part in docker-compose. When I run `docker-compose up -d; docker-compose logs -f ` there is some timeout happening with rabbitmq. Please see attached error.
![rabbitmq-error](https://user-images.githubusercontent.com/43997841/96387853-2f746300-1173-11eb-9cf9-715e03fe81ee.png)

Please let me know how to resolve this. Thanks!

**Comment by t-book** [comment]
Hi @rtpsr you cannot have LE certs for IPs from what I know. I would suggest to leave the compose file untouched and disable LE by it's env var: https://github.com/GeoNode/geonode-project/blob/master/.env#L93
Further restarting containers might not be an uncommon behavior. the startup takes some time. if you still do think something goes wrong start with checking invoke.log

**Comment by rtpsr** [comment]
Hi @t-book, 
Thanks again. I disabled LE at the moment. I got the public IP part "partly working". 
1) Geoserver works on http://publicip/geoserver
2) Geonode on http://publicip is getting "502 Bad Gateway" error from nginx. 

Tail from invoke is giving me this error.  A slightly detailed log is attached as well.
`django.db.utils.IntegrityError: Problem installing fixture '/tmp/default_monitoring_apps_docker.json': Could not load monitoring.Service(pk=3): duplicate key value violates unique constraint "monitoring_service_name_key"
DETAIL:  Key (name)=(geoserver-hostgeoserver) already exists.
[tail_log.txt](https://github.com/GeoNode/geonode/files/5403228/tail_log.txt)

ERROR installing monitoring fixture: Encountered a bad command exit code!
Command: 'django-admin.py loaddata /tmp/default_monitoring_apps_docker.json --settings=my_geonode.settings'`

Thanks!

**Comment by rtpsr** [comment]
Hi @t-book,

The layers from Geoserver work fine within GeoNode. When I try to preview layers from geoserver directly using public IP, they are pointing to localhost and hence not working. Tried switching manually in the url, but no luck. Is Geoserver (layer preview) not intended to be accessed directly in this basic installation setup? May be I am missing something in the env options. 

Thanks!

**Comment by t-book** [comment]
-> try to update the proxy base url in geoserver: https://docs.geoserver.org/stable/en/user/configuration/globalsettings.html

**Comment by giohappy** [comment]
Closing because this issue looks stale.
I invite you to use the [geonode-users](https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users) mailing list for additional questions.
