### ISSUE TITLE
[Docker installation] "There was a problem loading the page" with DEBUG=False and STATIC enabled

### ISSUE THREAD

**Issue by danjde** [GeoNode/geonode#6547]
## Expected Behavior

Disabling DEBUG the site works fine

## Actual Behavior
on ".env"  with 

`DEBUG=False `

and 

```
STATIC_ROOT=/mnt/volumes/statics/static/
MEDIA_ROOT=/mnt/volumes/statics/uploaded/
GEOIP_PATH=/mnt/volumes/statics/geoip.db

CACHE_BUSTING_STATIC_ENABLED=True
CACHE_BUSTING_MEDIA_ENABLED=True
```

the home page show:

_"There was a problem loading the page"
Please contact your GeoNode administrator (they may have received an email automatically if they configured it properly). If you are the site administrator, enable debug mode to see the actual error and fix it or file an issue in GeoNode's issue tracker_

## Steps to Reproduce the Problem

  1. Enable CACHE_BUSTING_STATIC and CACHE_BUSTING_MEDIA
  2. Disable DEBUG
  3. create directory:  /mnt/volumes/statics/static/ and /mnt/volumes/statics/uploaded/

## Specifications

  - GeoNode version: 3.1.0.dev1602709652
  - Installation method: Docker
  - Platform: Ubuntu 20.04
  - Additional details:

**Comment by danjde** [comment]
With `DEBUG=True` the site works fine.

**Comment by singh-atenekom** [comment]
@danjde I could not find CACHE_BUSTING_STATIC and CACHE_BUSTING_MEDIA_ENABLED settings in geonode 3.x Project structure. Can't reproduce the error.

Build was successful at branch 3.x by executing `docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build` with `DEBUG=False`

**Comment by danjde** [comment]
@singh-atenekom I simply follow the official documentation -> https://docs.geonode.org/en/master/install/basic/index.html#ubuntu-18-0-basic-setup

I think I don't understand, do you suggest me to repeat the rebuild of the dockers?
And eventually, where I can found into the official documentation what you suggest to me? 


Many thanks!


Davide

**Comment by giohappy** [comment]
Closing because this issue looks stale.
I invite you to use the [geonode-users](https://lists.osgeo.org/cgi-bin/mailman/listinfo/geonode-users) mailing list for additional questions.
