### ISSUE TITLE
Minor review of the current advanced resource workflow implementation

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6551]
The current advanced workflow implementation is missing some important features for the managers, which are limited to "approval" action only and within the same group of the resource.

As an advanced user I would like to propose the following enhancements to the current workflow:

1. Hide "unpublished" resources to **anonymous users only**. Still **allow the registered user** to access the resources (if they have the rights to do that, of course)

2. The "unpublished" resources will remain hidden to users if the permission will be explicitly removed

3. During the upload, whenever the advanced workflow is enabled, automatically allow the owner groups to access the resource, even if the "anonymous" flag has been disabled. Those permissions can be removed later on

4. During the upload, allow the "managers" of the groups associated to the resource, to edit the resource, the same as they are admin for that resource

5. Allow the "managers" to "publish" also the resources, not only to "approve" them

**Comment by gannebamm** [comment]
Do we need a revised docu section for this? See https://docs.geonode.org/en/master/admin/admin_panel/index.html#group-based-advanced-data-workflow

And this is not yet merged into 3.x branch AFAI can see?

**Comment by afabiani** [comment]
@gannebamm https://github.com/GeoNode/documentation/commit/a59c375c0f1069d9194fd0ab258b83dbadda8fa9

Yes, it has been backported already.
