### ISSUE TITLE
 build.geo-solutions.it server is down

### ISSUE THREAD

**Issue by enricofer** [GeoNode/geonode#6587]
## Expected Behavior
paver setup without issues

## Actual Behavior
paver setup throws exception:
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='build.geo-solutions.it', port=443): Max retries exceeded with url: /geonode/geoserver/latest/geoserver-2.17.2.war (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0xb5b0eb50>, 'Connection to build.geo-solutions.it timed out. (connect timeout=10)'))

## Steps to Reproduce the Problem

  1. paver setup
  2.
  3.

## Specifications

  - GeoNode version: 3
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: 
  - Additional details:

**Comment by t-book** [comment]
@giohappy It looks the build server is down?

**Comment by afabiani** [comment]
This will require some time to go up again, unfortunately.

You can temporarily use dropbox, see the needed changes

 - GeoNode [here](https://github.com/GeoNode/geonode/commit/7b970f847dceb33eb0ba562e15330d85648a47d4)

 - GeoNode Project [here](https://github.com/GeoNode/geonode-project/commit/19192302a0a8ed9adc2eb6b2a33bfbbbf12ee333)

**Comment by enricofer** [comment]
Thanks for the quick fix. for me is enough.
