### ISSUE TITLE
Error Pulling with Docker, Geonode 3.1

### ISSUE THREAD

**Issue by gsoto1990** [GeoNode/geonode#6598]
docker-compose -f docker-compose.yml -f docker-compo                                                                                        se.override.localhost.yml pull

Pulling db            ... done
Pulling data-dir-conf ... done
Pulling geoserver     ... done
**Pulling django        ... error**
Pulling geonode       ... done

ERROR: for django  manifest for geonode/geonode:3.1 not found: manifest unknown:                                                                                         manifest unknown
ERROR: manifest for geonode/geonode:3.1 not found: manifest unknown: manifest un                                                                                        known

**Comment by renzoepolo** [comment]
Hello! How have you solved this error?

**Comment by gsoto1990** [comment]
> 
> 
> Hello! How have you solved this error?

I clone de git from here: _https://github.com/GeoNode/geonode.git_
 this works for me.

If you want to deploy a version for production follow these steps.

https://docs.geonode.org/en/master/install/advanced/spc/index.html

Sorry for the delay in answering. Take care.

**Comment by renzoepolo** [comment]
I'll try what you tell me. Thank you
