### ISSUE TITLE
GeoNode Admin Interface looks old style

### ISSUE THREAD

**Issue by valeriodeluca** [GeoNode/geonode#6606]
Dear all,

I tried to install GeoNode on VPS Ubuntu 20.04 via Docker following this guide:

https://opensourcetutorials.in/cheetsheets/geonodeinstall/

Everything works fine. I just seem to notice slightly "older" graphics in Django's GeoNode Admin Interface.

GeoNode Admin Interface in GeoNode Docs:
https://docs.geonode.org/en/master/_images/django_geonode_admin_interface.png

GeoNode Admin Interface in my GeoNode Docker instance:
https://github.com/valeriodeluca/geonode/blob/main/geonode_admin_interface_old_like.jpg

Thanks
Valerio

**Comment by t-book** [comment]
Hi Valerio,

yours is actually newer ;)

It’s called grapelli and has been added recently.
https://grappelliproject.com/ <https://grappelliproject.com/>

cheers,

Toni
