### ISSUE TITLE
Image not visible in the map details panel

### ISSUE THREAD

**Issue by danjde** [GeoNode/geonode#6609]
## Expected Behavior

in the map view, see the image in the details column panel on the right

## Actual Behavior

in the map view, in the details column panel on the right, see only the image path, but not the complete image.

## Steps to Reproduce the Problem

  1. Load and create the layer
  2. Go to Editing Tools -> Advanced Editing -> Attributes -> and change into the image row, Display Type from Label to Image -> save
  3. Go to the new Layer -> create map from layer -> save
  4. Go to the new map, click on a marker -> open the details column on the right -> look if the image is displayed

## Specifications

  - GeoNode version: 3.1.0.dev1602709652
  - Installation method: GeoNode Docker
  - Platform: GNU Linux
  - Additional details: Inspecting the html source code you can verified that the specific area construction is different from layer to map, in this way:

Layer: 

```
<div class="col-xs-12" style="font-weight: bold; word-wrap: break-word;" align="center">                                             
<a href="https://3x1t.org/Wqz4sXz/img/photo_28-09-2020-10.jpg" target="_new"><img src="https://3x1t.org/Wqz4sXz/img/photo_28-09-2020-10.jpg" title="Foto" alt="Foto" width="100%" height="auto"></a>
</div>
```

![Schermata del 2020-11-04 09-54-19](https://user-images.githubusercontent.com/4129294/98090124-eb2bd700-1e83-11eb-97a6-ac4d31222a4c.png)

Map:

`<div class="col-xs-6" style="word-wrap: break-word;">https://3x1t.org/Wqz4sXz/img/photo_28-09-2020-10.jpg</div>`

![Schermata del 2020-11-04 09-52-38](https://user-images.githubusercontent.com/4129294/98090135-ee26c780-1e83-11eb-8a3f-8a810fe6b304.png)

**Comment by t-book** [comment]
@afabiani what do you think? Milestone 3.1?

**Comment by gannebamm** [comment]
If I understand this issue correctly it is mapstore code which needs to get changed?

**Comment by afabiani** [comment]
shouldn't be an issue. You need to add the layer again to the map after changing the attributes mapping.

**Comment by danjde** [comment]
Confirm, recreating the map on the same layer (with the layer attributes mapping changes already applied), the issue stops.
