### ISSUE TITLE
mixed active content during uploading vector layer

### ISSUE THREAD

**Issue by valeriodeluca** [GeoNode/geonode#6628]
Hi there,
## Expected Behavior
Upload and storing of vector layer (shp, shx, prj, dbf).

## Actual Behavior
"Unexpected error!" message during uploading vector layer.

## Issue exploring
Browser console notices "mixed active content" and block it.
I saw a similar issue:
https://github.com/GeoNode/geonode/issues/5279

I tried to set SITEURL in .env file. This is my actual .env file:
https://github.com/valeriodeluca/geonode/blob/main/.env
COMPOSE_PROJECT_NAME=geonode
SET_DOCKER_ENV=production
SITEURL=https://my_domain/

Then .env update, I run this set of commands:
docker-compose stop
docker-compose rm
docker-compose -f docker-compose.yml -f docker-compose.override.localhost.yml up --build -d

At this moment the "Unexpected error!" message cause mixed content remains.

## Specifications

  - GeoNode version: 3.1.0.dev1604048525
  - Installation method: GeoNode Docker
  - Platform: Ubuntu 20.04 VPS
  - Additional details: SSL with Let's Ecrypt by Certbot

Thanks a lot

**Comment by gannebamm** [comment]
Please change your domain according to the docs:
https://docs.geonode.org/en/3.x/install/advanced/core/index.html#override-the-env-variables-to-deploy-on-a-public-ip-or-domain

Change the address in a copy of https://github.com/GeoNode/geonode/blob/master/docker-compose.override.localhost.yml. and deploy it by `docker-compose -f docker-compose.yml -f docker-compose.override.your.domain.yml up --build -d`

**Comment by valeriodeluca** [comment]
Thanks @gannebamm 
I had already made the changes you suggested on the file:
docker-compose.override.localhost.yml
I report it below:
https://github.com/valeriodeluca/geonode/blob/main/docker-compose.override.localhost.yml

I also carry my NGINX configuration, if it can be useful to this issue:
https://github.com/valeriodeluca/geonode/blob/main/nginx.conf

And my docker-compose.yml file:
https://github.com/valeriodeluca/geonode/blob/main/docker-compose.yml

Unfortunately I am still unable to load shapefile.
Tks

**Comment by t-book** [comment]
@valeriodeluca watch your geoserver endpoints: https://github.com/valeriodeluca/geonode/blob/main/.env#L47-L48

and try: 

`docker-compose up -d django --build`

**Comment by t-book** [comment]
@valeriodeluca as this is definitely a configuration issue on your side let's continue at the mailinglist or gitter. Github issues should be used to bugs. In case you're cannot find a way drop me a p.m and gitter and there share your pub url that I can have a look.
