### ISSUE TITLE
Print function does not work Geonode 3.1

### ISSUE THREAD

**Issue by gsoto1990** [GeoNode/geonode#6630]
Hi, i deploy geonode using SPCGeonode guide, all working perfect, only the print option.

When i try print a map, I get the following error: Error on printing: _**DEBUG is set to False but the host of the path provided to the proxy service is not in the PROXY_ALLOWED_HOSTS setting.**_

What file should I edit for this to work?

Thanks in advance.
![Firefox_Screenshot_2020-11-11T00-42-47 130Z](https://user-images.githubusercontent.com/58429324/98751131-e1c7d080-2395-11eb-8882-6f3f5cefd37d.png)

**Comment by t-book** [comment]
Try to add `PROXY_ALLOWED_HOSTS=[HOSTNAME, 'localhost', 'django', 'geonode', 'spatialreference.org', 'nominatim.openstreetmap.org', 'dev.openlayers.org','YOUR_PUBLIC_DOMAIN']` to https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/.env

**Comment by gsoto1990** [comment]
> Hi, I have tried what you tell me but it keeps throwing the same error.  :(
> _Error on printing: DEBUG is set to False but the host of the path provided to the proxy service is not in the PROXY_ALLOWED_HOSTS setting._ 



> Try to add `PROXY_ALLOWED_HOSTS=[HOSTNAME, 'localhost', 'django', 'geonode', 'spatialreference.org', 'nominatim.openstreetmap.org', 'dev.openlayers.org','YOUR_PUBLIC_DOMAIN']` to https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/.env

**Comment by t-book** [comment]
you can try setting it here directly as well: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L1175

**Comment by villa101101** [comment]
I am experiencing the same issue and have tried the above suggestions with no success. Is there any other suggestions to solving this issue? I did my installation in the middle of February this year, the version is 3.1, using the manual setup on ubuntu 18.

**Comment by gsoto1990** [comment]
> 
> 
> I am experiencing the same issue and have tried the above suggestions with no success. Is there any other suggestions to solving this issue? I did my installation in the middle of February this year, the version is 3.1, using the manual setup on ubuntu 18.

I solved using this:

Run the following commands:
 

1. Stop all run containers.
2. Edit the file **.env** file.
2. Modify everything you need and save the changes.
3. Run this command: **docker-compose up --no-start**
4. Finally run this: **docker-compose start**

I was able to fix the problem that way.

Let me know if it works for you.

Greetings!

**Comment by villa101101** [comment]
> > I am experiencing the same issue and have tried the above suggestions with no success. Is there any other suggestions to solving this issue? I did my installation in the middle of February this year, the version is 3.1, using the manual setup on ubuntu 18.
> 
> I using the Docker installation, i share with you how I could solve it, using Docker.
> 
> https://docs.geonode.org/en/master/install/advanced/spc/index.html
> 
> **I solved using this:**
> 
> Run the following commands:
> 
> 1. Stop all run containers.
> 2. Edit the file **.env** file.
> 3. Modify everything you need and save the changes.
> 4. Run this command: **docker-compose up --no-start**
> 5. Finally run this: **docker-compose start**
> 
> I was able to fix the problem that way.
> 
> Let me know if it works for you.
> 
> Greetings!

I don't follow. What should I be modifying in the .env file?
