### ISSUE TITLE
500 Error response on request https://master.demo.geonode.org/maps/somekindofstring

### ISSUE THREAD

**Issue by singh-atenekom** [GeoNode/geonode#6632]
## Expected Behavior
Response expected 404 or some other valid code.  

## Actual Behavior
Returns 500. If some one continue triggering the same links, we get many tracebacks in sentry.

## Steps to Reproduce the Problem
  On Click [https://master.demo.geonode.org/maps/somekindofstring](https://master.demo.geonode.org/maps/somekindofstring)  , it shows 500 error page.

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details: The url  `maps/<id>` considers only integer value, not string, thus throw 500. I tried locally and I can see the error as shown in the image below 

<img width="508" alt="500" src="https://user-images.githubusercontent.com/53856536/98838379-7db01580-2444-11eb-93cc-1dd37bc860e9.png">

**Comment by afabiani** [comment]
Should be fixed now

**Comment by singh-atenekom** [comment]
Cool, it works, closing the issue :)
