### ISSUE TITLE
Mail notifications for private datasets are public

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6653]
## Expected Behavior
If I have enabled email notifications I will get notified for new datasets. **Except the datasets are private** and not visible by me.

## Actual Behavior
I get notified for datasets I have no permission to view.

## Steps to Reproduce the Problem

  1. EMAIL_ENABLE=True, GROUP_PRIVATE_RESOURCES=True, valid SMTP credentials
  1. User A with enabled notifications and varified mail address.
  1. Create two private groups.
  1. User B uploads a dataset into his private group.
  1. User A gets notified per mail.

## Specifications

  - GeoNode version: 3.1.0.dev1605604154
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 20.04 LTS
  - Additional details:

**Comment by gannebamm** [comment]
Users A 'https://my.geonode.instance/social/recent-activity' does properly display the activities according to the user's permissions.

**Comment by gannebamm** [comment]
On those lines there is no check for permission:
https://github.com/GeoNode/geonode/blob/master/geonode/base/models.py#L913

While the recent-activity view does check permissions:
https://github.com/GeoNode/geonode/blob/master/geonode/social/views.py#L62

I would propose to add the signalling object (e.g. the saved document) as parameter to the function _get_notification_recipients_ (https://github.com/GeoNode/geonode/blob/master/geonode/notifications_helper.py#L106) to check on that level if the profile should be returned. What do the more experienced devs say @t-book @afabiani @francbartoli ?

**Comment by t-book** [comment]
sounds  good . it should work to exclude more users in case the resource is private https://github.com/GeoNode/geonode/blob/master/geonode/notifications_helper.py#L116-L117

**Comment by afabiani** [comment]
Yep, seems to be a good plan!

**Comment by gannebamm** [comment]
Hi, some progress report:

```py
def get_notification_recipients(notice_type_label, exclude_user=None, resource=None):
    """ Get notification recipients
    """
    if not has_notifications:
        return []
    recipients_ids = notifications.models.NoticeSetting.objects \
        .filter(notice_type__label=notice_type_label) \
        .values('user')
    from django.contrib.auth import get_user_model
    profiles = get_user_model().objects.filter(id__in=recipients_ids)
    if exclude_user:
        profiles.exclude(username=exclude_user.username)
    if resource:
        for profile in profiles:
            print("check permissions for " + resource.title + " and " + profile.username + ">> view permission: " + str(profile.has_perm('view_resourcebase', resource)))
            if not profile.has_perm('view_resourcebase', resource):
                profiles = profiles.exclude(username=profile.username)
                print(profile.username + " will get excluded from notifaction list")
    return profiles
```

Does not work perfectly. Eg If a group is set as view permitted on upload this info is not yet available to the function. It seems like the permissions will get set later? I will have to double check that. Furthermore, one other functions need to get the resource info: `get_comment_notification_recipients()` https://github.com/GeoNode/geonode/blob/master/geonode/notifications_helper.py#L122

**Comment by gannebamm** [comment]
Ok, the above does not work. The permission seem to get set after the signal arrives. In the social activity feed everything is fine and the view does use the same code. I think we have to:
a) notify via a digest. Collect objects which are CRUD-ed and check notify options later.
b) change where the `get_notification_recipients()` function will get called to some part after the permissions are set.

**Comment by gannebamm** [comment]
I had to check the permissions for the ResourceBase object by using:
`if not profile.has_perm('base.view_resourcebase', resource.get_self_resource()):`
This fixes the above error. Sorry for the spam.
