### ISSUE TITLE
Improve WYSIWYG metadata editor to store formatted and plain texts

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6665]
At this time the [new WYSIWYG editor for text-area metadata fields](https://github.com/GeoNode/geonode/pull/6627/files), pollutes the metadata outputs of the CSW and the metadata detail preview (see image below). 
HTML content is stored even for empty text.

I suspect that the only solution is to store both a plain version and a formatted version for each field, and use the plain version for the contexts that do not support HTML output. The following tasks are required for this:

 - create new model fields for the [current fields](https://github.com/GeoNode/geonode/pull/6627/files#diff-5b6481c1b771417fbd324e3fd49a0c19aa9a35a505d01fcb06f17fbc53a1d3b0R337-R356) that are using TyniMCE, and populate the fields with the plain version of the field text
- make the CSW module use the plain fields
- make the metadata preview module use the plain fields

![image](https://user-images.githubusercontent.com/571129/99544729-ee12e580-29b4-11eb-933e-c16ff95ac4e2.png)

**Comment by t-book** [comment]
wouldn't it work to just remove all html tags in certain views? (Instead of changing the model again?)

```
  tags_regex = re.compile('<.*?>')
  cleaned_csw = re.sub(tags_regex, '', raw_html)
  render ...
```

**Comment by t-book** [comment]
okay ignore there is already a PR ;)

**Comment by afabiani** [comment]
no hard changes, just added a few properties. DB won't be touched again.
