### ISSUE TITLE
Add a command to Fix the tables to upgrade to new schema

### ISSUE THREAD

**Issue by MoRadwan74** [GeoNode/geonode#6670]
I have a running instance of GeoNode 2.10.4 and tried to upgrade to 3.0 but got stuck at migration errors like these:
- `django.db.utils.ProgrammingError: table ... does not exist`
- `django.db.utils.ProgrammingError: column ... of relation ... already exists`

Tried some wetwork of showing migrations and applying `psql` commands to the CREATED or DROPED tables with no luck.

Then came across [this guide in the documentation](https://docs.geonode.org/en/master/admin/upgrade/index.html) and did the required fixes to migrate to the new schema through psql terminal. Then applying the `migrate` command, It ran most of the migrations successfully except for one table `base_configuration` which outputs the error of:
`django.db.utils.ProgrammingError: table base_configuration already exists`

So I ran another `psql` command to `geonode` table as follows: `DROP TABLE base_configuration CASCADE;`

Then applying the `migrate` command and it migrated successfully.

Just wanted to point out to add the above command in the documentation to the list of commands that [Fix the tables in order to migrate to the new schema](https://docs.geonode.org/en/master/admin/upgrade/index.html#fix-the-tables-in-order-to-migrate-to-the-new-schema).

**Comment by afabiani** [comment]
Many thanks @MoRadwan74 

Added your changes to the docs  https://github.com/GeoNode/documentation/commit/d8be339725a02b40ba64a13d60ecacf5b32de0d2
