### ISSUE TITLE
Using external postgresql as database on geonode docker

### ISSUE THREAD

**Issue by msalmanfarisi** [GeoNode/geonode#6671]
Hello,

I'm a geonode newbie. Any help how can I configure geonode docker if database used from external postgresql server?
I have read the guide from https://docs.geonode.org/en/3.x/install/advanced/core/index.html#docker but I couldn't find how to use external db.

Thank you very much

**Comment by gannebamm** [comment]
We will create a new part in the documentation to describe how this can be accomplished

**Comment by khaledboka** [comment]
Hello, I have created the gist to discuss
https://gist.github.com/khaledboka/25d1263c8dbf465dfd227b08b81edcd5

How to improve `wait-for-databases.sh` file
https://gist.github.com/khaledboka/25d1263c8dbf465dfd227b08b81edcd5#improvement-suggestion-for-wait-for-databases-script

**Comment by gannebamm** [comment]
@khaledboka I see two thumbs up from @afabiani and @t-book. Have you decided how to bring this to a pull request? I think the wait-for-databases.sh issue should be a separate one in this repository. The other part should be an issue on the documentation repository. For both you could create PRs. Thats my 2 cents.
Thanks for your work!

**Comment by t-book** [comment]
@gannebamm yep we've talked about a PR that we can review. Looks all fine for me so far.

**Comment by khaledboka** [comment]
@gannebamm @t-book @afabiani 
Thanks very much for the following up, 

But as @t-book mentioned during the sprint to make sure that it does not affect anything else, I am currently making sure that it doesn't affect any other scenarios or files like the env files for development and production

`scripts/docker/env/development/db.env`
`scripts/docker/env/production/db.env`

I will create the required the PRs very soon
