### ISSUE TITLE
Geonode CMS (wordpress) integration

### ISSUE THREAD

**Issue by HaidarZ** [GeoNode/geonode#6675]
> Interoperability
> Integrates with other content management systems (WordPress, Drupal)
[http://geonode.org/dev_features/#interoperability](url)

Is there any reallife example for the means of integration with other cms ?
Is there an already built plugins or we should implement our own ?

**Comment by t-book** [comment]
hi @HaidarZ  While I cannot provide realtime example I like to share this PDF which describes the integration of wagtail: https://summit.geonode.org/presentation/2018/Customizing-GeoNode.pdf

**Comment by singh-atenekom** [comment]
I would also prefer Wagtail as It is written in Django and compatible to geonode (need to make sure, that geonode and wagtail use same django version ).

**Comment by ahmednosman** [comment]
Hello HaidarZ, 
we actually have a couple of GeoNode and Wagtail implementations
http://portal.arabspatial.org/ in this project the geonode instance is rather not directly exposed from the UI and is working as a framework to provide the maps and layers needed for the projects
https://nafcoast.org/
It is worth noting that both cases were implementing CMS integration differently
In one project the CMS was actually an app inside the GeoNode project, the other we had two projects integrations on the API level. 
Wagtail was an obvious choice for us when we started, given both Wagtail and GeoNode run on Django coupled with the huge flexibility you get from Wagtail.
However there should not be a problem to integrate GeoNode with any CMS as GeoNode is offering an API which you can use to embed the components you need in your solution
Within the next few days CartoView will offer a CMS app (based on Wagtail) allowing the integration of CMS and GeoNode in a single platform

**Comment by gannebamm** [comment]
I think this question as answered already. The major outcomes were:

1. There is an [old workshop document](https://summit.geonode.org/presentation/2018/Customizing-GeoNode.pdf) describing wagtail integration
2. Cartologic (@ahmednosman) does provide a GeoNode implementation with wagtail integration called Cartoview.

I will close this issue now.
