### ISSUE TITLE
layer.attribute.attribute_type stored as string tuple

### ISSUE THREAD

**Issue by khaledboka** [GeoNode/geonode#6694]
## Expected Behavior
Layer.attribute.attribute_type = 'xsd:string'

attribute type to be stored as a string in the database:
"xsd:int", 'xsd:string' ..

## Actual Behavior
Layer.attribute.attribute_type = '('xsd:string',)'

## Steps to Reproduce the Problem

  1. Upload a layer
  2. check the attribute value in the database

![Screenshot from 2020-12-05 19-45-37](https://user-images.githubusercontent.com/13452248/101259610-84276980-3732-11eb-8577-d1f9decece77.png)

**Comment by khaledboka** [comment]
Possible solution
#6693

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/commit/c14b797a25492f71ab58bab8930cc5266f8571bc
