### ISSUE TITLE
2 Faktor Authentication in Geonode

### ISSUE THREAD

**Issue by singh-atenekom** [GeoNode/geonode#6699]
We would likely to integrate 2 Faktor Authentication in Geonode projects. There are some django packages like [django-two-factor-auth](https://pypi.org/project/django-two-factor-auth/0.1.2/).  Is this kind of package is compatible to geonode or there should be self implemented app in geonode 3.x?

**Comment by giohappy** [comment]
Closing because this issue looks stale.
You can open a GNIP if you have a proposal for it.
