### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6701]
https://docs.geonode.org/en/master/contribute/translation/index.html?highlight=translation

- [x] german Carsten
- [ ] portugese Julierme
- [ ] spanish
- [ ] english
- [ ] greek @kalxas 
- [ ] persian Naqi Sadaqatzada
- [ ] ...

**Comment by tallistroan** [comment]
I reviewed the already quite good german translation, added some missing texts, changed the translation from the informal 'Du' to the formal 'Sie' and made some other small changes. However I don't have push access to the repo, so for the meantime I attached the changed files here at this comment:
[LC_MESSAGES_de.zip](https://github.com/GeoNode/geonode/files/5660074/LC_MESSAGES_de.zip)

**Comment by t-book** [comment]
@tallistroan thanks! -> https://github.com/GeoNode/geonode/pull/6708

**Comment by giohappy** [comment]
can we clse this @gannebamm?
