### ISSUE TITLE
UUID will not be used on XML upload

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6704]
## Expected Behavior
If I upload a shapefile with iso metadata xml the uuid will be used.

## Actual Behavior

the uuid will not be used.

## Steps to Reproduce the Problem

  1. download and inspect a shapefile with iso xml file (eg: https://github.com/gannebamm/geonode-workshop/tree/main/00_getStarted/data)
  2. upload a shapefile with XML data 
  3. compare the UUIDs

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: ubuntu
  - Additional details: not plattform dependend

**Comment by gannebamm** [comment]
I looked into this:

https://github.com/GeoNode/geonode/blob/master/geonode/layers/utils.py#L655

This **will** use the UUID of the metadata **but only if** the metadata is marked as `metadata_uploaded_preserve`. 

If this field is not set a new UUID will get created as part of this* https://github.com/GeoNode/geonode/blob/master/geonode/layers/utils.py#L655. 

The line https://github.com/GeoNode/geonode/blob/master/geonode/layers/utils.py#L699 (elif identifier) will not be used on an upload. I think this will maybe get triggered if you upload a metadata XML afterwards - which will cause massive confusion because both files will have different UUIDs.

I, therefore, propose to use the UUID regardless of the `metadata_uploaded_preserve` setting. This setting will make the metadata static. We most likely will upload a set of metadata and later add metadata info in GeoNode. This workflow would not be possible by setting the metadata to  `metadata_uploaded_preserve`.

@t-book @afabiani @simod - thoughts? 

* to be precise this should be the line which creates the UUID? https://github.com/GeoNode/geonode/blob/f50b4ff18698289afd4075aff85014d17585a066/geonode/layers/models.py#L610

**Comment by gannebamm** [comment]
I created a draft PR for this:
https://github.com/GeoNode/geonode/pull/6711

**Comment by stefmec** [comment]
I'm not sure if this is really the expected behaviour. At the moment the uuid is used for selecting the layer when uploading metadata XML (https://github.com/GeoNode/geonode/blob/master/geonode/layers/utils.py#L700).

So the system expects UIDs to be unique.

But when a user copy-pastes metadata.xmls they will have the same UID. If he/she uploads them to geonode, they will have the same uid. On updating one of their metadata maybe the wrong one is overwritten.

Maybe better: The UID from metadata.xml is preserved only if it is unique. Otherwise the user will get an error message.

**Comment by gannebamm** [comment]
@stefmec I see your point. You want to reuse metadata xmls for other datasets to prefill metadata fields. In that case I would assume you should not use a already established UUID. We should define the workflow you would like as user and uploader and maybe rethink how metadata xmls will be parsed (as part of an open discussion and maybe GNIP).
