### ISSUE TITLE
Typo on Document Information page

### ISSUE THREAD

**Issue by mckinnon** [GeoNode/geonode#6714]
## Expected Behavior
On Document Information page [(example in Docs)](https://docs.geonode.org/en/master/usage/managing_documents/document_info.html#document-information) the word "Publication" is spelled with one B.

## Actual Behavior
The word "Publication" is spelled with two Bs ("Pubblication Date").

## Specifications
  - GeoNode version: 3.1.0.dev1604048590
  - Installation method: GeoNode Docker via [GeoNode Basic Installation](https://docs.geonode.org/en/master/install/basic/index.html)
  - Platform: Ubuntu 18.04.5 LTS
  - Additional details: I'd submit a patch instead but I have no idea where this typo is in the codebase.

**Comment by t-book** [comment]
@mckinnon can you show me exactly where you read _Pubblication_?

**Comment by mckinnon** [comment]
You'll see the 'Pubblication Date' typo on [this page](http://therefugiaproject.org/documents/56) and all Document pages like it.
