### ISSUE TITLE
Improve Upload (Importer) speed and code quality

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6715]
Currently, when uploading using the "geonode.importer" workflow, GeoNode seems to stuck for a long time even after the Importer session has successfully completed.

By examining the code, it looks like the "final_step" of the workflow is managing a lot of synchronous logic before returning an "ok" status back. Moreover the resource is saved multiple times causing GeoNode to throw unnecessary signals to GeoServer.

Last but not least, the method is too big and it would benefit of some refactoring by isolating the buisness logic not strictly related to the upload process on separate methods or tasks.

The idea would be here to:

 - Review the method logic and avoid redoundant updates or saves
 - Move metadata and permission logic outside, on "tasks" which could be eventually run asynchronously
 - Try to move outside any "heavy" logic comunicating with GeoServer to async tasks in order to benefit of Celery engine when it is enabled

**Comment by t-book** [comment]
This is a very good proposal!
