### ISSUE TITLE
Remote service seems not support extra parameter in the url

### ISSUE THREAD

**Issue by vipcxj** [GeoNode/geonode#6755]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I need a remote wms service which need a token as extra parameter.
For example, all request url should carry with a tk parameter
http://t0.tianditu.gov.cn/img_w/wmts?request=GetCapabilities&service=wmts&tk=XXXXXXX

But geonode seems not support it.
I guess geonode ignores the extra query parameter and still use '?' to append additional parameters, causing the link to be unavailable.
The solution is check the url provided, If there is extra query parameter, append them in all request.

**Comment by giohappy** [comment]
It doesn't seem the case at least in current 3.2 release, 3.2.x  and master branch. As you can see from the screenshot below prameters are kept and used to retrieve GetCapabilities.

Do you have a URL to test?

![image](https://user-images.githubusercontent.com/571129/116710433-0e1dea80-a9d2-11eb-8d21-02f9a0d8077c.png)

**Comment by afabiani** [comment]
Superseded by https://github.com/GeoNode/geonode/issues/6631
