### ISSUE TITLE
Not support delete layers?

### ISSUE THREAD

**Issue by vipcxj** [GeoNode/geonode#6756]
## Expected Behavior
Support delete layers

## Actual Behavior
Not support delete layers

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

I haven't found any infomation about how to delete a layer in the document. And I even not found a button to delete layer in the  web page. I can delete the layers in the geoserver. However, they still left in the geonode.

**Comment by t-book** [comment]
You can see the remove layer button (red) in the first screenshot here:
https://docs.geonode.org/en/master/usage/managing_layers/layer_editing.html#layer-editing

**Comment by vipcxj** [comment]
The delete function is also hidden too concealed, isn't it usually the same level as the add?
