### ISSUE TITLE
OAI-PMH endpoint does not work properly

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6771]
## Expected Behavior
If I use the OAI-PMH endpoint the XML response should be valid.

## Actual Behavior

A `<ns0:error code="badArgument">Illegal parameter 'access_token'</ns0:error>` is thrown. Even if logged in as superuser.

## Steps to Reproduce the Problem

  1. open https://master.demo.geonode.org/developer/
  2. click OAI-PMH 2.0

## Specifications

  - GeoNode version: 3.1.0.dev1609412094
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): master.demo.geonode.org

**Comment by giohappy** [comment]
@gannebamm as you will know 3.1.1 has been released along with 3.2 and no further support is expected on 3.1.x branch.
Are you going to manage this issue on your side?

**Comment by gannebamm** [comment]
Currently we do not have the capacities to add this functionality back, but maybe later this year we are able to do so.

**Comment by gannebamm** [comment]
Seems to be fixed on current branch (master): https://master.demo.geonode.org/catalogue/csw?mode=opensearch&service=CSW&version=2.0.2&request=GetCapabilities
