### ISSUE TITLE
Open Data endpoint does not exist anymore

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6772]
## Expected Behavior
If I click the Open Data endpoint at the developers page a json representation should be displayed.

## Actual Behavior

The site does not exist.

## Steps to Reproduce the Problem

  1. https://master.demo.geonode.org/developer/
  2. click Open Data (btw the link is wrong with two `//`)

## Specifications

  - GeoNode version: 3.1.0.dev1609412094
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): master.demo.geonode.org
  - Additional details: Maybe this commit (2e47fc3935fbb9ffac05c93eec6f2f72faa78861) got rid of the open data endpoint?

**Comment by t-book** [comment]
You can see the initial implementation here: 
https://github.com/GeoNode/geonode/pull/2342/files

Further the definition:
https://project-open-data.cio.gov/schema/

From what the view looks like it might need some updates to fit into the current version for example I wouldn't serialize with json module but use DRF for it.  ... there might be a reason why it has been removed.

Personally, I would just remove the link from the dev page.

**Comment by afabiani** [comment]
That implementation is quite dangerous other than inefficient. I wouldn't restore it back.

**Comment by t-book** [comment]
closed with PR
