### ISSUE TITLE
Improve GeoApps REST serializer

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6779]
Thanks to the existing amazing code base and after applying this PR the developer will be easily allowed to:
1. Inherit from GeoAppSerializer with no need to copy the whole code again
2. Override the `create` & `update` methods easily
3. Add extra checks if needed

Also, this benefits to have a centralized Class to add all common method to

For Example, 
After applying this PR to the `GeoStorySerializer` GeoStories App, the `class GeoStorySerializer` could be as follows

`@mapstore2_adapter/geoapps/geostories/api/serializers.py`
```python
class GeoStorySerializer(GeoAppSerializer):
    class Meta:
        model = GeoStory
        name = 'geostory'
        fields = GeoAppSerializer.Meta.fields + ('app_type', )
```

Instead of the [current file](https://github.com/GeoNode/django-mapstore-adapter/blob/master/mapstore2_adapter/geoapps/geostories/api/serializers.py)

This helped me a lot while creating our own first GeoNode GeoApp that will be demonstrated soon
[simple_geonode_leaflet_app](https://github.com/cartologic/simple_geonode_leaflet_app)

I could also implement my own serializer class with extra checks as follows
```python
from geonode.geoapps.api.serializers import GeoAppSerializer
from .models import SimpleGeoApp


class SimpleGeoAppSerializer(GeoAppSerializer):
    class Meta(GeoAppSerializer.Meta):
        model = SimpleGeoApp
        name = 'simple_geoapp'
        fields = GeoAppSerializer.Meta.fields + ('app_type', )

    def extra_checks(self, validated_data):
        '''
        raise ValidationError if any of validated_data is not valid
        '''
        pass

    def create(self, validated_data):
        # perform extra checks
        self.extra_checks(validated_data)
        
        _instance = super(SimpleGeoAppSerializer, self).create(self, validated_data)
        return _instance

    def update(self, instance, validated_data):
        # perform extra checks
        self.extra_checks(validated_data)

        _instance = super(SimpleGeoAppSerializer, self).update(self, instance, validated_data)
        return _instance
```

**Comment by gannebamm** [comment]
@khaledboka any news regarding this:

> _This helped me a lot while creating our own first GeoNode GeoApp that will be demonstrated soon_

> simple_geonode_leaflet_app
