### ISSUE TITLE
Move import statements to top of file

### ISSUE THREAD

**Issue by dhlambert** [GeoNode/geonode#6798]
_Reserved for Catalyst Academy 2021_

### Description

PEP8 guidelines state that all import statements should be defined at the top of the file. Some import statements in GeoNode are defined in the middle of the file, within method definitions and are sometimes duplicated. These imports should be moved to the top of the file and duplicates should be deleted.

### Tasks

- [ ] Identify instances of imports that do not occur at the top of the file
- [ ] Move the imports to the top of the file and delete any duplicates

**Comment by GeoTob** [comment]
Some of this may have been for good reason (ie to avoid circular imports or similar issues) - fixing it could break other parts of the code. While the idea is good, I suggest you don't make something PEP8 compliant just for the sake of it.

**Comment by dhlambert** [comment]
Good point, thanks for raising this. I'll close this issue then.
