### ISSUE TITLE
CSV layer uploads fail

### ISSUE THREAD

**Issue by mtnorthcott** [GeoNode/geonode#6829]
### Description
There is a bug where uploading a layer stored as a CSV file will fail, reporting
```
Server Error: Internal Server Error
Please check your network connection. In case of Layer Upload make sure GeoServer is running and accepting connections.
```

Inspecting the logs provides the following stack trace,
```python
Internal Server Error: /layers/upload
Traceback (most recent call last):
  File "/home/mattn/dev/geonode/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/mattn/dev/geonode/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/mattn/dev/geonode/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mattn/dev/geonode/venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/mattn/dev/geonode/geonode/layers/views.py", line 384, in layer_upload
    for key, value in out[_k].items():
RuntimeError: dictionary keys changed during iteration
"POST /layers/upload HTTP/1.1" 500 46453
```
which is caused by the variable set within the loop at [geonode/layers/views.py:389-392](https://github.com/GeoNode/geonode/blob/a283dd1ec9efa20dc24ff3801b18db45fde7eede/geonode/layers/views.py#L389).

### Tasks
* [ ] Refactor the loop starting at [geonode/layers/views.py:379](https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L379)
* [ ] Verify you can upload CSV layers

**Comment by t-book** [comment]
@mtnorthcott this looks important. Could you care for a PR?

**Comment by mtnorthcott** [comment]
@t-book I have taken some time to look at this today and have fixed the initial error in the above PR. Instead, the message

> Only Shapefiles, GeoTiffs, and ASCIIs are supported. You uploaded a .csv file

is shown after selecting "Upload files" (from [geonode/layers/forms.py#L150](https://github.com/GeoNode/geonode/blob/master/geonode/layers/forms.py#L150)). Permitting CSV files to pass form validation allows the layer to be created, at least in the database. However, no geometry is displayed on preview. I have marked my PR as a draft for the time being.
