### ISSUE TITLE
Geoserver menu entry leads to login-dialog / GeoWebCache page

### ISSUE THREAD

**Issue by stefmec** [GeoNode/geonode#6830]
## Expected Behavior
* login to geonode with default admin credentials
* click on the "admin" dropdown menu 
* click on "GeoServer"
* you'll see the the geoserver admin-page (with logo top left, menu "About & Status" ... on the left and a welcome message

## Actual Behavior
* the browser is showing a dialog requesting username and passwort
* after entering geoserver credentials the URL is "http://localhost:8080/geoserver/" and shows "Welcome to GeoWebCache version 1.18-SNAPSHOT, build a4571508b2aae66c899d2d95c0ef873294f96853/a4571508b2aae66c899d2d95c0ef873294f96853 ...."

I can reach the admin gui by manually typing:
http://localhost:8080/geoserver/index.html
or
http://localhost:8080/geoserver/web/

## Steps to Reproduce the Problem

  1. login to geonode with default admin credentials
  2. click on the "admin" dropdown menu 
  3. click on "GeoServer"

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: manual
  - Additional details: this happens with geoserver-2.17.4.war and geoserver-2.18.1.war but it works with geoserver-2.17.2.war

**Comment by gannebamm** [comment]
Comment from @afabiani about the issue:
https://github.com/GeoNode/geonode/issues/6780#issuecomment-762117094

**Comment by afabiani** [comment]
@gannebamm I'm going to rebuild the WARs being sure that the file is not empty

**Comment by gannebamm** [comment]
I can confirm, that 2.18.1 and 2.17.4 *do not provide the mentioned lines* in the property file. The property file is empty. Nonetheless the data-dir you can download via eg https://build.geo-solutions.it/geonode/geoserver/latest/data-2.17.4.zip does provide the file with contents.

For me downloading the 2.17.4 GeoServer does look like this and provides two separate /data folders:

/geoserver
-----------/data  (is this one used?
----------------------/geofence/geofence-server.properties

geoserver/geoserver
----------------------/data (or this one?)
--------------------------------/geoserver/data/geofence/geofence-server.properties

Both properties files are empty.

I can not see the `DATA_DIR_URL` is used. This method does use the .war file https://github.com/GeoNode/geonode/blob/master/pavement.py#L186 and in the end calls _install_data_dir().

The _install_data_dir() method *will not* use the `DATA_DIR_URL` but does direct editing to the XML files, like https://github.com/GeoNode/geonode/blob/9dac9fc4ea7ae9319b26fa3c232ce44ab28d5c29/pavement.py#L266

In fact, searching through the whole repo for `DATA_DIR_URL` shows only one hit > dev_config.yml.

**Comment by gannebamm** [comment]
I can confirm that:
using `paver setup` and manually copying the DATA_DIR over the above-mentioned data directories (done both, just to be sure) will fix this issue.

For reference I used these two builds:
GEOSERVER_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.17.4.war"
DATA_DIR_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/data-2.17.4.zip"

**Comment by afabiani** [comment]
WARs have been updated on dropbox, they will be updated on build server soon.

Acutally, cannot say much more regarding the GWC exception. But I don't think that can impact the performances that much.

**Comment by stefmec** [comment]
I just created a complete new venv an hour ago; geoserver was downloaded from dropbox; version is 2.17.4; geonode from git/master.

After logging in to geonode and clicking on the "geoserver" menu entry i'll see the geoserver welcome page. But after clicking on the "star"-button in the top right corner I get to:
`http://localhost:8080/geoserver/web/j_spring_oauth2_geonode_login`

HTTP ERROR 404 Not Found
URI:	/geoserver/web/j_spring_oauth2_geonode_login
STATUS:	404
MESSAGE:	Not Found
SERVLET:	dispatcher

Login manually works; behind the scenes authentication somehow works too because layers uploaded will show up in geoserver.

**Comment by stefmec** [comment]
It works as expected with version 2.17.1 / these URLs:
GEOSERVER_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/geoserver-2.17.1.war"
DATA_DIR_URL: "https://build.geo-solutions.it/geonode/geoserver/latest/data-2.17.1.zip"

**Comment by gannebamm** [comment]
> But after clicking on the "star"-button in the top right corner I get to:
> `http://localhost:8080/geoserver/web/j_spring_oauth2_geonode_login`
> 
> HTTP ERROR 404 Not Found
> URI: /geoserver/web/j_spring_oauth2_geonode_login
> STATUS: 404
> MESSAGE: Not Found
> SERVLET: dispatcher

@t-book and I had this behaviour yesterday on a docker-compose based setup, too. It usually will work if you retry the GeoNode icon ('star'). It seems like some caching prevents proper OAuth based login. We should investigate that in the future.

**Comment by stefmec** [comment]
@gannebamm : This does not help (complete new venv; checkout from master; paver setup; geoserver 2.17.4 was downloaded from dropbox). I did not copy any data-directories manually. 
The "star button" always shows the error page.

**Comment by gannebamm** [comment]
This will fix the issue:
```
Index: pavement.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/pavement.py b/pavement.py
--- a/pavement.py	(revision b5d360e0a041348b6e427313efee86fe7fdb6f0c)
+++ b/pavement.py	(date 1614620832713)
@@ -165,6 +165,8 @@
             os.path.basename(urlparse(dev_config['GEOSERVER_URL']).path)
         jetty_runner = download_dir / \
             os.path.basename(urlparse(dev_config['JETTY_RUNNER_URL']).path)
+        geoserver_data = download_dir / \
+                       os.path.basename(urlparse(dev_config['DATA_DIR_URL']).path)
         grab(
             options.get(
                 'geoserver',
@@ -177,6 +179,13 @@
                 dev_config['JETTY_RUNNER_URL']),
             jetty_runner,
             "jetty runner")
+        grab(
+            options.get(
+                'geoserver data',
+                dev_config['DATA_DIR_URL']),
+            geoserver_data,
+            "geoserver data-dir")
+
         if not geoserver_dir.exists():
             geoserver_dir.makedirs()
 
@@ -187,7 +196,12 @@
             logger.info("extracting geoserver")
             z = zipfile.ZipFile(geoserver_bin, "r")
             z.extractall(webapp_dir)
-        _install_data_dir()
+
+            logger.info("extracting geoserver data dir")
+            z = zipfile.ZipFile(geoserver_data, "r")
+            z.extractall(geoserver_dir)
+
+        _configure_data_dir()
 
 
 def _robust_rmtree(path, logger=None, max_retries=5):
@@ -211,17 +225,7 @@
     shutil.rmtree(path)
 
 
-def _install_data_dir():
-    target_data_dir = path('geoserver/data')
-    if target_data_dir.exists():
-        try:
-            target_data_dir.rmtree()
-        except OSError:
-            _robust_rmtree(target_data_dir, logger=True)
-
-    original_data_dir = path('geoserver/geoserver/data')
-    justcopy(original_data_dir, target_data_dir)
-
+def _configure_data_dir():
     try:
         config = path(
             'geoserver/data/global.xml')
@@ -907,7 +911,7 @@
     )
     sh("rm -rf geonode/development.db")
     sh("rm -rf geonode/uploaded/*")
-    _install_data_dir()
+    _configure_data_dir()
 
 
 @needs(['reset'])
```

I will create an PR for it
