### ISSUE TITLE
Inconsistent behavior between document and layer upload flow

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6856]
Differently from layers after a document has been uploaded the user is redirected to the Metadata Wizard page.
The client (and me) expect the same behavior for all the types of uploads.

If we don't have an intermediate page as in layers, where the user is presented with a set of buttons to decide where to go (Layer info page, Metadata, etc.) I would be more inclined toward redirecting to the document page, rather then the metadata wizard.

**The proposal** here would be to change the redirect of the document upload page to the `document_detail` page instead of the `document_metadata` one.

**Comment by gannebamm** [comment]
Just today I noticed, that for layers you can multi upload several files. Maybe this is something to consider for documents, too?

**Comment by afabiani** [comment]
Uhm, ok, this is a bit more complex than expected. I'll take a look how difficult would be to implement the multi-upload for documents too.
We might need a new specific thread for this, along with a dedicated branch.

**Comment by afabiani** [comment]
@gannebamm for the time being I just updated the default redirect to `document_detail` instead of `document_metadata`, since the documents upload form is non-trivial.
As you can see from the image below, while uploading a document you can already decide which resources you would like to link and either if the resource is an external url or an uploaded file.
I guess changing this behavior requires some more analysis, especially from the users' perspective.

![image](https://user-images.githubusercontent.com/1278021/105735008-84263780-5f33-11eb-81cc-b054f8adc310.png)

**Comment by gannebamm** [comment]
Yeah OK, you are absolutely right! Maybe better use the resources to get the api working for mass uploads of files
