### ISSUE TITLE
Embedding a map/geo-app on an IFRAME may fail due to X-Frame Options:sameorigin on NGINX

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6865]
## Expected Behavior
Embed a map or a geoapp (e.g. a GeoStory) on a IFRAME, allows me to include it seamlessly on an external web site.

## Actual Behavior
IFRAME fails due to a X-Frame constraint header created by default from NGINX.

## Steps to Reproduce the Problem

  1. Create a simple HTML page with an IFRAME
  2. As IFRAM source specify a map embed link form GeoNode
  3. Try to open the HTML page locally

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: docker
  - Additional details:

**Comment by afabiani** [comment]
Accordingly to what stated [here](https://stackoverflow.com/questions/47405597/x-frame-options-in-nginx-to-allow-all-domains?rq=1) we should add the option `proxy_hide_header X-Frame-Options;` to the NGINX configuration.

E.g.: by using a public GeoStory  (visible to anonymous users too), I can see the GeoStory on the IFRAME
![image](https://user-images.githubusercontent.com/1278021/105520026-72962300-5cda-11eb-809c-a902e924c938.png)

**Comment by t-book** [comment]
Isn't it already covered here?
https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L780

Loosely connected, we should mention GeoServer Cors https://docs.geoserver.org/latest/en/user/production/container.html#enable-cors in our docs or at the developer page in case someone needs to read services with an external client

**Comment by afabiani** [comment]
@t-book nope, that option is not sufficient. NGINX injects by default the `x-frame option: sameorigin` if not explicitly changed or hidden to something else.

**Comment by t-book** [comment]
I see! Thanks for pointing it out!
