### ISSUE TITLE
What is the effect of assigning permissions to styles? 

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6866]
Aa a customer I'm wondering what's the effect of settings permissions for a style during its upload.

Playing with them I would expect to not see the styles listed to users without permissions, but it's not the case.

![image](https://user-images.githubusercontent.com/571129/104477397-56e79a00-55c1-11eb-9974-8dfad09c8f1c.png)

Currently the permissions are completely ignored by the default style upload form, even because there's no concept on GeoNode/GeoServer of "private style".

Let's remove this misleading form.

**Comment by t-book** [comment]
+1
