### ISSUE TITLE
how to activate bing or google maps in 2.7.4 version

### ISSUE THREAD

**Issue by MrNico** [GeoNode/geonode#6887]
Hello, I need to activate the bing and / or google maps, searching I have found that you must edit the /etc/geonode/local_settings.py file and complete the section

# A Google Maps API key is needed for the 3D Google Earth view of maps
# See http://code.google.com/apis/maps/signup.html
GOOGLE_API_KEY = ''

My question is how can I also activate the bing maps?

I am using Version
2.7.4
Build Date
19-Nov-2015 15:24
GeoTools Version
13.4 (rev 32fd0ea5beb1ac38186a3f40081389776f7ca86b)
GeoWebCache Version
1.7.3 (rev a09f77d3b14d4bbcee3feb407fd2d8ea2cf62d64 / a09f77d3b14d4bbcee3feb407fd2d8ea2cf62d64)

**Comment by MrNico** [comment]
Can someone give me some information? I still can't read anything concrete to activate this
Thank you

**Comment by gannebamm** [comment]
The GeoNode version you use is very old. I never used it and am unable to easily find the codebase you are at in github. I think you shall edit the basemaps somewhere here:

(2.6.x version of codebase)
https://github.com/GeoNode/geonode/blob/2.6.x/geonode/settings.py#L722-L744
