### ISSUE TITLE
meaningful filename for document download

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6910]
**Is your feature request related to a problem? Please describe.**
If a user uploads a document its filename will be auto-generated by Django and stored in the filesystem with a unique filename. This lead to a document download filename which is not meaningful. See the [gitter discussion on 29. Januar 2021 11:21](https://gitter.im/GeoNode/general?at=6013e1a9aa6a6f319deed192).

**Describe the solution you'd like**
The document download filename should be a slugified version of its title.

**Describe alternatives you've considered**
In the discussion with [Daniel Röser on gitter](https://gitter.im/GeoNode/general?at=6017edb89fa6765ef8ee7658) we considered modifying the Document model to store the initial upload filename. This would force all users to run migrations. We need to discuss on GitHub if this behaviour is worth the additional field and complexity on the model side.

**Additional context**
See my PR for the easy to implement solution #6911

**Comment by obersupermega** [comment]
It would be great, when we backport it to tag 3.1. My clients would be super happy ;-)
