### ISSUE TITLE
GNIP 82 - Thesauri improvements

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#6925]
WIP
# GNIP 82 - Thesauri improvements

## Overview

Thesauri implementation needs some revision, update and improvements.
Currently it's only possibile to have a single thesaurus in the GUI, while INSPIRE and other profiles require keywords from different thesauri.
We want to:
- handle multiple thesauri
- improve i18n in thesauri titles
- improve cardinality handling

### Proposed By

@etj (Emanuele Tajariol)

### Assigned to Release

This proposal is for GeoNode ???

### State

* [x] Under Discussion
* [x] In Progress
* [x] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Thesaurus code is stale and needs some revisions.
Currently it's only possibile to have a single thesaurus in the GUI, while INSPIRE and other profiles require keywords from different thesauri. 
Furthermore, when compiling a 19115 metadata, recent INSPIRE specs (and related profiles) require both href and title of the cited thesaurus.

#### `Thesaurus` table (to be updated)

We need to support an href referencing the thesaurus; it's stored into the `rdf:about` field.
  - Add field `about = models.CharField(max_length=255, null=True, blank=True)`

We need to move into the DB the config currently kept in SETTINGS (see https://docs.geonode.org/en/master/admin/thesaurus/#configure-a-thesaurus-in-geonode).
This is an excerpt from the current doc:

  > `name`: (mandatory string) the identifier you used in the load_thesaurus commands.
  > `required`: (optional boolean) if True, a keyword of this thesaurus is mandatory to complete the metadata. Currently not implemented.
  > `filter`: (optional boolean) if True, a faceted list of keywords of this thesaurus will be presented on the search page.

  - `name` will not be ported, since it's a FK to the Thesaurus identifier;
  - `required` will be enhanced, in order to better support cardinality info; we'll have `card_min` and `card_max`
  - `filter` is a too general concept, so we can transform it into a field named `facet`
  
We'll add:
- `card_min` integer 
- `card_max` integer
- `facet` boolean

**Warning**: the change about moving the settings from the `SETTINGS` file into the DB is breaking backcompatibility, so we'll have to change the logic accordingly:
- when one of the moved settings is needed, 
  - we'll first check in the SETTINGS; if the setting is there, we'll use it and notify a warning about a deprecated setting.
  - only as a fallback step we'll check for the value in the DB

#### `ThesaurusLabel` table (new)

  Contains localized version of the thesaurus title
  - `lang = models.CharField(max_length=3)`
  - `label = models.CharField(max_length=255)`
  - FK to Thesaurus

We'll use the localized label in the GUI, and the general title (in the `Thesaurus` class) for the xml template.

### Commands

The command to load the thesaurus will be improved in order to support the thesaurus label localization.
In particular, we may have rdf files which only have localized titles, and a missing "general" title.
We need to handle all condition:

e.g.: only general title:

    <skos:ConceptScheme rdf:about="http://geonetwork-opensource.org/thesaurus/naturalearth-and-seavox">
        <dc:title>Continents, countries, sea regions of the world.</dc:title>
        <dc:description>Generated from NaturalEarth datasets and SeaVox.</dc:description>

- `Thesaurus.title` --> "Continents, countries, sea regions of the world."
- `ThesaurusLabel` --> no records

e.g.: only localized titles:

    <skos:ConceptScheme xmlns:skos="http://www.w3.org/2004/02/skos/core#" rdf:about="https://registry.geodati.gov.it/rndt-all1">
      <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/" xml:lang="it">Registro dei dati di interesse generale per il RNDT</dc:title>
      <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/" xml:lang="en">Register of the reference data sets for RNDT</dc:title>

- `ThesaurusLabel` --> entries for `it` and `en`
- `Thesaurus.title` --> We have to chose one. 
  - **A new setting will be introduced** `DEFAULT_THESAURUS_LANG`, so that the title with the selected language will be chosen
    1. If a title with the language set in `DEFAULT_THESAURUS_LANG`, chose that one to fill the `Thesaurus.title` field
    1. Else take the title with `en` language
    1. Else take the first localized title found

### Metadata Editing GUI

Modify the editing GUI so that thesauri selection is rendered in the first tab.

We want to display all of the thesauri set as required in the GUI.
The requirement is set in the DB (`card_min`, `card_max`), but we also have a legacy setting (https://docs.geonode.org/en/2.10/admin/thesaurus/index.html#configure-a-thesaurus-in-geonode)

In the GUI we will have, according to the `card_max` and `card_min` values, 
- `card_max=0` --> Disabled, won't be shown in the GUI (`card_min` is not even checked in this case)
- `card_max=1` --> Single choice
  - `card_min = 0` --> Single choice, optional --> rendered as a dropdown, with an empty/unselected element
  - `card_min = 1` --> Single choice, required --> rendered as a dropdown
- `card_max=-1` --> Multiple choice
  - `card_min = 0`  --> [0..N] Multiple choices, optional --> rendered as a typeahead badges(?)
  - `card_min = 1` --> [1..N] Multiple choices, required --> rendered as a typeahead badges(?) + apply check for the mandatory warning

If the legacy `required` boolean setting is in the configuration, we'll use it as if we'd found:
- `required` = `true`
  -  `card_min = 1`
  -  `card_max = -1`
- `required` = `false`
  -  `card_min = 0`
  -  `card_max = -1`

As stated elewhere also, when a legacy settings is found, we'll use it and notify a warning about the deprecated setting.

The displayed thesaurus label should be the localized one, if any, otherwise the generic title will be used.

---

GUI should be restructed as follows:
- free keywords moved to the bottom
- list of Thesauri keywords selectors

![GeoNode - thesauri](https://user-images.githubusercontent.com/717359/105035791-dced6000-5a5b-11eb-81c8-b28141bd0374.png)

Also, the validation checks should act according to the mandatory requirements of the displayed thesauri.

### Metadata template

The XML metadata template has to be modified in order to include all of the thesauri keywords added to the layer metadata.
The thesaurus title to be put into the template is the generic (non localized) `Thesaurus.title`.

### Settings changes

- Deprecated `THESAURUS` entry ( https://docs.geonode.org/en/master/admin/thesaurus/#configure-a-thesaurus-in-geonode). 
- New `DEFAULT_THESAURUS_LANG` for Thesaurus title, default 'en'.

### Backwards Compatibility

Thesaurus configuration is currently made in the `settings` file (as `THESAURUS` entry), and this is going to be moved to DB. 
As noted in the proposal, if file configuration is present, it will be used instead of the DB data for a given thesaurus, but a warning log will be notified about the deprecation of the file setting.

## Future evolution

-

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: +1
* Francesco Bartoli:
* Giovanni Allegri: +1
* Simone Dalmasso:
* Toni Schoenbuchner: +1
* Florian Hoedt: +1

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by gannebamm** [comment]
Just to be clear: If you mention 'will be moved to DB' you mean this will get its own model and therefore admin panel page, right?

I like the concept of the GNIP backend and frontend-wise.

**Comment by t-book** [comment]
My +1
( Ping @giohappy )

**Comment by etj** [comment]
Some missing details about the GUI:

- The titles of the thesaurus should be localized, using the language expressed in the language currently choosen for the GUI, i.e. the record in `ThesaurusLabel` which matches the thesaurus FK and the `lang`.
If no such language exists for that the thesaurus title, the default title will be displayed (`Thesaurus.title`).

- In the same way, the thesaurus keywords should be localized, using the language currently choosen for the GUI.
If such lang is not present for a given keyword (i.e. no record in `ThesaurusKeywordLabel` pointing to a `ThesaurusKeyword` with a given `lang`), the default keyword will be used (i.e. `ThesaurusKeyword.alt_label`).

Please note that when retrieving the records for GUI display, the `DEFAULT_THESAURUS_LANG` setting will not be used at all: that setting is only used when parsing the `rdf` files and importing the thesauri.

**Comment by etj** [comment]
Thesauri editing in maps and documents should be added.

**Comment by gannebamm** [comment]
Is the loading of an RDF thesaurus still valid? See https://docs.geonode.org/en/master/admin/thesaurus/#loading-a-thesaurus

**Comment by etj** [comment]
@gannebamm sure, we also made some improvements related to importing the items in various languages. 
Found any issues loading RDF files?
