### ISSUE TITLE
GeoNode Headless phase 1: Move frontend stuff into client library

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#6926]
The proposal would be to move:

- base/[templates,templatetags]
- layers/[templates,templatetags]
- maps/[templates,templatetags]
- documents/[templates,templatetags]
- apps/[templates,templatetags]
- ...
- static/*

and everything that is possible from [*/templates,*/templatetags,*/static] into the geonode client library app.

That way, the GeoNode frontend becomes completely pluggable. Eventually we can envisage to move the client library outside, as an external geonode dependency.

Reference branch: https://github.com/GeoNode/geonode/tree/cilent_cleanup

Estimate: 0.5

**Comment by t-book** [comment]
+1

**Comment by gannebamm** [comment]
@afabiani You think this can be accomplished for 3.2 (milestone)? Seems like a huge effort?
My +1
