### ISSUE TITLE
Email activation not working

### ISSUE THREAD

**Issue by roya2543** [GeoNode/geonode#6945]
Hello,
I am trying to send invitations, receive an activation email when a user registers, or approved confirmation by admin however none of them work. I have updated .env   as suggested and it actually says that the admin has to approve your registration but my admin email doesn't get any notification, and I can not send any invite as admin. followings are what I added in .env 

ACCOUNT_EMAIL_CONFIRMATION_EMAIL=True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=True
ACCOUNT_CONFIRM_EMAIL_ON_GET=True
ACCOUNT_APPROVAL_REQUIRED=True
ACCOUNT_EMAIL_VERIFICATION="mandatory"
ACCOUNT_OPEN_SIGNUP=True
ACCOUNT_EMAIL_REQUIRED=True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'myemail@gmail.com'
EMAIL_HOST_PASSWORD = 'my app key' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'default from email'

Does someone has any experience regarding this and be able to fix this issue?

**Comment by t-book** [comment]
Hi @roya2543 from what I remember Gmail has some security steps for allowing sending mails by Django also see: https://github.com/GeoNode/geonode/issues/5907#issuecomment-602742845 do you have some other SMTP which you could try for sending?

Provided you have set to  https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L68 to true your shown config looks correct.

**Comment by roya2543** [comment]
> Hi @roya2543 from what I remember Gmail has some security steps for allowing sending mails by Django also see: [#5907 (comment)](https://github.com/GeoNode/geonode/issues/5907#issuecomment-602742845) do you have some other SMTP which you could try for sending?
> 
> Provided you have set to https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L68 to true your shown config looks correct.

Hi @t-book 
We used docker to install Geonode and our settings.py is not the same as this link here. It is almost empty.  So I have changed .env file and added Email_Enable = true. 

I also managed Gmail security steps and got an activation code for the second app.  I guess it might be related to Geonode and Docker, or our server and domain that needs to activate SMTP somehow. We are trying to see if it is from our server. 
Cheers,

**Comment by davidherbert2** [comment]
Hi @t-book - I'm a colleague of roya2543 taking a look at the sending issue which we're still having trouble with.  Our Geonode install is the Docker stack installed on Ubuntu 18.04 via https://docs.geonode.org/en/master/install/basic/index.html.  We got the Geonode code from GitHub via git clone https://github.com/GeoNode/geonode-project.git -b 3.x.  This is pretty much working on our server with the exception of the email sending on user registration.  We have made changes to .env, but have not touched the settings.py file.  This looks, as Roya said, substantially different to the one at https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L68 - our file is identical to the one at https://github.com/GeoNode/geonode-project/blob/master/project_name/settings.py.   

I have tried using gmail SMTP (as configured below), and have also installed and configured a Postfix instance locally, using the Docker network bridge.  Neither show any sign of being invoked by Geonode whatsoever, according to the Django logs. There are no connection refused errors or anything suggesting sending didn't work. It is as if email sending is not switched on for some reason.  Our .env contains:

DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
DJANGO_EMAIL_HOST=smtp.gmail.com
DJANGO_EMAIL_PORT=587
DJANGO_EMAIL_HOST_USER=<our_email>
DJANGO_EMAIL_HOST_PASSWORD=<our_password>
DJANGO_EMAIL_USE_TLS=True
DJANGO_EMAIL_USE_SSL=True
DEFAULT_FROM_EMAIL='<our_email>'

EMAIL_ENABLE=True
REGISTRATION_OPEN=True
ACCOUNT_EMAIL_CONFIRMATION_EMAIL=True
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=True
ACCOUNT_CONFIRM_EMAIL_ON_GET=True
ACCOUNT_APPROVAL_REQUIRED=True
ACCOUNT_EMAIL_VERIFICATION="mandatory"
ACCOUNT_OPEN_SIGNUP=True
ACCOUNT_EMAIL_REQUIRED=True

EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='<our_email>'
EMAIL_HOST_PASSWORD='<our_password>'
EMAIL_PORT=587
EMAIL_USE_TLS=True
EMAIL_USE_SSL=True
DEFAULT_FROM_EMAIL='<our_email>'

Clearly with the settings.py you refer to the EMAIL_* env vars are set via the DJANGO_* ones, so at least one set of these is redundant.  REGISTRATION_OPEN was mentioned (among other places) in https://training.geonode.geo-solutions.it/006_adv_workshop/003_geonode_production/production.html#configuring-user-registration.  However, I think this may be a superseded setting no longer used?

I can see in the settings.py at https://github.com/GeoNode/geonode/blob/master/geonode/settings.py the line:

MANAGERS = ADMINS = os.getenv('ADMINS', [])

We do not have this set.  I am not clear what this needs to be - I imagine a list of users? Might this be why no registration emails are sent?

Appreciative of any help you might be able to give,

David Herbert.

**Comment by davidherbert2** [comment]
Further to the above, I have tried adding the line:

ADMINS=['admin','<my_user_id>',]

to .env, but it makes no difference.

**Comment by t-book** [comment]
hi @davidherbert2 First of all could you try the following:

Log into your django container:

`docker exec -it django4your_geonode bash` (replace _your_geonode_ with correct name)

and inside your container try to send a mail via shell:

```
./manage.py shell

from django.core.mail import send_mail
send_mail('we test it','let us try','toni.schoenbuchner@csgis.de',['toni.schoenbuchner@csgis.de'],fail_silently=False,)
```

Hopefully, we run into a meaningful error message ;)

**Comment by t-book** [comment]
> Further to the above, I have tried adding the line:
> 
> ADMINS=['admin','<my_user_id>',]
> 
> to .env, but it makes no difference.

This should be set as a list: https://docs.djangoproject.com/en/3.1/ref/settings/#admins

**Comment by davidherbert2** [comment]
Thanks @t-book - I have verified that mail is being sent successfully from the Django shell - there was a problem with the App Password for the Google account.   Also I had DJANGO_EMAIL_USE_SSL set True which wasn't harmless as I thought.  So a couple of bugs sorted out!  Thanks Toni.  I have now set ADMINS as per the Django docs you pointed out.  However, from the Geonode (dockerised) application I am still getting no emails sent.  Nothing appears in the logs at all.  I think the next thing to do is set DEBUG=True in .env?  To get some more output in the logs.  Is there any other diagnostics I can use to track down what's happening?

**Comment by t-book** [comment]
Hi David, great this does not sound too bad. Just to double-check:

- registration is open and users do get welcome messages
- admins do NOT get notifications. Neither for registration nor when f.e a layer is updated.

is this correct?

**Comment by davidherbert2** [comment]
Thanks for prompt reply - yes both these are correct.

**Comment by davidherbert2** [comment]
DEBUG=True in .env does not appear to have made much difference to the logs, at least not from the Django container.

**Comment by davidherbert2** [comment]
Sorry @t-book misread your comment earlier - registration is open but users DO NOT get welcome messages.  Second statement is correct.  Apologies!

**Comment by afabiani** [comment]
@davidherbert2 as far as I remember the users get the welcome message only once they have been "approved" by the admin (i.e. activated) id the `ACCOUNT_APPROVAL_REQUIRED` is set to `True`

In this case they should not receive any message until an admin approves them.

**Comment by t-book** [comment]
There might be a problem with notifications. Which should be the module that actually cares for sending out emails. The first thing to check is: log in as an admin and visit the following page: `https://your-domain.com/notifications/settings/`
All boxes should be checked. Next double check: https://docs.geonode.org/en/master/usage/accounts_user_profile/updating_profile/associating_email.html?highlight=notifications

Next, open a new private window and register a new user. As you've set `ACCOUNT_EMAIL_VERIFICATION="mandatory"`
you should get an admin notification. 

In the window where you're logged in as admin continue with visiting following section: `https://your-domain/en/admin/pinax_notifications/`. Have a look at the settings. Do you see the registration notification and if so, what is the status of `send`?

**Comment by davidherbert2** [comment]
Thanks for your inputs @t-book and @afabiani.  I can verify that in notification settings all boxes are checked.  Looking at the associated email accounts, I saw our gmail one there.  It was neither primary nor verified at this stage.  I made it primary, and did the verification step.  There *was* an email sent to our gmail account by Geonode at this point.  I clicked on the link in said email to complete verification.   So something is working as expected!  However, registering as a new user (using a 1 use email account) fails to result in an email to admin (inbox in admin console empty, and nothing in the gmail client either).   Clearly my expectation that the registering user gets some kind of holding email on registration (pre-approval) was not correct.   Looking as you suggest in Pinax Notifications -> noticesettings results in the attached screenshot.

![pinax_notifications_screenshot](https://user-images.githubusercontent.com/49239555/108341737-e50efb80-71d1-11eb-8277-58a01df9ee4d.png)

I can't see any user registrations have ever made it there (I have done dozens in the last couple of days).  Any further ideas much appreciated!

**Comment by afabiani** [comment]
Uhm, it looks there something missing in the process. I should try it myself. Not sure if it depends on a combination of settings or there's some regression in the registration process.

**Comment by davidherbert2** [comment]
@afabiani just wondering if you have had a chance to look further at this?  Is there any other input I can provide to help solve the problem?  I'm willing to dive into code with some direction (experienced with Python but not directly familiar with Geonode architecture and workflow).  Many thanks for your help so far.

**Comment by allilou** [comment]
We ran in the same problem today and it seems to be a problem caused by environment variables that are not available the same way for uWSGI, Celery and the shell command. Also you have to be aware about passwords with special characters.

We solve it by duplicating all our environment variables definitions in all the configurations files, especially BROKER_URL and database account access.  
* geonode.ini
* supervisord.conf
* .env

Some errors are only visible in the rabbitMQ log:
``` sudo tail -F -n 300 /var/log/rabbitmq/rabbit@<yourmachine>.log```

The environment variables in geonode.ini are:

```ini
env =  GEONODE_INSTANCE_NAME=geonode
env =  GEONODE_DATABASE=geonode
env =  GEOWEBA_DATABASE_USER=geonode
env =  GEONODE_DATABASE_PASSWORD=<pwd>
env =  GEONODE_GEODATABASE=geonode_data
env =  GEONODE_GEODATABASE_PASSWORD=<pwd>

env =  DATABASE_URL=postgis://geonode:'<pwd>'@localhost:5432/geonode
env =  GEODATABASE_URL=postgis://geonde:'<pwd>'@localhost:5432/geonode_data
env =  DEFAULT_BACKEND_DATASTORE=datastore

#email
env = EMAIL_ENABLE=True
env = DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
env = DJANGO_EMAIL_HOST=your.host.name
env = DJANGO_EMAIL_PORT=465
env = DJANGO_EMAIL_HOST_USER=mail@you.dns
env = DJANGO_EMAIL_HOST_PASSWORD=<pwd>
env = DJANGO_EMAIL_USE_TLS=False
env = DJANGO_EMAIL_USE_SSL=True
env = DEFAULT_FROM_EMAIL=mail@you.dns

env = EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
env = EMAIL_HOST=mail.you.dns
env = EMAIL_PORT=465
env = EMAIL_HOST_USER=mail@you.dns
env = EMAIL_HOST_PASSWORD=<pwd>
env = EMAIL_USE_TLS=False
env = EMAIL_USE_SSL=True

env = ACCOUNT_OPEN_SIGNUP=True 
env = ACCOUNT_EMAIL_REQUIRED=True
env = ACCOUNT_APPROVAL_REQUIRED=False 
env = ACCOUNT_CONFIRM_EMAIL_ON_GET=False 
env = ACCOUNT_EMAIL_VERIFICATION=mandatory 
env = ACCOUNT_EMAIL_CONFIRMATION_EMAIL=True
env = ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=True 
env = ACCOUNT_AUTHENTICATION_METHOD=username_email

env = ASYNC_SIGNALS=True
env = BROKER_URL=amqp://admin:<pwd>@localhost:5672/
```

For supervisord.conf:

```conf
environment=DEBUG="False",CACHE_BUSTING_STATIC_ENABLED="True",CACHE_BUSTING_MEDIA_ENABLED="True",SITEURL="https://you.dns/",DJANGO_SETTINGS_MODULE="geonode.local_settings",GEOSERVER_ADMIN_PASSWORD="geoserver",GEOSERVER_LOCATION="http://you.dns/geoserver/",GEOSERVER_PUBLIC_LOCATION="https://you.dns/geoserver/",GEOSERVER_WEB_UI_LOCATION="https://you.dns/geoserver/",MONITORING_ENABLED="True",BROKER_URL="amqp://admin:<pwd>@localhost:5672/",ASYNC_SIGNALS="True",ALLOWED_HOSTS="['you.dns','localhost']",EMAIL_ENABLE="True",DJANGO_EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend",DJANGO_EMAIL_HOST="mail.you.dns",DJANGO_EMAIL_PORT="465",DJANGO_EMAIL_HOST_USER="mail@you.dns",DJANGO_EMAIL_HOST_PASSWORD="<pwd>", DJANGO_EMAIL_USE_TLS="False", DJANGO_EMAIL_USE_SSL="True", DEFAULT_FROM_EMAIL="mail@you.dns", EMAIL_BACKEND="django.core.mail.backends.smtp.EmailBackend", EMAIL_HOST="mail.you.dns", EMAIL_PORT="465", EMAIL_HOST_USER="mail@you.dns", EMAIL_HOST_PASSWORD="<pwd>", EMAIL_USE_TLS="False", EMAIL_USE_SSL="True", ACCOUNT_OPEN_SIGNUP="True", ACCOUNT_EMAIL_REQUIRED="True", ACCOUNT_APPROVAL_REQUIRED="False", ACCOUNT_CONFIRM_EMAIL_ON_GET="False", ACCOUNT_EMAIL_VERIFICATION="mandatory", ACCOUNT_EMAIL_CONFIRMATION_EMAIL="True",ACCOUNT_EMAIL_CONFIRMATION_REQUIRED="True", ACCOUNT_AUTHENTICATION_METHOD="username_email", GEONODE_DATABASE="geonode",geonode_DATABASE_USER="geonode",GEONODE_DATABASE_PASSWORD="<pwd>",GEONODE_GEODATABASE="geonode_data",GEONODE_GEODATABASE_PASSWORD="<pwd>",DATABASE_URL="postgis://geonode:'<pwd>'@localhost:5432/geonode",GEODATABASE_URL="postgis://geonode:'<pwd>'@localhost:5432/geonode_data",DEFAULT_BACKEND_DATASTORE="datastore"
```

**Comment by t-book** [comment]
Just tested with branch 3.2.x on geonode project.

- Invite User
- registration -> email to admin -> email to user

was working fine so far.

**Comment by davidherbert2** [comment]
@allilou Thanks for your helpful input - will give your suggestions a try in our installation.

**Comment by t-book** [comment]
@davidherbert2 is this issue solved on your side? Can we close?

**Comment by allilou** [comment]
> @davidherbert2 is this issue solved on your side? Can we close?

Yes @davidherbert2, in my side it's OK. Thanks.

**Comment by t-book** [comment]
please reopen if needed ;)
