### ISSUE TITLE
Layer UUID hook

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#6952]
The current generation of the `UUID` for the `Layers` is based on those two lines:

`instance.uuid = str(uuid.uuid1())` in [geonode/geonode/layers/models.py](https://github.com/geosolutions-it/geonode/blob/0a82a14f39d9545e9206d6f4cd5ae0fe68d4673f/geonode/layers/models.py#L620)
`layer_uuid = str(uuid.uuid1())` in [geonode/geonode/upload/upload.py](https://github.com/geosolutions-it/geonode/blob/0a82a14f39d9545e9206d6f4cd5ae0fe68d4673f/geonode/upload/upload.py#L596)

We want to let the UUID creation be pluggable and let the user use his own UUID generator based on their needs.

```
if hasattr(settings, 'LAYER_UUID_HANDLER') and settings.LAYER_UUID_HANDLER != '':
        from geonode.layers.utils import get_uuid_handler
        instance.uuid = get_uuid_handler()(instance).create_uuid()
```

And is enough to add this config in `settings.py` by specifying the object that is responsible to manage the new UUID
```
LAYER_UUID_HANDLER = "mymodule.myfile.MyObject"
```
More information related to the configuration are available in this [PR](https://github.com/GeoNode/geonode/pull/6953)

Documentation PR at this [link](https://github.com/GeoNode/documentation/pull/78)

**Comment by gannebamm** [comment]
Will this interfere with #6711?

**Comment by mattiagiupponi** [comment]
Hey, @gannebamm thanks for the comment.
As you can see in this part of the code ([pr](https://github.com/GeoNode/geonode/pull/6953))

https://github.com/GeoNode/geonode/blob/ce20d4d2a7f70b89df146fa51b80ef3ff3343f26/geonode/layers/models.py#L620-L626

The UUID will change only if a new handler is defined, otherwise will continue using the old version of the UUID
As far as I can see, the #6711 should not impact your development, but I don't have enough context on it, because from the code of the `utils.py` looks like that the UUID is read from the XML file and not defined on run-time.
So, if you decide to override the way to save the UUID (since is a `Charfield` could be anything) if you upload the metadata you (user) should have enough context of what's going on.
This is just an observation, maybe @afabiani could help us more :)
