### ISSUE TITLE
Add java.sql.Timestamp to the bindings eligeble for time support

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#6962]
The Geoserver importer assigns the `java.sql.Timestamp` bidning to the `year` attribute for this [example.zip](https://github.com/GeoNode/geonode/files/5996702/2d2591a7-c39c-42dc-b129-f158e0955ed0.zip).
This field has the special (non standard) encoding generated by Geoserver when the -Dorg.geotools.shapefile.datetime JAVA_OPTS is `true`. It is false by default.

If we add the the `java.sql.Timestamp` to the parser for the attributes eligeble for time support, we would be able to reingest a shapefile that was generated with the special encoding.

`java.sql.Timestamp` must be added within the conditional checks in [upload.utils._get_time_dimensions](https://github.com/GeoNode/geonode/blob/69bc39de6fb3db8f174f1c16d52c266bb73db65a/geonode/upload/utils.py#L481-L498)

**Comment by giohappy** [comment]
This requires some more investigation, because it seems that the test dataset had a bad encoding.

**Comment by simboss** [comment]
@giohappy is this still relevant?
What was the client behind this?

**Comment by giohappy** [comment]
@simboss it is a strenghtening, with low priority, just in case someone tries to load a shapefile that was downloaded from Geoserver with that option turned on.
