### ISSUE TITLE
Thesaurus wrong data in initial_data.json

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#6966]
## Expected Behavior

In `initial_data.json`, only valid initial data should be present

## Actual Behavior

In `initial_data.json`, some mock values are available

https://github.com/GeoNode/geonode/blob/7e1b7a0d3dce3b74309be01e9f3024e1f3b15981/geonode/base/fixtures/initial_data.json#L4917-L4930

## Steps to Reproduce the Problem

  1. Clone Geonode repository
  2. Load initial data
  3. Check `thesaurus` table

or
Open the file at this link to see the issue:

https://github.com/GeoNode/geonode/blob/7e1b7a0d3dce3b74309be01e9f3024e1f3b15981/geonode/base/fixtures/initial_data.json#L4917-L4930

## Specifications

  - GeoNode version: 3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all

**Comment by etj** [comment]
In initial data we don't want any thesaurus pre-installed. 
ISO19115 make it possible to refer to thesaurus keywords, ma no one is mandatory in the base profile.
Specific profiles (INSPIRE, RNDT) require one or more keywords for specific thesauri, and GeoNode should be configurabile to handle them, aand that's what [GNIP 82](https://github.com/GeoNode/geonode/issues/6925) was about.
