### ISSUE TITLE
Doesn't run with Docker

### ISSUE THREAD

**Issue by rokcarl** [GeoNode/geonode#6969]
I've been debugging this with people on Gitter for a couple of weeks almost, hitting a lot of problems.

I'm trying to get GeoNode working in production. I got it working off the 3.x branch, but it didn't have support for https, so I switched to master. I'm on `7e1b7a0d3dce3b74309be01e9f3024e1f3b15981` from Feb 19.

I tried now with SPCGeoNode, I get a django container restarting with error `Bad Gateway for url: http://nginx/geoserver//rest/security/masterpw.json`, [full log here](https://gist.github.com/rokcarl/97ddd37429be0ccfcb1832f2db10d5cc).

Running the normal version in root I also get errors. The django container is restarting. The db container says has a few errors like `ERROR:  column "type" of relation "monitoring_metric" already exists` and `ERROR:  relation "base_region" does not exist at character 341`. But the django container is restarted without anything noteworthy in the [logs](https://gist.github.com/rokcarl/df202dabbe1188cefa23c4068049403d).
I also get a `Unknown command: 'rebuild_index'` in the [`invoke.log`](https://gist.github.com/612c83fe92a5a40be20749c22b0be7ff).

## Specifications

  - GeoNode version: on master, `7e1b7a0d3dce3b74309be01e9f3024e1f3b15981`,
  - Installation method: GeoNode Docker and SPCGeoNode Docker
  - Platform: Ubuntu 20.04.1 LTS

**Comment by t-book** [comment]
ref.: #6981

**Comment by rokcarl** [comment]
In the meantime, I [got 3.1 working](https://gist.github.com/rokcarl/08af31c7a7f63e599fba08775b8d2c67).

**Comment by t-book** [comment]
@rokcarl is this solved? Can we close?

**Comment by rokcarl** [comment]
Yes.
