### ISSUE TITLE
Revert deferred loading of assets

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#6974]
The changes introduced in https://github.com/GeoNode/geonode/commit/f0b278df25e3a75e4f67ddc1db087a74dcaf53f9 do not only affect the autocomplete and the extent filter (which were reverted in https://github.com/GeoNode/geonode/commit/431e6a3f231c63ba1526d0d71f0983b10d6f1282 and https://github.com/GeoNode/geonode/commit/431e6a3f231c63ba1526d0d71f0983b10d6f1282) but also cause glitches during any page load. 
All the deferred loading commit must be reverted.

**Comment by afabiani** [comment]
Done through https://github.com/GeoNode/geonode/commit/7ed80970b4b1d51d0e4358b75c4fec202803051c
