### ISSUE TITLE
LE certs not correctly issued on master branch docker

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#6981]
## Expected Behavior

Run master branch via docker over https

## Actual Behavior

LE is failing and restarting:

```
 letsencrypt4geonode | Failed authorization procedure. geonode-test.csgis.de (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://geonode-test.csgis.de/.well-known/acme-challenge/V460x8F1NYuuri_DJ5pB7V_dXeu3UP5BZujBbQ01pCM [82.165.23.225]: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.17.2</ce"
```

## Steps to Reproduce the Problem

  1. clone master
  2.  A-record to vm
  2. ./docker.purge.sh (just to be sure...)
  3. update .env for https
  4. docker-compose up -d --build

## Solution

It looks there is some confusion as the le service from spc is saving certs [in a dir called](https://github.com/GeoNode/geonode/blob/master/scripts/spcgeonode/letsencrypt/docker-entrypoint.sh#L12) `/spcgeonode-certificates` where the  Nginx service mounts `nginx-certificates:/geonode-certificates` further I've needed a `depends_on` to make it work.

@afabiani If you agree I would prepare a PR. (Besides what do you think having the letsencrypt service outside of geonode (core) and spc and always use directory `/geonode-certificates`? One service to rule them all  ... less work in the end.)

```
diff --git a/docker-compose.yml b/docker-compose.yml
index fe305f6ce..4e8a4d949 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -77,8 +77,10 @@ services:
       - ADMIN_EMAIL=${ADMIN_EMAIL}
       - LETSENCRYPT_MODE=${LETSENCRYPT_MODE}
     volumes:
-      - nginx-certificates:/geonode-certificates
+      - nginx-certificates:/spcgeonode-certificates
     restart: on-failure
+    depends_on:
+      - geonode
```

## Specifications

  - GeoNode version: geonode master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: ubuntu
  - Additional details:

**Comment by afabiani** [comment]
@t-book sure go ahead, many thanks!

As usual, you know my policy, I'm not a fan of maintaining a lot of services, the work and problems always duplicate!

Is this happening only on unsatble version, or this affects 3.1 too?

**Comment by t-book** [comment]
Good morning @afabiani 

> As usual, you know my policy, I'm not a fan of maintaining a lot of services, the work and problems always duplicate!

I think this is a misunderstanding. From what I see we currently have the following letsencrypt setups:

**Used by "Core on master branch and SPC"**
https://github.com/GeoNode/geonode/tree/master/scripts/spcgeonode/letsencrypt

**Used by GeoNode Project:**
https://github.com/GeoNode/geonode-project/tree/master/docker/letsencrypt

Both are super close to each other but differ from the directory used for storing certs. Whenever something changes (for example with certbot) we need to change and test both. My Idea was as the only difference is the cert directory, moving this service into a separate repository which is used by both would reduce the overhead. _But this is absolutely nothing urgent. Just thinking out loud_



> Is this happening only on unsatble version, or this affects 3.1 too?

From what I see 3.1 and 3.x do not have let's encrypt  service added .
https://github.com/GeoNode/geonode/blob/3.x/docker-compose.yml 
Something we should backport from master for 3.2 release. (I can take care of)

**Comment by afabiani** [comment]
I @t-book the plan would to let:

- Extract a 3.1.1 version from the current 3.x branch
- Extract a 3.2.0 version from the current master branch
- Create a 3.1.x branch
- Create a 3.2.x branch
- Let the master branch become the new development branch
- Possibly get rid of confusing 3.x branch

What do you think?
I tend to keep 3.1.x as much as possible untouched for the time being, however I have nothing against with your proposal of backporting letsencrypt there if you have time/resources to do that.

**Comment by t-book** [comment]
@afabiani  

I agree with your plan. Especially with getting rid of 3.x which is confusing.
How long would you maintain 3.1.x?


> I tend to keep 3.1.x as much as possible untouched for the time being, however I have nothing against with your proposal of backporting letsencrypt there if you have time/resources to do that.

This is fine for me. 


_Just for the record:
**master => main** (github is using a different name in future; new users will get used to the term "main". But renaming it might bring a lot of confusion on our side. Better stick to master https://www.infoq.com/news/2020/10/github-main-branch/, )_
