### ISSUE TITLE
ISO category translation not shown (german)

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#6984]
## Expected Behavior
The ISO category (oceans, imagery base maps ...) are translated to their respective counterpart.

## Actual Behavior
The English string will be used all over the UI. Example:

![grafik](https://user-images.githubusercontent.com/6172324/108838562-17569980-75d4-11eb-8556-c4f87170a384.png)

## Steps to Reproduce the Problem

  1. switch language to german
  2. take a look at the iso strings

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all

  - Additional details:

This [commit](https://github.com/GeoNode/geonode/blame/master/geonode/locale/de/LC_MESSAGES/django.po#L8754) did comment out many translation strings in the german .po file. That is why those are not used anymore. I have uncommented those needed for the translation again and will provide a PR for the german translation, soon.

**Comment by afabiani** [comment]
@gannebamm I cannot see this currently working on master demo. Is it working on your local installation?

**Comment by gannebamm** [comment]
@afabiani I tested the PR locally and it seems to fix the issue. Could you please double-check for the Italian translations? Sorry again for messing this up in the first try!
