### ISSUE TITLE
Extending Geonode Template

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#6995]
**Is your feature request related to a problem? Please describe.**
If you need to change a little part of geonode template (without touching the core) from an external app, sometimes is required to override the entire HTML instead of a small piece of the template due to the lack of `{% block %}` tags.
For example, if I want to add a new facet in `_search_content.html`, I need to extend the template and override the whole content instead of override only the part related to the facets.

**Describe the solution you'd like**
I'd like to start adding `{% block %}` tags in order to let geonode be more customizable from an external application.
Here is an example:
Actual code:

https://github.com/GeoNode/geonode/blob/2ebd3199ceea9ce87e397e1a743c85ba8bcee304/geonode/templates/search/_search_content.html#L29-L46

Will become something like this:

```django
{% block search_facet_lists %}
  {% if SEARCH_FILTERS.H_KEYWORDS_ENABLED %}
    {% include "search/_h_keywords_filter.html" %}
  {% endif %}
  {% if SEARCH_FILTERS.T_KEYWORDS_ENABLED %}
    {% include "search/_t_keywords_filter.html" %}
  {% endif %}
  {% if SEARCH_FILTERS.TYPE_ENABLED and include_type_filter == 'true' %}
    {% include "search/_type_filters.html" %}
  {% endif %}
  {% include "search/_general_filters.html" %}
  {% if SEARCH_FILTERS.REGION_ENABLED %}
    {% include "search/_region_filter.html" %}
  {% endif %}
  {% if SEARCH_FILTERS.EXTENT_ENABLED %}
    {% include "search/_extent_filter.html" %}
  {% endif %}
{% endblock %}
```
So from my application, i can do something like this:

```django
{% extends "search/_search_content.html" %}
{% block search_facet_lists %}
    my custom facet lists
{% endblock %}
```
I think that will be really useful. 
For sure will be a progressive process, I'll probably start from `search.html`, `_search_content.html` and `panels.html`

**Describe alternatives you've considered**
The alternatives, are don't add block tags and directly override the original template with the custom one, by changing the whole template `HTML` 

**Additional context**
Django docs on [{% block %}](https://docs.djangoproject.com/en/3.1/howto/overriding-templates/#extending-an-overridden-template) tags.

**Comment by t-book** [comment]
👍

**Comment by etj** [comment]
There's a need to exclude the free keywords from the editing page. 
A new `{block}` should be added in order to allow extending pages to remove them.
While we're on it, we may want to add `block`s for every non-mandatory field once and for all.

**Comment by etj** [comment]
This issue has been used for extending the metadata editing page.
If the model has been customized, it's very likely that we may want to customize the metadata view as well.

By adding `{block}`s to [metadata_detail.html](https://github.com/GeoNode/geonode/blob/master/geonode/templates/metadata_detail.html) would allow an easier customization of the page.
