### ISSUE TITLE
Layers without viewing and downloading permissions, are still displayed

### ISSUE THREAD

**Issue by dpadron** [GeoNode/geonode#6996]
## Expected Behavior
Upload a layer and remove the viewing and download permissions for the public. 
When I invoke the layer through geoservices, it shouldn't be seen or downloaded

## Actual Behavior
Upload a layer and remove the viewing and download permissions for the public. 

The layer's permissions are respected in Geonode, but if I invoke the layer using geoservices in QGis for example, it continues to display

## Steps to Reproduce the Problem

  1. Upload a layer and remove public viewing and download permissions
  2. Create a WMS / WMST data source in Qgis
  3. Podrá comprobar que sigue desplegandose  la capa que se oculto en geonode

## Specifications

  - GeoNode version: master.demo.geonode.org
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: ubuntu 20.04
![wms_master demo geonode org](https://user-images.githubusercontent.com/7094961/109279766-7148a080-781a-11eb-901b-9847bd4c4878.jpg)

  - Additional details:

**Comment by gannebamm** [comment]
I will take a look at this issue later this week.

**Comment by gannebamm** [comment]
Sorry, I was not able to test this behaviour, yet. I will start investigating next week 🤞

**Comment by afabiani** [comment]
@dpadron there was a `WMS|*` rule on master.demo GeoFence. I removed it and so far the security rules seem to be correctly applied now. Could you please try again?

**Comment by afabiani** [comment]
I just confirmed the issue, it looks like a new upload also adds the following rules to GeoFence despite the permissions

![image](https://user-images.githubusercontent.com/1278021/110150542-ab4c1080-7ddf-11eb-8cb6-5cdd93941b9c.png)

Need to investigate more.

**Comment by afabiani** [comment]
It looks like the [fix](https://github.com/GeoNode/geonode/commit/6813680652ec38ab75dfb73eb35fd00f8e66136f) is quite straightforward. Nevertheless let's keep this issue open until everyone can confirm the issue has been solved.

**Comment by dpadron** [comment]
I have performed an update and now it works correctly. Thanks
