### ISSUE TITLE
CSW prefiltering

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7012]
**Is your feature request related to a problem? Please describe.**

We may want CSW endpoints returning only a subset of the catalog.
Such subsets may not be statically defined, e.g. we may want only the metadata of layers belonging to a certain group, so that whenever i create a new group, I can ask for its metadata by querying `csw/{group_slug}`.

**Describe the solution you'd like**
The simplest yet flexible solution would be to pass an optional filter class/function to `csw_global_dispatch`.
If such a filter is defined, the Layers passed to the csw local backend would be filtered by it.

**Describe alternatives you've considered**
Copy and modifiy the `csw_global_dispatch` in apps that may be an option, but that mean to have a lot of code duplicated, while implementing a pre-filtering in the original function would save a lot of code, while offering a simple point of extension.

**Additional context**
The foreseen solution is only aimed at the `pycsw_local` backend. Also, the authorization logic already in geonode only targets the local backend, so the other ones would not be included in this feature implementation as well.

**Comment by giohappy** [comment]
I'm in favour of the first solution. It is what I had in mind when I considered the dynamic filtering inside the csw dispatch.
local pycsw is the only solution that we're employing, so to me it's fine to focus only on this.

To be honest I would be inclined to remove the other options, but this of course should be a proposal to be discussed with the community.

**Comment by gannebamm** [comment]
Since the layers will be filtered: Will this enable basic auth CSW requests? AFAIK the current implementation does not enable auth and will not show records according to the set permissions. Am I wrong?
