### ISSUE TITLE
makemessages command will set fixture translations to inactive

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#7015]
## Expected Behavior

Using `python manage.py makemessages` (like described in the docs [here](https://docs.geonode.org/en/master/contribute/translation/index.html)) creates new translation msgids. Already translated and used mgsids will stay untouched.

## Actual Behavior

Some msgids will be rendered obsolete and inactive (due to commenting them out). Those msgids are for example the iso-category strings, which are not present in a python file but kept as fixture (JSON).

## Steps to Reproduce the Problem

  1. `python manage.py makemessages`
  2.  search for ISO category strings

## Specifications

  - GeoNode version: 3.x / master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all
  - Additional details:

See this conversation: https://github.com/GeoNode/geonode/pull/6711#issuecomment-787850634

(Executive Summary from the conversation above)
This was the cause of #6984 . Some translations are part of fixtures, eg. https://github.com/GeoNode/geonode/blob/master/geonode/base/fixtures/initial_data.json#L40

As much as I discovered up to now, there is no easy way to get fixtures included in the .po files through `makemessages`. `python manage.py makemessages --help` does not show anything which would be able to make our translations working:

`-i` will ignore a module. We want to keep previously translated msgid which are not marked as gettext items anymore.

`--no-obsolete` will delete our translations instead of marking them as needed. See https://stackoverflow.com/questions/49339298/django-admin-makemessages-no-obsolete-doesnt-seem-to-be-working and documentation.

The only thing I can think of is to create a python file with the relevant fixture string and load gettext there. This will trigger makemessages and therefore keep them in the translation which is not DRY but will work. See:

https://gist.github.com/gannebamm/10cb356b93f97b47e869d394dd883e29

placing this file somewhere in the GeoNode codebase will create the iso texts from the fixtures as msgids.

**Comment by gannebamm** [comment]
I would like to create a PR for this which will:

* change the `makemessage` command to not write out locations, since those will change due to code changes (line numbers like this `#: geonode/base/__init__.py:29`) and this will create loads of noise in the commit messages. This renders it hard to spot new translations and errors (like the #6984 regression).
* Use the shown [custom_message.py](https://gist.github.com/gannebamm/10cb356b93f97b47e869d394dd883e29) file, which will activate the already translated strings.
* In a second step, I would strip the .po files from all obsolete old strings (like worldmap stuff).

By this we will have a clean and future proof `makemessage` output which is easier to maintain.

**Comment by giohappy** [comment]
@gannebamm thanks for raising this problem. My only concern is keeping that custom_message.py file, updated, but I don't see any other solution at the moment, since JSON won't let us use gettext symbols inside fixtures (that could be stripped with a custom loaddata command).

**Comment by gannebamm** [comment]
See: https://github.com/GeoNode/geonode/pull/7019
