### ISSUE TITLE
Metadata-Text and -HTML don't show for Layers with slashes in title

### ISSUE THREAD

**Issue by stefmec** [GeoNode/geonode#7024]
## Expected Behavior
Clicking on a layer, then clicking on "Download metadata" opens a popup-window. Then clicking on one of the links "Text Format" or "HTML Format" should open a web page showing the layer's metadata in HTML- or Text-Format.

## Actual Behavior
For layers with a slash in the layer title (e.g. "grid release 2/2021") you'll get the "page not found" error page.

## Steps to Reproduce the Problem
 1. Upload a layer
  2. Make the title contain a slash
  3. Click on the layer
  4. Click Download Metadata
  5. Click on "HTML Format"

Examples:
* https://master.demo.geonode.org/catalogue/csw_to_extra_format/7200de46-5cc4-11eb-810c-0242ac150008/zurich_point%20[01/2021].txt
* https://master.demo.geonode.org/catalogue/csw_to_extra_format/7200de46-5cc4-11eb-810c-0242ac150008/zurich_point%20[01/2021].html

Additional findings:
* Escaping with %2F does not help
* Changing the last part after the uid to any random text solves the problem.

## Specifications

  - GeoNode version: current
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: linux
  - Additional details:

**Comment by gannebamm** [comment]
slugifying the output does fix the issue. See #7052
