### ISSUE TITLE
Legend, Style and thumbnail do not match

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#7053]
## Expected Behavior

A layer style matches the legend and the current thumbnail

## Actual Behavior

Irregularly those three do not match

![Bildschirmfoto 2021-03-10 um 07 20 50](https://user-images.githubusercontent.com/20478652/110586061-dd5bca80-8171-11eb-8469-0d4116ef6289.png)
![Bildschirmfoto 2021-03-10 um 07 23 31](https://user-images.githubusercontent.com/20478652/110586063-df258e00-8171-11eb-85e7-c2be187dd0a3.png)

## Steps to Reproduce the Problem

  1. Fresh VM with GeoNode 3.2 dev Docker
  2. Upload the same layer several times and keep an eye on legend, style thumbnail 

I could yet not find a way how to reliably reproduce it.

## Specifications

  - GeoNode version: 3.2 dev
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): docker
  - Platform: ubuntu 2004

**Comment by gannebamm** [comment]
This is most likely linked to #7051

**Comment by afabiani** [comment]
This will be fixed by https://github.com/GeoNode/geonode/issues/7060

**Comment by afabiani** [comment]
That should be done now.
