### ISSUE TITLE
set postgis:13 tag for 3.2.x and 3.1.x

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7064]
3.2.x [https://github.com/GeoNode/geonode/blob/3.2.x/docker-compose.yml#L114](https://github.com/GeoNode/geonode/blob/3.2.x/docker-compose.yml#L114)
3.1.x [https://github.com/GeoNode/geonode/blob/3.1.x/docker-compose.yml#L5](https://github.com/GeoNode/geonode/blob/3.1.x/docker-compose.yml#L5)

**Comment by afabiani** [comment]
Done through https://github.com/GeoNode/geonode/pull/7070
