### ISSUE TITLE
Totals of results inside the facets filters don't match the total value shown in the resource list when abstract and prupose filters are set

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7067]
## Expected Behavior
The number of results at the top of the page with the list of resources must match the total counts in the type and responsible facets filters.

## Actual Behavior
The results in the page are equal or more then the counts in the filters, since facets don't take into account the `abstract` and `purpose` filters 

## Steps to Reproduce the Problem

  1. Open [https://master.demo.geonode.org/](https://master.demo.geonode.org/)
  2. search for ["ma"](https://master.demo.geonode.org/search/?title__icontains=ma&abstract__icontains=ma&purpose__icontains=ma&f_method=or&limit=5&offset=0)
  3. you get 129 results in the page (at the moment) and 64 counts inside the type filter facets

![image](https://user-images.githubusercontent.com/571129/110784735-56d6e400-826a-11eb-9e4b-1d701bbeb500.png)

## Resolution
The `abstract` and `purpose` filters must be added to the [facets tag](https://github.com/GeoNode/geonode/blob/d6f4f6289381ea5ea2815e007de1b1afea2dc5c7/geonode/base/templatetags/base_tags.py#L71).
We expect that the sum of counts for the type facets and the responsbile (owner) facets match those returned by the [search API](https://github.com/GeoNode/geonode/blob/8f61d1325a97b86d1061d0f97ae33f69cadcb5f2/geonode/api/resourcebase_api.py#L159), which is the result shown at the top of the page.

## Specifications

  - GeoNode version: 3.2.x, 3.x, master

**Comment by gannebamm** [comment]
Maybe related: If a facet is used, eg a filter by group, Keywords should get prefiltered? Currently all keywords will be listed, even those not inside the current selection.

**Comment by giohappy** [comment]
@gannebamm this is not related. AFAICS the counts are never updated without a page reload.
