### ISSUE TITLE
mixed case TopicCategories are mangled during layer upload

### ISSUE THREAD

**Issue by stefmec** [GeoNode/geonode#7068]
## Expected Behavior
Uploading a shapefile with `<gmd:MD_TopicCategoryCode>utilitiesCommunication</gmd:MD_TopicCategoryCode>` or `gmd:MD_TopicCategoryCode>plannincCadastre</gmd:MD_TopicCategoryCode>` should show up in the predefined categories.

## Actual Behavior
A new Catageory "utilitiesCommunication" resp. "plannincCadastre" without an Icon is created. The predefined categories "Utilities Communication" or "Planning Cadastre" are not used.

## Steps to Reproduce the Problem

  1. Upload a shapefile with an ISO-XML containing one of the above mentioned MD_TopicCategoryCode codes
  2. View the layer or the layers metadata

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Linux X64

**Comment by gannebamm** [comment]
Hi @stefmec 
I took a quick look at this PR. The changes will only work for syncronous uploads. See @afabiani comment on my PR regarding the UUID ingestion https://github.com/GeoNode/geonode/pull/6711#issuecomment-779709029

Therefore it does not work as expected with docker-compose, which does use async uploads.

**Comment by afabiani** [comment]
@stefmec as @gannebamm pointed out, please port the fix here too

https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/tasks.py#L327

btw, any chance to put a test in order to avoid this issue poping up again in the future?

**Comment by gannebamm** [comment]
I will help @stefmec to get the tests working and update this PR the upcoming week.
