### ISSUE TITLE
Delete existing table on restore command

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#7089]
**Is your feature request related to a problem? Please describe.**
When running the `restore` management command, the tables that are present in the DB are preserved and only some table/resources are dropped and restored.

**Describe the solution you'd like**
Let's take an example:
Tables/Resources available: `t1`, `t2` and `t3`
Backup file: `t1`, `t4`
Actual output:  `t1`, `t2` ,`t3`, `t4`
Expected output: `t1`, `t4`

Since is a restore, the idea is ( by default) to delete the existing tables in the database and then restore only the one present in the backup file.
Of course, there will be an option called `--soft-reset` that if preset will preserve all the tables & resources.

**Describe alternatives you've considered**
Manually deletion of the tables/resources that are no longer needed

**Additional context**

**Comment by afabiani** [comment]
I expect that the GeoServer catalogue will be managed accordingly, i.e.:

1. Hard restore if not `--preserve-table` option available
2. Soft restore (i.e. preserve the existing resources) if `--preserve-table` on

**Comment by mattiagiupponi** [comment]
If `--soft-reset` is present, will remove the resoures & table of geoserver

**Comment by mattiagiupponi** [comment]
Updated Documentation PR -> https://github.com/GeoNode/documentation/pull/86
