### ISSUE TITLE
Facet titles alignment

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7094]
## Actual Behavior vs Expected Behavior

When a facet title is too long and is split in two lines, the second line is not properly aligned.

![image](https://user-images.githubusercontent.com/717359/111443340-92a9f780-8709-11eb-94bd-c5a961feadd3.png)

## Steps to Reproduce the Problem

This issues is only visible with thesauri, because the labels of the other faceted filters are fixes and have been made short enough not to split.

  1. Load any thesaurus
  2. Enter in the django admin, Thesaurus (or Thesaurus Label)
  3. Set the title long enough to split in two lines
  4. Enable the "facet" checkbox

## Specifications

  - GeoNode version: 3.2, or after GNIP82

**Comment by gannebamm** [comment]
Maybe related and could be tackled while working on this one:
![grafik](https://user-images.githubusercontent.com/6172324/111445546-cb4ad080-870b-11eb-8edd-e83095d79f1d.png)

For keywords the linebreaks does not align either.

**Comment by giohappy** [comment]
yes @gannebamm we are already working on it ;)
