### ISSUE TITLE
Mandatory fields handling

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7095]
## Expected Behavior

- [ ] The editor should clearly tell which fields are mandatory
- [ ] The "mandatory" label above the tab name should turn green/red accordingly to the mandatory fields status

## Actual Behavior

The "mandatory" label stays red even if all 
The fields
- abstract field 
- thumbnail
- ..

are mandatory, but it's not advertised anywhere

## Steps to Reproduce the Problem

  1. create a document
  2.
  3.

## Specifications

  - GeoNode version: 3.2, master

**Comment by mattiagiupponi** [comment]
With the new changes, also the part related to the "Category" and "Group" will change in this way:

![image](https://user-images.githubusercontent.com/51856725/111464954-c55fea00-8721-11eb-8d5a-a846e48a07da.png)

The thumbnail (that is required for all resources) will be shown like this:

![image](https://user-images.githubusercontent.com/51856725/111465053-e88a9980-8721-11eb-8673-411c2b999250.png)

**Comment by mattiagiupponi** [comment]
Now also the title and the date follow the same behaviour of the other items in the panel:
![image](https://user-images.githubusercontent.com/51856725/111596336-59d35680-87cd-11eb-94e8-d5dfed72a26d.png)

**Comment by etj** [comment]
Missing errors for 
- date
- thesaurus

![image](https://user-images.githubusercontent.com/717359/111648770-00d2e500-8804-11eb-8f53-7ff2236b0d7b.png)
