### ISSUE TITLE
All new Styles seem to be called Default Styler, not their actual name

### ISSUE THREAD

**Issue by luorlandini** [GeoNode/geonode#7102]
## Expected Behavior
in the page layer, the name assigned by the style editor must be displayed instead of "Default Styler"

## Actual Behavior
when an user make a new style it seems to be always called "Default Styler"

## Steps to Reproduce the Problem

  1. Sign in 
  2. layers page
  3. choose a layer
  4. click on editing tools
  5. click on Create a new style, choose a style and add it
  6. back in layer page
  7. in the right side, the list style must not have the name  "Default Styler" 

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform:
  - Additional details:

**Comment by gannebamm** [comment]
I think this is behaviour is related to this fix:
If I create a new style its name will get suffixed with an UUID. See this:
![grafik](https://user-images.githubusercontent.com/6172324/111957351-328dc980-8aec-11eb-96cb-d759ccf96564.png)

https://master.demo.geonode.org/layers/geonode_master_data:geonode:testsetestest

In the style editor the name `test css` was given.

**Comment by gannebamm** [comment]
The above will get fixed, if the sld_title field gets filled via the admin interface. For CSS styles the name shall be used to fill this field on save.

**Comment by afabiani** [comment]
@gannebamm I'm going to open a specific issue (regression) for this.
