### ISSUE TITLE
Use link to resource instead of download for the documents preview

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7104]
**Is your feature request related to a problem? Please describe.**
The preview of a document resource links to the download (as attachment). Often the direct link is more useful, e.g. to use an image inside another page, application, style, etc.

![image](https://user-images.githubusercontent.com/571129/111639698-c49b8680-87fb-11eb-99a7-a23ef4375100.png)

**Describe the solution you'd like**
I propose to set make the link of the document preview point to the resource, rather then to download.

**Comment by gannebamm** [comment]
Will this have any side-effects for API / ...?
I can not think of any.

**Comment by giohappy** [comment]
Well, in my opinion the API should also return the direct link, not the download link.

**Comment by t-book** [comment]
The reason for it is to check permissions on the object level

https://github.com/GeoNode/geonode/blob/7ca60d7c650bf57214d1c9fc3775f00c56916bcd/geonode/documents/views.py#L190-L199

Besides, in my opinion, a good addition might be a file size check. For example below 3mb reply with jpeg above 3mb reply with an icon. Otherwise, people are forced to always download files that can get really large.

**Comment by giohappy** [comment]
you're @t-book..
My proposal is to adopt the "inline" content-disposition, instead of attachment. Otherwise we can implement an alternative view to get the resoure inlined instead of an attachmemt response.

I haven't investigated the configuration of the django downloadview response (it also support Nginx X-Accel if configured, and it would be very important!)

**Comment by t-book** [comment]
@giohappy I agree. There is another thing that is not optimal in my opinion. Large images are always rendered in full size: https://master.demo.geonode.org/documents/1000  (10MB for a preview;/ ) Imaging this image would weigh 100MB. Not the best User experience. Creating thumbnails would raise complexity but maybe a size check might work as well. If the size exceeds NN the user gets a link or Icon for downloading.

**Comment by giohappy** [comment]
@t-book I agree, and this is or our plans (in particular for master version), but I would split this. Changing from attachment to inline doesn't exacerbate the problem.

**Comment by giohappy** [comment]
the proposal is to create a new view, that could be `/document/link`, which behaves the same as `/document/download` but with `DownloadResponse` called with `attachment=False`, to obtain the document as inlined content-disposition instead of attachment.

This new view should be used in [these <a> tags](https://github.com/GeoNode/geonode/blob/9247796a333381a9e7bd19184afd1125a3a2de24/geonode/documents/templates/documents/document_detail.html#L38) (for any type of document), so that the user has the option to obatin and use the direct link to the document. 
The "Download Document" link will keep using the `/document/download` view
