### ISSUE TITLE
paver setup not working 

### ISSUE THREAD

**Issue by villa101101** [GeoNode/geonode#7112]
## Steps to Reproduce the Problem

  1 . paver setup
  2.
  3.

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual 
  - Platform: ubuntu 20.0.4
  - Additional details:
  
  
<img width="490" alt="Screenshot 2021-03-18 at 2 29 05 PM" src="https://user-images.githubusercontent.com/34188824/111686034-949db480-87f6-11eb-8faa-f32332467a77.png">

**Comment by afabiani** [comment]
Time to drop `spatialite` support at all IMHO

**Comment by t-book** [comment]
... has only caused problems for some time now my +1.

**Comment by villa101101** [comment]
when will it be removed ?

**Comment by t-book** [comment]
A bit dirty but at least to get it running you could try to work around it:

https://github.com/GeoNode/geonode/blob/9f1474a784682e919e70963ae1fd1da0919ff576/geonode/settings.py#L115

` spatialite_version = int(spatialite_proc.stdout.decode()[0]) if len(spatialite_proc.stdout.decode()) > 0 else 3`

Of course, it would be good to actually check what `spatialite -version` is returning

**Comment by DarkwinXXX** [comment]
Hello all,

Same problem here. I gonna try the code from @t-book!

**Comment by t-book** [comment]
@DarkwinXXX what is your output for :  `spatialite -version` (run from terminal where you also use paver start)

**Comment by DarkwinXXX** [comment]
@t-book the output is: `3.31.1 2020-01-27 19:55:54 3bfa9cc97da1059821b342961df8f5f68c7388fa117345eeb516eaa837balt1
free(): invalid pointer
Abortado ('core' generado)`

**Comment by nasrosoft** [comment]
same problem here

**Comment by nasrosoft** [comment]
> @t-book the output is: `3.31.1 2020-01-27 19:55:54 3bfa9cc97da1059821b342961df8f5f68c7388fa117345eeb516eaa837balt1 free(): invalid pointer Abortado ('core' generado)`

just restart your computer !

**Comment by t-book** [comment]
> just restart your computer !

?

**Comment by DarkwinXXX** [comment]
> 
> 
> > just restart your computer !
> 
> ?

I did it and I have the same error...

Also, I tried with your post from 23/mar and even if I was able to move forward in the setup, I had many errors which in the guided aren't present.

**Comment by nasrosoft** [comment]
> A bit dirty but at least to get it running you could try to work around it:
> 
> https://github.com/GeoNode/geonode/blob/9f1474a784682e919e70963ae1fd1da0919ff576/geonode/settings.py#L115
> 
> ` spatialite_version = int(spatialite_proc.stdout.decode()[0]) if len(spatialite_proc.stdout.decode()) > 0 else 3`
> 
> Of course, it would be good to actually check what `spatialite -version` is returning

after this this is the following error i get : 
free(): invalid pointer
---> pavement.setup
---> pavement.setup_geoserver
---> pavement.updategeoip
 python -W ignore manage.py updategeoip -o
/bin/sh: 1: python: not found


Captured Task Output:
---------------------

---> pavement.setup
---> pavement.setup_geoserver
---> pavement.updategeoip
 python -W ignore manage.py updategeoip -o

Build failed running pavement.setup: Subprocess return code: 127

**Comment by nasrosoft** [comment]
output for : spatialite -version 
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
free(): invalid pointer
Aborted (core dumped)

**Comment by t-book** [comment]
Hi @DarkwinXXX @nasrosoft  I would suggest that you do not lose time with spatialite anymore but just use PostGIS as database backend. as it comes will all major distributions it should not be too hard to set up a local instance. you can even just start the docker image ... then all you have to do is to set the env var https://github.com/GeoNode/geonode-project/blob/master/.env#L36-L37

**Comment by DarkwinXXX** [comment]
Hello @t-book 
I am just following the official Guide (https://docs.geonode.org/en/master/install/advanced/core/index.html#ubuntu-20-04lts). So, you are saying me that I don't need to do the step "3. Test the GeoNode installation" and go on with the rest? I don't need spatialite, so we going to use PostgreSQL+PostGIS.

**Comment by nasrosoft** [comment]
> Hi @DarkwinXXX @nasrosoft I would suggest that you do not lose time with spatialite anymore but just use PostGIS as database backend. as it comes will all major distributions it should not be too hard to set up a local instance. you can even just start the docker image ... then all you have to do is to set the env var https://github.com/GeoNode/geonode-project/blob/master/.env#L36-L37

tnxs a lot, it's working

**Comment by t-book** [comment]
@DarkwinXXX Exactly. The paver setup is mainly a fast and easy development setup. It will use django inbuilt dev server running on port 8000, Geoserver by use of jetty and instead of postgis spatialite. This all is done by paver defined in pavement.py  when you run `paver setup`. But in production we want Nginx handling the requests instead of Django, let tomcat serve GeoServer, and use PostGIS for data persistence. as shown the settings is the source of truth there you can define connection strings for postgis. what is worth looking at  is`paver sync`. It's running migrations and taking care of initial data: https://github.com/GeoNode/geonode/blob/master/pavement.py#L392

**Comment by afabiani** [comment]
I'm going to remove the spatialite setup from docs today, simplifying it a bit by using directly postgis.

**Comment by vbaryshev** [comment]
Danke! Ich habe auch probleme mit der spatialite (paver) in Ubuntu 20.04.2

**Comment by DarkwinXXX** [comment]
> 
> 
> I'm going to remove the spatialite setup from docs today, simplifying it a bit by using directly postgis.

@afabiani I'm working in an improvement for the guide in order to make it easier for non specialist.
