### ISSUE TITLE
Geonode is not validating client_id and client_secret sent y GeoServer on Oauth

### ISSUE THREAD

**Issue by casta1999** [GeoNode/geonode#7113]
## Expected Behavior
GeoNode should deny the token request when client_id or client_secret are incorrect

## Actual Behavior
GeoNode returns the token info even if the client_id or client_secret are incorrect

We found that api/views/verify_access_token(request, key) is not validating these two to return the token info

## Steps to Reproduce the Problem

  1. Configure any client_id or client_secret on geoserver
  2.  Access any geonode layer
  3.  Geonode/Mapstore2 renders the lauer

Dev step:
1.  post to http://<dev geonode>:8000/api/o/v4/tokeninfo/? sending a POST request with valid token value only (not including client_id and client_secret)
2. GeoNode returns the token info in Json format without validating client_id or client_secret

## Specifications

  - GeoNode version: 2.10.3 (may be happening on 3.1 as well)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: linus 18.04
  - Additional details:

**Comment by afabiani** [comment]
As far as I know if you own a valid `access_token` you don't need to validate the `client keys`. Even because the client should send the keys over again.

**Comment by casta1999** [comment]
Thanks Alessio, I will check the specification for this.
What felt strange for me is that, as geonode generates the token initially, everything works even id the client_id or secret dont match on geonode and geoserver

**Comment by afabiani** [comment]
Because the tokens are refreshed automatically when the user logins again.

If you need to make a token expire forever, the best solution is to delete it from the DB whenever you change some security setting around.

**Comment by afabiani** [comment]
If you envisage a better `refersh` mechanism, feel free to describe it here. We can implement it eventually.

**Comment by casta1999** [comment]
We reviewed the oauth flow and as Alessio states once you have an access token, clientid and clientsecret are not required to be validated.
