### ISSUE TITLE
Alternate field used as a filter in CSW getRecords

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7159]
## Actual Behavior

The `ResourceBase.alternate` field is used to find out if a Resource should be returned by a CSW `GetRecords` request.

## Expected Behavior

Such filtering should be removed, or at least documented somewhere.

## Steps to Reproduce the Problem

  1. Create a ResourceBase instance that you need to be returned by the CSW, having a null `alternate` field (you can try using a metadata service as implemented in https://github.com/geosolutions-it/geonode-csw-services)
  2. Perform a GetRecords request
  3. => the returned records do not include that one with blank `alternate` field.

## Specifications

  - GeoNode version: at least >= 3.1
  - Involved code: https://github.com/GeoNode/geonode/blob/3.1/geonode/catalogue/backends/pycsw_plugin.py#L164-L172

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/commit/c665093d949898a7a400a9e713af5a0cd8d1c159#diff-82a748c87907961bf8e42049188c4f07d98985bcd303d300c319b12dff23fee9
