### ISSUE TITLE
Downloadable ISO-XML-Metadata is invalid against GMD-Schema

### ISSUE THREAD

**Issue by stefmec** [GeoNode/geonode#7181]
## Expected Behavior
When Downloading the metadata of a layer via "Metadata Download" -> "ISO" the file must be valid against the schema in order to archive it or import into other tools.

## Actual Behavior
The Metadata is not valid:
* Element '{http://www.isotc211.org/2005/gmd}name': This element is not allowed.
* Element '{http://www.isotc211.org/2005/gmd}includedWithDataset': This element is in the wrong place.
* Element '{http://www.isotc211.org/2005/gmd}URL', attribute 'updated': The attribute 'updated' is not allowed. (only on some installations or layers?)

## Steps to Reproduce the Problem

  1. Chose a random layer from e.g. master.demo.geonode.org. Click on "Download Metadata", "ISO"; save the file as "iso-metadata.xml" (e.g. https://master.demo.geonode.org/catalogue/csw?request=GetRecordById&service=CSW&version=2.0.2&id=9980cef6-8e43-11eb-a392-3cf0116f9b71&outputschema=http%3A%2F%2Fwww.isotc211.org%2F2005%2Fgmd&elementsetname=full)
  2. Download and unzip the schema files:
  
- ``wget http://schemas.opengis.net/iso/19139/iso19139-20070417.zip``
- ``unzip unzip iso19139-20070417.zip``
- ``unzip iso19139-20070417_4-v20180321.zip  # creates `iso/19139/20070417/``
  
3. Validate the downloaded XML with xmllint
`xmllint -noout -schema iso/19139/20070417/gmd/gmd.xsd iso-metadata.xml`

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): both (?)
  - Platform: linux
  - Additional details:

**Comment by stefmec** [comment]
I already have some ideas how to fix it. I'd create a branch and propose a fix.

**Comment by stefmec** [comment]
I'm also thinking of creating a test case. But don't feel comfortable with including the schema files in the geonode repo. But including the download in the test script does not seem a good idea either. Maybe a solution like the geoserver download during setup? I'm interested in your ideas.

**Comment by etj** [comment]
Hi @stefmec 

- the `updated` attribute should have been removed with PR https://github.com/GeoNode/geonode/pull/7161
- the `includedWIthDataset` attribute is defined here https://github.com/GeoNode/geonode/blob/3.1/geonode/catalogue/templates/catalogue/full_metadata.xml#L470-L472

**Comment by d3netxer** [comment]
Any progress/news on this? I tried to do a test by removing 5 lines at https://github.com/GeoNode/geonode/blob/3.2.x/geonode/catalogue/templates/catalogue/full_metadata.xml#L189. I am using the Docker GeoNode-Project installation, and when I did ```docker-compose up -d``` the following XML was retained, but I wanted to get rid of it and test validation again: 
```
<gmd:name>
   <gco:CharacterString>geonode:LSIB</gco:CharacterString>
</gmd:name>
```
