### ISSUE TITLE
Cannot print map

### ISSUE THREAD

**Issue by villa101101** [GeoNode/geonode#7182]
## Expected Behavior
map should be printed

## Actual Behavior
error message is shown 

## Steps to Reproduce the Problem

  1.create map
  2.go to print option in the menu 
  3. select any configuration to print the map in then select print

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: ubuntu 20
  - Additional details:
  
<img width="804" alt="Screenshot 2021-03-26 at 2 55 06 PM" src="https://user-images.githubusercontent.com/34188824/112686178-9ba27380-8e43-11eb-95aa-cd573d67ada3.png">

**Comment by villa101101** [comment]
I was able to fix the issue by changing the base url in the config.yaml file located in geoserver/data/printing/config.yaml

**Comment by mradamcox** [comment]
@villa101101 If you have a minute, I'd love to learn a little more about this config setting you changed. I have updated mine and restarted geoserver, but it seems to not be used (Geonode is still getting the default `geoserver:8080` address). Thank you!

**Comment by afabiani** [comment]
@gannebamm yes, correct. Also make sure, as usual, that the GeoServer proxy base url is also correct from the `global.xml`

**Comment by mradamcox** [comment]
@afabiani Thanks for that comment, in my data directory's `global.xml` the proxyBaseUrl wasn't set properly (still had the default) so I updated that. I am surprised by this though, I would have thought that file's content to follow what has been entered in the UI?
@villa101101 Thanks, I'm looking at my .env file now and I don't actually see a variable like this (non-Docker install). Do you mean [this one](https://github.com/GeoNode/geonode/blob/2f18e0260dc750793e8be53b7a8f664c86c17ed1/geonode/settings.py#L1261)? I'll try adding that when I can look at this next.

**Comment by giohappy** [comment]
Apparently the proxybaseurl configuration for Docker has a regression. We also noticed something strange yesterday.
We're going to investigate it.

**Comment by gannebamm** [comment]
I just changed the files according to https://github.com/GeoNode/geonode/issues/7182#issuecomment-1084313843 @afabiani and it works fine.

Had to cp the files into the docker volume but after I've done that it was working

**Comment by mradamcox** [comment]
Well that `PROXY_URL` does pull from the environment, but I looked more at the docs for it and it does not seem like the right variable for this issue anyway.

So in my .env I have
```
export GEOSERVER_WEB_UI_LOCATION=https://oldinsurancemaps.net/geoserver/
export GEOSERVER_PUBLIC_LOCATION=https://oldinsurancemaps.net/geoserver/
export GEOSERVER_LOCATION=https://oldinsurancemaps.net/geoserver/
```
and this works in production for everything, it seems, except printing. So I should change that last one to localhost?

(I am not using docker, and I just use `source .env` before starting the app and then [cascading all of the variables](https://github.com/mradamcox/loc-insurancemaps/blob/main/loc_insurancemaps/management/commands/configure.py) to various configuration files like uwsqi.ini, etc... hence the `export` statements. I _think_ this is a decent setup but I may be missing something.)

**Comment by villa101101** [comment]
Trying using the localhost for the last URL .

**Comment by mradamcox** [comment]
Thanks, I will when I get a chance. Looking further, I realize I haven't updated the `GEOSERVER_JAVA_OPTS` variable at all in my installation, because I have these settings defined within tomcat. However, maybe the default value of that variable in GeoNode is overriding what I have in tomcat.

**Comment by gannebamm** [comment]
I did not see anything which overwrites or envsubstitutes the printing config.yaml
/geoserver_data/data/printing/config.yml

Depending on where you have that one (in tomcat as web app?) you should be able to just change its contents.

From a deployment perspective this should be done in entrypoint.sh for docker and... Dunno, manually 🤷🏼‍♂️ for non docker deployments?

**Comment by mradamcox** [comment]
Oh. I just realized I had updated the `printing/config.yaml` in the default geoserver data directory within tomcat, not the external one that is actually in use :facepalm: I bet that will fix it once I can restart the service, I'll report back. Thanks for the help everyone.

**Comment by mradamcox** [comment]
Ok, I can confirm that updating the (correct) config.yaml file **did** work for me, so thanks again for the pointers. I still have one lingering environment variable causing some issue, but that's an issue on my end.
