### ISSUE TITLE
SLD and XML file are not recognized and applied when uploaded with a layer 

### ISSUE THREAD

**Issue by N-SunHing** [GeoNode/geonode#7210]
## Expected Behavior
When uploading an SLD or XML file it should be recognized and the files should change the styles or apply the metadata to the layer respectively

## Actual Behavior
These files are not recognized and are not uploaded with the accompanied layer
![image](https://user-images.githubusercontent.com/79317490/113118823-1edf1300-9210-11eb-9079-4e4adcb2425c.png)
The layer can be edited and the SLD file can be applied in the "Editing Tools" menu after the layer has been added and it is supported then. The XML layer cannot be added and when applied in the "Editing Tools" menu the metadata file uploads as a separate file instead of being applied to the layer being edited
## Steps to Reproduce the Problem

  1. Select upload a layer from the data drop down  
  2. Choose the layer file with the accompanying SLD file or XML file 
  3. Click on upload
  4. Go to the uploaded layer and edit the layer
  5. Apply the SLD file and then the XML file

## Specifications

  - GeoNode version: Master demo at https://master.demo.geonode.org/
  - Platform: Windows

**Comment by gannebamm** [comment]
The filenames must be identical with the uploaded layer name. Eg.:

yourShapefile.shp
yourShapefile.shx
yourShapefile.dbf
yourShapefile.xml
yourShapefile.sld

should work.

Even though it should work, it is not intuitive?

**Comment by NyakudyaA** [comment]
@gannebamm Perhaps this should also be documented
