### ISSUE TITLE
Unable to replace layer using a layer with a different name to the existing layer

### ISSUE THREAD

**Issue by N-SunHing** [GeoNode/geonode#7213]
## Expected Behavior
In the Geonode documentation there is an activity where the roads layer is replaced with the railway layer please check link: https://docs.geonode.org/en/master/usage/managing_layers/layer_editing.html

![image](https://user-images.githubusercontent.com/79317490/113301176-04d02e00-92ff-11eb-98af-5ce218b55187.png)
I have tried this but experienced an error
## Actual Behavior
An error message appear that reads the following
![image](https://user-images.githubusercontent.com/79317490/113301309-2e895500-92ff-11eb-9bee-d8006f428b70.png)

## Steps to Reproduce the Problem

  1. Upload a layer file to geonode
  2. Once the layer has been uploaded go to the editing tools and replace layer option
  3. Choose the layer that you wish to replace the existing layer with (the one with a different name)

## Specifications

  - GeoNode version: Master Demo version
  - Platform: Windows

**Comment by NyakudyaA** [comment]
If this is the intended behaviour can we either update the documentation and reflect this.

**Comment by afabiani** [comment]
This is the intended behavior. It is not possible to replace a layer with a different one. The name and the schema must be the same.

I agree that the documentation should be updated accordingly.

**Comment by giohappy** [comment]
@NyakudyaA you can open an issue on https://github.com/GeoNode/documentation and, if possible, submit a PR with the improvements.
