### ISSUE TITLE
Harmonize/improve metadata editing pages

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7224]
## Expected Behavior

Layers, Map and Documents metadata editor pages should all look the same.

## Actual Behavior

Here the editing pages for a Layer, a Map and a Document:

![image](https://user-images.githubusercontent.com/717359/113325643-0149a080-9319-11eb-99a4-592dd67f2776.png)

- Field description
  - Layer has a (?) icon, and hovering over the icon the description is shown
  - Map and Document have the description just below the text field
- Back to resource
  - Layer has a button "Back to layer"
  - Map and Document do not have such button
- Text field resizing (see images in next comment)
  - Layer and map text fields shrink when window is enlarged
  - Document text fields keeps the same size

Other issues relates to all three editing pages:
- spacing around thesaurus entries and topic category should be fixed
- mandatory fields handling is different than the editing wizard

## Specifications

  - GeoNode version: master (as of 2021-04), 3.2.x

**Comment by etj** [comment]
# Textfield resizing: base size  
![image](https://user-images.githubusercontent.com/717359/113326275-be3bfd00-9319-11eb-809f-ee35ca580847.png)

# Textfield resizing: windows enlarged, text field shrunk
![image](https://user-images.githubusercontent.com/717359/113326369-db70cb80-9319-11eb-84de-f43dcd9ef138.png)

**Comment by mattiagiupponi** [comment]
- [ ] TextField resizing
- [ ] Field description

- [ ]  Layer has a (?) icon, and hovering over the icon the description is shown
Map and Document have the description just below the text field
Back to resource

- [ ] Layer has a button "Back to layer"
Map and Document do not have such button
Text field resizing (see images in next comment)

- [ ] Layer and map text fields shrink when window is enlarged
Document text fields keeps the same size
Other issues relates to all three editing pages:

- [ ] spacing around thesaurus entries and topic category should be fixed

- [ ] mandatory fields handling is different than the editing wizard
