### ISSUE TITLE
Style Editor will not allow editing saved style again

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#7265]
## Expected Behavior

After saving my style I will be able to edit it again to fix errors.

## Actual Behavior

The style will not load:

![grafik](https://user-images.githubusercontent.com/6172324/114061921-3a44c080-9897-11eb-95ea-e8f1e9b4d6be.png)

## Steps to Reproduce the Problem

  1. create new style from template (css)
  2. save style
  3. try to edit it again

## Specifications

  - GeoNode version: 3.2 (master.demo.geonode.org)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@gannebamm we're going to make some tests with UTF-8 chars. We suspect this is connected to https://github.com/GeoNode/geonode/issues/7267.
I'm going to move both the issues to the mapstore client repo.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #121](https://github.com/GeoNode/geonode-mapstore-client/issues/121) via [**ZenHub**](https://www.zenhub.com/)
