### ISSUE TITLE
Unable to edit symbol of css style

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#7266]
## Expected Behavior
Clicking the symbol will open a list of possible symbols.

## Actual Behavior

clicking the symbol will not open the dropdown list:
![grafik](https://user-images.githubusercontent.com/6172324/114062166-8132b600-9897-11eb-9de1-ec1436886bf0.png)

## Steps to Reproduce the Problem

  1. create new style
  2. add renderer
  3. try to change the symbol

## Specifications

  - GeoNode version: 3.2 (master.demo.geonode.org)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #118](https://github.com/GeoNode/geonode-mapstore-client/issues/118) via [**ZenHub**](https://www.zenhub.com/)
