### ISSUE TITLE
Legend graphics will not render UTF-8 characters (eg. äöü)

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#7267]
## Expected Behavior

My style label will be rendered in the legend graphic.

## Actual Behavior

UTF-8 characters, like german Umlaute (üöä), will not render properly:

![grafik](https://user-images.githubusercontent.com/6172324/114062363-b8a16280-9897-11eb-9a8d-f4a144dcd76c.png)

## Steps to Reproduce the Problem

  1. create a style
  2. change the label to something with UTF-8 characters 'öäü'
  3. check the preview of the legend graphic

## Specifications

  - GeoNode version: 3.2 (master.demo.geonode.org)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #122](https://github.com/GeoNode/geonode-mapstore-client/issues/122) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gannebamm** [comment]
Since this will render layers broken I would like to close this if the issue  https://github.com/GeoNode/geonode-mapstore-client/issues/122 is closed. I tested again and quickly made my layer useless by using UTF-8 chars ('öäü')

**Comment by giohappy** [comment]
@gannebamm you added the regression label. Are you sure it was working before?

**Comment by gannebamm** [comment]
I am quite sure, but will try to get an old version running to test.

**Comment by gannebamm** [comment]
My old Node refused to build. Will check a different one tomorrow. @t-book Did you ever come across the issue above? We had working UTF-8 legends, didn´t we?

**Comment by t-book** [comment]
I cannot say for sure. But yes I do darkly remember broken utf 8 legends.

**Comment by gannebamm** [comment]
I was unable to pin it to an regression. My 3.0 GeoNode has the same issues. But I think they worked with 2.10.x and GeoExplorer. Nonetheless I will change the labels

**Comment by giohappy** [comment]
@bieganowski we should check if something goes wrong with the charset inside geoserver-proxy, when the style REST request passes through it.

**Comment by bieganowski** [comment]
**Investigation results**

`gs` proxy decodes incoming request's data to replace Geoserver location:
- https://github.com/GeoNode/geonode/blob/edf64701d2c244ab8caa2079b90117fa944d2218/geonode/proxy/views.py#L172
- https://github.com/GeoNode/geonode/blob/edf64701d2c244ab8caa2079b90117fa944d2218/geonode/proxy/views.py#L180-L182

and this causes issues when sending it later on with `http_client`:
- https://github.com/GeoNode/geonode/blob/edf64701d2c244ab8caa2079b90117fa944d2218/geonode/proxy/views.py#L184-L190

simply decoding data before sending it should solve the issue:
![image](https://user-images.githubusercontent.com/57660086/116533499-bb650580-a8e1-11eb-9ef3-5f8e21636365.png)

**Comment by gannebamm** [comment]
tested and confirmed. Thanks @bieganowski
