### ISSUE TITLE
Users information leak

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#7269]
## Expected Behavior

Only administrators must be able to retrieve a full list of users including their personal information.

## Actual Behavior

GeoNode's /owners API endpoint returns the full list of users, including their personal information (!!!!).

## Steps to Reproduce the Problem

  1. Go to layers page
  2. On inspect, In the network tab, Check response for owners request. The list returned includes all attributes on a user.
  3. Also check on the user's profile, more information is provided.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Closing in favour of https://github.com/GeoNode/geonode/issues/7282
