### ISSUE TITLE
Missleading message on upload

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#7289]
The reworked upload is showing the following message:

![Bildschirmfoto von 2021-04-12 18-01-25](https://user-images.githubusercontent.com/20478652/114425732-a71eca00-9bb9-11eb-8f8d-c0372354cbf2.png)

"You have the following incomplete uploads:" is misleading as the actual upload finished and is 100% complete.
As an easy fix I'd like to suggest to completely remove

https://github.com/GeoNode/geonode/blob/0c19159beed5585059c95e0e6fdb9356b7a35f97/geonode/layers/templates/upload/layer_upload.html#L41

and replace

https://github.com/GeoNode/geonode/blob/0c19159beed5585059c95e0e6fdb9356b7a35f97/geonode/layers/templates/upload/layer_upload.html#L40

with "Upload status:"

**Comment by afabiani** [comment]
+1 thanks @t-book
