### ISSUE TITLE
REST API v2 endpoint for GeoStories throws an exception

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#7294]
## Expected Behavior
Hitting https://master.demo.geonode.org/api/v2/geostories I expect to see the list of GeoStories 

## Actual Behavior
I'm getting an error
![image](https://user-images.githubusercontent.com/1278021/114568008-0f31e680-9c74-11eb-818c-2aad73a7d9c8.png)

## Steps to Reproduce the Problem

  1. Log in a s superuser
  2. Go to <geonode>/api/v2/geostories
  3. It will rise an exception

## Specifications

  - GeoNode version: 3.2.0
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): any
  - Platform: any
  - Additional details:

**Comment by t-book** [comment]
Strange that https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/api/tests.py#L137 did not catch it?!

**Comment by afabiani** [comment]
That's because the generic one https://master.demo.geonode.org/api/v2/geoapps works fine

**Comment by t-book** [comment]
I see. there cannot be enough tests ...

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode-mapstore-client/issues/130
