### ISSUE TITLE
Primary keys of tables not carried over on Backup-Restore

### ISSUE THREAD

**Issue by jcaceres85** [GeoNode/geonode#7301]
## Expected Behavior
Update from Geonode 3.0 to 3.1, using commandos Backup/Restored. Keep same functionality, styles, layers and Maps.

## Actual Behavior
Everything looks good in the Web interface, however, trying a WFS request to geoserver has the following error:

java.io.IOException
java.lang.RuntimeException: java.io.IOException
java.io.IOExceptionCannot do natural order without a primary key, please add it or specify a manual sort over existing

Looking at the tables in the database (geonode_data) none of the tables have a defined primary key field, causing the error.

To fix the problem I had perform pg_dump on old database, delete all tables created after the Restore commando, and dump the old database into the new one. So it maybe something from the Backup/Restore commando that doesn't get carried over.

## Steps to Reproduce the Problem

  1. Run python manage.py backup command on old version.
  2. Update Geonode to new version
  3. Run python manage.py restore on new deployment
  4. Perform a WFS request to the Geoserver

## Specifications

  - GeoNode version: 3.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: Ubuntu 20.04
  - Additional details: The layers looks good inside the Geonode, with the right amount of features in each layers, however, establishing a WFS connection from QGIS generates duplicate features and no modification to the layer can be perform from QGIS.

**Comment by giohappy** [comment]
The B/R mechanism has been refactored and enhanced a lot in recent versions. No activities are planned for the versions mentioned in this issue.
