### ISSUE TITLE
Missing cache in layers loaded on geonode

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7311]
Displaying a newly added layer the cache is always missing. This is the reason reported in the console:

> geowebcache-cache-result: MISS
geowebcache-miss-reason: exception occurred: ParameterException: Style 'states1' is invalid.

![cache.png](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/4bd07a4e-4a28-4e73-af0a-e5b04e319123)

**How to reproduce**
- Open [this layer](https://master.demo.geonode.org/layers/geonode_master_data:geonode:states1)
- Click on View Layer
- Open the console on Network

*Current Result*
The layer is not cached. 

*Expected Result*
The layer is cached.

**Comment by giohappy** [comment]
The problem is that the style name inside the STYLES parameter of the GetMap request doesn't contain the workspace prefix.
I suppose the WMS service assumes the workspace from the request subpath, while GWC uses the style name strictly. 

Without workspace:
 - [https://master.demo.geonode.org/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Ane_110m_admin_0_boundary_lines_land&STYLES=ne_110m_admin_0_boundary_lines_land&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=-20037508.342789244%2C0%2C0%2C20037508.342789244](https://master.demo.geonode.org/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Ane_110m_admin_0_boundary_lines_land&STYLES=ne_110m_admin_0_boundary_lines_land&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=-20037508.342789244%2C0%2C0%2C20037508.342789244)
 -  `exception occurred: ParameterException: Style 'ne_110m_admin_0_boundary_lines_land' is invalid`

With workspace:
 - [https://master.demo.geonode.org/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Ane_110m_admin_0_boundary_lines_land&STYLES=geonode:ne_110m_admin_0_boundary_lines_land&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=-20037508.342789244%2C0%2C0%2C20037508.342789244](https://master.demo.geonode.org/geoserver/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=geonode%3Ane_110m_admin_0_boundary_lines_land&STYLES=geonode:ne_110m_admin_0_boundary_lines_land&SRS=EPSG%3A3857&CRS=EPSG%3A3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=-20037508.342789244%2C0%2C0%2C20037508.342789244)
 - cache MISS

This is what happens for saved maps:

 - MapStore includes the workspace prefix for the layer style name inside the map configuration when a map is saved.
 - The mapstore adatapter [sets the capability['style']](https://github.com/GeoNode/geonode-mapstore-client/blob/0a4f0013094f1d1640d7c936a39c2d94d1c91642/mapstore2_adapter/plugins/serializers.py#L201) inside the MapLayer's layer_params 
 - When the map is viewed, the style for the layer [is retrieved from the capaibilities](https://github.com/GeoNode/geonode-mapstore-client/blob/0a4f0013094f1d1640d7c936a39c2d94d1c91642/mapstore2_adapter/plugins/geonode.py#L360) and it contains the workspace prefix
 - Everything is fine afterwards

However, for layer previews and new maps, a map configuration is generated by GeoNode "on the fly". In this case the style name [that is injected](https://github.com/GeoNode/geonode/blob/c9de9e04d13ca42f3ab9a875679acf5d4924eaf4/geonode/layers/views.py#L500) is the layer's default style name without the prefix. [The same happens](https://github.com/GeoNode/geonode/blob/c9de9e04d13ca42f3ab9a875679acf5d4924eaf4/geonode/maps/views.py#L893) when the context for a new map is created.

In both cases probably we can safely set the style to an empty string `"style": ''`, since it's fine to use an empty value for the style in case it is the default style.

@marthamareal please verify if this fix would be fine and it doesn't break the map legend logic.
A small fix to the map legend template is probably required, because if I'm not wrong you need the style name to show it inside the sidebar. Moreover, the current way of treating style names always result in names with hash suffixes, etc. Until we don't solve it we could hide the style name and just show the legend image.

**Comment by marthamareal** [comment]
> please verify if this fix would be fine and it doesn't break the map legend logic.
> A small fix to the map legend template is probably required, because if I'm not wrong you need the style name to show it inside the sidebar.

On getting the legend on MapLayer, [this](https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L588) checks if the style is an empty string or None and it will default to using the default of the Layer. Therefore i do not expect the change to affect the map-legend display.
