### ISSUE TITLE
Thumbnail generation fails for remote services

### ISSUE THREAD

**Issue by bieganowski** [GeoNode/geonode#7336]
## Expected Behavior
Correct thumbnail generation

## Actual Behavior
`MISSING_THUMBNAIL` is assigned to a remote layer on importing remote resources.

## Steps to Reproduce the Problem
Example for https://master.demo.geonode.org/ with resources from: httpwww502regionetoscanaitwmsrastercomrtwmsrtmapwmsmapwmsofcmap_resolution91languageita

  1. Connect to the external service
  2. Import layer named `OFC 2013 col`
  3. Thumbnail generation fails with logs:
  ```
  Task geonode.geoserver.tasks.geoserver_create_thumbnail[76890f80-131a-4a8b-8a20-78fc7e9814e1] retry: Retry in 180s: ValueError('bad transparency mask')
  ```

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): master demo
  - Platform:
  - Additional details:

**Comment by bieganowski** [comment]
In some cases, error is caused by a wrong mode of the retrieved [image](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste). Correct modes are: `1`, `P` and `RGBA`.

**Comment by giohappy** [comment]
The problem is caused by the new version of Pillow, which was [bumped to 8.2.0](https://github.com/GeoNode/geonode/pull/7219) 2 weeks ago.
@afabiani let's be careful with these automated updates.

**Comment by afabiani** [comment]
I see. Sorry, no breaking changes were declared by the new version.
