### ISSUE TITLE
Fix the HTML for the italian translation of the "developers" page

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7338]
HTML inside the italian django.po must be fixed (empty elements, missing closings, etc.)

**English page**
![image](https://user-images.githubusercontent.com/571129/115029979-da699d80-9ec6-11eb-9940-bb1ab62da740.png)

**Italian page**
![image](https://user-images.githubusercontent.com/571129/115030010-e35a6f00-9ec6-11eb-9c1d-d7f07e3b4cda.png)

**Comment by etj** [comment]
Python keywords should not be translated.
Added some notes in the merged PR.

**Comment by giohappy** [comment]
Waiting for the backport to 3.2.x before closing @mattiagiupponi

**Comment by mattiagiupponi** [comment]
> Waiting for the backport to 3.2.x before closing @mattiagiupponi

It's aready merged by alessio https://github.com/GeoNode/geonode/commit/b240a07de5b01be8730436afc303d0ab3097e54e

**Comment by giohappy** [comment]
oh ok, I missed that.
@e moving to Done. We will close it when we have deployed the update.
