### ISSUE TITLE
Migration breaks layers as bbox is not calculated correctly

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#7342]
## Expected Behavior

Migration should correctly calculate bbox from `bbox_x0, bbox_y0, bbox_x1, bbox_y1`

## Actual Behavior

bbox stays empty as it looks like the base app migrations run before layers and the fields get removed before they can get calculated.

<img width="583" alt="Bildschirmfoto 2021-04-20 um 20 30 51" src="https://user-images.githubusercontent.com/20478652/115446427-7ec94800-a217-11eb-93d0-662e21472808.png">

## Solution 

Add a dependency to base migration that it waits until layers is finished

## Steps to Reproduce the Problem

  1. Try to migrate an instance from 2.10 to 3.2
  2. the map will stay empty and no map is shown for bounding boxes in Django admin /layers

## Specifications

  - GeoNode version:  3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker but all will be affected
  - Platform: Ubuntu

**Comment by t-book** [comment]
I'm unsure about this but from the migration table the layers migration runs after the base migration which removes the box fields?

<img width="583" alt="Bildschirmfoto 2021-04-20 um 20 30 51" src="https://user-images.githubusercontent.com/20478652/115446427-7ec94800-a217-11eb-93d0-662e21472808.png">

**Comment by afabiani** [comment]
@t-book FWI through [this](https://github.com/GeoNode/geonode/commit/878442e86aaea83eb2a99e2be09ddf90b4a08b73) commit GeoNode is able to:

1. Regenerate automatically the bbox from GeoServer whenever the bbox_polygon is None
2. Allow the "set_metadata_layers -d" management command to force the BBOX update and synchronization with GeoServer

**Comment by t-book** [comment]
@afabiani thanks. but still it looks that the migration is missing a dependency:

```
diff --git a/geonode/base/migrations/0045_auto_20200507_0445.py b/geonode/base/migrations/0045_auto_20200507_0445.py
index 45864d705..7f639e3a3 100644
--- a/geonode/base/migrations/0045_auto_20200507_0445.py
+++ b/geonode/base/migrations/0045_auto_20200507_0445.py
@@ -7,6 +7,7 @@ class Migration(migrations.Migration):
 
     dependencies = [
         ('base', '0044_resourcebase_bbox_polygon'),
+        ('layers', '0028_auto_20200323_1945'),
     ]
 
     operations = [
```

If I'm right, we have two possible ways:

- fixing the migration
- updating the docs for all users who migrate and ask to run the management command.

I tend to fix the migration as it looks a bit cleaner to me.

**Comment by t-book** [comment]
(just tested fixing the migration dependency worked for me )

**Comment by afabiani** [comment]
@t-book sure, the migration should be fixed
