### ISSUE TITLE
Allow GWC to refresh the gridsets bounds dynamically in order to avoid breaking the TiledLayer configuration

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#7358]
Integrated GWC in GeoServer computes the gridsets bounds of the Tiled Layer automatically whenever the tile configuration is enabled.

The bounds are set to the layer ones and aligned to the gridsets projection and resolutions.

In order to allow GWC to compute the bounds dynamically, GeoNode should simply send back the tiledlayer configuration by specifying the default gridsets without any fixed extent.

**Comment by t-book** [comment]
this is very good 👍

**Comment by afabiani** [comment]
Use the management command 

`sync_geonode_layers --updatepermissions`

in order to allow GeoNode automatically fix the GWC TiledLayers, if needed.
