### ISSUE TITLE
ogr2ogr shipped with docker image  doesn't work with PostgreSQL 12 +

### ISSUE THREAD

**Issue by ahmednoureldeen** [GeoNode/geonode#7362]
## Expected Behavior
ogr2ogr shipped with docker image should be compatible with PostgreSQL 13 

all issue details [here](https://github.com/OSGeo/gdal/issues/1692)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 3.1
  - Installation method  GeoNode Docker:
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
Are there alternatives to let Dockerfile compile proj and GDAL 3.2.1 sources?
