### ISSUE TITLE
GNIP 88: Upgrade from Django 2.2 to 3.2

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#7366]
# GNIP 88: Upgrade from Django 2.2 to 3.2

## Overview

As described in this [post](https://docs.djangoproject.com/en/3.2/releases/3.2/), the support for the Django version 2.2 will end in April 2022. The new LTS version will be the 3.2

### Proposed By

@mattiagiupponi 
@giohappy 

### Assigned to Release

This proposal is for the GeoNode master.

### State

* [x] Under Discussion
* [x] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation
Since version 2.2 will be deprecated the next year, is better to upgrade to the new TLS version.

## Proposal

Django provides a sort of [guide](https://docs.djangoproject.com/en/3.2/howto/upgrade-version/) to upgrade with some steps to follow. After this, the steps are:
- upgrade Django from 2.2 to 3.2
- upgrade GeoNode dependencies
- Fix the code that is no more compatible or deprecated (ex: `lxml ` (deprecated) or `from django.utils import six` (removed) )

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani: 👍
* Francesco Bartoli:
* Giovanni Allegri: 👍
* Simone Dalmasso:
* Toni Schoenbuchner: 👍 
* Florian Hoedt: 👍

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by t-book** [comment]
thanks @mattiagiupponi please don't forget to label GNIPs and to create an entry here: https://github.com/GeoNode/geonode/wiki/GeoNode-Improvement-Proposals (already done)
