### ISSUE TITLE
Thesauri in metadata details

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7377]
**Is your feature request related to a problem? Please describe.**

Thesauri keywords are displayed along with free keyword, without any categorization.

**Describe the solution you'd like**

Thesauri keywords should be grouped, showing the thesaurus they belong to.
This change should be implemented in both:
- layer info
- metadata detail page.

Note that thesauri titles and keywords should be localized:
- use `ThesaurusLabel` for localization and fallback to `Thesaurus.title`; 
- use use `ThesaurusKeywordLabel` for localization and fallback to `ThesaurusKeyword.alt_title`

e.g.:

![image](https://user-images.githubusercontent.com/717359/115892044-123c8c00-a457-11eb-9300-1dcc070aa72d.png)

This could be implemented by placing entries in a `<ul>` :
```html
<dd>
   <ul>
      <li>free kw 1</li>
      <li>free kw 2</li>
      <li>free kw 3</li>
      <li>Thesaurus title 1
         <ul>
            <li>item1</li>
            <li>item2</li>
         </ul>
      </li>
      <li>Thesaurus title 2
         <ul>
            <li>item3</li>
            <li>item4</li>
         </ul>
      </li>
   </ul>   
</dd>
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mattiagiupponi** [comment]
Here is an example of how the keywords will be displayed:
Layer info:
![image](https://user-images.githubusercontent.com/51856725/116226989-ec173480-a753-11eb-9ead-83e74cc9744c.png)

Medatata details:
![image](https://user-images.githubusercontent.com/51856725/116227019-f33e4280-a753-11eb-82ae-f17501455c6d.png)

Is this fine @etj ?

**Comment by etj** [comment]
It looks really good to me.
I would like to hear from @giohappy and @afabiani about the layer info page, where keywords may take a very large portion of the page.
