### ISSUE TITLE
HTTP Status 401 - Unauthorized

### ISSUE THREAD

**Issue by KAWAMALA** [GeoNode/geonode#7378]
![401](https://user-images.githubusercontent.com/65165225/115895058-ab24d480-a462-11eb-8ba1-5c55239a7afb.JPG)
Every time i try to upload data to geonode as Admin or User it pops up with that error,
Anyone with the solution i would appreciate.

**Comment by t-book** [comment]
Most likely the connection credentials for GeoServer that Django is using are incorrect.  https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L977-L983

**Comment by afabiani** [comment]
Please send detailed logs and stacktraces.
