### ISSUE TITLE
MapLegend shows wrong legend instead od the selected (default) style

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7391]
[test_e](https://master.demo.geonode.org/maps/1548) uses [Swe_sea_ports_points](https://master.demo.geonode.org/layers/geonode:hotosm_swe_sea_ports_points) layer.

- Swe_sea_ports_points -> default_style -> hotosm_swe_sea_ports_points
- The map uses the layer's default style (Fig.1) but the Map Legend shows the other style (Fig.2).

Apprently the information is stored correctly:

- The layer instance has the default style correctly associated
- The MapLayer layer_params have the style set to an empy string (being the default style).

@marthamareal please investigate why the non default style is used instead inside the legend of the map detail page 

**Fig.1**
![image](https://user-images.githubusercontent.com/571129/116115930-e0c3fa80-a6ba-11eb-869b-61e59e8b768b.png)

**Fig.2**
![image](https://user-images.githubusercontent.com/571129/116116025-f9ccab80-a6ba-11eb-8e43-439cf7eb5f16.png)

**Comment by marthamareal** [comment]
@giohappy, can you make this visible, am unable to access both map and layer.
