### ISSUE TITLE
Capability to import multiple documents at once

### ISSUE THREAD

**Issue by ppasq** [GeoNode/geonode#7418]
**Is your feature request related to a problem? Please describe.**
Some users may want to publish an archive of several documents (e.g. pdf maps, old map scans, reports etc.). Currently the only way is to upload the documents one by one. If the number of files is not small it requires a large amount of time.

**Describe the solution you'd like**
A solution could be to make available an importdocuments management command equivalent to [importlayers](https://docs.geonode.org/en/master/admin/mgmt_commands/index.html#management-command-importlayers).
Ideally, the Upload Document page can be also improved with the capability to import different files stored in a single folder.

**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by gannebamm** [comment]
@t-book and I had a brief discussion about that. Maybe we should use the new REST API for that. There is some news on the documentation side of things: https://github.com/GeoNode/documentation/pull/93

I hope we will have some spare resources in July to start with this improvement.
