### ISSUE TITLE
Update of a GeoApp metadata returns a JSON message instead of redirecting to the GeoApp page

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7456]
## Expected Behavior
When hitting the "Update" button either from a GeoAppsì Advanced Metadata edit or the Metadata Wizard page the user is redirected to the GepApp detail page.

## Actual Behavior
A JSON string is retrurned. E.g.:

`{"message": 1739}`

## Steps to Reproduce the Problem

  1. Open any GeoApp (GeoStory)
  2. Click Editing Tools -> (Metadata) Advanced Edit
  3. Change a value
  4. Click the Update button
  5. The JSON string is returned

## Specifications

  - GeoNode version: 3.2.x, master
  - Installation method (manual, GeoNode Docker)

**Comment by marthamareal** [comment]
@giohappy, The update on this form makes a POST request, should we also consider changing it to make a PATCH?

**Comment by giohappy** [comment]
@afabiani do you know if we're returning a JSON for the MapStore client purposes?
Anyway @marthamareal we chould change the response type depending if the request is an ajax request or not (`request.is_ajax()`)

**Comment by marthamareal** [comment]
@giohappy  this is already dome [here](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L433)

**Comment by giohappy** [comment]
That's curious. So why the request from the browser is treated as ajax? A flow in Django?

**Comment by marthamareal** [comment]
> That's curious. So why the request from the browser is treated as ajax? A flow in Django?

It's True by default, [here](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L310)

**Comment by giohappy** [comment]
why is it set as a parameter on that request? Shouldn't it be set by Django as a request property???

**Comment by giohappy** [comment]
@allyoucanmap is the mapstore client using this view somehow and set this property explicitely?

**Comment by marthamareal** [comment]
The js is supposed to handle the response and then display the detail page.
However checking with my local and console, this line throws an error https://github.com/GeoNode/geonode/blob/master/geonode/templates/metadata_form_js.html#L26 and then wrong display.

**Comment by marthamareal** [comment]
@giohappy  passing the `UI_MANDATORY_FIELDS` context [here](https://github.com/GeoNode/geonode/blob/master/geonode/geoapps/views.py#L518) solves the issue. should i continue with it?

This is also done for layers maps and documents eg [here](https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L1262)
