### ISSUE TITLE
Missing language on dropdown

### ISSUE THREAD

**Issue by sir-onze** [GeoNode/geonode#7528]
## Expected Behavior
To appear all the languages available to choose in the home page (I need portuguese ;) )

<img width="173" alt="imagem" src="https://user-images.githubusercontent.com/26677486/117957698-3b439480-b312-11eb-8d7b-dc0c46ed9b06.png">

## Actual Behavior
In the home page of version 3.2 is expected to appear all the languages available to choose but it only appears 5, English, French,Spanish,German and Italian.

## Steps to Reproduce the Problem

  1. Install using docker geonode 
  2. Go to home page
  3. Select language

## Specifications

  - GeoNode version: 3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform: Ubuntu 18.04
  - Additional details:

**Comment by t-book** [comment]
my -1. it is super easy to enable every language that you need: https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L225 

unfortunately most of them are outdated which should not show up for all if not needed.

**Comment by sir-onze** [comment]
Thanks for the answer, it makes sense, so if i put in my .env something like this : 
![imagem](https://user-images.githubusercontent.com/26677486/117962550-40571280-b317-11eb-9595-8ab28eb0ed45.png)
I should have get in the menu only the options for pt and en ? I still get the same behaviour. I know portguese works because in the admin menu i can change it via url :
<img width="836" alt="imagem" src="https://user-images.githubusercontent.com/26677486/117962796-857b4480-b317-11eb-9d83-72e30eb42aef.png">
I am looking for a way(does not matter if hard coded to show the pt in that dropdown ), then i can change the .po to apply better translations.

**Comment by t-book** [comment]
my guess is that either you have
a) to rebuild the container (hopefully not the whole image)
b) clear your browser cache

the .env var is correct

**Comment by allyoucanmap** [comment]
@t-book @sir-onze I just noticed that the screenshot in the description seems to show the new homepage enabled by default on **master** version of GeoNode.
The GeoNode **3.2.x should not enable this homepage by default because it should target the version 2.1.x of geonode-mapstore-client** https://github.com/GeoNode/geonode-mapstore-client/tree/2.1.x.

The current homepage extends only 5 of the [supported langugage of MapStore](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/LocaleUtils.js#L12-L22) so I just opened an issue to improve this part on geonode-mapstore-client side https://github.com/GeoNode/geonode-mapstore-client/issues/170 .

**Comment by giohappy** [comment]
I assume that your intention @sir-onze is to use GeoNode 3.2.x and not master. By the way if you could contribute with the portuguese translation for the new client it would be great!
They are located here: https://github.com/GeoNode/geonode-mapstore-client/tree/master/geonode_mapstore_client/client/static/mapstore/translations

**Comment by t-book** [comment]
@allyoucanmap my guess is even if the ticket says 3.2 @sir-onze is using master?

**Comment by sir-onze** [comment]
Thanks fro the feedback!  I was using the wrong version. Meanwhile the team decided to go back to geonode 3.0 . Maybe i can still contribute with the pt translations to the 3.0 version ? I don't know if there is interest in updating this older version.
