### ISSUE TITLE
UI not updating when editing a new geometry

### ISSUE THREAD

**Issue by tpot1** [GeoNode/geonode#7552]
When adding a new feature and moving the geometry, the UI does not update.

Steps to reproduce: 

1) Load an editable layer onto a map. Open the attribute table, enter edit mode and click 'Add new feature'
![image](https://user-images.githubusercontent.com/10741917/118683483-570ad700-b7f9-11eb-849b-1fe3d85b70bb.png)
2) Click 'Draw feature' 
![image](https://user-images.githubusercontent.com/10741917/118683908-acdf7f00-b7f9-11eb-89d3-18c40d9297b5.png)
3) Draw the new geometry
![image](https://user-images.githubusercontent.com/10741917/118683976-bb2d9b00-b7f9-11eb-866d-6c45cdf614c1.png)
4) Drag the blue dot to move the new geometry. Note that while the geometry moves, the UI does not update and the yellow circle remains in the original location.
![image](https://user-images.githubusercontent.com/10741917/118684134-dd271d80-b7f9-11eb-882b-e631ae874bc6.png)

This issue occurs for both point and line geometry types.

**Comment by giohappy** [comment]
@tpot1 this should be fixed for all versions.
