### ISSUE TITLE
Permissions set during the upload are lost

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7557]
## Expected Behavior
When view and download permissions are set during the upload of a resource, they should be applied to the new resource

## Actual Behavior
If view and download permissions are undet for Anyone during the upload of a layer, I can see them turned on the new layer

## Steps to Reproduce the Problem

  1. Upload layer
  2. Uncheck view and download permissions for Anyone from the permissions panel
  3. Open the new layer -> the permissions are checked

## Specifications

  - GeoNode version: master, 3.2.x

**Comment by marthamareal** [comment]
@giohappy  Should these setting be considered while uploading a layer with custom permissions?
https://github.com/GeoNode/geonode/blob/master/geonode/security/models.py#L190
