### ISSUE TITLE
Layers without viewing and downloading permissions are displayed as WMS layer e.g. in QGIS

### ISSUE THREAD

**Issue by Phantast-01** [GeoNode/geonode#7568]
## Expected Behavior
Upload a layer and remove the viewing and download permissions for the public.
If I looking for data with QGIS via WMS Layer, I don't find the layer

## Actual Behavior
Upload a layer and remove the viewing and download permissions for the public.

The layer's permissions are respected in Geonode, but if I invoke the layer using WMS Layer in QGis for example, it continues to display.
If I invoke the layer using WFS Layer in QGIS, I cannot find the layer (works well).
Issue is similar to  #6996

## Steps to Reproduce the Problem

  1. Upload a layer and remove public viewing and download permissions
  2. Create a WMS / WMST data source in Qgis
  3. The layer is displayed as a WMS layer, but not as a WFS layer.

## Specifications

  - GeoNode version: 3.2.0
  - Installation method (GeoNode Docker):
  - Platform: 18.04.5 LTS
  - Additional details:

**Comment by giohappy** [comment]
We weren't able to reproduce this. In our tests Geofence rules (which control access to Geoserver services) are working as expected, preventing users without the correct permissions (token) to access the services.

If you have more info feel free to reopen the issue, but be aware that 3.2.x is [ending its life soon](https://github.com/GeoNode/geonode/wiki/Release-schedule)
