### ISSUE TITLE
Possibility to create a permalink to a single position on a map

### ISSUE THREAD

**Issue by adrianbajer** [GeoNode/geonode#7570]
**Is your feature request related to a problem? Please describe.**
I am unable to share a link to the map, which display an indicated location (i.e. settlement). Currently I can only create general link to the map. What the user see is the the view present when the map was saved. I can't generate a bunch of links to different locations without creating a bunch of maps.

**Describe the solution you'd like**
I need a solution similar to "share" option in MapStore to add center coordinates and zoom to sharing link.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by michalkozak** [comment]
I would like to join this request, asking that additionally the URL could carry information about the time range (in case the map is built from "temporal serie" layers). These optional parameters could set the timeline panel on the map.

**Comment by t-book** [comment]
Hi *, do you have experience with mapstore or modern js (including a build process) you could try to enable it similar to the annotations plugin: https://github.com/GeoNode/geonode/wiki/Good-to-know . The component in question should be here: https://github.com/geosolutions-it/MapStore2/blob/ae9343f65299fb92993eea4842f5489d66560864/web/client/components/share/ShareLink.jsx

**Comment by bradjones1** [comment]
So this would mean that geonode doesn't need anything new on the backend, but only a new element exposed in the UI?

**Comment by bradjones1** [comment]
@giohappy Is this completed or closed? I don't see any links to a PR. Mind helping understand what the status change tracks to? Thanks!

**Comment by giohappy** [comment]
@bradjones1 This has been closed for inactivity. 
It would be a nice feature and it can be reopened to keep it aroung.
