### ISSUE TITLE
Documents are shown in the catalog when creating a map 

### ISSUE THREAD

**Issue by villa101101** [GeoNode/geonode#7607]
## Expected Behavior
seeing only spatial data in catalog 

## Actual Behavior
seeing both spatial data and documents 

## Steps to Reproduce the Problem

  1. go on create map 
  2. select catalog 
  3. browse through catalog 

## Specifications

  - GeoNode version: 3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual 
  - Platform: Ubuntu 20.0.4
  - Additional details:

**Comment by gannebamm** [comment]
I am unable to reproduce this issue in my 3.2.x environment

**Comment by villa101101** [comment]
I installed version 3.2.0 on May 5th. It may be a case that a commit that was made after that date fixed the issue if you are not able to replicate it now.

**Comment by villa101101** [comment]
The issue is not present after reinstalling Geonode
