### ISSUE TITLE
Unexpected error: Request Entity too Large

### ISSUE THREAD

**Issue by KAWAMALA** [GeoNode/geonode#7639]
## Expected Behavior
Upload successfully

## Actual Behavior
Unexpected error: Request Entity too Large
413 Request Entity Too Large
nginx/1.17.1
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Linux
  - Additional details:          
![geonode2](https://user-images.githubusercontent.com/65165225/121374160-57a21380-c948-11eb-8228-50c0af8a7b27.JPG)

**Comment by tomjcolley** [comment]
You need to increase nginx client_max_body_size as per https://docs.geonode.org/en/master/install/advanced/core/index.html#install-and-configure-nginx.

Hope this helps
