### ISSUE TITLE
Print fails with vector polygon features

### ISSUE THREAD

**Issue by tomjcolley** [GeoNode/geonode#7641]
**Expected Behavior**
Map prints with vector layer polygon features.

**Actual Behavior**
Map prints without vector layer polygon features.

**Steps to Reproduce the Problem**
1. Open any map on Geonode demo
2. Open **Measure** tool and select **Measure area** control
3. Draw a polygon to complete an area measurement
4. Click **Add as layer** button to add Measurements layer to TOC
5. Attempt to print map
6. Generated print does not include polygon features. 
7. Sometimes no response comes back and print doesn't generate at all

**Specifications**
This seems to affect any vector polygon layer, we are using Annotations plugin which behaves in the same way.
Other vector geometry types print successfully.
Issue is not present on Mapstore2 demo instance.

**Comment by giohappy** [comment]
@tomjcolley I confirm that printing with annotations is broken. It often doesn't return anything because the backend goes in timeout.

A big upgrade of the print backend is going to be planned, but it's an heavy task, which also requires funding.
For the moment I don't think there's much that can be done.

**Comment by tomjcolley** [comment]
> @tomjcolley I confirm that printing with annotations is broken. It often doesn't return anything because the backend goes in timeout.
> 
> A big upgrade of the print backend is going to be planned, but it's an heavy task, which also requires funding.
> For the moment I don't think there's much that can be done.

@giohappy, thanks for the quick reply. Is the print backend specific to Geonode or is this upgrade needed in the Mapstore code? We may be able to contribute in some way as we have requirements for more advanced printing capabilities
