### ISSUE TITLE
GeoFence rules not removed when a Remote Service is deleted

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7647]
## Expected Behavior

Rules related to layers belonging to the deleted remote service should be removed.

## Actual Behavior

Rule are not removed.

## Steps to Reproduce the Problem

  1. Create a layer from a remote service
  2. Delete the remote service
  3. Enter in the "GeoFence Data Rules" page in GeoServer and check for rules related to the deleted layer

## Specifications

  - GeoNode version: 3.2.x (as of 2021-06-10)
  - GeoServer version: 2.18.x (as of 2021-06-10)
  - Installation method (GeoNode Docker):

**Comment by simboss** [comment]
@giohappy let's discuss this as part of the larger review of interactions with geofence for 3.3
