### ISSUE TITLE
Unable to activate Lets encrypt SSL certificate in Geonode Core docker installation

### ISSUE THREAD

**Issue by AnimeshN** [GeoNode/geonode#7674]
## Expected Behavior
I have hosted geonode on ubuntu 20.04 server, I have used the following documentation
https://docs.geonode.org/en/master/install/advanced/core/index.html#docker

To enable Lets encrypt I have made the following changes to .env file

LETSENCRYPT_MODE=production

 I have also replaced localhost with domain name

I rebuild the image after that
 docker-compose -f docker-compose.yml up --build
After these changes when I access the site from the browser, HTTPS is still disabled

## Actual Behavior

I have installed the docker project before with these changes and it works but now it's causing this issue

## Specifications

  - GeoNode version: 3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):Geonode Docker
  - Platform: Ubuntu 20.04
  - Additional details:

**Comment by jitendrashahiitb** [comment]
This is critical.
Without https the site is rendered useless.

**Comment by afabiani** [comment]
HTTPS can be enabled only on correct and public DNS names.

**Comment by jitendrashahiitb** [comment]
http://geonode.communitygis.net is a public dns
Yet the problem exists

**Comment by AnimeshN** [comment]
We tried docker installation of "geonode core" with public domain geonode3.communitygis.net. we were unable to setup Https certificates ,though docker installation is working with "geonode project". https://geonode3.communitygis.net . But with this we are unable to upload layers.

**Comment by Darkonyks** [comment]
@AnimeshN I had a same issue and it suppose to be problem in .env file in ADMIN_EMAIL=admin@localhost
Try changing it to real e-mail address like admin@yourdomain.... It works for me..

**Comment by afabiani** [comment]
I am not currently able to reproduce this issue. Most probably this is caused by some configuration problem.

Please try to send more detailed logs otherwise it will be impossible to understand where the cause could be.

**Comment by nextgen-pk** [comment]
I think this issue still persists, letsencrypt4geonode up and running but browser still shows Issued to and issued by: Localhost.

I'm using 

Centos 7.9
Docker
GeoNode 3.2.0

Installed through https://docs.geonode.org/en/master/install/advanced/core/index.html#docker

**Comment by jitendrashahiitb** [comment]
I have suspended using geonode till I get an assured official response of a
fix . Unfortunate.

**Comment by teresafazio** [comment]
I had problem with letsencrypt and certifcates and I found an issue into path definition inside scripts/spcgeonode/letsencrypt/docker-entrypoint.sh file
I changed 
/spcgeonode-certificates
with
/geonode-certificates
that is the correct shared volume between geonode and letsencrypt services (inside docker-compose.yml file)

**Comment by AnimeshN** [comment]
Thanks, updating the scripts/spcgeonode/letsencrypt/docker-entrypoint.sh file worked

**Comment by jitendrashahiitb** [comment]
Awesome, thanks!
