### ISSUE TITLE
Layers caching problem

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#7692]
The layer panes are set to 512 by default but the configuration for the cache in GWC is not active and the following dridsets: EPSG: 900913x2 and EPSG: 4326x2 should be set by default when a layer is loaded

**Comment by gannebamm** [comment]
See > [gitter chat at 15. Dezember 2021 14:10](https://gitter.im/GeoNode/general?at=61b9e92e440178658b97a5d2)
Seems like this is not fixed in 3.3.x

**Comment by giohappy** [comment]
@gannebamm see my answer on gitter. When did you update Geoserver last time? When Geoserver for GeoNode was upgraded to 2.19.x the 512px GWC configs weren't correctly ported. It has been fixed a few weeks ago with a new build.

**Comment by gannebamm** [comment]
Because of some dynamic SLD render issue we were not able to use the 2.19.x GeoServer. That's the reason we had an outdated GWC GridSet. Thanks for the clarification @giohappy
