### ISSUE TITLE
GNIP - Provide UI for adding remote CSW servers

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#770]
pycsw already supports federation, and it was possible to do in 1.2 with the geonetwork ui.

**Comment by jj0hns0n** [comment]
I've upgraded this to a GNIP and will work with @tomkralidis on fleshing it out. @jtcolton are you still interested in working on this?

**Comment by jj0hns0n** [comment]
@tomkralidis any update on this one? I think its not anywhere near done, so moving to 2.7
