### ISSUE TITLE
Harvest errors on dataset metadata XML

### ISSUE THREAD

**Issue by d3netxer** [GeoNode/geonode#7703]
## Expected Behavior
Data.gov would harvest datasets on GeoNode successfully

## Actual Behavior
A few errors occurred:
- Element '{http://www.isotc211.org/2005/gmd}name': This element is not expected. Expected is ({http://www.isotc211.org/2005/gmd}title).
- Element '{http://www.isotc211.org/2005/gmd}includedWithDataset': This element is not expected. Expected is one of ( ({http://www.isotc211.org/2005/gmd}AbstractMD_ContentInformation,
{http://www.isotc211.org/2005/gmd}MD_FeatureCatalogueDescription,
{http://www.isotc211.org/2005/gmd}MD_CoverageDescription,
{http://www.isotc211.org/2005/gmd}MD_ImageDescription,
{http://www.isotc211.org/2005/gmd}MI_CoverageDescription,
{http://www.isotc211.org/2005/gmd}MI_ImageDescription).

## Steps to Reproduce the Problem

  1. upload a dataset through the GeoNode UI and fill out metadata fields

## Specifications

  - GeoNode version: 3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Ubuntu 20.04

In order to correct the errors, the gmd:name element can be removed, and also the includedWithDataset can be relocated within the gmd:MD_FeatureCatalogueDescription element. Am I correct in assuming that these updates can be implemented by editing the [full_metadata.xml template](https://github.com/GeoNode/geonode/blob/9f1474a784682e919e70963ae1fd1da0919ff576/geonode/catalogue/templates/catalogue/full_metadata.xml)?

Also, would removing the gmd:name from the template element break anything?

Does GeoNode document metadata XML get validated in tests?

**Comment by gannebamm** [comment]
linked to: https://github.com/GeoNode/geonode/issues/7181

**Comment by giohappy** [comment]
@gannebamm is this still valid on GN 4?

**Comment by giohappy** [comment]
that was my point :)
And I think we should restore it...

**Comment by kikislater** [comment]
+1 ! 
Without metadata Geonode is useless IMO

**Comment by giohappy** [comment]
Metadata download is available. It's the UI button that is missing at the moment.

Take a look at the API response of a resource. You'll find the metadata links inside the `links` property.

For example [here it](https://development.demo.geonode.org/catalogue/csw?request=GetRecordById&service=CSW&version=2.0.2&id=5cef8201-ec44-4dbd-9554-f40d254db7cc&outputschema=http%3A%2F%2Fwww.opengis.net%2Fcat%2Fcsw%2F2.0.2&elementsetname=full) is the Dublin Core document for [this dataset](https://development.demo.geonode.org/api/v2/datasets/399#/)

**Comment by gannebamm** [comment]
Just a little update: The UI now enables to download the metadata
![grafik](https://user-images.githubusercontent.com/6172324/197780883-f2343676-95b5-473b-8b1f-14e35a9fa6a1.png)
https://master.demo.geonode.org/catalogue/#/dataset/3049
