### ISSUE TITLE
Cannot connect to a remote Geonode server using OAuth2 

### ISSUE THREAD

**Issue by geogeek11** [GeoNode/geonode#7716]
I have tried following [Geonode guide](https://docs.geonode.org/en/master/usage/other_apps/qgis/index.html#connect-to-private-layers-by-using-oauth2) to connect to a geonode private layer using OAuth2.

Please check below the settings that I have used to connect to a remote geonode server.
![Screenshot from 2021-06-21 12-20-48](https://user-images.githubusercontent.com/7670475/123639482-25355900-d818-11eb-83f7-9b6df88e9144.png)

After clicking on Test connection, I get the web page below, then I click on authorize
![Screenshot from 2021-06-21 12-22-11](https://user-images.githubusercontent.com/7670475/123639500-2bc3d080-d818-11eb-93ab-4891e45ec089.png)

After that, I get redirected to the web page below, and no connection is set up.
![Screenshot from 2021-06-21 12-22-31](https://user-images.githubusercontent.com/7670475/123639522-32eade80-d818-11eb-84f7-9a4453625948.png)

QGIS 3.16.4 & 3.18 & 3.20.0
GeoNode version: 3.2.0, SPCGeoNode Docker

**Comment by frafra** [comment]
`URL de redirection` is `http://120.0.1:7070/qgis-client`, which is what your browser is following, but there is nothing there. This is a problem with your external service, not with GeoNode, sorry.
