### ISSUE TITLE
Keep serializer consistent with the new ResourceBase.subtype

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7794]
@mattiagiupponi let's avoid [magic translations](https://github.com/GeoNode/geonode/blob/6f2f6b60892f5e155f61469f3ffba31d1d6eaa50/geonode/base/api/serializers.py?plain=1#L336) inside the serializer. I understand they were meant to make the change transparent to the client, but it confuses.
Let's adopt the new subtype along all the line and adapt the client where needed.

**Comment by mattiagiupponi** [comment]
https://github.com/GeoNode/geonode/pull/7798
