### ISSUE TITLE
blank rows in spatial representation type dropdown

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#7812]
## Expected Behavior
If I use the metadata wizard to fill in spatial representation information a list of ISO types is shown.

## Actual Behavior
The representation type dropdown is filled with blank rows:
![grafik](https://user-images.githubusercontent.com/6172324/125928782-3378360c-25a3-4ac7-b7cd-e90fec365296.png)

## Steps to Reproduce the Problem

  1. Open metadata editor for owned dataset
  2. switch to optional metadata
  3. click dropdown

## Specifications

  - GeoNode version: 3.2.x (stable.demo)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): stable.demo & docker
  - Platform: 
  - Additional details:

**Comment by afabiani** [comment]
It looks just a DB issue
![image](https://user-images.githubusercontent.com/1278021/125940417-c676b6ee-d9b7-4ea0-b09b-3833341f41a1.png)

Are you able to reproduce this locally?

**Comment by gannebamm** [comment]
Yes it is also present in our instance. Maybe a fixture error?

**Comment by afabiani** [comment]
I guess so, just tested couple of setup from scratch before releasing, I could not reproduce this issue.

However let's postpone to 3.3.0

**Comment by giohappy** [comment]
@gamesbook setting up GeoNode from scratch doesn't generate those datasets rows. I would remove the regression label and just leave this issue around if we face it again.

**Comment by gannebamm** [comment]
I deleted the rows in our system and will take a look at what caused the creation of those. I will close this issue for the time beeing.
