### ISSUE TITLE
X_FRAME_OPTIONS="ALLOW-FROM ALL" is not valid

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7813]
[This env](https://github.com/GeoNode/geonode/blob/master/.env#L123) is not valid. [Valid options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) are DENY and SAMEORIGIN

**Comment by giohappy** [comment]
@afabiani we need it on geonode-project too

**Comment by afabiani** [comment]
@giohappy done

**Comment by drumbsd** [comment]
@giohappy @afabiani 

https://github.com/GeoNode/geonode-demo/blob/3.3.x/.env

Here seems that **ALLOW-FROM ALL** is still present. I checked and also "master" and "3.2.x". Both have it.

**Comment by afabiani** [comment]
@drumbsd this is not related to geonode, those are `geonode-project` specific implementations on different repositories. Please open a ticket on the right repo.
