### ISSUE TITLE
Layer Upload broken in 3.2.1

### ISSUE THREAD

**Issue by cwygoda** [GeoNode/geonode#7828]
## Expected Behavior

1. Upload a layer dataset (zipped shapefile or set of files of the shapefile)
2. Upload is getting processed
3. Layer is created successfully

## Actual Behavior

1. Upload a layer dataset (zipped shapefile or set of files of the shapefile)
2. Immediate error response: 500 - `{"errormsgs": "Please, upload a valid XML file"}`

## Steps to Reproduce the Problem

1. Upload a layer dataset (zipped shapefile or set of files of the shapefile)

## Specifications

- GeoNode version: 3.2.1
- Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Custom docker setup
- Additional details: Same setup works with geonode==3.2.0

## Additional Info

Problem seems to be in https://github.com/GeoNode/geonode/blame/717af9502a5cbc66991e485946c204af4d2555f5/geonode/layers/views.py#L339 coming from https://github.com/GeoNode/geonode/pull/7715 (which also deleted the tests...)

**Comment by afabiani** [comment]
1. I guess this is a wanted behavior
2. Attach an example please

**Comment by cwygoda** [comment]
# Uploading zipped Natural Earth Shapefile
![Screenshot from 2021-07-20 11-48-49](https://user-images.githubusercontent.com/764327/126302921-c02658a1-6a65-42ae-a5a1-1420c62f51be.png)
yields immediate response:
![Screenshot from 2021-07-20 11-48-44](https://user-images.githubusercontent.com/764327/126302931-2f3ad439-e513-4b54-b1a7-202a1cfe815c.png)
![Screenshot from 2021-07-20 11-50-18](https://user-images.githubusercontent.com/764327/126303124-e5216bde-5766-4b97-b588-3a0f840bf1a8.png)
![Screenshot from 2021-07-20 11-50-12](https://user-images.githubusercontent.com/764327/126303127-e3c9d88f-bef0-48f7-9951-190da04b6303.png)
![Screenshot from 2021-07-20 11-50-09](https://user-images.githubusercontent.com/764327/126303130-099ac749-8bcc-4c94-95d5-46b891629b21.png)

**Comment by afabiani** [comment]
Can you provide the zip file? Also, remove any xml file inside the ZIP or update it with a valid one.

**Comment by afabiani** [comment]
Nevertheless it looks like your GeoServer configuration is wrong or GeoServer is not running properly.

**Comment by cwygoda** [comment]
[ne_10m_admin_0_countries.zip](https://github.com/GeoNode/geonode/files/6848935/ne_10m_admin_0_countries.zip)

There's no XML inside the ZIP. Also, this never hits Geoserver, GeoNode's Django code throws this, follow these four code points:
1. routing: https://github.com/GeoNode/geonode/blob/3.2.x/geonode/layers/urls.py#L41
2. view handler https://github.com/GeoNode/geonode/blob/717af9502a5cbc66991e485946c204af4d2555f5/geonode/layers/views.py#L339
3. 500 reponse is explicitely created here: https://github.com/GeoNode/geonode/blob/717af9502a5cbc66991e485946c204af4d2555f5/geonode/layers/views.py#L346

Nothing ever hits Geoserver in this scenario.

**Comment by afabiani** [comment]
@cwygoda I just did some tests against https://stable.demo.geonode.org/ and I could not reproduce the error

![image](https://user-images.githubusercontent.com/1278021/126342919-5290c864-485c-4155-87dd-338c691b55b9.png)

**Comment by t-book** [comment]
@afabiani stable.demo.geonode.org is on 3.2.0 from what I see: https://stable.demo.geonode.org/version.txt but @cwygoda is talking about 3.2.1. Will do a local test as well.

**Comment by afabiani** [comment]
I guess just because stable.demo.geonode.org is not aligned with the release, but the code is 3.2.1

**Comment by t-book** [comment]
I've tested the provided zip with a fresh 3.2.1 docker (core) setup. Worked without problems. No regression for me.

**Comment by cwygoda** [comment]
I took a deep dive debug session and the root cause for my setup is as follows:
- still using `geonode.rest` for `UPLOADER["BACKEND"]` which works in 3.2.0 but not in 3.2.1 it seems
- switching to `geonode.importer` as is set in the env file in the core repo

So sorry for the overly alert report, still looks to me there's an issue depending on the choosen backend.
