### ISSUE TITLE
Add support for styles attached to a workspace in GeoServer

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#783]
The url looks more or less like the following:

```
http://geoserver.example.com/geoserver/rest/workspaces/<workspace_name>/styles/<style_name>.xml|.json
```

Thanks Micah Wengren and @matthewhanson for the report.

**Comment by jj0hns0n** [comment]
@matthewhanson can you verify this is still an issue? Perhaps something you can help with?

**Comment by jj0hns0n** [comment]
Moving to 2.5
