### ISSUE TITLE
Delete incomplete upload sessions after a configurable amount of time

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7832]
Incomplete sessions (either in error state or waiting for inputs) accumulate indefinitely, with a list of bad side effects.
We should configure a deadline after which the session and any connected resource (file, models) are deleted.
I would set a default retention time of 24 hours, to be configured through Django settings.

**Comment by t-book** [comment]
° I would set a default retention time of 24 hours.

I fully agree! Thanks @giohappy

**Comment by asgharsir** [comment]
I would like to be more precise about the **"any connected resource (file, models)"** part. 
- Are these resources, only, those uploaded files which have not completed all processes in an incomplete session?
- Or there are more files/models that have to be taken care of while deleting the session.

**Comment by giohappy** [comment]
@afabiani can give you more info on this. These are the basic resources that are created when an upload starts:

 - [Upload session](https://github.com/GeoNode/geonode/blob/017155ccbdef8f4d43df59ac2f2457fc30c7f943/geonode/upload/upload.py?plain=1#L307) 
 - [Geoserver import session](https://github.com/GeoNode/geonode/blob/017155ccbdef8f4d43df59ac2f2457fc30c7f943/geonode/upload/upload.py?plain=1#L357) 
 - temporary files copied under the temp folder

One importatn thing to notice is that up to 3.3.x we also have the [UploadSession](https://github.com/GeoNode/geonode/blob/3ee2f7d4a727fd030723411768dbbb07f9949ef7/geonode/layers/models.py?plain=1#L125), which is populated and used during the upload procedure. It has been dropped in master and it's been replaced by the [Upload.session](https://github.com/GeoNode/geonode/blob/017155ccbdef8f4d43df59ac2f2457fc30c7f943/geonode/upload/models.py?plain=1#L88) field, where the serialized uploadsession is held.

I think you could use the `upload.Session.delete` method, both on 3.3.x and master, which should already do all the work for you.

As far as I know nothing else is created until the upload is completed, but I would ask @afabiani to confirm.

**Comment by afabiani** [comment]
confirmed, `Upload.delete`

**Comment by asgharsir** [comment]
Thanks. So it is confirmed that these are only `Upload` which have not riped to `STATE_COMPLETE` yet. Thanks.

High Level View of the apparent Solution is, the Session can be deadlined to 24 hours. But doing the deletion of incomplete resources, per session, would be very costly. It should be a cron job @giohappy.

Next I will see the implementation outline for this solution, specially, how a cron job will determine incomplete session resources.

**Comment by giohappy** [comment]
I see two options here:

 - count the stale sessions each time the upload API is queried and run an async task to delete them in case.
 - configure a celery beat task to run twice the rate of the retention time (i.e. every 12 hours for a default 24h retention)

**Comment by asgharsir** [comment]
Yes. These are the two. First one I believe would be costlier than the second one. So looking into the second option.

**Comment by giohappy** [comment]
I suppose you're already aware of this toolset (that is also used by the new harvester module): https://django-celery-beat.readthedocs.io/en/latest/

**Comment by asgharsir** [comment]
Yes. I have already added the celery scheduled. I am finding the best way to find the **expired sessions' incomplete uploads** to delete. As in the above message, I expected that should be tricky.
