### ISSUE TITLE
Drop upload sessions if Geoserver import session is not available

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7834]
Geoserver import sessions are kept in memory. If, for whatever reason, the sessions are removed any GeoNode upload sessions will become orphans.
GeoNode must check if an import session is still available when returning the list of active (incomplete) upload sessions. In case of orphan sessions they must be deleted together with any connected resource (file, model entries).

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/commit/148fb937c73360416bb033117f0966a583dca58b
