### ISSUE TITLE
The first time a map is saved thumbnail is created using the default style instead of the selected one

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#7835]
When a layer has more than one styles we have found that: 

1) the thumbnail always use the layer default style despite the one chosen on the map 
2) the first time we save the map it will use the default style of the layer instead of the chosen one;

**Comment by marthamareal** [comment]
@giohappy here are example pictures on recreating this
![lis](https://user-images.githubusercontent.com/20810749/126468452-b2251997-b284-4824-8e6d-e506b3c78ebd.png)
![leg](https://user-images.githubusercontent.com/20810749/126468464-4df47370-29bb-4a9c-91d5-48cb41be4db3.png)

The legend displays as expected, its the thumbnail that has issues,In scenarios where more than 2 layers are added on creating a map
