### ISSUE TITLE
Geonode Docker

### ISSUE THREAD

**Issue by zahirulislamovich** [GeoNode/geonode#7869]
## Expected Behavior
Geonode docker core is not successfully installing 3.2.1

## Actual Behavior

after installation url is not working
## Steps to Reproduce the Problem

  1.installed geonode as per the instructions
  2. on build there are some  exited with code 1
  3. finally after assigning domain name is not showing to the welcome page and not even geoserver

## Specifications

  - GeoNode version: 3.2.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): docker
  - Platform: ubuntu 20.04
  - Additional details:

**Comment by t-book** [comment]
Please check your logs with `docker-compose logs -f` also uncomment this line https://github.com/GeoNode/geonode/blob/3.2.x/docker-compose.yml#L12 and look for a file called invoke.log in your root directory (where you run the commands). Come back with logs

**Comment by zahirulislamovich** [comment]
> docker-compose logs -f
Sorry , i didnot find invoke logs file..
![error3 2 ](https://user-images.githubusercontent.com/18528163/127311430-f27e3210-e350-4efc-baa2-5a1f51c3b6db.JPG)
![error3 2](https://user-images.githubusercontent.com/18528163/127311438-fcecfbb8-5f49-4f61-aa6b-79b6dafe31c1.jpg)
