### ISSUE TITLE
instructions regarding Geoserver DATA directory and extensions

### ISSUE THREAD

**Issue by zahirulislamovich** [GeoNode/geonode#7870]
it is very trouble some and still not getting any concrete material like basic user regarding how to activates geoserver plugin and external mounting of geoserver data directory

please provide a through tutorial regarding gdal or other plugin activation of geonode in docker environment. and mounting of geoserver data directory. it will be very helpful

**Comment by t-book** [comment]
@zahirulislamovich We know that starting with geonode is not an easy task as the different components demand vast knowledge. Further please note that writing documentation is a time-consuming task done by volunteers! What you're requesting leaves the normal user demands.

To answer your question:

Try to get more familiar with Docker, the geoserver data-directory is actually stored in a persistent volume: https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L144-L145
Docker makes it easy to define the target directory where your volumes will be stored:
https://devopsheaven.com/docker/docker-compose/volumes/2018/01/16/volumes-in-docker-compose.html

If you're familiar with geoserver plugin installation (https://docs.geoserver.org/latest/en/user/styling/workshop/setup/install.html) you can also edit your geoserver service. Either directly the container (you will lose the plugin after next build) or you create a custom install and build from it except using the image: https://github.com/GeoNode/geonode/blob/master/docker-compose.yml#L88
