### ISSUE TITLE
Geoserver Password is not changing from .env_dev

### ISSUE THREAD

**Issue by zahirulislamovich** [GeoNode/geonode#7876]
## Expected Behavior
Geoserver admin password need ot be changed from default password

## Actual Behavior
While changing the geoserver password is not changing

## Steps to Reproduce the Problem

  1. installed geonode project docker as per the instruction
  2. after starting changed .env geoserver password which didnot worked
  3.

## Specifications

  - GeoNode version: 3.1.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): docker
  - Platform: ubuntu 20.04
  - Additional details:

**Comment by t-book** [comment]
Please always use the section steps to reproduce. 
(Lot of problems arise as people mix compose restart, build, up etc. Hence it helps to read what people trying to do.)

In this case, I agree, the update only runs on the first start. But it's easy to change it afterward.

- Change the password in .env
- Run `docker-compose down; docker-compose up -d`
- Log into geoserver with your old password and update it in the user section

**Comment by zahirulislamovich** [comment]
Many many thanks, but here is suggestion please include this in geonode installation guide also

**Comment by zahirulislamovich** [comment]
Geoserver changing password in 3.2.1(docker Project) is ok. But in 3.1.1 docker core as per above instructions lead geoserver to geonode and geonode to geoserver link in localhost. meanwhile uploading shapefile after password change shows Unexpected error! - Unknwon Error Code. Contact the system administrator for more information regarding this error message.

**Comment by jcaceres85** [comment]
As @t-book mentioned, the geoserver password set on the .env i used bu django to manage files uploads, is not the actual password set for the geoserver container. So after creating your containers you have to log in to geoserver using default credentials admin:geoserver and change the password from th WebUI and set it to the same password of the .env file. I have deploy Geonode 3.1.1. Docker Core and following this procedure works just fine.

**Comment by zahirulislamovich** [comment]
Finally able to change password. its double checked in settings.py; env_dev; geoserver user. succed to login logout and revisit form geoserver-geonode-geoserver interface but facing this error, 
![image](https://user-images.githubusercontent.com/18528163/133882671-b9b6d32a-52bb-40a0-ac4e-7fc53f3ce44c.png)
