### ISSUE TITLE
After Deleting all template files geonode runs

### ISSUE THREAD

**Issue by zahirulislamovich** [GeoNode/geonode#7877]
![Untitled](https://user-images.githubusercontent.com/18528163/127285697-e0c5d368-4f10-4256-9469-744a6430bbff.png)
![Untitled](https://user-images.githubusercontent.com/18528163/127285949-bfa556fe-9451-41c8-b782-794fddf5324b.png)
## Expected Behavior
i am working for changing geonode themes

## Actual Behavior
there is no clear procedure of how to change themes. i then install geonode project in docker . made copy paste of index and base file from github to the my-geonode projects. there is no change finally. finally when i delete the template it still runs!!!

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 3.2.1 docker project
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): docker
  - Platform: ubuntu 20.4
  - Additional details:

**Comment by t-book** [comment]
> there is no clear procedure of how to change themes.

The templating is pure Django! Nothing special about it. Changing your Docker stack to your needs is up to you. This means you need to make sure your templates are copied to your container on build. For further guidance see: https://geonode.org/dev-workshop/#/1

Closing here. For further help please use gitter or the mailing list and keep GitHub for bug reports
