### ISSUE TITLE
Implement more filtering options for GeoNode harvesters 

### ISSUE THREAD

**Issue by meomancer** [GeoNode/geonode#7880]
Based on https://github.com/geosolutions-it/nexus-geonode/issues/350

## Overview
We want more options to filter the list harvestable resources to be retrieved.
Piority fields are marked in **bold**

- **start_date** 
- **end_date**
- keywords
- category

**Comment by meomancer** [comment]
hi @giohappy 
the PR already merged, could we close this?

**Comment by giohappy** [comment]
@meomancer I'm going to close this but please always connect the issue to the PR inside the description and the title. You set it to "[Fixes #7881] ..." instead of "[Fixes #7880] ...."
