### ISSUE TITLE
File upload fails with 400 Bad Request

### ISSUE THREAD

**Issue by pieterprovoost** [GeoNode/geonode#7895]
## Actual Behavior

I'm running the latest GeoNode with Docker in the default configuration. When I'm trying to upload a new dataset I get the following error after 15 seconds or so, with progress stuck at 33%:

```
Unexpected error! - 400 Bad Request. Server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
```

In the browser console I see a request to `http://localhost/upload/time?id=5&force_ajax=true` which returned a 400 with the following body:

```
{"success": false, "errors": ["Expecting value: line 1 column 1 (char 0)"]}
```

Everything seems to be up and running:

```
CONTAINER ID   IMAGE                                COMMAND                  CREATED          STATUS                    PORTS                                                                      NAMES
af0bc4f43ad4   geonode/geonode:latest               "/usr/src/geonode/en…"   26 minutes ago   Up 26 minutes             8000/tcp                                                                   celery4geonode
aebfa79ff152   rabbitmq:3.7-alpine                  "docker-entrypoint.s…"   26 minutes ago   Up 26 minutes             4369/tcp, 5671-5672/tcp, 25672/tcp                                         rabbitmq4geonode
d40e2906813a   geonode/geonode:latest               "/usr/src/geonode/en…"   26 minutes ago   Up 26 minutes (healthy)   8000/tcp                                                                   django4geonode
d773445ffa9b   geonode/nginx:3.x                    "/docker-entrypoint.…"   26 minutes ago   Up 26 minutes             0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx4geonode
0d64682d5ed5   geonode/geoserver:2.18.2             "/usr/local/tomcat/t…"   26 minutes ago   Up 26 minutes (healthy)   8080/tcp                                                                   geoserver4geonode
c3848ba8e060   geonode/spcgeonode:letsencrypt-3.1   "./docker-entrypoint…"   26 minutes ago   Up 2 seconds                                                                                         letsencrypt4geonode
f5f50c2213e1   geonode/postgis:13                   "docker-entrypoint.s…"   26 minutes ago   Up 26 minutes             5432/tcp                                                                   db4geonode
```

## Steps to Reproduce the Problem

  1. Checkout master
  2. `docker-compose --force-recreate up`
  3. Sign in with defaults
  4. Go to Data > Datasets > Create new > Dataset
  5. Upload [this shapefile](https://github.com/GeoNode/geonode/files/6907737/WorldMarineHeritageSites.zip)

## Specifications

  - GeoNode version:
    - master (73a524e87484eaa909fcad957d87de5f381222e0)
    - 3.2.x (5ff70c668fddaa846ae8534e7190dee2610c30af)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker
  - Platform: macOS 11.4

**Comment by afabiani** [comment]
Hi @pieterprovoost are you using the branch 3.2.x?

Any chance to test the changes proposed [here](https://github.com/GeoNode/geonode/pull/7898) and on geonode-project [here](7c39769048093de562ff55b1949b0aa1aeb91a1f) and [here](249f127401e74153b205fde8256353c88b3057c4)

**Comment by pieterprovoost** [comment]
No, I'm on master (https://github.com/GeoNode/geonode/commit/73a524e87484eaa909fcad957d87de5f381222e0), sorry for the confusion and I have amended above. So far I have no luck with the changes proposed in https://github.com/GeoNode/geonode/pull/7898.

**Comment by pieterprovoost** [comment]
@afabiani After a bit more experimentation I found that the problem also presents itself on 3.2.x, but seems to be related to the shapefile I used. I tried a few other files and was able to upload them without any issues. The problematic file has a number of self intersections according to QGIS.

**Comment by afabiani** [comment]
Going to close this for now. Feel free to re-open or create a new one if something new comes out.

Thanks @pieterprovoost
