### ISSUE TITLE
Geonode build fails on Ubuntu 1804 installation - Error: Pull access denied for my_geonode_django, repository doesnt exist or may require docker login, login denied: requested access to the resource is denied. 

### ISSUE THREAD

**Issue by lmneville** [GeoNode/geonode#7901]
## Expected Behavior
Following instructions posted at :https://docs.geonode.org/en/master/install/basic/index.html#first-step-deploy-geonode-on-a-local-server-e-g-http-localhost

Followed this process:

Installation Steps:

1) Packages Installation
First, we are going to install all the system packages needed for the GeoNode setup. Login to the target machine and execute the following commands:

sudo apt install -y gdal-bin
sudo apt install -y python3-pip python3-dev python3-virtualenv python3-venv virtualenvwrapper
sudo apt install -y libxml2 libxml2-dev gettext
sudo apt install -y libxslt1-dev libjpeg-dev libpng-dev libpq-dev libgdal-dev
sudo apt install -y software-properties-common build-essential
sudo apt install -y git unzip gcc zlib1g-dev libgeos-dev libproj-dev
sudo apt install -y sqlite3 spatialite-bin libsqlite3-mod-spatialite
sudo apt install -y libgdal20

2) Docker Setup (First time only)

sudo add-apt-repository universe
sudo apt-get update -y
sudo apt-get install -y git-core git-buildpackage debhelper devscripts
sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update -y
sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose
sudo apt autoremove --purge

sudo usermod -aG docker ubuntu
cat /etc/group | grep docker - this should indicate docker:x:999:ubuntu (this means ubuntu is in docker group)

3) Creating an instance 

git clone https://github.com/GeoNode/geonode-project.git -b 3.2.x
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
mkvirtualenv --python=/usr/bin/python3 my_geonode
pip install Django==3.2
django-admin startproject --template=./geonode-project -e py,sh,md,rst,json,yml,ini,env,sample,properties -n monitoring-cron -n Dockerfile my_geonode

4) Startup the containers

cd my_geonode 
./docker-build.sh

./docker-build.sh fails  - no container. No project.  No website. 

## Actual Behavior
./docker-build.sh fails

Pulling celery (my_geonode_django:latest)...
ERROR: pull access denied for my_geonode_django, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all images without at least one container associated to them
  - all build cache

## Steps to Reproduce the Problem

We have manually tried creating _django subdirectory in advance of error, error occurs anyway. 

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Manual
  - Platform: AWS AMI 18.0.4 (Bionic Beaver).
  - Additional details:

**Comment by JSalaCoro** [comment]
Hi, 

I got the same error and in my case had to to with python version used in the my_geonode virtualenv. I installed python 3.8 and made a new venv with this version:

mkvirtualenv --python=/usr/bin/python3.8 my_geonode

The error disappeared and containers seem to be running correctly.

Hope is useful

**Comment by phyokyi** [comment]
> Hi,
> 
> I got the same error and in my case had to to with python version used in the my_geonode virtualenv. I installed python 3.8 and made a new venv with this version:
> 
> mkvirtualenv --python=/usr/bin/python3.8 my_geonode
> 
> The error disappeared and containers seem to be running correctly.
> 
> Hope is useful

I try with python 3.8.0 problem still persist.

**Comment by drumbsd** [comment]
Avoid to use the word "geonode" in your instances. I got the same problem with celery, but after created a new instance named "foobar" the error disappeared.
