### ISSUE TITLE
Can't disable dashboard on 3.3.x

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7913]
## Expected Behavior
Removing the `mapstore2_adapter.geoapps.dashboards` the dashboard option should not appear in the GeoApps menu.

## Actual Behavior
Removing the `mapstore2_adapter.geoapps.dashboards` the dashboard option appears in the GeoApps menu.

## Steps to Reproduce the Problem

  1. Disable the dashboard either by editing your setting files or adding these lines to a customized setting file:
      ```
     APPS_TO_BE_REMOVED = ('mapstore2_adapter.geoapps.dashboards',)
     INSTALLED_APPS = tuple(x for x in INSTALLED_APPS if x not in APPS_TO_BE_REMOVED)
     ```
  2. Login in GeoNode, go in GeoApps list
  3. Open the "Create GeoApps" button menu

## Specifications

  - GeoNode version: 3.3.x

**Comment by etj** [comment]
There is a fix in this branch: https://github.com/GeoNode/geonode/tree/quickfix

**Comment by afabiani** [comment]
Fixed through https://github.com/GeoNode/geonode/commit/2385ac8428a5e1e2016f49649713c2eba79c16a6
