### ISSUE TITLE
Categories and Groups are not visible

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#7919]
## Expected Behavior
Categories and Group correctly showed on the edit page

## Actual Behavior
Categories and Groups are empty

## Steps to Reproduce the Problem

  1. Upload a resource
  2. Go to the MetadataEdit page
  3. Check category and group dropdown

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual / docker
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Fixed through https://github.com/GeoNode/geonode-mapstore-client/commit/1e287654a01f30711441c39e1dcbd9ace7da7839.
