### ISSUE TITLE
Geonode Project 3.2x Backup Failure—"CommandError: Unable to serialize database"

### ISSUE THREAD

**Issue by cavernousguess** [GeoNode/geonode#7928]
## Expected Behavior
Successful Geonode backup with .zip backup file in "backup_restore" directory.

## Actual Behavior
Running "backup.sh" in a fresh Geonode-Project Docker install is successfull. However running the backup script after Geonode has GIS layers uploaded to it, the backup fails with `CommandError: Unable to serialize database`.

I ran this command on the host machine  in the same directory as the docker-compose.yml files to execute the backup.sh file in the Django container:
`docker exec -it django4wmrgeonode sh -c './wmrgeonode/br/backup.sh'`

The above results in the following error (with `--traceback` appended to https://github.com/GeoNode/geonode-project/blob/249f127401e74153b205fde8256353c88b3057c4/project_name/br/backup.sh#L35):
```
-----------------------------------------------------
STARTING wmrgeonode BACKUP Fri Aug  6 02:37:56 UTC 2021
-----------------------------------------------------
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'rest_framework' isn't unique. You may not be able to reverse all URLs in this namespace
Before proceeding with the Backup, please ensure that:
 1. The backend (DB or whatever) is accessible and you have rights
 2. The GeoServer is up and running and reachable from this machine
STARTED - 1/11
STARTED - 7/11
COMPLETED - 11/11
Dumping existing GeoServer Vectorial Data: ['structure_inner_metro', 'structure_core_corridors', 'outer_metro', 'gf_rule', 'gf_layer_styles', 'gf_usergroup', 'gf_adminrule', 'gf_layer_details', 'gf_layer_attributes', 'structure_commutershed', 'gf_gsuser', 'gf_gfuser', 'gf_gsinstance', 'gf_rule_limits', 'gf_user_usergroups', 'airports3', 'boundaries_wmr_outline', 'test', 'structure_wpg_dt', 'structure_centres']
Dump Table: wmrgeonode_data:structure_inner_metro
Dump Table: wmrgeonode_data:structure_core_corridors
Dump Table: wmrgeonode_data:outer_metro
Dump Table: wmrgeonode_data:gf_rule
Dump Table: wmrgeonode_data:gf_layer_styles
Dump Table: wmrgeonode_data:gf_usergroup
Dump Table: wmrgeonode_data:gf_adminrule
Dump Table: wmrgeonode_data:gf_layer_details
Dump Table: wmrgeonode_data:gf_layer_attributes
Dump Table: wmrgeonode_data:structure_commutershed
Dump Table: wmrgeonode_data:gf_gsuser
Dump Table: wmrgeonode_data:gf_gfuser
Dump Table: wmrgeonode_data:gf_gsinstance
Dump Table: wmrgeonode_data:gf_rule_limits
Dump Table: wmrgeonode_data:gf_user_usergroups
Dump Table: wmrgeonode_data:airports3
Dump Table: wmrgeonode_data:boundaries_wmr_outline
Dump Table: wmrgeonode_data:test
Dump Table: wmrgeonode_data:structure_wpg_dt
Dump Table: wmrgeonode_data:structure_centres
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 181, in handle
    serializers.serialize(
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/__init__.py", line 128, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/serializers/base.py", line 90, in serialize
    for count, obj in enumerate(queryset, start=1):
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 169, in get_objects
    yield from queryset.iterator()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 341, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 72, in __iter__
    for row in compiler.results_iter(results):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1086, in apply_converters
    value = converter(value, expression, connection)
  File "/usr/local/lib/python3.8/site-packages/django_jsonfield_backport/models.py", line 111, in from_db_value
    if connection.features.has_native_json_field and self.decoder is None:
  File "/usr/local/lib/python3.8/site-packages/django/contrib/gis/db/backends/base/features.py", line 98, in __getattr__
    raise AttributeError
AttributeError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/wmrgeonode/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/geonode/br/management/commands/backup.py", line 108, in handle
    self.execute_backup(**options)
  File "/usr/local/lib/python3.8/site-packages/geonode/br/management/commands/backup.py", line 163, in execute_backup
    call_command('dumpdata', app_name, format='json', indent=2, stdout=output)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/dumpdata.py", line 194, in handle
    raise CommandError("Unable to serialize database: %s" % e)
django.core.management.base.CommandError: Unable to serialize database:

```

 

## Steps to Reproduce the Problem

  1. Install Docker Geonode-Project
  2. Add data
  3. Append `--traceback` to https://github.com/GeoNode/geonode-project/blob/249f127401e74153b205fde8256353c88b3057c4/project_name/br/backup.sh#L35
  3. Run backup script from custom project folder with `docker exec -it django4wmrgeonode sh -c './wmrgeonode/br/backup.sh'`

## Specifications

  - GeoNode version: Geonode-Project 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Docker Compose
  - Platform: Docker running on Ubuntu 20
  - Additional details:

**Comment by cavernousguess** [comment]
A solution has been provided by @Pratyush1991 (many thanks). Adding some lines to the Geonode Core 3.2.1 `backup.py` file has fixed the serialization error.

### Fix
Add these two lines to the top of the `backup.py` file:
```
from django_jsonfield_backport.features import extend_features
from django.db import connection
```

![geonode_image1](https://user-images.githubusercontent.com/87546523/129111397-675e0b21-4729-4cbc-8ae6-61a81356ac4b.png)

Then add `extend_features(connection)` to function `def handle(self, **options)`:
```
def handle(self, **options):
    extend_features(connection)
    ...
```

![geonode_image2](https://user-images.githubusercontent.com/87546523/129111405-9813e111-daeb-45dd-8f5d-de1f0acd9526.png)

### Process
These are the steps I used for utilizing the edited `backup.py` file:

1. After setting up Geonode-Project with a custom directory, `cd` into the custom directory where the `docker-compose.yml` file is located.
2. Clone Geonode Core 3.2.1 into the above directory
    `git clone https://github.com/GeoNode/geonode.git -b 3.2.1 geonode`
3. Edit the geonode-project `setup.py` file, delete the `dependency_links` lines.
4. Edit the geonode-project `requirements.txt` file, comment out `Geonode==3.2.1` and add `-e ./geonode/` to the top of the file.
5. Build and compose up the Docker containers.
6.  Upload some data
7. Run the geonode-project backup command
8. Backup completes with a .zip file.

### Notes
The issue this fix solves is related to Django rather than the Geonode-specific code. Apparently the master branch of Geonode Core using Django 3.2.x does not experience this issue.

**Comment by giohappy** [comment]
@cavernousguess it would be nice if you could send a PR with the patch.

**Comment by cavernousguess** [comment]
@giohappy I'm unfamiliar with creating pull requests so it may be a few weeks before I have time to figure that out. It would be quicker for someone else to open a pull request for this issue instead.
