### ISSUE TITLE
No idea what 'devrequirements' is! 

### ISSUE THREAD

**Issue by ttungbmt** [GeoNode/geonode#7936]
## Steps to Reproduce the Problem

  1. Modify .env, DOCKER_ENV=production to DOCKER_ENV=development
  2. RUN compose up -d
  3.  Failed: "No idea what 'devrequirements' is!". Unknown @task devrequirements
![image](https://user-images.githubusercontent.com/12232155/128833818-76ddf434-0eb2-46bb-a446-40d2d95c965b.png)

## Specifications

  - GeoNode version: 3.2.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Docker Destktop (Window 10)
  - Additional details:

**Comment by giohappy** [comment]
hi @ttungbmt thansk for reporting this issue. I could replicate it. We will investigate and see what happened [to this line](https://github.com/GeoNode/geonode/blob/master/entrypoint.sh#L64), which invokes a non existing task.

**Comment by giohappy** [comment]
It has been removed quite a [long time ago](https://github.com/GeoNode/geonode/commit/6ea3992a8ffc7d4136ed9930c48912c0ad5569d7#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6L125-R256). Apparently the dev mode for docker is not used very much!

We have plans to resurrect the dev mode for docker, but we don't have any date.
