### ISSUE TITLE
Unable to build docker container to set up geonode version 3.3.x , 3.2.x and even 3.0

### ISSUE THREAD

**Issue by RenukaNaik** [GeoNode/geonode#7937]
## Expected Behavior
I am trying to host geonode on ubuntu 20.04 server, I have used the following documentation
https://docs.geonode.org/en/master/install/advanced/core/index.html#docker

At first, I tried version 3.3.x =>
I pulled docker images using following commands:
docker-compose -f docker-compose.yml pull
docker-compose -f docker-compose.yml up -d

Next when i checked for logs, it is giving error in log file.
docker logs -f django4geonode

**logs

(for geonode 3.3.X)

Restarting periodic command scheduler: cronStopping periodic command scheduler: cron.
Starting periodic command scheduler: cron.
Restarting memcached: memcached.
\n\n\n
-----------------------------------------------------
STARTING DJANGO ENTRYPOINT Thu Aug  5 05:23:31 UTC 2021
-----------------------------------------------------
***************************setting env*********************************
ACCOUNT_EMAIL_CONFIRMATION_EMAIL=False
MODIFY_TOPICCATEGORY=True
LDAP_USER_SEARCH_FILTERSTR=(&(uid=%(user)s)(objectClass=person))
X_FRAME_OPTIONS="SAMEORIGIN"
ASYNC_SIGNALS=True
DJANGO_EMAIL_USE_SSL=False
OGC_REQUEST_POOL_CONNECTIONS=10
DATABASE_URL=postgis://geonode:geonode@db:5432/geonode
OAUTH2_API_KEY=
OGC_REQUEST_MAX_RETRIES=1
ADMIN_USERNAME=admin
API_LOCKDOWN=False
HOSTNAME=f27aa688bb37
AUTO_ASSIGN_REGISTERED_MEMBERS_TO_REGISTERED_MEMBERS_GROUP_NAME=True
PYTHON_VERSION=3.8.9
DJANGO_EMAIL_HOST=localhost
ENABLE_JSONP=true
POSTGRES_PASSWORD=postgres
TIME_ENABLED=True
CENTRALIZED_DASHBOARD_ENABLED=False
AVATAR_GRAVATAR_SSL=True
ALLOWED_HOSTS="['django', '*']"
MONITORING_SERVICE_NAME=local-geonode
FAVORITE_ENABLED=True
USER_ANALYTICS_GZIP=True
MEMCACHED_LOCK_EXPIRE=3600
C_FORCE_ROOT=1
CACHE_BUSTING_STATIC_ENABLED=False
MOSAIC_ENABLED=False
DEFAULT_BACKEND_UPLOADER=geonode.importer
EXIF_ENABLED=True
COMPOSE_PROJECT_NAME=geonode
LOCKDOWN_GEONODE=False
LDAP_GROUP_SEARCH_FILTERSTR=(|(cn=abt1)(cn=abt2)(cn=abt3)(cn=abt4)(cn=abt5)(cn=abt6))
MAX_DOCUMENT_SIZE=2
RESOLVER=127.0.0.11
LDAP_USER_SEARCH_DN=dc=ad,dc=example,dc=org
MEMCACHED_BACKEND=django.core.cache.backends.memcached.MemcachedCache
DOCKER_HOST_IP=
PWD=/usr/src/geonode
BING_API_KEY=
ACCOUNT_AUTHENTICATION_METHOD=username_email
MEMCACHED_LOCK_TIMEOUT=10
HAYSTACK_ENGINE_INDEX_NAME=haystack
OGC_REQUEST_TIMEOUT=30
DJANGO_EMAIL_PORT=25
DEFAULT_ANONYMOUS_DOWNLOAD_PERMISSION=True
STATIC_ROOT=/mnt/volumes/statics/static/
_=/usr/bin/env
CACHE_BUSTING_MEDIA_ENABLED=False
GEONODE_DB_CONN_MAX_AGE=0
TASTYPIE_APIKEY=
BROKER_URL=amqp://guest:guest@rabbitmq:5672/
ADMIN_EMAIL=admin@localhost
HOME=/root
LANG=C.UTF-8
HTTP_PORT=80
DEFAULT_BACKEND_DATASTORE=datastore
CLIENT_RESULTS_LIMIT=5
outFormat=text/javascript
MAPBOX_ACCESS_TOKEN=
HAYSTACK_ENGINE_URL=http://elasticsearch:9200/
BACKUPS_VOLUME_DRIVER=local
SECRET_KEY='myv-y4#7j-d*p-__@j#*3z@!y24fz8%^z2v6atuy4bo9vqr1_a'
LDAP_BIND_DN=uid=ldapinfo,cn=users,dc=ad,dc=example,dc=org
ADMIN_PASSWORD=admin
DATABASE_PORT=5432
GPG_KEY=E3FF2839C048B25C084DEBE9B26995E310250568
GEONODE_DATABASE_SCHEMA=public
ACCOUNT_OPEN_SIGNUP=True
DJANGO_EMAIL_HOST_PASSWORD=
HAYSTACK_SEARCH_RESULTS_PER_PAGE=200
DJANGO_SETTINGS_MODULE=geonode.settings
GEOSERVER_JAVA_OPTS="-Djava.awt.headless=true -Xms2G -Xmx4G -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/var/log/jvm.log -XX:PerfDataSamplingInterval=500 -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:-UseGCOverheadLimit -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Dfile.encoding=UTF8 -Djavax.servlet.request.encoding=UTF-8 -Djavax.servlet.response.encoding=UTF-8 -Duser.timezone=GMT -Dorg.geotools.shapefile.datetime=false -DGEOSERVER_CSRF_DISABLED=true -DPRINT_BASE_URL=http://geoserver:8080/geoserver/pdf -DALLOW_ENV_PARAMETRIZATION=true -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-0.9.3-Unsafe.jar -Dsun.java2d.renderer=org.marlin.pisces.MarlinRenderingEngine"
ACCOUNT_EMAIL_REQUIRED=True
ACCOUNT_APPROVAL_REQUIRED=False
SITEURL=http://localhost/
MEMCACHED_ENABLED=False
GEONODE_LB_HOST_IP=localhost
LDAP_ENABLED=False
OAUTH2_CLIENT_ID=Jrchz2oPY3akmzndmgUTYrs9gczlgoV20YPSvqaV
API_LIMIT_PER_PAGE=1000
USER_ANALYTICS_ENABLED=True
DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
GEOSERVER_LOCATION=http://geoserver:8080/geoserver/
LDAP_BIND_PASSWORD=<something_secret>
ACCOUNT_EMAIL_VERIFICATION=none
GEONODE_GEODATABASE_SCHEMA=public
HAYSTACK_SEARCH=False
HTTP_HOST=localhost
GEONODE_INSTANCE_NAME=geonode
EMAIL_ENABLE=False
LETSENCRYPT_MODE=disabled
HTTPS_PORT=443
SHLVL=1
HTTPS_HOST=
OGC_REQUEST_POOL_MAXSIZE=10
POSTGRES_USER=postgres
ACCOUNT_EMAIL_CONFIRMATION_REQUIRED=False
GEODATABASE_URL=postgis://geonode_data:geonode_data@db:5432/geonode_data
LDAP_GROUP_PROFILE_MEMBER_ATTR=uniqueMember
DJANGO_EMAIL_USE_TLS=False
DJANGO_EMAIL_HOST_USER=
MONITORING_HOST_NAME=geonode
GEONODE_GEODATABASE_PASSWORD=geonode_data
IS_CELERY=False
GEONODE_DATABASE_PASSWORD=geonode
PYTHON_PIP_VERSION=21.1.1
DATABASE_HOST=db
GEOSERVER_PUBLIC_LOCATION=http://localhost/geoserver/
GEONODE_DB_CONN_TOUT=5
CORS_ORIGIN_ALLOW_ALL=True
GEOSERVER_ADMIN_PASSWORD=geoserver
CREATE_LAYER=True
PYTHON_GET_PIP_SHA256=f499d76e0149a673fb8246d88e116db589afbd291739bd84f2cd9a7bca7b6993
INVOKE_LOG_STDOUT=true
GOOGLE_API_KEY=
GEOIP_PATH=/mnt/volumes/statics/geoip.db
GEONODE_CLIENT_LAYER_PREVIEW_LIBRARY=mapstore
GEONODE_GEODATABASE=geonode_data
OGC_REQUEST_BACKOFF_FACTOR=0.3
PYTHON_GET_PIP_URL=https://github.com/pypa/get-pip/raw/1954f15b3f102ace496a34a013ea76b061535bd2/public/get-pip.py
FORCE_REINIT=false
MEMCACHED_LOCATION=127.0.0.1:11211
GEOSERVER_ADMIN_USER=admin
GEONODE_DATABASE=geonode
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEFAULT_ANONYMOUS_VIEW_PERMISSION=True
MONITORING_ENABLED=True
GEONODE_LB_PORT=80
DOCKER_ENV=production
DOCKER_API_VERSION="1.24"
GEOSERVER_WEB_UI_LOCATION=http://localhost/geoserver/
LDAP_GROUP_SEARCH_DN=cn=groups,dc=ad,dc=example,dc=org
DEFAULT_FROM_EMAIL='GeoNode <no-reply@geonode.org>'
ACCOUNT_CONFIRM_EMAIL_ON_GET=False
DEBUG=False
MEDIA_ROOT=/mnt/volumes/statics/uploaded/
OAUTH2_CLIENT_SECRET=rCnp5txobUo83EpQEblM8fVj3QT5zb5qRfxNsuPzCqZaiRyIoxM4jdgMiZKFfePBHYXCLd7B8NlkfDBY9HKeIQPcy5Cp08KQNpRHQbjpLItDHv12GvkSeXp6OxaUETv3
SESSION_EXPIRED_CONTROL_ENABLED=True
LDAP_SERVER_URL=ldap://<the_ldap_server>
MONITORING_DATA_TTL=365
Public Hostname or IP is localhost
Public PORT is None
Can not delete the $HOME/.override_env file as it doesn't exists
Traceback (most recent call last):
  File "/usr/local/bin/invoke", line 8, in <module>
    sys.exit(program.run())
  File "/usr/local/lib/python3.8/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/usr/local/lib/python3.8/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/usr/local/lib/python3.8/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/usr/local/lib/python3.8/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/usr/src/geonode/tasks.py", line 121, in update
    current_allowed.extend([str(pub_ip), f'{pub_ip}:{pub_port}'])
AttributeError: 'str' object has no attribute 'extend'

## Actual Behavior
I have installed the docker project before with these changes and it works but now it's causing this issue

## Steps to Reproduce the Problem

  1. Then I tried setting up geonode version 3.2.x,
      I am getting same error in log file as version 3.3.x     
  2. At last when I tried setting up version 3.0,
      the docker images buildind process was taking time longer than time it took previously and process did not complete.  

command used to build docker images: 
           docker-compose -f docker-compose.yml up --build -d

    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-61uht986/django-tastypie_ea1b9fad42b74b78b2178a7c0619aeb1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-61uht986/django-tastypie_ea1b9fad42b74b78b2178a7c0619aeb1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qkayid0q
         cwd: /tmp/pip-install-61uht986/django-tastypie_ea1b9fad42b74b78b2178a7c0619aeb1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-61uht986/django-tastypie_ea1b9fad42b74b78b2178a7c0619aeb1/setup.py", line 10, in <module>
        import rose
    ModuleNotFoundError: No module named 'rose'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b3/b2/8415d678042a364b73cefaacc2f22656a31e1a3b32dfd6703d8d83b41df9/django-tastypie-0.9.13.tar.gz#sha256=60ff6e88a8cf7a48b3ac9d23bb3307135bf153026beb6b9adbfac1bb586f516b (from https://pypi.org/simple/django-tastypie/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading django-tastypie-0.9.12.tar.gz (704 kB)
  Downloading django-tastypie-0.9.11.tar.gz (519 kB)
  Downloading django-tastypie-0.9.10.tar.gz (36 kB)
  Downloading django-tastypie-0.9.9.tar.gz (36 kB)
  Downloading django-tastypie-0.9.7.tar.gz (34 kB)
  Downloading django-tastypie-0.9.6.tar.gz (34 kB)
INFO: pip is looking at multiple versions of django-guardian to determine which version is compatible with other requirements. This could take a while.
Collecting django-guardian<2.3.1
  Downloading django_guardian-2.2.0-py3-none-any.whl (104 kB)
  Downloading django_guardian-2.1.0-py3-none-any.whl (102 kB)

## Specifications

-GeoNode version: 3.2
-Installation method (manual, GeoNode Docker, SPCGeoNode Docker):Geonode Docker
-Platform: Ubuntu 20.04
-Additional details:

**Comment by jitendrashahiitb** [comment]
Request response to this .
If this issue is faced by others , can we collaborate to find a solution?
