### ISSUE TITLE
OSM refuses to return tiles while generating thumbnails

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#7958]
## Expected Behavior
A thumbnail should have background graphics.

## Actual Behavior
The thumbnail only have graphic from the internal layer, with no background.

## Steps to Reproduce the Problem

  1. happens randomly when generating thumbnails.

## Specifications

  - GeoNode version: 3.2.x, 3.3.x, ...

Here the traceback
```
Thumbnail background fetching from https://maps.wikimedia.org/osm-intl/11/1630/961.png failed 0 time(s) with: cannot identify image file <_io.BytesIO object at 0xffff7ecf8270>
Thumbnail background fetching from https://maps.wikimedia.org/osm-intl/11/1630/961.png failed 1 time(s) with: cannot identify image file <_io.BytesIO object at 0xffff7ef31810>
Thumbnail background fetching from https://maps.wikimedia.org/osm-intl/11/1630/961.png failed 2 time(s) with: cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
Traceback (most recent call last):
  File "/usr/src/myproject/src/geonode/geonode/thumbs/background.py", line 347, in fetch
    Image.open(im).verify()  # verify that it is, in fact an image
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
Thumbnail generation. Error occurred while fetching background image: cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
Traceback (most recent call last):
  File "/usr/src/myproject/src/geonode/geonode/thumbs/thumbnails.py", line 194, in create_thumbnail
    background = BackgroundGenerator(width, height).fetch(bbox, background_zoom) if bbox else None
  File "/usr/src/myproject/src/geonode/geonode/thumbs/background.py", line 352, in fetch
    raise e
  File "/usr/src/myproject/src/geonode/geonode/thumbs/background.py", line 347, in fetch
    Image.open(im).verify()  # verify that it is, in fact an image
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xffff7ef1ac20>
```

## Solution

This is something also seen in geoserver. It seems that osm sometime denies the response when there is a generic "python" or "java" user agent in order to prevent some trivial bot attack.

The issue can be solved by adding the line
```python
headers['User-Agent'] = 'GeoNode'
```
just before the request at 
https://github.com/GeoNode/geonode/blob/1b714c902be4094ac7e10fcf925267ccfede62b2/geonode/utils.py#L1464

**Comment by mattiagiupponi** [comment]
@giohappy @etj I made a lot of testing (master & 3.3.x) and looks like that adding the user agent could be a solution, but probably is not the definitive one.
Reading the [Wikimedia terms of use](https://foundation.wikimedia.org/wiki/Maps_Terms_of_Use), we need a more robust user-agent:

> If you are developing an application that uses the Wikimedia Maps service, you must provide a valid HTTP User-Agent that includes your application, version, and sufficient information to easily contact you (e.g., your email address).

Plus in certain moments, Wikimedia reserves the right to block excessive requests to their service:

> - We reserve the right to discontinue or change our service, block or limit certain users or applications, or take other measures in cases at our sole discretion at any time without notice.
> - Excessive downloading is prohibited

So, the user agent could be a good solution to mitigate the issue, but we cannot be certain that this will fix forever the problem since (as they say) they could block for a limited time our requests.

**Comment by giohappy** [comment]
I know @mattiagiupponi. The plan is to investigate alternative services, includin the OSM served by our own (GeoSolutions maps).
