### ISSUE TITLE
The form account/login is redirecting automatically to account/signup

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode#7970]
## Expected Behavior

The login form should not redirect automatically to http://localhost:8000/account/signup after clicking on the login or password inputs

## Actual Behavior

There login inputs are wrapped with an `<a/>` tag that redirect to signup page and this is blocking the possibility to login in the master version of GeoNode 
![image](https://user-images.githubusercontent.com/19175505/130434752-553beee2-616d-492e-8a89-4bf46ebaea62.png)

## Steps to Reproduce the Problem

  1. open a Firefox browser version 91.0 (64 bit)
  2. navigate to http://localhost:8000/account/login
  3. try to login by fill the login and password fields
  4. as soon as you click on the login input the page is redirect to http://localhost:8000/account/signup

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: 
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal this issue affect particularly master but it also happens on 3.3 and 3.2. In these cases you can login because a popup appears, but it's, still annoying and a bug, so we want to address this for all versions.

**Comment by marthamareal** [comment]
I am able to reproduce the issue with Italian translation.(English looks good).

**Comment by marthamareal** [comment]
The issue here is with the italian translation using ``, the <a> tag is not closed properly making the whole fom an href eg this is the translation populated.
"Se non hai ancora creato un account, allora si prega di\n"
"      <a href=\"%(signup_url)s\">prima iscriviti</a."

**Comment by etj** [comment]
Lots of italian translations got lost with this commit.

Look for instance "health": 
https://github.com/marthamareal/geonode/commit/528b3d83323eab87eb003b4f60888ccc7243e42f#diff-b0b68729645be0830ded32fc640b67257edfe0d12234bd4043141f1eaa6079b8L743-L753

https://github.com/marthamareal/geonode/commit/528b3d83323eab87eb003b4f60888ccc7243e42f#diff-b0b68729645be0830ded32fc640b67257edfe0d12234bd4043141f1eaa6079b8R6198-R6208


The commented out entries should be restored.
Note that makemessages is not able to detect such strings bc they are not in the code but are needed to localize stuff in the db.
