### ISSUE TITLE
Create app for management commands

### ISSUE THREAD

**Issue by asgharsir** [GeoNode/geonode#7976]
Refer Epic #909:
Issue refers to a proposal:
> "to implement a mechanism inside GeoNode to generate an HTTP API for any management command. The idea is to expose management over a common HTTP endpoint, granting of course full control of which commands we want to be exposed and under which security restrictions."

## Proposed Solution
* [x] Explore the [django-http-commands](https://github.com/geosolutions-it/django-http-commands) library to undestand the proposal.
* [x] Create an app called `mngmt_commands_http`.
* [x] Create a decorator `expose_command_over_http` to indicate that a specific command should be exposed or not.
* [x] Implement method to list the exposed commands.
    * Note: Using `django.core.management.get_command` to list the commands and a decorator on the commands that we want to be exposed.
    * Note: Only the commands with the decorator `@expose_command_over_http` are going to be exposed.
* [x] Create a Model for the ManagementCommandJob:
    * Fields: command, app_name, user, args, kwargs, output_message, start_time, end_time, celerytaskresult (FK).
    * Status options: Created, Queued, Running, Success, Failed.
    * Method: `start_task` --> Change status from `created` to `queued` and adds to the celery queue.
* [x] Create a method to handle the job running (`run_management_command`):
    * Redirects stdout and stderr to the `output_message` field.
    * Updated the status to --> `running` (on enter) and `success` or `fail` (on exit). 
* [x] Create a single celery async task: Call the `run_management_command` method.
* [x] Create an APIView, providing the following endpoints:
    * [x]  `GET` `/api/v2/management/` : **List** exposed commands
    * [x] `GET` `/api/v2/management/<cmd_name>`: Get the **help message** of a given cmd_name (if it's exposed)
    * [x] `POST` `/api/v2/management/<cmd_name>`: **Create** and **run** an async job with the given command. 
* [x] Tests and validation

##  Alternative solutions considered.
On the discussion of the issue #920, some alternative solutions were considered.
* ~Using `django-http-commands` as external library~ --> The approach to add an app alongside the geonode apps was chosen.
* Not creating a model for the ManagementCommands -->  Following this approach because all the management commands can be listed by the `django.core.management.get_command` django built-in function.
* ~Not creating a model for the ManagementCommandJobs~ --> A model will be created, although celery's TaskResult model is already storing some data related to the task, it's better to store these requests separately and to have control over the celery execution. Also, following this approach, we can show/control the results in the django-admin page and use a ModelViewSet (See pictures below).

## Additional context
* Admin view (list) for ManagementCommandJobs
![image](https://user-images.githubusercontent.com/12943132/132017699-db3ce1d3-0b1d-4f16-9324-15c91d9adb9e.png)
* Admin view (details)
![image](https://user-images.githubusercontent.com/12943132/132017956-80db092a-4609-460d-bca7-1e2f04ca00af.png)

* Response of `POST` `/api/v2/management/<cmd_name>`
```json
{
    "success": true,
    "error": null,
    "data": {
        "id": 129,
        "command": "sleep_some_minutes",
        "app_name": "geonode.base",
        "status": "QUEUED",
        "args": "[0.1]",
        "kwargs": "{}"
    }
}
```

**Comment by t-book** [comment]
awesome!

**Comment by gannebamm** [comment]
@giohappy @afabiani is there an example how to use this for updating layers? Like this:

> `./manage.sh updatelayers --store=STORE --workspace=WORKSPACE --skip-geonode-registered`

**Comment by giohappy** [comment]
@gannebamm [here the async commands are explained](https://docs.geonode.org/en/master/admin/mgmt_commands/index.html#async-execution-over-http), along with examples to execute them from the Django admin or http calls
