### ISSUE TITLE
Delegate data download to the client's export tool

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8006]
The operations performed by the data download (except the direct download of the original files) are heavy and detrimental for performances, in particular when filtering is applied. 

 - In general the use of Geoserver WFS requests for the download of entire datasets is discouraged
 - the setup of the filter options triggers many requests to Geoserver to obtain the required information about the dataset
 - filters on WFS can be extremely heavy operations for big datasets

MapStore client implements a much more efficient approach to data export, based on the GeoServer export WPS extension. This is the only available option on master version, but on 3.2.x and 3.3.x we still have both the MapStore export and the GeoNode download options.

We want to drop the data download options from the GeoNode views and delegate the operation to the client. 
A dedicated epic will implement the prerequisites to enable this approach https://github.com/GeoNode/geonode-mapstore-client/issues/471.

The tasks for this issue are:

1. **removal of the filter section from GeoNode templates and the backend functionalities (views, methods, etc.) which will not be needed anymore**
2. **removal of the list of format options and the backend functionality that drive them**

The final UI is depicted here below:

![image](https://user-images.githubusercontent.com/571129/130921467-6a3deb36-a030-4503-94ab-e3c40cd117cf.png)

**Comment by marthamareal** [comment]
@giohappy The PRs blocking this are ready.
