### ISSUE TITLE
GeoStory: missing "favorite" handling

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8059]
## Expected Behavior

As for the other resources, it is expected to mark a GeoStory as favorite.

## Actual Behavior

"favorite" tab is missing

![image](https://user-images.githubusercontent.com/717359/132336063-fdfa0020-426c-48fa-84d3-c30cb1c02698.png)

## Specifications

  - GeoNode version: at least 3.3

**Comment by marthamareal** [comment]
@giohappy, I have implemented this on only 3.3.x and 3.2.x since master has new designs and I do not see a menu for comments, ratings etc.
