### ISSUE TITLE
Export layer data fails in Geonode 3.2.1 / GeoServer 2.18.3

### ISSUE THREAD

**Issue by tpot1** [GeoNode/geonode#8062]
## Expected Behavior
Able to successfully download layer data using the 'Export layer data' button

## Actual Behavior
Export fails with the error: `Download process failed! The server has returned incorrect data, error code: "{errorCode}"`
There is also an error in the GeoServer logs - see below

## Steps to Reproduce the Problem

  1. Load a layer onto a map
  2. Select the layer in the table of contents and click the 'Export layer data' button
  3. Select any file format and spatial reference system and click 'Export'
  4. The export process starts, but fails with the above error message

## Specifications

  - GeoNode version: 3.2.1
  - GeoServer version: 2.18.3
  - Mapstore Client Version: 3.2.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Debian 9.13

## Additional details:
We are using Geonode 3.2.1 with the GeoServer 2.18.3, as per the release notes (https://github.com/GeoNode/geonode/releases/tag/3.2.1)

Our investigations indicate that this is an issue with GeoServer 2.18.3. Reverting to GeoServer 2.18.2 fixes this issue for us, however we are looking for a solution that allows us to continue using 2.18.3.

The GeoServer logs show the following error:
`2021-08-31 09:01:54,216 ERROR [wps.executor] - Failed writing out the results org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'scopedTarget.geoNodeOauth2RestTemplate': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request. at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:369) at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) at org.springframework.aop.target.SimpleBeanTargetSource.getTarget(SimpleBeanTargetSource.java:35) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:675) at org.springframework.security.oauth2.client.OAuth2RestTemplate$$EnhancerBySpringCGLIB$$b9d9afcd.getOAuth2ClientContext(<generated>) at org.geoserver.security.oauth2.OAuth2AccessTokenURLMangler.mangleURL(OAuth2AccessTokenURLMangler.java:78) at org.geoserver.ows.util.ResponseUtils.buildURL(ResponseUtils.java:372) at org.geoserver.wps.executor.ExecuteResponseBuilder.build(ExecuteResponseBuilder.java:112) at org.geoserver.wps.executor.WPSExecutionManager$Executor.execute(WPSExecutionManager.java:472) at org.geoserver.wps.executor.WPSExecutionManager$Executor.call(WPSExecutionManager.java:381) at org.geoserver.wps.executor.WPSExecutionManager$Executor.call(WPSExecutionManager.java:310) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request. at org.springframework.web.context.request.RequestContextHolder.currentRequestAttributes(RequestContextHolder.java:131) at org.springframework.web.context.request.SessionScope.get(SessionScope.java:55) at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:357) ... 14 more`

**Comment by etj** [comment]
Try removing the `geoServerOAuth2AccessTokenURLMangler` bean in the `applicationContext.xml` file inside the `oauth2-geonode` jar file:

https://github.com/geoserver/geoserver/blob/2.18.3/src/community/security/oauth2-geonode/src/main/resources/applicationContext.xml#L39-L44

The bean has been removed from the 2.18.4 on.

**Comment by tpot1** [comment]
Thanks @etj, I've removed that bean and the export is now working as expected.

Do you know if removing that bean can cause any other issues? It looks stable to me, but I imagine there was a reason why it was included in 2.18.3?
