### ISSUE TITLE
Add a call to RM.update inside sync_geonode_layers command

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8116]
Currently there's now way to trigger an update on a dataset, and trigger the downstream logic like recalculation of the dataset's bbox.

We want to add the `resource_manager.update(resource.uuid)` command at the end of `sync_geonode_layers` management command as a facility to trigger the update.

**Comment by afabiani** [comment]
- GeoNode PR available [here](https://github.com/GeoNode/geonode/pull/8117)
- Documentation PR available [here](https://github.com/GeoNode/documentation/pull/158)
