### ISSUE TITLE
 Remote Services: Vector Tile Server

### ISSUE THREAD

**Issue by CodeSpatial** [GeoNode/geonode#8133]
**Is your feature request related to a problem? Please describe.**

A number of our larger vector datasets are served using pg_tileserv. Currently I can't add these to geonode and am left with a lingering vector tile service that I have to find a way to duplicate in GeoServer - which by default doesn't serve mapbox vector tiles to begin with.

These are also quite useful for dynamically loading parametric functions built within PostGIS as they show up immediately within the service as long as they are returning MVT types.

**Describe the solution you'd like**

The ability to add a vector tile service that follows the [vector tile spec](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers) and be able to add these layers, attach metadata, and view these vector layers within GeoNode.

**Describe alternatives you've considered**

I've considered adding the mapbox tile plugin to GeoServer and adding each layer again along with SQL views that call custom PostGIS functions. 

**Additional context**

Here is the link to [pg_tileserv](https://github.com/CrunchyData/pg_tileserv)

**Comment by rajanski** [comment]
I'd use that too

**Comment by jeff-bradley** [comment]
has this been implemented?

**Comment by giohappy** [comment]
@jeff-bradley nope
