### ISSUE TITLE
"Found conflicting types Double and Long" for GeoJSON is a bug

### ISSUE THREAD

**Issue by markstos** [GeoNode/geonode#8150]
## Expected Behavior

I uploaded a GeoJSON file on the demo site and expected it to be imported.

## Actual Behavior

I got this error:

 "Found conflicting types Double and Long for property buildingDensity".

From reading the GeoJSON spec, GeoJSON defers to the JSON spec on what a valid number is in GeoJSON: Here's the JSON reference:

https://datatracker.ietf.org/doc/html/rfc7159#section-6

The triggering file passes both a JSON linter and GeoJSON linter.

If files are valid GeoJSON, then GeoNode should cast the numbers to a compatible type, not throw an error.

## Steps to Reproduce the Problem

  1.  Upload a GeoJSON with properties values  that would cast to both Double and Long for the same property.
  2. There is no step 2.

## Specifications

  - GeoNode version: Whatever your stable site is running. 
  - Installation method: However you installed the demo site.
  - Platform: Whatever your demo site is running on.
  - Additional details: None.

**Comment by markstos** [comment]
While I can't see which numbers triggered the conflict, I reviewed the values I have in the triggering field. They are all within 1-100 range. This is about the most digits I can find involved in one:  

  `0.00037374442902109574`

Other values simply "0" or "100"

So I check how those three values get cast when used as a GeoJSON property.

**Comment by giohappy** [comment]
@markstos the error is thrown by Geoserver, in particular by Geotools' geojsonstore module [here](https://github.com/geotools/geotools/blob/main/modules/unsupported/geojson/src/main/java/org/geotools/geojson/feature/FeatureTypeHandler.java#L137).

Honestly I don't know why it doesn't try to change the schema when conflicting types are parsed, but in case this is something to be asked on the Geotools ML. However that module is in an unsupprted state. It's been superseded by [GeoJSONDatastore](https://docs.geotools.org/stable/javadocs/org/geotools/data/geojson/GeoJSONDataStore.html), but Geoserver importer (which is what GeoNode uses) doesn't support it yet.

**Comment by markstos** [comment]
@giohappy Thanks for the prompt reply.  

So Geonode's route to resolving this is that the Geoserver Importer plans to use GeoJSONDatastore in the future, and that fix will eventually resolve the issue for Geonode?
