### ISSUE TITLE
Create Endpoints to handle Management Command Jobs

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8158]
**Is your feature request related to a problem? Please describe.**
Refers #7976.
The task #8052 provides a way to create exposed management commands calling endpoints over HTTP.
This issue aims to provide the needed endpoints to handle the management commands jobs (Create, Read, Update). And also to improve the admin GUI. 

**Describe the solution you'd like**
* Creates the following endpoints for ManagementCommandJobs.
    * [x] `GET` `/api/v2/management/jobs/`:  **List** jobs.
    * [x] `POST` `/api/v2/management/jobs/{id}/`: **Details** of a job.
    * [x] `PATCH` `/api/v2/management/jobs/{id}/start/`: **start** action.
    * [x] `PATCH` `/api/v2/management/jobs/{id}/stop/`: **stop** action.
    * [x] `GET` `/api/v2/management/jobs/{id}/status/`: **status** action (celery details).
    * [x]  `GET` `/api/v2/management/commands/<cmd_name>/jobs/` : **List** jobs filtered by `cmd_name`.
* [x] Add a **create** option in django admin, the available commands should be displayed as a ChoicesField.
* [x] Tests and validation

**Describe alternatives you've considered**

**Additional context**

**Comment by giohappy** [comment]
Waiting for port to master branch.
