### ISSUE TITLE
GeoApps: missing actions in user profile page

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8174]
As a continuation of #8058, all available GeoApps should be considered (previous issue was only about GeoStories, but we should consider dashboards as well)

Pls consider that some geoapps may be disabled, so provide some logic to only handle available geoapps.

**Comment by marthamareal** [comment]
> Pls consider that some geoapps may be disabled, so provide some logic to only handle available geoapps.

@etj How are geoapps disabled?
