### ISSUE TITLE
Bad behaviour in upload page when no file is selected

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8179]
## Expected Behavior

When uploading a resource, the "upload" button should be disabled or return an error if no file il selected.

## Actual Behavior
The "Uploading" dialog pops up and never exits:
![image](https://user-images.githubusercontent.com/717359/135428293-2040fc00-0efc-4f1e-a9ff-829d3802d517.png)

## Steps to Reproduce the Problem

  1. go to "upload documents"
  2. press the "Upload" button
  3. the "uploading.." dialog pops up and won't exit

## Specifications
  - GeoNode version: 3.3.x
  - Additional details: replicated on development.demo

**Comment by marthamareal** [comment]
We could provide a form validity check [here](https://github.com/GeoNode/geonode/blob/3.3.x/geonode/documents/templates/documents/document_upload.html#L54) before showing the dialog.
