### ISSUE TITLE
Strange the style editor behavior

### ISSUE THREAD

**Issue by CAIAG-D** [GeoNode/geonode#8183]
## Expected Behavior
After new style created, it should be accessible for editing anytime by the layer owner. 

## Actual Behavior
After first saving of the layer, the style editor button ("Edit selected style") gets a "disabled" status. 

## Steps to Reproduce the Problem

  1. Add new layer by loading shape-files. 
  2. Go to "Data->Layers".
  3. Select by click the layer.
  4. Click "Editing Tools", then "Edit" under "Styles" caption.
  5. Press "Create new style" button, select any template at bottom and press "Add selected template to list of styles".
  6. Confirm "Save".
  7. Now the "Edit selected style" tool is still active.
  8. Push "Save" button.
  9. Now in the "Selected layer settings" -> "Style", the "Edit selected style" tool is in a disabled state...

## Specifications

  - GeoNode version: 3.2.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): In exact accordance with this manual for Ubuntu: https://docs.geonode.org/en/master/install/basic/index.html
  - Platform: Ubuntu 20.04.3 LTS
  - Additional details:

**Comment by giohappy** [comment]
@CAIAG-D this is a known issue. We're already [working on it](https://github.com/GeoNode/geonode-mapstore-client/issues/519). This is caused by a change to Geoserver.
