### ISSUE TITLE
geonode 1.2 package installation fails on Ubuntu 12.04 if python-django package is installed.

### ISSUE THREAD

**Issue by nastasi-oq** [GeoNode/geonode#821]
If python-django package is installed the pip install in the installation script skip django installation and than some import fails breaking the package.

To test it:
- apt-get install python-django
- apt-get install geonode
- go to the homepage of geonode => HTTP 500 return code.

**Comment by jj0hns0n** [comment]
Can we close this?

**Comment by capooti** [comment]
+1 to close it
