### ISSUE TITLE
CSV upload issues

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8231]
## Actual Behavior

When a CSV file is uploaded, this line is shown:
![image](https://user-images.githubusercontent.com/717359/136926877-1375fcb0-7290-4ae6-a286-a9b94dc8bdd1.png)

As a first (minor) issue, the polling toward the server sends too many requests (15-20 per second).

Once the lat lon column and CRS are selected, and the layer is created both in GeoServer and in GeoNode, the entry is sill at 50% in the "upload layer" page.
Furthermore, is you click on the ">" button to configure (again) the layer, you'll get this error
```
{"success": false, "errors": ["Unexpected exception File does not exist: /mnt/volumes/statics/static/tmpufk77h74/anagrafica.csv"]}
```
in a blank page with plain json:

## Expected Behavior

- [ ] the polling should send much less requests 
- once configured, 
  - [ ] the layer should be reported as 100%
  - [ ] the ">" button should not be displayed
  - [ ] the layer name should be a link to the actual layer page

## Steps to Reproduce the Problem

  1. upload any csv file
  2. run the configuration steps (assign lat, lot, crs)
  3. go back in the "upload layer" page

## Specifications

  - GeoNode version: 
    - 3.3.x, 
    - 3.2.x, 
    - master : only has the fast polling issue, the layer is not displayed again in the "load layer" page

**Comment by etj** [comment]
You can use this csv as sample file

[anagrafica2.csv](https://github.com/GeoNode/geonode/files/7330820/anagrafica2.csv)

**Comment by afabiani** [comment]
@etj @italogsfernandes I guess this affects 3.2.x too, right?
