### ISSUE TITLE
Change map print header image

### ISSUE THREAD

**Issue by Mianveca** [GeoNode/geonode#8317]
How can you change the default image of the print header in geonode version 3.2?
![Captura](https://user-images.githubusercontent.com/9463172/140339083-facf6623-78f8-4997-a5a6-ea2ca5a035c1.PNG)

**Comment by AleMScof** [comment]
Hi @Mianveca ,
this file is located under GEOSERVER_DATA_DIR/printing/print_header.png

you can change that one according to your needs
