### ISSUE TITLE
Wrong match for Geoserver path

### ISSUE THREAD

**Issue by AleMScof** [GeoNode/geonode#8318]
Looking at the lines below there's a control where you are checking if 'rest' is in the path. 
I have no idea all the use cases to which this event is related to but actually if a layerName contains the word rest let's say "forest" the url returned is wrongly manipulated causing WFS for instance to return a 404 error

As an example
if the url it's composed this way:

`http://localhost:8080/geoserver/ows?service=WFS&version=1.1.0&request=DescribeFeatureType&typeName=geonode:tipi_forestali&outputFormat=application/json&access_token=something`

Due to the condition it turns to (missing ows)
`http://localhost:8080/geoserver/service=WFS&version=1.1.0&request=DescribeFeatureType&typeName=geonode:tipi_forestali&outputFormat=application/json&access_token=something`

https://github.com/GeoNode/geonode/blob/5d07a010667e5437c1ee741131738702c0a98fb3/geonode/geoserver/views.py#L466

This can be replicated over all branches: master,development,stable

**Comment by afabiani** [comment]
That looks a major issue, thanks for reporting.
