### ISSUE TITLE
Geoapp thumbnails uploaded from the MapStore client disappear after saving the metadata from the wizard

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8325]
Apparently the path for setting the thumbnails of a geoapp are different when the thumbnail is set during the "Save As" from the client editor or the thumbnail is set from the Editing tools.

In the frist case we obtain a strange behaviour: **the thumbnail is removed when the metadata are updated using the wizard page. It doesn't happen with the advnaced metadata edit**. 
I suspect something wrong happens with the thumbnail widget inside the wizard page. Maybe it doesn't set correctly the body data that is sent to the backend?

![save geostory with thumbnail](https://user-images.githubusercontent.com/571129/140531850-3200174b-f2f7-4458-b040-c34920c903ef.gif)

**Comment by afabiani** [comment]
I suspect the form sends an empty value for the `thumbnail` on `submit`.

**Comment by marthamareal** [comment]
The form data sent does not include the thumbnail, and also on the value shows no file is selected.
![im](https://user-images.githubusercontent.com/20810749/140557505-54743685-c138-48db-9a50-46f012a4b363.png)


**NOTE** i checked and below is how thumbnail is saved.
![url](https://user-images.githubusercontent.com/20810749/140556736-c876dea7-fa20-4db6-a7e2-d8008bde0b1e.png)

However, On taking the following steps:
1. Create a new geoapp with a thumbnail image
2. Go to metadata form
3. Update thumbnail image using choose file then update the whole form

The thumbnail will not be replaced

**Comment by afabiani** [comment]
@marthamareal nope, I don't think this is good solution, even because someone might need to modify the thumbnail link manually by uploading a file via the admin dashboard.
