### ISSUE TITLE
The final file extension is incorrect when exporting data from the attribute table

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8327]
@giohappy commented on [Fri Nov 05 2021](https://github.com/GeoNode/geonode-mapstore-client/issues/572)

By exporting data (GeoJson, GeoPackage, CSV, Shapefile, wfs-collection-1.1 and wfs-collection-1.1) from the Attribute Table the fianl file is on `tif` extension.

**How to Reproduce**
Follows the steps on the gif below:

![2](https://user-images.githubusercontent.com/56537133/140510340-fb4209e7-4c5d-446b-a815-2009db4a6b50.gif)

## Other useful informations
On GeoNode 3.3.0

**Comment by giohappy** [comment]
The problem surfaces because the export from the FeatureGrid uses the Geoserver URL returned inside the [wfs](url) property of the layer configuration, which is the proxied Geoserver and not the direct URL as used by the export from the TOC.

Example:

![image](https://user-images.githubusercontent.com/571129/140553086-15217be5-32fa-4412-9a9a-d43d997ac58d.png)

Apparently the GeoNode proxy strips the Content-Disposition header from the final WPS response from Geoserver.
The following two requests represent two results and their respective response headers.

**Response through GeoNode proxy** -> the result is saved as *.tif (**NOTICE**: that this depends on Geoserver returning a wrong `image/tiff` mimetype)
`https://development.demo.geonode.org/gs/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=af4b58a3-1953-4502-841d-85dbb9ffb120&outputId=result.zip&mimetype=image/tiff`
```
Access-Control-Allow-Credentials: false
Access-Control-Allow-Headers: Content-Type, Accept, Authorization, Origin, User-Agent
Access-Control-Allow-Methods: GET, POST, PUT, PATCH, OPTIONS
Cache-Control: public, must-revalidate, max-age=30
Connection: keep-alive
Content-Language: en
Content-Length: 116559
Content-Type: image/tiff
Date: Fri, 05 Nov 2021 17:19:11 GMT
Server: nginx/1.17.2
Set-Cookie: sessionid=q4culn1qddd4747erb6xkn19b3p0kevl; HttpOnly; Path=/; SameSite=Lax
Strict-Transport-Security: max-age=3600; includeSubDomains
Vary: Authorization, Accept-Language, Cookie, Origin
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
```

Direct response -> the result is saved accordingin to the content disposition (result.zip)
`https://development.demo.geonode.org/geoserver/ows?service=WPS&version=1.0.0&request=GetExecutionResult&executionId=c84e6fa4-5632-4d98-a7c0-28e6854943ed&outputId=result.zip&mimetype=image/tiff`
```
Connection: keep-alive
Content-Disposition: inline; filename=result.zip
Content-Type: image/tiff
Date: Fri, 05 Nov 2021 17:20:11 GMT
Server: nginx/1.17.2
Set-Cookie: GS_FLOW_CONTROL=GS_CFLOW_-5606394a:17bf46c2a90:-7ff4
Transfer-Encoding: chunked
X-Control-flow-delay-ms: 0
```

1 - @afabiani we should give a look to the gs proxy and check why the content-disposition gets stripped
2 - @simboss Geoserver returns a wrong mime-type. If the content-disposition is present it overrides the mime-type, but I think this should be fixed in any case in Geoserver

**Comment by giohappy** [comment]
@afabiani the problems is still reproducible on development demo. Can you please check?

**Comment by simboss** [comment]
@afabiani before closing an issue we need to make sure we have actually tested that the fix work.
We have now 3 demo servers, let's make them to good use, please.

**Comment by afabiani** [comment]
@giohappy it looks like the `HttpResponse` behaves a little differently on Django 2. Sending a PR for 3.3.x and 3.2.x

**Comment by giohappy** [comment]
@simboss issue for Geoserver created https://github.com/geosolutions-it/geoserver/issues/318

**Comment by giohappy** [comment]
In the end the problem can be solved client side.
Issue for MapStore created https://github.com/geosolutions-it/MapStore2/issues/7536

**Comment by afabiani** [comment]
it should be good now, waiting for the fixes to be re-deployed on demo instances.
