### ISSUE TITLE
Implement upload size limiting mechanism for datasets

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8346]
GeoNode currently doesn't provide an explicit and controlled mechanism to limit the upload size for datasets (and documents).
In the past custom configurations (mainly at the level of Nginx) have been adopted to enforce such a limit, but suche solutions lacl an integration with the client (leading to a poor UX) and require to set fixed configurations that cannot be easily changed at runtime.

In view of introducing additional controls over upload funtionality (e.g. rate limiting, quota limits, etc.) we want, as a first step, introduce a size limiting mechanism inside GeoNode core. 

It will be controlled by a new global configuration (to be placed inside GeoNode settings module). A numerical value will set the file size limit for the fiels that a user can upload for a single session.

The implementation will:

- provide the means to let frontend clients cooperate (expose the limits to the client through configurations). For example, client might block the upload operation from the beginning by inspecting files size
- integrate with the Upload API to support the required messaging between the frontend and the upload backend (e.g. for reporting limits, errors, etc.)
- provide an internal API that can be used by GeoNode modules to query for the configured limits
- offer a high level interface to be integrated inside the Upload module (APIs / views), with an underlying concrete implementation that could be adapted for master (the target of this proposal) and 3.3.x (optional backporting). 

An analysis of the interactions between the Upload module and the Resource Manager +  Storage Manager services will be required to define the right placement and architecture of this size limiting component.

**Comment by italogsfernandes** [comment]
@giohappy What should be the default value for the upload size limits of these files: 
* base_file: __ MB
* dbf_file: __ MB
* shx_file: __ MB
* prj_file: __ MB
* xml_file: __ MB
* sld_file: __ MB

I set as 100MB for the moment, but it was a random guess.

**Comment by giohappy** [comment]
The limit must be applied to the sum of files and it's fine to set 100MB by default.

**Comment by italogsfernandes** [comment]
> The limit must be applied to the sum of files and it's fine to set 100MB by default.

Updated on PR https://github.com/GeoNode/geonode/pull/8512
