### ISSUE TITLE
Implement limiting for the number of upload sessions per user

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8347]
In view of introducing additional controls over upload funtionality (e.g. [size limit](https://github.com/GeoNode/geonode/issues/8346), quota limits, etc.) we want to introduce the ability to control the maximum number of active upload sessions per user.

It will be controlled by a new global configuration (to be placed inside GeoNode settings module). A numerical value will set the numbers of active upload sessions that a user can execute. Any additional attempt to upload will be blocked until a previous session has completed. 

The implementation will:

- provide the means to let frontend clients cooperate (expose the limits to the client through configurations). For example, client might block the upload operation from the beginning by inspecting files size
- integrate with the Upload API to support the required messaging between the frontend and the upload backend (e.g. for reporting limits, errors, etc.)
- provide an internal API that can be used by GeoNode modules to query for the configured limits
- offer a high level interface to be integrated inside the Upload module (APIs / views), with an underlying concrete implementation that could be adapted for master (the target of this proposal) and 3.3.x (optional backporting).

**Comment by giohappy** [comment]
@marthamareal pkease test this once deployed.

**Comment by marthamareal** [comment]
Tests are passing
