### ISSUE TITLE
Missing feeds for groups

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8353]
## Expected Behavior

Group feeds should contain activities at least for default resources (layer, maps, documents)

## Actual Behavior

Different versions seems to have different behaviours (checked on demo instances):
- stable (3.2.x) only has feeds for layers (no map and documents)
- dev (3.3.x) only has feeds for maps
- master: 
  - layers ok (both in all and in layers tab)
  - maps ok in "all" tab, "map" tab is not working (try moving from one other tab to "map")
  - documents: no feeds at all

**Comment by giohappy** [comment]
@etj where do you see feed tabs on master? Legacy pages? They're being removed, piece by piece, so they shouldn't be taken in consideration.

**Comment by etj** [comment]
@giohappy feed for group "test-group": https://master.demo.geonode.org/groups/group/test-group/activity/

**Comment by afabiani** [comment]
@etj there's nothing wrong with the groups activities at least on 3.2.x and 3.3.x

![image](https://user-images.githubusercontent.com/1278021/140934206-77a5da87-d7c2-458b-a37e-fa1af820dae4.png)

Simply those ones list only the objects belonging to the selected group (aka you need to set the group from the metadata editor)

**Comment by etj** [comment]
Ok, it seems there's a misalignment about group handling: sometimes a resource is belonging to a group if its owner belongs to it, some other times (like in this case) you have to assign the group to the resource by editing its metadata.
Anyway this misalignment is beyond the scope of this issue, so I guess this one can be closed.

**Comment by giohappy** [comment]
in general a resource is not considered to be assigned to group "through" group members, but I can imagine there are blocks in GeoNode that assumes this...
