### ISSUE TITLE
Synch BBOX from GeoServer

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8360]
**Is your feature request related to a problem? Please describe.**

It happened in various servers that a GeoServer layer had bad bbox (e.g.: ![image](https://user-images.githubusercontent.com/717359/140169788-e44cf499-2108-413d-8a41-49a5f7d4897a.png)

Pressing the "compute from data" button sets the right coordinates, but GeoNode bbox remains the old (bad) ones.
Pls consider that this error also creates bad request for OGC services.

**Describe the solution you'd like**

One of the sync scripts should be improved by adding the possibility to synch the bbox from geoserver.

We may want to add an `--updatebbox`  argument to `sync_geonode_layer`.

**Describe alternatives you've considered**

Editing the bbox in the metadata form is not implemented.

**Additional context**

Master already implements a `--updatebbox` argument
https://github.com/GeoNode/geonode/blob/04c8d08af1800502f8a7820f18e15b67864a0b9b/geonode/geoserver/management/commands/sync_geonode_datasets.py#L65-L67, but
1. it has not been ported to 3.3.x
2. the implementation in master updates more than the only bbox, so master behaviour should be reviewed as well

**Comment by etj** [comment]
@giohappy shall we open a issue on its own about the revision of the master behaviour?

**Comment by marthamareal** [comment]
@afabiani, I see 3.3.0 milestone removed, does it mean this will be done for only 3.2.x?

**Comment by afabiani** [comment]
@marthamareal both 3.3.0 and 3.2.x
Major issues must be always backported to 3.2.x too

**Comment by afabiani** [comment]
@etj @marthamareal let's please open another issue to change the behavior of the command.For the time being let's just backport that option.

**Comment by etj** [comment]
@afabiani I don't see this as a major "issue": I opened this as an enhancement/feature and not as a bugfix. I'd add this feature on 3.2.x only if it's easily backportable.

What do you mean by "let's please open another issue to change the behavior of the command"? For `master`?

**Comment by giohappy** [comment]
If the command is working fine on `master` a backprot to 3.3.x and 3.2.x is all that we need, isnt'it?

Aside: why is this method named [is_monochromatic_image](https://github.com/GeoNode/geonode/blob/5b4edf0f35dc5441f45ff2087756fdae7492af4e/geonode/utils.py#L2075)? From what I see it checks if the path refers to a real image... it doesn't check if the image is monochromatic. This is just for curiosity, I'm not asking to change it!

**Comment by etj** [comment]
@giohappy I would not define it "working fine": the `--updatebbox` argument will make the procedure call the method [`sync_instance_with_geoserver`]( https://github.com/GeoNode/geonode/blob/04c8d08af1800502f8a7820f18e15b67864a0b9b/geonode/geoserver/helpers.py#L1495) which is updating much more stuff than the bbox alone.

**Comment by afabiani** [comment]
@etj you marked this as `major`

**Comment by afabiani** [comment]
@etj @giohappy @marthamareal in the end I took the occasion to refactor the PR from @marthamareal and added the option to update the bbox only to the method `sync_instance_with_geoserver`
