### ISSUE TITLE
GeoStory: Can't add map in media block

### ISSUE THREAD

**Issue by mradamcox** [GeoNode/geonode#8374]
## Expected Behavior
Adding a media block with a GeoNode Map in it should work.

## Actual Behavior
Whenever I try to add a media section with a Map in it, I get a "something has gone wrong" error. The output from the django dev server says that the Map object can't be found.
```
Traceback (most recent call last):
  File "env/lib/python3.8/site-packages/mapstore2_adapter/plugins/serializers.py", line 80, in get_queryset
    map_obj = _resolve_map(
  File "geonode/geonode/maps/views.py", line 111, in _resolve_map
    return resolve_object(request, Map, {key: id}, permission=permission,
  File "geonode/geonode/utils.py", line 887, in resolve_object
    obj = get_object_or_404(model, **query)
  File "env/lib/python3.8/site-packages/django/shortcuts.py", line 95, in get_object_or_404
    raise Http404('No %s matches the given query.' % queryset.model._meta.object_name)
django.http.response.Http404: No Map matches the given query.
```
What seems to be happening is that the Mapstore Map object pk is being used to find the Geonode Map object (which has a different pk).

I've tracked the problem to [this function](https://github.com/GeoNode/geonode-mapstore-client/blob/6d44e4be6a80afe917fe469a38ffbb00fa9cfe54/mapstore2_adapter/plugins/serializers.py#L72) which seems to have been removed since the 3.2.1 mapstore client release.

Perhaps I need to upgrade something? I've looked through issues on this repo and the mapstore client repo but haven't found mention of this issue.

## Steps to Reproduce the Problem

  1. Create a Map & save
  2. Create a new GeoStory
  3. Add a media section to the story, and select the Map as content.

## Specifications

  - GeoNode version: 3.2.1
  - django_geonode_mapstore_client==3.2.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual
  - Platform: Ubuntu 20
  - Additional details:

**Comment by gannebamm** [comment]
I just tested it on our 3.3.x GeoNode instance which uses docker-compose as deployment option. It is slightly modified but does not change anything regarding mapstore and geostories. It was successful and I am unable to reproduce the issue.
The latest commit in that 3.3.x instance we use from the main project is : https://github.com/GeoNode/geonode/commit/34a9746310ec0852be78460916b2cdff6ddac5b6

**Comment by giohappy** [comment]
@jcaceres85 I'm not able to reproduce the issue on [stable.demo.geonode.or](https://stable.demo.geonode.org), which is 3.2.x.
Can you try an upgrade of you instance? A new (last) release for 3.2.x will be done soon, probably next week.

**Comment by giohappy** [comment]
That's weird @jcaceres85. How did you configure [these env vars](https://github.com/GeoNode/geonode-project/blob/3.3.x/.env.sample#L89-L93)?
