### ISSUE TITLE
Docker container letsencrypt setup misconfiguration

### ISSUE THREAD

**Issue by lucernae** [GeoNode/geonode#8376]
## Expected Behavior

I setup GeoNode in a VM using these docs: https://docs.geonode.org/en/master/install/advanced/core/index.html#docker

Although not mentioned, I know from docker-compose.yml file in the repo root that it includes letsencrypt containers taken from the old spcgeonode. I thought I could use this.

Expected behaviour was to toggle `LETSENCRYPT_MODE` in `.env` file to `production` and certbot will provision the certificate automatically.

## Actual Behavior

Certificate request failed due to misconfiguration.

## Steps to Reproduce the Problem

  1. Edit `.env` and change `LETSENCRYPT_MODE` to `production` or `staging` to hit letsencrypt
  2. Run a redeploy, like `docker-compose down && docker-compose up -d`
  3. View letsencrypt logs to see the error message `docker-compose logs -f --tail=100 letsencrypt`

## Specifications

  - GeoNode version: master branch
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode docker
  - Platform: Ubuntu
  - Additional details:

## Proposed fix

If I look out `docker-compose.yml` file in the `letsencrypt` service section, it mounts the certificates to `geonode-certificates`.
However, if I see https://github.com/GeoNode/geonode/blob/master/scripts/docker/letsencrypt/docker-entrypoint.sh the webroot is pointing to `spcgeonode-certificates`. We should change it to match, either choosing `geonode-certificates` or `spcgeonode-certificates`. I believe GeoNode team would prefer to use `geonode-certificates` at this point.

Additionally, the certbot package that alpine has is outdated. It is probably better to use certbot official image, which is `certbot/certbot` as the base image for letsencrypt container.

I can submit the PR later with this kind of fix if it is approved.

**Comment by afabiani** [comment]
@lpasquali see the comments from @lucernae I know you worked on geonode-project certs, not sure this is related to some issues you faced already. Thanks!

**Comment by lpasquali** [comment]
> @lpasquali see the comments from @lucernae I know you worked on geonode-project certs, not sure this is related to some issues you faced already. Thanks!

Hello @afabiani all my work concerning ssl is for geonode-project branch 3.2.x and yet to be merged, in my opinion, to live along well with existing installations I would endorse such work for 3.3.x 3.2.x and I also would recommend to backport this work on plain geonode (this is the PR: https://github.com/GeoNode/geonode-project/pull/268).
I am quite sure that the problem encountered by @lucernae is affecting only geonode docker composition, nevertheless I think https://github.com/GeoNode/geonode/pull/8397 is a good thing to be merged into master, but I am not sure how to test it , as we run our master instances through geonode-project.

**Comment by afabiani** [comment]
@lpasquali PR merged on geonode-project, can you please proceed with the backport?
