### ISSUE TITLE
Wrap default font preloading in template block

### ISSUE THREAD

**Issue by mradamcox** [GeoNode/geonode#8380]
**Is your feature request related to a problem? Please describe.**

Currently, three Lato fonts are preloaded in the geonode base template head ([here](https://github.com/GeoNode/geonode/blob/da297e687ab445c669978dac316d2b9ea45933ed/geonode/templates/base.html#L43)). If a geonode-project implementation does not use Lato, then these three fonts are loaded for no reason, and browser dev tools give a warning as well. It would be cleaner for these fonts to not be loaded at all if they are never going to be used.

**Describe the solution you'd like**

One way to fix this would be to wrap the 3 preload lines in a new template block, for example
```
{% block font_preload %}
<link rel="preload" as="font" href="{% static "geonode/fonts/lato_regular.ttf" %}" crossorigin="" />
<link rel="preload" as="font" href="{% static "geonode/fonts/lato_bold.ttf" %}" crossorigin="" />
<link rel="preload" as="font" href="{% static "geonode/fonts/lato_light.ttf" %}" crossorigin="" />
{% endblock %}
```
Then, downstream project templates could preload their own fonts by overriding this block, or just remove it altogether with
```
{% block font_preload %}{% endblock %}
```

**Describe alternatives you've considered**

Another way to fix this would be to move these 3 lines into the `{% block head %}` but that would require a much more careful downstream override, so I think the above suggestion is better.

**Additional Notes**

There is also a preload line use to load font awesome (see link above), but I don't see a great need to include that in a new block  because fa icons are ubiquitous throughout the app and unlikely to be unneeded.

**Comment by gannebamm** [comment]
@giohappy Will this still be an issue for v4?

**Comment by giohappy** [comment]
@gannebamm the new client overrides the base.html template completely, so we don't have the preload from the base.html. We should probably reduce the base.html in GeoNode core to only a list of empty blocks to clarify that the old template ore not meant to be used anymore.

Anyway I think adding a `font_preload` is ok. It doesn't hurt. Can you send a PR?
