### ISSUE TITLE
Error On Redirecting After Updating Document Metadata

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8399]
## Expected Behavior
After metadata update, the user should be redirected to the document detail page.

## Actual Behavior
The user is not redirected to the detail page. This error is returned by the API instead
![redirect](https://user-images.githubusercontent.com/20810749/142387987-e48e277a-3b42-4185-98b3-da7d85c64578.png)

## Steps to Reproduce the Problem

  1. Open document detail page eg https://master.demo.geonode.org/documents/329/metadata
  2. Go to edit Metadata and  update Metadata
  3. Check dev tools, the metadata redirect throws an error

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
AFAICS it is also broekn for maps. Please also check geoapps.
