### ISSUE TITLE
Drop GXP* classes from Map / MapLayer models and views

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8403]
## Context
After the improvements of https://github.com/GeoNode/geonode/pull/8395, it's possible now to completely remove hundreds of even thousands of lines  that are no more needed.

## To do
* [x] Simplify the big [`dataset_detail`](https://github.com/GeoNode/geonode/blob/master/geonode/layers/views.py#L337) view (currently with >300 lines), so it will only:
     * [x] Get the dataset.
     * [x] Get the access token.
     * [x] Populate the context only with `access_token` and `resource`.
     * [x] Handle the Event.
     * [x] Also look for whether there is more responsibilities that we should not drop.
* [x] Simplify the [`map_embed`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/views.py#L341) view:
     * [x] `config`, `default_map_config` and `map_obj.viewer_json` are not needed.
* [x] Update [client_lib_tags.py](https://github.com/GeoNode/geonode/blob/master/geonode/client/templatetags/client_lib_tags.py) so that the hookset don't need to be called any more. It can directly return the template path without calling all the convoluted context processing methods.
* [x] Remove the GXP* from the [`Map`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L44) and [`MapLayer`](https://github.com/GeoNode/geonode/blob/master/geonode/maps/models.py#L384) models. Pay attention to:
    * [x] Remove the models' inheritance from the GXP classes.
    * [x] Check in the methods for methods that depends on this classes, if they are used, where they are used and if they can be deleted.
    * [x] Check the legacy fields/columns, and remove the unused.
    * [x] In that part it will be needed to pay more attention to the path of the code and its relations.
* [x] Verify the path of the code, list and drop the unused methods/functions.
* [x] To finish, runs a [vulture](https://pypi.org/project/vulture/) analysis to verify whether there is uncalled code. 

## Questions
1. @giohappy The update to `client_lib_tags.py` should be done here in geonode or in mapstore?
2. @giohappy We are not using the MapLayer's model any more, it would not be better to delete this model instead of keeping an unused table on the database?

**Comment by giohappy** [comment]
>The update to client_lib_tags.py should be done here in geonode or in mapstore?

@italogsfernandes [GeoNodeClientLibraryTag](https://github.com/GeoNode/geonode/blob/1689eb2759c5e7b9c7904eeac2bc640b46e687d8/geonode/client/templatetags/client_lib_tags.py#L122) will disappear piece by piece. Focusing on the embed view, I expect to move the current GeoNode urlpatterns and the views to the mapstore client, and directly use the templates provided by mapstore. This means that the current GeoNode templates won't be used anymore, and consequently we can remove the related templatetags (`get_dataset_embed` and `get_map_embed`).
In the end we should be able to get rid of most part (if not everything) from `GeoNodeClientLibraryTag`

>We are not using the MapLayer's model any more, it would not be better to delete this model instead of keeping an unused table on the database?

??? We want to use the MapLayer model, why do you say it's not needed? The client will send the maplayer objects when a maps is created / updated, and we will use them to obtain the relations between maps and datasets. Currently we are not showing them in the client, but soon we will reintroduce this information inside the resource panels.
See the two pictures below from GN 3.3.x, showing the relations ("this layer is used in map xxx", "this map uses layer xxx, layer yyy, etc.").
The MapLayer will also store the relation between a dataset and the style assigned to it within a certain map (again, see second image below)

![image](https://user-images.githubusercontent.com/571129/143028781-9a029675-1737-4250-8ed5-077e76be0a9f.png)

![image](https://user-images.githubusercontent.com/571129/143029004-a5dcd4d6-9476-44b8-94b6-68031119c59c.png)

**Comment by giohappy** [comment]
As agrees @italogsfernandes  we should also:

- remove `center_x`, `center_y`, `projection` and `zoom` fields from the `Map` model. The `BaseResource.srid` and `bbox_polygon` / `ll_bboc_polygon` fields are enough
- remove `MapLayer.styles` field. For the moment it's only useful to MapStore, so it can be stored under `MapLayer.extra_params`

**Comment by giohappy** [comment]
@afabiani I had something [like this](https://stackoverflow.com/a/67500550) in mind, and I would like to try this approach to avoid breaking migrations. I don't like at all the idea of creating ad-hoc procedures / management commands for the upgrade to 4.0.
Can you please report here the break that was introduced with the drop of django-celery-beat?

@italogsfernandes I invite you to experiment the solution with GXP* classes.
