### ISSUE TITLE
GeoApps have empty uuid

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8429]
## Expected Behavior
GeoApps should have uuid value generated.

## Actual Behavior

GeoApps have empty uuid

## Steps to Reproduce the Problem

  1. Go to https://development.demo.geonode.org/api/v2/geoapps
  2. Check that uuid values are empty on geoApps

## Specifications

  - GeoNode version: 3.3.x, 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Please invetigate why the uuid is not populated.
