### ISSUE TITLE
Error on setting Datasets batch permissions in admin

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8445]
## Actual Behavior
This error is thrown on editing datasets batch permissions in the admin panel

![Screenshot from 2021-11-29 16-06-59](https://user-images.githubusercontent.com/20810749/143873503-62e67e69-38fe-46da-b87b-47dee83d8b91.png)

## Steps to Reproduce the Problem

  1. Go to Admin panel
  2. Go to Home > Dataset >Datasets, select multiple datasets and then chose `set permissions` action then click `Go`
  3. The error above will be raised

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
I would keep this on hold since we're going to make new developments for batch actions in the near future.

**Comment by giohappy** [comment]
@marthamareal the view was dropped in https://github.com/GeoNode/geonode/pull/8201.
I would remove the Django admin action for the moment and, in case, any residual template specific for that action.
