### ISSUE TITLE
Rating average available only in English #304

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8454]
## Expected Behavior

When changing language, ratings average should stay the same.

## Actual Behavior

Ratings average in any other language than English is always 0.
Example from a layer in 2 different languages:
- Italian:
  ![image](https://user-images.githubusercontent.com/717359/144251236-ac713e21-c5c4-4cbd-bd64-9180684f2cac.png)
- English:
  ![image](https://user-images.githubusercontent.com/717359/144251411-19bc01fa-0e50-42fa-9287-b9021e4225f9.png)
)

**Comment by etj** [comment]
@marthamareal @giohappy 
Fix implemented for documents only.

It should be applied also to
- layers
- maps
- apps

**Comment by etj** [comment]
Yet to be fixed:
- Layers: https://github.com/GeoNode/geonode/blob/a13b6e15de5d728f6d745f57d90c4ebed63e3702/geonode/layers/templates/layers/layer_detail.html#L250
- Maps: https://github.com/GeoNode/geonode/blob/a13b6e15de5d728f6d745f57d90c4ebed63e3702/geonode/maps/templates/maps/map_detail.html#L93
- GeoApps: https://github.com/GeoNode/geonode/blob/a13b6e15de5d728f6d745f57d90c4ebed63e3702/geonode/geoapps/templates/apps/app_detail.html#L78
