### ISSUE TITLE
Direct download timeout with big files

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8458]
## Expected Behavior

When requesting a download, the download procedure should start as soon as possible, in order to avoid timeout errors and to improve user experience.

## Actual Behavior

When there are large files to export, the preparation stage may last really long, leading to timeout errors in the client-server communications.

## Specifications

  - GeoNode version: *

## Additional details

The direct download logic at the moment takes long because there are multiple time consuming steps involved:
- copy the data into a different folder
- zip the data
https://github.com/GeoNode/geonode/blob/aa4b805a23cf5f9b5de2882374d3ccfdd61a9d60/geonode/proxy/views.py#L286-L327

**Comment by etj** [comment]
There are libraries specifically targeted at this kind of issues, e.g. https://pypi.org/project/django-sendfile2

**Comment by simboss** [comment]
@italogsfernandes please, provide feedback as you progress on this.
An ETA would not be bad to have.

**Comment by italogsfernandes** [comment]
@simboss I think, about 2 days.
