### ISSUE TITLE
WCS getCoverage links have wrong params

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#8461]
Links to WCS `getCoverage` requests are wrong.

Check the first comment for more info.

## Specifications

  - GeoNode version: *

## Additional details:

This on master:
https://github.com/GeoNode/geonode/blob/aca637c71bb41b8cafba4c1368479086eb5e6377/geonode/geoserver/ows.py#L50-L62

**Comment by etj** [comment]
As reported by @aaime in another comment:

There is an issue... but before getting to it, please note the request GeoNode is making is bonkers:

```
https://TESTSERVER.geosolutionsgroup.com/geoserver/wcs?service=WCS&
request=GetCoverage&
coverageid=hazard__gar17eqpga1500&
format=image%2Ftiff&
version=2.0.1&
srs=EPSG%3A4326&                         <-----------------
bbox=-180.0,-90.0,180.0,90.0&           <-----------------
access_token=__hidden__&
```

``bbox``?  ``srs?`` :-D There are no such things in WCS 2.0.
If there actually was a desire to get a portion of the image in that box, and a width of 100, the request should have been:

```
https://TESTSERVER.geosolutionsgroup.com/geoserver/wcs?service=WCS&
request=GetCoverage&
coverageid=hazard__gar17eqpga1500&
format=image%2Ftiff&
version=2.0.1&
outputCrs=EPSG%3A4326&                                           <-- How target CRS is specified
&subset=Long(-180.0,180)&subset=Lat(-90,%2090)      <--- How a bbox is specified
access_token=__hidden__&
&scaleextent=i(0,100),j(0,50)                                           <-- How a target size is specified
```

@simboss showed me a GeoNode GUI allowing to download the full layer, so I'm guessing you want all of it, in its native CRS... in that case, please remove those extra keys (``bbox``, ``srs``, ``width``)... they are ignored anyways.

The reason why we are getting the issue is that the "bbox", when not specified, defaults to the native one of the coverage.
The native one crosses around the datelines on both ends, goes from -180.0360072 to 180.0360072... which ends up triggering the WCS 2.0 "dateline crossing" behavior (by standard), making it try to read also two tiny slivers of data just beyond the dateline. They are too small to read actually anything, which results in the exception (read width is zero).

I think it can be fixed in a few hours, I'm just going ahead with the fix.

**Comment by afabiani** [comment]
@etj @simboss so far I have been modifying this method as follows:

### Default "GetCoverage" Metadata Links
The default links generated by GeoNode will allow us to download the whole raster into the native SRS.
GeoNode currently provides the following two "outputFormats":

 - "x-gzip"; ASCII Grid output format GZIP compressed
 - "geotiff"; GeoTIFF which will be compressed and tiled by passing to the WCS the default query params compression='DEFLATE' and tile_size=512

The `GetCoverage` urls will be something like the ones here below; notice that **no** `outputCrs` or `subsetting` will be generated by default.

```
http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__relief_san_andres0&format=application%2Fx-gzip&version=2.0.1

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__relief_san_andres0&format=image%2Ftiff&version=2.0.1&compression=DEFLATE&tileWidth=512&tileHeight=512

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__gebco_2020_n54_0659179519862_s51_64453104883433_w0_5559082031249998_e4_409911975264549&format=application%2Fx-gzip&version=2.0.1

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__gebco_2020_n54_0659179519862_s51_64453104883433_w0_5559082031249998_e4_409911975264549&format=image%2Ftiff&version=2.0.1&compression=DEFLATE&tileWidth=512&tileHeight=512
```

The utility method has been, however, generalized in order to be able to recognize the `axisLabels` automatically from the `DescribeCoverage` request. Subsetting can be generated by providing a _non-null_ `bbox` and `sird` params couple.
In the latter case, the links will change as shown here below:

```
http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__relief_san_andres0&format=application%2Fx-gzip&version=2.0.1&outputCrs=EPSG%3A4326&subset=Long(-84.0,-78.0)&subset=Lat(11.0,15.0)

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__relief_san_andres0&format=image%2Ftiff&version=2.0.1&compression=DEFLATE&tileWidth=512&tileHeight=512&outputCrs=EPSG%3A4326&subset=Long(-84.0,-78.0)&subset=Lat(11.0,15.0)

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__gebco_2020_n54_0659179519862_s51_64453104883433_w0_5559082031249998_e4_409911975264549&format=application%2Fx-gzip&version=2.0.1&outputCrs=EPSG%3A404000&subset=x(-0.5,924.5)&subset=y(-0.5,580.5)

http://localhost:8080/geoserver/ows?service=WCS&request=GetCoverage&coverageid=geonode__gebco_2020_n54_0659179519862_s51_64453104883433_w0_5559082031249998_e4_409911975264549&format=image%2Ftiff&version=2.0.1&compression=DEFLATE&tileWidth=512&tileHeight=512&outputCrs=EPSG%3A404000&subset=x(-0.5,924.5)&subset=y(-0.5,580.5)
```

**Comment by afabiani** [comment]
### Update
- ASCII Grid outputFormat has been removed

**Comment by simboss** [comment]
@afabiani iI would go ahead with two separate PR these two things do not really look like the same thing.
I would go ahead and clean up the WCS GetCoverage link on all branches so that we have simple GetCoverage calls working once for all.
Notice that this is something that we need quickly.

I would separate the other enhancements in a separate PR.

**Comment by afabiani** [comment]
@simboss the cleanup PR has been approved and merged on master: https://github.com/GeoNode/geonode/pull/8470

Backports to 3.3.x and 3.2.x are ongoing.

**Comment by afabiani** [comment]
@simboss I confirm the links have been generated correctly on the demo instances now, moreover I tested the already existing management command and it is able to correctly refresh the old links, e.g.:

`./manage.sh set_all_layers_metadata -p -d -f <layer_name>`

**Comment by afabiani** [comment]
So far I have been able to refresh the `stable.demo` metadata links by running the following commands:

```
docker-compose exec django bash
./manage.sh set_all_layers_metadata -p -d -f <layer_name>
```

By removing the `-f` option you can safely run the command over the whole datasets.
