### ISSUE TITLE
Option to link GS workspaces to GN categories

### ISSUE THREAD

**Issue by giovand** [GeoNode/geonode#848]
This is a proposed feature. I discussed it on the Dev list and ..Paolo seemed interested in hacking some code to implement it ;-)

Here's the original thread for reference: https://groups.google.com/a/opengeo.org/forum/?fromgroups=#!topic/geonode-dev/ZEWdqAEB8m4

And this is what I proposed:

---

Within Geoserver I usually organize layers with workspaces. Since workspaces resemble what in Geonode are categories, I was wondering if it made sense extending the upload/import functions to allow for choosing a specific workspace (and matching category). That way each layer's URL would also semantically look better than just using "geonode" as the namespace before each layer name. Here's an example:

Current: http://maps.opensandiego.org/layers/geonode:zip_codes

Proposed: http://maps.opensandiego.org/layers/boundaries:zip_codes

I understand that this is also very specific to using Geoserver as the mapping engine, while workspace namespaces are not normally found in other map serving software or mandated by any OGC standard. Still, would be nice to have the geonodeinstance/layers/category/layername structure.

---

There are some limitations to have it as default: https://groups.google.com/a/opengeo.org/d/msg/geonode-dev/ZEWdqAEB8m4/-30yy_wvUVIJ

So, I would just propose this as an optional switch when importing or uploading new layers.

C

**Comment by jj0hns0n** [comment]
Adding to 2.5 to be handled with Portals.

**Comment by jj0hns0n** [comment]
My portals branch is still outstanding. If anyone is interested in working on this, let me know. Moving to 2.7 for now.
