### ISSUE TITLE
CORS activation in GeoServer4GeoNode

### ISSUE THREAD

**Issue by satigebah** [GeoNode/geonode#8483]
Hi everyone,
I have some concerns. I installed geonode with docker. I would like to activate the CORS of the geoserver but I cannot.
I entered the geoserver4geonode container with docker exec -it geoserver4geonode bash
And I added in the webapps / geoserver / WEB-INF / web.xml file:

<filter>
  <filter-name> CorsFilter </filter-name>
  <filter-class> org.apache.catalina.filters.CorsFilter </filter-class>
  <init-param>
    <param-name> cors.allowed.origins </param-name>
    <param-value> https://www.apache.org </param-value>
  </init-param>
  <init-param>
    <param-name> cors.allowed.methods </param-name>
    <param-value> GET, POST, HEAD, OPTIONS, PUT </param-value>
  </init-param>
  <init-param>
    <param-name> cors.allowed.headers </param-name>
    <param-value> Content-Type, X-Requested-With, accept, Origin, Access-Control-Request-Method, Access-Control-Request-Headers </param-value>
  </init-param>
  <init-param>
    <param-name> cors.exposed.headers </param-name>
    <param-value> Access-Control-Allow-Origin, Access-Control-Allow-Credentials </param-value>
  </init-param>
  <init-param>
    <param-name> cors.support.credentials </param-name>
    <param-value> true </param-value>
  </init-param>
  <init-param>
    <param-name> cors.preflight.maxage </param-name>
    <param-value> 10 </param-value>
  </init-param>
</filter>
<filter-mapping>
  <filter-name> CorsFilter </filter-name>
  <url-pattern> / * </url-pattern>
</filter-mapping>

Then I restarted the geoserver4geonode but I have the same problem with the CORS

**Comment by afabiani** [comment]
@satigebah in order to enable the CORS on GeoServer you will need to tweak this option on the `GEOSERVER_JAVA_OPTS` variable of the `.env` file:

`-DGEOSERVER_CSRF_DISABLED=true`
