### ISSUE TITLE
GNIP 90 -  Add Pluggable Service Types

### ISSUE THREAD

**Issue by minardimarcello** [GeoNode/geonode#8496]
# GNIP 90 - Add Pluggable Service Types

## Overview

In the current state of GEONODE, we can't implement Custom Service Type. That's caused by the Handler class implementation, currently inside Geonode.
This prevents the Geonode project to create its harvester and management page.

### Proposed By

@minardimarcello

### Assigned to Release

This proposal is for GeoNode 3.3.x

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

We need to develop our custom Service Types, OGC or non-OCG complaints.

## Proposal

The first thing to do is to create a hook accessible from inherited projects:
the usual is to create environment variables that contain the module with configurations; since there's no default, the implementation will admit None values or empty lists as far as we have no custom service type. Otherwise, we can create a group of service types in each module we desire, as long as you write in this environment variable the list of each module that contains the configuration.
For the environment variable, we decided to use SERVICES_TYPE_MODULES, meanwhile, the linked modules will contain the variable "services_type" written like this:

`
services_type = {
    "<key_of_service_type>": {
        "OWS": True/False,
        "handler": "<path.to.Handler>",
        "label": "<label to show in remote service page>",
        "management_view": "<path.to.view>"
    }
}
`

the key_of_service_type is just an identifier to assign at the service type.
OWS is True if the service type is an OGC Service Compliant.
The handler key must contain the path to the class that will provide all methods to manage the service type
The label is what is shown in the service form when adding a new service.
The management_view, if exists, must contain the path to the method where the management page is opened.

After the hook we need to change how the Handlers are built:
they inherit from a base.ServiceHandler has some unimplemented methods, but we need to have a base handler for the OCG service type to avoid the repetition of code. Until now the base handler is WmsServiceHandler and its child GeoNodeServiceHandler redefine the constructor and the harvest_resource method (and adds some internal methods to elaborate the enrichment of data in the layer). 
We can create an OCGServiceHandler within which we can create a uniformed process of enrichment and so that we can implement the enrichment method in the child without repeating the code of all harvest_resource methods.
Unfortunately, we can't create a standard class for non-OCG compliant service types.

## Feedback

* None

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

## Links

* [Pull Request](https://github.com/GeoNode/geonode/pull/8453)
* [Linked Issue](https://github.com/GeoNode/geonode/issues/8422)

**Comment by gannebamm** [comment]
If I understand this correctly the pluggable service type could help in registering foreign services, like the new OGC APIs and there like?

**Comment by giohappy** [comment]
The idea @gannebamm is to let third party modules add their own remote services. The module will be in charge of implementing the concrete job for the remote resource retrieval and the creation of GeoNode resources. So, in a certain way, yes, you can create your could create a module for the OGC APIs.

Notice that in master we have a much more advanced engine. The harvesting module (which is also begind remote services) is more versatile and offers advanced features for the scheduling of ingestions, etc.

**Comment by gannebamm** [comment]
Is this still worked on?
