### ISSUE TITLE
GeoApps types missing from advanced search filters

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#8499]
## Expected Behavior
As a user I expect also the `GeoApp` to be listed into the `Advanced Search` type filter.

## Actual Behavior
Only the default `ResourceBase` are listed.

## Steps to Reproduce the Problem

  1. Go to the `Advanced Search` page (e.g.: https://development.demo.geonode.org/search/)
  2. Verify the `GeoApp` types are not present among the type filters

![image](https://user-images.githubusercontent.com/1278021/146227331-39a744d2-948e-4d42-99f2-b31ca6326995.png)

## Specifications

  - GeoNode version: 3.3.x, 3.2.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by minardimarcello** [comment]
As I can see from the code the GeoApp are not listed in that filter.
I see only:
* Raster Layer
* Vector Layer
* Vector Temporal Serie
* Remote Layer
* WMS Cascade Layer
* Map
* Document

I think we can add the part in  facet_type == "geoapps" ti the facet_type=="all" filter si we can show the GeoApps even in the advanced research.

**Comment by afabiani** [comment]
@minardimarcello not exactly. `geoapps` are a special type of `ResourceType` which may have pluggable implementations. You will need to dynamically look for the available `sub_types`. Something similar to what this method does [here](https://github.com/GeoNode/geonode/blob/3.3.x/geonode/security/utils.py#L896)

**Comment by minardimarcello** [comment]
@afabiani if I understand correctly  I can take that code and add a filter this
```python
 _model = filter(lambda _model: issubclass(_model, GeoApp), apps.get_model(label, app.default_model).objects.all())
```
and add the geoapps this way:
```python
geoapps = get_visible_resources(
                    _model,
                    request.user if request else None,
                    admin_approval_required=settings.ADMIN_MODERATE_UPLOADS,
                    unpublished_not_visible=settings.RESOURCE_PUBLISHING,
                    private_groups_not_visibile=settings.GROUP_PRIVATE_RESOURCES)```
without changing any other line

**Comment by afabiani** [comment]
go ahead @minardimarcello let's see if that works... don't forget to add tests to the PR

**Comment by mattiagiupponi** [comment]
closed in favor of https://github.com/GeoNode/geonode/pull/8684
