### ISSUE TITLE
Geonode -> Django 2.2 x GDAL 3

### ISSUE THREAD

**Issue by cmotadev** [GeoNode/geonode#8502]
Hi @afabiani and other colleagues

We are developing a plugin for GeoNode, running on Docker, that uses geonode-project and we are experiencing some issues. We have a django model that uses a GeometryField and the model saves geometry with flipped coordinates. 

I checked that Geonode uses [Django 2.2.x](https://docs.djangoproject.com/en/2.2/ref/contrib/gis/install/geolibs/), which GDAL requirements are up to 2.3.x, and in the dockerfile it brings GDAL 3. I think it's a Django behavior than Geonode itself, but I think that it's crucial for setting the geonode requierements - [GDAL 3 changed the default behavior of coordinate transformation](https://github.com/OSGeo/gdal/issues/1546)

There is a ticket into the [Django Project](https://code.djangoproject.com/ticket/31611) that issues this problem.

My suggestion is to put GDAL 2.X as default, or adopt Django 3.1.x as default, which one is easier :)

Thanks for appreciate.

## Expected Behavior
GeoDjango saves the geometry as is

## Actual Behavior
GeoDjango is flipping the geometry's coordinates

## Steps to Reproduce the Problem

  1. Create a Django geonode project
  2. Create a spatial model using geodjango
  3. Fill the model props and save it to db.

## Specifications

  - GeoNode version: 3.2.1
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Platform: Linux
  - Additional details:

**Comment by afabiani** [comment]
@cmotadev currently only `master` is using Django==3.2.* the older branches are still using Django 2.*

As far as I remember we used this checks in order to deal with the GDAL 3 coordinate flipping issue

https://github.com/GeoNode/geonode/blob/3.2.x/geonode/utils.py#L398

Maybe this one could work for you too?

**Comment by cmotadev** [comment]
@afabiani I checked your suggestion and doesn't work for me, but your implementation gived me an idea: The main problem is because the GeoDjango implementation doesn't use pyGDAL. The bindings are done [directly on the library](https://github.com/django/django/blob/stable/2.2.x/django/contrib/gis/gdal/srs.py#L37).

I solved my problem subclassing the GeometryField to flip coordinates before saving into DB and after retrieve on it.

from django.contrib.gis.db.models import MultiPolygonField as BaseMultiPolygonField
from django.contrib.gis.geos import GEOSGeometry
from osgeo.gdal import __version__ as version 
from shapely.wkb import loads
from shapely.ops import transform


class MultiPolygonField(BaseMultiPolygonField):
    gdal_version = int(version.split(".")[0])

    def _fix_gdal_axis_error(self, geom):
        if self.gdal_version >= 3:
            _g = transform(lambda x, y: (y, x), loads(bytes(geom.wkb)))
            wkb = _g.wkb_hex
            srid = geom.srs.srid
        
            geom = GEOSGeometry(wkb, srid=srid)
        
        return geom
    
    def to_python(self, value):
        _value = super().to_python(value)
        return self._fix_gdal_axis_error(_value)

    def from_db_value(self, value, expression, connection):
        if value is None:
            return value

        return self._fix_gdal_axis_error(value)
```
