### ISSUE TITLE
Implement maps / dataset relationships endpoints

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8504]
### datasets/{pk}/maps
Retuns  the maps where the dataset is used (through a maplayer).
The returned objects will contain only compact informations of the maps:

```
{
  id
  title
  detail_url
}
```

### datasets/{pk}/maplayers
Retuns all the maplayers where the dataset is referenced. 
The complete model for the maplayer will be returned inside the response.

### maps/{pk}/datasets
Returns the list of datasets referenced through the map's maplayers
The returned objects will contain only compact informations of the datasets:

```
{
  id
  title
  detail_url
}
```
## Actual Behavior
N/A

## Steps to Reproduce the Problem

  1.N/A

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@giohappy `maps/{pk}/datasets` seems similar to the existing `maps/{pk}/local_datasets` implemented [here](https://github.com/GeoNode/geonode/blob/master/geonode/maps/api/views.py#L107) The difference is the name and fields returned.

**Comment by marthamareal** [comment]
@giohappy 
Shouldn't response have `pk` instead of `id`?

Also currently map layers don't have detail_url and title,
Should we use 
```
{
  pk
  name
}
```

**Comment by giohappy** [comment]
as agreed @marthamareal please rename `local_datasets` to `datasets` and, to make this possible, also fix https://github.com/GeoNode/geonode/issues/8509 inside this PR.
