### ISSUE TITLE
Improve GeoLimits layer tiles loading

### ISSUE THREAD

**Issue by allyoucanmap** [GeoNode/geonode#8508]
## Expected Behavior

Possible improvements:

- [x] use 512 x 512 px tile size
- [x] set the params to TILED true to the layer request to cache the tile
- [x] initialize the map only when the permission modal is open

## Actual Behavior

geolimits layer are requested even if the modal is not open

## Steps to Reproduce the Problem

  1. login as admin
  2. go to layer list  `/layers/`
  3. select a layer and open layer detail

## Specifications

  - GeoNode version:  3.3.x, 3.2.x (we should also verify on master with new plugin)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by simboss** [comment]
This is something I noticed on some heavy layers; when accessing their page there was a few seconds lag and I notice a burst of 256x256 with no TILED= TRUE parameter were sent before MapStore could load.

It turned out this was the geolimits page eagerly loading these tiles (quite unnecessarily) but also in a way which was not optimized at all.

**Comment by simboss** [comment]
@allyoucanmap can we prioritize this?
I would want to have it before next release 3.3.1.

**Comment by allyoucanmap** [comment]
@simboss @giohappy 
Here PR for branch 3.3.x https://github.com/GeoNode/geonode/pull/8596

**Comment by simboss** [comment]
@allyoucanmap that is great, thx...

**Comment by giohappy** [comment]
@allyoucanmap merged

**Comment by allyoucanmap** [comment]
@simboss @giohappy 
Here backport for 3.2.x
https://github.com/GeoNode/geonode/pull/8606

Master does not need update because it using a different component and structure
