### ISSUE TITLE
Dropbox endpoint to download geoserver_data folder and geoserver moved

### ISSUE THREAD

**Issue by luigilangella** [GeoNode/geonode#8510]
## Expected Behavior
sudo wget --no-check-certificate "https://www.dropbox.com/s/cd20is9ddjz7ti5/data-2.18.3.zip?dl=1" -O data-2.18.3.zip

## Actual Behavior
--2021-12-17 16:20:29--  https://www.dropbox.com/s/cd20is9ddjz7ti5/data-2.18.3.zip?dl=1
Resolving www.dropbox.com (www.dropbox.com)... 162.125.64.18, 2620:100:6020:18::a27d:4012
Connecting to www.dropbox.com (www.dropbox.com)|162.125.64.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/cd20is9ddjz7ti5/data-2.18.3.zip [following]
--2021-12-17 16:20:35--  https://www.dropbox.com/s/dl/cd20is9ddjz7ti5/data-2.18.3.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-12-17 16:20:35 ERROR 404: Not Found.

## Steps to Reproduce the Problem

  1. 
  2.
  3.

## Specifications

  - GeoNode version: 3.2.x
  - Installation method (manual):
  - Platform: Ubuntu Server 20.04
  - Additional details: this links are essentials to install geonode

**Comment by pi1Mg** [comment]
Not tested, I found a [mirror link](https://github.com/t-book/geonode-geoserver-mirror/releases), maybe it can help.

**Comment by giohappy** [comment]
@luigilangella the repository has been moved. You can get the new link from [here](https://github.com/GeoNode/geonode/blob/3.2.x/dev_config.yml#L3)

**Comment by luigilangella** [comment]
Grazie Giovanni 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
