### ISSUE TITLE
Missing Link Geoserver and Geoserver Data Dir on Dropbox

### ISSUE THREAD

**Issue by adilutfihanafi** [GeoNode/geonode#8542]
## Expected Behavior
Geoserver Data Dir package and Geoserver package can be download with wget

## Actual Behavior

Resolving www.dropbox.com (www.dropbox.com)... 162.125.81.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.81.18|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/dl/cd20is9ddjz7ti5/data-2.18.3.zip [following]
--2021-12-23 04:48:52--  https://www.dropbox.com/s/dl/cd20is9ddjz7ti5/data-2.18.3.zip
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-12-23 04:48:53 ERROR 404: Not Found.

## Steps to Reproduce the Problem

  1. sudo wget --no-check-certificate "https://www.dropbox.com/s/cd20is9ddjz7ti5/data-2.18.3.zip?dl=1" -O data-2.18.3.zip
  2. sudo wget --no-check-certificate "https://www.dropbox.com/s/cmrdzde1oq67pre/geoserver-2.18.3.war?dl=0" -O geoserver-2.18.3.war
  3.

## Specifications

  - GeoNode version: 3.2
  - Installation method (manual):
  - Platform:ubuntu server 20.04
  - Additional details:

**Comment by afabiani** [comment]
Please, update the links with the one specified [here](https://github.com/GeoNode/geonode/blob/master/dev_config.yml)
