### ISSUE TITLE
raster uploads require sending the same file twice

### ISSUE THREAD

**Issue by ricardogsilva** [GeoNode/geonode#8551]
I'm working on the [QGIS GeoNode plugin](https://kartoza.github.io/qgis_geonode/), specifically on uploading of raster files. I've found that in order to be able to successfully upload GeoTiff files to GeoNode one needs to send in the file in duplicate.

GeoNode expects there to be both a `base_file` and a `tif_file` file fields being sent with the upload's `multipart/form-data` content-type. This means the actual GeoTiff file is being sent over the wire twice, which seems rather wasteful.

**Comment by giohappy** [comment]
@afabiani can you take a look at what @ricardogsilva is reporting?

**Comment by afabiani** [comment]
PR available here https://github.com/GeoNode/geonode/pull/8586/

**Comment by giohappy** [comment]
@afabiani what about the web upload form? The commit fixes the backend but, given the described behaviour, I suppose that the web form is still sending the files twice, isn'it?

**Comment by afabiani** [comment]
@giohappy the upload form `cleaned` method uses that helpers to retrieve from the `FILES` the valid `extensions`.

The modified `tests` show that the upload form works now even without passing that parameter explicitly.
