### ISSUE TITLE
Dataset Clone does not seem to be setting the GeoFence rules correctly

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#8565]
## Expected Behavior
As a User, when cloning a dataset I'd expect the GeoFence rules to be set also.

## Actual Behavior
It looks like the GeoFence security rules are not set for the cloned resource.

## Steps to Reproduce the Problem

  1. Login as a User (better a non-admin one)
  2. Check a dataset with edit permissions
  3. Clone it and check that it won't be visible
  4. Login as admin into the GeoServer admin dashboard: the layer exists but the GeoFence rules for the latter aren't set.

## Specifications

  - GeoNode version: 4
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@afabiani IMHO a clone should have the default rules, not the ones from the cloned resouirce.
We're also considering to remove the option to set the permissions at upload time, so the expected behaviour should be that any new resource (either created or cloned) should have the default permissions.

**Comment by gannebamm** [comment]
> We're also considering to remove the option to set the permissions at upload time
I would like the mentioned behaviour. Better to have them uploaded with defaults (private or public) and later set fine-grained permissions if needed.

**Comment by giohappy** [comment]
@gannebamm we're on it on the master branch. The new upload page will be simplified and the permission settings. will be removed

**Comment by afabiani** [comment]
> @afabiani IMHO a clone should have the default rules, not the ones from the cloned resouirce. We're also considering to remove the option to set the permissions at upload time, so the expected behaviour should be that any new resource (either created or cloned) should have the default permissions.

@giohappy by using the default rules you could either end up having a public copy of a private layer or having a copy no more editable by the original owner.

**Comment by gannebamm** [comment]
Oh. You're right @afabiani. A private dataset will be public - at least for a short while. This is not good.

**Comment by giohappy** [comment]
IMHO we should move to a private by default configuration, as requested by many users and customers. This is what happens on any other share platform....

**Comment by afabiani** [comment]
@giohappy @gannebamm I will create a new issue covering (and describing) the behavior above, i.e. set the cloned layer to private by default.
