### ISSUE TITLE
adding tools to the viewer is too difficult after the upgrade to GeoExplorer

### ISSUE THREAD

**Issue by bartvde** [GeoNode/geonode#858]
This came up with @capooti 

Previously people could simply use config.tools but this does not work anymore. They will need to add their tool to the viewerTools array and set it to checked to get it to show up. Something like this works but we should either document this properly or we should make this easier again:

```
bart-van-den-eijndens-macbook-pro:geonode_master_17042013 bartvde$ git diff ./geonode/templates/geonode/geo_header.html
diff --git a/geonode/templates/geonode/geo_header.html b/geonode/templates/geonode/geo_header.html
index aec9dee..05f6b64 100644
--- a/geonode/templates/geonode/geo_header.html
+++ b/geonode/templates/geonode/geo_header.html
@@ -21,6 +21,10 @@ GeoExplorer.Viewer.prototype.loadConfig = function(config) {
             ptype: "gxp_getfeedfeatureinfo",
             checked: true
         });
+        config.viewerTools.splice(5, 0, {
+            ptype: "gxp_styler",
+            checked: true
+        });
     GeoExplorer.Viewer.superclass.loadConfig.call(this, config);
 };
```

**Comment by jj0hns0n** [comment]
This is now 2 years old :) I wonder how things look now. @bartvde can you take a quick look and advise?

**Comment by bartvde** [comment]
nothing has changed in this regard, it's still kind of hacky to do this, but it works

**Comment by jj0hns0n** [comment]
Is this documented somewhere? If we at least have documentation about the
hack then we can point people to it.

**Comment by bartvde** [comment]
I don't think it's documented outside of the ticket, where should the docs go?

**Comment by jj0hns0n** [comment]
If you can point to them and maybe prepare a quick google doc or something,
I can make sure it gets into the docs when we sprint on them in a few weeks.

**Comment by capooti** [comment]
I can help as well here, during the sprint I can take care of it.

**Comment by bartvde** [comment]
thanks @capooti !
