### ISSUE TITLE
Unexpected SRS step required when uploading a shapefile

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8625]
The attached shapefile has been used extensively to test GeoNode, and it never required an SRS step during the upload. If you upload this file on GN 3.3.x (development demo) it completes without any user interaction.
Master demo is requesting the SRS step instead, so something might be changed / brolen in the upload flow.

[Reg01012019_g.zip](https://github.com/GeoNode/geonode/files/7883817/Reg01012019_g.zip)

**Comment by italogsfernandes** [comment]
It's working now: (I didn't change anything)

![image](https://user-images.githubusercontent.com/12943132/149935200-c810f31d-e6ea-42f2-bdf0-f97fba22c4b6.png)

We had new merges on the master branch, I think it triggered an update in the master demo.

**Comment by allyoucanmap** [comment]
@giohappy @italogsfernandes could be a difference with a sync vs async geonode instance?

**Comment by giohappy** [comment]
> @giohappy @italogsfernandes could be a difference with a sync vs async geonode instance?

I don't think @allyoucanmap since I'm using a sync env locally and it works. However it's working fine for me too now, so I'll close this.
