### ISSUE TITLE
[Upload Improvements] Avoid dumping local files to disk on save_step if not strictly needed

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#8636]
Currently the `upload` view always assumes the files have been uploaded thorugh the `LayerUploadForm` and therefore it dumps the files locally ([here](https://github.com/GeoNode/geonode/blob/master/geonode/upload/views.py#L156)).

We need to distinguish whenever the files are local or not and avoid dumping them again on the temporary folder.

**WARNING**: On an `ASYNC` environment, whenever the `django` and `celery` machines are seperated, we need to be sure both are able to access the local files. That is not trivial. My proposal is to always leverage on the `StorageManager` instead of relying on a local `tempdir` by improving it and allowing to recognize whenever the files exists or not locally. There must be an option allowing us to set a `shared` space on the `StorageManager` and manage it accordingly, which means also make sure to clean up temporary streams when those are not used anymore.

**Comment by giohappy** [comment]
closed in favour of https://github.com/GeoNode/geonode/issues/8667
