### ISSUE TITLE
[Upload Improvements] Always send a zip stream to the Importer

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#8638]
Currently everytime we need to add some files to an `Importer` session, we are relaying on the `upload_task` client library method, which is something like this:

```python
    def upload_task(self, files, use_url=False, initial_opts=None):
        """create a task with the provided files
        files - collection of files to upload or zip file
        use_url - if true, post a URL to the uploader
        """
        # @todo getting the task response updates the session tasks, but
        # neglects to retreive the overall session status field
        fname = os.path.basename(files[0])
        _, ext = os.path.splitext(fname)

        def addopts(base):
            if initial_opts:
                # pass options in as value:key parameters, this allows multiple
                # options per key
                base = base + '&' + '&'.join(['option=%s:%s' % (v, k) for k, v in initial_opts.items()])
            return base
        if use_url:
            if ext == '.zip':
                upload_url = files[0]
            else:
                upload_url = os.path.dirname(files[0])
            url = self._url("imports/%s/tasks?expand=3" % self.id)
            upload_url = "file://%s" % os.path.abspath(upload_url)
            resp = self._client().post_upload_url(url, upload_url)
        elif ext == '.zip':
            url = self._url("imports/%s/tasks/%s?expand=3" % (self.id, fname))
            resp = self._client().put_zip(addopts(url), files[0])
        else:
            url = self._url("imports/%s/tasks?expand=3" % self.id)
            resp = self._client().post_multipart(addopts(url), files)
 ...
```

From that code snippet we can clearly see that:

1. The method always looks for files present on the local storage, and currently this is mandatory because the GeoServer Importer is not able to read streams from different sources.
2. GeoNode never uses the option `use_url=True`, meaning that it always assumes the GeoServer Importer must be able to access the files on a shared file-system

The proposal is to change this by:
1. Zip the spatial files to send to the Importer on a local path, possibly managed by the `StorageManager`
2. Stream the zip file to the `Importer` so that we don't need a shared file-system between GeoNode and GeoServer anymore
3. Make sure the local zipped files are cleared once finished

**Comment by mattiagiupponi** [comment]
Import flow has been changed via https://github.com/GeoNode/geonode/issues/10474
