### ISSUE TITLE
line chart with time rendered wrong

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#8654]
## Expected Behavior
If I add a time enabled linechart the datapoints should be rendered by time.

## Actual Behavior
The lines are not rendered properly and by date. Example:
![grafik](https://user-images.githubusercontent.com/6172324/150346781-7312c4a4-cd5b-4234-a562-00f8e63db96a.png)

used dataset: https://stable.demo.geonode.org/layers/geonode_master_data:geonode:winterCrangonSurvey_jWiiqM4
As live map on stable :  https://stable.demo.geonode.org/maps/4248/view#/
As live map on master : https://master.demo.geonode.org/catalogue/#/map/697

## Steps to Reproduce the Problem

  1. Upload time enabled dataset
  2. Create linechart with time as x-axis

## Specifications

  - GeoNode version: 3.3.x + master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by pvgenuchten** [comment]
nice functionality there Florian, seems the times returned by the WPS are not in order (and geonode doesn't sort it)
![image](https://user-images.githubusercontent.com/299829/150440134-70eed601-bb7d-463c-a20c-953d1d54e30e.png)

**Comment by giohappy** [comment]
That's odd @gannebamm. I will ask the MapStore team to investigate this case....

**Comment by giohappy** [comment]
I'm going to move this issue to the mapstore client repo.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #746](https://github.com/GeoNode/geonode-mapstore-client/issues/746) via [**ZenHub**](https://www.zenhub.com/)
