### ISSUE TITLE
Implement the upload of files from remote locations

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8667]
The current implementation of the `upload` view, and in particular the [save_step_view](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/views.py#L133), only supports files uploaded as multipart data through `LayerUploadForm`.

We want to extend it to accept paths to a remote location, from which the file can be read and uploaded to Geoserver.

The high level requirements are:

 - for the moment we only implement support to filesystem paths (that of course are visible to GeoNode), but we want to make it generic to support additional implementations for other types of remote storages (S3, etc.). [smart_open](https://github.com/RaRe-Technologies/smart_open) could be a nice solution to be considered.
 - we don't want to make local copies of the remote file, including temporary copies.
 - files will be [uploaded directly through the gs_uploader instance](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/upload.py#L358) . I guess that the file interface should make it mostly transparent, without any modification.

GeoNode doesn't rely much on local copies of uploaded files. In 3.3.x, if available, a direct link for their download is provided, but it's not a prerequisite for the functionality of GeoNode. However we have to check all the steps in the upload procedure, in case in some place they expect to have the files copied to local locations. 

Notice that in this moment the support for mosaic granules is not well maintained (a new issue will be created for this), so this must be taken into account in implementing and testing this requirements.

This task targets both master and 3.3.x. The upload that is affected should still be the same (or very similar) on both branches. The big differences happen at the end of the import, where the GeoNode resource is finalized and created (master uses the Resource Manager, which doesn't exist in 3.3.x).

**Comment by afabiani** [comment]
We need also to pay attention to the "Original Dataset" download link. That will also need to be updated, probably, in the case of a remote location.

**Comment by giohappy** [comment]
Please @italogsfernandes report here any blocker or unexpected complexity that is worth to be discussed and agreed.

**Comment by italogsfernandes** [comment]
I would divide it in 2 parts:
* **Filesystem paths**: ETA 4 days
     * Adds the field to the form, example: `base_file_path`, `dbf_file_path` etc...
     * Add validators.
     * Change [existing validations](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/upload_validators.py#L47) to handle file paths and not only django file objects.
     * Also change every small steps inside the [save_step_view](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/views.py#L133).
     * Manual and also unit tests with different files, and file types.
* **Generic remote storages** (using smart_open): it needs more analysis.
    * We can't pass it direct to the [gs_uploader](https://github.com/GeoNode/geonode/blob/1c4278ac12cdc7aae9226ab2d2b92586e0173c1c/geonode/upload/upload.py#L358).
    * Inside the gsimporter library, we open the file using the python built-in open. [here](https://github.com/GeoNode/gsimporter/blob/gn-gsimporter/gsimporter/client.py#L294-L296) (called by the [upload task](https://github.com/GeoNode/gsimporter/blob/gn-gsimporter/gsimporter/api.py#L429-L430))
    * So, to use the smat_open library it's needed to update these files of gsimporter.

----
Example of possible/proposed call to the upload api:
```
curl --location --request POST 'http://localhost:8000/api/v2/uploads/upload/' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--header 'Cookie: csrftoken=V7g4BJKNmgqRFltoM5GizihCa9uV2eWD4g213CJQPDK1lROupIE44MArEWhtyLvv; sessionid=x20mqic58gc0oct5mkko30v1iwi8l294' \
--form 'permissions="{ \"users\": {\"AnonymousUser\": [\"view_resourcebase\"]} , \"groups\":{}}"' \
--form 'time="false"' \
--form 'charset="UTF-8"' \
--form 'base_file_path="/usr/src/gisdata/gisdata/data/good/vector/san_andres_y_providencia_administrative.shp"' \
--form 'dbf_file_path="/usr/src/gisdata/gisdata/data/good/vector/san_andres_y_providencia_administrative.dbf"' \
--form 'prj_file_path="/usr/src/gisdata/gisdata/data/good/vector/san_andres_y_providencia_administrative.prj"' \
--form 'shp_file_path="/usr/src/gisdata/gisdata/data/good/vector/san_andres_y_providencia_administrative.shp"' \
--form 'shx_file_path="/usr/src/gisdata/gisdata/data/good/vector/san_andres_y_providencia_administrative.shx"'
```

**Comment by giohappy** [comment]
Given the feedback from @italogsfernandes the plan is to implement what is depicted in the following diagram

The grey component on the left should be something uncoupled from the upload view, since we would like to make it reusable inside the Resource Manager that we have in `master` branch (where it would replace part of the logic inside `GeoServerResourceManager._revise_resource_value` method). For the moment it will be used by the upload component also in `master`, to simplify its design that must adapt both to `master` and `3.3.x`

![image](https://user-images.githubusercontent.com/571129/151178261-851dc9dd-882c-4b3a-bd47-d7537a3f6b8c.png)

**Comment by italogsfernandes** [comment]
ETA for the solution proposed in the diagram: Wednesday, Feb 2nd

**Comment by giohappy** [comment]
Some more clarifications about the bounderies of the DataRetriever component:

 - DataRetriever offers the following minimal high level interface (the naming can be different):
   - open(source, options) -> source can be, for the moment, a Django form instance, a URL (including file:// paths). Options is an extensible object where specific configurations can be set for the DataRetriever operaions. For example, we can say that the file:// path is a r/w location, in this case the DataRetriever does a short circuit to the remote path, without copying anything 
   - getFile() -> DatraRetriever returns a file-like object to the resource.  Where the data is actually locates is transparent to the outside worls.

In theory management of the tmp files is a DataRetriever concern, since the ownership of the data source should be kept internal to the component. The file-like object returned by DataRetriever could be smart enough to delete the tmp file when the read operation completes, but this would prevent reading the resource multiple times.
@afabiani @etj what's your opinion on this?

**Comment by giohappy** [comment]
The following points were agreed with @italogsfernandes and @afabiani:

- The Data Retriever will just take care of obtaining the data (wherever it comes from) and provide either a valid file object or file path
- The caller is responsible to singal that the file reference can be closed (deleted) when we're done with it
- The Upload object will still be used, since it keeps track of the import progress and the connection with the upload session object. However, the `Upload` object **will not create any additional temporary copy** of the file and it will create the UploadFile entry **only** in case we want to store the data inside GeoNode storage (e.g. in case of files uploaded through the Web UI, or whenevent we want to keep a local copy of the drata)

Here below th updated the diagram 

![image](https://user-images.githubusercontent.com/571129/151581426-e71317ca-a1cd-4c69-8bc9-bdc0b28c5109.png)
