### ISSUE TITLE
window install error

### ISSUE THREAD

**Issue by gengyanlei** [GeoNode/geonode#8677]
geonode version: 3.0 or 3.2.x
I commented out # production uWSGI==2.0.18 gunicorn==20.0.4 ipython==7.14.0 docker==4.2.0 invoke==1.4.1
pip install -r requirements.txt ,successful
pip install -e .   error
![image](https://user-images.githubusercontent.com/22360785/150717303-534e0bac-70f8-4798-a22b-f777b5348176.png)

Please help, thanks.

**Comment by gengyanlei** [comment]
And I tried to install on ubuntu18.04 and docker, both failed, and all attempts to solve failed.
![4ebf739c1364cca8825980d415ef513](https://user-images.githubusercontent.com/22360785/150758816-123cfb0f-0c0c-4af2-9142-71afc88c4abb.jpg)

**Comment by giohappy** [comment]
what errosrs did you get on ubuntu?
In general I advice you to use a more recent version of Ubuntu. 20.04 is the LTS we currently use as referemce.

**Comment by gengyanlei** [comment]
@giohappy 
I test it on docker-ubuntu20.04，but error。just like the above。
In the documentation, it is suggested that Shapely=1.6.3 and python>=3.7 in the windows, but it is contradictory and the installation fails.
Is there a difference between anaconda-python and the official python.exe?

win10 and ubuntu20.04 I  have tried, but error.

**Comment by MoRadwan74** [comment]
> I commented out # production uWSGI==2.0.18 gunicorn==20.0.4 ipython==7.14.0 docker==4.2.0 invoke==1.4.1
> pip install -r requirements.txt ,successful
> pip install -e . error

This makes sense as you also should comment the production and tests packages from **setup.cfg**

https://github.com/GeoNode/geonode/blob/3.2.x/setup.cfg#L163-L188

**Comment by gengyanlei** [comment]
Thanks, I didn't realize the problem and searched to find out that "pip install ." is equivalent to "python setup.py".

**Comment by gengyanlei** [comment]
But on ubuntu18.04, no matter whether you use docker or not, there are problems, there are 3 packages that cannot be installed.

“apt install -y --allow-downgrades build-essential \
    python3-gdal=3.3.2+dfsg-2~focal2 gdal-bin=3.3.2+dfsg-2~focal2 libgdal-dev=3.3.2+dfsg-2~focal2 \
    python3.8-dev python3.8-venv virtualenvwrapper \
    libxml2 libxml2-dev gettext libmemcached-dev zlib1g-dev \
    libxslt1-dev libjpeg-dev libpng-dev libpq-dev \
    software-properties-common build-essential \
    git unzip gcc zlib1g-dev libgeos-dev libproj-dev \
    sqlite3 spatialite-bin libsqlite3-mod-spatialite libsqlite3-dev”

I tried win10 again.
tks.
