### ISSUE TITLE
Simplify Upload Size Limiting setup

### ISSUE THREAD

**Issue by italogsfernandes** [GeoNode/geonode#8687]
## Overview

* `file_upload_handler` size limit
    * We have 3 size limits settings available, but the `file_upload_handler` is too complex. (https://github.com/GeoNode/geonode/blob/master/geonode/upload/migrations/0034_uploadsizelimit.py#L13-L17)
    * This limit prevents the upload of large files to the server, even before the django form validations.
    * It should be always greater than the other sizes, so instead of exposing this config through the size limiting api. It can be better set as a Django settings variable and corresponding env variable.
    * This variable should indicate the multiplier to be used:
        * For example: 3 times, means that the `file_upload_handler` limit is going to be 3 times the value of the `total_upload_size_sum` limit.
    * Simplifying it, we can also prevent misconfiguration that can lead to the creation empty datasets/documents.
* Update comments on the env variables related to it, letting it clear that it's only used to create the objects and when modified it won't modify the current already existing value.
* Improve code comments in the UploadManager to better differentiate document limits and datasets limits.  https://github.com/GeoNode/geonode/blob/master/geonode/upload/models.py#L95-L101

**Comment by giohappy** [comment]
@italogsfernandes I would totally hide that configuration. It's a detail that dependa on the current implementation of the upload view, and I hope it will change soon.

That limit can be defined in code as (DEFAULT_MAX_UPLOAD_SIZE * 2) + some room for the rest of request data.
