### ISSUE TITLE
Printing not working - Communication Trouble: Status undefined [object, Object]

### ISSUE THREAD

**Issue by stephenedavis** [GeoNode/geonode#872]
When trying to print a map, the following error message is given

Communication Trouble: Status undefined [object, Object]

Verified the yaml file is correct.  Issue is reproducible on alpha dev server.

**Comment by abersh** [comment]
I deploy Geonod 2.4 production by domain name after deployed when I want to print the layer this error is displayed "communication trouble status undefined [object Object]"
