### ISSUE TITLE
Errors with harvested ressources

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#8726]
## Expected Behavior

If I define a GeoNode Unified Harvester to copy resources:
![grafik](https://user-images.githubusercontent.com/6172324/152013531-ceae2ecf-b4a7-4f59-9ba2-774558f01e7e.png)

these resources will be accessible by my node.

## Actual Behavior
Some resources are not able to get copied and throw keyword errors:
![grafik](https://user-images.githubusercontent.com/6172324/152013914-021720b2-0b15-48d5-a8a7-f0d8a24deda0.png)

The other resources´ metadata are copied (ResourceBase objects) but the content itself is not present:
![grafik](https://user-images.githubusercontent.com/6172324/152014450-5603988d-70e2-4f15-b4f8-c44953123bff.png)

Layer resources are not loaded properly as well:
![grafik](https://user-images.githubusercontent.com/6172324/152014871-b6469081-4e98-4142-9a0a-7aa6e3ad7713.png)

Even though they are part of GeoServer:
![grafik](https://user-images.githubusercontent.com/6172324/152014946-35ea7bf0-b3c7-40cb-9bfa-8b08da37ae8e.png)

But there is an additional `geonode_` in the layers name.

## Steps to Reproduce the Problem

  1. Define harvester with copy configuration (master as harvester node, 3.2.x as instance which gets harvested)
  2. Harvest resources
  3. try to open the resources

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker
  - Additional details:

There are many PRs and ISSUEs targeting the new harvester feature (https://github.com/GeoNode/geonode/pulls?q=is%3Apr+harvest ; https://github.com/GeoNode/geonode/issues?q=is%3Aissue+harvester). It was first discussed as part of the GNIP-89 (#7664). Some of the issues I encountered were addressed before (https://github.com/GeoNode/geonode/pull/7947#pullrequestreview-763235622) but should be fixed by now. I would encourage other users and admins to test this feature more thorough.

**Comment by giohappy** [comment]
@ricardogsilva can you please take a look a this issue?

**Comment by ricardogsilva** [comment]
@giohappy, I will take a look at it

@gannebamm 
is this still relevant?
are you able to share a public GeoNode URL that I may use as a harvest test target where I can reproduce the problem?

**Comment by gannebamm** [comment]
stale
