### ISSUE TITLE
Notifications for account approval are sent even if GeoNode is configured for open signup

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8732]
[notify_admins_new_signup](https://github.com/GeoNode/geonode/blob/76d80ce898d86cc19830f07812b6c76b5b74bafa/geonode/people/signals.py#L94) is called on every signup. It might be ok, but it should distinguish if a notification for an approval request should be sent or not. When `ACCOUNT_APPROVAL_REQUIRED` is True, which mean that self-registration is active, the notification should just inform of the event, without requesting any approval action.

A conditional check must be added to the [account_approve notifaction template](https://github.com/GeoNode/geonode/blob/d89fe308d97ac41e658007a7d86cdd63d281de54/geonode/templates/pinax/notifications/account_approve/full.txt). The paragraph about the account approval will only be rendered if `ACCOUNT_APPROVAL_REQUIRED` is `True`.

**Comment by marthamareal** [comment]
@giohappy , should we create the notification of the event in pinax too or we can send it directly with [queue_notification](https://github.com/GeoNode/geonode/blob/76d80ce898d86cc19830f07812b6c76b5b74bafa/geonode/notifications_helper.py#L106)

**Comment by afabiani** [comment]
I guess this must be backported to 3.3.x too

**Comment by giohappy** [comment]
cherry-picked in https://github.com/GeoNode/geonode/commit/6d2fe7fcaf973adeed9c550d7517d1b139196d85
