### ISSUE TITLE
Implement non-interactive upload for vector layers and csv

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8738]
The upload interface is being employed by the upload API and the importlayers command. For this use cases we want the upload service to ingest the data without triggering any interactive step, whose current design targets the Upload web form.

The best solution is to give the client the option to provide the expected values for those steps (srs step time step, imagemosaic granule) when the upload is started. This way we can automatically ingest a dataset as time series, for example.
However, this will require quite a deep change to the upload module, which is not the current goal.

For simplicity **we will just implement a "non-interactive" option** to make the upload module only execute the "run" and "final" steps, skipping any intermediate step (as we have for [shapefiles and csv](https://github.com/GeoNode/geonode/blob/76d80ce898d86cc19830f07812b6c76b5b74bafa/geonode/upload/utils.py#L203-L204)).

**Comment by majid-saeed** [comment]
it will be good. also 
1- the image mosaic granule datasets having dimensions (time specifically) are not recognized as time series in the layer type section.
2- downloading an image mosaic plugin layer should have an option to filter the mosaic granules.
![image](https://user-images.githubusercontent.com/56892853/152401860-89cf2efc-5028-4f76-affd-d519f8226586.png)

**Comment by giohappy** [comment]
done in https://github.com/GeoNode/geonode/pull/8812
