### ISSUE TITLE
DisallowedHost at / Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS

### ISSUE THREAD

**Issue by gengyanlei** [GeoNode/geonode#8747]
windows
geonode3.0
ALLOWED_HOSTS=['django', '*', 'localhost', '127.0.0.1'] in geonode.settings.py

**Comment by t-book** [comment]
Try

`ALLOWED_HOSTS=['*'] `

for testing

**Comment by gengyanlei** [comment]
@t-book 
![image](https://user-images.githubusercontent.com/22360785/152681350-79b4d476-c79e-4a62-99af-38c00a9970ae.png)
![image](https://user-images.githubusercontent.com/22360785/152681378-f87726fe-7f3d-4803-b56b-7344f954d74f.png)

**Comment by gengyanlei** [comment]
"DisallowedHost at / Invalid HTTP_HOST header", does this question prohibit webpage access?
