### ISSUE TITLE
No resources imported on a remote service

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8810]
## Expected Behavior

A user should be able to import resources on a remote service.

## Actual Behavior
`Import Service Resources` always displays this message with 0 resources fetched.
![xx](https://user-images.githubusercontent.com/20810749/154027731-57598550-cd9e-45df-9f7c-bc4a7748ca74.png)

## Steps to Reproduce the Problem

  1. Go to https://master.demo.geonode.org.
  2. `Data` -> `Remote Services` -> `Add remote service`.
  3. The import resources page will always have the above message.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal which remote resource URl are you testing?

**Comment by marthamareal** [comment]
> @marthamareal which remote resource URl are you testing?

Am testing this, in particular, https://master.demo.geonode.org/services/969/, however there other existing services with the same status.

**Comment by giohappy** [comment]
>Am testing this, in particular, https://master.demo.geonode.org/services/969/, however there other existing services with the same status.

Did you inspect the GetCapabilities response from that WMS service? Resources can only be imported if they are advertized inside the GetCap response.

**Comment by marthamareal** [comment]
> Did you inspect the GetCapabilities response from that WMS service? Resources can only be imported if they are advertized inside the GetCap response.

@giohappy, From [here](https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/#requests) `GetCapabilities` is among the supported service requests. 
Also in 3.3.x, resources import resources are listed, using this service

**Comment by giohappy** [comment]
Could you share the URL that you set for the remote service?

**Comment by marthamareal** [comment]
> Could you share the URL that you set for the remote service?

https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv

**Comment by giohappy** [comment]
The tasks that should retrieve harvestable resources are pending since days, so it looks like they're stuck inside the celery queues.

![image](https://user-images.githubusercontent.com/571129/154709615-0a45221f-bfcd-4e20-975d-86ca60050adb.png)

**Comment by afabiani** [comment]
So far I had to remove that `on-going` session and refresh the others.

Restarting the `GEBCO` one, worked

![image](https://user-images.githubusercontent.com/1278021/154719235-b7365f8d-1ed2-471f-b74c-9cc88cd21c2a.png)

Had to click on `Rescan` also in order to refresh the `Harvesting Session`

![image](https://user-images.githubusercontent.com/1278021/154719359-277c1b39-a487-4ab3-b2b3-d68677845a35.png)

Not sure why that one was blocked... we would need probably to envisage an expiration time for those sessions so that in the case of a server crash or restart they won't block the new ones.

**Comment by giohappy** [comment]
The scheduled harvesting mechanism must be made more robust. It happens that some harvesting sessions remain stuck. The frequent deployments might be the reason, with pending tasks failing to recover. 

@ricardogsilva might give us some more insights on the cases that might get stuck in a running session.

We have stopped any scheduled harvester now. 
@marthamareal I would like you to make some tests creating / updating the services and see if they are configured with the scheduling enabled, which shouldn't happen. The scheduling should be enabled only by configuration. The remote services should perform one-time harvesting and wait for requests triggered by the user.

**Comment by marthamareal** [comment]
@giohappy, I am testing this with master.demo, and these are the steps am taking with results:
1. Removed the service URL i was testing with.
2. Created the service with url (https://www.gebco.net/data_and_products/gebco_web_services/web_map_service/mapserv)
3. On checking `Admin` -> `Harvesting` -> `Harvester`, scheduling is enabled.
![schedule](https://user-images.githubusercontent.com/20810749/154920175-02edea4b-d655-4513-8397-a77969bbec1b.png)

**Comment by giohappy** [comment]
This PR https://github.com/GeoNode/geonode/commit/205daf09df5486ca316ca142638ca35e5b82c126 from @afabiani should fix most of these problems. 
Let's wait for it to be deployed on master demo then please test it again.
