### ISSUE TITLE
Total in responsible facet for Apps and layers does not match with total of resources found.

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8813]
## Expected Behavior
Total in responsible facet for Apps should match with the total of resources found

## Actual Behavior

Currently, the total of resources found on the apps list and layers list don't match with total in responsible facet.
 
![xx](https://user-images.githubusercontent.com/20810749/154222878-0081435c-d4b5-4c82-aad5-5a6bebe128b2.png)

## Steps to Reproduce the Problem

  1. Go to `Apps` -> `Explore Apps` on https://development.demo.geonode.org
  2. Am also `Data` -> `Layers`
  3. Check the toatal of resources found does not match with total in `RESPONSIBLE` dropdown

## Specifications

  - GeoNode version: 3.3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@afabiani This is fixed for `Apps` however for layers, I think the `vector_time` type is still not catered for hence miss-matching totals. Eg when i filter with `owner__username__in=giohappy`, these are the results i get
![layers](https://user-images.githubusercontent.com/20810749/154930556-d2004201-0093-4fba-9fb3-1dac89bb7985.png)

**Comment by afabiani** [comment]
@marthamareal nope, for the time series is ok. It always worked like this.
