### ISSUE TITLE
Docker config :  Cant upload shapefiles or create maps . Error HTTPConnectionPool(host='geoserver', port=8080)

### ISSUE THREAD

**Issue by Somnerd** [GeoNode/geonode#8854]
## Expected Behavior
Upload a shapefile project and have it create borders on a map with appropriate metadata 

## Actual Behavior
It refuses to accept the upload with an error of [
UI output : Unexpected error! - 404 Not Found. Origin server was unable or unwilling to find the resource requested.

Web console output :
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/progress:1          Failed to load resource: the server responded with a status of 404 (Not Found)
gisnode.crowdapps.net/upload/srs?id=107&force_ajax=true&force_ajax=true:1          Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for https://gisnode.crowdapps.net/static/lib/js/underscore.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Cant post celery container output , too long .

## Steps to Reproduce the Problem

  1. Manually install and config docker setup of Geonode
  2. Upload shapefile project
  3. Get error

## Specifications

  - GeoNode version: latest docker image
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): manual docker (followed the tutorial :https://docs.geonode.org/en/master/install/advanced/core/index.html#install-the-docker-and-docker-compose-packages-on-a-ubuntu-host)
  - Platform: Ubuntu 20.04
  - Additional details:

**Comment by afabiani** [comment]
Can you please try with `docker-compose -f docker-compose.yml up --build`

**Comment by Somnerd** [comment]
![image](https://user-images.githubusercontent.com/25110750/155512547-f674bed4-68ac-4252-b46c-a7b2de2a87c5.png) 
It falls into this loop , or at least it has been for the past hour or  so

**Comment by Somnerd** [comment]
I tried shutting everything down and building the again the containers , it falls into the same behaviour 
![image](https://user-images.githubusercontent.com/25110750/155513374-38d94b27-fa5a-403e-830b-1e0ab52f41d9.png)

**Comment by obersupermega** [comment]
Hi. As I already wrote in the Gitter forum on 02 May, the problem is the .env file of the docker version. The enclosing double quotes in the GEOSERVER_JAVA_OPTS must be removed.

This concerns the current master and the 3.3.x branch.
