### ISSUE TITLE
Implementation of an Users Map

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#886]
We could add a location field to the user profile, and let the user populate in its profile using a geocoding API such as GeoNames from the filled information in the city, area, zipcode, country field.
Having this in place we could add a user map in the people page.
As we are not using geodjango, we may need to add two fields for storing x and y.
Or do you think we can switch to geodjango at this point (and have spatialite/postgis in the db)?
I am planning to keep this in my branch and postpone its integration in the development of 2.1.

**Comment by jj0hns0n** [comment]
This would be a really fun project at the sprint, but Im going to push to 2.5 for now. 

I'd also like a geonode users/servers map on our geonode.org site.

**Comment by capooti** [comment]
We did some work at this regard in our instance.
Maye I can try to integrate the work done.
Assigning it to myself.

**Comment by jj0hns0n** [comment]
@capooti any update on this? Moving to 2.7 for now, but feel free to move back if its going to get in in time.
