### ISSUE TITLE
User layers WMS GetCapabilities document in the user's profile, redirects to a blank page.

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#8874]
## Actual Behavior
 Clicking on the `User layers WMS GetCapabilities document` in the user's profile takes me to a blank page.

## Steps to Reproduce the Problem

  1. Go to master.demo and login
  2. Click `About` > `People` and select a user's profile
  3. Click on `User layers WMS GetCapabilities document`, it redirects to a blank page.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
Cannot reproduce this currently.

**Comment by afabiani** [comment]
Yes, likely. The outcome should be an XML document.

**Comment by giohappy** [comment]
@marthamareal can we close this?

**Comment by marthamareal** [comment]
@giohappy I think from the above description, this is not a bug(So it can be closed), However, maybe we could make an improvement to inform a user if there is no XML to show. instead of them seeing a blank page. for better `UX`.

**Comment by giohappy** [comment]
@marthamareal please do it. I will close this one meanwhile.
