### ISSUE TITLE
Data export based on extent

### ISSUE THREAD

**Issue by capooti** [GeoNode/geonode#889]
The download link in the layer info page should export data clipped to the currently selected extent in the map frame.
This shouldn't be that complicated, as the GS WFS GetFeature and WCS GetCoverage supports the BBOX parameter.

**Comment by jj0hns0n** [comment]
Moving to 2.5. Clip and Ship would still be very useful.

**Comment by capooti** [comment]
I think I will need to work with this in the next days as we really need it urgently. Maybe in the sprint if I have time? So assigning it to me and set back to 2.4 milestone.

**Comment by jlautarosilva** [comment]
this feature is going to be implemented in 2.4? I offer myself for testing.

**Comment by simod** [comment]
I don't think it will be.

**Comment by jj0hns0n** [comment]
There was a thread about this feature from WFP. @pjdufour do you have any insight on the status. Would be good to get merged for 2.5/2.6 but moving to 2.7 for now until we know.
