### ISSUE TITLE
Review API v2 allowed methods

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#8908]
We want to make a review of the exposed API v2 methods and disable any method that isn't expected to be allowed / used.

**Comment by giohappy** [comment]
@marthamareal

>- POST [/api/v2/uploads/upload/](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/uploads/uploads_upload_create)

This is clearly required. It's the main method for executing the upload

>- GET [/api/v2/resource-service/execution-status/{execution_id}{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_execution_status_formatted_retrieve)

I think we can safely remove the [format_suffix_patterns](url) call [here](https://github.com/GeoNode/geonode/blob/0474498ad197a791a54ce15b76bf0a8cede95667/geonode/resource/api/urls.py#L31)

>- GET [/api/v2/resource-service/exists/{uuid}{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_exists_formatted_retrieve)
- GET [/api/v2/resource-service/search{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_search_formatted_retrieve_2)
- GET [/api/v2/resource-service/search/{resource_type}{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_search_formatted_retrieve)

 I think we can remove [these URLs,](https://github.com/GeoNode/geonode/blob/0474498ad197a791a54ce15b76bf0a8cede95667/geonode/resource/api/urls.py#L25-L27) since they overlap with the search endpoints that are being used at the moment.

Regarding the DELETE methods for the single users and groups (which I don't see reported in your comment), I would make some test to verify they work as expected. In particular the cascaded actions on related itesm.

**Comment by marthamareal** [comment]
@giohappy, Do you mean these

**To remove**:

1. DELETE [/api/v2/groups/](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/groups/groups_destroy)
2. DELETE [/api/v2/users/](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/users/users_destroy)

**To test:**

1. DELETE [/api/v2/groups/{id}/](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/groups/groups_destroy_2)
2. DELETE [/api/v2/users/{id}/](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/users/users_destroy_2)

**Comment by giohappy** [comment]
@marthamareal yes. I don't understand how a DELETE would work on a list endpoint...

**Comment by giohappy** [comment]
@marthamareal let's recap:

 - we're going to hide the following:
   - GET [/api/v2/resource-service/exists/{uuid}{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_exists_formatted_retrieve)
   - GET [/api/v2/resource-service/search{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_search_formatted_retrieve_2)
   - GET [/api/v2/resource-service/search/{resource_type}{format}](https://master.demo.geonode.org/api/v2/schema/swagger-ui/#/resource-service/resource_service_search_formatted_retrieve)
 - We disable POST and DELETE for all the resources endpoints (`resources`, `documents`, `datasets` and `geoaps`) by listing the accepted methods with the `http_method_names` property
 - We disable PATCH and DELETE for Upload-size-limits and Uploads
 - We want to test the following:
   - groups
     - POST and DELETE (available only to admins)
     - PATCH (only available to group managers and admins)
   - users:
     - POST and DELETE (available only to admins)
     - PATCH (only available for the logged in user and admins)

**Comment by marthamareal** [comment]
@giohappy, From the tests i did on groups and users, On the UI,(Everything is managed correctly **accept where a group manager can delete a group**) However from the API requests, This is how the requests behave:

**Groups**
1. POST api/v2/groups
   - Anonymous = 403
   - Registered user = 201
   - admin = 201
2. PATCH api/v2/groups/{id}
   - Anonymous = 403
   - Registered user = 200
   - group manager = 200
   - admin = 200
3. DELETE api/v2/groups/{id}
   - Anonymous = 403
   - Registered user = 204
   - group manager = 204
   - admin = 204
   
**Users**
1. POST api/v2/users
   - Anonymous = 403
   - admin = 201
2. PATCH api/v2/users/{id}
   - Anonymous = 403
   - Registered user = 403
   - profile owner = 403
   - admin = 200
3. DELETE api/v2/users/{id}
   - Anonymous = 403
   - Registered user = 403
   - profile owner = 403
   - admin = 204

**Comment by marthamareal** [comment]
@giohappy, 
The delete for groups, `204` means success. so it might also need fixing
