### ISSUE TITLE
DataSet option missing on GeoNode 

### ISSUE THREAD

**Issue by ChiranthTL** [GeoNode/geonode#8986]
hello Guys...i have installed GeoNode on ubuntu. As on the demo site it has an option to add or upload an dataset. But i do not see in mine. why would that be any idea. ?

**Comment by gannebamm** [comment]
Was discussed and resolved on gitter
[28. März 2022 08:53](https://gitter.im/GeoNode/general?at=62415b4e0909252318466ada)
