### ISSUE TITLE
Transaction Management Error at metadata edit

### ISSUE THREAD

**Issue by gannebamm** [GeoNode/geonode#8997]
## Expected Behavior
I am able to edit metadata

## Actual Behavior
**Sometimes** the following error is thrown:

https://gist.github.com/gannebamm/3e34c49332ddf153239f3ede073c0489

## Steps to Reproduce the Problem

  1. upload dataset
  2. edit metadata
  3. **sometimes** an exception is thrown

## Specifications

  - GeoNode version: 3.3.x (at: 04f0bf2fdc860c4ba553bc003ec5bd521952827f)
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform: docker
  - Additional details:

**Comment by gannebamm** [comment]
Sometimes it works and the already present tags get deleted

**Comment by gannebamm** [comment]
@giohappy are you sure about the PR number ([Fixes #8984] Error adding remote services)?

**Comment by giohappy** [comment]
yes, the error is probable related to the same issue that was affecting the creation of remote services. Take a look at the files in the PR that was just merged by @afabiani https://github.com/GeoNode/geonode/pull/8985

**Comment by gannebamm** [comment]
I can confirm that https://github.com/GeoNode/geonode/pull/8985 fixed this issue. Well done 👍
