### ISSUE TITLE
No such file or directory *static* when creating layer

### ISSUE THREAD

**Issue by etj** [GeoNode/geonode#9007]
## Actual Behavior

When uploading a new layer, often there is this kind of error:

![image](https://user-images.githubusercontent.com/717359/160582756-09483f36-8dec-45ce-b7d3-8c512b6d550c.png)

```
Errore imprevisto! - Unknwon Error Code. Contattare l'amministratore di sistema per ulteriori informazioni su questo messaggio di errore. 
Additional info: [Client Error: Bad Request
Unexpected exception [Errno 2] No such file or directory: '/mnt/volumes/statics/static/tmpjt3stccf']
```

## Steps to Reproduce the Problem

  1. create a layer by uploading a big file

## Specifications

  - GeoNode version: 3.3.x @ https://development.demo.geonode.org/
  - This bug has already been fixed on master (issue to be found yet)

**Comment by afabiani** [comment]
Fixed by https://github.com/GeoNode/geonode/pull/9019
