### ISSUE TITLE
Geoserver importer NO_CRS task status doesn't trigger the CRS selection step

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#9016]
When an invalid .prj file is sent to Geoserver the importer blocks in a `PENDING` status with the first task in `NO_CRS` status.
GeoNode's upload keeps returning the `PENDING` status but with an empty `resume_url`, which is expected to be populated to let the client redirect to the CRS selection (as with the `srs` step).

The result is a stale import that can only be deleted with the delete button (`delete_url`).

This was tested on master with this [shepafile](https://github.com/GeoNode/geonode/files/8387958/Secondary_Schools.zip).
I suspect it also affects 3.3.x.

**Comment by giohappy** [comment]
The problem is still there @afabiani. It can be reproduced on master with [this sample tiff](https://github.com/GeoNode/geonode/files/8483463/n32_1991_0001_123.zip)

**Comment by afabiani** [comment]
@giohappy I don't think this one is related to this issue, or at least it does not depend from the Importer... I'll check
This is the error I get

```
Could not find any valid Time Regex for the Mosaic files.
Traceback (most recent call last):
  File "/mnt/c/Work/Code/geonode/geonode/upload/views.py", line 705, in view
    resp = _steps[step](req, upload_session)
  File "/mnt/c/Work/Code/geonode/geonode/upload/views.py", line 161, in save_step_view
    import_session, upload = save_step(
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/mnt/c/Work/Code/geonode/geonode/upload/upload.py", line 427, in save_step
    raise e
  File "/mnt/c/Work/Code/geonode/geonode/upload/upload.py", line 340, in save_step
    target_store, files_to_upload = utils.import_imagemosaic_granules(
  File "/mnt/c/Work/Code/geonode/geonode/upload/utils.py", line 722, in import_imagemosaic_granules
    raise GeneralUploadException(detail=_("Could not find any valid Time Regex for the Mosaic files."))
geonode.upload.api.exceptions.GeneralUploadException: Could not find any valid Time Regex for the Mosaic files.
Internal Server Error: /api/v2/uploads/upload
"POST /api/v2/uploads/upload HTTP/1.1" 500 114
```

while uploading a dataset without a valid CRS resulting in

![image](https://user-images.githubusercontent.com/1278021/163238468-2e8fa274-efd1-4fb9-b747-49253ec27722.png)

**Comment by giohappy** [comment]
@afabiani I've tested the sample I attached both locally and master. Both cases I get the progress bar stuck and the importer session task[0] with NO_CRS.

**Comment by afabiani** [comment]
we should explictly send "mosaic=False" from the upload form

**Comment by giohappy** [comment]
No, we should assume mosaic False by default, not the reverse. Also considering that support for mosaic is a not well defined status right now.

**Comment by giohappy** [comment]
Found the difference. You were trying to upload the zip file, which triggers the mosaic workflow, because of the field. 
I will open an issue for that, but when the tiff is loaded directly the problme of the progress stuck can be reproduced

**Comment by afabiani** [comment]
About the raster files, currently the workflow does not envisage passing through the `srs_step`, this is why it is not blocking...

**Comment by giohappy** [comment]
@afabiani either we support it, or we return an error in case the importer is stuck with an invalid CRS.

**Comment by afabiani** [comment]
yes, I agree @giohappy
