### ISSUE TITLE
Unable to load page on Safari browser with GeoNode 4.0.x

### ISSUE THREAD

**Issue by manhninh** [GeoNode/geonode#9022]
## Expected Behavior
Install the latest version on the master branch. Expect to work on all browsers

## Actual Behavior
Google Chrome browser has no problem but on Safari browser the screen stops.
![Screen Shot 2022-04-03 at 16 58 30](https://user-images.githubusercontent.com/13707506/161422380-4f5a6315-bdcd-4763-a027-793a7a14e99f.png)

## Steps to Reproduce the Problem

   1. Install GeoNode from master branch
   2. Access from Safari browser

## Specifications

   - GeoNode version: 4.0.0
   - Installation method: manual
   - Platform: Ubuntu

**Comment by t-book** [comment]
@allyoucanmap It looks safari has some problems with regex look behinds?

**Comment by giohappy** [comment]
@t-book I don't have Safari to test it but can you replicate it on master demo?

**Comment by manhninh** [comment]
@giohappy The error is still happening on Safari browser. Can you help me?

**Comment by gannebamm** [comment]
One of my researchers also experienced this issue, but with a 3.3.x instance.

**Comment by giohappy** [comment]
@manhninh it wasn't a priority but we are investigating right now.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #954](https://github.com/GeoNode/geonode-mapstore-client/issues/954) via [**ZenHub**](https://www.zenhub.com/)
