### ISSUE TITLE
Disable caching header in GeoNode proxy for the REST API

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9042]
MapStore proxies requests to Geoserver REST API through GeoNode's internal Geoserver proxy.
Apparently, the proxy sets its own cache headers, instead of returning the headers set by Geoserver'r response.
This is particularly problematic for the requests toward Geoserver REST API, since these are assumed to not be cached.

For example when requesting style metadata MapStore sees stale data and gets fooled. Consequently, MapStore does wrong assumptions and causes the corruption of style data and metadata.

We want the Geoserver proxy to avoid setting cache headers and, in case, return the ones received from Geoserver.

**Comment by simboss** [comment]
@afabiani we need to backport this to 3.2.x as well.

**Comment by afabiani** [comment]
@simboss done https://github.com/GeoNode/geonode/pull/9087
