### ISSUE TITLE
Unable to upload dataset zip file downloaded from direct download feature

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9080]
## Expected Behavior

Users should be able to upload dataset zip file downloaded from the direct download feature in Geonode

## Actual Behavior
Uploading a zip file obtained from the direct download feature throw 500 Internal server error
```
[ErrorDetail(string='Could not find any valid spatial file inside the uploaded zip', code='upload_exception')]
Traceback (most recent call last):
  File "/opt/geonode/geonode/upload/views.py", line 703, in view
    resp = _steps[step](req, upload_session)
  File "/opt/geonode/geonode/upload/views.py", line 222, in save_step_view
    raise GeneralUploadException(detail=errors)
geonode.upload.api.exceptions.GeneralUploadException: [ErrorDetail(string='Could not find any valid spatial file inside the uploaded zip', code='upload_exception')]
Internal Server Error: /api/v2/uploads/upload
"POST /api/v2/uploads/upload HTTP/1.1" 500 167
```

## Steps to Reproduce the Problem

  1. Go to master.demo datasets and upload a dataset with a zip file
  2. From the list of datasets, Click on an uploaded dataset, and click the download icon between share and favorite icons
  3. Then upload a dataset using the downloaded zip file
  4. An internal server error will be raised by the API

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal can you share the zip file please?

**Comment by giohappy** [comment]
@marthamareal from a quick inspection you will see that the downloaded zip files contains a zip file on its turn. GeoNode of coruse won't accept it. If the double encoding is the result of the direct download we should in case open an issue for that.
