### ISSUE TITLE
Group managers are assigned Manage permission on adding a group with any permission in share permissions form

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9114]
## Expected Behavior

On sharing a resource, 
1. Default workflow(AUTO PUBLISH):
 - permission set to a group should apply to all group members and managers.
 - promotion and demotion of group members should not affect the shared permission
 - on removing a member from a group should affect their permission to a resource
 
2. Other workflows
 - Managers are only assigned permissions relative to a workflow if the group added is an owner's group or a resource group ( group assigned in resource's metadata)

## Actual Behavior
On sharing a resource, 
- In default workflow(AUTO PUBLISH), Managers of a group are given Manage permissions regardless of the assigned permission.

## Steps to Reproduce the Problem

  1. as an admin, Select a resource and share it with a group with managers, and assign `View` permission
  2. Refresh the page and click on share. Notice that managers of the group are added with `Manage` permission                                                                                           
  4. Access the resource as a manager in the `/api/v2/{resource_id}`, Notice that only view perms are returned and can not perform manage permissions.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by afabiani** [comment]
@marthamareal the _second_ part of the issue sentence is superseded by https://github.com/GeoNode/geonode/issues/9115
