### ISSUE TITLE
Advanced Workflow: permissions assigned to managers/members should be filtered by owner and resource group metadata only

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9115]
## Expected Behavior
When automatically setting the permissions through the advanced workflow, the `groups` to consider in order to set the `managers` and `members` ones are **only**:
 - The `resource.owner` group (if any)
 - The `resource.metadata.group` (if any)

That means that whenever we manually assign some sort of permission to another `group`, whatever, through the `share` panel, unless one of the previous condition are met, there won't be any automatic action.

## Actual Behavior
The advanced workflow consider any `group` having some sort of access to the resource.

## Steps to Reproduce the Problem

  1. Create a `test_group1` and assign it to `test_user1`, also create `test_manager1` and `test_member1`
  2. Create a `test_group2` and create `test_manager2` and `test_member2`
  3. Create a `test_group3` and create `test_manager3` and `test_member3`
  4. Upload a resource owining to `test_user1`, verify the `test_manager1` and `test_member1` have permissions to the `resource`
  5. Assign `test_group2` to the resource, verify the `test_manager2` and `test_member2` have permissions to the `resource`
  6. Assign `view` permissions to `test_group3`, verify no further/specifc permissions have been set for `test_manager3` or `test_member3`

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
confirmed @afabiani
