### ISSUE TITLE
502 Bad Gateway on updating thumbnail

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9148]
## Expected Behavior
User should be able to update the thumbnail successfully

## Actual Behavior

502 Bad Gateway is returned on updating thumbnail on all forms.
![ss](https://user-images.githubusercontent.com/20810749/163956120-b117b073-ded0-4a6f-9873-3298d490250b.png)

## Steps to Reproduce the Problem

  1. Select a dataset, `Edit` > `Edit Metadata`
  2. Set thumbnail from map
  3. Notice the error above is shown.

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal can you please try again now?

**Comment by marthamareal** [comment]
@giohappy i can now update thumbs correctly

**Comment by giohappy** [comment]
the problem is wikimedia. I'm going to send a PR to switch to OSM for the time being.
