### ISSUE TITLE
Blured icon images 

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#9225]
**Is your feature request related to a problem? Please describe.**
The document icons are stretched over their actual file dimensions, which leads to an ugly look and feel.

![Bildschirmfoto 2022-04-26 um 11 24 43](https://user-images.githubusercontent.com/20478652/165268940-6600012d-5d0d-458f-a898-6d676a406d59.png)

![Bildschirmfoto 2022-04-26 um 11 24 32](https://user-images.githubusercontent.com/20478652/165268961-fde1e9f6-1148-49e3-95c9-e1a337095acb.png)

https://master.demo.geonode.org/catalogue/#/document/858

**Describe the solution you'd like**
We can either provide the images in a better resulution and/or load them via a [srcset](https://html.com/attributes/img-srcset/) or prevent stretching the image by getting rid of 100% values in css.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #955](https://github.com/GeoNode/geonode-mapstore-client/issues/955) via [**ZenHub**](https://www.zenhub.com/)
