### ISSUE TITLE
The font size seems undecided

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#9227]
**Is your feature request related to a problem? Please describe.**
The look and feel of the font sizing across pages feels undecided. 
F.e. Some important interface options like ordering appear very small. 

![Bildschirmfoto 2022-04-26 um 11 41 27](https://user-images.githubusercontent.com/20478652/165271774-7a0f9e78-95bb-4cbd-8709-a5efdaf8b871.png)

Further important buttons like the save button could stand out more clearly by use of a different font weight or background color.

![Bildschirmfoto 2022-04-26 um 10 21 16](https://user-images.githubusercontent.com/20478652/165271896-c7188031-9b2f-4744-9a20-a11950199768.png)

**Describe the solution you'd like**
A balance and clear font sizing. As often less is more.

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #956](https://github.com/GeoNode/geonode-mapstore-client/issues/956) via [**ZenHub**](https://www.zenhub.com/)
