### ISSUE TITLE
Disable permissions in the UI when running with a vanilla geoserver

### ISSUE THREAD

**Issue by ingenieroariel** [GeoNode/geonode#923]
This is needed for the live dvd

**Comment by jj0hns0n** [comment]
This was completed in https://github.com/GeoNode/geonode/commit/1e1969a73a4f98739bc2e05750d6089675d9eaf9

**Comment by kalxas** [comment]
Thanks!

**Comment by kalxas** [comment]
Unfortunately this is still happening, even after upgrade to 2.4 final

**Comment by jj0hns0n** [comment]
@kalxas can we look at this on current geonode-live?
