### ISSUE TITLE
Add "with_resources" GET parameter on regions and categories endpoints

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9248]
## Expected Behavior

The client should be able to use the "with_resources" GET parameter to filter only values with at least one resource, visible to the current users

## Actual Behavior
Currently, by default the regions and categories endpoints return all items including those with 0 resources connected.

## Steps to Reproduce the Problem

1. go to https://master.demo.geonode.org/
2. Click on Filter > Categories or Regions
3. Notice that items with 0 resources are returned

## Specifications

  - GeoNode version: master
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #969](https://github.com/GeoNode/geonode-mapstore-client/issues/969) via [**ZenHub**](https://www.zenhub.com/)
