### ISSUE TITLE
Migration form Version 3.2 to 4 – map config is missing

### ISSUE THREAD

**Issue by t-book** [GeoNode/geonode#9252]
@afabiani @giohappy did we oversee some already included migration or task?

---

When migrating a GeoNode 3.2 instance to GeoNode 4 (current master), the maps are not loading. 
This as the blob coloumn in `resource_base`, which holds the map configuration is empty. 

The map definition in versions prior to 4 kept this data in `mapstore2_adapter_mapstoredata`.
Further the new version of mapstore expects the existence of a `map` key/value, which might be missing in older map definitions.

**Describe the solution you'd like**
A django migration that copy needed data and taking care of a correct json scheme. 

In [conversation](https://gitter.im/GeoNode/general?at=62696726bb0de60c72120a9e) with @davekennewell, Dave provided a migration that covers most of the work.
What is missing is some kind of validation and/or adding missing keys from ancient map definitions.

See 
https://github.com/Hydrata/geonode/commit/b1b275a9913bd046c0eb93406ebad06bc07a2400

**Comment by giohappy** [comment]
@t-book in theory the upgrade should work seamlessly since the migrations have the needed code to migrate maps data.
We will make some tests internally, in case something is missing, in particular from 3.2  to 4

**Comment by mattiagiupponi** [comment]
Hi @t-book, @giohappy 
Starting from the migration provided, I add another couple of checks to make the migration safer (it migrate also the attributes) and the migration has been moved under the `client` app instead of the `GeoNode maps` app.

The PR is available here: https://github.com/GeoNode/geonode-mapstore-client/pull/959
I tested on a local instance:
- the creation of the DB with the 3.2.x version
- apply migration
- map creation
- checkout to master
- run migrations
- the maps work smoothly

**Comment by giohappy** [comment]
@gannebamm in theory running the migrations should be enough. We have tried to make the transition as smooth as possible, without any manual intervention or custom commands to apply.

**Comment by davekennewell** [comment]
Yes, @gannebamm - for me now, the core geonode migration "just worked". Just pull the new code & run migrations. 

If you're using geonode-project, I found the easiest thing to do was create a fresh 4.x project with the same name as my existing, and then merge my 3.2.x code into the fresh 4.x structure. It's a bit finicky but now I'm confident it's working well. I used the same strategy for geonode-mapstore plugins and no problems their either.

**Comment by t-book** [comment]
@mattiagiupponi I have the case where the json string from geonode 3.2 mapstore_adapter is migrated as string in the resourcebase blob field (masked quotes). And hence cards to not work. 
Did you ever run into this?

**Comment by Inogeo** [comment]
**Not sure this can help/ is relevant** 

I share this work with you, i could migrate from 3 to 4 using this:

Generate backup:
https://github.com/Inogeo/spade/blob/5c314a6a04b9571bd64e7def4dca793a7e85ccce/geonode-backup.sh

Restore backup:
https://github.com/Inogeo/spade/blob/5c314a6a04b9571bd64e7def4dca793a7e85ccce/geonode-restore.sh

I created this django/python command to re-assign properly permissions once the migration is done.
https://github.com/Inogeo/spade/blob/5c314a6a04b9571bd64e7def4dca793a7e85ccce/geonode/api_spade/management/commands/reassign_permissions.py

The migration seems to be working properly on my side, except for thumbnails... I can bring some additionnal docs on *.sh files if you are interrested.

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi I have the case where the json string from geonode 3.2 mapstore_adapter is migrated as string in the resourcebase blob field (masked quotes). And hence cards to not work. Did you ever run into this?

Just as info, the discussion continues here -> https://github.com/GeoNode/geonode-mapstore-client/issues/1148
