### ISSUE TITLE
Favorite tab shows `Add to Favorites` even when geoapp is already in favorites

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9269]
## Expected Behavior
After adding a geoapp to favorites, user should see `Delete from favorites` button in the favorite tab

## Actual Behavior

Favorite tab shows `Add to Favorites` button even when geoapp is already in favorites

## Steps to Reproduce the Problem

  1. Login to https://development.demo.geonode.org
  2. Select a geoapp and go to Favorite tab
  3. Add resource to Favorite
  4. Refresh the page, and notice that `Add to Favorites` button is still shown on the page

## Specifications

  - GeoNode version: 3.3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal fix deployed to dev server. You can test it

**Comment by marthamareal** [comment]
Issue is fixed.
