### ISSUE TITLE
Owner is unable to delete a published/approved map and `Request Change` button is shown on map with a user having permissions to edit in A/W

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9283]
## Expected Behavior
- The `Request Change` button should only be shown if the user(owner) has no permission to edit a map. (map is approved/published)
- The owner should be able to see the Editing Tools button with a delete option

## Actual Behavior
The `Request Change` button is shown on a map for the owner when its not approved/published.
The `Editing Tools` on a map button is hidden if the resource is approved/published, hence owner is unable to edit.
## Steps to Reproduce the Problem

  1.Enable advanced workflow
  2. Create a map and assign a group to it
  3. Notice that both `Request changes` and Editing Tolls` with all editing options is visble
  4. Login as admin and approve the map
  5. Login as the owner, Notice Editing Tools button is unavailable hence can't delete the map

## Specifications

  - GeoNode version: 3.3.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal fix deployed to dev demo. Please test it.

**Comment by marthamareal** [comment]
Since the issue happens when A/W is enabled and its not configured on dev demo, I tested this locally on geonode 3.3.x and mapstore-client 3.3.x and tests are passing.
