### ISSUE TITLE
Error on Searching uploads in Admin Site

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9314]
## Expected Behavior
Users should be able to search uploads

## Actual Behavior
Searching uploads in the Admin site throws the error above.
![ss](https://user-images.githubusercontent.com/20810749/167615894-af6f93b0-ee9a-410e-a57b-a6e6e5292477.png)

## Steps to Reproduce the Problem

  1. Login into the Admin site
  2. Type in the search box
  3. Error will be returned

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by jkariukidev** [comment]
This is what I get when try searching in the admin uploads search. 
Installation method: Docker
Platform: Ubuntu20.04

Search text
![image](https://user-images.githubusercontent.com/23359514/168035953-c1c6ed1b-0b24-42db-bb35-b0a9b4f1d71e.png)
Result
![image](https://user-images.githubusercontent.com/23359514/168035319-29c5ba1f-e83a-4eb4-9bf2-595f06fdbb53.png)

**Comment by giohappy** [comment]
@jkariukidev probably you have `DEBUG=False`
