### ISSUE TITLE
After installing Via Docker, Geoserver routes to HTTP after signin. 

### ISSUE THREAD

**Issue by bcarty** [GeoNode/geonode#9326]
## Expected Behavior
The install appears to be working properly but when I login into geoserver it returns a 444 and closed connection in the browser.  The protocol switches from https to http. 

I am not sure if it is a tomcat issue or a nginx issue.  i have checked the configuration files

## Steps to Reproduce the Problem

  1.install via basic install on ubuntu 20.04
  2.change .env to domain using https in url
  3. go to https://www.domain.com/geoserver

**Comment by giohappy** [comment]
Did you configure all the env variables for the public URLs with the https domain? Including `HTTP_HOST` (should be empty) and `HTTPS_HOST`?

I suggest to use the new `create-env.py` script (see the README) which simplifies the creation of the envfile.

**Comment by bcarty** [comment]
Thank you for your quick response. 

I  had an instance of geonode running for a class I was teaching.  I cleared the server to do a fresh install and I am using the .env that I had used with the previous instance which worked smoothly.  

everything else seems to work with this install except I can not upload files and I can not login into the geoserver without it re-routing to http and giving an error.  If i append https to the failed Http request I can see a logged in page of the geoserver admin but if i click on the options with in geoserver it redirects to http again. 

I will do a fresh install again and try the create-env.py

**Comment by Inogeo** [comment]
I noticed that even if HTTPs is properly configured, the geoserver form still class an unsecured HTTP route at form submission.

![httproute](https://user-images.githubusercontent.com/16825471/171360721-aff6d005-bed9-4d8f-b655-7cf24e89eb31.jpg)

**Comment by Inogeo** [comment]
One more information, if I send manually a login request to **https**://%DOMAIN_NAME%/geoserver/j_spring_security_check I have a [HTTP 302](https://developer.mozilla.org/fr/docs/Web/HTTP/Status/302) response with "location" header value equals to **http**://%DOMAIN_NAME%/geoserver/j_spring_security_check

**Comment by Inogeo** [comment]
Actually, following documentation sovled the problem for me. @bcarty you can refer to the following chapter: [Install and enable https secured connection through the let's encrypt provider](https://docs.geonode.org/en/master/install/advanced/core/index.html#install-and-enable-https-secured-connection-through-the-let-s-encrypt-provider)

**Comment by gotjoshua** [comment]
> following documentation sovled the problem for me.

well, i didn't find the documentation crystal clear here @Inogeo but i did manage to get the redirect working after reading some code and inferring some stuff.

in the end it was simply to change one env setting
```sh
PUBLIC_PORT=443
```
