### ISSUE TITLE
django.db.utils.DatabaseError: ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by sairamMuddana** [GeoNode/geonode#9367]
# GNIP <num> - <title of the GNIP here>

## Overview

Describe briefly and clearly what this proposal is meant for.

### Proposed By

<user and full name of the proponent>

### Assigned to Release

This proposal is for GeoNode <version>.

### State

* [x] Under Discussion
* [ ] In Progress
* [ ] Completed
* [ ] Rejected
* [ ] Deferred

### Motivation

Details about the motivations. Why people should accept this proposal. What are the benefits compared to the current situation.

## Proposal

Technical details for developers.

### Backwards Compatibility

Declare its Backwards Compatibility.

## Future evolution

Explain which could be future evolutions.

## Feedback

Update this section with relevant feedbacks, if any.

## Voting

Project Steering Committee:

* Alessio Fabiani:
* Francesco Bartoli:
* Giovanni Allegri:
* Simone Dalmasso:
* Toni Schoenbuchner:
* Florian Hoedt:

## Links

Remove unused links below.

* [Email Discussion]()
* [Pull Request]()
* [Mail Discussion]()
* [Linked Issue]()

**Comment by gannebamm** [comment]
This is not a GNIP. Please use the **Report a bug** template and properly describe your environment. It seems like you use oracle as a database which is currently not supported.
