### ISSUE TITLE
Unable to upload data to geonode

### ISSUE THREAD

**Issue by KoriPatience** [GeoNode/geonode#9382]
## Expected Behavior
After uploading the shapefile i will be able to view it and add styling and metadata

## Actual Behavior
I am not able to upload the shapefile in geonode. The following error appears: 

Unexpected error!-Unknown error code.Contact the system administrator for more information regarding this error message. Additional info: [Client Error: Bad Request Unexpected Exception HTTP ConnectionPool (host='geoserver', port = 8080): Max retries exceeded with url:/geoserver/rest/workspaces.xml (Caused by NewConnectionError (': Failed to establish a new connection: [Errno 111] Connection refused'))]

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 3.2.4
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform: ssh

  - Additional details:

**Comment by KoriPatience** [comment]
![Screenshot (85)](https://user-images.githubusercontent.com/97432635/169327130-f96769fc-ac97-4295-9c0d-f164d02d4c1a.png)

**Comment by KoriPatience** [comment]
> ![Screenshot (85)](https://user-images.githubusercontent.com/97432635/169327130-f96769fc-ac97-4295-9c0d-f164d02d4c1a.png)

This is the error that i get

**Comment by geogeek11** [comment]
I have encountered the same issue while uploading geojson file.

**Comment by categulario** [comment]
I suspect I'm experiencing the same issue. If I try to curl the URL that fails (according to the logs) from the container (using `podman exec -it ...` I can get the info without problems. It doesn't make sense for me that it times out.

In the browser I noticed that I can see my uploaded layers in geoserver without problems, however if I try to visit the `layer preview` list it times out (or perhaps it creates a redirection loop). So I'm suspecting it is actually a problem of how the authentication between geonode and geoserver works (or doesn't)

**Comment by categulario** [comment]
@geogeek11 can you access your geoserver? have you been able to access using the star button next to the login form (oauth)?

**Comment by mattiagiupponi** [comment]
Closing this since Geonode 3.3 is no longer mantained and the import flow in the >=4.1.x is changed
