### ISSUE TITLE
Downloading geoserver.war with "paver setup" is slow

### ISSUE THREAD

**Issue by vdeparday** [GeoNode/geonode#940]
The artifact is currently downloaded from http://build.geonode.org/geoserver/latest/geoserver.war
As discussed on IRC, the job should push the artifact geoserver.war to S3 or something faster as more people will be using it with the 2.0 release.

**Comment by state-hiu** [comment]
See https://github.com/GeoNode/geonode/pull/1978.  You can now specify a custom url for the geoserver.war, including local with `file:///.../.../geoserver.war`.  Still think the long-term goal should be to move copies of deps to geonode.org as much as possible.

**Comment by simod** [comment]
+1
