### ISSUE TITLE
README.md docs links broken

### ISSUE THREAD

**Issue by GuidoS** [GeoNode/geonode#9401]
## Expected Behavior

Expect to click on link and go to that link.

## Actual Behavior

Click on link and then it goes to a 404 page

## Steps to Reproduce the Problem

  1. Click on any link that uses docs.geonode.org/en/ (e.g. User Workshop)
  2.
  3.

## Specifications

  - GeoNode version:
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:  
  
It seams that the readme document has old 3.x links and should now point to master. This change seems to have taken place in the index.html and CHANGELOG, but not in the readme. Doing a simple find of  **"https://docs.geonode.org/en/3.x"** and replace of **"https://docs.geonode.org/en/master"** should solve this.

I did not submit a pull request because I do not have  eula set up and I don't know if i will ever contribute anything else at this point.

Thank you for your assist in fixing this.

**Comment by t-book** [comment]
fixed, thank you @GuidoS
