### ISSUE TITLE
Fix port of PRINT_BASE_URL inside the .env file

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#9456]
@marthamareal you fixed the port for the other env files but not for [.env.](https://github.com/GeoNode/geonode/blob/master/.env#L103).

.env files to be fixes on `master`, `4.x` and `3.3.x`, and `geonode-project 3.3.x`

**Comment by marthamareal** [comment]
@giohappy In the PR the .env file is included [here](https://github.com/GeoNode/geonode/pull/9425/files#diff-e9cbb0224c4a3d23a6019ba557e0cd568c1ad5e1582ff1e335fb7d99b7a1055d) and its ported to 4.x and 3.3.x.
