### ISSUE TITLE
Documents, Maps and GeoApps permissions are not persisted on GeoNode

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9498]
## Expected Behavior
By assiging permissions to other users/group to Documents, Maps or GeoApps, I expect those permissions are correctly persisted.

## Actual Behavior
It looks like the permissions are not persisted and GeoNode always returns empty permissions.

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - GeoNode version: 3.3.2
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@afabiani, From testing with Maps, permissions are persisted in the system, however, it's the permissions api that returns empty permissions.

**Comment by marthamareal** [comment]
Tests are working on stable.demo
