### ISSUE TITLE
400 error on some APIs when a Bearer token is used

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9623]
## Expected Behavior

Users should be able to access all APIs with any form of authentication.

## Actual Behavior
When a user provides a bearer token on the following APIs, 400 status code is returned.
- [resource_service_permissions](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L509)
- [resource_service_ingest](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L697)
- [resource_service_create](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L794)
- [resource_service_update](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L969)
- [resource_service_copy](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L1083)

**NOTE:** Also lookout for functions that accesses data as `request.body`
Example logs show this error raised

![l](https://user-images.githubusercontent.com/20810749/177996292-5f774d97-cb73-429c-9dc0-791968a6d3d5.png)

**NOTE**: API work with basic auth.
## Steps to Reproduce the Problem

  1. Make a request to permissions API eg `PATCH https://master.demo.geonode.org/api/v2/resources/1804/permissions` providing the bearer token in auth.
  2. Notice that 400 will be raised.
  
## Specifications

  - GeoNode version: master 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi maybe the auth middleware is consuming the data?

I don't think so otherwise all the requests should suffer from this issue, plus the `LoginFromApiKeyMiddleware` by default is turned off 
https://github.com/GeoNode/geonode/blob/f794285b042fa109849e175ca2a069e81b5885fe/geonode/settings.py#L1845-L1848

I can take care of the issue and give a check
