### ISSUE TITLE
Make PUT for permissions accept a raw JSON body instead of urlencoded form

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#9624]
The PUT method for [resource_service_permissions](https://github.com/GeoNode/geonode/blob/f794285b042fa109849e175ca2a069e81b5885fe/geonode/base/api/views.py#L509) currently requires an `x-www-form-urlencoded` body, with the perm spec encoded and assigned to the `permissions` key.

This was inherited from previous versions of the client, but now we want to harmonize the API making them work with raw `JSON` body.

The required changes are:

 - [x] #9625
 - [ ] https://github.com/GeoNode/geonode-mapstore-client/issues/1084

**Comment by mattiagiupponi** [comment]
@giohappy the PR is ready here: https://github.com/GeoNode/geonode/pull/9639
The permissions endpoint now uses the JSON body to update the permissions

I'll keep it in "draft" until the client part is ready, otherwise we will have an inconsistency between BE and FE
