### ISSUE TITLE
Avoid Whitenoise compression if not explicitly needed

### ISSUE THREAD

**Issue by afabiani** [GeoNode/geonode#9652]
[Whitenoise](http://whitenoise.evans.io/) is a powerful middleware allowing Django to serve its own static files, making it a self-contained unit that can be deployed anywhere without relying on nginx, Amazon S3 or any other external service. (Especially useful on Heroku, OpenShift and other PaaS providers.)

The [current settings](https://github.com/GeoNode/geonode/blob/master/geonode/settings.py#L312) enable by default the `whitenoise.storage.CompressedStaticFilesStorage`, which is really not needed on a development/default environment, and slows down a lot the deployment/publishing process.

The proposal is to enable the `whitenoise.storage.CompressedStaticFilesStorage` only if explicitly driven by the user through the `.env`, and keep using the `whitenoise.storage.StaticFilesStorage` one instead.

**Comment by giohappy** [comment]
I agree to make it an opt-in, if we consider that Nginx is employed for the usual deployment and it's already configured to perform gzip compression.

We might consider to install and configure Brotli for Ngnix. The [module](https://github.com/google/ngx_brotli) is provided by Google and several images already exist (e.g. [this one](https://hub.docker.com/r/macbre/nginx-brotli) )to take inspiration for its setup.
