### ISSUE TITLE
Trying to update permissions on a dataset raises AttributeError

### ISSUE THREAD

**Issue by StevenGrether** [GeoNode/geonode#9664]
## Expected Behavior
Permissions should be updated successfully.

## Actual Behavior

Following log can be found inside the /var/log/geonode.log of the django container when trying to update permissions of any layer or map.
```
This QueryDict instance is immutable
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/geonode/base/api/views.py", line 585, in resource_service_permissions
    perms_spec_compact = PermSpecCompact(request.data, resource)
  File "/usr/local/lib/python3.10/site-packages/geonode/security/permissions.py", line 371, in __init__
    self._bind_json(json)
  File "/usr/local/lib/python3.10/site-packages/geonode/security/permissions.py", line 379, in _bind_json
    val = json.pop(binding.name, None)
  File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 552, in pop
    self._assert_mutable()
  File "/usr/local/lib/python3.10/site-packages/django/http/request.py", line 510, in _assert_mutable
    raise AttributeError("This QueryDict instance is immutable")
AttributeError: This QueryDict instance is immutable
```

## Steps to Reproduce the Problem

  1. Add any dataset
  2. Try to update permissions

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): GeoNode Docker (GeoNode-Project)
  - Platform: Ubuntu 20.04
  - Additional details:
I have configured ldap to sync users and groups

**Comment by afabiani** [comment]
@StevenGrether I guess this should be fixed already. Can you try to update both GeoNode and MapStore client?

**Comment by StevenGrether** [comment]
@afabiani I have completely reset and reinstalled the containers using the docker-prune and docker-build shell scripts. Unfortunately no success. I also deleted the two requirements in the django4geonode container and reinstalled them using pip install git+https://github.com/GeoNode/geonode.git@4.x#egg=GeoNode git+https://github.com/GeoNode/geonode-mapstore-client.git@4.x#egg=django_geonode_mapstore_client and then restarted the container using docker container start/stop. Unfortunately i get the same error log afterwards.
Is this the right way or is there another way to update the modules that I should try?

**Comment by afabiani** [comment]
That something related to [this](https://github.com/GeoNode/geonode/pull/9626) PR probably.

@mattiagiupponi can you please have a look at this?

**Comment by giohappy** [comment]
I've tested in the past few days, both from curl and online on development and master demo (both contain the commits from the PR), and it works fine.

By the way [this is probably](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L1366) wrong @mattiagiupponi.
The downstream methods modify request.data, e.g. [here](https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L379), and this is epxected to throw the exception since a QueryDict is [immutable](https://docs.djangoproject.com/en/3.2/ref/request-response/#querydict-objects). Probably a copy od the dict must be returned instead.

**Comment by mattiagiupponi** [comment]
> By the way [this is probably](https://github.com/GeoNode/geonode/blob/master/geonode/base/api/views.py#L1366) wrong @mattiagiupponi. The downstream methods modify request.data, e.g. [here](https://github.com/GeoNode/geonode/blob/master/geonode/security/permissions.py#L379), 

That piece of the code is the previous one, is placed there to keep the compatibility with the other endpoints since was not migrated yet.

> and this is expected to throw the exception since a QueryDict is [immutable](https://docs.djangoproject.com/en/3.2/ref/request-response/#querydict-objects). Probably a copy od the dict must be returned instead.
This might not be true since the Querydict created use `mutable=True` so the QueryDict, in this case, should be mutable

I'll try again the whole flow to be sure that nothing is broken

**Comment by afabiani** [comment]
@mattiagiupponi @StevenGrether is that possible that the 4.x branch is not using the correct mapstre-client branch either?
Notice that the 4.x branch specifies a fixed version of the dependency in the [requirements](https://github.com/GeoNode/geonode/blob/4.x/requirements.txt#L87).

**Comment by mattiagiupponi** [comment]
> @mattiagiupponi @StevenGrether is that possible that the 4.x branch is not using the correct mapstre-client branch either? Notice that the 4.x branch specifies a fixed version of the dependency in the [requirements](https://github.com/GeoNode/geonode/blob/4.x/requirements.txt#L87).

I'm building it on my local, btw that may be the problem @afabiani

**Comment by afabiani** [comment]
@giohappy probably using a geonode-project you are parsing the most updated mapstore-client branch (4.x), but if you try to use the geonode branch you will stick to the rc version

**Comment by giohappy** [comment]
@StevenGrether please try now and close this if it works.

**Comment by StevenGrether** [comment]
Works after rebuilding the containers. Thanks for the effort!
