### ISSUE TITLE
Registered members with edit/manage permission can not edit Resource

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode#9795]
@ElenaGallo commented on [Thu Jul 28 2022](https://github.com/GeoNode/geonode-mapstore-client/issues/1121)

Registered members with edit/manage permission can not edit/manage Resource

**How to Reproduce**
- See the steps in the video below:

https://user-images.githubusercontent.com/56537133/181476655-c4fa681c-cb84-45fb-aa4e-90b3a5060c08.mov

**Comment by giohappy** [comment]
@mattiagiupponi I could reproduce this with any layer per "Registered members" have Edit permissions.

**Comment by mattiagiupponi** [comment]
By calling the resource_types endpoint, it looks like the "registered members" group has the "manage" and "edit" permission as compact, but the extednded ones are only:

```
"registered-members": [
                        "delete_resourcebase",
                        "change_resourcebase_permissions",
                        "publish_resourcebase",
                        "change_resourcebase",
                        "change_resourcebase_metadata",
                        "view_resourcebase",
                        "download_resourcebase",
                        "change_dataset_data",
                        "change_dataset_style"
                    ]
```
I'm still checking
