### ISSUE TITLE
Time series search filter is not working

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#9819]
## Expected Behavior
On the master demo, if I filter for "time series" datasets, I'm expecting that only the dataset with time series are shown

## Actual Behavior
The search return "No results" even if a time series dataset is uploaded:
Search: https://master.demo.geonode.org/catalogue/#/search/filter/?f=store-time-series
Dataset with time series: https://master.demo.geonode.org/catalogue/#/detail/dataset/1972

## Steps to Reproduce the Problem

  1. Go on master Demo
  2. Upload a new dataset with time series
  3. filter for time series datasets
  4. The search returns 0 results

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): all
  - Platform: all
  - Additional details: None

**Comment by mattiagiupponi** [comment]
This PR https://github.com/GeoNode/geonode/pull/9840 will fix also the `subtype` value to let the filter works as expected

**Comment by giohappy** [comment]
@marthamareal test this and add a test to Cucumber.

**Comment by marthamareal** [comment]
The filtering works fine.
1. When you upload a time dataset, with time configured, it appears in the filter search
2. When you upload without configuring time, it does not appear in the search
3. When you update and configure time on the non-time dataset, it appears in the search
