### ISSUE TITLE
Geonode Download filtered dataset, where filter is based on another layer

### ISSUE THREAD

**Issue by nagyrobir** [GeoNode/geonode#9856]
## Expected Behavior
I have a point layer uploaded in Geonode, via the QGIS geonode plugin. I can view the dataset, everything works as expected.
I have a polygon layer created through geonode with one polygon. Works as expected.
When i try to filter the point layer by the polygon layer, the filtering works as expected.
When i try to download the filtered dataset, i would expect to be able to download it, the same way as when i hand draw the polygon filter without using the polygon layer.

## Actual Behavior
When i try to download the filtered dataset then i get the error message from the image attached.
If i filter the point layer by a polygon that i hand draw, to be explicit, without the use of the polygon layer that i created manually,then i can export the filtered dataset without any problem

![download_failed](https://user-images.githubusercontent.com/46939331/184875959-39720ddb-4230-4952-81ae-11a0dd1952df.png)

Download all the points from the points layer, which intersect the polygon that i am drawing myself during the filtering -> Works!
Download all the points from the points layer, which intersect the polygon that is in the polygon layer - > Does not work.

## Steps to Reproduce the Problem

  1.Get a point layer
  2.Get a polygon layer
  3.Intersect the point layer by the polygon layer
  4. Try to download the filtered dataset. 

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker): Geonode Docker
  - Platform:Linux
  - Additional details:

**Comment by marthamareal** [comment]
This error is similar to the one raised when you try to export a map layer with the `Layer filter` option enabled.
**Steps to reproduce**:
- Open a map with a dataset
- Select a layer and apply filters and save
![b](https://user-images.githubusercontent.com/20810749/188442745-efe3da8a-7ad4-4044-a4c0-9602e3ee525d.png)
- Export the layer with both options enabled, and the error will be raised
![b2](https://user-images.githubusercontent.com/20810749/188442786-139b3d39-cefa-405f-84c8-f0215d0def24.png)

![b3](https://user-images.githubusercontent.com/20810749/188443210-2768aa12-42df-460b-b0b1-edf0a1b2166f.png)

**NOTE: Export works fine if `Layer filter ` is not enabled**

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #1192](https://github.com/GeoNode/geonode-mapstore-client/issues/1192) via [**Zenhub**](https://www.zenhub.com/)
