### ISSUE TITLE
AttributeError on viewing recent activities

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9881]
## Expected Behavior
User should be able to view the recent activities page

## Actual Behavior
![aa](https://user-images.githubusercontent.com/20810749/186374194-ddebc437-b6ca-4a87-8286-c405beda8fc3.png)

## Steps to Reproduce the Problem

  1. Login, on [development.demo.org](https://development.demo.geonode.org/)
  2. Click on the profile icon on the right and select `Recent activity`
  3. The error above is raised

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@giohappy This error is because in the previous data on development from (3.3.x), we have actions about comments. however, the `dialogos` app is not included in the settings on 4.x hence Comment model is not defined. The activity page includes comments and the above error is raised trying to retrieve their info.

**Comment by giohappy** [comment]
That's odd. I testes it and it worked fine...
In that case we need to remove any additional reference to comments @marthamareal
