### ISSUE TITLE
User endpoint return 404 if user is not in registered members

### ISSUE THREAD

**Issue by mattiagiupponi** [GeoNode/geonode#9919]
## Expected Behavior
even if the user is not in the registered member's group, the user API should return the user information

## Actual Behavior
If a user is not in the registered member's group, the API return 404 with "detail not found"
```
GET /api/v2/users/1001
HTTP 404 Not Found
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "detail": "Not found."
}
```
Probably a regression of this: https://github.com/GeoNode/geonode/issues/9381
## Steps to Reproduce the Problem

  1. create a user that doesn't belong to the "registered members" group
  2. check the http://localhost:8000/api/v2/users/{user_id} API
  3.

## Specifications

  - GeoNode version: master, 4x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by marthamareal** [comment]
@giohappy What do yo think about. 
1. add a variable that can control user listing for default groups (anonymous and contributors, and registered members). by default we can have it = True and for custom projects that would prefer controlling user listing not considering default groups, they can set it to False
2. creating GroupProfiles for the available default groups(registered_members, anonymous, and contributors).
Currently they don't have a relation to Group profile that is why the user is not included [here](https://github.com/GeoNode/geonode/blob/master/geonode/people/utils.py#L125) hence 404

**Comment by giohappy** [comment]
@marthamareal the point of this issue is not the visibility of users, but the ability for the current user to see its own details.
The problem now is that, apparently, the user detail endpoint forbids requests if the requesting user is not inside the `registered_members` group.
