### ISSUE TITLE
Unable to upload CSV dataset

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9946]
## Expected Behavior

User should be able to upload datasets using CSV file.

## Actual Behavior
- On upload, When choosing the longtude and latitude fields, the form accepts one field to be none, then after choosing the SRS, the page gets stuck on `Next`. then the upload is marked as failed on the upload list.
- Sometimes when correct selections are made, a user is directed to a page with json response instead of the dataset view.
![ss](https://user-images.githubusercontent.com/20810749/187876791-ce60635e-fb54-459b-9437-5b318df21a3b.png)

## Steps to Reproduce the Problem

  1. Login and try uploading file [result (2).csv](https://github.com/GeoNode/geonode/files/9468481/result.2.csv)
  2. follow steps described in actual behavior
  3.

## Specifications

  - GeoNode version: 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
@marthamareal I don't see any lat/lon filed in the example csv file that you have attached to the issue.

**Comment by giohappy** [comment]
@marthamareal[ this is the same file](https://github.com/GeoNode/geonode/files/9548905/points_coords.zip) with some random coords (lat/lon) fields, and it loads correctly.

**Comment by giohappy** [comment]
It was confirmed that the test CSV wasn't a valid point csv.
