### ISSUE TITLE
Some filters for Area of Interest not working

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9953]
## Expected Behavior
All filters should display correct results when applied

## Actual Behavior
Some filters are not working eg
![b2](https://user-images.githubusercontent.com/20810749/188435224-ea894bb5-8028-4d33-945f-346ad07f7b84.png)

![b3](https://user-images.githubusercontent.com/20810749/188435231-12cfd399-845b-4323-b0d2-f773020d98da.png)

## Steps to Reproduce the Problem

  1. View a dataset with some data features eg https://master.demo.geonode.org/catalogue/#/dataset/2467
  2. Click on Filter from the menu, select the filter type as `Polygon` and `Geometry` as `Contains` or `Is contained`
  3. Draw a polygon containing some of the features. 
  4. Notice that all features will disappear

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #1194](https://github.com/GeoNode/geonode-mapstore-client/issues/1194) via [**Zenhub**](https://www.zenhub.com/)
