### ISSUE TITLE
GIF(popup of a feature) are not shown on map content in Geostories (both data and annotations)

### ISSUE THREAD

**Issue by marthamareal** [GeoNode/geonode#9971]
## Expected Behavior
Apop up with info is expected when you click on a feature in the map content

## Actual Behavior
GIF(popup of a feature) are not shown on map content in Geostories (both data and annotations)

## Steps to Reproduce the Problem

  1. Create a geostory
  2. Add a map (also try with annotations) and save
  3. Click on the features on the map
  4. Notice no popup is shown

## Specifications

  - GeoNode version: master, 4.x
  - Installation method (manual, GeoNode Docker, SPCGeoNode Docker):
  - Platform:
  - Additional details:

**Comment by giohappy** [comment]
The error I see in console looks somehow related:

![image](https://user-images.githubusercontent.com/571129/189682311-54e03199-7f7b-436c-8cdb-711ee7cea0ff.png)

**Comment by giohappy** [comment]
Issue moved to [GeoNode/geonode-mapstore-client #1193](https://github.com/GeoNode/geonode-mapstore-client/issues/1193) via [**Zenhub**](https://www.zenhub.com/)
