### ISSUE TITLE
uwsgi service doesn't restart

### ISSUE THREAD

**Issue by sknera** [GeoNode/geonode#9989]
Hi, I'm trying to install GeoNode 4.0 from this documentation:  https://docs.geonode.org/en/master/install/advanced/core/index.html

However, when trying to:
```console
systemctl restart uwsgi.service
```
I've got:
``` Job for uwsgi.service failed because the control process exited with error code.
See "systemctl status uwsgi.service" and "journalctl -xeu uwsgi.service" for details. 
```

So, after checking logs:
```console
sudo tail -F -n 300 /opt/data/geoserver_logs/geoserver.log
```

Fri Sep  9 11:09:59 2022 - *** Starting uWSGI 2.0.20-debian (64bit) on [Fri Sep  9 11:09:59 2022] ***
Fri Sep  9 11:09:59 2022 - compiled with version: 11.2.0 on 21 March 2022 11:00:44
Fri Sep  9 11:09:59 2022 - os: Linux-5.15.0-47-generic #51-Ubuntu SMP Thu Aug 11 07:51:15 UTC 2022
Fri Sep  9 11:09:59 2022 - nodename: xero-VirtualBox
Fri Sep  9 11:09:59 2022 - machine: x86_64
Fri Sep  9 11:09:59 2022 - clock source: unix
Fri Sep  9 11:09:59 2022 - pcre jit disabled
Fri Sep  9 11:09:59 2022 - detected number of CPU cores: 1
Fri Sep  9 11:09:59 2022 - current working directory: /
Fri Sep  9 11:09:59 2022 - writing pidfile to /run/uwsgi/app/geonode/pid
Fri Sep  9 11:09:59 2022 - detected binary path: /usr/bin/uwsgi-core
Fri Sep  9 11:09:59 2022 - chdir() to /opt/geonode
Fri Sep  9 11:09:59 2022 - your processes number limit is 47605
Fri Sep  9 11:09:59 2022 - your memory page size is 4096 bytes
Fri Sep  9 11:09:59 2022 -  *** WARNING: you have enabled harakiri without post buffering. Slow upload could be rejected on post-unbuffered webservers *** 
Fri Sep  9 11:09:59 2022 - detected max file descriptor number: 1024
Fri Sep  9 11:09:59 2022 - lock engine: pthread robust mutexes
Fri Sep  9 11:09:59 2022 - thunder lock: disabled (you can enable it with --thunder-lock)
Fri Sep  9 11:09:59 2022 - uwsgi socket 0 bound to UNIX address /run/uwsgi/app/geonode/socket fd 3
Fri Sep  9 11:09:59 2022 - uwsgi socket 1 bound to TCP address 0.0.0.0:8000 fd 5
Fri Sep  9 11:09:59 2022 - setgid() to 33
Fri Sep  9 11:09:59 2022 - setuid() to 33
Fri Sep  9 11:09:59 2022 - Python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
Fri Sep  9 11:09:59 2022 - !!! Python Home is not a directory: /home/xero/.virtualenvs/geonode !!!
Fri Sep  9 11:09:59 2022 - Set PythonHome to /home/xero/.virtualenvs/geonode
Python path configuration:
  PYTHONHOME = '/home/xero/.virtualenvs/geonode'
  PYTHONPATH = (not set)
  program name = '/home/xero/.virtualenvs/geonode/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/xero/.virtualenvs/geonode/bin/python'
  sys.base_prefix = '/home/xero/.virtualenvs/geonode'
  sys.base_exec_prefix = '/home/xero/.virtualenvs/geonode'
  sys.platlibdir = 'lib'
  sys.executable = '/home/xero/.virtualenvs/geonode/bin/python'
  sys.prefix = '/home/xero/.virtualenvs/geonode'
  sys.exec_prefix = '/home/xero/.virtualenvs/geonode'
  sys.path = [
    '/home/xero/.virtualenvs/geonode/lib/python310.zip',
    '/home/xero/.virtualenvs/geonode/lib/python3.10',
    '/home/xero/.virtualenvs/geonode/lib/python3.10/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f46adccebc0 (most recent call first):
  <no Python frame>

### In my  config file for uwsgi:
```console
sudo vim /etc/uwsgi/apps-available/geonode.ini
```
```
[uwsgi]
uwsgi-socket = 0.0.0.0:8000
# http-socket = 0.0.0.0:8000

gid = www-data

plugins = python3
virtualenv  = /home/xero/.virtualenvs/geonode

env = DJANGO_SETTINGS_MODULE=geonode.settings
env = GEONODE_INSTANCE_NAME=geonode
env = GEONODE_LB_HOST_IP=
env = GEONODE_LB_PORT=
```

Where "xero" is my username.

I have also checked if my geonode virtualenv is in this directory, and it's seems so:

> (geonode) xero@xero-VirtualBox:~$ which python

/home/xero/.virtualenvs/geonode/bin/python

> (geonode) xero@xero-VirtualBox:~$ echo $VIRTUAL_ENV

/home/xero/.virtualenvs/geonode

**Comment by SteveFirsake** [comment]
I got the same challenge while installing version 4.x.

**Comment by abdoulaye2019** [comment]
Hi! I solved this error by deleting the **/var/log/uwsgi/app/geonode.log**  you can use **sudo rm -rf /var/log/uwsgi/app/geonode.log**  and after restarting all services. If you want to see geonode.log processes use **sudo tail -F -n 300 /opt/data/logs/geonode.log**

**Comment by giohappy** [comment]
That's unlikely that the presence of the log file was the real problem.
Anyway good to know that you solved it! I'm going to close this issue.
