### ISSUE TITLE
Docker Install static file unique path

### ISSUE THREAD

**Issue by eiacopini** [GeoNode/geonode#9996]
Hi I have installed geonode via docker (fresh installation on ubuntu 20.4) but the homepage remains loading. In docker-compose logs -f django I have this error

![unique_path](https://user-images.githubusercontent.com/107869133/189536948-89a8067e-5400-4032-b193-83f91a3df7fc.jpg)

![loading](https://user-images.githubusercontent.com/107869133/189537634-c3cb1f14-0870-4f0a-9eda-ac3bcf1528e6.jpg)

in the .env file i used this settings
STATIC_ROOT = / mnt / volumes / statics / static /
MEDIA_ROOT = / mnt / volumes / statics / uploaded /
GEOIP_PATH = / mnt / volumes / statics / geoip.db

**Comment by t-book** [comment]
Hi, can you confirm that you're using https://github.com/GeoNode/geonode/releases/tag/4.0.0post1 release?

**Comment by eiacopini** [comment]
Hi my import OS in __init__.py
is version (4,0,0,'final',0)
I had followed this guide
https://docs.geonode.org/en/master/install/basic/index.html

git clone https://github.com/GeoNode/geonode-project.git -b 4.x

**Comment by t-book** [comment]
So there was a bug preventing the splash page to load. With the post release this should be fixed ;)

**Comment by eiacopini** [comment]
Hi Toni now it's work fine, but i have a problem when i try to log inside geoserver because redirect to http://localhost/geoserver/web/j_spring_oauth2_geonode_login instead http://domain.cloud/geoserver/web/j_spring_oauth2_geonode_login

in the .env file i used this settings

GEOSERVER_WEB_UI_LOCATION=http://geonode.arkeo-server.cloud/geoserver/
GEOSERVER_PUBLIC_LOCATION=http://geonode.arkeo-server.cloud/geoserver/
GEOSERVER_LOCATION=http://geoserver:8080/geoserver/
GEOSERVER_ADMIN_USER=admin
GEOSERVER_ADMIN_PASSWORD=geoserver

**Comment by t-book** [comment]
You're welcome.
